#ifndef OS4x00_HH
#define OS4x00_HH

/*
#define	OS_FD_Init									NU_FD_Init
#define	OS_FD_Set									NU_FD_Set
#define	OS_Write									NU_Write
#define	OS_Timer_Pointers                           NU_Timer_Pointers
#define	OS_Timer_Information                        NU_Timer_Information
#define	OS_Terminate_Task                           NU_Terminate_Task
#define	OS_Terminate_All                            NU_Terminate_All
#define	OS_Tell                                     NU_Tell
#define	OS_Task_Pointers                            NU_Task_Pointers
#define	OS_Task_Information                         NU_Task_Information
#define	OS_Suspend_Task                             NU_Suspend_Task
#define	OS_Socket                                   NU_Socket
#define	OS_Sleep                                    NU_Sleep
#define	OS_Setsockopt                               NU_Setsockopt
#define	OS_Set_Events                               NU_Set_Events
#define	OS_Set_Default_Drive                        NU_Set_Default_Drive
#define	OS_Set_Current_Dir                          NU_Set_Current_Dir
#define	OS_Set_Clock                                NU_Set_Clock
#define	OS_Send_To_Queue                            NU_Send_To_Queue
#define	OS_Send_To_Mailbox                          NU_Send_To_Mailbox
#define	OS_Send_To_Front_Of_Queue                   NU_Send_To_Front_Of_Queue
#define	OS_Send_To                                  NU_Send_To
#define	OS_Send                                     NU_Send
#define	OS_Semaphore_Pointers                       NU_Semaphore_Pointers
#define	OS_Semaphore_Information                    NU_Semaphore_Information
#define	OS_Select                                   NU_Select
#define	OS_Seek                                     NU_Seek
#define	OS_Retrieve_Events                          NU_Retrieve_Events
#define	OS_Retrieve_Clock                           NU_Retrieve_Clock
#define	OS_Resume_Task                              NU_Resume_Task
#define	OS_Reset_Timer                              NU_Reset_Timer
#define	OS_Reset_Task                               NU_Reset_Task
#define	OS_Reset_Semaphore                          NU_Reset_Semaphore
#define	OS_Reset_Queue                              NU_Reset_Queue
#define	OS_Reset_Mailbox                            NU_Reset_Mailbox
#define	OS_Rename                                   NU_Rename
#define	OS_Remove_Dir                               NU_Remove_Dir
#define	OS_Relinquish                               NU_Relinquish
#define	OS_Release_Semaphore                        NU_Release_Semaphore
#define	OS_Release_File_User                        NU_Release_File_User
#define	OS_Recv_Timed                               NU_Recv_Timed
#define	OS_Recv_From                                NU_Recv_From
#define	OS_Recv                                     NU_Recv
#define	OS_Receive_From_Queue                       NU_Receive_From_Queue
#define	OS_Receive_From_Mailbox                     NU_Receive_From_Mailbox
#define	OS_Read                                     NU_Read
#define	OS_Queue_Pointers                           NU_Queue_Pointers
#define	OS_Queue_Information                        NU_Queue_Information
#define	OS_Ping                                     NU_Ping
#define	OS_Open_Disk                                NU_Open_Disk
#define	OS_Open                                     NU_Open
#define	OS_Obtain_Semaphore                         NU_Obtain_Semaphore
#define	OS_Memory_Pool_Information                  NU_Memory_Pool_Information
#define	OS_Make_Dir                                 NU_Make_Dir
#define	OS_Mailbox_Pointers                         NU_Mailbox_Pointers
#define	OS_Mailbox_Information                      NU_Mailbox_Information
#define	OS_Listen                                   NU_Listen
#define	OS_Is_Connected                             NU_Is_Connected
#define	OS_Getsockopt                               NU_Getsockopt
#define	OS_Get_Peer_Name                            NU_Get_Peer_Name
#define	OS_Get_Next                                 NU_Get_Next
#define	OS_Get_Host_Name                            NU_Get_Host_Name
#define OS_Get_Host_By_Name							NU_Get_Host_By_Name
#define	OS_Get_First                                NU_Get_First
#define	OS_Get_Default_Drive                        NU_Get_Default_Drive
#define	OS_Get_Attributes                           NU_Get_Attributes
#define	OS_FreeSpace                                NU_FreeSpace
#define	OS_Format                                   NU_Format
#define	OS_Flush                                    NU_Flush
#define	OS_Fcntl                                    NU_Fcntl
#define	OS_ENC_Decrypt                              ENC_Decrypt
#define	OS_ENC_Encrypt                              ENC_Encrypt
#define	OS_Event_Group_Pointers                     NU_Event_Group_Pointers
#define	OS_Event_Group_Information                  NU_Event_Group_Information
#define	OS_Established_Timers                       NU_Established_Timers
#define	OS_Established_Tasks                        NU_Established_Tasks
#define	OS_Established_Semaphores                   NU_Established_Semaphores
#define	OS_Established_Queues                       NU_Established_Queues
#define	OS_Established_Memory_Pools                 NU_Established_Memory_Pools
#define	OS_Established_Mailboxes                    NU_Established_Mailboxes
#define	OS_Established_Event_Groups                 NU_Established_Event_Groups
#define	OS_Enable_History_Saving                    NU_Enable_History_Saving
#define	OS_Done                                     NU_Done
#define	OS_Disk_Abort                               NU_Disk_Abort
#define	OS_Disable_History_Saving                   NU_Disable_History_Saving
#define	OS_Delete_Timer                             NU_Delete_Timer
#define	OS_Delete_Task                              NU_Delete_Task
#define	OS_Delete_Semaphore                         NU_Delete_Semaphore
#define	OS_Delete_Queue                             NU_Delete_Queue
#define	OS_Delete_Memory_Pool                       NU_Delete_Memory_Pool
#define	OS_Delete_Mailbox                           NU_Delete_Mailbox
#define	OS_Delete_Event_Group                       NU_Delete_Event_Group
#define	OS_Delete                                   NU_Delete
#define	OS_Deallocate_Memory                        NU_Deallocate_Memory
#define	OS_Current_Task_Pointer                     NU_Current_Task_Pointer
#define	OS_Current_HISR_Pointer                     NU_Current_HISR_Pointer
#define	OS_Current_Dir                              NU_Current_Dir
#define	OS_Create_Timer                             NU_Create_Timer
#define	OS_Create_Task                              NU_Create_Task
#define	OS_Create_Semaphore                         NU_Create_Semaphore
#define	OS_Create_Queue                             NU_Create_Queue
#define	OS_Create_Memory_Pool                       NU_Create_Memory_Pool
#define	OS_Create_Mailbox                           NU_Create_Mailbox
#define	OS_Create_Event_Group                       NU_Create_Event_Group
#define	OS_Control_Timer                            NU_Control_Timer
#define	OS_Control_Interrupts                       NU_Control_Interrupts
#define	OS_Connect                                  NU_Connect
#define	OS_Close_Socket                             NU_Close_Socket
#define	OS_Close_Disk                               NU_Close_Disk
#define	OS_Close                                    NU_Close
#define	OS_Check_Stack                              NU_Check_Stack
#define	OS_Check_File_User                          NU_Check_File_User
#define	OS_Change_Time_Slice                        NU_Change_Time_Slice
#define	OS_Change_Priority                          NU_Change_Priority
#define	OS_Change_Preemption                        NU_Change_Preemption
#define	OS_Broadcast_To_Queue                       NU_Broadcast_To_Queue
#define	OS_Broadcast_To_Mailbox                     NU_Broadcast_To_Mailbox
#define	OS_Bind                                     NU_Bind
#define	OS_Become_File_User                         NU_Become_File_User
#define	OS_Allocate_Memory                          NU_Allocate_Memory
#define	OS_Accept                                   NU_Accept
#define	OS_Abort                                    NU_Abort


#define OS_ValidateAPI												ValidateAPI										
#define	OS__get_str_mem                                            _get_str_mem										
#define	OS_ActivateStatusCode                                      ActivateStatusCode  
#define OS_DisableStatusCode                                       DisableStatusCode
#define	OS_AddLines                                                AddLines                                           
#define	OS_AddMenu                                                 AddMenu                                            
#define	OS_ALARMLOG_make_entry                                     ALARMLOG_make_entry                                
#define	OS_App_Request_Reboot                                      App_Request_Reboot                                 
#define	OS_CALLLOG_make_entry                                      CALLLOG_make_entry                                 
#define	OS_com_printf                                              com_printf                                         
#define	OS_crc32 												   crc32
#define	OS_CreateButtons                                           CReateButtons
#define	OS_CreateMenuGroup                                         CreateMenuGroup                                    
#define	OS_CreateMenus                                             CreateMenus                                        
#define	OS_DEBUGLOG_make_entry                                     DEBUGLOG_make_entry
#define	OS_DoesVariablesExist                                      DoesVariablesExist                                 
#define	OS_EVENTLOG_make_entry                                     EVENTLOG_make_entry                                
#define	OS_GetHoursFromUnitClock                                   GetHoursFromUnitClock                              
#define	OS_GetMailStatus                                           GetMailStatus                                      
#define	OS_GetMillisecondsFromUnitClock                            GetMillisecondsFromUnitClock                       
#define	OS_GetMinutesFromUnitClock                                 GetMinutesFromUnitClock                            
#define	OS_GetSecondsFromUnitClock                                 GetSecondsFromUnitClock                            
#define	OS_GetTimeInMs                                             GetTimeInMs                               			
#define	OS_GetTimeTickStart                                        GetTimeTickStart                                   
#define	OS_GetTimeTickStop                                         GetTimeTickStop                                    
#define	OS_listen_for_tcp                                          listen_for_tcp                                     
#define	OS_listen_for_udp                                          listen_for_udp                                     
#define	OS_module_create_all                                       module_create_all                                  
#define	OS_module_destruct_all                                     module_destruct_all                                
#define	OS_module_destruct_all_v                                   module_destruct_all_v                              
#define	OS_module_HISR_create                                      module_HISR_create                                 
#define	OS_module_HISR_destruct                                    module_HISR_destruct                               
#define	OS_module_queue_create                                     module_queue_create                                
#define	OS_module_queue_destruct                                   module_queue_destruct                              
#define	OS_module_start_all                                        module_start_all                                   
#define	OS_module_stop_all                                         module_stop_all                                    
#define	OS_module_task_create                                      module_task_create                                 
#define	OS_module_task_destruct                                    module_task_destruct                               
#define	OS_ModuleLastRebootCause                                   ModuleLastRebootCause                              
#define	OS_NoOfActiveStatusCodes                                   NoOfActiveStatusCodes                              
#define	OS_ReadVariables                                           ReadVariables                                      
#define	OS_RegisterPasswordVerifier                                RegisterPasswordVerifier                           
#define	OS_RequestComportUsageAPP                                  RequestComportUsageAPP                             
#define	OS_Retrieve_Backup_File_Names                              Retrieve_Backup_File_Names                         
#define	OS_SendMail                                                SendMail                                           
#define	OS_SetResourceFreeAPP                                      SetResourceFreeAPP                                 
#define	OS_SetSafetyChainMode                                      SetSafetyChainMode                                 
#define	OS_SetupComPort                                            SetupComPort                                       
#define	OS_StatusCodeActive                                        StatuscodeActive                                   
#define	OS_StatusCodeActiveErr                                     StatusCodeActiveErr                                
#define	OS_StatusCodeBlockReset                                    StatusCodeBlockReset                               
#define	OS_StatusCodeInit                                          StatusCodeInit                                     
#define	OS_StatusCodeResetAll                                      StatusCodeResetAll                                 
#define	OS_StatusCodeResetAutomatic                                StatusCodeResetAutomatic                           
#define	OS_StatusCodeSetAutomatic                                  StatusCodeSetAutomatic                             
#define	OS_StatusCodeSetReset                                      StatusCodeSetReset                                 
#define	OS_StatusCodeUnblockReset                                  StatusCodeUnblockReset   
#define	OS_STR_CONV                                                STR_CONV                                           
#define	OS_StsDetailMenuLink                                       StsDetailMenuLink                                  
#define	OS_SubHandl_InitSubscriptionBlocks                         SubHandl_InitSubscriptionBlocks                    
#define	OS_SubHandl_Subscribe                                      SubHandl_Subscribe                                 
#define	OS_SubHandl_SubscribeEvent                                 SubHandl_SubscribeEvent                            
#define	OS_SubHandl_SubscribeFunction                              SubHandl_SubscribeFunction                         
#define	OS_SubHandl_SubscribeFunctionWithRef                       SubHandl_SubscribeFunctionWithRef                  
#define	OS_SubHandl_SubscribeMailbox                               SubHandl_SubscribeMailbox                          
#define	OS_SubHandl_SubscribeQueue                                 SubHandl_SubscribeQueue                            
#define	OS_SubHandl_SubscribeSignal                                SubHandl_SubscribeSignal                           
#define	OS_SubHandl_Unsubscribe                                    SubHandl_Unsubscribe                               
#define	OS_SUM_CreateSummations                                    SUM_CreateSummations                               
#define	OS_SYSLOG_make_entry                                       SYSLOG_make_entry                                  
#define	OS_timevar_change_timervariable                            timevar_change_timervariable                       
#define	OS_timevar_create_timervariable                            timevar_create_timervariable                       
#define	OS_TOTLOG_SetTrig                                          TOTLOG_SetTrig                                     
#define	OS_U128_add                                                U128_add                                           
#define	OS_U64_multiply                                            U64_multiply                                       
#define	OS_ValidateUnitClock                                       ValidateUnitClock                                  
#define	OS_VarDB_CreateAliases                                     VarDB_CreateAliases                                
#define	OS_VarDB_CreateBackups                                     VarDB_CreateBackups                                
#define	OS_VarDB_CreateLocals                                      VarDB_CreateLocals                                 
#define	OS_VarDB_CreateOutputParameters                            VarDB_CreateOutputParameters                       
#define	OS_VarDB_CreateParameters                                  VarDB_CreateParameters                             
#define	OS_VarDB_CreateTimers                                      VarDB_CreateTimers                                 
#define	OS_VarDB_GetDisplayScaleTypeValueUnitAndPrecision          VarDB_GetDisplayScaleTypeValueUnitAndPrecision     
#define	OS_VarDB_GetVariableID                                     VarDB_GetVariableID                                
#define	OS_VarDB_GetVariableInfo                                   VarDB_GetVariableInfo                              
#define	OS_VarDB_GetVariableLimits                                 VarDB_GetVariableLimits                            
#define	OS_VarDB_GetVariableType                                   VarDB_GetVariableType                              
#define	OS_VarDB_LockOutputParameter                               VarDB_LockOutputParameter  
#define	OS_VarDB_ObtainNewObjectID                                 VarDB_ObtainNewObjectID                            
#define	OS_VarDB_ParameterRestoreDefault                           VarDB_ParameterRestoreDefault                      
#define	OS_VarDB_ReadVariable                                      VarDB_ReadVariable                                 
#define	OS_VarDB_ReadVariableByName                                VarDB_ReadVariableByName                           
#define	OS_VarDB_SetDisplayScaleTypeValueUnitAndPrecision          VarDB_SetDisplayScaleTypeValueUnitAndPrecision     
#define	OS_vardb_to_object                                         vardb_to_object                                    
#define	OS_VarDB_UpdateLockedOutputParameter                       VarDB_UpdateLockedOutputParameter                  
#define	OS_VarDB_UpdateReady                                       VarDB_UpdateReady
#define	OS_VarDB_UpdateS16                                         VarDB_UpdateS16                                    
#define	OS_VarDB_UpdateS32                                         VarDB_UpdateS32                                    
#define	OS_VarDB_UpdateS64                                         VarDB_UpdateS64                                    
#define	OS_VarDB_UpdateS8                                          VarDB_UpdateS8                                     
#define	OS_VarDB_UpdateString                                      VarDB_UpdateString                                 
#define	OS_VarDB_UpdateU16                                         VarDB_UpdateU16                                    
#define	OS_VarDB_UpdateU32                                         VarDB_UpdateU32                                    
#define	OS_VarDB_UpdateU64                                         VarDB_UpdateU64                                    
#define	OS_VarDB_UpdateU8                                          VarDB_UpdateU8                                     
#define	OS_VarDB_UpdateVariable                                    VarDB_UpdateVariable                               
#define	OS_VarDB_UpdateVariableByName                              VarDB_UpdateVariableByName                         
#define	OS_VarDB_UpdateVariableConditional                         VarDB_UpdateVariableConditional                    
#define	OS_VarDB_UpdateVariableConditionalByName                   VarDB_UpdateVariableConditionalByName
#define	OS_Watchdog_Change_Item                                    Watchdog_Change_Item                               
#define	OS_Watchdog_Create_Item                                    Watchdog_Create_Item                               
#define	OS_Watchdog_Get_Schedule_time                              Watchdog_Get_Schedule_time                         
#define	OS_Watchdog_Hit_Item                                       Watchdog_Hit_Item                                  
#define	OS_Watchdog_SetOptions                                     Watchdog_SetOptions                                
#define	OS_WriteVariables                                          WriteVariables                                     
#define	OS_WriteVariablesConditional                               WriteVariablesConditional                          
#define	OS_StatusCodeUnblockReset                                  StatusCodeUnblockReset								
#define	OS_StatusCodeBlockReset                                    StatusCodeBlockReset								
#define OS_StcodeMainScan                                          StcodeMainScan
*/

//#include "prototypes.h"

#endif
