//*****************************PEPTOOL Header Start******************************
//                                                                               
//                         Copyright © 2018 Mita-Teknik.                         
// This software may only be used with the Controllers delivered by Mita-Teknik  
//                                                                               
//*******************************************************************************
//                                                                               
// $PEPTOOL version:9.0$                                                         
// $PEPTOOL file version:101$                                                    
//                                                                               
//*******************************************************************************
//                                                                               
// $Date: XXXX/XX/XX XX:XX:XX $                                                  
// $Author: DESKTOP-3H3JCEK\jaakl $                                              
// $RCSfile: turbdef.h,v $                                                       
// $Revision: X.X $                                                              
//                                                                               
//******************************PEPTOOL Header End*******************************
#ifndef FILE_TURBDEF_H
#define FILE_TURBDEF_H

#include "os_lib.h"

// ---------------------------------------------------------------------
// Only this module uses these variables and functions. (xx_lib.c and xx_app.c)
// ---------------------------------------------------------------------

// ---------------------------------------------------------------------
// Other modules may uses these variables and functions.
// ---------------------------------------------------------------------

// ---------------------------------------------------------------------
// This module uses these variables and functions from other modules.
// ---------------------------------------------------------------------

//-----------------------------------------------------------------------
// Errorcode definitions   Errorcode definitions  Errorcode definitions
//-----------------------------------------------------------------------
#define AUTOGENERATED_PART

#define BRAKE_PROG_0 ((U8)0)
#define BRAKE_PROG_10 ((U8)10)
#define BRAKE_PROG_50 ((U8)50)
#define BRAKE_PROG_70 ((U8)70)
#define BRAKE_PROG_75 ((U8)75)
#define BRAKE_PROG_99 ((U8)99)
#define BRAKE_PROG_199 ((U8)199)
#define BRAKE_PROG_200 ((U8)200)
#define BRAKE_PROG_MAX ((U8)201)
#define YAW_PROG_0 ((U8)0)
#define YAW_PROG_30 ((U8)30)
#define YAW_PROG_50 ((U8)50)
#define YAW_PROG_60 ((U8)60)
#define YAW_PROG_70 ((U8)70)
#define YAW_PROG_80 ((U8)80)
#define YAW_PROG_100 ((U8)100)
#define YAW_PROG_230 ((U8)230)
#define YAW_PROG_240 ((U8)240)
#define YAW_PROG_MIN ((U8)0)
#define YAW_PROG_MAX ((U8)241)
#define B_YAWCCW 62721
#define B_YAWCW 62722
#define B_YAWBLOCK 62723
#define B_YAWAUTO 62724

#undef AUTOGENERATED_PART

#endif