//*****************************PEPTOOL Header Start******************************
//                                                                               
//                         Copyright © 2015 Mita-Teknik.                         
//This software may only be used with WP4x00 Controllers delivered by Mita-Teknik
//                                                                               
//*******************************************************************************
//                                                                               
// $PEPTOOL version:9.0$                                                         
// $PEPTOOL file version:101$                                                    
//                                                                               
//*******************************************************************************
//                                                                               
// $Date: XXXX/XX/XX XX:XX:XX $                                                  
// $Author: XXXX\XXX $                                                           
// $RCSfile: AirPressure_Conf.c,v $                                              
// $Revision: X.X $                                                              
//                                                                               
//******************************PEPTOOL Header End*******************************

//***********************************************************************
// OS header files
#include <os_main.h>
// App header files
#include <InitIo.h>

#define AUTOGENERATED_PART

#include <Turbdef.h>

//-----------------------------------------------------------------------
// AUTOGENERATED START     AUTOGENERATED START     AUTOGENERATED START
//-----------------------------------------------------------------------
char AirPressure_Conf_copyright[] =
{
   67, 111, 112, 121, 114, 105, 103, 104, 116, 32, 63, 32, 50, 48, 49, 53,
   32, 77, 105, 116, 97, 45, 84, 101, 107, 110, 105, 107, 46, 13, 10, 84,
   104, 105, 115, 32, 115, 111, 102, 116, 119, 97, 114, 101, 32, 109, 97, 121,
   32, 111, 110, 108, 121, 32, 98, 101, 32, 117, 115, 101, 100, 32, 119, 105,
   116, 104, 32, 87, 80, 52, 120, 48, 48, 32, 67, 111, 110, 116, 114, 111,
   108, 108, 101, 114, 115, 32, 100, 101, 108, 105, 118, 101, 114, 101, 100, 32,
   98, 121, 32, 77, 105, 116, 97, 45, 84, 101, 107, 110, 105, 107, 0
};
//-----------------------------------------------------------------------
// MODIFIABLE                  MODIFIABLE               MODIFIABLE
//-----------------------------------------------------------------------
const char AirPressureAppGroupName[] = "G_"APP_ID"App";
const char AirPressureAppMenuName[] = "M_"APP_ID"AppMain";

//-----------------------------------------------------------------------
// IO VARIABLES                IO VARIABLES                IO VARIABLES
//-----------------------------------------------------------------------

void (*AirPressureSetLockValues)(void);
struct os_db_alias *AirPressureIOVars;
size_t AirPressureIOVarsSize = 0;
            
struct os_db_alias AirPressureIOVars1[]=
{
    VAR_ELEMENT_ALIAS("3.2.61",                           "AI_AirPressure"),
    VAR_ELEMENT_ALIAS("3.2.61_Ss",                        "AI_AirPressure_Ss"),
    VAR_ELEMENT_ALIAS("3.2.61_E",                         "AI_AirPressure_E"),
    VAR_ELEMENT_ALIAS( "3.2.61_Th",                        "AI_AirPressure_Th"),
    VAR_ELEMENT_ALIAS("3.2.61_Ht",                        "AI_AirPressure_Ht"),
    VAR_ELEMENT_ALIAS("3.2.61_S",                         "AI_AirPressure_S"),
    VAR_ELEMENT_ALIAS("3.2.61_O",                         "AI_AirPressure_O"),

};
size_t AirPressureIOVars1Size = sizeof(AirPressureIOVars1)/sizeof(AirPressureIOVars1[0]);

void AirPressureSetLockValues1(void)
{
   SetLockValue("AI_AirPressure_Ss",                     TYP_8,     1);
   SetLockValue("AI_AirPressure_E",                      TYP_8,     0);
   SetLockValue("AI_AirPressure_Th",                     TYP_16,    1);
   SetLockValue("AI_AirPressure_Ht",                     TYP_32,    100);
   SetLockValue("AI_AirPressure_S",                      TYP_32,    1);
   SetValue("AI_AirPressure_O",                          TYP_32,    0);
}


STATUS AirPressureInitIOAliases()
{
   AirPressureIOVars = AirPressureIOVars1;
   AirPressureIOVarsSize = AirPressureIOVars1Size;
   AirPressureSetLockValues = &AirPressureSetLockValues1;
   return OS_SUCCESS;
}
//-----------------------------------------------------------------------
// AUTOGENERATED END        AUTOGENERATED END        AUTOGENERATED END
//-----------------------------------------------------------------------

#undef AUTOGENERATED_PART
