//*****************************PEPTOOL Header Start******************************
//                                                                               
//                         Copyright © 2015 Mita-Teknik.                         
//This software may only be used with WP4x00 Controllers delivered by Mita-Teknik
//                                                                               
//*******************************************************************************
//                                                                               
// $PEPTOOL version:9.0$                                                         
// $PEPTOOL file version:106$                                                    
//                                                                               
//*******************************************************************************
//                                                                               
// $Date: XXXX/XX/XX XX:XX:XX $                                                  
// $Author: XXXX\XXX $                                                           
// $RCSfile: AirPressure.c,v $                                                   
// $Revision: X.X $                                                              
//                                                                               
//******************************PEPTOOL Header End*******************************

//***********************************************************************

// OS header files
#include <os_main.h>
// AppLib header files
#include <lib_main.h>
// App header files
#include <turbdef.h>
#include <VarMacros.h>

// Object header file
#include <AirPressure.h>

#define AUTOGENERATED_PART
//{
//-----------------------------------------------------------------------
// AUTOGENERATED START     AUTOGENERATED START     AUTOGENERATED START
//-----------------------------------------------------------------------

#define VALIDATE_HASH
char AirPressure_copyright[] =
{
   67, 111, 112, 121, 114, 105, 103, 104, 116, 32, 63, 32, 50, 48, 49, 53,
   32, 77, 105, 116, 97, 45, 84, 101, 107, 110, 105, 107, 46, 13, 10, 84,
   104, 105, 115, 32, 115, 111, 102, 116, 119, 97, 114, 101, 32, 109, 97, 121,
   32, 111, 110, 108, 121, 32, 98, 101, 32, 117, 115, 101, 100, 32, 119, 105,
   116, 104, 32, 87, 80, 52, 120, 48, 48, 32, 67, 111, 110, 116, 114, 111,
   108, 108, 101, 114, 115, 32, 100, 101, 108, 105, 118, 101, 114, 101, 100, 32,
   98, 121, 32, 77, 105, 116, 97, 45, 84, 101, 107, 110, 105, 107, 0
};

#define MODULE_NAME "Air PressureA"

//-----------------------------------------------------------------------
// ALLOCATE MEMORY FOR STRINGS IN VARDB
//-----------------------------------------------------------------------

static char A_V_AirPressureModeText[31]  = "12345678901234567890123456789";

//-----------------------------------------------------------------------
// DEFINE LOCAL VARIABLES DEFINE LOCAL VARIABLES DEFINE LOCAL VARIABLES
//-----------------------------------------------------------------------

static struct os_db_local LocalVars[] =
{
   VAR_ELEMENT_LOCAL("V_AirPressure",                            TYPE_U16,     PASSWORD_LEVEL_UNLOGGED_IN,        PASSWORD_LEVEL_UNLOGGED_IN,        SCALE_NONE,   0,       UNIT_MBAR,          0,   1013,            0,               2000,            NULL,  TOTLOG_ENABLE | FIVEMINLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_AirPressure1Sec",                        TYPE_U16,     PASSWORD_LEVEL_UNLOGGED_IN,        PASSWORD_LEVEL_UNLOGGED_IN,        SCALE_NONE,   0,       UNIT_MBAR,          0,   1013,            0,               2000,            NULL,  FIVEMINLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_AirPressure30Sec",                       TYPE_U16,     PASSWORD_LEVEL_UNLOGGED_IN,        PASSWORD_LEVEL_UNLOGGED_IN,        SCALE_NONE,   0,       UNIT_MBAR,          0,   1013,            0,               2000,            NULL,  FIVEMINLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_AirPressure10Min",                       TYPE_U16,     PASSWORD_LEVEL_UNLOGGED_IN,        PASSWORD_LEVEL_UNLOGGED_IN,        SCALE_NONE,   0,       UNIT_MBAR,          0,   1013,            0,               2000,            NULL,  FIVEMINLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_AirPressureStatusText",                  TYPE_STRING + sizeof(A_V_AirPressureModeText) - 1,  PASSWORD_LEVEL_UNLOGGED_IN,        PASSWORD_LEVEL_UNLOGGED_IN,        SCALE_NONE,   0,       UNIT_NONE,          0,   A_V_AirPressureModeText, 0,                0,                NULL,  NOLOG_ENABLE  ),
   VAR_ELEMENT_LOCAL("V_AirPressureStatus",                      TYPE_U8,      PASSWORD_LEVEL_UNLOGGED_IN,        PASSWORD_LEVEL_UNLOGGED_IN,        SCALE_NONE,   0,       UNIT_NONE,          0,   0,               0,               2,               NULL,  TOTLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_AirPressureMeassured",                   TYPE_U16,     PASSWORD_LEVEL_UNLOGGED_IN,        PASSWORD_LEVEL_UNLOGGED_IN,        SCALE_NONE,   0,       UNIT_MBAR,          0,   1013,            0,               2000,            NULL,  TOTLOG_ENABLE | FIVEMINLOG_ENABLE),
};

//-----------------------------------------------------------------------
// DEFINE PARAMETERS        DEFINE PARAMETERS        DEFINE PARAMETERS
//-----------------------------------------------------------------------

static struct os_db_parameter ParameterVars[] =
{
   VAR_ELEMENT_PARAMETER("P_AirPressure",                            TYPE_U16,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         SCALE_NONE,   0,       UNIT_MBAR,          0,   1013,            0,               2000,            NULL  ),
   VAR_ELEMENT_PARAMETER("P_AirPressureSensorEnable",                TYPE_U8,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         SCALE_NONE,   0,       UNIT_NONE,          0,   1,               0,               1,               NULL  ),
   VAR_ELEMENT_PARAMETER("P_AirPressureMBarAt4mA",                   TYPE_U16,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         SCALE_NONE,   0,       UNIT_MBAR,          0,   0,               0,               1000,            NULL  ),
   VAR_ELEMENT_PARAMETER("P_AirPressureMBarAt20mA",                  TYPE_U16,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         SCALE_NONE,   0,       UNIT_MBAR,          0,   2000,            1000,            3000,            NULL  ),
   VAR_ELEMENT_PARAMETER("P_AirPressure4to20MaErrHigh",              TYPE_S16,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         SCALE_DIV,    1000,    UNIT_MAMPERE,       1,   21000,           18000,           22000,           NULL  ),
   VAR_ELEMENT_PARAMETER("P_AirPressure4to20MaErrLow",               TYPE_S16,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         SCALE_DIV,    1000,    UNIT_MAMPERE,       1,   3000,            0,               6000,            NULL  ),
};

//-----------------------------------------------------------------------
// DEFINE BACKUPS            DEFINE BACKUPS            DEFINE BACKUPS
//-----------------------------------------------------------------------

//----------------------------------------------------------------------------------
// DEFINE VAR ARRAYS            DEFINE VAR ARRAYS            DEFINE VAR ARRAYS
//----------------------------------------------------------------------------------
char AirPressure_initialValues[] =
{
   100, 115, 22, 186, 184, 191, 141, 147, 216, 116, 231, 240, 141, 170, 250, 26,
   114, 241, 95, 205, 46, 207, 160, 132, 105, 217, 154, 13, 187, 188, 187, 157,
   0
};

//-----------------------------------------------------------------------
// CREATE DATABASE VARS   CREATE DATABASE VARS   CREATE DATABASE VARS
//-----------------------------------------------------------------------

static STATUS CreateVarDbVars(void)
{
   STATUS Status;
   size_t ErrorEntry;

   Status = OS_VarDB_CreateLocals(LocalVars, sizeof(LocalVars)/sizeof(LocalVars[0]), &ErrorEntry, AppLocalParameterPosition());
   if (Status != 0)
   {
      AppSystemLog(ERR_7, MODULE_NAME"CrVL: %d,%d", Status, ErrorEntry);
      return ERR_7;
   }

   Status = OS_VarDB_CreateParameters(ParameterVars, sizeof(ParameterVars)/sizeof(ParameterVars[0]), &ErrorEntry, AppExportParameterPosition());
   if (Status != 0)
   {
      AppSystemLog(ERR_7, MODULE_NAME"CrVXP: %d,%d", Status, ErrorEntry);
      return ERR_7;
   }

   return OS_SUCCESS;
}

#define CREATE_VARDB_VARS

//-----------------------------------------------------------------------
// CREATE IO VARIABLES     CREATE IO VARIABLES     CREATE IO VARIABLES
//-----------------------------------------------------------------------

extern STATUS AirPressureInitIOAliases();
extern struct os_db_alias* AirPressureIOVars;
extern void (*AirPressureSetLockValues)(void);
extern size_t AirPressureIOVarsSize;

static STATUS CreateIOVars(void)
{
   STATUS Status;
   size_t ErrorEntry;

   varid_t VarId;
   BOOL variablesExist = false;
   U8 counter = 50;
   Status = AirPressureInitIOAliases();
   STATUS_LINE_VAR_RETURN_VALUE(Status)
   while (!variablesExist && counter-- > 0)
   {
      variablesExist = true;
      U32 i = 0;
      for (i = 0; i < AirPressureIOVarsSize; ++i)
      {
         if (OS_VarDB_GetVariableID(AirPressureIOVars[i].Name, &VarId) != OS_SUCCESS)
         {
            variablesExist = false;
            break;
         }
      }

      if (!variablesExist)
      {
         OS_Sleep(100);
      }
   }

   Status = OS_VarDB_CreateAliases(AirPressureIOVars, AirPressureIOVarsSize, &ErrorEntry);
   if (Status)
   {
      AppDebugLog(5000, "Var Name = %s", AirPressureIOVars[ErrorEntry].Alias);
   }
   STATUS_LINE_VAR_RETURN_CONST(Status, ErrorEntry);
   return OS_SUCCESS;
}

#define CREATE_IO_VARS

//-----------------------------------------------------------------------
// ALIASES                       ALIASES                       ALIASES
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// INPUT                          INPUT                          INPUT
//-----------------------------------------------------------------------

// Create local variable
#define MODUL_INPUTS
static S16 AI_AirPressure = 0;
static U16 V_AirPressureMeassured = 0;
static U16 V_AirPressure = 0;
static U16 P_AirPressure = 0;
static U8 P_AirPressureSensorEnable = 0;
static U16 P_AirPressureMBarAt4mA = 0;
static U16 P_AirPressureMBarAt20mA = 0;
static S16 P_AirPressure4to20MaErrHigh = 0;
static S16 P_AirPressure4to20MaErrLow = 0;

//-----------------------------------------------------------------------
static struct ModulInOut ModulInputs[] =
{
   {"AI_AirPressure",                           &AI_AirPressure,                           sizeof(AI_AirPressure),                           },
   {"V_AirPressureMeassured",                   &V_AirPressureMeassured,                   sizeof(V_AirPressureMeassured),                   },
   {"V_AirPressure",                            &V_AirPressure,                            sizeof(V_AirPressure),                            },
   {"P_AirPressure",                            &P_AirPressure,                            sizeof(P_AirPressure),                            },
   {"P_AirPressureSensorEnable",                &P_AirPressureSensorEnable,                sizeof(P_AirPressureSensorEnable),                },
   {"P_AirPressureMBarAt4mA",                   &P_AirPressureMBarAt4mA,                   sizeof(P_AirPressureMBarAt4mA),                   },
   {"P_AirPressureMBarAt20mA",                  &P_AirPressureMBarAt20mA,                  sizeof(P_AirPressureMBarAt20mA),                  },
   {"P_AirPressure4to20MaErrHigh",              &P_AirPressure4to20MaErrHigh,              sizeof(P_AirPressure4to20MaErrHigh),              },
   {"P_AirPressure4to20MaErrLow",               &P_AirPressure4to20MaErrLow,               sizeof(P_AirPressure4to20MaErrLow),               },
};

//-----------------------------------------------------------------------
// Check variable type
static STATUS VarsReadReturnStatus;
static type_t ReadVarType = TYPE_NONE;
static void VarsReadTypeCheck(void)
{
   (void)VarsReadReturnStatus;
   (void)ReadVarType;
   VERIFY_INPUT_REF_ID(S16,       ModulInputs[0].Name,                      ModulInputs[0].Id)
   VERIFY_INPUT_REF_ID(U16,       ModulInputs[1].Name,                      ModulInputs[1].Id)
   VERIFY_INPUT_REF_ID(U16,       ModulInputs[2].Name,                      ModulInputs[2].Id)
   VERIFY_INPUT_REF_ID(U16,       ModulInputs[3].Name,                      ModulInputs[3].Id)
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[4].Name,                      ModulInputs[4].Id)
   VERIFY_INPUT_REF_ID(U16,       ModulInputs[5].Name,                      ModulInputs[5].Id)
   VERIFY_INPUT_REF_ID(U16,       ModulInputs[6].Name,                      ModulInputs[6].Id)
   VERIFY_INPUT_REF_ID(S16,       ModulInputs[7].Name,                      ModulInputs[7].Id)
   VERIFY_INPUT_REF_ID(S16,       ModulInputs[8].Name,                      ModulInputs[8].Id)
}

#undef MODUL_INPUTS
#define MODUL_INPUTS_SIZE (sizeof(ModulInputs)/sizeof(ModulInputs[0]))

//------------------------------------------------------------------------------------------
// READ/WRITE VARDB ARRAY      READ/WRITE VARDB ARRAY      READ/WRATE VARDB ARRAY
//------------------------------------------------------------------------------------------


//-----------------------------------------------------------------------
// PARAMETER                    PARAMETER                    PARAMETER
//-----------------------------------------------------------------------


//-----------------------------------------------------------------------
// READ VARS FROM VARDB    READ VARS FROM VARDB    READ VARS FROM VARDB
//-----------------------------------------------------------------------

static STATUS InputReferenceRoutine(U8 ModuleState)
{
   STATUS LocalStatus = 0;

   // Read input references
   if (ModuleState >= APP_INIT3)
   {
      // Check inputdata
      if (sizeof(ModulInputs) == 0)
      {
         AppSystemLog(ERR_4, MODULE_NAME"ModuleInputs = 0");
         return ERR_4;
      }
      // Read inputdata
      LocalStatus = OS_ReadVariables(ModulInputs, MODUL_INPUTS_SIZE);
      if (LocalStatus != 0)
      {
         AppSystemLog(ERR_4, MODULE_NAME"ReadVErr: element=%d elementpointer=0x%x", LocalStatus, &ModulInputs[LocalStatus]);
         return ERR_4;
      }
   }
   return 0;
}

#define READ_VARS

//-----------------------------------------------------------------------
// OUTPUT                         OUTPUT                         OUTPUT
//-----------------------------------------------------------------------

// Create local variable
#define MODUL_OUTPUTS
static U16 V_AirPressure1Sec = 0;
static U16 V_AirPressure30Sec = 0;
static U16 V_AirPressure10Min = 0;
static U8 V_AirPressureStatus = 0;
static char V_AirPressureStatusText[31];


//-----------------------------------------------------------------------
static struct ModulInOut ModulOutputs[] =
{
   {"V_AirPressure1Sec",                        &V_AirPressure1Sec,                        sizeof(V_AirPressure1Sec),                        },
   {"V_AirPressure30Sec",                       &V_AirPressure30Sec,                       sizeof(V_AirPressure30Sec),                       },
   {"V_AirPressure10Min",                       &V_AirPressure10Min,                       sizeof(V_AirPressure10Min),                       },
   {"V_AirPressureStatusText",                  &V_AirPressureStatusText,                  sizeof(V_AirPressureStatusText),                  },
   {"V_AirPressureStatus",                      &V_AirPressureStatus,                      sizeof(V_AirPressureStatus),                      },
   {"V_AirPressure",                            &V_AirPressure,                            sizeof(V_AirPressure),                            },
};

//-----------------------------------------------------------------------
// Check variable type
static STATUS VarsWriteReturnStatus;
static type_t WriteVarType = TYPE_NONE;
static void VarsWriteTypeCheck(void)
{
   (void)VarsWriteReturnStatus;
   (void)WriteVarType;
   VERIFY_OUTPUT_REF_ID(U16,       ModulOutputs[0].Name,                     ModulOutputs[0].Id,                       0)
   VERIFY_OUTPUT_REF_ID(U16,       ModulOutputs[1].Name,                     ModulOutputs[1].Id,                       0)
   VERIFY_OUTPUT_REF_ID(U16,       ModulOutputs[2].Name,                     ModulOutputs[2].Id,                       0)
   VERIFY_OUTPUT_STRING_REF_ID(STRING,     ModulOutputs[3].Name,                      ModulOutputs[3].Id, 0)
   VERIFY_OUTPUT_REF_ID(U8,        ModulOutputs[4].Name,                     ModulOutputs[4].Id,                       0)
   VERIFY_OUTPUT_REF_ID(U16,       ModulOutputs[5].Name,                     ModulOutputs[5].Id,                       0)
}

#undef MODUL_OUTPUTS
#define MODUL_OUTPUTS_SIZE (sizeof(ModulOutputs)/sizeof(ModulOutputs[0]))

//-----------------------------------------------------------------------
// WRITE VARS TO VARDB     WRITE VARS TO VARDB     WRITE VARS TO VARDB
//-----------------------------------------------------------------------

static STATUS InitOutputVars(void)
{
   STATUS LocalStatus;
   // Read outputdata
   LocalStatus = OS_ReadVariables(ModulOutputs, MODUL_OUTPUTS_SIZE);
   if (LocalStatus != 0)
   {
      AppSystemLog(ERR_4, MODULE_NAME"InitErr: element=%d elementpointer=0x%x", LocalStatus, &ModulOutputs[LocalStatus]);
      return ERR_4;
   }
   return OS_SUCCESS;
}
static STATUS OutputReferenceRoutine(U8 ModuleState)
{
   STATUS LocalStatus = 0;
   // Write Outputdata
   LocalStatus = OS_WriteVariablesConditional(ModulOutputs, MODUL_OUTPUTS_SIZE);
   if (LocalStatus != 0)
   {
      AppSystemLog(ERR_5, MODULE_NAME"WriteVErr: element=%d elementpointer=0x%x", LocalStatus, &ModulOutputs[LocalStatus]);
      return ERR_5;
   }
   return 0;
}

#define WRITE_VARS

//-----------------------------------------------------------------------
// VERIFY VARIABLES CREATION                 VERIFY VARIABLES CREATION
//-----------------------------------------------------------------------

static STATUS LocalIoCheck(void)
{
   // Check if input variables exist.
   STATUS LocalStatus;

   LocalStatus = OS_DoesVariablesExist(ModulInputs, MODUL_INPUTS_SIZE);
   if (LocalStatus != 0)
   {
      AppSystemLog(ERR_1, MODULE_NAME"InputErr: %d", LocalStatus);
      AppSystemLog(ERR_1, "Name: %s", ModulInputs[LocalStatus-1].Name);
      return ERR_1;
   }
   (void)VarsReadTypeCheck();

   LocalStatus = OS_DoesVariablesExist(ModulOutputs, MODUL_OUTPUTS_SIZE);
   if (LocalStatus != 0)
   {
      AppSystemLog(ERR_2, MODULE_NAME"OutputErr: %d", LocalStatus);
      AppSystemLog(ERR_2, "Name: %s", ModulOutputs[LocalStatus-1].Name);
      return ERR_2;
   }
   (void)VarsWriteTypeCheck();

   return OS_SUCCESS;
}

#define VERIFY_VARIABLES

//-----------------------------------------------------------------------
// ALLOCATE MEMORY FOR SUMMATIONS        ALLOCATE MEMORY FOR SUMMATIONS
//-----------------------------------------------------------------------


//-----------------------------------------------------------------------
// SUMMATIONS                  SUMMATIONS                  SUMMATIONS
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// DEFINE MENUS               DEFINE MENUS               DEFINE MENUS
//-----------------------------------------------------------------------



// Menu line and link to local menu
//-----------------------------------------------------------------------
static struct line_struct M_AirPressureLinkToLocalMenu[] =
{
   MENU_ELEMENT_LINE_LINK("Air Pressure",                      PASSWORD_LEVEL_END_CUSTOMER,        "M_AirPressure",                    "G_AirPressure"),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_AirPressureMenu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_AirPressure",                    PASSWORD_LEVEL_END_CUSTOMER),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_AirPressureMenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("AIR PRESSURE",                      PASSWORD_LEVEL_END_CUSTOMER,        "M_"APP_ID"AppMain",                "G_"APP_ID"App"),
   MENU_ELEMENT_LINE_VARRO("Air Pressure",                     PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_AirPressure",                              LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_LINK("Status",                            PASSWORD_LEVEL_END_CUSTOMER,        "M_Status121",                      "G_AirPressure"),
   MENU_ELEMENT_LINE_LINK("Parameter",                         PASSWORD_LEVEL_END_CUSTOMER,        "M_Parameter131",                   "G_AirPressure"),
   MENU_ELEMENT_LINE_LINK("Service",                           PASSWORD_LEVEL_SERVICE,             "M_Service141",                     "G_AirPressure"),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_Status121Menu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_Status121",                      PASSWORD_LEVEL_END_CUSTOMER),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_Status121MenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("STATUS",                            PASSWORD_LEVEL_END_CUSTOMER,        "M_AirPressure",                    "G_AirPressure"),
   MENU_ELEMENT_LINE_VARRO("Air Pressure",                     PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_AirPressure",                              LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Air Pressure (1s avr.)",           PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_AirPressure1Sec",                          LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Air Pressure (30s avr.)",          PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_AirPressure30Sec",                         LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Air Pressure (10m avr.)",          PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_AirPressure10Min",                         LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_LINK("Sensor status",                     PASSWORD_LEVEL_END_CUSTOMER,        "M_Sensorstatus1",                  "G_AirPressure"),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_Sensorstatus1Menu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_Sensorstatus1",                  PASSWORD_LEVEL_END_CUSTOMER),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_Sensorstatus1MenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("SENSOR STATUS",                     PASSWORD_LEVEL_END_CUSTOMER,        "M_Status121",                      "G_AirPressure"),
   MENU_ELEMENT_LINE_VARRO("Air Pressure Status",              PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_AirPressureStatusText",                    LINE_FORMAT_NONE),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_Parameter131Menu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_Parameter131",                   PASSWORD_LEVEL_END_CUSTOMER),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_Parameter131MenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("PARAMETER",                         PASSWORD_LEVEL_END_CUSTOMER,        "M_AirPressure",                    "G_AirPressure"),
   MENU_ELEMENT_LINE_VARRW("Air Pressure Sensor Enable",       PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_AirPressureSensorEnable",                  LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Air Pressure (Manual value)",      PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_AirPressure",                              LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Air Pressure at 4mA",              PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_AirPressureMBarAt4mA",                     LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Air Pressure at 20mA",             PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_AirPressureMBarAt20mA",                    LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Air Pressure 4to20mA Error High",  PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_AirPressure4to20MaErrHigh",                LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Air Pressure 4to20mA Error Low",   PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_AirPressure4to20MaErrLow",                 LINE_FORMAT_NONE),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_Service141Menu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_Service141",                     PASSWORD_LEVEL_SERVICE),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_Service141MenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("SERVICE",                           PASSWORD_LEVEL_SERVICE,             "M_AirPressure",                    "G_AirPressure"),
   MENU_ELEMENT_LINE_VARRO("Air Pressure",                     PASSWORD_LEVEL_SERVICE,             (char*)"AI_AirPressure",                             LINE_FORMAT_NONE),
};
// Creating parameters for multiplexed categories
//-----------------------------------------------------------------------
static struct multiplexed_info_struct M_AirPressureMultiplexedCategoriesParameters[] =
{
0};

//-----------------------------------------------------------------------
// CREATE MENUS               CREATE MENUS               CREATE MENUS
//-----------------------------------------------------------------------

// Memory reservation
//-----------------------------------------------------------------------
static struct menu_group_struct ObjGroup[1];

// Creating the menus
//-----------------------------------------------------------------------
STATUS AirPressureMenuAppInit(U8 ModuleState, OS_MEMORY_POOL* pPool)
{
   STATUS Status;

   if (ModuleState == APP_INIT1)
   {
      /* Create application group */
      Status = OS_CreateMenuGroup(ObjGroup, M_AirPressureLinkToLocalMenu[0].LinkGroup);
      STATUS_LINE_VAR_RETURN_VALUE(Status);
   }

   Status = CreateAndInitializeMenu(ModuleState,
                                    M_AirPressureMenuLines[0].LinkGroup,
                                    M_AirPressureMenuLines[0].LinkName,
                                    ELEMENT(M_AirPressureLinkToLocalMenu),
                                    M_AirPressureLinkToLocalMenu[0].LinkGroup,
                                    ELEMENT(M_AirPressureMenu),
                                    M_AirPressureLinkToLocalMenu[0].LinkName,
                                    ELEMENT(M_AirPressureMenuLines),
                                    pPool,
                                    M_AirPressureMultiplexedCategoriesParameters);
   STATUS_LINE_VAR_RETURN_VALUE(Status);

   Status = CreateAndInitializeMenu(ModuleState,
                                    M_Status121MenuLines[0].LinkGroup,
                                    M_Status121MenuLines[0].LinkName,
                                    NULL,
                                    0,
                                    M_AirPressureMenuLines[2].LinkGroup,
                                    ELEMENT(M_Status121Menu),
                                    M_AirPressureMenuLines[2].LinkName,
                                    ELEMENT(M_Status121MenuLines),
                                    pPool,
                                    M_AirPressureMultiplexedCategoriesParameters);
   STATUS_LINE_VAR_RETURN_VALUE(Status);

   Status = CreateAndInitializeMenu(ModuleState,
                                    M_Sensorstatus1MenuLines[0].LinkGroup,
                                    M_Sensorstatus1MenuLines[0].LinkName,
                                    NULL,
                                    0,
                                    M_Status121MenuLines[5].LinkGroup,
                                    ELEMENT(M_Sensorstatus1Menu),
                                    M_Status121MenuLines[5].LinkName,
                                    ELEMENT(M_Sensorstatus1MenuLines),
                                    pPool,
                                    M_AirPressureMultiplexedCategoriesParameters);
   STATUS_LINE_VAR_RETURN_VALUE(Status);

   Status = CreateAndInitializeMenu(ModuleState,
                                    M_Parameter131MenuLines[0].LinkGroup,
                                    M_Parameter131MenuLines[0].LinkName,
                                    NULL,
                                    0,
                                    M_AirPressureMenuLines[3].LinkGroup,
                                    ELEMENT(M_Parameter131Menu),
                                    M_AirPressureMenuLines[3].LinkName,
                                    ELEMENT(M_Parameter131MenuLines),
                                    pPool,
                                    M_AirPressureMultiplexedCategoriesParameters);
   STATUS_LINE_VAR_RETURN_VALUE(Status);

   Status = CreateAndInitializeMenu(ModuleState,
                                    M_Service141MenuLines[0].LinkGroup,
                                    M_Service141MenuLines[0].LinkName,
                                    NULL,
                                    0,
                                    M_AirPressureMenuLines[4].LinkGroup,
                                    ELEMENT(M_Service141Menu),
                                    M_AirPressureMenuLines[4].LinkName,
                                    ELEMENT(M_Service141MenuLines),
                                    pPool,
                                    M_AirPressureMultiplexedCategoriesParameters);
   STATUS_LINE_VAR_RETURN_VALUE(Status);

   return OS_SUCCESS;
}

#define CREATE_MENU

//-----------------------------------------------------------------------
//               BUTTONS FUNCTIONS FORWARD DECLARATIONS
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// BUTTONS                       BUTTONS                      BUTTONS
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
//             SET/RESET FUNCTIONS FORWARD DECLARATIONS
//-----------------------------------------------------------------------
//-----------------------------------------------------------------------
// STATUSCODES                 STATUSCODES                 STATUSCODES
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// MODIFIABLE                  MODIFIABLE                   MODIFIABLE
//-----------------------------------------------------------------------

extern const char AirPressureAppGroupName[];
extern const char AirPressureAppMenuName[];

static void Init_Structures_From_Conf_File(void)
{
   M_AirPressureMenuLines[0].LinkName = (char*)AirPressureAppMenuName;
   M_AirPressureMenuLines[0].LinkGroup = (char*)AirPressureAppGroupName;
}

//-----------------------------------------------------------------------
// AUTOGENERATED END        AUTOGENERATED END        AUTOGENERATED END
//-----------------------------------------------------------------------
//}

#undef AUTOGENERATED_PART

//-----------------------------------------------------------------------
// USER DEFINITIONS         USER DEFINITIONS         USER DEFINITIONS
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// SET/RESET FUNCTIONS    SET/RESET FUNCTIONS    SET/RESET FUNCTIONS
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// DRIVER FUNCTION         DRIVER FUNCTION         DRIVER FUNCTION
//-----------------------------------------------------------------------
  

STATUS InOutHwDriverAirPressure(U16 Counter, struct IoDriverStruct *IoDriverTable) {

	return 0;
	//return InOutAirPressure______Drv_t1_v1(Counter, IoDriverTable);
}


//-----------------------------------------------------------------------
// INIT                   INIT                     INIT
//-----------------------------------------------------------------------
  
//-----------------------------------------------------------------------
// CONTROL                CONTROL                 CONTROL
//-----------------------------------------------------------------------
  
static STATUS LocalCtrl( U32 Interval )
{
   STATUS LocalStatus = 0;

   return LocalStatus;
}

static STATUS ShutdownCtrl( U8 ModuleState, U8 *DoneState, U32 Interval )
{
    STATUS LocalStatus = 0;

    LocalStatus = LocalCtrl( Interval );
    STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);

    switch( ModuleState )
    {
        case AS_SHUTDOWN:
        {
            // Activate "Manual Shutdown" status code

            *DoneState = AS_SHUTDOWN;
            break;
        }
        case AS_REBOOT:
        {

            *DoneState = AS_REBOOT;
            break;
        }
        case AS_SHUTDOWN_FAST:
        {

            *DoneState = AS_SHUTDOWN_FAST;
            break;
        }
        default:
        {
            *DoneState = ModuleState;
            break;
        }
    }
    return LocalStatus;
}
 
//-----------------------------------------------------------------------
// MAIN CALL             MAIN CALL               MAIN CALL
//-----------------------------------------------------------------------

STATUS AirPressure( U8 ModuleState, U8 *DoneState , U32 Interval )
{
   STATUS LocalStatus = 0;

   #ifdef READ_VARS
      // Read input data
      LocalStatus = InputReferenceRoutine(ModuleState);
      STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
   #endif
   #ifdef COMMON_VDB_READ
      LocalStatus = ReadVdbWindow(ModuleState);
      STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
   #endif


   switch( ModuleState )
   {
      //__________________________________________________________________________
      case APP_RUN:
      {
         #ifdef FUNCTION_BLOCKS_PRE_LOCAL_CONTROL
            LocalStatus = FunctionBlocksPreLocalCtrl( Interval );
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif
         
         LocalStatus = LocalCtrl( Interval );
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);

         #ifdef FUNCTION_BLOCKS_POST_LOCAL_CONTROL
            LocalStatus = FunctionBlocksPostLocalCtrl( Interval );
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef WRITE_VARS
            // Write Output data
            LocalStatus = OutputReferenceRoutine(ModuleState);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef COMMON_VDB_WRITE
            LocalStatus = WriteVdbWindow(ModuleState);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         *DoneState = APP_RUN;
         break;
      }
      //__________________________________________________________________________
      case APP_INIT1:
      {
         // Version check
         LocalStatus = OS_ValidateAPI( API_VERSION_MAJOR,
                                API_VERSION_MINOR,
                                OS_LinkTime,
                                ReleaseTag,
                                __MODULE__
                               );
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);

         Init_Structures_From_Conf_File();

         #ifdef CREATE_VARDB_VARS
            LocalStatus = CreateVarDbVars();
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef CREATE_MENU
            LocalStatus = AirPressureMenuAppInit(ModuleState, GetMemPool());
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);

            #ifdef MULTIPLEXIBLE_MENU
               LocalStatus = MenuArraysAppInit(ModuleState, GetMemPool());
               STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
            #endif
         #endif

         #ifdef CREATE_VARDB_ARRAY_VARS
               LocalStatus = CreateVdbArrays(GetMemPool());
               STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
         #endif


         #ifdef CREATE_IO_VARS
               LocalStatus = CreateIOVars();
               STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
         #endif

         *DoneState = APP_INIT1;

         break;
      }
      //__________________________________________________________________________
      case APP_INIT2:
      {
         #ifdef CREATE_MENU
            #ifdef MULTIPLEXIBLE_MENU
               LocalStatus = MenuArraysAppInit(ModuleState, GetMemPool());
               STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
            #endif
         #endif

         #ifdef CREATE_ALIASES
               size_t ErrorEntry = 0;
               LocalStatus = OS_VarDB_CreateAliases(AliasVars, sizeof(AliasVars)/sizeof(AliasVars[0]), &ErrorEntry);
               STATUS_LINE_VAR_RETURN_CONST(LocalStatus, ErrorEntry);
         #endif

         #ifdef VERIFY_ARRAY
               LocalStatus = VerifyArray(GetMemPool());
               STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef VERIFY_VARIABLES
               LocalStatus = LocalIoCheck();
               STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef CREATE_BUTTONS
               LocalStatus = CreateButtons();
               STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         *DoneState = APP_INIT2;

         break;
      }
      //__________________________________________________________________________
      case APP_INIT3 :
      {
         #ifdef CREATE_SUMMATIONS
            LocalStatus = CreateSummations();
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef WRITE_VARS
            LocalStatus = InitOutputVars();
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef CREATE_STATUS_CODES
            LocalStatus = LocalStatusCodeInit();
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef CREATE_IO_VARS
           AirPressureSetLockValues();
         #endif

         *DoneState = APP_INIT3;

         break;
      }
      //__________________________________________________________________________
      case APP_INIT4:
      {
         #ifdef CREATE_MENU
            LocalStatus = AirPressureMenuAppInit(ModuleState, GetMemPool());
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);

            #ifdef MULTIPLEXIBLE_MENU
               LocalStatus = MenuArraysAppInit(ModuleState, GetMemPool());
               STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
            #endif
         #endif

         *DoneState = APP_INIT4;

         break;
      }
      //__________________________________________________________________________
      case APP_INIT5:
      {
         #ifdef VALIDATE_HASH
            LocalStatus = ValidateHash( AirPressure_copyright, MODULE_NAME, AirPressure_initialValues);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef INIT_FUNCTION_BLOCKS
            LocalStatus = FunctionBlocksInit( Interval );
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         *DoneState = APP_INIT5_DONE;

         break;
      }
      //__________________________________________________________________________
      //Other initialization round can be inserted here
      //__________________________________________________________________________
      case AS_SHUTDOWN:
      {
         LocalStatus = ShutdownCtrl ( ModuleState, DoneState, Interval );
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);

         #ifdef WRITE_VARS
            // Write Output data
            LocalStatus = OutputReferenceRoutine(ModuleState);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef COMMON_VDB_WRITE
            LocalStatus = WriteVdbWindow(ModuleState);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         break;
      }
      //__________________________________________________________________________
      case AS_REBOOT:
      {
         LocalStatus = ShutdownCtrl ( ModuleState, DoneState, Interval );
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);

         #ifdef WRITE_VARS
            // Write Output data
            LocalStatus = OutputReferenceRoutine(ModuleState);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef COMMON_VDB_WRITE
            LocalStatus = WriteVdbWindow(ModuleState);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         break;
      }
      //__________________________________________________________________________
      case AS_SHUTDOWN_FAST:
      {
         LocalStatus = ShutdownCtrl ( ModuleState, DoneState, Interval );
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);

         #ifdef WRITE_VARS
            // Write Output data
            LocalStatus = OutputReferenceRoutine(ModuleState);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef COMMON_VDB_WRITE
            LocalStatus = WriteVdbWindow(ModuleState);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         break;
      }
      default:
      {
         *DoneState = ModuleState;

         break;
      }
   }
   return OS_SUCCESS;
}
//-----------------------------------------------------------------------
