//*****************************PEPTOOL Header Start******************************
//                                                                               
//                         Copyright © 2015 Mita-Teknik.                         
//This software may only be used with WP4x00 Controllers delivered by Mita-Teknik
//                                                                               
//*******************************************************************************
//                                                                               
// $PEPTOOL version:9.0$                                                         
// $PEPTOOL file version:106$                                                    
//                                                                               
//*******************************************************************************
//                                                                               
// $Date: XXXX/XX/XX XX:XX:XX $                                                  
// $Author: XXXX\XXX $                                                           
// $RCSfile: BladeController_emulator.c,v $                                      
// $Revision: X.X $                                                              
//                                                                               
//******************************PEPTOOL Header End*******************************

//***********************************************************************

// OS header files
#include <os_main.h>
// AppLib header files
#include <lib_main.h>
// App header files
#include <turbdef.h>
#include <VarMacros.h>

// Object header file
#include <BladeController_emulator.h>

#include <Hysteresis_UpDown.h>


#define BLADECONTROLLER_SCAN_TIME 20


#pragma region AUTOGENERATED
#define AUTOGENERATED_PART
//{
//-----------------------------------------------------------------------
// AUTOGENERATED START     AUTOGENERATED START     AUTOGENERATED START
//-----------------------------------------------------------------------

#define VALIDATE_HASH
char BladeController_emulator_copyright[] =
{
    67, 111, 112, 121, 114, 105, 103, 104, 116, 32, 63, 32, 50, 48, 49, 53,
    32, 77, 105, 116, 97, 45, 84, 101, 107, 110, 105, 107, 46, 13, 10, 84,
    104, 105, 115, 32, 115, 111, 102, 116, 119, 97, 114, 101, 32, 109, 97, 121,
    32, 111, 110, 108, 121, 32, 98, 101, 32, 117, 115, 101, 100, 32, 119, 105,
    116, 104, 32, 87, 80, 52, 120, 48, 48, 32, 67, 111, 110, 116, 114, 111,
    108, 108, 101, 114, 115, 32, 100, 101, 108, 105, 118, 101, 114, 101, 100, 32,
    98, 121, 32, 77, 105, 116, 97, 45, 84, 101, 107, 110, 105, 107, 0
};

#define MODULE_NAME "Blade Controller emulatorA"

//-----------------------------------------------------------------------
// ALLOCATE MEMORY FOR STRINGS IN VARDB
//-----------------------------------------------------------------------


//-----------------------------------------------------------------------
// DEFINE LOCAL VARIABLES DEFINE LOCAL VARIABLES DEFINE LOCAL VARIABLES
//-----------------------------------------------------------------------

static struct os_db_local LocalVars[] =
{
   VAR_ELEMENT_LOCAL("V_BladeControllerReady",                   TYPE_U8,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   1,               0,               1,               NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_BladeControllerSafetyChainOk",           TYPE_U8,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   1,               0,               1,               NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_BladeControllerSts1119Enable",           TYPE_U8,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   1,               0,               1,               NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_MDSActPitchAngleA",                      TYPE_S32,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    100,     UNIT_DEGREE,        1,   9000,            -32000,          32000,           NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_MDSActPitchAngleB",                      TYPE_S32,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    100,     UNIT_DEGREE,        1,   9000,            -32000,          32000,           NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_MDSActPitchAngleC",                      TYPE_S32,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    100,     UNIT_DEGREE,        1,   9000,            -32000,          32000,           NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_MDSCurrentMode",                         TYPE_U8,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   0,               0,               6,               NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_MDSCurrentState",                        TYPE_U8,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   0,               0,               6,               NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_MDSRequestMode",                         TYPE_U8,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   0,               0,               5,               NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_MDSServiceAllowed",                      TYPE_U8,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   0,               0,               1,               NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_PitchAngle",                             TYPE_S32,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    100,     UNIT_DEGREE,        1,   9000,            -1000,           10500,           NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_PitchAngleSetPoint",                     TYPE_S32,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    100,     UNIT_DEGREE,        1,   9000,            S32_MIN,         S32_MAX,         NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_PitchAngleSetPoint1",                    TYPE_S32,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    100,     UNIT_DEGREE,        1,   9000,            S32_MIN,         S32_MAX,         NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_PitchAngleSetPoint2",                    TYPE_S32,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    100,     UNIT_DEGREE,        1,   9000,            S32_MIN,         S32_MAX,         NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_PitchAngleSetPoint3",                    TYPE_S32,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    100,     UNIT_DEGREE,        1,   9000,            S32_MIN,         S32_MAX,         NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_PitchSpeedLimit",                        TYPE_U32,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    100,     UNIT_DEGREESPSEC,   1,   800,             U32_MIN,         U32_MAX,         NULL,  NOLOG_ENABLE),
};

//-----------------------------------------------------------------------
// DEFINE PARAMETERS        DEFINE PARAMETERS        DEFINE PARAMETERS
//-----------------------------------------------------------------------

static struct os_db_parameter ParameterVars[] =
{
   VAR_ELEMENT_PARAMETER("P_BLC_AngleMaxDeviation",                  TYPE_S32,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         SCALE_DIV,    100,     UNIT_DEGREE,        2,   300,             50,              2000,            NULL  ),
   VAR_ELEMENT_PARAMETER("P_BLC_AngleIndividualDeviation",           TYPE_S32,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         SCALE_DIV,    100,     UNIT_DEGREE,        2,   200,             50,              2000,            NULL  ),
};

//-----------------------------------------------------------------------
// DEFINE BACKUPS            DEFINE BACKUPS            DEFINE BACKUPS
//-----------------------------------------------------------------------

//----------------------------------------------------------------------------------
// DEFINE VAR ARRAYS            DEFINE VAR ARRAYS            DEFINE VAR ARRAYS
//----------------------------------------------------------------------------------
char BladeController_emulator_initialValues[] =
{
    118, 18, 253, 81, 216, 223, 153, 34, 202, 133, 89, 46, 140, 55, 128, 201,
    84, 161, 120, 38, 118, 221, 228, 179, 78, 186, 4, 252, 48, 136, 156, 77,
    0
};

//-----------------------------------------------------------------------
// CREATE DATABASE VARS   CREATE DATABASE VARS   CREATE DATABASE VARS
//-----------------------------------------------------------------------

static STATUS CreateVarDbVars(void)
{
   STATUS Status;
   size_t ErrorEntry;

   Status = OS_VarDB_CreateLocals(LocalVars, sizeof(LocalVars)/sizeof(LocalVars[0]), &ErrorEntry, AppLocalParameterPosition());
   if (Status != 0)
   {
      AppSystemLog(ERR_7, MODULE_NAME"CrVL: %d,%d", Status, ErrorEntry);
      return ERR_7;
   }

   Status = OS_VarDB_CreateParameters(ParameterVars, sizeof(ParameterVars)/sizeof(ParameterVars[0]), &ErrorEntry, AppExportParameterPosition());
   if (Status != 0)
   {
      AppSystemLog(ERR_7, MODULE_NAME"CrVXP: %d,%d", Status, ErrorEntry);
      return ERR_7;
   }

   return OS_SUCCESS;
}

#define CREATE_VARDB_VARS

//-----------------------------------------------------------------------
// CREATE IO VARIABLES     CREATE IO VARIABLES     CREATE IO VARIABLES
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// ALIASES                       ALIASES                       ALIASES
//-----------------------------------------------------------------------

static struct os_db_alias AliasVars[] =
{
   VAR_ELEMENT_ALIAS("V_MDSActPitchAngleA",                      "V_PitchAngle1"),
   VAR_ELEMENT_ALIAS("V_MDSActPitchAngleB",                      "V_PitchAngle2"),
   VAR_ELEMENT_ALIAS("V_MDSActPitchAngleC",                      "V_PitchAngle3"),
};

#define CREATE_ALIASES

//-----------------------------------------------------------------------
// INPUT                          INPUT                          INPUT
//-----------------------------------------------------------------------

// Create local variable
#define MODUL_INPUTS
static S32 V_PitchAngleSetPoint = 0;
static S32 V_PitchAngleSetPoint2 = 0;
static S32 V_PitchAngleSetPoint1 = 0;
static S32 V_PitchAngleSetPoint3 = 0;
static U32 V_PitchSpeedLimit = 0;
static U8 DLL_IN_Initialize = 0;
static S32 P_PAT_PitchAngleStop = 0;
static S32 P_BLC_AngleMaxDeviation = 0;
static S32 P_BLC_AngleIndividualDeviation = 0;
static F32 DLL_IN_PitchAngle_1 = 0;
static F32 DLL_IN_PitchAngle_2 = 0;
static F32 DLL_IN_PitchAngle_3 = 0;

//-----------------------------------------------------------------------
static struct ModulInOut ModulInputs[] =
{
   {"V_PitchAngleSetPoint",                     &V_PitchAngleSetPoint,                     sizeof(V_PitchAngleSetPoint),                     },
   {"V_PitchAngleSetPoint2",                    &V_PitchAngleSetPoint2,                    sizeof(V_PitchAngleSetPoint2),                    },
   {"V_PitchAngleSetPoint1",                    &V_PitchAngleSetPoint1,                    sizeof(V_PitchAngleSetPoint1),                    },
   {"V_PitchAngleSetPoint3",                    &V_PitchAngleSetPoint3,                    sizeof(V_PitchAngleSetPoint3),                    },
   {"V_PitchSpeedLimit",                        &V_PitchSpeedLimit,                        sizeof(V_PitchSpeedLimit),                        },
   {"DLL_IN_Initialize",                        &DLL_IN_Initialize,                        sizeof(DLL_IN_Initialize),                        },
   {"P_PAT_PitchAngleStop",                     &P_PAT_PitchAngleStop,                     sizeof(P_PAT_PitchAngleStop),                     },
   {"P_BLC_AngleMaxDeviation",                  &P_BLC_AngleMaxDeviation,                  sizeof(P_BLC_AngleMaxDeviation),                  },
   {"P_BLC_AngleIndividualDeviation",           &P_BLC_AngleIndividualDeviation,           sizeof(P_BLC_AngleIndividualDeviation),           },
   {"DLL_IN_PitchAngle_1",                      &DLL_IN_PitchAngle_1,                      sizeof(DLL_IN_PitchAngle_1),                      },
   {"DLL_IN_PitchAngle_2",                      &DLL_IN_PitchAngle_2,                      sizeof(DLL_IN_PitchAngle_2),                      },
   {"DLL_IN_PitchAngle_3",                      &DLL_IN_PitchAngle_3,                      sizeof(DLL_IN_PitchAngle_3),                      },
};

//-----------------------------------------------------------------------
// Check variable type
static STATUS VarsReadReturnStatus;
static type_t ReadVarType = TYPE_NONE;
static void VarsReadTypeCheck(void)
{
   (void)VarsReadReturnStatus;
   (void)ReadVarType;
   VERIFY_INPUT_REF_ID(S32,       ModulInputs[0].Name,                      ModulInputs[0].Id)
   VERIFY_INPUT_REF_ID(S32,       ModulInputs[1].Name,                      ModulInputs[1].Id)
   VERIFY_INPUT_REF_ID(S32,       ModulInputs[2].Name,                      ModulInputs[2].Id)
   VERIFY_INPUT_REF_ID(S32,       ModulInputs[3].Name,                      ModulInputs[3].Id)
   VERIFY_INPUT_REF_ID(U32,       ModulInputs[4].Name,                      ModulInputs[4].Id)
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[5].Name,                      ModulInputs[5].Id)
   VERIFY_INPUT_REF_ID(S32,       ModulInputs[6].Name,                      ModulInputs[6].Id)
   VERIFY_INPUT_REF_ID(S32,       ModulInputs[7].Name,                      ModulInputs[7].Id)
   VERIFY_INPUT_REF_ID(S32,       ModulInputs[8].Name,                      ModulInputs[8].Id)
   VERIFY_INPUT_REF_ID(F32,       ModulInputs[9].Name,                      ModulInputs[9].Id)
   VERIFY_INPUT_REF_ID(F32,       ModulInputs[10].Name,                     ModulInputs[10].Id)
   VERIFY_INPUT_REF_ID(F32,       ModulInputs[11].Name,                     ModulInputs[11].Id)
}

#undef MODUL_INPUTS
#define MODUL_INPUTS_SIZE (sizeof(ModulInputs)/sizeof(ModulInputs[0]))

//------------------------------------------------------------------------------------------
// READ/WRITE VARDB ARRAY      READ/WRITE VARDB ARRAY      READ/WRATE VARDB ARRAY
//------------------------------------------------------------------------------------------


//-----------------------------------------------------------------------
// PARAMETER                    PARAMETER                    PARAMETER
//-----------------------------------------------------------------------


//-----------------------------------------------------------------------
// READ VARS FROM VARDB    READ VARS FROM VARDB    READ VARS FROM VARDB
//-----------------------------------------------------------------------

static STATUS InputReferenceRoutine(U8 ModuleState)
{
   STATUS LocalStatus = 0;

   // Read input references
   if (ModuleState >= APP_INIT3)
   {
      // Check inputdata
      if (sizeof(ModulInputs) == 0)
      {
         AppSystemLog(ERR_4, MODULE_NAME"ModuleInputs = 0");
         return ERR_4;
      }
      // Read inputdata
      LocalStatus = OS_ReadVariables(ModulInputs, MODUL_INPUTS_SIZE);
      if (LocalStatus != 0)
      {
         AppSystemLog(ERR_4, MODULE_NAME"ReadVErr: element=%d elementpointer=0x%x", LocalStatus, &ModulInputs[LocalStatus]);
         return ERR_4;
      }
   }
   return 0;
}

#define READ_VARS

//-----------------------------------------------------------------------
// OUTPUT                         OUTPUT                         OUTPUT
//-----------------------------------------------------------------------

// Create local variable
#define MODUL_OUTPUTS
static S32 V_MDSActPitchAngleA = 0;
static S32 V_MDSActPitchAngleB = 0;
static S32 V_MDSActPitchAngleC = 0;
static S32 V_PitchAngle = 0;


//-----------------------------------------------------------------------
static struct ModulInOut ModulOutputs[] =
{
   {"V_MDSActPitchAngleA",                      &V_MDSActPitchAngleA,                      sizeof(V_MDSActPitchAngleA),                      },
   {"V_MDSActPitchAngleB",                      &V_MDSActPitchAngleB,                      sizeof(V_MDSActPitchAngleB),                      },
   {"V_MDSActPitchAngleC",                      &V_MDSActPitchAngleC,                      sizeof(V_MDSActPitchAngleC),                      },
   {"V_PitchAngle",                             &V_PitchAngle,                             sizeof(V_PitchAngle),                             },
};

//-----------------------------------------------------------------------
// Check variable type
static STATUS VarsWriteReturnStatus;
static type_t WriteVarType = TYPE_NONE;
static void VarsWriteTypeCheck(void)
{
   (void)VarsWriteReturnStatus;
   (void)WriteVarType;
   VERIFY_OUTPUT_REF_ID(S32,       ModulOutputs[0].Name,                     ModulOutputs[0].Id,                       0)
   VERIFY_OUTPUT_REF_ID(S32,       ModulOutputs[1].Name,                     ModulOutputs[1].Id,                       0)
   VERIFY_OUTPUT_REF_ID(S32,       ModulOutputs[2].Name,                     ModulOutputs[2].Id,                       0)
   VERIFY_OUTPUT_REF_ID(S32,       ModulOutputs[3].Name,                     ModulOutputs[3].Id,                       0)
}

#undef MODUL_OUTPUTS
#define MODUL_OUTPUTS_SIZE (sizeof(ModulOutputs)/sizeof(ModulOutputs[0]))

//-----------------------------------------------------------------------
// WRITE VARS TO VARDB     WRITE VARS TO VARDB     WRITE VARS TO VARDB
//-----------------------------------------------------------------------

static STATUS InitOutputVars(void)
{
   STATUS LocalStatus;
   // Read outputdata
   LocalStatus = OS_ReadVariables(ModulOutputs, MODUL_OUTPUTS_SIZE);
   if (LocalStatus != 0)
   {
      AppSystemLog(ERR_4, MODULE_NAME"InitErr: element=%d elementpointer=0x%x", LocalStatus, &ModulOutputs[LocalStatus]);
      return ERR_4;
   }
   return OS_SUCCESS;
}
static STATUS OutputReferenceRoutine(U8 ModuleState)
{
   STATUS LocalStatus = 0;
   // Write Outputdata
   LocalStatus = OS_WriteVariablesConditional(ModulOutputs, MODUL_OUTPUTS_SIZE);
   if (LocalStatus != 0)
   {
      AppSystemLog(ERR_5, MODULE_NAME"WriteVErr: element=%d elementpointer=0x%x", LocalStatus, &ModulOutputs[LocalStatus]);
      return ERR_5;
   }
   return 0;
}

#define WRITE_VARS

//-----------------------------------------------------------------------
// VERIFY VARIABLES CREATION                 VERIFY VARIABLES CREATION
//-----------------------------------------------------------------------

static STATUS LocalIoCheck(void)
{
   // Check if input variables exist.
   STATUS LocalStatus;

   LocalStatus = OS_DoesVariablesExist(ModulInputs, MODUL_INPUTS_SIZE);
   if (LocalStatus != 0)
   {
      AppSystemLog(ERR_1, MODULE_NAME"InputErr: %d", LocalStatus);
      AppSystemLog(ERR_1, "Name: %s", ModulInputs[LocalStatus-1].Name);
      return ERR_1;
   }
   (void)VarsReadTypeCheck();

   LocalStatus = OS_DoesVariablesExist(ModulOutputs, MODUL_OUTPUTS_SIZE);
   if (LocalStatus != 0)
   {
      AppSystemLog(ERR_2, MODULE_NAME"OutputErr: %d", LocalStatus);
      AppSystemLog(ERR_2, "Name: %s", ModulOutputs[LocalStatus-1].Name);
      return ERR_2;
   }
   (void)VarsWriteTypeCheck();

   return OS_SUCCESS;
}

#define VERIFY_VARIABLES

//-----------------------------------------------------------------------
// ALLOCATE MEMORY FOR SUMMATIONS        ALLOCATE MEMORY FOR SUMMATIONS
//-----------------------------------------------------------------------


//-----------------------------------------------------------------------
// SUMMATIONS                  SUMMATIONS                  SUMMATIONS
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// DEFINE MENUS               DEFINE MENUS               DEFINE MENUS
//-----------------------------------------------------------------------



// Menu line and link to local menu
//-----------------------------------------------------------------------
static struct line_struct M_BladeControlleremulatorLinkToLocalMenu[] =
{
   MENU_ELEMENT_LINE_LINK("Blade Controller emulator",         PASSWORD_LEVEL_LICENCE_CUSTOMER,    "M_BladeControlleremulator",        "G_BladeController_emulator"),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_BladeControlleremulatorMenu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_BladeControlleremulator",        PASSWORD_LEVEL_LICENCE_CUSTOMER),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_BladeControlleremulatorMenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("BLADE CONTROLLER EMULATOR",         PASSWORD_LEVEL_LICENCE_CUSTOMER,    "M_"APP_ID"AppMain",                "G_"APP_ID"App"),
   MENU_ELEMENT_LINE_VARRW("V_BladeControllerReady",           PASSWORD_LEVEL_LICENCE_CUSTOMER,    (char*)"V_BladeControllerReady",                     LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("V_BladeControllerSafetyChainOk",   PASSWORD_LEVEL_LICENCE_CUSTOMER,    (char*)"V_BladeControllerSafetyChainOk",             LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("V_MDSCurrentMode",                 PASSWORD_LEVEL_LICENCE_CUSTOMER,    (char*)"V_MDSCurrentMode",                           LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("V_MDSCurrentState",                PASSWORD_LEVEL_LICENCE_CUSTOMER,    (char*)"V_MDSCurrentState",                          LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("V_MDSRequestMode",                 PASSWORD_LEVEL_LICENCE_CUSTOMER,    (char*)"V_MDSRequestMode",                           LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("V_MDSServiceAllowed",              PASSWORD_LEVEL_LICENCE_CUSTOMER,    (char*)"V_MDSServiceAllowed",                        LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("V_BladeControllerSts1119Enable",   PASSWORD_LEVEL_LICENCE_CUSTOMER,    (char*)"V_BladeControllerSts1119Enable",             LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("V_PitchSpeedLimit",                PASSWORD_LEVEL_LICENCE_CUSTOMER,    (char*)"V_PitchSpeedLimit",                          LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("V_PitchAngleSetPoint",             PASSWORD_LEVEL_LICENCE_CUSTOMER,    (char*)"V_PitchAngleSetPoint",                       LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("V_PitchAngle",                     PASSWORD_LEVEL_LICENCE_CUSTOMER,    (char*)"V_PitchAngle",                               LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Pitch Angle A",                    PASSWORD_LEVEL_LICENCE_CUSTOMER,    (char*)"V_MDSActPitchAngleA",                        LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Pitch Angle B",                    PASSWORD_LEVEL_LICENCE_CUSTOMER,    (char*)"V_MDSActPitchAngleB",                        LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Pitch Angle C",                    PASSWORD_LEVEL_LICENCE_CUSTOMER,    (char*)"V_MDSActPitchAngleC",                        LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_LINK("Parameters",                        PASSWORD_LEVEL_LICENCE_CUSTOMER,    "M_Parameters",                     "G_BladeController_emulator"),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_ParametersMenu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_Parameters",                     PASSWORD_LEVEL_LICENCE_CUSTOMER),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_ParametersMenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("PARAMETERS",                        PASSWORD_LEVEL_LICENCE_CUSTOMER,    "M_BladeControlleremulator",        "G_BladeController_emulator"),
   MENU_ELEMENT_LINE_VARRW("Max Positioning Angle Deviation",  PASSWORD_LEVEL_LICENCE_CUSTOMER,    (char*)"P_BLC_AngleMaxDeviation",                    LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Max Individual Angle Deviation",   PASSWORD_LEVEL_LICENCE_CUSTOMER,    (char*)"P_BLC_AngleIndividualDeviation",             LINE_FORMAT_NONE),
};
// Creating parameters for multiplexed categories
//-----------------------------------------------------------------------
static struct multiplexed_info_struct M_BladeControlleremulatorMultiplexedCategoriesParameters[] =
{
0};

//-----------------------------------------------------------------------
// CREATE MENUS               CREATE MENUS               CREATE MENUS
//-----------------------------------------------------------------------

// Memory reservation
//-----------------------------------------------------------------------
static struct menu_group_struct ObjGroup[1];

// Creating the menus
//-----------------------------------------------------------------------
STATUS BladeController_emulatorMenuAppInit(U8 ModuleState, OS_MEMORY_POOL* pPool)
{
   STATUS Status;

   if (ModuleState == APP_INIT1)
   {
      /* Create application group */
      Status = OS_CreateMenuGroup(ObjGroup, M_BladeControlleremulatorLinkToLocalMenu[0].LinkGroup);
      STATUS_LINE_VAR_RETURN_VALUE(Status);
   }

   Status = CreateAndInitializeMenu(ModuleState,
                                    M_BladeControlleremulatorMenuLines[0].LinkGroup,
                                    M_BladeControlleremulatorMenuLines[0].LinkName,
                                    ELEMENT(M_BladeControlleremulatorLinkToLocalMenu),
                                    M_BladeControlleremulatorLinkToLocalMenu[0].LinkGroup,
                                    ELEMENT(M_BladeControlleremulatorMenu),
                                    M_BladeControlleremulatorLinkToLocalMenu[0].LinkName,
                                    ELEMENT(M_BladeControlleremulatorMenuLines),
                                    pPool,
                                    M_BladeControlleremulatorMultiplexedCategoriesParameters);
   STATUS_LINE_VAR_RETURN_VALUE(Status);

   Status = CreateAndInitializeMenu(ModuleState,
                                    M_ParametersMenuLines[0].LinkGroup,
                                    M_ParametersMenuLines[0].LinkName,
                                    NULL,
                                    0,
                                    M_BladeControlleremulatorMenuLines[14].LinkGroup,
                                    ELEMENT(M_ParametersMenu),
                                    M_BladeControlleremulatorMenuLines[14].LinkName,
                                    ELEMENT(M_ParametersMenuLines),
                                    pPool,
                                    M_BladeControlleremulatorMultiplexedCategoriesParameters);
   STATUS_LINE_VAR_RETURN_VALUE(Status);

   return OS_SUCCESS;
}

#define CREATE_MENU

//-----------------------------------------------------------------------
//               BUTTONS FUNCTIONS FORWARD DECLARATIONS
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// BUTTONS                       BUTTONS                      BUTTONS
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
//             SET/RESET FUNCTIONS FORWARD DECLARATIONS
//-----------------------------------------------------------------------
static U8 StatusSetFunc1113(void);
static U8 StatusSetFunc1131(void);
static U8 StatusSetFunc1132(void);
static U8 StatusSetFunc1133(void);
//-----------------------------------------------------------------------
// STATUSCODES                 STATUSCODES                 STATUSCODES
//-----------------------------------------------------------------------

static struct sts_statuscode_structure StatusCodes[] =
{
   STS_CODE_ELEMENT("Pitch angle diff.",      20*SEC,    1113,      STATUSCODE_UPDATE_TYPE_POLLING,         PASSWORD_LEVEL_SERVICE,            STATUSCODE_TIMER_TYPE_CONSTANT,     STATUSCODE_TIMER_TYPE_CONSTANT,     STATUSCODE_RESET_TYPE_DISPLAY,      STATUSCODE_PRIORITY_LOW,       18,   0,    32,   NULL,      PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_SERVICE,            StatusSetFunc1113,       NULL,                    BRAKE_PROG_0,       BRAKE_PROG_0,        BRAKE_PROG_200,      NULL,                PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_SERVICE,            YAW_PROG_0,          YAW_PROG_0,          YAW_PROG_240,        NULL,                PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_SERVICE,            1,    0,    255,  NULL,      PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_SERVICE,            1,  PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_SERVICE,            100,       20,        1000,      NULL,      PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_SERVICE,            2*SEC,     SETDELAY_MIN,   SETDELAY_MAX,   NULL,      PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_SERVICE,            0,         RESETDELAY_MIN, RESETDELAY_MAX, NULL,      PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_SERVICE,            0,         REPEATTIMES_MIN,     REPEATTIMES_MAX,     NULL,      PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_SERVICE,            0,         REPEATPERIOD_MIN,    REPEATPERIOD_MAX,    NULL,      PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_SERVICE,            0,         REPEATCODE_MIN,      REPEATCODE_MAX,      NULL,      PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_SERVICE,            0,         TIMEOUTPERIOD_MIN,   TIMEOUTPERIOD_MAX,   NULL,      PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_SERVICE,            0,         TIMEOUTCODE_MIN,     TIMEOUTCODE_MAX,     NULL,      PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_SERVICE,            NULL),
   STS_CODE_ELEMENT("Pitch angle 1",          20*SEC,    1131,      STATUSCODE_UPDATE_TYPE_POLLING,         PASSWORD_LEVEL_SERVICE,            STATUSCODE_TIMER_TYPE_CONSTANT,     STATUSCODE_TIMER_TYPE_CONSTANT,     STATUSCODE_RESET_TYPE_DISPLAY,      STATUSCODE_PRIORITY_LOW,       18,   0,    32,   NULL,      PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_SERVICE,            StatusSetFunc1131,       NULL,                    BRAKE_PROG_0,       BRAKE_PROG_0,        BRAKE_PROG_200,      NULL,                PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_SERVICE,            YAW_PROG_0,          YAW_PROG_0,          YAW_PROG_240,        NULL,                PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_SERVICE,            1,    0,    255,  NULL,      PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_SERVICE,            1,  PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_SERVICE,            100,       20,        1000,      NULL,      PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_SERVICE,            0,         SETDELAY_MIN,   SETDELAY_MAX,   NULL,      PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_SERVICE,            0,         RESETDELAY_MIN, RESETDELAY_MAX, NULL,      PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_SERVICE,            0,         REPEATTIMES_MIN,     REPEATTIMES_MAX,     NULL,      PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_SERVICE,            0,         REPEATPERIOD_MIN,    REPEATPERIOD_MAX,    NULL,      PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_SERVICE,            0,         REPEATCODE_MIN,      REPEATCODE_MAX,      NULL,      PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_SERVICE,            0,         TIMEOUTPERIOD_MIN,   TIMEOUTPERIOD_MAX,   NULL,      PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_SERVICE,            0,         TIMEOUTCODE_MIN,     TIMEOUTCODE_MAX,     NULL,      PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_SERVICE,            NULL),
   STS_CODE_ELEMENT("Pitch angle 2",          20*SEC,    1132,      STATUSCODE_UPDATE_TYPE_POLLING,         PASSWORD_LEVEL_SERVICE,            STATUSCODE_TIMER_TYPE_CONSTANT,     STATUSCODE_TIMER_TYPE_CONSTANT,     STATUSCODE_RESET_TYPE_DISPLAY,      STATUSCODE_PRIORITY_LOW,       18,   0,    32,   NULL,      PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_SERVICE,            StatusSetFunc1132,       NULL,                    BRAKE_PROG_0,       BRAKE_PROG_0,        BRAKE_PROG_200,      NULL,                PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_SERVICE,            YAW_PROG_0,          YAW_PROG_0,          YAW_PROG_240,        NULL,                PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_SERVICE,            1,    0,    255,  NULL,      PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_SERVICE,            1,  PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_SERVICE,            100,       20,        1000,      NULL,      PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_SERVICE,            0,         SETDELAY_MIN,   SETDELAY_MAX,   NULL,      PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_SERVICE,            0,         RESETDELAY_MIN, RESETDELAY_MAX, NULL,      PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_SERVICE,            0,         REPEATTIMES_MIN,     REPEATTIMES_MAX,     NULL,      PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_SERVICE,            0,         REPEATPERIOD_MIN,    REPEATPERIOD_MAX,    NULL,      PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_SERVICE,            0,         REPEATCODE_MIN,      REPEATCODE_MAX,      NULL,      PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_SERVICE,            0,         TIMEOUTPERIOD_MIN,   TIMEOUTPERIOD_MAX,   NULL,      PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_SERVICE,            0,         TIMEOUTCODE_MIN,     TIMEOUTCODE_MAX,     NULL,      PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_SERVICE,            NULL),
   STS_CODE_ELEMENT("Pitch angle 3",          20*SEC,    1133,      STATUSCODE_UPDATE_TYPE_POLLING,         PASSWORD_LEVEL_SERVICE,            STATUSCODE_TIMER_TYPE_CONSTANT,     STATUSCODE_TIMER_TYPE_CONSTANT,     STATUSCODE_RESET_TYPE_DISPLAY,      STATUSCODE_PRIORITY_LOW,       18,   0,    32,   NULL,      PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_SERVICE,            StatusSetFunc1133,       NULL,                    BRAKE_PROG_0,       BRAKE_PROG_0,        BRAKE_PROG_200,      NULL,                PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_SERVICE,            YAW_PROG_0,          YAW_PROG_0,          YAW_PROG_240,        NULL,                PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_SERVICE,            1,    0,    255,  NULL,      PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_SERVICE,            1,  PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_SERVICE,            100,       20,        1000,      NULL,      PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_SERVICE,            0,         SETDELAY_MIN,   SETDELAY_MAX,   NULL,      PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_SERVICE,            0,         RESETDELAY_MIN, RESETDELAY_MAX, NULL,      PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_SERVICE,            0,         REPEATTIMES_MIN,     REPEATTIMES_MAX,     NULL,      PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_SERVICE,            0,         REPEATPERIOD_MIN,    REPEATPERIOD_MAX,    NULL,      PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_SERVICE,            0,         REPEATCODE_MIN,      REPEATCODE_MAX,      NULL,      PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_SERVICE,            0,         TIMEOUTPERIOD_MIN,   TIMEOUTPERIOD_MAX,   NULL,      PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_SERVICE,            0,         TIMEOUTCODE_MIN,     TIMEOUTCODE_MAX,     NULL,      PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_SERVICE,            NULL),
};

static STATUS_CODE_CONTROL_BLOCK StatusCodeControlBlock;

static STATUS LocalStatusCodeInit(void)
{
   STATUS LocalStatus;

   LocalStatus = OS_StatusCodeInit(STATUSCODE_INTERFACE_VERSION,
                                   &StatusCodeControlBlock,
                                   StatusCodes,
                                   sizeof(StatusCodes)/sizeof(StatusCodes[0]),
                                   AppLocalParameterPosition(),
                                   AppBackupPosition());
   STATUS_LINE_VAR_RETURN_CONST(LocalStatus, ERR_3);

   return OS_SUCCESS;
}

#define CREATE_STATUS_CODES

//-----------------------------------------------------------------------
// MODIFIABLE                  MODIFIABLE                   MODIFIABLE
//-----------------------------------------------------------------------

extern const char BladeController_emulatorAppGroupName[];
extern const char BladeController_emulatorAppMenuName[];

static void Init_Structures_From_Conf_File(void)
{
   M_BladeControlleremulatorMenuLines[0].LinkName = (char*)BladeController_emulatorAppMenuName;
   M_BladeControlleremulatorMenuLines[0].LinkGroup = (char*)BladeController_emulatorAppGroupName;
}

//-----------------------------------------------------------------------
// AUTOGENERATED END        AUTOGENERATED END        AUTOGENERATED END
//-----------------------------------------------------------------------
//}

#undef AUTOGENERATED_PART
#pragma endregion AUTOGENERATED

//-----------------------------------------------------------------------
// USER DEFINITIONS         USER DEFINITIONS         USER DEFINITIONS
//-----------------------------------------------------------------------

//************************
// Rate limiter struct
//************************
typedef struct
{
    //Inputs
    BOOL Enable;        // If Enable is false then RateLim() will just output input value, else it will return recalculated(limited) input value.
    BOOL Reset;         // All values are initalized
    BOOL TimeMode;      // TRUE - time delay between RateLim() calls can be different and is calculated from system time. "Time_delta" is not checked in this case.
    // FALSE - RateLim() function call period should be constant and delay value for calculations is taken from "Time_delta".
    U32 Time_delta;     // Fixed time step/delay - used when "TimeMode" = FALSE.
    S32 RateUp;         // Maximum rate of increasing signal per defined time base.
    S32 RateDown;       // Maximum rate of decreasing signal per defined time base.
    U32 TimeBase;       // Base time for "RateUp" and "RateDown" rate values.
    S32 Init_value; // Value after Reset

    //Outputs
    S32 Output;         // Current output value (scaled x100)

    //Internal
    S32 max_newOut;
    time_t TimeStamp_prev;

} SRateLimiter;


//************************
// Rate limiter function
//************************
#define SCALE_VALUE 100     // for preserving precision during calculations without using floating point
							// and to keep track of small value changes, that would be otherwise lost when calling function very often

static S32 RateLim( SRateLimiter* pRateLimiter, S32 Input )
{
    S32 _Input = Input * SCALE_VALUE;

    if ( pRateLimiter->Reset )
    {
        pRateLimiter->Reset = 0;
        pRateLimiter->Output = pRateLimiter->Init_value * SCALE_VALUE;
        pRateLimiter->TimeStamp_prev = OS_GetTimeInMs();
    }

    //-----------------------------------------------------------------------
    //Time Step calculation
    S64 time_del;
    time_t TimeStamp;

    if ( pRateLimiter->TimeMode )
    {
        TimeStamp = OS_GetTimeInMs();
        time_del = (S64)(TimeStamp - pRateLimiter->TimeStamp_prev);
        pRateLimiter->TimeStamp_prev = TimeStamp;
    }
    else
    {
        time_del = (S64)pRateLimiter->Time_delta;
    }
    //-----------------------------------------------------------------------

    if (pRateLimiter->Enable)
    {
        if ( pRateLimiter->TimeBase && time_del )
        {
            if ( _Input > pRateLimiter->Output )
            {
                pRateLimiter->max_newOut = pRateLimiter->Output + (S32)((S64)pRateLimiter->RateUp * SCALE_VALUE * time_del / (S64)pRateLimiter->TimeBase);
                if ( _Input > pRateLimiter->max_newOut )
                {
                    pRateLimiter->Output = pRateLimiter->max_newOut;
                }
                else
                {
                    pRateLimiter->Output = _Input;
                }
            }
            else if ( _Input < pRateLimiter->Output )
            {
                pRateLimiter->max_newOut = pRateLimiter->Output - (S32)((S64)pRateLimiter->RateDown * SCALE_VALUE * time_del / (S64)pRateLimiter->TimeBase);
                if ( _Input < pRateLimiter->max_newOut )
                {
                    pRateLimiter->Output = pRateLimiter->max_newOut;
                }
                else
                {
                    pRateLimiter->Output = _Input;
                }
            }
        }
    }
    else
    {
        pRateLimiter->Output = _Input;
    }

    return pRateLimiter->Output / SCALE_VALUE;
}


//************************
// define rate limiters
//************************
static SRateLimiter LimiterPitchAngle1 = { 1, 1, 0, BLADECONTROLLER_SCAN_TIME, 200, 200, 1000, 9000, 0, 0, 0 };
static SRateLimiter LimiterPitchAngle2 = { 1, 1, 0, BLADECONTROLLER_SCAN_TIME, 200, 200, 1000, 9000, 0, 0, 0 };
static SRateLimiter LimiterPitchAngle3 = { 1, 1, 0, BLADECONTROLLER_SCAN_TIME, 200, 200, 1000, 9000, 0, 0, 0 };


//**************************************************************************
// pointers to actual variable values in variable database structures
// pointers are used in this code, to make accessing database variables easier (and faster)
//**************************************************************************

// values as inputs to this module
U8* V_MDSRequestMode_value;
U32* V_PitchSpeedLimit_value;

// values as outputs to this module
U8* V_MDSCurrentMode_value;
U8* V_MDSCurrentState_value;

Hysteresis_UpDown pitchAngleHyst;


//**************************************************************************
//**************************************************************************

//-----------------------------------------------------------------------
// SET/RESET FUNCTIONS    SET/RESET FUNCTIONS    SET/RESET FUNCTIONS
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// Pitch angle diff.
//-----------------------------------------------------------------------
static U8 StatusSetFunc1113(void)
{
    S32 maxAngle = V_MDSActPitchAngleA;
    S32 minAngle = V_MDSActPitchAngleA;
    
    if (V_MDSActPitchAngleB > maxAngle)
    {
        maxAngle = V_MDSActPitchAngleB;
    }
    if (V_MDSActPitchAngleC > maxAngle)
    {
        maxAngle = V_MDSActPitchAngleC;
    }
    
    if (V_MDSActPitchAngleB < minAngle)
    {
        minAngle = V_MDSActPitchAngleB;
    }
    if (V_MDSActPitchAngleC < minAngle)
    {
        minAngle = V_MDSActPitchAngleC;
    }
    
    if ( (maxAngle - minAngle) >= P_BLC_AngleMaxDeviation)
    {
        return 1;
    }
    
    return 0;
}
static U8 StatusResetFunc1113(void)
{
    return !StatusSetFunc1113();
}

//-----------------------------------------------------------------------
// Pitch angle 1
//-----------------------------------------------------------------------
static U8 StatusSetFunc1131(void)
{
    S32 angleDiff = V_MDSActPitchAngleA - V_PitchAngleSetPoint1;
    
    if (angleDiff <= -P_BLC_AngleIndividualDeviation || angleDiff >= P_BLC_AngleIndividualDeviation)
    {
        return 1;
    }
    
    return 0;
}
static U8 StatusResetFunc1131(void)
{
    return !StatusSetFunc1131();
}

//-----------------------------------------------------------------------
// Pitch angle 2
//-----------------------------------------------------------------------
static U8 StatusSetFunc1132(void)
{
    S32 angleDiff = V_MDSActPitchAngleB - V_PitchAngleSetPoint2;
    
    if (angleDiff <= -P_BLC_AngleIndividualDeviation || angleDiff >= P_BLC_AngleIndividualDeviation)
    {
        return 1;
    }
    
    return 0;
}
static U8 StatusResetFunc1132(void)
{
    return !StatusSetFunc1132();
}

//-----------------------------------------------------------------------
// Pitch angle 3
//-----------------------------------------------------------------------
static U8 StatusSetFunc1133(void)
{
    S32 angleDiff = V_MDSActPitchAngleC - V_PitchAngleSetPoint3;
    
    if (angleDiff <= -P_BLC_AngleIndividualDeviation || angleDiff >= P_BLC_AngleIndividualDeviation)
    {
        return 1;
    }
    
    return 0;
}
static U8 StatusResetFunc1133(void)
{
    return !StatusSetFunc1133();
}

//-----------------------------------------------------------------------
// DRIVER FUNCTION         DRIVER FUNCTION         DRIVER FUNCTION
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// INIT                   INIT                     INIT
//-----------------------------------------------------------------------

static void Initialize()
{
    pitchAngleHyst = HystUpDown_New(10/*hysteresis*/, 0/*low_Limit*/, P_PAT_PitchAngleStop/*high_Limit*/);

    // get database variables IDs (pointers to database variable structs) and then
    // assign pointers to direct to the value fields of the variables (for easy direct database value access from application)
    struct os_db_variable* varID;

    // values as inputs to this module
    OS_VarDB_GetVariableID("V_MDSRequestMode", &varID);
    V_MDSRequestMode_value = &(varID->c.Value.u8);
    OS_VarDB_GetVariableID("V_PitchSpeedLimit", &varID);
    V_PitchSpeedLimit_value = &(varID->c.Value.u32);

    // values as outputs to this module
    OS_VarDB_GetVariableID("V_MDSCurrentState", &varID);
    V_MDSCurrentState_value = &(varID->c.Value.u8);
    OS_VarDB_GetVariableID("V_MDSCurrentMode", &varID);
    V_MDSCurrentMode_value = &(varID->c.Value.u8);


    // initialize values
    *V_MDSCurrentMode_value = 0;// MODE_READY
    *V_MDSCurrentState_value = 2;// STATE_RUNNING
}



//-----------------------------------------------------------------------
// CONTROL                CONTROL                 CONTROL
//-----------------------------------------------------------------------

/*U16 LregCollection[MAX_NUMBER_OF_MDS_UNITS][LREG_COLLECTION_SIZE];
OS_QUEUE LregQueue;

STATUS MDS_UpdateRegister(U16 CustomRegister, U16 MDSUnit, U16 Value);
void MDS_SetMode_Operate(void);
void MDS_SetMode_Safety(void);
U32 MDS_GetMDSConnectStatus(U16 MDSUnit);
U8 CommunicationError(void);*/




static STATUS LocalCtrl( U32 Interval )
{
    STATUS LocalStatus = 0;


// simulate blade movement

#ifndef DLL_SIMU_EXTERNALPITCH  // using internal simulation

    if (DLL_IN_Initialize)
    {
        LimiterPitchAngle1.Init_value = P_PAT_PitchAngleStop;
        LimiterPitchAngle1.Reset = 1;
        LimiterPitchAngle2.Init_value = P_PAT_PitchAngleStop;
        LimiterPitchAngle2.Reset = 1;
        LimiterPitchAngle3.Init_value = P_PAT_PitchAngleStop;
        LimiterPitchAngle3.Reset = 1;
        //HystUpDown_Control(pitchAngleHyst, P_PAT_PitchAngleStop);
    }

    switch (*V_MDSCurrentMode_value)
    {
        case MODE_SAFETY:

            // Emergency pitching - 4 deg/s to 90 deg position
            LimiterPitchAngle1.RateUp = 400;
            LimiterPitchAngle1.RateDown = 400;
            V_MDSActPitchAngleA = RateLim(&LimiterPitchAngle1, P_PAT_PitchAngleStop);
            LimiterPitchAngle2.RateUp = 400;
            LimiterPitchAngle2.RateDown = 400;
            V_MDSActPitchAngleB = RateLim(&LimiterPitchAngle2, P_PAT_PitchAngleStop);
            LimiterPitchAngle3.RateUp = 400;
            LimiterPitchAngle3.RateDown = 400;
            V_MDSActPitchAngleC = RateLim(&LimiterPitchAngle3, P_PAT_PitchAngleStop);
            
            V_PitchAngle = (V_MDSActPitchAngleA + V_MDSActPitchAngleB + V_MDSActPitchAngleC) / 3;
            break;

        default:

            // Pitch angle feedback simulation, dynamics according to pitch speed limit value
            LimiterPitchAngle1.RateUp = *V_PitchSpeedLimit_value;
            LimiterPitchAngle1.RateDown = *V_PitchSpeedLimit_value;
            V_MDSActPitchAngleA = RateLim(&LimiterPitchAngle1, V_PitchAngleSetPoint1);
            LimiterPitchAngle2.RateUp = *V_PitchSpeedLimit_value;
            LimiterPitchAngle2.RateDown = *V_PitchSpeedLimit_value;
            V_MDSActPitchAngleB = RateLim(&LimiterPitchAngle2, V_PitchAngleSetPoint2);
            LimiterPitchAngle3.RateUp = *V_PitchSpeedLimit_value;
            LimiterPitchAngle3.RateDown = *V_PitchSpeedLimit_value;
            V_MDSActPitchAngleC = RateLim(&LimiterPitchAngle3, V_PitchAngleSetPoint3);
            
            V_PitchAngle = (V_MDSActPitchAngleA + V_MDSActPitchAngleB + V_MDSActPitchAngleC) / 3;
            break;
    }
    
#else   // using external simulation

    V_PitchAngle = (DLL_IN_PitchAngle_1 + DLL_IN_PitchAngle_2 + DLL_IN_PitchAngle_3) / 3 * 100;
    
    V_MDSActPitchAngleA = DLL_IN_PitchAngle_1 * 100;
    V_MDSActPitchAngleB = DLL_IN_PitchAngle_2 * 100;
    V_MDSActPitchAngleC = DLL_IN_PitchAngle_3 * 100;
    
#endif


    *V_MDSCurrentMode_value = *V_MDSRequestMode_value;

    return LocalStatus;
}

static STATUS ShutdownCtrl( U8 ModuleState, U8* DoneState, U32 Interval )
{
    STATUS LocalStatus = 0;

    LocalStatus = LocalCtrl( Interval );
    STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);

    switch ( ModuleState )
    {
        case AS_SHUTDOWN:
        {
            // Activate "Manual Shutdown" status code

            *DoneState = AS_SHUTDOWN;
            break;
        }
        case AS_REBOOT:
        {

            *DoneState = AS_REBOOT;
            break;
        }
        case AS_SHUTDOWN_FAST:
        {

            *DoneState = AS_SHUTDOWN_FAST;
            break;
        }
        default:
        {
            *DoneState = ModuleState;
            break;
        }
    }
    return LocalStatus;
}

//-----------------------------------------------------------------------
// MAIN CALL             MAIN CALL               MAIN CALL
//-----------------------------------------------------------------------

STATUS BladeController_emulator( U8 ModuleState, U8* DoneState , U32 Interval )
{
    STATUS LocalStatus = 0;

#ifdef READ_VARS
    // Read input data
    LocalStatus = InputReferenceRoutine(ModuleState);
    STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
#endif
#ifdef COMMON_VDB_READ
    LocalStatus = ReadVdbWindow(ModuleState);
    STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
#endif


    switch ( ModuleState )
    {
            //__________________________________________________________________________
        case APP_RUN:
        {
#ifdef FUNCTION_BLOCKS_PRE_LOCAL_CONTROL
            LocalStatus = FunctionBlocksPreLocalCtrl( Interval );
            STATUS_LINE_VAR_RETURN_VALUE( LocalStatus );
#endif

            LocalStatus = LocalCtrl( Interval );
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);

#ifdef FUNCTION_BLOCKS_POST_LOCAL_CONTROL
            LocalStatus = FunctionBlocksPostLocalCtrl( Interval );
            STATUS_LINE_VAR_RETURN_VALUE( LocalStatus );
#endif

#ifdef WRITE_VARS
            // Write Output data
            LocalStatus = OutputReferenceRoutine(ModuleState);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
#endif

#ifdef COMMON_VDB_WRITE
            LocalStatus = WriteVdbWindow(ModuleState);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
#endif

            *DoneState = APP_RUN;
            break;
        }
        //__________________________________________________________________________
        case APP_INIT1:
        {
            // Version check
            LocalStatus = OS_ValidateAPI( API_VERSION_MAJOR,
                                          API_VERSION_MINOR,
                                          OS_LinkTime,
                                          ReleaseTag,
                                          __MODULE__
                                        );
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);

            Init_Structures_From_Conf_File();

#ifdef CREATE_VARDB_VARS
            LocalStatus = CreateVarDbVars();
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
#endif

#ifdef CREATE_MENU
            LocalStatus = BladeController_emulatorMenuAppInit(ModuleState, GetMemPool());
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);

#ifdef MULTIPLEXIBLE_MENU
            LocalStatus = MenuArraysAppInit(ModuleState, GetMemPool());
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
#endif
#endif

#ifdef CREATE_VARDB_ARRAY_VARS
            LocalStatus = CreateVdbArrays(GetMemPool());
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif


#ifdef CREATE_IO_VARS
            LocalStatus = CreateIOVars();
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif

            *DoneState = APP_INIT1;

            break;
        }
        //__________________________________________________________________________
        case APP_INIT2:
        {
#ifdef CREATE_MENU
#ifdef MULTIPLEXIBLE_MENU
            LocalStatus = MenuArraysAppInit(ModuleState, GetMemPool());
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
#endif
#endif

#ifdef CREATE_ALIASES
            size_t ErrorEntry = 0;
            LocalStatus = OS_VarDB_CreateAliases(AliasVars, sizeof(AliasVars)/sizeof(AliasVars[0]), &ErrorEntry);
            OS_com_printf("\n\n+++DEBUG+++ Finished creating Aliases STATUS: %d\n\n", LocalStatus);
            STATUS_LINE_VAR_RETURN_CONST(LocalStatus, ErrorEntry);
#endif

#ifdef VERIFY_ARRAY
            LocalStatus = VerifyArray(GetMemPool());
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
#endif

#ifdef VERIFY_VARIABLES
            LocalStatus = LocalIoCheck();
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
#endif

#ifdef CREATE_BUTTONS
            LocalStatus = CreateButtons();
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
#endif

            *DoneState = APP_INIT2;

            break;
        }
        //__________________________________________________________________________
        case APP_INIT3 :
        {
#ifdef CREATE_SUMMATIONS
            LocalStatus = CreateSummations();
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
#endif

#ifdef WRITE_VARS
            LocalStatus = InitOutputVars();
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
#endif

#ifdef CREATE_STATUS_CODES
            LocalStatus = LocalStatusCodeInit();
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
#endif

#ifdef CREATE_IO_VARS
            BladeController_emulatorSetLockValues();
#endif

            *DoneState = APP_INIT3;

            break;
        }
        //__________________________________________________________________________
        case APP_INIT4:
        {
#ifdef CREATE_MENU
            LocalStatus = BladeController_emulatorMenuAppInit(ModuleState, GetMemPool());
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);

#ifdef MULTIPLEXIBLE_MENU
            LocalStatus = MenuArraysAppInit(ModuleState, GetMemPool());
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
#endif
#endif

            *DoneState = APP_INIT4;

            break;
        }
        //__________________________________________________________________________
        case APP_INIT5:
        {
#ifdef VALIDATE_HASH
            LocalStatus = ValidateHash( BladeController_emulator_copyright, MODULE_NAME, BladeController_emulator_initialValues);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
#endif

#ifdef INIT_FUNCTION_BLOCKS
            LocalStatus = FunctionBlocksInit( Interval );
            STATUS_LINE_VAR_RETURN_VALUE( LocalStatus );
#endif


            Initialize();

            *DoneState = APP_INIT5_DONE;

            break;
        }
        //__________________________________________________________________________
        //Other initialization round can be inserted here
        //__________________________________________________________________________
        case AS_SHUTDOWN:
        {
            LocalStatus = ShutdownCtrl ( ModuleState, DoneState, Interval );
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);

#ifdef WRITE_VARS
            // Write Output data
            LocalStatus = OutputReferenceRoutine(ModuleState);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
#endif

#ifdef COMMON_VDB_WRITE
            LocalStatus = WriteVdbWindow(ModuleState);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
#endif

            break;
        }
        //__________________________________________________________________________
        case AS_REBOOT:
        {
            LocalStatus = ShutdownCtrl ( ModuleState, DoneState, Interval );
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);

#ifdef WRITE_VARS
            // Write Output data
            LocalStatus = OutputReferenceRoutine(ModuleState);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
#endif

#ifdef COMMON_VDB_WRITE
            LocalStatus = WriteVdbWindow(ModuleState);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
#endif

            break;
        }
        //__________________________________________________________________________
        case AS_SHUTDOWN_FAST:
        {
            LocalStatus = ShutdownCtrl ( ModuleState, DoneState, Interval );
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);

#ifdef WRITE_VARS
            // Write Output data
            LocalStatus = OutputReferenceRoutine(ModuleState);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
#endif

#ifdef COMMON_VDB_WRITE
            LocalStatus = WriteVdbWindow(ModuleState);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
#endif

            break;
        }
        default:
        {
            *DoneState = ModuleState;

            break;
        }
    }
    return OS_SUCCESS;
}
//-----------------------------------------------------------------------
