//*****************************PEPTOOL Header Start******************************
//                                                                               
//                         Copyright © 2015 Mita-Teknik.                         
//This software may only be used with WP4x00 Controllers delivered by Mita-Teknik
//                                                                               
//*******************************************************************************
//                                                                               
// $PEPTOOL version:9.0$                                                         
// $PEPTOOL file version:101$                                                    
//                                                                               
//*******************************************************************************
//                                                                               
// $Date: 2014/04/08 07:06:09 $                                                  
// $Author: MITA\ihn $                                                           
// $RCSfile: Brake_Conf.c,v $                                                    
// $Revision: 1.10 $                                                             
//                                                                               
//******************************PEPTOOL Header End*******************************

//***********************************************************************
// OS header files
#include <os_main.h>
// IO init file
#include <InitIo.h>
      
#define AUTOGENERATED_PART

#include <Turbdef.h>

//-----------------------------------------------------------------------
// AUTOGENERATED START     AUTOGENERATED START     AUTOGENERATED START
//-----------------------------------------------------------------------
char Brake_Conf_copyright[] =
{
   67, 111, 112, 121, 114, 105, 103, 104, 116, 32, 63, 32, 50, 48, 49, 53,
   32, 77, 105, 116, 97, 45, 84, 101, 107, 110, 105, 107, 46, 13, 10, 84,
   104, 105, 115, 32, 115, 111, 102, 116, 119, 97, 114, 101, 32, 109, 97, 121,
   32, 111, 110, 108, 121, 32, 98, 101, 32, 117, 115, 101, 100, 32, 119, 105,
   116, 104, 32, 87, 80, 52, 120, 48, 48, 32, 67, 111, 110, 116, 114, 111,
   108, 108, 101, 114, 115, 32, 100, 101, 108, 105, 118, 101, 114, 101, 100, 32,
   98, 121, 32, 77, 105, 116, 97, 45, 84, 101, 107, 110, 105, 107, 0
};
//-----------------------------------------------------------------------
// MODIFIABLE                  MODIFIABLE               MODIFIABLE
//-----------------------------------------------------------------------
const char BrakeAppGroupName[] = "G_"APP_ID"App";
const char BrakeAppMenuName[] = "M_"APP_ID"AppMain";

//-----------------------------------------------------------------------
// IO VARIABLES                IO VARIABLES                IO VARIABLES
//-----------------------------------------------------------------------

void (*BrakeSetLockValues)(void);
struct os_db_alias *BrakeIOVars;
size_t BrakeIOVarsSize = 0;
            
struct os_db_alias BrakeIOVars1[]=
{
    VAR_ELEMENT_ALIAS("3.3.15",                           "DO_RotorBrake"),

    VAR_ELEMENT_ALIAS("3.3.16",                           "DO_RotorBrake2"),

    VAR_ELEMENT_ALIAS("3.3.10",                           "DO_BRK_HydPump"),

    VAR_ELEMENT_ALIAS("3.2.47",                           "DI_HydrOilPump_MCBFeedback"),
    VAR_ELEMENT_ALIAS("3.2.47_Ss",                        "DI_HydrOilPump_MCBFeedback_Ss"),
    VAR_ELEMENT_ALIAS("3.2.47_E",                         "DI_HydrOilPump_MCBFeedback_E"),
    VAR_ELEMENT_ALIAS("3.2.47_I",                         "DI_HydrOilPump_MCBFeedback_I"),
    VAR_ELEMENT_ALIAS("3.2.47_Cm",                        "DI_HydrOilPump_MCBFeedback_Cm"),
    VAR_ELEMENT_ALIAS("3.2.47_Ht",                        "DI_HydrOilPump_MCBFeedback_Ht"),

    VAR_ELEMENT_ALIAS("3.3.63",                           "AI_Hydraulic_PressureMa"),
    VAR_ELEMENT_ALIAS("3.3.63_Ss",                        "AI_Hydraulic_PressureMa_Ss"),
    VAR_ELEMENT_ALIAS("3.3.63_E",                         "AI_Hydraulic_PressureMa_E"),
    VAR_ELEMENT_ALIAS( "3.3.63_Th",                        "AI_Hydraulic_PressureMa_Th"),
    VAR_ELEMENT_ALIAS("3.3.63_Ht",                        "AI_Hydraulic_PressureMa_Ht"),
    VAR_ELEMENT_ALIAS("3.3.63_S",                         "AI_Hydraulic_PressureMa_S"),
    VAR_ELEMENT_ALIAS("3.3.63_O",                         "AI_Hydraulic_PressureMa_O"),

};
size_t BrakeIOVars1Size = sizeof(BrakeIOVars1)/sizeof(BrakeIOVars1[0]);

void BrakeSetLockValues1(void)
{
   SetLockValue("DI_HydrOilPump_MCBFeedback_Ss",         TYP_8,     1);
   SetLockValue("DI_HydrOilPump_MCBFeedback_E",          TYP_8,     1);
   SetValue("DI_HydrOilPump_MCBFeedback_I",              TYP_8,     0);
   SetLockValue("DI_HydrOilPump_MCBFeedback_Cm",         TYP_8,     1);
   SetLockValue("DI_HydrOilPump_MCBFeedback_Ht",         TYP_32,    20);

   SetLockValue("AI_Hydraulic_PressureMa_Ss",            TYP_8,     1);
   SetLockValue("AI_Hydraulic_PressureMa_E",             TYP_8,     1);
   SetLockValue("AI_Hydraulic_PressureMa_Th",            TYP_16,    50);
   SetLockValue("AI_Hydraulic_PressureMa_Ht",            TYP_32,    20);
   SetLockValue("AI_Hydraulic_PressureMa_S",             TYP_32,    0);
   SetValue("AI_Hydraulic_PressureMa_O",                 TYP_32,    0);
}


STATUS BrakeInitIOAliases()
{
   BrakeIOVars = BrakeIOVars1;
   BrakeIOVarsSize = BrakeIOVars1Size;
   BrakeSetLockValues = &BrakeSetLockValues1;
   return OS_SUCCESS;
}
//-----------------------------------------------------------------------
// AUTOGENERATED END        AUTOGENERATED END        AUTOGENERATED END
//-----------------------------------------------------------------------

#undef AUTOGENERATED_PART
