//*****************************PEPTOOL Header Start******************************
//                                                                               
//                         Copyright © 2015 Mita-Teknik.                         
//This software may only be used with WP4x00 Controllers delivered by Mita-Teknik
//                                                                               
//*******************************************************************************
//                                                                               
// $PEPTOOL version:9.0$                                                         
// $PEPTOOL file version:106$                                                    
//                                                                               
//*******************************************************************************
//                                                                               
// $Date: 2014/03/04 13:22:50 $                                                  
// $Author: MITA\ihn $                                                           
// $RCSfile: CMS.c,v $                                                           
// $Revision: 1.5 $                                                              
//                                                                               
//******************************PEPTOOL Header End*******************************

//***********************************************************************
// OS header files
#include <os_main.h>
// AppLib header files
#include <lib_main.h>
// App header files
#include <turbdef.h>
#include <VarMacros.h>
// Object header file
#include <CMS.h>

#define AUTOGENERATED_PART
//{
//-----------------------------------------------------------------------
// AUTOGENERATED START     AUTOGENERATED START     AUTOGENERATED START
//-----------------------------------------------------------------------

#define VALIDATE_HASH
char CMS_copyright[] =
{
   67, 111, 112, 121, 114, 105, 103, 104, 116, 32, 63, 32, 50, 48, 49, 53,
   32, 77, 105, 116, 97, 45, 84, 101, 107, 110, 105, 107, 46, 13, 10, 84,
   104, 105, 115, 32, 115, 111, 102, 116, 119, 97, 114, 101, 32, 109, 97, 121,
   32, 111, 110, 108, 121, 32, 98, 101, 32, 117, 115, 101, 100, 32, 119, 105,
   116, 104, 32, 87, 80, 52, 120, 48, 48, 32, 67, 111, 110, 116, 114, 111,
   108, 108, 101, 114, 115, 32, 100, 101, 108, 105, 118, 101, 114, 101, 100, 32,
   98, 121, 32, 77, 105, 116, 97, 45, 84, 101, 107, 110, 105, 107, 0
};

#define MODULE_NAME "CMSA"

//-----------------------------------------------------------------------
// ALLOCATE MEMORY FOR STRINGS IN VARDB
//-----------------------------------------------------------------------


//-----------------------------------------------------------------------
// DEFINE LOCAL VARIABLES DEFINE LOCAL VARIABLES DEFINE LOCAL VARIABLES
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// DEFINE PARAMETERS        DEFINE PARAMETERS        DEFINE PARAMETERS
//-----------------------------------------------------------------------

static struct os_db_parameter ParameterVars[] =
{
   VAR_ELEMENT_PARAMETER("P_CMSPitchAngleMin",                       TYPE_S32,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_DIV,    100,     UNIT_DEGREE,        1,   0,               -500,            500,             NULL  ),
   VAR_ELEMENT_PARAMETER("P_CMSPitchAngleMax",                       TYPE_S32,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_DIV,    100,     UNIT_DEGREE,        1,   9000,            0,               9500,            NULL  ),
   VAR_ELEMENT_PARAMETER("P_CMSPitchAngleMinCurrent",                TYPE_S32,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_DIV,    1000,    UNIT_MAMPERE,       3,   4000,            0,               6000,            NULL  ),
   VAR_ELEMENT_PARAMETER("P_CMSPitchAngleMaxCurrent",                TYPE_S32,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_DIV,    1000,    UNIT_MAMPERE,       3,   20000,           18000,           22000,           NULL  ),
   VAR_ELEMENT_PARAMETER("P_CMSRotorRpmMin",                         TYPE_S32,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_DIV,    100,     UNIT_RPM,           1,   0,               0,               5000,            NULL  ),
   VAR_ELEMENT_PARAMETER("P_CMSRotorRpmMax",                         TYPE_S32,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_DIV,    100,     UNIT_RPM,           1,   3000,            0,               5000,            NULL  ),
   VAR_ELEMENT_PARAMETER("P_CMSRotorRpmMinCurrent",                  TYPE_S32,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_DIV,    1000,    UNIT_MAMPERE,       3,   4000,            0,               6000,            NULL  ),
   VAR_ELEMENT_PARAMETER("P_CMSRotorRpmMaxCurrent",                  TYPE_S32,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_DIV,    1000,    UNIT_MAMPERE,       3,   20000,           18000,           20000,           NULL  ),
   VAR_ELEMENT_PARAMETER("P_CMSPowerMin",                            TYPE_S32,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_DIV,    1000,    UNIT_KWATT,         1,   0,               -100000,         5000000,         NULL  ),
   VAR_ELEMENT_PARAMETER("P_CMSPowerMax",                            TYPE_S32,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_DIV,    1000,    UNIT_KWATT,         1,   3000000,         -100000,         5000000,         NULL  ),
   VAR_ELEMENT_PARAMETER("P_CMSPowerMinCurrent",                     TYPE_S32,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_DIV,    1000,    UNIT_MAMPERE,       3,   0,               0,               6000,            NULL  ),
   VAR_ELEMENT_PARAMETER("P_CMSPowerMaxCurrent",                     TYPE_S32,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_DIV,    1000,    UNIT_MAMPERE,       3,   20000,           18000,           22000,           NULL  ),
   VAR_ELEMENT_PARAMETER("P_CMSYawAngleMin",                         TYPE_S32,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_DIV,    10,      UNIT_DEGREE,        0,   0,               0,               3599,            NULL  ),
   VAR_ELEMENT_PARAMETER("P_CMSYawAngleMax",                         TYPE_S32,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_DIV,    10,      UNIT_DEGREE,        0,   3599,            0,               3599,            NULL  ),
   VAR_ELEMENT_PARAMETER("P_CMSYawAngleMinCurrent",                  TYPE_S32,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_DIV,    1000,    UNIT_MAMPERE,       3,   0,               0,               6000,            NULL  ),
   VAR_ELEMENT_PARAMETER("P_CMSYawAngleMaxCurrent",                  TYPE_S32,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_DIV,    1000,    UNIT_MAMPERE,       3,   20000,           18000,           22000,           NULL  ),
};

//-----------------------------------------------------------------------
// DEFINE BACKUPS            DEFINE BACKUPS            DEFINE BACKUPS
//-----------------------------------------------------------------------

//----------------------------------------------------------------------------------
// DEFINE VAR ARRAYS            DEFINE VAR ARRAYS            DEFINE VAR ARRAYS
//----------------------------------------------------------------------------------
char CMS_initialValues[] =
{
   225, 37, 34, 160, 153, 139, 224, 74, 5, 123, 157, 33, 78, 98, 188, 204,
   117, 222, 146, 230, 233, 252, 136, 99, 132, 161, 104, 208, 186, 98, 168, 128,
   0
};

//-----------------------------------------------------------------------
// CREATE DATABASE VARS   CREATE DATABASE VARS   CREATE DATABASE VARS
//-----------------------------------------------------------------------

static STATUS CreateVarDbVars(void)
{
   STATUS Status;
   size_t ErrorEntry;

   Status = OS_VarDB_CreateParameters(ParameterVars, sizeof(ParameterVars)/sizeof(ParameterVars[0]), &ErrorEntry, AppExportParameterPosition());
   if (Status != 0)
   {
      AppSystemLog(ERR_7, MODULE_NAME"CrVXP: %d,%d", Status, ErrorEntry);
      return ERR_7;
   }

   return OS_SUCCESS;
}

#define CREATE_VARDB_VARS

//-----------------------------------------------------------------------
// CREATE IO VARIABLES     CREATE IO VARIABLES     CREATE IO VARIABLES
//-----------------------------------------------------------------------

extern STATUS CMSInitIOAliases();
extern struct os_db_alias* CMSIOVars;
extern void (*CMSSetLockValues)(void);
extern size_t CMSIOVarsSize;

static STATUS CreateIOVars(void)
{
   STATUS Status;
   size_t ErrorEntry;

   varid_t VarId;
   BOOL variablesExist = false;
   U8 counter = 50;
   Status = CMSInitIOAliases();
   STATUS_LINE_VAR_RETURN_VALUE(Status)
   while (!variablesExist && counter-- > 0)
   {
      variablesExist = true;
      U32 i = 0;
      for (i = 0; i < CMSIOVarsSize; ++i)
      {
         if (OS_VarDB_GetVariableID(CMSIOVars[i].Name, &VarId) != OS_SUCCESS)
         {
            variablesExist = false;
            break;
         }
      }

      if (!variablesExist)
      {
         OS_Sleep(100);
      }
   }

   Status = OS_VarDB_CreateAliases(CMSIOVars, CMSIOVarsSize, &ErrorEntry);
   if (Status)
   {
      AppDebugLog(5000, "Var Name = %s", CMSIOVars[ErrorEntry].Alias);
   }
   STATUS_LINE_VAR_RETURN_CONST(Status, ErrorEntry);
   return OS_SUCCESS;
}

#define CREATE_IO_VARS

//-----------------------------------------------------------------------
// ALIASES                       ALIASES                       ALIASES
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// INPUT                          INPUT                          INPUT
//-----------------------------------------------------------------------

// Create local variable
#define MODUL_INPUTS
static S32 V_PitchAngle = 0;
static U32 V_GEN_EncoderRpm = 0;
static S32 V_GridRealPower = 0;
static U16 V_NacelleDirection = 0;

//-----------------------------------------------------------------------
static struct ModulInOut ModulInputs[] =
{
   {"V_PitchAngle",                             &V_PitchAngle,                             sizeof(V_PitchAngle),                             },
   {"V_GEN_EncoderRpm",                         &V_GEN_EncoderRpm,                         sizeof(V_GEN_EncoderRpm),                         },
   {"V_GridRealPower",                          &V_GridRealPower,                          sizeof(V_GridRealPower),                          },
   {"V_NacelleDirection",                       &V_NacelleDirection,                       sizeof(V_NacelleDirection),                       },
};

//-----------------------------------------------------------------------
// Check variable type
static STATUS VarsReadReturnStatus;
static type_t ReadVarType = TYPE_NONE;
static void VarsReadTypeCheck(void)
{
   (void)VarsReadReturnStatus;
   (void)ReadVarType;
   VERIFY_INPUT_REF_ID(S32,       ModulInputs[0].Name,                      ModulInputs[0].Id)
   VERIFY_INPUT_REF_ID(U32,       ModulInputs[1].Name,                      ModulInputs[1].Id)
   VERIFY_INPUT_REF_ID(S32,       ModulInputs[2].Name,                      ModulInputs[2].Id)
   VERIFY_INPUT_REF_ID(U16,       ModulInputs[3].Name,                      ModulInputs[3].Id)
}

#undef MODUL_INPUTS
#define MODUL_INPUTS_SIZE (sizeof(ModulInputs)/sizeof(ModulInputs[0]))

//------------------------------------------------------------------------------------------
// READ/WRITE VARDB ARRAY      READ/WRITE VARDB ARRAY      READ/WRATE VARDB ARRAY
//------------------------------------------------------------------------------------------


//-----------------------------------------------------------------------
// PARAMETER                    PARAMETER                    PARAMETER
//-----------------------------------------------------------------------


//-----------------------------------------------------------------------
// READ VARS FROM VARDB    READ VARS FROM VARDB    READ VARS FROM VARDB
//-----------------------------------------------------------------------

static STATUS InputReferenceRoutine(U8 ModuleState)
{
   STATUS LocalStatus = 0;

   // Read input references
   if (ModuleState >= APP_INIT3)
   {
      // Check inputdata
      if (sizeof(ModulInputs) == 0)
      {
         AppSystemLog(ERR_4, MODULE_NAME"ModuleInputs = 0");
         return ERR_4;
      }
      // Read inputdata
      LocalStatus = OS_ReadVariables(ModulInputs, MODUL_INPUTS_SIZE);
      if (LocalStatus != 0)
      {
         AppSystemLog(ERR_4, MODULE_NAME"ReadVErr: element=%d elementpointer=0x%x", LocalStatus, &ModulInputs[LocalStatus]);
         return ERR_4;
      }
   }
   return 0;
}

#define READ_VARS

//-----------------------------------------------------------------------
// OUTPUT                         OUTPUT                         OUTPUT
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// WRITE VARS TO VARDB     WRITE VARS TO VARDB     WRITE VARS TO VARDB
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// VERIFY VARIABLES CREATION                 VERIFY VARIABLES CREATION
//-----------------------------------------------------------------------

static STATUS LocalIoCheck(void)
{
   // Check if input variables exist.
   STATUS LocalStatus;

   LocalStatus = OS_DoesVariablesExist(ModulInputs, MODUL_INPUTS_SIZE);
   if (LocalStatus != 0)
   {
      AppSystemLog(ERR_1, MODULE_NAME"InputErr: %d", LocalStatus);
      AppSystemLog(ERR_1, "Name: %s", ModulInputs[LocalStatus-1].Name);
      return ERR_1;
   }
   (void)VarsReadTypeCheck();

   return OS_SUCCESS;
}

#define VERIFY_VARIABLES

//-----------------------------------------------------------------------
// ALLOCATE MEMORY FOR SUMMATIONS        ALLOCATE MEMORY FOR SUMMATIONS
//-----------------------------------------------------------------------


//-----------------------------------------------------------------------
// SUMMATIONS                  SUMMATIONS                  SUMMATIONS
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// DEFINE MENUS               DEFINE MENUS               DEFINE MENUS
//-----------------------------------------------------------------------



// Menu line and link to local menu
//-----------------------------------------------------------------------
static struct line_struct M_CMSLinkToLocalMenu[] =
{
   MENU_ELEMENT_LINE_LINK("CMS",                               PASSWORD_LEVEL_LICENCE_CUSTOMER,    "M_CMS",                            "G_CMS"),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_CMSMenu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_CMS",                            PASSWORD_LEVEL_LICENCE_CUSTOMER),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_CMSMenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("CMS",                               PASSWORD_LEVEL_LICENCE_CUSTOMER,    "M_"APP_ID"AppMain",                "G_"APP_ID"App"),
   MENU_ELEMENT_LINE_LINK("Status",                            PASSWORD_LEVEL_END_CUSTOMER,        "M_Status11",                       "G_CMS"),
   MENU_ELEMENT_LINE_LINK("Parameter",                         PASSWORD_LEVEL_END_CUSTOMER,        "M_Parameter29",                    "G_CMS"),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_Status11Menu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_Status11",                       PASSWORD_LEVEL_END_CUSTOMER),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_Status11MenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("STATUS",                            PASSWORD_LEVEL_END_CUSTOMER,        "M_CMS",                            "G_CMS"),
   MENU_ELEMENT_LINE_VARRO("Pitch Angle",                      PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_PitchAngle",                               LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("CMS: Pitch Angle",                 PASSWORD_LEVEL_END_CUSTOMER,        (char*)"AO_CMSActualPitchAngle",                     LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Rotor Speed",                      PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_GEN_EncoderRpm",                           LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("CMS: Rotor Speed",                 PASSWORD_LEVEL_END_CUSTOMER,        (char*)"AO_CMSRotorRpm",                             LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Actual Power",                     PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_GridRealPower",                            LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("CMS: Actual Power",                PASSWORD_LEVEL_END_CUSTOMER,        (char*)"AO_CMSActualPower",                          LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Nacelle Position",                 PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_NacelleDirection",                         LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("CMS: Nacelle Position",            PASSWORD_LEVEL_END_CUSTOMER,        (char*)"AO_CMSYawAngle",                             LINE_FORMAT_NONE),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_Parameter29Menu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_Parameter29",                    PASSWORD_LEVEL_END_CUSTOMER),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_Parameter29MenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("PARAMETER",                         PASSWORD_LEVEL_END_CUSTOMER,        "M_CMS",                            "G_CMS"),
   MENU_ELEMENT_LINE_VARRW("CMS Pitch Angle Min",              PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_CMSPitchAngleMin",                         LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("CMS Pitch Angle Max",              PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_CMSPitchAngleMax",                         LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("CMS Pitch Angle Min Current",      PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_CMSPitchAngleMinCurrent",                  LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("CMS Pitch Angle Max Current",      PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_CMSPitchAngleMaxCurrent",                  LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("CMS Rotor Speed Min",              PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_CMSRotorRpmMin",                           LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("CMS Rotor Speed Max",              PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_CMSRotorRpmMax",                           LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("CMS Rotor Speed Min Current",      PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_CMSRotorRpmMinCurrent",                    LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("CMS Rotor Speed Max Current",      PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_CMSRotorRpmMaxCurrent",                    LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("CMS Actual Power Min",             PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_CMSPowerMin",                              LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("CMS Actual Power Max",             PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_CMSPowerMax",                              LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("CMS Actual Power Min Current",     PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_CMSPowerMinCurrent",                       LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("CMS Actual Power Max Current",     PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_CMSPowerMaxCurrent",                       LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("CMS Nacelle Position Min",         PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_CMSYawAngleMin",                           LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("CMS Nacelle Position Max",         PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_CMSYawAngleMax",                           LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("CMS Nacelle Position Min Current", PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_CMSYawAngleMinCurrent",                    LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("CMS Nacelle Position Max Current", PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_CMSYawAngleMaxCurrent",                    LINE_FORMAT_NONE),
};
// Creating parameters for multiplexed categories
//-----------------------------------------------------------------------
static struct multiplexed_info_struct M_CMSMultiplexedCategoriesParameters[] =
{
0};

//-----------------------------------------------------------------------
// CREATE MENUS               CREATE MENUS               CREATE MENUS
//-----------------------------------------------------------------------

// Memory reservation
//-----------------------------------------------------------------------
static struct menu_group_struct ObjGroup[1];

// Creating the menus
//-----------------------------------------------------------------------
STATUS CMSMenuAppInit(U8 ModuleState, OS_MEMORY_POOL* pPool)
{
   STATUS Status;

   if (ModuleState == APP_INIT1)
   {
      /* Create application group */
      Status = OS_CreateMenuGroup(ObjGroup, M_CMSLinkToLocalMenu[0].LinkGroup);
      STATUS_LINE_VAR_RETURN_VALUE(Status);
   }

   Status = CreateAndInitializeMenu(ModuleState,
                                    M_CMSMenuLines[0].LinkGroup,
                                    M_CMSMenuLines[0].LinkName,
                                    ELEMENT(M_CMSLinkToLocalMenu),
                                    M_CMSLinkToLocalMenu[0].LinkGroup,
                                    ELEMENT(M_CMSMenu),
                                    M_CMSLinkToLocalMenu[0].LinkName,
                                    ELEMENT(M_CMSMenuLines),
                                    pPool,
                                    M_CMSMultiplexedCategoriesParameters);
   STATUS_LINE_VAR_RETURN_VALUE(Status);

   Status = CreateAndInitializeMenu(ModuleState,
                                    M_Status11MenuLines[0].LinkGroup,
                                    M_Status11MenuLines[0].LinkName,
                                    NULL,
                                    0,
                                    M_CMSMenuLines[1].LinkGroup,
                                    ELEMENT(M_Status11Menu),
                                    M_CMSMenuLines[1].LinkName,
                                    ELEMENT(M_Status11MenuLines),
                                    pPool,
                                    M_CMSMultiplexedCategoriesParameters);
   STATUS_LINE_VAR_RETURN_VALUE(Status);

   Status = CreateAndInitializeMenu(ModuleState,
                                    M_Parameter29MenuLines[0].LinkGroup,
                                    M_Parameter29MenuLines[0].LinkName,
                                    NULL,
                                    0,
                                    M_CMSMenuLines[2].LinkGroup,
                                    ELEMENT(M_Parameter29Menu),
                                    M_CMSMenuLines[2].LinkName,
                                    ELEMENT(M_Parameter29MenuLines),
                                    pPool,
                                    M_CMSMultiplexedCategoriesParameters);
   STATUS_LINE_VAR_RETURN_VALUE(Status);

   return OS_SUCCESS;
}

#define CREATE_MENU

//-----------------------------------------------------------------------
//               BUTTONS FUNCTIONS FORWARD DECLARATIONS
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// BUTTONS                       BUTTONS                      BUTTONS
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
//             SET/RESET FUNCTIONS FORWARD DECLARATIONS
//-----------------------------------------------------------------------
//-----------------------------------------------------------------------
// STATUSCODES                 STATUSCODES                 STATUSCODES
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// MODIFIABLE                  MODIFIABLE                   MODIFIABLE
//-----------------------------------------------------------------------

extern const char CMSAppGroupName[];
extern const char CMSAppMenuName[];

static void Init_Structures_From_Conf_File(void)
{
   M_CMSMenuLines[0].LinkName = (char*)CMSAppMenuName;
   M_CMSMenuLines[0].LinkGroup = (char*)CMSAppGroupName;
}

//-----------------------------------------------------------------------
// AUTOGENERATED END        AUTOGENERATED END        AUTOGENERATED END
//-----------------------------------------------------------------------
//}

#undef AUTOGENERATED_PART

//-----------------------------------------------------------------------
// USER DEFINITIONS         USER DEFINITIONS         USER DEFINITIONS
//-----------------------------------------------------------------------

 
 
//-----------------------------------------------------------------------
// SET/RESET FUNCTIONS    SET/RESET FUNCTIONS    SET/RESET FUNCTIONS
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// DRIVER FUNCTION         DRIVER FUNCTION         DRIVER FUNCTION
//-----------------------------------------------------------------------

STATUS InOutCMS_PitchAngleToCurrentDrv(U16 Counter, struct IoDriverStruct *IoDriverTable)
{
   return InOutLinearScale_Drv_t1_v1(Counter,IoDriverTable);
}

STATUS InOutCMS_RotorRpmToCurrentDrv(U16 Counter, struct IoDriverStruct *IoDriverTable)
{
	return InOutLinearScale_Drv_t1_v1(Counter,IoDriverTable);
}

STATUS InOutCMS_PowerToCurrentDrv(U16 Counter, struct IoDriverStruct *IoDriverTable)
{
	return InOutLinearScale_Drv_t1_v1(Counter,IoDriverTable);
}

STATUS InOutCMS_YawAngleToCurrentDrv(U16 Counter, struct IoDriverStruct *IoDriverTable)
{
	return InOutLinearScale_Drv_t1_v1(Counter,IoDriverTable);
}

//-----------------------------------------------------------------------
// INIT                   INIT                     INIT
//-----------------------------------------------------------------------
  
//-----------------------------------------------------------------------
// CONTROL                CONTROL                 CONTROL
//-----------------------------------------------------------------------
  
static STATUS LocalCtrl(void)
{
   STATUS LocalStatus = 0;

   return LocalStatus;
}
  
//-----------------------------------------------------------------------
// MAIN CALL             MAIN CALL               MAIN CALL
//-----------------------------------------------------------------------

STATUS CMS(U8 ModuleState, OS_MEMORY_POOL *MemPool, U32 *Arg3)
{
   STATUS LocalStatus = 0;

   
   if(ModuleState == APP_INIT1)
   {
      LocalStatus = OS_ValidateAPI(API_VERSION_MAJOR,
                                   API_VERSION_MINOR,
                                   OS_LinkTime,
                                   ReleaseTag,
                                   __MODULE__
                                   );
      if ( OS_SUCCESS != LocalStatus )
      {
         return LocalStatus;
      }
   }
#ifdef READ_VARS
   // Read inputdata
   LocalStatus = InputReferenceRoutine(ModuleState);
   STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif
#ifdef COMMON_VDB_READ
   LocalStatus = ReadVdbWindow(ModuleState);
   STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif
   switch(ModuleState)
   {
      case APP_RUN :
      {
         #ifdef FUNCTION_BLOCKS_PRE_LOCAL_CONTROL
            LocalStatus = FunctionBlocksPreLocalCtrl( Interval );
            STATUS_LINE_VAR_RETURN_VALUE( LocalStatus );
         #endif

         LocalStatus = LocalCtrl();
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
        
         #ifdef FUNCTION_BLOCKS_POST_LOCAL_CONTROL
            LocalStatus = FunctionBlocksPostLocalCtrl( Interval );
            STATUS_LINE_VAR_RETURN_VALUE( LocalStatus );
         #endif

#ifdef WRITE_VARS
         // Write Outputdata
         LocalStatus = OutputReferenceRoutine(ModuleState);
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif

#ifdef COMMON_VDB_WRITE
         LocalStatus = WriteVdbWindow(ModuleState);
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif
         break;
      }
      case APP_INIT1 :
      {
         Init_Structures_From_Conf_File();
                 

#ifdef CREATE_VARDB_VARS
         LocalStatus = CreateVarDbVars();
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif

#ifdef CREATE_MENU
         LocalStatus = CMSMenuAppInit(ModuleState, MemPool);
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)

#ifdef MULTIPLEXIBLE_MENU
         LocalStatus = MenuArraysAppInit(ModuleState, MemPool);
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif
#endif

#ifdef CREATE_VARDB_ARRAY_VARS
         LocalStatus = CreateVdbArrays(MemPool);
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif

#ifdef CREATE_IO_VARS
         LocalStatus = CreateIOVars();
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif
         break;
      }
      case APP_INIT2 :
      {
#ifdef CREATE_MENU
#ifdef MULTIPLEXIBLE_MENU
         LocalStatus = MenuArraysAppInit(ModuleState, MemPool);
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif
#endif

#ifdef CREATE_ALIASES
         size_t ErrorEntry = 0;
         LocalStatus = OS_VarDB_CreateAliases(AliasVars, sizeof(AliasVars)/sizeof(AliasVars[0]), &ErrorEntry);
         STATUS_LINE_VAR_RETURN_CONST(LocalStatus, ErrorEntry)
#endif

#ifdef VERIFY_ARRAY
        LocalStatus = VerifyArray(MemPool);
        STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif

#ifdef VERIFY_VARIABLES
         LocalStatus = LocalIoCheck();
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif

#ifdef CREATE_BUTTONS
         LocalStatus = CreateButtons();
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif
         break;
      }
      case APP_INIT3 :
      {
#ifdef CREATE_SUMMATIONS
         LocalStatus = CreateSummations();
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif

#ifdef WRITE_VARS
         LocalStatus = InitOutputVars();
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif

#ifdef CREATE_STATUS_CODES
         LocalStatus = LocalStatusCodeInit();
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif

#ifdef CREATE_IO_VARS
        CMSSetLockValues();
#endif
         break;
      }
      case APP_INIT4 :
      {
#ifdef CREATE_MENU
         LocalStatus = CMSMenuAppInit(ModuleState, MemPool);
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)

#ifdef MULTIPLEXIBLE_MENU
         LocalStatus = MenuArraysAppInit(ModuleState, MemPool);
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif
#endif
         break;
      }
      case APP_INIT5 :
      {
#ifdef VALIDATE_HASH
         LocalStatus = ValidateHash(CMS_copyright, MODULE_NAME, CMS_initialValues);
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif

         #ifdef INIT_FUNCTION_BLOCKS
            LocalStatus = FunctionBlocksInit( Interval );
            STATUS_LINE_VAR_RETURN_VALUE( LocalStatus );
         #endif

         break;
      }
      default :
      {
         break;
      }
   }
   return OS_SUCCESS;
}
//-----------------------------------------------------------------------
