//*****************************PEPTOOL Header Start******************************
//                                                                               
//                         Copyright © 2015 Mita-Teknik.                         
//This software may only be used with WP4x00 Controllers delivered by Mita-Teknik
//                                                                               
//*******************************************************************************
//                                                                               
// $PEPTOOL version:9.0$                                                         
// $PEPTOOL file version:106$                                                    
//                                                                               
//*******************************************************************************
//                                                                               
// $Date: XXXX/XX/XX XX:XX:XX $                                                  
// $Author: XXXX\XXX $                                                           
// $RCSfile: Configurator.c,v $                                                  
// $Revision: X.X $                                                              
//                                                                               
//******************************PEPTOOL Header End*******************************

//***********************************************************************

// OS header files
#include <os_main.h>
// AppLib header files
#include <lib_main.h>
// App header files
#include <turbdef.h>
#include <VarMacros.h>

// Object header file
#include <Configurator.h>

#define AUTOGENERATED_PART
//{
//-----------------------------------------------------------------------
// AUTOGENERATED START     AUTOGENERATED START     AUTOGENERATED START
//-----------------------------------------------------------------------

#define VALIDATE_HASH
char Configurator_copyright[] =
{
    67, 111, 112, 121, 114, 105, 103, 104, 116, 32, 63, 32, 50, 48, 49, 53,
    32, 77, 105, 116, 97, 45, 84, 101, 107, 110, 105, 107, 46, 13, 10, 84,
    104, 105, 115, 32, 115, 111, 102, 116, 119, 97, 114, 101, 32, 109, 97, 121,
    32, 111, 110, 108, 121, 32, 98, 101, 32, 117, 115, 101, 100, 32, 119, 105,
    116, 104, 32, 87, 80, 52, 120, 48, 48, 32, 67, 111, 110, 116, 114, 111,
    108, 108, 101, 114, 115, 32, 100, 101, 108, 105, 118, 101, 114, 101, 100, 32,
    98, 121, 32, 77, 105, 116, 97, 45, 84, 101, 107, 110, 105, 107, 0
};

#define MODULE_NAME "ConfiguratorA"

//-----------------------------------------------------------------------
// ALLOCATE MEMORY FOR STRINGS IN VARDB
//-----------------------------------------------------------------------

static char A_V_ConfiguratorUsageTxt[34]  = "12345678901234567890123456789";

//-----------------------------------------------------------------------
// DEFINE LOCAL VARIABLES DEFINE LOCAL VARIABLES DEFINE LOCAL VARIABLES
//-----------------------------------------------------------------------

static struct os_db_local LocalVars[] =
{
   VAR_ELEMENT_LOCAL("V_ConfiguratorUsage",                      TYPE_U8,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         SCALE_NONE,   0,       UNIT_NONE,          0,   0,               0,               2,               NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_ConfiguratorUsageTxt",                   TYPE_STRING + sizeof(A_V_ConfiguratorUsageTxt) - 1,  PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         SCALE_NONE,   0,       UNIT_NONE,          0,   A_V_ConfiguratorUsageTxt, 0,                0,                NULL,  NOLOG_ENABLE  ),
};

//-----------------------------------------------------------------------
// DEFINE PARAMETERS        DEFINE PARAMETERS        DEFINE PARAMETERS
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// DEFINE BACKUPS            DEFINE BACKUPS            DEFINE BACKUPS
//-----------------------------------------------------------------------

static struct os_db_backup BackupVars[] =
{
   VAR_ELEMENT_BACKUP("B_ConfiguratorUsage",                      TYPE_U8,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         SCALE_NONE,   0,       UNIT_NONE,          0,   0,               0,               2,               NULL,  NOLOG_ENABLE),
};

//----------------------------------------------------------------------------------
// DEFINE VAR ARRAYS            DEFINE VAR ARRAYS            DEFINE VAR ARRAYS
//----------------------------------------------------------------------------------
char Configurator_initialValues[] =
{
    127, 160, 88, 77, 191, 126, 241, 95, 90, 6, 115, 177, 26, 0, 193, 146,
    197, 32, 60, 123, 55, 246, 225, 216, 250, 127, 43, 6, 34, 74, 77, 153,
    0
};

//-----------------------------------------------------------------------
// CREATE DATABASE VARS   CREATE DATABASE VARS   CREATE DATABASE VARS
//-----------------------------------------------------------------------

static STATUS CreateVarDbVars(void)
{
   STATUS Status;
   size_t ErrorEntry;

   Status = OS_VarDB_CreateLocals(LocalVars, sizeof(LocalVars)/sizeof(LocalVars[0]), &ErrorEntry, AppLocalParameterPosition());
   if (Status != 0)
   {
      AppSystemLog(ERR_7, MODULE_NAME"CrVL: %d,%d", Status, ErrorEntry);
      return ERR_7;
   }

   Status = OS_VarDB_CreateBackups(BackupVars, sizeof(BackupVars)/sizeof(BackupVars[0]), &ErrorEntry, AppLocalParameterPosition(), AppBackupPosition());
   if (Status != 0)
   {
      AppSystemLog(ERR_7, MODULE_NAME"CrVB: %d,%d", Status, ErrorEntry);
      return ERR_7;
   }

   return OS_SUCCESS;
}

#define CREATE_VARDB_VARS

//-----------------------------------------------------------------------
// CREATE IO VARIABLES     CREATE IO VARIABLES     CREATE IO VARIABLES
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// ALIASES                       ALIASES                       ALIASES
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// INPUT                          INPUT                          INPUT
//-----------------------------------------------------------------------

//------------------------------------------------------------------------------------------
// READ/WRITE VARDB ARRAY      READ/WRITE VARDB ARRAY      READ/WRATE VARDB ARRAY
//------------------------------------------------------------------------------------------


//-----------------------------------------------------------------------
// PARAMETER                    PARAMETER                    PARAMETER
//-----------------------------------------------------------------------


//-----------------------------------------------------------------------
// READ VARS FROM VARDB    READ VARS FROM VARDB    READ VARS FROM VARDB
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// OUTPUT                         OUTPUT                         OUTPUT
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// WRITE VARS TO VARDB     WRITE VARS TO VARDB     WRITE VARS TO VARDB
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// VERIFY VARIABLES CREATION                 VERIFY VARIABLES CREATION
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// ALLOCATE MEMORY FOR SUMMATIONS        ALLOCATE MEMORY FOR SUMMATIONS
//-----------------------------------------------------------------------


//-----------------------------------------------------------------------
// SUMMATIONS                  SUMMATIONS                  SUMMATIONS
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// DEFINE MENUS               DEFINE MENUS               DEFINE MENUS
//-----------------------------------------------------------------------



// Menu line and link to local menu
//-----------------------------------------------------------------------
static struct line_struct M_ConfiguratorLinkToLocalMenu[] =
{
   MENU_ELEMENT_LINE_LINK("Configurator",                      PASSWORD_LEVEL_END_CUSTOMER,        "M_Configurator",                   "G_Configurator"),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_ConfiguratorMenu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_Configurator",                   PASSWORD_LEVEL_END_CUSTOMER),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_ConfiguratorMenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("CONFIGURATOR",                      PASSWORD_LEVEL_END_CUSTOMER,        "M_"APP_ID"AppMain",                "G_"APP_ID"App"),
   MENU_ELEMENT_LINE_VARRW("Configuration Number Usage",       PASSWORD_LEVEL_END_CUSTOMER,        (char*)"B_ConfiguratorUsage",                        LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Configuration Usage",              PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_ConfiguratorUsageTxt",                     LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_LINK("1: Fecon Converter",                PASSWORD_LEVEL_END_CUSTOMER,        "M_1FeconConverter4",               "G_Configurator"),
   MENU_ELEMENT_LINE_LINK("2: Liebherr Converter",             PASSWORD_LEVEL_END_CUSTOMER,        "M_2LiebherrConverter6",            "G_Configurator"),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_1FeconConverter4Menu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_1FeconConverter4",               PASSWORD_LEVEL_END_CUSTOMER),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_1FeconConverter4MenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("1: FECON CONVERTER",                PASSWORD_LEVEL_END_CUSTOMER,        "M_Configurator",                   "G_Configurator"),
   MENU_ELEMENT_LINE_TEXT("FeCon Converter",                   PASSWORD_LEVEL_END_CUSTOMER),
   MENU_ELEMENT_LINE_TEXT("FeCon Converter 1",                 PASSWORD_LEVEL_END_CUSTOMER),
   MENU_ELEMENT_LINE_TEXT("FeCon Converter 2",                 PASSWORD_LEVEL_END_CUSTOMER),
   MENU_ELEMENT_LINE_TEXT("FeCon Converter 3",                 PASSWORD_LEVEL_END_CUSTOMER),
   MENU_ELEMENT_LINE_TEXT("FeCon Converter 4",                 PASSWORD_LEVEL_END_CUSTOMER),
   MENU_ELEMENT_LINE_TEXT("Inverter Cooling",                  PASSWORD_LEVEL_END_CUSTOMER),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_2LiebherrConverter6Menu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_2LiebherrConverter6",            PASSWORD_LEVEL_END_CUSTOMER),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_2LiebherrConverter6MenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("2: LIEBHERR CONVERTER",             PASSWORD_LEVEL_END_CUSTOMER,        "M_Configurator",                   "G_Configurator"),
   MENU_ELEMENT_LINE_TEXT("Liebherr Converter",                PASSWORD_LEVEL_END_CUSTOMER),
};
// Creating parameters for multiplexed categories
//-----------------------------------------------------------------------
static struct multiplexed_info_struct M_ConfiguratorMultiplexedCategoriesParameters[] =
{0
};

//-----------------------------------------------------------------------
// CREATE MENUS               CREATE MENUS               CREATE MENUS
//-----------------------------------------------------------------------

// Memory reservation
//-----------------------------------------------------------------------
static struct menu_group_struct ObjGroup[1];

// Creating the menus
//-----------------------------------------------------------------------
STATUS ConfiguratorMenuAppInit(U8 ModuleState, OS_MEMORY_POOL* pPool)
{
   STATUS Status;

   if (ModuleState == APP_INIT1)
   {
      /* Create application group */
      Status = OS_CreateMenuGroup(ObjGroup, M_ConfiguratorLinkToLocalMenu[0].LinkGroup);
      STATUS_LINE_VAR_RETURN_VALUE(Status);
   }

   Status = CreateAndInitializeMenu(ModuleState,
                                    M_ConfiguratorMenuLines[0].LinkGroup,
                                    M_ConfiguratorMenuLines[0].LinkName,
                                    ELEMENT(M_ConfiguratorLinkToLocalMenu),
                                    M_ConfiguratorLinkToLocalMenu[0].LinkGroup,
                                    ELEMENT(M_ConfiguratorMenu),
                                    M_ConfiguratorLinkToLocalMenu[0].LinkName,
                                    ELEMENT(M_ConfiguratorMenuLines),
                                    pPool,
                                    M_ConfiguratorMultiplexedCategoriesParameters);
   STATUS_LINE_VAR_RETURN_VALUE(Status);

   Status = CreateAndInitializeMenu(ModuleState,
                                    M_1FeconConverter4MenuLines[0].LinkGroup,
                                    M_1FeconConverter4MenuLines[0].LinkName,
                                    NULL,
                                    0,
                                    M_ConfiguratorMenuLines[3].LinkGroup,
                                    ELEMENT(M_1FeconConverter4Menu),
                                    M_ConfiguratorMenuLines[3].LinkName,
                                    ELEMENT(M_1FeconConverter4MenuLines),
                                    pPool,
                                    M_ConfiguratorMultiplexedCategoriesParameters);
   STATUS_LINE_VAR_RETURN_VALUE(Status);

   Status = CreateAndInitializeMenu(ModuleState,
                                    M_2LiebherrConverter6MenuLines[0].LinkGroup,
                                    M_2LiebherrConverter6MenuLines[0].LinkName,
                                    NULL,
                                    0,
                                    M_ConfiguratorMenuLines[4].LinkGroup,
                                    ELEMENT(M_2LiebherrConverter6Menu),
                                    M_ConfiguratorMenuLines[4].LinkName,
                                    ELEMENT(M_2LiebherrConverter6MenuLines),
                                    pPool,
                                    M_ConfiguratorMultiplexedCategoriesParameters);
   STATUS_LINE_VAR_RETURN_VALUE(Status);

   return OS_SUCCESS;
}

#define CREATE_MENU

//-----------------------------------------------------------------------
//               BUTTONS FUNCTIONS FORWARD DECLARATIONS
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// BUTTONS                       BUTTONS                      BUTTONS
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
//             SET/RESET FUNCTIONS FORWARD DECLARATIONS
//-----------------------------------------------------------------------
//-----------------------------------------------------------------------
// STATUSCODES                 STATUSCODES                 STATUSCODES
//-----------------------------------------------------------------------

static struct sts_statuscode_structure StatusCodes[] =
{
   STS_CODE_ELEMENT("App. not configured",    20*SEC,    2476,      STATUSCODE_UPDATE_TYPE_AUTOMATIC,       PASSWORD_LEVEL_SERVICE,            STATUSCODE_TIMER_TYPE_CONSTANT,     STATUSCODE_TIMER_TYPE_CONSTANT,     STATUSCODE_RESET_TYPE_DISPLAY,      STATUSCODE_PRIORITY_LOW,       0,    0,    32,   NULL,      PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_SERVICE,            NULL,                    NULL,                    BRAKE_PROG_0,        BRAKE_PROG_0,        BRAKE_PROG_MAX,      NULL,                PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_MITA_PROGRAMMER,    YAW_PROG_0,          YAW_PROG_0,          YAW_PROG_240,        NULL,                PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_MITA_PROGRAMMER,    0,    0,    255,  NULL,      PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_SERVICE,            1,  PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_SERVICE,            1000,      20,        1000,      NULL,      PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         SETDELAY_MIN,   SETDELAY_MAX,   NULL,      PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         RESETDELAY_MIN, RESETDELAY_MAX, NULL,      PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         REPEATTIMES_MIN,     REPEATTIMES_MAX,     NULL,      PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         REPEATPERIOD_MIN,    REPEATPERIOD_MAX,    NULL,      PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         REPEATCODE_MIN,      REPEATCODE_MAX,      NULL,      PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         TIMEOUTPERIOD_MIN,   TIMEOUTPERIOD_MAX,   NULL,      PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         TIMEOUTCODE_MIN,     TIMEOUTCODE_MAX,     NULL,      PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         NULL),
};

static STATUS_CODE_CONTROL_BLOCK StatusCodeControlBlock;

static STATUS LocalStatusCodeInit(void)
{
   STATUS LocalStatus;

   LocalStatus = OS_StatusCodeInit(STATUSCODE_INTERFACE_VERSION,
                                   &StatusCodeControlBlock,
                                   StatusCodes,
                                   sizeof(StatusCodes)/sizeof(StatusCodes[0]),
                                   AppLocalParameterPosition(),
                                   AppBackupPosition());
   STATUS_LINE_VAR_RETURN_CONST(LocalStatus, ERR_3);

   return OS_SUCCESS;
}

#define CREATE_STATUS_CODES

//-----------------------------------------------------------------------
// MODIFIABLE                  MODIFIABLE                   MODIFIABLE
//-----------------------------------------------------------------------

extern const char ConfiguratorAppGroupName[];
extern const char ConfiguratorAppMenuName[];

static void Init_Structures_From_Conf_File(void)
{
   M_ConfiguratorMenuLines[0].LinkName = (char*)ConfiguratorAppMenuName;
   M_ConfiguratorMenuLines[0].LinkGroup = (char*)ConfiguratorAppGroupName;
}

//-----------------------------------------------------------------------
// CONFIGURATOR               CONFIGURATOR               CONFIGURATOR
//-----------------------------------------------------------------------

U32 FeConConverter_FeConGmbH_Type1CallStatus = 0;
U32 LiebherrConverterCallStatus = 0;
U32 FeConConverter1_MT_Type1CallStatus = 0;
U32 FeConConverter2_MT_Type1CallStatus = 0;
U32 FeConConverter3_MT_Type1CallStatus = 0;
U32 FeConConverter4_MT_Type1CallStatus = 0;
U32 InverterCooling_MT_Type1CallStatus = 0;

static U8 Running = 0;

#ifndef CONFIGURATOR_NOT_CONFIGURED
#define CONFIGURATOR_NOT_CONFIGURED 0
#endif

#ifndef FECON_CONVERTER_NUMBER
#define FECON_CONVERTER_NUMBER 1
#endif

#ifndef LIEBHERR_CONVERTER_NUMBER
#define LIEBHERR_CONVERTER_NUMBER 2
#endif

static U8 B_ConfiguratorUsage = 0;
static varid_t B_ConfiguratorUsage_id = NULL;
static U8 V_ConfiguratorUsage = 0;
static varid_t V_ConfiguratorUsage_id = NULL;
static char V_ConfiguratorUsageTxt[34]= "Not Init";
static varid_t V_ConfiguratorUsageTxt_id = NULL;

static STATUS ConfCtrl(void)
{
   STATUS LocalStatus = 0;

   if (V_ConfiguratorUsage_id == NULL)
   {
      LocalStatus = OS_VarDB_GetVariableID("V_ConfiguratorUsage", &V_ConfiguratorUsage_id);
      STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
   }

   if (B_ConfiguratorUsage_id == NULL)
   {
      LocalStatus = OS_VarDB_GetVariableID("B_ConfiguratorUsage", &B_ConfiguratorUsage_id);
      STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
   }

   if (V_ConfiguratorUsageTxt_id == NULL)
   {
      LocalStatus = OS_VarDB_GetVariableID("V_ConfiguratorUsageTxt", &V_ConfiguratorUsageTxt_id);
      STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
   }

   LocalStatus = OS_VarDB_ReadVariable(V_ConfiguratorUsage_id, &V_ConfiguratorUsage, sizeof(V_ConfiguratorUsage), NULL);
   STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);

   LocalStatus = OS_VarDB_ReadVariable(B_ConfiguratorUsage_id, &B_ConfiguratorUsage, sizeof(B_ConfiguratorUsage), NULL);
   STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);

   if (B_ConfiguratorUsage == CONFIGURATOR_NOT_CONFIGURED)
   {
      if (!StatusCodeActive(2476))
      {
         OS_ActivateStatusCode(2476);
      }
      strcpy(V_ConfiguratorUsageTxt, "Not configured");
   }
   else if ((V_ConfiguratorUsage != B_ConfiguratorUsage) && (B_ConfiguratorUsage == FECON_CONVERTER_NUMBER))
   {
      if (!StatusCodeActive(2476) && Running)
      {
         OS_ActivateStatusCode(2476);
      }
      if (Running)
      {
         strcpy(V_ConfiguratorUsageTxt, "Reboot for Fecon Converter");
      }
      else
      {
         strcpy(V_ConfiguratorUsageTxt, "Starting Fecon Converter");
      }
   }
   else if ((V_ConfiguratorUsage != B_ConfiguratorUsage) && (B_ConfiguratorUsage == LIEBHERR_CONVERTER_NUMBER))
   {
      if (!StatusCodeActive(2476) && Running)
      {
         OS_ActivateStatusCode(2476);
      }
      if (Running)
      {
         strcpy(V_ConfiguratorUsageTxt, "Reboot for Liebherr Converter");
      }
      else
      {
         strcpy(V_ConfiguratorUsageTxt, "Starting Liebherr Converter");
      }
   }
   else if (V_ConfiguratorUsage == FECON_CONVERTER_NUMBER)
   {
      strcpy(V_ConfiguratorUsageTxt, "Fecon Converter");
   }
   else if (V_ConfiguratorUsage == LIEBHERR_CONVERTER_NUMBER)
   {
      strcpy(V_ConfiguratorUsageTxt, "Liebherr Converter");
   }
   else
   {
      strcpy(V_ConfiguratorUsageTxt, "Error");
   }

   LocalStatus = OS_VarDB_UpdateVariable(V_ConfiguratorUsageTxt_id, &V_ConfiguratorUsageTxt, sizeof(V_ConfiguratorUsageTxt));
   STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);

   return OS_SUCCESS;
}

static STATUS ConfMain(void)
{
   STATUS LocalStatus = 0;

   while (B_ConfiguratorUsage == CONFIGURATOR_NOT_CONFIGURED || (B_ConfiguratorUsage != FECON_CONVERTER_NUMBER && B_ConfiguratorUsage != LIEBHERR_CONVERTER_NUMBER))
   {
      LocalStatus = ConfCtrl();
      STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);

      OS_Sleep(100);
   }

   V_ConfiguratorUsage = B_ConfiguratorUsage;
   LocalStatus = OS_VarDB_UpdateVariable(V_ConfiguratorUsage_id, &V_ConfiguratorUsage, sizeof(V_ConfiguratorUsage));
   STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);

   FeConConverter_FeConGmbH_Type1CallStatus = V_ConfiguratorUsage == FECON_CONVERTER_NUMBER;
   LiebherrConverterCallStatus = V_ConfiguratorUsage == LIEBHERR_CONVERTER_NUMBER;
   FeConConverter1_MT_Type1CallStatus = V_ConfiguratorUsage == FECON_CONVERTER_NUMBER;
   FeConConverter2_MT_Type1CallStatus = V_ConfiguratorUsage == FECON_CONVERTER_NUMBER;
   FeConConverter3_MT_Type1CallStatus = V_ConfiguratorUsage == FECON_CONVERTER_NUMBER;
   FeConConverter4_MT_Type1CallStatus = V_ConfiguratorUsage == FECON_CONVERTER_NUMBER;
   InverterCooling_MT_Type1CallStatus = V_ConfiguratorUsage == FECON_CONVERTER_NUMBER;

   Running = 1;

   return LocalStatus;
}

//-----------------------------------------------------------------------
// AUTOGENERATED END        AUTOGENERATED END        AUTOGENERATED END
//-----------------------------------------------------------------------
//}

#undef AUTOGENERATED_PART

//-----------------------------------------------------------------------
// USER DEFINITIONS         USER DEFINITIONS         USER DEFINITIONS
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// SET/RESET FUNCTIONS    SET/RESET FUNCTIONS    SET/RESET FUNCTIONS
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// DRIVER FUNCTION         DRIVER FUNCTION         DRIVER FUNCTION
//-----------------------------------------------------------------------
  
//-----------------------------------------------------------------------
// INIT                   INIT                     INIT
//-----------------------------------------------------------------------
  
//-----------------------------------------------------------------------
// CONTROL                CONTROL                 CONTROL
//-----------------------------------------------------------------------
  
static STATUS LocalCtrl( U32 Interval )
{
   STATUS LocalStatus = 0;

   LocalStatus = ConfCtrl();
   STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);

   return LocalStatus;
}

static STATUS ShutdownCtrl( U8 ModuleState, U8 *DoneState, U32 Interval )
{
    STATUS LocalStatus = 0;

    LocalStatus = LocalCtrl( Interval );
    STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);

    switch( ModuleState )
    {
        case AS_SHUTDOWN:
        {
            // Activate "Manual Shutdown" status code

            *DoneState = AS_SHUTDOWN;
            break;
        }
        case AS_REBOOT:
        {

            *DoneState = AS_REBOOT;
            break;
        }
        case AS_SHUTDOWN_FAST:
        {

            *DoneState = AS_SHUTDOWN_FAST;
            break;
        }
        default:
        {
            *DoneState = ModuleState;
            break;
        }
    }
    return LocalStatus;
}
 
//-----------------------------------------------------------------------
// MAIN CALL             MAIN CALL               MAIN CALL
//-----------------------------------------------------------------------

STATUS Configurator( U8 ModuleState, U8 *DoneState , U32 Interval )
{
   STATUS LocalStatus = 0;

   #ifdef READ_VARS
      // Read input data
      LocalStatus = InputReferenceRoutine(ModuleState);
      STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
   #endif
   #ifdef COMMON_VDB_READ
      LocalStatus = ReadVdbWindow(ModuleState);
      STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
   #endif


   switch( ModuleState )
   {
      //__________________________________________________________________________
      case APP_RUN:
      {
         #ifdef FUNCTION_BLOCKS_PRE_LOCAL_CONTROL
            LocalStatus = FunctionBlocksPreLocalCtrl( Interval );
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif
         
         LocalStatus = LocalCtrl( Interval );
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);

         #ifdef FUNCTION_BLOCKS_POST_LOCAL_CONTROL
            LocalStatus = FunctionBlocksPostLocalCtrl( Interval );
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef WRITE_VARS
            // Write Output data
            LocalStatus = OutputReferenceRoutine(ModuleState);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef COMMON_VDB_WRITE
            LocalStatus = WriteVdbWindow(ModuleState);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         *DoneState = APP_RUN;
         break;
      }
      //__________________________________________________________________________
      case APP_INIT1:
      {
         // Version check
         LocalStatus = OS_ValidateAPI( API_VERSION_MAJOR,
                                API_VERSION_MINOR,
                                OS_LinkTime,
                                ReleaseTag,
                                __MODULE__
                               );
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);

         Init_Structures_From_Conf_File();

         #ifdef CREATE_VARDB_VARS
            LocalStatus = CreateVarDbVars();
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef CREATE_VARDB_ARRAY_VARS
               LocalStatus = CreateVdbArrays(GetMemPool());
               STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
         #endif

         #ifdef CREATE_MENU
            LocalStatus = ConfiguratorMenuAppInit(APP_INIT1, GetMemPool());
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);

            #ifdef MULTIPLEXIBLE_MENU
               LocalStatus = MenuArraysAppInit(APP_INIT1, GetMemPool());
               STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);

               LocalStatus = MenuArraysAppInit(APP_INIT2, GetMemPool());
               STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
            #endif

            LocalStatus = ConfiguratorMenuAppInit(APP_INIT4, GetMemPool());
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);

            #ifdef MULTIPLEXIBLE_MENU
               LocalStatus = MenuArraysAppInit(APP_INIT4, GetMemPool());
               STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
            #endif
         #endif

         #ifdef CREATE_STATUS_CODES
            LocalStatus = LocalStatusCodeInit();
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         LocalStatus = ConfMain();
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);

         #ifdef CREATE_IO_VARS
               LocalStatus = CreateIOVars();
               STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
         #endif

         *DoneState = APP_INIT1;

         break;
      }
      //__________________________________________________________________________
      case APP_INIT2:
      {
         #ifdef CREATE_ALIASES
               size_t ErrorEntry = 0;
               LocalStatus = OS_VarDB_CreateAliases(AliasVars, sizeof(AliasVars)/sizeof(AliasVars[0]), &ErrorEntry);
               STATUS_LINE_VAR_RETURN_CONST(LocalStatus, ErrorEntry);
         #endif

         #ifdef VERIFY_ARRAY
               LocalStatus = VerifyArray(GetMemPool());
               STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef VERIFY_VARIABLES
               LocalStatus = LocalIoCheck();
               STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef CREATE_BUTTONS
               LocalStatus = CreateButtons();
               STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         *DoneState = APP_INIT2;

         break;
      }
      //__________________________________________________________________________
      case APP_INIT3 :
      {
         #ifdef CREATE_SUMMATIONS
            LocalStatus = CreateSummations();
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef WRITE_VARS
            LocalStatus = InitOutputVars();
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef CREATE_IO_VARS
           ConfiguratorSetLockValues();
         #endif

         *DoneState = APP_INIT3;

         break;
      }
      //__________________________________________________________________________
      case APP_INIT4:
      {

         *DoneState = APP_INIT4;

         break;
      }
      //__________________________________________________________________________
      case APP_INIT5:
      {
         #ifdef VALIDATE_HASH
            LocalStatus = ValidateHash( Configurator_copyright, MODULE_NAME, Configurator_initialValues);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef INIT_FUNCTION_BLOCKS
            LocalStatus = FunctionBlocksInit( Interval );
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         *DoneState = APP_INIT5_DONE;

         break;
      }
      //__________________________________________________________________________
      //Other initialization round can be inserted here
      //__________________________________________________________________________
      case AS_SHUTDOWN:
      {
         LocalStatus = ShutdownCtrl ( ModuleState, DoneState, Interval );
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);

         #ifdef WRITE_VARS
            // Write Output data
            LocalStatus = OutputReferenceRoutine(ModuleState);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef COMMON_VDB_WRITE
            LocalStatus = WriteVdbWindow(ModuleState);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         break;
      }
      //__________________________________________________________________________
      case AS_REBOOT:
      {
         LocalStatus = ShutdownCtrl ( ModuleState, DoneState, Interval );
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);

         #ifdef WRITE_VARS
            // Write Output data
            LocalStatus = OutputReferenceRoutine(ModuleState);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef COMMON_VDB_WRITE
            LocalStatus = WriteVdbWindow(ModuleState);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         break;
      }
      //__________________________________________________________________________
      case AS_SHUTDOWN_FAST:
      {
         LocalStatus = ShutdownCtrl ( ModuleState, DoneState, Interval );
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);

         #ifdef WRITE_VARS
            // Write Output data
            LocalStatus = OutputReferenceRoutine(ModuleState);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef COMMON_VDB_WRITE
            LocalStatus = WriteVdbWindow(ModuleState);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         break;
      }
      default:
      {
         *DoneState = ModuleState;

         break;
      }
   }
   return OS_SUCCESS;
}
//-----------------------------------------------------------------------
