//*****************************PEPTOOL Header Start******************************
//                                                                               
//                         Copyright © 2015 Mita-Teknik.                         
//This software may only be used with WP4x00 Controllers delivered by Mita-Teknik
//                                                                               
//*******************************************************************************
//                                                                               
// $PEPTOOL version:9.0$                                                         
// $PEPTOOL file version:101$                                                    
//                                                                               
//*******************************************************************************
//                                                                               
// $Date: 2014/04/07 12:43:17 $                                                  
// $Author: MITA\aos $                                                           
// $RCSfile: drivers.h,v $                                                       
// $Revision: 1.3 $                                                              
//                                                                               
//******************************PEPTOOL Header End*******************************
#ifndef FILE_DRIVERS_H
#define FILE_DRIVERS_H

STATUS InitIoDrivers( U8 ModuleState, U8 *DoneState , U32 Interval );

#define AUTOGENERATED_INCLUDE
    
#include <SafetySystem_MT_GL2010.h>
#include <EStopChain_MT_GL20101ExtStop.h>
#include <SafetyChain_MT_GL20102ManStop.h>
#include <VibrationMonitoringEmulator.h>
#include <SurgeProtection.h>
#include <Generator.h>
#include <TowerResonansTime.h>
#include <WeatherSensor2.h>
#include <WindSpeed.h>
#include <WindDirection.h>
#include <Wind.h>
#include <OutdoorTemperature.h>
#include <Brake.h>
#include <BladeController_emulator.h>
#include <Transformer.h>
#include <PowerManagement.h>
#include <PitchAndTorque.h>
#include <Yaw_MK1.h>
#include <YawMotorControl_MK1.h>
#include <FeConConverter_FeConGmbh_Type1.h>
#include <FeConConverter1_MT_Type1.h>
#include <FeConConverter2_MT_Type1.h>
#include <FeConConverter3_MT_Type1.h>
#include <FeConConverter4_MT_Type1.h>
#include <InverterCooling_MT_Type1.h>
#include <GeneratorCooling_MT_Type1.h>
#include <TowerBase.h>
#include <Nacelle.h>
#include <Panels.h>
#include <FlightWarningLight.h>
#include <WindRose.h>
#include <PowerCurve.h>
#include <FileInterface.h>
#include <UPS1.h>
#include <Info.h>
#include <CMS.h>
#include <Lubrication_MT_Type1.h>
#include <Lubrication_Main_Bearing_MT_Type1.h>
#include <Lubrication_Pitch_Pinion_MT_Type1.h>
#include <LubricationYaw_MT_Type1.h>
#include <UPS.h>
#include <FRT.h>
#include <Grid.h>
#include <AirPressure.h>
#include <WindSpeedPower_Normalization.h>
#include <Hub_MT_Type1.h>
#include <Operate_MT_Type2.h>
#include <LVRT.h>
#include <NacelleAcceleration.h>
#include <BladeLoads_Type1.h>
#include <Lidar.h>
#include <MainBearingPressure.h>
#include <Shutdown.h>

#undef AUTOGENERATED_INCLUDE

#endif
