//*****************************PEPTOOL Header Start******************************
//                                                                               
//                         Copyright © 2015 Mita-Teknik.                         
//This software may only be used with WP4x00 Controllers delivered by Mita-Teknik
//                                                                               
//*******************************************************************************
//                                                                               
// $PEPTOOL version:9.0$                                                         
// $PEPTOOL file version:101$                                                    
//                                                                               
//*******************************************************************************
//                                                                               
// $Date: XXXX/XX/XX XX:XX:XX $                                                  
// $Author: XXXX\XXX $                                                           
// $RCSfile: EtillStopChain_MT_GL20101ExtStop_Conf.c,v $                         
// $Revision: X.X $                                                              
//                                                                               
//******************************PEPTOOL Header End*******************************

//***********************************************************************
// OS header files
#include <os_main.h>
// App header files
#include <InitIo.h>

#define AUTOGENERATED_PART

#include <Turbdef.h>

//-----------------------------------------------------------------------
// AUTOGENERATED START     AUTOGENERATED START     AUTOGENERATED START
//-----------------------------------------------------------------------
char EStopChain_MT_GL20101ExtStop_Conf_copyright[] =
{
   67, 111, 112, 121, 114, 105, 103, 104, 116, 32, 63, 32, 50, 48, 49, 53,
   32, 77, 105, 116, 97, 45, 84, 101, 107, 110, 105, 107, 46, 13, 10, 84,
   104, 105, 115, 32, 115, 111, 102, 116, 119, 97, 114, 101, 32, 109, 97, 121,
   32, 111, 110, 108, 121, 32, 98, 101, 32, 117, 115, 101, 100, 32, 119, 105,
   116, 104, 32, 87, 80, 52, 120, 48, 48, 32, 67, 111, 110, 116, 114, 111,
   108, 108, 101, 114, 115, 32, 100, 101, 108, 105, 118, 101, 114, 101, 100, 32,
   98, 121, 32, 77, 105, 116, 97, 45, 84, 101, 107, 110, 105, 107, 0
};
//-----------------------------------------------------------------------
// MODIFIABLE                  MODIFIABLE               MODIFIABLE
//-----------------------------------------------------------------------
const char EStopChain_MT_GL20101ExtStopAppGroupName[] = "G_"APP_ID"App";
const char EStopChain_MT_GL20101ExtStopAppMenuName[] = "M_"APP_ID"AppMain";

//-----------------------------------------------------------------------
// IO VARIABLES                IO VARIABLES                IO VARIABLES
//-----------------------------------------------------------------------

void (*EStopChain_MT_GL20101ExtStopSetLockValues)(void);
struct os_db_alias *EStopChain_MT_GL20101ExtStopIOVars;
size_t EStopChain_MT_GL20101ExtStopIOVarsSize = 0;
            
struct os_db_alias EStopChain_MT_GL20101ExtStopIOVars1[]=
{
    VAR_ELEMENT_ALIAS("1.4.25",                           "DI_SafetySystemEStopTBp"),
    VAR_ELEMENT_ALIAS("1.4.25_Ss",                        "DI_SafetySystemEStopTBp_Ss"),
    VAR_ELEMENT_ALIAS("1.4.25_E",                         "DI_SafetySystemEStopTBp_E"),
    VAR_ELEMENT_ALIAS("1.4.25_I",                         "DI_SafetySystemEStopTBp_I"),
    VAR_ELEMENT_ALIAS("1.4.25_Cm",                        "DI_SafetySystemEStopTBp_Cm"),
    VAR_ELEMENT_ALIAS("1.4.25_Ht",                        "DI_SafetySystemEStopTBp_Ht"),

    VAR_ELEMENT_ALIAS("3.2.25",                           "DI_SafetySystemEStopNp"),
    VAR_ELEMENT_ALIAS("3.2.25_Ss",                        "DI_SafetySystemEStopNp_Ss"),
    VAR_ELEMENT_ALIAS("3.2.25_E",                         "DI_SafetySystemEStopNp_E"),
    VAR_ELEMENT_ALIAS("3.2.25_I",                         "DI_SafetySystemEStopNp_I"),
    VAR_ELEMENT_ALIAS("3.2.25_Cm",                        "DI_SafetySystemEStopNp_Cm"),
    VAR_ELEMENT_ALIAS("3.2.25_Ht",                        "DI_SafetySystemEStopNp_Ht"),

    VAR_ELEMENT_ALIAS("3.2.27",                           "DI_SafetySystemEStopExt1"),
    VAR_ELEMENT_ALIAS("3.2.27_Ss",                        "DI_SafetySystemEStopExt1_Ss"),
    VAR_ELEMENT_ALIAS("3.2.27_E",                         "DI_SafetySystemEStopExt1_E"),
    VAR_ELEMENT_ALIAS("3.2.27_I",                         "DI_SafetySystemEStopExt1_I"),
    VAR_ELEMENT_ALIAS("3.2.27_Cm",                        "DI_SafetySystemEStopExt1_Cm"),
    VAR_ELEMENT_ALIAS("3.2.27_Ht",                        "DI_SafetySystemEStopExt1_Ht"),

    VAR_ELEMENT_ALIAS("3.2.26",                           "DI_SafetySystemEStopExt2"),
    VAR_ELEMENT_ALIAS("3.2.26_Ss",                        "DI_SafetySystemEStopExt2_Ss"),
    VAR_ELEMENT_ALIAS("3.2.26_E",                         "DI_SafetySystemEStopExt2_E"),
    VAR_ELEMENT_ALIAS("3.2.26_I",                         "DI_SafetySystemEStopExt2_I"),
    VAR_ELEMENT_ALIAS("3.2.26_Cm",                        "DI_SafetySystemEStopExt2_Cm"),
    VAR_ELEMENT_ALIAS("3.2.26_Ht",                        "DI_SafetySystemEStopExt2_Ht"),

    VAR_ELEMENT_ALIAS("3.2.28",                           "DI_SafetySystemKES"),
    VAR_ELEMENT_ALIAS("3.2.28_Ss",                        "DI_SafetySystemKES_Ss"),
    VAR_ELEMENT_ALIAS("3.2.28_E",                         "DI_SafetySystemKES_E"),
    VAR_ELEMENT_ALIAS("3.2.28_I",                         "DI_SafetySystemKES_I"),
    VAR_ELEMENT_ALIAS("3.2.28_Cm",                        "DI_SafetySystemKES_Cm"),
    VAR_ELEMENT_ALIAS("3.2.28_Ht",                        "DI_SafetySystemKES_Ht"),

    VAR_ELEMENT_ALIAS("3.3.17",                           "DO_SafetySystemEStopOESR"),

    VAR_ELEMENT_ALIAS("3.2.30",                           "DI_SafetySystemYawCam1"),
    VAR_ELEMENT_ALIAS("3.2.30_Ss",                        "DI_SafetySystemYawCam1_Ss"),
    VAR_ELEMENT_ALIAS("3.2.30_E",                         "DI_SafetySystemYawCam1_E"),
    VAR_ELEMENT_ALIAS("3.2.30_I",                         "DI_SafetySystemYawCam1_I"),
    VAR_ELEMENT_ALIAS("3.2.30_Cm",                        "DI_SafetySystemYawCam1_Cm"),
    VAR_ELEMENT_ALIAS("3.2.30_Ht",                        "DI_SafetySystemYawCam1_Ht"),

    VAR_ELEMENT_ALIAS("3.2.31",                           "DI_SafetySystemYawCam2"),
    VAR_ELEMENT_ALIAS("3.2.31_Ss",                        "DI_SafetySystemYawCam2_Ss"),
    VAR_ELEMENT_ALIAS("3.2.31_E",                         "DI_SafetySystemYawCam2_E"),
    VAR_ELEMENT_ALIAS("3.2.31_I",                         "DI_SafetySystemYawCam2_I"),
    VAR_ELEMENT_ALIAS("3.2.31_Cm",                        "DI_SafetySystemYawCam2_Cm"),
    VAR_ELEMENT_ALIAS("3.2.31_Ht",                        "DI_SafetySystemYawCam2_Ht"),

    VAR_ELEMENT_ALIAS("3.3.42",                           "DI_SafetySystemYawCableTwisted"),
    VAR_ELEMENT_ALIAS("3.3.42_Ss",                        "DI_SafetySystemYawCableTwisted_Ss"),
    VAR_ELEMENT_ALIAS("3.3.42_E",                         "DI_SafetySystemYawCableTwisted_E"),
    VAR_ELEMENT_ALIAS("3.3.42_I",                         "DI_SafetySystemYawCableTwisted_I"),
    VAR_ELEMENT_ALIAS("3.3.42_Cm",                        "DI_SafetySystemYawCableTwisted_Cm"),
    VAR_ELEMENT_ALIAS("3.3.42_Ht",                        "DI_SafetySystemYawCableTwisted_Ht"),

};
size_t EStopChain_MT_GL20101ExtStopIOVars1Size = sizeof(EStopChain_MT_GL20101ExtStopIOVars1)/sizeof(EStopChain_MT_GL20101ExtStopIOVars1[0]);

void EStopChain_MT_GL20101ExtStopSetLockValues1(void)
{
   SetLockValue("DI_SafetySystemEStopTBp_Ss",            TYP_8,     1);
   SetLockValue("DI_SafetySystemEStopTBp_E",             TYP_8,     1);
   SetValue("DI_SafetySystemEStopTBp_I",                 TYP_8,     0);
   SetLockValue("DI_SafetySystemEStopTBp_Cm",            TYP_8,     1);
   SetLockValue("DI_SafetySystemEStopTBp_Ht",            TYP_32,    20);

   SetLockValue("DI_SafetySystemEStopNp_Ss",             TYP_8,     1);
   SetLockValue("DI_SafetySystemEStopNp_E",              TYP_8,     1);
   SetValue("DI_SafetySystemEStopNp_I",                  TYP_8,     0);
   SetLockValue("DI_SafetySystemEStopNp_Cm",             TYP_8,     1);
   SetLockValue("DI_SafetySystemEStopNp_Ht",             TYP_32,    20);

   SetLockValue("DI_SafetySystemEStopExt1_Ss",           TYP_8,     1);
   SetLockValue("DI_SafetySystemEStopExt1_E",            TYP_8,     1);
   SetValue("DI_SafetySystemEStopExt1_I",                TYP_8,     0);
   SetLockValue("DI_SafetySystemEStopExt1_Cm",           TYP_8,     1);
   SetLockValue("DI_SafetySystemEStopExt1_Ht",           TYP_32,    20);

   SetLockValue("DI_SafetySystemEStopExt2_Ss",           TYP_8,     1);
   SetLockValue("DI_SafetySystemEStopExt2_E",            TYP_8,     1);
   SetValue("DI_SafetySystemEStopExt2_I",                TYP_8,     0);
   SetLockValue("DI_SafetySystemEStopExt2_Cm",           TYP_8,     1);
   SetLockValue("DI_SafetySystemEStopExt2_Ht",           TYP_32,    20);

   SetLockValue("DI_SafetySystemKES_Ss",                 TYP_8,     1);
   SetLockValue("DI_SafetySystemKES_E",                  TYP_8,     1);
   SetValue("DI_SafetySystemKES_I",                      TYP_8,     0);
   SetLockValue("DI_SafetySystemKES_Cm",                 TYP_8,     1);
   SetLockValue("DI_SafetySystemKES_Ht",                 TYP_32,    20);

   SetLockValue("DI_SafetySystemYawCam1_Ss",             TYP_8,     1);
   SetLockValue("DI_SafetySystemYawCam1_E",              TYP_8,     1);
   SetValue("DI_SafetySystemYawCam1_I",                  TYP_8,     0);
   SetLockValue("DI_SafetySystemYawCam1_Cm",             TYP_8,     1);
   SetLockValue("DI_SafetySystemYawCam1_Ht",             TYP_32,    20);

   SetLockValue("DI_SafetySystemYawCam2_Ss",             TYP_8,     1);
   SetLockValue("DI_SafetySystemYawCam2_E",              TYP_8,     1);
   SetValue("DI_SafetySystemYawCam2_I",                  TYP_8,     0);
   SetLockValue("DI_SafetySystemYawCam2_Cm",             TYP_8,     1);
   SetLockValue("DI_SafetySystemYawCam2_Ht",             TYP_32,    20);

   SetLockValue("DI_SafetySystemYawCableTwisted_Ss",     TYP_8,     1);
   SetLockValue("DI_SafetySystemYawCableTwisted_E",      TYP_8,     1);
   SetValue("DI_SafetySystemYawCableTwisted_I",          TYP_8,     0);
   SetLockValue("DI_SafetySystemYawCableTwisted_Cm",     TYP_8,     1);
   SetLockValue("DI_SafetySystemYawCableTwisted_Ht",     TYP_32,    20);
}


STATUS EStopChain_MT_GL20101ExtStopInitIOAliases()
{
   EStopChain_MT_GL20101ExtStopIOVars = EStopChain_MT_GL20101ExtStopIOVars1;
   EStopChain_MT_GL20101ExtStopIOVarsSize = EStopChain_MT_GL20101ExtStopIOVars1Size;
   EStopChain_MT_GL20101ExtStopSetLockValues = &EStopChain_MT_GL20101ExtStopSetLockValues1;
   return OS_SUCCESS;
}
//-----------------------------------------------------------------------
// AUTOGENERATED END        AUTOGENERATED END        AUTOGENERATED END
//-----------------------------------------------------------------------

#undef AUTOGENERATED_PART
