//*****************************PEPTOOL Header Start******************************
//                                                                               
//                         Copyright © 2015 Mita-Teknik.                         
//This software may only be used with WP4x00 Controllers delivered by Mita-Teknik
//                                                                               
//*******************************************************************************
//                                                                               
// $PEPTOOL version:9.0$                                                         
// $PEPTOOL file version:106$                                                    
//                                                                               
//*******************************************************************************
//                                                                               
// $Date: XXXX/XX/XX XX:XX:XX $                                                  
// $Author: XXXX\XXX $                                                           
// $RCSfile: EtillStopChain_MT_GL20101ExtStop.c,v $                              
// $Revision: X.X $                                                              
//                                                                               
//******************************PEPTOOL Header End*******************************

//***********************************************************************

// OS header files
#include <os_main.h>
// AppLib header files
#include <lib_main.h>
// App header files
#include <turbdef.h>
#include <VarMacros.h>

// Object header file
#include <EStopChain_MT_GL20101ExtStop.h>

#define AUTOGENERATED_PART
//{
//-----------------------------------------------------------------------
// AUTOGENERATED START     AUTOGENERATED START     AUTOGENERATED START
//-----------------------------------------------------------------------

#define VALIDATE_HASH
char EStopChain_MT_GL20101ExtStop_copyright[] =
{
   67, 111, 112, 121, 114, 105, 103, 104, 116, 32, 63, 32, 50, 48, 49, 53,
   32, 77, 105, 116, 97, 45, 84, 101, 107, 110, 105, 107, 46, 13, 10, 84,
   104, 105, 115, 32, 115, 111, 102, 116, 119, 97, 114, 101, 32, 109, 97, 121,
   32, 111, 110, 108, 121, 32, 98, 101, 32, 117, 115, 101, 100, 32, 119, 105,
   116, 104, 32, 87, 80, 52, 120, 48, 48, 32, 67, 111, 110, 116, 114, 111,
   108, 108, 101, 114, 115, 32, 100, 101, 108, 105, 118, 101, 114, 101, 100, 32,
   98, 121, 32, 77, 105, 116, 97, 45, 84, 101, 107, 110, 105, 107, 0
};

#define MODULE_NAME "E-Stop ChainA"

//-----------------------------------------------------------------------
// ALLOCATE MEMORY FOR STRINGS IN VARDB
//-----------------------------------------------------------------------

static char A_V_SafetySystemESCStatusText[31]  = "12345678901234567890123456789";

//-----------------------------------------------------------------------
// DEFINE LOCAL VARIABLES DEFINE LOCAL VARIABLES DEFINE LOCAL VARIABLES
//-----------------------------------------------------------------------

static struct os_db_local LocalVars[] =
{
   VAR_ELEMENT_LOCAL("V_SafetySystemESCStatusText",              TYPE_STRING + sizeof(A_V_SafetySystemESCStatusText) - 1,  PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   A_V_SafetySystemESCStatusText, 0,                0,                NULL,  NOLOG_ENABLE  ),
   VAR_ELEMENT_LOCAL("V_SafetySystemInvertOESR",                 TYPE_U8,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   0,               0,               1,               NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_SafetySystemRequestEStop",               TYPE_U8,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   0,               0,               1,               NULL,  TOTLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_SafetySystemESCStatus",                  TYPE_U8,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   0,               0,               2,               NULL,  TOTLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_SafetySystemESCSelftestSuccess",         TYPE_U8,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   1,               0,               1,               NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_SafetySystemESCSelftestInProgress",      TYPE_U8,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   0,               0,               1,               NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_SafetySystemInvertYawCam1",              TYPE_U8,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   0,               0,               1,               NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_SafetySystemInvertYawCam2",              TYPE_U8,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   0,               0,               1,               NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_SafetySystemInvertYawCableTwisted",      TYPE_U8,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   0,               0,               1,               NULL,  NOLOG_ENABLE),
};

//-----------------------------------------------------------------------
// DEFINE PARAMETERS        DEFINE PARAMETERS        DEFINE PARAMETERS
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// DEFINE BACKUPS            DEFINE BACKUPS            DEFINE BACKUPS
//-----------------------------------------------------------------------

static struct os_db_backup BackupVars[] =
{
   VAR_ELEMENT_BACKUP("B_SafetySystemEStopTimeNp",                TYPE_TIME,    PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_SERVICE,            SCALE_NONE,   0,       UNIT_NONE,          0,   (0ULL),          ((U64)U64_MIN),  ((U64)U64_MAX),  NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_BACKUP("B_SafetySystemEStopTimeTBp",               TYPE_TIME,    PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_SERVICE,            SCALE_NONE,   0,       UNIT_NONE,          0,   (0ULL),          ((U64)U64_MIN),  ((U64)U64_MAX),  NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_BACKUP("B_SafetySystemEStopTimeExt1",              TYPE_TIME,    PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_SERVICE,            SCALE_NONE,   0,       UNIT_NONE,          0,   (0ULL),          ((U64)U64_MIN),  ((U64)U64_MAX),  NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_BACKUP("B_SafetySystemEStopTimeExt2",              TYPE_TIME,    PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_SERVICE,            SCALE_NONE,   0,       UNIT_NONE,          0,   (0ULL),          ((U64)U64_MIN),  ((U64)U64_MAX),  NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_BACKUP("B_SafetySystemEStopTimeYawCam1",           TYPE_TIME,    PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_SERVICE,            SCALE_NONE,   0,       UNIT_NONE,          0,   (0ULL),          ((U64)U64_MIN),  ((U64)U64_MAX),  NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_BACKUP("B_SafetySystemEStopTimeYawCam2",           TYPE_TIME,    PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_SERVICE,            SCALE_NONE,   0,       UNIT_NONE,          0,   (0ULL),          ((U64)U64_MIN),  ((U64)U64_MAX),  NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_BACKUP("B_SafetySystemEStopTimeYawCableTwisted",   TYPE_TIME,    PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_SERVICE,            SCALE_NONE,   0,       UNIT_NONE,          0,   (0ULL),          ((U64)U64_MIN),  ((U64)U64_MAX),  NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_BACKUP("B_SafetySystemEStopTimeController",        TYPE_TIME,    PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_SERVICE,            SCALE_NONE,   0,       UNIT_NONE,          0,   (0ULL),          ((U64)U64_MIN),  ((U64)U64_MAX),  NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_BACKUP("B_SafetySystemEStopControllerService",     TYPE_U8,      PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_SERVICE,            SCALE_NONE,   0,       UNIT_NONE,          0,   0,               0,               1,               NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_BACKUP("B_SafetySystemESCSelftestDueIn",           TYPE_U32,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    3600000, UNIT_HOUR,          2,   U32_MAX,         U32_MIN,         U32_MAX,         NULL,  NOLOG_ENABLE),
};

//----------------------------------------------------------------------------------
// DEFINE VAR ARRAYS            DEFINE VAR ARRAYS            DEFINE VAR ARRAYS
//----------------------------------------------------------------------------------
char EStopChain_MT_GL20101ExtStop_initialValues[] =
{
   112, 141, 215, 172, 200, 150, 54, 135, 146, 156, 145, 252, 59, 186, 152, 168,
   101, 240, 75, 6, 36, 20, 108, 174, 140, 197, 56, 70, 168, 106, 226, 91,
   0
};

//-----------------------------------------------------------------------
// CREATE DATABASE VARS   CREATE DATABASE VARS   CREATE DATABASE VARS
//-----------------------------------------------------------------------

static STATUS CreateVarDbVars(void)
{
   STATUS Status;
   size_t ErrorEntry;

   Status = OS_VarDB_CreateLocals(LocalVars, sizeof(LocalVars)/sizeof(LocalVars[0]), &ErrorEntry, AppLocalParameterPosition());
   if (Status != 0)
   {
      AppSystemLog(ERR_7, MODULE_NAME"CrVL: %d,%d", Status, ErrorEntry);
      return ERR_7;
   }

   Status = OS_VarDB_CreateBackups(BackupVars, sizeof(BackupVars)/sizeof(BackupVars[0]), &ErrorEntry, AppLocalParameterPosition(), AppBackupPosition());
   if (Status != 0)
   {
      AppSystemLog(ERR_7, MODULE_NAME"CrVB: %d,%d", Status, ErrorEntry);
      return ERR_7;
   }

   return OS_SUCCESS;
}

#define CREATE_VARDB_VARS

//-----------------------------------------------------------------------
// CREATE IO VARIABLES     CREATE IO VARIABLES     CREATE IO VARIABLES
//-----------------------------------------------------------------------

extern STATUS EStopChain_MT_GL20101ExtStopInitIOAliases();
extern struct os_db_alias* EStopChain_MT_GL20101ExtStopIOVars;
extern void (*EStopChain_MT_GL20101ExtStopSetLockValues)(void);
extern size_t EStopChain_MT_GL20101ExtStopIOVarsSize;

static STATUS CreateIOVars(void)
{
   STATUS Status;
   size_t ErrorEntry;

   varid_t VarId;
   BOOL variablesExist = false;
   U8 counter = 50;
   Status = EStopChain_MT_GL20101ExtStopInitIOAliases();
   STATUS_LINE_VAR_RETURN_VALUE(Status)
   while (!variablesExist && counter-- > 0)
   {
      variablesExist = true;
      U32 i = 0;
      for (i = 0; i < EStopChain_MT_GL20101ExtStopIOVarsSize; ++i)
      {
         if (OS_VarDB_GetVariableID(EStopChain_MT_GL20101ExtStopIOVars[i].Name, &VarId) != OS_SUCCESS)
         {
            variablesExist = false;
            break;
         }
      }

      if (!variablesExist)
      {
         OS_Sleep(100);
      }
   }

   Status = OS_VarDB_CreateAliases(EStopChain_MT_GL20101ExtStopIOVars, EStopChain_MT_GL20101ExtStopIOVarsSize, &ErrorEntry);
   if (Status)
   {
      AppDebugLog(5000, "Var Name = %s", EStopChain_MT_GL20101ExtStopIOVars[ErrorEntry].Alias);
   }
   STATUS_LINE_VAR_RETURN_CONST(Status, ErrorEntry);
   return OS_SUCCESS;
}

#define CREATE_IO_VARS

//-----------------------------------------------------------------------
// ALIASES                       ALIASES                       ALIASES
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// INPUT                          INPUT                          INPUT
//-----------------------------------------------------------------------

// Create local variable
#define MODUL_INPUTS
static U8 DI_SafetySystemEStopTBp = 0;
static U8 DI_SafetySystemEStopNp = 0;
static U8 DI_SafetySystemEStopExt1 = 0;
static U8 DI_SafetySystemEStopExt2 = 0;
static U8 DI_SafetySystemKES = 0;
static U8 DO_SafetySystemEStopOESR = 0;
static U8 DI_SafetySystemYawCam1 = 0;
static U8 DI_SafetySystemYawCam2 = 0;
static U8 V_SafetySystemRequestEStop = 0;
static U8 V_GridErrorActive = 0;
static U8 B_SafetySystemEStopControllerService = 0;
static U8 V_SafetySystemExecuteSelftest = 0;
static U8 DI_SafetySystemYawCableTwisted = 0;
static U8 DI_SafetySystemSCMS = 0;

//-----------------------------------------------------------------------
static struct ModulInOut ModulInputs[] =
{
   {"DI_SafetySystemEStopTBp",                  &DI_SafetySystemEStopTBp,                  sizeof(DI_SafetySystemEStopTBp),                  },
   {"DI_SafetySystemEStopNp",                   &DI_SafetySystemEStopNp,                   sizeof(DI_SafetySystemEStopNp),                   },
   {"DI_SafetySystemEStopExt1",                 &DI_SafetySystemEStopExt1,                 sizeof(DI_SafetySystemEStopExt1),                 },
   {"DI_SafetySystemEStopExt2",                 &DI_SafetySystemEStopExt2,                 sizeof(DI_SafetySystemEStopExt2),                 },
   {"DI_SafetySystemKES",                       &DI_SafetySystemKES,                       sizeof(DI_SafetySystemKES),                       },
   {"DO_SafetySystemEStopOESR",                 &DO_SafetySystemEStopOESR,                 sizeof(DO_SafetySystemEStopOESR),                 },
   {"DI_SafetySystemYawCam1",                   &DI_SafetySystemYawCam1,                   sizeof(DI_SafetySystemYawCam1),                   },
   {"DI_SafetySystemYawCam2",                   &DI_SafetySystemYawCam2,                   sizeof(DI_SafetySystemYawCam2),                   },
   {"V_SafetySystemRequestEStop",               &V_SafetySystemRequestEStop,               sizeof(V_SafetySystemRequestEStop),               },
   {"V_GridErrorActive",                        &V_GridErrorActive,                        sizeof(V_GridErrorActive),                        },
   {"B_SafetySystemEStopControllerService",     &B_SafetySystemEStopControllerService,     sizeof(B_SafetySystemEStopControllerService),     },
   {"V_SafetySystemExecuteSelftest",            &V_SafetySystemExecuteSelftest,            sizeof(V_SafetySystemExecuteSelftest),            },
   {"DI_SafetySystemYawCableTwisted",           &DI_SafetySystemYawCableTwisted,           sizeof(DI_SafetySystemYawCableTwisted),           },
   {"DI_SafetySystemSCMS",                      &DI_SafetySystemSCMS,                      sizeof(DI_SafetySystemSCMS),                      },
};

//-----------------------------------------------------------------------
// Check variable type
static STATUS VarsReadReturnStatus;
static type_t ReadVarType = TYPE_NONE;
static void VarsReadTypeCheck(void)
{
   (void)VarsReadReturnStatus;
   (void)ReadVarType;
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[0].Name,                      ModulInputs[0].Id)
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[1].Name,                      ModulInputs[1].Id)
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[2].Name,                      ModulInputs[2].Id)
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[3].Name,                      ModulInputs[3].Id)
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[4].Name,                      ModulInputs[4].Id)
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[5].Name,                      ModulInputs[5].Id)
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[6].Name,                      ModulInputs[6].Id)
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[7].Name,                      ModulInputs[7].Id)
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[8].Name,                      ModulInputs[8].Id)
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[9].Name,                      ModulInputs[9].Id)
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[10].Name,                     ModulInputs[10].Id)
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[11].Name,                     ModulInputs[11].Id)
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[12].Name,                     ModulInputs[12].Id)
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[13].Name,                     ModulInputs[13].Id)
}

#undef MODUL_INPUTS
#define MODUL_INPUTS_SIZE (sizeof(ModulInputs)/sizeof(ModulInputs[0]))

//------------------------------------------------------------------------------------------
// READ/WRITE VARDB ARRAY      READ/WRITE VARDB ARRAY      READ/WRATE VARDB ARRAY
//------------------------------------------------------------------------------------------


//-----------------------------------------------------------------------
// PARAMETER                    PARAMETER                    PARAMETER
//-----------------------------------------------------------------------


//-----------------------------------------------------------------------
// READ VARS FROM VARDB    READ VARS FROM VARDB    READ VARS FROM VARDB
//-----------------------------------------------------------------------

static STATUS InputReferenceRoutine(U8 ModuleState)
{
   STATUS LocalStatus = 0;

   // Read input references
   if (ModuleState >= APP_INIT3)
   {
      // Check inputdata
      if (sizeof(ModulInputs) == 0)
      {
         AppSystemLog(ERR_4, MODULE_NAME"ModuleInputs = 0");
         return ERR_4;
      }
      // Read inputdata
      LocalStatus = OS_ReadVariables(ModulInputs, MODUL_INPUTS_SIZE);
      if (LocalStatus != 0)
      {
         AppSystemLog(ERR_4, MODULE_NAME"ReadVErr: element=%d elementpointer=0x%x", LocalStatus, &ModulInputs[LocalStatus]);
         return ERR_4;
      }
   }
   return 0;
}

#define READ_VARS

//-----------------------------------------------------------------------
// OUTPUT                         OUTPUT                         OUTPUT
//-----------------------------------------------------------------------

// Create local variable
#define MODUL_OUTPUTS
static U8 V_SafetySystemESCStatus = 0;
static U8 V_SafetySystemInvertOESR = 0;
static time_t B_SafetySystemEStopTimeNp = 0;
static time_t B_SafetySystemEStopTimeTBp = 0;
static time_t B_SafetySystemEStopTimeExt1 = 0;
static time_t B_SafetySystemEStopTimeYawCam1 = 0;
static time_t B_SafetySystemEStopTimeYawCam2 = 0;
static time_t B_SafetySystemEStopTimeYawCableTwisted = 0;
static time_t B_SafetySystemEStopTimeController = 0;
static U8 V_SafetySystemESCSelftestSuccess = 0;
static U8 V_SafetySystemESCSelftestInProgress = 0;
static U32 B_SafetySystemESCSelftestDueIn = 0;
static U8 V_SafetySystemInvertYawCam1 = 0;
static U8 V_SafetySystemInvertYawCam2 = 0;
static U8 V_SafetySystemInvertYawCableTwisted = 0;
static time_t B_SafetySystemEStopTimeExt2 = 0;
static char V_SafetySystemESCStatusText[31];


//-----------------------------------------------------------------------
static struct ModulInOut ModulOutputs[] =
{
   {"V_SafetySystemESCStatusText",              &V_SafetySystemESCStatusText,              sizeof(V_SafetySystemESCStatusText),              },
   {"V_SafetySystemESCStatus",                  &V_SafetySystemESCStatus,                  sizeof(V_SafetySystemESCStatus),                  },
   {"V_SafetySystemInvertOESR",                 &V_SafetySystemInvertOESR,                 sizeof(V_SafetySystemInvertOESR),                 },
   {"DO_SafetySystemEStopOESR",                 &DO_SafetySystemEStopOESR,                 sizeof(DO_SafetySystemEStopOESR),                 },
   {"B_SafetySystemEStopTimeNp",                &B_SafetySystemEStopTimeNp,                sizeof(B_SafetySystemEStopTimeNp),                },
   {"B_SafetySystemEStopTimeTBp",               &B_SafetySystemEStopTimeTBp,               sizeof(B_SafetySystemEStopTimeTBp),               },
   {"B_SafetySystemEStopTimeExt1",              &B_SafetySystemEStopTimeExt1,              sizeof(B_SafetySystemEStopTimeExt1),              },
   {"B_SafetySystemEStopTimeYawCam1",           &B_SafetySystemEStopTimeYawCam1,           sizeof(B_SafetySystemEStopTimeYawCam1),           },
   {"B_SafetySystemEStopTimeYawCam2",           &B_SafetySystemEStopTimeYawCam2,           sizeof(B_SafetySystemEStopTimeYawCam2),           },
   {"B_SafetySystemEStopTimeYawCableTwisted",   &B_SafetySystemEStopTimeYawCableTwisted,   sizeof(B_SafetySystemEStopTimeYawCableTwisted),   },
   {"B_SafetySystemEStopTimeController",        &B_SafetySystemEStopTimeController,        sizeof(B_SafetySystemEStopTimeController),        },
   {"V_SafetySystemESCSelftestSuccess",         &V_SafetySystemESCSelftestSuccess,         sizeof(V_SafetySystemESCSelftestSuccess),         },
   {"V_SafetySystemESCSelftestInProgress",      &V_SafetySystemESCSelftestInProgress,      sizeof(V_SafetySystemESCSelftestInProgress),      },
   {"B_SafetySystemESCSelftestDueIn",           &B_SafetySystemESCSelftestDueIn,           sizeof(B_SafetySystemESCSelftestDueIn),           },
   {"V_SafetySystemInvertYawCam1",              &V_SafetySystemInvertYawCam1,              sizeof(V_SafetySystemInvertYawCam1),              },
   {"V_SafetySystemInvertYawCam2",              &V_SafetySystemInvertYawCam2,              sizeof(V_SafetySystemInvertYawCam2),              },
   {"V_SafetySystemInvertYawCableTwisted",      &V_SafetySystemInvertYawCableTwisted,      sizeof(V_SafetySystemInvertYawCableTwisted),      },
   {"B_SafetySystemEStopTimeExt2",              &B_SafetySystemEStopTimeExt2,              sizeof(B_SafetySystemEStopTimeExt2),              },
};

//-----------------------------------------------------------------------
// Check variable type
static STATUS VarsWriteReturnStatus;
static type_t WriteVarType = TYPE_NONE;
static void VarsWriteTypeCheck(void)
{
   (void)VarsWriteReturnStatus;
   (void)WriteVarType;
   VERIFY_OUTPUT_STRING_REF_ID(STRING,     ModulOutputs[0].Name,                      ModulOutputs[0].Id, 0)
   VERIFY_OUTPUT_REF_ID(U8,        ModulOutputs[1].Name,                     ModulOutputs[1].Id,                       0)
   VERIFY_OUTPUT_REF_ID(U8,        ModulOutputs[2].Name,                     ModulOutputs[2].Id,                       0)
   VERIFY_OUTPUT_REF_ID(U8,        ModulOutputs[3].Name,                     ModulOutputs[3].Id,                       0)
   VERIFY_OUTPUT_TIME_REF_ID(time_t,       ModulOutputs[4].Name,                     ModulOutputs[4].Id,                       0)
   VERIFY_OUTPUT_TIME_REF_ID(time_t,       ModulOutputs[5].Name,                     ModulOutputs[5].Id,                       0)
   VERIFY_OUTPUT_TIME_REF_ID(time_t,       ModulOutputs[6].Name,                     ModulOutputs[6].Id,                       0)
   VERIFY_OUTPUT_TIME_REF_ID(time_t,       ModulOutputs[7].Name,                     ModulOutputs[7].Id,                       0)
   VERIFY_OUTPUT_TIME_REF_ID(time_t,       ModulOutputs[8].Name,                     ModulOutputs[8].Id,                       0)
   VERIFY_OUTPUT_TIME_REF_ID(time_t,       ModulOutputs[9].Name,                     ModulOutputs[9].Id,                       0)
   VERIFY_OUTPUT_TIME_REF_ID(time_t,       ModulOutputs[10].Name,                    ModulOutputs[10].Id,                      0)
   VERIFY_OUTPUT_REF_ID(U8,        ModulOutputs[11].Name,                    ModulOutputs[11].Id,                      0)
   VERIFY_OUTPUT_REF_ID(U8,        ModulOutputs[12].Name,                    ModulOutputs[12].Id,                      0)
   VERIFY_OUTPUT_REF_ID(U32,       ModulOutputs[13].Name,                    ModulOutputs[13].Id,                      0)
   VERIFY_OUTPUT_REF_ID(U8,        ModulOutputs[14].Name,                    ModulOutputs[14].Id,                      0)
   VERIFY_OUTPUT_REF_ID(U8,        ModulOutputs[15].Name,                    ModulOutputs[15].Id,                      0)
   VERIFY_OUTPUT_REF_ID(U8,        ModulOutputs[16].Name,                    ModulOutputs[16].Id,                      0)
   VERIFY_OUTPUT_TIME_REF_ID(time_t,       ModulOutputs[17].Name,                    ModulOutputs[17].Id,                      0)
}

#undef MODUL_OUTPUTS
#define MODUL_OUTPUTS_SIZE (sizeof(ModulOutputs)/sizeof(ModulOutputs[0]))

//-----------------------------------------------------------------------
// WRITE VARS TO VARDB     WRITE VARS TO VARDB     WRITE VARS TO VARDB
//-----------------------------------------------------------------------

static STATUS InitOutputVars(void)
{
   STATUS LocalStatus;
   // Read outputdata
   LocalStatus = OS_ReadVariables(ModulOutputs, MODUL_OUTPUTS_SIZE);
   if (LocalStatus != 0)
   {
      AppSystemLog(ERR_4, MODULE_NAME"InitErr: element=%d elementpointer=0x%x", LocalStatus, &ModulOutputs[LocalStatus]);
      return ERR_4;
   }
   return OS_SUCCESS;
}
static STATUS OutputReferenceRoutine(U8 ModuleState)
{
   STATUS LocalStatus = 0;
   // Write Outputdata
   LocalStatus = OS_WriteVariablesConditional(ModulOutputs, MODUL_OUTPUTS_SIZE);
   if (LocalStatus != 0)
   {
      AppSystemLog(ERR_5, MODULE_NAME"WriteVErr: element=%d elementpointer=0x%x", LocalStatus, &ModulOutputs[LocalStatus]);
      return ERR_5;
   }
   return 0;
}

#define WRITE_VARS

//-----------------------------------------------------------------------
// VERIFY VARIABLES CREATION                 VERIFY VARIABLES CREATION
//-----------------------------------------------------------------------

static STATUS LocalIoCheck(void)
{
   // Check if input variables exist.
   STATUS LocalStatus;

   LocalStatus = OS_DoesVariablesExist(ModulInputs, MODUL_INPUTS_SIZE);
   if (LocalStatus != 0)
   {
      AppSystemLog(ERR_1, MODULE_NAME"InputErr: %d", LocalStatus);
      AppSystemLog(ERR_1, "Name: %s", ModulInputs[LocalStatus-1].Name);
      return ERR_1;
   }
   (void)VarsReadTypeCheck();

   LocalStatus = OS_DoesVariablesExist(ModulOutputs, MODUL_OUTPUTS_SIZE);
   if (LocalStatus != 0)
   {
      AppSystemLog(ERR_2, MODULE_NAME"OutputErr: %d", LocalStatus);
      AppSystemLog(ERR_2, "Name: %s", ModulOutputs[LocalStatus-1].Name);
      return ERR_2;
   }
   (void)VarsWriteTypeCheck();

   return OS_SUCCESS;
}

#define VERIFY_VARIABLES

//-----------------------------------------------------------------------
// ALLOCATE MEMORY FOR SUMMATIONS        ALLOCATE MEMORY FOR SUMMATIONS
//-----------------------------------------------------------------------


//-----------------------------------------------------------------------
// SUMMATIONS                  SUMMATIONS                  SUMMATIONS
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// DEFINE MENUS               DEFINE MENUS               DEFINE MENUS
//-----------------------------------------------------------------------



// Menu line and link to local menu
//-----------------------------------------------------------------------
static struct line_struct M_EToStopChainLinkToLocalMenu[] =
{
   MENU_ELEMENT_LINE_LINK("E-Stop Chain",                      PASSWORD_LEVEL_END_CUSTOMER,        "M_EToStopChain",                   "G_EtillStopChain_MT_GL20101ExtStop"),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_EToStopChainMenu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_EToStopChain",                   PASSWORD_LEVEL_END_CUSTOMER),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_EToStopChainMenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("E-STOP CHAIN",                      PASSWORD_LEVEL_END_CUSTOMER,        "M_"APP_ID"AppMain",                "G_"APP_ID"App"),
   MENU_ELEMENT_LINE_VARRO("E-Stop Chain Status",              PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_SafetySystemESCStatusText",                LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_LINK("Status",                            PASSWORD_LEVEL_END_CUSTOMER,        "M_Status381",                      "G_EtillStopChain_MT_GL20101ExtStop"),
   MENU_ELEMENT_LINE_LINK("Service",                           PASSWORD_LEVEL_SERVICE,             "M_Service201",                     "G_EtillStopChain_MT_GL20101ExtStop"),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_Status381Menu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_Status381",                      PASSWORD_LEVEL_END_CUSTOMER),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_Status381MenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("STATUS",                            PASSWORD_LEVEL_END_CUSTOMER,        "M_EToStopChain",                   "G_EtillStopChain_MT_GL20101ExtStop"),
   MENU_ELEMENT_LINE_VARRO("E-Stop Tower Base Panel (S1.1)",   PASSWORD_LEVEL_END_CUSTOMER,        (char*)"DI_SafetySystemEStopTBp",                    LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("E-Stop External 1 (S1.3)",         PASSWORD_LEVEL_END_CUSTOMER,        (char*)"DI_SafetySystemEStopExt1",                   LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("E-Stop External 2 (Power Panel)",  PASSWORD_LEVEL_END_CUSTOMER,        (char*)"DI_SafetySystemEStopExt2",                   LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("E-Stop Nacelle Panel (S1.4)",      PASSWORD_LEVEL_END_CUSTOMER,        (char*)"DI_SafetySystemEStopNp",                     LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("E-Stop Cable Twist (Y) Cam 1",     PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_SafetySystemInvertYawCam1",                LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("E-Stop Cable Twist (Y) Cam 2",     PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_SafetySystemInvertYawCam2",                LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("E-Stop Yaw Cable Twisted",         PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_SafetySystemInvertYawCableTwisted",        LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("E-Stop Control System (OESR)",     PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_SafetySystemInvertOESR",                   LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("E-Stop Relay (KES)",               PASSWORD_LEVEL_END_CUSTOMER,        (char*)"DI_SafetySystemKES",                         LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("E-Stop Yaw Bypass Switch (SYFB)",  PASSWORD_LEVEL_END_CUSTOMER,        (char*)"DI_SafetySystemSCMS",                        LINE_FORMAT_NONE),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_Service201Menu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_Service201",                     PASSWORD_LEVEL_SERVICE),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_Service201MenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("SERVICE",                           PASSWORD_LEVEL_SERVICE,             "M_EToStopChain",                   "G_EtillStopChain_MT_GL20101ExtStop"),
   MENU_ELEMENT_LINE_VARRW("Manual E-Stop (OESR)",             PASSWORD_LEVEL_SERVICE,             (char*)"B_SafetySystemEStopControllerService",       LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Control System Request E-Stop",    PASSWORD_LEVEL_SERVICE,             (char*)"V_SafetySystemRequestEStop",                 LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_TEXT("Last Time Activations:",            PASSWORD_LEVEL_SERVICE),
   MENU_ELEMENT_LINE_VARRO("E-Stop (TBp)",                     PASSWORD_LEVEL_SERVICE,             (char*)"B_SafetySystemEStopTimeTBp",                 LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("E-Stop (Np)",                      PASSWORD_LEVEL_SERVICE,             (char*)"B_SafetySystemEStopTimeNp",                  LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("E-Stop Ext. 1",                    PASSWORD_LEVEL_SERVICE,             (char*)"B_SafetySystemEStopTimeExt1",                LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("E-Stop Ext. 2",                    PASSWORD_LEVEL_SERVICE,             (char*)"B_SafetySystemEStopTimeExt2",                LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("E-Stop Yaw Cam 1",                 PASSWORD_LEVEL_SERVICE,             (char*)"B_SafetySystemEStopTimeYawCam1",             LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("E-Stop Yaw Cam 2",                 PASSWORD_LEVEL_SERVICE,             (char*)"B_SafetySystemEStopTimeYawCam2",             LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("E-Stop Yaw Cable Twisted",         PASSWORD_LEVEL_SERVICE,             (char*)"B_SafetySystemEStopTimeYawCableTwisted",     LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("E-Stop Control System",            PASSWORD_LEVEL_SERVICE,             (char*)"B_SafetySystemEStopTimeController",          LINE_FORMAT_NONE),
};
// Creating parameters for multiplexed categories
//-----------------------------------------------------------------------
static struct multiplexed_info_struct M_EToStopChainMultiplexedCategoriesParameters[] =
{
0};

//-----------------------------------------------------------------------
// CREATE MENUS               CREATE MENUS               CREATE MENUS
//-----------------------------------------------------------------------

// Memory reservation
//-----------------------------------------------------------------------
static struct menu_group_struct ObjGroup[1];

// Creating the menus
//-----------------------------------------------------------------------
STATUS EStopChain_MT_GL20101ExtStopMenuAppInit(U8 ModuleState, OS_MEMORY_POOL* pPool)
{
   STATUS Status;

   if (ModuleState == APP_INIT1)
   {
      /* Create application group */
      Status = OS_CreateMenuGroup(ObjGroup, M_EToStopChainLinkToLocalMenu[0].LinkGroup);
      STATUS_LINE_VAR_RETURN_VALUE(Status);
   }

   Status = CreateAndInitializeMenu(ModuleState,
                                    M_EToStopChainMenuLines[0].LinkGroup,
                                    M_EToStopChainMenuLines[0].LinkName,
                                    ELEMENT(M_EToStopChainLinkToLocalMenu),
                                    M_EToStopChainLinkToLocalMenu[0].LinkGroup,
                                    ELEMENT(M_EToStopChainMenu),
                                    M_EToStopChainLinkToLocalMenu[0].LinkName,
                                    ELEMENT(M_EToStopChainMenuLines),
                                    pPool,
                                    M_EToStopChainMultiplexedCategoriesParameters);
   STATUS_LINE_VAR_RETURN_VALUE(Status);

   Status = CreateAndInitializeMenu(ModuleState,
                                    M_Status381MenuLines[0].LinkGroup,
                                    M_Status381MenuLines[0].LinkName,
                                    NULL,
                                    0,
                                    M_EToStopChainMenuLines[2].LinkGroup,
                                    ELEMENT(M_Status381Menu),
                                    M_EToStopChainMenuLines[2].LinkName,
                                    ELEMENT(M_Status381MenuLines),
                                    pPool,
                                    M_EToStopChainMultiplexedCategoriesParameters);
   STATUS_LINE_VAR_RETURN_VALUE(Status);

   Status = CreateAndInitializeMenu(ModuleState,
                                    M_Service201MenuLines[0].LinkGroup,
                                    M_Service201MenuLines[0].LinkName,
                                    NULL,
                                    0,
                                    M_EToStopChainMenuLines[3].LinkGroup,
                                    ELEMENT(M_Service201Menu),
                                    M_EToStopChainMenuLines[3].LinkName,
                                    ELEMENT(M_Service201MenuLines),
                                    pPool,
                                    M_EToStopChainMultiplexedCategoriesParameters);
   STATUS_LINE_VAR_RETURN_VALUE(Status);

   return OS_SUCCESS;
}

#define CREATE_MENU

//-----------------------------------------------------------------------
//               BUTTONS FUNCTIONS FORWARD DECLARATIONS
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// BUTTONS                       BUTTONS                      BUTTONS
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
//             SET/RESET FUNCTIONS FORWARD DECLARATIONS
//-----------------------------------------------------------------------
//-----------------------------------------------------------------------
// STATUSCODES                 STATUSCODES                 STATUSCODES
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// MODIFIABLE                  MODIFIABLE                   MODIFIABLE
//-----------------------------------------------------------------------

extern const char EStopChain_MT_GL20101ExtStopAppGroupName[];
extern const char EStopChain_MT_GL20101ExtStopAppMenuName[];

static void Init_Structures_From_Conf_File(void)
{
   M_EToStopChainMenuLines[0].LinkName = (char*)EStopChain_MT_GL20101ExtStopAppMenuName;
   M_EToStopChainMenuLines[0].LinkGroup = (char*)EStopChain_MT_GL20101ExtStopAppGroupName;
}

//-----------------------------------------------------------------------
// AUTOGENERATED END        AUTOGENERATED END        AUTOGENERATED END
//-----------------------------------------------------------------------
//}

#undef AUTOGENERATED_PART

//-----------------------------------------------------------------------
// USER DEFINITIONS         USER DEFINITIONS         USER DEFINITIONS
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// SET/RESET FUNCTIONS    SET/RESET FUNCTIONS    SET/RESET FUNCTIONS
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// DRIVER FUNCTION         DRIVER FUNCTION         DRIVER FUNCTION
//-----------------------------------------------------------------------
  
//-----------------------------------------------------------------------
// INIT                   INIT                     INIT
//-----------------------------------------------------------------------
  
//-----------------------------------------------------------------------
// CONTROL                CONTROL                 CONTROL
//-----------------------------------------------------------------------
  
static STATUS LocalCtrl( U32 Interval )
{
   STATUS LocalStatus = 0;

   return LocalStatus;
}

static STATUS ShutdownCtrl( U8 ModuleState, U8 *DoneState, U32 Interval )
{
    STATUS LocalStatus = 0;

    LocalStatus = LocalCtrl( Interval );
    STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);

    switch( ModuleState )
    {
        case AS_SHUTDOWN:
        {
            // Activate "Manual Shutdown" status code

            *DoneState = AS_SHUTDOWN;
            break;
        }
        case AS_REBOOT:
        {

            *DoneState = AS_REBOOT;
            break;
        }
        case AS_SHUTDOWN_FAST:
        {

            *DoneState = AS_SHUTDOWN_FAST;
            break;
        }
        default:
        {
            *DoneState = ModuleState;
            break;
        }
    }
    return LocalStatus;
}
 
//-----------------------------------------------------------------------
// MAIN CALL             MAIN CALL               MAIN CALL
//-----------------------------------------------------------------------

STATUS EStopChain_MT_GL20101ExtStop( U8 ModuleState, U8 *DoneState , U32 Interval )
{
   STATUS LocalStatus = 0;

   #ifdef READ_VARS
      // Read input data
      LocalStatus = InputReferenceRoutine(ModuleState);
      STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
   #endif
   #ifdef COMMON_VDB_READ
      LocalStatus = ReadVdbWindow(ModuleState);
      STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
   #endif


   switch( ModuleState )
   {
      //__________________________________________________________________________
      case APP_RUN:
      {
         #ifdef FUNCTION_BLOCKS_PRE_LOCAL_CONTROL
            LocalStatus = FunctionBlocksPreLocalCtrl( Interval );
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif
         
         LocalStatus = LocalCtrl( Interval );
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);

         #ifdef FUNCTION_BLOCKS_POST_LOCAL_CONTROL
            LocalStatus = FunctionBlocksPostLocalCtrl( Interval );
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef WRITE_VARS
            // Write Output data
            LocalStatus = OutputReferenceRoutine(ModuleState);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef COMMON_VDB_WRITE
            LocalStatus = WriteVdbWindow(ModuleState);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         *DoneState = APP_RUN;
         break;
      }
      //__________________________________________________________________________
      case APP_INIT1:
      {
         // Version check
         LocalStatus = OS_ValidateAPI( API_VERSION_MAJOR,
                                API_VERSION_MINOR,
                                OS_LinkTime,
                                ReleaseTag,
                                __MODULE__
                               );
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);

         Init_Structures_From_Conf_File();

         #ifdef CREATE_VARDB_VARS
            LocalStatus = CreateVarDbVars();
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef CREATE_MENU
            LocalStatus = EStopChain_MT_GL20101ExtStopMenuAppInit(ModuleState, GetMemPool());
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);

            #ifdef MULTIPLEXIBLE_MENU
               LocalStatus = MenuArraysAppInit(ModuleState, GetMemPool());
               STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
            #endif
         #endif

         #ifdef CREATE_VARDB_ARRAY_VARS
               LocalStatus = CreateVdbArrays(GetMemPool());
               STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
         #endif


         #ifdef CREATE_IO_VARS
               LocalStatus = CreateIOVars();
               STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
         #endif

         *DoneState = APP_INIT1;

         break;
      }
      //__________________________________________________________________________
      case APP_INIT2:
      {
         #ifdef CREATE_MENU
            #ifdef MULTIPLEXIBLE_MENU
               LocalStatus = MenuArraysAppInit(ModuleState, GetMemPool());
               STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
            #endif
         #endif

         #ifdef CREATE_ALIASES
               size_t ErrorEntry = 0;
               LocalStatus = OS_VarDB_CreateAliases(AliasVars, sizeof(AliasVars)/sizeof(AliasVars[0]), &ErrorEntry);
               STATUS_LINE_VAR_RETURN_CONST(LocalStatus, ErrorEntry);
         #endif

         #ifdef VERIFY_ARRAY
               LocalStatus = VerifyArray(GetMemPool());
               STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef VERIFY_VARIABLES
               LocalStatus = LocalIoCheck();
               STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef CREATE_BUTTONS
               LocalStatus = CreateButtons();
               STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         *DoneState = APP_INIT2;

         break;
      }
      //__________________________________________________________________________
      case APP_INIT3 :
      {
         #ifdef CREATE_SUMMATIONS
            LocalStatus = CreateSummations();
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef WRITE_VARS
            LocalStatus = InitOutputVars();
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef CREATE_STATUS_CODES
            LocalStatus = LocalStatusCodeInit();
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef CREATE_IO_VARS
           EStopChain_MT_GL20101ExtStopSetLockValues();
         #endif

         *DoneState = APP_INIT3;

         break;
      }
      //__________________________________________________________________________
      case APP_INIT4:
      {
         #ifdef CREATE_MENU
            LocalStatus = EStopChain_MT_GL20101ExtStopMenuAppInit(ModuleState, GetMemPool());
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);

            #ifdef MULTIPLEXIBLE_MENU
               LocalStatus = MenuArraysAppInit(ModuleState, GetMemPool());
               STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
            #endif
         #endif

         *DoneState = APP_INIT4;

         break;
      }
      //__________________________________________________________________________
      case APP_INIT5:
      {
         #ifdef VALIDATE_HASH
            LocalStatus = ValidateHash( EStopChain_MT_GL20101ExtStop_copyright, MODULE_NAME, EStopChain_MT_GL20101ExtStop_initialValues);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef INIT_FUNCTION_BLOCKS
            LocalStatus = FunctionBlocksInit( Interval );
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         *DoneState = APP_INIT5_DONE;

         break;
      }
      //__________________________________________________________________________
      //Other initialization round can be inserted here
      //__________________________________________________________________________
      case AS_SHUTDOWN:
      {
         LocalStatus = ShutdownCtrl ( ModuleState, DoneState, Interval );
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);

         #ifdef WRITE_VARS
            // Write Output data
            LocalStatus = OutputReferenceRoutine(ModuleState);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef COMMON_VDB_WRITE
            LocalStatus = WriteVdbWindow(ModuleState);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         break;
      }
      //__________________________________________________________________________
      case AS_REBOOT:
      {
         LocalStatus = ShutdownCtrl ( ModuleState, DoneState, Interval );
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);

         #ifdef WRITE_VARS
            // Write Output data
            LocalStatus = OutputReferenceRoutine(ModuleState);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef COMMON_VDB_WRITE
            LocalStatus = WriteVdbWindow(ModuleState);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         break;
      }
      //__________________________________________________________________________
      case AS_SHUTDOWN_FAST:
      {
         LocalStatus = ShutdownCtrl ( ModuleState, DoneState, Interval );
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);

         #ifdef WRITE_VARS
            // Write Output data
            LocalStatus = OutputReferenceRoutine(ModuleState);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef COMMON_VDB_WRITE
            LocalStatus = WriteVdbWindow(ModuleState);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         break;
      }
      default:
      {
         *DoneState = ModuleState;

         break;
      }
   }
   return OS_SUCCESS;
}
//-----------------------------------------------------------------------
