//*****************************PEPTOOL Header Start******************************
//                                                                               
//                         Copyright © 2015 Mita-Teknik.                         
//This software may only be used with WP4x00 Controllers delivered by Mita-Teknik
//                                                                               
//*******************************************************************************
//                                                                               
// $PEPTOOL version:9.0$                                                         
// $PEPTOOL file version:106$                                                    
//                                                                               
//*******************************************************************************
//                                                                               
// $Date: XXXX/XX/XX XX:XX:XX $                                                  
// $Author: XXXX\XXX $                                                           
// $RCSfile: FileInterface.c,v $                                                 
// $Revision: X.X $                                                              
//                                                                               
//******************************PEPTOOL Header End*******************************

//***********************************************************************

// OS header files
#include <os_main.h>
// AppLib header files
#include <lib_main.h>
// App header files
#include <turbdef.h>
#include <VarMacros.h>

// Object header file
#include <FileInterface.h>

#define AUTOGENERATED_PART
//{
//-----------------------------------------------------------------------
// AUTOGENERATED START     AUTOGENERATED START     AUTOGENERATED START
//-----------------------------------------------------------------------

#define VALIDATE_HASH
char FileInterface_copyright[] =
{
   67, 111, 112, 121, 114, 105, 103, 104, 116, 32, 63, 32, 50, 48, 49, 53,
   32, 77, 105, 116, 97, 45, 84, 101, 107, 110, 105, 107, 46, 13, 10, 84,
   104, 105, 115, 32, 115, 111, 102, 116, 119, 97, 114, 101, 32, 109, 97, 121,
   32, 111, 110, 108, 121, 32, 98, 101, 32, 117, 115, 101, 100, 32, 119, 105,
   116, 104, 32, 87, 80, 52, 120, 48, 48, 32, 67, 111, 110, 116, 114, 111,
   108, 108, 101, 114, 115, 32, 100, 101, 108, 105, 118, 101, 114, 101, 100, 32,
   98, 121, 32, 77, 105, 116, 97, 45, 84, 101, 107, 110, 105, 107, 0
};

#define MODULE_NAME "File InterfaceA"

//-----------------------------------------------------------------------
// ALLOCATE MEMORY FOR STRINGS IN VARDB
//-----------------------------------------------------------------------

static char A_V_FileInterfaceToTxt[31]  = "012345678901234567890123456789";
static char A_V_FileInterfaceFrTxt[31]  = "012345678901234567890123456789";

//-----------------------------------------------------------------------
// DEFINE LOCAL VARIABLES DEFINE LOCAL VARIABLES DEFINE LOCAL VARIABLES
//-----------------------------------------------------------------------

static struct os_db_local LocalVars[] =
{
   VAR_ELEMENT_LOCAL("V_FileInterfaceToTxt",                     TYPE_STRING + sizeof(A_V_FileInterfaceToTxt) - 1,  PASSWORD_LEVEL_LICENCE_PROGRAMMER, PASSWORD_LEVEL_MITA_PROGRAMMER,    SCALE_NONE,   0,       UNIT_NONE,          0,   A_V_FileInterfaceToTxt, 0,                0,                NULL,  NOLOG_ENABLE  ),
   VAR_ELEMENT_LOCAL("V_FileInterfaceToOperation",               TYPE_U32,     PASSWORD_LEVEL_LICENCE_PROGRAMMER, PASSWORD_LEVEL_MITA_PROGRAMMER,    SCALE_NONE,   0,       UNIT_NONE,          0,   0,               0,               0,               NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_FileInterfaceToCount",                   TYPE_U32,     PASSWORD_LEVEL_LICENCE_PROGRAMMER, PASSWORD_LEVEL_MITA_PROGRAMMER,    SCALE_NONE,   0,       UNIT_NONE,          0,   0,               0,               0,               NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_FileInterfaceToStatus",                  TYPE_S32,     PASSWORD_LEVEL_LICENCE_PROGRAMMER, PASSWORD_LEVEL_MITA_PROGRAMMER,    SCALE_NONE,   0,       UNIT_NONE,          0,   0,               0,               0,               NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_FileInterfaceFrTxt",                     TYPE_STRING + sizeof(A_V_FileInterfaceFrTxt) - 1,  PASSWORD_LEVEL_LICENCE_PROGRAMMER, PASSWORD_LEVEL_MITA_PROGRAMMER,    SCALE_NONE,   0,       UNIT_NONE,          0,   A_V_FileInterfaceFrTxt, 0,                0,                NULL,  NOLOG_ENABLE  ),
   VAR_ELEMENT_LOCAL("V_FileInterfaceFrOperation",               TYPE_U32,     PASSWORD_LEVEL_LICENCE_PROGRAMMER, PASSWORD_LEVEL_MITA_PROGRAMMER,    SCALE_NONE,   0,       UNIT_NONE,          0,   0,               0,               0,               NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_FileInterfaceFrCount",                   TYPE_U32,     PASSWORD_LEVEL_LICENCE_PROGRAMMER, PASSWORD_LEVEL_MITA_PROGRAMMER,    SCALE_NONE,   0,       UNIT_NONE,          0,   0,               0,               0,               NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_FileInterfaceFrStatus",                  TYPE_S32,     PASSWORD_LEVEL_LICENCE_PROGRAMMER, PASSWORD_LEVEL_MITA_PROGRAMMER,    SCALE_NONE,   0,       UNIT_NONE,          0,   0,               0,               0,               NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL_U64("V_FileInterfaceTimeUse",                            PASSWORD_LEVEL_LICENCE_PROGRAMMER, PASSWORD_LEVEL_MITA_PROGRAMMER,    SCALE_DIV,    1000,    UNIT_SECOND,        3,   0ULL,            0ULL,            0ULL,            NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_FileInterfaceReadTimeStamp",             TYPE_TIME,    PASSWORD_LEVEL_LICENCE_PROGRAMMER, PASSWORD_LEVEL_MITA_PROGRAMMER,    SCALE_NONE,   0,       UNIT_NONE,          0,   (0ULL),          (0ULL),          (0ULL),          NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_FileInterfaceWriteTimeStamp",            TYPE_TIME,    PASSWORD_LEVEL_LICENCE_PROGRAMMER, PASSWORD_LEVEL_MITA_PROGRAMMER,    SCALE_NONE,   0,       UNIT_NONE,          0,   (0ULL),          (0ULL),          (0ULL),          NULL,  NOLOG_ENABLE),
};

//-----------------------------------------------------------------------
// DEFINE PARAMETERS        DEFINE PARAMETERS        DEFINE PARAMETERS
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// DEFINE BACKUPS            DEFINE BACKUPS            DEFINE BACKUPS
//-----------------------------------------------------------------------

//----------------------------------------------------------------------------------
// DEFINE VAR ARRAYS            DEFINE VAR ARRAYS            DEFINE VAR ARRAYS
//----------------------------------------------------------------------------------
char FileInterface_initialValues[] =
{
   16, 191, 77, 210, 30, 49, 247, 123, 25, 183, 109, 26, 119, 253, 68, 125,
   91, 27, 15, 130, 43, 172, 34, 155, 188, 78, 17, 92, 95, 132, 170, 193,
   0
};

//-----------------------------------------------------------------------
// CREATE DATABASE VARS   CREATE DATABASE VARS   CREATE DATABASE VARS
//-----------------------------------------------------------------------

static STATUS CreateVarDbVars(void)
{
   STATUS Status;
   size_t ErrorEntry;

   Status = OS_VarDB_CreateLocals(LocalVars, sizeof(LocalVars)/sizeof(LocalVars[0]), &ErrorEntry, AppLocalParameterPosition());
   if (Status != 0)
   {
      AppSystemLog(ERR_7, MODULE_NAME"CrVL: %d,%d", Status, ErrorEntry);
      return ERR_7;
   }

   return OS_SUCCESS;
}

#define CREATE_VARDB_VARS

//-----------------------------------------------------------------------
// CREATE IO VARIABLES     CREATE IO VARIABLES     CREATE IO VARIABLES
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// ALIASES                       ALIASES                       ALIASES
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// INPUT                          INPUT                          INPUT
//-----------------------------------------------------------------------

//------------------------------------------------------------------------------------------
// READ/WRITE VARDB ARRAY      READ/WRITE VARDB ARRAY      READ/WRATE VARDB ARRAY
//------------------------------------------------------------------------------------------


//-----------------------------------------------------------------------
// PARAMETER                    PARAMETER                    PARAMETER
//-----------------------------------------------------------------------


//-----------------------------------------------------------------------
// READ VARS FROM VARDB    READ VARS FROM VARDB    READ VARS FROM VARDB
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// OUTPUT                         OUTPUT                         OUTPUT
//-----------------------------------------------------------------------

// Create local variable
#define MODUL_OUTPUTS
static U32 V_FileInterfaceToOperation = 0;
static U32 V_FileInterfaceToCount = 0;
static S32 V_FileInterfaceToStatus = 0;
static U32 V_FileInterfaceFrOperation = 0;
static U32 V_FileInterfaceFrCount = 0;
static S32 V_FileInterfaceFrStatus = 0;
static U64 V_FileInterfaceTimeUse = 0;
static time_t V_FileInterfaceReadTimeStamp = 0;
static time_t V_FileInterfaceWriteTimeStamp = 0;


//-----------------------------------------------------------------------
static struct ModulInOut ModulOutputs[] =
{
   {"V_FileInterfaceToOperation",               &V_FileInterfaceToOperation,               sizeof(V_FileInterfaceToOperation),               },
   {"V_FileInterfaceToCount",                   &V_FileInterfaceToCount,                   sizeof(V_FileInterfaceToCount),                   },
   {"V_FileInterfaceToStatus",                  &V_FileInterfaceToStatus,                  sizeof(V_FileInterfaceToStatus),                  },
   {"V_FileInterfaceFrOperation",               &V_FileInterfaceFrOperation,               sizeof(V_FileInterfaceFrOperation),               },
   {"V_FileInterfaceFrCount",                   &V_FileInterfaceFrCount,                   sizeof(V_FileInterfaceFrCount),                   },
   {"V_FileInterfaceFrStatus",                  &V_FileInterfaceFrStatus,                  sizeof(V_FileInterfaceFrStatus),                  },
   {"V_FileInterfaceTimeUse",                   &V_FileInterfaceTimeUse,                   sizeof(V_FileInterfaceTimeUse),                   },
   {"V_FileInterfaceReadTimeStamp",             &V_FileInterfaceReadTimeStamp,             sizeof(V_FileInterfaceReadTimeStamp),             },
   {"V_FileInterfaceWriteTimeStamp",            &V_FileInterfaceWriteTimeStamp,            sizeof(V_FileInterfaceWriteTimeStamp),            },
};

//-----------------------------------------------------------------------
// Check variable type
static STATUS VarsWriteReturnStatus;
static type_t WriteVarType = TYPE_NONE;
static void VarsWriteTypeCheck(void)
{
   (void)VarsWriteReturnStatus;
   (void)WriteVarType;
   VERIFY_OUTPUT_REF_ID(U32,       ModulOutputs[0].Name,                     ModulOutputs[0].Id,                       0)
   VERIFY_OUTPUT_REF_ID(U32,       ModulOutputs[1].Name,                     ModulOutputs[1].Id,                       0)
   VERIFY_OUTPUT_REF_ID(S32,       ModulOutputs[2].Name,                     ModulOutputs[2].Id,                       0)
   VERIFY_OUTPUT_REF_ID(U32,       ModulOutputs[3].Name,                     ModulOutputs[3].Id,                       0)
   VERIFY_OUTPUT_REF_ID(U32,       ModulOutputs[4].Name,                     ModulOutputs[4].Id,                       0)
   VERIFY_OUTPUT_REF_ID(S32,       ModulOutputs[5].Name,                     ModulOutputs[5].Id,                       0)
   VERIFY_OUTPUT_REF_ID(U64,       ModulOutputs[6].Name,                     ModulOutputs[6].Id,                       0)
   VERIFY_OUTPUT_TIME_REF_ID(time_t,       ModulOutputs[7].Name,                     ModulOutputs[7].Id,                       0)
   VERIFY_OUTPUT_TIME_REF_ID(time_t,       ModulOutputs[8].Name,                     ModulOutputs[8].Id,                       0)
}

#undef MODUL_OUTPUTS
#define MODUL_OUTPUTS_SIZE (sizeof(ModulOutputs)/sizeof(ModulOutputs[0]))

//-----------------------------------------------------------------------
// WRITE VARS TO VARDB     WRITE VARS TO VARDB     WRITE VARS TO VARDB
//-----------------------------------------------------------------------

static STATUS InitOutputVars(void)
{
   STATUS LocalStatus;
   // Read outputdata
   LocalStatus = OS_ReadVariables(ModulOutputs, MODUL_OUTPUTS_SIZE);
   if (LocalStatus != 0)
   {
      AppSystemLog(ERR_4, MODULE_NAME"InitErr: element=%d elementpointer=0x%x", LocalStatus, &ModulOutputs[LocalStatus]);
      return ERR_4;
   }
   return OS_SUCCESS;
}
static STATUS OutputReferenceRoutine(U8 ModuleState)
{
   STATUS LocalStatus = 0;
   // Write Outputdata
   LocalStatus = OS_WriteVariablesConditional(ModulOutputs, MODUL_OUTPUTS_SIZE);
   if (LocalStatus != 0)
   {
      AppSystemLog(ERR_5, MODULE_NAME"WriteVErr: element=%d elementpointer=0x%x", LocalStatus, &ModulOutputs[LocalStatus]);
      return ERR_5;
   }
   return 0;
}

#define WRITE_VARS

//-----------------------------------------------------------------------
// VERIFY VARIABLES CREATION                 VERIFY VARIABLES CREATION
//-----------------------------------------------------------------------

static STATUS LocalIoCheck(void)
{
   // Check if input variables exist.
   STATUS LocalStatus;

   LocalStatus = OS_DoesVariablesExist(ModulOutputs, MODUL_OUTPUTS_SIZE);
   if (LocalStatus != 0)
   {
      AppSystemLog(ERR_2, MODULE_NAME"OutputErr: %d", LocalStatus);
      AppSystemLog(ERR_2, "Name: %s", ModulOutputs[LocalStatus-1].Name);
      return ERR_2;
   }
   (void)VarsWriteTypeCheck();

   return OS_SUCCESS;
}

#define VERIFY_VARIABLES

//-----------------------------------------------------------------------
// ALLOCATE MEMORY FOR SUMMATIONS        ALLOCATE MEMORY FOR SUMMATIONS
//-----------------------------------------------------------------------


//-----------------------------------------------------------------------
// SUMMATIONS                  SUMMATIONS                  SUMMATIONS
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// DEFINE MENUS               DEFINE MENUS               DEFINE MENUS
//-----------------------------------------------------------------------



// Menu line and link to local menu
//-----------------------------------------------------------------------
static struct line_struct M_FileInterfaceLinkToLocalMenu[] =
{
   MENU_ELEMENT_LINE_LINK("File Interface",                    PASSWORD_LEVEL_END_CUSTOMER,        "M_FileInterface",                  "G_FileInterface"),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_FileInterfaceMenu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_FileInterface",                  PASSWORD_LEVEL_END_CUSTOMER),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_FileInterfaceMenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("FILE INTERFACE",                    PASSWORD_LEVEL_END_CUSTOMER,        "M_"APP_ID"AppMain",                "G_"APP_ID"App"),
   MENU_ELEMENT_LINE_LINK("Debug",                             PASSWORD_LEVEL_LICENCE_PROGRAMMER,  "M_Status1",                        "G_FileInterface"),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_Status1Menu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_Status1",                        PASSWORD_LEVEL_LICENCE_PROGRAMMER),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_Status1MenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("DEBUG",                             PASSWORD_LEVEL_LICENCE_PROGRAMMER,  "M_FileInterface",                  "G_FileInterface"),
   MENU_ELEMENT_LINE_VARRO("Last ToQ FileName",                PASSWORD_LEVEL_LICENCE_PROGRAMMER,  (char*)"V_FileInterfaceToTxt",                       LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Last ToQ operation",               PASSWORD_LEVEL_LICENCE_PROGRAMMER,  (char*)"V_FileInterfaceToOperation",                 LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Last ToQ Count",                   PASSWORD_LEVEL_LICENCE_PROGRAMMER,  (char*)"V_FileInterfaceToCount",                     LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Last ToQ Status",                  PASSWORD_LEVEL_LICENCE_PROGRAMMER,  (char*)"V_FileInterfaceToStatus",                    LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Last FrQ FileName",                PASSWORD_LEVEL_LICENCE_PROGRAMMER,  (char*)"V_FileInterfaceFrTxt",                       LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Last FrQ operation",               PASSWORD_LEVEL_LICENCE_PROGRAMMER,  (char*)"V_FileInterfaceFrOperation",                 LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Last FrQ Count",                   PASSWORD_LEVEL_LICENCE_PROGRAMMER,  (char*)"V_FileInterfaceFrCount",                     LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Last FrQ Status",                  PASSWORD_LEVEL_LICENCE_PROGRAMMER,  (char*)"V_FileInterfaceFrStatus",                    LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Last read operation",              PASSWORD_LEVEL_LICENCE_PROGRAMMER,  (char*)"V_FileInterfaceReadTimeStamp",               LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Last block write",                 PASSWORD_LEVEL_LICENCE_PROGRAMMER,  (char*)"V_FileInterfaceWriteTimeStamp",              LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Last time use",                    PASSWORD_LEVEL_LICENCE_PROGRAMMER,  (char*)"V_FileInterfaceTimeUse",                     LINE_FORMAT_NONE),
};
// Creating parameters for multiplexed categories
//-----------------------------------------------------------------------
static struct multiplexed_info_struct M_FileInterfaceMultiplexedCategoriesParameters[] =
{0
};

//-----------------------------------------------------------------------
// CREATE MENUS               CREATE MENUS               CREATE MENUS
//-----------------------------------------------------------------------

// Memory reservation
//-----------------------------------------------------------------------
static struct menu_group_struct ObjGroup[1];

// Creating the menus
//-----------------------------------------------------------------------
STATUS FileInterfaceMenuAppInit(U8 ModuleState, OS_MEMORY_POOL* pPool)
{
   STATUS Status;

   if (ModuleState == APP_INIT1)
   {
      /* Create application group */
      Status = OS_CreateMenuGroup(ObjGroup, M_FileInterfaceLinkToLocalMenu[0].LinkGroup);
      STATUS_LINE_VAR_RETURN_VALUE(Status);
   }

   Status = CreateAndInitializeMenu(ModuleState,
                                    M_FileInterfaceMenuLines[0].LinkGroup,
                                    M_FileInterfaceMenuLines[0].LinkName,
                                    ELEMENT(M_FileInterfaceLinkToLocalMenu),
                                    M_FileInterfaceLinkToLocalMenu[0].LinkGroup,
                                    ELEMENT(M_FileInterfaceMenu),
                                    M_FileInterfaceLinkToLocalMenu[0].LinkName,
                                    ELEMENT(M_FileInterfaceMenuLines),
                                    pPool,
                                    M_FileInterfaceMultiplexedCategoriesParameters);
   STATUS_LINE_VAR_RETURN_VALUE(Status);

   Status = CreateAndInitializeMenu(ModuleState,
                                    M_Status1MenuLines[0].LinkGroup,
                                    M_Status1MenuLines[0].LinkName,
                                    NULL,
                                    0,
                                    M_FileInterfaceMenuLines[1].LinkGroup,
                                    ELEMENT(M_Status1Menu),
                                    M_FileInterfaceMenuLines[1].LinkName,
                                    ELEMENT(M_Status1MenuLines),
                                    pPool,
                                    M_FileInterfaceMultiplexedCategoriesParameters);
   STATUS_LINE_VAR_RETURN_VALUE(Status);

   return OS_SUCCESS;
}

#define CREATE_MENU

//-----------------------------------------------------------------------
//               BUTTONS FUNCTIONS FORWARD DECLARATIONS
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// BUTTONS                       BUTTONS                      BUTTONS
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
//             SET/RESET FUNCTIONS FORWARD DECLARATIONS
//-----------------------------------------------------------------------
//-----------------------------------------------------------------------
// STATUSCODES                 STATUSCODES                 STATUSCODES
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// MODIFIABLE                  MODIFIABLE                   MODIFIABLE
//-----------------------------------------------------------------------

extern const char FileInterfaceAppGroupName[];
extern const char FileInterfaceAppMenuName[];

static void Init_Structures_From_Conf_File(void)
{
   M_FileInterfaceMenuLines[0].LinkName = (char*)FileInterfaceAppMenuName;
   M_FileInterfaceMenuLines[0].LinkGroup = (char*)FileInterfaceAppGroupName;
}

//-----------------------------------------------------------------------
// AUTOGENERATED END        AUTOGENERATED END        AUTOGENERATED END
//-----------------------------------------------------------------------
//}

#undef AUTOGENERATED_PART

//-----------------------------------------------------------------------
// USER DEFINITIONS         USER DEFINITIONS         USER DEFINITIONS
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// SET/RESET FUNCTIONS    SET/RESET FUNCTIONS    SET/RESET FUNCTIONS
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// DRIVER FUNCTION         DRIVER FUNCTION         DRIVER FUNCTION
//-----------------------------------------------------------------------
  
//-----------------------------------------------------------------------
// INIT                   INIT                     INIT
//-----------------------------------------------------------------------
  
//-----------------------------------------------------------------------
// CONTROL                CONTROL                 CONTROL
//-----------------------------------------------------------------------
  
static STATUS LocalCtrl( U32 Interval )
{
   STATUS LocalStatus = 0;

   return LocalStatus;
}

static STATUS ShutdownCtrl( U8 ModuleState, U8 *DoneState, U32 Interval )
{
    STATUS LocalStatus = 0;

    LocalStatus = LocalCtrl( Interval );
    STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);

    switch( ModuleState )
    {
        case AS_SHUTDOWN:
        {
            // Activate "Manual Shutdown" status code

            *DoneState = AS_SHUTDOWN;
            break;
        }
        case AS_REBOOT:
        {

            *DoneState = AS_REBOOT;
            break;
        }
        case AS_SHUTDOWN_FAST:
        {

            *DoneState = AS_SHUTDOWN_FAST;
            break;
        }
        default:
        {
            *DoneState = ModuleState;
            break;
        }
    }
    return LocalStatus;
}
 
//-----------------------------------------------------------------------
// MAIN CALL             MAIN CALL               MAIN CALL
//-----------------------------------------------------------------------

STATUS FileInterface( U8 ModuleState, U8 *DoneState , U32 Interval )
{
   STATUS LocalStatus = 0;

   #ifdef READ_VARS
      // Read input data
      LocalStatus = InputReferenceRoutine(ModuleState);
      STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
   #endif
   #ifdef COMMON_VDB_READ
      LocalStatus = ReadVdbWindow(ModuleState);
      STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
   #endif


   switch( ModuleState )
   {
      //__________________________________________________________________________
      case APP_RUN:
      {
         #ifdef FUNCTION_BLOCKS_PRE_LOCAL_CONTROL
            LocalStatus = FunctionBlocksPreLocalCtrl( Interval );
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif
         
         LocalStatus = LocalCtrl( Interval );
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);

         #ifdef FUNCTION_BLOCKS_POST_LOCAL_CONTROL
            LocalStatus = FunctionBlocksPostLocalCtrl( Interval );
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef WRITE_VARS
            // Write Output data
            LocalStatus = OutputReferenceRoutine(ModuleState);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef COMMON_VDB_WRITE
            LocalStatus = WriteVdbWindow(ModuleState);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         *DoneState = APP_RUN;
         break;
      }
      //__________________________________________________________________________
      case APP_INIT1:
      {
         // Version check
         LocalStatus = OS_ValidateAPI( API_VERSION_MAJOR,
                                API_VERSION_MINOR,
                                OS_LinkTime,
                                ReleaseTag,
                                __MODULE__
                               );
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);

         Init_Structures_From_Conf_File();

         #ifdef CREATE_VARDB_VARS
            LocalStatus = CreateVarDbVars();
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef CREATE_MENU
            LocalStatus = FileInterfaceMenuAppInit(ModuleState, GetMemPool());
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);

            #ifdef MULTIPLEXIBLE_MENU
               LocalStatus = MenuArraysAppInit(ModuleState, GetMemPool());
               STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
            #endif
         #endif

         #ifdef CREATE_VARDB_ARRAY_VARS
               LocalStatus = CreateVdbArrays(GetMemPool());
               STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
         #endif


         #ifdef CREATE_IO_VARS
               LocalStatus = CreateIOVars();
               STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
         #endif

         *DoneState = APP_INIT1;

         break;
      }
      //__________________________________________________________________________
      case APP_INIT2:
      {
         #ifdef CREATE_MENU
            #ifdef MULTIPLEXIBLE_MENU
               LocalStatus = MenuArraysAppInit(ModuleState, GetMemPool());
               STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
            #endif
         #endif

         #ifdef CREATE_ALIASES
               size_t ErrorEntry = 0;
               LocalStatus = OS_VarDB_CreateAliases(AliasVars, sizeof(AliasVars)/sizeof(AliasVars[0]), &ErrorEntry);
               STATUS_LINE_VAR_RETURN_CONST(LocalStatus, ErrorEntry);
         #endif

         #ifdef VERIFY_ARRAY
               LocalStatus = VerifyArray(GetMemPool());
               STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef VERIFY_VARIABLES
               LocalStatus = LocalIoCheck();
               STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef CREATE_BUTTONS
               LocalStatus = CreateButtons();
               STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         *DoneState = APP_INIT2;

         break;
      }
      //__________________________________________________________________________
      case APP_INIT3 :
      {
         #ifdef CREATE_SUMMATIONS
            LocalStatus = CreateSummations();
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef WRITE_VARS
            LocalStatus = InitOutputVars();
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef CREATE_STATUS_CODES
            LocalStatus = LocalStatusCodeInit();
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef CREATE_IO_VARS
           FileInterfaceSetLockValues();
         #endif

         *DoneState = APP_INIT3;

         break;
      }
      //__________________________________________________________________________
      case APP_INIT4:
      {
         #ifdef CREATE_MENU
            LocalStatus = FileInterfaceMenuAppInit(ModuleState, GetMemPool());
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);

            #ifdef MULTIPLEXIBLE_MENU
               LocalStatus = MenuArraysAppInit(ModuleState, GetMemPool());
               STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
            #endif
         #endif

         *DoneState = APP_INIT4;

         break;
      }
      //__________________________________________________________________________
      case APP_INIT5:
      {
         #ifdef VALIDATE_HASH
            LocalStatus = ValidateHash( FileInterface_copyright, MODULE_NAME, FileInterface_initialValues);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef INIT_FUNCTION_BLOCKS
            LocalStatus = FunctionBlocksInit( Interval );
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         *DoneState = APP_INIT5_DONE;

         break;
      }
      //__________________________________________________________________________
      //Other initialization round can be inserted here
      //__________________________________________________________________________
      case AS_SHUTDOWN:
      {
         LocalStatus = ShutdownCtrl ( ModuleState, DoneState, Interval );
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);

         #ifdef WRITE_VARS
            // Write Output data
            LocalStatus = OutputReferenceRoutine(ModuleState);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef COMMON_VDB_WRITE
            LocalStatus = WriteVdbWindow(ModuleState);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         break;
      }
      //__________________________________________________________________________
      case AS_REBOOT:
      {
         LocalStatus = ShutdownCtrl ( ModuleState, DoneState, Interval );
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);

         #ifdef WRITE_VARS
            // Write Output data
            LocalStatus = OutputReferenceRoutine(ModuleState);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef COMMON_VDB_WRITE
            LocalStatus = WriteVdbWindow(ModuleState);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         break;
      }
      //__________________________________________________________________________
      case AS_SHUTDOWN_FAST:
      {
         LocalStatus = ShutdownCtrl ( ModuleState, DoneState, Interval );
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);

         #ifdef WRITE_VARS
            // Write Output data
            LocalStatus = OutputReferenceRoutine(ModuleState);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef COMMON_VDB_WRITE
            LocalStatus = WriteVdbWindow(ModuleState);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         break;
      }
      default:
      {
         *DoneState = ModuleState;

         break;
      }
   }
   return OS_SUCCESS;
}
//-----------------------------------------------------------------------
