//*****************************PEPTOOL Header Start******************************
//                                                                               
//                         Copyright © 2015 Mita-Teknik.                         
//This software may only be used with WP4x00 Controllers delivered by Mita-Teknik
//                                                                               
//*******************************************************************************
//                                                                               
// $PEPTOOL version:9.0$                                                         
// $PEPTOOL file version:101$                                                    
//                                                                               
//*******************************************************************************
//                                                                               
// $Date: 2014/03/04 14:22:43 $                                                  
// $Author: MITA\ihn $                                                           
// $RCSfile: FlightWarningLight_Conf.c,v $                                       
// $Revision: 1.8 $                                                              
//                                                                               
//******************************PEPTOOL Header End*******************************

//***********************************************************************
// OS header files
#include <os_main.h>
// IO init file
#include <InitIo.h>
      
#define AUTOGENERATED_PART

#include <Turbdef.h>

//-----------------------------------------------------------------------
// AUTOGENERATED START     AUTOGENERATED START     AUTOGENERATED START
//-----------------------------------------------------------------------
char FlightWarningLight_Conf_copyright[] =
{
   67, 111, 112, 121, 114, 105, 103, 104, 116, 32, 63, 32, 50, 48, 49, 53,
   32, 77, 105, 116, 97, 45, 84, 101, 107, 110, 105, 107, 46, 13, 10, 84,
   104, 105, 115, 32, 115, 111, 102, 116, 119, 97, 114, 101, 32, 109, 97, 121,
   32, 111, 110, 108, 121, 32, 98, 101, 32, 117, 115, 101, 100, 32, 119, 105,
   116, 104, 32, 87, 80, 52, 120, 48, 48, 32, 67, 111, 110, 116, 114, 111,
   108, 108, 101, 114, 115, 32, 100, 101, 108, 105, 118, 101, 114, 101, 100, 32,
   98, 121, 32, 77, 105, 116, 97, 45, 84, 101, 107, 110, 105, 107, 0
};
//-----------------------------------------------------------------------
// MODIFIABLE                  MODIFIABLE               MODIFIABLE
//-----------------------------------------------------------------------
const char FlightWarningLightAppGroupName[] = "G_"APP_ID"App";
const char FlightWarningLightAppMenuName[] = "M_"APP_ID"AppMain";

//-----------------------------------------------------------------------
// IO VARIABLES                IO VARIABLES                IO VARIABLES
//-----------------------------------------------------------------------

void (*FlightWarningLightSetLockValues)(void);
struct os_db_alias *FlightWarningLightIOVars;
size_t FlightWarningLightIOVarsSize = 0;
            
struct os_db_alias FlightWarningLightIOVars1[]=
{
    VAR_ELEMENT_ALIAS("3.2.46",                           "DI_ObstructionLightAlarm"),
    VAR_ELEMENT_ALIAS("3.2.46_Ss",                        "DI_ObstructionLightAlarm_Ss"),
    VAR_ELEMENT_ALIAS("3.2.46_E",                         "DI_ObstructionLightAlarm_E"),
    VAR_ELEMENT_ALIAS("3.2.46_I",                         "DI_ObstructionLightAlarm_I"),
    VAR_ELEMENT_ALIAS("3.2.46_Cm",                        "DI_ObstructionLightAlarm_Cm"),
    VAR_ELEMENT_ALIAS("3.2.46_Ht",                        "DI_ObstructionLightAlarm_Ht"),

};
size_t FlightWarningLightIOVars1Size = sizeof(FlightWarningLightIOVars1)/sizeof(FlightWarningLightIOVars1[0]);

void FlightWarningLightSetLockValues1(void)
{
   SetLockValue("DI_ObstructionLightAlarm_Ss",           TYP_8,     1);
   SetLockValue("DI_ObstructionLightAlarm_E",            TYP_8,     1);
   SetValue("DI_ObstructionLightAlarm_I",                TYP_8,     0);
   SetLockValue("DI_ObstructionLightAlarm_Cm",           TYP_8,     1);
   SetLockValue("DI_ObstructionLightAlarm_Ht",           TYP_32,    1000);
}


STATUS FlightWarningLightInitIOAliases()
{
   FlightWarningLightIOVars = FlightWarningLightIOVars1;
   FlightWarningLightIOVarsSize = FlightWarningLightIOVars1Size;
   FlightWarningLightSetLockValues = &FlightWarningLightSetLockValues1;
   return OS_SUCCESS;
}
//-----------------------------------------------------------------------
// AUTOGENERATED END        AUTOGENERATED END        AUTOGENERATED END
//-----------------------------------------------------------------------

#undef AUTOGENERATED_PART
