//*****************************PEPTOOL Header Start******************************
//                                                                               
//                         Copyright © 2015 Mita-Teknik.                         
//This software may only be used with WP4x00 Controllers delivered by Mita-Teknik
//                                                                               
//*******************************************************************************
//                                                                               
// $PEPTOOL version:9.0$                                                         
// $PEPTOOL file version:106$                                                    
//                                                                               
//*******************************************************************************
//                                                                               
// $Date: 2014/05/23 09:10:01 $                                                  
// $Author: MITA\ihn $                                                           
// $RCSfile: FlightWarningLight.c,v $                                            
// $Revision: 1.11 $                                                             
//                                                                               
//******************************PEPTOOL Header End*******************************
// OS header files
#include <os_main.h>
// AppLib header files
#include <lib_main.h>
// App header files
#include <turbdef.h>
#include <VarMacros.h>
// Object header file
#include <FlightWarningLight.h>


#define AUTOGENERATED_PART
//{
//-----------------------------------------------------------------------
// AUTOGENERATED START     AUTOGENERATED START     AUTOGENERATED START
//-----------------------------------------------------------------------

#define VALIDATE_HASH
char FlightWarningLight_copyright[] =
{
   67, 111, 112, 121, 114, 105, 103, 104, 116, 32, 63, 32, 50, 48, 49, 53,
   32, 77, 105, 116, 97, 45, 84, 101, 107, 110, 105, 107, 46, 13, 10, 84,
   104, 105, 115, 32, 115, 111, 102, 116, 119, 97, 114, 101, 32, 109, 97, 121,
   32, 111, 110, 108, 121, 32, 98, 101, 32, 117, 115, 101, 100, 32, 119, 105,
   116, 104, 32, 87, 80, 52, 120, 48, 48, 32, 67, 111, 110, 116, 114, 111,
   108, 108, 101, 114, 115, 32, 100, 101, 108, 105, 118, 101, 114, 101, 100, 32,
   98, 121, 32, 77, 105, 116, 97, 45, 84, 101, 107, 110, 105, 107, 0
};

#define MODULE_NAME "Flight Warning LightA"

//-----------------------------------------------------------------------
// ALLOCATE MEMORY FOR STRINGS IN VARDB
//-----------------------------------------------------------------------


//-----------------------------------------------------------------------
// DEFINE LOCAL VARIABLES DEFINE LOCAL VARIABLES DEFINE LOCAL VARIABLES
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// DEFINE PARAMETERS        DEFINE PARAMETERS        DEFINE PARAMETERS
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// DEFINE BACKUPS            DEFINE BACKUPS            DEFINE BACKUPS
//-----------------------------------------------------------------------

//----------------------------------------------------------------------------------
// DEFINE VAR ARRAYS            DEFINE VAR ARRAYS            DEFINE VAR ARRAYS
//----------------------------------------------------------------------------------
char FlightWarningLight_initialValues[] =
{
   59, 86, 31, 236, 192, 62, 74, 119, 80, 83, 21, 112, 248, 248, 196, 87,
   48, 202, 234, 75, 209, 27, 124, 146, 200, 233, 118, 181, 223, 208, 182, 202,
   0
};

//-----------------------------------------------------------------------
// CREATE DATABASE VARS   CREATE DATABASE VARS   CREATE DATABASE VARS
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// CREATE IO VARIABLES     CREATE IO VARIABLES     CREATE IO VARIABLES
//-----------------------------------------------------------------------

extern STATUS FlightWarningLightInitIOAliases();
extern struct os_db_alias* FlightWarningLightIOVars;
extern void (*FlightWarningLightSetLockValues)(void);
extern size_t FlightWarningLightIOVarsSize;

static STATUS CreateIOVars(void)
{
   STATUS Status;
   size_t ErrorEntry;

   varid_t VarId;
   BOOL variablesExist = false;
   U8 counter = 50;
   Status = FlightWarningLightInitIOAliases();
   STATUS_LINE_VAR_RETURN_VALUE(Status)
   while (!variablesExist && counter-- > 0)
   {
      variablesExist = true;
      U32 i = 0;
      for (i = 0; i < FlightWarningLightIOVarsSize; ++i)
      {
         if (OS_VarDB_GetVariableID(FlightWarningLightIOVars[i].Name, &VarId) != OS_SUCCESS)
         {
            variablesExist = false;
            break;
         }
      }

      if (!variablesExist)
      {
         OS_Sleep(100);
      }
   }

   Status = OS_VarDB_CreateAliases(FlightWarningLightIOVars, FlightWarningLightIOVarsSize, &ErrorEntry);
   if (Status)
   {
      AppDebugLog(5000, "Var Name = %s", FlightWarningLightIOVars[ErrorEntry].Alias);
   }
   STATUS_LINE_VAR_RETURN_CONST(Status, ErrorEntry);
   return OS_SUCCESS;
}

#define CREATE_IO_VARS

//-----------------------------------------------------------------------
// ALIASES                       ALIASES                       ALIASES
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// INPUT                          INPUT                          INPUT
//-----------------------------------------------------------------------

// Create local variable
#define MODUL_INPUTS
static U8 DI_ObstructionLightAlarm = 0;

//-----------------------------------------------------------------------
static struct ModulInOut ModulInputs[] =
{
   {"DI_ObstructionLightAlarm",                 &DI_ObstructionLightAlarm,                 sizeof(DI_ObstructionLightAlarm),                 },
};

//-----------------------------------------------------------------------
// Check variable type
static STATUS VarsReadReturnStatus;
static type_t ReadVarType = TYPE_NONE;
static void VarsReadTypeCheck(void)
{
   (void)VarsReadReturnStatus;
   (void)ReadVarType;
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[0].Name,                      ModulInputs[0].Id)
}

#undef MODUL_INPUTS
#define MODUL_INPUTS_SIZE (sizeof(ModulInputs)/sizeof(ModulInputs[0]))

//------------------------------------------------------------------------------------------
// READ/WRITE VARDB ARRAY      READ/WRITE VARDB ARRAY      READ/WRATE VARDB ARRAY
//------------------------------------------------------------------------------------------


//-----------------------------------------------------------------------
// PARAMETER                    PARAMETER                    PARAMETER
//-----------------------------------------------------------------------


//-----------------------------------------------------------------------
// READ VARS FROM VARDB    READ VARS FROM VARDB    READ VARS FROM VARDB
//-----------------------------------------------------------------------

static STATUS InputReferenceRoutine(U8 ModuleState)
{
   STATUS LocalStatus = 0;

   // Read input references
   if (ModuleState >= APP_INIT3)
   {
      // Check inputdata
      if (sizeof(ModulInputs) == 0)
      {
         AppSystemLog(ERR_4, MODULE_NAME"ModuleInputs = 0");
         return ERR_4;
      }
      // Read inputdata
      LocalStatus = OS_ReadVariables(ModulInputs, MODUL_INPUTS_SIZE);
      if (LocalStatus != 0)
      {
         AppSystemLog(ERR_4, MODULE_NAME"ReadVErr: element=%d elementpointer=0x%x", LocalStatus, &ModulInputs[LocalStatus]);
         return ERR_4;
      }
   }
   return 0;
}

#define READ_VARS

//-----------------------------------------------------------------------
// OUTPUT                         OUTPUT                         OUTPUT
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// WRITE VARS TO VARDB     WRITE VARS TO VARDB     WRITE VARS TO VARDB
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// VERIFY VARIABLES CREATION                 VERIFY VARIABLES CREATION
//-----------------------------------------------------------------------

static STATUS LocalIoCheck(void)
{
   // Check if input variables exist.
   STATUS LocalStatus;

   LocalStatus = OS_DoesVariablesExist(ModulInputs, MODUL_INPUTS_SIZE);
   if (LocalStatus != 0)
   {
      AppSystemLog(ERR_1, MODULE_NAME"InputErr: %d", LocalStatus);
      AppSystemLog(ERR_1, "Name: %s", ModulInputs[LocalStatus-1].Name);
      return ERR_1;
   }
   (void)VarsReadTypeCheck();

   return OS_SUCCESS;
}

#define VERIFY_VARIABLES

//-----------------------------------------------------------------------
// ALLOCATE MEMORY FOR SUMMATIONS        ALLOCATE MEMORY FOR SUMMATIONS
//-----------------------------------------------------------------------


//-----------------------------------------------------------------------
// SUMMATIONS                  SUMMATIONS                  SUMMATIONS
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// DEFINE MENUS               DEFINE MENUS               DEFINE MENUS
//-----------------------------------------------------------------------



// Menu line and link to local menu
//-----------------------------------------------------------------------
static struct line_struct M_ObjMainLinkToLocalMenu[] =
{
   MENU_ELEMENT_LINE_LINK("Flight Warning Light",              PASSWORD_LEVEL_END_CUSTOMER,        "M_ObjMain",                        "G_Flight"),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_ObjMainMenu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_ObjMain",                        PASSWORD_LEVEL_END_CUSTOMER),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_ObjMainMenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("FLIGHT WARNING LIGHT",              PASSWORD_LEVEL_END_CUSTOMER,        "M_"APP_ID"AppMain",                "G_"APP_ID"App"),
   MENU_ELEMENT_LINE_LINK("Status",                            PASSWORD_LEVEL_END_CUSTOMER,        "M_Status",                         "G_Flight"),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_StatusMenu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_Status",                         PASSWORD_LEVEL_END_CUSTOMER),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_StatusMenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("STATUS",                            PASSWORD_LEVEL_END_CUSTOMER,        "M_ObjMain",                        "G_Flight"),
   MENU_ELEMENT_LINE_VARRO("Flight Warning Light OK",          PASSWORD_LEVEL_END_CUSTOMER,        (char*)"DI_ObstructionLightAlarm",                   LINE_FORMAT_NONE),
};
// Creating parameters for multiplexed categories
//-----------------------------------------------------------------------
static struct multiplexed_info_struct M_ObjMainMultiplexedCategoriesParameters[] =
{
0};

//-----------------------------------------------------------------------
// CREATE MENUS               CREATE MENUS               CREATE MENUS
//-----------------------------------------------------------------------

// Memory reservation
//-----------------------------------------------------------------------
static struct menu_group_struct ObjGroup[1];

// Creating the menus
//-----------------------------------------------------------------------
STATUS FlightWarningLightMenuAppInit(U8 ModuleState, OS_MEMORY_POOL* pPool)
{
   STATUS Status;

   if (ModuleState == APP_INIT1)
   {
      /* Create application group */
      Status = OS_CreateMenuGroup(ObjGroup, M_ObjMainLinkToLocalMenu[0].LinkGroup);
      STATUS_LINE_VAR_RETURN_VALUE(Status);
   }

   Status = CreateAndInitializeMenu(ModuleState,
                                    M_ObjMainMenuLines[0].LinkGroup,
                                    M_ObjMainMenuLines[0].LinkName,
                                    ELEMENT(M_ObjMainLinkToLocalMenu),
                                    M_ObjMainLinkToLocalMenu[0].LinkGroup,
                                    ELEMENT(M_ObjMainMenu),
                                    M_ObjMainLinkToLocalMenu[0].LinkName,
                                    ELEMENT(M_ObjMainMenuLines),
                                    pPool,
                                    M_ObjMainMultiplexedCategoriesParameters);
   STATUS_LINE_VAR_RETURN_VALUE(Status);

   Status = CreateAndInitializeMenu(ModuleState,
                                    M_StatusMenuLines[0].LinkGroup,
                                    M_StatusMenuLines[0].LinkName,
                                    NULL,
                                    0,
                                    M_ObjMainMenuLines[1].LinkGroup,
                                    ELEMENT(M_StatusMenu),
                                    M_ObjMainMenuLines[1].LinkName,
                                    ELEMENT(M_StatusMenuLines),
                                    pPool,
                                    M_ObjMainMultiplexedCategoriesParameters);
   STATUS_LINE_VAR_RETURN_VALUE(Status);

   return OS_SUCCESS;
}

#define CREATE_MENU

//-----------------------------------------------------------------------
//               BUTTONS FUNCTIONS FORWARD DECLARATIONS
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// BUTTONS                       BUTTONS                      BUTTONS
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
//             SET/RESET FUNCTIONS FORWARD DECLARATIONS
//-----------------------------------------------------------------------
static U8 StatusSetFunc1569(void);
static U8 StatusResetFunc1569(void);
//-----------------------------------------------------------------------
// STATUSCODES                 STATUSCODES                 STATUSCODES
//-----------------------------------------------------------------------

static struct sts_statuscode_structure StatusCodes[] =
{
   STS_CODE_ELEMENT("Flight warn.ligh.def",   20*SEC,    1569,      STATUSCODE_UPDATE_TYPE_POLLING,         PASSWORD_LEVEL_SERVICE,            STATUSCODE_TIMER_TYPE_CONSTANT,     STATUSCODE_TIMER_TYPE_CONSTANT,     STATUSCODE_RESET_TYPE_AUTOMATIC,    STATUSCODE_PRIORITY_LOW,       27,   1,    32,   NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    StatusSetFunc1569,       StatusResetFunc1569,     BRAKE_PROG_0,        BRAKE_PROG_0,        BRAKE_PROG_MAX,      NULL,                PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    YAW_PROG_0,          YAW_PROG_0,          YAW_PROG_240,        NULL,                PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    1,    0,    255,  NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            1,  PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      1000,      20,        1000,      NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         SETDELAY_MIN,   SETDELAY_MAX,   NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      0,         RESETDELAY_MIN, RESETDELAY_MAX, NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      0,         REPEATTIMES_MIN,     REPEATTIMES_MAX,     NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         REPEATPERIOD_MIN,    REPEATPERIOD_MAX,    NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         REPEATCODE_MIN,      REPEATCODE_MAX,      NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         TIMEOUTPERIOD_MIN,   TIMEOUTPERIOD_MAX,   NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         TIMEOUTCODE_MIN,     TIMEOUTCODE_MAX,     NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    NULL),
};

static STATUS_CODE_CONTROL_BLOCK StatusCodeControlBlock;

static STATUS LocalStatusCodeInit(void)
{
   STATUS LocalStatus;

   LocalStatus = OS_StatusCodeInit(STATUSCODE_INTERFACE_VERSION,
                                   &StatusCodeControlBlock,
                                   StatusCodes,
                                   sizeof(StatusCodes)/sizeof(StatusCodes[0]),
                                   AppLocalParameterPosition(),
                                   AppBackupPosition());
   STATUS_LINE_VAR_RETURN_CONST(LocalStatus, ERR_3);

   return OS_SUCCESS;
}

#define CREATE_STATUS_CODES

//-----------------------------------------------------------------------
// MODIFIABLE                  MODIFIABLE                   MODIFIABLE
//-----------------------------------------------------------------------

extern const char FlightWarningLightAppGroupName[];
extern const char FlightWarningLightAppMenuName[];

static void Init_Structures_From_Conf_File(void)
{
   M_ObjMainMenuLines[0].LinkName = (char*)FlightWarningLightAppMenuName;
   M_ObjMainMenuLines[0].LinkGroup = (char*)FlightWarningLightAppGroupName;
}

//-----------------------------------------------------------------------
// AUTOGENERATED END        AUTOGENERATED END        AUTOGENERATED END
//-----------------------------------------------------------------------
//}

#undef AUTOGENERATED_PART

//-----------------------------------------------------------------------
// USER DEFINITIONS         USER DEFINITIONS         USER DEFINITIONS
//-----------------------------------------------------------------------

volatile const U8 FlightWarningLight_ModuleInterfaceError_Version_1; // Version check

//-----------------------------------------------------------------------
// SET/RESET FUNCTIONS    SET/RESET FUNCTIONS    SET/RESET FUNCTIONS
//-----------------------------------------------------------------------
// Status code 1569 : Flight warn.ligh.def
//-----------------------------------------------------------------------
static U8 StatusSetFunc1569( void )
{
    if( DI_ObstructionLightAlarm )
    {
        return 0;
    }
    if( WPlineError() )
    {
        return 0;
    }

    return !DI_ObstructionLightAlarm;
}

static U8 StatusResetFunc1569( void )
{
    return !StatusSetFunc1569();
}

//-----------------------------------------------------------------------
// DRIVER FUNCTION         DRIVER FUNCTION         DRIVER FUNCTION
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// INIT                   INIT                     INIT
//-----------------------------------------------------------------------


//-----------------------------------------------------------------------
// CONTROL                CONTROL                 CONTROL
//-----------------------------------------------------------------------
static STATUS LocalCtrl( void )
{
    STATUS LocalStatus = OS_SUCCESS;

    return LocalStatus;
}

//-----------------------------------------------------------------------
// MAIN CALL             MAIN CALL               MAIN CALL
//-----------------------------------------------------------------------

STATUS FlightWarningLight( U8 ModuleState, OS_MEMORY_POOL *MemPool, U32 *Arg3 )
{
    STATUS LocalStatus = 0;

    // Version check
    if( ModuleState == APP_INIT1 )
    {
        LocalStatus = OS_ValidateAPI( OS_SERVICES->APIVersionMajor,
                                      OS_SERVICES->APIVersionMinor,
                                      OS_LinkTime,
                                      ReleaseTag,
                                      __MODULE__ );
        if( OS_SUCCESS != LocalStatus )
        {
            return LocalStatus;
        }
    }
#ifdef READ_VARS
    // Read inputdata
    LocalStatus = InputReferenceRoutine( ModuleState );
    STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif
#ifdef CREATE_MENU
    if( ModuleState == APP_INIT1 || ModuleState == APP_INIT4 )
    {
        LocalStatus = FlightWarningLightMenuAppInit( ModuleState, MemPool );
        STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
    }
#endif
    switch( ModuleState )
    {
        case APP_RUN:
        {
         #ifdef FUNCTION_BLOCKS_PRE_LOCAL_CONTROL
            LocalStatus = FunctionBlocksPreLocalCtrl( Interval );
            STATUS_LINE_VAR_RETURN_VALUE( LocalStatus );
         #endif

            LocalStatus = LocalCtrl();
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
        
         #ifdef FUNCTION_BLOCKS_POST_LOCAL_CONTROL
            LocalStatus = FunctionBlocksPostLocalCtrl( Interval );
            STATUS_LINE_VAR_RETURN_VALUE( LocalStatus );
         #endif

#ifdef WRITE_VARS
            // Write Outputdata
            LocalStatus = OutputReferenceRoutine( ModuleState );
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif
            break;
        }
        case APP_INIT1:
        {
            Init_Structures_From_Conf_File();
            (void)FlightWarningLight_ModuleInterfaceError_Version_1; // Version check
#ifdef CREATE_VARDB_VARS
            LocalStatus = CreateVarDbVars();
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif
#ifdef CREATE_IO_VARS
            LocalStatus = CreateIOVars();
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif
            break;
        }
        case APP_INIT2:
        {
#ifdef CREATE_ALIASES
            size_t ErrorEntry = 0;
            LocalStatus = OS_VarDB_CreateAliases(AliasVars, sizeof(AliasVars)/sizeof(AliasVars[0]), &ErrorEntry);
            STATUS_LINE_VAR_RETURN_CONST(LocalStatus, ErrorEntry)
#endif

#ifdef VERIFY_VARIABLES
            LocalStatus = LocalIoCheck();
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif

#ifdef CREATE_BUTTONS
            LocalStatus = CreateButtons();
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif
            break;
        }
        case APP_INIT3:
        {
#ifdef CREATE_SUMMATIONS
            LocalStatus = CreateSummations();
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif

#ifdef WRITE_VARS
            LocalStatus = InitOutputVars();
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif

#ifdef CREATE_STATUS_CODES
            LocalStatus = LocalStatusCodeInit();
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif
#ifdef CREATE_IO_VARS
            FlightWarningLightSetLockValues();
#endif
            break;
        }
        case APP_INIT4:
        {
            break;
        }
        case APP_INIT5:
        {

         #ifdef INIT_FUNCTION_BLOCKS
            LocalStatus = FunctionBlocksInit( Interval );
            STATUS_LINE_VAR_RETURN_VALUE( LocalStatus );
         #endif

            break;
        }
        default:
        {
            break;
        }
    }
    return OS_SUCCESS;
}
//-----------------------------------------------------------------------
