//*****************************PEPTOOL Header Start******************************
//                                                                               
//                         Copyright © 2015 Mita-Teknik.                         
//This software may only be used with WP4x00 Controllers delivered by Mita-Teknik
//                                                                               
//*******************************************************************************
//                                                                               
// $PEPTOOL version:9.0$                                                         
// $PEPTOOL file version:101$                                                    
//                                                                               
//*******************************************************************************
//                                                                               
// $Date: 2014/04/25 13:45:41 $                                                  
// $Author: MITA\ihn $                                                           
// $RCSfile: Generator_Conf.c,v $                                                
// $Revision: 1.12 $                                                             
//                                                                               
//******************************PEPTOOL Header End*******************************

//***********************************************************************
// OS header files
#include <os_main.h>
// IO init file
#include <InitIo.h>
      
#define AUTOGENERATED_PART

#include <Turbdef.h>

//-----------------------------------------------------------------------
// AUTOGENERATED START     AUTOGENERATED START     AUTOGENERATED START
//-----------------------------------------------------------------------
char Generator_Conf_copyright[] =
{
    67, 111, 112, 121, 114, 105, 103, 104, 116, 32, 63, 32, 50, 48, 49, 53,
    32, 77, 105, 116, 97, 45, 84, 101, 107, 110, 105, 107, 46, 13, 10, 84,
    104, 105, 115, 32, 115, 111, 102, 116, 119, 97, 114, 101, 32, 109, 97, 121,
    32, 111, 110, 108, 121, 32, 98, 101, 32, 117, 115, 101, 100, 32, 119, 105,
    116, 104, 32, 87, 80, 52, 120, 48, 48, 32, 67, 111, 110, 116, 114, 111,
    108, 108, 101, 114, 115, 32, 100, 101, 108, 105, 118, 101, 114, 101, 100, 32,
    98, 121, 32, 77, 105, 116, 97, 45, 84, 101, 107, 110, 105, 107, 0
};
//-----------------------------------------------------------------------
// MODIFIABLE                  MODIFIABLE               MODIFIABLE
//-----------------------------------------------------------------------
const char GeneratorAppGroupName[] = "G_"APP_ID"App";
const char GeneratorAppMenuName[] = "M_"APP_ID"AppMain";

//-----------------------------------------------------------------------
// IO VARIABLES                IO VARIABLES                IO VARIABLES
//-----------------------------------------------------------------------

void (*GeneratorSetLockValues)(void);
struct os_db_alias *GeneratorIOVars;
size_t GeneratorIOVarsSize = 0;
            
struct os_db_alias GeneratorIOVars1[]=
{
    VAR_ELEMENT_ALIAS("3.2.62",                           "AI_GeneratorStatorAirGap1"),
    VAR_ELEMENT_ALIAS("3.2.62_Ss",                        "AI_GeneratorStatorAirGap1_Ss"),
    VAR_ELEMENT_ALIAS("3.2.62_E",                         "AI_GeneratorStatorAirGap1_E"),
    VAR_ELEMENT_ALIAS( "3.2.62_Th",                        "AI_GeneratorStatorAirGap1_Th"),
    VAR_ELEMENT_ALIAS("3.2.62_Ht",                        "AI_GeneratorStatorAirGap1_Ht"),
    VAR_ELEMENT_ALIAS("3.2.62_S",                         "AI_GeneratorStatorAirGap1_S"),
    VAR_ELEMENT_ALIAS("3.2.62_O",                         "AI_GeneratorStatorAirGap1_O"),

    VAR_ELEMENT_ALIAS("3.2.63",                           "AI_GeneratorStatorAirGap2"),
    VAR_ELEMENT_ALIAS("3.2.63_Ss",                        "AI_GeneratorStatorAirGap2_Ss"),
    VAR_ELEMENT_ALIAS("3.2.63_E",                         "AI_GeneratorStatorAirGap2_E"),
    VAR_ELEMENT_ALIAS( "3.2.63_Th",                        "AI_GeneratorStatorAirGap2_Th"),
    VAR_ELEMENT_ALIAS("3.2.63_Ht",                        "AI_GeneratorStatorAirGap2_Ht"),
    VAR_ELEMENT_ALIAS("3.2.63_S",                         "AI_GeneratorStatorAirGap2_S"),
    VAR_ELEMENT_ALIAS("3.2.63_O",                         "AI_GeneratorStatorAirGap2_O"),

    VAR_ELEMENT_ALIAS("5.2.61",                           "AI_GeneratorStatorAirGap3"),
    VAR_ELEMENT_ALIAS("5.2.61_Ss",                        "AI_GeneratorStatorAirGap3_Ss"),
    VAR_ELEMENT_ALIAS("5.2.61_E",                         "AI_GeneratorStatorAirGap3_E"),
    VAR_ELEMENT_ALIAS( "5.2.61_Th",                        "AI_GeneratorStatorAirGap3_Th"),
    VAR_ELEMENT_ALIAS("5.2.61_Ht",                        "AI_GeneratorStatorAirGap3_Ht"),
    VAR_ELEMENT_ALIAS("5.2.61_S",                         "AI_GeneratorStatorAirGap3_S"),
    VAR_ELEMENT_ALIAS("5.2.61_O",                         "AI_GeneratorStatorAirGap3_O"),

    VAR_ELEMENT_ALIAS("5.2.62",                           "AI_GeneratorStatorAirGap4"),
    VAR_ELEMENT_ALIAS("5.2.62_Ss",                        "AI_GeneratorStatorAirGap4_Ss"),
    VAR_ELEMENT_ALIAS("5.2.62_E",                         "AI_GeneratorStatorAirGap4_E"),
    VAR_ELEMENT_ALIAS( "5.2.62_Th",                        "AI_GeneratorStatorAirGap4_Th"),
    VAR_ELEMENT_ALIAS("5.2.62_Ht",                        "AI_GeneratorStatorAirGap4_Ht"),
    VAR_ELEMENT_ALIAS("5.2.62_S",                         "AI_GeneratorStatorAirGap4_S"),
    VAR_ELEMENT_ALIAS("5.2.62_O",                         "AI_GeneratorStatorAirGap4_O"),

    VAR_ELEMENT_ALIAS("5.2.63",                           "AI_GeneratorStatorAirGap5"),
    VAR_ELEMENT_ALIAS("5.2.63_Ss",                        "AI_GeneratorStatorAirGap5_Ss"),
    VAR_ELEMENT_ALIAS("5.2.63_E",                         "AI_GeneratorStatorAirGap5_E"),
    VAR_ELEMENT_ALIAS( "5.2.63_Th",                        "AI_GeneratorStatorAirGap5_Th"),
    VAR_ELEMENT_ALIAS("5.2.63_Ht",                        "AI_GeneratorStatorAirGap5_Ht"),
    VAR_ELEMENT_ALIAS("5.2.63_S",                         "AI_GeneratorStatorAirGap5_S"),
    VAR_ELEMENT_ALIAS("5.2.63_O",                         "AI_GeneratorStatorAirGap5_O"),

    VAR_ELEMENT_ALIAS("5.2.64",                           "AI_MagneticFluxCurr"),
    VAR_ELEMENT_ALIAS("5.2.64_Ss",                        "AI_MagneticFluxCurr_Ss"),
    VAR_ELEMENT_ALIAS("5.2.64_E",                         "AI_MagneticFluxCurr_E"),
    VAR_ELEMENT_ALIAS( "5.2.64_Th",                        "AI_MagneticFluxCurr_Th"),
    VAR_ELEMENT_ALIAS("5.2.64_Ht",                        "AI_MagneticFluxCurr_Ht"),
    VAR_ELEMENT_ALIAS("5.2.64_S",                         "AI_MagneticFluxCurr_S"),
    VAR_ELEMENT_ALIAS("5.2.64_O",                         "AI_MagneticFluxCurr_O"),

    VAR_ELEMENT_ALIAS("3.2.24_Frq",                       "AI_GEN_PulserFrequency"),
    VAR_ELEMENT_ALIAS("3.2.24_Frq_Ss",                    "AI_GEN_PulserFrequency_Ss"),
    VAR_ELEMENT_ALIAS("3.2.24_Frq_E",                     "AI_GEN_PulserFrequency_E"),
    VAR_ELEMENT_ALIAS( "3.2.24_Frq_Th",                    "AI_GEN_PulserFrequency_Th"),
    VAR_ELEMENT_ALIAS("3.2.24_Frq_Ht",                    "AI_GEN_PulserFrequency_Ht"),
    VAR_ELEMENT_ALIAS("3.2.24_Frq_S",                     "AI_GEN_PulserFrequency_S"),
    VAR_ELEMENT_ALIAS("3.2.24_Frq_O",                     "AI_GEN_PulserFrequency_O"),

    VAR_ELEMENT_ALIAS("3.3.21_Avg",                       "HSI_GEN_EncoderFrq1AvgCnt"),

    VAR_ELEMENT_ALIAS("3.3.22_Avg",                       "HSI_GEN_EncoderFrq2AvgCnt"),

    VAR_ELEMENT_ALIAS("3.3.21_Frq",                       "HSI_GEN_EncoderFrequency1"),
    VAR_ELEMENT_ALIAS("3.3.21_Frq_Ss",                    "HSI_GEN_EncoderFrequency1_Ss"),
    VAR_ELEMENT_ALIAS("3.3.21_Frq_E",                     "HSI_GEN_EncoderFrequency1_E"),
    VAR_ELEMENT_ALIAS( "3.3.21_Frq_Th",                    "HSI_GEN_EncoderFrequency1_Th"),
    VAR_ELEMENT_ALIAS("3.3.21_Frq_Ht",                    "HSI_GEN_EncoderFrequency1_Ht"),
    VAR_ELEMENT_ALIAS("3.3.21_Frq_S",                     "HSI_GEN_EncoderFrequency1_S"),
    VAR_ELEMENT_ALIAS("3.3.21_Frq_O",                     "HSI_GEN_EncoderFrequency1_O"),

    VAR_ELEMENT_ALIAS("3.3.22_Frq",                       "HSI_GEN_EncoderFrequency2"),
    VAR_ELEMENT_ALIAS("3.3.22_Frq_Ss",                    "HSI_GEN_EncoderFrequency2_Ss"),
    VAR_ELEMENT_ALIAS("3.3.22_Frq_E",                     "HSI_GEN_EncoderFrequency2_E"),
    VAR_ELEMENT_ALIAS( "3.3.22_Frq_Th",                    "HSI_GEN_EncoderFrequency2_Th"),
    VAR_ELEMENT_ALIAS("3.3.22_Frq_Ht",                    "HSI_GEN_EncoderFrequency2_Ht"),
    VAR_ELEMENT_ALIAS("3.3.22_Frq_S",                     "HSI_GEN_EncoderFrequency2_S"),
    VAR_ELEMENT_ALIAS("3.3.22_Frq_O",                     "HSI_GEN_EncoderFrequency2_O"),

    VAR_ELEMENT_ALIAS("3.3.21-24_GrcMode",                "AO_GEN_EncoderGrayCode"),

    VAR_ELEMENT_ALIAS("3.3.21-22_GrcCnt",                 "AI_GEN_EncoderCounter"),
    VAR_ELEMENT_ALIAS("3.3.21-22_GrcCnt_Ss",              "AI_GEN_EncoderCounter_Ss"),
    VAR_ELEMENT_ALIAS("3.3.21-22_GrcCnt_E",               "AI_GEN_EncoderCounter_E"),
    VAR_ELEMENT_ALIAS( "3.3.21-22_GrcCnt_Th",              "AI_GEN_EncoderCounter_Th"),
    VAR_ELEMENT_ALIAS("3.3.21-22_GrcCnt_Ht",              "AI_GEN_EncoderCounter_Ht"),
    VAR_ELEMENT_ALIAS("3.3.21-22_GrcCnt_S",               "AI_GEN_EncoderCounter_S"),
    VAR_ELEMENT_ALIAS("3.3.21-22_GrcCnt_O",               "AI_GEN_EncoderCounter_O"),

    VAR_ELEMENT_ALIAS("3.3.21-22_GrcDir",                 "AI_GEN_EncoderRotDirection"),
    VAR_ELEMENT_ALIAS("3.3.21-22_GrcDir_Ss",              "AI_GEN_EncoderRotDirection_Ss"),
    VAR_ELEMENT_ALIAS("3.3.21-22_GrcDir_E",               "AI_GEN_EncoderRotDirection_E"),
    VAR_ELEMENT_ALIAS( "3.3.21-22_GrcDir_Th",              "AI_GEN_EncoderRotDirection_Th"),
    VAR_ELEMENT_ALIAS("3.3.21-22_GrcDir_Ht",              "AI_GEN_EncoderRotDirection_Ht"),
    VAR_ELEMENT_ALIAS("3.3.21-22_GrcDir_S",               "AI_GEN_EncoderRotDirection_S"),
    VAR_ELEMENT_ALIAS("3.3.21-22_GrcDir_O",               "AI_GEN_EncoderRotDirection_O"),

    VAR_ELEMENT_ALIAS("3.3.21-22_GrcDef",                 "AI_GEN_EncoderDefect"),
    VAR_ELEMENT_ALIAS("3.3.21-22_GrcDef_Ss",              "AI_GEN_EncoderDefect_Ss"),
    VAR_ELEMENT_ALIAS("3.3.21-22_GrcDef_E",               "AI_GEN_EncoderDefect_E"),
    VAR_ELEMENT_ALIAS( "3.3.21-22_GrcDef_Th",              "AI_GEN_EncoderDefect_Th"),
    VAR_ELEMENT_ALIAS("3.3.21-22_GrcDef_Ht",              "AI_GEN_EncoderDefect_Ht"),
    VAR_ELEMENT_ALIAS("3.3.21-22_GrcDef_S",               "AI_GEN_EncoderDefect_S"),
    VAR_ELEMENT_ALIAS("3.3.21-22_GrcDef_O",               "AI_GEN_EncoderDefect_O"),

    VAR_ELEMENT_ALIAS("3.3.8",                            "DO_RotorUnlockValve"),

    VAR_ELEMENT_ALIAS("3.3.45",                           "DI_RotorOneLocked"),
    VAR_ELEMENT_ALIAS("3.3.45_Ss",                        "DI_RotorOneLocked_Ss"),
    VAR_ELEMENT_ALIAS("3.3.45_E",                         "DI_RotorOneLocked_E"),
    VAR_ELEMENT_ALIAS("3.3.45_I",                         "DI_RotorOneLocked_I"),
    VAR_ELEMENT_ALIAS("3.3.45_Cm",                        "DI_RotorOneLocked_Cm"),
    VAR_ELEMENT_ALIAS("3.3.45_Ht",                        "DI_RotorOneLocked_Ht"),

    VAR_ELEMENT_ALIAS("3.3.46",                           "DI_RotorOneUnlocked"),
    VAR_ELEMENT_ALIAS("3.3.46_Ss",                        "DI_RotorOneUnlocked_Ss"),
    VAR_ELEMENT_ALIAS("3.3.46_E",                         "DI_RotorOneUnlocked_E"),
    VAR_ELEMENT_ALIAS("3.3.46_I",                         "DI_RotorOneUnlocked_I"),
    VAR_ELEMENT_ALIAS("3.3.46_Cm",                        "DI_RotorOneUnlocked_Cm"),
    VAR_ELEMENT_ALIAS("3.3.46_Ht",                        "DI_RotorOneUnlocked_Ht"),

    VAR_ELEMENT_ALIAS("3.3.47",                           "DI_RotorTwoLocked"),
    VAR_ELEMENT_ALIAS("3.3.47_Ss",                        "DI_RotorTwoLocked_Ss"),
    VAR_ELEMENT_ALIAS("3.3.47_E",                         "DI_RotorTwoLocked_E"),
    VAR_ELEMENT_ALIAS("3.3.47_I",                         "DI_RotorTwoLocked_I"),
    VAR_ELEMENT_ALIAS("3.3.47_Cm",                        "DI_RotorTwoLocked_Cm"),
    VAR_ELEMENT_ALIAS("3.3.47_Ht",                        "DI_RotorTwoLocked_Ht"),

    VAR_ELEMENT_ALIAS("3.3.48",                           "DI_RotorTwoUnlocked"),
    VAR_ELEMENT_ALIAS("3.3.48_Ss",                        "DI_RotorTwoUnlocked_Ss"),
    VAR_ELEMENT_ALIAS("3.3.48_E",                         "DI_RotorTwoUnlocked_E"),
    VAR_ELEMENT_ALIAS("3.3.48_I",                         "DI_RotorTwoUnlocked_I"),
    VAR_ELEMENT_ALIAS("3.3.48_Cm",                        "DI_RotorTwoUnlocked_Cm"),
    VAR_ELEMENT_ALIAS("3.3.48_Ht",                        "DI_RotorTwoUnlocked_Ht"),

    VAR_ELEMENT_ALIAS("5.2.42",                           "DI_GEN_BoltBreakSensor"),
    VAR_ELEMENT_ALIAS("5.2.42_Ss",                        "DI_GEN_BoltBreakSensor_Ss"),
    VAR_ELEMENT_ALIAS("5.2.42_E",                         "DI_GEN_BoltBreakSensor_E"),
    VAR_ELEMENT_ALIAS("5.2.42_I",                         "DI_GEN_BoltBreakSensor_I"),
    VAR_ELEMENT_ALIAS("5.2.42_Cm",                        "DI_GEN_BoltBreakSensor_Cm"),
    VAR_ELEMENT_ALIAS("5.2.42_Ht",                        "DI_GEN_BoltBreakSensor_Ht"),

    VAR_ELEMENT_ALIAS("3.2.21_Avg",                       "HSI_GEN_Encoder2Frq1AvgCnt"),

    VAR_ELEMENT_ALIAS("3.2.22_Avg",                       "HSI_GEN_Encoder2Freq2AvgCnt"),

    VAR_ELEMENT_ALIAS("3.2.21_Frq",                       "HSI_GEN_Encoder2Frequency1"),
    VAR_ELEMENT_ALIAS("3.2.21_Frq_Ss",                    "HSI_GEN_Encoder2Frequency1_Ss"),
    VAR_ELEMENT_ALIAS("3.2.21_Frq_E",                     "HSI_GEN_Encoder2Frequency1_E"),
    VAR_ELEMENT_ALIAS( "3.2.21_Frq_Th",                    "HSI_GEN_Encoder2Frequency1_Th"),
    VAR_ELEMENT_ALIAS("3.2.21_Frq_Ht",                    "HSI_GEN_Encoder2Frequency1_Ht"),
    VAR_ELEMENT_ALIAS("3.2.21_Frq_S",                     "HSI_GEN_Encoder2Frequency1_S"),
    VAR_ELEMENT_ALIAS("3.2.21_Frq_O",                     "HSI_GEN_Encoder2Frequency1_O"),

    VAR_ELEMENT_ALIAS("3.2.22_Frq",                       "HSI_GEN_Encoder2Frequency2"),
    VAR_ELEMENT_ALIAS("3.2.22_Frq_Ss",                    "HSI_GEN_Encoder2Frequency2_Ss"),
    VAR_ELEMENT_ALIAS("3.2.22_Frq_E",                     "HSI_GEN_Encoder2Frequency2_E"),
    VAR_ELEMENT_ALIAS( "3.2.22_Frq_Th",                    "HSI_GEN_Encoder2Frequency2_Th"),
    VAR_ELEMENT_ALIAS("3.2.22_Frq_Ht",                    "HSI_GEN_Encoder2Frequency2_Ht"),
    VAR_ELEMENT_ALIAS("3.2.22_Frq_S",                     "HSI_GEN_Encoder2Frequency2_S"),
    VAR_ELEMENT_ALIAS("3.2.22_Frq_O",                     "HSI_GEN_Encoder2Frequency2_O"),

    VAR_ELEMENT_ALIAS("3.2.21-24_GrcDivide",              "AO_GEN_Encoder2GrayCode"),

    VAR_ELEMENT_ALIAS("3.2.21-22_GrcCnt",                 "AI_GEN_Encoder2Counter"),
    VAR_ELEMENT_ALIAS("3.2.21-22_GrcCnt_Ss",              "AI_GEN_Encoder2Counter_Ss"),
    VAR_ELEMENT_ALIAS("3.2.21-22_GrcCnt_E",               "AI_GEN_Encoder2Counter_E"),
    VAR_ELEMENT_ALIAS( "3.2.21-22_GrcCnt_Th",              "AI_GEN_Encoder2Counter_Th"),
    VAR_ELEMENT_ALIAS("3.2.21-22_GrcCnt_Ht",              "AI_GEN_Encoder2Counter_Ht"),
    VAR_ELEMENT_ALIAS("3.2.21-22_GrcCnt_S",               "AI_GEN_Encoder2Counter_S"),
    VAR_ELEMENT_ALIAS("3.2.21-22_GrcCnt_O",               "AI_GEN_Encoder2Counter_O"),

    VAR_ELEMENT_ALIAS("3.2.21-22_GrcDir",                 "AI_GEN_Encoder2RotDirection"),
    VAR_ELEMENT_ALIAS("3.2.21-22_GrcDir_Ss",              "AI_GEN_Encoder2RotDirection_Ss"),
    VAR_ELEMENT_ALIAS("3.2.21-22_GrcDir_E",               "AI_GEN_Encoder2RotDirection_E"),
    VAR_ELEMENT_ALIAS( "3.2.21-22_GrcDir_Th",              "AI_GEN_Encoder2RotDirection_Th"),
    VAR_ELEMENT_ALIAS("3.2.21-22_GrcDir_Ht",              "AI_GEN_Encoder2RotDirection_Ht"),
    VAR_ELEMENT_ALIAS("3.2.21-22_GrcDir_S",               "AI_GEN_Encoder2RotDirection_S"),
    VAR_ELEMENT_ALIAS("3.2.21-22_GrcDir_O",               "AI_GEN_Encoder2RotDirection_O"),

    VAR_ELEMENT_ALIAS("3.2.21-22_GrcDef",                 "AI_GEN_Encoder2Defect"),
    VAR_ELEMENT_ALIAS("3.2.21-22_GrcDef_Ss",              "AI_GEN_Encoder2Defect_Ss"),
    VAR_ELEMENT_ALIAS("3.2.21-22_GrcDef_E",               "AI_GEN_Encoder2Defect_E"),
    VAR_ELEMENT_ALIAS( "3.2.21-22_GrcDef_Th",              "AI_GEN_Encoder2Defect_Th"),
    VAR_ELEMENT_ALIAS("3.2.21-22_GrcDef_Ht",              "AI_GEN_Encoder2Defect_Ht"),
    VAR_ELEMENT_ALIAS("3.2.21-22_GrcDef_S",               "AI_GEN_Encoder2Defect_S"),
    VAR_ELEMENT_ALIAS("3.2.21-22_GrcDef_O",               "AI_GEN_Encoder2Defect_O"),

};
size_t GeneratorIOVars1Size = sizeof(GeneratorIOVars1)/sizeof(GeneratorIOVars1[0]);

void GeneratorSetLockValues1(void)
{
   SetLockValue("AI_GeneratorStatorAirGap1_Ss",          TYP_8,     1);
   SetLockValue("AI_GeneratorStatorAirGap1_E",           TYP_8,     1);
   SetLockValue("AI_GeneratorStatorAirGap1_Th",          TYP_16,    200);
   SetLockValue("AI_GeneratorStatorAirGap1_Ht",          TYP_32,    20);
   SetLockValue("AI_GeneratorStatorAirGap1_S",           TYP_32,    0);
   SetValue("AI_GeneratorStatorAirGap1_O",               TYP_32,    0);

   SetLockValue("AI_GeneratorStatorAirGap2_Ss",          TYP_8,     1);
   SetLockValue("AI_GeneratorStatorAirGap2_E",           TYP_8,     1);
   SetLockValue("AI_GeneratorStatorAirGap2_Th",          TYP_16,    200);
   SetLockValue("AI_GeneratorStatorAirGap2_Ht",          TYP_32,    20);
   SetLockValue("AI_GeneratorStatorAirGap2_S",           TYP_32,    0);
   SetValue("AI_GeneratorStatorAirGap2_O",               TYP_32,    0);

   SetLockValue("AI_GeneratorStatorAirGap3_Ss",          TYP_8,     1);
   SetLockValue("AI_GeneratorStatorAirGap3_E",           TYP_8,     1);
   SetLockValue("AI_GeneratorStatorAirGap3_Th",          TYP_16,    200);
   SetLockValue("AI_GeneratorStatorAirGap3_Ht",          TYP_32,    20);
   SetLockValue("AI_GeneratorStatorAirGap3_S",           TYP_32,    0);
   SetValue("AI_GeneratorStatorAirGap3_O",               TYP_32,    0);

   SetLockValue("AI_GeneratorStatorAirGap4_Ss",          TYP_8,     1);
   SetLockValue("AI_GeneratorStatorAirGap4_E",           TYP_8,     1);
   SetLockValue("AI_GeneratorStatorAirGap4_Th",          TYP_16,    200);
   SetLockValue("AI_GeneratorStatorAirGap4_Ht",          TYP_32,    20);
   SetLockValue("AI_GeneratorStatorAirGap4_S",           TYP_32,    0);
   SetValue("AI_GeneratorStatorAirGap4_O",               TYP_32,    0);

   SetLockValue("AI_GeneratorStatorAirGap5_Ss",          TYP_8,     1);
   SetLockValue("AI_GeneratorStatorAirGap5_E",           TYP_8,     1);
   SetLockValue("AI_GeneratorStatorAirGap5_Th",          TYP_16,    200);
   SetLockValue("AI_GeneratorStatorAirGap5_Ht",          TYP_32,    20);
   SetLockValue("AI_GeneratorStatorAirGap5_S",           TYP_32,    0);
   SetValue("AI_GeneratorStatorAirGap5_O",               TYP_32,    0);

   SetLockValue("AI_MagneticFluxCurr_Ss",                TYP_8,     1);
   SetLockValue("AI_MagneticFluxCurr_E",                 TYP_8,     1);
   SetLockValue("AI_MagneticFluxCurr_Th",                TYP_16,    1);
   SetLockValue("AI_MagneticFluxCurr_Ht",                TYP_32,    1000);
   SetLockValue("AI_MagneticFluxCurr_S",                 TYP_32,    0);
   SetValue("AI_MagneticFluxCurr_O",                     TYP_32,    0);

   SetLockValue("AI_GEN_PulserFrequency_Ss",             TYP_8,     1);
   SetLockValue("AI_GEN_PulserFrequency_E",              TYP_8,     1);
   SetLockValue("AI_GEN_PulserFrequency_Th",             TYP_32,    10);
   SetLockValue("AI_GEN_PulserFrequency_Ht",             TYP_32,    20);
   SetLockValue("AI_GEN_PulserFrequency_S",              TYP_32,    0);
   SetValue("AI_GEN_PulserFrequency_O",                  TYP_32,    0);

   SetValue("HSI_GEN_EncoderFrq1AvgCnt",                 TYP_16,    1);

   SetValue("HSI_GEN_EncoderFrq2AvgCnt",                 TYP_16,    1);

   SetLockValue("HSI_GEN_EncoderFrequency1_Ss",          TYP_8,     1);
   SetLockValue("HSI_GEN_EncoderFrequency1_E",           TYP_8,     1);
   SetLockValue("HSI_GEN_EncoderFrequency1_Th",          TYP_32,    1);
   SetLockValue("HSI_GEN_EncoderFrequency1_Ht",          TYP_32,    20);
   SetLockValue("HSI_GEN_EncoderFrequency1_S",           TYP_32,    0);
   SetValue("HSI_GEN_EncoderFrequency1_O",               TYP_32,    0);

   SetLockValue("HSI_GEN_EncoderFrequency2_Ss",          TYP_8,     1);
   SetLockValue("HSI_GEN_EncoderFrequency2_E",           TYP_8,     1);
   SetLockValue("HSI_GEN_EncoderFrequency2_Th",          TYP_32,    1);
   SetLockValue("HSI_GEN_EncoderFrequency2_Ht",          TYP_32,    20);
   SetLockValue("HSI_GEN_EncoderFrequency2_S",           TYP_32,    0);
   SetValue("HSI_GEN_EncoderFrequency2_O",               TYP_32,    0);

   SetLockValue("AI_GEN_EncoderCounter_Ss",              TYP_8,     1);
   SetLockValue("AI_GEN_EncoderCounter_E",               TYP_8,     1);
   SetLockValue("AI_GEN_EncoderCounter_Th",              TYP_32,    1);
   SetLockValue("AI_GEN_EncoderCounter_Ht",              TYP_32,    20);
   SetLockValue("AI_GEN_EncoderCounter_S",               TYP_32,    0);
   SetValue("AI_GEN_EncoderCounter_O",                   TYP_32,    0);

   SetLockValue("AI_GEN_EncoderRotDirection_Ss",         TYP_8,     1);
   SetLockValue("AI_GEN_EncoderRotDirection_E",          TYP_8,     1);
   SetLockValue("AI_GEN_EncoderRotDirection_Th",         TYP_8,     1);
   SetLockValue("AI_GEN_EncoderRotDirection_Ht",         TYP_32,    20);
   SetLockValue("AI_GEN_EncoderRotDirection_S",          TYP_32,    0);
   SetValue("AI_GEN_EncoderRotDirection_O",              TYP_32,    0);

   SetLockValue("AI_GEN_EncoderDefect_Ss",               TYP_8,     1);
   SetLockValue("AI_GEN_EncoderDefect_E",                TYP_8,     1);
   SetLockValue("AI_GEN_EncoderDefect_Th",               TYP_8,     1);
   SetLockValue("AI_GEN_EncoderDefect_Ht",               TYP_32,    100);
   SetLockValue("AI_GEN_EncoderDefect_S",                TYP_32,    0);
   SetValue("AI_GEN_EncoderDefect_O",                    TYP_32,    0);

   SetLockValue("DI_RotorOneLocked_Ss",                  TYP_8,     1);
   SetLockValue("DI_RotorOneLocked_E",                   TYP_8,     1);
   SetValue("DI_RotorOneLocked_I",                       TYP_8,     0);
   SetLockValue("DI_RotorOneLocked_Cm",                  TYP_8,     1);
   SetLockValue("DI_RotorOneLocked_Ht",                  TYP_32,    1000);

   SetLockValue("DI_RotorOneUnlocked_Ss",                TYP_8,     1);
   SetLockValue("DI_RotorOneUnlocked_E",                 TYP_8,     1);
   SetValue("DI_RotorOneUnlocked_I",                     TYP_8,     0);
   SetLockValue("DI_RotorOneUnlocked_Cm",                TYP_8,     1);
   SetLockValue("DI_RotorOneUnlocked_Ht",                TYP_32,    1000);

   SetLockValue("DI_RotorTwoLocked_Ss",                  TYP_8,     1);
   SetLockValue("DI_RotorTwoLocked_E",                   TYP_8,     1);
   SetValue("DI_RotorTwoLocked_I",                       TYP_8,     0);
   SetLockValue("DI_RotorTwoLocked_Cm",                  TYP_8,     1);
   SetLockValue("DI_RotorTwoLocked_Ht",                  TYP_32,    1000);

   SetLockValue("DI_RotorTwoUnlocked_Ss",                TYP_8,     1);
   SetLockValue("DI_RotorTwoUnlocked_E",                 TYP_8,     1);
   SetValue("DI_RotorTwoUnlocked_I",                     TYP_8,     0);
   SetLockValue("DI_RotorTwoUnlocked_Cm",                TYP_8,     1);
   SetLockValue("DI_RotorTwoUnlocked_Ht",                TYP_32,    1000);

   SetLockValue("DI_GEN_BoltBreakSensor_Ss",             TYP_8,     1);
   SetLockValue("DI_GEN_BoltBreakSensor_E",              TYP_8,     1);
   SetValue("DI_GEN_BoltBreakSensor_I",                  TYP_8,     0);
   SetLockValue("DI_GEN_BoltBreakSensor_Cm",             TYP_8,     1);
   SetLockValue("DI_GEN_BoltBreakSensor_Ht",             TYP_32,    1000);

   SetValue("HSI_GEN_Encoder2Frq1AvgCnt",                TYP_16,    1);

   SetValue("HSI_GEN_Encoder2Freq2AvgCnt",               TYP_16,    1);

   SetLockValue("HSI_GEN_Encoder2Frequency1_Ss",         TYP_8,     1);
   SetLockValue("HSI_GEN_Encoder2Frequency1_E",          TYP_8,     1);
   SetLockValue("HSI_GEN_Encoder2Frequency1_Th",         TYP_32,    1);
   SetLockValue("HSI_GEN_Encoder2Frequency1_Ht",         TYP_32,    20);
   SetLockValue("HSI_GEN_Encoder2Frequency1_S",          TYP_32,    0);
   SetValue("HSI_GEN_Encoder2Frequency1_O",              TYP_32,    0);

   SetLockValue("HSI_GEN_Encoder2Frequency2_Ss",         TYP_8,     1);
   SetLockValue("HSI_GEN_Encoder2Frequency2_E",          TYP_8,     1);
   SetLockValue("HSI_GEN_Encoder2Frequency2_Th",         TYP_32,    1);
   SetLockValue("HSI_GEN_Encoder2Frequency2_Ht",         TYP_32,    20);
   SetLockValue("HSI_GEN_Encoder2Frequency2_S",          TYP_32,    0);
   SetValue("HSI_GEN_Encoder2Frequency2_O",              TYP_32,    0);

   SetValue("AO_GEN_Encoder2GrayCode",                   TYP_8,     0);

   SetLockValue("AI_GEN_Encoder2Counter_Ss",             TYP_8,     1);
   SetLockValue("AI_GEN_Encoder2Counter_E",              TYP_8,     1);
   SetLockValue("AI_GEN_Encoder2Counter_Th",             TYP_32,    1);
   SetLockValue("AI_GEN_Encoder2Counter_Ht",             TYP_32,    20);
   SetLockValue("AI_GEN_Encoder2Counter_S",              TYP_32,    0);
   SetValue("AI_GEN_Encoder2Counter_O",                  TYP_32,    0);

   SetLockValue("AI_GEN_Encoder2RotDirection_Ss",        TYP_8,     1);
   SetLockValue("AI_GEN_Encoder2RotDirection_E",         TYP_8,     1);
   SetLockValue("AI_GEN_Encoder2RotDirection_Th",        TYP_8,     1);
   SetLockValue("AI_GEN_Encoder2RotDirection_Ht",        TYP_32,    20);
   SetLockValue("AI_GEN_Encoder2RotDirection_S",         TYP_32,    0);
   SetValue("AI_GEN_Encoder2RotDirection_O",             TYP_32,    0);

   SetLockValue("AI_GEN_Encoder2Defect_Ss",              TYP_8,     1);
   SetLockValue("AI_GEN_Encoder2Defect_E",               TYP_8,     1);
   SetLockValue("AI_GEN_Encoder2Defect_Th",              TYP_8,     1);
   SetLockValue("AI_GEN_Encoder2Defect_Ht",              TYP_32,    100);
   SetLockValue("AI_GEN_Encoder2Defect_S",               TYP_32,    0);
   SetValue("AI_GEN_Encoder2Defect_O",                   TYP_32,    0);
}


STATUS GeneratorInitIOAliases()
{
   GeneratorIOVars = GeneratorIOVars1;
   GeneratorIOVarsSize = GeneratorIOVars1Size;
   GeneratorSetLockValues = &GeneratorSetLockValues1;
   return OS_SUCCESS;
}
//-----------------------------------------------------------------------
// AUTOGENERATED END        AUTOGENERATED END        AUTOGENERATED END
//-----------------------------------------------------------------------

#undef AUTOGENERATED_PART
