//*****************************PEPTOOL Header Start******************************
//                                                                               
//                         Copyright © 2015 Mita-Teknik.                         
//This software may only be used with WP4x00 Controllers delivered by Mita-Teknik
//                                                                               
//*******************************************************************************
//                                                                               
// $PEPTOOL version:9.0$                                                         
// $PEPTOOL file version:101$                                                    
//                                                                               
//*******************************************************************************
//                                                                               
// $Date: 2014/04/25 13:45:44 $                                                  
// $Author: MITA\ihn $                                                           
// $RCSfile: GeneratorCooling_MT_Type1_Conf.c,v $                                
// $Revision: 1.14 $                                                             
//                                                                               
//******************************PEPTOOL Header End*******************************

//***********************************************************************
// OS header files
#include <os_main.h>
// App header files
#include <InitIo.h>

#define AUTOGENERATED_PART

#include <Turbdef.h>

//-----------------------------------------------------------------------
// AUTOGENERATED START     AUTOGENERATED START     AUTOGENERATED START
//-----------------------------------------------------------------------
char GeneratorCooling_MT_Type1_Conf_copyright[] =
{
   67, 111, 112, 121, 114, 105, 103, 104, 116, 32, 63, 32, 50, 48, 49, 53,
   32, 77, 105, 116, 97, 45, 84, 101, 107, 110, 105, 107, 46, 13, 10, 84,
   104, 105, 115, 32, 115, 111, 102, 116, 119, 97, 114, 101, 32, 109, 97, 121,
   32, 111, 110, 108, 121, 32, 98, 101, 32, 117, 115, 101, 100, 32, 119, 105,
   116, 104, 32, 87, 80, 52, 120, 48, 48, 32, 67, 111, 110, 116, 114, 111,
   108, 108, 101, 114, 115, 32, 100, 101, 108, 105, 118, 101, 114, 101, 100, 32,
   98, 121, 32, 77, 105, 116, 97, 45, 84, 101, 107, 110, 105, 107, 0
};
//-----------------------------------------------------------------------
// MODIFIABLE                  MODIFIABLE               MODIFIABLE
//-----------------------------------------------------------------------
const char GeneratorCooling_MT_Type1AppGroupName[] = "G_Generator";
const char GeneratorCooling_MT_Type1AppMenuName[] = "M_ObjMain";

//-----------------------------------------------------------------------
// IO VARIABLES                IO VARIABLES                IO VARIABLES
//-----------------------------------------------------------------------

void (*GeneratorCooling_MT_Type1SetLockValues)(void);
struct os_db_alias *GeneratorCooling_MT_Type1IOVars;
size_t GeneratorCooling_MT_Type1IOVarsSize = 0;
            
struct os_db_alias GeneratorCooling_MT_Type1IOVars1[]=
{
    VAR_ELEMENT_ALIAS("3.2.42",                           "DI_GeneratorFan1ContactorFB"),
    VAR_ELEMENT_ALIAS("3.2.42_Ss",                        "DI_GeneratorFan1ContactorFB_Ss"),
    VAR_ELEMENT_ALIAS("3.2.42_E",                         "DI_GeneratorFan1ContactorFB_E"),
    VAR_ELEMENT_ALIAS("3.2.42_I",                         "DI_GeneratorFan1ContactorFB_I"),
    VAR_ELEMENT_ALIAS("3.2.42_Cm",                        "DI_GeneratorFan1ContactorFB_Cm"),
    VAR_ELEMENT_ALIAS("3.2.42_Ht",                        "DI_GeneratorFan1ContactorFB_Ht"),

    VAR_ELEMENT_ALIAS("3.2.43",                           "DI_GeneratorFan2ContactorFB"),
    VAR_ELEMENT_ALIAS("3.2.43_Ss",                        "DI_GeneratorFan2ContactorFB_Ss"),
    VAR_ELEMENT_ALIAS("3.2.43_E",                         "DI_GeneratorFan2ContactorFB_E"),
    VAR_ELEMENT_ALIAS("3.2.43_I",                         "DI_GeneratorFan2ContactorFB_I"),
    VAR_ELEMENT_ALIAS("3.2.43_Cm",                        "DI_GeneratorFan2ContactorFB_Cm"),
    VAR_ELEMENT_ALIAS("3.2.43_Ht",                        "DI_GeneratorFan2ContactorFB_Ht"),

    VAR_ELEMENT_ALIAS("3.3.5",                            "DO_GeneratorFan1ContactorON"),

    VAR_ELEMENT_ALIAS("3.3.6",                            "DO_GeneratorFan2ContactorON"),

    VAR_ELEMENT_ALIAS("3.3.COM1_activation",              "FansComPortConfigurationActivation"),

    VAR_ELEMENT_ALIAS("3.3.COM1_Baud",                    "FansComPortConfigurationBaudRate"),

    VAR_ELEMENT_ALIAS("3.3.COM1_DataBits",                "FansComPortConfigurationDataBits"),

    VAR_ELEMENT_ALIAS("3.3.COM1_Mode",                    "FansComPortConfigurationMode"),

    VAR_ELEMENT_ALIAS("3.3.COM1_Parity",                  "FansComPortConfigurationParity"),

    VAR_ELEMENT_ALIAS("3.3.COM1_StopBits",                "FansComPortConfigurationStopBits"),

    VAR_ELEMENT_ALIAS("3.3.COM1_Sync",                    "FansComPortConfigurationSync"),

    VAR_ELEMENT_ALIAS("3.2.51_D",                         "TI_GeneratorFan1Thermistor"),
    VAR_ELEMENT_ALIAS("3.2.51_D_Ss",                      "TI_GeneratorFan1Thermistor_Ss"),
    VAR_ELEMENT_ALIAS("3.2.51_D_E",                       "TI_GeneratorFan1Thermistor_E"),
    VAR_ELEMENT_ALIAS("3.2.51_D_I",                       "TI_GeneratorFan1Thermistor_I"),
    VAR_ELEMENT_ALIAS("3.2.51_D_Cm",                      "TI_GeneratorFan1Thermistor_Cm"),
    VAR_ELEMENT_ALIAS("3.2.51_D_Ht",                      "TI_GeneratorFan1Thermistor_Ht"),

    VAR_ELEMENT_ALIAS("3.2.51_Hi",                        "TI_GeneratorFan1Thermistor_Hi"),

    VAR_ELEMENT_ALIAS("3.2.51_Lo",                        "TI_GeneratorFan1Thermistor_Lo"),

    VAR_ELEMENT_ALIAS("3.2.52_D",                         "TI_GeneratorFan2Thermistor"),
    VAR_ELEMENT_ALIAS("3.2.52_D_Ss",                      "TI_GeneratorFan2Thermistor_Ss"),
    VAR_ELEMENT_ALIAS("3.2.52_D_E",                       "TI_GeneratorFan2Thermistor_E"),
    VAR_ELEMENT_ALIAS("3.2.52_D_I",                       "TI_GeneratorFan2Thermistor_I"),
    VAR_ELEMENT_ALIAS("3.2.52_D_Cm",                      "TI_GeneratorFan2Thermistor_Cm"),
    VAR_ELEMENT_ALIAS("3.2.52_D_Ht",                      "TI_GeneratorFan2Thermistor_Ht"),

    VAR_ELEMENT_ALIAS("3.2.52_Hi",                        "TI_GeneratorFan2Thermistor_Hi"),

    VAR_ELEMENT_ALIAS("3.2.52_Lo",                        "TI_GeneratorFan2Thermistor_Lo"),

    VAR_ELEMENT_ALIAS("5.2.67",                           "PT_GeneratorTemperatureHubSide1"),
    VAR_ELEMENT_ALIAS("5.2.67_Ss",                        "PT_GeneratorTemperatureHubSide1_Ss"),
    VAR_ELEMENT_ALIAS("5.2.67_E",                         "PT_GeneratorTemperatureHubSide1_E"),
    VAR_ELEMENT_ALIAS( "5.2.67_Th",                        "PT_GeneratorTemperatureHubSide1_Th"),
    VAR_ELEMENT_ALIAS("5.2.67_Ht",                        "PT_GeneratorTemperatureHubSide1_Ht"),
    VAR_ELEMENT_ALIAS("5.2.67_S",                         "PT_GeneratorTemperatureHubSide1_S"),
    VAR_ELEMENT_ALIAS("5.2.67_O",                         "PT_GeneratorTemperatureHubSide1_O"),

    VAR_ELEMENT_ALIAS("5.2.68",                           "PT_GeneratorTemperatureHubSide2"),
    VAR_ELEMENT_ALIAS("5.2.68_Ss",                        "PT_GeneratorTemperatureHubSide2_Ss"),
    VAR_ELEMENT_ALIAS("5.2.68_E",                         "PT_GeneratorTemperatureHubSide2_E"),
    VAR_ELEMENT_ALIAS( "5.2.68_Th",                        "PT_GeneratorTemperatureHubSide2_Th"),
    VAR_ELEMENT_ALIAS("5.2.68_Ht",                        "PT_GeneratorTemperatureHubSide2_Ht"),
    VAR_ELEMENT_ALIAS("5.2.68_S",                         "PT_GeneratorTemperatureHubSide2_S"),
    VAR_ELEMENT_ALIAS("5.2.68_O",                         "PT_GeneratorTemperatureHubSide2_O"),

    VAR_ELEMENT_ALIAS("5.2.69",                           "PT_GeneratorTemperatureHubSide3"),
    VAR_ELEMENT_ALIAS("5.2.69_Ss",                        "PT_GeneratorTemperatureHubSide3_Ss"),
    VAR_ELEMENT_ALIAS("5.2.69_E",                         "PT_GeneratorTemperatureHubSide3_E"),
    VAR_ELEMENT_ALIAS( "5.2.69_Th",                        "PT_GeneratorTemperatureHubSide3_Th"),
    VAR_ELEMENT_ALIAS("5.2.69_Ht",                        "PT_GeneratorTemperatureHubSide3_Ht"),
    VAR_ELEMENT_ALIAS("5.2.69_S",                         "PT_GeneratorTemperatureHubSide3_S"),
    VAR_ELEMENT_ALIAS("5.2.69_O",                         "PT_GeneratorTemperatureHubSide3_O"),

    VAR_ELEMENT_ALIAS("5.2.70",                           "PT_GeneratorTemperatureHubSide4"),
    VAR_ELEMENT_ALIAS("5.2.70_Ss",                        "PT_GeneratorTemperatureHubSide4_Ss"),
    VAR_ELEMENT_ALIAS("5.2.70_E",                         "PT_GeneratorTemperatureHubSide4_E"),
    VAR_ELEMENT_ALIAS( "5.2.70_Th",                        "PT_GeneratorTemperatureHubSide4_Th"),
    VAR_ELEMENT_ALIAS("5.2.70_Ht",                        "PT_GeneratorTemperatureHubSide4_Ht"),
    VAR_ELEMENT_ALIAS("5.2.70_S",                         "PT_GeneratorTemperatureHubSide4_S"),
    VAR_ELEMENT_ALIAS("5.2.70_O",                         "PT_GeneratorTemperatureHubSide4_O"),

    VAR_ELEMENT_ALIAS("5.2.71",                           "PT_GeneratorTemperatureHubSide5"),
    VAR_ELEMENT_ALIAS("5.2.71_Ss",                        "PT_GeneratorTemperatureHubSide5_Ss"),
    VAR_ELEMENT_ALIAS("5.2.71_E",                         "PT_GeneratorTemperatureHubSide5_E"),
    VAR_ELEMENT_ALIAS( "5.2.71_Th",                        "PT_GeneratorTemperatureHubSide5_Th"),
    VAR_ELEMENT_ALIAS("5.2.71_Ht",                        "PT_GeneratorTemperatureHubSide5_Ht"),
    VAR_ELEMENT_ALIAS("5.2.71_S",                         "PT_GeneratorTemperatureHubSide5_S"),
    VAR_ELEMENT_ALIAS("5.2.71_O",                         "PT_GeneratorTemperatureHubSide5_O"),

    VAR_ELEMENT_ALIAS("5.2.72",                           "PT_GeneratorTemperatureHubSide6"),
    VAR_ELEMENT_ALIAS("5.2.72_Ss",                        "PT_GeneratorTemperatureHubSide6_Ss"),
    VAR_ELEMENT_ALIAS("5.2.72_E",                         "PT_GeneratorTemperatureHubSide6_E"),
    VAR_ELEMENT_ALIAS( "5.2.72_Th",                        "PT_GeneratorTemperatureHubSide6_Th"),
    VAR_ELEMENT_ALIAS("5.2.72_Ht",                        "PT_GeneratorTemperatureHubSide6_Ht"),
    VAR_ELEMENT_ALIAS("5.2.72_S",                         "PT_GeneratorTemperatureHubSide6_S"),
    VAR_ELEMENT_ALIAS("5.2.72_O",                         "PT_GeneratorTemperatureHubSide6_O"),

    VAR_ELEMENT_ALIAS("3.2.67",                           "PT_GeneratorTemperatureNacelleSide1"),
    VAR_ELEMENT_ALIAS("3.2.67_Ss",                        "PT_GeneratorTemperatureNacelleSide1_Ss"),
    VAR_ELEMENT_ALIAS("3.2.67_E",                         "PT_GeneratorTemperatureNacelleSide1_E"),
    VAR_ELEMENT_ALIAS( "3.2.67_Th",                        "PT_GeneratorTemperatureNacelleSide1_Th"),
    VAR_ELEMENT_ALIAS("3.2.67_Ht",                        "PT_GeneratorTemperatureNacelleSide1_Ht"),
    VAR_ELEMENT_ALIAS("3.2.67_S",                         "PT_GeneratorTemperatureNacelleSide1_S"),
    VAR_ELEMENT_ALIAS("3.2.67_O",                         "PT_GeneratorTemperatureNacelleSide1_O"),

    VAR_ELEMENT_ALIAS("3.2.68",                           "PT_GeneratorTemperatureNacelleSide2"),
    VAR_ELEMENT_ALIAS("3.2.68_Ss",                        "PT_GeneratorTemperatureNacelleSide2_Ss"),
    VAR_ELEMENT_ALIAS("3.2.68_E",                         "PT_GeneratorTemperatureNacelleSide2_E"),
    VAR_ELEMENT_ALIAS( "3.2.68_Th",                        "PT_GeneratorTemperatureNacelleSide2_Th"),
    VAR_ELEMENT_ALIAS("3.2.68_Ht",                        "PT_GeneratorTemperatureNacelleSide2_Ht"),
    VAR_ELEMENT_ALIAS("3.2.68_S",                         "PT_GeneratorTemperatureNacelleSide2_S"),
    VAR_ELEMENT_ALIAS("3.2.68_O",                         "PT_GeneratorTemperatureNacelleSide2_O"),

    VAR_ELEMENT_ALIAS("3.2.69",                           "PT_GeneratorTemperatureNacelleSide3"),
    VAR_ELEMENT_ALIAS("3.2.69_Ss",                        "PT_GeneratorTemperatureNacelleSide3_Ss"),
    VAR_ELEMENT_ALIAS("3.2.69_E",                         "PT_GeneratorTemperatureNacelleSide3_E"),
    VAR_ELEMENT_ALIAS( "3.2.69_Th",                        "PT_GeneratorTemperatureNacelleSide3_Th"),
    VAR_ELEMENT_ALIAS("3.2.69_Ht",                        "PT_GeneratorTemperatureNacelleSide3_Ht"),
    VAR_ELEMENT_ALIAS("3.2.69_S",                         "PT_GeneratorTemperatureNacelleSide3_S"),
    VAR_ELEMENT_ALIAS("3.2.69_O",                         "PT_GeneratorTemperatureNacelleSide3_O"),

    VAR_ELEMENT_ALIAS("3.2.70",                           "PT_GeneratorTemperatureNacelleSide4"),
    VAR_ELEMENT_ALIAS("3.2.70_Ss",                        "PT_GeneratorTemperatureNacelleSide4_Ss"),
    VAR_ELEMENT_ALIAS("3.2.70_E",                         "PT_GeneratorTemperatureNacelleSide4_E"),
    VAR_ELEMENT_ALIAS( "3.2.70_Th",                        "PT_GeneratorTemperatureNacelleSide4_Th"),
    VAR_ELEMENT_ALIAS("3.2.70_Ht",                        "PT_GeneratorTemperatureNacelleSide4_Ht"),
    VAR_ELEMENT_ALIAS("3.2.70_S",                         "PT_GeneratorTemperatureNacelleSide4_S"),
    VAR_ELEMENT_ALIAS("3.2.70_O",                         "PT_GeneratorTemperatureNacelleSide4_O"),

    VAR_ELEMENT_ALIAS("3.2.71",                           "PT_GeneratorTemperatureNacelleSide5"),
    VAR_ELEMENT_ALIAS("3.2.71_Ss",                        "PT_GeneratorTemperatureNacelleSide5_Ss"),
    VAR_ELEMENT_ALIAS("3.2.71_E",                         "PT_GeneratorTemperatureNacelleSide5_E"),
    VAR_ELEMENT_ALIAS( "3.2.71_Th",                        "PT_GeneratorTemperatureNacelleSide5_Th"),
    VAR_ELEMENT_ALIAS("3.2.71_Ht",                        "PT_GeneratorTemperatureNacelleSide5_Ht"),
    VAR_ELEMENT_ALIAS("3.2.71_S",                         "PT_GeneratorTemperatureNacelleSide5_S"),
    VAR_ELEMENT_ALIAS("3.2.71_O",                         "PT_GeneratorTemperatureNacelleSide5_O"),

    VAR_ELEMENT_ALIAS("3.2.72",                           "PT_GeneratorTemperatureNacelleSide6"),
    VAR_ELEMENT_ALIAS("3.2.72_Ss",                        "PT_GeneratorTemperatureNacelleSide6_Ss"),
    VAR_ELEMENT_ALIAS("3.2.72_E",                         "PT_GeneratorTemperatureNacelleSide6_E"),
    VAR_ELEMENT_ALIAS( "3.2.72_Th",                        "PT_GeneratorTemperatureNacelleSide6_Th"),
    VAR_ELEMENT_ALIAS("3.2.72_Ht",                        "PT_GeneratorTemperatureNacelleSide6_Ht"),
    VAR_ELEMENT_ALIAS("3.2.72_S",                         "PT_GeneratorTemperatureNacelleSide6_S"),
    VAR_ELEMENT_ALIAS("3.2.72_O",                         "PT_GeneratorTemperatureNacelleSide6_O"),

    VAR_ELEMENT_ALIAS("3.3.65",                           "PT_GeneratorTemperatureNacelleSide7"),
    VAR_ELEMENT_ALIAS("3.3.65_Ss",                        "PT_GeneratorTemperatureNacelleSide7_Ss"),
    VAR_ELEMENT_ALIAS("3.3.65_E",                         "PT_GeneratorTemperatureNacelleSide7_E"),
    VAR_ELEMENT_ALIAS( "3.3.65_Th",                        "PT_GeneratorTemperatureNacelleSide7_Th"),
    VAR_ELEMENT_ALIAS("3.3.65_Ht",                        "PT_GeneratorTemperatureNacelleSide7_Ht"),
    VAR_ELEMENT_ALIAS("3.3.65_S",                         "PT_GeneratorTemperatureNacelleSide7_S"),
    VAR_ELEMENT_ALIAS("3.3.65_O",                         "PT_GeneratorTemperatureNacelleSide7_O"),

    VAR_ELEMENT_ALIAS("3.3.66",                           "PT_GeneratorTemperatureNacelleSide8"),
    VAR_ELEMENT_ALIAS("3.3.66_Ss",                        "PT_GeneratorTemperatureNacelleSide8_Ss"),
    VAR_ELEMENT_ALIAS("3.3.66_E",                         "PT_GeneratorTemperatureNacelleSide8_E"),
    VAR_ELEMENT_ALIAS( "3.3.66_Th",                        "PT_GeneratorTemperatureNacelleSide8_Th"),
    VAR_ELEMENT_ALIAS("3.3.66_Ht",                        "PT_GeneratorTemperatureNacelleSide8_Ht"),
    VAR_ELEMENT_ALIAS("3.3.66_S",                         "PT_GeneratorTemperatureNacelleSide8_S"),
    VAR_ELEMENT_ALIAS("3.3.66_O",                         "PT_GeneratorTemperatureNacelleSide8_O"),

    VAR_ELEMENT_ALIAS("3.3.67",                           "PT_GeneratorTemperatureNacelleSide9"),
    VAR_ELEMENT_ALIAS("3.3.67_Ss",                        "PT_GeneratorTemperatureNacelleSide9_Ss"),
    VAR_ELEMENT_ALIAS("3.3.67_E",                         "PT_GeneratorTemperatureNacelleSide9_E"),
    VAR_ELEMENT_ALIAS( "3.3.67_Th",                        "PT_GeneratorTemperatureNacelleSide9_Th"),
    VAR_ELEMENT_ALIAS("3.3.67_Ht",                        "PT_GeneratorTemperatureNacelleSide9_Ht"),
    VAR_ELEMENT_ALIAS("3.3.67_S",                         "PT_GeneratorTemperatureNacelleSide9_S"),
    VAR_ELEMENT_ALIAS("3.3.67_O",                         "PT_GeneratorTemperatureNacelleSide9_O"),

    VAR_ELEMENT_ALIAS("3.3.68",                           "PT_GeneratorTemperatureNacelleSide10"),
    VAR_ELEMENT_ALIAS("3.3.68_Ss",                        "PT_GeneratorTemperatureNacelleSide10_Ss"),
    VAR_ELEMENT_ALIAS("3.3.68_E",                         "PT_GeneratorTemperatureNacelleSide10_E"),
    VAR_ELEMENT_ALIAS( "3.3.68_Th",                        "PT_GeneratorTemperatureNacelleSide10_Th"),
    VAR_ELEMENT_ALIAS("3.3.68_Ht",                        "PT_GeneratorTemperatureNacelleSide10_Ht"),
    VAR_ELEMENT_ALIAS("3.3.68_S",                         "PT_GeneratorTemperatureNacelleSide10_S"),
    VAR_ELEMENT_ALIAS("3.3.68_O",                         "PT_GeneratorTemperatureNacelleSide10_O"),

    VAR_ELEMENT_ALIAS("3.3.69",                           "PT_GeneratorTemperatureNacelleSide11"),
    VAR_ELEMENT_ALIAS("3.3.69_Ss",                        "PT_GeneratorTemperatureNacelleSide11_Ss"),
    VAR_ELEMENT_ALIAS("3.3.69_E",                         "PT_GeneratorTemperatureNacelleSide11_E"),
    VAR_ELEMENT_ALIAS( "3.3.69_Th",                        "PT_GeneratorTemperatureNacelleSide11_Th"),
    VAR_ELEMENT_ALIAS("3.3.69_Ht",                        "PT_GeneratorTemperatureNacelleSide11_Ht"),
    VAR_ELEMENT_ALIAS("3.3.69_S",                         "PT_GeneratorTemperatureNacelleSide11_S"),
    VAR_ELEMENT_ALIAS("3.3.69_O",                         "PT_GeneratorTemperatureNacelleSide11_O"),

    VAR_ELEMENT_ALIAS("3.3.70",                           "PT_GeneratorTemperatureNacelleSide12"),
    VAR_ELEMENT_ALIAS("3.3.70_Ss",                        "PT_GeneratorTemperatureNacelleSide12_Ss"),
    VAR_ELEMENT_ALIAS("3.3.70_E",                         "PT_GeneratorTemperatureNacelleSide12_E"),
    VAR_ELEMENT_ALIAS( "3.3.70_Th",                        "PT_GeneratorTemperatureNacelleSide12_Th"),
    VAR_ELEMENT_ALIAS("3.3.70_Ht",                        "PT_GeneratorTemperatureNacelleSide12_Ht"),
    VAR_ELEMENT_ALIAS("3.3.70_S",                         "PT_GeneratorTemperatureNacelleSide12_S"),
    VAR_ELEMENT_ALIAS("3.3.70_O",                         "PT_GeneratorTemperatureNacelleSide12_O"),

    VAR_ELEMENT_ALIAS("3.3.71",                           "PT_GeneratorTemperatureNacelleSide13"),
    VAR_ELEMENT_ALIAS("3.3.71_Ss",                        "PT_GeneratorTemperatureNacelleSide13_Ss"),
    VAR_ELEMENT_ALIAS("3.3.71_E",                         "PT_GeneratorTemperatureNacelleSide13_E"),
    VAR_ELEMENT_ALIAS( "3.3.71_Th",                        "PT_GeneratorTemperatureNacelleSide13_Th"),
    VAR_ELEMENT_ALIAS("3.3.71_Ht",                        "PT_GeneratorTemperatureNacelleSide13_Ht"),
    VAR_ELEMENT_ALIAS("3.3.71_S",                         "PT_GeneratorTemperatureNacelleSide13_S"),
    VAR_ELEMENT_ALIAS("3.3.71_O",                         "PT_GeneratorTemperatureNacelleSide13_O"),

    VAR_ELEMENT_ALIAS("3.3.72",                           "PT_GeneratorTemperatureNacelleSide14"),
    VAR_ELEMENT_ALIAS("3.3.72_Ss",                        "PT_GeneratorTemperatureNacelleSide14_Ss"),
    VAR_ELEMENT_ALIAS("3.3.72_E",                         "PT_GeneratorTemperatureNacelleSide14_E"),
    VAR_ELEMENT_ALIAS( "3.3.72_Th",                        "PT_GeneratorTemperatureNacelleSide14_Th"),
    VAR_ELEMENT_ALIAS("3.3.72_Ht",                        "PT_GeneratorTemperatureNacelleSide14_Ht"),
    VAR_ELEMENT_ALIAS("3.3.72_S",                         "PT_GeneratorTemperatureNacelleSide14_S"),
    VAR_ELEMENT_ALIAS("3.3.72_O",                         "PT_GeneratorTemperatureNacelleSide14_O"),

    VAR_ELEMENT_ALIAS("3.3.9",                            "DO_GeneratorCooling_Ventilation1_ON"),

    VAR_ELEMENT_ALIAS("3.3.11",                           "DO_GeneratorCooling_Ventilation2_ON"),

    VAR_ELEMENT_ALIAS("3.4.9",                            "PT_GeneratorTemperatureNacelleSide15"),
    VAR_ELEMENT_ALIAS("3.4.9_Ss",                         "PT_GeneratorTemperatureNacelleSide15_Ss"),
    VAR_ELEMENT_ALIAS("3.4.9_E",                          "PT_GeneratorTemperatureNacelleSide15_E"),
    VAR_ELEMENT_ALIAS( "3.4.9_Th",                         "PT_GeneratorTemperatureNacelleSide15_Th"),
    VAR_ELEMENT_ALIAS("3.4.9_Ht",                         "PT_GeneratorTemperatureNacelleSide15_Ht"),
    VAR_ELEMENT_ALIAS("3.4.9_S",                          "PT_GeneratorTemperatureNacelleSide15_S"),
    VAR_ELEMENT_ALIAS("3.4.9_O",                          "PT_GeneratorTemperatureNacelleSide15_O"),

    VAR_ELEMENT_ALIAS("3.4.10",                           "PT_GeneratorTemperatureNacelleSide16"),
    VAR_ELEMENT_ALIAS("3.4.10_Ss",                        "PT_GeneratorTemperatureNacelleSide16_Ss"),
    VAR_ELEMENT_ALIAS("3.4.10_E",                         "PT_GeneratorTemperatureNacelleSide16_E"),
    VAR_ELEMENT_ALIAS( "3.4.10_Th",                        "PT_GeneratorTemperatureNacelleSide16_Th"),
    VAR_ELEMENT_ALIAS("3.4.10_Ht",                        "PT_GeneratorTemperatureNacelleSide16_Ht"),
    VAR_ELEMENT_ALIAS("3.4.10_S",                         "PT_GeneratorTemperatureNacelleSide16_S"),
    VAR_ELEMENT_ALIAS("3.4.10_O",                         "PT_GeneratorTemperatureNacelleSide16_O"),

    VAR_ELEMENT_ALIAS("3.4.11",                           "PT_GeneratorTemperatureNacelleSide17"),
    VAR_ELEMENT_ALIAS("3.4.11_Ss",                        "PT_GeneratorTemperatureNacelleSide17_Ss"),
    VAR_ELEMENT_ALIAS("3.4.11_E",                         "PT_GeneratorTemperatureNacelleSide17_E"),
    VAR_ELEMENT_ALIAS( "3.4.11_Th",                        "PT_GeneratorTemperatureNacelleSide17_Th"),
    VAR_ELEMENT_ALIAS("3.4.11_Ht",                        "PT_GeneratorTemperatureNacelleSide17_Ht"),
    VAR_ELEMENT_ALIAS("3.4.11_S",                         "PT_GeneratorTemperatureNacelleSide17_S"),
    VAR_ELEMENT_ALIAS("3.4.11_O",                         "PT_GeneratorTemperatureNacelleSide17_O"),

    VAR_ELEMENT_ALIAS("3.4.12",                           "PT_GeneratorTemperatureNacelleSide18"),
    VAR_ELEMENT_ALIAS("3.4.12_Ss",                        "PT_GeneratorTemperatureNacelleSide18_Ss"),
    VAR_ELEMENT_ALIAS("3.4.12_E",                         "PT_GeneratorTemperatureNacelleSide18_E"),
    VAR_ELEMENT_ALIAS( "3.4.12_Th",                        "PT_GeneratorTemperatureNacelleSide18_Th"),
    VAR_ELEMENT_ALIAS("3.4.12_Ht",                        "PT_GeneratorTemperatureNacelleSide18_Ht"),
    VAR_ELEMENT_ALIAS("3.4.12_S",                         "PT_GeneratorTemperatureNacelleSide18_S"),
    VAR_ELEMENT_ALIAS("3.4.12_O",                         "PT_GeneratorTemperatureNacelleSide18_O"),

    VAR_ELEMENT_ALIAS("3.4.13",                           "PT_GeneratorTemperatureNacelleSide19"),
    VAR_ELEMENT_ALIAS("3.4.13_Ss",                        "PT_GeneratorTemperatureNacelleSide19_Ss"),
    VAR_ELEMENT_ALIAS("3.4.13_E",                         "PT_GeneratorTemperatureNacelleSide19_E"),
    VAR_ELEMENT_ALIAS( "3.4.13_Th",                        "PT_GeneratorTemperatureNacelleSide19_Th"),
    VAR_ELEMENT_ALIAS("3.4.13_Ht",                        "PT_GeneratorTemperatureNacelleSide19_Ht"),
    VAR_ELEMENT_ALIAS("3.4.13_S",                         "PT_GeneratorTemperatureNacelleSide19_S"),
    VAR_ELEMENT_ALIAS("3.4.13_O",                         "PT_GeneratorTemperatureNacelleSide19_O"),

    VAR_ELEMENT_ALIAS("3.4.14",                           "PT_GeneratorTemperatureNacelleSide20"),
    VAR_ELEMENT_ALIAS("3.4.14_Ss",                        "PT_GeneratorTemperatureNacelleSide20_Ss"),
    VAR_ELEMENT_ALIAS("3.4.14_E",                         "PT_GeneratorTemperatureNacelleSide20_E"),
    VAR_ELEMENT_ALIAS( "3.4.14_Th",                        "PT_GeneratorTemperatureNacelleSide20_Th"),
    VAR_ELEMENT_ALIAS("3.4.14_Ht",                        "PT_GeneratorTemperatureNacelleSide20_Ht"),
    VAR_ELEMENT_ALIAS("3.4.14_S",                         "PT_GeneratorTemperatureNacelleSide20_S"),
    VAR_ELEMENT_ALIAS("3.4.14_O",                         "PT_GeneratorTemperatureNacelleSide20_O"),

    VAR_ELEMENT_ALIAS("3.4.2",                            "PT_GENC_RearBearingTemp"),
    VAR_ELEMENT_ALIAS("3.4.2_Ss",                         "PT_GENC_RearBearingTemp_Ss"),
    VAR_ELEMENT_ALIAS("3.4.2_E",                          "PT_GENC_RearBearingTemp_E"),
    VAR_ELEMENT_ALIAS( "3.4.2_Th",                         "PT_GENC_RearBearingTemp_Th"),
    VAR_ELEMENT_ALIAS("3.4.2_Ht",                         "PT_GENC_RearBearingTemp_Ht"),
    VAR_ELEMENT_ALIAS("3.4.2_S",                          "PT_GENC_RearBearingTemp_S"),
    VAR_ELEMENT_ALIAS("3.4.2_O",                          "PT_GENC_RearBearingTemp_O"),

    VAR_ELEMENT_ALIAS("5.2.57",                           "AI_GENC_MainBearingTempVolt"),
    VAR_ELEMENT_ALIAS("5.2.57_Ss",                        "AI_GENC_MainBearingTempVolt_Ss"),
    VAR_ELEMENT_ALIAS("5.2.57_E",                         "AI_GENC_MainBearingTempVolt_E"),
    VAR_ELEMENT_ALIAS( "5.2.57_Th",                        "AI_GENC_MainBearingTempVolt_Th"),
    VAR_ELEMENT_ALIAS("5.2.57_Ht",                        "AI_GENC_MainBearingTempVolt_Ht"),
    VAR_ELEMENT_ALIAS("5.2.57_S",                         "AI_GENC_MainBearingTempVolt_S"),
    VAR_ELEMENT_ALIAS("5.2.57_O",                         "AI_GENC_MainBearingTempVolt_O"),

};
size_t GeneratorCooling_MT_Type1IOVars1Size = sizeof(GeneratorCooling_MT_Type1IOVars1)/sizeof(GeneratorCooling_MT_Type1IOVars1[0]);

void GeneratorCooling_MT_Type1SetLockValues1(void)
{
   SetLockValue("DI_GeneratorFan1ContactorFB_Ss",        TYP_8,     1);
   SetLockValue("DI_GeneratorFan1ContactorFB_E",         TYP_8,     1);
   SetValue("DI_GeneratorFan1ContactorFB_I",             TYP_8,     0);
   SetLockValue("DI_GeneratorFan1ContactorFB_Cm",        TYP_8,     1);
   SetLockValue("DI_GeneratorFan1ContactorFB_Ht",        TYP_32,    100);

   SetLockValue("DI_GeneratorFan2ContactorFB_Ss",        TYP_8,     1);
   SetLockValue("DI_GeneratorFan2ContactorFB_E",         TYP_8,     1);
   SetValue("DI_GeneratorFan2ContactorFB_I",             TYP_8,     0);
   SetLockValue("DI_GeneratorFan2ContactorFB_Cm",        TYP_8,     1);
   SetLockValue("DI_GeneratorFan2ContactorFB_Ht",        TYP_32,    100);

   SetLockValue("TI_GeneratorFan1Thermistor_Ss",         TYP_8,     1);
   SetLockValue("TI_GeneratorFan1Thermistor_E",          TYP_8,     1);
   SetValue("TI_GeneratorFan1Thermistor_I",              TYP_8,     0);
   SetLockValue("TI_GeneratorFan1Thermistor_Cm",         TYP_8,     1);
   SetLockValue("TI_GeneratorFan1Thermistor_Ht",         TYP_32,    1000);

   SetValue("TI_GeneratorFan1Thermistor_Hi",             TYP_32,    2800);

   SetValue("TI_GeneratorFan1Thermistor_Lo",             TYP_32,    1300);

   SetLockValue("TI_GeneratorFan2Thermistor_Ss",         TYP_8,     1);
   SetLockValue("TI_GeneratorFan2Thermistor_E",          TYP_8,     1);
   SetValue("TI_GeneratorFan2Thermistor_I",              TYP_8,     0);
   SetLockValue("TI_GeneratorFan2Thermistor_Cm",         TYP_8,     1);
   SetLockValue("TI_GeneratorFan2Thermistor_Ht",         TYP_32,    1000);

   SetValue("TI_GeneratorFan2Thermistor_Hi",             TYP_32,    2800);

   SetValue("TI_GeneratorFan2Thermistor_Lo",             TYP_32,    1300);

   SetLockValue("PT_GeneratorTemperatureHubSide1_Ss",    TYP_8,     1);
   SetLockValue("PT_GeneratorTemperatureHubSide1_E",     TYP_8,     1);
   SetLockValue("PT_GeneratorTemperatureHubSide1_Th",    TYP_16,    10);
   SetLockValue("PT_GeneratorTemperatureHubSide1_Ht",    TYP_32,    1000);
   SetLockValue("PT_GeneratorTemperatureHubSide1_S",     TYP_32,    0);
   SetValue("PT_GeneratorTemperatureHubSide1_O",         TYP_32,    0);

   SetLockValue("PT_GeneratorTemperatureHubSide2_Ss",    TYP_8,     1);
   SetLockValue("PT_GeneratorTemperatureHubSide2_E",     TYP_8,     1);
   SetLockValue("PT_GeneratorTemperatureHubSide2_Th",    TYP_16,    10);
   SetLockValue("PT_GeneratorTemperatureHubSide2_Ht",    TYP_32,    1000);
   SetLockValue("PT_GeneratorTemperatureHubSide2_S",     TYP_32,    0);
   SetValue("PT_GeneratorTemperatureHubSide2_O",         TYP_32,    0);

   SetLockValue("PT_GeneratorTemperatureHubSide3_Ss",    TYP_8,     1);
   SetLockValue("PT_GeneratorTemperatureHubSide3_E",     TYP_8,     1);
   SetLockValue("PT_GeneratorTemperatureHubSide3_Th",    TYP_16,    10);
   SetLockValue("PT_GeneratorTemperatureHubSide3_Ht",    TYP_32,    1000);
   SetLockValue("PT_GeneratorTemperatureHubSide3_S",     TYP_32,    0);
   SetValue("PT_GeneratorTemperatureHubSide3_O",         TYP_32,    0);

   SetLockValue("PT_GeneratorTemperatureHubSide4_Ss",    TYP_8,     1);
   SetLockValue("PT_GeneratorTemperatureHubSide4_E",     TYP_8,     1);
   SetLockValue("PT_GeneratorTemperatureHubSide4_Th",    TYP_16,    10);
   SetLockValue("PT_GeneratorTemperatureHubSide4_Ht",    TYP_32,    1000);
   SetLockValue("PT_GeneratorTemperatureHubSide4_S",     TYP_32,    0);
   SetValue("PT_GeneratorTemperatureHubSide4_O",         TYP_32,    0);

   SetLockValue("PT_GeneratorTemperatureHubSide5_Ss",    TYP_8,     1);
   SetLockValue("PT_GeneratorTemperatureHubSide5_E",     TYP_8,     1);
   SetLockValue("PT_GeneratorTemperatureHubSide5_Th",    TYP_16,    10);
   SetLockValue("PT_GeneratorTemperatureHubSide5_Ht",    TYP_32,    1000);
   SetLockValue("PT_GeneratorTemperatureHubSide5_S",     TYP_32,    0);
   SetValue("PT_GeneratorTemperatureHubSide5_O",         TYP_32,    0);

   SetLockValue("PT_GeneratorTemperatureHubSide6_Ss",    TYP_8,     1);
   SetLockValue("PT_GeneratorTemperatureHubSide6_E",     TYP_8,     1);
   SetLockValue("PT_GeneratorTemperatureHubSide6_Th",    TYP_16,    10);
   SetLockValue("PT_GeneratorTemperatureHubSide6_Ht",    TYP_32,    1000);
   SetLockValue("PT_GeneratorTemperatureHubSide6_S",     TYP_32,    0);
   SetValue("PT_GeneratorTemperatureHubSide6_O",         TYP_32,    0);

   SetLockValue("PT_GeneratorTemperatureNacelleSide1_Ss",TYP_8,     1);
   SetLockValue("PT_GeneratorTemperatureNacelleSide1_E", TYP_8,     1);
   SetLockValue("PT_GeneratorTemperatureNacelleSide1_Th",TYP_16,    10);
   SetLockValue("PT_GeneratorTemperatureNacelleSide1_Ht",TYP_32,    1000);
   SetLockValue("PT_GeneratorTemperatureNacelleSide1_S", TYP_32,    0);
   SetValue("PT_GeneratorTemperatureNacelleSide1_O",     TYP_32,    0);

   SetLockValue("PT_GeneratorTemperatureNacelleSide2_Ss",TYP_8,     1);
   SetLockValue("PT_GeneratorTemperatureNacelleSide2_E", TYP_8,     1);
   SetLockValue("PT_GeneratorTemperatureNacelleSide2_Th",TYP_16,    10);
   SetLockValue("PT_GeneratorTemperatureNacelleSide2_Ht",TYP_32,    1000);
   SetLockValue("PT_GeneratorTemperatureNacelleSide2_S", TYP_32,    0);
   SetValue("PT_GeneratorTemperatureNacelleSide2_O",     TYP_32,    0);

   SetLockValue("PT_GeneratorTemperatureNacelleSide3_Ss",TYP_8,     1);
   SetLockValue("PT_GeneratorTemperatureNacelleSide3_E", TYP_8,     1);
   SetLockValue("PT_GeneratorTemperatureNacelleSide3_Th",TYP_16,    10);
   SetLockValue("PT_GeneratorTemperatureNacelleSide3_Ht",TYP_32,    1000);
   SetLockValue("PT_GeneratorTemperatureNacelleSide3_S", TYP_32,    0);
   SetValue("PT_GeneratorTemperatureNacelleSide3_O",     TYP_32,    0);

   SetLockValue("PT_GeneratorTemperatureNacelleSide4_Ss",TYP_8,     1);
   SetLockValue("PT_GeneratorTemperatureNacelleSide4_E", TYP_8,     1);
   SetLockValue("PT_GeneratorTemperatureNacelleSide4_Th",TYP_16,    10);
   SetLockValue("PT_GeneratorTemperatureNacelleSide4_Ht",TYP_32,    1000);
   SetLockValue("PT_GeneratorTemperatureNacelleSide4_S", TYP_32,    0);
   SetValue("PT_GeneratorTemperatureNacelleSide4_O",     TYP_32,    0);

   SetLockValue("PT_GeneratorTemperatureNacelleSide5_Ss",TYP_8,     1);
   SetLockValue("PT_GeneratorTemperatureNacelleSide5_E", TYP_8,     1);
   SetLockValue("PT_GeneratorTemperatureNacelleSide5_Th",TYP_16,    10);
   SetLockValue("PT_GeneratorTemperatureNacelleSide5_Ht",TYP_32,    1000);
   SetLockValue("PT_GeneratorTemperatureNacelleSide5_S", TYP_32,    0);
   SetValue("PT_GeneratorTemperatureNacelleSide5_O",     TYP_32,    0);

   SetLockValue("PT_GeneratorTemperatureNacelleSide6_Ss",TYP_8,     1);
   SetLockValue("PT_GeneratorTemperatureNacelleSide6_E", TYP_8,     1);
   SetLockValue("PT_GeneratorTemperatureNacelleSide6_Th",TYP_16,    10);
   SetLockValue("PT_GeneratorTemperatureNacelleSide6_Ht",TYP_32,    1000);
   SetLockValue("PT_GeneratorTemperatureNacelleSide6_S", TYP_32,    0);
   SetValue("PT_GeneratorTemperatureNacelleSide6_O",     TYP_32,    0);

   SetLockValue("PT_GeneratorTemperatureNacelleSide7_Ss",TYP_8,     1);
   SetLockValue("PT_GeneratorTemperatureNacelleSide7_E", TYP_8,     1);
   SetLockValue("PT_GeneratorTemperatureNacelleSide7_Th",TYP_16,    10);
   SetLockValue("PT_GeneratorTemperatureNacelleSide7_Ht",TYP_32,    1000);
   SetLockValue("PT_GeneratorTemperatureNacelleSide7_S", TYP_32,    0);
   SetValue("PT_GeneratorTemperatureNacelleSide7_O",     TYP_32,    0);

   SetLockValue("PT_GeneratorTemperatureNacelleSide8_Ss",TYP_8,     1);
   SetLockValue("PT_GeneratorTemperatureNacelleSide8_E", TYP_8,     1);
   SetLockValue("PT_GeneratorTemperatureNacelleSide8_Th",TYP_16,    10);
   SetLockValue("PT_GeneratorTemperatureNacelleSide8_Ht",TYP_32,    1000);
   SetLockValue("PT_GeneratorTemperatureNacelleSide8_S", TYP_32,    0);
   SetValue("PT_GeneratorTemperatureNacelleSide8_O",     TYP_32,    0);

   SetLockValue("PT_GeneratorTemperatureNacelleSide9_Ss",TYP_8,     1);
   SetLockValue("PT_GeneratorTemperatureNacelleSide9_E", TYP_8,     1);
   SetLockValue("PT_GeneratorTemperatureNacelleSide9_Th",TYP_16,    10);
   SetLockValue("PT_GeneratorTemperatureNacelleSide9_Ht",TYP_32,    1000);
   SetLockValue("PT_GeneratorTemperatureNacelleSide9_S", TYP_32,    0);
   SetValue("PT_GeneratorTemperatureNacelleSide9_O",     TYP_32,    0);

   SetLockValue("PT_GeneratorTemperatureNacelleSide10_Ss",TYP_8,     1);
   SetLockValue("PT_GeneratorTemperatureNacelleSide10_E",TYP_8,     1);
   SetLockValue("PT_GeneratorTemperatureNacelleSide10_Th",TYP_16,    10);
   SetLockValue("PT_GeneratorTemperatureNacelleSide10_Ht",TYP_32,    1000);
   SetLockValue("PT_GeneratorTemperatureNacelleSide10_S",TYP_32,    0);
   SetValue("PT_GeneratorTemperatureNacelleSide10_O",    TYP_32,    0);

   SetLockValue("PT_GeneratorTemperatureNacelleSide11_Ss",TYP_8,     1);
   SetLockValue("PT_GeneratorTemperatureNacelleSide11_E",TYP_8,     1);
   SetLockValue("PT_GeneratorTemperatureNacelleSide11_Th",TYP_16,    10);
   SetLockValue("PT_GeneratorTemperatureNacelleSide11_Ht",TYP_32,    1000);
   SetLockValue("PT_GeneratorTemperatureNacelleSide11_S",TYP_32,    0);
   SetValue("PT_GeneratorTemperatureNacelleSide11_O",    TYP_32,    0);

   SetLockValue("PT_GeneratorTemperatureNacelleSide12_Ss",TYP_8,     1);
   SetLockValue("PT_GeneratorTemperatureNacelleSide12_E",TYP_8,     1);
   SetLockValue("PT_GeneratorTemperatureNacelleSide12_Th",TYP_16,    10);
   SetLockValue("PT_GeneratorTemperatureNacelleSide12_Ht",TYP_32,    1000);
   SetLockValue("PT_GeneratorTemperatureNacelleSide12_S",TYP_32,    0);
   SetValue("PT_GeneratorTemperatureNacelleSide12_O",    TYP_32,    0);

   SetLockValue("PT_GeneratorTemperatureNacelleSide13_Ss",TYP_8,     1);
   SetLockValue("PT_GeneratorTemperatureNacelleSide13_E",TYP_8,     1);
   SetLockValue("PT_GeneratorTemperatureNacelleSide13_Th",TYP_16,    10);
   SetLockValue("PT_GeneratorTemperatureNacelleSide13_Ht",TYP_32,    1000);
   SetLockValue("PT_GeneratorTemperatureNacelleSide13_S",TYP_32,    0);
   SetValue("PT_GeneratorTemperatureNacelleSide13_O",    TYP_32,    0);

   SetLockValue("PT_GeneratorTemperatureNacelleSide14_Ss",TYP_8,     1);
   SetLockValue("PT_GeneratorTemperatureNacelleSide14_E",TYP_8,     1);
   SetLockValue("PT_GeneratorTemperatureNacelleSide14_Th",TYP_16,    10);
   SetLockValue("PT_GeneratorTemperatureNacelleSide14_Ht",TYP_32,    1000);
   SetLockValue("PT_GeneratorTemperatureNacelleSide14_S",TYP_32,    0);
   SetValue("PT_GeneratorTemperatureNacelleSide14_O",    TYP_32,    0);

   SetLockValue("PT_GeneratorTemperatureNacelleSide15_Ss",TYP_8,     1);
   SetLockValue("PT_GeneratorTemperatureNacelleSide15_E",TYP_8,     1);
   SetLockValue("PT_GeneratorTemperatureNacelleSide15_Th",TYP_16,    10);
   SetLockValue("PT_GeneratorTemperatureNacelleSide15_Ht",TYP_32,    1000);
   SetLockValue("PT_GeneratorTemperatureNacelleSide15_S",TYP_32,    0);
   SetValue("PT_GeneratorTemperatureNacelleSide15_O",    TYP_32,    0);

   SetLockValue("PT_GeneratorTemperatureNacelleSide16_Ss",TYP_8,     1);
   SetLockValue("PT_GeneratorTemperatureNacelleSide16_E",TYP_8,     1);
   SetLockValue("PT_GeneratorTemperatureNacelleSide16_Th",TYP_16,    10);
   SetLockValue("PT_GeneratorTemperatureNacelleSide16_Ht",TYP_32,    1000);
   SetLockValue("PT_GeneratorTemperatureNacelleSide16_S",TYP_32,    0);
   SetValue("PT_GeneratorTemperatureNacelleSide16_O",    TYP_32,    0);

   SetLockValue("PT_GeneratorTemperatureNacelleSide17_Ss",TYP_8,     1);
   SetLockValue("PT_GeneratorTemperatureNacelleSide17_E",TYP_8,     1);
   SetLockValue("PT_GeneratorTemperatureNacelleSide17_Th",TYP_16,    10);
   SetLockValue("PT_GeneratorTemperatureNacelleSide17_Ht",TYP_32,    1000);
   SetLockValue("PT_GeneratorTemperatureNacelleSide17_S",TYP_32,    0);
   SetValue("PT_GeneratorTemperatureNacelleSide17_O",    TYP_32,    0);

   SetLockValue("PT_GeneratorTemperatureNacelleSide18_Ss",TYP_8,     1);
   SetLockValue("PT_GeneratorTemperatureNacelleSide18_E",TYP_8,     1);
   SetLockValue("PT_GeneratorTemperatureNacelleSide18_Th",TYP_16,    10);
   SetLockValue("PT_GeneratorTemperatureNacelleSide18_Ht",TYP_32,    1000);
   SetLockValue("PT_GeneratorTemperatureNacelleSide18_S",TYP_32,    0);
   SetValue("PT_GeneratorTemperatureNacelleSide18_O",    TYP_32,    0);

   SetLockValue("PT_GeneratorTemperatureNacelleSide19_Ss",TYP_8,     1);
   SetLockValue("PT_GeneratorTemperatureNacelleSide19_E",TYP_8,     1);
   SetLockValue("PT_GeneratorTemperatureNacelleSide19_Th",TYP_16,    10);
   SetLockValue("PT_GeneratorTemperatureNacelleSide19_Ht",TYP_32,    1000);
   SetLockValue("PT_GeneratorTemperatureNacelleSide19_S",TYP_32,    0);
   SetValue("PT_GeneratorTemperatureNacelleSide19_O",    TYP_32,    0);

   SetLockValue("PT_GeneratorTemperatureNacelleSide20_Ss",TYP_8,     1);
   SetLockValue("PT_GeneratorTemperatureNacelleSide20_E",TYP_8,     1);
   SetLockValue("PT_GeneratorTemperatureNacelleSide20_Th",TYP_16,    10);
   SetLockValue("PT_GeneratorTemperatureNacelleSide20_Ht",TYP_32,    1000);
   SetLockValue("PT_GeneratorTemperatureNacelleSide20_S",TYP_32,    0);
   SetValue("PT_GeneratorTemperatureNacelleSide20_O",    TYP_32,    0);

   SetLockValue("PT_GENC_RearBearingTemp_Ss",            TYP_8,     1);
   SetLockValue("PT_GENC_RearBearingTemp_E",             TYP_8,     1);
   SetLockValue("PT_GENC_RearBearingTemp_Th",            TYP_16,    10);
   SetLockValue("PT_GENC_RearBearingTemp_Ht",            TYP_32,    1000);
   SetLockValue("PT_GENC_RearBearingTemp_S",             TYP_32,    0);
   SetValue("PT_GENC_RearBearingTemp_O",                 TYP_32,    0);

   SetLockValue("AI_GENC_MainBearingTempVolt_Ss",        TYP_8,     1);
   SetLockValue("AI_GENC_MainBearingTempVolt_E",         TYP_8,     1);
   SetLockValue("AI_GENC_MainBearingTempVolt_Th",        TYP_16,    1);
   SetLockValue("AI_GENC_MainBearingTempVolt_Ht",        TYP_32,    10000);
   SetLockValue("AI_GENC_MainBearingTempVolt_S",         TYP_32,    0);
   SetValue("AI_GENC_MainBearingTempVolt_O",             TYP_32,    0);

   SetValue("FansComPortConfigurationActivation",        TYP_8,     0);

   SetValue("FansComPortConfigurationBaudRate",          TYP_32,    9600);

   SetValue("FansComPortConfigurationDataBits",          TYP_8,     8);

   SetValue("FansComPortConfigurationMode",              TYP_8,     5);

   SetValue("FansComPortConfigurationParity",            TYP_8,     0);

   SetValue("FansComPortConfigurationStopBits",          TYP_8,     1);

   SetValue("FansComPortConfigurationSync",              TYP_8,     0);
}


STATUS GeneratorCooling_MT_Type1InitIOAliases()
{
   GeneratorCooling_MT_Type1IOVars = GeneratorCooling_MT_Type1IOVars1;
   GeneratorCooling_MT_Type1IOVarsSize = GeneratorCooling_MT_Type1IOVars1Size;
   GeneratorCooling_MT_Type1SetLockValues = &GeneratorCooling_MT_Type1SetLockValues1;
   return OS_SUCCESS;
}
//-----------------------------------------------------------------------
// AUTOGENERATED END        AUTOGENERATED END        AUTOGENERATED END
//-----------------------------------------------------------------------

#undef AUTOGENERATED_PART
