//*****************************PEPTOOL Header Start******************************
//                                                                               
//                         Copyright © 2015 Mita-Teknik.                         
//This software may only be used with WP4x00 Controllers delivered by Mita-Teknik
//                                                                               
//*******************************************************************************
//                                                                               
// $PEPTOOL version:9.0$                                                         
// $PEPTOOL file version:101$                                                    
//                                                                               
//*******************************************************************************
//                                                                               
// $Date: 2014/04/23 06:34:38 $                                                  
// $Author: MITA\ihn $                                                           
// $RCSfile: Grid_Conf.c,v $                                                     
// $Revision: 1.7 $                                                              
//                                                                               
//******************************PEPTOOL Header End*******************************

//***********************************************************************
// OS header files
#include <os_main.h>

#include <InitIo.h>

#define AUTOGENERATED_PART

#include <Turbdef.h>

//-----------------------------------------------------------------------
// AUTOGENERATED START     AUTOGENERATED START     AUTOGENERATED START
//-----------------------------------------------------------------------
char Grid_Conf_copyright[] =
{
   67, 111, 112, 121, 114, 105, 103, 104, 116, 32, 63, 32, 50, 48, 49, 53,
   32, 77, 105, 116, 97, 45, 84, 101, 107, 110, 105, 107, 46, 13, 10, 84,
   104, 105, 115, 32, 115, 111, 102, 116, 119, 97, 114, 101, 32, 109, 97, 121,
   32, 111, 110, 108, 121, 32, 98, 101, 32, 117, 115, 101, 100, 32, 119, 105,
   116, 104, 32, 87, 80, 52, 120, 48, 48, 32, 67, 111, 110, 116, 114, 111,
   108, 108, 101, 114, 115, 32, 100, 101, 108, 105, 118, 101, 114, 101, 100, 32,
   98, 121, 32, 77, 105, 116, 97, 45, 84, 101, 107, 110, 105, 107, 0
};
//-----------------------------------------------------------------------
// MODIFIABLE                  MODIFIABLE               MODIFIABLE
//-----------------------------------------------------------------------
const char GridAppGroupName[] = "G_"APP_ID"App";
const char GridAppMenuName[] = "M_"APP_ID"AppMain";
const U8 Grid_Conf_151_MeasureMode = 2;
const U8 Grid_Conf_ModuleGroup = 1;
const U8 Grid_Conf_ModuleNode = 3;

//-----------------------------------------------------------------------
// IO VARIABLES                IO VARIABLES                IO VARIABLES
//-----------------------------------------------------------------------

void (*GridSetLockValues)(void);
struct os_db_alias *GridIOVars;
size_t GridIOVarsSize = 0;
            
struct os_db_alias GridIOVars1[]=
{
    VAR_ELEMENT_ALIAS("1.3.PIL1",                         "AI_GridL1Current"),
    VAR_ELEMENT_ALIAS("1.3.PIL1_Ss",                      "AI_GridL1Current_Ss"),
    VAR_ELEMENT_ALIAS("1.3.PIL1_E",                       "AI_GridL1Current_E"),
    VAR_ELEMENT_ALIAS( "1.3.PIL1_Th",                      "AI_GridL1Current_Th"),
    VAR_ELEMENT_ALIAS("1.3.PIL1_Ht",                      "AI_GridL1Current_Ht"),
    VAR_ELEMENT_ALIAS("1.3.PIL1_S",                       "AI_GridL1Current_S"),
    VAR_ELEMENT_ALIAS("1.3.PIL1_O",                       "AI_GridL1Current_O"),

    VAR_ELEMENT_ALIAS("1.3.PIL2",                         "AI_GridL2Current"),
    VAR_ELEMENT_ALIAS("1.3.PIL2_Ss",                      "AI_GridL2Current_Ss"),
    VAR_ELEMENT_ALIAS("1.3.PIL2_E",                       "AI_GridL2Current_E"),
    VAR_ELEMENT_ALIAS( "1.3.PIL2_Th",                      "AI_GridL2Current_Th"),
    VAR_ELEMENT_ALIAS("1.3.PIL2_Ht",                      "AI_GridL2Current_Ht"),
    VAR_ELEMENT_ALIAS("1.3.PIL2_S",                       "AI_GridL2Current_S"),
    VAR_ELEMENT_ALIAS("1.3.PIL2_O",                       "AI_GridL2Current_O"),

    VAR_ELEMENT_ALIAS("1.3.PIL3",                         "AI_GridL3Current"),
    VAR_ELEMENT_ALIAS("1.3.PIL3_Ss",                      "AI_GridL3Current_Ss"),
    VAR_ELEMENT_ALIAS("1.3.PIL3_E",                       "AI_GridL3Current_E"),
    VAR_ELEMENT_ALIAS( "1.3.PIL3_Th",                      "AI_GridL3Current_Th"),
    VAR_ELEMENT_ALIAS("1.3.PIL3_Ht",                      "AI_GridL3Current_Ht"),
    VAR_ELEMENT_ALIAS("1.3.PIL3_S",                       "AI_GridL3Current_S"),
    VAR_ELEMENT_ALIAS("1.3.PIL3_O",                       "AI_GridL3Current_O"),

    VAR_ELEMENT_ALIAS("1.3.PIAvg",                        "AI_GridCurrent"),
    VAR_ELEMENT_ALIAS("1.3.PIAvg_Ss",                     "AI_GridCurrent_Ss"),
    VAR_ELEMENT_ALIAS("1.3.PIAvg_E",                      "AI_GridCurrent_E"),
    VAR_ELEMENT_ALIAS( "1.3.PIAvg_Th",                     "AI_GridCurrent_Th"),
    VAR_ELEMENT_ALIAS("1.3.PIAvg_Ht",                     "AI_GridCurrent_Ht"),
    VAR_ELEMENT_ALIAS("1.3.PIAvg_S",                      "AI_GridCurrent_S"),
    VAR_ELEMENT_ALIAS("1.3.PIAvg_O",                      "AI_GridCurrent_O"),

    VAR_ELEMENT_ALIAS("1.3.PVL1",                         "AI_GridL1Voltage"),
    VAR_ELEMENT_ALIAS("1.3.PVL1_Ss",                      "AI_GridL1Voltage_Ss"),
    VAR_ELEMENT_ALIAS("1.3.PVL1_E",                       "AI_GridL1Voltage_E"),
    VAR_ELEMENT_ALIAS( "1.3.PVL1_Th",                      "AI_GridL1Voltage_Th"),
    VAR_ELEMENT_ALIAS("1.3.PVL1_Ht",                      "AI_GridL1Voltage_Ht"),
    VAR_ELEMENT_ALIAS("1.3.PVL1_S",                       "AI_GridL1Voltage_S"),
    VAR_ELEMENT_ALIAS("1.3.PVL1_O",                       "AI_GridL1Voltage_O"),

    VAR_ELEMENT_ALIAS("1.3.PVL2",                         "AI_GridL2Voltage"),
    VAR_ELEMENT_ALIAS("1.3.PVL2_Ss",                      "AI_GridL2Voltage_Ss"),
    VAR_ELEMENT_ALIAS("1.3.PVL2_E",                       "AI_GridL2Voltage_E"),
    VAR_ELEMENT_ALIAS( "1.3.PVL2_Th",                      "AI_GridL2Voltage_Th"),
    VAR_ELEMENT_ALIAS("1.3.PVL2_Ht",                      "AI_GridL2Voltage_Ht"),
    VAR_ELEMENT_ALIAS("1.3.PVL2_S",                       "AI_GridL2Voltage_S"),
    VAR_ELEMENT_ALIAS("1.3.PVL2_O",                       "AI_GridL2Voltage_O"),

    VAR_ELEMENT_ALIAS("1.3.PVL3",                         "AI_GridL3Voltage"),
    VAR_ELEMENT_ALIAS("1.3.PVL3_Ss",                      "AI_GridL3Voltage_Ss"),
    VAR_ELEMENT_ALIAS("1.3.PVL3_E",                       "AI_GridL3Voltage_E"),
    VAR_ELEMENT_ALIAS( "1.3.PVL3_Th",                      "AI_GridL3Voltage_Th"),
    VAR_ELEMENT_ALIAS("1.3.PVL3_Ht",                      "AI_GridL3Voltage_Ht"),
    VAR_ELEMENT_ALIAS("1.3.PVL3_S",                       "AI_GridL3Voltage_S"),
    VAR_ELEMENT_ALIAS("1.3.PVL3_O",                       "AI_GridL3Voltage_O"),

    VAR_ELEMENT_ALIAS("1.3.PVAvg",                        "AI_GridVoltage"),
    VAR_ELEMENT_ALIAS("1.3.PVAvg_Ss",                     "AI_GridVoltage_Ss"),
    VAR_ELEMENT_ALIAS("1.3.PVAvg_E",                      "AI_GridVoltage_E"),
    VAR_ELEMENT_ALIAS( "1.3.PVAvg_Th",                     "AI_GridVoltage_Th"),
    VAR_ELEMENT_ALIAS("1.3.PVAvg_Ht",                     "AI_GridVoltage_Ht"),
    VAR_ELEMENT_ALIAS("1.3.PVAvg_S",                      "AI_GridVoltage_S"),
    VAR_ELEMENT_ALIAS("1.3.PVAvg_O",                      "AI_GridVoltage_O"),

    VAR_ELEMENT_ALIAS("1.3.SysFreq",                      "AI_GridFrequency"),
    VAR_ELEMENT_ALIAS("1.3.SysFreq_Ss",                   "AI_GridFrequency_Ss"),
    VAR_ELEMENT_ALIAS("1.3.SysFreq_E",                    "AI_GridFrequency_E"),
    VAR_ELEMENT_ALIAS( "1.3.SysFreq_Th",                   "AI_GridFrequency_Th"),
    VAR_ELEMENT_ALIAS("1.3.SysFreq_Ht",                   "AI_GridFrequency_Ht"),
    VAR_ELEMENT_ALIAS("1.3.SysFreq_S",                    "AI_GridFrequency_S"),
    VAR_ELEMENT_ALIAS("1.3.SysFreq_O",                    "AI_GridFrequency_O"),

    VAR_ELEMENT_ALIAS("1.3.AngleVL12",                    "AI_GridL1L2PhaseShift"),
    VAR_ELEMENT_ALIAS("1.3.AngleVL12_Ss",                 "AI_GridL1L2PhaseShift_Ss"),
    VAR_ELEMENT_ALIAS("1.3.AngleVL12_E",                  "AI_GridL1L2PhaseShift_E"),
    VAR_ELEMENT_ALIAS( "1.3.AngleVL12_Th",                 "AI_GridL1L2PhaseShift_Th"),
    VAR_ELEMENT_ALIAS("1.3.AngleVL12_Ht",                 "AI_GridL1L2PhaseShift_Ht"),
    VAR_ELEMENT_ALIAS("1.3.AngleVL12_S",                  "AI_GridL1L2PhaseShift_S"),
    VAR_ELEMENT_ALIAS("1.3.AngleVL12_O",                  "AI_GridL1L2PhaseShift_O"),

    VAR_ELEMENT_ALIAS("1.3.AngleVL13",                    "AI_GridL1L3PhaseShift"),
    VAR_ELEMENT_ALIAS("1.3.AngleVL13_Ss",                 "AI_GridL1L3PhaseShift_Ss"),
    VAR_ELEMENT_ALIAS("1.3.AngleVL13_E",                  "AI_GridL1L3PhaseShift_E"),
    VAR_ELEMENT_ALIAS( "1.3.AngleVL13_Th",                 "AI_GridL1L3PhaseShift_Th"),
    VAR_ELEMENT_ALIAS("1.3.AngleVL13_Ht",                 "AI_GridL1L3PhaseShift_Ht"),
    VAR_ELEMENT_ALIAS("1.3.AngleVL13_S",                  "AI_GridL1L3PhaseShift_S"),
    VAR_ELEMENT_ALIAS("1.3.AngleVL13_O",                  "AI_GridL1L3PhaseShift_O"),

    VAR_ELEMENT_ALIAS("1.3.PVjL1Max",                     "AI_GridL1VectorSurgeSignal"),
    VAR_ELEMENT_ALIAS("1.3.PVjL1Max_Ss",                  "AI_GridL1VectorSurgeSignal_Ss"),
    VAR_ELEMENT_ALIAS("1.3.PVjL1Max_E",                   "AI_GridL1VectorSurgeSignal_E"),
    VAR_ELEMENT_ALIAS( "1.3.PVjL1Max_Th",                  "AI_GridL1VectorSurgeSignal_Th"),
    VAR_ELEMENT_ALIAS("1.3.PVjL1Max_Ht",                  "AI_GridL1VectorSurgeSignal_Ht"),
    VAR_ELEMENT_ALIAS("1.3.PVjL1Max_S",                   "AI_GridL1VectorSurgeSignal_S"),
    VAR_ELEMENT_ALIAS("1.3.PVjL1Max_O",                   "AI_GridL1VectorSurgeSignal_O"),

    VAR_ELEMENT_ALIAS("1.3.PVjL2Max",                     "AI_GridL2VectorSurgeSignal"),
    VAR_ELEMENT_ALIAS("1.3.PVjL2Max_Ss",                  "AI_GridL2VectorSurgeSignal_Ss"),
    VAR_ELEMENT_ALIAS("1.3.PVjL2Max_E",                   "AI_GridL2VectorSurgeSignal_E"),
    VAR_ELEMENT_ALIAS( "1.3.PVjL2Max_Th",                  "AI_GridL2VectorSurgeSignal_Th"),
    VAR_ELEMENT_ALIAS("1.3.PVjL2Max_Ht",                  "AI_GridL2VectorSurgeSignal_Ht"),
    VAR_ELEMENT_ALIAS("1.3.PVjL2Max_S",                   "AI_GridL2VectorSurgeSignal_S"),
    VAR_ELEMENT_ALIAS("1.3.PVjL2Max_O",                   "AI_GridL2VectorSurgeSignal_O"),

    VAR_ELEMENT_ALIAS("1.3.PVjL3Max",                     "AI_GridL3VectorSurgeSignal"),
    VAR_ELEMENT_ALIAS("1.3.PVjL3Max_Ss",                  "AI_GridL3VectorSurgeSignal_Ss"),
    VAR_ELEMENT_ALIAS("1.3.PVjL3Max_E",                   "AI_GridL3VectorSurgeSignal_E"),
    VAR_ELEMENT_ALIAS( "1.3.PVjL3Max_Th",                  "AI_GridL3VectorSurgeSignal_Th"),
    VAR_ELEMENT_ALIAS("1.3.PVjL3Max_Ht",                  "AI_GridL3VectorSurgeSignal_Ht"),
    VAR_ELEMENT_ALIAS("1.3.PVjL3Max_S",                   "AI_GridL3VectorSurgeSignal_S"),
    VAR_ELEMENT_ALIAS("1.3.PVjL3Max_O",                   "AI_GridL3VectorSurgeSignal_O"),

    VAR_ELEMENT_ALIAS("1.3.PVjAvgMax",                    "AI_GridVectorSurgeSignal"),
    VAR_ELEMENT_ALIAS("1.3.PVjAvgMax_Ss",                 "AI_GridVectorSurgeSignal_Ss"),
    VAR_ELEMENT_ALIAS("1.3.PVjAvgMax_E",                  "AI_GridVectorSurgeSignal_E"),
    VAR_ELEMENT_ALIAS( "1.3.PVjAvgMax_Th",                 "AI_GridVectorSurgeSignal_Th"),
    VAR_ELEMENT_ALIAS("1.3.PVjAvgMax_Ht",                 "AI_GridVectorSurgeSignal_Ht"),
    VAR_ELEMENT_ALIAS("1.3.PVjAvgMax_S",                  "AI_GridVectorSurgeSignal_S"),
    VAR_ELEMENT_ALIAS("1.3.PVjAvgMax_O",                  "AI_GridVectorSurgeSignal_O"),

    VAR_ELEMENT_ALIAS("1.3.PQSum",                        "AI_GridReactivePower"),
    VAR_ELEMENT_ALIAS("1.3.PQSum_Ss",                     "AI_GridReactivePower_Ss"),
    VAR_ELEMENT_ALIAS("1.3.PQSum_E",                      "AI_GridReactivePower_E"),
    VAR_ELEMENT_ALIAS( "1.3.PQSum_Th",                     "AI_GridReactivePower_Th"),
    VAR_ELEMENT_ALIAS("1.3.PQSum_Ht",                     "AI_GridReactivePower_Ht"),
    VAR_ELEMENT_ALIAS("1.3.PQSum_S",                      "AI_GridReactivePower_S"),
    VAR_ELEMENT_ALIAS("1.3.PQSum_O",                      "AI_GridReactivePower_O"),

    VAR_ELEMENT_ALIAS("1.3.PCosPhiAvg",                   "AI_GridCosPhi"),
    VAR_ELEMENT_ALIAS("1.3.PCosPhiAvg_Ss",                "AI_GridCosPhi_Ss"),
    VAR_ELEMENT_ALIAS("1.3.PCosPhiAvg_E",                 "AI_GridCosPhi_E"),
    VAR_ELEMENT_ALIAS( "1.3.PCosPhiAvg_Th",                "AI_GridCosPhi_Th"),
    VAR_ELEMENT_ALIAS("1.3.PCosPhiAvg_Ht",                "AI_GridCosPhi_Ht"),
    VAR_ELEMENT_ALIAS("1.3.PCosPhiAvg_S",                 "AI_GridCosPhi_S"),
    VAR_ELEMENT_ALIAS("1.3.PCosPhiAvg_O",                 "AI_GridCosPhi_O"),

    VAR_ELEMENT_ALIAS("1.3.PPSum",                        "AI_GridRealPower"),
    VAR_ELEMENT_ALIAS("1.3.PPSum_Ss",                     "AI_GridRealPower_Ss"),
    VAR_ELEMENT_ALIAS("1.3.PPSum_E",                      "AI_GridRealPower_E"),
    VAR_ELEMENT_ALIAS( "1.3.PPSum_Th",                     "AI_GridRealPower_Th"),
    VAR_ELEMENT_ALIAS("1.3.PPSum_Ht",                     "AI_GridRealPower_Ht"),
    VAR_ELEMENT_ALIAS("1.3.PPSum_S",                      "AI_GridRealPower_S"),
    VAR_ELEMENT_ALIAS("1.3.PPSum_O",                      "AI_GridRealPower_O"),

    VAR_ELEMENT_ALIAS("1.3.EPpSum",                       "V_PosActivePowerDelta"),
    VAR_ELEMENT_ALIAS("1.3.EPpSum_Ss",                    "V_PosActivePowerDelta_Ss"),
    VAR_ELEMENT_ALIAS("1.3.EPpSum_E",                     "V_PosActivePowerDelta_E"),
    VAR_ELEMENT_ALIAS( "1.3.EPpSum_Th",                    "V_PosActivePowerDelta_Th"),
    VAR_ELEMENT_ALIAS("1.3.EPpSum_Ht",                    "V_PosActivePowerDelta_Ht"),
    VAR_ELEMENT_ALIAS("1.3.EPpSum_S",                     "V_PosActivePowerDelta_S"),
    VAR_ELEMENT_ALIAS("1.3.EPpSum_O",                     "V_PosActivePowerDelta_O"),

    VAR_ELEMENT_ALIAS("1.3.EPnSum",                       "V_NegActivePowerDelta"),
    VAR_ELEMENT_ALIAS("1.3.EPnSum_Ss",                    "V_NegActivePowerDelta_Ss"),
    VAR_ELEMENT_ALIAS("1.3.EPnSum_E",                     "V_NegActivePowerDelta_E"),
    VAR_ELEMENT_ALIAS( "1.3.EPnSum_Th",                    "V_NegActivePowerDelta_Th"),
    VAR_ELEMENT_ALIAS("1.3.EPnSum_Ht",                    "V_NegActivePowerDelta_Ht"),
    VAR_ELEMENT_ALIAS("1.3.EPnSum_S",                     "V_NegActivePowerDelta_S"),
    VAR_ELEMENT_ALIAS("1.3.EPnSum_O",                     "V_NegActivePowerDelta_O"),

    VAR_ELEMENT_ALIAS("1.3.EQpSum",                       "V_PosReactivePowerDelta"),
    VAR_ELEMENT_ALIAS("1.3.EQpSum_Ss",                    "V_PosReactivePowerDelta_Ss"),
    VAR_ELEMENT_ALIAS("1.3.EQpSum_E",                     "V_PosReactivePowerDelta_E"),
    VAR_ELEMENT_ALIAS( "1.3.EQpSum_Th",                    "V_PosReactivePowerDelta_Th"),
    VAR_ELEMENT_ALIAS("1.3.EQpSum_Ht",                    "V_PosReactivePowerDelta_Ht"),
    VAR_ELEMENT_ALIAS("1.3.EQpSum_S",                     "V_PosReactivePowerDelta_S"),
    VAR_ELEMENT_ALIAS("1.3.EQpSum_O",                     "V_PosReactivePowerDelta_O"),

    VAR_ELEMENT_ALIAS("1.3.EQnSum",                       "V_NegReactivePowerDelta"),
    VAR_ELEMENT_ALIAS("1.3.EQnSum_Ss",                    "V_NegReactivePowerDelta_Ss"),
    VAR_ELEMENT_ALIAS("1.3.EQnSum_E",                     "V_NegReactivePowerDelta_E"),
    VAR_ELEMENT_ALIAS( "1.3.EQnSum_Th",                    "V_NegReactivePowerDelta_Th"),
    VAR_ELEMENT_ALIAS("1.3.EQnSum_Ht",                    "V_NegReactivePowerDelta_Ht"),
    VAR_ELEMENT_ALIAS("1.3.EQnSum_S",                     "V_NegReactivePowerDelta_S"),
    VAR_ELEMENT_ALIAS("1.3.EQnSum_O",                     "V_NegReactivePowerDelta_O"),

    VAR_ELEMENT_ALIAS("1.3.OUCalL1",                      "AO_GridL1VoltageGain"),

    VAR_ELEMENT_ALIAS("1.3.OUCalL2",                      "AO_GridL2VoltageGain"),

    VAR_ELEMENT_ALIAS("1.3.OUCalL3",                      "AO_GridL3VoltageGain"),

    VAR_ELEMENT_ALIAS("1.3.OICalL1",                      "AO_GridL1CurrentGain"),

    VAR_ELEMENT_ALIAS("1.3.OICalL2",                      "AO_GridL2CurrentGain"),

    VAR_ELEMENT_ALIAS("1.3.OICalL3",                      "AO_GridL3CurrentGain"),

    VAR_ELEMENT_ALIAS("1.3.PeriodsPrUpdate",              "AI_PeriodsPrUpdate"),

};
size_t GridIOVars1Size = sizeof(GridIOVars1)/sizeof(GridIOVars1[0]);

void GridSetLockValues1(void)
{
   SetLockValue("AI_GridL1Current_Ss",                   TYP_8,     1);
   SetLockValue("AI_GridL1Current_E",                    TYP_8,     1);
   SetLockValue("AI_GridL1Current_Th",                   TYP_16,    1);
   SetLockValue("AI_GridL1Current_Ht",                   TYP_32,    100);
   SetLockValue("AI_GridL1Current_S",                    TYP_32,    0);
   SetValue("AI_GridL1Current_O",                        TYP_32,    0);

   SetLockValue("AI_GridL2Current_Ss",                   TYP_8,     1);
   SetLockValue("AI_GridL2Current_E",                    TYP_8,     1);
   SetLockValue("AI_GridL2Current_Th",                   TYP_16,    1);
   SetLockValue("AI_GridL2Current_Ht",                   TYP_32,    100);
   SetLockValue("AI_GridL2Current_S",                    TYP_32,    0);
   SetValue("AI_GridL2Current_O",                        TYP_32,    0);

   SetLockValue("AI_GridL3Current_Ss",                   TYP_8,     1);
   SetLockValue("AI_GridL3Current_E",                    TYP_8,     1);
   SetLockValue("AI_GridL3Current_Th",                   TYP_16,    1);
   SetLockValue("AI_GridL3Current_Ht",                   TYP_32,    100);
   SetLockValue("AI_GridL3Current_S",                    TYP_32,    0);
   SetValue("AI_GridL3Current_O",                        TYP_32,    0);

   SetLockValue("AI_GridCurrent_Ss",                     TYP_8,     1);
   SetLockValue("AI_GridCurrent_E",                      TYP_8,     1);
   SetLockValue("AI_GridCurrent_Th",                     TYP_16,    1);
   SetLockValue("AI_GridCurrent_Ht",                     TYP_32,    100);
   SetLockValue("AI_GridCurrent_S",                      TYP_32,    0);
   SetValue("AI_GridCurrent_O",                          TYP_32,    0);

   SetLockValue("AI_GridL1Voltage_Ss",                   TYP_8,     1);
   SetLockValue("AI_GridL1Voltage_E",                    TYP_8,     1);
   SetLockValue("AI_GridL1Voltage_Th",                   TYP_32,    1);
   SetLockValue("AI_GridL1Voltage_Ht",                   TYP_32,    20);
   SetLockValue("AI_GridL1Voltage_S",                    TYP_32,    0);
   SetValue("AI_GridL1Voltage_O",                        TYP_32,    0);

   SetLockValue("AI_GridL2Voltage_Ss",                   TYP_8,     1);
   SetLockValue("AI_GridL2Voltage_E",                    TYP_8,     1);
   SetLockValue("AI_GridL2Voltage_Th",                   TYP_32,    1);
   SetLockValue("AI_GridL2Voltage_Ht",                   TYP_32,    20);
   SetLockValue("AI_GridL2Voltage_S",                    TYP_32,    0);
   SetValue("AI_GridL2Voltage_O",                        TYP_32,    0);

   SetLockValue("AI_GridL3Voltage_Ss",                   TYP_8,     1);
   SetLockValue("AI_GridL3Voltage_E",                    TYP_8,     1);
   SetLockValue("AI_GridL3Voltage_Th",                   TYP_32,    1);
   SetLockValue("AI_GridL3Voltage_Ht",                   TYP_32,    20);
   SetLockValue("AI_GridL3Voltage_S",                    TYP_32,    0);
   SetValue("AI_GridL3Voltage_O",                        TYP_32,    0);

   SetLockValue("AI_GridVoltage_Ss",                     TYP_8,     1);
   SetLockValue("AI_GridVoltage_E",                      TYP_8,     1);
   SetLockValue("AI_GridVoltage_Th",                     TYP_32,    1);
   SetLockValue("AI_GridVoltage_Ht",                     TYP_32,    20);
   SetLockValue("AI_GridVoltage_S",                      TYP_32,    0);
   SetValue("AI_GridVoltage_O",                          TYP_32,    0);

   SetLockValue("AI_GridFrequency_Ss",                   TYP_8,     1);
   SetLockValue("AI_GridFrequency_E",                    TYP_8,     1);
   SetLockValue("AI_GridFrequency_Th",                   TYP_32,    10);
   SetLockValue("AI_GridFrequency_Ht",                   TYP_32,    20);
   SetLockValue("AI_GridFrequency_S",                    TYP_32,    0);
   SetValue("AI_GridFrequency_O",                        TYP_32,    0);

   SetLockValue("AI_GridL1L2PhaseShift_Ss",              TYP_8,     1);
   SetLockValue("AI_GridL1L2PhaseShift_E",               TYP_8,     1);
   SetLockValue("AI_GridL1L2PhaseShift_Th",              TYP_32,    1000);
   SetLockValue("AI_GridL1L2PhaseShift_Ht",              TYP_32,    1000);
   SetLockValue("AI_GridL1L2PhaseShift_S",               TYP_32,    0);
   SetValue("AI_GridL1L2PhaseShift_O",                   TYP_32,    0);

   SetLockValue("AI_GridL1L3PhaseShift_Ss",              TYP_8,     1);
   SetLockValue("AI_GridL1L3PhaseShift_E",               TYP_8,     1);
   SetLockValue("AI_GridL1L3PhaseShift_Th",              TYP_32,    1000);
   SetLockValue("AI_GridL1L3PhaseShift_Ht",              TYP_32,    1000);
   SetLockValue("AI_GridL1L3PhaseShift_S",               TYP_32,    0);
   SetValue("AI_GridL1L3PhaseShift_O",                   TYP_32,    0);

   SetLockValue("AI_GridL1VectorSurgeSignal_Ss",         TYP_8,     1);
   SetLockValue("AI_GridL1VectorSurgeSignal_E",          TYP_8,     1);
   SetLockValue("AI_GridL1VectorSurgeSignal_Th",         TYP_32,    5);
   SetLockValue("AI_GridL1VectorSurgeSignal_Ht",         TYP_32,    20);
   SetLockValue("AI_GridL1VectorSurgeSignal_S",          TYP_32,    0);
   SetValue("AI_GridL1VectorSurgeSignal_O",              TYP_32,    0);

   SetLockValue("AI_GridL2VectorSurgeSignal_Ss",         TYP_8,     1);
   SetLockValue("AI_GridL2VectorSurgeSignal_E",          TYP_8,     1);
   SetLockValue("AI_GridL2VectorSurgeSignal_Th",         TYP_32,    5);
   SetLockValue("AI_GridL2VectorSurgeSignal_Ht",         TYP_32,    20);
   SetLockValue("AI_GridL2VectorSurgeSignal_S",          TYP_32,    0);
   SetValue("AI_GridL2VectorSurgeSignal_O",              TYP_32,    0);

   SetLockValue("AI_GridL3VectorSurgeSignal_Ss",         TYP_8,     1);
   SetLockValue("AI_GridL3VectorSurgeSignal_E",          TYP_8,     1);
   SetLockValue("AI_GridL3VectorSurgeSignal_Th",         TYP_32,    5);
   SetLockValue("AI_GridL3VectorSurgeSignal_Ht",         TYP_32,    20);
   SetLockValue("AI_GridL3VectorSurgeSignal_S",          TYP_32,    0);
   SetValue("AI_GridL3VectorSurgeSignal_O",              TYP_32,    0);

   SetLockValue("AI_GridVectorSurgeSignal_Ss",           TYP_8,     1);
   SetLockValue("AI_GridVectorSurgeSignal_E",            TYP_8,     1);
   SetLockValue("AI_GridVectorSurgeSignal_Th",           TYP_32,    5);
   SetLockValue("AI_GridVectorSurgeSignal_Ht",           TYP_32,    20);
   SetLockValue("AI_GridVectorSurgeSignal_S",            TYP_32,    0);
   SetValue("AI_GridVectorSurgeSignal_O",                TYP_32,    0);

   SetLockValue("AI_GridReactivePower_Ss",               TYP_8,     1);
   SetLockValue("AI_GridReactivePower_E",                TYP_8,     1);
   SetLockValue("AI_GridReactivePower_Th",               TYP_32,    1000);
   SetLockValue("AI_GridReactivePower_Ht",               TYP_32,    100);
   SetLockValue("AI_GridReactivePower_S",                TYP_32,    0);
   SetValue("AI_GridReactivePower_O",                    TYP_32,    0);

   SetLockValue("AI_GridCosPhi_Ss",                      TYP_8,     1);
   SetLockValue("AI_GridCosPhi_E",                       TYP_8,     1);
   SetLockValue("AI_GridCosPhi_Th",                      TYP_16,    20);
   SetLockValue("AI_GridCosPhi_Ht",                      TYP_32,    100);
   SetLockValue("AI_GridCosPhi_S",                       TYP_32,    0);
   SetValue("AI_GridCosPhi_O",                           TYP_32,    0);

   SetLockValue("AI_GridRealPower_Ss",                   TYP_8,     1);
   SetLockValue("AI_GridRealPower_E",                    TYP_8,     1);
   SetLockValue("AI_GridRealPower_Th",                   TYP_32,    1000);
   SetLockValue("AI_GridRealPower_Ht",                   TYP_32,    20);
   SetLockValue("AI_GridRealPower_S",                    TYP_32,    0);
   SetValue("AI_GridRealPower_O",                        TYP_32,    0);

   SetLockValue("V_PosActivePowerDelta_Ss",              TYP_8,     1);
   SetLockValue("V_PosActivePowerDelta_E",               TYP_8,     1);
   SetLockValue("V_PosActivePowerDelta_Th",              TYP_32,    1);
   SetLockValue("V_PosActivePowerDelta_Ht",              TYP_32,    20);
   SetLockValue("V_PosActivePowerDelta_S",               TYP_32,    0);
   SetValue("V_PosActivePowerDelta_O",                   TYP_32,    0);

   SetLockValue("V_NegActivePowerDelta_Ss",              TYP_8,     1);
   SetLockValue("V_NegActivePowerDelta_E",               TYP_8,     1);
   SetLockValue("V_NegActivePowerDelta_Th",              TYP_32,    1);
   SetLockValue("V_NegActivePowerDelta_Ht",              TYP_32,    20);
   SetLockValue("V_NegActivePowerDelta_S",               TYP_32,    0);
   SetValue("V_NegActivePowerDelta_O",                   TYP_32,    0);

   SetLockValue("V_PosReactivePowerDelta_Ss",            TYP_8,     1);
   SetLockValue("V_PosReactivePowerDelta_E",             TYP_8,     1);
   SetLockValue("V_PosReactivePowerDelta_Th",            TYP_32,    1);
   SetLockValue("V_PosReactivePowerDelta_Ht",            TYP_32,    20);
   SetLockValue("V_PosReactivePowerDelta_S",             TYP_32,    0);
   SetValue("V_PosReactivePowerDelta_O",                 TYP_32,    0);

   SetLockValue("V_NegReactivePowerDelta_Ss",            TYP_8,     1);
   SetLockValue("V_NegReactivePowerDelta_E",             TYP_8,     1);
   SetLockValue("V_NegReactivePowerDelta_Th",            TYP_32,    1);
   SetLockValue("V_NegReactivePowerDelta_Ht",            TYP_32,    20);
   SetLockValue("V_NegReactivePowerDelta_S",             TYP_32,    0);
   SetValue("V_NegReactivePowerDelta_O",                 TYP_32,    0);

   SetValue("AO_GridL1VoltageGain",                      TYP_32,    0);

   SetValue("AO_GridL2VoltageGain",                      TYP_32,    0);

   SetValue("AO_GridL3VoltageGain",                      TYP_32,    0);

   SetValue("AO_GridL1CurrentGain",                      TYP_32,    0);

   SetValue("AO_GridL2CurrentGain",                      TYP_32,    0);

   SetValue("AO_GridL3CurrentGain",                      TYP_32,    0);

   SetValue("AI_PeriodsPrUpdate",                        TYP_8,     0);
}


STATUS GridInitIOAliases()
{
   GridIOVars = GridIOVars1;
   GridIOVarsSize = GridIOVars1Size;
   GridSetLockValues = &GridSetLockValues1;
   return OS_SUCCESS;
}
//-----------------------------------------------------------------------
// AUTOGENERATED END        AUTOGENERATED END        AUTOGENERATED END
//-----------------------------------------------------------------------

#undef AUTOGENERATED_PART
