//*****************************PEPTOOL Header Start******************************
//                                                                               
//                         Copyright © 2015 Mita-Teknik.                         
//This software may only be used with WP4x00 Controllers delivered by Mita-Teknik
//                                                                               
//*******************************************************************************
//                                                                               
// $PEPTOOL version:9.0$                                                         
// $PEPTOOL file version:101$                                                    
//                                                                               
//*******************************************************************************
//                                                                               
// $Date: 2014/04/25 13:45:47 $                                                  
// $Author: MITA\ihn $                                                           
// $RCSfile: Hub_MT_Type1_Conf.c,v $                                             
// $Revision: 1.8 $                                                              
//                                                                               
//******************************PEPTOOL Header End*******************************

//***********************************************************************
// OS header files
#include <os_main.h>
// App header files
#include <InitIo.h>

#define AUTOGENERATED_PART

#include <Turbdef.h>

//-----------------------------------------------------------------------
// AUTOGENERATED START     AUTOGENERATED START     AUTOGENERATED START
//-----------------------------------------------------------------------
char Hub_MT_Type1_Conf_copyright[] =
{
   67, 111, 112, 121, 114, 105, 103, 104, 116, 32, 63, 32, 50, 48, 49, 53,
   32, 77, 105, 116, 97, 45, 84, 101, 107, 110, 105, 107, 46, 13, 10, 84,
   104, 105, 115, 32, 115, 111, 102, 116, 119, 97, 114, 101, 32, 109, 97, 121,
   32, 111, 110, 108, 121, 32, 98, 101, 32, 117, 115, 101, 100, 32, 119, 105,
   116, 104, 32, 87, 80, 52, 120, 48, 48, 32, 67, 111, 110, 116, 114, 111,
   108, 108, 101, 114, 115, 32, 100, 101, 108, 105, 118, 101, 114, 101, 100, 32,
   98, 121, 32, 77, 105, 116, 97, 45, 84, 101, 107, 110, 105, 107, 0
};
//-----------------------------------------------------------------------
// MODIFIABLE                  MODIFIABLE               MODIFIABLE
//-----------------------------------------------------------------------
const char Hub_MT_Type1AppGroupName[] = "G_"APP_ID"App";
const char Hub_MT_Type1AppMenuName[] = "M_"APP_ID"AppMain";

//-----------------------------------------------------------------------
// IO VARIABLES                IO VARIABLES                IO VARIABLES
//-----------------------------------------------------------------------

void (*Hub_MT_Type1SetLockValues)(void);
struct os_db_alias *Hub_MT_Type1IOVars;
size_t Hub_MT_Type1IOVarsSize = 0;
            
struct os_db_alias Hub_MT_Type1IOVars1[]=
{
    VAR_ELEMENT_ALIAS("5.2.66",                           "PT_HubTemp"),
    VAR_ELEMENT_ALIAS("5.2.66_Ss",                        "PT_HubTemp_Ss"),
    VAR_ELEMENT_ALIAS("5.2.66_E",                         "PT_HubTemp_E"),
    VAR_ELEMENT_ALIAS( "5.2.66_Th",                        "PT_HubTemp_Th"),
    VAR_ELEMENT_ALIAS("5.2.66_Ht",                        "PT_HubTemp_Ht"),
    VAR_ELEMENT_ALIAS("5.2.66_S",                         "PT_HubTemp_S"),
    VAR_ELEMENT_ALIAS("5.2.66_O",                         "PT_HubTemp_O"),

    VAR_ELEMENT_ALIAS("5.2.28",                           "DI_Hub400V_ON"),
    VAR_ELEMENT_ALIAS("5.2.28_Ss",                        "DI_Hub400V_ON_Ss"),
    VAR_ELEMENT_ALIAS("5.2.28_E",                         "DI_Hub400V_ON_E"),
    VAR_ELEMENT_ALIAS("5.2.28_I",                         "DI_Hub400V_ON_I"),
    VAR_ELEMENT_ALIAS("5.2.28_Cm",                        "DI_Hub400V_ON_Cm"),
    VAR_ELEMENT_ALIAS("5.2.28_Ht",                        "DI_Hub400V_ON_Ht"),

    VAR_ELEMENT_ALIAS("5.2.29",                           "DI_HubLightON"),
    VAR_ELEMENT_ALIAS("5.2.29_Ss",                        "DI_HubLightON_Ss"),
    VAR_ELEMENT_ALIAS("5.2.29_E",                         "DI_HubLightON_E"),
    VAR_ELEMENT_ALIAS("5.2.29_I",                         "DI_HubLightON_I"),
    VAR_ELEMENT_ALIAS("5.2.29_Cm",                        "DI_HubLightON_Cm"),
    VAR_ELEMENT_ALIAS("5.2.29_Ht",                        "DI_HubLightON_Ht"),

    VAR_ELEMENT_ALIAS("5.2.37",                           "DI_HubSmokeDetect"),
    VAR_ELEMENT_ALIAS("5.2.37_Ss",                        "DI_HubSmokeDetect_Ss"),
    VAR_ELEMENT_ALIAS("5.2.37_E",                         "DI_HubSmokeDetect_E"),
    VAR_ELEMENT_ALIAS("5.2.37_I",                         "DI_HubSmokeDetect_I"),
    VAR_ELEMENT_ALIAS("5.2.37_Cm",                        "DI_HubSmokeDetect_Cm"),
    VAR_ELEMENT_ALIAS("5.2.37_Ht",                        "DI_HubSmokeDetect_Ht"),

    VAR_ELEMENT_ALIAS("5.2.8",                            "DO_HubSmokeDetectorSupply"),

    VAR_ELEMENT_ALIAS("5.2.38",                           "DI_Hub_BoltMonitoringSystemOk1"),
    VAR_ELEMENT_ALIAS("5.2.38_Ss",                        "DI_Hub_BoltMonitoringSystemOk1_Ss"),
    VAR_ELEMENT_ALIAS("5.2.38_E",                         "DI_Hub_BoltMonitoringSystemOk1_E"),
    VAR_ELEMENT_ALIAS("5.2.38_I",                         "DI_Hub_BoltMonitoringSystemOk1_I"),
    VAR_ELEMENT_ALIAS("5.2.38_Cm",                        "DI_Hub_BoltMonitoringSystemOk1_Cm"),
    VAR_ELEMENT_ALIAS("5.2.38_Ht",                        "DI_Hub_BoltMonitoringSystemOk1_Ht"),

    VAR_ELEMENT_ALIAS("5.2.39",                           "DI_Hub_BoltMonitoringBoltOk1"),
    VAR_ELEMENT_ALIAS("5.2.39_Ss",                        "DI_Hub_BoltMonitoringBoltOk1_Ss"),
    VAR_ELEMENT_ALIAS("5.2.39_E",                         "DI_Hub_BoltMonitoringBoltOk1_E"),
    VAR_ELEMENT_ALIAS("5.2.39_I",                         "DI_Hub_BoltMonitoringBoltOk1_I"),
    VAR_ELEMENT_ALIAS("5.2.39_Cm",                        "DI_Hub_BoltMonitoringBoltOk1_Cm"),
    VAR_ELEMENT_ALIAS("5.2.39_Ht",                        "DI_Hub_BoltMonitoringBoltOk1_Ht"),

    VAR_ELEMENT_ALIAS("5.2.40",                           "DI_Hub_BoltMonitoringSystemOk2"),
    VAR_ELEMENT_ALIAS("5.2.40_Ss",                        "DI_Hub_BoltMonitoringSystemOk2_Ss"),
    VAR_ELEMENT_ALIAS("5.2.40_E",                         "DI_Hub_BoltMonitoringSystemOk2_E"),
    VAR_ELEMENT_ALIAS("5.2.40_I",                         "DI_Hub_BoltMonitoringSystemOk2_I"),
    VAR_ELEMENT_ALIAS("5.2.40_Cm",                        "DI_Hub_BoltMonitoringSystemOk2_Cm"),
    VAR_ELEMENT_ALIAS("5.2.40_Ht",                        "DI_Hub_BoltMonitoringSystemOk2_Ht"),

    VAR_ELEMENT_ALIAS("5.2.41",                           "DI_Hub_BoltMonitoringBoltOk2"),
    VAR_ELEMENT_ALIAS("5.2.41_Ss",                        "DI_Hub_BoltMonitoringBoltOk2_Ss"),
    VAR_ELEMENT_ALIAS("5.2.41_E",                         "DI_Hub_BoltMonitoringBoltOk2_E"),
    VAR_ELEMENT_ALIAS("5.2.41_I",                         "DI_Hub_BoltMonitoringBoltOk2_I"),
    VAR_ELEMENT_ALIAS("5.2.41_Cm",                        "DI_Hub_BoltMonitoringBoltOk2_Cm"),
    VAR_ELEMENT_ALIAS("5.2.41_Ht",                        "DI_Hub_BoltMonitoringBoltOk2_Ht"),

    VAR_ELEMENT_ALIAS("5.2.14",                           "DO_Hub_LightON"),

};
size_t Hub_MT_Type1IOVars1Size = sizeof(Hub_MT_Type1IOVars1)/sizeof(Hub_MT_Type1IOVars1[0]);

void Hub_MT_Type1SetLockValues1(void)
{
   SetLockValue("PT_HubTemp_Ss",                         TYP_8,     1);
   SetLockValue("PT_HubTemp_E",                          TYP_8,     1);
   SetLockValue("PT_HubTemp_Th",                         TYP_16,    10);
   SetLockValue("PT_HubTemp_Ht",                         TYP_32,    2000);
   SetLockValue("PT_HubTemp_S",                          TYP_32,    0);
   SetValue("PT_HubTemp_O",                              TYP_32,    0);

   SetLockValue("DI_Hub400V_ON_Ss",                      TYP_8,     1);
   SetLockValue("DI_Hub400V_ON_E",                       TYP_8,     1);
   SetValue("DI_Hub400V_ON_I",                           TYP_8,     0);
   SetLockValue("DI_Hub400V_ON_Cm",                      TYP_8,     1);
   SetLockValue("DI_Hub400V_ON_Ht",                      TYP_32,    1000);

   SetLockValue("DI_HubLightON_Ss",                      TYP_8,     1);
   SetLockValue("DI_HubLightON_E",                       TYP_8,     1);
   SetValue("DI_HubLightON_I",                           TYP_8,     0);
   SetLockValue("DI_HubLightON_Cm",                      TYP_8,     1);
   SetLockValue("DI_HubLightON_Ht",                      TYP_32,    1000);

   SetLockValue("DI_HubSmokeDetect_Ss",                  TYP_8,     1);
   SetLockValue("DI_HubSmokeDetect_E",                   TYP_8,     1);
   SetValue("DI_HubSmokeDetect_I",                       TYP_8,     0);
   SetLockValue("DI_HubSmokeDetect_Cm",                  TYP_8,     1);
   SetLockValue("DI_HubSmokeDetect_Ht",                  TYP_32,    1000);

   SetLockValue("DI_Hub_BoltMonitoringSystemOk1_Ss",     TYP_8,     1);
   SetLockValue("DI_Hub_BoltMonitoringSystemOk1_E",      TYP_8,     1);
   SetValue("DI_Hub_BoltMonitoringSystemOk1_I",          TYP_8,     0);
   SetLockValue("DI_Hub_BoltMonitoringSystemOk1_Cm",     TYP_8,     1);
   SetLockValue("DI_Hub_BoltMonitoringSystemOk1_Ht",     TYP_32,    100);

   SetLockValue("DI_Hub_BoltMonitoringBoltOk1_Ss",       TYP_8,     1);
   SetLockValue("DI_Hub_BoltMonitoringBoltOk1_E",        TYP_8,     1);
   SetValue("DI_Hub_BoltMonitoringBoltOk1_I",            TYP_8,     0);
   SetLockValue("DI_Hub_BoltMonitoringBoltOk1_Cm",       TYP_8,     1);
   SetLockValue("DI_Hub_BoltMonitoringBoltOk1_Ht",       TYP_32,    100);

   SetLockValue("DI_Hub_BoltMonitoringSystemOk2_Ss",     TYP_8,     1);
   SetLockValue("DI_Hub_BoltMonitoringSystemOk2_E",      TYP_8,     1);
   SetValue("DI_Hub_BoltMonitoringSystemOk2_I",          TYP_8,     0);
   SetLockValue("DI_Hub_BoltMonitoringSystemOk2_Cm",     TYP_8,     1);
   SetLockValue("DI_Hub_BoltMonitoringSystemOk2_Ht",     TYP_32,    100);

   SetLockValue("DI_Hub_BoltMonitoringBoltOk2_Ss",       TYP_8,     1);
   SetLockValue("DI_Hub_BoltMonitoringBoltOk2_E",        TYP_8,     1);
   SetValue("DI_Hub_BoltMonitoringBoltOk2_I",            TYP_8,     0);
   SetLockValue("DI_Hub_BoltMonitoringBoltOk2_Cm",       TYP_8,     1);
   SetLockValue("DI_Hub_BoltMonitoringBoltOk2_Ht",       TYP_32,    100);
}


STATUS Hub_MT_Type1InitIOAliases()
{
   Hub_MT_Type1IOVars = Hub_MT_Type1IOVars1;
   Hub_MT_Type1IOVarsSize = Hub_MT_Type1IOVars1Size;
   Hub_MT_Type1SetLockValues = &Hub_MT_Type1SetLockValues1;
   return OS_SUCCESS;
}
//-----------------------------------------------------------------------
// AUTOGENERATED END        AUTOGENERATED END        AUTOGENERATED END
//-----------------------------------------------------------------------

#undef AUTOGENERATED_PART
