//*****************************PEPTOOL Header Start******************************
//                                                                               
//                         Copyright © 2015 Mita-Teknik.                         
//This software may only be used with WP4x00 Controllers delivered by Mita-Teknik
//                                                                               
//*******************************************************************************
//                                                                               
// $PEPTOOL version:9.0$                                                         
// $PEPTOOL file version:106$                                                    
//                                                                               
//*******************************************************************************
//                                                                               
// $Date: 2014/05/23 09:10:06 $                                                  
// $Author: MITA\ihn $                                                           
// $RCSfile: Hub_MT_Type1.c,v $                                                  
// $Revision: 1.18 $                                                             
//                                                                               
//******************************PEPTOOL Header End*******************************

//***********************************************************************

// OS header files
#include <os_main.h>
// AppLib header files
#include <lib_main.h>
// App header files
#include <turbdef.h>
#include <VarMacros.h>

// Object header file
#include <Hub_MT_Type1.h>

#define AUTOGENERATED_PART
//{
//-----------------------------------------------------------------------
// AUTOGENERATED START     AUTOGENERATED START     AUTOGENERATED START
//-----------------------------------------------------------------------

#define VALIDATE_HASH
char Hub_MT_Type1_copyright[] =
{
   67, 111, 112, 121, 114, 105, 103, 104, 116, 32, 63, 32, 50, 48, 49, 53,
   32, 77, 105, 116, 97, 45, 84, 101, 107, 110, 105, 107, 46, 13, 10, 84,
   104, 105, 115, 32, 115, 111, 102, 116, 119, 97, 114, 101, 32, 109, 97, 121,
   32, 111, 110, 108, 121, 32, 98, 101, 32, 117, 115, 101, 100, 32, 119, 105,
   116, 104, 32, 87, 80, 52, 120, 48, 48, 32, 67, 111, 110, 116, 114, 111,
   108, 108, 101, 114, 115, 32, 100, 101, 108, 105, 118, 101, 114, 101, 100, 32,
   98, 121, 32, 77, 105, 116, 97, 45, 84, 101, 107, 110, 105, 107, 0
};

#define MODULE_NAME "HubA"

//-----------------------------------------------------------------------
// ALLOCATE MEMORY FOR STRINGS IN VARDB
//-----------------------------------------------------------------------

static char A_V_HubTempSensorStateTxt[31]  = "not defined";

//-----------------------------------------------------------------------
// DEFINE LOCAL VARIABLES DEFINE LOCAL VARIABLES DEFINE LOCAL VARIABLES
//-----------------------------------------------------------------------

static struct os_db_local LocalVars[] =
{
   VAR_ELEMENT_LOCAL("V_HubTemperatureLog",                      TYPE_S16,     PASSWORD_LEVEL_UNLOGGED_IN,        PASSWORD_LEVEL_UNLOGGED_IN,        SCALE_DIV,    10,      UNIT_CELSIUS,       1,   0,               0,               0,               NULL,  TOTLOG_ENABLE | FIVEMINLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_HubTempSensorStateTxt",                  TYPE_STRING + sizeof(A_V_HubTempSensorStateTxt) - 1,  PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   A_V_HubTempSensorStateTxt, 0,                0,                NULL,  NOLOG_ENABLE  ),
   VAR_ELEMENT_LOCAL("V_HubTempSensorState",                     TYPE_S32,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   0,               S32_MIN,         S32_MAX,         NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_HubLightOn",                             TYPE_U8,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   0,               0,               1,               NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_HubSmokeDetectorReset",                  TYPE_U8,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_END_CUSTOMER,       SCALE_NONE,   0,       UNIT_NONE,          0,   0,               0,               1,               NULL,  NOLOG_ENABLE),
};

//-----------------------------------------------------------------------
// DEFINE PARAMETERS        DEFINE PARAMETERS        DEFINE PARAMETERS
//-----------------------------------------------------------------------

static struct os_db_parameter ParameterVars[] =
{
   VAR_ELEMENT_PARAMETER("P_HubTempEnable",                          TYPE_U8,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_NONE,   0,       UNIT_NONE,          0,   1,               0,               1,               NULL  ),
   VAR_ELEMENT_PARAMETER("P_HubHighTempWarnOn",                      TYPE_S16,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_DIV,    10,      UNIT_CELSIUS,       0,   450,             -300,            2000,            NULL  ),
   VAR_ELEMENT_PARAMETER("P_HubHighTempWarnOff",                     TYPE_S16,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_DIV,    10,      UNIT_CELSIUS,       0,   400,             -300,            2000,            NULL  ),
   VAR_ELEMENT_PARAMETER("P_HubHighTempStopOn",                      TYPE_S16,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_DIV,    10,      UNIT_CELSIUS,       0,   550,             -300,            2000,            NULL  ),
   VAR_ELEMENT_PARAMETER("P_HubHighTempStopOff",                     TYPE_S16,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_DIV,    10,      UNIT_CELSIUS,       0,   500,             -300,            2000,            NULL  ),
   VAR_ELEMENT_PARAMETER("P_HubLowTempWarnOn",                       TYPE_S16,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_DIV,    10,      UNIT_CELSIUS,       0,   0,               -300,            2000,            NULL  ),
   VAR_ELEMENT_PARAMETER("P_HubLowTempWarnOff",                      TYPE_S16,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_DIV,    10,      UNIT_CELSIUS,       0,   50,              -300,            2000,            NULL  ),
   VAR_ELEMENT_PARAMETER("P_HubTempErrHigh",                         TYPE_S16,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_DIV,    10,      UNIT_CELSIUS,       0,   2100,            0,               2200,            NULL  ),
   VAR_ELEMENT_PARAMETER("P_HubTempErrLow",                          TYPE_S16,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_DIV,    10,      UNIT_CELSIUS,       0,   -400,            -500,            0,               NULL  ),
   VAR_ELEMENT_PARAMETER("P_Hub_BoltMonitoringEnable1",              TYPE_U8,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_NONE,   0,       UNIT_NONE,          0,   1,               0,               1,               NULL  ),
   VAR_ELEMENT_PARAMETER("P_Hub_BoltMonitoringEnable2",              TYPE_U8,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_NONE,   0,       UNIT_NONE,          0,   1,               0,               1,               NULL  ),
   VAR_ELEMENT_PARAMETER("P_Hub_LightMode",                          TYPE_U8,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   0,               0,               2,               NULL  ),
};

//-----------------------------------------------------------------------
// DEFINE BACKUPS            DEFINE BACKUPS            DEFINE BACKUPS
//-----------------------------------------------------------------------

//----------------------------------------------------------------------------------
// DEFINE VAR ARRAYS            DEFINE VAR ARRAYS            DEFINE VAR ARRAYS
//----------------------------------------------------------------------------------
char Hub_MT_Type1_initialValues[] =
{
   115, 91, 154, 165, 20, 68, 140, 155, 124, 188, 72, 222, 63, 115, 27, 19,
   10, 194, 36, 28, 142, 213, 117, 75, 197, 217, 170, 253, 220, 217, 247, 249,
   0
};

//-----------------------------------------------------------------------
// CREATE DATABASE VARS   CREATE DATABASE VARS   CREATE DATABASE VARS
//-----------------------------------------------------------------------

static STATUS CreateVarDbVars(void)
{
   STATUS Status;
   size_t ErrorEntry;

   Status = OS_VarDB_CreateLocals(LocalVars, sizeof(LocalVars)/sizeof(LocalVars[0]), &ErrorEntry, AppLocalParameterPosition());
   if (Status != 0)
   {
      AppSystemLog(ERR_7, MODULE_NAME"CrVL: %d,%d", Status, ErrorEntry);
      return ERR_7;
   }

   Status = OS_VarDB_CreateParameters(ParameterVars, sizeof(ParameterVars)/sizeof(ParameterVars[0]), &ErrorEntry, AppExportParameterPosition());
   if (Status != 0)
   {
      AppSystemLog(ERR_7, MODULE_NAME"CrVXP: %d,%d", Status, ErrorEntry);
      return ERR_7;
   }

   return OS_SUCCESS;
}

#define CREATE_VARDB_VARS

//-----------------------------------------------------------------------
// CREATE IO VARIABLES     CREATE IO VARIABLES     CREATE IO VARIABLES
//-----------------------------------------------------------------------

extern STATUS Hub_MT_Type1InitIOAliases();
extern struct os_db_alias* Hub_MT_Type1IOVars;
extern void (*Hub_MT_Type1SetLockValues)(void);
extern size_t Hub_MT_Type1IOVarsSize;

static STATUS CreateIOVars(void)
{
   STATUS Status;
   size_t ErrorEntry;

   varid_t VarId;
   BOOL variablesExist = false;
   U8 counter = 50;
   Status = Hub_MT_Type1InitIOAliases();
   STATUS_LINE_VAR_RETURN_VALUE(Status)
   while (!variablesExist && counter-- > 0)
   {
      variablesExist = true;
      U32 i = 0;
      for (i = 0; i < Hub_MT_Type1IOVarsSize; ++i)
      {
         if (OS_VarDB_GetVariableID(Hub_MT_Type1IOVars[i].Name, &VarId) != OS_SUCCESS)
         {
            variablesExist = false;
            break;
         }
      }

      if (!variablesExist)
      {
         OS_Sleep(100);
      }
   }

   Status = OS_VarDB_CreateAliases(Hub_MT_Type1IOVars, Hub_MT_Type1IOVarsSize, &ErrorEntry);
   if (Status)
   {
      AppDebugLog(5000, "Var Name = %s", Hub_MT_Type1IOVars[ErrorEntry].Alias);
   }
   STATUS_LINE_VAR_RETURN_CONST(Status, ErrorEntry);
   return OS_SUCCESS;
}

#define CREATE_IO_VARS

//-----------------------------------------------------------------------
// ALIASES                       ALIASES                       ALIASES
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// INPUT                          INPUT                          INPUT
//-----------------------------------------------------------------------

// Create local variable
#define MODUL_INPUTS
static S16 PT_HubTemp = 0;
static U8 DI_Hub400V_ON = 0;
static U8 DI_HubLightON = 0;
static U8 DI_HubSmokeDetect = 0;
static U8 V_HubSmokeDetectorReset = 0;
static U8 DI_Hub_BoltMonitoringSystemOk1 = 0;
static U8 DI_Hub_BoltMonitoringSystemOk2 = 0;
static U8 DI_Hub_BoltMonitoringBoltOk1 = 0;
static U8 DI_Hub_BoltMonitoringBoltOk2 = 0;
static U8 P_Hub_BoltMonitoringEnable1 = 0;
static U8 P_Hub_BoltMonitoringEnable2 = 0;

//-----------------------------------------------------------------------
static struct ModulInOut ModulInputs[] =
{
   {"PT_HubTemp",                               &PT_HubTemp,                               sizeof(PT_HubTemp),                               },
   {"DI_Hub400V_ON",                            &DI_Hub400V_ON,                            sizeof(DI_Hub400V_ON),                            },
   {"DI_HubLightON",                            &DI_HubLightON,                            sizeof(DI_HubLightON),                            },
   {"DI_HubSmokeDetect",                        &DI_HubSmokeDetect,                        sizeof(DI_HubSmokeDetect),                        },
   {"V_HubSmokeDetectorReset",                  &V_HubSmokeDetectorReset,                  sizeof(V_HubSmokeDetectorReset),                  },
   {"DI_Hub_BoltMonitoringSystemOk1",           &DI_Hub_BoltMonitoringSystemOk1,           sizeof(DI_Hub_BoltMonitoringSystemOk1),           },
   {"DI_Hub_BoltMonitoringSystemOk2",           &DI_Hub_BoltMonitoringSystemOk2,           sizeof(DI_Hub_BoltMonitoringSystemOk2),           },
   {"DI_Hub_BoltMonitoringBoltOk1",             &DI_Hub_BoltMonitoringBoltOk1,             sizeof(DI_Hub_BoltMonitoringBoltOk1),             },
   {"DI_Hub_BoltMonitoringBoltOk2",             &DI_Hub_BoltMonitoringBoltOk2,             sizeof(DI_Hub_BoltMonitoringBoltOk2),             },
   {"P_Hub_BoltMonitoringEnable1",              &P_Hub_BoltMonitoringEnable1,              sizeof(P_Hub_BoltMonitoringEnable1),              },
   {"P_Hub_BoltMonitoringEnable2",              &P_Hub_BoltMonitoringEnable2,              sizeof(P_Hub_BoltMonitoringEnable2),              },
};

//-----------------------------------------------------------------------
// Check variable type
static STATUS VarsReadReturnStatus;
static type_t ReadVarType = TYPE_NONE;
static void VarsReadTypeCheck(void)
{
   (void)VarsReadReturnStatus;
   (void)ReadVarType;
   VERIFY_INPUT_REF_ID(S16,       ModulInputs[0].Name,                      ModulInputs[0].Id)
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[1].Name,                      ModulInputs[1].Id)
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[2].Name,                      ModulInputs[2].Id)
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[3].Name,                      ModulInputs[3].Id)
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[4].Name,                      ModulInputs[4].Id)
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[5].Name,                      ModulInputs[5].Id)
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[6].Name,                      ModulInputs[6].Id)
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[7].Name,                      ModulInputs[7].Id)
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[8].Name,                      ModulInputs[8].Id)
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[9].Name,                      ModulInputs[9].Id)
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[10].Name,                     ModulInputs[10].Id)
}

#undef MODUL_INPUTS
#define MODUL_INPUTS_SIZE (sizeof(ModulInputs)/sizeof(ModulInputs[0]))

//------------------------------------------------------------------------------------------
// READ/WRITE VARDB ARRAY      READ/WRITE VARDB ARRAY      READ/WRATE VARDB ARRAY
//------------------------------------------------------------------------------------------


//-----------------------------------------------------------------------
// PARAMETER                    PARAMETER                    PARAMETER
//-----------------------------------------------------------------------

// Create local variable
#define MODUL_PARAMETERS
static U8 P_HubTempEnable = 0;
static S16 P_HubHighTempWarnOn = 0;
static S16 P_HubHighTempWarnOff = 0;
static S16 P_HubHighTempStopOn = 0;
static S16 P_HubHighTempStopOff = 0;
static S16 P_HubLowTempWarnOn = 0;
static S16 P_HubLowTempWarnOff = 0;
static S16 P_HubTempErrHigh = 0;
static S16 P_HubTempErrLow = 0;
static U8 P_Hub_LightMode = 0;
static U8 DI_Panels_TowerBasePanelLight = 0;



//-----------------------------------------------------------------------
static struct ModulInOut ModulParameters0[] =
{
   {"P_HubTempEnable",                          &P_HubTempEnable,                          sizeof(P_HubTempEnable),                          },
   {"P_HubHighTempWarnOn",                      &P_HubHighTempWarnOn,                      sizeof(P_HubHighTempWarnOn),                      },
   {"P_HubHighTempWarnOff",                     &P_HubHighTempWarnOff,                     sizeof(P_HubHighTempWarnOff),                     },
   {"P_HubHighTempStopOn",                      &P_HubHighTempStopOn,                      sizeof(P_HubHighTempStopOn),                      },
   {"P_HubHighTempStopOff",                     &P_HubHighTempStopOff,                     sizeof(P_HubHighTempStopOff),                     },
   {"P_HubLowTempWarnOn",                       &P_HubLowTempWarnOn,                       sizeof(P_HubLowTempWarnOn),                       },
   {"P_HubLowTempWarnOff",                      &P_HubLowTempWarnOff,                      sizeof(P_HubLowTempWarnOff),                      },
   {"P_HubTempErrHigh",                         &P_HubTempErrHigh,                         sizeof(P_HubTempErrHigh),                         },
   {"P_HubTempErrLow",                          &P_HubTempErrLow,                          sizeof(P_HubTempErrLow),                          },
   {"P_Hub_LightMode",                          &P_Hub_LightMode,                          sizeof(P_Hub_LightMode),                          },
   {"DI_Panels_TowerBasePanelLight",            &DI_Panels_TowerBasePanelLight,            sizeof(DI_Panels_TowerBasePanelLight),            },

};
static struct ModulInOut* ModulParameters[] =
{
   ModulParameters0,
};

//-----------------------------------------------------------------------
// Check variable type
static STATUS ParaVarsReadReturnStatus;
static type_t ParaReadVarType = TYPE_NONE;
static void ParaVarsReadTypeCheck(void)
{
   (void)ParaVarsReadReturnStatus;
   (void)ParaReadVarType;
}

#undef MODUL_PARAMETERS

#define PARAMETERS_GROUPS_SIZE        1
#define GENERAL_GROUP                 0
#define MODUL_PARAMETERS_TOTAL_SIZE   11
static SUBSCRIPTION ParaSubscription[MODUL_PARAMETERS_TOTAL_SIZE];
static U8 ReadParameters[PARAMETERS_GROUPS_SIZE];
static U8 ParametersChanged[PARAMETERS_GROUPS_SIZE];
static UNSIGNED GroupsIndexes[PARAMETERS_GROUPS_SIZE];
static int ParaGroupsSizes[PARAMETERS_GROUPS_SIZE] = { 11 };
static STATUS VarDbUpdateParameter(varid_t VariableId, void* Message, U16 Length, UNSIGNED paraGroupIndex, UNSIGNED Ref2)
{
   ReadParameters[paraGroupIndex] = 1;
   ParametersChanged[paraGroupIndex] = 1;
   return OS_SUCCESS;
}
static STATUS ReadParametersFunc(int paraGroupIndex)
{
   STATUS LocalStatus;
   // Check inputdata
   if (sizeof(ModulParameters[paraGroupIndex]) == 0)
   {
      AppSystemLog(ERR_4, MODULE_NAME"Group %d ModuleParameters = 0", paraGroupIndex);
      return ERR_4;
   }
   // Read inputdata
   LocalStatus = OS_ReadVariables(ModulParameters[paraGroupIndex], ParaGroupsSizes[paraGroupIndex]);
   if (LocalStatus != 0)
   {
      AppSystemLog(11, "LocalStatus: %d", LocalStatus);
      AppSystemLog(ERR_4, MODULE_NAME"ReadParErr: group=%d element=%d elementpointer=0x%x", paraGroupIndex, LocalStatus, &ModulParameters[LocalStatus]);
      return ERR_4;
   }
   return OS_SUCCESS;
}


//-----------------------------------------------------------------------
// READ VARS FROM VARDB    READ VARS FROM VARDB    READ VARS FROM VARDB
//-----------------------------------------------------------------------

static STATUS InputReferenceRoutine(U8 ModuleState)
{
   STATUS LocalStatus = 0;

   // Read input references
   if (ModuleState >= APP_INIT3)
   {
      // Check inputdata
      if (sizeof(ModulInputs) == 0)
      {
         AppSystemLog(ERR_4, MODULE_NAME"ModuleInputs = 0");
         return ERR_4;
      }
      // Read inputdata
      LocalStatus = OS_ReadVariables(ModulInputs, MODUL_INPUTS_SIZE);
      if (LocalStatus != 0)
      {
         AppSystemLog(ERR_4, MODULE_NAME"ReadVErr: element=%d elementpointer=0x%x", LocalStatus, &ModulInputs[LocalStatus]);
         return ERR_4;
      }
   }
   // Read input parameters
   if (ModuleState == APP_INIT3)
   {
      static size_t ParaCounter = 0;
      int groupIndex;
      for (groupIndex = 0; groupIndex < PARAMETERS_GROUPS_SIZE; groupIndex++)
      {
         ParametersChanged[groupIndex] = 1;
         ReadParameters[groupIndex] = 1;
         GroupsIndexes[groupIndex] = groupIndex;

         // Check inputdata
         if (sizeof(ModulParameters[groupIndex]) == 0)
         {
            AppSystemLog(ERR_4, MODULE_NAME"Group = %d ModuleParameters = 0", groupIndex);
            return ERR_4;
         }
         // Read inputdata
         LocalStatus = OS_ReadVariables(ModulParameters[groupIndex], ParaGroupsSizes[groupIndex]);
         if (LocalStatus != 0)
         {
            AppSystemLog(ERR_4, MODULE_NAME"ReadVParaErr: group=%d element=%d elementpointer=0x%x", groupIndex, LocalStatus, &ModulParameters[groupIndex][LocalStatus]);
            return ERR_4;
         }
         int paraIndex;
         for (paraIndex = 0; paraIndex < ParaGroupsSizes[groupIndex]; paraIndex++)
         {
            LocalStatus = OS_SubHandl_SubscribeFunctionWithRef(&ParaSubscription[ParaCounter], 1, &ModulParameters[groupIndex][paraIndex].Id, &GroupsIndexes[groupIndex], &GroupsIndexes[groupIndex], VarDbUpdateParameter);
            ParaCounter++;
            if (LocalStatus != 0)
            {
               AppSystemLog(ERR_4, MODULE_NAME"Subscribe Parameter: group=%d element=%d elementpointer=0x%x", groupIndex, LocalStatus, &ModulParameters[LocalStatus]);
               return ERR_4;
            }
         }
      }
   }
   if (ModuleState == APP_RUN)
   {
      int groupIndex;
      for (groupIndex = 0; groupIndex < PARAMETERS_GROUPS_SIZE; groupIndex++)
      {
         if (ReadParameters[groupIndex])
         {
            LocalStatus = ReadParametersFunc(groupIndex);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
            ReadParameters[groupIndex] = 0;
         }
      }
   }

   return 0;
}

#define READ_VARS

//-----------------------------------------------------------------------
// OUTPUT                         OUTPUT                         OUTPUT
//-----------------------------------------------------------------------

// Create local variable
#define MODUL_OUTPUTS
static S16 V_HubTemperatureLog = 0;
static S32 V_HubTempSensorState = 0;
static U8 V_HubLightOn = 0;
static U8 DO_HubSmokeDetectorSupply = 0;
static U8 DO_Hub_LightON = 0;
static char V_HubTempSensorStateTxt[31];


//-----------------------------------------------------------------------
static struct ModulInOut ModulOutputs[] =
{
   {"V_HubTemperatureLog",                      &V_HubTemperatureLog,                      sizeof(V_HubTemperatureLog),                      },
   {"V_HubTempSensorStateTxt",                  &V_HubTempSensorStateTxt,                  sizeof(V_HubTempSensorStateTxt),                  },
   {"V_HubTempSensorState",                     &V_HubTempSensorState,                     sizeof(V_HubTempSensorState),                     },
   {"V_HubLightOn",                             &V_HubLightOn,                             sizeof(V_HubLightOn),                             },
   {"DO_HubSmokeDetectorSupply",                &DO_HubSmokeDetectorSupply,                sizeof(DO_HubSmokeDetectorSupply),                },
   {"DO_Hub_LightON",                           &DO_Hub_LightON,                           sizeof(DO_Hub_LightON),                           },
};

//-----------------------------------------------------------------------
// Check variable type
static STATUS VarsWriteReturnStatus;
static type_t WriteVarType = TYPE_NONE;
static void VarsWriteTypeCheck(void)
{
   (void)VarsWriteReturnStatus;
   (void)WriteVarType;
   VERIFY_OUTPUT_REF_ID(S16,       ModulOutputs[0].Name,                     ModulOutputs[0].Id,                       0)
   VERIFY_OUTPUT_STRING_REF_ID(STRING,     ModulOutputs[1].Name,                      ModulOutputs[1].Id,                   0)
   VERIFY_OUTPUT_REF_ID(S32,       ModulOutputs[2].Name,                     ModulOutputs[2].Id,                       0)
   VERIFY_OUTPUT_REF_ID(U8,        ModulOutputs[3].Name,                     ModulOutputs[3].Id,                       0)
   VERIFY_OUTPUT_REF_ID(U8,        ModulOutputs[4].Name,                     ModulOutputs[4].Id,                       0)
   VERIFY_OUTPUT_REF_ID(U8,        ModulOutputs[5].Name,                     ModulOutputs[5].Id,                       0)
}

#undef MODUL_OUTPUTS
#define MODUL_OUTPUTS_SIZE (sizeof(ModulOutputs)/sizeof(ModulOutputs[0]))

//-----------------------------------------------------------------------
// WRITE VARS TO VARDB     WRITE VARS TO VARDB     WRITE VARS TO VARDB
//-----------------------------------------------------------------------

static STATUS InitOutputVars(void)
{
   STATUS LocalStatus;
   // Read outputdata
   LocalStatus = OS_ReadVariables(ModulOutputs, MODUL_OUTPUTS_SIZE);
   if (LocalStatus != 0)
   {
      AppSystemLog(ERR_4, MODULE_NAME"InitErr: element=%d elementpointer=0x%x", LocalStatus, &ModulOutputs[LocalStatus]);
      return ERR_4;
   }
   return OS_SUCCESS;
}
static STATUS OutputReferenceRoutine(U8 ModuleState)
{
   STATUS LocalStatus = 0;
   // Write Outputdata
   LocalStatus = OS_WriteVariablesConditional(ModulOutputs, MODUL_OUTPUTS_SIZE);
   if (LocalStatus != 0)
   {
      AppSystemLog(ERR_5, MODULE_NAME"WriteVErr: element=%d elementpointer=0x%x", LocalStatus, &ModulOutputs[LocalStatus]);
      return ERR_5;
   }
   return 0;
}

#define WRITE_VARS

//-----------------------------------------------------------------------
// VERIFY VARIABLES CREATION                 VERIFY VARIABLES CREATION
//-----------------------------------------------------------------------

static STATUS LocalIoCheck(void)
{
   // Check if input variables exist.
   STATUS LocalStatus;

   LocalStatus = OS_DoesVariablesExist(ModulInputs, MODUL_INPUTS_SIZE);
   if (LocalStatus != 0)
   {
      AppSystemLog(ERR_1, MODULE_NAME"InputErr: %d", LocalStatus);
      AppSystemLog(ERR_1, "Name: %s", ModulInputs[LocalStatus-1].Name);
      return ERR_1;
   }
   (void)VarsReadTypeCheck();

   int groupIndex;
   for (groupIndex = 0; groupIndex < PARAMETERS_GROUPS_SIZE; groupIndex++)
   {
      LocalStatus = OS_DoesVariablesExist(ModulParameters[groupIndex], ParaGroupsSizes[groupIndex]);
      if (LocalStatus != 0)
      {
         AppSystemLog(ERR_3, MODULE_NAME"ParameterErr: %d Group:%d", LocalStatus, groupIndex);
         AppSystemLog(ERR_3, "Name: %s", ModulParameters[groupIndex][LocalStatus-1].Name);
         return ERR_3;
      }
   }
   (void)ParaVarsReadTypeCheck();

   LocalStatus = OS_DoesVariablesExist(ModulOutputs, MODUL_OUTPUTS_SIZE);
   if (LocalStatus != 0)
   {
      AppSystemLog(ERR_2, MODULE_NAME"OutputErr: %d", LocalStatus);
      AppSystemLog(ERR_2, "Name: %s", ModulOutputs[LocalStatus-1].Name);
      return ERR_2;
   }
   (void)VarsWriteTypeCheck();

   return OS_SUCCESS;
}

#define VERIFY_VARIABLES

//-----------------------------------------------------------------------
// ALLOCATE MEMORY FOR SUMMATIONS        ALLOCATE MEMORY FOR SUMMATIONS
//-----------------------------------------------------------------------


//-----------------------------------------------------------------------
// SUMMATIONS                  SUMMATIONS                  SUMMATIONS
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// DEFINE MENUS               DEFINE MENUS               DEFINE MENUS
//-----------------------------------------------------------------------



// Menu line and link to local menu
//-----------------------------------------------------------------------
static struct line_struct M_HubLinkToLocalMenu[] =
{
   MENU_ELEMENT_LINE_LINK("Hub",                               PASSWORD_LEVEL_LICENCE_CUSTOMER,    "M_Hub",                            "G_Hub_MT_Type1"),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_HubMenu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_Hub",                            PASSWORD_LEVEL_LICENCE_CUSTOMER),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_HubMenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("HUB",                               PASSWORD_LEVEL_LICENCE_CUSTOMER,    "M_"APP_ID"AppMain",                "G_"APP_ID"App"),
   MENU_ELEMENT_LINE_VARRO("Hub temp. Status",                 PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_HubTempSensorStateTxt",                    LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Hub Temperature",                  PASSWORD_LEVEL_END_CUSTOMER,        (char*)"PT_HubTemp",                                 LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Smoke Detection",                  PASSWORD_LEVEL_END_CUSTOMER,        (char*)"DI_NacelleSmokeDetect",                      LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_LINK("Status",                            PASSWORD_LEVEL_END_CUSTOMER,        "M_Status2",                        "G_Hub_MT_Type1"),
   MENU_ELEMENT_LINE_LINK("Parameter",                         PASSWORD_LEVEL_END_CUSTOMER,        "M_Parameter3",                     "G_Hub_MT_Type1"),
   MENU_ELEMENT_LINE_LINK("Service",                           PASSWORD_LEVEL_SERVICE,             "M_Service344342",                  "G_Hub_MT_Type1"),
   MENU_ELEMENT_LINE_LINK("Debug",                             PASSWORD_LEVEL_MITA_PROGRAMMER,     "M_Debug5",                         "G_Hub_MT_Type1"),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_Status2Menu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_Status2",                        PASSWORD_LEVEL_END_CUSTOMER),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_Status2MenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("STATUS",                            PASSWORD_LEVEL_END_CUSTOMER,        "M_Hub",                            "G_Hub_MT_Type1"),
   MENU_ELEMENT_LINE_VARRO("Hub Smoke Detector Supply",        PASSWORD_LEVEL_END_CUSTOMER,        (char*)"DO_HubSmokeDetectorSupply",                  LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Smoke Detection",                  PASSWORD_LEVEL_END_CUSTOMER,        (char*)"DI_HubSmokeDetect",                          LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Hub Temperature",                  PASSWORD_LEVEL_END_CUSTOMER,        (char*)"PT_HubTemp",                                 LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Hub Light ON",                     PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_HubLightOn",                               LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("400V ON",                          PASSWORD_LEVEL_END_CUSTOMER,        (char*)"DI_Hub400V_ON",                              LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Hub Light Status",                 PASSWORD_LEVEL_END_CUSTOMER,        (char*)"DI_HubLightON",                              LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Bolt Monitoring System System Ok 1", PASSWORD_LEVEL_END_CUSTOMER,        (char*)"DI_Hub_BoltMonitoringSystemOk1",             LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Bolt Monitoring System System Ok 2", PASSWORD_LEVEL_END_CUSTOMER,        (char*)"DI_Hub_BoltMonitoringSystemOk2",             LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Bolt Monitoring System Bolt Ok 1", PASSWORD_LEVEL_END_CUSTOMER,        (char*)"DI_Hub_BoltMonitoringBoltOk1",               LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Bolt Monitoring System Bolt Ok 2", PASSWORD_LEVEL_END_CUSTOMER,        (char*)"DI_Hub_BoltMonitoringBoltOk2",               LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Hub Light ON",                     PASSWORD_LEVEL_END_CUSTOMER,        (char*)"DO_Hub_LightON",                             LINE_FORMAT_NONE),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_Parameter3Menu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_Parameter3",                     PASSWORD_LEVEL_END_CUSTOMER),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_Parameter3MenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("PARAMETER",                         PASSWORD_LEVEL_END_CUSTOMER,        "M_Hub",                            "G_Hub_MT_Type1"),
   MENU_ELEMENT_LINE_VARRW("Hub Temp. Enable",                 PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_HubTempEnable",                            LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Hub High Temp. Warning ON",        PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_HubHighTempWarnOn",                        LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Hub High Temp. Warning OFF",       PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_HubHighTempWarnOff",                       LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Hub High Temp. Stop ON",           PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_HubHighTempStopOn",                        LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Hub High Temp. Stop OFF",          PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_HubHighTempStopOff",                       LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Hub Low Temp. Warning ON",         PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_HubLowTempWarnOn",                         LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Hub Low Temp. Warning OFF",        PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_HubLowTempWarnOff",                        LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("PT100 Sensor Error High",          PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_HubTempErrHigh",                           LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("PT100 Sensor Error Low",           PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_HubTempErrLow",                            LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Hub Bolt Monitoring System 1 Enable", PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_Hub_BoltMonitoringEnable1",                LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Hub Bolt Monitoring System 2 Enable", PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_Hub_BoltMonitoringEnable2",                LINE_FORMAT_NONE),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_Service344342Menu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_Service344342",                  PASSWORD_LEVEL_SERVICE),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_Service344342MenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("SERVICE",                           PASSWORD_LEVEL_SERVICE,             "M_Hub",                            "G_Hub_MT_Type1"),
   MENU_ELEMENT_LINE_VARRW("Reset Smoke Detector",             PASSWORD_LEVEL_SERVICE,             (char*)"V_HubSmokeDetectorReset",                    LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Hub Light Mode",                   PASSWORD_LEVEL_SERVICE,             (char*)"P_Hub_LightMode",                            LINE_FORMAT_NONE),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_Debug5Menu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_Debug5",                         PASSWORD_LEVEL_MITA_PROGRAMMER),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_Debug5MenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("DEBUG",                             PASSWORD_LEVEL_MITA_PROGRAMMER,     "M_Hub",                            "G_Hub_MT_Type1"),
   MENU_ELEMENT_LINE_VARRO("V_HubTempSensorState",             PASSWORD_LEVEL_MITA_PROGRAMMER,     (char*)"V_HubTempSensorState",                       LINE_FORMAT_NONE),
};
// Creating parameters for multiplexed categories
//-----------------------------------------------------------------------
static struct multiplexed_info_struct M_HubMultiplexedCategoriesParameters[] =
{
0};

//-----------------------------------------------------------------------
// CREATE MENUS               CREATE MENUS               CREATE MENUS
//-----------------------------------------------------------------------

// Memory reservation
//-----------------------------------------------------------------------
static struct menu_group_struct ObjGroup[1];

// Creating the menus
//-----------------------------------------------------------------------
STATUS Hub_MT_Type1MenuAppInit(U8 ModuleState, OS_MEMORY_POOL* pPool)
{
   STATUS Status;

   if (ModuleState == APP_INIT1)
   {
      /* Create application group */
      Status = OS_CreateMenuGroup(ObjGroup, M_HubLinkToLocalMenu[0].LinkGroup);
      STATUS_LINE_VAR_RETURN_VALUE(Status);
   }

   Status = CreateAndInitializeMenu(ModuleState,
                                    M_HubMenuLines[0].LinkGroup,
                                    M_HubMenuLines[0].LinkName,
                                    ELEMENT(M_HubLinkToLocalMenu),
                                    M_HubLinkToLocalMenu[0].LinkGroup,
                                    ELEMENT(M_HubMenu),
                                    M_HubLinkToLocalMenu[0].LinkName,
                                    ELEMENT(M_HubMenuLines),
                                    pPool,
                                    M_HubMultiplexedCategoriesParameters);
   STATUS_LINE_VAR_RETURN_VALUE(Status);

   Status = CreateAndInitializeMenu(ModuleState,
                                    M_Status2MenuLines[0].LinkGroup,
                                    M_Status2MenuLines[0].LinkName,
                                    NULL,
                                    0,
                                    M_HubMenuLines[4].LinkGroup,
                                    ELEMENT(M_Status2Menu),
                                    M_HubMenuLines[4].LinkName,
                                    ELEMENT(M_Status2MenuLines),
                                    pPool,
                                    M_HubMultiplexedCategoriesParameters);
   STATUS_LINE_VAR_RETURN_VALUE(Status);

   Status = CreateAndInitializeMenu(ModuleState,
                                    M_Parameter3MenuLines[0].LinkGroup,
                                    M_Parameter3MenuLines[0].LinkName,
                                    NULL,
                                    0,
                                    M_HubMenuLines[5].LinkGroup,
                                    ELEMENT(M_Parameter3Menu),
                                    M_HubMenuLines[5].LinkName,
                                    ELEMENT(M_Parameter3MenuLines),
                                    pPool,
                                    M_HubMultiplexedCategoriesParameters);
   STATUS_LINE_VAR_RETURN_VALUE(Status);

   Status = CreateAndInitializeMenu(ModuleState,
                                    M_Service344342MenuLines[0].LinkGroup,
                                    M_Service344342MenuLines[0].LinkName,
                                    NULL,
                                    0,
                                    M_HubMenuLines[6].LinkGroup,
                                    ELEMENT(M_Service344342Menu),
                                    M_HubMenuLines[6].LinkName,
                                    ELEMENT(M_Service344342MenuLines),
                                    pPool,
                                    M_HubMultiplexedCategoriesParameters);
   STATUS_LINE_VAR_RETURN_VALUE(Status);

   Status = CreateAndInitializeMenu(ModuleState,
                                    M_Debug5MenuLines[0].LinkGroup,
                                    M_Debug5MenuLines[0].LinkName,
                                    NULL,
                                    0,
                                    M_HubMenuLines[7].LinkGroup,
                                    ELEMENT(M_Debug5Menu),
                                    M_HubMenuLines[7].LinkName,
                                    ELEMENT(M_Debug5MenuLines),
                                    pPool,
                                    M_HubMultiplexedCategoriesParameters);
   STATUS_LINE_VAR_RETURN_VALUE(Status);

   return OS_SUCCESS;
}

#define CREATE_MENU

//-----------------------------------------------------------------------
//               BUTTONS FUNCTIONS FORWARD DECLARATIONS
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// BUTTONS                       BUTTONS                      BUTTONS
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
//             SET/RESET FUNCTIONS FORWARD DECLARATIONS
//-----------------------------------------------------------------------
static U8 StatusSetFunc2481(void);
static U8 StatusResetFunc2481(void);
static U8 StatusSetFunc2482(void);
static U8 StatusResetFunc2482(void);
static U8 StatusSetFunc2483(void);
static U8 StatusResetFunc2483(void);
static U8 StatusSetFunc3509(void);
static U8 StatusSetFunc5009(void);
static U8 StatusResetFunc5009(void);
static U8 StatusSetFunc5071(void);
static U8 StatusResetFunc5071(void);
static U8 StatusSetFunc5072(void);
static U8 StatusResetFunc5072(void);
static U8 StatusSetFunc5073(void);
static U8 StatusResetFunc5073(void);
static U8 StatusSetFunc5074(void);
static U8 StatusResetFunc5074(void);
//-----------------------------------------------------------------------
// STATUSCODES                 STATUSCODES                 STATUSCODES
//-----------------------------------------------------------------------

static struct sts_statuscode_structure StatusCodes[] =
{
   STS_CODE_ELEMENT("Hub high temp. Warn.",   20*SEC,    2481,      STATUSCODE_UPDATE_TYPE_POLLING,         PASSWORD_LEVEL_SERVICE,            STATUSCODE_TIMER_TYPE_CONSTANT,     STATUSCODE_TIMER_TYPE_CONSTANT,     STATUSCODE_RESET_TYPE_AUTOMATIC,    STATUSCODE_PRIORITY_LOW,       22,   0,    32,   NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      StatusSetFunc2481,       StatusResetFunc2481,     0,                   BRAKE_PROG_0,        BRAKE_PROG_MAX,      NULL,                PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,                   YAW_PROG_0,          YAW_PROG_240,        NULL,                PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    1,    0,    255,  NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            1,  PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      1000,      20,        1000,      NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         SETDELAY_MIN,   SETDELAY_MAX,   NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      0,         RESETDELAY_MIN, RESETDELAY_MAX, NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      0,         REPEATTIMES_MIN,     REPEATTIMES_MAX,     NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         REPEATPERIOD_MIN,    REPEATPERIOD_MAX,    NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         REPEATCODE_MIN,      REPEATCODE_MAX,      NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         TIMEOUTPERIOD_MIN,   TIMEOUTPERIOD_MAX,   NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         TIMEOUTCODE_MIN,     TIMEOUTCODE_MAX,     NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      NULL),
   STS_CODE_ELEMENT("Hub high temp. Stop",    20*SEC,    2482,      STATUSCODE_UPDATE_TYPE_POLLING,         PASSWORD_LEVEL_SERVICE,            STATUSCODE_TIMER_TYPE_CONSTANT,     STATUSCODE_TIMER_TYPE_CONSTANT,     STATUSCODE_RESET_TYPE_AUTOMATIC,    STATUSCODE_PRIORITY_LOW,       22,   0,    32,   NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      StatusSetFunc2482,       StatusResetFunc2482,     BRAKE_PROG_50,       BRAKE_PROG_0,        BRAKE_PROG_MAX,      NULL,                PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,                   YAW_PROG_0,          YAW_PROG_240,        NULL,                PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    1,    0,    255,  NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            1,  PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      1000,      20,        1000,      NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         SETDELAY_MIN,   SETDELAY_MAX,   NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      0,         RESETDELAY_MIN, RESETDELAY_MAX, NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      0,         REPEATTIMES_MIN,     REPEATTIMES_MAX,     NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         REPEATPERIOD_MIN,    REPEATPERIOD_MAX,    NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         REPEATCODE_MIN,      REPEATCODE_MAX,      NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         TIMEOUTPERIOD_MIN,   TIMEOUTPERIOD_MAX,   NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         TIMEOUTCODE_MIN,     TIMEOUTCODE_MAX,     NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      NULL),
   STS_CODE_ELEMENT("Hub low temp. Warn.",    20*SEC,    2483,      STATUSCODE_UPDATE_TYPE_POLLING,         PASSWORD_LEVEL_SERVICE,            STATUSCODE_TIMER_TYPE_CONSTANT,     STATUSCODE_TIMER_TYPE_CONSTANT,     STATUSCODE_RESET_TYPE_AUTOMATIC,    STATUSCODE_PRIORITY_LOW,       27,   0,    32,   NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      StatusSetFunc2483,       StatusResetFunc2483,     0,                   BRAKE_PROG_0,        BRAKE_PROG_MAX,      NULL,                PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,                   YAW_PROG_0,          YAW_PROG_240,        NULL,                PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    1,    0,    255,  NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            1,  PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      1000,      20,        1000,      NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         SETDELAY_MIN,   SETDELAY_MAX,   NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      0,         RESETDELAY_MIN, RESETDELAY_MAX, NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      0,         REPEATTIMES_MIN,     REPEATTIMES_MAX,     NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         REPEATPERIOD_MIN,    REPEATPERIOD_MAX,    NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         REPEATCODE_MIN,      REPEATCODE_MAX,      NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         TIMEOUTPERIOD_MIN,   TIMEOUTPERIOD_MAX,   NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         TIMEOUTCODE_MIN,     TIMEOUTCODE_MAX,     NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      NULL),
   STS_CODE_ELEMENT("Smoke Hub",              20*SEC,    3509,      STATUSCODE_UPDATE_TYPE_POLLING,         PASSWORD_LEVEL_SERVICE,            STATUSCODE_TIMER_TYPE_CONSTANT,     STATUSCODE_TIMER_TYPE_CONSTANT,     STATUSCODE_RESET_TYPE_DISPLAY,      STATUSCODE_PRIORITY_LOW,       15,   0,    32,   NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         StatusSetFunc3509,       NULL,                    BRAKE_PROG_50,       BRAKE_PROG_0,        BRAKE_PROG_MAX,      NULL,                PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    YAW_PROG_240,        YAW_PROG_0,          YAW_PROG_240,        NULL,                PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    1,    0,    255,  NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            1,  PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      1000,      20,        1000,      NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         SETDELAY_MIN,   SETDELAY_MAX,   NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         0,         RESETDELAY_MIN, RESETDELAY_MAX, NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         0,         REPEATTIMES_MIN,     REPEATTIMES_MAX,     NULL,      PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         REPEATPERIOD_MIN,    REPEATPERIOD_MAX,    NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         REPEATCODE_MIN,      REPEATCODE_MAX,      NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         TIMEOUTPERIOD_MIN,   TIMEOUTPERIOD_MAX,   NULL,      PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         TIMEOUTCODE_MIN,     TIMEOUTCODE_MAX,     NULL,      PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         NULL),
   STS_CODE_ELEMENT("Hub PT100!",             20*SEC,    5009,      STATUSCODE_UPDATE_TYPE_POLLING,         PASSWORD_LEVEL_SERVICE,            STATUSCODE_TIMER_TYPE_CONSTANT,     STATUSCODE_TIMER_TYPE_CONSTANT,     STATUSCODE_RESET_TYPE_AUTOMATIC,    STATUSCODE_PRIORITY_LOW,       21,   1,    32,   NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    StatusSetFunc5009,       StatusResetFunc5009,     BRAKE_PROG_50,       BRAKE_PROG_0,        BRAKE_PROG_MAX,      NULL,                PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    YAW_PROG_0,          YAW_PROG_0,          YAW_PROG_240,        NULL,                PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    1,    0,    255,  NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            1,  PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      1000,      20,        1000,      NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    5*SEC,     SETDELAY_MIN,   SETDELAY_MAX,   NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      5*SEC,     RESETDELAY_MIN, RESETDELAY_MAX, NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      3,         REPEATTIMES_MIN,     REPEATTIMES_MAX,     NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    1ULL*DAY,  REPEATPERIOD_MIN,    REPEATPERIOD_MAX,    NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    23,        REPEATCODE_MIN,      REPEATCODE_MAX,      NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         TIMEOUTPERIOD_MIN,   TIMEOUTPERIOD_MAX,   NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         TIMEOUTCODE_MIN,     TIMEOUTCODE_MAX,     NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    NULL),
   STS_CODE_ELEMENT("Hub Bolt 1 Warn.",       20*SEC,    5071,      STATUSCODE_UPDATE_TYPE_POLLING,         PASSWORD_LEVEL_SERVICE,            STATUSCODE_TIMER_TYPE_CONSTANT,     STATUSCODE_TIMER_TYPE_CONSTANT,     STATUSCODE_RESET_TYPE_AUTOMATIC,    STATUSCODE_PRIORITY_LOW,       22,   0,    32,   NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      StatusSetFunc5071,       StatusResetFunc5071,     0,                   BRAKE_PROG_0,        BRAKE_PROG_MAX,      NULL,                PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,                   YAW_PROG_0,          YAW_PROG_240,        NULL,                PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    1,    0,    255,  NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            1,  PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      20,        20,        1000,      NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    1*SEC,     SETDELAY_MIN,   SETDELAY_MAX,   NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      5*SEC,     RESETDELAY_MIN, RESETDELAY_MAX, NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      0,         REPEATTIMES_MIN,     REPEATTIMES_MAX,     NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         REPEATPERIOD_MIN,    REPEATPERIOD_MAX,    NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         REPEATCODE_MIN,      REPEATCODE_MAX,      NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         TIMEOUTPERIOD_MIN,   TIMEOUTPERIOD_MAX,   NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         TIMEOUTCODE_MIN,     TIMEOUTCODE_MAX,     NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      NULL),
   STS_CODE_ELEMENT("Hub Bolt 1 Stop",        20*SEC,    5072,      STATUSCODE_UPDATE_TYPE_POLLING,         PASSWORD_LEVEL_SERVICE,            STATUSCODE_TIMER_TYPE_CONSTANT,     STATUSCODE_TIMER_TYPE_CONSTANT,     STATUSCODE_RESET_TYPE_AUTOMATIC,    STATUSCODE_PRIORITY_LOW,       22,   0,    32,   NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      StatusSetFunc5072,       StatusResetFunc5072,     BRAKE_PROG_50,       BRAKE_PROG_0,        BRAKE_PROG_MAX,      NULL,                PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,                   YAW_PROG_0,          YAW_PROG_240,        NULL,                PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    1,    0,    255,  NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            1,  PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      20,        20,        1000,      NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    1*SEC,     SETDELAY_MIN,   SETDELAY_MAX,   NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      5*SEC,     RESETDELAY_MIN, RESETDELAY_MAX, NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      0,         REPEATTIMES_MIN,     REPEATTIMES_MAX,     NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         REPEATPERIOD_MIN,    REPEATPERIOD_MAX,    NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         REPEATCODE_MIN,      REPEATCODE_MAX,      NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         TIMEOUTPERIOD_MIN,   TIMEOUTPERIOD_MAX,   NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         TIMEOUTCODE_MIN,     TIMEOUTCODE_MAX,     NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      NULL),
   STS_CODE_ELEMENT("Hub Bolt 2 Warn.",       20*SEC,    5073,      STATUSCODE_UPDATE_TYPE_POLLING,         PASSWORD_LEVEL_SERVICE,            STATUSCODE_TIMER_TYPE_CONSTANT,     STATUSCODE_TIMER_TYPE_CONSTANT,     STATUSCODE_RESET_TYPE_AUTOMATIC,    STATUSCODE_PRIORITY_LOW,       22,   0,    32,   NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      StatusSetFunc5073,       StatusResetFunc5073,     0,                   BRAKE_PROG_0,        BRAKE_PROG_MAX,      NULL,                PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,                   YAW_PROG_0,          YAW_PROG_240,        NULL,                PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    1,    0,    255,  NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            1,  PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      20,        20,        1000,      NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    1*SEC,     SETDELAY_MIN,   SETDELAY_MAX,   NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      5*SEC,     RESETDELAY_MIN, RESETDELAY_MAX, NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      0,         REPEATTIMES_MIN,     REPEATTIMES_MAX,     NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         REPEATPERIOD_MIN,    REPEATPERIOD_MAX,    NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         REPEATCODE_MIN,      REPEATCODE_MAX,      NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         TIMEOUTPERIOD_MIN,   TIMEOUTPERIOD_MAX,   NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         TIMEOUTCODE_MIN,     TIMEOUTCODE_MAX,     NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      NULL),
   STS_CODE_ELEMENT("Hub Bolt 2 Stop",        20*SEC,    5074,      STATUSCODE_UPDATE_TYPE_POLLING,         PASSWORD_LEVEL_SERVICE,            STATUSCODE_TIMER_TYPE_CONSTANT,     STATUSCODE_TIMER_TYPE_CONSTANT,     STATUSCODE_RESET_TYPE_AUTOMATIC,    STATUSCODE_PRIORITY_LOW,       22,   0,    32,   NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      StatusSetFunc5074,       StatusResetFunc5074,     BRAKE_PROG_50,       BRAKE_PROG_0,        BRAKE_PROG_MAX,      NULL,                PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,                   YAW_PROG_0,          YAW_PROG_240,        NULL,                PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    1,    0,    255,  NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            1,  PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      20,        20,        1000,      NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    1*SEC,     SETDELAY_MIN,   SETDELAY_MAX,   NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      5*SEC,     RESETDELAY_MIN, RESETDELAY_MAX, NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      0,         REPEATTIMES_MIN,     REPEATTIMES_MAX,     NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         REPEATPERIOD_MIN,    REPEATPERIOD_MAX,    NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         REPEATCODE_MIN,      REPEATCODE_MAX,      NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         TIMEOUTPERIOD_MIN,   TIMEOUTPERIOD_MAX,   NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         TIMEOUTCODE_MIN,     TIMEOUTCODE_MAX,     NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      NULL),
};

static STATUS_CODE_CONTROL_BLOCK StatusCodeControlBlock;

static STATUS LocalStatusCodeInit(void)
{
   STATUS LocalStatus;

   LocalStatus = OS_StatusCodeInit(STATUSCODE_INTERFACE_VERSION,
                                   &StatusCodeControlBlock,
                                   StatusCodes,
                                   sizeof(StatusCodes)/sizeof(StatusCodes[0]),
                                   AppLocalParameterPosition(),
                                   AppBackupPosition());
   STATUS_LINE_VAR_RETURN_CONST(LocalStatus, ERR_3);

   return OS_SUCCESS;
}

#define CREATE_STATUS_CODES

//-----------------------------------------------------------------------
// MODIFIABLE                  MODIFIABLE                   MODIFIABLE
//-----------------------------------------------------------------------

extern const char Hub_MT_Type1AppGroupName[];
extern const char Hub_MT_Type1AppMenuName[];

static void Init_Structures_From_Conf_File(void)
{
   M_HubMenuLines[0].LinkName = (char*)Hub_MT_Type1AppMenuName;
   M_HubMenuLines[0].LinkGroup = (char*)Hub_MT_Type1AppGroupName;
}

//-----------------------------------------------------------------------
// AUTOGENERATED END        AUTOGENERATED END        AUTOGENERATED END
//-----------------------------------------------------------------------
//}

#undef AUTOGENERATED_PART

//-----------------------------------------------------------------------
// USER DEFINITIONS         USER DEFINITIONS         USER DEFINITIONS
//-----------------------------------------------------------------------
static S32 LinearConvertion(S32 Value, S32 MinIn, S32 MaxIn, S32 MinOut, S32 MaxOut)
{
    S32 Res;

    if (MaxIn != MinIn) { Res = ((S64)Value - MinIn)*(MaxOut - MinOut)/(MaxIn - MinIn) + MinOut; }
    else                { Res = MinOut; }

    return Res;
}
//-----------------------------------------------------------------------
static S32 LinearLimConvertion(S32 Value, S32 MinIn, S32 MaxIn, S32 MinOut, S32 MaxOut)
{
    S32 Res;
    S32 MinVal;
    S32 MaxVal;

    if (MinOut != MaxOut)
    {
      MinVal = MinOut;
      MaxVal = MaxOut;
    }
    else
    {
      MinVal = MaxOut;
      MaxVal = MinOut;
    }

    Res = LinearConvertion(Value, MinIn, MaxIn, MinOut, MaxOut);

    if      (Res < MinVal) { Res = MinVal; }
    else if (Res > MaxVal) { Res = MaxVal; }

    return Res;
}

// Values for Status of the Sensors
typedef enum _SENSOR_STATUS_t
{
    SENSOR_STATUS_OK = 1,
    SENSOR_STATUS_ERROR,
    SENSOR_STATUS_DISABLED
} SENSOR_STATUS_t;
 
//-----------------------------------------------------------------------
// SET/RESET FUNCTIONS    SET/RESET FUNCTIONS    SET/RESET FUNCTIONS
//-----------------------------------------------------------------------
// Status code 2481 : Hub high temp. Warn.
//-----------------------------------------------------------------------
static U8 StatusSetFunc2481(void)
{
    if(P_HubTempEnable && (P_HubHighTempWarnOn < PT_HubTemp))
    {
        return 1;
    }
    return 0;
}

static U8 StatusResetFunc2481(void)
{
    if(!P_HubTempEnable || (P_HubHighTempWarnOff > PT_HubTemp))
    {
        return 1;
    }
    return 0;
}

// Status code 2482 : Hub high temp. Stop
//-----------------------------------------------------------------------
static U8 StatusSetFunc2482(void)
{
    if(P_HubTempEnable && (P_HubHighTempStopOn < PT_HubTemp))
    {
        return 1;
    }
    return 0;
}

static U8 StatusResetFunc2482(void)
{
    if(!P_HubTempEnable || (P_HubHighTempStopOff > PT_HubTemp))
    {
       return 1;
    }
    return 0;
}

// Status code 2483 : Hub low temp. Warn.
//-----------------------------------------------------------------------
static U8 StatusSetFunc2483(void)
{
    if(P_HubTempEnable && (P_HubLowTempWarnOn > PT_HubTemp))
    {
        return 1;
    }
    return 0;
}

static U8 StatusResetFunc2483(void)
{
    if(P_HubTempEnable && (P_HubLowTempWarnOff < PT_HubTemp))
    {
        return 1;
    }
    return 0;
}
// Status code 3509 : Smoke Hub
//-----------------------------------------------------------------------
static U8 StatusSetFunc3509(void)
{
    if ( GridErrorActive() || WPlineError() )
    {
       return 0;
    }

    return !DI_HubSmokeDetect;
}

// Status code 5009 : Hub PT100!
//-----------------------------------------------------------------------
static U8 StatusSetFunc5009(void)
{
    if( SENSOR_STATUS_ERROR == V_HubTempSensorState)
    {
        return 1;
    }
    return 0;
}

static U8 StatusResetFunc5009(void)
{
    return !StatusSetFunc5009();
}

// Status code 5071 : Hub Bolt 1 Warn.
//-----------------------------------------------------------------------
static U8 StatusSetFunc5071(void)
{
   if(!P_Hub_BoltMonitoringEnable1) { return 0; }

   if(DI_Hub_BoltMonitoringSystemOk1 && DI_Hub_BoltMonitoringBoltOk1){ return 0; }

   return 1;
}

static U8 StatusResetFunc5071(void)
{
   if(!P_Hub_BoltMonitoringEnable1) { return 1; }

   if(DI_Hub_BoltMonitoringSystemOk1 && DI_Hub_BoltMonitoringBoltOk1){ return 1; }

   return 0;
}

// Status code 5072 : Hub Bolt 1 Stop
//-----------------------------------------------------------------------
static U8 StatusSetFunc5072(void)
{
   if(!P_Hub_BoltMonitoringEnable1) { return 0; }

   if(!DI_Hub_BoltMonitoringSystemOk1 && !DI_Hub_BoltMonitoringBoltOk1){ return 1; }

   return 0;
}

static U8 StatusResetFunc5072(void)
{
   if(!P_Hub_BoltMonitoringEnable1) { return 1; }

   if(DI_Hub_BoltMonitoringSystemOk1 && DI_Hub_BoltMonitoringBoltOk1){ return 1; }

   return 0;
}

// Status code 5073 : Hub Bolt 2 Warn.
//-----------------------------------------------------------------------
static U8 StatusSetFunc5073(void)
{
   if(!P_Hub_BoltMonitoringEnable2) { return 0; }

   if(DI_Hub_BoltMonitoringSystemOk2 && DI_Hub_BoltMonitoringBoltOk2){ return 0; }

   return 1;
}

static U8 StatusResetFunc5073(void)
{
   if(!P_Hub_BoltMonitoringEnable2) { return 1; }

   if(DI_Hub_BoltMonitoringSystemOk2 && DI_Hub_BoltMonitoringBoltOk2){ return 1; }

   return 0;
}


// Status code 5074 : Hub Bolt 2 Stop
//-----------------------------------------------------------------------
static U8 StatusSetFunc5074(void)
{
   if(!P_Hub_BoltMonitoringEnable2) { return 0; }

   if(!DI_Hub_BoltMonitoringSystemOk2 && !DI_Hub_BoltMonitoringBoltOk2){ return 1; }

   return 0;
}

static U8 StatusResetFunc5074(void)
{
   if(!P_Hub_BoltMonitoringEnable2) { return 1; }

   if(DI_Hub_BoltMonitoringSystemOk2 && DI_Hub_BoltMonitoringBoltOk2){ return 1; }

   return 0;
}

//-----------------------------------------------------------------------
// DRIVER FUNCTION         DRIVER FUNCTION         DRIVER FUNCTION
//-----------------------------------------------------------------------
  
//-----------------------------------------------------------------------
// INIT                   INIT                     INIT
//-----------------------------------------------------------------------
static const U32 SmokeResetTimeout = 3000;
static varid_t V_HubSmokeDetectorResetID;

static struct StandardTimerVarStruct SmokeResetTimer =
{
   0,                              // Timer value [ms]
   &SmokeResetTimeout,             // Pointer to the timeout variable [ms]
   HUB_TIMER,                      // Timer interval [ms]. The function "StandardTimer" is called with this interval.
   TIMER_STOP,                     // Start TIMER_DOWN / TIMER_STOP / TIMER_UP
   0                               // Is used to check if the "StandardTimer" function is called.
};
//-----------------------------------------------------------------------
// CONTROL                CONTROL                 CONTROL
//-----------------------------------------------------------------------
static void SensorStatus( void )
{
    if( !P_HubTempEnable )
    {
        V_HubTempSensorState = SENSOR_STATUS_DISABLED;
    }
    else if( (PT_HubTemp > P_HubTempErrHigh) || (PT_HubTemp < P_HubTempErrLow) )
    {
        V_HubTempSensorState = SENSOR_STATUS_ERROR;
    }
    else
    {
        V_HubTempSensorState = SENSOR_STATUS_OK;
    }
}

//___________________________________________________________________
static void SensorStatusTxt( S32 Status, S32 *OldStatus, char *Text, S32 Size )
{
    if( Status != *OldStatus )
    {
        switch( Status )
        {
            case SENSOR_STATUS_OK:
            {
                strncpy( Text, "OK", Size );
            }
                break;
            case SENSOR_STATUS_DISABLED:
            {
                strncpy( Text, "Disabled", Size );
            }
                break;
            case SENSOR_STATUS_ERROR:
            {
                strncpy( Text, "Sensor Error", Size );
            }
                break;
            default:
            {
                strncpy( Text, "WARNING", Size );
            }
                break;
        }
    }

    *OldStatus = Status;
}

static void ResetSmokeDetector()
{
    if (V_HubSmokeDetectorReset)
    {
        DO_HubSmokeDetectorSupply = 0;
        StartTimer(&SmokeResetTimer);
        if (StandardTimer(&SmokeResetTimer))
        {
            V_HubSmokeDetectorReset = 0;
            OS_VarDB_UpdateVariable(V_HubSmokeDetectorResetID, &V_HubSmokeDetectorReset, sizeof V_HubSmokeDetectorReset);
            DO_HubSmokeDetectorSupply = 1;
        }
    }
    else
    {
        ResetTimer(&SmokeResetTimer);
        DO_HubSmokeDetectorSupply = 1;
    }
}

static void Hub_LightCtrl()
{
    switch (P_Hub_LightMode)
    {
        case MODE_AUTO :
        {
            DO_Hub_LightON = DI_Panels_TowerBasePanelLight;
        }
        break;
        case MODE_SERVICE_OFF:
        {
            DO_Hub_LightON = OFF;
        }
        break;
        case MODE_SERVICE_ON :
        {
            DO_Hub_LightON = ON;
        }
        break;
        default :
        {
            DO_Hub_LightON = OFF;
        }
        break;
    }
}
static STATUS LocalCtrl(void)
{
   STATUS LocalStatus = 0;

   static S32 HubTempSensorState_Old = 100500;

   V_HubTemperatureLog     = PT_HubTemp;

   SensorStatus();

   SensorStatusTxt( V_HubTempSensorState,
                    &HubTempSensorState_Old,
                    V_HubTempSensorStateTxt,
                    sizeof(V_HubTempSensorStateTxt) );

   V_HubLightOn = DI_Hub400V_ON & DI_HubLightON;

   ResetSmokeDetector();

   Hub_LightCtrl();

   return LocalStatus;
}
  
//-----------------------------------------------------------------------
// MAIN CALL             MAIN CALL               MAIN CALL
//-----------------------------------------------------------------------

STATUS Hub_MT_Type1(U8 ModuleState, OS_MEMORY_POOL *MemPool, U32 *Arg3)
{
   STATUS LocalStatus = 0;

   // Version check
   if(ModuleState == APP_INIT1)
   {
      LocalStatus = OS_ValidateAPI(API_VERSION_MAJOR,
                                   API_VERSION_MINOR,
                                   OS_LinkTime,
                                   ReleaseTag,
                                   __MODULE__
                                   );
      if ( OS_SUCCESS != LocalStatus )
      {
         return LocalStatus;
      }
   }
#ifdef READ_VARS
   // Read inputdata
   LocalStatus = InputReferenceRoutine(ModuleState);
   STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif
#ifdef COMMON_VDB_READ
   LocalStatus = ReadVdbWindow(ModuleState);
   STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif
   switch(ModuleState)
   {
      case APP_RUN :
      {
         #ifdef FUNCTION_BLOCKS_PRE_LOCAL_CONTROL
            LocalStatus = FunctionBlocksPreLocalCtrl( Interval );
            STATUS_LINE_VAR_RETURN_VALUE( LocalStatus );
         #endif

         LocalStatus = LocalCtrl();
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
        
         #ifdef FUNCTION_BLOCKS_POST_LOCAL_CONTROL
            LocalStatus = FunctionBlocksPostLocalCtrl( Interval );
            STATUS_LINE_VAR_RETURN_VALUE( LocalStatus );
         #endif

#ifdef WRITE_VARS
         // Write Outputdata
         LocalStatus = OutputReferenceRoutine(ModuleState);
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif

#ifdef COMMON_VDB_WRITE
         LocalStatus = WriteVdbWindow(ModuleState);
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif
         break;
      }
      case APP_INIT1 :
      {
         Init_Structures_From_Conf_File();

#ifdef CREATE_VARDB_VARS
         LocalStatus = CreateVarDbVars();
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif

#ifdef CREATE_MENU
         LocalStatus = Hub_MT_Type1MenuAppInit(ModuleState, MemPool);
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)

#ifdef MULTIPLEXIBLE_MENU
         LocalStatus = MenuArraysAppInit(ModuleState, MemPool);
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif
#endif

#ifdef CREATE_VARDB_ARRAY_VARS
         LocalStatus = CreateVdbArrays(MemPool);
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif

#ifdef CREATE_IO_VARS
         LocalStatus = CreateIOVars();
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif
         break;
      }
      case APP_INIT2 :
      {
#ifdef CREATE_MENU
#ifdef MULTIPLEXIBLE_MENU
         LocalStatus = MenuArraysAppInit(ModuleState, MemPool);
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif
#endif

#ifdef CREATE_ALIASES
         size_t ErrorEntry = 0;
         LocalStatus = OS_VarDB_CreateAliases(AliasVars, sizeof(AliasVars)/sizeof(AliasVars[0]), &ErrorEntry);
         STATUS_LINE_VAR_RETURN_CONST(LocalStatus, ErrorEntry)
#endif

#ifdef VERIFY_ARRAY
        LocalStatus = VerifyArray(MemPool);
        STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif

#ifdef VERIFY_VARIABLES
         LocalStatus = LocalIoCheck();
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif

#ifdef CREATE_BUTTONS
         LocalStatus = CreateButtons();
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif
         break;
      }
      case APP_INIT3 :
      {
#ifdef CREATE_SUMMATIONS
         LocalStatus = CreateSummations();
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif

#ifdef WRITE_VARS
         LocalStatus = InitOutputVars();
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif

#ifdef CREATE_STATUS_CODES
         LocalStatus = LocalStatusCodeInit();
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif

#ifdef CREATE_IO_VARS
        Hub_MT_Type1SetLockValues();
#endif
         break;
      }
      case APP_INIT4 :
      {
#ifdef CREATE_MENU
         LocalStatus = Hub_MT_Type1MenuAppInit(ModuleState, MemPool);
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)

#ifdef MULTIPLEXIBLE_MENU
         LocalStatus = MenuArraysAppInit(ModuleState, MemPool);
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif
#endif
         break;
      }
      case APP_INIT5 :
      {
#ifdef VALIDATE_HASH
         LocalStatus = ValidateHash(Hub_MT_Type1_copyright, MODULE_NAME, Hub_MT_Type1_initialValues);
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif

         #ifdef INIT_FUNCTION_BLOCKS
            LocalStatus = FunctionBlocksInit( Interval );
            STATUS_LINE_VAR_RETURN_VALUE( LocalStatus );
         #endif


         LocalStatus = OS_VarDB_GetVariableID("V_HubSmokeDetectorReset", &V_HubSmokeDetectorResetID);
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
         break;
      }
      default :
      {
         break;
      }
   }
   return OS_SUCCESS;
}
//-----------------------------------------------------------------------
