//*****************************PEPTOOL Header Start******************************
//                                                                               
//                         Copyright © 2015 Mita-Teknik.                         
//This software may only be used with WP4x00 Controllers delivered by Mita-Teknik
//                                                                               
//*******************************************************************************
//                                                                               
// $PEPTOOL version:9.0$                                                         
// $PEPTOOL file version:106$                                                    
//                                                                               
//*******************************************************************************
//                                                                               
// $Date: 2014/04/08 06:57:01 $                                                  
// $Author: MITA\ihn $                                                           
// $RCSfile: Info.c,v $                                                          
// $Revision: 1.3 $                                                              
//                                                                               
//******************************PEPTOOL Header End*******************************

//***********************************************************************
// OS header files
#include <os_main.h>
// AppLib header files
#include <lib_main.h>
// App header files
#include <turbdef.h>
#include <VarMacros.h>
// Object header file
#include <Info.h>

#define AUTOGENERATED_PART
//{
//-----------------------------------------------------------------------
// AUTOGENERATED START     AUTOGENERATED START     AUTOGENERATED START
//-----------------------------------------------------------------------

#define VALIDATE_HASH
char Info_copyright[] =
{
   67, 111, 112, 121, 114, 105, 103, 104, 116, 32, 63, 32, 50, 48, 49, 53,
   32, 77, 105, 116, 97, 45, 84, 101, 107, 110, 105, 107, 46, 13, 10, 84,
   104, 105, 115, 32, 115, 111, 102, 116, 119, 97, 114, 101, 32, 109, 97, 121,
   32, 111, 110, 108, 121, 32, 98, 101, 32, 117, 115, 101, 100, 32, 119, 105,
   116, 104, 32, 87, 80, 52, 120, 48, 48, 32, 67, 111, 110, 116, 114, 111,
   108, 108, 101, 114, 115, 32, 100, 101, 108, 105, 118, 101, 114, 101, 100, 32,
   98, 121, 32, 77, 105, 116, 97, 45, 84, 101, 107, 110, 105, 107, 0
};

#define MODULE_NAME "InfoA"

//-----------------------------------------------------------------------
// ALLOCATE MEMORY FOR STRINGS IN VARDB
//-----------------------------------------------------------------------

static char A_V_WP4000StatusText[31]  = "12345678901234567890123456789";
static char A_V_InfoTxt[61]  = "12345678901234567890123456789012345678901234567890123456789";
static char A_V_DirectionsTxt[61]  = "12345678901234567890123456789012345678901234567890123456789";
static char A_V_PitchAnglesTxt[61]  = "12345678901234567890123456789012345678901234567890123456789";
static char A_V_PowersTxt[31]  = "12345678901234567890123456789";
static char A_V_RPMsTxt[31]  = "12345678901234567890123456789";
static char A_V_SafetyChainWithGridTxt[31]  = "12345678901234567890123456789";
static char A_V_StatusLineTxt[61]  = "12345678901234567890123456789012345678901234567890123456789";
static char A_V_SystemStateTxt[31]  = "12345678901234567890123456789";
static char A_V_WindSpeedTxt[31]  = "12345678901234567890123456789";
static char A_V_INF_InfoMsgTxt[61]  = "";
static char A_P_InfoMessageTxt[121]  = "";

//-----------------------------------------------------------------------
// DEFINE LOCAL VARIABLES DEFINE LOCAL VARIABLES DEFINE LOCAL VARIABLES
//-----------------------------------------------------------------------

static struct os_db_local LocalVars[] =
{
   VAR_ELEMENT_LOCAL("V_ControlProgramsTxt",                     TYPE_STRING + sizeof(A_V_InfoTxt) - 1,  PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   A_V_InfoTxt, 0,                0,                NULL,  NOLOG_ENABLE  ),
   VAR_ELEMENT_LOCAL("V_DirectionsTxt",                          TYPE_STRING + sizeof(A_V_DirectionsTxt) - 1,  PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   A_V_DirectionsTxt, 0,                0,                NULL,  NOLOG_ENABLE  ),
   VAR_ELEMENT_LOCAL("V_PitchAnglesTxt",                         TYPE_STRING + sizeof(A_V_PitchAnglesTxt) - 1,  PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   A_V_PitchAnglesTxt, 0,                0,                NULL,  NOLOG_ENABLE  ),
   VAR_ELEMENT_LOCAL("V_PowersTxt",                              TYPE_STRING + sizeof(A_V_PowersTxt) - 1,  PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   A_V_PowersTxt, 0,                0,                NULL,  NOLOG_ENABLE  ),
   VAR_ELEMENT_LOCAL("V_RPMsTxt",                                TYPE_STRING + sizeof(A_V_RPMsTxt) - 1,  PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   A_V_RPMsTxt, 0,                0,                NULL,  NOLOG_ENABLE  ),
   VAR_ELEMENT_LOCAL("V_SafetyChainWithGridTxt",                 TYPE_STRING + sizeof(A_V_SafetyChainWithGridTxt) - 1,  PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   A_V_SafetyChainWithGridTxt, 0,                0,                NULL,  NOLOG_ENABLE  ),
   VAR_ELEMENT_LOCAL("V_StatusLineTxt",                          TYPE_STRING + sizeof(A_V_StatusLineTxt) - 1,  PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   A_V_StatusLineTxt, 0,                0,                NULL,  NOLOG_ENABLE  ),
   VAR_ELEMENT_LOCAL("V_SystemStateTxt",                         TYPE_STRING + sizeof(A_V_SystemStateTxt) - 1,  PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   A_V_SystemStateTxt, 0,                0,                NULL,  NOLOG_ENABLE  ),
   VAR_ELEMENT_LOCAL("V_WindSpeedTxt",                           TYPE_STRING + sizeof(A_V_WindSpeedTxt) - 1,  PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   A_V_WindSpeedTxt, 0,                0,                NULL,  NOLOG_ENABLE  ),
   VAR_ELEMENT_LOCAL("V_INF_InfoMsgTxt",                         TYPE_STRING + sizeof(A_V_INF_InfoMsgTxt) - 1,  PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   A_V_INF_InfoMsgTxt, 0,                0,                NULL,  NOLOG_ENABLE  ),
   VAR_ELEMENT_LOCAL("V_INF_InfoMsgShowDuration",                TYPE_U8,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   0,               0,               20,              NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_INF_AvailabilityTotal",                  TYPE_U16,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    100,     UNIT_PCT,           2,   0,               U16_MIN,         U16_MAX,         NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_INF_AvailabilityMonth",                  TYPE_U16,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    100,     UNIT_PCT,           2,   0,               U16_MIN,         U16_MAX,         NULL,  NOLOG_ENABLE),
};

//-----------------------------------------------------------------------
// DEFINE PARAMETERS        DEFINE PARAMETERS        DEFINE PARAMETERS
//-----------------------------------------------------------------------

static struct os_db_parameter ParameterVars[] =
{
   VAR_ELEMENT_PARAMETER("P_InfoMessageTxt",                         TYPE_STRING + sizeof(A_P_InfoMessageTxt) - 1,  PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_SERVICE,            SCALE_NONE,   0,       UNIT_NONE,          0,   A_P_InfoMessageTxt, 0,                0,                NULL  ),
   VAR_ELEMENT_PARAMETER("P_InfoMessageUpdateInterval",              TYPE_U32,     PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_SERVICE,            SCALE_DIV,    1000,    UNIT_SECOND,        1,   100,             100,             10000,           NULL  ),
   VAR_ELEMENT_PARAMETER("P_OperateStateUpdateInterval",             TYPE_U32,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         SCALE_DIV,    1000,    UNIT_SECOND,        1,   500,             100,             10000,           NULL  ),
   VAR_ELEMENT_PARAMETER("P_StatusUpdateInterval",                   TYPE_U32,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         SCALE_DIV,    1000,    UNIT_SECOND,        1,   1000,            100,             10000,           NULL  ),
};

//-----------------------------------------------------------------------
// DEFINE BACKUPS            DEFINE BACKUPS            DEFINE BACKUPS
//-----------------------------------------------------------------------

//----------------------------------------------------------------------------------
// DEFINE VAR ARRAYS            DEFINE VAR ARRAYS            DEFINE VAR ARRAYS
//----------------------------------------------------------------------------------
char Info_initialValues[] =
{
   62, 130, 225, 37, 202, 187, 176, 252, 154, 137, 72, 78, 173, 14, 104, 0,
   71, 225, 8, 205, 18, 195, 130, 72, 126, 155, 183, 166, 88, 14, 143, 61,
   0
};

//-----------------------------------------------------------------------
// CREATE DATABASE VARS   CREATE DATABASE VARS   CREATE DATABASE VARS
//-----------------------------------------------------------------------

static STATUS CreateVarDbVars(void)
{
   STATUS Status;
   size_t ErrorEntry;

   Status = OS_VarDB_CreateLocals(LocalVars, sizeof(LocalVars)/sizeof(LocalVars[0]), &ErrorEntry, AppLocalParameterPosition());
   if (Status != 0)
   {
      AppSystemLog(ERR_7, MODULE_NAME"CrVL: %d,%d", Status, ErrorEntry);
      return ERR_7;
   }

   Status = OS_VarDB_CreateParameters(ParameterVars, sizeof(ParameterVars)/sizeof(ParameterVars[0]), &ErrorEntry, AppExportParameterPosition());
   if (Status != 0)
   {
      AppSystemLog(ERR_7, MODULE_NAME"CrVXP: %d,%d", Status, ErrorEntry);
      return ERR_7;
   }

   return OS_SUCCESS;
}

#define CREATE_VARDB_VARS

//-----------------------------------------------------------------------
// CREATE IO VARIABLES     CREATE IO VARIABLES     CREATE IO VARIABLES
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// ALIASES                       ALIASES                       ALIASES
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// INPUT                          INPUT                          INPUT
//-----------------------------------------------------------------------

// Create local variable
#define MODUL_INPUTS
static S32 V_GridReactivePower = 0;
static S32 V_GridRealPower1Sec = 0;
static U32 V_ControllerRpm = 0;
static U8 V_ServiceModeSwitch = 0;
static U32 P_InfoMessageUpdateInterval = 0;
static U32 P_OperateStateUpdateInterval = 0;
static U32 P_StatusUpdateInterval = 0;
static U16 V_ActiveCP1CodeNo = 0;
static U16 V_ActiveCP2CodeNo = 0;
static U8 V_ActiveControlProgram1 = 0;
static U8 V_ActiveControlProgram2 = 0;
static U16 V_NacelleDirection = 0;
static S32 V_PitchAngle = 0;
static S32 V_PitchAngle1 = 0;
static S32 V_PitchAngle2 = 0;
static S32 V_PitchAngle3 = 0;
static U8 B_RemoteService = 0;
static U16 V_WindDirection30Sec = 0;
static U16 V_WindSpeed = 0;
static U8 V_INF_InfoMsgShowDuration = 0;
static char P_InfoMessageTxt[121];
static char V_ActualOperateStateTxt[31];
static char V_SafetyChainStateText[31];
static char V_SystemStatusText[31];

//-----------------------------------------------------------------------
static struct ModulInOut ModulInputs[] =
{
   {"V_GridReactivePower",                      &V_GridReactivePower,                      sizeof(V_GridReactivePower),                      },
   {"V_GridRealPower1Sec",                      &V_GridRealPower1Sec,                      sizeof(V_GridRealPower1Sec),                      },
   {"V_ControllerRpm",                          &V_ControllerRpm,                          sizeof(V_ControllerRpm),                          },
   {"V_ServiceModeSwitch",                      &V_ServiceModeSwitch,                      sizeof(V_ServiceModeSwitch),                      },
   {"P_InfoMessageTxt",                         &P_InfoMessageTxt,                         sizeof(P_InfoMessageTxt),                         },
   {"P_InfoMessageUpdateInterval",              &P_InfoMessageUpdateInterval,              sizeof(P_InfoMessageUpdateInterval),              },
   {"P_OperateStateUpdateInterval",             &P_OperateStateUpdateInterval,             sizeof(P_OperateStateUpdateInterval),             },
   {"P_StatusUpdateInterval",                   &P_StatusUpdateInterval,                   sizeof(P_StatusUpdateInterval),                   },
   {"V_ActiveCP1CodeNo",                        &V_ActiveCP1CodeNo,                        sizeof(V_ActiveCP1CodeNo),                        },
   {"V_ActiveCP2CodeNo",                        &V_ActiveCP2CodeNo,                        sizeof(V_ActiveCP2CodeNo),                        },
   {"V_ActiveControlProgram1",                  &V_ActiveControlProgram1,                  sizeof(V_ActiveControlProgram1),                  },
   {"V_ActiveControlProgram2",                  &V_ActiveControlProgram2,                  sizeof(V_ActiveControlProgram2),                  },
   {"V_ActualOperateStateTxt",                  &V_ActualOperateStateTxt,                  sizeof(V_ActualOperateStateTxt),                  },
   {"V_NacelleDirection",                       &V_NacelleDirection,                       sizeof(V_NacelleDirection),                       },
   {"V_PitchAngle",                             &V_PitchAngle,                             sizeof(V_PitchAngle),                             },
   {"V_PitchAngle1",                            &V_PitchAngle1,                            sizeof(V_PitchAngle1),                            },
   {"V_PitchAngle2",                            &V_PitchAngle2,                            sizeof(V_PitchAngle2),                            },
   {"V_PitchAngle3",                            &V_PitchAngle3,                            sizeof(V_PitchAngle3),                            },
   {"B_RemoteService",                          &B_RemoteService,                          sizeof(B_RemoteService),                          },
   {"V_SafetyChainStateText",                   &V_SafetyChainStateText,                   sizeof(V_SafetyChainStateText),                   },
   {"V_SystemStatusText",                       &V_SystemStatusText,                       sizeof(V_SystemStatusText),                       },
   {"V_WindDirection30Sec",                     &V_WindDirection30Sec,                     sizeof(V_WindDirection30Sec),                     },
   {"V_WindSpeed",                              &V_WindSpeed,                              sizeof(V_WindSpeed),                              },
   {"V_INF_InfoMsgShowDuration",                &V_INF_InfoMsgShowDuration,                sizeof(V_INF_InfoMsgShowDuration),                },
};

//-----------------------------------------------------------------------
// Check variable type
static STATUS VarsReadReturnStatus;
static type_t ReadVarType = TYPE_NONE;
static void VarsReadTypeCheck(void)
{
   (void)VarsReadReturnStatus;
   (void)ReadVarType;
   VERIFY_INPUT_REF_ID(S32,       ModulInputs[0].Name,                      ModulInputs[0].Id)
   VERIFY_INPUT_REF_ID(S32,       ModulInputs[1].Name,                      ModulInputs[1].Id)
   VERIFY_INPUT_REF_ID(U32,       ModulInputs[2].Name,                      ModulInputs[2].Id)
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[3].Name,                      ModulInputs[3].Id)
   VERIFY_INPUT_STRING_REF_ID(STRING,    ModulInputs[4].Name,                      ModulInputs[4].Id)
   VERIFY_INPUT_REF_ID(U32,       ModulInputs[5].Name,                      ModulInputs[5].Id)
   VERIFY_INPUT_REF_ID(U32,       ModulInputs[6].Name,                      ModulInputs[6].Id)
   VERIFY_INPUT_REF_ID(U32,       ModulInputs[7].Name,                      ModulInputs[7].Id)
   VERIFY_INPUT_REF_ID(U16,       ModulInputs[8].Name,                      ModulInputs[8].Id)
   VERIFY_INPUT_REF_ID(U16,       ModulInputs[9].Name,                      ModulInputs[9].Id)
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[10].Name,                     ModulInputs[10].Id)
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[11].Name,                     ModulInputs[11].Id)
   VERIFY_INPUT_STRING_REF_ID(STRING,    ModulInputs[12].Name,                     ModulInputs[12].Id)
   VERIFY_INPUT_REF_ID(U16,       ModulInputs[13].Name,                     ModulInputs[13].Id)
   VERIFY_INPUT_REF_ID(S32,       ModulInputs[14].Name,                     ModulInputs[14].Id)
   VERIFY_INPUT_REF_ID(S32,       ModulInputs[15].Name,                     ModulInputs[15].Id)
   VERIFY_INPUT_REF_ID(S32,       ModulInputs[16].Name,                     ModulInputs[16].Id)
   VERIFY_INPUT_REF_ID(S32,       ModulInputs[17].Name,                     ModulInputs[17].Id)
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[18].Name,                     ModulInputs[18].Id)
   VERIFY_INPUT_STRING_REF_ID(STRING,    ModulInputs[19].Name,                     ModulInputs[19].Id)
   VERIFY_INPUT_STRING_REF_ID(STRING,    ModulInputs[20].Name,                     ModulInputs[20].Id)
   VERIFY_INPUT_REF_ID(U16,       ModulInputs[21].Name,                     ModulInputs[21].Id)
   VERIFY_INPUT_REF_ID(U16,       ModulInputs[22].Name,                     ModulInputs[22].Id)
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[23].Name,                     ModulInputs[23].Id)
}

#undef MODUL_INPUTS
#define MODUL_INPUTS_SIZE (sizeof(ModulInputs)/sizeof(ModulInputs[0]))

//------------------------------------------------------------------------------------------
// READ/WRITE VARDB ARRAY      READ/WRITE VARDB ARRAY      READ/WRATE VARDB ARRAY
//------------------------------------------------------------------------------------------


//-----------------------------------------------------------------------
// PARAMETER                    PARAMETER                    PARAMETER
//-----------------------------------------------------------------------


//-----------------------------------------------------------------------
// READ VARS FROM VARDB    READ VARS FROM VARDB    READ VARS FROM VARDB
//-----------------------------------------------------------------------

static STATUS InputReferenceRoutine(U8 ModuleState)
{
   STATUS LocalStatus = 0;

   // Read input references
   if (ModuleState >= APP_INIT3)
   {
      // Check inputdata
      if (sizeof(ModulInputs) == 0)
      {
         AppSystemLog(ERR_4, MODULE_NAME"ModuleInputs = 0");
         return ERR_4;
      }
      // Read inputdata
      LocalStatus = OS_ReadVariables(ModulInputs, MODUL_INPUTS_SIZE);
      if (LocalStatus != 0)
      {
         AppSystemLog(ERR_4, MODULE_NAME"ReadVErr: element=%d elementpointer=0x%x", LocalStatus, &ModulInputs[LocalStatus]);
         return ERR_4;
      }
   }
   return 0;
}

#define READ_VARS

//-----------------------------------------------------------------------
// OUTPUT                         OUTPUT                         OUTPUT
//-----------------------------------------------------------------------

// Create local variable
#define MODUL_OUTPUTS
static U16 V_INF_AvailabilityTotal = 0;
static U16 V_INF_AvailabilityMonth = 0;
static char V_ControlProgramsTxt[61];
static char V_DirectionsTxt[61];
static char V_PitchAnglesTxt[61];
static char V_PowersTxt[31];
static char V_RPMsTxt[31];
static char V_SafetyChainWithGridTxt[31];
static char V_StatusLineTxt[61];
static char V_SystemStateTxt[31];
static char V_WindSpeedTxt[31];


//-----------------------------------------------------------------------
static struct ModulInOut ModulOutputs[] =
{
   {"V_ControlProgramsTxt",                     &V_ControlProgramsTxt,                     sizeof(V_ControlProgramsTxt),                     },
   {"V_DirectionsTxt",                          &V_DirectionsTxt,                          sizeof(V_DirectionsTxt),                          },
   {"V_PitchAnglesTxt",                         &V_PitchAnglesTxt,                         sizeof(V_PitchAnglesTxt),                         },
   {"V_PowersTxt",                              &V_PowersTxt,                              sizeof(V_PowersTxt),                              },
   {"V_RPMsTxt",                                &V_RPMsTxt,                                sizeof(V_RPMsTxt),                                },
   {"V_SafetyChainWithGridTxt",                 &V_SafetyChainWithGridTxt,                 sizeof(V_SafetyChainWithGridTxt),                 },
   {"V_StatusLineTxt",                          &V_StatusLineTxt,                          sizeof(V_StatusLineTxt),                          },
   {"V_SystemStateTxt",                         &V_SystemStateTxt,                         sizeof(V_SystemStateTxt),                         },
   {"V_WindSpeedTxt",                           &V_WindSpeedTxt,                           sizeof(V_WindSpeedTxt),                           },
   {"V_INF_AvailabilityTotal",                  &V_INF_AvailabilityTotal,                  sizeof(V_INF_AvailabilityTotal),                  },
   {"V_INF_AvailabilityMonth",                  &V_INF_AvailabilityMonth,                  sizeof(V_INF_AvailabilityMonth),                  },
};

//-----------------------------------------------------------------------
// Check variable type
static STATUS VarsWriteReturnStatus;
static type_t WriteVarType = TYPE_NONE;
static void VarsWriteTypeCheck(void)
{
   (void)VarsWriteReturnStatus;
   (void)WriteVarType;
   VERIFY_OUTPUT_STRING_REF_ID(STRING,     ModulOutputs[0].Name,                      ModulOutputs[0].Id,0)
   VERIFY_OUTPUT_STRING_REF_ID(STRING,     ModulOutputs[1].Name,                      ModulOutputs[1].Id,0)
   VERIFY_OUTPUT_STRING_REF_ID(STRING,     ModulOutputs[2].Name,                      ModulOutputs[2].Id,0)
   VERIFY_OUTPUT_STRING_REF_ID(STRING,     ModulOutputs[3].Name,                      ModulOutputs[3].Id, 0)
   VERIFY_OUTPUT_STRING_REF_ID(STRING,     ModulOutputs[4].Name,                      ModulOutputs[4].Id, 0)
   VERIFY_OUTPUT_STRING_REF_ID(STRING,     ModulOutputs[5].Name,                      ModulOutputs[5].Id, 0)
   VERIFY_OUTPUT_STRING_REF_ID(STRING,     ModulOutputs[6].Name,                      ModulOutputs[6].Id,0)
   VERIFY_OUTPUT_STRING_REF_ID(STRING,     ModulOutputs[7].Name,                      ModulOutputs[7].Id, 0)
   VERIFY_OUTPUT_STRING_REF_ID(STRING,     ModulOutputs[8].Name,                      ModulOutputs[8].Id, 0)
   VERIFY_OUTPUT_REF_ID(U16,       ModulOutputs[9].Name,                     ModulOutputs[9].Id,                       0)
   VERIFY_OUTPUT_REF_ID(U16,       ModulOutputs[10].Name,                    ModulOutputs[10].Id,                      0)
}

#undef MODUL_OUTPUTS
#define MODUL_OUTPUTS_SIZE (sizeof(ModulOutputs)/sizeof(ModulOutputs[0]))

//-----------------------------------------------------------------------
// WRITE VARS TO VARDB     WRITE VARS TO VARDB     WRITE VARS TO VARDB
//-----------------------------------------------------------------------

static STATUS InitOutputVars(void)
{
   STATUS LocalStatus;
   // Read outputdata
   LocalStatus = OS_ReadVariables(ModulOutputs, MODUL_OUTPUTS_SIZE);
   if (LocalStatus != 0)
   {
      AppSystemLog(ERR_4, MODULE_NAME"InitErr: element=%d elementpointer=0x%x", LocalStatus, &ModulOutputs[LocalStatus]);
      return ERR_4;
   }
   return OS_SUCCESS;
}
static STATUS OutputReferenceRoutine(U8 ModuleState)
{
   STATUS LocalStatus = 0;
   // Write Outputdata
   LocalStatus = OS_WriteVariablesConditional(ModulOutputs, MODUL_OUTPUTS_SIZE);
   if (LocalStatus != 0)
   {
      AppSystemLog(ERR_5, MODULE_NAME"WriteVErr: element=%d elementpointer=0x%x", LocalStatus, &ModulOutputs[LocalStatus]);
      return ERR_5;
   }
   return 0;
}

#define WRITE_VARS

//-----------------------------------------------------------------------
// VERIFY VARIABLES CREATION                 VERIFY VARIABLES CREATION
//-----------------------------------------------------------------------

static STATUS LocalIoCheck(void)
{
   // Check if input variables exist.
   STATUS LocalStatus;

   LocalStatus = OS_DoesVariablesExist(ModulInputs, MODUL_INPUTS_SIZE);
   if (LocalStatus != 0)
   {
      AppSystemLog(ERR_1, MODULE_NAME"InputErr: %d", LocalStatus);
      AppSystemLog(ERR_1, "Name: %s", ModulInputs[LocalStatus-1].Name);
      return ERR_1;
   }
   (void)VarsReadTypeCheck();

   LocalStatus = OS_DoesVariablesExist(ModulOutputs, MODUL_OUTPUTS_SIZE);
   if (LocalStatus != 0)
   {
      AppSystemLog(ERR_2, MODULE_NAME"OutputErr: %d", LocalStatus);
      AppSystemLog(ERR_2, "Name: %s", ModulOutputs[LocalStatus-1].Name);
      return ERR_2;
   }
   (void)VarsWriteTypeCheck();

   return OS_SUCCESS;
}

#define VERIFY_VARIABLES

//-----------------------------------------------------------------------
// ALLOCATE MEMORY FOR SUMMATIONS        ALLOCATE MEMORY FOR SUMMATIONS
//-----------------------------------------------------------------------


//-----------------------------------------------------------------------
// SUMMATIONS                  SUMMATIONS                  SUMMATIONS
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// DEFINE MENUS               DEFINE MENUS               DEFINE MENUS
//-----------------------------------------------------------------------



// Menu line and link to local menu
//-----------------------------------------------------------------------
static struct line_struct M_ObjMainLinkToLocalMenu[] =
{
   MENU_ELEMENT_LINE_LINK("Info",                              PASSWORD_LEVEL_END_CUSTOMER,        "M_ObjMain",                        "G_Info"),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_ObjMainMenu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_ObjMain",                        PASSWORD_LEVEL_END_CUSTOMER),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_ObjMainMenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("INFO",                              PASSWORD_LEVEL_END_CUSTOMER,        "M_"APP_ID"AppMain",                "G_"APP_ID"App"),
   MENU_ELEMENT_LINE_VARRO("System State",                     PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_SystemStateTxt",                           LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Control Programs",                 PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_ControlProgramsTxt",                       LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Safety Chain / Grid",              PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_SafetyChainWithGridTxt",                   LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Direction Nacelle / Wind / Relative", PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_DirectionsTxt",                            LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Wind Speed",                       PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_WindSpeedTxt",                             LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Pitch Angle 1 / 2 / 3",            PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_PitchAnglesTxt",                           LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Rotor speed",                      PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_RPMsTxt",                                  LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Power Active / Reactive",          PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_PowersTxt",                                LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Month availability",               PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_INF_AvailabilityMonth",                    LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Total availability",               PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_INF_AvailabilityTotal",                    LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_LINK("Parameter",                         PASSWORD_LEVEL_END_CUSTOMER,        "M_Parameter25",                    "G_Info"),
   MENU_ELEMENT_LINE_LINK("Service",                           PASSWORD_LEVEL_SERVICE,             "M_Service29",                      "G_Info"),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_Parameter25Menu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_Parameter25",                    PASSWORD_LEVEL_END_CUSTOMER),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_Parameter25MenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("PARAMETER",                         PASSWORD_LEVEL_END_CUSTOMER,        "M_ObjMain",                        "G_Info"),
   MENU_ELEMENT_LINE_VARRW("Status Update Interval",           PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_StatusUpdateInterval",                     LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Operate State Scroll Interval",    PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_OperateStateUpdateInterval",               LINE_FORMAT_NONE),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_Service29Menu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_Service29",                      PASSWORD_LEVEL_SERVICE),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_Service29MenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("SERVICE",                           PASSWORD_LEVEL_SERVICE,             "M_ObjMain",                        "G_Info"),
   MENU_ELEMENT_LINE_VARRW("Info Message",                     PASSWORD_LEVEL_SERVICE,             (char*)"P_InfoMessageTxt",                           LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Info Message Scroll Interval",     PASSWORD_LEVEL_SERVICE,             (char*)"P_InfoMessageUpdateInterval",                LINE_FORMAT_NONE),
};
// Creating parameters for multiplexed categories
//-----------------------------------------------------------------------
static struct multiplexed_info_struct M_ObjMainMultiplexedCategoriesParameters[] =
{
0};

//-----------------------------------------------------------------------
// CREATE MENUS               CREATE MENUS               CREATE MENUS
//-----------------------------------------------------------------------

// Memory reservation
//-----------------------------------------------------------------------
static struct menu_group_struct ObjGroup[1];

// Creating the menus
//-----------------------------------------------------------------------
STATUS InfoMenuAppInit(U8 ModuleState, OS_MEMORY_POOL* pPool)
{
   STATUS Status;

   if (ModuleState == APP_INIT1)
   {
      /* Create application group */
      Status = OS_CreateMenuGroup(ObjGroup, M_ObjMainLinkToLocalMenu[0].LinkGroup);
      STATUS_LINE_VAR_RETURN_VALUE(Status);
   }

   Status = CreateAndInitializeMenu(ModuleState,
                                    M_ObjMainMenuLines[0].LinkGroup,
                                    M_ObjMainMenuLines[0].LinkName,
                                    ELEMENT(M_ObjMainLinkToLocalMenu),
                                    M_ObjMainLinkToLocalMenu[0].LinkGroup,
                                    ELEMENT(M_ObjMainMenu),
                                    M_ObjMainLinkToLocalMenu[0].LinkName,
                                    ELEMENT(M_ObjMainMenuLines),
                                    pPool,
                                    M_ObjMainMultiplexedCategoriesParameters);
   STATUS_LINE_VAR_RETURN_VALUE(Status);

   Status = CreateAndInitializeMenu(ModuleState,
                                    M_Parameter25MenuLines[0].LinkGroup,
                                    M_Parameter25MenuLines[0].LinkName,
                                    NULL,
                                    0,
                                    M_ObjMainMenuLines[11].LinkGroup,
                                    ELEMENT(M_Parameter25Menu),
                                    M_ObjMainMenuLines[11].LinkName,
                                    ELEMENT(M_Parameter25MenuLines),
                                    pPool,
                                    M_ObjMainMultiplexedCategoriesParameters);
   STATUS_LINE_VAR_RETURN_VALUE(Status);

   Status = CreateAndInitializeMenu(ModuleState,
                                    M_Service29MenuLines[0].LinkGroup,
                                    M_Service29MenuLines[0].LinkName,
                                    NULL,
                                    0,
                                    M_ObjMainMenuLines[12].LinkGroup,
                                    ELEMENT(M_Service29Menu),
                                    M_ObjMainMenuLines[12].LinkName,
                                    ELEMENT(M_Service29MenuLines),
                                    pPool,
                                    M_ObjMainMultiplexedCategoriesParameters);
   STATUS_LINE_VAR_RETURN_VALUE(Status);

   return OS_SUCCESS;
}

#define CREATE_MENU

//-----------------------------------------------------------------------
//               BUTTONS FUNCTIONS FORWARD DECLARATIONS
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// BUTTONS                       BUTTONS                      BUTTONS
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
//             SET/RESET FUNCTIONS FORWARD DECLARATIONS
//-----------------------------------------------------------------------
//-----------------------------------------------------------------------
// STATUSCODES                 STATUSCODES                 STATUSCODES
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// MODIFIABLE                  MODIFIABLE                   MODIFIABLE
//-----------------------------------------------------------------------

extern const char InfoAppGroupName[];
extern const char InfoAppMenuName[];

static void Init_Structures_From_Conf_File(void)
{
   M_ObjMainMenuLines[0].LinkName = (char*)InfoAppMenuName;
   M_ObjMainMenuLines[0].LinkGroup = (char*)InfoAppGroupName;
}

//-----------------------------------------------------------------------
// AUTOGENERATED END        AUTOGENERATED END        AUTOGENERATED END
//-----------------------------------------------------------------------
//}

#undef AUTOGENERATED_PART

//-----------------------------------------------------------------------
// USER DEFINITIONS         USER DEFINITIONS         USER DEFINITIONS
//-----------------------------------------------------------------------

#define SYSMSG_MAXDURATION 20       // system message displaying max duration in [s]
static S16 SysMsg_Timer;            // counts the delay when displaying message on Status Line
BOOL SysMsgShow = false;            // TRUE when system message is being displayed on status line

static  varid_t V_WP4000StatusText_ID = 0;      //Contains ID of status line variable
AVAIL* Availability;


static struct StandardTimerVarStruct StatusUpdateTimer =            //Timer used to update status line and menu lines
{
    0,                                // Timer value [ms]
    &P_StatusUpdateInterval,          // TimeMax value [ms]
    TIMER_100MS,                      // Internal variable, always set to 0
    TIMER_STOP,                       // TIMER_DOWN / TIMER_STOP / TIMER_UP
    0                                 // Standard timer called flag.
};

static struct StandardTimerVarStruct InfoMessageUpdateTimer =       //Timer used to scroll info message
{
    0,                                // Timer value [ms]
    &P_InfoMessageUpdateInterval,     // TimeMax value [ms]
    TIMER_100MS,                      // Internal variable, always set to 0
    TIMER_STOP,                       // TIMER_DOWN / TIMER_STOP / TIMER_UP
    0                                 // Standard timer called flag.
};

static struct StandardTimerVarStruct OperateStateUpdateTimer =      //Timer used to scroll operate state
{
    0,                                // Timer value [ms]
    &P_OperateStateUpdateInterval,    // TimeMax value [ms]
    TIMER_100MS,                      // Internal variable, always set to 0
    TIMER_STOP,                       // TIMER_DOWN / TIMER_STOP / TIMER_UP
    0                                 // Standard timer called flag.
};

//-----------------------------------------------------------------------
// SET/RESET FUNCTIONS    SET/RESET FUNCTIONS    SET/RESET FUNCTIONS
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// DRIVER FUNCTION         DRIVER FUNCTION         DRIVER FUNCTION
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// INIT                   INIT                     INIT
//-----------------------------------------------------------------------

static STATUS Initialize()
{
    STATUS LocalStatus;

    LocalStatus = OS_VarDB_GetVariableID("V_WP4000StatusText", &V_WP4000StatusText_ID);     //Reads ID of status line variable
    if (LocalStatus != OS_SUCCESS) { return LocalStatus; }

    StatusUpdateTimer.TimerValue = P_StatusUpdateInterval;                  //Sets timers values to TimeMax to update
    OperateStateUpdateTimer.TimerValue = P_OperateStateUpdateInterval;      //menu lines and status line immediately

    struct os_db_availability* pointer;
    // get pointer(ID) to availability variable
    LocalStatus = OS_VarDB_GetVariableID("AV_Availability", &pointer);
    if (LocalStatus != OS_SUCCESS) { return LocalStatus; }
    // get pointer to availability structure
    Availability = pointer->c.Value.avail;

    return OS_SUCCESS;
}

//-----------------------------------------------------------------------
// CONTROL                CONTROL                 CONTROL
//-----------------------------------------------------------------------

// Show message on status line
void InfoMessage(char* message/*message string to display*/, U8 duration/*duration in [s] to display message*/)
{
    OS_VarDB_UpdateVariableByName("V_INF_InfoMsgTxt", message, strlen(message) + 1);
    OS_VarDB_UpdateVariableByName("V_INF_InfoMsgShowDuration", &duration, sizeof(duration));
}


#define PERCENT_SIGN                0x25            //Percent sign used in status line and menu lines. Used like single symbol
#define STATUS_LINE_LENGTH          42              //Number of meaning characters in status line. 42 characters chosen due to characters count WP4051 can display
#define STATUS_LINE_TAIL_LENGTH     13              //Number of meaning characters in the end of status line for operate state

#define RIGHTWARDS                  1
#define LEFTWARDS                   -1

const char DEGREE_SIGN[3] = {0xC2, 0xB0, '\0'}; //Degree sign used in status line and menu lines. Used like string. NOTE: has two meaning characters

static STATUS LocalCtrl(void)
{
    static  U8      LongMessageState = 0;
    STATUS  LocalStatus;

    // Refresh availability data
    V_INF_AvailabilityTotal = Availability->Live.Total.Result.Percentage;
    V_INF_AvailabilityMonth = Availability->Live.ThisMonth.Result.Percentage;


    //Get local copy of Info Message and ensure that it will have EOL symbol
    char InfoMessageTxtLocal[sizeof(P_InfoMessageTxt)];
    strncpy(InfoMessageTxtLocal, P_InfoMessageTxt, sizeof(P_InfoMessageTxt) - 1);
    InfoMessageTxtLocal[sizeof(P_InfoMessageTxt) - 1] = '\0';


    S16 RelativeWindDirection = ((S16)V_WindDirection30Sec) - V_NacelleDirection;   //Relative Wind Direction

    if (RelativeWindDirection > 1800)                                                   //Fit Relative Wind Direction in -179.9...180.0 degrees
    {
        RelativeWindDirection -= 3600;
    }
    else
    {
        if (RelativeWindDirection < -1799)
        {
            RelativeWindDirection += 3600;
        }
    }
    //-----------------------------------------------------------------------
    // MENU                        MENU                       MENU
    //-----------------------------------------------------------------------

    StartTimer(&StatusUpdateTimer);
    S8 StatusTimerOut = StandardTimer(&StatusUpdateTimer);  //Separate variable to have possibility to use this timer in menu lines and status line

    if (StatusTimerOut)                                     //Updates menu lines every P_StatusUpdateInterval ms. Used the same timer as for status line
    {
        //--------------------------------------------------------------------
        //System State
        if (!V_ServiceModeSwitch)                           //If service button pressed
        {
            //Prints "LOCAL SERVICE"
            snprintf(V_SystemStateTxt,
                     sizeof(V_SystemStateTxt),
                     "%s",
                     "LOCAL SERVICE"
                    );
        }
        else
        {
            if (B_RemoteService)                            //If service requested by applet
            {
                //Prints "REMOTE SERVICE"
                snprintf(V_SystemStateTxt,
                         sizeof(V_SystemStateTxt),
                         "%s",
                         "REMOTE SERVICE"
                        );
            }
            else                                            //If no service requested
            {
                //Prints system state
                snprintf(V_SystemStateTxt,
                         sizeof(V_SystemStateTxt),
                         "%s",
                         V_SystemStatusText
                        );
            }
        }
        //--------------------------------------------------------------------
        //Control Programs
        U16 ActiveCP1CodeNoTemp;
        if (V_ActiveCP1CodeNo == 65535)
        {
            ActiveCP1CodeNoTemp = 0;                        //Set brake status code No to 0 if 65535
        }
        else
        {
            ActiveCP1CodeNoTemp = V_ActiveCP1CodeNo;        //Else use actual brake status code No
        }

        U16 ActiveCP2CodeNoTemp;
        if (V_ActiveCP2CodeNo == 65535)
        {
            ActiveCP2CodeNoTemp = 0;                        //Set yaw status code No to 0 if 65535
        }
        else
        {
            ActiveCP2CodeNoTemp = V_ActiveCP2CodeNo;        //Else use actual yaw status code No
        }


        snprintf(V_ControlProgramsTxt,                    //Prints active brake program and caused status code and
                 sizeof(V_ControlProgramsTxt),           //active yaw program and caused status code
                 "BP: %u, SC: %u;   YP: %u, SC: %u",
                 V_ActiveControlProgram1,
                 ActiveCP1CodeNoTemp,
                 V_ActiveControlProgram2,
                 ActiveCP2CodeNoTemp
                );
        //--------------------------------------------------------------------
        //Safety Chain / Grid
        if (GridErrorActive())
        {
            snprintf(V_SafetyChainWithGridTxt,                               //Prints Safety Chain state
                     sizeof(V_SafetyChainWithGridTxt),                       //and Grid error
                     "%s;   %s",
                     V_SafetyChainStateText,
                     "Grid Error"
                    );
        }
        else
        {
            snprintf(V_SafetyChainWithGridTxt,                               //Prints Safety Chain state
                     sizeof(V_SafetyChainWithGridTxt),                       //and Grid OK
                     "%s;   %s",
                     V_SafetyChainStateText,
                     "Grid OK"
                    );
        }
        //--------------------------------------------------------------------
        //Nacelle / Wind / Diff
        snprintf(V_DirectionsTxt,                             //Prints nacelle direction, 30 seconds averaged wind direction and difference
                 sizeof(V_DirectionsTxt),                            //between this directions with one number after decimal point and sign for difference
                 "%u.%u%s / %u.%u%s / %c%u.%u%s",
                 V_NacelleDirection / 10,
                 V_NacelleDirection % 10,
                 DEGREE_SIGN,
                 V_WindDirection30Sec / 10,
                 V_WindDirection30Sec % 10,
                 DEGREE_SIGN,
                 (RelativeWindDirection >= 0) ? ' ' : '-',
                 (RelativeWindDirection >= 0) ? RelativeWindDirection / 10 : (RelativeWindDirection * -1) / 10,
                 (RelativeWindDirection >= 0) ? RelativeWindDirection % 10 : (RelativeWindDirection * -1) % 10,
                 DEGREE_SIGN
                );
        //--------------------------------------------------------------------
        //Wind Speed
        snprintf(V_WindSpeedTxt,                                  //Prints current wind speed with one number after decimal point
                 sizeof(V_WindSpeedTxt),
                 "%u.%u m/s",
                 V_WindSpeed / 100,
                 (V_WindSpeed % 100) / 10
                );
        //--------------------------------------------------------------------
        //Blade 1 / Blade 2 / Blade 3 Angles
        snprintf(V_PitchAnglesTxt,                            //Prints actual pitch angle for each blade with one number after decimal point and sign
                 sizeof(V_PitchAnglesTxt),
                 "%c%u.%u%s / %c%u.%u%s / %c%u.%u%s",
                 (V_PitchAngle1 >= 0) ? ' ' : '-',
                 (V_PitchAngle1 >= 0) ? V_PitchAngle1 / 100 : (V_PitchAngle1 * -1) / 100,
                 (V_PitchAngle1 >= 0) ? (V_PitchAngle1 % 100) / 10 : ((V_PitchAngle1 * -1) % 100) / 10,
                 DEGREE_SIGN,
                 (V_PitchAngle2 >= 0) ? ' ' : '-',
                 (V_PitchAngle2 >= 0) ? V_PitchAngle2 / 100 : (V_PitchAngle2 * -1) / 100,
                 (V_PitchAngle2 >= 0) ? (V_PitchAngle2 % 100) / 10 : ((V_PitchAngle2 * -1) % 100) / 10,
                 DEGREE_SIGN,
                 (V_PitchAngle3 >= 0) ? ' ' : '-',
                 (V_PitchAngle3 >= 0) ? V_PitchAngle3 / 100 : (V_PitchAngle3 * -1) / 100,
                 (V_PitchAngle3 >= 0) ? (V_PitchAngle3 % 100) / 10 : ((V_PitchAngle3 * -1) % 100) / 10,
                 DEGREE_SIGN
                );
        //--------------------------------------------------------------------
        //Rotor rpm
        snprintf(V_RPMsTxt,                                       //Prints actual rotor speed with two numbers after decimal point
                 sizeof(V_RPMsTxt),
                 "%u.%u rpm",
                 V_ControllerRpm / 1000,
                 (V_ControllerRpm % 1000) / 10
                );
        //--------------------------------------------------------------------
        //Real Power / Reactive Power
        snprintf(V_PowersTxt,                                 //Prints actual active and reactive power with one number after decimal point and sign
                 sizeof(V_PowersTxt),
                 "%c%u.%u kW / %c%u.%u kVAr",
                 (V_GridRealPower1Sec >= 0) ? ' ' : '-',
                 (V_GridRealPower1Sec >= 0) ? V_GridRealPower1Sec / 1000 : (V_GridRealPower1Sec * -1) / 1000,
                 (V_GridRealPower1Sec >= 0) ? (V_GridRealPower1Sec % 1000) / 100 : ((V_GridRealPower1Sec * -1) % 1000) / 100,
                 (V_GridReactivePower >= 0) ? ' ' : '-',
                 (V_GridReactivePower >= 0) ? V_GridReactivePower / 1000 : (V_GridReactivePower * -1) / 1000,
                 (V_GridReactivePower >= 0) ? (V_GridReactivePower % 1000) / 100 : ((V_GridReactivePower * -1) % 1000) / 100
                );
        //--------------------------------------------------------------------

        ResetTimer(&StatusUpdateTimer);
    }
    //-----------------------------------------------------------------------
    // STATUS LINE TEXT        STATUS LINE TEXT           STATUS LINE TEXT
    //-----------------------------------------------------------------------



    if (0 != V_WP4000StatusText_ID)                          //Executes if got ID of status line variable
    {

        size_t InfoMessageLength = strlen(InfoMessageTxtLocal); //Info message length

        static  char*   PointerToInfoMessage1 = NULL;   //Two pointers used in
        static  char*   PointerToInfoMessage2 = NULL;   //info message scrolling
        static  char    PointerToSpaces[] = "                                                            ";

        static  U8      LongModifier0 = STATUS_LINE_LENGTH;         //Modifier to control spaces length in front of message in first scroll round
        static  U8      LongModifier1 = 0;                          //Modifier to control message length pointed by PointerToInfoMessage1
        static  U8      LongModifier2 = 0;                          //Modifier to control spaces between end of message and begining of new one
        static  U8      LongModifier3 = 0;                          //Modifier to control message length pointed by PointerToInfoMessage2


        // print info message in status line
        //----------------------------------------
        if (V_INF_InfoMsgShowDuration && !SysMsgShow)
        {
            SysMsgShow = true;
            if (V_INF_InfoMsgShowDuration <= SYSMSG_MAXDURATION)
            {
                SysMsg_Timer = V_INF_InfoMsgShowDuration * 1000;    // load timer value in [ms]
            }
            else
            {
                SysMsg_Timer = SYSMSG_MAXDURATION * 1000;
            }
            V_INF_InfoMsgShowDuration = 0;
            OS_VarDB_UpdateVariableByName("V_INF_InfoMsgShowDuration", &V_INF_InfoMsgShowDuration, sizeof(V_INF_InfoMsgShowDuration));

            // read system message text from variable database
            char SysMsgTxt[60];
            time_t TimeStamp;
            if (OS_VarDB_ReadVariableByName("V_INF_InfoMsgTxt", &SysMsgTxt, sizeof(SysMsgTxt), &TimeStamp) == OS_SUCCESS)
            {
                // write system message text to status line
                if (OS_VarDB_UpdateVariable(V_WP4000StatusText_ID, &SysMsgTxt, sizeof(SysMsgTxt)) == OS_SUCCESS) { return OS_SUCCESS; }
            }
        }
        else if (SysMsgShow)    // count system message text displaying duration
        {
            SysMsg_Timer -= SCANTIME_INFO;
            if (SysMsg_Timer <= 0)
            {
                SysMsgShow = false;
            }

            // new message request received
            if (V_INF_InfoMsgShowDuration)
            {
                SysMsgShow = false;
            }

            return OS_SUCCESS;
        }
        //----------------------------------------


        if (InfoMessageLength > STATUS_LINE_LENGTH)         //Info message is longer than status line can display
        {
            StartTimer(&InfoMessageUpdateTimer);
            if (StandardTimer(&InfoMessageUpdateTimer))     //Scroll message every P_InfoMessageUpdateInterval ms
            {
                if (LongMessageState != 1)                  //Service flag to reset pointer and modifiers when leave this state
                {
                    LongMessageState = 1;

                    PointerToInfoMessage1 = InfoMessageTxtLocal;
                    PointerToInfoMessage2 = InfoMessageTxtLocal;

                    LongModifier0 = STATUS_LINE_LENGTH;
                    LongModifier1 = 0;
                    LongModifier2 = 0;
                    LongModifier3 = 0;
                }

                snprintf(V_StatusLineTxt,
                         sizeof(V_StatusLineTxt),
                         "%.*s%.*s%.*s%.*s",
                         LongModifier0,
                         PointerToSpaces,
                         LongModifier1,
                         PointerToInfoMessage1,
                         LongModifier2,
                         PointerToSpaces,
                         LongModifier3,
                         PointerToInfoMessage2
                        );

                if (LongModifier1 < STATUS_LINE_LENGTH)     //Message is moving from right to left first time
                {
                    if (LongModifier0 > 0)
                    {
                        --LongModifier0;                    //Decrease amount of spaces
                    }

                    ++LongModifier1;                        //Increase amount of viewed characters
                }
                else                                        //Message occupies whole line from first character
                {
                    if (PointerToInfoMessage1 - InfoMessageTxtLocal < InfoMessageLength - STATUS_LINE_LENGTH)
                    {
                        ++PointerToInfoMessage1;            //Scroll message while last character occured
                    }
                    else
                    {
                        if (PointerToInfoMessage1 - InfoMessageTxtLocal < InfoMessageLength - STATUS_LINE_LENGTH + MESSAGE_SPACES_LENGTH - 1)
                        {
                            ++PointerToInfoMessage1;        //Scroll message and fill with spaces end of line
                            ++LongModifier2;                //till all the spaces viewed (MESSAGE_SPACES_LENGTH count)
                        }
                        else
                        {
                            if (PointerToInfoMessage1 - InfoMessageTxtLocal < InfoMessageLength)
                            {
                                ++PointerToInfoMessage1;    //Scroll message and spaces and fill end of line with begining of message
                                ++LongModifier3;            //till spaces take position in the beginning of line
                            }
                            else
                            {
                                if (LongModifier2 > 0)
                                {
                                    --LongModifier2;        //Scroll spaces and message
                                    ++LongModifier3;        //till all spaces disappear
                                }
                                else
                                {
                                    PointerToInfoMessage1 = InfoMessageTxtLocal;
                                    LongModifier2 = 0;      //Reset pointer and modifiers and continue from the place above
                                    LongModifier3 = 0;      //when message occupies whole line from first character
                                }
                            }
                        }
                    }
                }

                ResetTimer(&InfoMessageUpdateTimer);
            }
        }
        else
        {
            // print service info message
            if (InfoMessageLength > 0)                      //Message can fit in line fully
            {
                if (LongMessageState == 1)                  //Reset pointer and modifiers if message was too long
                {
                    LongMessageState = 0;

                    PointerToInfoMessage1 = InfoMessageTxtLocal;

                    LongModifier0 = STATUS_LINE_LENGTH;
                    LongModifier1 = 0;
                    LongModifier2 = 0;
                    LongModifier3 = 0;
                }

                snprintf(V_StatusLineTxt,                 //Message is printing in the begining of line
                         sizeof(V_StatusLineTxt),
                         "%s",
                         InfoMessageTxtLocal
                        );
            }
            else                                            //Info message is empty. Print standard status line
            {
                if (LongMessageState == 1)                  //Reset pointer and modifiers if message was too long
                {
                    LongMessageState = 0;

                    PointerToInfoMessage1 = InfoMessageTxtLocal;

                    LongModifier0 = STATUS_LINE_LENGTH;
                    LongModifier1 = 0;
                    LongModifier2 = 0;
                    LongModifier3 = 0;
                }

                /*
                char Yaw = YAW_STOPPED_SYMBOL;              //Set yaw to STOPPED by default

                if (V_YAW_State == YAW_RUN_CW)
                {
                    Yaw = YAW_CW_SYMBOL;                    //Set yaw to CW if respective DO is high
                }

                if (V_YAW_State == YAW_RUN_CCW)
                {
                    Yaw = YAW_CCW_SYMBOL;                   //Set yaw to CCW if respective DO is high
                }
                */

                //String where operate state will be placed
                static  char    OperationStateTxt[STATUS_LINE_TAIL_LENGTH + 1] = "1234567890123";

                //String where old operate state will be placed to track changes
                static  char    ActualOperateStateTxtOld[30];

                //Pointer to operate state
                static  char*   PointerToActualOperateState1 = V_ActualOperateStateTxt;
                static  char*   PointerToActualOperateState2 = V_ActualOperateStateTxt;
                static  char        PointerToSpaces[] = "                              ";

                static  U8      Modifier0 = STATUS_LINE_TAIL_LENGTH;
                static  U8      Modifier1 = 0;
                static  U8      Modifier2 = 0;
                static  U8      Modifier3 = 0;

                //Operate state length
                size_t ActualOperateStateLength = strlen(V_ActualOperateStateTxt);

                StartTimer(&OperateStateUpdateTimer);
                if (StandardTimer(&OperateStateUpdateTimer))//Scroll operate state every P_OperateStateUpdateInterval ms
                {
                    if (strcmp(V_ActualOperateStateTxt, ActualOperateStateTxtOld))  //Check if operate state changed and
                    {
                        //reset pointer and modifiers if yes
                        strcpy(ActualOperateStateTxtOld, V_ActualOperateStateTxt);
                        PointerToActualOperateState1 = V_ActualOperateStateTxt;
                        Modifier0 = STATUS_LINE_TAIL_LENGTH;
                        Modifier1 = 0;
                        Modifier2 = 0;
                        Modifier3 = 0;
                    }

                    if (ActualOperateStateLength > STATUS_LINE_TAIL_LENGTH)//If operate state is too long
                    {
                        snprintf(OperationStateTxt,
                                 sizeof(OperationStateTxt),
                                 "%.*s%.*s%.*s%.*s",
                                 Modifier0,
                                 PointerToSpaces,
                                 Modifier1,
                                 PointerToActualOperateState1,
                                 Modifier2,
                                 PointerToSpaces,
                                 Modifier3,
                                 PointerToActualOperateState2
                                );

                        if (Modifier1 < STATUS_LINE_TAIL_LENGTH)        //Operate state is moving from right to left first time
                        {
                            if (Modifier0 > 0)
                            {
                                --Modifier0;                    //Decrease amount of spaces
                            }

                            ++Modifier1;                        //Increase amount of viewed characters
                        }
                        else                                        //Operate state occupies whole line from first character
                        {
                            if (PointerToActualOperateState1 - V_ActualOperateStateTxt < ActualOperateStateLength - STATUS_LINE_TAIL_LENGTH)
                            {
                                ++PointerToActualOperateState1;         //Scroll Operate state while last character occured
                            }
                            else
                            {
                                if (PointerToActualOperateState1 - V_ActualOperateStateTxt < ActualOperateStateLength - STATUS_LINE_TAIL_LENGTH + OPERATE_SPACES_LENGTH - 1)
                                {
                                    ++PointerToActualOperateState1;     //Scroll Operate state and fill with spaces end of line
                                    ++Modifier2;                //till all the spaces viewed (OPERATE_SPACES_LENGTH count)
                                }
                                else
                                {
                                    if (PointerToActualOperateState1 - V_ActualOperateStateTxt < ActualOperateStateLength)
                                    {
                                        ++PointerToActualOperateState1; //Scroll Operate state and spaces and fill end of line with begining of Operate state
                                        ++Modifier3;            //till spaces take position in the begining of line
                                    }
                                    else
                                    {
                                        if (Modifier2 > 0)
                                        {
                                            --Modifier2;        //Scroll spaces and Operate state
                                            ++Modifier3;        //till all spaces disappear
                                        }
                                        else
                                        {
                                            PointerToActualOperateState1 = V_ActualOperateStateTxt;
                                            Modifier2 = 0;      //Reset pointer and modifiers and continue from the place above
                                            Modifier3 = 0;      //when Operate state occupies whole line from first character
                                        }
                                    }
                                }
                            }
                        }
                    }
                    else                                            //If operate state can be printed fully
                    {
                        strcpy(OperationStateTxt, V_ActualOperateStateTxt);
                    }

                    ResetTimer(&OperateStateUpdateTimer);
                }

                //Variables which will have information for standard status line
                static S16 SL_YawDiff               = 0;            //Difference between nacelle direction and 30 second average wind direction
                static U16 SL_WindSpeedOnes         = 0;            //30 second average wind speed, before decimal point
                static U16 SL_WindSpeedTenths       = 0;            //30 second average wind speed, after decimal point
                static S16 SL_PitchAngle            = 0;            //Average pitch angle, before decimal point
                static U16 SL_PitchAngleTenths      = 0;            //Average pitch angle, after decimal point
                static char SL_PitchAngleTxt[9]     = "--,-\0";     //Average pitch angle text
                static U32 SL_RotorRpmOnes          = 0;            //Rotor rotational speed, before decimal point
                static U32 SL_RotorRpmTenths        = 0;            //Rotor rotational speed, after decimal point
                static S32 SL_GridRealPower         = 0;            //Actual power
                static char SL_StatusTxt[6]         = "OK\0";       //Number of active status codes or OK

                if (StatusTimerOut)                                 //Update status line every P_StatusUpdateInterval ms. Used the same timer as for menu lines
                {
                    SL_YawDiff = RelativeWindDirection / 10;                                    //Division by 10 because of SCALE_DIV 10
                    SL_WindSpeedOnes = V_WindSpeed / 100;                                       //Value before decimal point. Division by 100 because of SCALE_DIV 100
                    SL_WindSpeedTenths = (V_WindSpeed % 100) / 10;                              //Value after decimal point. Division by 10 to have only one number after decimal point
                    if (V_PitchAngle < 0) { snprintf(SL_PitchAngleTxt, sizeof(SL_PitchAngleTxt), "-%d.%u%s", (V_PitchAngle / 100), ((abs(V_PitchAngle) % 100) / 10), DEGREE_SIGN); }
                    else { snprintf(SL_PitchAngleTxt, sizeof(SL_PitchAngleTxt), "%2d.%u%s", (V_PitchAngle / 100), ((abs(V_PitchAngle) % 100) / 10), DEGREE_SIGN); }
                    SL_RotorRpmOnes = V_ControllerRpm / 1000;                                   //Value before decimal point. Division by 1000 because of SCALE_DIV 1000
                    SL_RotorRpmTenths = (V_ControllerRpm % 1000) / 10;                         //Value after decimal point. Division by 10 to have only two numbers after decimal point
                    SL_GridRealPower = V_GridRealPower1Sec / 1000;                              //No rounding, simple whole value. Division by 1000 because of SCALE_DIV 1000
                    U16 Scount = OS_NoOfActiveStatusCodes();
                    if (Scount == 0) { sprintf(SL_StatusTxt, "OK"); }
                    else { snprintf(SL_StatusTxt, sizeof(SL_StatusTxt), "S:%u", Scount); }
                }

                snprintf(V_StatusLineTxt,                                                 //Prints status line. Not used by timer to have possibility
                         sizeof(V_StatusLineTxt),                                        //to update operate state with bigger frequency
                         "%3d%s%c%3d%s%c%2u.%um/s%c%s%c%2u.%urpm%c%4dkW%c%s%c%s",
                         SL_YawDiff,
                         DEGREE_SIGN,
                         SYMBOLS_SEPARATOR,
                         V_NacelleDirection / 10,
                         DEGREE_SIGN,
                         SYMBOLS_SEPARATOR,
                         //Yaw,
                         //SYMBOLS_SEPARATOR,
                         SL_WindSpeedOnes,
                         SL_WindSpeedTenths,
                         SYMBOLS_SEPARATOR,
                         SL_PitchAngleTxt,
                         SYMBOLS_SEPARATOR,
                         SL_RotorRpmOnes,
                         SL_RotorRpmTenths,
                         SYMBOLS_SEPARATOR,
                         SL_GridRealPower,
                         SYMBOLS_SEPARATOR,
                         SL_StatusTxt,
                         LAST_SYMBOL_SEPARATOR,
                         OperationStateTxt
                        );
            }
        }
        //Updates status line variable
        LocalStatus = OS_VarDB_UpdateVariable(V_WP4000StatusText_ID, &V_StatusLineTxt, sizeof(V_StatusLineTxt));
        if (OS_SUCCESS != LocalStatus)
        {
            V_WP4000StatusText_ID = 0;
        }
    }

    return OS_SUCCESS;
}

//-----------------------------------------------------------------------
// MAIN CALL             MAIN CALL               MAIN CALL
//-----------------------------------------------------------------------

STATUS Info(U8 ModuleState, OS_MEMORY_POOL* MemPool, U32* Arg3)
{
    STATUS LocalStatus = 0;


    if (ModuleState == APP_INIT1)
    {
        LocalStatus = OS_ValidateAPI(API_VERSION_MAJOR,
                                     API_VERSION_MINOR,
                                     OS_LinkTime,
                                     ReleaseTag,
                                     __MODULE__
                                    );
        if (OS_SUCCESS != LocalStatus)
        {
            return LocalStatus;
        }
    }
#ifdef READ_VARS
    // Read inputdata
    LocalStatus = InputReferenceRoutine(ModuleState);
    STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif
#ifdef COMMON_VDB_READ
    LocalStatus = ReadVdbWindow(ModuleState);
    STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif
    switch (ModuleState)
    {
        case APP_RUN :
        {
         #ifdef FUNCTION_BLOCKS_PRE_LOCAL_CONTROL
            LocalStatus = FunctionBlocksPreLocalCtrl( Interval );
            STATUS_LINE_VAR_RETURN_VALUE( LocalStatus );
         #endif

            LocalStatus = LocalCtrl();
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
        
         #ifdef FUNCTION_BLOCKS_POST_LOCAL_CONTROL
            LocalStatus = FunctionBlocksPostLocalCtrl( Interval );
            STATUS_LINE_VAR_RETURN_VALUE( LocalStatus );
         #endif

#ifdef WRITE_VARS
            // Write Outputdata
            LocalStatus = OutputReferenceRoutine(ModuleState);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif

#ifdef COMMON_VDB_WRITE
            LocalStatus = WriteVdbWindow(ModuleState);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif
            break;
        }
        case APP_INIT1 :
        {
            Init_Structures_From_Conf_File();


#ifdef CREATE_VARDB_VARS
            LocalStatus = CreateVarDbVars();
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif

#ifdef CREATE_MENU
            LocalStatus = InfoMenuAppInit(ModuleState, MemPool);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)

#ifdef MULTIPLEXIBLE_MENU
            LocalStatus = MenuArraysAppInit(ModuleState, MemPool);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif
#endif

#ifdef CREATE_VARDB_ARRAY_VARS
            LocalStatus = CreateVdbArrays(MemPool);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif

#ifdef CREATE_IO_VARS
            LocalStatus = CreateIOVars();
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif
            break;
        }
        case APP_INIT2 :
        {
#ifdef CREATE_MENU
#ifdef MULTIPLEXIBLE_MENU
            LocalStatus = MenuArraysAppInit(ModuleState, MemPool);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif
#endif

#ifdef CREATE_ALIASES
            size_t ErrorEntry = 0;
            LocalStatus = OS_VarDB_CreateAliases(AliasVars, sizeof(AliasVars) / sizeof(AliasVars[0]), &ErrorEntry);
            STATUS_LINE_VAR_RETURN_CONST(LocalStatus, ErrorEntry)
#endif

#ifdef VERIFY_ARRAY
            LocalStatus = VerifyArray(MemPool);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif

#ifdef VERIFY_VARIABLES
            LocalStatus = LocalIoCheck();
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif

#ifdef CREATE_BUTTONS
            LocalStatus = CreateButtons();
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif
            break;
        }
        case APP_INIT3 :
        {
#ifdef CREATE_SUMMATIONS
            LocalStatus = CreateSummations();
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif

#ifdef WRITE_VARS
            LocalStatus = InitOutputVars();
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif

#ifdef CREATE_STATUS_CODES
            LocalStatus = LocalStatusCodeInit();
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif

#ifdef CREATE_IO_VARS
            InfoSetLockValues();
#endif
            break;
        }
        case APP_INIT4 :
        {
#ifdef CREATE_MENU
            LocalStatus = InfoMenuAppInit(ModuleState, MemPool);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)

#ifdef MULTIPLEXIBLE_MENU
            LocalStatus = MenuArraysAppInit(ModuleState, MemPool);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif
#endif
            break;
        }
        case APP_INIT5 :
        {
#ifdef VALIDATE_HASH
            LocalStatus = ValidateHash(Info_copyright, MODULE_NAME, Info_initialValues);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif

         #ifdef INIT_FUNCTION_BLOCKS
            LocalStatus = FunctionBlocksInit( Interval );
            STATUS_LINE_VAR_RETURN_VALUE( LocalStatus );
         #endif

            LocalStatus = Initialize();
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)

            break;
        }
        default :
        {
            break;
        }
    }
    return OS_SUCCESS;
}
//-----------------------------------------------------------------------
