//*****************************PEPTOOL Header Start******************************
//                                                                               
//                         Copyright © 2015 Mita-Teknik.                         
//This software may only be used with WP4x00 Controllers delivered by Mita-Teknik
//                                                                               
//*******************************************************************************
//                                                                               
// $PEPTOOL version:9.0$                                                         
// $PEPTOOL file version:101$                                                    
//                                                                               
//*******************************************************************************
//                                                                               
// $Date: 2014/03/04 14:27:11 $                                                  
// $Author: MITA\ihn $                                                           
// $RCSfile: InverterCooling_MT_Type1_Conf.c,v $                                 
// $Revision: 1.9 $                                                              
//                                                                               
//******************************PEPTOOL Header End*******************************

//***********************************************************************
// OS header files
#include <os_main.h>
// App header files
#include <InitIo.h>

#define AUTOGENERATED_PART

#include <Turbdef.h>

//-----------------------------------------------------------------------
// AUTOGENERATED START     AUTOGENERATED START     AUTOGENERATED START
//-----------------------------------------------------------------------
char InverterCooling_MT_Type1_Conf_copyright[] =
{
   67, 111, 112, 121, 114, 105, 103, 104, 116, 32, 63, 32, 50, 48, 49, 53,
   32, 77, 105, 116, 97, 45, 84, 101, 107, 110, 105, 107, 46, 13, 10, 84,
   104, 105, 115, 32, 115, 111, 102, 116, 119, 97, 114, 101, 32, 109, 97, 121,
   32, 111, 110, 108, 121, 32, 98, 101, 32, 117, 115, 101, 100, 32, 119, 105,
   116, 104, 32, 87, 80, 52, 120, 48, 48, 32, 67, 111, 110, 116, 114, 111,
   108, 108, 101, 114, 115, 32, 100, 101, 108, 105, 118, 101, 114, 101, 100, 32,
   98, 121, 32, 77, 105, 116, 97, 45, 84, 101, 107, 110, 105, 107, 0
};
//-----------------------------------------------------------------------
// MODIFIABLE                  MODIFIABLE               MODIFIABLE
//-----------------------------------------------------------------------
const char InverterCooling_MT_Type1AppGroupName[] = "G_"APP_ID"App";
const char InverterCooling_MT_Type1AppMenuName[] = "M_"APP_ID"AppMain";

//-----------------------------------------------------------------------
// IO VARIABLES                IO VARIABLES                IO VARIABLES
//-----------------------------------------------------------------------

void (*InverterCooling_MT_Type1SetLockValues)(void);
struct os_db_alias *InverterCooling_MT_Type1IOVars;
size_t InverterCooling_MT_Type1IOVarsSize = 0;
            
struct os_db_alias InverterCooling_MT_Type1IOVars1[]=
{
    VAR_ELEMENT_ALIAS("1.4.9",                            "DO_CNVC_CoolantPump"),

    VAR_ELEMENT_ALIAS("1.4.10",                           "DO_CNVC_CoolantFan"),

    VAR_ELEMENT_ALIAS("1.4.29",                           "DI_CNVC_PumpMCB"),
    VAR_ELEMENT_ALIAS("1.4.29_Ss",                        "DI_CNVC_PumpMCB_Ss"),
    VAR_ELEMENT_ALIAS("1.4.29_E",                         "DI_CNVC_PumpMCB_E"),
    VAR_ELEMENT_ALIAS("1.4.29_I",                         "DI_CNVC_PumpMCB_I"),
    VAR_ELEMENT_ALIAS("1.4.29_Cm",                        "DI_CNVC_PumpMCB_Cm"),
    VAR_ELEMENT_ALIAS("1.4.29_Ht",                        "DI_CNVC_PumpMCB_Ht"),

    VAR_ELEMENT_ALIAS("1.4.30",                           "DI_CNVC_CoolantFanMCB"),
    VAR_ELEMENT_ALIAS("1.4.30_Ss",                        "DI_CNVC_CoolantFanMCB_Ss"),
    VAR_ELEMENT_ALIAS("1.4.30_E",                         "DI_CNVC_CoolantFanMCB_E"),
    VAR_ELEMENT_ALIAS("1.4.30_I",                         "DI_CNVC_CoolantFanMCB_I"),
    VAR_ELEMENT_ALIAS("1.4.30_Cm",                        "DI_CNVC_CoolantFanMCB_Cm"),
    VAR_ELEMENT_ALIAS("1.4.30_Ht",                        "DI_CNVC_CoolantFanMCB_Ht"),

    VAR_ELEMENT_ALIAS("1.4.37",                           "DI_CNVC_CoolantLevel"),
    VAR_ELEMENT_ALIAS("1.4.37_Ss",                        "DI_CNVC_CoolantLevel_Ss"),
    VAR_ELEMENT_ALIAS("1.4.37_E",                         "DI_CNVC_CoolantLevel_E"),
    VAR_ELEMENT_ALIAS("1.4.37_I",                         "DI_CNVC_CoolantLevel_I"),
    VAR_ELEMENT_ALIAS("1.4.37_Cm",                        "DI_CNVC_CoolantLevel_Cm"),
    VAR_ELEMENT_ALIAS("1.4.37_Ht",                        "DI_CNVC_CoolantLevel_Ht"),

    VAR_ELEMENT_ALIAS("1.5.65",                           "PT_CNVC_CoolantHotTemp"),
    VAR_ELEMENT_ALIAS("1.5.65_Ss",                        "PT_CNVC_CoolantHotTemp_Ss"),
    VAR_ELEMENT_ALIAS("1.5.65_E",                         "PT_CNVC_CoolantHotTemp_E"),
    VAR_ELEMENT_ALIAS( "1.5.65_Th",                        "PT_CNVC_CoolantHotTemp_Th"),
    VAR_ELEMENT_ALIAS("1.5.65_Ht",                        "PT_CNVC_CoolantHotTemp_Ht"),
    VAR_ELEMENT_ALIAS("1.5.65_S",                         "PT_CNVC_CoolantHotTemp_S"),
    VAR_ELEMENT_ALIAS("1.5.65_O",                         "PT_CNVC_CoolantHotTemp_O"),

    VAR_ELEMENT_ALIAS("1.5.66",                           "PT_CNVC_CoolantCooledTemp"),
    VAR_ELEMENT_ALIAS("1.5.66_Ss",                        "PT_CNVC_CoolantCooledTemp_Ss"),
    VAR_ELEMENT_ALIAS("1.5.66_E",                         "PT_CNVC_CoolantCooledTemp_E"),
    VAR_ELEMENT_ALIAS( "1.5.66_Th",                        "PT_CNVC_CoolantCooledTemp_Th"),
    VAR_ELEMENT_ALIAS("1.5.66_Ht",                        "PT_CNVC_CoolantCooledTemp_Ht"),
    VAR_ELEMENT_ALIAS("1.5.66_S",                         "PT_CNVC_CoolantCooledTemp_S"),
    VAR_ELEMENT_ALIAS("1.5.66_O",                         "PT_CNVC_CoolantCooledTemp_O"),

    VAR_ELEMENT_ALIAS("1.4.13",                           "DO_CNVC_OutdoorFanCont"),

    VAR_ELEMENT_ALIAS("1.4.31",                           "DI_CNVC_OutdoorFanMCB"),
    VAR_ELEMENT_ALIAS("1.4.31_Ss",                        "DI_CNVC_OutdoorFanMCB_Ss"),
    VAR_ELEMENT_ALIAS("1.4.31_E",                         "DI_CNVC_OutdoorFanMCB_E"),
    VAR_ELEMENT_ALIAS("1.4.31_I",                         "DI_CNVC_OutdoorFanMCB_I"),
    VAR_ELEMENT_ALIAS("1.4.31_Cm",                        "DI_CNVC_OutdoorFanMCB_Cm"),
    VAR_ELEMENT_ALIAS("1.4.31_Ht",                        "DI_CNVC_OutdoorFanMCB_Ht"),

    VAR_ELEMENT_ALIAS("1.4.53U",                          "AO_CNVC_OutdoorFanSpeed"),

    VAR_ELEMENT_ALIAS("1.5.33",                           "DI_CNVC_OutdoorFanHealth"),
    VAR_ELEMENT_ALIAS("1.5.33_Ss",                        "DI_CNVC_OutdoorFanHealth_Ss"),
    VAR_ELEMENT_ALIAS("1.5.33_E",                         "DI_CNVC_OutdoorFanHealth_E"),
    VAR_ELEMENT_ALIAS("1.5.33_I",                         "DI_CNVC_OutdoorFanHealth_I"),
    VAR_ELEMENT_ALIAS("1.5.33_Cm",                        "DI_CNVC_OutdoorFanHealth_Cm"),
    VAR_ELEMENT_ALIAS("1.5.33_Ht",                        "DI_CNVC_OutdoorFanHealth_Ht"),

};
size_t InverterCooling_MT_Type1IOVars1Size = sizeof(InverterCooling_MT_Type1IOVars1)/sizeof(InverterCooling_MT_Type1IOVars1[0]);

void InverterCooling_MT_Type1SetLockValues1(void)
{
   SetLockValue("DI_CNVC_PumpMCB_Ss",                    TYP_8,     1);
   SetLockValue("DI_CNVC_PumpMCB_E",                     TYP_8,     1);
   SetValue("DI_CNVC_PumpMCB_I",                         TYP_8,     0);
   SetLockValue("DI_CNVC_PumpMCB_Cm",                    TYP_8,     1);
   SetLockValue("DI_CNVC_PumpMCB_Ht",                    TYP_32,    100);

   SetLockValue("DI_CNVC_CoolantFanMCB_Ss",              TYP_8,     1);
   SetLockValue("DI_CNVC_CoolantFanMCB_E",               TYP_8,     1);
   SetValue("DI_CNVC_CoolantFanMCB_I",                   TYP_8,     0);
   SetLockValue("DI_CNVC_CoolantFanMCB_Cm",              TYP_8,     1);
   SetLockValue("DI_CNVC_CoolantFanMCB_Ht",              TYP_32,    100);

   SetLockValue("DI_CNVC_CoolantLevel_Ss",               TYP_8,     1);
   SetLockValue("DI_CNVC_CoolantLevel_E",                TYP_8,     1);
   SetValue("DI_CNVC_CoolantLevel_I",                    TYP_8,     0);
   SetLockValue("DI_CNVC_CoolantLevel_Cm",               TYP_8,     1);
   SetLockValue("DI_CNVC_CoolantLevel_Ht",               TYP_32,    1000);

   SetLockValue("PT_CNVC_CoolantHotTemp_Ss",             TYP_8,     1);
   SetLockValue("PT_CNVC_CoolantHotTemp_E",              TYP_8,     1);
   SetLockValue("PT_CNVC_CoolantHotTemp_Th",             TYP_16,    1);
   SetLockValue("PT_CNVC_CoolantHotTemp_Ht",             TYP_32,    60000);
   SetLockValue("PT_CNVC_CoolantHotTemp_S",              TYP_32,    0);
   SetValue("PT_CNVC_CoolantHotTemp_O",                  TYP_32,    0);

   SetLockValue("PT_CNVC_CoolantCooledTemp_Ss",          TYP_8,     1);
   SetLockValue("PT_CNVC_CoolantCooledTemp_E",           TYP_8,     1);
   SetLockValue("PT_CNVC_CoolantCooledTemp_Th",          TYP_16,    1);
   SetLockValue("PT_CNVC_CoolantCooledTemp_Ht",          TYP_32,    60000);
   SetLockValue("PT_CNVC_CoolantCooledTemp_S",           TYP_32,    0);
   SetValue("PT_CNVC_CoolantCooledTemp_O",               TYP_32,    0);

   SetLockValue("DI_CNVC_OutdoorFanMCB_Ss",              TYP_8,     1);
   SetLockValue("DI_CNVC_OutdoorFanMCB_E",               TYP_8,     1);
   SetValue("DI_CNVC_OutdoorFanMCB_I",                   TYP_8,     0);
   SetLockValue("DI_CNVC_OutdoorFanMCB_Cm",              TYP_8,     1);
   SetLockValue("DI_CNVC_OutdoorFanMCB_Ht",              TYP_32,    1000);

   SetLockValue("DI_CNVC_OutdoorFanHealth_Ss",           TYP_8,     1);
   SetLockValue("DI_CNVC_OutdoorFanHealth_E",            TYP_8,     1);
   SetValue("DI_CNVC_OutdoorFanHealth_I",                TYP_8,     0);
   SetLockValue("DI_CNVC_OutdoorFanHealth_Cm",           TYP_8,     1);
   SetLockValue("DI_CNVC_OutdoorFanHealth_Ht",           TYP_32,    1000);
}


STATUS InverterCooling_MT_Type1InitIOAliases()
{
   InverterCooling_MT_Type1IOVars = InverterCooling_MT_Type1IOVars1;
   InverterCooling_MT_Type1IOVarsSize = InverterCooling_MT_Type1IOVars1Size;
   InverterCooling_MT_Type1SetLockValues = &InverterCooling_MT_Type1SetLockValues1;
   return OS_SUCCESS;
}
//-----------------------------------------------------------------------
// AUTOGENERATED END        AUTOGENERATED END        AUTOGENERATED END
//-----------------------------------------------------------------------

#undef AUTOGENERATED_PART
