//*****************************PEPTOOL Header Start******************************
//                                                                               
//                         Copyright © 2015 Mita-Teknik.                         
//This software may only be used with WP4x00 Controllers delivered by Mita-Teknik
//                                                                               
//*******************************************************************************
//                                                                               
// $PEPTOOL version:9.0$                                                         
// $PEPTOOL file version:106$                                                    
//                                                                               
//*******************************************************************************
//                                                                               
// $Date: 2014/05/23 09:10:08 $                                                  
// $Author: MITA\ihn $                                                           
// $RCSfile: InverterCooling_MT_Type1.c,v $                                      
// $Revision: 1.19 $                                                             
//                                                                               
//******************************PEPTOOL Header End*******************************

//***********************************************************************

// OS header files
#include <os_main.h>
// AppLib header files
#include <lib_main.h>
// App header files
#include <turbdef.h>
#include <VarMacros.h>

// Object header file
#include <InverterCooling_MT_Type1.h>

#define AUTOGENERATED_PART
//{
//-----------------------------------------------------------------------
// AUTOGENERATED START     AUTOGENERATED START     AUTOGENERATED START
//-----------------------------------------------------------------------

#define VALIDATE_HASH
char InverterCooling_MT_Type1_copyright[] =
{
    67, 111, 112, 121, 114, 105, 103, 104, 116, 32, 63, 32, 50, 48, 49, 53,
    32, 77, 105, 116, 97, 45, 84, 101, 107, 110, 105, 107, 46, 13, 10, 84,
    104, 105, 115, 32, 115, 111, 102, 116, 119, 97, 114, 101, 32, 109, 97, 121,
    32, 111, 110, 108, 121, 32, 98, 101, 32, 117, 115, 101, 100, 32, 119, 105,
    116, 104, 32, 87, 80, 52, 120, 48, 48, 32, 67, 111, 110, 116, 114, 111,
    108, 108, 101, 114, 115, 32, 100, 101, 108, 105, 118, 101, 114, 101, 100, 32,
    98, 121, 32, 77, 105, 116, 97, 45, 84, 101, 107, 110, 105, 107, 0
};

#define MODULE_NAME "Inverter CoolingA"

//-----------------------------------------------------------------------
// ALLOCATE MEMORY FOR STRINGS IN VARDB
//-----------------------------------------------------------------------

static char A_V_CNVC_PumpStateTxt[31]  = "Unknown";
static char A_V_CNVC_CoolantFanStateTxt[31]  = "Unknown";

//-----------------------------------------------------------------------
// DEFINE LOCAL VARIABLES DEFINE LOCAL VARIABLES DEFINE LOCAL VARIABLES
//-----------------------------------------------------------------------

static struct os_db_local LocalVars[] =
{
   VAR_ELEMENT_LOCAL("V_CNVC_PumpService",                       TYPE_U8,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_NONE,   0,       UNIT_NONE,          0,   0,               0,               2,               NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_CNVC_CoolantFanService",                 TYPE_U8,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_NONE,   0,       UNIT_NONE,          0,   0,               0,               2,               NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_CNVC_PumpState",                         TYPE_U8,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   0,               U8_MIN,          U8_MAX,          NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_CNVC_PumpStateTxt",                      TYPE_STRING + sizeof(A_V_CNVC_PumpStateTxt) - 1,  PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_NONE,   0,       UNIT_NONE,          0,   A_V_CNVC_PumpStateTxt, 0,                0,                NULL,  NOLOG_ENABLE  ),
   VAR_ELEMENT_LOCAL("V_CNVC_CoolantFanState",                   TYPE_U8,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   0,               U8_MIN,          U8_MAX,          NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_CNVC_CoolantFanStateTxt",                TYPE_STRING + sizeof(A_V_CNVC_CoolantFanStateTxt) - 1,  PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_NONE,   0,       UNIT_NONE,          0,   A_V_CNVC_CoolantFanStateTxt, 0,                0,                NULL,  NOLOG_ENABLE  ),
   VAR_ELEMENT_LOCAL("V_CNVC_HeatPower",                         TYPE_S16,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    10,      UNIT_KWATT,         1,   0,               S16_MIN,         S16_MAX,         NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_CNVC_OutdoorFanService",                 TYPE_U8,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   0,               0,               2,               NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_CNVC_OutdoorFanSpeedPctService",         TYPE_U16,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    10,      UNIT_PCT,           1,   0,               0,               1000,            NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_CNVC_OutdoorFanSpeedPct",                TYPE_U16,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    10,      UNIT_PCT,           1,   0,               U16_MIN,         U16_MAX,         NULL,  NOLOG_ENABLE),
};

//-----------------------------------------------------------------------
// DEFINE PARAMETERS        DEFINE PARAMETERS        DEFINE PARAMETERS
//-----------------------------------------------------------------------

static struct os_db_parameter ParameterVars[] =
{
   VAR_ELEMENT_PARAMETER("P_CNVC_SystemStopDelay",                   TYPE_U32,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_DIV,    60000,   UNIT_MINUTE,        0,   60000,           0,               3600000,         NULL  ),
   VAR_ELEMENT_PARAMETER("P_CNVC_MaxOveralTemp",                     TYPE_S16,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_DIV,    10,      UNIT_CELSIUS,       0,   500,             0,               1000,            NULL  ),
   VAR_ELEMENT_PARAMETER("P_CNVC_FanTempON",                         TYPE_S16,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    10,      UNIT_CELSIUS,       0,   400,             200,             1000,            NULL  ),
   VAR_ELEMENT_PARAMETER("P_CNVC_FanTempOFF",                        TYPE_S16,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    10,      UNIT_CELSIUS,       0,   350,             100,             900,             NULL  ),
   VAR_ELEMENT_PARAMETER("P_CNVC_CoolantFlowRate",                   TYPE_U16,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   228,             U16_MIN,         U16_MAX,         NULL  ),
   VAR_ELEMENT_PARAMETER("P_CNVC_OutFanTempOFF",                     TYPE_S16,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    10,      UNIT_CELSIUS,       1,   440,             S16_MIN,         S16_MAX,         NULL  ),
   VAR_ELEMENT_PARAMETER("P_CNVC_OutFanTemp1",                       TYPE_S16,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    10,      UNIT_CELSIUS,       1,   450,             S16_MIN,         S16_MAX,         NULL  ),
   VAR_ELEMENT_PARAMETER("P_CNVC_OutFanTemp2",                       TYPE_S16,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    10,      UNIT_CELSIUS,       1,   500,             S16_MIN,         S16_MAX,         NULL  ),
   VAR_ELEMENT_PARAMETER("P_CNVC_OutFanSpeedPct1",                   TYPE_U16,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    10,      UNIT_PCT,           1,   100,             50,              1000,            NULL  ),
   VAR_ELEMENT_PARAMETER("P_CNVC_OutFanSpeedPct2",                   TYPE_U16,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    10,      UNIT_PCT,           1,   1000,            100,             1000,            NULL  ),
   VAR_ELEMENT_PARAMETER("P_CNVC_OutFanSpeedVolt_0",                 TYPE_S16,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    1000,    UNIT_VOLT,          3,   0,               S16_MIN,         S16_MAX,         NULL  ),
   VAR_ELEMENT_PARAMETER("P_CNVC_OutFanSpeedVolt_100",               TYPE_S16,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    1000,    UNIT_VOLT,          3,   10000,           S16_MIN,         S16_MAX,         NULL  ),
   VAR_ELEMENT_PARAMETER("P_CNVC_MaxCoolantTemp",                    TYPE_S16,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    10,      UNIT_CELSIUS,       1,   500,             0,               1000,            NULL  ),
   VAR_ELEMENT_PARAMETER("P_CNVC_MinIGBTTemp",                       TYPE_S16,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    10,      UNIT_CELSIUS,       1,   50,              -500,            500,             NULL  ),
};

//-----------------------------------------------------------------------
// DEFINE BACKUPS            DEFINE BACKUPS            DEFINE BACKUPS
//-----------------------------------------------------------------------

//----------------------------------------------------------------------------------
// DEFINE VAR ARRAYS            DEFINE VAR ARRAYS            DEFINE VAR ARRAYS
//----------------------------------------------------------------------------------
char InverterCooling_MT_Type1_initialValues[] =
{
    32, 37, 46, 174, 159, 175, 97, 56, 129, 67, 21, 240, 118, 221, 143, 207,
    90, 43, 19, 72, 160, 233, 137, 65, 243, 103, 42, 52, 107, 218, 160, 100,
    0
};

//-----------------------------------------------------------------------
// CREATE DATABASE VARS   CREATE DATABASE VARS   CREATE DATABASE VARS
//-----------------------------------------------------------------------

static STATUS CreateVarDbVars(void)
{
   STATUS Status;
   size_t ErrorEntry;

   Status = OS_VarDB_CreateLocals(LocalVars, sizeof(LocalVars)/sizeof(LocalVars[0]), &ErrorEntry, AppLocalParameterPosition());
   if (Status != 0)
   {
      AppSystemLog(ERR_7, MODULE_NAME"CrVL: %d,%d", Status, ErrorEntry);
      return ERR_7;
   }

   Status = OS_VarDB_CreateParameters(ParameterVars, sizeof(ParameterVars)/sizeof(ParameterVars[0]), &ErrorEntry, AppExportParameterPosition());
   if (Status != 0)
   {
      AppSystemLog(ERR_7, MODULE_NAME"CrVXP: %d,%d", Status, ErrorEntry);
      return ERR_7;
   }

   return OS_SUCCESS;
}

#define CREATE_VARDB_VARS

//-----------------------------------------------------------------------
// CREATE IO VARIABLES     CREATE IO VARIABLES     CREATE IO VARIABLES
//-----------------------------------------------------------------------

extern STATUS InverterCooling_MT_Type1InitIOAliases();
extern struct os_db_alias* InverterCooling_MT_Type1IOVars;
extern void (*InverterCooling_MT_Type1SetLockValues)(void);
extern size_t InverterCooling_MT_Type1IOVarsSize;

static STATUS CreateIOVars(void)
{
   STATUS Status;
   size_t ErrorEntry;

   varid_t VarId;
   BOOL variablesExist = false;
   U8 counter = 50;
   Status = InverterCooling_MT_Type1InitIOAliases();
   STATUS_LINE_VAR_RETURN_VALUE(Status)
   while (!variablesExist && counter-- > 0)
   {
      variablesExist = true;
      U32 i = 0;
      for (i = 0; i < InverterCooling_MT_Type1IOVarsSize; ++i)
      {
         if (OS_VarDB_GetVariableID(InverterCooling_MT_Type1IOVars[i].Name, &VarId) != OS_SUCCESS)
         {
            variablesExist = false;
            break;
         }
      }

      if (!variablesExist)
      {
         OS_Sleep(100);
      }
   }

   Status = OS_VarDB_CreateAliases(InverterCooling_MT_Type1IOVars, InverterCooling_MT_Type1IOVarsSize, &ErrorEntry);
   if (Status)
   {
      AppDebugLog(5000, "Var Name = %s", InverterCooling_MT_Type1IOVars[ErrorEntry].Alias);
   }
   STATUS_LINE_VAR_RETURN_CONST(Status, ErrorEntry);
   return OS_SUCCESS;
}

#define CREATE_IO_VARS

//-----------------------------------------------------------------------
// ALIASES                       ALIASES                       ALIASES
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// INPUT                          INPUT                          INPUT
//-----------------------------------------------------------------------

// Create local variable
#define MODUL_INPUTS
static U8 DI_CNVC_PumpMCB = 0;
static U8 DI_CNVC_CoolantFanMCB = 0;
static U8 V_CNVC_PumpService = 0;
static U8 V_CNVC_CoolantFanService = 0;
static U32 P_CNVC_SystemStopDelay = 0;
static S16 V_CNV_MaxIGBTTemp = 0;
static S16 V_CNV_MinIGBTTemp = 0;
static U8 DI_CNVC_CoolantLevel = 0;
static S16 PT_CNVC_CoolantHotTemp = 0;
static S16 PT_CNVC_CoolantCooledTemp = 0;
static U16 P_CNVC_CoolantFlowRate = 0;
static U8 DI_CNVC_OutdoorFanMCB = 0;
static U8 DI_CNVC_OutdoorFanHealth = 0;
static S16 P_CNVC_OutFanTemp1 = 0;
static S16 P_CNVC_OutFanTemp2 = 0;
static U16 P_CNVC_OutFanSpeedPct1 = 0;
static U16 P_CNVC_OutFanSpeedPct2 = 0;
static S16 P_CNVC_OutFanSpeedVolt_0 = 0;
static S16 P_CNVC_OutFanSpeedVolt_100 = 0;
static U8 V_CNVC_OutdoorFanService = 0;
static U16 V_CNVC_OutdoorFanSpeedPctService = 0;
static S16 P_CNVC_OutFanTempOFF = 0;
static S16 P_CNVC_MaxCoolantTemp = 0;
static S16 P_CNVC_MinIGBTTemp = 0;
static U8 V_CNV_State = 0;

//-----------------------------------------------------------------------
static struct ModulInOut ModulInputs[] =
{
   {"DI_CNVC_PumpMCB",                          &DI_CNVC_PumpMCB,                          sizeof(DI_CNVC_PumpMCB),                          },
   {"DI_CNVC_CoolantFanMCB",                    &DI_CNVC_CoolantFanMCB,                    sizeof(DI_CNVC_CoolantFanMCB),                    },
   {"V_CNVC_PumpService",                       &V_CNVC_PumpService,                       sizeof(V_CNVC_PumpService),                       },
   {"V_CNVC_CoolantFanService",                 &V_CNVC_CoolantFanService,                 sizeof(V_CNVC_CoolantFanService),                 },
   {"P_CNVC_SystemStopDelay",                   &P_CNVC_SystemStopDelay,                   sizeof(P_CNVC_SystemStopDelay),                   },
   {"V_CNV_MaxIGBTTemp",                        &V_CNV_MaxIGBTTemp,                        sizeof(V_CNV_MaxIGBTTemp),                        },
   {"V_CNV_MinIGBTTemp",                        &V_CNV_MinIGBTTemp,                        sizeof(V_CNV_MinIGBTTemp),                        },
   {"DI_CNVC_CoolantLevel",                     &DI_CNVC_CoolantLevel,                     sizeof(DI_CNVC_CoolantLevel),                     },
   {"PT_CNVC_CoolantHotTemp",                   &PT_CNVC_CoolantHotTemp,                   sizeof(PT_CNVC_CoolantHotTemp),                   },
   {"PT_CNVC_CoolantCooledTemp",                &PT_CNVC_CoolantCooledTemp,                sizeof(PT_CNVC_CoolantCooledTemp),                },
   {"P_CNVC_CoolantFlowRate",                   &P_CNVC_CoolantFlowRate,                   sizeof(P_CNVC_CoolantFlowRate),                   },
   {"DI_CNVC_OutdoorFanMCB",                    &DI_CNVC_OutdoorFanMCB,                    sizeof(DI_CNVC_OutdoorFanMCB),                    },
   {"DI_CNVC_OutdoorFanHealth",                 &DI_CNVC_OutdoorFanHealth,                 sizeof(DI_CNVC_OutdoorFanHealth),                 },
   {"P_CNVC_OutFanTemp1",                       &P_CNVC_OutFanTemp1,                       sizeof(P_CNVC_OutFanTemp1),                       },
   {"P_CNVC_OutFanTemp2",                       &P_CNVC_OutFanTemp2,                       sizeof(P_CNVC_OutFanTemp2),                       },
   {"P_CNVC_OutFanSpeedPct1",                   &P_CNVC_OutFanSpeedPct1,                   sizeof(P_CNVC_OutFanSpeedPct1),                   },
   {"P_CNVC_OutFanSpeedPct2",                   &P_CNVC_OutFanSpeedPct2,                   sizeof(P_CNVC_OutFanSpeedPct2),                   },
   {"P_CNVC_OutFanSpeedVolt_0",                 &P_CNVC_OutFanSpeedVolt_0,                 sizeof(P_CNVC_OutFanSpeedVolt_0),                 },
   {"P_CNVC_OutFanSpeedVolt_100",               &P_CNVC_OutFanSpeedVolt_100,               sizeof(P_CNVC_OutFanSpeedVolt_100),               },
   {"V_CNVC_OutdoorFanService",                 &V_CNVC_OutdoorFanService,                 sizeof(V_CNVC_OutdoorFanService),                 },
   {"V_CNVC_OutdoorFanSpeedPctService",         &V_CNVC_OutdoorFanSpeedPctService,         sizeof(V_CNVC_OutdoorFanSpeedPctService),         },
   {"P_CNVC_OutFanTempOFF",                     &P_CNVC_OutFanTempOFF,                     sizeof(P_CNVC_OutFanTempOFF),                     },
   {"P_CNVC_MaxCoolantTemp",                    &P_CNVC_MaxCoolantTemp,                    sizeof(P_CNVC_MaxCoolantTemp),                    },
   {"P_CNVC_MinIGBTTemp",                       &P_CNVC_MinIGBTTemp,                       sizeof(P_CNVC_MinIGBTTemp),                       },
   {"V_CNV_State",                              &V_CNV_State,                              sizeof(V_CNV_State),                              },
};

//-----------------------------------------------------------------------
// Check variable type
static STATUS VarsReadReturnStatus;
static type_t ReadVarType = TYPE_NONE;
static void VarsReadTypeCheck(void)
{
   (void)VarsReadReturnStatus;
   (void)ReadVarType;
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[0].Name,                      ModulInputs[0].Id)
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[1].Name,                      ModulInputs[1].Id)
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[2].Name,                      ModulInputs[2].Id)
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[3].Name,                      ModulInputs[3].Id)
   VERIFY_INPUT_REF_ID(U32,       ModulInputs[4].Name,                      ModulInputs[4].Id)
   VERIFY_INPUT_REF_ID(S16,       ModulInputs[5].Name,                      ModulInputs[5].Id)
   VERIFY_INPUT_REF_ID(S16,       ModulInputs[6].Name,                      ModulInputs[6].Id)
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[7].Name,                      ModulInputs[7].Id)
   VERIFY_INPUT_REF_ID(S16,       ModulInputs[8].Name,                      ModulInputs[8].Id)
   VERIFY_INPUT_REF_ID(S16,       ModulInputs[9].Name,                      ModulInputs[9].Id)
   VERIFY_INPUT_REF_ID(U16,       ModulInputs[10].Name,                     ModulInputs[10].Id)
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[11].Name,                     ModulInputs[11].Id)
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[12].Name,                     ModulInputs[12].Id)
   VERIFY_INPUT_REF_ID(S16,       ModulInputs[13].Name,                     ModulInputs[13].Id)
   VERIFY_INPUT_REF_ID(S16,       ModulInputs[14].Name,                     ModulInputs[14].Id)
   VERIFY_INPUT_REF_ID(U16,       ModulInputs[15].Name,                     ModulInputs[15].Id)
   VERIFY_INPUT_REF_ID(U16,       ModulInputs[16].Name,                     ModulInputs[16].Id)
   VERIFY_INPUT_REF_ID(S16,       ModulInputs[17].Name,                     ModulInputs[17].Id)
   VERIFY_INPUT_REF_ID(S16,       ModulInputs[18].Name,                     ModulInputs[18].Id)
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[19].Name,                     ModulInputs[19].Id)
   VERIFY_INPUT_REF_ID(U16,       ModulInputs[20].Name,                     ModulInputs[20].Id)
   VERIFY_INPUT_REF_ID(S16,       ModulInputs[21].Name,                     ModulInputs[21].Id)
   VERIFY_INPUT_REF_ID(S16,       ModulInputs[22].Name,                     ModulInputs[22].Id)
   VERIFY_INPUT_REF_ID(S16,       ModulInputs[23].Name,                     ModulInputs[23].Id)
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[24].Name,                     ModulInputs[24].Id)
}

#undef MODUL_INPUTS
#define MODUL_INPUTS_SIZE (sizeof(ModulInputs)/sizeof(ModulInputs[0]))

//------------------------------------------------------------------------------------------
// READ/WRITE VARDB ARRAY      READ/WRITE VARDB ARRAY      READ/WRATE VARDB ARRAY
//------------------------------------------------------------------------------------------


//-----------------------------------------------------------------------
// PARAMETER                    PARAMETER                    PARAMETER
//-----------------------------------------------------------------------

// Create local variable
#define MODUL_PARAMETERS
static S16 P_CNVC_MaxOveralTemp = 0;
static S16 P_CNVC_FanTempON = 0;
static S16 P_CNVC_FanTempOFF = 0;



//-----------------------------------------------------------------------
static struct ModulInOut ModulParameters0[] =
{
   {"P_CNVC_MaxOveralTemp",                     &P_CNVC_MaxOveralTemp,                     sizeof(P_CNVC_MaxOveralTemp),                     },
   {"P_CNVC_FanTempON",                         &P_CNVC_FanTempON,                         sizeof(P_CNVC_FanTempON),                         },
   {"P_CNVC_FanTempOFF",                        &P_CNVC_FanTempOFF,                        sizeof(P_CNVC_FanTempOFF),                        },

};
static struct ModulInOut* ModulParameters[] =
{
   ModulParameters0,
};

//-----------------------------------------------------------------------
// Check variable type
static STATUS ParaVarsReadReturnStatus;
static type_t ParaReadVarType = TYPE_NONE;
static void ParaVarsReadTypeCheck(void)
{
   (void)ParaVarsReadReturnStatus;
   (void)ParaReadVarType;
}

#undef MODUL_PARAMETERS

#define PARAMETERS_GROUPS_SIZE        1
#define GENERAL_GROUP                 0
#define MODUL_PARAMETERS_TOTAL_SIZE   3
static SUBSCRIPTION ParaSubscription[MODUL_PARAMETERS_TOTAL_SIZE];
static U8 ReadParameters[PARAMETERS_GROUPS_SIZE];
static U8 ParametersChanged[PARAMETERS_GROUPS_SIZE];
static UNSIGNED GroupsIndexes[PARAMETERS_GROUPS_SIZE];
static int ParaGroupsSizes[PARAMETERS_GROUPS_SIZE] = { 3 };
static STATUS VarDbUpdateParameter(varid_t VariableId, void* Message, U16 Length, UNSIGNED paraGroupIndex, UNSIGNED Ref2)
{
   ReadParameters[paraGroupIndex] = 1;
   ParametersChanged[paraGroupIndex] = 1;
   return OS_SUCCESS;
}
static STATUS ReadParametersFunc(int paraGroupIndex)
{
   STATUS LocalStatus;
   // Check inputdata
   if (sizeof(ModulParameters[paraGroupIndex]) == 0)
   {
      AppSystemLog(ERR_4, MODULE_NAME"Group %d ModuleParameters = 0", paraGroupIndex);
      return ERR_4;
   }
   // Read inputdata
   LocalStatus = OS_ReadVariables(ModulParameters[paraGroupIndex], ParaGroupsSizes[paraGroupIndex]);
   if (LocalStatus != 0)
   {
      AppSystemLog(11, "LocalStatus: %d", LocalStatus);
      AppSystemLog(ERR_4, MODULE_NAME"ReadParErr: group=%d element=%d elementpointer=0x%x", paraGroupIndex, LocalStatus, &ModulParameters[LocalStatus]);
      return ERR_4;
   }
   return OS_SUCCESS;
}


//-----------------------------------------------------------------------
// READ VARS FROM VARDB    READ VARS FROM VARDB    READ VARS FROM VARDB
//-----------------------------------------------------------------------

static STATUS InputReferenceRoutine(U8 ModuleState)
{
   STATUS LocalStatus = 0;

   // Read input references
   if (ModuleState >= APP_INIT3)
   {
      // Check inputdata
      if (sizeof(ModulInputs) == 0)
      {
         AppSystemLog(ERR_4, MODULE_NAME"ModuleInputs = 0");
         return ERR_4;
      }
      // Read inputdata
      LocalStatus = OS_ReadVariables(ModulInputs, MODUL_INPUTS_SIZE);
      if (LocalStatus != 0)
      {
         AppSystemLog(ERR_4, MODULE_NAME"ReadVErr: element=%d elementpointer=0x%x", LocalStatus, &ModulInputs[LocalStatus]);
         return ERR_4;
      }
   }
   // Read input parameters
   if (ModuleState == APP_INIT3)
   {
      static size_t ParaCounter = 0;
      int groupIndex;
      for (groupIndex = 0; groupIndex < PARAMETERS_GROUPS_SIZE; groupIndex++)
      {
         ParametersChanged[groupIndex] = 1;
         ReadParameters[groupIndex] = 1;
         GroupsIndexes[groupIndex] = groupIndex;

         // Check inputdata
         if (sizeof(ModulParameters[groupIndex]) == 0)
         {
            AppSystemLog(ERR_4, MODULE_NAME"Group = %d ModuleParameters = 0", groupIndex);
            return ERR_4;
         }
         // Read inputdata
         LocalStatus = OS_ReadVariables(ModulParameters[groupIndex], ParaGroupsSizes[groupIndex]);
         if (LocalStatus != 0)
         {
            AppSystemLog(ERR_4, MODULE_NAME"ReadVParaErr: group=%d element=%d elementpointer=0x%x", groupIndex, LocalStatus, &ModulParameters[groupIndex][LocalStatus]);
            return ERR_4;
         }
         int paraIndex;
         for (paraIndex = 0; paraIndex < ParaGroupsSizes[groupIndex]; paraIndex++)
         {
            LocalStatus = OS_SubHandl_SubscribeFunctionWithRef(&ParaSubscription[ParaCounter], 1, &ModulParameters[groupIndex][paraIndex].Id, &GroupsIndexes[groupIndex], &GroupsIndexes[groupIndex], VarDbUpdateParameter);
            ParaCounter++;
            if (LocalStatus != 0)
            {
               AppSystemLog(ERR_4, MODULE_NAME"Subscribe Parameter: group=%d element=%d elementpointer=0x%x", groupIndex, LocalStatus, &ModulParameters[LocalStatus]);
               return ERR_4;
            }
         }
      }
   }
   if (ModuleState == APP_RUN)
   {
      int groupIndex;
      for (groupIndex = 0; groupIndex < PARAMETERS_GROUPS_SIZE; groupIndex++)
      {
         if (ReadParameters[groupIndex])
         {
            LocalStatus = ReadParametersFunc(groupIndex);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
            ReadParameters[groupIndex] = 0;
         }
      }
   }

   return 0;
}

#define READ_VARS

//-----------------------------------------------------------------------
// OUTPUT                         OUTPUT                         OUTPUT
//-----------------------------------------------------------------------

// Create local variable
#define MODUL_OUTPUTS
static U8 DO_CNVC_CoolantPump = 0;
static U8 DO_CNVC_CoolantFan = 0;
static S16 V_CNVC_HeatPower = 0;
static S16 AO_CNVC_OutdoorFanSpeed = 0;
static U8 DO_CNVC_OutdoorFanCont = 0;
static U16 V_CNVC_OutdoorFanSpeedPct = 0;


//-----------------------------------------------------------------------
static struct ModulInOut ModulOutputs[] =
{
   {"DO_CNVC_CoolantPump",                      &DO_CNVC_CoolantPump,                      sizeof(DO_CNVC_CoolantPump),                      },
   {"DO_CNVC_CoolantFan",                       &DO_CNVC_CoolantFan,                       sizeof(DO_CNVC_CoolantFan),                       },
   {"V_CNVC_HeatPower",                         &V_CNVC_HeatPower,                         sizeof(V_CNVC_HeatPower),                         },
   {"AO_CNVC_OutdoorFanSpeed",                  &AO_CNVC_OutdoorFanSpeed,                  sizeof(AO_CNVC_OutdoorFanSpeed),                  },
   {"DO_CNVC_OutdoorFanCont",                   &DO_CNVC_OutdoorFanCont,                   sizeof(DO_CNVC_OutdoorFanCont),                   },
   {"V_CNVC_OutdoorFanSpeedPct",                &V_CNVC_OutdoorFanSpeedPct,                sizeof(V_CNVC_OutdoorFanSpeedPct),                },
};

//-----------------------------------------------------------------------
// Check variable type
static STATUS VarsWriteReturnStatus;
static type_t WriteVarType = TYPE_NONE;
static void VarsWriteTypeCheck(void)
{
   (void)VarsWriteReturnStatus;
   (void)WriteVarType;
   VERIFY_OUTPUT_REF_ID(U8,        ModulOutputs[0].Name,                     ModulOutputs[0].Id,                       0)
   VERIFY_OUTPUT_REF_ID(U8,        ModulOutputs[1].Name,                     ModulOutputs[1].Id,                       0)
   VERIFY_OUTPUT_REF_ID(S16,       ModulOutputs[2].Name,                     ModulOutputs[2].Id,                       0)
   VERIFY_OUTPUT_REF_ID(S16,       ModulOutputs[3].Name,                     ModulOutputs[3].Id,                       0)
   VERIFY_OUTPUT_REF_ID(U8,        ModulOutputs[4].Name,                     ModulOutputs[4].Id,                       0)
   VERIFY_OUTPUT_REF_ID(U16,       ModulOutputs[5].Name,                     ModulOutputs[5].Id,                       0)
}

#undef MODUL_OUTPUTS
#define MODUL_OUTPUTS_SIZE (sizeof(ModulOutputs)/sizeof(ModulOutputs[0]))

//-----------------------------------------------------------------------
// WRITE VARS TO VARDB     WRITE VARS TO VARDB     WRITE VARS TO VARDB
//-----------------------------------------------------------------------

static STATUS InitOutputVars(void)
{
   STATUS LocalStatus;
   // Read outputdata
   LocalStatus = OS_ReadVariables(ModulOutputs, MODUL_OUTPUTS_SIZE);
   if (LocalStatus != 0)
   {
      AppSystemLog(ERR_4, MODULE_NAME"InitErr: element=%d elementpointer=0x%x", LocalStatus, &ModulOutputs[LocalStatus]);
      return ERR_4;
   }
   return OS_SUCCESS;
}
static STATUS OutputReferenceRoutine(U8 ModuleState)
{
   STATUS LocalStatus = 0;
   // Write Outputdata
   LocalStatus = OS_WriteVariablesConditional(ModulOutputs, MODUL_OUTPUTS_SIZE);
   if (LocalStatus != 0)
   {
      AppSystemLog(ERR_5, MODULE_NAME"WriteVErr: element=%d elementpointer=0x%x", LocalStatus, &ModulOutputs[LocalStatus]);
      return ERR_5;
   }
   return 0;
}

#define WRITE_VARS

//-----------------------------------------------------------------------
// VERIFY VARIABLES CREATION                 VERIFY VARIABLES CREATION
//-----------------------------------------------------------------------

static STATUS LocalIoCheck(void)
{
   // Check if input variables exist.
   STATUS LocalStatus;

   LocalStatus = OS_DoesVariablesExist(ModulInputs, MODUL_INPUTS_SIZE);
   if (LocalStatus != 0)
   {
      AppSystemLog(ERR_1, MODULE_NAME"InputErr: %d", LocalStatus);
      AppSystemLog(ERR_1, "Name: %s", ModulInputs[LocalStatus-1].Name);
      return ERR_1;
   }
   (void)VarsReadTypeCheck();

   int groupIndex;
   for (groupIndex = 0; groupIndex < PARAMETERS_GROUPS_SIZE; groupIndex++)
   {
      LocalStatus = OS_DoesVariablesExist(ModulParameters[groupIndex], ParaGroupsSizes[groupIndex]);
      if (LocalStatus != 0)
      {
         AppSystemLog(ERR_3, MODULE_NAME"ParameterErr: %d Group:%d", LocalStatus, groupIndex);
         AppSystemLog(ERR_3, "Name: %s", ModulParameters[groupIndex][LocalStatus-1].Name);
         return ERR_3;
      }
   }
   (void)ParaVarsReadTypeCheck();

   LocalStatus = OS_DoesVariablesExist(ModulOutputs, MODUL_OUTPUTS_SIZE);
   if (LocalStatus != 0)
   {
      AppSystemLog(ERR_2, MODULE_NAME"OutputErr: %d", LocalStatus);
      AppSystemLog(ERR_2, "Name: %s", ModulOutputs[LocalStatus-1].Name);
      return ERR_2;
   }
   (void)VarsWriteTypeCheck();

   return OS_SUCCESS;
}

#define VERIFY_VARIABLES

//-----------------------------------------------------------------------
// ALLOCATE MEMORY FOR SUMMATIONS        ALLOCATE MEMORY FOR SUMMATIONS
//-----------------------------------------------------------------------


//-----------------------------------------------------------------------
// SUMMATIONS                  SUMMATIONS                  SUMMATIONS
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// DEFINE MENUS               DEFINE MENUS               DEFINE MENUS
//-----------------------------------------------------------------------



// Menu line and link to local menu
//-----------------------------------------------------------------------
static struct line_struct M_InverterCoolingLinkToLocalMenu[] =
{
   MENU_ELEMENT_LINE_LINK("Inverter Cooling",                  PASSWORD_LEVEL_END_CUSTOMER,        "M_InverterCooling",                "G_InverterCooling_MT_Type1"),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_InverterCoolingMenu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_InverterCooling",                PASSWORD_LEVEL_END_CUSTOMER),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_InverterCoolingMenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("INVERTER COOLING",                  PASSWORD_LEVEL_END_CUSTOMER,        "M_"APP_ID"AppMain",                "G_"APP_ID"App"),
   MENU_ELEMENT_LINE_VARRO("Coolant temp before cooler",       PASSWORD_LEVEL_END_CUSTOMER,        (char*)"PT_CNVC_CoolantHotTemp",                     LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Coolant temp after cooler",        PASSWORD_LEVEL_END_CUSTOMER,        (char*)"PT_CNVC_CoolantCooledTemp",                  LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Dissipated heat power",            PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_CNVC_HeatPower",                           LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_LINK("Status",                            PASSWORD_LEVEL_END_CUSTOMER,        "M_Status2",                        "G_InverterCooling_MT_Type1"),
   MENU_ELEMENT_LINE_LINK("Parameter",                         PASSWORD_LEVEL_END_CUSTOMER,        "M_Parameter3",                     "G_InverterCooling_MT_Type1"),
   MENU_ELEMENT_LINE_LINK("Service",                           PASSWORD_LEVEL_ADMINISTRATOR,       "M_Service4",                       "G_InverterCooling_MT_Type1"),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_Status2Menu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_Status2",                        PASSWORD_LEVEL_END_CUSTOMER),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_Status2MenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("STATUS",                            PASSWORD_LEVEL_END_CUSTOMER,        "M_InverterCooling",                "G_InverterCooling_MT_Type1"),
   MENU_ELEMENT_LINE_VARRO("Water pump state",                 PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_CNVC_PumpStateTxt",                        LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Water pump contactor",             PASSWORD_LEVEL_END_CUSTOMER,        (char*)"DO_CNVC_CoolantPump",                        LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Water pump MCB",                   PASSWORD_LEVEL_END_CUSTOMER,        (char*)"DI_CNVC_PumpMCB",                            LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Indoor cooling fan state",         PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_CNVC_CoolantFanStateTxt",                  LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Indoor cooling fan contactor",     PASSWORD_LEVEL_END_CUSTOMER,        (char*)"DO_CNVC_CoolantFan",                         LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Indoor cooling fan MCB",           PASSWORD_LEVEL_END_CUSTOMER,        (char*)"DI_CNVC_CoolantFanMCB",                      LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Outdoor cooling fan contactor",    PASSWORD_LEVEL_END_CUSTOMER,        (char*)"DO_CNVC_OutdoorFanCont",                     LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Outdoor cooling fan speed",        PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_CNVC_OutdoorFanSpeedPct",                  LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Outdoor cooling fan MCB",          PASSWORD_LEVEL_END_CUSTOMER,        (char*)"DI_CNVC_OutdoorFanMCB",                      LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Outdoor cooling fan health",       PASSWORD_LEVEL_END_CUSTOMER,        (char*)"DI_CNVC_OutdoorFanHealth",                   LINE_FORMAT_NONE),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_Parameter3Menu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_Parameter3",                     PASSWORD_LEVEL_END_CUSTOMER),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_Parameter3MenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("PARAMETER",                         PASSWORD_LEVEL_END_CUSTOMER,        "M_InverterCooling",                "G_InverterCooling_MT_Type1"),
   MENU_ELEMENT_LINE_LINK("Help",                              PASSWORD_LEVEL_END_CUSTOMER,        "M_Help",                           "G_InverterCooling_MT_Type1"),
   MENU_ELEMENT_LINE_VARRW("Cooling system stop delay",        PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_CNVC_SystemStopDelay",                     LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Max overal temperature",           PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_CNVC_MaxOveralTemp",                       LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Max coolant temperature",          PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_CNVC_MaxCoolantTemp",                      LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Min IGBT temperature",             PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_CNVC_MinIGBTTemp",                         LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Coolant flow rate [l/min]",        PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_CNVC_CoolantFlowRate",                     LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_LINK("Fan",                               PASSWORD_LEVEL_END_CUSTOMER,        "M_Fan",                            "G_InverterCooling_MT_Type1"),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_HelpMenu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_Help",                           PASSWORD_LEVEL_END_CUSTOMER),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_HelpMenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("HELP",                              PASSWORD_LEVEL_END_CUSTOMER,        "M_Parameter3",                     "G_InverterCooling_MT_Type1"),
   MENU_ELEMENT_LINE_TEXT("Min IGBT temp stops pump when IGBTs are too cold.", PASSWORD_LEVEL_END_CUSTOMER),
   MENU_ELEMENT_LINE_TEXT("Coolant flow rate is used for heat dissipation calculation", PASSWORD_LEVEL_END_CUSTOMER),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_FanMenu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_Fan",                            PASSWORD_LEVEL_END_CUSTOMER),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_FanMenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("FAN",                               PASSWORD_LEVEL_END_CUSTOMER,        "M_Parameter3",                     "G_InverterCooling_MT_Type1"),
   MENU_ELEMENT_LINE_VARRW("Indoor fan temp ON",               PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_CNVC_FanTempON",                           LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Indoor fan temp OFF",              PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_CNVC_FanTempOFF",                          LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Outdoor fan temp OFF",             PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_CNVC_OutFanTempOFF",                       LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Outdoor fan temp 1",               PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_CNVC_OutFanTemp1",                         LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Outdoor fan speed 1",              PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_CNVC_OutFanSpeedPct1",                     LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Outdoor fan temp 2",               PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_CNVC_OutFanTemp2",                         LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Outdoor fan speed 2",              PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_CNVC_OutFanSpeedPct2",                     LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_LINK("Fan Interface",                     PASSWORD_LEVEL_END_CUSTOMER,        "M_FanInterface",                   "G_InverterCooling_MT_Type1"),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_FanInterfaceMenu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_FanInterface",                   PASSWORD_LEVEL_END_CUSTOMER),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_FanInterfaceMenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("FAN INTERFACE",                     PASSWORD_LEVEL_END_CUSTOMER,        "M_Fan",                            "G_InverterCooling_MT_Type1"),
   MENU_ELEMENT_LINE_VARRW("Outdoor fan 0% speed volt",        PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_CNVC_OutFanSpeedVolt_0",                   LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Outdoor fan 100% speed volt",      PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_CNVC_OutFanSpeedVolt_100",                 LINE_FORMAT_NONE),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_Service4Menu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_Service4",                       PASSWORD_LEVEL_ADMINISTRATOR),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_Service4MenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("SERVICE",                           PASSWORD_LEVEL_ADMINISTRATOR,       "M_InverterCooling",                "G_InverterCooling_MT_Type1"),
   MENU_ELEMENT_LINE_VARRO("Water pump state",                 PASSWORD_LEVEL_SERVICE,             (char*)"V_CNVC_PumpStateTxt",                        LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Water pump service",               PASSWORD_LEVEL_SERVICE,             (char*)"V_CNVC_PumpService",                         LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Indoor cooling fan state",         PASSWORD_LEVEL_SERVICE,             (char*)"V_CNVC_CoolantFanStateTxt",                  LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Indoor cooling fan service",       PASSWORD_LEVEL_SERVICE,             (char*)"V_CNVC_CoolantFanService",                   LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Outdoor cooling fan service",      PASSWORD_LEVEL_SERVICE,             (char*)"V_CNVC_OutdoorFanService",                   LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Outdoor fan service speed",        PASSWORD_LEVEL_ADMINISTRATOR,       (char*)"V_CNVC_OutdoorFanSpeedPctService",           LINE_FORMAT_NONE),
};
// Creating parameters for multiplexed categories
//-----------------------------------------------------------------------
static struct multiplexed_info_struct M_InverterCoolingMultiplexedCategoriesParameters[] =
{
0};

//-----------------------------------------------------------------------
// CREATE MENUS               CREATE MENUS               CREATE MENUS
//-----------------------------------------------------------------------

// Memory reservation
//-----------------------------------------------------------------------
static struct menu_group_struct ObjGroup[1];

// Creating the menus
//-----------------------------------------------------------------------
STATUS InverterCooling_MT_Type1MenuAppInit(U8 ModuleState, OS_MEMORY_POOL* pPool)
{
   STATUS Status;

   if (ModuleState == APP_INIT1)
   {
      /* Create application group */
      Status = OS_CreateMenuGroup(ObjGroup, M_InverterCoolingLinkToLocalMenu[0].LinkGroup);
      STATUS_LINE_VAR_RETURN_VALUE(Status);
   }

   Status = CreateAndInitializeMenu(ModuleState,
                                    M_InverterCoolingMenuLines[0].LinkGroup,
                                    M_InverterCoolingMenuLines[0].LinkName,
                                    ELEMENT(M_InverterCoolingLinkToLocalMenu),
                                    M_InverterCoolingLinkToLocalMenu[0].LinkGroup,
                                    ELEMENT(M_InverterCoolingMenu),
                                    M_InverterCoolingLinkToLocalMenu[0].LinkName,
                                    ELEMENT(M_InverterCoolingMenuLines),
                                    pPool,
                                    M_InverterCoolingMultiplexedCategoriesParameters);
   STATUS_LINE_VAR_RETURN_VALUE(Status);

   Status = CreateAndInitializeMenu(ModuleState,
                                    M_Status2MenuLines[0].LinkGroup,
                                    M_Status2MenuLines[0].LinkName,
                                    NULL,
                                    0,
                                    M_InverterCoolingMenuLines[4].LinkGroup,
                                    ELEMENT(M_Status2Menu),
                                    M_InverterCoolingMenuLines[4].LinkName,
                                    ELEMENT(M_Status2MenuLines),
                                    pPool,
                                    M_InverterCoolingMultiplexedCategoriesParameters);
   STATUS_LINE_VAR_RETURN_VALUE(Status);

   Status = CreateAndInitializeMenu(ModuleState,
                                    M_Parameter3MenuLines[0].LinkGroup,
                                    M_Parameter3MenuLines[0].LinkName,
                                    NULL,
                                    0,
                                    M_InverterCoolingMenuLines[5].LinkGroup,
                                    ELEMENT(M_Parameter3Menu),
                                    M_InverterCoolingMenuLines[5].LinkName,
                                    ELEMENT(M_Parameter3MenuLines),
                                    pPool,
                                    M_InverterCoolingMultiplexedCategoriesParameters);
   STATUS_LINE_VAR_RETURN_VALUE(Status);

   Status = CreateAndInitializeMenu(ModuleState,
                                    M_HelpMenuLines[0].LinkGroup,
                                    M_HelpMenuLines[0].LinkName,
                                    NULL,
                                    0,
                                    M_Parameter3MenuLines[1].LinkGroup,
                                    ELEMENT(M_HelpMenu),
                                    M_Parameter3MenuLines[1].LinkName,
                                    ELEMENT(M_HelpMenuLines),
                                    pPool,
                                    M_InverterCoolingMultiplexedCategoriesParameters);
   STATUS_LINE_VAR_RETURN_VALUE(Status);

   Status = CreateAndInitializeMenu(ModuleState,
                                    M_FanMenuLines[0].LinkGroup,
                                    M_FanMenuLines[0].LinkName,
                                    NULL,
                                    0,
                                    M_Parameter3MenuLines[7].LinkGroup,
                                    ELEMENT(M_FanMenu),
                                    M_Parameter3MenuLines[7].LinkName,
                                    ELEMENT(M_FanMenuLines),
                                    pPool,
                                    M_InverterCoolingMultiplexedCategoriesParameters);
   STATUS_LINE_VAR_RETURN_VALUE(Status);

   Status = CreateAndInitializeMenu(ModuleState,
                                    M_FanInterfaceMenuLines[0].LinkGroup,
                                    M_FanInterfaceMenuLines[0].LinkName,
                                    NULL,
                                    0,
                                    M_FanMenuLines[8].LinkGroup,
                                    ELEMENT(M_FanInterfaceMenu),
                                    M_FanMenuLines[8].LinkName,
                                    ELEMENT(M_FanInterfaceMenuLines),
                                    pPool,
                                    M_InverterCoolingMultiplexedCategoriesParameters);
   STATUS_LINE_VAR_RETURN_VALUE(Status);

   Status = CreateAndInitializeMenu(ModuleState,
                                    M_Service4MenuLines[0].LinkGroup,
                                    M_Service4MenuLines[0].LinkName,
                                    NULL,
                                    0,
                                    M_InverterCoolingMenuLines[6].LinkGroup,
                                    ELEMENT(M_Service4Menu),
                                    M_InverterCoolingMenuLines[6].LinkName,
                                    ELEMENT(M_Service4MenuLines),
                                    pPool,
                                    M_InverterCoolingMultiplexedCategoriesParameters);
   STATUS_LINE_VAR_RETURN_VALUE(Status);

   return OS_SUCCESS;
}

#define CREATE_MENU

//-----------------------------------------------------------------------
//               BUTTONS FUNCTIONS FORWARD DECLARATIONS
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// BUTTONS                       BUTTONS                      BUTTONS
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
//             SET/RESET FUNCTIONS FORWARD DECLARATIONS
//-----------------------------------------------------------------------
static U8 StatusSetFunc2918(void);
static U8 StatusResetFunc2918(void);
static U8 StatusSetFunc2920(void);
static U8 StatusResetFunc2920(void);
static U8 StatusSetFunc2917(void);
static U8 StatusResetFunc2917(void);
static U8 StatusSetFunc5200(void);
static U8 StatusResetFunc5200(void);
static U8 StatusSetFunc5201(void);
static U8 StatusResetFunc5201(void);
//-----------------------------------------------------------------------
// STATUSCODES                 STATUSCODES                 STATUSCODES
//-----------------------------------------------------------------------

static struct sts_statuscode_structure StatusCodes[] =
{
   STS_CODE_ELEMENT("Cnv coolant pump MCB",   20*SEC,    2918,      STATUSCODE_UPDATE_TYPE_POLLING,         PASSWORD_LEVEL_SERVICE,            STATUSCODE_TIMER_TYPE_CONSTANT,     STATUSCODE_TIMER_TYPE_CONSTANT,     STATUSCODE_RESET_TYPE_AUTOMATIC,    STATUSCODE_PRIORITY_LOW,       23,   0,    32,   NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         StatusSetFunc2918,       StatusResetFunc2918,     BRAKE_PROG_50,       BRAKE_PROG_0,        BRAKE_PROG_MAX,      NULL,                PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    YAW_PROG_0,          YAW_PROG_0,          YAW_PROG_240,        NULL,                PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,    0,    255,  NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            1,  PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      1000,      20,        1000,      NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    1*SEC,     SETDELAY_MIN,   SETDELAY_MAX,   NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         0,         RESETDELAY_MIN, RESETDELAY_MAX, NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         0,         REPEATTIMES_MIN,     REPEATTIMES_MAX,     NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         REPEATPERIOD_MIN,    REPEATPERIOD_MAX,    NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         REPEATCODE_MIN,      REPEATCODE_MAX,      NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         TIMEOUTPERIOD_MIN,   TIMEOUTPERIOD_MAX,   NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         TIMEOUTCODE_MIN,     TIMEOUTCODE_MAX,     NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         NULL),
   STS_CODE_ELEMENT("Cnv coolant fan MCB",    20*SEC,    2920,      STATUSCODE_UPDATE_TYPE_POLLING,         PASSWORD_LEVEL_SERVICE,            STATUSCODE_TIMER_TYPE_CONSTANT,     STATUSCODE_TIMER_TYPE_CONSTANT,     STATUSCODE_RESET_TYPE_AUTOMATIC,    STATUSCODE_PRIORITY_LOW,       23,   0,    32,   NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         StatusSetFunc2920,       StatusResetFunc2920,     BRAKE_PROG_50,       BRAKE_PROG_0,        BRAKE_PROG_MAX,      NULL,                PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    YAW_PROG_0,          YAW_PROG_0,          YAW_PROG_240,        NULL,                PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,    0,    255,  NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            1,  PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      1000,      20,        1000,      NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    1*SEC,     SETDELAY_MIN,   SETDELAY_MAX,   NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         0,         RESETDELAY_MIN, RESETDELAY_MAX, NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         0,         REPEATTIMES_MIN,     REPEATTIMES_MAX,     NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         REPEATPERIOD_MIN,    REPEATPERIOD_MAX,    NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         REPEATCODE_MIN,      REPEATCODE_MAX,      NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         TIMEOUTPERIOD_MIN,   TIMEOUTPERIOD_MAX,   NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         TIMEOUTCODE_MIN,     TIMEOUTCODE_MAX,     NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         NULL),
   STS_CODE_ELEMENT("Cnv coolant temp.",      20*SEC,    2917,      STATUSCODE_UPDATE_TYPE_POLLING,         PASSWORD_LEVEL_SERVICE,            STATUSCODE_TIMER_TYPE_CONSTANT,     STATUSCODE_TIMER_TYPE_CONSTANT,     STATUSCODE_RESET_TYPE_AUTOMATIC,    STATUSCODE_PRIORITY_LOW,       23,   0,    32,   NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_LICENCE_PROGRAMMER, StatusSetFunc2917,       StatusResetFunc2917,     BRAKE_PROG_50,       BRAKE_PROG_0,        BRAKE_PROG_MAX,      NULL,                PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,                   YAW_PROG_0,          YAW_PROG_MAX,        NULL,                PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,    0,    255,  NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            1,  PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      1000,      20,        1000,      NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    1*SEC,     SETDELAY_MIN,   SETDELAY_MAX,   NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      1*SEC,     RESETDELAY_MIN, RESETDELAY_MAX, NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      0,         REPEATTIMES_MIN,     REPEATTIMES_MAX,     NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         REPEATPERIOD_MIN,    REPEATPERIOD_MAX,    NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         REPEATCODE_MIN,      REPEATCODE_MAX,      NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         TIMEOUTPERIOD_MIN,   TIMEOUTPERIOD_MAX,   NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_LICENCE_PROGRAMMER, 0,         TIMEOUTCODE_MIN,     TIMEOUTCODE_MAX,     NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            NULL),
   STS_CODE_ELEMENT("Outdoor cnv fan MCB",    20*SEC,    5200,      STATUSCODE_UPDATE_TYPE_POLLING,         PASSWORD_LEVEL_SERVICE,            STATUSCODE_TIMER_TYPE_CONSTANT,     STATUSCODE_TIMER_TYPE_CONSTANT,     STATUSCODE_RESET_TYPE_AUTOMATIC,    STATUSCODE_PRIORITY_LOW,       23,   0,    32,   NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         StatusSetFunc5200,       StatusResetFunc5200,     BRAKE_PROG_50,       BRAKE_PROG_0,        BRAKE_PROG_MAX,      NULL,                PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,                   YAW_PROG_0,          YAW_PROG_240,        NULL,                PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,    0,    255,  NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            1,  PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      1000,      20,        1000,      NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    10*SEC,    SETDELAY_MIN,   SETDELAY_MAX,   NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         0,         RESETDELAY_MIN, RESETDELAY_MAX, NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         0,         REPEATTIMES_MIN,     REPEATTIMES_MAX,     NULL,      PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         REPEATPERIOD_MIN,    REPEATPERIOD_MAX,    NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         REPEATCODE_MIN,      REPEATCODE_MAX,      NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         TIMEOUTPERIOD_MIN,   TIMEOUTPERIOD_MAX,   NULL,      PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         TIMEOUTCODE_MIN,     TIMEOUTCODE_MAX,     NULL,      PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         NULL),
   STS_CODE_ELEMENT("Outdoor cnv fan fault",  20*SEC,    5201,      STATUSCODE_UPDATE_TYPE_POLLING,         PASSWORD_LEVEL_SERVICE,            STATUSCODE_TIMER_TYPE_CONSTANT,     STATUSCODE_TIMER_TYPE_CONSTANT,     STATUSCODE_RESET_TYPE_AUTOMATIC,    STATUSCODE_PRIORITY_LOW,       24,   0,    32,   NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         StatusSetFunc5201,       StatusResetFunc5201,     BRAKE_PROG_0,        BRAKE_PROG_0,        BRAKE_PROG_MAX,      NULL,                PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,                   YAW_PROG_0,          YAW_PROG_240,        NULL,                PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,    0,    255,  NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            1,  PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      1000,      20,        1000,      NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    10*SEC,    SETDELAY_MIN,   SETDELAY_MAX,   NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         0,         RESETDELAY_MIN, RESETDELAY_MAX, NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         0,         REPEATTIMES_MIN,     REPEATTIMES_MAX,     NULL,      PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         REPEATPERIOD_MIN,    REPEATPERIOD_MAX,    NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         REPEATCODE_MIN,      REPEATCODE_MAX,      NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         TIMEOUTPERIOD_MIN,   TIMEOUTPERIOD_MAX,   NULL,      PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         TIMEOUTCODE_MIN,     TIMEOUTCODE_MAX,     NULL,      PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         NULL),
};

static STATUS_CODE_CONTROL_BLOCK StatusCodeControlBlock;

static STATUS LocalStatusCodeInit(void)
{
   STATUS LocalStatus;

   LocalStatus = OS_StatusCodeInit(STATUSCODE_INTERFACE_VERSION,
                                   &StatusCodeControlBlock,
                                   StatusCodes,
                                   sizeof(StatusCodes)/sizeof(StatusCodes[0]),
                                   AppLocalParameterPosition(),
                                   AppBackupPosition());
   STATUS_LINE_VAR_RETURN_CONST(LocalStatus, ERR_3);

   return OS_SUCCESS;
}

#define CREATE_STATUS_CODES

//-----------------------------------------------------------------------
// MODIFIABLE                  MODIFIABLE                   MODIFIABLE
//-----------------------------------------------------------------------

extern const char InverterCooling_MT_Type1AppGroupName[];
extern const char InverterCooling_MT_Type1AppMenuName[];

static void Init_Structures_From_Conf_File(void)
{
   M_InverterCoolingMenuLines[0].LinkName = (char*)InverterCooling_MT_Type1AppMenuName;
   M_InverterCoolingMenuLines[0].LinkGroup = (char*)InverterCooling_MT_Type1AppGroupName;
}

//-----------------------------------------------------------------------
// AUTOGENERATED END        AUTOGENERATED END        AUTOGENERATED END
//-----------------------------------------------------------------------
//}

#undef AUTOGENERATED_PART

//-----------------------------------------------------------------------
// USER DEFINITIONS         USER DEFINITIONS         USER DEFINITIONS
//-----------------------------------------------------------------------
//-----------------------------------------------------------------------

#ifndef AUTO_TEXT
#define AUTO_TEXT                  "Auto"
#endif

#ifndef FORCED_OFF_TEXT
#define FORCED_OFF_TEXT            "Forced OFF"
#endif
#ifndef FORCED_ON_TEXT
#define FORCED_ON_TEXT             "Forced ON"
#endif

#ifndef UNDEFINED_TEXT
#define UNDEFINED_TEXT             "Undefined"
#endif

#ifndef BLOCKED_TEXT
#define BLOCKED_TEXT               "Blocked"
#endif

#ifndef STOPPED_TEXT
#define STOPPED_TEXT               "Stopped"
#endif

#ifndef RUNNING_TEXT
#define RUNNING_TEXT               "Running"
#endif

#ifndef SERVICE_TEXT
#define SERVICE_TEXT               "Service"
#endif

#define HIGH 1
#define LOW  0

#ifndef AUTO_MODE
#define AUTO_MODE               0
#endif

#ifndef FORCED_OFF
#define FORCED_OFF              1
#endif

#ifndef FORCED_ON
#define FORCED_ON               2
#endif

#ifndef BLOCKED
#define BLOCKED                 0
#endif

#ifndef STOPPED
#define STOPPED                 1
#endif

#ifndef RUNNING
#define RUNNING                 2
#endif

#ifndef SERVICE
#define SERVICE                 3
#endif

static U8 OldPumpState = 0xff;
static U8 OldIndoorFanState = 0xff;
static U8 OldOutdoorFanState = 0xff;

static U8 V_CNVC_PumpState = 0;
static U8 V_CNVC_CoolantFanState = 0;
static U8 V_InverterWaterCoolState = 0;
static U8 OutdoorFanState = 0;

static char V_CNVC_PumpStateTxt[31];
static char V_CNVC_CoolantFanStateTxt[31];

// ID of state variables
static varid_t   V_InverterWaterPumpStateVariableID;
static varid_t   V_InverterWaterCoolFanStateVariableID;
static varid_t   V_InverterWaterCoolStateVariableID;

static varid_t   V_InverterWaterPumpStateTxtVariableID;
static varid_t   V_InverterWaterCoolFanStateTxtVariableID;

//-----------------------------------------------------------------------
static STATUS IWCSInterfaceInit(void)
{
    STATUS Status;
    //--- Write state variable -------------------------------------------
    Status = OS_VarDB_GetVariableID("V_CNVC_PumpState", &V_InverterWaterPumpStateVariableID);
    Status = OS_VarDB_UpdateVariableConditional(V_InverterWaterPumpStateVariableID, &V_CNVC_PumpState, sizeof(V_CNVC_PumpState));
    STATUS_LINE_VAR_RETURN_VALUE(Status)

    //--- Write state text variable -------------------------------------
    Status = OS_VarDB_GetVariableID("V_CNVC_PumpStateTxt", &V_InverterWaterPumpStateTxtVariableID);
    Status = OS_VarDB_UpdateVariableConditional(V_InverterWaterPumpStateTxtVariableID, &V_CNVC_PumpStateTxt, sizeof(V_CNVC_PumpStateTxt));
    STATUS_LINE_VAR_RETURN_VALUE(Status)

    //--- Write status variable -------------------------------------
    Status = OS_VarDB_GetVariableID("V_CNVC_CoolantFanState", &V_InverterWaterCoolFanStateVariableID);
    Status = OS_VarDB_UpdateVariableConditional(V_InverterWaterCoolFanStateVariableID, &V_CNVC_CoolantFanState, sizeof(V_CNVC_CoolantFanState));
    STATUS_LINE_VAR_RETURN_VALUE(Status)

    //--- Write status text variable -----------------------------------------
    Status = OS_VarDB_GetVariableID("V_CNVC_CoolantFanStateTxt", &V_InverterWaterCoolFanStateTxtVariableID);
    Status = OS_VarDB_UpdateVariableConditional(V_InverterWaterCoolFanStateTxtVariableID, &V_CNVC_CoolantFanStateTxt, sizeof(V_CNVC_CoolantFanStateTxt));
    STATUS_LINE_VAR_RETURN_VALUE(Status)

    // V_InverterWaterCoolState
    // V_InverterWaterCoolStateTxt

    return OS_SUCCESS;
}



//________________________________________________________________________
static void WriteState(U8 State, U8 OldState, char* Text, U8 Size, varid_t* StateID, varid_t* StateTxtID)
{
    if (State != OldState)
    {
        switch (State)
        {
            case FORCED_OFF        : { strncpy(Text, FORCED_OFF_TEXT        ,    Size);} break;
            case FORCED_ON         : { strncpy(Text, FORCED_ON_TEXT         ,    Size);} break;
            case AUTO_MODE         : { strncpy(Text, AUTO_TEXT              ,    Size);} break;
            default                : { strncpy(Text, UNDEFINED_TEXT         ,    Size);} break;
        }
        OS_VarDB_UpdateVariable(*StateID   , &State, sizeof(State));
        OS_VarDB_UpdateVariable(*StateTxtID, Text  , Size);
    }
    OldState = State;
}


//-----------------------------------------------------------------------
// SET/RESET FUNCTIONS    SET/RESET FUNCTIONS    SET/RESET FUNCTIONS
//-----------------------------------------------------------------------

static U8 StatusSetFunc2918(void)
{
    if (WPlineError()) { return 0; }
    if (LOW == DI_CNVC_PumpMCB) { return 1; }
    return 0;
}

static U8 StatusResetFunc2918(void)
{
    return !StatusSetFunc2918();
}

static U8 StatusSetFunc2920(void)
{
    if (WPlineError()) { return 0; }
    if (LOW == DI_CNVC_CoolantFanMCB) { return 1; }
    return 0;
}

static U8 StatusResetFunc2920(void)
{
    return !StatusSetFunc2920();
}

static U8 StatusSetFunc2917(void)
{
    if (PT_CNVC_CoolantCooledTemp > P_CNVC_MaxCoolantTemp) { return 1; }
    return 0;
}

static U8 StatusResetFunc2917(void)
{
    return !StatusSetFunc2917();
}

static U8 StatusSetFunc5200(void)
{
    if (WPlineError()) { return 0; }
    if (!DI_CNVC_OutdoorFanMCB) { return 1; }
    return 0;
}

static U8 StatusResetFunc5200(void)
{
    return !StatusSetFunc5200();
}

static U8 StatusSetFunc5201(void)
{
    if (WPlineError()) { return 0; }
    if (!DI_CNVC_OutdoorFanHealth && DO_CNVC_OutdoorFanCont) { return 1; }
    return 0;
}

static U8 StatusResetFunc5201(void)
{
    if (WPlineError()) { return 0; }
    if (DI_CNVC_OutdoorFanHealth && DO_CNVC_OutdoorFanCont) { return 1; }
    return 0;
}
//-----------------------------------------------------------------------
// DRIVER FUNCTION         DRIVER FUNCTION         DRIVER FUNCTION
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// INIT                   INIT                     INIT
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// CONTROL                CONTROL                 CONTROL
//-----------------------------------------------------------------------

static struct StandardTimerVarStruct IWCS_Timer =
{
    0,                               // Timer value [ms]
    &P_CNVC_SystemStopDelay, // TimeMax value [ms]
    TIMER_100MS,                     // Internal variable, always set to 0
    TIMER_STOP,                      // TIMER_DOWN / TIMER_STOP / TIMER_UP
    0                                // Standard timer called flag.
};

static U32  IWCS_TimerValue;

//______________________________________________________________________________________
static void I_WCS_PumpAuto(void)
{
    if (!DI_CNVC_PumpMCB)	// block AUTO operation when MCB is off
    {
        DO_CNVC_CoolantPump = OFF;
        return;
    }

    U8 i;
    U8 flag = 0;

    for (i = 0; i < CNV_UNIT_CNT; i++)
    {
        if (V_CNV_State >= CNV_GRID_STARTING)
        {
            flag++;
        }
    }
    if (flag)
    {
        if (V_CNV_MinIGBTTemp >= P_CNVC_MinIGBTTemp)
        {
        	DO_CNVC_CoolantPump = ON;
        	ResetTimer(&IWCS_Timer);
        }
    }
    else
    {
        StartTimer(&IWCS_Timer);
        IWCS_TimerValue = 0;
        StandardTimer(&IWCS_Timer);
        IWCS_TimerValue = P_CNVC_SystemStopDelay - IWCS_Timer.TimerValue;

        if (!IWCS_TimerValue && (V_CNV_MaxIGBTTemp <= P_CNVC_MaxOveralTemp))
        {
            DO_CNVC_CoolantPump = OFF;
        }
        else if (V_CNV_MinIGBTTemp < P_CNVC_MinIGBTTemp)
        {
        	DO_CNVC_CoolantPump = OFF;
        }
    }
    V_CNVC_PumpState = AUTO_MODE;
}


static void I_WCS_FanAuto(void)
{
    if (!DI_CNVC_CoolantFanMCB)	// block AUTO operation when MCB is off
    {
        DO_CNVC_CoolantFan = OFF;
        return;
    }
    
    if ((DO_CNVC_CoolantPump == ON) && (V_CNV_MaxIGBTTemp >= P_CNVC_FanTempON))
    {
        DO_CNVC_CoolantFan = ON;
    }
    else if ((DO_CNVC_CoolantPump == OFF) || (V_CNV_MaxIGBTTemp <= P_CNVC_FanTempOFF))
    {
        DO_CNVC_CoolantFan = OFF;
    }

    V_CNVC_CoolantFanState = AUTO_MODE;
}


static void PumpControl()
{
    switch (V_CNVC_PumpService)
    {
        case AUTO_MODE:
        {
            I_WCS_PumpAuto();
            break;
        }
        case FORCED_ON:
        {
            DO_CNVC_CoolantPump = ON;
            V_CNVC_PumpState = FORCED_ON;
            break;
        }
        case FORCED_OFF:
        {
            DO_CNVC_CoolantPump = OFF;
            V_CNVC_PumpState = FORCED_OFF;
            break;
        }
        default:
            break;
    }

    WriteState(V_CNVC_PumpState , OldPumpState , V_CNVC_PumpStateTxt , sizeof V_CNVC_PumpStateTxt, &V_InverterWaterPumpStateVariableID, &V_InverterWaterPumpStateTxtVariableID);
}


// Cooling fan inside tower base cooling housing
static void IndoorFanControl()
{
    switch (V_CNVC_CoolantFanService)
    {
        case AUTO_MODE:
        {
            I_WCS_FanAuto();
            break;
        }
        case FORCED_ON:
        {
            DO_CNVC_CoolantFan = ON;
            V_CNVC_CoolantFanState = FORCED_ON;
            break;
        }
        case FORCED_OFF:
        {
            DO_CNVC_CoolantFan = OFF;
            V_CNVC_CoolantFanState = FORCED_OFF;
            break;
        }
        default:
            break;
    }

    WriteState(V_CNVC_CoolantFanState , OldIndoorFanState , V_CNVC_CoolantFanStateTxt , sizeof V_CNVC_CoolantFanStateTxt, &V_InverterWaterCoolFanStateVariableID, &V_InverterWaterCoolFanStateTxtVariableID);
}


static S16 LinearConversion(S16 Value, S16 MinIn, S16 MaxIn, S16 MinOut, S16 MaxOut)
{
    S16 Res;

    if (MaxIn != MinIn) { Res = MinOut + ((S64)Value - MinIn) * (MaxOut - MinOut) / (MaxIn - MinIn); }
    else                { Res = MinOut; }

    return Res;
}

static S16 LinearLimConversion(S16 Value, S16 MinIn, S16 MaxIn, S16 MinOut, S16 MaxOut)
{
    S16 Res;

    Res = LinearConversion(Value, MinIn, MaxIn, MinOut, MaxOut);

    if (Res < MinOut) { Res = MinOut; }
    else if (Res > MaxOut) { Res = MaxOut; }

    return Res;
}


static S16 SelectFanSpeedPct(S16 Temperature)
{
    return LinearLimConversion(Temperature, P_CNVC_OutFanTemp1, P_CNVC_OutFanTemp2, P_CNVC_OutFanSpeedPct1, P_CNVC_OutFanSpeedPct2);
}


static S16 SelectFanSpeedVolt(S16 Percent)
{
    return LinearLimConversion(Percent, 0, 1000, P_CNVC_OutFanSpeedVolt_0, P_CNVC_OutFanSpeedVolt_100);
}


static void OutdoorFanAutoControl()
{
    if(!DI_CNVC_OutdoorFanMCB)	// block AUTO operation when MCB is off
    {
    	DO_CNVC_OutdoorFanCont = false;
    	V_CNVC_OutdoorFanSpeedPct = 0;
    	AO_CNVC_OutdoorFanSpeed = SelectFanSpeedVolt(V_CNVC_OutdoorFanSpeedPct);
    }
    
    if ((DO_CNVC_CoolantPump == ON) && V_CNV_MaxIGBTTemp >= P_CNVC_OutFanTemp1)
    {
        V_CNVC_OutdoorFanSpeedPct = SelectFanSpeedPct(V_CNV_MaxIGBTTemp);
        DO_CNVC_OutdoorFanCont = true;
        AO_CNVC_OutdoorFanSpeed = SelectFanSpeedVolt(V_CNVC_OutdoorFanSpeedPct);
    }
    else if ((DO_CNVC_CoolantPump == OFF) || V_CNV_MaxIGBTTemp <= P_CNVC_OutFanTempOFF)
    {
        // contactor stays always on //DO_CNVC_OutdoorFanCont = false;
        V_CNVC_OutdoorFanSpeedPct = 0;
        AO_CNVC_OutdoorFanSpeed = SelectFanSpeedVolt(V_CNVC_OutdoorFanSpeedPct);
    }
}


// Converter coolant cooling fan outside of tower
static void OutdoorFanControl()
{
    switch (V_CNVC_OutdoorFanService)
    {
        case AUTO_MODE:
        {
            OutdoorFanAutoControl();
            break;
        }
        case FORCED_ON:
        {
            DO_CNVC_OutdoorFanCont = true;
            V_CNVC_OutdoorFanSpeedPct = V_CNVC_OutdoorFanSpeedPctService;
            AO_CNVC_OutdoorFanSpeed = SelectFanSpeedVolt(V_CNVC_OutdoorFanSpeedPct);
            break;
        }
        case FORCED_OFF:
        {
            DO_CNVC_OutdoorFanCont = false;
            V_CNVC_OutdoorFanSpeedPct = 0;
            AO_CNVC_OutdoorFanSpeed = SelectFanSpeedVolt(V_CNVC_OutdoorFanSpeedPct);
            break;
        }
        default:
            break;
    }
}



/*
   Vedelikust 1 s jooksul eraldunud/neeldunud soojushulga(J) arvutus.

   vooluhulk - 228 l/min
   temp muutus - 2,59 K
   vedeliku erikaal - 1,07 kg/l
   vedeliku erisoojus - 3433 J/(kgxK)

   ( Andmed vedeliku temperatuuril ca 30 kraadi C. )

   (228 / 60) x 1,07 x 2,59 x 3433 = 36152 J = 36 kJ == 36 kW
*/
static void CalcHeatDissipation()
{
    static S16 delta;

    // calculate dissipated power only when pump is running
    if (DO_CNVC_CoolantPump)
    {
        delta = PT_CNVC_CoolantHotTemp - PT_CNVC_CoolantCooledTemp;   /*0,1 degrees precision*/
        V_CNVC_HeatPower = (S16)((S64)P_CNVC_CoolantFlowRate * 107 * delta * 3433 / 6000000);
    }
    else
    {
        V_CNVC_HeatPower = 0;
    }
}


static STATUS LocalCtrl(void)
{
    STATUS LocalStatus = 0;

    PumpControl();
    IndoorFanControl();
    OutdoorFanControl();
    CalcHeatDissipation();

    return LocalStatus;
}

//-----------------------------------------------------------------------
// MAIN CALL             MAIN CALL               MAIN CALL
//-----------------------------------------------------------------------

STATUS InverterCooling_MT_Type1(U8 ModuleState, OS_MEMORY_POOL* MemPool, U32* Arg3)
{
    STATUS LocalStatus = 0;

    // Version check
    if (ModuleState == APP_INIT1)
    {
        LocalStatus = OS_ValidateAPI(API_VERSION_MAJOR,
                                     API_VERSION_MINOR,
                                     OS_LinkTime,
                                     ReleaseTag,
                                     __MODULE__
                                    );
        if (OS_SUCCESS != LocalStatus)
        {
            return LocalStatus;
        }
    }
#ifdef READ_VARS
    // Read inputdata
    LocalStatus = InputReferenceRoutine(ModuleState);
    STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif
#ifdef COMMON_VDB_READ
    LocalStatus = ReadVdbWindow(ModuleState);
    STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif
    switch (ModuleState)
    {
        case APP_RUN :
        {
         #ifdef FUNCTION_BLOCKS_PRE_LOCAL_CONTROL
            LocalStatus = FunctionBlocksPreLocalCtrl( Interval );
            STATUS_LINE_VAR_RETURN_VALUE( LocalStatus );
         #endif

            LocalStatus = LocalCtrl();
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
        
         #ifdef FUNCTION_BLOCKS_POST_LOCAL_CONTROL
            LocalStatus = FunctionBlocksPostLocalCtrl( Interval );
            STATUS_LINE_VAR_RETURN_VALUE( LocalStatus );
         #endif

#ifdef WRITE_VARS
            // Write Outputdata
            LocalStatus = OutputReferenceRoutine(ModuleState);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif

#ifdef COMMON_VDB_WRITE
            LocalStatus = WriteVdbWindow(ModuleState);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif
            break;
        }
        case APP_INIT1 :
        {
            Init_Structures_From_Conf_File();

#ifdef CREATE_VARDB_VARS
            LocalStatus = CreateVarDbVars();
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif

#ifdef CREATE_MENU
            LocalStatus = InverterCooling_MT_Type1MenuAppInit(ModuleState, MemPool);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)

#ifdef MULTIPLEXIBLE_MENU
            LocalStatus = MenuArraysAppInit(ModuleState, MemPool);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif
#endif

#ifdef CREATE_VARDB_ARRAY_VARS
            LocalStatus = CreateVdbArrays(MemPool);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif

#ifdef CREATE_IO_VARS
            LocalStatus = CreateIOVars();
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif
            break;
        }
        case APP_INIT2 :
        {
#ifdef CREATE_MENU
#ifdef MULTIPLEXIBLE_MENU
            LocalStatus = MenuArraysAppInit(ModuleState, MemPool);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif
#endif

#ifdef CREATE_ALIASES
            size_t ErrorEntry = 0;
            LocalStatus = OS_VarDB_CreateAliases(AliasVars, sizeof(AliasVars) / sizeof(AliasVars[0]), &ErrorEntry);
            STATUS_LINE_VAR_RETURN_CONST(LocalStatus, ErrorEntry)
#endif

#ifdef VERIFY_ARRAY
            LocalStatus = VerifyArray(MemPool);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif

#ifdef VERIFY_VARIABLES
            LocalStatus = LocalIoCheck();
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif

#ifdef CREATE_BUTTONS
            LocalStatus = CreateButtons();
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif
            break;
        }
        case APP_INIT3 :
        {
#ifdef CREATE_SUMMATIONS
            LocalStatus = CreateSummations();
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif

#ifdef WRITE_VARS
            LocalStatus = InitOutputVars();
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif

#ifdef CREATE_STATUS_CODES
            LocalStatus = LocalStatusCodeInit();
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif

#ifdef CREATE_IO_VARS
            InverterCooling_MT_Type1SetLockValues();
#endif
            LocalStatus = IWCSInterfaceInit();
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
            break;
        }
        case APP_INIT4 :
        {
#ifdef CREATE_MENU
            LocalStatus = InverterCooling_MT_Type1MenuAppInit(ModuleState, MemPool);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)

#ifdef MULTIPLEXIBLE_MENU
            LocalStatus = MenuArraysAppInit(ModuleState, MemPool);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif
#endif
            break;
        }
        case APP_INIT5 :
        {
#ifdef VALIDATE_HASH
            LocalStatus = ValidateHash(InverterCooling_MT_Type1_copyright, MODULE_NAME, InverterCooling_MT_Type1_initialValues);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif

         #ifdef INIT_FUNCTION_BLOCKS
            LocalStatus = FunctionBlocksInit( Interval );
            STATUS_LINE_VAR_RETURN_VALUE( LocalStatus );
         #endif

            break;
        }
        default :
        {
            break;
        }
    }
    return OS_SUCCESS;
}
//-----------------------------------------------------------------------
