//*****************************PEPTOOL Header Start******************************
//                                                                               
//                         Copyright © 2015 Mita-Teknik.                         
//This software may only be used with WP4x00 Controllers delivered by Mita-Teknik
//                                                                               
//*******************************************************************************
//                                                                               
// $PEPTOOL version:9.0$                                                         
// $PEPTOOL file version:101$                                                    
//                                                                               
//*******************************************************************************
//                                                                               
// $Date: 2014/01/17 10:24:57 $                                                  
// $Author: MITA\obi $                                                           
// $RCSfile: WindMonitoring_Windar_LIDAR_Conf.c,v $                              
// $Revision: 1.6 $                                                              
//                                                                               
//******************************PEPTOOL Header End*******************************

//***********************************************************************
// OS header files
#include <os_main.h>
// App header files
#include <InitIo.h>

#define AUTOGENERATED_PART

#include <Turbdef.h>

//-----------------------------------------------------------------------
// AUTOGENERATED START     AUTOGENERATED START     AUTOGENERATED START
//-----------------------------------------------------------------------
char Lidar_Conf_copyright[] =
{
   67, 111, 112, 121, 114, 105, 103, 104, 116, 32, 63, 32, 50, 48, 49, 53,
   32, 77, 105, 116, 97, 45, 84, 101, 107, 110, 105, 107, 46, 13, 10, 84,
   104, 105, 115, 32, 115, 111, 102, 116, 119, 97, 114, 101, 32, 109, 97, 121,
   32, 111, 110, 108, 121, 32, 98, 101, 32, 117, 115, 101, 100, 32, 119, 105,
   116, 104, 32, 87, 80, 52, 120, 48, 48, 32, 67, 111, 110, 116, 114, 111,
   108, 108, 101, 114, 115, 32, 100, 101, 108, 105, 118, 101, 114, 101, 100, 32,
   98, 121, 32, 77, 105, 116, 97, 45, 84, 101, 107, 110, 105, 107, 0
};
//-----------------------------------------------------------------------
// MODIFIABLE                  MODIFIABLE               MODIFIABLE
//-----------------------------------------------------------------------
const char LidarAppGroupName[] = "G_"APP_ID"App";
const char LidarAppMenuName[] = "M_"APP_ID"AppMain";

//-----------------------------------------------------------------------
// IO VARIABLES                IO VARIABLES                IO VARIABLES
//-----------------------------------------------------------------------

void (*LidarSetLockValues)(void);
struct os_db_alias *LidarIOVars;
size_t LidarIOVarsSize = 0;
            
struct os_db_alias LidarIOVars1[]=
{
    VAR_ELEMENT_ALIAS("4.1.COM1_Mode",                    "LidarComSettingsBaudRate"),

    VAR_ELEMENT_ALIAS("4.1.COM1_DataBits",                "LidarComSettingsDataBits"),

    VAR_ELEMENT_ALIAS("4.1.COM1_StopBits",                "LidarComSettingsStopBits"),

    VAR_ELEMENT_ALIAS("4.1.COM1_Parity",                  "LidarComSettingsParity"),

    VAR_ELEMENT_ALIAS("4.1.COM1_TX",                      "LidarComSettingsTx"),

    VAR_ELEMENT_ALIAS("4.1.COM1_RX",                      "LidarComSettingsRx"),

    VAR_ELEMENT_ALIAS("4.1.COM1_Baud",                    "IO_LID_ComBaud"),

    VAR_ELEMENT_ALIAS("3.3.14",                           "DO_LID_LidarPowerRelay"),

};
size_t LidarIOVars1Size = sizeof(LidarIOVars1)/sizeof(LidarIOVars1[0]);

void LidarSetLockValues1(void)
{
   SetValue("IO_LID_ComBaud",                            TYP_32,    2400);

   SetValue("LidarComSettingsBaudRate",                  TYP_8,     1);

   SetValue("LidarComSettingsDataBits",                  TYP_8,     8);

   SetValue("LidarComSettingsStopBits",                  TYP_8,     1);

   SetValue("LidarComSettingsParity",                    TYP_8,     0);
}


STATUS LidarInitIOAliases()
{
   LidarIOVars = LidarIOVars1;
   LidarIOVarsSize = LidarIOVars1Size;
   LidarSetLockValues = &LidarSetLockValues1;
   return OS_SUCCESS;
}
//-----------------------------------------------------------------------
// AUTOGENERATED END        AUTOGENERATED END        AUTOGENERATED END
//-----------------------------------------------------------------------

#undef AUTOGENERATED_PART
