//*****************************PEPTOOL Header Start******************************
//                                                                               
//                         Copyright © 2015 Mita-Teknik.                         
//This software may only be used with WP4x00 Controllers delivered by Mita-Teknik
//                                                                               
//*******************************************************************************
//                                                                               
// $PEPTOOL version:9.0$                                                         
// $PEPTOOL file version:101$                                                    
//                                                                               
//*******************************************************************************
//                                                                               
// $Date: 2014/03/04 14:22:34 $                                                  
// $Author: MITA\ihn $                                                           
// $RCSfile: FeConConverter_FeConGmbH_Type1_Conf.c,v $                           
// $Revision: 1.4 $                                                              
//                                                                               
//******************************PEPTOOL Header End*******************************

//***********************************************************************
// OS header files
#include <os_main.h>
// App header files
#include <InitIo.h>

#define AUTOGENERATED_PART

#include <Turbdef.h>

//-----------------------------------------------------------------------
// AUTOGENERATED START     AUTOGENERATED START     AUTOGENERATED START
//-----------------------------------------------------------------------
char LiebherrConverter_Conf_copyright[] =
{
    67, 111, 112, 121, 114, 105, 103, 104, 116, 32, 63, 32, 50, 48, 49, 53,
    32, 77, 105, 116, 97, 45, 84, 101, 107, 110, 105, 107, 46, 13, 10, 84,
    104, 105, 115, 32, 115, 111, 102, 116, 119, 97, 114, 101, 32, 109, 97, 121,
    32, 111, 110, 108, 121, 32, 98, 101, 32, 117, 115, 101, 100, 32, 119, 105,
    116, 104, 32, 87, 80, 52, 120, 48, 48, 32, 67, 111, 110, 116, 114, 111,
    108, 108, 101, 114, 115, 32, 100, 101, 108, 105, 118, 101, 114, 101, 100, 32,
    98, 121, 32, 77, 105, 116, 97, 45, 84, 101, 107, 110, 105, 107, 0
};
//-----------------------------------------------------------------------
// MODIFIABLE                  MODIFIABLE               MODIFIABLE
//-----------------------------------------------------------------------
const char LiebherrConverterAppGroupName[] = "G_Power_Converter";
const char LiebherrConverterAppMenuName[] = "M_PowerConverter";

//-----------------------------------------------------------------------
// IO VARIABLES                IO VARIABLES                IO VARIABLES
//-----------------------------------------------------------------------

void (*LiebherrConverterSetLockValues)(void);
struct os_db_alias *LiebherrConverterIOVars;
size_t LiebherrConverterIOVarsSize = 0;
            
struct os_db_alias LiebherrConverterIOVars1[]=
{
    VAR_ELEMENT_ALIAS("1.4.17",                           "DO_LCNV_SafetyBypass_1"),

    VAR_ELEMENT_ALIAS("1.4.18",                           "DO_LCNV_SafetyBypass_2"),

    VAR_ELEMENT_ALIAS("1.4.19",                           "DO_LCNV_SafetyBypass_3"),

    VAR_ELEMENT_ALIAS("1.4.20",                           "DO_LCNV_SafetyBypass_4"),

    VAR_ELEMENT_ALIAS("1.4.45",                           "DI_LCNV_SafetyBypassFeedback_1"),
    VAR_ELEMENT_ALIAS("1.4.45_Ss",                        "DI_LCNV_SafetyBypassFeedback_1_Ss"),
    VAR_ELEMENT_ALIAS("1.4.45_E",                         "DI_LCNV_SafetyBypassFeedback_1_E"),
    VAR_ELEMENT_ALIAS("1.4.45_I",                         "DI_LCNV_SafetyBypassFeedback_1_I"),
    VAR_ELEMENT_ALIAS("1.4.45_Cm",                        "DI_LCNV_SafetyBypassFeedback_1_Cm"),
    VAR_ELEMENT_ALIAS("1.4.45_Ht",                        "DI_LCNV_SafetyBypassFeedback_1_Ht"),

    VAR_ELEMENT_ALIAS("1.4.46",                           "DI_LCNV_SafetyBypassFeedback_2"),
    VAR_ELEMENT_ALIAS("1.4.46_Ss",                        "DI_LCNV_SafetyBypassFeedback_2_Ss"),
    VAR_ELEMENT_ALIAS("1.4.46_E",                         "DI_LCNV_SafetyBypassFeedback_2_E"),
    VAR_ELEMENT_ALIAS("1.4.46_I",                         "DI_LCNV_SafetyBypassFeedback_2_I"),
    VAR_ELEMENT_ALIAS("1.4.46_Cm",                        "DI_LCNV_SafetyBypassFeedback_2_Cm"),
    VAR_ELEMENT_ALIAS("1.4.46_Ht",                        "DI_LCNV_SafetyBypassFeedback_2_Ht"),

    VAR_ELEMENT_ALIAS("1.4.47",                           "DI_LCNV_SafetyBypassFeedback_3"),
    VAR_ELEMENT_ALIAS("1.4.47_Ss",                        "DI_LCNV_SafetyBypassFeedback_3_Ss"),
    VAR_ELEMENT_ALIAS("1.4.47_E",                         "DI_LCNV_SafetyBypassFeedback_3_E"),
    VAR_ELEMENT_ALIAS("1.4.47_I",                         "DI_LCNV_SafetyBypassFeedback_3_I"),
    VAR_ELEMENT_ALIAS("1.4.47_Cm",                        "DI_LCNV_SafetyBypassFeedback_3_Cm"),
    VAR_ELEMENT_ALIAS("1.4.47_Ht",                        "DI_LCNV_SafetyBypassFeedback_3_Ht"),

    VAR_ELEMENT_ALIAS("1.4.48",                           "DI_LCNV_SafetyBypassFeedback_4"),
    VAR_ELEMENT_ALIAS("1.4.48_Ss",                        "DI_LCNV_SafetyBypassFeedback_4_Ss"),
    VAR_ELEMENT_ALIAS("1.4.48_E",                         "DI_LCNV_SafetyBypassFeedback_4_E"),
    VAR_ELEMENT_ALIAS("1.4.48_I",                         "DI_LCNV_SafetyBypassFeedback_4_I"),
    VAR_ELEMENT_ALIAS("1.4.48_Cm",                        "DI_LCNV_SafetyBypassFeedback_4_Cm"),
    VAR_ELEMENT_ALIAS("1.4.48_Ht",                        "DI_LCNV_SafetyBypassFeedback_4_Ht"),

};
size_t LiebherrConverterIOVars1Size = sizeof(LiebherrConverterIOVars1)/sizeof(LiebherrConverterIOVars1[0]);

void LiebherrConverterSetLockValues1(void)
{
   SetLockValue("DI_LCNV_SafetyBypassFeedback_1_Ss",     TYP_8,     1);
   SetLockValue("DI_LCNV_SafetyBypassFeedback_1_E",      TYP_8,     1);
   SetValue("DI_LCNV_SafetyBypassFeedback_1_I",          TYP_8,     0);
   SetLockValue("DI_LCNV_SafetyBypassFeedback_1_Cm",     TYP_8,     1);
   SetLockValue("DI_LCNV_SafetyBypassFeedback_1_Ht",     TYP_32,    1000);

   SetLockValue("DI_LCNV_SafetyBypassFeedback_2_Ss",     TYP_8,     1);
   SetLockValue("DI_LCNV_SafetyBypassFeedback_2_E",      TYP_8,     1);
   SetValue("DI_LCNV_SafetyBypassFeedback_2_I",          TYP_8,     0);
   SetLockValue("DI_LCNV_SafetyBypassFeedback_2_Cm",     TYP_8,     1);
   SetLockValue("DI_LCNV_SafetyBypassFeedback_2_Ht",     TYP_32,    1000);

   SetLockValue("DI_LCNV_SafetyBypassFeedback_3_Ss",     TYP_8,     1);
   SetLockValue("DI_LCNV_SafetyBypassFeedback_3_E",      TYP_8,     1);
   SetValue("DI_LCNV_SafetyBypassFeedback_3_I",          TYP_8,     0);
   SetLockValue("DI_LCNV_SafetyBypassFeedback_3_Cm",     TYP_8,     1);
   SetLockValue("DI_LCNV_SafetyBypassFeedback_3_Ht",     TYP_32,    1000);

   SetLockValue("DI_LCNV_SafetyBypassFeedback_4_Ss",     TYP_8,     1);
   SetLockValue("DI_LCNV_SafetyBypassFeedback_4_E",      TYP_8,     1);
   SetValue("DI_LCNV_SafetyBypassFeedback_4_I",          TYP_8,     0);
   SetLockValue("DI_LCNV_SafetyBypassFeedback_4_Cm",     TYP_8,     1);
   SetLockValue("DI_LCNV_SafetyBypassFeedback_4_Ht",     TYP_32,    1000);
}


STATUS LiebherrConverterInitIOAliases()
{
   LiebherrConverterIOVars = LiebherrConverterIOVars1;
   LiebherrConverterIOVarsSize = LiebherrConverterIOVars1Size;
   LiebherrConverterSetLockValues = &LiebherrConverterSetLockValues1;
   return OS_SUCCESS;
}
//-----------------------------------------------------------------------
// AUTOGENERATED END        AUTOGENERATED END        AUTOGENERATED END
//-----------------------------------------------------------------------

#undef AUTOGENERATED_PART
