//*****************************PEPTOOL Header Start******************************
//                                                                               
//                         Copyright © 2015 Mita-Teknik.                         
//This software may only be used with WP4x00 Controllers delivered by Mita-Teknik
//                                                                               
//*******************************************************************************
//                                                                               
// $PEPTOOL version:9.0$                                                         
// $PEPTOOL file version:101$                                                    
//                                                                               
//*******************************************************************************
//                                                                               
// $Date: 2014/04/23 06:34:45 $                                                  
// $Author: MITA\ihn $                                                           
// $RCSfile: Lubrication_Pitch_Pinion_MT_Type1_Conf.c,v $                        
// $Revision: 1.7 $                                                              
//                                                                               
//******************************PEPTOOL Header End*******************************

//***********************************************************************
// OS header files
#include <os_main.h>
// App header files
#include <InitIo.h>

#define AUTOGENERATED_PART

#include <Turbdef.h>

//-----------------------------------------------------------------------
// AUTOGENERATED START     AUTOGENERATED START     AUTOGENERATED START
//-----------------------------------------------------------------------
char Lubrication_Pitch_Pinion_MT_Type1_Conf_copyright[] =
{
   67, 111, 112, 121, 114, 105, 103, 104, 116, 32, 63, 32, 50, 48, 49, 53,
   32, 77, 105, 116, 97, 45, 84, 101, 107, 110, 105, 107, 46, 13, 10, 84,
   104, 105, 115, 32, 115, 111, 102, 116, 119, 97, 114, 101, 32, 109, 97, 121,
   32, 111, 110, 108, 121, 32, 98, 101, 32, 117, 115, 101, 100, 32, 119, 105,
   116, 104, 32, 87, 80, 52, 120, 48, 48, 32, 67, 111, 110, 116, 114, 111,
   108, 108, 101, 114, 115, 32, 100, 101, 108, 105, 118, 101, 114, 101, 100, 32,
   98, 121, 32, 77, 105, 116, 97, 45, 84, 101, 107, 110, 105, 107, 0
};
//-----------------------------------------------------------------------
// MODIFIABLE                  MODIFIABLE               MODIFIABLE
//-----------------------------------------------------------------------
const char Lubrication_Pitch_Pinion_MT_Type1AppGroupName[] = "G_LubricationManager_MT_Type1";
const char Lubrication_Pitch_Pinion_MT_Type1AppMenuName[] = "M_LubricationManagerMTType1";

//-----------------------------------------------------------------------
// IO VARIABLES                IO VARIABLES                IO VARIABLES
//-----------------------------------------------------------------------

void (*Lubrication_Pitch_Pinion_MT_Type1SetLockValues)(void);
struct os_db_alias *Lubrication_Pitch_Pinion_MT_Type1IOVars;
size_t Lubrication_Pitch_Pinion_MT_Type1IOVarsSize = 0;
            
struct os_db_alias Lubrication_Pitch_Pinion_MT_Type1IOVars1[]=
{
    VAR_ELEMENT_ALIAS("5.2.6",                            "DO_LubricationPP_Pump"),

    VAR_ELEMENT_ALIAS("5.2.33",                           "DI_LubricationPP_LevelWarning"),
    VAR_ELEMENT_ALIAS("5.2.33_Ss",                        "DI_LubricationPP_LevelWarning_Ss"),
    VAR_ELEMENT_ALIAS("5.2.33_E",                         "DI_LubricationPP_LevelWarning_E"),
    VAR_ELEMENT_ALIAS("5.2.33_I",                         "DI_LubricationPP_LevelWarning_I"),
    VAR_ELEMENT_ALIAS("5.2.33_Cm",                        "DI_LubricationPP_LevelWarning_Cm"),
    VAR_ELEMENT_ALIAS("5.2.33_Ht",                        "DI_LubricationPP_LevelWarning_Ht"),

    VAR_ELEMENT_ALIAS("5.2.34",                           "DI_LubricationPP_PumpFailure"),
    VAR_ELEMENT_ALIAS("5.2.34_Ss",                        "DI_LubricationPP_PumpFailure_Ss"),
    VAR_ELEMENT_ALIAS("5.2.34_E",                         "DI_LubricationPP_PumpFailure_E"),
    VAR_ELEMENT_ALIAS("5.2.34_I",                         "DI_LubricationPP_PumpFailure_I"),
    VAR_ELEMENT_ALIAS("5.2.34_Cm",                        "DI_LubricationPP_PumpFailure_Cm"),
    VAR_ELEMENT_ALIAS("5.2.34_Ht",                        "DI_LubricationPP_PumpFailure_Ht"),

};
size_t Lubrication_Pitch_Pinion_MT_Type1IOVars1Size = sizeof(Lubrication_Pitch_Pinion_MT_Type1IOVars1)/sizeof(Lubrication_Pitch_Pinion_MT_Type1IOVars1[0]);

void Lubrication_Pitch_Pinion_MT_Type1SetLockValues1(void)
{
   SetLockValue("DI_LubricationPP_LevelWarning_Ss",      TYP_8,     1);
   SetLockValue("DI_LubricationPP_LevelWarning_E",       TYP_8,     1);
   SetValue("DI_LubricationPP_LevelWarning_I",           TYP_8,     0);
   SetLockValue("DI_LubricationPP_LevelWarning_Cm",      TYP_8,     1);
   SetLockValue("DI_LubricationPP_LevelWarning_Ht",      TYP_32,    100);

   SetLockValue("DI_LubricationPP_PumpFailure_Ss",       TYP_8,     1);
   SetLockValue("DI_LubricationPP_PumpFailure_E",        TYP_8,     1);
   SetValue("DI_LubricationPP_PumpFailure_I",            TYP_8,     0);
   SetLockValue("DI_LubricationPP_PumpFailure_Cm",       TYP_8,     1);
   SetLockValue("DI_LubricationPP_PumpFailure_Ht",       TYP_32,    100);
}


STATUS Lubrication_Pitch_Pinion_MT_Type1InitIOAliases()
{
   Lubrication_Pitch_Pinion_MT_Type1IOVars = Lubrication_Pitch_Pinion_MT_Type1IOVars1;
   Lubrication_Pitch_Pinion_MT_Type1IOVarsSize = Lubrication_Pitch_Pinion_MT_Type1IOVars1Size;
   Lubrication_Pitch_Pinion_MT_Type1SetLockValues = &Lubrication_Pitch_Pinion_MT_Type1SetLockValues1;
   return OS_SUCCESS;
}
//-----------------------------------------------------------------------
// AUTOGENERATED END        AUTOGENERATED END        AUTOGENERATED END
//-----------------------------------------------------------------------

#undef AUTOGENERATED_PART
