//*****************************PEPTOOL Header Start******************************
//                                                                               
//                         Copyright © 2015 Mita-Teknik.                         
//This software may only be used with WP4x00 Controllers delivered by Mita-Teknik
//                                                                               
//*******************************************************************************
//                                                                               
// $PEPTOOL version:9.0$                                                         
// $PEPTOOL file version:106$                                                    
//                                                                               
//*******************************************************************************
//                                                                               
// $Date: 2014/05/23 09:10:09 $                                                  
// $Author: MITA\ihn $                                                           
// $RCSfile: Lubrication_Pitch_Pinion_MT_Type1.c,v $                             
// $Revision: 1.11 $                                                             
//                                                                               
//******************************PEPTOOL Header End*******************************

//***********************************************************************

// OS header files
#include <os_main.h>
// AppLib header files
#include <lib_main.h>
// App header files
#include <turbdef.h>
#include <VarMacros.h>

// Object header file
#include <Lubrication_Pitch_Pinion_MT_Type1.h>

#define AUTOGENERATED_PART
//{
//-----------------------------------------------------------------------
// AUTOGENERATED START     AUTOGENERATED START     AUTOGENERATED START
//-----------------------------------------------------------------------

#define VALIDATE_HASH
char Lubrication_Pitch_Pinion_MT_Type1_copyright[] =
{
   67, 111, 112, 121, 114, 105, 103, 104, 116, 32, 63, 32, 50, 48, 49, 53,
   32, 77, 105, 116, 97, 45, 84, 101, 107, 110, 105, 107, 46, 13, 10, 84,
   104, 105, 115, 32, 115, 111, 102, 116, 119, 97, 114, 101, 32, 109, 97, 121,
   32, 111, 110, 108, 121, 32, 98, 101, 32, 117, 115, 101, 100, 32, 119, 105,
   116, 104, 32, 87, 80, 52, 120, 48, 48, 32, 67, 111, 110, 116, 114, 111,
   108, 108, 101, 114, 115, 32, 100, 101, 108, 105, 118, 101, 114, 101, 100, 32,
   98, 121, 32, 77, 105, 116, 97, 45, 84, 101, 107, 110, 105, 107, 0
};

#define MODULE_NAME "Lubrication Pitch Pinion MT Type1A"

//-----------------------------------------------------------------------
// ALLOCATE MEMORY FOR STRINGS IN VARDB
//-----------------------------------------------------------------------

static char A_V_LubricationPP_OilTankEmptyTimeTxt[31]  = "Not Initialized";
static char A_V_LubricationPP_TimeIndicationTxt[31]  = "12345678901234567890123456789";
static char A_V_Lub_Equip0_ModeTxt[31]  = "Disable";
static char A_V_Lub_Equip0_StateTxt[31]  = "N/A";
static char A_V_Lub_Equip0_StatusTxt[31]  = "N/A";
static char A_P_PitchPLubr_ManagerVars_String[31]  = "V_Lub_";

//-----------------------------------------------------------------------
// DEFINE LOCAL VARIABLES DEFINE LOCAL VARIABLES DEFINE LOCAL VARIABLES
//-----------------------------------------------------------------------

static struct os_db_local LocalVars[] =
{
   VAR_ELEMENT_LOCAL("V_LubricationPP_OilTankEmptyTimeTxt",      TYPE_STRING + sizeof(A_V_LubricationPP_OilTankEmptyTimeTxt) - 1,  PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   A_V_LubricationPP_OilTankEmptyTimeTxt, 0,                0,                NULL,  NOLOG_ENABLE  ),
   VAR_ELEMENT_LOCAL("V_LubricationPP_TimeIndicationTxt",        TYPE_STRING + sizeof(A_V_LubricationPP_TimeIndicationTxt) - 1,  PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   A_V_LubricationPP_TimeIndicationTxt, 0,                0,                NULL,  NOLOG_ENABLE  ),
   VAR_ELEMENT_LOCAL("V_Lub_Equip0_Mode",                        TYPE_S32,     PASSWORD_LEVEL_ADMINISTRATOR,      PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   0,               0,               1,               NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_Lub_Equip0_ModeTxt",                     TYPE_STRING + sizeof(A_V_Lub_Equip0_ModeTxt) - 1,  PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   A_V_Lub_Equip0_ModeTxt, 0,                0,                NULL,  NOLOG_ENABLE  ),
   VAR_ELEMENT_LOCAL("V_Lub_Equip0_State",                       TYPE_S32,     PASSWORD_LEVEL_ADMINISTRATOR,      PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   0,               S32_MIN,         S32_MAX,         NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_Lub_Equip0_StateTxt",                    TYPE_STRING + sizeof(A_V_Lub_Equip0_StateTxt) - 1,  PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   A_V_Lub_Equip0_StateTxt, 0,                0,                NULL,  NOLOG_ENABLE  ),
   VAR_ELEMENT_LOCAL("V_Lub_Equip0_Status",                      TYPE_S32,     PASSWORD_LEVEL_ADMINISTRATOR,      PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   0,               S32_MIN,         S32_MAX,         NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_Lub_Equip0_StatusTxt",                   TYPE_STRING + sizeof(A_V_Lub_Equip0_StatusTxt) - 1,  PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   A_V_Lub_Equip0_StatusTxt, 0,                0,                NULL,  NOLOG_ENABLE  ),
};

//-----------------------------------------------------------------------
// DEFINE PARAMETERS        DEFINE PARAMETERS        DEFINE PARAMETERS
//-----------------------------------------------------------------------

static struct os_db_parameter ParameterVars[] =
{
   VAR_ELEMENT_PARAMETER("P_LubricationPP_PumpServiceCtrl",          TYPE_U8,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_NONE,   0,       UNIT_NONE,          0,   0,               0,               2,               NULL  ),
   VAR_ELEMENT_PARAMETER("P_LubricationPP_PumpOffTime",              TYPE_U32,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         SCALE_DIV,    3600000, UNIT_HOUR,          1,   7200000,         600000,          604800000,       NULL  ),
   VAR_ELEMENT_PARAMETER("P_LubricationPP_EquipNo",                  TYPE_U8,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         SCALE_NONE,   0,       UNIT_NONE,          0,   0,               0,               9,               NULL  ),
   VAR_ELEMENT_PARAMETER("P_LubricationPP_LevelLowOnTime",           TYPE_U32,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         SCALE_DIV,    3600000, UNIT_HOUR,          0,   1209600000,      3600000,         2419200000,      NULL  ),
   VAR_ELEMENT_PARAMETER("P_LubricationPP_InternalMode",             TYPE_U8,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         SCALE_NONE,   0,       UNIT_NONE,          0,   0,               0,               2,               NULL  ),
   VAR_ELEMENT_PARAMETER("P_PitchLubricationBladeAngleStart",        TYPE_S32,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         SCALE_DIV,    100,     UNIT_DEGREE,        0,   6000,            200,             9000,            NULL  ),
   VAR_ELEMENT_PARAMETER("P_PitchLubricationBladeAngleStop",         TYPE_S32,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         SCALE_DIV,    100,     UNIT_DEGREE,        0,   0,               0,               9000,            NULL  ),
   VAR_ELEMENT_PARAMETER("P_LubricationPP_FeedbackTime",             TYPE_U32,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         SCALE_DIV,    1000,    UNIT_SECOND,        1,   40000,           100,             300000,          NULL  ),
   VAR_ELEMENT_PARAMETER("P_LubricationPP_FeedbackType",             TYPE_U8,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         SCALE_NONE,   0,       UNIT_NONE,          0,   2,               0,               2,               NULL  ),
   VAR_ELEMENT_PARAMETER("P_PitchPLubr_ManagerVars_String",          TYPE_STRING + sizeof(A_P_PitchPLubr_ManagerVars_String) - 1,  PASSWORD_LEVEL_ADMINISTRATOR,      PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   A_P_PitchPLubr_ManagerVars_String, 0,                0,                NULL  ),
   VAR_ELEMENT_PARAMETER("P_LubricationPP_Stroke_ON",                TYPE_U8,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         SCALE_NONE,   0,       UNIT_NONE,          0,   7,               1,               10,              NULL  ),
};

//-----------------------------------------------------------------------
// DEFINE BACKUPS            DEFINE BACKUPS            DEFINE BACKUPS
//-----------------------------------------------------------------------

static struct os_db_backup BackupVars[] =
{
   VAR_ELEMENT_BACKUP("B_OilTankEmptyErrorTimer",                 TYPE_TIME,    PASSWORD_LEVEL_ADMINISTRATOR,      PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    1000,    UNIT_NONE,          0,   (0ULL),          ((U64)U64_MIN),  ((U64)U64_MAX),  NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_BACKUP("B_PPLubricationTimer",                     TYPE_TIME,    PASSWORD_LEVEL_ADMINISTRATOR,      PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   (0ULL),          ((U64)U64_MIN),  ((U64)U64_MAX),  NULL,  NOLOG_ENABLE),
};

//----------------------------------------------------------------------------------
// DEFINE VAR ARRAYS            DEFINE VAR ARRAYS            DEFINE VAR ARRAYS
//----------------------------------------------------------------------------------
char Lubrication_Pitch_Pinion_MT_Type1_initialValues[] =
{
   15, 54, 58, 189, 124, 200, 253, 92, 38, 154, 187, 180, 113, 101, 37, 160,
   161, 41, 64, 44, 181, 250, 50, 51, 169, 196, 47, 239, 101, 249, 198, 56,
   0
};

//-----------------------------------------------------------------------
// CREATE DATABASE VARS   CREATE DATABASE VARS   CREATE DATABASE VARS
//-----------------------------------------------------------------------

static STATUS CreateVarDbVars(void)
{
   STATUS Status;
   size_t ErrorEntry;

   Status = OS_VarDB_CreateLocals(LocalVars, sizeof(LocalVars)/sizeof(LocalVars[0]), &ErrorEntry, AppLocalParameterPosition());
   if (Status != 0)
   {
      AppSystemLog(ERR_7, MODULE_NAME"CrVL: %d,%d", Status, ErrorEntry);
      return ERR_7;
   }

   Status = OS_VarDB_CreateParameters(ParameterVars, sizeof(ParameterVars)/sizeof(ParameterVars[0]), &ErrorEntry, AppExportParameterPosition());
   if (Status != 0)
   {
      AppSystemLog(ERR_7, MODULE_NAME"CrVXP: %d,%d", Status, ErrorEntry);
      return ERR_7;
   }

   Status = OS_VarDB_CreateBackups(BackupVars, sizeof(BackupVars)/sizeof(BackupVars[0]), &ErrorEntry, AppLocalParameterPosition(), AppBackupPosition());
   if (Status != 0)
   {
      AppSystemLog(ERR_7, MODULE_NAME"CrVB: %d,%d", Status, ErrorEntry);
      return ERR_7;
   }

   return OS_SUCCESS;
}

#define CREATE_VARDB_VARS

//-----------------------------------------------------------------------
// CREATE IO VARIABLES     CREATE IO VARIABLES     CREATE IO VARIABLES
//-----------------------------------------------------------------------

extern STATUS Lubrication_Pitch_Pinion_MT_Type1InitIOAliases();
extern struct os_db_alias* Lubrication_Pitch_Pinion_MT_Type1IOVars;
extern void (*Lubrication_Pitch_Pinion_MT_Type1SetLockValues)(void);
extern size_t Lubrication_Pitch_Pinion_MT_Type1IOVarsSize;

static STATUS CreateIOVars(void)
{
   STATUS Status;
   size_t ErrorEntry;

   varid_t VarId;
   BOOL variablesExist = false;
   U8 counter = 50;
   Status = Lubrication_Pitch_Pinion_MT_Type1InitIOAliases();
   STATUS_LINE_VAR_RETURN_VALUE(Status)
   while (!variablesExist && counter-- > 0)
   {
      variablesExist = true;
      U32 i = 0;
      for (i = 0; i < Lubrication_Pitch_Pinion_MT_Type1IOVarsSize; ++i)
      {
         if (OS_VarDB_GetVariableID(Lubrication_Pitch_Pinion_MT_Type1IOVars[i].Name, &VarId) != OS_SUCCESS)
         {
            variablesExist = false;
            break;
         }
      }

      if (!variablesExist)
      {
         OS_Sleep(100);
      }
   }

   Status = OS_VarDB_CreateAliases(Lubrication_Pitch_Pinion_MT_Type1IOVars, Lubrication_Pitch_Pinion_MT_Type1IOVarsSize, &ErrorEntry);
   if (Status)
   {
      AppDebugLog(5000, "Var Name = %s", Lubrication_Pitch_Pinion_MT_Type1IOVars[ErrorEntry].Alias);
   }
   STATUS_LINE_VAR_RETURN_CONST(Status, ErrorEntry);
   return OS_SUCCESS;
}

#define CREATE_IO_VARS

//-----------------------------------------------------------------------
// ALIASES                       ALIASES                       ALIASES
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// INPUT                          INPUT                          INPUT
//-----------------------------------------------------------------------

// Create local variable
#define MODUL_INPUTS
static U8 V_ActiveControlProgram1 = 0;
static U8 V_Grid_ErrorActive = 0;
static U8 V_Inverter_StatusLVRT = 0;
static U8 DI_LubricationPP_LevelWarning = 0;
static U8 DI_LubricationPP_PumpFailure = 0;
static S32 V_BladeSystem_PositionAct = 0;
static S32 V_Lub_Equip0_Mode = 0;

//-----------------------------------------------------------------------
static struct ModulInOut ModulInputs[] =
{
   {"V_ActiveControlProgram1",                  &V_ActiveControlProgram1,                  sizeof(V_ActiveControlProgram1),                  },
   {"V_Grid_ErrorActive",                       &V_Grid_ErrorActive,                       sizeof(V_Grid_ErrorActive),                       },
   {"V_Inverter_StatusLVRT",                    &V_Inverter_StatusLVRT,                    sizeof(V_Inverter_StatusLVRT),                    },
   {"DI_LubricationPP_LevelWarning",            &DI_LubricationPP_LevelWarning,            sizeof(DI_LubricationPP_LevelWarning),            },
   {"DI_LubricationPP_PumpFailure",             &DI_LubricationPP_PumpFailure,             sizeof(DI_LubricationPP_PumpFailure),             },
   {"V_BladeSystem_PositionAct",                &V_BladeSystem_PositionAct,                sizeof(V_BladeSystem_PositionAct),                },
   {"V_Lub_Equip0_Mode",                        &V_Lub_Equip0_Mode,                        sizeof(V_Lub_Equip0_Mode),                        },
};

//-----------------------------------------------------------------------
// Check variable type
static STATUS VarsReadReturnStatus;
static type_t ReadVarType = TYPE_NONE;
static void VarsReadTypeCheck(void)
{
   (void)VarsReadReturnStatus;
   (void)ReadVarType;
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[0].Name,                      ModulInputs[0].Id)
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[1].Name,                      ModulInputs[1].Id)
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[2].Name,                      ModulInputs[2].Id)
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[3].Name,                      ModulInputs[3].Id)
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[4].Name,                      ModulInputs[4].Id)
   VERIFY_INPUT_REF_ID(S32,       ModulInputs[5].Name,                      ModulInputs[5].Id)
   VERIFY_INPUT_REF_ID(S32,       ModulInputs[6].Name,                      ModulInputs[6].Id)
}

#undef MODUL_INPUTS
#define MODUL_INPUTS_SIZE (sizeof(ModulInputs)/sizeof(ModulInputs[0]))

//------------------------------------------------------------------------------------------
// READ/WRITE VARDB ARRAY      READ/WRITE VARDB ARRAY      READ/WRATE VARDB ARRAY
//------------------------------------------------------------------------------------------


//-----------------------------------------------------------------------
// PARAMETER                    PARAMETER                    PARAMETER
//-----------------------------------------------------------------------

// Create local variable
#define MODUL_PARAMETERS
static U8 P_LubricationPP_PumpServiceCtrl = 0;
static U32 P_LubricationPP_PumpOffTime = 0;
static U32 P_LubricationPP_LevelLowOnTime = 0;
static U8 P_LubricationPP_InternalMode = 0;
static S32 P_PitchLubricationBladeAngleStart = 0;
static S32 P_PitchLubricationBladeAngleStop = 0;
static U32 P_LubricationPP_FeedbackTime = 0;
static U8 P_LubricationPP_FeedbackType = 0;
static U8 P_LubricationPP_Stroke_ON = 0;



//-----------------------------------------------------------------------
static struct ModulInOut ModulParameters0[] =
{
   {"P_LubricationPP_PumpServiceCtrl",          &P_LubricationPP_PumpServiceCtrl,          sizeof(P_LubricationPP_PumpServiceCtrl),          },
   {"P_LubricationPP_PumpOffTime",              &P_LubricationPP_PumpOffTime,              sizeof(P_LubricationPP_PumpOffTime),              },
   {"P_LubricationPP_LevelLowOnTime",           &P_LubricationPP_LevelLowOnTime,           sizeof(P_LubricationPP_LevelLowOnTime),           },
   {"P_LubricationPP_InternalMode",             &P_LubricationPP_InternalMode,             sizeof(P_LubricationPP_InternalMode),             },
   {"P_PitchLubricationBladeAngleStart",        &P_PitchLubricationBladeAngleStart,        sizeof(P_PitchLubricationBladeAngleStart),        },
   {"P_PitchLubricationBladeAngleStop",         &P_PitchLubricationBladeAngleStop,         sizeof(P_PitchLubricationBladeAngleStop),         },
   {"P_LubricationPP_FeedbackTime",             &P_LubricationPP_FeedbackTime,             sizeof(P_LubricationPP_FeedbackTime),             },
   {"P_LubricationPP_FeedbackType",             &P_LubricationPP_FeedbackType,             sizeof(P_LubricationPP_FeedbackType),             },
   {"P_LubricationPP_Stroke_ON",                &P_LubricationPP_Stroke_ON,                sizeof(P_LubricationPP_Stroke_ON),                },

};
static struct ModulInOut* ModulParameters[] =
{
   ModulParameters0,
};

//-----------------------------------------------------------------------
// Check variable type
static STATUS ParaVarsReadReturnStatus;
static type_t ParaReadVarType = TYPE_NONE;
static void ParaVarsReadTypeCheck(void)
{
   (void)ParaVarsReadReturnStatus;
   (void)ParaReadVarType;
}

#undef MODUL_PARAMETERS

#define PARAMETERS_GROUPS_SIZE        1
#define GENERAL_GROUP                 0
#define MODUL_PARAMETERS_TOTAL_SIZE   9
static SUBSCRIPTION ParaSubscription[MODUL_PARAMETERS_TOTAL_SIZE];
static U8 ReadParameters[PARAMETERS_GROUPS_SIZE];
static U8 ParametersChanged[PARAMETERS_GROUPS_SIZE];
static UNSIGNED GroupsIndexes[PARAMETERS_GROUPS_SIZE];
static int ParaGroupsSizes[PARAMETERS_GROUPS_SIZE] = { 9 };
static STATUS VarDbUpdateParameter(varid_t VariableId, void* Message, U16 Length, UNSIGNED paraGroupIndex, UNSIGNED Ref2)
{
   ReadParameters[paraGroupIndex] = 1;
   ParametersChanged[paraGroupIndex] = 1;
   return OS_SUCCESS;
}
static STATUS ReadParametersFunc(int paraGroupIndex)
{
   STATUS LocalStatus;
   // Check inputdata
   if (sizeof(ModulParameters[paraGroupIndex]) == 0)
   {
      AppSystemLog(ERR_4, MODULE_NAME"Group %d ModuleParameters = 0", paraGroupIndex);
      return ERR_4;
   }
   // Read inputdata
   LocalStatus = OS_ReadVariables(ModulParameters[paraGroupIndex], ParaGroupsSizes[paraGroupIndex]);
   if (LocalStatus != 0)
   {
      AppSystemLog(11, "LocalStatus: %d", LocalStatus);
      AppSystemLog(ERR_4, MODULE_NAME"ReadParErr: group=%d element=%d elementpointer=0x%x", paraGroupIndex, LocalStatus, &ModulParameters[LocalStatus]);
      return ERR_4;
   }
   return OS_SUCCESS;
}


//-----------------------------------------------------------------------
// READ VARS FROM VARDB    READ VARS FROM VARDB    READ VARS FROM VARDB
//-----------------------------------------------------------------------

static STATUS InputReferenceRoutine(U8 ModuleState)
{
   STATUS LocalStatus = 0;

   // Read input references
   if (ModuleState >= APP_INIT3)
   {
      // Check inputdata
      if (sizeof(ModulInputs) == 0)
      {
         AppSystemLog(ERR_4, MODULE_NAME"ModuleInputs = 0");
         return ERR_4;
      }
      // Read inputdata
      LocalStatus = OS_ReadVariables(ModulInputs, MODUL_INPUTS_SIZE);
      if (LocalStatus != 0)
      {
         AppSystemLog(ERR_4, MODULE_NAME"ReadVErr: element=%d elementpointer=0x%x", LocalStatus, &ModulInputs[LocalStatus]);
         return ERR_4;
      }
   }
   // Read input parameters
   if (ModuleState == APP_INIT3)
   {
      static size_t ParaCounter = 0;
      int groupIndex;
      for (groupIndex = 0; groupIndex < PARAMETERS_GROUPS_SIZE; groupIndex++)
      {
         ParametersChanged[groupIndex] = 1;
         ReadParameters[groupIndex] = 1;
         GroupsIndexes[groupIndex] = groupIndex;

         // Check inputdata
         if (sizeof(ModulParameters[groupIndex]) == 0)
         {
            AppSystemLog(ERR_4, MODULE_NAME"Group = %d ModuleParameters = 0", groupIndex);
            return ERR_4;
         }
         // Read inputdata
         LocalStatus = OS_ReadVariables(ModulParameters[groupIndex], ParaGroupsSizes[groupIndex]);
         if (LocalStatus != 0)
         {
            AppSystemLog(ERR_4, MODULE_NAME"ReadVParaErr: group=%d element=%d elementpointer=0x%x", groupIndex, LocalStatus, &ModulParameters[groupIndex][LocalStatus]);
            return ERR_4;
         }
         int paraIndex;
         for (paraIndex = 0; paraIndex < ParaGroupsSizes[groupIndex]; paraIndex++)
         {
            LocalStatus = OS_SubHandl_SubscribeFunctionWithRef(&ParaSubscription[ParaCounter], 1, &ModulParameters[groupIndex][paraIndex].Id, &GroupsIndexes[groupIndex], &GroupsIndexes[groupIndex], VarDbUpdateParameter);
            ParaCounter++;
            if (LocalStatus != 0)
            {
               AppSystemLog(ERR_4, MODULE_NAME"Subscribe Parameter: group=%d element=%d elementpointer=0x%x", groupIndex, LocalStatus, &ModulParameters[LocalStatus]);
               return ERR_4;
            }
         }
      }
   }
   if (ModuleState == APP_RUN)
   {
      int groupIndex;
      for (groupIndex = 0; groupIndex < PARAMETERS_GROUPS_SIZE; groupIndex++)
      {
         if (ReadParameters[groupIndex])
         {
            LocalStatus = ReadParametersFunc(groupIndex);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
            ReadParameters[groupIndex] = 0;
         }
      }
   }

   return 0;
}

#define READ_VARS

//-----------------------------------------------------------------------
// OUTPUT                         OUTPUT                         OUTPUT
//-----------------------------------------------------------------------

// Create local variable
#define MODUL_OUTPUTS
static U8 DO_LubricationPP_Pump = 0;
static time_t B_OilTankEmptyErrorTimer = 0;
static time_t B_PPLubricationTimer = 0;
static S32 V_Lub_Equip0_State = 0;
static S32 V_Lub_Equip0_Status = 0;
static char V_LubricationPP_OilTankEmptyTimeTxt[31];
static char V_LubricationPP_TimeIndicationTxt[31];
static char V_Lub_Equip0_StateTxt[31];
static char V_Lub_Equip0_StatusTxt[31];


//-----------------------------------------------------------------------
static struct ModulInOut ModulOutputs[] =
{
   {"DO_LubricationPP_Pump",                    &DO_LubricationPP_Pump,                    sizeof(DO_LubricationPP_Pump),                    },
   {"B_OilTankEmptyErrorTimer",                 &B_OilTankEmptyErrorTimer,                 sizeof(B_OilTankEmptyErrorTimer),                 },
   {"V_LubricationPP_OilTankEmptyTimeTxt",      &V_LubricationPP_OilTankEmptyTimeTxt,      sizeof(V_LubricationPP_OilTankEmptyTimeTxt),      },
   {"V_LubricationPP_TimeIndicationTxt",        &V_LubricationPP_TimeIndicationTxt,        sizeof(V_LubricationPP_TimeIndicationTxt),        },
   {"B_PPLubricationTimer",                     &B_PPLubricationTimer,                     sizeof(B_PPLubricationTimer),                     },
   {"V_Lub_Equip0_State",                       &V_Lub_Equip0_State,                       sizeof(V_Lub_Equip0_State),                       },
   {"V_Lub_Equip0_StateTxt",                    &V_Lub_Equip0_StateTxt,                    sizeof(V_Lub_Equip0_StateTxt),                    },
   {"V_Lub_Equip0_Status",                      &V_Lub_Equip0_Status,                      sizeof(V_Lub_Equip0_Status),                      },
   {"V_Lub_Equip0_StatusTxt",                   &V_Lub_Equip0_StatusTxt,                   sizeof(V_Lub_Equip0_StatusTxt),                   },
};

//-----------------------------------------------------------------------
// Check variable type
static STATUS VarsWriteReturnStatus;
static type_t WriteVarType = TYPE_NONE;
static void VarsWriteTypeCheck(void)
{
   (void)VarsWriteReturnStatus;
   (void)WriteVarType;
   VERIFY_OUTPUT_REF_ID(U8,        ModulOutputs[0].Name,                     ModulOutputs[0].Id,                       0)
   VERIFY_OUTPUT_TIME_REF_ID(time_t,       ModulOutputs[1].Name,                     ModulOutputs[1].Id,                       0)
   VERIFY_OUTPUT_STRING_REF_ID(STRING,     ModulOutputs[2].Name,                      ModulOutputs[2].Id,               0)
   VERIFY_OUTPUT_STRING_REF_ID(STRING,     ModulOutputs[3].Name,                      ModulOutputs[3].Id, 0)
   VERIFY_OUTPUT_TIME_REF_ID(time_t,       ModulOutputs[4].Name,                     ModulOutputs[4].Id,                       0)
   VERIFY_OUTPUT_REF_ID(S32,       ModulOutputs[5].Name,                     ModulOutputs[5].Id,                       0)
   VERIFY_OUTPUT_STRING_REF_ID(STRING,     ModulOutputs[6].Name,                      ModulOutputs[6].Id,                           0)
   VERIFY_OUTPUT_REF_ID(S32,       ModulOutputs[7].Name,                     ModulOutputs[7].Id,                       0)
   VERIFY_OUTPUT_STRING_REF_ID(STRING,     ModulOutputs[8].Name,                      ModulOutputs[8].Id,                           0)
}

#undef MODUL_OUTPUTS
#define MODUL_OUTPUTS_SIZE (sizeof(ModulOutputs)/sizeof(ModulOutputs[0]))

//-----------------------------------------------------------------------
// WRITE VARS TO VARDB     WRITE VARS TO VARDB     WRITE VARS TO VARDB
//-----------------------------------------------------------------------

static STATUS InitOutputVars(void)
{
   STATUS LocalStatus;
   // Read outputdata
   LocalStatus = OS_ReadVariables(ModulOutputs, MODUL_OUTPUTS_SIZE);
   if (LocalStatus != 0)
   {
      AppSystemLog(ERR_4, MODULE_NAME"InitErr: element=%d elementpointer=0x%x", LocalStatus, &ModulOutputs[LocalStatus]);
      return ERR_4;
   }
   return OS_SUCCESS;
}
static STATUS OutputReferenceRoutine(U8 ModuleState)
{
   STATUS LocalStatus = 0;
   // Write Outputdata
   LocalStatus = OS_WriteVariablesConditional(ModulOutputs, MODUL_OUTPUTS_SIZE);
   if (LocalStatus != 0)
   {
      AppSystemLog(ERR_5, MODULE_NAME"WriteVErr: element=%d elementpointer=0x%x", LocalStatus, &ModulOutputs[LocalStatus]);
      return ERR_5;
   }
   return 0;
}

#define WRITE_VARS

//-----------------------------------------------------------------------
// VERIFY VARIABLES CREATION                 VERIFY VARIABLES CREATION
//-----------------------------------------------------------------------

static STATUS LocalIoCheck(void)
{
   // Check if input variables exist.
   STATUS LocalStatus;

   LocalStatus = OS_DoesVariablesExist(ModulInputs, MODUL_INPUTS_SIZE);
   if (LocalStatus != 0)
   {
      AppSystemLog(ERR_1, MODULE_NAME"InputErr: %d", LocalStatus);
      AppSystemLog(ERR_1, "Name: %s", ModulInputs[LocalStatus-1].Name);
      return ERR_1;
   }
   (void)VarsReadTypeCheck();

   int groupIndex;
   for (groupIndex = 0; groupIndex < PARAMETERS_GROUPS_SIZE; groupIndex++)
   {
      LocalStatus = OS_DoesVariablesExist(ModulParameters[groupIndex], ParaGroupsSizes[groupIndex]);
      if (LocalStatus != 0)
      {
         AppSystemLog(ERR_3, MODULE_NAME"ParameterErr: %d Group:%d", LocalStatus, groupIndex);
         AppSystemLog(ERR_3, "Name: %s", ModulParameters[groupIndex][LocalStatus-1].Name);
         return ERR_3;
      }
   }
   (void)ParaVarsReadTypeCheck();

   LocalStatus = OS_DoesVariablesExist(ModulOutputs, MODUL_OUTPUTS_SIZE);
   if (LocalStatus != 0)
   {
      AppSystemLog(ERR_2, MODULE_NAME"OutputErr: %d", LocalStatus);
      AppSystemLog(ERR_2, "Name: %s", ModulOutputs[LocalStatus-1].Name);
      return ERR_2;
   }
   (void)VarsWriteTypeCheck();

   return OS_SUCCESS;
}

#define VERIFY_VARIABLES

//-----------------------------------------------------------------------
// ALLOCATE MEMORY FOR SUMMATIONS        ALLOCATE MEMORY FOR SUMMATIONS
//-----------------------------------------------------------------------

static SSUM SSummationS_LubricationPP_Pump;

//-----------------------------------------------------------------------
// SUMMATIONS                  SUMMATIONS                  SUMMATIONS
//-----------------------------------------------------------------------

static struct os_db_summation ServiceSummations[] =
{
   VAR_ELEMENT_SERVICE_SUM( "S_LubricationPP_Pump",                     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_99,                 "DO_LubricationPP_Pump",                    SSummationS_LubricationPP_Pump   ),
};

static STATUS CreateSummations(void)
{
  STATUS LocalStatus = 0;
  size_t ErrorEntry = 0;

  LocalStatus = OS_SUM_CreateSummations(ServiceSummations, sizeof(ServiceSummations)/sizeof(ServiceSummations[0]), &ErrorEntry, AppBackupPosition());
  if (OS_SUCCESS != LocalStatus)
  {
    return LocalStatus;
  }

  return LocalStatus;
}

#define CREATE_SUMMATIONS

//-----------------------------------------------------------------------
// DEFINE MENUS               DEFINE MENUS               DEFINE MENUS
//-----------------------------------------------------------------------



// Menu line and link to local menu
//-----------------------------------------------------------------------
static struct line_struct M_Lubrication_Pitch_Bearing_MT_Type1LinkToLocalMenu[] =
{
   MENU_ELEMENT_LINE_LINK("Lubrication Pitch Pinion",          PASSWORD_LEVEL_END_CUSTOMER,        "M_Lubrication_Pitch_Bearing_MT_Type1", "G_Lubrication_Pitch_Pinion_MT_Type1"),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_Lubrication_Pitch_Bearing_MT_Type1Menu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_Lubrication_Pitch_Bearing_MT_Type1",PASSWORD_LEVEL_END_CUSTOMER),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_Lubrication_Pitch_Bearing_MT_Type1MenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("LUBRICATION PITCH PINION",          PASSWORD_LEVEL_END_CUSTOMER,        "M_"APP_ID"AppMain",                "G_"APP_ID"App"),
   MENU_ELEMENT_LINE_VARRO("Pitch Pinion Lub. Pump State",     PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_Lub_Equip0_StateTxt",                      LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_LINK("Status",                            PASSWORD_LEVEL_END_CUSTOMER,        "M_Status21212",                    "G_Lubrication_Pitch_Pinion_MT_Type1"),
   MENU_ELEMENT_LINE_LINK("Parameter",                         PASSWORD_LEVEL_END_CUSTOMER,        "M_Parameter32020",                 "G_Lubrication_Pitch_Pinion_MT_Type1"),
   MENU_ELEMENT_LINE_LINK("Service",                           PASSWORD_LEVEL_END_CUSTOMER,        "M_Service42428",                   "G_Lubrication_Pitch_Pinion_MT_Type1"),
   MENU_ELEMENT_LINE_LINK("Debug",                             PASSWORD_LEVEL_MITA_PROGRAMMER,     "M_Debug47",                        "G_Lubrication_Pitch_Pinion_MT_Type1"),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_Status21212Menu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_Status21212",                    PASSWORD_LEVEL_END_CUSTOMER),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_Status21212MenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("STATUS",                            PASSWORD_LEVEL_END_CUSTOMER,        "M_Lubrication_Pitch_Bearing_MT_Type1", "G_Lubrication_Pitch_Pinion_MT_Type1"),
   MENU_ELEMENT_LINE_VARRO("Pitch Pinion Lub. Mode Request",   PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_Lub_Equip0_ModeTxt",                       LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Pitch Pinion Lub. Pump State",     PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_Lub_Equip0_StateTxt",                      LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Pitch Pinion Lub. Status",         PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_Lub_Equip0_StatusTxt",                     LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Pitch Pinion Lub. Timer",          PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_LubricationPP_TimeIndicationTxt",          LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Pitch Pinion Lub. Pump",           PASSWORD_LEVEL_END_CUSTOMER,        (char*)"DO_LubricationPP_Pump",                      LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Pitch Pinion Lub. Oil Level",      PASSWORD_LEVEL_END_CUSTOMER,        (char*)"DI_LubricationPP_LevelWarning",              LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Pitch Pinion Lub. Pump Distributor", PASSWORD_LEVEL_END_CUSTOMER,        (char*)"DI_LubricationPP_PumpFailure",               LINE_FORMAT_NONE),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_Parameter32020Menu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_Parameter32020",                 PASSWORD_LEVEL_END_CUSTOMER),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_Parameter32020MenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("PARAMETER",                         PASSWORD_LEVEL_END_CUSTOMER,        "M_Lubrication_Pitch_Bearing_MT_Type1", "G_Lubrication_Pitch_Pinion_MT_Type1"),
   MENU_ELEMENT_LINE_VARRW("Pitch Pinion Lub. Control Mode",   PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_LubricationPP_InternalMode",               LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Pitch Pinion Lub. Pump On Stroke", PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_LubricationPP_Stroke_ON",                  LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Pitch Pinion Lub. Pump Off Time",  PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_LubricationPP_PumpOffTime",                LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Pitch Pinion Lub. Start Angle",    PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_PitchLubricationBladeAngleStart",          LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Pitch Pinion Lub. Stop Angle",     PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_PitchLubricationBladeAngleStop",           LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Pitch Pinion Lub. FB Type",        PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_LubricationPP_FeedbackType",               LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Pitch Pinion Lub. FB Time",        PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_LubricationPP_FeedbackTime",               LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Max Time with Oil Level Low",      PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_LubricationPP_LevelLowOnTime",             LINE_FORMAT_NONE),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_Service42428Menu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_Service42428",                   PASSWORD_LEVEL_END_CUSTOMER),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_Service42428MenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("SERVICE",                           PASSWORD_LEVEL_END_CUSTOMER,        "M_Lubrication_Pitch_Bearing_MT_Type1", "G_Lubrication_Pitch_Pinion_MT_Type1"),
   MENU_ELEMENT_LINE_VARRW("Pitch Pinion Lub. Service Control", PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_LubricationPP_PumpServiceCtrl",            LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Pitch Pinion Lub. Oil Tank Empty Time", PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_LubricationPP_OilTankEmptyTimeTxt",        LINE_FORMAT_NONE),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_Debug47Menu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_Debug47",                        PASSWORD_LEVEL_MITA_PROGRAMMER),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_Debug47MenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("DEBUG",                             PASSWORD_LEVEL_MITA_PROGRAMMER,     "M_Lubrication_Pitch_Bearing_MT_Type1", "G_Lubrication_Pitch_Pinion_MT_Type1"),
   MENU_ELEMENT_LINE_VARRO("Pitch Pinion Lub. Mode Request",   PASSWORD_LEVEL_MITA_PROGRAMMER,     (char*)"V_Lub_Equip0_Mode",                          LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Pitch Pinion Lub. State",          PASSWORD_LEVEL_MITA_PROGRAMMER,     (char*)"V_Lub_Equip0_State",                         LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Pitch Pinion Lub. Status",         PASSWORD_LEVEL_MITA_PROGRAMMER,     (char*)"V_Lub_Equip0_Status",                        LINE_FORMAT_NONE),
};
// Creating parameters for multiplexed categories
//-----------------------------------------------------------------------
static struct multiplexed_info_struct M_Lubrication_Pitch_Bearing_MT_Type1MultiplexedCategoriesParameters[] =
{
0};

//-----------------------------------------------------------------------
// CREATE MENUS               CREATE MENUS               CREATE MENUS
//-----------------------------------------------------------------------

// Memory reservation
//-----------------------------------------------------------------------
static struct menu_group_struct ObjGroup[1];

// Creating the menus
//-----------------------------------------------------------------------
STATUS Lubrication_Pitch_Pinion_MT_Type1MenuAppInit(U8 ModuleState, OS_MEMORY_POOL* pPool)
{
   STATUS Status;

   if (ModuleState == APP_INIT1)
   {
      /* Create application group */
      Status = OS_CreateMenuGroup(ObjGroup, M_Lubrication_Pitch_Bearing_MT_Type1LinkToLocalMenu[0].LinkGroup);
      STATUS_LINE_VAR_RETURN_VALUE(Status);
   }

   Status = CreateAndInitializeMenu(ModuleState,
                                    M_Lubrication_Pitch_Bearing_MT_Type1MenuLines[0].LinkGroup,
                                    M_Lubrication_Pitch_Bearing_MT_Type1MenuLines[0].LinkName,
                                    ELEMENT(M_Lubrication_Pitch_Bearing_MT_Type1LinkToLocalMenu),
                                    M_Lubrication_Pitch_Bearing_MT_Type1LinkToLocalMenu[0].LinkGroup,
                                    ELEMENT(M_Lubrication_Pitch_Bearing_MT_Type1Menu),
                                    M_Lubrication_Pitch_Bearing_MT_Type1LinkToLocalMenu[0].LinkName,
                                    ELEMENT(M_Lubrication_Pitch_Bearing_MT_Type1MenuLines),
                                    pPool,
                                    M_Lubrication_Pitch_Bearing_MT_Type1MultiplexedCategoriesParameters);
   STATUS_LINE_VAR_RETURN_VALUE(Status);

   Status = CreateAndInitializeMenu(ModuleState,
                                    M_Status21212MenuLines[0].LinkGroup,
                                    M_Status21212MenuLines[0].LinkName,
                                    NULL,
                                    0,
                                    M_Lubrication_Pitch_Bearing_MT_Type1MenuLines[2].LinkGroup,
                                    ELEMENT(M_Status21212Menu),
                                    M_Lubrication_Pitch_Bearing_MT_Type1MenuLines[2].LinkName,
                                    ELEMENT(M_Status21212MenuLines),
                                    pPool,
                                    M_Lubrication_Pitch_Bearing_MT_Type1MultiplexedCategoriesParameters);
   STATUS_LINE_VAR_RETURN_VALUE(Status);

   Status = CreateAndInitializeMenu(ModuleState,
                                    M_Parameter32020MenuLines[0].LinkGroup,
                                    M_Parameter32020MenuLines[0].LinkName,
                                    NULL,
                                    0,
                                    M_Lubrication_Pitch_Bearing_MT_Type1MenuLines[3].LinkGroup,
                                    ELEMENT(M_Parameter32020Menu),
                                    M_Lubrication_Pitch_Bearing_MT_Type1MenuLines[3].LinkName,
                                    ELEMENT(M_Parameter32020MenuLines),
                                    pPool,
                                    M_Lubrication_Pitch_Bearing_MT_Type1MultiplexedCategoriesParameters);
   STATUS_LINE_VAR_RETURN_VALUE(Status);

   Status = CreateAndInitializeMenu(ModuleState,
                                    M_Service42428MenuLines[0].LinkGroup,
                                    M_Service42428MenuLines[0].LinkName,
                                    NULL,
                                    0,
                                    M_Lubrication_Pitch_Bearing_MT_Type1MenuLines[4].LinkGroup,
                                    ELEMENT(M_Service42428Menu),
                                    M_Lubrication_Pitch_Bearing_MT_Type1MenuLines[4].LinkName,
                                    ELEMENT(M_Service42428MenuLines),
                                    pPool,
                                    M_Lubrication_Pitch_Bearing_MT_Type1MultiplexedCategoriesParameters);
   STATUS_LINE_VAR_RETURN_VALUE(Status);

   Status = CreateAndInitializeMenu(ModuleState,
                                    M_Debug47MenuLines[0].LinkGroup,
                                    M_Debug47MenuLines[0].LinkName,
                                    NULL,
                                    0,
                                    M_Lubrication_Pitch_Bearing_MT_Type1MenuLines[5].LinkGroup,
                                    ELEMENT(M_Debug47Menu),
                                    M_Lubrication_Pitch_Bearing_MT_Type1MenuLines[5].LinkName,
                                    ELEMENT(M_Debug47MenuLines),
                                    pPool,
                                    M_Lubrication_Pitch_Bearing_MT_Type1MultiplexedCategoriesParameters);
   STATUS_LINE_VAR_RETURN_VALUE(Status);

   return OS_SUCCESS;
}

#define CREATE_MENU

//-----------------------------------------------------------------------
//               BUTTONS FUNCTIONS FORWARD DECLARATIONS
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// BUTTONS                       BUTTONS                      BUTTONS
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
//             SET/RESET FUNCTIONS FORWARD DECLARATIONS
//-----------------------------------------------------------------------
static U8 StatusSetFunc1907(void);
static U8 StatusSetFunc1934(void);
static U8 StatusSetFunc1971(void);
static U8 StatusResetFunc1971(void);
//-----------------------------------------------------------------------
// STATUSCODES                 STATUSCODES                 STATUSCODES
//-----------------------------------------------------------------------

static struct sts_statuscode_structure StatusCodes[] =
{
   STS_CODE_ELEMENT("Pitch lubrica. err",     20*SEC,    1907,      STATUSCODE_UPDATE_TYPE_POLLING,         PASSWORD_LEVEL_SERVICE,            STATUSCODE_TIMER_TYPE_CONSTANT,     STATUSCODE_TIMER_TYPE_CONSTANT,     STATUSCODE_RESET_TYPE_DISPLAY,      STATUSCODE_PRIORITY_LOW,       27,   0,    32,   NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         StatusSetFunc1907,       NULL,                    BRAKE_PROG_0,        BRAKE_PROG_0,        BRAKE_PROG_MAX,      NULL,                PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    YAW_PROG_0,          YAW_PROG_0,          YAW_PROG_240,        NULL,                PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    1,    0,    255,  NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            1,  PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      100,       20,        1000,      NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    1*SEC,     SETDELAY_MIN,   SETDELAY_MAX,   NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         0,         RESETDELAY_MIN, RESETDELAY_MAX, NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         REPEATTIMES_MIN,     REPEATTIMES_MAX,     NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         REPEATPERIOD_MIN,    REPEATPERIOD_MAX,    NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         REPEATCODE_MIN,      REPEATCODE_MAX,      NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         TIMEOUTPERIOD_MIN,   65535,               NULL,      PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         TIMEOUTCODE_MIN,     TIMEOUTCODE_MAX,     NULL,      PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         NULL),
   STS_CODE_ELEMENT("Pitch lubr. empty",      20*SEC,    1934,      STATUSCODE_UPDATE_TYPE_POLLING,         PASSWORD_LEVEL_SERVICE,            STATUSCODE_TIMER_TYPE_CONSTANT,     STATUSCODE_TIMER_TYPE_CONSTANT,     STATUSCODE_RESET_TYPE_DISPLAY,      STATUSCODE_PRIORITY_LOW,       27,   0,    32,   NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         StatusSetFunc1934,       NULL,                    BRAKE_PROG_0,        BRAKE_PROG_0,        BRAKE_PROG_MAX,      NULL,                PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,                   YAW_PROG_0,          YAW_PROG_240,        NULL,                PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    1,    0,    255,  NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            1,  PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      100,       20,        1000,      NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         SETDELAY_MIN,   SETDELAY_MAX,   NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         0,         RESETDELAY_MIN, RESETDELAY_MAX, NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         0,         REPEATTIMES_MIN,     REPEATTIMES_MAX,     NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         REPEATPERIOD_MIN,    REPEATPERIOD_MAX,    NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         REPEATCODE_MIN,      REPEATCODE_MAX,      NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         TIMEOUTPERIOD_MIN,   TIMEOUTPERIOD_MAX,   NULL,      PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         TIMEOUTCODE_MIN,     TIMEOUTCODE_MAX,     NULL,      PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         NULL),
   STS_CODE_ELEMENT("Pitch lubrica. Warn",    20*SEC,    1971,      STATUSCODE_UPDATE_TYPE_POLLING,         PASSWORD_LEVEL_SERVICE,            STATUSCODE_TIMER_TYPE_CONSTANT,     STATUSCODE_TIMER_TYPE_CONSTANT,     STATUSCODE_RESET_TYPE_AUTOMATIC,    STATUSCODE_PRIORITY_LOW,       27,   0,    32,   NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         StatusSetFunc1971,       StatusResetFunc1971,     BRAKE_PROG_0,        BRAKE_PROG_0,        BRAKE_PROG_MAX,      NULL,                PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    YAW_PROG_0,          YAW_PROG_0,          YAW_PROG_240,        NULL,                PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,    0,    255,  NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            1,  PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      100,       20,        1000,      NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    1*MINUTE,  SETDELAY_MIN,   SETDELAY_MAX,   NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         0,         RESETDELAY_MIN, RESETDELAY_MAX, NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         0,         REPEATTIMES_MIN,     REPEATTIMES_MAX,     NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         REPEATPERIOD_MIN,    REPEATPERIOD_MAX,    NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         REPEATCODE_MIN,      REPEATCODE_MAX,      NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         TIMEOUTPERIOD_MIN,   65535,               NULL,      PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         TIMEOUTCODE_MIN,     TIMEOUTCODE_MAX,     NULL,      PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         NULL),
};

static STATUS_CODE_CONTROL_BLOCK StatusCodeControlBlock;

static STATUS LocalStatusCodeInit(void)
{
   STATUS LocalStatus;

   LocalStatus = OS_StatusCodeInit(STATUSCODE_INTERFACE_VERSION,
                                   &StatusCodeControlBlock,
                                   StatusCodes,
                                   sizeof(StatusCodes)/sizeof(StatusCodes[0]),
                                   AppLocalParameterPosition(),
                                   AppBackupPosition());
   STATUS_LINE_VAR_RETURN_CONST(LocalStatus, ERR_3);

   return OS_SUCCESS;
}

#define CREATE_STATUS_CODES

//-----------------------------------------------------------------------
// MODIFIABLE                  MODIFIABLE                   MODIFIABLE
//-----------------------------------------------------------------------

extern const char Lubrication_Pitch_Pinion_MT_Type1AppGroupName[];
extern const char Lubrication_Pitch_Pinion_MT_Type1AppMenuName[];

static void Init_Structures_From_Conf_File(void)
{
   M_Lubrication_Pitch_Bearing_MT_Type1MenuLines[0].LinkName = (char*)Lubrication_Pitch_Pinion_MT_Type1AppMenuName;
   M_Lubrication_Pitch_Bearing_MT_Type1MenuLines[0].LinkGroup = (char*)Lubrication_Pitch_Pinion_MT_Type1AppGroupName;
}

//-----------------------------------------------------------------------
// AUTOGENERATED END        AUTOGENERATED END        AUTOGENERATED END
//-----------------------------------------------------------------------
//}

#undef AUTOGENERATED_PART

//-----------------------------------------------------------------------
// USER DEFINITIONS         USER DEFINITIONS         USER DEFINITIONS
//-----------------------------------------------------------------------

//________________________________________________________________________
typedef struct _STimer_t
{
    time_t           P_Time;
    U8               OStatus;

    U8               FirstRun;
    U8               Start;
    U8               Suspend;
    time_t           TimeStart;
    time_t           TimeLast;
    time_t           Backup;
} STimer_t;
//________________________________________________________________________
// Function prototypes:
static void TimerReset (STimer_t *pTimer);
static time_t TimerLeft(STimer_t *pTimer);
static void TimerSet   (STimer_t *pTimer, time_t Delay);
static BOOL TimerCheck (STimer_t *pTimer);
static void TimerStop  (STimer_t *pTimer);
static void TimerStart (STimer_t *pTimer);

static void TimeToText(U64 Time, char *Text, U8 size);

#if 0       //  For future use
//________________________________________________________________________
static void TimerInit(STimer_t *pTimer, time_t Delay)
{
    pTimer->P_Time = Delay;
    pTimer->FirstRun  = 0;
}
#endif

//________________________________________________________________________
static void TimerReset( STimer_t *pTimer )        //  Reset all values to default and start timer automatically
{
    pTimer->TimeStart = OS_GetTimeInMs();
    pTimer->Backup    = 0;
    pTimer->OStatus   = 0;
    pTimer->Suspend   = 0;
    pTimer->FirstRun  = 1;
    pTimer->Start     = 1;
}
//________________________________________________________________________
static time_t TimerLeft( STimer_t *pTimer )
{
time_t  TimeDiff = 0;

    if( !TimerCheck(pTimer) )
    {
        TimeDiff = OS_GetTimeInMs();    //  time can change within two following commands, so it is needed to save time at some moment of time to temporary variable
        return (pTimer->P_Time > ( TimeDiff - pTimer->TimeStart )) ? (pTimer->P_Time - ( TimeDiff - pTimer->TimeStart )) : 0;
    }
    else
    {
        return 0;
    }
}
//________________________________________________________________________
static void TimerSet( STimer_t *pTimer, time_t Delay )        // Timer can be restored from backup by this function
{
    if(Delay < pTimer->P_Time) { pTimer->TimeStart = OS_GetTimeInMs() -  pTimer->P_Time + Delay; }
    else                       { pTimer->TimeStart = OS_GetTimeInMs(); }
}
//________________________________________________________________________
static BOOL TimerCheck( STimer_t *pTimer )
{
    if( pTimer->Start && !pTimer->OStatus )
    {
        pTimer->TimeLast = OS_GetTimeInMs() - pTimer->TimeStart;
        if( pTimer->TimeLast >= pTimer->P_Time )
        {
            pTimer->TimeStart = 0;
            pTimer->OStatus   = 1;
        }
    }
    return pTimer->OStatus;
}
//________________________________________________________________________
static void TimerStop( STimer_t *pTimer )       // Backup current time and stop timer
{
    if( 0 == pTimer->Suspend ) { pTimer->Backup = TimerLeft(pTimer); }
    pTimer->Start = 0;
    pTimer->Suspend = 1;
}
//________________________________________________________________________
static void TimerStart( STimer_t *pTimer )    // Start timer if it was stopped before or was not started/resetted
{
    if( pTimer->Suspend )                     // timer was stopped previously, so reinitialize timer from backup and start it
    {
        TimerSet(pTimer, pTimer->Backup);
        pTimer->Suspend = 0;
        pTimer->Backup  = 0;
        pTimer->OStatus = 0;
        pTimer->Start   = 1;
    }
    else
    {
        pTimer->OStatus   = 0;
        pTimer->Suspend   = 0;
        pTimer->Backup    = 0;
        pTimer->FirstRun  = 1;
        pTimer->Start     = 1;
    }
}
//________________________________________________________________________

enum { LUB_MODE_PERIODIC_EXTRA_CTRL = 0 };
enum { LUB_MODE_PERIODIC_SIMPLE     = 1 };
enum { LUB_MODE_ALWAYS_ON           = 2 };

// Lubrication State
enum { PP_LUB_SERVICE_OFF          = 1 };
enum { PP_LUB_SERVICE_ON           = 2 };
enum { PP_LUB_BLOCKED              = 4 };
enum { PP_LUB_SUSPENDED            = 5 };
enum { PP_LUB_AUTO_OFF             = 6 };
enum { PP_LUB_AUTO_ON              = 7 };

// Lubrication Status
enum { PP_LUB_STATUS_OK            = 0 };
enum { PP_LUB_STATUS_SAFETY        = 1 };
enum { PP_LUB_STATUS_HW_ERROR      = 2 };
enum { PP_LUB_STATUS_EMPTY         = 3 };
enum { PP_LUB_STATUS_GRID_ERROR    = 4 };
enum { PP_LUB_STATUS_LVRT          = 5 };
enum { PP_LUB_STATUS_BP_ACTIVE     = 6 };
enum { PP_LUB_STATUS_LM_BLOCK      = 7 };
enum { PP_LUB_STATUS_BLADE_ANGLE   = 8 };

enum { MB_LUB_PUMP_OFF             = 0 };
enum { MB_LUB_PUMP_ON              = 1 };

static const char PP_LUB_STATUS_OK_TEXT[]           = "OK";
static const char PP_LUB_STATUS_SAFETY_TEXT[]       = "Safety";
static const char PP_LUB_STATUS_HW_ERROR_TEXT[]     = "HW Error";
static const char PP_LUB_STATUS_EMPTY_TEXT[]        = "Tank Empty";
static const char PP_LUB_STATUS_GRID_ERROR_TEXT[]   = "Grid Error";
static const char PP_LUB_STATUS_LVRT_TEXT[]         = "LVRT";
static const char PP_LUB_STATUS_BP_ACTIVE_TEXT[]    = "BP Active";
static const char PP_LUB_STATUS_LM_BLOCK_TEXT[]     = "LM Block";
static const char PP_LUB_STATUS_BLADE_ANGLE_TEXT[]  = "Pitch Angle";

enum { LUB_ERROR_FB_TYPE_LOW_LEVEL    = 0 };
enum { LUB_ERROR_FB_TYPE_HIGH_LEVEL   = 1 };
enum { LUB_ERROR_FB_TYPE_FREQUENCY    = 2 };

#ifndef NA_TEXT
static const char NA_TEXT[] = "N/A";
#endif
//_______________________________________________________________________________________
static void WriteState(S32 State, char *Text, S32 Size)
{
static U8 OldState = 0xFF;

    if ( State != OldState )
    {
        switch(State)
        {
            case STATE_SERVICE_OFF :    { strncpy(Text, STATE_TEXT_SERVICE_OFF, Size); } break;
            case STATE_SERVICE_ON  :    { strncpy(Text, STATE_TEXT_SERVICE_ON,  Size); } break;
            case STATE_AUTO_ON     :    { strncpy(Text, STATE_TEXT_AUTO_ON,     Size); } break;
            case STATE_AUTO_OFF    :    { strncpy(Text, STATE_TEXT_AUTO_OFF,    Size); } break;
            case STATE_BLOCKED     :    { strncpy(Text, STATE_TEXT_BLOCKED,     Size); } break;
            case STATE_SUSPENDED   :    { strncpy(Text, STATE_TEXT_SUSPENDED,   Size); } break;
            default:                    { strncpy(Text, STATE_TEXT_UNDEFINED,   Size); } break;
        }
    }
    OldState = State;
}

//______________________________________________________________________________________
static void WriteStatus(U8 Status, char *Text, S32 Size)
{
static U8 OldStatus = 0xFF;

    if ( Status != OldStatus )
    {
        switch(Status)
        {
            case  PP_LUB_STATUS_OK:         { strncpy(Text, PP_LUB_STATUS_OK_TEXT,          Size); } break;
            case  PP_LUB_STATUS_SAFETY:     { strncpy(Text, PP_LUB_STATUS_SAFETY_TEXT,      Size); } break;
            case  PP_LUB_STATUS_HW_ERROR:   { strncpy(Text, PP_LUB_STATUS_HW_ERROR_TEXT,    Size); } break;
            case  PP_LUB_STATUS_EMPTY:      { strncpy(Text, PP_LUB_STATUS_EMPTY_TEXT,       Size); } break;
            case  PP_LUB_STATUS_GRID_ERROR: { strncpy(Text, PP_LUB_STATUS_GRID_ERROR_TEXT,  Size); } break;
            case  PP_LUB_STATUS_LVRT:       { strncpy(Text, PP_LUB_STATUS_LVRT_TEXT,        Size); } break;
            case  PP_LUB_STATUS_BP_ACTIVE:  { strncpy(Text, PP_LUB_STATUS_BP_ACTIVE_TEXT,   Size); } break;
            case  PP_LUB_STATUS_LM_BLOCK:   { strncpy(Text, PP_LUB_STATUS_LM_BLOCK_TEXT,    Size); } break;
            case  PP_LUB_STATUS_BLADE_ANGLE:{ strncpy(Text, PP_LUB_STATUS_BLADE_ANGLE_TEXT, Size); } break;
            default:                        { strncpy(Text, STATUS_TEXT_UNDEFINED,          Size); } break;
        }
    }
    OldStatus = Status;
}

//______________________________________________________________________________________
static STimer_t PPLubrication_OffTimer;
static STimer_t PPLubrication_LevelWarningTimer;
static STimer_t PPLubrication_FeedbackTimer;

//-----------------------------------------------------------------------
// SET/RESET FUNCTIONS    SET/RESET FUNCTIONS    SET/RESET FUNCTIONS
//-----------------------------------------------------------------------
static U8 StatusSetFunc1907(void)
{ // Pitch lubrica. err
static U8 FeedbackOldState = 0;
static U8 FeedbackType_old = 0;
static U8 FirstTime = 1;

    if( WPlineError() ) { return 0; }

    if( FeedbackType_old != P_LubricationPP_FeedbackType )
    {
        FeedbackType_old = P_LubricationPP_FeedbackType;
        if( LUB_ERROR_FB_TYPE_FREQUENCY == P_LubricationPP_FeedbackType ) { TimerReset(&PPLubrication_FeedbackTimer); }
    }

    switch( P_LubricationPP_FeedbackType )
    {
        case LUB_ERROR_FB_TYPE_LOW_LEVEL:
        {
            if( 0 == DI_LubricationPP_PumpFailure ) return 1;
        }
        break;
        case LUB_ERROR_FB_TYPE_HIGH_LEVEL:
        {
            if( 1 == DI_LubricationPP_PumpFailure ) return 1;
        }
        break;
        case LUB_ERROR_FB_TYPE_FREQUENCY:
        {
            if( !DO_LubricationPP_Pump )
            {
				TimerReset(&PPLubrication_FeedbackTimer);
                return 0;
            }
            if( FirstTime )
            {
                FirstTime = 0;
                TimerReset(&PPLubrication_FeedbackTimer);
            }
            if( FeedbackOldState != DI_LubricationPP_PumpFailure )
            {
                FeedbackOldState = DI_LubricationPP_PumpFailure;
                TimerReset(&PPLubrication_FeedbackTimer);
            }
            if( TimerCheck(&PPLubrication_FeedbackTimer) )
			{
				TimerReset(&PPLubrication_FeedbackTimer);
				return 1;
			}
        }
        break;
        default:
        {
            return 1;
        }
        break;
    }

    return 0;
}
//______________________________________________________________________________________
static U8 StatusSetFunc1971(void)
{ // Pitch lubrica. Warn
    if( WPlineError() ) { return 0; }

    return !DI_LubricationPP_LevelWarning;
}
static U8 StatusResetFunc1971(void)
{ return !StatusSetFunc1971(); }
//______________________________________________________________________________________
static U8 StatusSetFunc1934(void)
{ // Pitch lubr. empty
static U8 FirstTime = 1;
static U8 FeedbackOldValue = 0;

    if( WPlineError() ) { return 0; }

    if( FirstTime )
    {
        FirstTime = 0;
        FeedbackOldValue = DI_LubricationPP_LevelWarning;
        strncpy(V_LubricationPP_OilTankEmptyTimeTxt, NA_TEXT, sizeof(V_LubricationPP_OilTankEmptyTimeTxt));
        if( DI_LubricationPP_LevelWarning )
        {
            B_OilTankEmptyErrorTimer = 0;
        }
        else
        {
            if( B_OilTankEmptyErrorTimer )
            {
                TimerSet(&PPLubrication_LevelWarningTimer, B_OilTankEmptyErrorTimer);
                TimerStart(&PPLubrication_LevelWarningTimer);
            }
            else
            {
                TimerReset(&PPLubrication_LevelWarningTimer);
            }
        }
    }

    if( FeedbackOldValue != DI_LubricationPP_LevelWarning )
    {
        FeedbackOldValue = DI_LubricationPP_LevelWarning;
        strncpy(V_LubricationPP_OilTankEmptyTimeTxt, NA_TEXT, sizeof(V_LubricationPP_OilTankEmptyTimeTxt));
        
        if( !DI_LubricationPP_LevelWarning )
        {
            TimerReset(&PPLubrication_LevelWarningTimer);
        }
    }

    if ( !DI_LubricationPP_LevelWarning )
    {
        B_OilTankEmptyErrorTimer = TimerLeft(&PPLubrication_LevelWarningTimer);
        TimeToText(B_OilTankEmptyErrorTimer, V_LubricationPP_OilTankEmptyTimeTxt, sizeof(V_LubricationPP_OilTankEmptyTimeTxt));
        if( TimerCheck(&PPLubrication_LevelWarningTimer) )
        {
            return 1;
        }
    }

    return 0;
}
//-----------------------------------------------------------------------
// DRIVER FUNCTION         DRIVER FUNCTION         DRIVER FUNCTION
//-----------------------------------------------------------------------
enum { STOP_CYCLE, START_CYCLE };
typedef struct
{
    U8 cycle;
    U8 old_data;
    U8 state;
}cycle_t;

static void StartCycle(cycle_t *a)
{
    a->state = START_CYCLE;
}
static void StopCycle(cycle_t *a)
{
    a->state = STOP_CYCLE;
}
static void ResetCycle(cycle_t *a, U8 data)
{
    a->old_data = data;
    a->cycle = 0;
    a->state = STOP_CYCLE;
}
static U8 WaitCycle(U8 data, U8 cycle_req, cycle_t *a)
{
    if( STOP_CYCLE == a->state )
    {
        return 0;
    }

    if(data != a->old_data)
    {
        a->cycle++;
        a->old_data = data;
    }

    return (cycle_req == (a->cycle/2));
}
//-----------------------------------------------------------------------
// INIT                   INIT                     INIT
//-----------------------------------------------------------------------
static cycle_t LubricationPP_StrokeCtrl;
//-----------------------------------------------------------------------
// CONTROL                CONTROL                 CONTROL
//-----------------------------------------------------------------------
static void AssignParameters (void)
{
    if ( ParametersChanged[GENERAL_GROUP] )
    {
        PPLubrication_OffTimer.P_Time           = P_LubricationPP_PumpOffTime;
        PPLubrication_LevelWarningTimer.P_Time  = P_LubricationPP_LevelLowOnTime;
        PPLubrication_FeedbackTimer.P_Time      = P_LubricationPP_FeedbackTime;

        ParametersChanged[GENERAL_GROUP] = 0;
    }
}
//___________________________________________________________________________
static U8 BlockPPLubrication(void)
{
    if      ( StatusCodeActive(10)   )          { V_Lub_Equip0_Status = PP_LUB_STATUS_SAFETY; }
    else if ( StatusCodeActive(1907) )          { V_Lub_Equip0_Status = PP_LUB_STATUS_HW_ERROR; }
    else if ( StatusCodeActive(1934) )          { V_Lub_Equip0_Status = PP_LUB_STATUS_EMPTY; }
    else if ( V_Grid_ErrorActive     )          { V_Lub_Equip0_Status = PP_LUB_STATUS_GRID_ERROR; }
    else if ( V_ActiveControlProgram1 >= 50 )   { V_Lub_Equip0_Status = PP_LUB_STATUS_BP_ACTIVE; }
    else                                        { V_Lub_Equip0_Status = PP_LUB_STATUS_OK; }

    return V_Lub_Equip0_Status;
}
//_________________________________________________________________________________
static void TimeToText(U64 Time, char *Text, U8 size)
{
    Time = Time / 1000; //  result in seconds
    if( Time > 3600 )
    {
        sprintf( Text, "%u h, %d min",
                 (U32)(Time / 3600), (U32)((Time % 3600) / 60));
    }
    else if( (Time < 3600) && (Time > 60) )
    {
        snprintf( Text, size, "%u min, %u sec",
                  (U32)(Time / 60), (U32)(Time % 60));
    }
    else if( Time < 60 )
    {
        snprintf(Text, size, "%u sec", (U32)Time);
    }
}
//________________________________________________________________________________________
void PPLubricationPeriodicExtraCtrl( U8 NewModeFlag )
{
static U8 FirstTime = 1;
static U8 State = PP_LUB_AUTO_OFF;

    if( FirstTime )
    {
        FirstTime = 0;
        State = PP_LUB_AUTO_OFF;
        if( (B_PPLubricationTimer > 0) && (B_PPLubricationTimer < P_LubricationPP_PumpOffTime) )
        {
            TimerSet(&PPLubrication_OffTimer, B_PPLubricationTimer);
            TimerStart(&PPLubrication_OffTimer);
        }
        else
        {
            TimerReset(&PPLubrication_OffTimer);
        }
    }

    if( NewModeFlag )
    {
        TimerReset(&PPLubrication_OffTimer);
        State = PP_LUB_AUTO_OFF;
    }

    if( BlockPPLubrication() )
    {
        DO_LubricationPP_Pump = MB_LUB_PUMP_OFF;
        strncpy(V_LubricationPP_TimeIndicationTxt, NA_TEXT, sizeof(V_LubricationPP_TimeIndicationTxt));
        V_Lub_Equip0_State = STATE_BLOCKED;
    }
    else
    {
        switch( State )
        {
            case PP_LUB_AUTO_OFF:
            {
                DO_LubricationPP_Pump = MB_LUB_PUMP_OFF;
                V_Lub_Equip0_State = STATE_AUTO_OFF;
                if( TimerCheck(&PPLubrication_OffTimer) )
                {
                    B_PPLubricationTimer = 0;
                    if( (V_BladeSystem_PositionAct >= P_PitchLubricationBladeAngleStop) &&
                        (V_BladeSystem_PositionAct <= P_PitchLubricationBladeAngleStart) &&
                        ( MANAGER_MODE_ENABLE == V_Lub_Equip0_Mode ) )
                    {
                        ResetCycle(&LubricationPP_StrokeCtrl, DI_LubricationPP_PumpFailure);
						      StartCycle(&LubricationPP_StrokeCtrl);
                        State = PP_LUB_AUTO_ON;
                    }
                    else
                    {
                        StopCycle(&LubricationPP_StrokeCtrl);
                        State = PP_LUB_SUSPENDED;
                    }
                }
                else
                {
                    TimeToText(TimerLeft(&PPLubrication_OffTimer), V_LubricationPP_TimeIndicationTxt, sizeof(V_LubricationPP_TimeIndicationTxt));
                    B_PPLubricationTimer = TimerLeft(&PPLubrication_OffTimer);  //  Backup timer
                }
            }
            break;

            case PP_LUB_SUSPENDED:
            {
                DO_LubricationPP_Pump = MB_LUB_PUMP_OFF;
                V_Lub_Equip0_State = STATE_SUSPENDED;
                strncpy(V_LubricationPP_TimeIndicationTxt, NA_TEXT, sizeof(V_LubricationPP_TimeIndicationTxt));
                if( (V_BladeSystem_PositionAct >= P_PitchLubricationBladeAngleStop) &&
                    (V_BladeSystem_PositionAct <= P_PitchLubricationBladeAngleStart) &&
                    ( MANAGER_MODE_ENABLE == V_Lub_Equip0_Mode ) &&
                    ( 0 == V_Inverter_StatusLVRT ) )
                {
                    StartCycle(&LubricationPP_StrokeCtrl);
                    State = PP_LUB_AUTO_ON;
                }
                if ( V_Inverter_StatusLVRT )                                                { V_Lub_Equip0_Status = PP_LUB_STATUS_LVRT; }
                else if (MANAGER_MODE_DISABLE == V_Lub_Equip0_Mode)                         { V_Lub_Equip0_Status = PP_LUB_STATUS_LM_BLOCK; }
                else if( (V_BladeSystem_PositionAct < P_PitchLubricationBladeAngleStop) ||
                         (V_BladeSystem_PositionAct > P_PitchLubricationBladeAngleStart))   { V_Lub_Equip0_Status = PP_LUB_STATUS_BLADE_ANGLE; }
                else                                                                        { V_Lub_Equip0_Status = PP_LUB_STATUS_OK; }
            }
            break;

            case PP_LUB_AUTO_ON:
            {
                V_Lub_Equip0_State = STATE_AUTO_ON;
                if( WaitCycle(DI_LubricationPP_PumpFailure, P_LubricationPP_Stroke_ON, &LubricationPP_StrokeCtrl) )
                {
                    TimerReset(&PPLubrication_OffTimer);
                    State = PP_LUB_AUTO_OFF;
                }
                else
                {
                    if( (MANAGER_MODE_DISABLE == V_Lub_Equip0_Mode) || V_Inverter_StatusLVRT )
                    {
                        DO_LubricationPP_Pump = MB_LUB_PUMP_OFF;
                        StopCycle(&LubricationPP_StrokeCtrl);
                        State = PP_LUB_SUSPENDED;
                    }
                    else
                    {
                        DO_LubricationPP_Pump = MB_LUB_PUMP_ON;
                    }
                }
            }
            break;

            default: { } break;
        }
    }
}
//________________________________________________________________________________________
void PPLubricationPeriodicSimple( U8 NewModeFlag )
{
static U8 FirstTime = 1;
static U8 State = PP_LUB_AUTO_OFF;

    if( FirstTime )
    {
        FirstTime = 0;
        State = PP_LUB_AUTO_OFF;
        if( (B_PPLubricationTimer > 0) && (B_PPLubricationTimer < P_LubricationPP_PumpOffTime) )
        {
            TimerSet(&PPLubrication_OffTimer, B_PPLubricationTimer);
            TimerStart(&PPLubrication_OffTimer);
        }
        else
        {
            TimerReset(&PPLubrication_OffTimer);
        }
    }

    if( NewModeFlag )
    {
        TimerReset(&PPLubrication_OffTimer);
        State = PP_LUB_AUTO_OFF;
    }

    if( BlockPPLubrication() )
    {
        DO_LubricationPP_Pump = MB_LUB_PUMP_OFF;
        strncpy(V_LubricationPP_TimeIndicationTxt, NA_TEXT, sizeof(V_LubricationPP_TimeIndicationTxt));
        if( PP_LUB_AUTO_ON == State ) { StopCycle(&LubricationPP_StrokeCtrl); }
        V_Lub_Equip0_State = STATE_BLOCKED;
    }
    else
    {
        switch( State )
        {
            case PP_LUB_AUTO_OFF:
            {
                DO_LubricationPP_Pump = MB_LUB_PUMP_OFF;
                V_Lub_Equip0_State = STATE_AUTO_OFF;
                if( TimerCheck(&PPLubrication_OffTimer) )
                {
                    B_PPLubricationTimer = 0;
                    if( MANAGER_MODE_ENABLE == V_Lub_Equip0_Mode )
                    {
                        ResetCycle(&LubricationPP_StrokeCtrl, DI_LubricationPP_PumpFailure);
                        State = PP_LUB_AUTO_ON;
                    }
                    else
                    {
                        StopCycle(&LubricationPP_StrokeCtrl);
                        State = PP_LUB_SUSPENDED;
                    }
                }
                else
                {
                    TimeToText(TimerLeft(&PPLubrication_OffTimer), V_LubricationPP_TimeIndicationTxt, sizeof(V_LubricationPP_TimeIndicationTxt));
                    B_PPLubricationTimer = TimerLeft(&PPLubrication_OffTimer);  //  Backup timer
                }
            }
            break;

            case PP_LUB_SUSPENDED:
            {
                DO_LubricationPP_Pump = MB_LUB_PUMP_OFF;
                V_Lub_Equip0_State = STATE_SUSPENDED;
                strncpy(V_LubricationPP_TimeIndicationTxt, NA_TEXT, sizeof(V_LubricationPP_TimeIndicationTxt));
                if( (MANAGER_MODE_ENABLE == V_Lub_Equip0_Mode) && (0 == V_Inverter_StatusLVRT) )
                {
                    StartCycle(&LubricationPP_StrokeCtrl);
                    State = PP_LUB_AUTO_ON;
                }
                if ( V_Inverter_StatusLVRT )                         { V_Lub_Equip0_Status = PP_LUB_STATUS_LVRT; }
                else if( MANAGER_MODE_DISABLE == V_Lub_Equip0_Mode ) { V_Lub_Equip0_Status = PP_LUB_STATUS_LM_BLOCK; }
                else                                                 { V_Lub_Equip0_Status = PP_LUB_STATUS_OK; }
            }
            break;

            case PP_LUB_AUTO_ON:
            {
                if( STATE_BLOCKED == V_Lub_Equip0_State ) { StartCycle(&LubricationPP_StrokeCtrl); }
                V_Lub_Equip0_State = STATE_AUTO_ON;
                if( WaitCycle(DI_LubricationPP_PumpFailure, P_LubricationPP_Stroke_ON, &LubricationPP_StrokeCtrl) )
                {
                    TimerReset(&PPLubrication_OffTimer);
                    State = PP_LUB_AUTO_OFF;
                }
                else
                {
                    if( (MANAGER_MODE_DISABLE == V_Lub_Equip0_Mode) || V_Inverter_StatusLVRT )
                    {
                        DO_LubricationPP_Pump = MB_LUB_PUMP_OFF;
                        StopCycle(&LubricationPP_StrokeCtrl);
                        State = PP_LUB_SUSPENDED;
                    }
                    else
                    {
                        DO_LubricationPP_Pump = MB_LUB_PUMP_ON;
                    }
                }
            }
            break;
            default: { } break;
        }
    }
}
//________________________________________________________________________________________
void PPLubricationAlwaysOn( U8 NewModeFlag )
{
static U8 FirstTime = 1;
static U8 State = PP_LUB_SUSPENDED;     //  Do not turn pump ON initially before check for block or suspend conditions

    if( FirstTime || NewModeFlag )
    {
        FirstTime = 0;
        State = PP_LUB_SUSPENDED;
        strncpy(V_LubricationPP_TimeIndicationTxt, NA_TEXT, sizeof(V_LubricationPP_TimeIndicationTxt));
    }

    if( BlockPPLubrication() )
    {
        DO_LubricationPP_Pump = MB_LUB_PUMP_OFF;
        V_Lub_Equip0_State = STATE_BLOCKED;
    }
    else
    {
        switch( State )
        {
            case PP_LUB_AUTO_OFF:
            case PP_LUB_SUSPENDED:
            {
                DO_LubricationPP_Pump = MB_LUB_PUMP_OFF;
                V_Lub_Equip0_State = STATE_SUSPENDED;
                if( (MANAGER_MODE_ENABLE == V_Lub_Equip0_Mode) && (0 == V_Inverter_StatusLVRT) )
                {
                    State = PP_LUB_AUTO_ON;
                }
                if ( V_Inverter_StatusLVRT )                         { V_Lub_Equip0_Status = PP_LUB_STATUS_LVRT; }
                else if( MANAGER_MODE_DISABLE == V_Lub_Equip0_Mode ) { V_Lub_Equip0_Status = PP_LUB_STATUS_LM_BLOCK; }
                else                                                 { V_Lub_Equip0_Status = PP_LUB_STATUS_OK; }
            }
            break;

            case PP_LUB_AUTO_ON:
            {
                V_Lub_Equip0_State = STATE_AUTO_ON;
                if( (MANAGER_MODE_DISABLE == V_Lub_Equip0_Mode) || V_Inverter_StatusLVRT )
                {
                    DO_LubricationPP_Pump = MB_LUB_PUMP_OFF;
                    State = PP_LUB_SUSPENDED;
                }
                else
                {
                    DO_LubricationPP_Pump = MB_LUB_PUMP_ON;
                }
            }
            break;
            default: { } break;
        }
    }
}
//________________________________________________________________________________________

void PPLubricationAutoCtrl(U8 ServiceModeChanged)
{
static U8 InternalModeOldValue = 0;
static U8 FirstTime = 1;
       U8 NewModeFlag = 0;

    if( FirstTime )
    {
        FirstTime = 0;
        InternalModeOldValue = P_LubricationPP_InternalMode;
    }
    if( InternalModeOldValue != P_LubricationPP_InternalMode )
    {
        InternalModeOldValue = P_LubricationPP_InternalMode;
        NewModeFlag = 1;
    }
    if( ServiceModeChanged ) { NewModeFlag = 1; }

    switch( P_LubricationPP_InternalMode )
    {
        case LUB_MODE_PERIODIC_EXTRA_CTRL: { PPLubricationPeriodicExtraCtrl(NewModeFlag); } break;
        case LUB_MODE_PERIODIC_SIMPLE    : { PPLubricationPeriodicSimple(NewModeFlag);    } break;
        case LUB_MODE_ALWAYS_ON          : { PPLubricationAlwaysOn(NewModeFlag);          } break;
        default:
        {
            DO_LubricationPP_Pump = MB_LUB_PUMP_OFF;
            strncpy(V_LubricationPP_TimeIndicationTxt, NA_TEXT, sizeof(V_LubricationPP_TimeIndicationTxt));
            V_Lub_Equip0_State = STATE_AUTO_OFF;
        }
        break;
    }
}

//________________________________________________________________________________________
static STATUS LocalCtrl(void)
{
    STATUS LocalStatus = 0;
    static U8 FirstTime = 1;
    static U8 P_LubricationPP_PumpServiceCtrl_old;
           U8 ServiceModeChanged = 0;

    if( FirstTime )
    {
        AssignParameters();
        FirstTime = 0;
        strncpy(V_LubricationPP_TimeIndicationTxt, NA_TEXT, sizeof(V_LubricationPP_TimeIndicationTxt));
        P_LubricationPP_PumpServiceCtrl_old = P_LubricationPP_PumpServiceCtrl;
    }

    if( P_LubricationPP_PumpServiceCtrl_old != P_LubricationPP_PumpServiceCtrl )
    {
        P_LubricationPP_PumpServiceCtrl_old = P_LubricationPP_PumpServiceCtrl;
        ServiceModeChanged = 1;
    }

    if( BlockPPLubrication() ) { V_Lub_Equip0_State = STATE_BLOCKED; }      //Retrieve Status

    switch( P_LubricationPP_PumpServiceCtrl )
    {
        case MODE_AUTO :
        {
            PPLubricationAutoCtrl(ServiceModeChanged);
        }
        break;

        case MODE_SERVICE_OFF :
        {
            DO_LubricationPP_Pump = MB_LUB_PUMP_OFF;
            V_Lub_Equip0_State = STATE_SERVICE_OFF;
            V_Lub_Equip0_Status = PP_LUB_STATUS_OK;
            strncpy(V_LubricationPP_TimeIndicationTxt, NA_TEXT, sizeof(V_LubricationPP_TimeIndicationTxt));
        }
        break;

        case MODE_SERVICE_ON :
        {
            DO_LubricationPP_Pump = MB_LUB_PUMP_ON;
            V_Lub_Equip0_State = STATE_SERVICE_ON;
            V_Lub_Equip0_Status = PP_LUB_STATUS_OK;
            strncpy(V_LubricationPP_TimeIndicationTxt, NA_TEXT, sizeof(V_LubricationPP_TimeIndicationTxt));
        }
        break;

        default:
        {
        }
        break;
    }

    AssignParameters();

    // update object State and Status and write to VDB if updated
    WriteState (V_Lub_Equip0_State , V_Lub_Equip0_StateTxt , sizeof(V_Lub_Equip0_StateTxt ));
    WriteStatus(V_Lub_Equip0_Status, V_Lub_Equip0_StatusTxt, sizeof(V_Lub_Equip0_StatusTxt));

    return LocalStatus;
}

//-----------------------------------------------------------------------
// MAIN CALL             MAIN CALL               MAIN CALL
//-----------------------------------------------------------------------

STATUS Lubrication_Pitch_Pinion_MT_Type1(U8 ModuleState, OS_MEMORY_POOL *MemPool, U32 *Arg3)
{
   STATUS LocalStatus = 0;

   // Version check
   if(ModuleState == APP_INIT1)
   {
      LocalStatus = OS_ValidateAPI(API_VERSION_MAJOR,
                                   API_VERSION_MINOR,
                                   OS_LinkTime,
                                   ReleaseTag,
                                   __MODULE__
                                   );
      if ( OS_SUCCESS != LocalStatus )
      {
         return LocalStatus;
      }
   }
#ifdef READ_VARS
   // Read inputdata
   LocalStatus = InputReferenceRoutine(ModuleState);
   STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif
#ifdef COMMON_VDB_READ
   LocalStatus = ReadVdbWindow(ModuleState);
   STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif
   switch(ModuleState)
   {
      case APP_RUN :
      {
         #ifdef FUNCTION_BLOCKS_PRE_LOCAL_CONTROL
            LocalStatus = FunctionBlocksPreLocalCtrl( Interval );
            STATUS_LINE_VAR_RETURN_VALUE( LocalStatus );
         #endif

         LocalStatus = LocalCtrl();
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
        
         #ifdef FUNCTION_BLOCKS_POST_LOCAL_CONTROL
            LocalStatus = FunctionBlocksPostLocalCtrl( Interval );
            STATUS_LINE_VAR_RETURN_VALUE( LocalStatus );
         #endif

#ifdef WRITE_VARS
         // Write Outputdata
         LocalStatus = OutputReferenceRoutine(ModuleState);
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif

#ifdef COMMON_VDB_WRITE
         LocalStatus = WriteVdbWindow(ModuleState);
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif
         break;
      }
      case APP_INIT1 :
      {
         Init_Structures_From_Conf_File();

#ifdef CREATE_VARDB_VARS
         LocalStatus = CreateVarDbVars();
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif

#ifdef CREATE_MENU
         LocalStatus = Lubrication_Pitch_Pinion_MT_Type1MenuAppInit(ModuleState, MemPool);
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)

#ifdef MULTIPLEXIBLE_MENU
         LocalStatus = MenuArraysAppInit(ModuleState, MemPool);
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif
#endif

#ifdef CREATE_VARDB_ARRAY_VARS
         LocalStatus = CreateVdbArrays(MemPool);
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif

#ifdef CREATE_IO_VARS
         LocalStatus = CreateIOVars();
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif
         break;
      }
      case APP_INIT2 :
      {
#ifdef CREATE_MENU
#ifdef MULTIPLEXIBLE_MENU
         LocalStatus = MenuArraysAppInit(ModuleState, MemPool);
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif
#endif

#ifdef CREATE_ALIASES
         size_t ErrorEntry = 0;
         LocalStatus = OS_VarDB_CreateAliases(AliasVars, sizeof(AliasVars)/sizeof(AliasVars[0]), &ErrorEntry);
         STATUS_LINE_VAR_RETURN_CONST(LocalStatus, ErrorEntry)
#endif

#ifdef VERIFY_ARRAY
        LocalStatus = VerifyArray(MemPool);
        STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif

#ifdef VERIFY_VARIABLES
         LocalStatus = LocalIoCheck();
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif

#ifdef CREATE_BUTTONS
         LocalStatus = CreateButtons();
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif
         break;
      }
      case APP_INIT3 :
      {
#ifdef CREATE_SUMMATIONS
         LocalStatus = CreateSummations();
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif

#ifdef WRITE_VARS
         LocalStatus = InitOutputVars();
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif

#ifdef CREATE_STATUS_CODES
         LocalStatus = LocalStatusCodeInit();
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif

#ifdef CREATE_IO_VARS
        Lubrication_Pitch_Pinion_MT_Type1SetLockValues();
#endif
         break;
      }
      case APP_INIT4 :
      {
#ifdef CREATE_MENU
         LocalStatus = Lubrication_Pitch_Pinion_MT_Type1MenuAppInit(ModuleState, MemPool);
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)

#ifdef MULTIPLEXIBLE_MENU
         LocalStatus = MenuArraysAppInit(ModuleState, MemPool);
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif
#endif
         break;
      }
      case APP_INIT5 :
      {
#ifdef VALIDATE_HASH
         LocalStatus = ValidateHash(Lubrication_Pitch_Pinion_MT_Type1_copyright, MODULE_NAME, Lubrication_Pitch_Pinion_MT_Type1_initialValues);
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif

         #ifdef INIT_FUNCTION_BLOCKS
            LocalStatus = FunctionBlocksInit( Interval );
            STATUS_LINE_VAR_RETURN_VALUE( LocalStatus );
         #endif

         break;
      }
      default :
      {
         break;
      }
   }
   return OS_SUCCESS;
}
//-----------------------------------------------------------------------
