//*****************************PEPTOOL Header Start******************************
//                                                                               
//                         Copyright © 2015 Mita-Teknik.                         
//This software may only be used with WP4x00 Controllers delivered by Mita-Teknik
//                                                                               
//*******************************************************************************
//                                                                               
// $PEPTOOL version:9.0$                                                         
// $PEPTOOL file version:106$                                                    
//                                                                               
//*******************************************************************************
//                                                                               
// $Date: 2014/04/23 06:34:43 $                                                  
// $Author: MITA\ihn $                                                           
// $RCSfile: Lubrication_Main_Bearing_MT_Type1.c,v $                             
// $Revision: 1.10 $                                                             
//                                                                               
//******************************PEPTOOL Header End*******************************

//***********************************************************************

// OS header files
#include <os_main.h>
// AppLib header files
#include <lib_main.h>
// App header files
#include <turbdef.h>
#include <VarMacros.h>

// Object header file
#include <Lubrication_Main_Bearing_MT_Type1.h>

#define AUTOGENERATED_PART
//{
//-----------------------------------------------------------------------
// AUTOGENERATED START     AUTOGENERATED START     AUTOGENERATED START
//-----------------------------------------------------------------------

#define VALIDATE_HASH
char Lubrication_Main_Bearing_MT_Type1_copyright[] =
{
   67, 111, 112, 121, 114, 105, 103, 104, 116, 32, 63, 32, 50, 48, 49, 53,
   32, 77, 105, 116, 97, 45, 84, 101, 107, 110, 105, 107, 46, 13, 10, 84,
   104, 105, 115, 32, 115, 111, 102, 116, 119, 97, 114, 101, 32, 109, 97, 121,
   32, 111, 110, 108, 121, 32, 98, 101, 32, 117, 115, 101, 100, 32, 119, 105,
   116, 104, 32, 87, 80, 52, 120, 48, 48, 32, 67, 111, 110, 116, 114, 111,
   108, 108, 101, 114, 115, 32, 100, 101, 108, 105, 118, 101, 114, 101, 100, 32,
   98, 121, 32, 77, 105, 116, 97, 45, 84, 101, 107, 110, 105, 107, 0
};

#define MODULE_NAME "Lubrication Main Bearing MT Type1A"

//-----------------------------------------------------------------------
// ALLOCATE MEMORY FOR STRINGS IN VARDB
//-----------------------------------------------------------------------

static char A_V_LubricationMB_OilTankEmptyTimeTxt[31]  = "Not Initialized";
static char A_V_LubricationMB_TimeIndicationTxt[31]  = "12345678901234567890123456789";
static char A_V_Lub_Equip1_ModeTxt[31]  = "Disable";
static char A_V_Lub_Equip1_StateTxt[31]  = "N/A";
static char A_V_Lub_Equip1_StatusTxt[31]  = "N/A";
static char A_P_MainBearLubr_ManagerVars_String[31]  = "V_Lub_";

//-----------------------------------------------------------------------
// DEFINE LOCAL VARIABLES DEFINE LOCAL VARIABLES DEFINE LOCAL VARIABLES
//-----------------------------------------------------------------------

static struct os_db_local LocalVars[] =
{
   VAR_ELEMENT_LOCAL("V_LubricationMB_OilTankEmptyTimeTxt",      TYPE_STRING + sizeof(A_V_LubricationMB_OilTankEmptyTimeTxt) - 1,  PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   A_V_LubricationMB_OilTankEmptyTimeTxt, 0,                0,                NULL,  NOLOG_ENABLE  ),
   VAR_ELEMENT_LOCAL("V_LubricationMB_TimeIndicationTxt",        TYPE_STRING + sizeof(A_V_LubricationMB_TimeIndicationTxt) - 1,  PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   A_V_LubricationMB_TimeIndicationTxt, 0,                0,                NULL,  NOLOG_ENABLE  ),
   VAR_ELEMENT_LOCAL("V_Lub_Equip1_Mode",                        TYPE_S32,     PASSWORD_LEVEL_ADMINISTRATOR,      PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   0,               0,               1,               NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_Lub_Equip1_ModeTxt",                     TYPE_STRING + sizeof(A_V_Lub_Equip1_ModeTxt) - 1,  PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   A_V_Lub_Equip1_ModeTxt, 0,                0,                NULL,  NOLOG_ENABLE  ),
   VAR_ELEMENT_LOCAL("V_Lub_Equip1_State",                       TYPE_S32,     PASSWORD_LEVEL_ADMINISTRATOR,      PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   0,               S32_MIN,         S32_MAX,         NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_Lub_Equip1_StateTxt",                    TYPE_STRING + sizeof(A_V_Lub_Equip1_StateTxt) - 1,  PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   A_V_Lub_Equip1_StateTxt, 0,                0,                NULL,  NOLOG_ENABLE  ),
   VAR_ELEMENT_LOCAL("V_Lub_Equip1_Status",                      TYPE_S32,     PASSWORD_LEVEL_ADMINISTRATOR,      PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   0,               S32_MIN,         S32_MAX,         NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_Lub_Equip1_StatusTxt",                   TYPE_STRING + sizeof(A_V_Lub_Equip1_StatusTxt) - 1,  PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   A_V_Lub_Equip1_StatusTxt, 0,                0,                NULL,  NOLOG_ENABLE  ),
};

//-----------------------------------------------------------------------
// DEFINE PARAMETERS        DEFINE PARAMETERS        DEFINE PARAMETERS
//-----------------------------------------------------------------------

static struct os_db_parameter ParameterVars[] =
{
   VAR_ELEMENT_PARAMETER("P_LubricationMB_ServiceCtrl",              TYPE_U8,      PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_SERVICE,            SCALE_NONE,   0,       UNIT_NONE,          0,   0,               0,               2,               NULL  ),
   VAR_ELEMENT_PARAMETER("P_LubricationMB_PumpOffTime",              TYPE_U32,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         SCALE_DIV,    3600000, UNIT_HOUR,          1,   2400000,         600000,          604800000,       NULL  ),
   VAR_ELEMENT_PARAMETER("P_LubricationMB_EquipNo",                  TYPE_U8,      PASSWORD_LEVEL_ADMINISTRATOR,      PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   1,               0,               9,               NULL  ),
   VAR_ELEMENT_PARAMETER("P_LubricationMB_MinRotorRPM",              TYPE_U16,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         SCALE_DIV,    1000,    UNIT_RPM,           1,   1000,            0,               20000,           NULL  ),
   VAR_ELEMENT_PARAMETER("P_LubricationMB_LevelLowOnTime",           TYPE_U32,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         SCALE_DIV,    3600000, UNIT_HOUR,          0,   1209600000,      3600000,         2419200000,      NULL  ),
   VAR_ELEMENT_PARAMETER("P_LubricationMB_InternalMode",             TYPE_U8,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         SCALE_NONE,   0,       UNIT_NONE,          0,   0,               0,               2,               NULL  ),
   VAR_ELEMENT_PARAMETER("P_LubricationMB_FeedbackTime",             TYPE_U32,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         SCALE_DIV,    1000,    UNIT_SECOND,        1,   40000,           100,             300000,          NULL  ),
   VAR_ELEMENT_PARAMETER("P_LubricationMB_FeedbackType",             TYPE_U8,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         SCALE_NONE,   0,       UNIT_NONE,          0,   2,               0,               2,               NULL  ),
   VAR_ELEMENT_PARAMETER("P_MainBearLubr_ManagerVars_String",        TYPE_STRING + sizeof(A_P_MainBearLubr_ManagerVars_String) - 1,  PASSWORD_LEVEL_ADMINISTRATOR,      PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   A_P_MainBearLubr_ManagerVars_String, 0,                0,                NULL  ),
   VAR_ELEMENT_PARAMETER("P_LubricationMB_Stroke_ON",                TYPE_U8,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         SCALE_NONE,   0,       UNIT_NONE,          0,   3,               1,               10,              NULL  ),
};

//-----------------------------------------------------------------------
// DEFINE BACKUPS            DEFINE BACKUPS            DEFINE BACKUPS
//-----------------------------------------------------------------------

static struct os_db_backup BackupVars[] =
{
   VAR_ELEMENT_BACKUP_U64("B_MBOilTankEmptyErrorTimer",                        PASSWORD_LEVEL_ADMINISTRATOR,      PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    1000,    UNIT_NONE,          0,   0ULL,            U64_MIN,         U64_MAX,         NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_BACKUP_U64("B_MBLubricationTimer",                              PASSWORD_LEVEL_ADMINISTRATOR,      PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   0ULL,            U64_MIN,         U64_MAX,         NULL,  NOLOG_ENABLE),
};

//----------------------------------------------------------------------------------
// DEFINE VAR ARRAYS            DEFINE VAR ARRAYS            DEFINE VAR ARRAYS
//----------------------------------------------------------------------------------
char Lubrication_Main_Bearing_MT_Type1_initialValues[] =
{
   84, 82, 52, 170, 58, 235, 167, 32, 97, 7, 19, 175, 43, 169, 202, 0,
   81, 207, 223, 57, 34, 221, 239, 108, 34, 212, 85, 87, 179, 14, 45, 1,
   0
};

//-----------------------------------------------------------------------
// CREATE DATABASE VARS   CREATE DATABASE VARS   CREATE DATABASE VARS
//-----------------------------------------------------------------------

static STATUS CreateVarDbVars(void)
{
   STATUS Status;
   size_t ErrorEntry;

   Status = OS_VarDB_CreateLocals(LocalVars, sizeof(LocalVars)/sizeof(LocalVars[0]), &ErrorEntry, AppLocalParameterPosition());
   if (Status != 0)
   {
      AppSystemLog(ERR_7, MODULE_NAME"CrVL: %d,%d", Status, ErrorEntry);
      return ERR_7;
   }

   Status = OS_VarDB_CreateParameters(ParameterVars, sizeof(ParameterVars)/sizeof(ParameterVars[0]), &ErrorEntry, AppExportParameterPosition());
   if (Status != 0)
   {
      AppSystemLog(ERR_7, MODULE_NAME"CrVXP: %d,%d", Status, ErrorEntry);
      return ERR_7;
   }

   Status = OS_VarDB_CreateBackups(BackupVars, sizeof(BackupVars)/sizeof(BackupVars[0]), &ErrorEntry, AppLocalParameterPosition(), AppBackupPosition());
   if (Status != 0)
   {
      AppSystemLog(ERR_7, MODULE_NAME"CrVB: %d,%d", Status, ErrorEntry);
      return ERR_7;
   }

   return OS_SUCCESS;
}

#define CREATE_VARDB_VARS

//-----------------------------------------------------------------------
// CREATE IO VARIABLES     CREATE IO VARIABLES     CREATE IO VARIABLES
//-----------------------------------------------------------------------

extern STATUS Lubrication_Main_Bearing_MT_Type1InitIOAliases();
extern struct os_db_alias* Lubrication_Main_Bearing_MT_Type1IOVars;
extern void (*Lubrication_Main_Bearing_MT_Type1SetLockValues)(void);
extern size_t Lubrication_Main_Bearing_MT_Type1IOVarsSize;

static STATUS CreateIOVars(void)
{
   STATUS Status;
   size_t ErrorEntry;

   varid_t VarId;
   BOOL variablesExist = false;
   U8 counter = 50;
   Status = Lubrication_Main_Bearing_MT_Type1InitIOAliases();
   STATUS_LINE_VAR_RETURN_VALUE(Status)
   while (!variablesExist && counter-- > 0)
   {
      variablesExist = true;
      U32 i = 0;
      for (i = 0; i < Lubrication_Main_Bearing_MT_Type1IOVarsSize; ++i)
      {
         if (OS_VarDB_GetVariableID(Lubrication_Main_Bearing_MT_Type1IOVars[i].Name, &VarId) != OS_SUCCESS)
         {
            variablesExist = false;
            break;
         }
      }

      if (!variablesExist)
      {
         OS_Sleep(100);
      }
   }

   Status = OS_VarDB_CreateAliases(Lubrication_Main_Bearing_MT_Type1IOVars, Lubrication_Main_Bearing_MT_Type1IOVarsSize, &ErrorEntry);
   if (Status)
   {
      AppDebugLog(5000, "Var Name = %s", Lubrication_Main_Bearing_MT_Type1IOVars[ErrorEntry].Alias);
   }
   STATUS_LINE_VAR_RETURN_CONST(Status, ErrorEntry);
   return OS_SUCCESS;
}

#define CREATE_IO_VARS

//-----------------------------------------------------------------------
// ALIASES                       ALIASES                       ALIASES
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// INPUT                          INPUT                          INPUT
//-----------------------------------------------------------------------

// Create local variable
#define MODUL_INPUTS
static U8 V_Grid_ErrorActive = 0;
static U8 V_Inverter_StatusLVRT = 0;
static U8 DI_LubricationMB_SystemLevelWarning = 0;
static U8 DI_LubricationMB_PumpFault = 0;
static U8 V_ActiveControlProgram1 = 0;
static S32 V_Lub_Equip1_Mode = 0;
static U32 V_ControllerRpm = 0;

//-----------------------------------------------------------------------
static struct ModulInOut ModulInputs[] =
{
   {"V_Grid_ErrorActive",                       &V_Grid_ErrorActive,                       sizeof(V_Grid_ErrorActive),                       },
   {"V_Inverter_StatusLVRT",                    &V_Inverter_StatusLVRT,                    sizeof(V_Inverter_StatusLVRT),                    },
   {"DI_LubricationMB_SystemLevelWarning",      &DI_LubricationMB_SystemLevelWarning,      sizeof(DI_LubricationMB_SystemLevelWarning),      },
   {"DI_LubricationMB_PumpFault",               &DI_LubricationMB_PumpFault,               sizeof(DI_LubricationMB_PumpFault),               },
   {"V_ActiveControlProgram1",                  &V_ActiveControlProgram1,                  sizeof(V_ActiveControlProgram1),                  },
   {"V_Lub_Equip1_Mode",                        &V_Lub_Equip1_Mode,                        sizeof(V_Lub_Equip1_Mode),                        },
   {"V_ControllerRpm",                          &V_ControllerRpm,                          sizeof(V_ControllerRpm),                          },
};

//-----------------------------------------------------------------------
// Check variable type
static STATUS VarsReadReturnStatus;
static type_t ReadVarType = TYPE_NONE;
static void VarsReadTypeCheck(void)
{
   (void)VarsReadReturnStatus;
   (void)ReadVarType;
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[0].Name,                      ModulInputs[0].Id)
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[1].Name,                      ModulInputs[1].Id)
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[2].Name,                      ModulInputs[2].Id)
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[3].Name,                      ModulInputs[3].Id)
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[4].Name,                      ModulInputs[4].Id)
   VERIFY_INPUT_REF_ID(S32,       ModulInputs[5].Name,                      ModulInputs[5].Id)
   VERIFY_INPUT_REF_ID(U32,       ModulInputs[6].Name,                      ModulInputs[6].Id)
}

#undef MODUL_INPUTS
#define MODUL_INPUTS_SIZE (sizeof(ModulInputs)/sizeof(ModulInputs[0]))

//------------------------------------------------------------------------------------------
// READ/WRITE VARDB ARRAY      READ/WRITE VARDB ARRAY      READ/WRATE VARDB ARRAY
//------------------------------------------------------------------------------------------


//-----------------------------------------------------------------------
// PARAMETER                    PARAMETER                    PARAMETER
//-----------------------------------------------------------------------

// Create local variable
#define MODUL_PARAMETERS
static U8 P_LubricationMB_ServiceCtrl = 0;
static U32 P_LubricationMB_PumpOffTime = 0;
static U16 P_LubricationMB_MinRotorRPM = 0;
static U32 P_LubricationMB_LevelLowOnTime = 0;
static U8 P_LubricationMB_InternalMode = 0;
static U32 P_LubricationMB_FeedbackTime = 0;
static U8 P_LubricationMB_FeedbackType = 0;
static U8 P_LubricationMB_Stroke_ON = 0;



//-----------------------------------------------------------------------
static struct ModulInOut ModulParameters0[] =
{
   {"P_LubricationMB_ServiceCtrl",              &P_LubricationMB_ServiceCtrl,              sizeof(P_LubricationMB_ServiceCtrl),              },
   {"P_LubricationMB_PumpOffTime",              &P_LubricationMB_PumpOffTime,              sizeof(P_LubricationMB_PumpOffTime),              },
   {"P_LubricationMB_MinRotorRPM",              &P_LubricationMB_MinRotorRPM,              sizeof(P_LubricationMB_MinRotorRPM),              },
   {"P_LubricationMB_LevelLowOnTime",           &P_LubricationMB_LevelLowOnTime,           sizeof(P_LubricationMB_LevelLowOnTime),           },
   {"P_LubricationMB_InternalMode",             &P_LubricationMB_InternalMode,             sizeof(P_LubricationMB_InternalMode),             },
   {"P_LubricationMB_FeedbackTime",             &P_LubricationMB_FeedbackTime,             sizeof(P_LubricationMB_FeedbackTime),             },
   {"P_LubricationMB_FeedbackType",             &P_LubricationMB_FeedbackType,             sizeof(P_LubricationMB_FeedbackType),             },
   {"P_LubricationMB_Stroke_ON",                &P_LubricationMB_Stroke_ON,                sizeof(P_LubricationMB_Stroke_ON),                },

};
static struct ModulInOut* ModulParameters[] =
{
   ModulParameters0,
};

//-----------------------------------------------------------------------
// Check variable type
static STATUS ParaVarsReadReturnStatus;
static type_t ParaReadVarType = TYPE_NONE;
static void ParaVarsReadTypeCheck(void)
{
   (void)ParaVarsReadReturnStatus;
   (void)ParaReadVarType;
}

#undef MODUL_PARAMETERS

#define PARAMETERS_GROUPS_SIZE        1
#define GENERAL_GROUP                 0
#define MODUL_PARAMETERS_TOTAL_SIZE   8
static SUBSCRIPTION ParaSubscription[MODUL_PARAMETERS_TOTAL_SIZE];
static U8 ReadParameters[PARAMETERS_GROUPS_SIZE];
static U8 ParametersChanged[PARAMETERS_GROUPS_SIZE];
static UNSIGNED GroupsIndexes[PARAMETERS_GROUPS_SIZE];
static int ParaGroupsSizes[PARAMETERS_GROUPS_SIZE] = { 8 };
static STATUS VarDbUpdateParameter(varid_t VariableId, void* Message, U16 Length, UNSIGNED paraGroupIndex, UNSIGNED Ref2)
{
   ReadParameters[paraGroupIndex] = 1;
   ParametersChanged[paraGroupIndex] = 1;
   return OS_SUCCESS;
}
static STATUS ReadParametersFunc(int paraGroupIndex)
{
   STATUS LocalStatus;
   // Check inputdata
   if (sizeof(ModulParameters[paraGroupIndex]) == 0)
   {
      AppSystemLog(ERR_4, MODULE_NAME"Group %d ModuleParameters = 0", paraGroupIndex);
      return ERR_4;
   }
   // Read inputdata
   LocalStatus = OS_ReadVariables(ModulParameters[paraGroupIndex], ParaGroupsSizes[paraGroupIndex]);
   if (LocalStatus != 0)
   {
      AppSystemLog(11, "LocalStatus: %d", LocalStatus);
      AppSystemLog(ERR_4, MODULE_NAME"ReadParErr: group=%d element=%d elementpointer=0x%x", paraGroupIndex, LocalStatus, &ModulParameters[LocalStatus]);
      return ERR_4;
   }
   return OS_SUCCESS;
}


//-----------------------------------------------------------------------
// READ VARS FROM VARDB    READ VARS FROM VARDB    READ VARS FROM VARDB
//-----------------------------------------------------------------------

static STATUS InputReferenceRoutine(U8 ModuleState)
{
   STATUS LocalStatus = 0;

   // Read input references
   if (ModuleState >= APP_INIT3)
   {
      // Check inputdata
      if (sizeof(ModulInputs) == 0)
      {
         AppSystemLog(ERR_4, MODULE_NAME"ModuleInputs = 0");
         return ERR_4;
      }
      // Read inputdata
      LocalStatus = OS_ReadVariables(ModulInputs, MODUL_INPUTS_SIZE);
      if (LocalStatus != 0)
      {
         AppSystemLog(ERR_4, MODULE_NAME"ReadVErr: element=%d elementpointer=0x%x", LocalStatus, &ModulInputs[LocalStatus]);
         return ERR_4;
      }
   }
   // Read input parameters
   if (ModuleState == APP_INIT3)
   {
      static size_t ParaCounter = 0;
      int groupIndex;
      for (groupIndex = 0; groupIndex < PARAMETERS_GROUPS_SIZE; groupIndex++)
      {
         ParametersChanged[groupIndex] = 1;
         ReadParameters[groupIndex] = 1;
         GroupsIndexes[groupIndex] = groupIndex;

         // Check inputdata
         if (sizeof(ModulParameters[groupIndex]) == 0)
         {
            AppSystemLog(ERR_4, MODULE_NAME"Group = %d ModuleParameters = 0", groupIndex);
            return ERR_4;
         }
         // Read inputdata
         LocalStatus = OS_ReadVariables(ModulParameters[groupIndex], ParaGroupsSizes[groupIndex]);
         if (LocalStatus != 0)
         {
            AppSystemLog(ERR_4, MODULE_NAME"ReadVParaErr: group=%d element=%d elementpointer=0x%x", groupIndex, LocalStatus, &ModulParameters[groupIndex][LocalStatus]);
            return ERR_4;
         }
         int paraIndex;
         for (paraIndex = 0; paraIndex < ParaGroupsSizes[groupIndex]; paraIndex++)
         {
            LocalStatus = OS_SubHandl_SubscribeFunctionWithRef(&ParaSubscription[ParaCounter], 1, &ModulParameters[groupIndex][paraIndex].Id, &GroupsIndexes[groupIndex], &GroupsIndexes[groupIndex], VarDbUpdateParameter);
            ParaCounter++;
            if (LocalStatus != 0)
            {
               AppSystemLog(ERR_4, MODULE_NAME"Subscribe Parameter: group=%d element=%d elementpointer=0x%x", groupIndex, LocalStatus, &ModulParameters[LocalStatus]);
               return ERR_4;
            }
         }
      }
   }
   if (ModuleState == APP_RUN)
   {
      int groupIndex;
      for (groupIndex = 0; groupIndex < PARAMETERS_GROUPS_SIZE; groupIndex++)
      {
         if (ReadParameters[groupIndex])
         {
            LocalStatus = ReadParametersFunc(groupIndex);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
            ReadParameters[groupIndex] = 0;
         }
      }
   }

   return 0;
}

#define READ_VARS

//-----------------------------------------------------------------------
// OUTPUT                         OUTPUT                         OUTPUT
//-----------------------------------------------------------------------

// Create local variable
#define MODUL_OUTPUTS
static U8 DO_LubricationMB_Pump = 0;
static U64 B_MBOilTankEmptyErrorTimer = 0;
static U64 B_MBLubricationTimer = 0;
static S32 V_Lub_Equip1_State = 0;
static S32 V_Lub_Equip1_Status = 0;
static char V_LubricationMB_OilTankEmptyTimeTxt[31];
static char V_LubricationMB_TimeIndicationTxt[31];
static char V_Lub_Equip1_StateTxt[31];
static char V_Lub_Equip1_StatusTxt[31];


//-----------------------------------------------------------------------
static struct ModulInOut ModulOutputs[] =
{
   {"DO_LubricationMB_Pump",                    &DO_LubricationMB_Pump,                    sizeof(DO_LubricationMB_Pump),                    },
   {"B_MBOilTankEmptyErrorTimer",               &B_MBOilTankEmptyErrorTimer,               sizeof(B_MBOilTankEmptyErrorTimer),               },
   {"B_MBLubricationTimer",                     &B_MBLubricationTimer,                     sizeof(B_MBLubricationTimer),                     },
   {"V_LubricationMB_OilTankEmptyTimeTxt",      &V_LubricationMB_OilTankEmptyTimeTxt,      sizeof(V_LubricationMB_OilTankEmptyTimeTxt),      },
   {"V_LubricationMB_TimeIndicationTxt",        &V_LubricationMB_TimeIndicationTxt,        sizeof(V_LubricationMB_TimeIndicationTxt),        },
   {"V_Lub_Equip1_State",                       &V_Lub_Equip1_State,                       sizeof(V_Lub_Equip1_State),                       },
   {"V_Lub_Equip1_StateTxt",                    &V_Lub_Equip1_StateTxt,                    sizeof(V_Lub_Equip1_StateTxt),                    },
   {"V_Lub_Equip1_Status",                      &V_Lub_Equip1_Status,                      sizeof(V_Lub_Equip1_Status),                      },
   {"V_Lub_Equip1_StatusTxt",                   &V_Lub_Equip1_StatusTxt,                   sizeof(V_Lub_Equip1_StatusTxt),                   },
};

//-----------------------------------------------------------------------
// Check variable type
static STATUS VarsWriteReturnStatus;
static type_t WriteVarType = TYPE_NONE;
static void VarsWriteTypeCheck(void)
{
   (void)VarsWriteReturnStatus;
   (void)WriteVarType;
   VERIFY_OUTPUT_REF_ID(U8,        ModulOutputs[0].Name,                     ModulOutputs[0].Id,                       0)
   VERIFY_OUTPUT_REF_ID(U64,       ModulOutputs[1].Name,                     ModulOutputs[1].Id,                       0)
   VERIFY_OUTPUT_REF_ID(U64,       ModulOutputs[2].Name,                     ModulOutputs[2].Id,                       0)
   VERIFY_OUTPUT_STRING_REF_ID(STRING,     ModulOutputs[3].Name,                      ModulOutputs[3].Id,               0)
   VERIFY_OUTPUT_STRING_REF_ID(STRING,     ModulOutputs[4].Name,                      ModulOutputs[4].Id, 0)
   VERIFY_OUTPUT_REF_ID(S32,       ModulOutputs[5].Name,                     ModulOutputs[5].Id,                       0)
   VERIFY_OUTPUT_STRING_REF_ID(STRING,     ModulOutputs[6].Name,                      ModulOutputs[6].Id,                           0)
   VERIFY_OUTPUT_REF_ID(S32,       ModulOutputs[7].Name,                     ModulOutputs[7].Id,                       0)
   VERIFY_OUTPUT_STRING_REF_ID(STRING,     ModulOutputs[8].Name,                      ModulOutputs[8].Id,                           0)
}

#undef MODUL_OUTPUTS
#define MODUL_OUTPUTS_SIZE (sizeof(ModulOutputs)/sizeof(ModulOutputs[0]))

//-----------------------------------------------------------------------
// WRITE VARS TO VARDB     WRITE VARS TO VARDB     WRITE VARS TO VARDB
//-----------------------------------------------------------------------

static STATUS InitOutputVars(void)
{
   STATUS LocalStatus;
   // Read outputdata
   LocalStatus = OS_ReadVariables(ModulOutputs, MODUL_OUTPUTS_SIZE);
   if (LocalStatus != 0)
   {
      AppSystemLog(ERR_4, MODULE_NAME"InitErr: element=%d elementpointer=0x%x", LocalStatus, &ModulOutputs[LocalStatus]);
      return ERR_4;
   }
   return OS_SUCCESS;
}
static STATUS OutputReferenceRoutine(U8 ModuleState)
{
   STATUS LocalStatus = 0;
   // Write Outputdata
   LocalStatus = OS_WriteVariablesConditional(ModulOutputs, MODUL_OUTPUTS_SIZE);
   if (LocalStatus != 0)
   {
      AppSystemLog(ERR_5, MODULE_NAME"WriteVErr: element=%d elementpointer=0x%x", LocalStatus, &ModulOutputs[LocalStatus]);
      return ERR_5;
   }
   return 0;
}

#define WRITE_VARS

//-----------------------------------------------------------------------
// VERIFY VARIABLES CREATION                 VERIFY VARIABLES CREATION
//-----------------------------------------------------------------------

static STATUS LocalIoCheck(void)
{
   // Check if input variables exist.
   STATUS LocalStatus;

   LocalStatus = OS_DoesVariablesExist(ModulInputs, MODUL_INPUTS_SIZE);
   if (LocalStatus != 0)
   {
      AppSystemLog(ERR_1, MODULE_NAME"InputErr: %d", LocalStatus);
      AppSystemLog(ERR_1, "Name: %s", ModulInputs[LocalStatus-1].Name);
      return ERR_1;
   }
   (void)VarsReadTypeCheck();

   int groupIndex;
   for (groupIndex = 0; groupIndex < PARAMETERS_GROUPS_SIZE; groupIndex++)
   {
      LocalStatus = OS_DoesVariablesExist(ModulParameters[groupIndex], ParaGroupsSizes[groupIndex]);
      if (LocalStatus != 0)
      {
         AppSystemLog(ERR_3, MODULE_NAME"ParameterErr: %d Group:%d", LocalStatus, groupIndex);
         AppSystemLog(ERR_3, "Name: %s", ModulParameters[groupIndex][LocalStatus-1].Name);
         return ERR_3;
      }
   }
   (void)ParaVarsReadTypeCheck();

   LocalStatus = OS_DoesVariablesExist(ModulOutputs, MODUL_OUTPUTS_SIZE);
   if (LocalStatus != 0)
   {
      AppSystemLog(ERR_2, MODULE_NAME"OutputErr: %d", LocalStatus);
      AppSystemLog(ERR_2, "Name: %s", ModulOutputs[LocalStatus-1].Name);
      return ERR_2;
   }
   (void)VarsWriteTypeCheck();

   return OS_SUCCESS;
}

#define VERIFY_VARIABLES

//-----------------------------------------------------------------------
// ALLOCATE MEMORY FOR SUMMATIONS        ALLOCATE MEMORY FOR SUMMATIONS
//-----------------------------------------------------------------------

static SSUM SSummationS_GeneratorLubricationPump;

//-----------------------------------------------------------------------
// SUMMATIONS                  SUMMATIONS                  SUMMATIONS
//-----------------------------------------------------------------------

static struct os_db_summation ServiceSummations[] =
{
   VAR_ELEMENT_SERVICE_SUM( "S_LubricationMB_Pump",                     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_99,                 "DO_LubricationMB_Pump",                    SSummationS_GeneratorLubricationPump   ),
};

static STATUS CreateSummations(void)
{
  STATUS LocalStatus = 0;
  size_t ErrorEntry = 0;

  LocalStatus = OS_SUM_CreateSummations(ServiceSummations, sizeof(ServiceSummations)/sizeof(ServiceSummations[0]), &ErrorEntry, AppBackupPosition());
  if (OS_SUCCESS != LocalStatus)
  {
    return LocalStatus;
  }

  return LocalStatus;
}

#define CREATE_SUMMATIONS

//-----------------------------------------------------------------------
// DEFINE MENUS               DEFINE MENUS               DEFINE MENUS
//-----------------------------------------------------------------------



// Menu line and link to local menu
//-----------------------------------------------------------------------
static struct line_struct M_Lubrication_Main_Bearing_MT_Type1LinkToLocalMenu[] =
{
   MENU_ELEMENT_LINE_LINK("Lubrication Main Bearing",          PASSWORD_LEVEL_END_CUSTOMER,        "M_Lubrication_Main_Bearing_MT_Type1", "G_Lubrication_Main_Bearing_MT_Type1"),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_Lubrication_Main_Bearing_MT_Type1Menu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_Lubrication_Main_Bearing_MT_Type1",PASSWORD_LEVEL_END_CUSTOMER),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_Lubrication_Main_Bearing_MT_Type1MenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("LUBRICATION MAIN BEARING",          PASSWORD_LEVEL_END_CUSTOMER,        "M_"APP_ID"AppMain",                "G_"APP_ID"App"),
   MENU_ELEMENT_LINE_VARRO("Main Bearing Lubrication State",   PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_Lub_Equip1_StateTxt",                      LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_LINK("Status",                            PASSWORD_LEVEL_END_CUSTOMER,        "M_Status212",                      "G_Lubrication_Main_Bearing_MT_Type1"),
   MENU_ELEMENT_LINE_LINK("Parameter",                         PASSWORD_LEVEL_END_CUSTOMER,        "M_Parameter320",                   "G_Lubrication_Main_Bearing_MT_Type1"),
   MENU_ELEMENT_LINE_LINK("Service",                           PASSWORD_LEVEL_SERVICE,             "M_Service424",                     "G_Lubrication_Main_Bearing_MT_Type1"),
   MENU_ELEMENT_LINE_LINK("Debug",                             PASSWORD_LEVEL_MITA_PROGRAMMER,     "M_Debug4743",                      "G_Lubrication_Main_Bearing_MT_Type1"),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_Status212Menu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_Status212",                      PASSWORD_LEVEL_END_CUSTOMER),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_Status212MenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("STATUS",                            PASSWORD_LEVEL_END_CUSTOMER,        "M_Lubrication_Main_Bearing_MT_Type1", "G_Lubrication_Main_Bearing_MT_Type1"),
   MENU_ELEMENT_LINE_VARRO("Main Bearing Lub. Mode Request",   PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_Lub_Equip1_ModeTxt",                       LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Main Bearing Lub. Pump State",     PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_Lub_Equip1_StateTxt",                      LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Main Bearing Lub. Status",         PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_Lub_Equip1_StatusTxt",                     LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Main Bearing Lub. Timer",          PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_LubricationMB_TimeIndicationTxt",          LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Main Bearing Lub. Pump",           PASSWORD_LEVEL_END_CUSTOMER,        (char*)"DO_LubricationMB_Pump",                      LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Main Bearing Lub. Oil Level",      PASSWORD_LEVEL_END_CUSTOMER,        (char*)"DI_LubricationMB_SystemLevelWarning",        LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Main Bearing Lub. Pump Distributor", PASSWORD_LEVEL_END_CUSTOMER,        (char*)"DI_LubricationMB_PumpFault",                 LINE_FORMAT_NONE),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_Parameter320Menu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_Parameter320",                   PASSWORD_LEVEL_END_CUSTOMER),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_Parameter320MenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("PARAMETER",                         PASSWORD_LEVEL_END_CUSTOMER,        "M_Lubrication_Main_Bearing_MT_Type1", "G_Lubrication_Main_Bearing_MT_Type1"),
   MENU_ELEMENT_LINE_VARRW("Main Bearing Lub. Control Mode",   PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_LubricationMB_InternalMode",               LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Main Bearing Lub. Pump ON Stroke", PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_LubricationMB_Stroke_ON",                  LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Main Bearing Lub. Pump Off Time",  PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_LubricationMB_PumpOffTime",                LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Main Bearing Lub. Min Rotor RPM",  PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_LubricationMB_MinRotorRPM",                LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Main Bearing Lub. FB Type",        PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_LubricationMB_FeedbackType",               LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Main Bearing Lub. FB Time",        PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_LubricationMB_FeedbackTime",               LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Max Time with Oil Level Low",      PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_LubricationMB_LevelLowOnTime",             LINE_FORMAT_NONE),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_Service424Menu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_Service424",                     PASSWORD_LEVEL_SERVICE),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_Service424MenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("SERVICE",                           PASSWORD_LEVEL_SERVICE,             "M_Lubrication_Main_Bearing_MT_Type1", "G_Lubrication_Main_Bearing_MT_Type1"),
   MENU_ELEMENT_LINE_VARRW("Main Bearing Lub. Service Control", PASSWORD_LEVEL_SERVICE,             (char*)"P_LubricationMB_ServiceCtrl",                LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Main Bearing Lub. Oil Tank Empty Time", PASSWORD_LEVEL_SERVICE,             (char*)"V_LubricationMB_OilTankEmptyTimeTxt",        LINE_FORMAT_NONE),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_Debug4743Menu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_Debug4743",                      PASSWORD_LEVEL_MITA_PROGRAMMER),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_Debug4743MenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("DEBUG",                             PASSWORD_LEVEL_MITA_PROGRAMMER,     "M_Lubrication_Main_Bearing_MT_Type1", "G_Lubrication_Main_Bearing_MT_Type1"),
   MENU_ELEMENT_LINE_VARRO("Main Bearing Lub. Mode Request",   PASSWORD_LEVEL_MITA_PROGRAMMER,     (char*)"V_Lub_Equip1_Mode",                          LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Main Bearing Lub. State",          PASSWORD_LEVEL_MITA_PROGRAMMER,     (char*)"V_Lub_Equip1_State",                         LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Main Bearing Lub. Status",         PASSWORD_LEVEL_MITA_PROGRAMMER,     (char*)"V_Lub_Equip1_Status",                        LINE_FORMAT_NONE),
};
// Creating parameters for multiplexed categories
//-----------------------------------------------------------------------
static struct multiplexed_info_struct M_Lubrication_Main_Bearing_MT_Type1MultiplexedCategoriesParameters[] =
{
0};

//-----------------------------------------------------------------------
// CREATE MENUS               CREATE MENUS               CREATE MENUS
//-----------------------------------------------------------------------

// Memory reservation
//-----------------------------------------------------------------------
static struct menu_group_struct ObjGroup[1];

// Creating the menus
//-----------------------------------------------------------------------
STATUS Lubrication_Main_Bearing_MT_Type1MenuAppInit(U8 ModuleState, OS_MEMORY_POOL* pPool)
{
   STATUS Status;

   if (ModuleState == APP_INIT1)
   {
      /* Create application group */
      Status = OS_CreateMenuGroup(ObjGroup, M_Lubrication_Main_Bearing_MT_Type1LinkToLocalMenu[0].LinkGroup);
      STATUS_LINE_VAR_RETURN_VALUE(Status);
   }

   Status = CreateAndInitializeMenu(ModuleState,
                                    M_Lubrication_Main_Bearing_MT_Type1MenuLines[0].LinkGroup,
                                    M_Lubrication_Main_Bearing_MT_Type1MenuLines[0].LinkName,
                                    ELEMENT(M_Lubrication_Main_Bearing_MT_Type1LinkToLocalMenu),
                                    M_Lubrication_Main_Bearing_MT_Type1LinkToLocalMenu[0].LinkGroup,
                                    ELEMENT(M_Lubrication_Main_Bearing_MT_Type1Menu),
                                    M_Lubrication_Main_Bearing_MT_Type1LinkToLocalMenu[0].LinkName,
                                    ELEMENT(M_Lubrication_Main_Bearing_MT_Type1MenuLines),
                                    pPool,
                                    M_Lubrication_Main_Bearing_MT_Type1MultiplexedCategoriesParameters);
   STATUS_LINE_VAR_RETURN_VALUE(Status);

   Status = CreateAndInitializeMenu(ModuleState,
                                    M_Status212MenuLines[0].LinkGroup,
                                    M_Status212MenuLines[0].LinkName,
                                    NULL,
                                    0,
                                    M_Lubrication_Main_Bearing_MT_Type1MenuLines[2].LinkGroup,
                                    ELEMENT(M_Status212Menu),
                                    M_Lubrication_Main_Bearing_MT_Type1MenuLines[2].LinkName,
                                    ELEMENT(M_Status212MenuLines),
                                    pPool,
                                    M_Lubrication_Main_Bearing_MT_Type1MultiplexedCategoriesParameters);
   STATUS_LINE_VAR_RETURN_VALUE(Status);

   Status = CreateAndInitializeMenu(ModuleState,
                                    M_Parameter320MenuLines[0].LinkGroup,
                                    M_Parameter320MenuLines[0].LinkName,
                                    NULL,
                                    0,
                                    M_Lubrication_Main_Bearing_MT_Type1MenuLines[3].LinkGroup,
                                    ELEMENT(M_Parameter320Menu),
                                    M_Lubrication_Main_Bearing_MT_Type1MenuLines[3].LinkName,
                                    ELEMENT(M_Parameter320MenuLines),
                                    pPool,
                                    M_Lubrication_Main_Bearing_MT_Type1MultiplexedCategoriesParameters);
   STATUS_LINE_VAR_RETURN_VALUE(Status);

   Status = CreateAndInitializeMenu(ModuleState,
                                    M_Service424MenuLines[0].LinkGroup,
                                    M_Service424MenuLines[0].LinkName,
                                    NULL,
                                    0,
                                    M_Lubrication_Main_Bearing_MT_Type1MenuLines[4].LinkGroup,
                                    ELEMENT(M_Service424Menu),
                                    M_Lubrication_Main_Bearing_MT_Type1MenuLines[4].LinkName,
                                    ELEMENT(M_Service424MenuLines),
                                    pPool,
                                    M_Lubrication_Main_Bearing_MT_Type1MultiplexedCategoriesParameters);
   STATUS_LINE_VAR_RETURN_VALUE(Status);

   Status = CreateAndInitializeMenu(ModuleState,
                                    M_Debug4743MenuLines[0].LinkGroup,
                                    M_Debug4743MenuLines[0].LinkName,
                                    NULL,
                                    0,
                                    M_Lubrication_Main_Bearing_MT_Type1MenuLines[5].LinkGroup,
                                    ELEMENT(M_Debug4743Menu),
                                    M_Lubrication_Main_Bearing_MT_Type1MenuLines[5].LinkName,
                                    ELEMENT(M_Debug4743MenuLines),
                                    pPool,
                                    M_Lubrication_Main_Bearing_MT_Type1MultiplexedCategoriesParameters);
   STATUS_LINE_VAR_RETURN_VALUE(Status);

   return OS_SUCCESS;
}

#define CREATE_MENU

//-----------------------------------------------------------------------
//               BUTTONS FUNCTIONS FORWARD DECLARATIONS
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// BUTTONS                       BUTTONS                      BUTTONS
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
//             SET/RESET FUNCTIONS FORWARD DECLARATIONS
//-----------------------------------------------------------------------
static U8 StatusSetFunc1390(void);
static U8 StatusResetFunc1390(void);
static U8 StatusSetFunc1391(void);
static U8 StatusSetFunc3091(void);
//-----------------------------------------------------------------------
// STATUSCODES                 STATUSCODES                 STATUSCODES
//-----------------------------------------------------------------------

static struct sts_statuscode_structure StatusCodes[] =
{
   STS_CODE_ELEMENT("M.bear.lubrication",     20*SEC,    1390,      STATUSCODE_UPDATE_TYPE_POLLING,         PASSWORD_LEVEL_SERVICE,            STATUSCODE_TIMER_TYPE_CONSTANT,     STATUSCODE_TIMER_TYPE_CONSTANT,     STATUSCODE_RESET_TYPE_AUTOMATIC,    STATUSCODE_PRIORITY_LOW,       27,   0,    32,   NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         StatusSetFunc1390,       StatusResetFunc1390,     0,                   BRAKE_PROG_0,        BRAKE_PROG_MAX,      NULL,                PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,                   YAW_PROG_0,          YAW_PROG_240,        NULL,                PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,    0,    255,  NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            1,  PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      100,       20,        1000,      NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         SETDELAY_MIN,   SETDELAY_MAX,   NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         0,         RESETDELAY_MIN, RESETDELAY_MAX, NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         0,         REPEATTIMES_MIN,     REPEATTIMES_MAX,     NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         REPEATPERIOD_MIN,    REPEATPERIOD_MAX,    NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         REPEATCODE_MIN,      REPEATCODE_MAX,      NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         TIMEOUTPERIOD_MIN,   TIMEOUTPERIOD_MAX,   NULL,      PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         TIMEOUTCODE_MIN,     TIMEOUTCODE_MAX,     NULL,      PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         NULL),
   STS_CODE_ELEMENT("M.bear.lubricat.err.",   20*SEC,    1391,      STATUSCODE_UPDATE_TYPE_POLLING,         PASSWORD_LEVEL_SERVICE,            STATUSCODE_TIMER_TYPE_CONSTANT,     STATUSCODE_TIMER_TYPE_CONSTANT,     STATUSCODE_RESET_TYPE_DISPLAY,      STATUSCODE_PRIORITY_LOW,       27,   0,    32,   NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         StatusSetFunc1391,       NULL,                    0,                   BRAKE_PROG_0,        BRAKE_PROG_MAX,      NULL,                PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,                   YAW_PROG_0,          YAW_PROG_240,        NULL,                PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    1,    0,    255,  NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            1,  PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      100,       20,        1000,      NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         SETDELAY_MIN,   SETDELAY_MAX,   NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         0,         RESETDELAY_MIN, RESETDELAY_MAX, NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         REPEATTIMES_MIN,     REPEATTIMES_MAX,     NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         REPEATPERIOD_MIN,    REPEATPERIOD_MAX,    NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         REPEATCODE_MIN,      REPEATCODE_MAX,      NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         TIMEOUTPERIOD_MIN,   TIMEOUTPERIOD_MAX,   NULL,      PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         TIMEOUTCODE_MIN,     TIMEOUTCODE_MAX,     NULL,      PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         NULL),
   STS_CODE_ELEMENT("Main bear.lub.empty!",   20*SEC,    3091,      STATUSCODE_UPDATE_TYPE_POLLING,         PASSWORD_LEVEL_SERVICE,            STATUSCODE_TIMER_TYPE_CONSTANT,     STATUSCODE_TIMER_TYPE_CONSTANT,     STATUSCODE_RESET_TYPE_DISPLAY,      STATUSCODE_PRIORITY_LOW,       27,   0,    32,   NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         StatusSetFunc3091,       NULL,                    BRAKE_PROG_50,       BRAKE_PROG_0,        BRAKE_PROG_MAX,      NULL,                PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,                   YAW_PROG_0,          YAW_PROG_240,        NULL,                PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    1,    0,    255,  NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            1,  PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      100,       20,        1000,      NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         SETDELAY_MIN,   SETDELAY_MAX,   NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         0,         RESETDELAY_MIN, RESETDELAY_MAX, NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         0,         REPEATTIMES_MIN,     REPEATTIMES_MAX,     NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         REPEATPERIOD_MIN,    REPEATPERIOD_MAX,    NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         REPEATCODE_MIN,      REPEATCODE_MAX,      NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         TIMEOUTPERIOD_MIN,   TIMEOUTPERIOD_MAX,   NULL,      PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         TIMEOUTCODE_MIN,     TIMEOUTCODE_MAX,     NULL,      PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         NULL),
};

static STATUS_CODE_CONTROL_BLOCK StatusCodeControlBlock;

static STATUS LocalStatusCodeInit(void)
{
   STATUS LocalStatus;

   LocalStatus = OS_StatusCodeInit(STATUSCODE_INTERFACE_VERSION,
                                   &StatusCodeControlBlock,
                                   StatusCodes,
                                   sizeof(StatusCodes)/sizeof(StatusCodes[0]),
                                   AppLocalParameterPosition(),
                                   AppBackupPosition());
   STATUS_LINE_VAR_RETURN_CONST(LocalStatus, ERR_3);

   return OS_SUCCESS;
}

#define CREATE_STATUS_CODES

//-----------------------------------------------------------------------
// MODIFIABLE                  MODIFIABLE                   MODIFIABLE
//-----------------------------------------------------------------------

extern const char Lubrication_Main_Bearing_MT_Type1AppGroupName[];
extern const char Lubrication_Main_Bearing_MT_Type1AppMenuName[];

static void Init_Structures_From_Conf_File(void)
{
   M_Lubrication_Main_Bearing_MT_Type1MenuLines[0].LinkName = (char*)Lubrication_Main_Bearing_MT_Type1AppMenuName;
   M_Lubrication_Main_Bearing_MT_Type1MenuLines[0].LinkGroup = (char*)Lubrication_Main_Bearing_MT_Type1AppGroupName;
}

//-----------------------------------------------------------------------
// AUTOGENERATED END        AUTOGENERATED END        AUTOGENERATED END
//-----------------------------------------------------------------------
//}

#undef AUTOGENERATED_PART

//-----------------------------------------------------------------------
// USER DEFINITIONS         USER DEFINITIONS         USER DEFINITIONS
//-----------------------------------------------------------------------

//________________________________________________________________________
typedef struct _STimer_t
{
    time_t           P_Time;
    U8               OStatus;

    U8               FirstRun;
    U8               Start;
    U8               Suspend;
    time_t           TimeStart;
    time_t           TimeLast;
    time_t           Backup;
} STimer_t;
//________________________________________________________________________
// Function prototypes:
static void TimerReset (STimer_t *pTimer);
static time_t TimerLeft(STimer_t *pTimer);
static void TimerSet   (STimer_t *pTimer, time_t Delay);
static BOOL TimerCheck (STimer_t *pTimer);
static void TimerStop  (STimer_t *pTimer);
static void TimerStart (STimer_t *pTimer);

static void TimeToText(U64 Time, char *Text, U8 size);

#if 0       //  For future use
//________________________________________________________________________
static void TimerInit(STimer_t *pTimer, time_t Delay)
{
    pTimer->P_Time = Delay;
    pTimer->FirstRun  = 0;
}
#endif

//________________________________________________________________________
static void TimerReset(STimer_t *pTimer)        //  Reset all values to default and start timer automatically
{
    pTimer->TimeStart = OS_GetTimeInMs();
    pTimer->Backup    = 0;
    pTimer->OStatus   = 0;
    pTimer->Suspend   = 0;
    pTimer->FirstRun  = 1;
    pTimer->Start     = 1;
}
//________________________________________________________________________
static time_t TimerLeft(STimer_t *pTimer)
{
time_t  TimeDiff = 0;

    if( !TimerCheck(pTimer) )
    {
        TimeDiff = OS_GetTimeInMs();    //  time can change within two following commands, so it is needed to save time at some moment of time to temporary variable
        return (pTimer->P_Time > ( TimeDiff - pTimer->TimeStart )) ? (pTimer->P_Time - ( TimeDiff - pTimer->TimeStart )) : 0;
    }
    else
    {
        return 0;
    }
}
//________________________________________________________________________
static void TimerSet(STimer_t *pTimer, time_t Delay)        //  Timer can be restored from backup by this function
{
    if(Delay < pTimer->P_Time) { pTimer->TimeStart = OS_GetTimeInMs() -  pTimer->P_Time + Delay; }
    else                       { pTimer->TimeStart = OS_GetTimeInMs(); }
}
//________________________________________________________________________
static BOOL TimerCheck(STimer_t *pTimer)
{
    if( pTimer->Start && !pTimer->OStatus )
    {
        pTimer->TimeLast = OS_GetTimeInMs() - pTimer->TimeStart;
        if ( pTimer->TimeLast >= pTimer->P_Time )
        {
            pTimer->TimeStart = 0;
            pTimer->OStatus   = 1;
        }
    }
    return pTimer->OStatus;
}
//________________________________________________________________________
static void TimerStop(STimer_t *pTimer)         //  Backup current time and stop timer
{
    if( 0 == pTimer->Suspend ) { pTimer->Backup = TimerLeft(pTimer); }
    pTimer->Start = 0;
    pTimer->Suspend = 1;
}
//________________________________________________________________________
static void TimerStart(STimer_t *pTimer)        //  Start timer if it was stopped before or was not started/resetted
{
    if( pTimer->Suspend )                       //  timer was stopped previously, so reinitialize timer from backup and start it
    {
        TimerSet(pTimer, pTimer->Backup);
        pTimer->Suspend = 0;
        pTimer->Backup  = 0;
        pTimer->OStatus = 0;
        pTimer->Start   = 1;
    }
    else
    {
        pTimer->OStatus   = 0;
        pTimer->Suspend   = 0;
        pTimer->Backup    = 0;
        pTimer->FirstRun  = 1;
        pTimer->Start     = 1;
    }
}
//________________________________________________________________________
enum { LUB_MODE_PERIODIC_EXTRA_CTRL = 0 };
enum { LUB_MODE_PERIODIC_SIMPLE     = 1 };
enum { LUB_MODE_ALWAYS_ON           = 2 };

// Internal Lubrication State
enum { MB_LUB_SERVICE_OFF          = 1 };
enum { MB_LUB_SERVICE_ON           = 2 };
enum { MB_LUB_BLOCKED              = 4 };
enum { MB_LUB_SUSPENDED            = 5 };
enum { MB_LUB_AUTO_OFF             = 6 };
enum { MB_LUB_AUTO_ON              = 7 };

// Lubrication Status
enum { MB_LUB_STATUS_OK            = 0 };
enum { MB_LUB_STATUS_SAFETY        = 1 };
enum { MB_LUB_STATUS_HW_ERROR      = 2 };
enum { MB_LUB_STATUS_EMPTY         = 3 };
enum { MB_LUB_STATUS_GRID_ERROR    = 4 };
enum { MB_LUB_STATUS_LVRT          = 5 };
enum { MB_LUB_STATUS_BP_ACTIVE     = 6 };
enum { MB_LUB_STATUS_LM_BLOCK      = 7 };
enum { MB_LUB_STATUS_ROTOR_SPEED   = 8 };

enum { MB_LUB_PUMP_ON              = 1 };
enum { MB_LUB_PUMP_OFF             = 0 };

static const char MB_LUB_STATUS_OK_TEXT[]           = "OK";
static const char MB_LUB_STATUS_SAFETY_TEXT[]       = "Safety";
static const char MB_LUB_STATUS_HW_ERROR_TEXT[]     = "HW Error";
static const char MB_LUB_STATUS_EMPTY_TEXT[]        = "Tank Empty";
static const char MB_LUB_STATUS_GRID_ERROR_TEXT[]   = "Grid Error";
static const char MB_LUB_STATUS_LVRT_TEXT[]         = "LVRT";
static const char MB_LUB_STATUS_BP_ACTIVE_TEXT[]    = "BP Active";
static const char MB_LUB_STATUS_LM_BLOCK_TEXT[]     = "LM Block";
static const char MB_LUB_STATUS_ROTOR_SPEED_TEXT[]  = "(R) Speed";

enum { LUB_ERROR_FB_TYPE_LOW_LEVEL    = 0 };
enum { LUB_ERROR_FB_TYPE_HIGH_LEVEL   = 1 };
enum { LUB_ERROR_FB_TYPE_FREQUENCY    = 2 };

#ifndef NA_TEXT
static const char NA_TEXT[] = "N/A";
#endif
//______________________________________________________________________________________
static void WriteState(S32 State, char *Text, S32 Size)
{
static U8 OldState = 0xFF;

    if ( State != OldState )
    {
        switch(State)
        {
            case STATE_SERVICE_OFF :    { strncpy(Text, STATE_TEXT_SERVICE_OFF, Size); } break;
            case STATE_SERVICE_ON  :    { strncpy(Text, STATE_TEXT_SERVICE_ON,  Size); } break;
            case STATE_AUTO_ON     :    { strncpy(Text, STATE_TEXT_AUTO_ON,     Size); } break;
            case STATE_AUTO_OFF    :    { strncpy(Text, STATE_TEXT_AUTO_OFF,    Size); } break;
            case STATE_BLOCKED     :    { strncpy(Text, STATE_TEXT_BLOCKED,     Size); } break;
            case STATE_SUSPENDED   :    { strncpy(Text, STATE_TEXT_SUSPENDED,   Size); } break;
            default:                    { strncpy(Text, STATE_TEXT_UNDEFINED,   Size); } break;
        }
    }
    OldState = State;
}

//______________________________________________________________________________________
static void WriteStatus(U8 Status, char *Text, S32 Size)
{
static U8 OldStatus = 0xFF;

    if ( Status != OldStatus )
    {
        switch(Status)
        {
            case  MB_LUB_STATUS_OK:         { strncpy(Text, MB_LUB_STATUS_OK_TEXT,          Size); } break;
            case  MB_LUB_STATUS_SAFETY:     { strncpy(Text, MB_LUB_STATUS_SAFETY_TEXT,      Size); } break;
            case  MB_LUB_STATUS_HW_ERROR:   { strncpy(Text, MB_LUB_STATUS_HW_ERROR_TEXT,    Size); } break;
            case  MB_LUB_STATUS_EMPTY:      { strncpy(Text, MB_LUB_STATUS_EMPTY_TEXT,       Size); } break;
            case  MB_LUB_STATUS_GRID_ERROR: { strncpy(Text, MB_LUB_STATUS_GRID_ERROR_TEXT,  Size); } break;
            case  MB_LUB_STATUS_LVRT:       { strncpy(Text, MB_LUB_STATUS_LVRT_TEXT,        Size); } break;
            case  MB_LUB_STATUS_BP_ACTIVE:  { strncpy(Text, MB_LUB_STATUS_BP_ACTIVE_TEXT,   Size); } break;
            case  MB_LUB_STATUS_LM_BLOCK:   { strncpy(Text, MB_LUB_STATUS_LM_BLOCK_TEXT,    Size); } break;
            case  MB_LUB_STATUS_ROTOR_SPEED:{ strncpy(Text, MB_LUB_STATUS_ROTOR_SPEED_TEXT, Size); } break;
            default:                        { strncpy(Text, STATUS_TEXT_UNDEFINED,          Size); } break;
        }
    }
    OldStatus = Status;
}

//______________________________________________________________________________________
static STimer_t MBLubrication_OffTimer;
static STimer_t MBLubrication_LevelWarningTimer;
static STimer_t MBLubrication_FeedbackTimer;

//-----------------------------------------------------------------------
// SET/RESET FUNCTIONS    SET/RESET FUNCTIONS    SET/RESET FUNCTIONS
//-----------------------------------------------------------------------
static U8 StatusSetFunc1391(void)
{// MB lubrica. err
   static U8 FeedbackOldState = 0;
   static U8 FeedbackType_old = 0;
   static U8 FirstTime = 1;

    if( WPlineError() ) { return 0; }

    if(FeedbackType_old != P_LubricationMB_FeedbackType )
    {
        FeedbackType_old = P_LubricationMB_FeedbackType;
        if(LUB_ERROR_FB_TYPE_FREQUENCY == P_LubricationMB_FeedbackType) { TimerReset(&MBLubrication_FeedbackTimer); }
    }

    switch( P_LubricationMB_FeedbackType )
    {
        case LUB_ERROR_FB_TYPE_LOW_LEVEL:
        {
            if( 0 == DI_LubricationMB_PumpFault ) return 1;
        }
        break;
        case LUB_ERROR_FB_TYPE_HIGH_LEVEL:
        {
            if( 1 == DI_LubricationMB_PumpFault ) return 1;
        }
        break;
        case LUB_ERROR_FB_TYPE_FREQUENCY:
        {
            if( !DO_LubricationMB_Pump )
            {
				    TimerReset(&MBLubrication_FeedbackTimer);
                return 0;
            }
            if( FirstTime )
            {
                FirstTime = 0;
                TimerReset(&MBLubrication_FeedbackTimer);
            }
            if( FeedbackOldState != DI_LubricationMB_PumpFault )
            {
                FeedbackOldState = DI_LubricationMB_PumpFault;
                TimerReset(&MBLubrication_FeedbackTimer);
            }
            if( TimerCheck(&MBLubrication_FeedbackTimer) )
			   {
				    TimerReset(&MBLubrication_FeedbackTimer);
				    return 1;
			   }
        }
        break;
        default:
        {
            return 1;
        }
        break;
    }

    return 0;
}

//___________________________________________________________________________
static U8 StatusSetFunc1390(void)
{ // Pitch lubrica. Warn
    if( WPlineError() ) { return 0; }

    return !DI_LubricationMB_SystemLevelWarning;
}

static U8 StatusResetFunc1390(void)
{ return !StatusSetFunc1390(); }
//___________________________________________________________________________
static U8 StatusSetFunc3091(void)
{ // MB lubr. empty
static U8 FirstTime = 1;
static U8 FeedbackOldValue = 0;

    if( WPlineError() ) { return 0; }

    if(FirstTime)
    {
        FirstTime = 0;
        FeedbackOldValue = DI_LubricationMB_SystemLevelWarning;
        strncpy(V_LubricationMB_OilTankEmptyTimeTxt, NA_TEXT, sizeof(V_LubricationMB_OilTankEmptyTimeTxt));
        if( DI_LubricationMB_SystemLevelWarning )
        {
            B_MBOilTankEmptyErrorTimer = 0;
        }
        else
        {
            if( B_MBOilTankEmptyErrorTimer )
            {
                TimerSet(&MBLubrication_LevelWarningTimer, B_MBOilTankEmptyErrorTimer);
                TimerStart(&MBLubrication_LevelWarningTimer);
            }
            else
            {
                TimerReset(&MBLubrication_LevelWarningTimer);
            }
        }
    }

    if( FeedbackOldValue != DI_LubricationMB_SystemLevelWarning )
    {
        FeedbackOldValue = DI_LubricationMB_SystemLevelWarning;
        strncpy(V_LubricationMB_OilTankEmptyTimeTxt, NA_TEXT, sizeof(V_LubricationMB_OilTankEmptyTimeTxt));
        
        if( !DI_LubricationMB_SystemLevelWarning )
        {
            TimerReset(&MBLubrication_LevelWarningTimer);            
        }
    }

    if ( !DI_LubricationMB_SystemLevelWarning )
    {
        B_MBOilTankEmptyErrorTimer = TimerLeft(&MBLubrication_LevelWarningTimer);
        TimeToText(B_MBOilTankEmptyErrorTimer, V_LubricationMB_OilTankEmptyTimeTxt, sizeof(V_LubricationMB_OilTankEmptyTimeTxt));
        if (TimerCheck(&MBLubrication_LevelWarningTimer))
        {
            return 1;
        }
    }

    return 0;
}
//-----------------------------------------------------------------------
// DRIVER FUNCTION         DRIVER FUNCTION         DRIVER FUNCTION
//-----------------------------------------------------------------------
enum { STOP_CYCLE, START_CYCLE };
typedef struct
{
    U8 cycle;
    U8 old_data;
    U8 state;
}cycle_t;

static void StartCycle(cycle_t *a)
{
    a->state = START_CYCLE;
}
static void StopCycle(cycle_t *a)
{
    a->state = STOP_CYCLE;
}
static void ResetCycle(cycle_t *a, U8 data)
{
    a->old_data = data;
    a->cycle = 0;
    a->state = STOP_CYCLE;
}
static U8 WaitCycle(U8 data, U8 cycle_req, cycle_t *a)
{
    if( STOP_CYCLE == a->state )
    {
        return 0;
    }

    if(data != a->old_data)
    {
        a->cycle++;
        a->old_data = data;
    }

    return (cycle_req == (a->cycle/2));
}
//-----------------------------------------------------------------------
// INIT                   INIT                     INIT
//-----------------------------------------------------------------------
static cycle_t LubricationMB_StrokeCtrl;
//-----------------------------------------------------------------------
// CONTROL                CONTROL                 CONTROL
//-----------------------------------------------------------------------
static void AssignParameters (void)
{
    if ( ParametersChanged[GENERAL_GROUP] )
    {
        MBLubrication_OffTimer.P_Time           = P_LubricationMB_PumpOffTime;
        MBLubrication_LevelWarningTimer.P_Time  = P_LubricationMB_LevelLowOnTime;
        MBLubrication_FeedbackTimer.P_Time      = P_LubricationMB_FeedbackTime;

        ParametersChanged[GENERAL_GROUP] = 0;
    }
}
//___________________________________________________________________________
static U8 BlockMBLubrication(void)
{
    if      ( StatusCodeActive(10)   )          { V_Lub_Equip1_Status = MB_LUB_STATUS_SAFETY; }
    else if ( StatusCodeActive(1391) )          { V_Lub_Equip1_Status = MB_LUB_STATUS_HW_ERROR; }
    else if ( StatusCodeActive(3091) )          { V_Lub_Equip1_Status = MB_LUB_STATUS_EMPTY; }
    else if ( V_Grid_ErrorActive     )          { V_Lub_Equip1_Status = MB_LUB_STATUS_GRID_ERROR; }
    else if ( V_ActiveControlProgram1 >= 50 )   { V_Lub_Equip1_Status = MB_LUB_STATUS_BP_ACTIVE; }
    else                                        { V_Lub_Equip1_Status = MB_LUB_STATUS_OK; }

    return V_Lub_Equip1_Status;
}
//_________________________________________________________________________________
static void TimeToText(U64 Time, char *Text, U8 size)
{
    Time = Time / 1000; //  result in seconds
    if(Time > 3600)
    {
        sprintf( Text, "%u h, %d min",
                 (U32)(Time / 3600), (U32)((Time % 3600) / 60));
    }
    else if((Time < 3600) && (Time > 60))
    {
        snprintf( Text, size, "%u min, %u sec",
                  (U32)(Time / 60), (U32)(Time % 60));
    }
    else if(Time < 60)
    {
        snprintf(Text, size, "%u sec", (U32)Time);
    }
}
//________________________________________________________________________________________
void MBLubricationPeriodicExtraCtrl(U8 NewModeFlag)
{
static U8 FirstTime = 1;
static U8 State = MB_LUB_AUTO_OFF;

    if( FirstTime )
    {
        FirstTime = 0;
        State = MB_LUB_AUTO_OFF;
        if( (B_MBLubricationTimer > 0) && (B_MBLubricationTimer < P_LubricationMB_PumpOffTime) )
        {
            TimerSet(&MBLubrication_OffTimer, B_MBLubricationTimer);
            TimerStart(&MBLubrication_OffTimer);
        }
        else
        {
            TimerReset(&MBLubrication_OffTimer);
        }
    }

    if( NewModeFlag )
    {
        TimerReset(&MBLubrication_OffTimer);
        State = MB_LUB_AUTO_OFF;
    }

    if( BlockMBLubrication() )
    {
        DO_LubricationMB_Pump = MB_LUB_PUMP_OFF;
        strncpy(V_LubricationMB_TimeIndicationTxt, NA_TEXT, sizeof(V_LubricationMB_TimeIndicationTxt));
        V_Lub_Equip1_State = STATE_BLOCKED;
    }
    else
    {
        switch( State )
        {
            case MB_LUB_AUTO_OFF:
            {
                DO_LubricationMB_Pump = MB_LUB_PUMP_OFF;
                V_Lub_Equip1_State = STATE_AUTO_OFF;
                if( TimerCheck(&MBLubrication_OffTimer) )
                {
                    B_MBLubricationTimer = 0;
                    if( ( V_ControllerRpm >= P_LubricationMB_MinRotorRPM) &&
                        ( MANAGER_MODE_ENABLE == V_Lub_Equip1_Mode ) )
                    {
                        ResetCycle(&LubricationMB_StrokeCtrl, DI_LubricationMB_PumpFault);
						      StartCycle(&LubricationMB_StrokeCtrl);
                        State = MB_LUB_AUTO_ON;
                    }
                    else
                    {
                        StopCycle(&LubricationMB_StrokeCtrl);
                        State = MB_LUB_SUSPENDED;
                    }
                }
                else
                {
                    TimeToText(TimerLeft(&MBLubrication_OffTimer), V_LubricationMB_TimeIndicationTxt, sizeof(V_LubricationMB_TimeIndicationTxt));
                    B_MBLubricationTimer = TimerLeft(&MBLubrication_OffTimer);  //  Backup timer
                }
            }
            break;

            case MB_LUB_SUSPENDED:
            {
                DO_LubricationMB_Pump = MB_LUB_PUMP_OFF;
                V_Lub_Equip1_State = STATE_SUSPENDED;
                strncpy(V_LubricationMB_TimeIndicationTxt, NA_TEXT, sizeof(V_LubricationMB_TimeIndicationTxt));
                if( ( V_ControllerRpm >= P_LubricationMB_MinRotorRPM) &&
                    ( MANAGER_MODE_ENABLE == V_Lub_Equip1_Mode ) &&
                    ( 0 == V_Inverter_StatusLVRT ) )
                {
                    StartCycle(&LubricationMB_StrokeCtrl);
                    State = MB_LUB_AUTO_ON;
                }
                if ( V_Inverter_StatusLVRT )                               { V_Lub_Equip1_Status = MB_LUB_STATUS_LVRT; }
                else if (MANAGER_MODE_DISABLE == V_Lub_Equip1_Mode)        { V_Lub_Equip1_Status = MB_LUB_STATUS_LM_BLOCK; }
                else if( V_ControllerRpm < P_LubricationMB_MinRotorRPM ) { V_Lub_Equip1_Status = MB_LUB_STATUS_ROTOR_SPEED; }
                else                                                       { V_Lub_Equip1_Status = MB_LUB_STATUS_OK; }
            }
            break;

            case MB_LUB_AUTO_ON:
            {
                V_Lub_Equip1_State = STATE_AUTO_ON;
                if( WaitCycle(DI_LubricationMB_PumpFault, P_LubricationMB_Stroke_ON, &LubricationMB_StrokeCtrl) )
                {
                    TimerReset(&MBLubrication_OffTimer);
                    State = MB_LUB_AUTO_OFF;
                }
                else
                {
                    if(( MANAGER_MODE_DISABLE == V_Lub_Equip1_Mode) || V_Inverter_StatusLVRT)
                    {
                        DO_LubricationMB_Pump = MB_LUB_PUMP_OFF;
                        StopCycle(&LubricationMB_StrokeCtrl);
                        State = MB_LUB_SUSPENDED;
                    }
                    else
                    {
                        DO_LubricationMB_Pump = MB_LUB_PUMP_ON;
                    }
                }
            }
            break;

            default: { } break;
        }
    }
}
//________________________________________________________________________________________
void MBLubricationPeriodicSimple(U8 NewModeFlag)
{
static U8 FirstTime = 1;
static U8 State = MB_LUB_AUTO_OFF;

    if( FirstTime )
    {
        FirstTime = 0;
        State = MB_LUB_AUTO_OFF;
        if( (B_MBLubricationTimer > 0) && (B_MBLubricationTimer < P_LubricationMB_PumpOffTime) )
        {
            TimerSet(&MBLubrication_OffTimer, B_MBLubricationTimer);
            TimerStart(&MBLubrication_OffTimer);
        }
        else
        {
            TimerReset(&MBLubrication_OffTimer);
        }
    }

    if( NewModeFlag )
    {
        TimerReset(&MBLubrication_OffTimer);
        State = MB_LUB_AUTO_OFF;
    }

    if( BlockMBLubrication() )
    {
        DO_LubricationMB_Pump = MB_LUB_PUMP_OFF;
        strncpy(V_LubricationMB_TimeIndicationTxt, NA_TEXT, sizeof(V_LubricationMB_TimeIndicationTxt));
        if( MB_LUB_AUTO_ON == State ) { StopCycle(&LubricationMB_StrokeCtrl); }
        V_Lub_Equip1_State = STATE_BLOCKED;
    }
    else
    {
        switch( State )
        {
            case MB_LUB_AUTO_OFF:
            {
                DO_LubricationMB_Pump = MB_LUB_PUMP_OFF;
                V_Lub_Equip1_State = STATE_AUTO_OFF;
                if( TimerCheck(&MBLubrication_OffTimer) )
                {
                    B_MBLubricationTimer = 0;
                    if( MANAGER_MODE_ENABLE == V_Lub_Equip1_Mode )
                    {
                        ResetCycle(&LubricationMB_StrokeCtrl, DI_LubricationMB_PumpFault);
                        State = MB_LUB_AUTO_ON;
                    }
                    else
                    {
                        StopCycle(&LubricationMB_StrokeCtrl);
                        State = MB_LUB_SUSPENDED;
                    }
                }
                else
                {
                    TimeToText(TimerLeft(&MBLubrication_OffTimer), V_LubricationMB_TimeIndicationTxt, sizeof(V_LubricationMB_TimeIndicationTxt));
                    B_MBLubricationTimer = TimerLeft(&MBLubrication_OffTimer);  //  Backup timer
                }
            }
            break;

            case MB_LUB_SUSPENDED:
            {
                DO_LubricationMB_Pump = MB_LUB_PUMP_OFF;
                V_Lub_Equip1_State = STATE_SUSPENDED;
                strncpy(V_LubricationMB_TimeIndicationTxt, NA_TEXT, sizeof(V_LubricationMB_TimeIndicationTxt));
                if( (MANAGER_MODE_ENABLE == V_Lub_Equip1_Mode) && (0 == V_Inverter_StatusLVRT) )
                {
                    StartCycle(&LubricationMB_StrokeCtrl);
                    State = MB_LUB_AUTO_ON;
                }
                if( V_Inverter_StatusLVRT )                          { V_Lub_Equip1_Status = MB_LUB_STATUS_LVRT; }
                else if( MANAGER_MODE_DISABLE == V_Lub_Equip1_Mode ) { V_Lub_Equip1_Status = MB_LUB_STATUS_LM_BLOCK; }
                else                                                 { V_Lub_Equip1_Status = MB_LUB_STATUS_OK; }
            }
            break;

            case MB_LUB_AUTO_ON:
            {
                if( STATE_BLOCKED == V_Lub_Equip1_State ) { StartCycle(&LubricationMB_StrokeCtrl); }
                V_Lub_Equip1_State = STATE_AUTO_ON;
                if( WaitCycle(DI_LubricationMB_PumpFault, P_LubricationMB_Stroke_ON, &LubricationMB_StrokeCtrl) )
                {
                    TimerReset(&MBLubrication_OffTimer);
                    State = MB_LUB_AUTO_OFF;
                }
                else
                {
                    if(( MANAGER_MODE_DISABLE == V_Lub_Equip1_Mode) || V_Inverter_StatusLVRT)
                    {
                        DO_LubricationMB_Pump = MB_LUB_PUMP_OFF;
                        StopCycle(&LubricationMB_StrokeCtrl);
                        State = MB_LUB_SUSPENDED;
                    }
                    else
                    {
                        DO_LubricationMB_Pump = MB_LUB_PUMP_ON;
                    }
                }
            }
            break;
            default: { } break;
        }
    }
}
//________________________________________________________________________________________
void MBLubricationAlwaysOn(U8 NewModeFlag)
{
    static U8 FirstTime = 1;
    static U8 State = MB_LUB_SUSPENDED;     //  Do not turn pump ON initially before check for block or suspend conditions

    if( FirstTime || NewModeFlag)
    {
        FirstTime = 0;
        State = MB_LUB_SUSPENDED;
        strncpy(V_LubricationMB_TimeIndicationTxt, NA_TEXT, sizeof(V_LubricationMB_TimeIndicationTxt));
    }

    if( BlockMBLubrication() )
    {
        DO_LubricationMB_Pump = MB_LUB_PUMP_OFF;
        V_Lub_Equip1_State = STATE_BLOCKED;
    }
    else
    {
        switch( State )
        {
            case MB_LUB_AUTO_OFF:
            case MB_LUB_SUSPENDED:
            {
                DO_LubricationMB_Pump = MB_LUB_PUMP_OFF;
                V_Lub_Equip1_State = STATE_SUSPENDED;
                if( (MANAGER_MODE_ENABLE == V_Lub_Equip1_Mode) && (0 == V_Inverter_StatusLVRT) )
                {
                    State = MB_LUB_AUTO_ON;
                }
                if ( V_Inverter_StatusLVRT )                            { V_Lub_Equip1_Status = MB_LUB_STATUS_LVRT; }
                else if (MANAGER_MODE_DISABLE == V_Lub_Equip1_Mode)     { V_Lub_Equip1_Status = MB_LUB_STATUS_LM_BLOCK; }
                else                                                    { V_Lub_Equip1_Status = MB_LUB_STATUS_OK; }
            }
            break;

            case MB_LUB_AUTO_ON:
            {
                V_Lub_Equip1_State = STATE_AUTO_ON;
                if(( MANAGER_MODE_DISABLE == V_Lub_Equip1_Mode) || V_Inverter_StatusLVRT)
                {
                    DO_LubricationMB_Pump = MB_LUB_PUMP_OFF;
                    State = MB_LUB_SUSPENDED;
                }
                else
                {
                    DO_LubricationMB_Pump = MB_LUB_PUMP_ON;
                }
            }
            break;
            default: { } break;
        }
    }
}
//________________________________________________________________________________________

void MBLubricationAutoCtrl(U8 ServiceModeChanged)
{
static U8 InternalModeOldValue = 0;
static U8 FirstTime = 1;
       U8 NewModeFlag = 0;

    if(FirstTime)
    {
        FirstTime = 0;
        InternalModeOldValue = P_LubricationMB_InternalMode;
    }
    if(InternalModeOldValue != P_LubricationMB_InternalMode)
    {
        InternalModeOldValue = P_LubricationMB_InternalMode;
        NewModeFlag = 1;
    }
    if( ServiceModeChanged ) { NewModeFlag = 1; }

    switch( P_LubricationMB_InternalMode )
    {
        case LUB_MODE_PERIODIC_EXTRA_CTRL: { MBLubricationPeriodicExtraCtrl( NewModeFlag ); } break;
        case LUB_MODE_PERIODIC_SIMPLE:     { MBLubricationPeriodicSimple( NewModeFlag );    } break;
        case LUB_MODE_ALWAYS_ON:           { MBLubricationAlwaysOn( NewModeFlag );          } break;
        default:
        {
            DO_LubricationMB_Pump = MB_LUB_PUMP_OFF;
            strncpy(V_LubricationMB_TimeIndicationTxt, NA_TEXT, sizeof(V_LubricationMB_TimeIndicationTxt));
            V_Lub_Equip1_State = STATE_AUTO_OFF;
        }
        break;
    }
}

//________________________________________________________________________________________
static STATUS LocalCtrl(void)
{
    STATUS LocalStatus = 0;
    static U8 FirstTime = 1;
           U8 ServiceModeChanged = 0;
    static U8 P_LubricationMB_ServiceCtrl_old;

    if(FirstTime)
    {
        AssignParameters();
        FirstTime = 0;
        strncpy(V_LubricationMB_TimeIndicationTxt, NA_TEXT, sizeof(V_LubricationMB_TimeIndicationTxt));
        P_LubricationMB_ServiceCtrl_old = P_LubricationMB_ServiceCtrl;
    }

    if( P_LubricationMB_ServiceCtrl_old != P_LubricationMB_ServiceCtrl)
    {
        P_LubricationMB_ServiceCtrl_old = P_LubricationMB_ServiceCtrl;
        ServiceModeChanged = 1;
    }

    if( BlockMBLubrication() ) { V_Lub_Equip1_State = STATE_BLOCKED; }        //Retrieve Status

    switch( P_LubricationMB_ServiceCtrl )
    {
        case MODE_AUTO :
        {
            MBLubricationAutoCtrl(ServiceModeChanged);
        }
        break;

        case MODE_SERVICE_OFF :
        {
            DO_LubricationMB_Pump = MB_LUB_PUMP_OFF;
            V_Lub_Equip1_State = STATE_SERVICE_OFF;
            V_Lub_Equip1_Status = MB_LUB_STATUS_OK;
            strncpy(V_LubricationMB_TimeIndicationTxt, NA_TEXT, sizeof(V_LubricationMB_TimeIndicationTxt));
        }
        break;

        case MODE_SERVICE_ON :
        {
            DO_LubricationMB_Pump = MB_LUB_PUMP_ON;
            V_Lub_Equip1_State = STATE_SERVICE_ON;
            V_Lub_Equip1_Status = MB_LUB_STATUS_OK;
            strncpy(V_LubricationMB_TimeIndicationTxt, NA_TEXT, sizeof(V_LubricationMB_TimeIndicationTxt));
        }
        break;

        default:
        {
        }
        break;
    }

    AssignParameters();

    // update object State and Status and write to VDB if updated
    WriteState (V_Lub_Equip1_State , V_Lub_Equip1_StateTxt , sizeof(V_Lub_Equip1_StateTxt ));
    WriteStatus(V_Lub_Equip1_Status, V_Lub_Equip1_StatusTxt, sizeof(V_Lub_Equip1_StatusTxt));

    return LocalStatus;
}

//-----------------------------------------------------------------------
// MAIN CALL             MAIN CALL               MAIN CALL
//-----------------------------------------------------------------------

STATUS Lubrication_Main_Bearing_MT_Type1(U8 ModuleState, OS_MEMORY_POOL *MemPool, U32 *Arg3)
{
   STATUS LocalStatus = 0;

   // Version check
   if(ModuleState == APP_INIT1)
   {
      LocalStatus = OS_ValidateAPI(API_VERSION_MAJOR,
                                   API_VERSION_MINOR,
                                   OS_LinkTime,
                                   ReleaseTag,
                                   __MODULE__
                                   );
      if ( OS_SUCCESS != LocalStatus )
      {
         return LocalStatus;
      }
   }
#ifdef READ_VARS
   // Read inputdata
   LocalStatus = InputReferenceRoutine(ModuleState);
   STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif
#ifdef COMMON_VDB_READ
   LocalStatus = ReadVdbWindow(ModuleState);
   STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif
   switch(ModuleState)
   {
      case APP_RUN :
      {
         #ifdef FUNCTION_BLOCKS_PRE_LOCAL_CONTROL
            LocalStatus = FunctionBlocksPreLocalCtrl( Interval );
            STATUS_LINE_VAR_RETURN_VALUE( LocalStatus );
         #endif

         LocalStatus = LocalCtrl();
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
        
         #ifdef FUNCTION_BLOCKS_POST_LOCAL_CONTROL
            LocalStatus = FunctionBlocksPostLocalCtrl( Interval );
            STATUS_LINE_VAR_RETURN_VALUE( LocalStatus );
         #endif

#ifdef WRITE_VARS
         // Write Outputdata
         LocalStatus = OutputReferenceRoutine(ModuleState);
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif

#ifdef COMMON_VDB_WRITE
         LocalStatus = WriteVdbWindow(ModuleState);
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif
         break;
      }
      case APP_INIT1 :
      {
         Init_Structures_From_Conf_File();

#ifdef CREATE_VARDB_VARS
         LocalStatus = CreateVarDbVars();
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif

#ifdef CREATE_MENU
         LocalStatus = Lubrication_Main_Bearing_MT_Type1MenuAppInit(ModuleState, MemPool);
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)

#ifdef MULTIPLEXIBLE_MENU
         LocalStatus = MenuArraysAppInit(ModuleState, MemPool);
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif
#endif

#ifdef CREATE_VARDB_ARRAY_VARS
         LocalStatus = CreateVdbArrays(MemPool);
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif

#ifdef CREATE_IO_VARS
         LocalStatus = CreateIOVars();
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif
         break;
      }
      case APP_INIT2 :
      {
#ifdef CREATE_MENU
#ifdef MULTIPLEXIBLE_MENU
         LocalStatus = MenuArraysAppInit(ModuleState, MemPool);
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif
#endif

#ifdef CREATE_ALIASES
         size_t ErrorEntry = 0;
         LocalStatus = OS_VarDB_CreateAliases(AliasVars, sizeof(AliasVars)/sizeof(AliasVars[0]), &ErrorEntry);
         STATUS_LINE_VAR_RETURN_CONST(LocalStatus, ErrorEntry)
#endif

#ifdef VERIFY_ARRAY
        LocalStatus = VerifyArray(MemPool);
        STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif

#ifdef VERIFY_VARIABLES
         LocalStatus = LocalIoCheck();
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif

#ifdef CREATE_BUTTONS
         LocalStatus = CreateButtons();
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif
         break;
      }
      case APP_INIT3 :
      {
#ifdef CREATE_SUMMATIONS
         LocalStatus = CreateSummations();
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif

#ifdef WRITE_VARS
         LocalStatus = InitOutputVars();
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif

#ifdef CREATE_STATUS_CODES
         LocalStatus = LocalStatusCodeInit();
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif

#ifdef CREATE_IO_VARS
        Lubrication_Main_Bearing_MT_Type1SetLockValues();
#endif
         break;
      }
      case APP_INIT4 :
      {
#ifdef CREATE_MENU
         LocalStatus = Lubrication_Main_Bearing_MT_Type1MenuAppInit(ModuleState, MemPool);
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)

#ifdef MULTIPLEXIBLE_MENU
         LocalStatus = MenuArraysAppInit(ModuleState, MemPool);
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif
#endif
         break;
      }
      case APP_INIT5 :
      {
#ifdef VALIDATE_HASH
         LocalStatus = ValidateHash(Lubrication_Main_Bearing_MT_Type1_copyright, MODULE_NAME, Lubrication_Main_Bearing_MT_Type1_initialValues);
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif

         #ifdef INIT_FUNCTION_BLOCKS
            LocalStatus = FunctionBlocksInit( Interval );
            STATUS_LINE_VAR_RETURN_VALUE( LocalStatus );
         #endif

         break;
      }
      default :
      {
         break;
      }
   }
   return OS_SUCCESS;
}
//-----------------------------------------------------------------------
