//*****************************PEPTOOL Header Start******************************
//                                                                               
//                         Copyright © 2015 Mita-Teknik.                         
//This software may only be used with WP4x00 Controllers delivered by Mita-Teknik
//                                                                               
//*******************************************************************************
//                                                                               
// $PEPTOOL version:9.0$                                                         
// $PEPTOOL file version:106$                                                    
//                                                                               
//*******************************************************************************
//                                                                               
// $Date: 2014/06/06 05:09:31 $                                                  
// $Author: MITA\ihn $                                                           
// $RCSfile: LubricationYaw_MT_Type1.c,v $                                       
// $Revision: 1.13 $                                                             
//                                                                               
//******************************PEPTOOL Header End*******************************

//***********************************************************************

// OS header files
#include <os_main.h>
// AppLib header files
#include <lib_main.h>
// App header files
#include <turbdef.h>
#include <VarMacros.h>

// Object header file
#include <LubricationYaw_MT_Type1.h>

#define AUTOGENERATED_PART
//{
//-----------------------------------------------------------------------
// AUTOGENERATED START     AUTOGENERATED START     AUTOGENERATED START
//-----------------------------------------------------------------------

#define VALIDATE_HASH
char LubricationYaw_MT_Type1_copyright[] =
{
   67, 111, 112, 121, 114, 105, 103, 104, 116, 32, 63, 32, 50, 48, 49, 53,
   32, 77, 105, 116, 97, 45, 84, 101, 107, 110, 105, 107, 46, 13, 10, 84,
   104, 105, 115, 32, 115, 111, 102, 116, 119, 97, 114, 101, 32, 109, 97, 121,
   32, 111, 110, 108, 121, 32, 98, 101, 32, 117, 115, 101, 100, 32, 119, 105,
   116, 104, 32, 87, 80, 52, 120, 48, 48, 32, 67, 111, 110, 116, 114, 111,
   108, 108, 101, 114, 115, 32, 100, 101, 108, 105, 118, 101, 114, 101, 100, 32,
   98, 121, 32, 77, 105, 116, 97, 45, 84, 101, 107, 110, 105, 107, 0
};

#define MODULE_NAME "Lubrication Yaw MT Type 1A"

//-----------------------------------------------------------------------
// ALLOCATE MEMORY FOR STRINGS IN VARDB
//-----------------------------------------------------------------------

static char A_V_LubricationYaw_OilTankEmptyTimeTxt[31]  = "Not Initialized";
static char A_V_LubricationYaw_TimeIndicationTxt[31]  = "12345678901234567890123456789";
static char A_V_Lub_Equip2_StateTxt[31]  = "N/A";
static char A_V_Lub_Equip2_ModeTxt[31]  = "Disable";
static char A_V_Lub_Equip2_StatusTxt[31]  = "N/A";
static char A_P_YawLubr_ManagerVars_String[31]  = "V_Lub_";

//-----------------------------------------------------------------------
// DEFINE LOCAL VARIABLES DEFINE LOCAL VARIABLES DEFINE LOCAL VARIABLES
//-----------------------------------------------------------------------

static struct os_db_local LocalVars[] =
{
   VAR_ELEMENT_LOCAL("V_LubricationYaw_OilTankEmptyTimeTxt",     TYPE_STRING + sizeof(A_V_LubricationYaw_OilTankEmptyTimeTxt) - 1,  PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   A_V_LubricationYaw_OilTankEmptyTimeTxt, 0,                0,                NULL,  NOLOG_ENABLE  ),
   VAR_ELEMENT_LOCAL("V_LubricationYaw_TimeIndicationTxt",       TYPE_STRING + sizeof(A_V_LubricationYaw_TimeIndicationTxt) - 1,  PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   A_V_LubricationYaw_TimeIndicationTxt, 0,                0,                NULL,  NOLOG_ENABLE  ),
   VAR_ELEMENT_LOCAL("V_FirstExceptionYawBearing",               TYPE_U8,      PASSWORD_LEVEL_ADMINISTRATOR,      PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   0,               U8_MIN,          U8_MAX,          NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_Lub_Equip2_State",                       TYPE_S32,     PASSWORD_LEVEL_ADMINISTRATOR,      PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   0,               S32_MIN,         S32_MAX,         NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_Lub_Equip2_StateTxt",                    TYPE_STRING + sizeof(A_V_Lub_Equip2_StateTxt) - 1,  PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   A_V_Lub_Equip2_StateTxt, 0,                0,                NULL,  NOLOG_ENABLE  ),
   VAR_ELEMENT_LOCAL("V_Lub_Equip2_Mode",                        TYPE_S32,     PASSWORD_LEVEL_ADMINISTRATOR,      PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   0,               0,               1,               NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_Lub_Equip2_ModeTxt",                     TYPE_STRING + sizeof(A_V_Lub_Equip2_ModeTxt) - 1,  PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   A_V_Lub_Equip2_ModeTxt, 0,                0,                NULL,  NOLOG_ENABLE  ),
   VAR_ELEMENT_LOCAL("V_Lub_Equip2_Status",                      TYPE_S32,     PASSWORD_LEVEL_ADMINISTRATOR,      PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   0,               S32_MIN,         S32_MAX,         NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_Lub_Equip2_StatusTxt",                   TYPE_STRING + sizeof(A_V_Lub_Equip2_StatusTxt) - 1,  PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   A_V_Lub_Equip2_StatusTxt, 0,                0,                NULL,  NOLOG_ENABLE  ),
};

//-----------------------------------------------------------------------
// DEFINE PARAMETERS        DEFINE PARAMETERS        DEFINE PARAMETERS
//-----------------------------------------------------------------------

static struct os_db_parameter ParameterVars[] =
{
   VAR_ELEMENT_PARAMETER("P_LubricationYaw_ServiceCtrl",             TYPE_U8,      PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_SERVICE,            SCALE_NONE,   0,       UNIT_NONE,          0,   0,               0,               2,               NULL  ),
   VAR_ELEMENT_PARAMETER("P_LubricationYaw_PumpOffTime",             TYPE_U32,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         SCALE_DIV,    3600000, UNIT_HOUR,          1,   7200000,         600000,          604800000,       NULL  ),
   VAR_ELEMENT_PARAMETER("P_LubricationYaw_PumpOffTimeUnwind",       TYPE_U32,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         SCALE_DIV,    1000,    UNIT_SECOND,        0,   300000,          10000,           600000,          NULL  ),
   VAR_ELEMENT_PARAMETER("P_LubricationYaw_EquipNo",                 TYPE_U8,      PASSWORD_LEVEL_ADMINISTRATOR,      PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   2,               0,               9,               NULL  ),
   VAR_ELEMENT_PARAMETER("P_LubricationYaw_LevelLowOnTime",          TYPE_U32,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         SCALE_DIV,    3600000, UNIT_HOUR,          0,   1209600000,      3600000,         2419200000,      NULL  ),
   VAR_ELEMENT_PARAMETER("P_LubricationYaw_InternalMode",            TYPE_U8,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         SCALE_NONE,   0,       UNIT_NONE,          0,   0,               0,               2,               NULL  ),
   VAR_ELEMENT_PARAMETER("P_LubricationYaw_FeedbackTime",            TYPE_U32,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         SCALE_DIV,    1000,    UNIT_SECOND,        1,   40000,           100,             300000,          NULL  ),
   VAR_ELEMENT_PARAMETER("P_LubricationYaw_FeedbackType",            TYPE_U8,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         SCALE_NONE,   0,       UNIT_NONE,          0,   2,               0,               2,               NULL  ),
   VAR_ELEMENT_PARAMETER("P_YawLubr_ManagerVars_String",             TYPE_STRING + sizeof(A_P_YawLubr_ManagerVars_String) - 1,  PASSWORD_LEVEL_ADMINISTRATOR,      PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   A_P_YawLubr_ManagerVars_String, 0,                0,                NULL  ),
   VAR_ELEMENT_PARAMETER("P_LubricationYaw_Stroke_ON",               TYPE_U8,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   2,               1,               10,              NULL  ),
   VAR_ELEMENT_PARAMETER("P_LubricationYawUnwinding_Stroke_ON",      TYPE_U8,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   1,               1,               10,              NULL  ),
};

//-----------------------------------------------------------------------
// DEFINE BACKUPS            DEFINE BACKUPS            DEFINE BACKUPS
//-----------------------------------------------------------------------

static struct os_db_backup BackupVars[] =
{
   VAR_ELEMENT_BACKUP_U64("B_YawOilTankEmptyErrorTimer",                       PASSWORD_LEVEL_ADMINISTRATOR,      PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    1000,    UNIT_NONE,          0,   0ULL,            U64_MIN,         U64_MAX,         NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_BACKUP_U64("B_YawLubricationTimer",                             PASSWORD_LEVEL_ADMINISTRATOR,      PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   0ULL,            U64_MIN,         U64_MAX,         NULL,  NOLOG_ENABLE),
};

//----------------------------------------------------------------------------------
// DEFINE VAR ARRAYS            DEFINE VAR ARRAYS            DEFINE VAR ARRAYS
//----------------------------------------------------------------------------------
char LubricationYaw_MT_Type1_initialValues[] =
{
   221, 177, 82, 201, 178, 130, 23, 7, 229, 92, 171, 135, 72, 204, 100, 115,
   142, 105, 250, 176, 179, 213, 178, 235, 55, 151, 223, 21, 121, 248, 82, 179,
   0
};

//-----------------------------------------------------------------------
// CREATE DATABASE VARS   CREATE DATABASE VARS   CREATE DATABASE VARS
//-----------------------------------------------------------------------

static STATUS CreateVarDbVars(void)
{
   STATUS Status;
   size_t ErrorEntry;

   Status = OS_VarDB_CreateLocals(LocalVars, sizeof(LocalVars)/sizeof(LocalVars[0]), &ErrorEntry, AppLocalParameterPosition());
   if (Status != 0)
   {
      AppSystemLog(ERR_7, MODULE_NAME"CrVL: %d,%d", Status, ErrorEntry);
      return ERR_7;
   }

   Status = OS_VarDB_CreateParameters(ParameterVars, sizeof(ParameterVars)/sizeof(ParameterVars[0]), &ErrorEntry, AppExportParameterPosition());
   if (Status != 0)
   {
      AppSystemLog(ERR_7, MODULE_NAME"CrVXP: %d,%d", Status, ErrorEntry);
      return ERR_7;
   }

   Status = OS_VarDB_CreateBackups(BackupVars, sizeof(BackupVars)/sizeof(BackupVars[0]), &ErrorEntry, AppLocalParameterPosition(), AppBackupPosition());
   if (Status != 0)
   {
      AppSystemLog(ERR_7, MODULE_NAME"CrVB: %d,%d", Status, ErrorEntry);
      return ERR_7;
   }

   return OS_SUCCESS;
}

#define CREATE_VARDB_VARS

//-----------------------------------------------------------------------
// CREATE IO VARIABLES     CREATE IO VARIABLES     CREATE IO VARIABLES
//-----------------------------------------------------------------------

extern STATUS LubricationYaw_MT_Type1InitIOAliases();
extern struct os_db_alias* LubricationYaw_MT_Type1IOVars;
extern void (*LubricationYaw_MT_Type1SetLockValues)(void);
extern size_t LubricationYaw_MT_Type1IOVarsSize;

static STATUS CreateIOVars(void)
{
   STATUS Status;
   size_t ErrorEntry;

   varid_t VarId;
   BOOL variablesExist = false;
   U8 counter = 50;
   Status = LubricationYaw_MT_Type1InitIOAliases();
   STATUS_LINE_VAR_RETURN_VALUE(Status)
   while (!variablesExist && counter-- > 0)
   {
      variablesExist = true;
      U32 i = 0;
      for (i = 0; i < LubricationYaw_MT_Type1IOVarsSize; ++i)
      {
         if (OS_VarDB_GetVariableID(LubricationYaw_MT_Type1IOVars[i].Name, &VarId) != OS_SUCCESS)
         {
            variablesExist = false;
            break;
         }
      }

      if (!variablesExist)
      {
         OS_Sleep(100);
      }
   }

   Status = OS_VarDB_CreateAliases(LubricationYaw_MT_Type1IOVars, LubricationYaw_MT_Type1IOVarsSize, &ErrorEntry);
   if (Status)
   {
      AppDebugLog(5000, "Var Name = %s", LubricationYaw_MT_Type1IOVars[ErrorEntry].Alias);
   }
   STATUS_LINE_VAR_RETURN_CONST(Status, ErrorEntry);
   return OS_SUCCESS;
}

#define CREATE_IO_VARS

//-----------------------------------------------------------------------
// ALIASES                       ALIASES                       ALIASES
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// INPUT                          INPUT                          INPUT
//-----------------------------------------------------------------------

// Create local variable
#define MODUL_INPUTS
static U8 V_Grid_ErrorActive = 0;
static U8 V_Inverter_StatusLVRT = 0;
static U8 DI_LubricationYaw_SystemLevelWarning = 0;
static U8 DI_LubricationYaw_PumpFault = 0;
static U8 V_YAW_State = 0;
static S32 V_Lub_Equip2_Mode = 0;
static char V_Lub_Equip2_ModeTxt[31];

//-----------------------------------------------------------------------
static struct ModulInOut ModulInputs[] =
{
   {"V_Grid_ErrorActive",                       &V_Grid_ErrorActive,                       sizeof(V_Grid_ErrorActive),                       },
   {"V_Inverter_StatusLVRT",                    &V_Inverter_StatusLVRT,                    sizeof(V_Inverter_StatusLVRT),                    },
   {"DI_LubricationYaw_SystemLevelWarning",     &DI_LubricationYaw_SystemLevelWarning,     sizeof(DI_LubricationYaw_SystemLevelWarning),     },
   {"DI_LubricationYaw_PumpFault",              &DI_LubricationYaw_PumpFault,              sizeof(DI_LubricationYaw_PumpFault),              },
   {"V_YAW_State",                              &V_YAW_State,                              sizeof(V_YAW_State),                              },
   {"V_Lub_Equip2_Mode",                        &V_Lub_Equip2_Mode,                        sizeof(V_Lub_Equip2_Mode),                        },
   {"V_Lub_Equip2_ModeTxt",                     &V_Lub_Equip2_ModeTxt,                     sizeof(V_Lub_Equip2_ModeTxt),                     },
};

//-----------------------------------------------------------------------
// Check variable type
static STATUS VarsReadReturnStatus;
static type_t ReadVarType = TYPE_NONE;
static void VarsReadTypeCheck(void)
{
   (void)VarsReadReturnStatus;
   (void)ReadVarType;
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[0].Name,                      ModulInputs[0].Id)
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[1].Name,                      ModulInputs[1].Id)
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[2].Name,                      ModulInputs[2].Id)
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[3].Name,                      ModulInputs[3].Id)
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[4].Name,                      ModulInputs[4].Id)
   VERIFY_INPUT_REF_ID(S32,       ModulInputs[5].Name,                      ModulInputs[5].Id)
   VERIFY_INPUT_STRING_REF_ID(STRING,    ModulInputs[6].Name,                      ModulInputs[6].Id)
}

#undef MODUL_INPUTS
#define MODUL_INPUTS_SIZE (sizeof(ModulInputs)/sizeof(ModulInputs[0]))

//------------------------------------------------------------------------------------------
// READ/WRITE VARDB ARRAY      READ/WRITE VARDB ARRAY      READ/WRATE VARDB ARRAY
//------------------------------------------------------------------------------------------


//-----------------------------------------------------------------------
// PARAMETER                    PARAMETER                    PARAMETER
//-----------------------------------------------------------------------

// Create local variable
#define MODUL_PARAMETERS
static U8 P_LubricationYaw_ServiceCtrl = 0;
static U32 P_LubricationYaw_PumpOffTime = 0;
static U32 P_LubricationYaw_LevelLowOnTime = 0;
static U8 P_LubricationYaw_InternalMode = 0;
static U32 P_LubricationYaw_FeedbackTime = 0;
static U8 P_LubricationYaw_FeedbackType = 0;
static U32 P_LubricationYaw_PumpOffTimeUnwind = 0;
static U8 P_LubricationYaw_Stroke_ON = 0;
static U8 P_LubricationYawUnwinding_Stroke_ON = 0;



//-----------------------------------------------------------------------
static struct ModulInOut ModulParameters0[] =
{
   {"P_LubricationYaw_ServiceCtrl",             &P_LubricationYaw_ServiceCtrl,             sizeof(P_LubricationYaw_ServiceCtrl),             },
   {"P_LubricationYaw_PumpOffTime",             &P_LubricationYaw_PumpOffTime,             sizeof(P_LubricationYaw_PumpOffTime),             },
   {"P_LubricationYaw_LevelLowOnTime",          &P_LubricationYaw_LevelLowOnTime,          sizeof(P_LubricationYaw_LevelLowOnTime),          },
   {"P_LubricationYaw_InternalMode",            &P_LubricationYaw_InternalMode,            sizeof(P_LubricationYaw_InternalMode),            },
   {"P_LubricationYaw_FeedbackTime",            &P_LubricationYaw_FeedbackTime,            sizeof(P_LubricationYaw_FeedbackTime),            },
   {"P_LubricationYaw_FeedbackType",            &P_LubricationYaw_FeedbackType,            sizeof(P_LubricationYaw_FeedbackType),            },
   {"P_LubricationYaw_PumpOffTimeUnwind",       &P_LubricationYaw_PumpOffTimeUnwind,       sizeof(P_LubricationYaw_PumpOffTimeUnwind),       },
   {"P_LubricationYaw_Stroke_ON",               &P_LubricationYaw_Stroke_ON,               sizeof(P_LubricationYaw_Stroke_ON),               },
   {"P_LubricationYawUnwinding_Stroke_ON",      &P_LubricationYawUnwinding_Stroke_ON,      sizeof(P_LubricationYawUnwinding_Stroke_ON),      },

};
static struct ModulInOut* ModulParameters[] =
{
   ModulParameters0,
};

//-----------------------------------------------------------------------
// Check variable type
static STATUS ParaVarsReadReturnStatus;
static type_t ParaReadVarType = TYPE_NONE;
static void ParaVarsReadTypeCheck(void)
{
   (void)ParaVarsReadReturnStatus;
   (void)ParaReadVarType;
}

#undef MODUL_PARAMETERS

#define PARAMETERS_GROUPS_SIZE        1
#define GENERAL_GROUP                 0
#define MODUL_PARAMETERS_TOTAL_SIZE   9
static SUBSCRIPTION ParaSubscription[MODUL_PARAMETERS_TOTAL_SIZE];
static U8 ReadParameters[PARAMETERS_GROUPS_SIZE];
static U8 ParametersChanged[PARAMETERS_GROUPS_SIZE];
static UNSIGNED GroupsIndexes[PARAMETERS_GROUPS_SIZE];
static int ParaGroupsSizes[PARAMETERS_GROUPS_SIZE] = { 9 };
static STATUS VarDbUpdateParameter(varid_t VariableId, void* Message, U16 Length, UNSIGNED paraGroupIndex, UNSIGNED Ref2)
{
   ReadParameters[paraGroupIndex] = 1;
   ParametersChanged[paraGroupIndex] = 1;
   return OS_SUCCESS;
}
static STATUS ReadParametersFunc(int paraGroupIndex)
{
   STATUS LocalStatus;
   // Check inputdata
   if (sizeof(ModulParameters[paraGroupIndex]) == 0)
   {
      AppSystemLog(ERR_4, MODULE_NAME"Group %d ModuleParameters = 0", paraGroupIndex);
      return ERR_4;
   }
   // Read inputdata
   LocalStatus = OS_ReadVariables(ModulParameters[paraGroupIndex], ParaGroupsSizes[paraGroupIndex]);
   if (LocalStatus != 0)
   {
      AppSystemLog(11, "LocalStatus: %d", LocalStatus);
      AppSystemLog(ERR_4, MODULE_NAME"ReadParErr: group=%d element=%d elementpointer=0x%x", paraGroupIndex, LocalStatus, &ModulParameters[LocalStatus]);
      return ERR_4;
   }
   return OS_SUCCESS;
}


//-----------------------------------------------------------------------
// READ VARS FROM VARDB    READ VARS FROM VARDB    READ VARS FROM VARDB
//-----------------------------------------------------------------------

static STATUS InputReferenceRoutine(U8 ModuleState)
{
   STATUS LocalStatus = 0;

   // Read input references
   if (ModuleState >= APP_INIT3)
   {
      // Check inputdata
      if (sizeof(ModulInputs) == 0)
      {
         AppSystemLog(ERR_4, MODULE_NAME"ModuleInputs = 0");
         return ERR_4;
      }
      // Read inputdata
      LocalStatus = OS_ReadVariables(ModulInputs, MODUL_INPUTS_SIZE);
      if (LocalStatus != 0)
      {
         AppSystemLog(ERR_4, MODULE_NAME"ReadVErr: element=%d elementpointer=0x%x", LocalStatus, &ModulInputs[LocalStatus]);
         return ERR_4;
      }
   }
   // Read input parameters
   if (ModuleState == APP_INIT3)
   {
      static size_t ParaCounter = 0;
      int groupIndex;
      for (groupIndex = 0; groupIndex < PARAMETERS_GROUPS_SIZE; groupIndex++)
      {
         ParametersChanged[groupIndex] = 1;
         ReadParameters[groupIndex] = 1;
         GroupsIndexes[groupIndex] = groupIndex;

         // Check inputdata
         if (sizeof(ModulParameters[groupIndex]) == 0)
         {
            AppSystemLog(ERR_4, MODULE_NAME"Group = %d ModuleParameters = 0", groupIndex);
            return ERR_4;
         }
         // Read inputdata
         LocalStatus = OS_ReadVariables(ModulParameters[groupIndex], ParaGroupsSizes[groupIndex]);
         if (LocalStatus != 0)
         {
            AppSystemLog(ERR_4, MODULE_NAME"ReadVParaErr: group=%d element=%d elementpointer=0x%x", groupIndex, LocalStatus, &ModulParameters[groupIndex][LocalStatus]);
            return ERR_4;
         }
         int paraIndex;
         for (paraIndex = 0; paraIndex < ParaGroupsSizes[groupIndex]; paraIndex++)
         {
            LocalStatus = OS_SubHandl_SubscribeFunctionWithRef(&ParaSubscription[ParaCounter], 1, &ModulParameters[groupIndex][paraIndex].Id, &GroupsIndexes[groupIndex], &GroupsIndexes[groupIndex], VarDbUpdateParameter);
            ParaCounter++;
            if (LocalStatus != 0)
            {
               AppSystemLog(ERR_4, MODULE_NAME"Subscribe Parameter: group=%d element=%d elementpointer=0x%x", groupIndex, LocalStatus, &ModulParameters[LocalStatus]);
               return ERR_4;
            }
         }
      }
   }
   if (ModuleState == APP_RUN)
   {
      int groupIndex;
      for (groupIndex = 0; groupIndex < PARAMETERS_GROUPS_SIZE; groupIndex++)
      {
         if (ReadParameters[groupIndex])
         {
            LocalStatus = ReadParametersFunc(groupIndex);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
            ReadParameters[groupIndex] = 0;
         }
      }
   }

   return 0;
}

#define READ_VARS

//-----------------------------------------------------------------------
// OUTPUT                         OUTPUT                         OUTPUT
//-----------------------------------------------------------------------

// Create local variable
#define MODUL_OUTPUTS
static U8 DO_LubricationYaw_Pump = 0;
static U64 B_YawOilTankEmptyErrorTimer = 0;
static U64 B_YawLubricationTimer = 0;
static U8 V_FirstExceptionYawBearing = 0;
static S32 V_Lub_Equip2_State = 0;
static S32 V_Lub_Equip2_Status = 0;
static char V_LubricationYaw_OilTankEmptyTimeTxt[31];
static char V_LubricationYaw_TimeIndicationTxt[31];
static char V_Lub_Equip2_StateTxt[31];
static char V_Lub_Equip2_StatusTxt[31];


//-----------------------------------------------------------------------
static struct ModulInOut ModulOutputs[] =
{
   {"DO_LubricationYaw_Pump",                   &DO_LubricationYaw_Pump,                   sizeof(DO_LubricationYaw_Pump),                   },
   {"B_YawOilTankEmptyErrorTimer",              &B_YawOilTankEmptyErrorTimer,              sizeof(B_YawOilTankEmptyErrorTimer),              },
   {"B_YawLubricationTimer",                    &B_YawLubricationTimer,                    sizeof(B_YawLubricationTimer),                    },
   {"V_LubricationYaw_OilTankEmptyTimeTxt",     &V_LubricationYaw_OilTankEmptyTimeTxt,     sizeof(V_LubricationYaw_OilTankEmptyTimeTxt),     },
   {"V_LubricationYaw_TimeIndicationTxt",       &V_LubricationYaw_TimeIndicationTxt,       sizeof(V_LubricationYaw_TimeIndicationTxt),       },
   {"V_FirstExceptionYawBearing",               &V_FirstExceptionYawBearing,               sizeof(V_FirstExceptionYawBearing),               },
   {"V_Lub_Equip2_State",                       &V_Lub_Equip2_State,                       sizeof(V_Lub_Equip2_State),                       },
   {"V_Lub_Equip2_StateTxt",                    &V_Lub_Equip2_StateTxt,                    sizeof(V_Lub_Equip2_StateTxt),                    },
   {"V_Lub_Equip2_Status",                      &V_Lub_Equip2_Status,                      sizeof(V_Lub_Equip2_Status),                      },
   {"V_Lub_Equip2_StatusTxt",                   &V_Lub_Equip2_StatusTxt,                   sizeof(V_Lub_Equip2_StatusTxt),                   },
};

//-----------------------------------------------------------------------
// Check variable type
static STATUS VarsWriteReturnStatus;
static type_t WriteVarType = TYPE_NONE;
static void VarsWriteTypeCheck(void)
{
   (void)VarsWriteReturnStatus;
   (void)WriteVarType;
   VERIFY_OUTPUT_REF_ID(U8,        ModulOutputs[0].Name,                     ModulOutputs[0].Id,                       0)
   VERIFY_OUTPUT_REF_ID(U64,       ModulOutputs[1].Name,                     ModulOutputs[1].Id,                       0)
   VERIFY_OUTPUT_REF_ID(U64,       ModulOutputs[2].Name,                     ModulOutputs[2].Id,                       0)
   VERIFY_OUTPUT_STRING_REF_ID(STRING,     ModulOutputs[3].Name,                      ModulOutputs[3].Id,               0)
   VERIFY_OUTPUT_STRING_REF_ID(STRING,     ModulOutputs[4].Name,                      ModulOutputs[4].Id, 0)
   VERIFY_OUTPUT_REF_ID(U8,        ModulOutputs[5].Name,                     ModulOutputs[5].Id,                       0)
   VERIFY_OUTPUT_REF_ID(S32,       ModulOutputs[6].Name,                     ModulOutputs[6].Id,                       0)
   VERIFY_OUTPUT_STRING_REF_ID(STRING,     ModulOutputs[7].Name,                      ModulOutputs[7].Id,                           0)
   VERIFY_OUTPUT_REF_ID(S32,       ModulOutputs[8].Name,                     ModulOutputs[8].Id,                       0)
   VERIFY_OUTPUT_STRING_REF_ID(STRING,     ModulOutputs[9].Name,                      ModulOutputs[9].Id,                           0)
}

#undef MODUL_OUTPUTS
#define MODUL_OUTPUTS_SIZE (sizeof(ModulOutputs)/sizeof(ModulOutputs[0]))

//-----------------------------------------------------------------------
// WRITE VARS TO VARDB     WRITE VARS TO VARDB     WRITE VARS TO VARDB
//-----------------------------------------------------------------------

static STATUS InitOutputVars(void)
{
   STATUS LocalStatus;
   // Read outputdata
   LocalStatus = OS_ReadVariables(ModulOutputs, MODUL_OUTPUTS_SIZE);
   if (LocalStatus != 0)
   {
      AppSystemLog(ERR_4, MODULE_NAME"InitErr: element=%d elementpointer=0x%x", LocalStatus, &ModulOutputs[LocalStatus]);
      return ERR_4;
   }
   return OS_SUCCESS;
}
static STATUS OutputReferenceRoutine(U8 ModuleState)
{
   STATUS LocalStatus = 0;
   // Write Outputdata
   LocalStatus = OS_WriteVariablesConditional(ModulOutputs, MODUL_OUTPUTS_SIZE);
   if (LocalStatus != 0)
   {
      AppSystemLog(ERR_5, MODULE_NAME"WriteVErr: element=%d elementpointer=0x%x", LocalStatus, &ModulOutputs[LocalStatus]);
      return ERR_5;
   }
   return 0;
}

#define WRITE_VARS

//-----------------------------------------------------------------------
// VERIFY VARIABLES CREATION                 VERIFY VARIABLES CREATION
//-----------------------------------------------------------------------

static STATUS LocalIoCheck(void)
{
   // Check if input variables exist.
   STATUS LocalStatus;

   LocalStatus = OS_DoesVariablesExist(ModulInputs, MODUL_INPUTS_SIZE);
   if (LocalStatus != 0)
   {
      AppSystemLog(ERR_1, MODULE_NAME"InputErr: %d", LocalStatus);
      AppSystemLog(ERR_1, "Name: %s", ModulInputs[LocalStatus-1].Name);
      return ERR_1;
   }
   (void)VarsReadTypeCheck();

   int groupIndex;
   for (groupIndex = 0; groupIndex < PARAMETERS_GROUPS_SIZE; groupIndex++)
   {
      LocalStatus = OS_DoesVariablesExist(ModulParameters[groupIndex], ParaGroupsSizes[groupIndex]);
      if (LocalStatus != 0)
      {
         AppSystemLog(ERR_3, MODULE_NAME"ParameterErr: %d Group:%d", LocalStatus, groupIndex);
         AppSystemLog(ERR_3, "Name: %s", ModulParameters[groupIndex][LocalStatus-1].Name);
         return ERR_3;
      }
   }
   (void)ParaVarsReadTypeCheck();

   LocalStatus = OS_DoesVariablesExist(ModulOutputs, MODUL_OUTPUTS_SIZE);
   if (LocalStatus != 0)
   {
      AppSystemLog(ERR_2, MODULE_NAME"OutputErr: %d", LocalStatus);
      AppSystemLog(ERR_2, "Name: %s", ModulOutputs[LocalStatus-1].Name);
      return ERR_2;
   }
   (void)VarsWriteTypeCheck();

   return OS_SUCCESS;
}

#define VERIFY_VARIABLES

//-----------------------------------------------------------------------
// ALLOCATE MEMORY FOR SUMMATIONS        ALLOCATE MEMORY FOR SUMMATIONS
//-----------------------------------------------------------------------

static SSUM SSummationS_YawLubricationPump;

//-----------------------------------------------------------------------
// SUMMATIONS                  SUMMATIONS                  SUMMATIONS
//-----------------------------------------------------------------------

static struct os_db_summation ServiceSummations[] =
{
   VAR_ELEMENT_SERVICE_SUM( "S_YawLubricationPump",                     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_99,                 "DO_LubricationYaw_Pump",                   SSummationS_YawLubricationPump   ),
};

static STATUS CreateSummations(void)
{
  STATUS LocalStatus = 0;
  size_t ErrorEntry = 0;

  LocalStatus = OS_SUM_CreateSummations(ServiceSummations, sizeof(ServiceSummations)/sizeof(ServiceSummations[0]), &ErrorEntry, AppBackupPosition());
  if (OS_SUCCESS != LocalStatus)
  {
    return LocalStatus;
  }

  return LocalStatus;
}

#define CREATE_SUMMATIONS

//-----------------------------------------------------------------------
// DEFINE MENUS               DEFINE MENUS               DEFINE MENUS
//-----------------------------------------------------------------------



// Menu line and link to local menu
//-----------------------------------------------------------------------
static struct line_struct M_LubricationYawBearingLinkToLocalMenu[] =
{
   MENU_ELEMENT_LINE_LINK("Lubrication Yaw MT Type 1",         PASSWORD_LEVEL_END_CUSTOMER,        "M_LubricationYawBearing",          "G_LubricationYawBearing"),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_LubricationYawBearingMenu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_LubricationYawBearing",          PASSWORD_LEVEL_END_CUSTOMER),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_LubricationYawBearingMenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("LUBRICATION YAW MT TYPE 1",         PASSWORD_LEVEL_END_CUSTOMER,        "M_"APP_ID"AppMain",                "G_"APP_ID"App"),
   MENU_ELEMENT_LINE_VARRO("Yaw Lubrication State",            PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_Lub_Equip2_StateTxt",                      LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_LINK("Status",                            PASSWORD_LEVEL_END_CUSTOMER,        "M_Status2",                        "G_LubricationYawBearing"),
   MENU_ELEMENT_LINE_LINK("Parameter",                         PASSWORD_LEVEL_END_CUSTOMER,        "M_Parameter3",                     "G_LubricationYawBearing"),
   MENU_ELEMENT_LINE_LINK("Service",                           PASSWORD_LEVEL_SERVICE,             "M_Service4",                       "G_LubricationYawBearing"),
   MENU_ELEMENT_LINE_LINK("Debug",                             PASSWORD_LEVEL_LICENCE_PROGRAMMER,  "M_Debug5",                         "G_LubricationYawBearing"),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_Status2Menu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_Status2",                        PASSWORD_LEVEL_END_CUSTOMER),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_Status2MenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("STATUS",                            PASSWORD_LEVEL_END_CUSTOMER,        "M_LubricationYawBearing",          "G_LubricationYawBearing"),
   MENU_ELEMENT_LINE_VARRO("Yaw Lubrication Mode Request",     PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_Lub_Equip2_ModeTxt",                       LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Yaw Lubrication Pump State",       PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_Lub_Equip2_StateTxt",                      LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Yaw Lubrication Status",           PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_Lub_Equip2_StatusTxt",                     LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Yaw Lubrication Timer",            PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_LubricationYaw_TimeIndicationTxt",         LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Yaw Lubrication Pump",             PASSWORD_LEVEL_END_CUSTOMER,        (char*)"DO_LubricationYaw_Pump",                     LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Yaw Lubrication Oil Level",        PASSWORD_LEVEL_END_CUSTOMER,        (char*)"DI_LubricationYaw_SystemLevelWarning",       LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Yaw Lubrication Pump Distributor", PASSWORD_LEVEL_END_CUSTOMER,        (char*)"DI_LubricationYaw_PumpFault",                LINE_FORMAT_NONE),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_Parameter3Menu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_Parameter3",                     PASSWORD_LEVEL_END_CUSTOMER),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_Parameter3MenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("PARAMETER",                         PASSWORD_LEVEL_END_CUSTOMER,        "M_LubricationYawBearing",          "G_LubricationYawBearing"),
   MENU_ELEMENT_LINE_VARRW("Yaw Lubrication Control Mode",     PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_LubricationYaw_InternalMode",              LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Yaw Lubrication Pump On Stroke",   PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_LubricationYaw_Stroke_ON",                 LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Yaw Lubrication Pump Off Time",    PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_LubricationYaw_PumpOffTime",               LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Yaw Lubrication Pump On Stroke (Unwind)", PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_LubricationYawUnwinding_Stroke_ON",        LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Yaw Lubrication Pump Off Time (Unwind)", PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_LubricationYaw_PumpOffTimeUnwind",         LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Yaw Lubrication FB Type",          PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_LubricationYaw_FeedbackType",              LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Yaw Lubrication FB Time",          PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_LubricationYaw_FeedbackTime",              LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Max Time with Oil Level Low",      PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_LubricationYaw_LevelLowOnTime",            LINE_FORMAT_NONE),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_Service4Menu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_Service4",                       PASSWORD_LEVEL_SERVICE),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_Service4MenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("SERVICE",                           PASSWORD_LEVEL_SERVICE,             "M_LubricationYawBearing",          "G_LubricationYawBearing"),
   MENU_ELEMENT_LINE_VARRW("Yaw Lubrication Service Control",  PASSWORD_LEVEL_SERVICE,             (char*)"P_LubricationYaw_ServiceCtrl",               LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Yaw Lubrication Oil Tank Empty Time", PASSWORD_LEVEL_SERVICE,             (char*)"V_LubricationYaw_OilTankEmptyTimeTxt",       LINE_FORMAT_NONE),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_Debug5Menu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_Debug5",                         PASSWORD_LEVEL_LICENCE_PROGRAMMER),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_Debug5MenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("DEBUG",                             PASSWORD_LEVEL_LICENCE_PROGRAMMER,  "M_LubricationYawBearing",          "G_LubricationYawBearing"),
   MENU_ELEMENT_LINE_VARRO("Yaw Lubrication Mode Request",     PASSWORD_LEVEL_MITA_PROGRAMMER,     (char*)"V_Lub_Equip2_Mode",                          LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Yaw Lubrication State",            PASSWORD_LEVEL_MITA_PROGRAMMER,     (char*)"V_Lub_Equip2_State",                         LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Yaw Lubrication Status",           PASSWORD_LEVEL_MITA_PROGRAMMER,     (char*)"V_Lub_Equip2_Status",                        LINE_FORMAT_NONE),
};
// Creating parameters for multiplexed categories
//-----------------------------------------------------------------------
static struct multiplexed_info_struct M_LubricationYawBearingMultiplexedCategoriesParameters[] =
{
0};

//-----------------------------------------------------------------------
// CREATE MENUS               CREATE MENUS               CREATE MENUS
//-----------------------------------------------------------------------

// Memory reservation
//-----------------------------------------------------------------------
static struct menu_group_struct ObjGroup[1];

// Creating the menus
//-----------------------------------------------------------------------
STATUS LubricationYaw_MT_Type1MenuAppInit(U8 ModuleState, OS_MEMORY_POOL* pPool)
{
   STATUS Status;

   if (ModuleState == APP_INIT1)
   {
      /* Create application group */
      Status = OS_CreateMenuGroup(ObjGroup, M_LubricationYawBearingLinkToLocalMenu[0].LinkGroup);
      STATUS_LINE_VAR_RETURN_VALUE(Status);
   }

   Status = CreateAndInitializeMenu(ModuleState,
                                    M_LubricationYawBearingMenuLines[0].LinkGroup,
                                    M_LubricationYawBearingMenuLines[0].LinkName,
                                    ELEMENT(M_LubricationYawBearingLinkToLocalMenu),
                                    M_LubricationYawBearingLinkToLocalMenu[0].LinkGroup,
                                    ELEMENT(M_LubricationYawBearingMenu),
                                    M_LubricationYawBearingLinkToLocalMenu[0].LinkName,
                                    ELEMENT(M_LubricationYawBearingMenuLines),
                                    pPool,
                                    M_LubricationYawBearingMultiplexedCategoriesParameters);
   STATUS_LINE_VAR_RETURN_VALUE(Status);

   Status = CreateAndInitializeMenu(ModuleState,
                                    M_Status2MenuLines[0].LinkGroup,
                                    M_Status2MenuLines[0].LinkName,
                                    NULL,
                                    0,
                                    M_LubricationYawBearingMenuLines[2].LinkGroup,
                                    ELEMENT(M_Status2Menu),
                                    M_LubricationYawBearingMenuLines[2].LinkName,
                                    ELEMENT(M_Status2MenuLines),
                                    pPool,
                                    M_LubricationYawBearingMultiplexedCategoriesParameters);
   STATUS_LINE_VAR_RETURN_VALUE(Status);

   Status = CreateAndInitializeMenu(ModuleState,
                                    M_Parameter3MenuLines[0].LinkGroup,
                                    M_Parameter3MenuLines[0].LinkName,
                                    NULL,
                                    0,
                                    M_LubricationYawBearingMenuLines[3].LinkGroup,
                                    ELEMENT(M_Parameter3Menu),
                                    M_LubricationYawBearingMenuLines[3].LinkName,
                                    ELEMENT(M_Parameter3MenuLines),
                                    pPool,
                                    M_LubricationYawBearingMultiplexedCategoriesParameters);
   STATUS_LINE_VAR_RETURN_VALUE(Status);

   Status = CreateAndInitializeMenu(ModuleState,
                                    M_Service4MenuLines[0].LinkGroup,
                                    M_Service4MenuLines[0].LinkName,
                                    NULL,
                                    0,
                                    M_LubricationYawBearingMenuLines[4].LinkGroup,
                                    ELEMENT(M_Service4Menu),
                                    M_LubricationYawBearingMenuLines[4].LinkName,
                                    ELEMENT(M_Service4MenuLines),
                                    pPool,
                                    M_LubricationYawBearingMultiplexedCategoriesParameters);
   STATUS_LINE_VAR_RETURN_VALUE(Status);

   Status = CreateAndInitializeMenu(ModuleState,
                                    M_Debug5MenuLines[0].LinkGroup,
                                    M_Debug5MenuLines[0].LinkName,
                                    NULL,
                                    0,
                                    M_LubricationYawBearingMenuLines[5].LinkGroup,
                                    ELEMENT(M_Debug5Menu),
                                    M_LubricationYawBearingMenuLines[5].LinkName,
                                    ELEMENT(M_Debug5MenuLines),
                                    pPool,
                                    M_LubricationYawBearingMultiplexedCategoriesParameters);
   STATUS_LINE_VAR_RETURN_VALUE(Status);

   return OS_SUCCESS;
}

#define CREATE_MENU

//-----------------------------------------------------------------------
//               BUTTONS FUNCTIONS FORWARD DECLARATIONS
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// BUTTONS                       BUTTONS                      BUTTONS
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
//             SET/RESET FUNCTIONS FORWARD DECLARATIONS
//-----------------------------------------------------------------------
static U8 StatusSetFunc769(void);
static U8 StatusSetFunc787(void);
static U8 StatusResetFunc787(void);
static U8 StatusSetFunc788(void);
//-----------------------------------------------------------------------
// STATUSCODES                 STATUSCODES                 STATUSCODES
//-----------------------------------------------------------------------

static struct sts_statuscode_structure StatusCodes[] =
{
   STS_CODE_ELEMENT("Yaw rim lubricat.err",   20*SEC,    769,       STATUSCODE_UPDATE_TYPE_POLLING,         PASSWORD_LEVEL_SUPERVISOR,         STATUSCODE_TIMER_TYPE_CONSTANT,     STATUSCODE_TIMER_TYPE_CONSTANT,     STATUSCODE_RESET_TYPE_DISPLAY,      STATUSCODE_PRIORITY_LOW,       27,   0,    32,   NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         StatusSetFunc769,        NULL,                    BRAKE_PROG_0,        BRAKE_PROG_0,        BRAKE_PROG_MAX,      NULL,                PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      YAW_PROG_0,          YAW_PROG_0,          YAW_PROG_240,        NULL,                PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      1,    0,    255,  NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      1,  PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      100,       20,        1000,      NULL,      PASSWORD_LEVEL_ADMINISTRATOR,      PASSWORD_LEVEL_ADMINISTRATOR,      0,         SETDELAY_MIN,   SETDELAY_MAX,   NULL,      PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         RESETDELAY_MIN, RESETDELAY_MAX, NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         REPEATTIMES_MIN,     REPEATTIMES_MAX,     NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         REPEATPERIOD_MIN,    REPEATPERIOD_MAX,    NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      0,         REPEATCODE_MIN,      REPEATCODE_MAX,      NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      0,         TIMEOUTPERIOD_MIN,   65535,               NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      0,         TIMEOUTCODE_MIN,     TIMEOUTCODE_MAX,     NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         NULL),
   STS_CODE_ELEMENT("Yaw bear.lubr. Warn.",   20*SEC,    787,       STATUSCODE_UPDATE_TYPE_POLLING,         PASSWORD_LEVEL_SUPERVISOR,         STATUSCODE_TIMER_TYPE_CONSTANT,     STATUSCODE_TIMER_TYPE_CONSTANT,     STATUSCODE_RESET_TYPE_AUTOMATIC,    STATUSCODE_PRIORITY_LOW,       27,   0,    32,   NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         StatusSetFunc787,        StatusResetFunc787,      BRAKE_PROG_0,        BRAKE_PROG_0,        BRAKE_PROG_MAX,      NULL,                PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      YAW_PROG_0,          YAW_PROG_0,          YAW_PROG_240,        NULL,                PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      1,    0,    255,  NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      1,  PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      100,       20,        1000,      NULL,      PASSWORD_LEVEL_ADMINISTRATOR,      PASSWORD_LEVEL_ADMINISTRATOR,      0,         SETDELAY_MIN,   SETDELAY_MAX,   NULL,      PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         RESETDELAY_MIN, RESETDELAY_MAX, NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         0,         REPEATTIMES_MIN,     REPEATTIMES_MAX,     NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         REPEATPERIOD_MIN,    REPEATPERIOD_MAX,    NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      0,         REPEATCODE_MIN,      REPEATCODE_MAX,      NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      0,         TIMEOUTPERIOD_MIN,   65535,               NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      0,         TIMEOUTCODE_MIN,     TIMEOUTCODE_MAX,     NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         NULL),
   STS_CODE_ELEMENT("Yaw rim lubr. empty",    20*SEC,    788,       STATUSCODE_UPDATE_TYPE_POLLING,         PASSWORD_LEVEL_SUPERVISOR,         STATUSCODE_TIMER_TYPE_CONSTANT,     STATUSCODE_TIMER_TYPE_CONSTANT,     STATUSCODE_RESET_TYPE_DISPLAY,      STATUSCODE_PRIORITY_LOW,       27,   0,    32,   NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         StatusSetFunc788,        NULL,                    BRAKE_PROG_0,        BRAKE_PROG_0,        BRAKE_PROG_MAX,      NULL,                PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      YAW_PROG_0,          YAW_PROG_0,          YAW_PROG_240,        NULL,                PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      1,    0,    255,  NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      1,  PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      100,       20,        1000,      NULL,      PASSWORD_LEVEL_ADMINISTRATOR,      PASSWORD_LEVEL_ADMINISTRATOR,      0,         SETDELAY_MIN,   SETDELAY_MAX,   NULL,      PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         RESETDELAY_MIN, RESETDELAY_MAX, NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         0,         REPEATTIMES_MIN,     REPEATTIMES_MAX,     NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         REPEATPERIOD_MIN,    REPEATPERIOD_MAX,    NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      0,         REPEATCODE_MIN,      REPEATCODE_MAX,      NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      0,         TIMEOUTPERIOD_MIN,   65535,               NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      0,         TIMEOUTCODE_MIN,     TIMEOUTCODE_MAX,     NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         NULL),
};

static STATUS_CODE_CONTROL_BLOCK StatusCodeControlBlock;

static STATUS LocalStatusCodeInit(void)
{
   STATUS LocalStatus;

   LocalStatus = OS_StatusCodeInit(STATUSCODE_INTERFACE_VERSION,
                                   &StatusCodeControlBlock,
                                   StatusCodes,
                                   sizeof(StatusCodes)/sizeof(StatusCodes[0]),
                                   AppLocalParameterPosition(),
                                   AppBackupPosition());
   STATUS_LINE_VAR_RETURN_CONST(LocalStatus, ERR_3);

   return OS_SUCCESS;
}

#define CREATE_STATUS_CODES

//-----------------------------------------------------------------------
// MODIFIABLE                  MODIFIABLE                   MODIFIABLE
//-----------------------------------------------------------------------

extern const char LubricationYaw_MT_Type1AppGroupName[];
extern const char LubricationYaw_MT_Type1AppMenuName[];

static void Init_Structures_From_Conf_File(void)
{
   M_LubricationYawBearingMenuLines[0].LinkName = (char*)LubricationYaw_MT_Type1AppMenuName;
   M_LubricationYawBearingMenuLines[0].LinkGroup = (char*)LubricationYaw_MT_Type1AppGroupName;
}

//-----------------------------------------------------------------------
// AUTOGENERATED END        AUTOGENERATED END        AUTOGENERATED END
//-----------------------------------------------------------------------
//}

#undef AUTOGENERATED_PART

//-----------------------------------------------------------------------
// USER DEFINITIONS         USER DEFINITIONS         USER DEFINITIONS
//-----------------------------------------------------------------------
//________________________________________________________________________
typedef struct _STimer_t
{
    time_t           P_Time;
    U8               OStatus;

    U8               FirstRun;
    U8               Start;
    U8               Suspend;
    time_t           TimeStart;
    time_t           TimeLast;
    time_t           Backup;
} STimer_t;
//________________________________________________________________________
// Function prototypes:
static void TimerReset(STimer_t *pTimer);
static time_t TimerLeft(STimer_t *pTimer);
static void TimerSet(STimer_t *pTimer, time_t Delay);
static BOOL TimerCheck(STimer_t *pTimer);
static void TimerStop(STimer_t *pTimer);
static void TimerStart(STimer_t *pTimer);

static void TimeToText(U64 Time, char *Text, U8 size);

#if 0       //  For future use
//________________________________________________________________________
static void TimerInit(STimer_t *pTimer, time_t Delay)
{
    pTimer->P_Time = Delay;
    pTimer->FirstRun  = 0;
}
#endif

//________________________________________________________________________
static void TimerReset(STimer_t *pTimer)        //  Reset all values to default and start timer automatically
{
    pTimer->TimeStart = OS_GetTimeInMs();
    pTimer->Backup    = 0;
    pTimer->OStatus   = 0;
    pTimer->Suspend   = 0;
    pTimer->FirstRun  = 1;
    pTimer->Start     = 1;
}
//________________________________________________________________________
static time_t TimerLeft(STimer_t *pTimer)
{
time_t  TimeDiff = 0;

    if( !TimerCheck(pTimer) )
    {
        TimeDiff = OS_GetTimeInMs();    //  time can change within two following commands, so it is needed to save time at some moment of time to temporary variable
        return (pTimer->P_Time > ( TimeDiff - pTimer->TimeStart )) ? (pTimer->P_Time - ( TimeDiff - pTimer->TimeStart )) : 0;
    }
    else
    {
        return 0;
    }
}
//________________________________________________________________________
static void TimerSet(STimer_t *pTimer, time_t Delay)        //  Timer can be restored from backup by this function
{
    if(Delay < pTimer->P_Time) { pTimer->TimeStart = OS_GetTimeInMs() -  pTimer->P_Time + Delay; }
    else                       { pTimer->TimeStart = OS_GetTimeInMs(); }
}
//________________________________________________________________________
static BOOL TimerCheck(STimer_t *pTimer)
{
    if( pTimer->Start && !pTimer->OStatus )
    {
        pTimer->TimeLast = OS_GetTimeInMs() - pTimer->TimeStart;
        if ( pTimer->TimeLast >= pTimer->P_Time )
        {
            pTimer->TimeStart = 0;
            pTimer->OStatus   = 1;
        }
    }
    return pTimer->OStatus;
}
//________________________________________________________________________
static void TimerStop(STimer_t *pTimer)         //  Backup current time and stop timer
{
    if( 0 == pTimer->Suspend ) { pTimer->Backup = TimerLeft(pTimer); }
    pTimer->Start = 0;
    pTimer->Suspend = 1;
}
//________________________________________________________________________
static void TimerStart(STimer_t *pTimer)        //  Start timer if it was stopped before or was not started/resetted
{
    if( pTimer->Suspend )                       //  timer was stopped previously, so reinitialize timer from backup and start it
    {
        TimerSet(pTimer, pTimer->Backup);
        pTimer->Suspend = 0;
        pTimer->Backup  = 0;
        pTimer->OStatus = 0;
        pTimer->Start   = 1;
    }
    else
    {
        pTimer->OStatus   = 0;
        pTimer->Suspend   = 0;
        pTimer->Backup    = 0;
        pTimer->FirstRun  = 1;
        pTimer->Start     = 1;
    }
}
//________________________________________________________________________
enum { LUB_MODE_PERIODIC_EXTRA_CTRL = 0 };
enum { LUB_MODE_PERIODIC_SIMPLE     = 1 };
enum { LUB_MODE_ALWAYS_ON           = 2 };

// Internal Lubrication State
enum { YAW_LUB_SERVICE_OFF          = 1 };
enum { YAW_LUB_SERVICE_ON           = 2 };
enum { YAW_LUB_BLOCKED              = 4 };
enum { YAW_LUB_SUSPENDED            = 5 };
enum { YAW_LUB_AUTO_OFF             = 6 };
enum { YAW_LUB_AUTO_ON              = 7 };

// Lubrication Status
enum { YAW_LUB_STATUS_OK            = 0 };
enum { YAW_LUB_STATUS_SAFETY        = 1 };
enum { YAW_LUB_STATUS_HW_ERROR      = 2 };
enum { YAW_LUB_STATUS_EMPTY         = 3 };
enum { YAW_LUB_STATUS_GRID_ERROR    = 4 };
enum { YAW_LUB_STATUS_LVRT          = 5 };
enum { YAW_LUB_STATUS_YP_ACTIVE     = 6 };
enum { YAW_LUB_STATUS_LM_BLOCK      = 7 };
enum { YAW_LUB_STATUS_YAW_ACTIVITY  = 8 };

enum { YAW_LUB_PUMP_ON              = 1 };
enum { YAW_LUB_PUMP_OFF             = 0 };

enum { YAW_LUB_YAW_RUN_CW           = 2  };	//enum { YAW_LUB_YAW_RUN_CW           = 40  };
enum { YAW_LUB_YAW_RUN_CCW          = 3  };	//enum { YAW_LUB_YAW_RUN_CCW          = 41  };
enum { YAW_LUB_YAW_UNWIND_CW        = 4  };	//enum { YAW_LUB_YAW_UNWIND_CW        = 50  };
enum { YAW_LUB_YAW_UNWIND_CCW       = 5  };	//enum { YAW_LUB_YAW_UNWIND_CCW       = 51  };
enum { YAW_LUB_YAW_ERROR            = 255 };

static const char YAW_LUB_STATUS_OK_TEXT[]           = "OK";
static const char YAW_LUB_STATUS_SAFETY_TEXT[]       = "Safety";
static const char YAW_LUB_STATUS_HW_ERROR_TEXT[]     = "HW Error";
static const char YAW_LUB_STATUS_EMPTY_TEXT[]        = "Tank Empty";
static const char YAW_LUB_STATUS_GRID_ERROR_TEXT[]   = "Grid Error";
static const char YAW_LUB_STATUS_LVRT_TEXT[]         = "LVRT";
static const char YAW_LUB_STATUS_YP_ACTIVE_TEXT[]    = "Yaw Error";
static const char YAW_LUB_STATUS_LM_BLOCK_TEXT[]     = "LM Block";
static const char YAW_LUB_STATUS_YAW_ACTIVITY_TEXT[] = "Yaw Activity";

enum { LUB_ERROR_FB_TYPE_LOW_LEVEL    = 0 };
enum { LUB_ERROR_FB_TYPE_HIGH_LEVEL   = 1 };
enum { LUB_ERROR_FB_TYPE_FREQUENCY    = 2 };

#ifndef NA_TEXT
static const char NA_TEXT[] = "N/A";
#endif
//______________________________________________________________________________________
static void WriteState(void)
{
static U8 OldState = 0xFF;

    if ( V_Lub_Equip2_State != OldState )
    {
        switch(V_Lub_Equip2_State)
        {
            case STATE_SERVICE_OFF :    { strncpy(V_Lub_Equip2_StateTxt, STATE_TEXT_SERVICE_OFF,  sizeof(V_Lub_Equip2_StateTxt)); } break;
            case STATE_SERVICE_ON :     { strncpy(V_Lub_Equip2_StateTxt, STATE_TEXT_SERVICE_ON,   sizeof(V_Lub_Equip2_StateTxt)); } break;
            case STATE_AUTO_ON :        { strncpy(V_Lub_Equip2_StateTxt, STATE_TEXT_AUTO_ON,      sizeof(V_Lub_Equip2_StateTxt)); } break;
            case STATE_AUTO_OFF :       { strncpy(V_Lub_Equip2_StateTxt, STATE_TEXT_AUTO_OFF,     sizeof(V_Lub_Equip2_StateTxt)); } break;
            case STATE_BLOCKED :        { strncpy(V_Lub_Equip2_StateTxt, STATE_TEXT_BLOCKED,      sizeof(V_Lub_Equip2_StateTxt)); } break;
            case STATE_SUSPENDED :      { strncpy(V_Lub_Equip2_StateTxt, STATE_TEXT_SUSPENDED,    sizeof(V_Lub_Equip2_StateTxt)); } break;
            default:                    { strncpy(V_Lub_Equip2_StateTxt, STATE_TEXT_UNDEFINED,    sizeof(V_Lub_Equip2_StateTxt)); } break;
        }
    }
    OldState = V_Lub_Equip2_State;
}

//______________________________________________________________________________________
static void WriteStatus(void)
{
static U8 OldStatus = 0xFF;

    if ( V_Lub_Equip2_Status != OldStatus )
    {
        switch(V_Lub_Equip2_Status)
        {
            case  YAW_LUB_STATUS_OK:            { strncpy(V_Lub_Equip2_StatusTxt, YAW_LUB_STATUS_OK_TEXT,          sizeof(V_Lub_Equip2_StatusTxt)); } break;
            case  YAW_LUB_STATUS_SAFETY:        { strncpy(V_Lub_Equip2_StatusTxt, YAW_LUB_STATUS_SAFETY_TEXT,      sizeof(V_Lub_Equip2_StatusTxt)); } break;
            case  YAW_LUB_STATUS_HW_ERROR:      { strncpy(V_Lub_Equip2_StatusTxt, YAW_LUB_STATUS_HW_ERROR_TEXT,    sizeof(V_Lub_Equip2_StatusTxt)); } break;
            case  YAW_LUB_STATUS_EMPTY:         { strncpy(V_Lub_Equip2_StatusTxt, YAW_LUB_STATUS_EMPTY_TEXT,       sizeof(V_Lub_Equip2_StatusTxt)); } break;
            case  YAW_LUB_STATUS_GRID_ERROR:    { strncpy(V_Lub_Equip2_StatusTxt, YAW_LUB_STATUS_GRID_ERROR_TEXT,  sizeof(V_Lub_Equip2_StatusTxt)); } break;
            case  YAW_LUB_STATUS_LVRT:          { strncpy(V_Lub_Equip2_StatusTxt, YAW_LUB_STATUS_LVRT_TEXT,        sizeof(V_Lub_Equip2_StatusTxt)); } break;
            case  YAW_LUB_STATUS_YP_ACTIVE:     { strncpy(V_Lub_Equip2_StatusTxt, YAW_LUB_STATUS_YP_ACTIVE_TEXT,   sizeof(V_Lub_Equip2_StatusTxt)); } break;
            case  YAW_LUB_STATUS_LM_BLOCK:      { strncpy(V_Lub_Equip2_StatusTxt, YAW_LUB_STATUS_LM_BLOCK_TEXT,    sizeof(V_Lub_Equip2_StatusTxt)); } break;
            case  YAW_LUB_STATUS_YAW_ACTIVITY:  { strncpy(V_Lub_Equip2_StatusTxt, YAW_LUB_STATUS_YAW_ACTIVITY_TEXT,sizeof(V_Lub_Equip2_StatusTxt)); } break;
            default:                            { strncpy(V_Lub_Equip2_StatusTxt, STATUS_TEXT_UNDEFINED,           sizeof(V_Lub_Equip2_StatusTxt)); } break;
        }
    }
    OldStatus = V_Lub_Equip2_Status;
}

//______________________________________________________________________________________
static STimer_t YawLubrication_OffTimer;
static STimer_t YawLubrication_UntwistOffTimer;
static STimer_t YawLubrication_LevelWarningTimer;
static STimer_t YawLubrication_FeedbackTimer;

//-----------------------------------------------------------------------
// SET/RESET FUNCTIONS    SET/RESET FUNCTIONS    SET/RESET FUNCTIONS
//-----------------------------------------------------------------------

static U8 StatusSetFunc769(void)
{// Yaw lubrica. err
static U8 FeedbackOldState = 0;
static U8 FeedbackType_old = 0;
static U8 FirstTime = 1;

    if( WPlineError() ) { return 0; }

    if(FeedbackType_old != P_LubricationYaw_FeedbackType )
    {
        FeedbackType_old = P_LubricationYaw_FeedbackType;
        if(LUB_ERROR_FB_TYPE_FREQUENCY == P_LubricationYaw_FeedbackType) { TimerReset(&YawLubrication_FeedbackTimer); }
    }

    switch( P_LubricationYaw_FeedbackType )
    {
    case LUB_ERROR_FB_TYPE_LOW_LEVEL:
        if( 0 == DI_LubricationYaw_PumpFault ) return 1;
        break;
    case LUB_ERROR_FB_TYPE_HIGH_LEVEL:
        if( 1 == DI_LubricationYaw_PumpFault ) return 1;
        break;
    case LUB_ERROR_FB_TYPE_FREQUENCY:
        if( !DO_LubricationYaw_Pump )
        {
			TimerReset(&YawLubrication_FeedbackTimer);
            return 0;
        }
        if( FirstTime )
        {
            FirstTime = 0;
            TimerReset(&YawLubrication_FeedbackTimer);
        }
        if( FeedbackOldState != DI_LubricationYaw_PumpFault )
        {
            FeedbackOldState = DI_LubricationYaw_PumpFault;
            TimerReset(&YawLubrication_FeedbackTimer);
        }
        if( TimerCheck(&YawLubrication_FeedbackTimer) )
		{
			TimerReset(&YawLubrication_FeedbackTimer);
			return 1;
		}
        break;
    default:
        return 1;
        break;
    }

    return 0;
}

//___________________________________________________________________________
static U8 StatusSetFunc787(void)
{ // Yaw lubrica. Warn
    if( WPlineError() ) { return 0; }

    return !DI_LubricationYaw_SystemLevelWarning;
}

static U8 StatusResetFunc787(void)
{ return !StatusSetFunc787(); }
//___________________________________________________________________________
static U8 StatusSetFunc788(void)
{ // Yaw lubr. empty
static U8 FirstTime = 1;
static U8 FeedbackOldValue = 0;

    if( WPlineError() ) { return 0; }

    if(FirstTime)
    {
        FirstTime = 0;
        FeedbackOldValue = DI_LubricationYaw_SystemLevelWarning;
        strncpy(V_LubricationYaw_OilTankEmptyTimeTxt, NA_TEXT, sizeof(V_LubricationYaw_OilTankEmptyTimeTxt));
        if( DI_LubricationYaw_SystemLevelWarning )
        {
            B_YawOilTankEmptyErrorTimer = 0;
        }
        else
        {
            if( B_YawOilTankEmptyErrorTimer )
            {
                TimerSet(&YawLubrication_LevelWarningTimer, B_YawOilTankEmptyErrorTimer);
                TimerStart(&YawLubrication_LevelWarningTimer);
            }
            else
            {
                TimerReset(&YawLubrication_LevelWarningTimer);
            }
        }
    }

    if( FeedbackOldValue != DI_LubricationYaw_SystemLevelWarning )
    {
        FeedbackOldValue = DI_LubricationYaw_SystemLevelWarning;
        strncpy(V_LubricationYaw_OilTankEmptyTimeTxt, NA_TEXT, sizeof(V_LubricationYaw_OilTankEmptyTimeTxt));

        if( !DI_LubricationYaw_SystemLevelWarning )
        {
            TimerReset(&YawLubrication_LevelWarningTimer);
        }
    }

    if ( !DI_LubricationYaw_SystemLevelWarning )
    {
        B_YawOilTankEmptyErrorTimer = TimerLeft(&YawLubrication_LevelWarningTimer);
        TimeToText(B_YawOilTankEmptyErrorTimer, V_LubricationYaw_OilTankEmptyTimeTxt, sizeof(V_LubricationYaw_OilTankEmptyTimeTxt));
        if (TimerCheck(&YawLubrication_LevelWarningTimer))
        {
            return 1;
        }
    }

    return 0;
}

//-----------------------------------------------------------------------
// DRIVER FUNCTION         DRIVER FUNCTION         DRIVER FUNCTION
//-----------------------------------------------------------------------
enum { STOP_CYCLE, START_CYCLE };
typedef struct
{
    U8 cycle;
    U8 old_data;
    U8 state;
}cycle_t;

static void StartCycle(cycle_t *a)
{
    a->state = START_CYCLE;
}
static void StopCycle(cycle_t *a)
{
    a->state = STOP_CYCLE;
}
static void ResetCycle(cycle_t *a, U8 data)
{
    a->old_data = data;
    a->cycle = 0;
    a->state = STOP_CYCLE;
}
static U8 WaitCycle(U8 data, U8 cycle_req, cycle_t *a)
{
    if( STOP_CYCLE == a->state )
    {
        return 0;
    }

    if(data != a->old_data)
    {
        a->cycle++;
        a->old_data = data;
    }

    return (cycle_req == ((a->cycle)/2));
}
//-----------------------------------------------------------------------
// INIT                   INIT                     INIT
//-----------------------------------------------------------------------
static cycle_t LubricationY_StrokeCtrl;
//-----------------------------------------------------------------------
// CONTROL                CONTROL                 CONTROL
//-----------------------------------------------------------------------

struct EventTextStruct EventText_Ex_Yaw_LUB_NUMBER_MODE      = {0, NULL};
struct EventTextStruct EventText_Ex_Yaw_LUB_NUMBER_TYPE      = {0, NULL};
struct EventTextStruct EventText_Ex_Yaw_LUB_LOST_MODE        = {0, NULL};

static STATUS CreateEventNumbers(void)
{
    STATUS LocalStatus = OS_SUCCESS;

    LocalStatus += GetEventNumber(&EventText_Ex_Yaw_LUB_NUMBER_MODE      , "Lubr.Yaw.Parameter > Modes");
    LocalStatus += GetEventNumber(&EventText_Ex_Yaw_LUB_NUMBER_TYPE      , "Lubr.Yaw.Parameter > Ctrl.Mode");
    LocalStatus += GetEventNumber(&EventText_Ex_Yaw_LUB_LOST_MODE        , "Lubr.Yaw. Lost Mode");

    STATUS_LINE_VAR(LocalStatus)
    return LocalStatus;
}

typedef enum
{
    Ex_YAW_LUB_OK,
    Ex_YAW_LUB_NUMBER_MODE,          // = 1
    Ex_YAW_LUB_NUMBER_TYPE,          // = 2
    Ex_YAW_LUB_LOST_MODE,            // = 3
    Ex_YAW_LUB_MAX
} Ex_Yaw_Lubrication;

static int YawLubrication_ExceptionLast = 0;

//______________________________________________________________________________________
void YawLubrication_Exception(Ex_Yaw_Lubrication exception)
{
    if( exception != YawLubrication_ExceptionLast )
    {
        switch(exception)
        {
            case Ex_YAW_LUB_NUMBER_MODE      :    UserEvent(    EventText_Ex_Yaw_LUB_NUMBER_MODE      );    break;
            case Ex_YAW_LUB_NUMBER_TYPE      :    UserEvent(    EventText_Ex_Yaw_LUB_NUMBER_TYPE      );    break;
            case Ex_YAW_LUB_LOST_MODE        :    UserEvent(    EventText_Ex_Yaw_LUB_LOST_MODE        );    break;
            default:;
        }
        YawLubrication_ExceptionLast = exception;

        if( V_FirstExceptionYawBearing == Ex_YAW_LUB_OK )    { V_FirstExceptionYawBearing = exception; }
        else
        {
            if(exception == Ex_YAW_LUB_OK) { V_FirstExceptionYawBearing = Ex_YAW_LUB_OK; }
        }
    }
}

static void AssignParameters (void)
{
    if ( ParametersChanged[GENERAL_GROUP] )
    {
        YawLubrication_OffTimer.P_Time           = P_LubricationYaw_PumpOffTime;
        YawLubrication_LevelWarningTimer.P_Time  = P_LubricationYaw_LevelLowOnTime;
        YawLubrication_FeedbackTimer.P_Time      = P_LubricationYaw_FeedbackTime;
        YawLubrication_UntwistOffTimer.P_Time    = P_LubricationYaw_PumpOffTimeUnwind;

        ParametersChanged[GENERAL_GROUP] = 0;
    }
}
//___________________________________________________________________________
static U8 BlockYawLubrication(void)
{
    if      ( StatusCodeActive(10) )                { V_Lub_Equip2_Status = YAW_LUB_STATUS_SAFETY; }
    else if ( StatusCodeActive(769) )               { V_Lub_Equip2_Status = YAW_LUB_STATUS_HW_ERROR; }
    else if ( StatusCodeActive(788) )               { V_Lub_Equip2_Status = YAW_LUB_STATUS_EMPTY; }
    else if ( V_Grid_ErrorActive )                  { V_Lub_Equip2_Status = YAW_LUB_STATUS_GRID_ERROR; }
    else if ( V_YAW_State == YAW_LUB_YAW_ERROR )   { V_Lub_Equip2_Status = YAW_LUB_STATUS_YP_ACTIVE; }
    else                                            { V_Lub_Equip2_Status = YAW_LUB_STATUS_OK; }

    return V_Lub_Equip2_Status;
}
//_________________________________________________________________________________
static void TimeToText(U64 Time, char *Text, U8 size)
{
    Time = Time / 1000; //  result in seconds
    if(Time > 3600)
    {
        sprintf( Text, "%u h, %d min",
                 (U32)(Time / 3600), (U32)((Time % 3600) / 60));
    }
    else if((Time < 3600) && (Time > 60))
    {
        snprintf( Text, size, "%u min, %u sec",
                  (U32)(Time / 60), (U32)(Time % 60));
    }
    else if(Time < 60)
    {
        snprintf(Text, size, "%u sec", (U32)Time);
    }
}
//________________________________________________________________________________________
void YawLubricationPeriodicExtraCtrl(U8 NewModeFlag)
{
static U8 FirstTime = 1;
static U8 State = YAW_LUB_AUTO_OFF;
static U8 V_YawCommand_Start;

    if( FirstTime )
    {
        FirstTime = 0;
        State = YAW_LUB_AUTO_OFF;
        if( (B_YawLubricationTimer > 0) && (B_YawLubricationTimer < P_LubricationYaw_PumpOffTime) )
        {
            TimerSet(&YawLubrication_OffTimer, B_YawLubricationTimer);
            TimerStart(&YawLubrication_OffTimer);
        }
        else
        {
            TimerReset(&YawLubrication_OffTimer);
        }
    }

    if( NewModeFlag )
    {
        TimerReset(&YawLubrication_OffTimer);
        State = YAW_LUB_AUTO_OFF;
    }

    if( BlockYawLubrication() )
    {
        DO_LubricationYaw_Pump = YAW_LUB_PUMP_OFF;
        strncpy(V_LubricationYaw_TimeIndicationTxt, NA_TEXT, sizeof(V_LubricationYaw_TimeIndicationTxt));
        V_Lub_Equip2_State = STATE_BLOCKED;
        State = YAW_LUB_AUTO_OFF;
    }
    else
    {
        switch( State )
        {
        case YAW_LUB_AUTO_OFF:
            DO_LubricationYaw_Pump = YAW_LUB_PUMP_OFF;
            V_Lub_Equip2_State = STATE_AUTO_OFF;
            if( (( YAW_LUB_YAW_UNWIND_CW == V_YAW_State ) || ( YAW_LUB_YAW_UNWIND_CCW == V_YAW_State )) &&
                ( MANAGER_MODE_ENABLE == V_Lub_Equip2_Mode ) )
            {
                ResetCycle(&LubricationY_StrokeCtrl, DI_LubricationYaw_PumpFault);
				StartCycle(&LubricationY_StrokeCtrl);

                TimerReset(&YawLubrication_UntwistOffTimer);
                B_YawLubricationTimer = 0;

                V_YawCommand_Start = V_YAW_State;          //  to remember should it be lubrication during unwinding or just one-time on.
                DO_LubricationYaw_Pump = YAW_LUB_PUMP_ON;
                State = YAW_LUB_AUTO_ON;
            }
            if( TimerCheck(&YawLubrication_OffTimer) )
            {
                B_YawLubricationTimer = 0;
                if( (( YAW_LUB_YAW_RUN_CW == V_YAW_State ) || ( YAW_LUB_YAW_RUN_CCW == V_YAW_State )) &&
                    ( MANAGER_MODE_ENABLE == V_Lub_Equip2_Mode ) )
                {
                    ResetCycle(&LubricationY_StrokeCtrl, DI_LubricationYaw_PumpFault);
                    StartCycle(&LubricationY_StrokeCtrl);

                    V_YawCommand_Start = V_YAW_State;      //  to remember should it be lubrication during unwinding or just one-time on.
                    State = YAW_LUB_AUTO_ON;
                }
                else
                {
                    StopCycle(&LubricationY_StrokeCtrl);

                    DO_LubricationYaw_Pump = YAW_LUB_PUMP_OFF;
                    State = YAW_LUB_SUSPENDED;
                }
            }
            else
            {
                TimeToText(TimerLeft(&YawLubrication_OffTimer), V_LubricationYaw_TimeIndicationTxt, sizeof(V_LubricationYaw_TimeIndicationTxt));
                B_YawLubricationTimer = TimerLeft(&YawLubrication_OffTimer);  //  Backup timer
            }
            break;

        case YAW_LUB_SUSPENDED:
            DO_LubricationYaw_Pump = YAW_LUB_PUMP_OFF;
            V_Lub_Equip2_State = STATE_SUSPENDED;

            strncpy(V_LubricationYaw_TimeIndicationTxt, NA_TEXT, sizeof(V_LubricationYaw_TimeIndicationTxt));

            if( ( MANAGER_MODE_ENABLE == V_Lub_Equip2_Mode ) && ( 0 == V_Inverter_StatusLVRT ) &&
                ( ( YAW_LUB_YAW_UNWIND_CW == V_YAW_State ) || ( YAW_LUB_YAW_UNWIND_CCW == V_YAW_State ) ||
                  ( YAW_LUB_YAW_RUN_CW == V_YAW_State ) || ( YAW_LUB_YAW_RUN_CCW == V_YAW_State ) ) )
            {
                StartCycle(&LubricationY_StrokeCtrl);

                TimerStart(&YawLubrication_UntwistOffTimer);

                V_YawCommand_Start = V_YAW_State;      //  to remember should it be lubrication during unwinding or just one-time on.

                DO_LubricationYaw_Pump = YAW_LUB_PUMP_ON;
                State = YAW_LUB_AUTO_ON;
            }
            if ( V_Inverter_StatusLVRT )                                                { V_Lub_Equip2_Status = YAW_LUB_STATUS_LVRT; }
            else if( MANAGER_MODE_DISABLE == V_Lub_Equip2_Mode )                              { V_Lub_Equip2_Status = YAW_LUB_STATUS_LM_BLOCK; }
            else if( ( YAW_LUB_YAW_UNWIND_CW != V_YAW_State ) &&
                     ( YAW_LUB_YAW_UNWIND_CCW != V_YAW_State ) &&
                     ( YAW_LUB_YAW_RUN_CW != V_YAW_State ) &&
                     ( YAW_LUB_YAW_RUN_CCW != V_YAW_State ) )                          { V_Lub_Equip2_Status = YAW_LUB_STATUS_YAW_ACTIVITY; }
            else                                                                        { V_Lub_Equip2_Status = YAW_LUB_STATUS_OK; }

            break;

        case YAW_LUB_AUTO_ON:
            if( ( YAW_LUB_YAW_UNWIND_CW == V_YawCommand_Start ) || ( YAW_LUB_YAW_UNWIND_CCW == V_YawCommand_Start ) )   //  Yaw Unwind procedure is active
            {
                if( ( YAW_LUB_YAW_UNWIND_CW != V_YAW_State ) && ( YAW_LUB_YAW_UNWIND_CCW != V_YAW_State ) )   //  return if Unwind procedure is not active any more
                {
                    TimerReset(&YawLubrication_OffTimer);

                    DO_LubricationYaw_Pump = YAW_LUB_PUMP_OFF;
                    State = YAW_LUB_AUTO_OFF;
                }
                else        //  Unwind is still running
                {
                    if(( MANAGER_MODE_DISABLE == V_Lub_Equip2_Mode) || V_Inverter_StatusLVRT)     //  Pump must be turned off immediately
                    {
                        if( YAW_LUB_PUMP_OFF == DO_LubricationYaw_Pump ) { TimerStop(&YawLubrication_UntwistOffTimer); }

                        StopCycle(&LubricationY_StrokeCtrl);

                        DO_LubricationYaw_Pump = YAW_LUB_PUMP_OFF;
                        State = YAW_LUB_SUSPENDED;
                    }
                    else        //  turn pump On/Off periodically
                    {
                        if( YAW_LUB_PUMP_ON == DO_LubricationYaw_Pump )
                        {
                            V_Lub_Equip2_State = STATE_AUTO_ON;
                            if( WaitCycle(DI_LubricationYaw_PumpFault, P_LubricationYawUnwinding_Stroke_ON, &LubricationY_StrokeCtrl) )
                            {
                                TimerReset(&YawLubrication_UntwistOffTimer);
                                TimerStart(&YawLubrication_UntwistOffTimer);

                                DO_LubricationYaw_Pump = YAW_LUB_PUMP_OFF;
                            }
                        }
                        else
                        {
                            V_Lub_Equip2_State = STATE_AUTO_OFF;
                            TimeToText(TimerLeft(&YawLubrication_UntwistOffTimer), V_LubricationYaw_TimeIndicationTxt, sizeof(V_LubricationYaw_TimeIndicationTxt));
                            if(TimerCheck(&YawLubrication_UntwistOffTimer))
                            {
                                ResetCycle(&LubricationY_StrokeCtrl, DI_LubricationYaw_PumpFault);
                                StartCycle(&LubricationY_StrokeCtrl);

                                DO_LubricationYaw_Pump = YAW_LUB_PUMP_ON;
                            }
                        }
                    }
                }
            }
            else            //  Normal Yaw run is active (or was active when entered this state)
            {
                V_Lub_Equip2_State = STATE_AUTO_ON;
                //  switch to unwinding mode if it started during normal yawing or just after return from suspended state
                if( (( YAW_LUB_YAW_UNWIND_CW == V_YAW_State ) || ( YAW_LUB_YAW_UNWIND_CCW == V_YAW_State )) &&
                    ( MANAGER_MODE_ENABLE == V_Lub_Equip2_Mode ) )
                {
                    ResetCycle(&LubricationY_StrokeCtrl, DI_LubricationYaw_PumpFault);
                    StartCycle(&LubricationY_StrokeCtrl);

                    TimerReset(&YawLubrication_UntwistOffTimer);
                    B_YawLubricationTimer = 0;
                    V_YawCommand_Start = V_YAW_State;          //  to remember should it be lubrication during unwinding or just one-time on.
                    DO_LubricationYaw_Pump = YAW_LUB_PUMP_ON;
                    State = YAW_LUB_AUTO_ON;
                }
                //  lubrication during normal yawing
                if( WaitCycle(DI_LubricationYaw_PumpFault, P_LubricationYaw_Stroke_ON, &LubricationY_StrokeCtrl) )
                {
                    TimerReset(&YawLubrication_OffTimer);
                    State = YAW_LUB_AUTO_OFF;
                }
                else
                {
                    if(( MANAGER_MODE_DISABLE == V_Lub_Equip2_Mode) || V_Inverter_StatusLVRT)
                    {
                        DO_LubricationYaw_Pump = YAW_LUB_PUMP_OFF;
                        StopCycle(&LubricationY_StrokeCtrl);
                        State = YAW_LUB_SUSPENDED;
                    }
                    else
                    {
                        DO_LubricationYaw_Pump = YAW_LUB_PUMP_ON;
                    }
                }
            }
            break;

        default:
            YawLubrication_Exception(Ex_YAW_LUB_LOST_MODE);
            DO_LubricationYaw_Pump = YAW_LUB_PUMP_OFF;
            break;
        }
    }
}
//________________________________________________________________________________________
void YawLubricationPeriodicSimple(U8 NewModeFlag)
{
static U8 FirstTime = 1;
static U8 State = YAW_LUB_AUTO_OFF;

    if( FirstTime )
    {
        FirstTime = 0;
        State = YAW_LUB_AUTO_OFF;
        if( (B_YawLubricationTimer > 0) && (B_YawLubricationTimer < P_LubricationYaw_PumpOffTime) )
        {
            TimerSet(&YawLubrication_OffTimer, B_YawLubricationTimer);
            TimerStart(&YawLubrication_OffTimer);
        }
        else
        {
            TimerReset(&YawLubrication_OffTimer);
        }
    }

    if( NewModeFlag )
    {
        TimerReset(&YawLubrication_OffTimer);
        State = YAW_LUB_AUTO_OFF;
    }

    if( BlockYawLubrication() )
    {
        DO_LubricationYaw_Pump = YAW_LUB_PUMP_OFF;
        strncpy(V_LubricationYaw_TimeIndicationTxt, NA_TEXT, sizeof(V_LubricationYaw_TimeIndicationTxt));
        if( YAW_LUB_AUTO_ON == State ) { StopCycle(&LubricationY_StrokeCtrl); }
        V_Lub_Equip2_State = STATE_BLOCKED;
        State = YAW_LUB_AUTO_OFF;
    }
    else
    {
        switch( State )
        {
        case YAW_LUB_AUTO_OFF:
            DO_LubricationYaw_Pump = YAW_LUB_PUMP_OFF;
            V_Lub_Equip2_State = STATE_AUTO_OFF;
            if( TimerCheck(&YawLubrication_OffTimer) )
            {
                B_YawLubricationTimer = 0;
                if( MANAGER_MODE_ENABLE == V_Lub_Equip2_Mode )
                {
                    ResetCycle(&LubricationY_StrokeCtrl, DI_LubricationYaw_PumpFault);
                    StartCycle(&LubricationY_StrokeCtrl);

                    State = YAW_LUB_AUTO_ON;
                }
                else
                {
                    StopCycle(&LubricationY_StrokeCtrl);
                    State = YAW_LUB_SUSPENDED;
                }
            }
            else
            {
                TimeToText(TimerLeft(&YawLubrication_OffTimer), V_LubricationYaw_TimeIndicationTxt, sizeof(V_LubricationYaw_TimeIndicationTxt));
                B_YawLubricationTimer = TimerLeft(&YawLubrication_OffTimer);  //  Backup timer
            }
            break;

        case YAW_LUB_SUSPENDED:
            DO_LubricationYaw_Pump = YAW_LUB_PUMP_OFF;
            V_Lub_Equip2_State = STATE_SUSPENDED;
            strncpy(V_LubricationYaw_TimeIndicationTxt, NA_TEXT, sizeof(V_LubricationYaw_TimeIndicationTxt));
            if( (MANAGER_MODE_ENABLE == V_Lub_Equip2_Mode) && (0 == V_Inverter_StatusLVRT) )
            {
                StartCycle(&LubricationY_StrokeCtrl);
                State = YAW_LUB_AUTO_ON;
            }
            if ( V_Inverter_StatusLVRT )                                                { V_Lub_Equip2_Status = YAW_LUB_STATUS_LVRT; }
            else if (MANAGER_MODE_DISABLE == V_Lub_Equip2_Mode)                               { V_Lub_Equip2_Status = YAW_LUB_STATUS_LM_BLOCK; }
            else                                                                        { V_Lub_Equip2_Status = YAW_LUB_STATUS_OK; }

            break;

        case YAW_LUB_AUTO_ON:
            DO_LubricationYaw_Pump = YAW_LUB_PUMP_ON;
            V_Lub_Equip2_State = STATE_AUTO_ON;

            if( WaitCycle(DI_LubricationYaw_PumpFault, P_LubricationYaw_Stroke_ON, &LubricationY_StrokeCtrl) )
            {
                TimerReset(&YawLubrication_OffTimer);
                State = YAW_LUB_AUTO_OFF;
            }
            else if(( MANAGER_MODE_DISABLE == V_Lub_Equip2_Mode) || V_Inverter_StatusLVRT)
            {
                DO_LubricationYaw_Pump = YAW_LUB_PUMP_OFF;
                StopCycle(&LubricationY_StrokeCtrl);
                State = YAW_LUB_SUSPENDED;
            }

            break;

        default:
            YawLubrication_Exception(Ex_YAW_LUB_LOST_MODE);
            DO_LubricationYaw_Pump = YAW_LUB_PUMP_OFF;
            break;
        }
    }
}
//________________________________________________________________________________________
void YawLubricationAlwaysOn(U8 NewModeFlag)
{
static U8 FirstTime = 1;
static U8 State = YAW_LUB_SUSPENDED;     //  Do not turn pump ON initially before check for block or suspend conditions

    if( FirstTime || NewModeFlag)
    {
        FirstTime = 0;
        State = YAW_LUB_SUSPENDED;
        strncpy(V_LubricationYaw_TimeIndicationTxt, NA_TEXT, sizeof(V_LubricationYaw_TimeIndicationTxt));
    }

    if( BlockYawLubrication() )
    {
        DO_LubricationYaw_Pump = YAW_LUB_PUMP_OFF;
        V_Lub_Equip2_State = STATE_BLOCKED;
    }
    else
    {
        switch( State )
        {
        case YAW_LUB_AUTO_OFF:
        case YAW_LUB_SUSPENDED:
            DO_LubricationYaw_Pump = YAW_LUB_PUMP_OFF;
            V_Lub_Equip2_State = STATE_SUSPENDED;
            if( (MANAGER_MODE_ENABLE == V_Lub_Equip2_Mode) && (0 == V_Inverter_StatusLVRT) )
            {
                State = YAW_LUB_AUTO_ON;
            }
            if ( V_Inverter_StatusLVRT )                                                { V_Lub_Equip2_Status = YAW_LUB_STATUS_LVRT; }
            else if (MANAGER_MODE_DISABLE == V_Lub_Equip2_Mode)                               { V_Lub_Equip2_Status = YAW_LUB_STATUS_LM_BLOCK; }
            else                                                                        { V_Lub_Equip2_Status = YAW_LUB_STATUS_OK; }

            break;

        case YAW_LUB_AUTO_ON:
            V_Lub_Equip2_State = STATE_AUTO_ON;
            if(( MANAGER_MODE_DISABLE == V_Lub_Equip2_Mode) || V_Inverter_StatusLVRT)
            {
                DO_LubricationYaw_Pump = YAW_LUB_PUMP_OFF;
                State = YAW_LUB_SUSPENDED;
            }
            else
            {
                DO_LubricationYaw_Pump = YAW_LUB_PUMP_ON;
            }
            break;
        default:
            YawLubrication_Exception(Ex_YAW_LUB_LOST_MODE);
            DO_LubricationYaw_Pump = YAW_LUB_PUMP_OFF;
            break;
        }
    }
}
//________________________________________________________________________________________

void YawLubricationAutoCtrl(U8 ServiceModeChanged)
{
static U8 InternalModeOldValue = 0;
static U8 FirstTime = 1;
U8 NewModeFlag = 0;

    if(FirstTime)
    {
        FirstTime = 0;
        InternalModeOldValue = P_LubricationYaw_InternalMode;
    }
    if(InternalModeOldValue != P_LubricationYaw_InternalMode)
    {
        InternalModeOldValue = P_LubricationYaw_InternalMode;
        NewModeFlag = 1;
    }
    if( ServiceModeChanged ) { NewModeFlag = 1; }

    switch( P_LubricationYaw_InternalMode )
    {
    case LUB_MODE_PERIODIC_EXTRA_CTRL:
        YawLubricationPeriodicExtraCtrl(NewModeFlag);
        break;
    case LUB_MODE_PERIODIC_SIMPLE:
        YawLubricationPeriodicSimple(NewModeFlag);
        break;
    case LUB_MODE_ALWAYS_ON:
        YawLubricationAlwaysOn(NewModeFlag);
        break;
    default:
        DO_LubricationYaw_Pump = YAW_LUB_PUMP_OFF;
        strncpy(V_LubricationYaw_TimeIndicationTxt, NA_TEXT, sizeof(V_LubricationYaw_TimeIndicationTxt));
        YawLubrication_Exception(Ex_YAW_LUB_NUMBER_TYPE);
        V_Lub_Equip2_State = STATE_AUTO_OFF;
        break;
    }
}

//________________________________________________________________________________________
static STATUS LocalCtrl(void)
{
    STATUS LocalStatus = 0;
    static U8 FirstTime = 1;
    U8 ServiceModeChanged = 0;
    static U8 P_LubricationYaw_ServiceCtrl_old;


    if(FirstTime)
    {
        AssignParameters();
        FirstTime = 0;
        strncpy(V_LubricationYaw_TimeIndicationTxt, NA_TEXT, sizeof(V_LubricationYaw_TimeIndicationTxt));
        P_LubricationYaw_ServiceCtrl_old = P_LubricationYaw_ServiceCtrl;
    }

    if(P_LubricationYaw_ServiceCtrl_old != P_LubricationYaw_ServiceCtrl)
    {
        P_LubricationYaw_ServiceCtrl_old = P_LubricationYaw_ServiceCtrl;
        ServiceModeChanged = 1;
    }

    if( BlockYawLubrication() ) { V_Lub_Equip2_State = STATE_BLOCKED; }        //Retrieve Status

    switch( P_LubricationYaw_ServiceCtrl )
    {
        case MODE_AUTO :
            YawLubricationAutoCtrl(ServiceModeChanged);
            break;

        case MODE_SERVICE_OFF :
            DO_LubricationYaw_Pump = YAW_LUB_PUMP_OFF;
            V_Lub_Equip2_State = STATE_SERVICE_OFF;
            V_Lub_Equip2_Status = YAW_LUB_STATUS_OK;
            strncpy(V_LubricationYaw_TimeIndicationTxt, NA_TEXT, sizeof(V_LubricationYaw_TimeIndicationTxt));
            break;

        case MODE_SERVICE_ON :
            DO_LubricationYaw_Pump = YAW_LUB_PUMP_ON;
            V_Lub_Equip2_State = STATE_SERVICE_ON;
            V_Lub_Equip2_Status = YAW_LUB_STATUS_OK;
            strncpy(V_LubricationYaw_TimeIndicationTxt, NA_TEXT, sizeof(V_LubricationYaw_TimeIndicationTxt));
            break;

        default:
            DO_LubricationYaw_Pump = YAW_LUB_PUMP_OFF;
            YawLubrication_Exception(Ex_YAW_LUB_NUMBER_MODE);
            V_Lub_Equip2_State = STATE_SERVICE_OFF;
            V_Lub_Equip2_Status = YAW_LUB_STATUS_OK;
            strncpy(V_LubricationYaw_TimeIndicationTxt, NA_TEXT, sizeof(V_LubricationYaw_TimeIndicationTxt));
            break;
    }

    AssignParameters();

    // update object State and Status and write to VDB if updated
    WriteState();
    WriteStatus();

   return LocalStatus;
}

//-----------------------------------------------------------------------
// MAIN CALL             MAIN CALL               MAIN CALL
//-----------------------------------------------------------------------

STATUS LubricationYaw_MT_Type1(U8 ModuleState, OS_MEMORY_POOL *MemPool, U32 *Arg3)
{
   STATUS LocalStatus = 0;

   // Version check
   if(ModuleState == APP_INIT1)
   {
      LocalStatus = OS_ValidateAPI(API_VERSION_MAJOR,
                                   API_VERSION_MINOR,
                                   OS_LinkTime,
                                   ReleaseTag,
                                   __MODULE__
                                   );
      if ( OS_SUCCESS != LocalStatus )
      {
         return LocalStatus;
      }
   }
#ifdef READ_VARS
   // Read inputdata
   LocalStatus = InputReferenceRoutine(ModuleState);
   STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif
#ifdef COMMON_VDB_READ
   LocalStatus = ReadVdbWindow(ModuleState);
   STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif
   switch(ModuleState)
   {
      case APP_RUN :
      {
         #ifdef FUNCTION_BLOCKS_PRE_LOCAL_CONTROL
            LocalStatus = FunctionBlocksPreLocalCtrl( Interval );
            STATUS_LINE_VAR_RETURN_VALUE( LocalStatus );
         #endif

         LocalStatus = LocalCtrl();
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
        
         #ifdef FUNCTION_BLOCKS_POST_LOCAL_CONTROL
            LocalStatus = FunctionBlocksPostLocalCtrl( Interval );
            STATUS_LINE_VAR_RETURN_VALUE( LocalStatus );
         #endif

#ifdef WRITE_VARS
         // Write Outputdata
         LocalStatus = OutputReferenceRoutine(ModuleState);
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif

#ifdef COMMON_VDB_WRITE
         LocalStatus = WriteVdbWindow(ModuleState);
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif
         break;
      }
      case APP_INIT1 :
      {
         Init_Structures_From_Conf_File();

#ifdef CREATE_VARDB_VARS
         LocalStatus = CreateVarDbVars();
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)

         LocalStatus = CreateEventNumbers();
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif

#ifdef CREATE_MENU
         LocalStatus = LubricationYaw_MT_Type1MenuAppInit(ModuleState, MemPool);
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)

#ifdef MULTIPLEXIBLE_MENU
         LocalStatus = MenuArraysAppInit(ModuleState, MemPool);
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif
#endif

#ifdef CREATE_VARDB_ARRAY_VARS
         LocalStatus = CreateVdbArrays(MemPool);
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif

#ifdef CREATE_IO_VARS
         LocalStatus = CreateIOVars();
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif
         break;
      }
      case APP_INIT2 :
      {
#ifdef CREATE_MENU
#ifdef MULTIPLEXIBLE_MENU
         LocalStatus = MenuArraysAppInit(ModuleState, MemPool);
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif
#endif

#ifdef CREATE_ALIASES
         size_t ErrorEntry = 0;
         LocalStatus = OS_VarDB_CreateAliases(AliasVars, sizeof(AliasVars)/sizeof(AliasVars[0]), &ErrorEntry);
         STATUS_LINE_VAR_RETURN_CONST(LocalStatus, ErrorEntry)
#endif

#ifdef VERIFY_ARRAY
        LocalStatus = VerifyArray(MemPool);
        STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif

#ifdef VERIFY_VARIABLES
         LocalStatus = LocalIoCheck();
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif

#ifdef CREATE_BUTTONS
         LocalStatus = CreateButtons();
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif
         break;
      }
      case APP_INIT3 :
      {
#ifdef CREATE_SUMMATIONS
         LocalStatus = CreateSummations();
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif

#ifdef WRITE_VARS
         LocalStatus = InitOutputVars();
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif

#ifdef CREATE_STATUS_CODES
         LocalStatus = LocalStatusCodeInit();
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif

#ifdef CREATE_IO_VARS
        LubricationYaw_MT_Type1SetLockValues();
#endif
         break;
      }
      case APP_INIT4 :
      {
#ifdef CREATE_MENU
         LocalStatus = LubricationYaw_MT_Type1MenuAppInit(ModuleState, MemPool);
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)

#ifdef MULTIPLEXIBLE_MENU
         LocalStatus = MenuArraysAppInit(ModuleState, MemPool);
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif
#endif
         break;
      }
      case APP_INIT5 :
      {
#ifdef VALIDATE_HASH
         LocalStatus = ValidateHash(LubricationYaw_MT_Type1_copyright, MODULE_NAME, LubricationYaw_MT_Type1_initialValues);
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif

         #ifdef INIT_FUNCTION_BLOCKS
            LocalStatus = FunctionBlocksInit( Interval );
            STATUS_LINE_VAR_RETURN_VALUE( LocalStatus );
         #endif

         break;
      }
      default :
      {
         break;
      }
   }
   return OS_SUCCESS;
}
//-----------------------------------------------------------------------
