//*****************************PEPTOOL Header Start******************************
//                                                                               
//                         Copyright © 2015 Mita-Teknik.                         
//This software may only be used with WP4x00 Controllers delivered by Mita-Teknik
//                                                                               
//*******************************************************************************
//                                                                               
// $PEPTOOL version:9.0$                                                         
// $PEPTOOL file version:106$                                                    
//                                                                               
//*******************************************************************************
//                                                                               
// $Date: 2014/03/04 14:27:19 $                                                  
// $Author: MITA\ihn $                                                           
// $RCSfile: Lubrication_MT_Type1.c,v $                                          
// $Revision: 1.3 $                                                              
//                                                                               
//******************************PEPTOOL Header End*******************************

//***********************************************************************

// OS header files
#include <os_main.h>
// AppLib header files
#include <lib_main.h>
// App header files
#include <turbdef.h>
#include <VarMacros.h>

// Object header file
#include <Lubrication_MT_Type1.h>

#define AUTOGENERATED_PART
//{
//-----------------------------------------------------------------------
// AUTOGENERATED START     AUTOGENERATED START     AUTOGENERATED START
//-----------------------------------------------------------------------

#define VALIDATE_HASH
char Lubrication_MT_Type1_copyright[] =
{
   67, 111, 112, 121, 114, 105, 103, 104, 116, 32, 63, 32, 50, 48, 49, 53,
   32, 77, 105, 116, 97, 45, 84, 101, 107, 110, 105, 107, 46, 13, 10, 84,
   104, 105, 115, 32, 115, 111, 102, 116, 119, 97, 114, 101, 32, 109, 97, 121,
   32, 111, 110, 108, 121, 32, 98, 101, 32, 117, 115, 101, 100, 32, 119, 105,
   116, 104, 32, 87, 80, 52, 120, 48, 48, 32, 67, 111, 110, 116, 114, 111,
   108, 108, 101, 114, 115, 32, 100, 101, 108, 105, 118, 101, 114, 101, 100, 32,
   98, 121, 32, 77, 105, 116, 97, 45, 84, 101, 107, 110, 105, 107, 0
};

#define MODULE_NAME "LubricationA"

//-----------------------------------------------------------------------
// ALLOCATE MEMORY FOR STRINGS IN VARDB
//-----------------------------------------------------------------------


//-----------------------------------------------------------------------
// DEFINE LOCAL VARIABLES DEFINE LOCAL VARIABLES DEFINE LOCAL VARIABLES
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// DEFINE PARAMETERS        DEFINE PARAMETERS        DEFINE PARAMETERS
//-----------------------------------------------------------------------

static struct os_db_parameter ParameterVars[] =
{
   VAR_ELEMENT_PARAMETER("P_Lub_Equip0_ForcedMode",                  TYPE_U8,      PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_SERVICE,            SCALE_NONE,   0,       UNIT_NONE,          0,   0,               0,               2,               NULL  ),
   VAR_ELEMENT_PARAMETER("P_Lub_Equip1_ForcedMode",                  TYPE_U8,      PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_SERVICE,            SCALE_NONE,   0,       UNIT_NONE,          0,   0,               0,               2,               NULL  ),
   VAR_ELEMENT_PARAMETER("P_Lub_Equip2_ForcedMode",                  TYPE_U8,      PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_SERVICE,            SCALE_NONE,   0,       UNIT_NONE,          0,   0,               0,               2,               NULL  ),
};

//-----------------------------------------------------------------------
// DEFINE BACKUPS            DEFINE BACKUPS            DEFINE BACKUPS
//-----------------------------------------------------------------------

//----------------------------------------------------------------------------------
// DEFINE VAR ARRAYS            DEFINE VAR ARRAYS            DEFINE VAR ARRAYS
//----------------------------------------------------------------------------------
char Lubrication_MT_Type1_initialValues[] =
{
   114, 26, 199, 71, 111, 156, 116, 5, 126, 117, 76, 75, 10, 191, 93, 88,
   44, 211, 94, 125, 218, 27, 201, 102, 52, 72, 98, 84, 214, 229, 95, 34,
   0
};

//-----------------------------------------------------------------------
// CREATE DATABASE VARS   CREATE DATABASE VARS   CREATE DATABASE VARS
//-----------------------------------------------------------------------

static STATUS CreateVarDbVars(void)
{
   STATUS Status;
   size_t ErrorEntry;

   Status = OS_VarDB_CreateParameters(ParameterVars, sizeof(ParameterVars)/sizeof(ParameterVars[0]), &ErrorEntry, AppExportParameterPosition());
   if (Status != 0)
   {
      AppSystemLog(ERR_7, MODULE_NAME"CrVXP: %d,%d", Status, ErrorEntry);
      return ERR_7;
   }

   return OS_SUCCESS;
}

#define CREATE_VARDB_VARS

//-----------------------------------------------------------------------
// CREATE IO VARIABLES     CREATE IO VARIABLES     CREATE IO VARIABLES
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// ALIASES                       ALIASES                       ALIASES
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// INPUT                          INPUT                          INPUT
//-----------------------------------------------------------------------

// Create local variable
#define MODUL_INPUTS
static S32 V_Lub_Equip0_State = 0;
static S32 V_Lub_Equip1_State = 0;
static S32 V_Lub_Equip2_State = 0;

//-----------------------------------------------------------------------
static struct ModulInOut ModulInputs[] =
{
   {"V_Lub_Equip0_State",                       &V_Lub_Equip0_State,                       sizeof(V_Lub_Equip0_State),                       },
   {"V_Lub_Equip1_State",                       &V_Lub_Equip1_State,                       sizeof(V_Lub_Equip1_State),                       },
   {"V_Lub_Equip2_State",                       &V_Lub_Equip2_State,                       sizeof(V_Lub_Equip2_State),                       },
};

//-----------------------------------------------------------------------
// Check variable type
static STATUS VarsReadReturnStatus;
static type_t ReadVarType = TYPE_NONE;
static void VarsReadTypeCheck(void)
{
   (void)VarsReadReturnStatus;
   (void)ReadVarType;
   VERIFY_INPUT_REF_ID(S32,       ModulInputs[0].Name,                      ModulInputs[0].Id)
   VERIFY_INPUT_REF_ID(S32,       ModulInputs[1].Name,                      ModulInputs[1].Id)
   VERIFY_INPUT_REF_ID(S32,       ModulInputs[2].Name,                      ModulInputs[2].Id)
}

#undef MODUL_INPUTS
#define MODUL_INPUTS_SIZE (sizeof(ModulInputs)/sizeof(ModulInputs[0]))

//------------------------------------------------------------------------------------------
// READ/WRITE VARDB ARRAY      READ/WRITE VARDB ARRAY      READ/WRATE VARDB ARRAY
//------------------------------------------------------------------------------------------


//-----------------------------------------------------------------------
// PARAMETER                    PARAMETER                    PARAMETER
//-----------------------------------------------------------------------

// Create local variable
#define MODUL_PARAMETERS
static U8 P_Lub_Equip0_ForcedMode = 0;
static U8 P_Lub_Equip1_ForcedMode = 0;
static U8 P_Lub_Equip2_ForcedMode = 0;



//-----------------------------------------------------------------------
static struct ModulInOut ModulParameters0[] =
{
   {"P_Lub_Equip0_ForcedMode",                  &P_Lub_Equip0_ForcedMode,                  sizeof(P_Lub_Equip0_ForcedMode),                  },
   {"P_Lub_Equip1_ForcedMode",                  &P_Lub_Equip1_ForcedMode,                  sizeof(P_Lub_Equip1_ForcedMode),                  },
   {"P_Lub_Equip2_ForcedMode",                  &P_Lub_Equip2_ForcedMode,                  sizeof(P_Lub_Equip2_ForcedMode),                  },

};
static struct ModulInOut* ModulParameters[] =
{
   ModulParameters0,
};

//-----------------------------------------------------------------------
// Check variable type
static STATUS ParaVarsReadReturnStatus;
static type_t ParaReadVarType = TYPE_NONE;
static void ParaVarsReadTypeCheck(void)
{
   (void)ParaVarsReadReturnStatus;
   (void)ParaReadVarType;
}

#undef MODUL_PARAMETERS

#define PARAMETERS_GROUPS_SIZE        1
#define GENERAL_GROUP                 0
#define MODUL_PARAMETERS_TOTAL_SIZE   3
static SUBSCRIPTION ParaSubscription[MODUL_PARAMETERS_TOTAL_SIZE];
static U8 ReadParameters[PARAMETERS_GROUPS_SIZE];
static U8 ParametersChanged[PARAMETERS_GROUPS_SIZE];
static UNSIGNED GroupsIndexes[PARAMETERS_GROUPS_SIZE];
static int ParaGroupsSizes[PARAMETERS_GROUPS_SIZE] = { 3 };
static STATUS VarDbUpdateParameter(varid_t VariableId, void* Message, U16 Length, UNSIGNED paraGroupIndex, UNSIGNED Ref2)
{
   ReadParameters[paraGroupIndex] = 1;
   ParametersChanged[paraGroupIndex] = 1;
   return OS_SUCCESS;
}
static STATUS ReadParametersFunc(int paraGroupIndex)
{
   STATUS LocalStatus;
   // Check inputdata
   if (sizeof(ModulParameters[paraGroupIndex]) == 0)
   {
      AppSystemLog(ERR_4, MODULE_NAME"Group %d ModuleParameters = 0", paraGroupIndex);
      return ERR_4;
   }
   // Read inputdata
   LocalStatus = OS_ReadVariables(ModulParameters[paraGroupIndex], ParaGroupsSizes[paraGroupIndex]);
   if (LocalStatus != 0)
   {
      AppSystemLog(11, "LocalStatus: %d", LocalStatus);
      AppSystemLog(ERR_4, MODULE_NAME"ReadParErr: group=%d element=%d elementpointer=0x%x", paraGroupIndex, LocalStatus, &ModulParameters[LocalStatus]);
      return ERR_4;
   }
   return OS_SUCCESS;
}


//-----------------------------------------------------------------------
// READ VARS FROM VARDB    READ VARS FROM VARDB    READ VARS FROM VARDB
//-----------------------------------------------------------------------

static STATUS InputReferenceRoutine(U8 ModuleState)
{
   STATUS LocalStatus = 0;

   // Read input references
   if (ModuleState >= APP_INIT3)
   {
      // Check inputdata
      if (sizeof(ModulInputs) == 0)
      {
         AppSystemLog(ERR_4, MODULE_NAME"ModuleInputs = 0");
         return ERR_4;
      }
      // Read inputdata
      LocalStatus = OS_ReadVariables(ModulInputs, MODUL_INPUTS_SIZE);
      if (LocalStatus != 0)
      {
         AppSystemLog(ERR_4, MODULE_NAME"ReadVErr: element=%d elementpointer=0x%x", LocalStatus, &ModulInputs[LocalStatus]);
         return ERR_4;
      }
   }
   // Read input parameters
   if (ModuleState == APP_INIT3)
   {
      static size_t ParaCounter = 0;
      int groupIndex;
      for (groupIndex = 0; groupIndex < PARAMETERS_GROUPS_SIZE; groupIndex++)
      {
         ParametersChanged[groupIndex] = 1;
         ReadParameters[groupIndex] = 1;
         GroupsIndexes[groupIndex] = groupIndex;

         // Check inputdata
         if (sizeof(ModulParameters[groupIndex]) == 0)
         {
            AppSystemLog(ERR_4, MODULE_NAME"Group = %d ModuleParameters = 0", groupIndex);
            return ERR_4;
         }
         // Read inputdata
         LocalStatus = OS_ReadVariables(ModulParameters[groupIndex], ParaGroupsSizes[groupIndex]);
         if (LocalStatus != 0)
         {
            AppSystemLog(ERR_4, MODULE_NAME"ReadVParaErr: group=%d element=%d elementpointer=0x%x", groupIndex, LocalStatus, &ModulParameters[groupIndex][LocalStatus]);
            return ERR_4;
         }
         int paraIndex;
         for (paraIndex = 0; paraIndex < ParaGroupsSizes[groupIndex]; paraIndex++)
         {
            LocalStatus = OS_SubHandl_SubscribeFunctionWithRef(&ParaSubscription[ParaCounter], 1, &ModulParameters[groupIndex][paraIndex].Id, &GroupsIndexes[groupIndex], &GroupsIndexes[groupIndex], VarDbUpdateParameter);
            ParaCounter++;
            if (LocalStatus != 0)
            {
               AppSystemLog(ERR_4, MODULE_NAME"Subscribe Parameter: group=%d element=%d elementpointer=0x%x", groupIndex, LocalStatus, &ModulParameters[LocalStatus]);
               return ERR_4;
            }
         }
      }
   }
   if (ModuleState == APP_RUN)
   {
      int groupIndex;
      for (groupIndex = 0; groupIndex < PARAMETERS_GROUPS_SIZE; groupIndex++)
      {
         if (ReadParameters[groupIndex])
         {
            LocalStatus = ReadParametersFunc(groupIndex);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
            ReadParameters[groupIndex] = 0;
         }
      }
   }

   return 0;
}

#define READ_VARS

//-----------------------------------------------------------------------
// OUTPUT                         OUTPUT                         OUTPUT
//-----------------------------------------------------------------------

// Create local variable
#define MODUL_OUTPUTS
static S32 V_Lub_Equip0_Mode = 0;
static S32 V_Lub_Equip1_Mode = 0;
static S32 V_Lub_Equip2_Mode = 0;
static char V_Lub_Equip0_ModeTxt[31];
static char V_Lub_Equip1_ModeTxt[31];
static char V_Lub_Equip2_ModeTxt[31];


//-----------------------------------------------------------------------
static struct ModulInOut ModulOutputs[] =
{
   {"V_Lub_Equip0_Mode",                        &V_Lub_Equip0_Mode,                        sizeof(V_Lub_Equip0_Mode),                        },
   {"V_Lub_Equip0_ModeTxt",                     &V_Lub_Equip0_ModeTxt,                     sizeof(V_Lub_Equip0_ModeTxt),                     },
   {"V_Lub_Equip1_Mode",                        &V_Lub_Equip1_Mode,                        sizeof(V_Lub_Equip1_Mode),                        },
   {"V_Lub_Equip1_ModeTxt",                     &V_Lub_Equip1_ModeTxt,                     sizeof(V_Lub_Equip1_ModeTxt),                     },
   {"V_Lub_Equip2_Mode",                        &V_Lub_Equip2_Mode,                        sizeof(V_Lub_Equip2_Mode),                        },
   {"V_Lub_Equip2_ModeTxt",                     &V_Lub_Equip2_ModeTxt,                     sizeof(V_Lub_Equip2_ModeTxt),                     },
};

//-----------------------------------------------------------------------
// Check variable type
static STATUS VarsWriteReturnStatus;
static type_t WriteVarType = TYPE_NONE;
static void VarsWriteTypeCheck(void)
{
   (void)VarsWriteReturnStatus;
   (void)WriteVarType;
   VERIFY_OUTPUT_REF_ID(S32,       ModulOutputs[0].Name,                     ModulOutputs[0].Id,                       0)
   VERIFY_OUTPUT_STRING_REF_ID(STRING,     ModulOutputs[1].Name,                      ModulOutputs[1].Id,                       0)
   VERIFY_OUTPUT_REF_ID(S32,       ModulOutputs[2].Name,                     ModulOutputs[2].Id,                       0)
   VERIFY_OUTPUT_STRING_REF_ID(STRING,     ModulOutputs[3].Name,                      ModulOutputs[3].Id,                       0)
   VERIFY_OUTPUT_REF_ID(S32,       ModulOutputs[4].Name,                     ModulOutputs[4].Id,                       0)
   VERIFY_OUTPUT_STRING_REF_ID(STRING,     ModulOutputs[5].Name,                      ModulOutputs[5].Id,                       0)
}

#undef MODUL_OUTPUTS
#define MODUL_OUTPUTS_SIZE (sizeof(ModulOutputs)/sizeof(ModulOutputs[0]))

//-----------------------------------------------------------------------
// WRITE VARS TO VARDB     WRITE VARS TO VARDB     WRITE VARS TO VARDB
//-----------------------------------------------------------------------

static STATUS InitOutputVars(void)
{
   STATUS LocalStatus;
   // Read outputdata
   LocalStatus = OS_ReadVariables(ModulOutputs, MODUL_OUTPUTS_SIZE);
   if (LocalStatus != 0)
   {
      AppSystemLog(ERR_4, MODULE_NAME"InitErr: element=%d elementpointer=0x%x", LocalStatus, &ModulOutputs[LocalStatus]);
      return ERR_4;
   }
   return OS_SUCCESS;
}
static STATUS OutputReferenceRoutine(U8 ModuleState)
{
   STATUS LocalStatus = 0;
   // Write Outputdata
   LocalStatus = OS_WriteVariablesConditional(ModulOutputs, MODUL_OUTPUTS_SIZE);
   if (LocalStatus != 0)
   {
      AppSystemLog(ERR_5, MODULE_NAME"WriteVErr: element=%d elementpointer=0x%x", LocalStatus, &ModulOutputs[LocalStatus]);
      return ERR_5;
   }
   return 0;
}

#define WRITE_VARS

//-----------------------------------------------------------------------
// VERIFY VARIABLES CREATION                 VERIFY VARIABLES CREATION
//-----------------------------------------------------------------------

static STATUS LocalIoCheck(void)
{
   // Check if input variables exist.
   STATUS LocalStatus;

   LocalStatus = OS_DoesVariablesExist(ModulInputs, MODUL_INPUTS_SIZE);
   if (LocalStatus != 0)
   {
      AppSystemLog(ERR_1, MODULE_NAME"InputErr: %d", LocalStatus);
      AppSystemLog(ERR_1, "Name: %s", ModulInputs[LocalStatus-1].Name);
      return ERR_1;
   }
   (void)VarsReadTypeCheck();

   int groupIndex;
   for (groupIndex = 0; groupIndex < PARAMETERS_GROUPS_SIZE; groupIndex++)
   {
      LocalStatus = OS_DoesVariablesExist(ModulParameters[groupIndex], ParaGroupsSizes[groupIndex]);
      if (LocalStatus != 0)
      {
         AppSystemLog(ERR_3, MODULE_NAME"ParameterErr: %d Group:%d", LocalStatus, groupIndex);
         AppSystemLog(ERR_3, "Name: %s", ModulParameters[groupIndex][LocalStatus-1].Name);
         return ERR_3;
      }
   }
   (void)ParaVarsReadTypeCheck();

   LocalStatus = OS_DoesVariablesExist(ModulOutputs, MODUL_OUTPUTS_SIZE);
   if (LocalStatus != 0)
   {
      AppSystemLog(ERR_2, MODULE_NAME"OutputErr: %d", LocalStatus);
      AppSystemLog(ERR_2, "Name: %s", ModulOutputs[LocalStatus-1].Name);
      return ERR_2;
   }
   (void)VarsWriteTypeCheck();

   return OS_SUCCESS;
}

#define VERIFY_VARIABLES

//-----------------------------------------------------------------------
// ALLOCATE MEMORY FOR SUMMATIONS        ALLOCATE MEMORY FOR SUMMATIONS
//-----------------------------------------------------------------------


//-----------------------------------------------------------------------
// SUMMATIONS                  SUMMATIONS                  SUMMATIONS
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// DEFINE MENUS               DEFINE MENUS               DEFINE MENUS
//-----------------------------------------------------------------------



// Menu line and link to local menu
//-----------------------------------------------------------------------
static struct line_struct M_LubricationManagerMTType1LinkToLocalMenu[] =
{
   MENU_ELEMENT_LINE_LINK("Lubrication",                       PASSWORD_LEVEL_END_CUSTOMER,        "M_LubricationManagerMTType1",      "G_LubricationManager_MT_Type1"),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_LubricationManagerMTType1Menu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_LubricationManagerMTType1",      PASSWORD_LEVEL_END_CUSTOMER),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_LubricationManagerMTType1MenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("LUBRICATION",                       PASSWORD_LEVEL_END_CUSTOMER,        "M_"APP_ID"AppMain",                "G_"APP_ID"App"),
   MENU_ELEMENT_LINE_VARRO("Pitch Pinion Lub. Mode Request",   PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_Lub_Equip0_ModeTxt",                       LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Pitch Pinion Lub. State",          PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_Lub_Equip0_StateTxt",                      LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Main Bearing Lub. Mode Request",   PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_Lub_Equip1_ModeTxt",                       LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Main Bearing Lub. State",          PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_Lub_Equip1_StateTxt",                      LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Yaw Lubrication Mode Request",     PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_Lub_Equip2_ModeTxt",                       LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Yaw Lubrication State",            PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_Lub_Equip2_StateTxt",                      LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_LINK("Status",                            PASSWORD_LEVEL_END_CUSTOMER,        "M_Status3",                        "G_LubricationManager_MT_Type1"),
   MENU_ELEMENT_LINE_LINK("Service",                           PASSWORD_LEVEL_SERVICE,             "M_Service15",                      "G_LubricationManager_MT_Type1"),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_Status3Menu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_Status3",                        PASSWORD_LEVEL_END_CUSTOMER),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_Status3MenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("STATUS",                            PASSWORD_LEVEL_END_CUSTOMER,        "M_LubricationManagerMTType1",      "G_LubricationManager_MT_Type1"),
   MENU_ELEMENT_LINE_VARRO("Pitch Pinion Lub. Status",         PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_Lub_Equip0_StatusTxt",                     LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Main Bearing Lub. Status",         PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_Lub_Equip1_StatusTxt",                     LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Yaw Lubrication Status",           PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_Lub_Equip2_StatusTxt",                     LINE_FORMAT_NONE),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_Service15Menu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_Service15",                      PASSWORD_LEVEL_SERVICE),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_Service15MenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("SERVICE",                           PASSWORD_LEVEL_SERVICE,             "M_LubricationManagerMTType1",      "G_LubricationManager_MT_Type1"),
   MENU_ELEMENT_LINE_VARRW("Pitch Pinion Lub. Forced Mode",    PASSWORD_LEVEL_SERVICE,             (char*)"P_Lub_Equip0_ForcedMode",                    LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Main Bearing Lub. Forced Mode",    PASSWORD_LEVEL_SERVICE,             (char*)"P_Lub_Equip1_ForcedMode",                    LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Yaw Lubrication Forced Mode",      PASSWORD_LEVEL_SERVICE,             (char*)"P_Lub_Equip2_ForcedMode",                    LINE_FORMAT_NONE),
};
// Creating parameters for multiplexed categories
//-----------------------------------------------------------------------
static struct multiplexed_info_struct M_LubricationManagerMTType1MultiplexedCategoriesParameters[] =
{
0};

//-----------------------------------------------------------------------
// CREATE MENUS               CREATE MENUS               CREATE MENUS
//-----------------------------------------------------------------------

// Memory reservation
//-----------------------------------------------------------------------
static struct menu_group_struct ObjGroup[1];

// Creating the menus
//-----------------------------------------------------------------------
STATUS Lubrication_MT_Type1MenuAppInit(U8 ModuleState, OS_MEMORY_POOL* pPool)
{
   STATUS Status;

   if (ModuleState == APP_INIT1)
   {
      /* Create application group */
      Status = OS_CreateMenuGroup(ObjGroup, M_LubricationManagerMTType1LinkToLocalMenu[0].LinkGroup);
      STATUS_LINE_VAR_RETURN_VALUE(Status);
   }

   Status = CreateAndInitializeMenu(ModuleState,
                                    M_LubricationManagerMTType1MenuLines[0].LinkGroup,
                                    M_LubricationManagerMTType1MenuLines[0].LinkName,
                                    ELEMENT(M_LubricationManagerMTType1LinkToLocalMenu),
                                    M_LubricationManagerMTType1LinkToLocalMenu[0].LinkGroup,
                                    ELEMENT(M_LubricationManagerMTType1Menu),
                                    M_LubricationManagerMTType1LinkToLocalMenu[0].LinkName,
                                    ELEMENT(M_LubricationManagerMTType1MenuLines),
                                    pPool,
                                    M_LubricationManagerMTType1MultiplexedCategoriesParameters);
   STATUS_LINE_VAR_RETURN_VALUE(Status);

   Status = CreateAndInitializeMenu(ModuleState,
                                    M_Status3MenuLines[0].LinkGroup,
                                    M_Status3MenuLines[0].LinkName,
                                    NULL,
                                    0,
                                    M_LubricationManagerMTType1MenuLines[7].LinkGroup,
                                    ELEMENT(M_Status3Menu),
                                    M_LubricationManagerMTType1MenuLines[7].LinkName,
                                    ELEMENT(M_Status3MenuLines),
                                    pPool,
                                    M_LubricationManagerMTType1MultiplexedCategoriesParameters);
   STATUS_LINE_VAR_RETURN_VALUE(Status);

   Status = CreateAndInitializeMenu(ModuleState,
                                    M_Service15MenuLines[0].LinkGroup,
                                    M_Service15MenuLines[0].LinkName,
                                    NULL,
                                    0,
                                    M_LubricationManagerMTType1MenuLines[8].LinkGroup,
                                    ELEMENT(M_Service15Menu),
                                    M_LubricationManagerMTType1MenuLines[8].LinkName,
                                    ELEMENT(M_Service15MenuLines),
                                    pPool,
                                    M_LubricationManagerMTType1MultiplexedCategoriesParameters);
   STATUS_LINE_VAR_RETURN_VALUE(Status);

   return OS_SUCCESS;
}

#define CREATE_MENU

//-----------------------------------------------------------------------
//               BUTTONS FUNCTIONS FORWARD DECLARATIONS
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// BUTTONS                       BUTTONS                      BUTTONS
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
//             SET/RESET FUNCTIONS FORWARD DECLARATIONS
//-----------------------------------------------------------------------
//-----------------------------------------------------------------------
// STATUSCODES                 STATUSCODES                 STATUSCODES
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// MODIFIABLE                  MODIFIABLE                   MODIFIABLE
//-----------------------------------------------------------------------

extern const char Lubrication_MT_Type1AppGroupName[];
extern const char Lubrication_MT_Type1AppMenuName[];

static void Init_Structures_From_Conf_File(void)
{
   M_LubricationManagerMTType1MenuLines[0].LinkName = (char*)Lubrication_MT_Type1AppMenuName;
   M_LubricationManagerMTType1MenuLines[0].LinkGroup = (char*)Lubrication_MT_Type1AppGroupName;
}

//-----------------------------------------------------------------------
// AUTOGENERATED END        AUTOGENERATED END        AUTOGENERATED END
//-----------------------------------------------------------------------
//}

#undef AUTOGENERATED_PART

//-----------------------------------------------------------------------
// USER DEFINITIONS         USER DEFINITIONS         USER DEFINITIONS
//-----------------------------------------------------------------------
 
//-----------------------------------------------------------------------
// SET/RESET FUNCTIONS    SET/RESET FUNCTIONS    SET/RESET FUNCTIONS
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// DRIVER FUNCTION         DRIVER FUNCTION         DRIVER FUNCTION
//-----------------------------------------------------------------------
  
//-----------------------------------------------------------------------
// INIT                   INIT                     INIT
//-----------------------------------------------------------------------
  
//-----------------------------------------------------------------------
// CONTROL                CONTROL                 CONTROL
//-----------------------------------------------------------------------

static U8 PitchPinionLubricationObjectPresent = 0;
static U8 MainBearingLubricationObjectPresent = 0;
static U8 YawLubricationObjectPresent = 0;

static STATUS LocalCtrl(void)
{
    STATUS LocalStatus = 0;
    static U8 FirstTime = 1;

    if( FirstTime )
    {
        FirstTime = 0;
        if( STATE_UNREGISTERED != V_Lub_Equip0_State ) { PitchPinionLubricationObjectPresent = 1; }
        if( STATE_UNREGISTERED != V_Lub_Equip1_State ) { MainBearingLubricationObjectPresent = 1; }
        if( STATE_UNREGISTERED != V_Lub_Equip2_State ) { YawLubricationObjectPresent = 1; }
    }

    if( PitchPinionLubricationObjectPresent )
    {
        switch( P_Lub_Equip0_ForcedMode )
        {
        case 0:
            V_Lub_Equip0_Mode = MANAGER_MODE_ENABLE;
            strncpy(V_Lub_Equip0_ModeTxt, TEXT_ENABLE, sizeof(V_Lub_Equip0_ModeTxt));
            break;

        case 1:
            V_Lub_Equip0_Mode = MANAGER_MODE_ENABLE;
            strncpy(V_Lub_Equip0_ModeTxt, TEXT_ENABLE, sizeof(V_Lub_Equip0_ModeTxt));
            break;

        case 2:
            V_Lub_Equip0_Mode = MANAGER_MODE_DISABLE;
            strncpy(V_Lub_Equip0_ModeTxt, TEXT_DISABLE, sizeof(V_Lub_Equip0_ModeTxt));
            break;

        default:
            V_Lub_Equip0_Mode = MANAGER_MODE_DISABLE;
            strncpy(V_Lub_Equip0_ModeTxt, TEXT_DISABLE, sizeof(V_Lub_Equip0_ModeTxt));
            break;
        }
    }
    else
    {
        V_Lub_Equip0_Mode = MANAGER_MODE_DISABLE;
        strncpy(V_Lub_Equip0_ModeTxt, TEXT_DISABLE, sizeof(V_Lub_Equip0_ModeTxt));
    }

    if( MainBearingLubricationObjectPresent )
    {
        switch( P_Lub_Equip1_ForcedMode )
        {
        case 0:
            V_Lub_Equip1_Mode = MANAGER_MODE_ENABLE;
            strncpy(V_Lub_Equip1_ModeTxt, TEXT_ENABLE, sizeof(V_Lub_Equip1_ModeTxt));
            break;

        case 1:
            V_Lub_Equip1_Mode = MANAGER_MODE_ENABLE;
            strncpy(V_Lub_Equip1_ModeTxt, TEXT_ENABLE, sizeof(V_Lub_Equip1_ModeTxt));
            break;

        case 2:
            V_Lub_Equip1_Mode = MANAGER_MODE_DISABLE;
            strncpy(V_Lub_Equip1_ModeTxt, TEXT_DISABLE, sizeof(V_Lub_Equip1_ModeTxt));
            break;

        default:
            V_Lub_Equip1_Mode = MANAGER_MODE_DISABLE;
            strncpy(V_Lub_Equip1_ModeTxt, TEXT_DISABLE, sizeof(V_Lub_Equip1_ModeTxt));
            break;
        }
    }
    else
    {
        V_Lub_Equip1_Mode = MANAGER_MODE_DISABLE;
        strncpy(V_Lub_Equip1_ModeTxt, TEXT_DISABLE, sizeof(V_Lub_Equip1_ModeTxt));
    }

    if( YawLubricationObjectPresent )
    {
        switch( P_Lub_Equip2_ForcedMode )
        {
        case 0:
            V_Lub_Equip2_Mode = MANAGER_MODE_ENABLE;
            strncpy(V_Lub_Equip2_ModeTxt, TEXT_ENABLE, sizeof(V_Lub_Equip2_ModeTxt));
            break;

        case 1:
            V_Lub_Equip2_Mode = MANAGER_MODE_ENABLE;
            strncpy(V_Lub_Equip2_ModeTxt, TEXT_ENABLE, sizeof(V_Lub_Equip2_ModeTxt));
            break;

        case 2:
            V_Lub_Equip2_Mode = MANAGER_MODE_DISABLE;
            strncpy(V_Lub_Equip2_ModeTxt, TEXT_DISABLE, sizeof(V_Lub_Equip2_ModeTxt));
            break;

        default:
            V_Lub_Equip2_Mode = MANAGER_MODE_DISABLE;
            strncpy(V_Lub_Equip2_ModeTxt, TEXT_DISABLE, sizeof(V_Lub_Equip2_ModeTxt));
            break;
        }
    }
    else
    {
        V_Lub_Equip2_Mode = MANAGER_MODE_DISABLE;
        strncpy(V_Lub_Equip2_ModeTxt, TEXT_DISABLE, sizeof(V_Lub_Equip2_ModeTxt));
    }

    return LocalStatus;
}
  
//-----------------------------------------------------------------------
// MAIN CALL             MAIN CALL               MAIN CALL
//-----------------------------------------------------------------------

STATUS Lubrication_MT_Type1(U8 ModuleState, OS_MEMORY_POOL *MemPool, U32 *Arg3)
{
   STATUS LocalStatus = 0;

   // Version check
   if(ModuleState == APP_INIT1)
   {
      LocalStatus = OS_ValidateAPI(API_VERSION_MAJOR,
                                   API_VERSION_MINOR,
                                   OS_LinkTime,
                                   ReleaseTag,
                                   __MODULE__
                                   );
      if ( OS_SUCCESS != LocalStatus )
      {
         return LocalStatus;
      }
   }
#ifdef READ_VARS
   // Read inputdata
   LocalStatus = InputReferenceRoutine(ModuleState);
   STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif
#ifdef COMMON_VDB_READ
   LocalStatus = ReadVdbWindow(ModuleState);
   STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif
   switch(ModuleState)
   {
      case APP_RUN :
      {
         #ifdef FUNCTION_BLOCKS_PRE_LOCAL_CONTROL
            LocalStatus = FunctionBlocksPreLocalCtrl( Interval );
            STATUS_LINE_VAR_RETURN_VALUE( LocalStatus );
         #endif

         LocalStatus = LocalCtrl();
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
        
         #ifdef FUNCTION_BLOCKS_POST_LOCAL_CONTROL
            LocalStatus = FunctionBlocksPostLocalCtrl( Interval );
            STATUS_LINE_VAR_RETURN_VALUE( LocalStatus );
         #endif

#ifdef WRITE_VARS
         // Write Outputdata
         LocalStatus = OutputReferenceRoutine(ModuleState);
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif

#ifdef COMMON_VDB_WRITE
         LocalStatus = WriteVdbWindow(ModuleState);
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif
         break;
      }
      case APP_INIT1 :
      {
         Init_Structures_From_Conf_File();

#ifdef CREATE_VARDB_VARS
         LocalStatus = CreateVarDbVars();
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif

#ifdef CREATE_MENU
         LocalStatus = Lubrication_MT_Type1MenuAppInit(ModuleState, MemPool);
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)

#ifdef MULTIPLEXIBLE_MENU
         LocalStatus = MenuArraysAppInit(ModuleState, MemPool);
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif
#endif

#ifdef CREATE_VARDB_ARRAY_VARS
         LocalStatus = CreateVdbArrays(MemPool);
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif

#ifdef CREATE_IO_VARS
         LocalStatus = CreateIOVars();
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif
         break;
      }
      case APP_INIT2 :
      {
#ifdef CREATE_MENU
#ifdef MULTIPLEXIBLE_MENU
         LocalStatus = MenuArraysAppInit(ModuleState, MemPool);
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif
#endif

#ifdef CREATE_ALIASES
         size_t ErrorEntry = 0;
         LocalStatus = OS_VarDB_CreateAliases(AliasVars, sizeof(AliasVars)/sizeof(AliasVars[0]), &ErrorEntry);
         STATUS_LINE_VAR_RETURN_CONST(LocalStatus, ErrorEntry)
#endif

#ifdef VERIFY_ARRAY
        LocalStatus = VerifyArray(MemPool);
        STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif

#ifdef VERIFY_VARIABLES
         LocalStatus = LocalIoCheck();
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif

#ifdef CREATE_BUTTONS
         LocalStatus = CreateButtons();
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif
         break;
      }
      case APP_INIT3 :
      {
#ifdef CREATE_SUMMATIONS
         LocalStatus = CreateSummations();
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif

#ifdef WRITE_VARS
         LocalStatus = InitOutputVars();
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif

#ifdef CREATE_STATUS_CODES
         LocalStatus = LocalStatusCodeInit();
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif

#ifdef CREATE_IO_VARS
        Lubrication_MT_Type1SetLockValues();
#endif
         break;
      }
      case APP_INIT4 :
      {
#ifdef CREATE_MENU
         LocalStatus = Lubrication_MT_Type1MenuAppInit(ModuleState, MemPool);
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)

#ifdef MULTIPLEXIBLE_MENU
         LocalStatus = MenuArraysAppInit(ModuleState, MemPool);
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif
#endif
         break;
      }
      case APP_INIT5 :
      {
#ifdef VALIDATE_HASH
         LocalStatus = ValidateHash(Lubrication_MT_Type1_copyright, MODULE_NAME, Lubrication_MT_Type1_initialValues);
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif

         #ifdef INIT_FUNCTION_BLOCKS
            LocalStatus = FunctionBlocksInit( Interval );
            STATUS_LINE_VAR_RETURN_VALUE( LocalStatus );
         #endif

         break;
      }
      default :
      {
         break;
      }
   }
   return OS_SUCCESS;
}
//-----------------------------------------------------------------------
