//*****************************PEPTOOL Header Start******************************
//                                                                               
//                         Copyright © 2015 Mita-Teknik.                         
//This software may only be used with WP4x00 Controllers delivered by Mita-Teknik
//                                                                               
//*******************************************************************************
//                                                                               
// $PEPTOOL version:9.0$                                                         
// $PEPTOOL file version:101$                                                    
//                                                                               
//*******************************************************************************
//                                                                               
// $Date: 2014/05/23 09:10:11 $                                                  
// $Author: MITA\ihn $                                                           
// $RCSfile: LubricationYaw_MT_Type1_Conf.c,v $                                  
// $Revision: 1.6 $                                                              
//                                                                               
//******************************PEPTOOL Header End*******************************

//***********************************************************************
// OS header files
#include <os_main.h>
// App header files
#include <InitIo.h>

#define AUTOGENERATED_PART

#include <Turbdef.h>

//-----------------------------------------------------------------------
// AUTOGENERATED START     AUTOGENERATED START     AUTOGENERATED START
//-----------------------------------------------------------------------
char LubricationYaw_MT_Type1_Conf_copyright[] =
{
   67, 111, 112, 121, 114, 105, 103, 104, 116, 32, 63, 32, 50, 48, 49, 53,
   32, 77, 105, 116, 97, 45, 84, 101, 107, 110, 105, 107, 46, 13, 10, 84,
   104, 105, 115, 32, 115, 111, 102, 116, 119, 97, 114, 101, 32, 109, 97, 121,
   32, 111, 110, 108, 121, 32, 98, 101, 32, 117, 115, 101, 100, 32, 119, 105,
   116, 104, 32, 87, 80, 52, 120, 48, 48, 32, 67, 111, 110, 116, 114, 111,
   108, 108, 101, 114, 115, 32, 100, 101, 108, 105, 118, 101, 114, 101, 100, 32,
   98, 121, 32, 77, 105, 116, 97, 45, 84, 101, 107, 110, 105, 107, 0
};
//-----------------------------------------------------------------------
// MODIFIABLE                  MODIFIABLE               MODIFIABLE
//-----------------------------------------------------------------------
const char LubricationYaw_MT_Type1AppGroupName[] = "G_LubricationManager_MT_Type1";
const char LubricationYaw_MT_Type1AppMenuName[] = "M_LubricationManagerMTType1";

//-----------------------------------------------------------------------
// IO VARIABLES                IO VARIABLES                IO VARIABLES
//-----------------------------------------------------------------------

void (*LubricationYaw_MT_Type1SetLockValues)(void);
struct os_db_alias *LubricationYaw_MT_Type1IOVars;
size_t LubricationYaw_MT_Type1IOVarsSize = 0;
            
struct os_db_alias LubricationYaw_MT_Type1IOVars1[]=
{
    VAR_ELEMENT_ALIAS("3.3.7",                            "DO_LubricationYaw_Pump"),

    VAR_ELEMENT_ALIAS("3.3.43",                           "DI_LubricationYaw_SystemLevelWarning"),
    VAR_ELEMENT_ALIAS("3.3.43_Ss",                        "DI_LubricationYaw_SystemLevelWarning_Ss"),
    VAR_ELEMENT_ALIAS("3.3.43_E",                         "DI_LubricationYaw_SystemLevelWarning_E"),
    VAR_ELEMENT_ALIAS("3.3.43_I",                         "DI_LubricationYaw_SystemLevelWarning_I"),
    VAR_ELEMENT_ALIAS("3.3.43_Cm",                        "DI_LubricationYaw_SystemLevelWarning_Cm"),
    VAR_ELEMENT_ALIAS("3.3.43_Ht",                        "DI_LubricationYaw_SystemLevelWarning_Ht"),

    VAR_ELEMENT_ALIAS("3.3.44",                           "DI_LubricationYaw_PumpFault"),
    VAR_ELEMENT_ALIAS("3.3.44_Ss",                        "DI_LubricationYaw_PumpFault_Ss"),
    VAR_ELEMENT_ALIAS("3.3.44_E",                         "DI_LubricationYaw_PumpFault_E"),
    VAR_ELEMENT_ALIAS("3.3.44_I",                         "DI_LubricationYaw_PumpFault_I"),
    VAR_ELEMENT_ALIAS("3.3.44_Cm",                        "DI_LubricationYaw_PumpFault_Cm"),
    VAR_ELEMENT_ALIAS("3.3.44_Ht",                        "DI_LubricationYaw_PumpFault_Ht"),

};
size_t LubricationYaw_MT_Type1IOVars1Size = sizeof(LubricationYaw_MT_Type1IOVars1)/sizeof(LubricationYaw_MT_Type1IOVars1[0]);

void LubricationYaw_MT_Type1SetLockValues1(void)
{
   SetLockValue("DI_LubricationYaw_SystemLevelWarning_Ss",TYP_8,     1);
   SetLockValue("DI_LubricationYaw_SystemLevelWarning_E",TYP_8,     1);
   SetValue("DI_LubricationYaw_SystemLevelWarning_I",    TYP_8,     0);
   SetLockValue("DI_LubricationYaw_SystemLevelWarning_Cm",TYP_8,     1);
   SetLockValue("DI_LubricationYaw_SystemLevelWarning_Ht",TYP_32,    100);

   SetLockValue("DI_LubricationYaw_PumpFault_Ss",        TYP_8,     1);
   SetLockValue("DI_LubricationYaw_PumpFault_E",         TYP_8,     1);
   SetValue("DI_LubricationYaw_PumpFault_I",             TYP_8,     0);
   SetLockValue("DI_LubricationYaw_PumpFault_Cm",        TYP_8,     1);
   SetLockValue("DI_LubricationYaw_PumpFault_Ht",        TYP_32,    100);
}


STATUS LubricationYaw_MT_Type1InitIOAliases()
{
   LubricationYaw_MT_Type1IOVars = LubricationYaw_MT_Type1IOVars1;
   LubricationYaw_MT_Type1IOVarsSize = LubricationYaw_MT_Type1IOVars1Size;
   LubricationYaw_MT_Type1SetLockValues = &LubricationYaw_MT_Type1SetLockValues1;
   return OS_SUCCESS;
}
//-----------------------------------------------------------------------
// AUTOGENERATED END        AUTOGENERATED END        AUTOGENERATED END
//-----------------------------------------------------------------------

#undef AUTOGENERATED_PART
