//*****************************PEPTOOL Header Start******************************
//                                                                               
//                         Copyright © 2015 Mita-Teknik.                         
//This software may only be used with WP4x00 Controllers delivered by Mita-Teknik
//                                                                               
//*******************************************************************************
//                                                                               
// $PEPTOOL version:9.0$                                                         
// $PEPTOOL file version:106$                                                    
//                                                                               
//*******************************************************************************
//                                                                               
// $Date: 2014/05/23 09:10:12 $                                                  
// $Author: MITA\ihn $                                                           
// $RCSfile: LVRT.c,v $                                                          
// $Revision: 1.9 $                                                              
//                                                                               
//******************************PEPTOOL Header End*******************************

//***********************************************************************
// OS header files
#include <os_main.h>
// AppLib header files
#include <lib_main.h>
// App header files
#include <turbdef.h>
#include <VarMacros.h>
// Object header file
#include <LVRT.h>

#define AUTOGENERATED_PART
//{
//-----------------------------------------------------------------------
// AUTOGENERATED START     AUTOGENERATED START     AUTOGENERATED START
//-----------------------------------------------------------------------

#define VALIDATE_HASH
char LVRT_copyright[] =
{
   67, 111, 112, 121, 114, 105, 103, 104, 116, 32, 63, 32, 50, 48, 49, 53,
   32, 77, 105, 116, 97, 45, 84, 101, 107, 110, 105, 107, 46, 13, 10, 84,
   104, 105, 115, 32, 115, 111, 102, 116, 119, 97, 114, 101, 32, 109, 97, 121,
   32, 111, 110, 108, 121, 32, 98, 101, 32, 117, 115, 101, 100, 32, 119, 105,
   116, 104, 32, 87, 80, 52, 120, 48, 48, 32, 67, 111, 110, 116, 114, 111,
   108, 108, 101, 114, 115, 32, 100, 101, 108, 105, 118, 101, 114, 101, 100, 32,
   98, 121, 32, 77, 105, 116, 97, 45, 84, 101, 107, 110, 105, 107, 0
};

#define MODULE_NAME "LVRTA"

//-----------------------------------------------------------------------
// ALLOCATE MEMORY FOR STRINGS IN VARDB
//-----------------------------------------------------------------------

static char A_V_LVRT_OperateTimerTxt[31]  = "12345678901234567890123456789";

//-----------------------------------------------------------------------
// DEFINE LOCAL VARIABLES DEFINE LOCAL VARIABLES DEFINE LOCAL VARIABLES
//-----------------------------------------------------------------------

static struct os_db_local LocalVars[] =
{
   VAR_ELEMENT_LOCAL("V_LVRT_Active",                            TYPE_U8,      PASSWORD_LEVEL_ADMINISTRATOR,      PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   0,               0,               1,               NULL,  TOTLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_LVRT_Detected",                          TYPE_U8,      PASSWORD_LEVEL_ADMINISTRATOR,      PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   0,               0,               1,               NULL,  TOTLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_LVRT_DropDurationTime",                  TYPE_U32,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_MS,            0,   0,               0,               2000,            NULL,  TOTLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_LVRT_DropStartTimeStamp",                TYPE_TIME,    PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   (0ULL),          (0ULL),          (0ULL),          NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_LVRT_EventTimeOut",                      TYPE_U32,     PASSWORD_LEVEL_ADMINISTRATOR,      PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_MS,            0,   0,               0,               12000,           NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_LVRT_GeneratorRpmLimit",                 TYPE_S32,     PASSWORD_LEVEL_ADMINISTRATOR,      PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    100,     UNIT_RPM,           2,   0,               0,               250000,          NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_LVRT_OperateTimerTxt",                   TYPE_STRING + sizeof(A_V_LVRT_OperateTimerTxt) - 1,  PASSWORD_LEVEL_ADMINISTRATOR,      PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   A_V_LVRT_OperateTimerTxt, 0,                0,                NULL,  NOLOG_ENABLE  ),
   VAR_ELEMENT_LOCAL("V_LVRT_PitchAngleFactorFromTable",         TYPE_U16,     PASSWORD_LEVEL_ADMINISTRATOR,      PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    10,      UNIT_PCT,           1,   0,               0,               2000,            NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_LVRT_PitchBackTime",                     TYPE_U32,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_MS,            0,   0,               0,               10000,           NULL,  TOTLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_LVRT_PitchBackTimeFromTable",            TYPE_U32,     PASSWORD_LEVEL_ADMINISTRATOR,      PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_MS,            0,   0,               0,               10000,           NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_LVRT_PitchMode",                         TYPE_U8,      PASSWORD_LEVEL_ADMINISTRATOR,      PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   0,               0,               10,              NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_LVRT_PitchPositionLimit",                TYPE_S32,     PASSWORD_LEVEL_ADMINISTRATOR,      PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    100,     UNIT_DEGREE,        2,   0,               0,               9000,            NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_LVRT_PitchPowersetpoint",                TYPE_S32,     PASSWORD_LEVEL_ADMINISTRATOR,      PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    1000,    UNIT_KWATT,         3,   0,               0,               2500000,         NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_LVRT_PitchRPMsetpoint",                  TYPE_U32,     PASSWORD_LEVEL_ADMINISTRATOR,      PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    100,     UNIT_RPM,           2,   0,               0,               250000,          NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_LVRT_PitchSpeedLimit",                   TYPE_U32,     PASSWORD_LEVEL_ADMINISTRATOR,      PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    100,     UNIT_DEGREESPSEC,   2,   0,               0,               3000,            NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_LVRT_SimulateDropTime",                  TYPE_U32,     PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_SERVICE,            SCALE_NONE,   0,       UNIT_MS,            0,   0,               0,               5000,            NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_LVRT_SimulateLVRT",                      TYPE_U8,      PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_SERVICE,            SCALE_NONE,   0,       UNIT_NONE,          0,   0,               0,               1,               NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_LVRT_SimulateTorqueAct",                 TYPE_S16,     PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_SERVICE,            SCALE_DIV,    100,     UNIT_PCT,           0,   0,               0,               10000,           NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_LVRT_TorqueDropMeanValuePct",            TYPE_S16,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    100,     UNIT_PCT,           1,   0,               -10000,          10000,           NULL,  TOTLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_LVRT_TorqueLimit",                       TYPE_S32,     PASSWORD_LEVEL_ADMINISTRATOR,      PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    10,      UNIT_NM,            1,   0,               0,               10000000,        NULL,  TOTLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_LVRT_TorqueRecoveryRatePct",             TYPE_S16,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    100,     UNIT_PCTPSEC,       1,   0,               0,               10000,           NULL,  TOTLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_LVRT_TorqueRecoveryTimeClaculated",      TYPE_U32,     PASSWORD_LEVEL_ADMINISTRATOR,      PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_MS,            0,   0,               0,               10000,           NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_LVRT_TorqueRecoveryTimeReal",            TYPE_U32,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_MS,            0,   0,               0,               10000,           NULL,  TOTLOG_ENABLE),
};

//-----------------------------------------------------------------------
// DEFINE PARAMETERS        DEFINE PARAMETERS        DEFINE PARAMETERS
//-----------------------------------------------------------------------

static struct os_db_parameter ParameterVars[] =
{
   VAR_ELEMENT_PARAMETER("P_LVRT_Enable",                            TYPE_U8,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_NONE,   0,       UNIT_NONE,          0,   1,               0,               1,               NULL  ),
   VAR_ELEMENT_PARAMETER("P_LVRT_HardwareDetectEnabled",             TYPE_U8,      PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_MITA_PROGRAMMER,    SCALE_NONE,   0,       UNIT_NONE,          0,   0,               0,               1,               NULL  ),
   VAR_ELEMENT_PARAMETER("P_LVRT_InverterDetectEnabled",             TYPE_U8,      PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_MITA_PROGRAMMER,    SCALE_NONE,   0,       UNIT_NONE,          0,   1,               0,               1,               NULL  ),
   VAR_ELEMENT_PARAMETER("P_LVRT_MaxDurationTime",                   TYPE_U32,     PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_MITA_PROGRAMMER,    SCALE_DIV,    1000,    UNIT_SECOND,        0,   15000,           15000,           15000,           NULL  ),
   VAR_ELEMENT_PARAMETER("P_LVRT_PitchAngleFactor0Deg",              TYPE_U16,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_DIV,    10,      UNIT_PCT,           0,   1000,            100,             2000,            NULL  ),
   VAR_ELEMENT_PARAMETER("P_LVRT_PitchAngleFactor10Deg",             TYPE_U16,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_DIV,    10,      UNIT_PCT,           0,   1000,            100,             2000,            NULL  ),
   VAR_ELEMENT_PARAMETER("P_LVRT_PitchAngleFactor12Deg",             TYPE_U16,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_DIV,    10,      UNIT_PCT,           0,   1000,            100,             2000,            NULL  ),
   VAR_ELEMENT_PARAMETER("P_LVRT_PitchAngleFactor14Deg",             TYPE_U16,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_DIV,    10,      UNIT_PCT,           0,   1000,            100,             2000,            NULL  ),
   VAR_ELEMENT_PARAMETER("P_LVRT_PitchAngleFactor16Deg",             TYPE_U16,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_DIV,    10,      UNIT_PCT,           0,   1000,            100,             2000,            NULL  ),
   VAR_ELEMENT_PARAMETER("P_LVRT_PitchAngleFactor18Deg",             TYPE_U16,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_DIV,    10,      UNIT_PCT,           0,   1000,            100,             2000,            NULL  ),
   VAR_ELEMENT_PARAMETER("P_LVRT_PitchAngleFactor20Deg",             TYPE_U16,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_DIV,    10,      UNIT_PCT,           0,   1000,            100,             2000,            NULL  ),
   VAR_ELEMENT_PARAMETER("P_LVRT_PitchAngleFactor2Deg",              TYPE_U16,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_DIV,    10,      UNIT_PCT,           0,   1000,            100,             2000,            NULL  ),
   VAR_ELEMENT_PARAMETER("P_LVRT_PitchAngleFactor4Deg",              TYPE_U16,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_DIV,    10,      UNIT_PCT,           0,   1000,            100,             2000,            NULL  ),
   VAR_ELEMENT_PARAMETER("P_LVRT_PitchAngleFactor6Deg",              TYPE_U16,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_DIV,    10,      UNIT_PCT,           0,   1000,            100,             2000,            NULL  ),
   VAR_ELEMENT_PARAMETER("P_LVRT_PitchAngleFactor8Deg",              TYPE_U16,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_DIV,    10,      UNIT_PCT,           0,   1000,            100,             2000,            NULL  ),
   VAR_ELEMENT_PARAMETER("P_LVRT_PitchBackTime0Pct",                 TYPE_U32,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_NONE,   0,       UNIT_MS,            0,   0,               0,               10000,           NULL  ),
   VAR_ELEMENT_PARAMETER("P_LVRT_PitchBackTime100Pct",               TYPE_U32,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_NONE,   0,       UNIT_MS,            0,   2000,            0,               10000,           NULL  ),
   VAR_ELEMENT_PARAMETER("P_LVRT_PitchBackTime10Pct",                TYPE_U32,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_NONE,   0,       UNIT_MS,            0,   200,             0,               10000,           NULL  ),
   VAR_ELEMENT_PARAMETER("P_LVRT_PitchBackTime20Pct",                TYPE_U32,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_NONE,   0,       UNIT_MS,            0,   400,             0,               10000,           NULL  ),
   VAR_ELEMENT_PARAMETER("P_LVRT_PitchBackTime30Pct",                TYPE_U32,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_NONE,   0,       UNIT_MS,            0,   600,             0,               10000,           NULL  ),
   VAR_ELEMENT_PARAMETER("P_LVRT_PitchBackTime40Pct",                TYPE_U32,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_NONE,   0,       UNIT_MS,            0,   800,             0,               10000,           NULL  ),
   VAR_ELEMENT_PARAMETER("P_LVRT_PitchBackTime50Pct",                TYPE_U32,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_NONE,   0,       UNIT_MS,            0,   1000,            0,               10000,           NULL  ),
   VAR_ELEMENT_PARAMETER("P_LVRT_PitchBackTime60Pct",                TYPE_U32,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_NONE,   0,       UNIT_MS,            0,   1200,            0,               10000,           NULL  ),
   VAR_ELEMENT_PARAMETER("P_LVRT_PitchBackTime70Pct",                TYPE_U32,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_NONE,   0,       UNIT_MS,            0,   1400,            0,               10000,           NULL  ),
   VAR_ELEMENT_PARAMETER("P_LVRT_PitchBackTime80Pct",                TYPE_U32,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_NONE,   0,       UNIT_MS,            0,   1600,            0,               10000,           NULL  ),
   VAR_ELEMENT_PARAMETER("P_LVRT_PitchBackTime90Pct",                TYPE_U32,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_NONE,   0,       UNIT_MS,            0,   1800,            0,               10000,           NULL  ),
   VAR_ELEMENT_PARAMETER("P_LVRT_PitchDelay",                        TYPE_U32,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_NONE,   0,       UNIT_MS,            0,   500,             0,               2000,            NULL  ),
   VAR_ELEMENT_PARAMETER("P_LVRT_PitchRecoveryRpm",                  TYPE_U32,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_DIV,    100,     UNIT_RPM,           1,   13,              1000,            2500,            NULL  ),
   VAR_ELEMENT_PARAMETER("P_LVRT_PitchSpeed",                        TYPE_U32,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_DIV,    100,     UNIT_DEGREESPSEC,   0,   300,             0,               1500,            NULL  ),
   VAR_ELEMENT_PARAMETER("P_LVRT_SoftwareDetectEnabled",             TYPE_U8,      PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_MITA_PROGRAMMER,    SCALE_NONE,   0,       UNIT_NONE,          0,   0,               0,               1,               NULL  ),
   VAR_ELEMENT_PARAMETER("P_LVRT_TorqueRecoveryRateMax",             TYPE_S16,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_DIV,    100,     UNIT_PCTPSEC,       0,   5000,            1000,            20000,           NULL  ),
   VAR_ELEMENT_PARAMETER("P_LVRT_TorqueRecoveryRateMin",             TYPE_S16,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_DIV,    100,     UNIT_PCTPSEC,       0,   1000,            500,             5000,            NULL  ),
   VAR_ELEMENT_PARAMETER("P_LVRT_TriggerLogEnable",                  TYPE_U8,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_NONE,   0,       UNIT_NONE,          0,   1,               0,               1,               NULL  ),
};

//-----------------------------------------------------------------------
// DEFINE BACKUPS            DEFINE BACKUPS            DEFINE BACKUPS
//-----------------------------------------------------------------------

//----------------------------------------------------------------------------------
// DEFINE VAR ARRAYS            DEFINE VAR ARRAYS            DEFINE VAR ARRAYS
//----------------------------------------------------------------------------------
char LVRT_initialValues[] =
{
   249, 97, 79, 38, 110, 212, 68, 57, 219, 218, 250, 230, 241, 142, 7, 227,
   131, 244, 23, 39, 210, 117, 249, 130, 17, 248, 45, 164, 143, 104, 244, 46,
   0
};

//-----------------------------------------------------------------------
// CREATE DATABASE VARS   CREATE DATABASE VARS   CREATE DATABASE VARS
//-----------------------------------------------------------------------

static STATUS CreateVarDbVars(void)
{
   STATUS Status;
   size_t ErrorEntry;

   Status = OS_VarDB_CreateLocals(LocalVars, sizeof(LocalVars)/sizeof(LocalVars[0]), &ErrorEntry, AppLocalParameterPosition());
   if (Status != 0)
   {
      AppSystemLog(ERR_7, MODULE_NAME"CrVL: %d,%d", Status, ErrorEntry);
      return ERR_7;
   }

   Status = OS_VarDB_CreateParameters(ParameterVars, sizeof(ParameterVars)/sizeof(ParameterVars[0]), &ErrorEntry, AppExportParameterPosition());
   if (Status != 0)
   {
      AppSystemLog(ERR_7, MODULE_NAME"CrVXP: %d,%d", Status, ErrorEntry);
      return ERR_7;
   }

   return OS_SUCCESS;
}

#define CREATE_VARDB_VARS

//-----------------------------------------------------------------------
// CREATE IO VARIABLES     CREATE IO VARIABLES     CREATE IO VARIABLES
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// ALIASES                       ALIASES                       ALIASES
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// INPUT                          INPUT                          INPUT
//-----------------------------------------------------------------------

// Create local variable
#define MODUL_INPUTS
static S32 V_GeneratorRpmLimit = 0;
static S32 V_CNV_TorqueActNm = 0;
static U32 V_LVRT_SimulateDropTime = 0;
static U8 V_LVRT_SimulateLVRT = 0;
static S16 V_LVRT_SimulateTorqueAct = 0;
static S32 V_PitchAngle = 0;
static S32 V_PitchPositionLimit = 0;
static U32 V_PitchSpeedLimit = 0;
static S32 V_TorqueLimit = 0;
static U32 V_ControllerRpm = 0;
static U8 V_Inverter_StatusLVRT = 0;
static S32 V_Operate_TorqeuDuringLVRT = 0;

//-----------------------------------------------------------------------
static struct ModulInOut ModulInputs[] =
{
   {"V_GeneratorRpmLimit",                      &V_GeneratorRpmLimit,                      sizeof(V_GeneratorRpmLimit),                      },
   {"V_CNV_TorqueActNm",                        &V_CNV_TorqueActNm,                        sizeof(V_CNV_TorqueActNm),                        },
   {"V_LVRT_SimulateDropTime",                  &V_LVRT_SimulateDropTime,                  sizeof(V_LVRT_SimulateDropTime),                  },
   {"V_LVRT_SimulateLVRT",                      &V_LVRT_SimulateLVRT,                      sizeof(V_LVRT_SimulateLVRT),                      },
   {"V_LVRT_SimulateTorqueAct",                 &V_LVRT_SimulateTorqueAct,                 sizeof(V_LVRT_SimulateTorqueAct),                 },
   {"V_PitchAngle",                             &V_PitchAngle,                             sizeof(V_PitchAngle),                             },
   {"V_PitchPositionLimit",                     &V_PitchPositionLimit,                     sizeof(V_PitchPositionLimit),                     },
   {"V_PitchSpeedLimit",                        &V_PitchSpeedLimit,                        sizeof(V_PitchSpeedLimit),                        },
   {"V_TorqueLimit",                            &V_TorqueLimit,                            sizeof(V_TorqueLimit),                            },
   {"V_ControllerRpm",                          &V_ControllerRpm,                          sizeof(V_ControllerRpm),                          },
   {"V_Inverter_StatusLVRT",                    &V_Inverter_StatusLVRT,                    sizeof(V_Inverter_StatusLVRT),                    },
   {"V_Operate_TorqeuDuringLVRT",               &V_Operate_TorqeuDuringLVRT,               sizeof(V_Operate_TorqeuDuringLVRT),               },
};

//-----------------------------------------------------------------------
// Check variable type
static STATUS VarsReadReturnStatus;
static type_t ReadVarType = TYPE_NONE;
static void VarsReadTypeCheck(void)
{
   (void)VarsReadReturnStatus;
   (void)ReadVarType;
   VERIFY_INPUT_REF_ID(S32,       ModulInputs[0].Name,                      ModulInputs[0].Id)
   VERIFY_INPUT_REF_ID(S32,       ModulInputs[1].Name,                      ModulInputs[1].Id)
   VERIFY_INPUT_REF_ID(U32,       ModulInputs[2].Name,                      ModulInputs[2].Id)
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[3].Name,                      ModulInputs[3].Id)
   VERIFY_INPUT_REF_ID(S16,       ModulInputs[4].Name,                      ModulInputs[4].Id)
   VERIFY_INPUT_REF_ID(S32,       ModulInputs[5].Name,                      ModulInputs[5].Id)
   VERIFY_INPUT_REF_ID(S32,       ModulInputs[6].Name,                      ModulInputs[6].Id)
   VERIFY_INPUT_REF_ID(U32,       ModulInputs[7].Name,                      ModulInputs[7].Id)
   VERIFY_INPUT_REF_ID(S32,       ModulInputs[8].Name,                      ModulInputs[8].Id)
   VERIFY_INPUT_REF_ID(U32,       ModulInputs[9].Name,                      ModulInputs[9].Id)
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[10].Name,                     ModulInputs[10].Id)
   VERIFY_INPUT_REF_ID(S32,       ModulInputs[11].Name,                     ModulInputs[11].Id)
}

#undef MODUL_INPUTS
#define MODUL_INPUTS_SIZE (sizeof(ModulInputs)/sizeof(ModulInputs[0]))

//------------------------------------------------------------------------------------------
// READ/WRITE VARDB ARRAY      READ/WRITE VARDB ARRAY      READ/WRATE VARDB ARRAY
//------------------------------------------------------------------------------------------


//-----------------------------------------------------------------------
// PARAMETER                    PARAMETER                    PARAMETER
//-----------------------------------------------------------------------

// Create local variable
#define MODUL_PARAMETERS
static U8 P_LVRT_Enable = 0;
static U8 P_LVRT_HardwareDetectEnabled = 0;
static U8 P_LVRT_InverterDetectEnabled = 0;
static U32 P_LVRT_MaxDurationTime = 0;
static U16 P_LVRT_PitchAngleFactor0Deg = 0;
static U16 P_LVRT_PitchAngleFactor10Deg = 0;
static U16 P_LVRT_PitchAngleFactor12Deg = 0;
static U16 P_LVRT_PitchAngleFactor14Deg = 0;
static U16 P_LVRT_PitchAngleFactor16Deg = 0;
static U16 P_LVRT_PitchAngleFactor18Deg = 0;
static U16 P_LVRT_PitchAngleFactor20Deg = 0;
static U16 P_LVRT_PitchAngleFactor2Deg = 0;
static U16 P_LVRT_PitchAngleFactor4Deg = 0;
static U16 P_LVRT_PitchAngleFactor6Deg = 0;
static U16 P_LVRT_PitchAngleFactor8Deg = 0;
static U32 P_LVRT_PitchBackTime0Pct = 0;
static U32 P_LVRT_PitchBackTime100Pct = 0;
static U32 P_LVRT_PitchBackTime10Pct = 0;
static U32 P_LVRT_PitchBackTime20Pct = 0;
static U32 P_LVRT_PitchBackTime30Pct = 0;
static U32 P_LVRT_PitchBackTime40Pct = 0;
static U32 P_LVRT_PitchBackTime50Pct = 0;
static U32 P_LVRT_PitchBackTime60Pct = 0;
static U32 P_LVRT_PitchBackTime70Pct = 0;
static U32 P_LVRT_PitchBackTime80Pct = 0;
static U32 P_LVRT_PitchBackTime90Pct = 0;
static U32 P_LVRT_PitchDelay = 0;
static U32 P_LVRT_PitchRecoveryRpm = 0;
static U32 P_LVRT_PitchSpeed = 0;
static U8 P_LVRT_SoftwareDetectEnabled = 0;
static S16 P_LVRT_TorqueRecoveryRateMax = 0;
static S16 P_LVRT_TorqueRecoveryRateMin = 0;
static U8 P_LVRT_TriggerLogEnable = 0;
static S32 P_PitchStopPosition = 0;



//-----------------------------------------------------------------------
static struct ModulInOut ModulParameters0[] =
{
   {"P_LVRT_Enable",                            &P_LVRT_Enable,                            sizeof(P_LVRT_Enable),                            },
   {"P_LVRT_HardwareDetectEnabled",             &P_LVRT_HardwareDetectEnabled,             sizeof(P_LVRT_HardwareDetectEnabled),             },
   {"P_LVRT_InverterDetectEnabled",             &P_LVRT_InverterDetectEnabled,             sizeof(P_LVRT_InverterDetectEnabled),             },
   {"P_LVRT_MaxDurationTime",                   &P_LVRT_MaxDurationTime,                   sizeof(P_LVRT_MaxDurationTime),                   },
   {"P_LVRT_PitchAngleFactor0Deg",              &P_LVRT_PitchAngleFactor0Deg,              sizeof(P_LVRT_PitchAngleFactor0Deg),              },
   {"P_LVRT_PitchAngleFactor10Deg",             &P_LVRT_PitchAngleFactor10Deg,             sizeof(P_LVRT_PitchAngleFactor10Deg),             },
   {"P_LVRT_PitchAngleFactor12Deg",             &P_LVRT_PitchAngleFactor12Deg,             sizeof(P_LVRT_PitchAngleFactor12Deg),             },
   {"P_LVRT_PitchAngleFactor14Deg",             &P_LVRT_PitchAngleFactor14Deg,             sizeof(P_LVRT_PitchAngleFactor14Deg),             },
   {"P_LVRT_PitchAngleFactor16Deg",             &P_LVRT_PitchAngleFactor16Deg,             sizeof(P_LVRT_PitchAngleFactor16Deg),             },
   {"P_LVRT_PitchAngleFactor18Deg",             &P_LVRT_PitchAngleFactor18Deg,             sizeof(P_LVRT_PitchAngleFactor18Deg),             },
   {"P_LVRT_PitchAngleFactor20Deg",             &P_LVRT_PitchAngleFactor20Deg,             sizeof(P_LVRT_PitchAngleFactor20Deg),             },
   {"P_LVRT_PitchAngleFactor2Deg",              &P_LVRT_PitchAngleFactor2Deg,              sizeof(P_LVRT_PitchAngleFactor2Deg),              },
   {"P_LVRT_PitchAngleFactor4Deg",              &P_LVRT_PitchAngleFactor4Deg,              sizeof(P_LVRT_PitchAngleFactor4Deg),              },
   {"P_LVRT_PitchAngleFactor6Deg",              &P_LVRT_PitchAngleFactor6Deg,              sizeof(P_LVRT_PitchAngleFactor6Deg),              },
   {"P_LVRT_PitchAngleFactor8Deg",              &P_LVRT_PitchAngleFactor8Deg,              sizeof(P_LVRT_PitchAngleFactor8Deg),              },
   {"P_LVRT_PitchBackTime0Pct",                 &P_LVRT_PitchBackTime0Pct,                 sizeof(P_LVRT_PitchBackTime0Pct),                 },
   {"P_LVRT_PitchBackTime100Pct",               &P_LVRT_PitchBackTime100Pct,               sizeof(P_LVRT_PitchBackTime100Pct),               },
   {"P_LVRT_PitchBackTime10Pct",                &P_LVRT_PitchBackTime10Pct,                sizeof(P_LVRT_PitchBackTime10Pct),                },
   {"P_LVRT_PitchBackTime20Pct",                &P_LVRT_PitchBackTime20Pct,                sizeof(P_LVRT_PitchBackTime20Pct),                },
   {"P_LVRT_PitchBackTime30Pct",                &P_LVRT_PitchBackTime30Pct,                sizeof(P_LVRT_PitchBackTime30Pct),                },
   {"P_LVRT_PitchBackTime40Pct",                &P_LVRT_PitchBackTime40Pct,                sizeof(P_LVRT_PitchBackTime40Pct),                },
   {"P_LVRT_PitchBackTime50Pct",                &P_LVRT_PitchBackTime50Pct,                sizeof(P_LVRT_PitchBackTime50Pct),                },
   {"P_LVRT_PitchBackTime60Pct",                &P_LVRT_PitchBackTime60Pct,                sizeof(P_LVRT_PitchBackTime60Pct),                },
   {"P_LVRT_PitchBackTime70Pct",                &P_LVRT_PitchBackTime70Pct,                sizeof(P_LVRT_PitchBackTime70Pct),                },
   {"P_LVRT_PitchBackTime80Pct",                &P_LVRT_PitchBackTime80Pct,                sizeof(P_LVRT_PitchBackTime80Pct),                },
   {"P_LVRT_PitchBackTime90Pct",                &P_LVRT_PitchBackTime90Pct,                sizeof(P_LVRT_PitchBackTime90Pct),                },
   {"P_LVRT_PitchDelay",                        &P_LVRT_PitchDelay,                        sizeof(P_LVRT_PitchDelay),                        },
   {"P_LVRT_PitchRecoveryRpm",                  &P_LVRT_PitchRecoveryRpm,                  sizeof(P_LVRT_PitchRecoveryRpm),                  },
   {"P_LVRT_PitchSpeed",                        &P_LVRT_PitchSpeed,                        sizeof(P_LVRT_PitchSpeed),                        },
   {"P_LVRT_SoftwareDetectEnabled",             &P_LVRT_SoftwareDetectEnabled,             sizeof(P_LVRT_SoftwareDetectEnabled),             },
   {"P_LVRT_TorqueRecoveryRateMax",             &P_LVRT_TorqueRecoveryRateMax,             sizeof(P_LVRT_TorqueRecoveryRateMax),             },
   {"P_LVRT_TorqueRecoveryRateMin",             &P_LVRT_TorqueRecoveryRateMin,             sizeof(P_LVRT_TorqueRecoveryRateMin),             },
   {"P_LVRT_TriggerLogEnable",                  &P_LVRT_TriggerLogEnable,                  sizeof(P_LVRT_TriggerLogEnable),                  },
   {"P_PitchStopPosition",                      &P_PitchStopPosition,                      sizeof(P_PitchStopPosition),                      },

};
static struct ModulInOut* ModulParameters[] =
{
   ModulParameters0,
};

//-----------------------------------------------------------------------
// Check variable type
static STATUS ParaVarsReadReturnStatus;
static type_t ParaReadVarType = TYPE_NONE;
static void ParaVarsReadTypeCheck(void)
{
   (void)ParaVarsReadReturnStatus;
   (void)ParaReadVarType;
}

#undef MODUL_PARAMETERS

#define PARAMETERS_GROUPS_SIZE        1
#define GENERAL_GROUP                 0
#define MODUL_PARAMETERS_TOTAL_SIZE   34
static SUBSCRIPTION ParaSubscription[MODUL_PARAMETERS_TOTAL_SIZE];
static U8 ReadParameters[PARAMETERS_GROUPS_SIZE];
static U8 ParametersChanged[PARAMETERS_GROUPS_SIZE];
static UNSIGNED GroupsIndexes[PARAMETERS_GROUPS_SIZE];
static int ParaGroupsSizes[PARAMETERS_GROUPS_SIZE] = { 34 };
static STATUS VarDbUpdateParameter(varid_t VariableId, void* Message, U16 Length, UNSIGNED paraGroupIndex, UNSIGNED Ref2)
{
   ReadParameters[paraGroupIndex] = 1;
   ParametersChanged[paraGroupIndex] = 1;
   return OS_SUCCESS;
}
static STATUS ReadParametersFunc(int paraGroupIndex)
{
   STATUS LocalStatus;
   // Check inputdata
   if (sizeof(ModulParameters[paraGroupIndex]) == 0)
   {
      AppSystemLog(ERR_4, MODULE_NAME"Group %d ModuleParameters = 0", paraGroupIndex);
      return ERR_4;
   }
   // Read inputdata
   LocalStatus = OS_ReadVariables(ModulParameters[paraGroupIndex], ParaGroupsSizes[paraGroupIndex]);
   if (LocalStatus != 0)
   {
      AppSystemLog(11, "LocalStatus: %d", LocalStatus);
      AppSystemLog(ERR_4, MODULE_NAME"ReadParErr: group=%d element=%d elementpointer=0x%x", paraGroupIndex, LocalStatus, &ModulParameters[LocalStatus]);
      return ERR_4;
   }
   return OS_SUCCESS;
}


//-----------------------------------------------------------------------
// READ VARS FROM VARDB    READ VARS FROM VARDB    READ VARS FROM VARDB
//-----------------------------------------------------------------------

static STATUS InputReferenceRoutine(U8 ModuleState)
{
   STATUS LocalStatus = 0;

   // Read input references
   if (ModuleState >= APP_INIT3)
   {
      // Check inputdata
      if (sizeof(ModulInputs) == 0)
      {
         AppSystemLog(ERR_4, MODULE_NAME"ModuleInputs = 0");
         return ERR_4;
      }
      // Read inputdata
      LocalStatus = OS_ReadVariables(ModulInputs, MODUL_INPUTS_SIZE);
      if (LocalStatus != 0)
      {
         AppSystemLog(ERR_4, MODULE_NAME"ReadVErr: element=%d elementpointer=0x%x", LocalStatus, &ModulInputs[LocalStatus]);
         return ERR_4;
      }
   }
   // Read input parameters
   if (ModuleState == APP_INIT3)
   {
      static size_t ParaCounter = 0;
      int groupIndex;
      for (groupIndex = 0; groupIndex < PARAMETERS_GROUPS_SIZE; groupIndex++)
      {
         ParametersChanged[groupIndex] = 1;
         ReadParameters[groupIndex] = 1;
         GroupsIndexes[groupIndex] = groupIndex;

         // Check inputdata
         if (sizeof(ModulParameters[groupIndex]) == 0)
         {
            AppSystemLog(ERR_4, MODULE_NAME"Group = %d ModuleParameters = 0", groupIndex);
            return ERR_4;
         }
         // Read inputdata
         LocalStatus = OS_ReadVariables(ModulParameters[groupIndex], ParaGroupsSizes[groupIndex]);
         if (LocalStatus != 0)
         {
            AppSystemLog(ERR_4, MODULE_NAME"ReadVParaErr: group=%d element=%d elementpointer=0x%x", groupIndex, LocalStatus, &ModulParameters[groupIndex][LocalStatus]);
            return ERR_4;
         }
         int paraIndex;
         for (paraIndex = 0; paraIndex < ParaGroupsSizes[groupIndex]; paraIndex++)
         {
            LocalStatus = OS_SubHandl_SubscribeFunctionWithRef(&ParaSubscription[ParaCounter], 1, &ModulParameters[groupIndex][paraIndex].Id, &GroupsIndexes[groupIndex], &GroupsIndexes[groupIndex], VarDbUpdateParameter);
            ParaCounter++;
            if (LocalStatus != 0)
            {
               AppSystemLog(ERR_4, MODULE_NAME"Subscribe Parameter: group=%d element=%d elementpointer=0x%x", groupIndex, LocalStatus, &ModulParameters[LocalStatus]);
               return ERR_4;
            }
         }
      }
   }
   if (ModuleState == APP_RUN)
   {
      int groupIndex;
      for (groupIndex = 0; groupIndex < PARAMETERS_GROUPS_SIZE; groupIndex++)
      {
         if (ReadParameters[groupIndex])
         {
            LocalStatus = ReadParametersFunc(groupIndex);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
            ReadParameters[groupIndex] = 0;
         }
      }
   }

   return 0;
}

#define READ_VARS

//-----------------------------------------------------------------------
// OUTPUT                         OUTPUT                         OUTPUT
//-----------------------------------------------------------------------

// Create local variable
#define MODUL_OUTPUTS
static U8 V_LVRT_Active = 0;
static U8 V_LVRT_Detected = 0;
static U32 V_LVRT_DropDurationTime = 0;
static U32 V_LVRT_EventTimeOut = 0;
static S32 V_LVRT_GeneratorRpmLimit = 0;
static U16 V_LVRT_PitchAngleFactorFromTable = 0;
static U32 V_LVRT_PitchBackTime = 0;
static U32 V_LVRT_PitchBackTimeFromTable = 0;
static U8 V_LVRT_PitchMode = 0;
static S32 V_LVRT_PitchPositionLimit = 0;
static S32 V_LVRT_PitchPowersetpoint = 0;
static U32 V_LVRT_PitchRPMsetpoint = 0;
static U32 V_LVRT_PitchSpeedLimit = 0;
static S16 V_LVRT_TorqueDropMeanValuePct = 0;
static S32 V_LVRT_TorqueLimit = 0;
static S16 V_LVRT_TorqueRecoveryRatePct = 0;
static U32 V_LVRT_TorqueRecoveryTimeClaculated = 0;
static U32 V_LVRT_TorqueRecoveryTimeReal = 0;
static char V_LVRT_OperateTimerTxt[31];


//-----------------------------------------------------------------------
static struct ModulInOut ModulOutputs[] =
{
   {"V_LVRT_Active",                            &V_LVRT_Active,                            sizeof(V_LVRT_Active),                            },
   {"V_LVRT_Detected",                          &V_LVRT_Detected,                          sizeof(V_LVRT_Detected),                          },
   {"V_LVRT_DropDurationTime",                  &V_LVRT_DropDurationTime,                  sizeof(V_LVRT_DropDurationTime),                  },
   {"V_LVRT_EventTimeOut",                      &V_LVRT_EventTimeOut,                      sizeof(V_LVRT_EventTimeOut),                      },
   {"V_LVRT_GeneratorRpmLimit",                 &V_LVRT_GeneratorRpmLimit,                 sizeof(V_LVRT_GeneratorRpmLimit),                 },
   {"V_LVRT_OperateTimerTxt",                   &V_LVRT_OperateTimerTxt,                   sizeof(V_LVRT_OperateTimerTxt),                   },
   {"V_LVRT_PitchAngleFactorFromTable",         &V_LVRT_PitchAngleFactorFromTable,         sizeof(V_LVRT_PitchAngleFactorFromTable),         },
   {"V_LVRT_PitchBackTime",                     &V_LVRT_PitchBackTime,                     sizeof(V_LVRT_PitchBackTime),                     },
   {"V_LVRT_PitchBackTimeFromTable",            &V_LVRT_PitchBackTimeFromTable,            sizeof(V_LVRT_PitchBackTimeFromTable),            },
   {"V_LVRT_PitchMode",                         &V_LVRT_PitchMode,                         sizeof(V_LVRT_PitchMode),                         },
   {"V_LVRT_PitchPositionLimit",                &V_LVRT_PitchPositionLimit,                sizeof(V_LVRT_PitchPositionLimit),                },
   {"V_LVRT_PitchPowersetpoint",                &V_LVRT_PitchPowersetpoint,                sizeof(V_LVRT_PitchPowersetpoint),                },
   {"V_LVRT_PitchRPMsetpoint",                  &V_LVRT_PitchRPMsetpoint,                  sizeof(V_LVRT_PitchRPMsetpoint),                  },
   {"V_LVRT_PitchSpeedLimit",                   &V_LVRT_PitchSpeedLimit,                   sizeof(V_LVRT_PitchSpeedLimit),                   },
   {"V_LVRT_TorqueDropMeanValuePct",            &V_LVRT_TorqueDropMeanValuePct,            sizeof(V_LVRT_TorqueDropMeanValuePct),            },
   {"V_LVRT_TorqueLimit",                       &V_LVRT_TorqueLimit,                       sizeof(V_LVRT_TorqueLimit),                       },
   {"V_LVRT_TorqueRecoveryRatePct",             &V_LVRT_TorqueRecoveryRatePct,             sizeof(V_LVRT_TorqueRecoveryRatePct),             },
   {"V_LVRT_TorqueRecoveryTimeClaculated",      &V_LVRT_TorqueRecoveryTimeClaculated,      sizeof(V_LVRT_TorqueRecoveryTimeClaculated),      },
   {"V_LVRT_TorqueRecoveryTimeReal",            &V_LVRT_TorqueRecoveryTimeReal,            sizeof(V_LVRT_TorqueRecoveryTimeReal),            },
};

//-----------------------------------------------------------------------
// Check variable type
static STATUS VarsWriteReturnStatus;
static type_t WriteVarType = TYPE_NONE;
static void VarsWriteTypeCheck(void)
{
   (void)VarsWriteReturnStatus;
   (void)WriteVarType;
   VERIFY_OUTPUT_REF_ID(U8,        ModulOutputs[0].Name,                     ModulOutputs[0].Id,                       0)
   VERIFY_OUTPUT_REF_ID(U8,        ModulOutputs[1].Name,                     ModulOutputs[1].Id,                       0)
   VERIFY_OUTPUT_REF_ID(U32,       ModulOutputs[2].Name,                     ModulOutputs[2].Id,                       0)
   VERIFY_OUTPUT_REF_ID(U32,       ModulOutputs[3].Name,                     ModulOutputs[3].Id,                       0)
   VERIFY_OUTPUT_REF_ID(S32,       ModulOutputs[4].Name,                     ModulOutputs[4].Id,                       0)
   VERIFY_OUTPUT_STRING_REF_ID(STRING,     ModulOutputs[5].Name,                      ModulOutputs[5].Id, 0)
   VERIFY_OUTPUT_REF_ID(U16,       ModulOutputs[6].Name,                     ModulOutputs[6].Id,                       0)
   VERIFY_OUTPUT_REF_ID(U32,       ModulOutputs[7].Name,                     ModulOutputs[7].Id,                       0)
   VERIFY_OUTPUT_REF_ID(U32,       ModulOutputs[8].Name,                     ModulOutputs[8].Id,                       0)
   VERIFY_OUTPUT_REF_ID(U8,        ModulOutputs[9].Name,                     ModulOutputs[9].Id,                       0)
   VERIFY_OUTPUT_REF_ID(S32,       ModulOutputs[10].Name,                    ModulOutputs[10].Id,                      0)
   VERIFY_OUTPUT_REF_ID(S32,       ModulOutputs[11].Name,                    ModulOutputs[11].Id,                      0)
   VERIFY_OUTPUT_REF_ID(U32,       ModulOutputs[12].Name,                    ModulOutputs[12].Id,                      0)
   VERIFY_OUTPUT_REF_ID(U32,       ModulOutputs[13].Name,                    ModulOutputs[13].Id,                      0)
   VERIFY_OUTPUT_REF_ID(S16,       ModulOutputs[14].Name,                    ModulOutputs[14].Id,                      0)
   VERIFY_OUTPUT_REF_ID(S32,       ModulOutputs[15].Name,                    ModulOutputs[15].Id,                      0)
   VERIFY_OUTPUT_REF_ID(S16,       ModulOutputs[16].Name,                    ModulOutputs[16].Id,                      0)
   VERIFY_OUTPUT_REF_ID(U32,       ModulOutputs[17].Name,                    ModulOutputs[17].Id,                      0)
   VERIFY_OUTPUT_REF_ID(U32,       ModulOutputs[18].Name,                    ModulOutputs[18].Id,                      0)
}

#undef MODUL_OUTPUTS
#define MODUL_OUTPUTS_SIZE (sizeof(ModulOutputs)/sizeof(ModulOutputs[0]))

//-----------------------------------------------------------------------
// WRITE VARS TO VARDB     WRITE VARS TO VARDB     WRITE VARS TO VARDB
//-----------------------------------------------------------------------

static STATUS InitOutputVars(void)
{
   STATUS LocalStatus;
   // Read outputdata
   LocalStatus = OS_ReadVariables(ModulOutputs, MODUL_OUTPUTS_SIZE);
   if (LocalStatus != 0)
   {
      AppSystemLog(ERR_4, MODULE_NAME"InitErr: element=%d elementpointer=0x%x", LocalStatus, &ModulOutputs[LocalStatus]);
      return ERR_4;
   }
   return OS_SUCCESS;
}
static STATUS OutputReferenceRoutine(U8 ModuleState)
{
   STATUS LocalStatus = 0;
   // Write Outputdata
   LocalStatus = OS_WriteVariablesConditional(ModulOutputs, MODUL_OUTPUTS_SIZE);
   if (LocalStatus != 0)
   {
      AppSystemLog(ERR_5, MODULE_NAME"WriteVErr: element=%d elementpointer=0x%x", LocalStatus, &ModulOutputs[LocalStatus]);
      return ERR_5;
   }
   return 0;
}

#define WRITE_VARS

//-----------------------------------------------------------------------
// VERIFY VARIABLES CREATION                 VERIFY VARIABLES CREATION
//-----------------------------------------------------------------------

static STATUS LocalIoCheck(void)
{
   // Check if input variables exist.
   STATUS LocalStatus;

   LocalStatus = OS_DoesVariablesExist(ModulInputs, MODUL_INPUTS_SIZE);
   if (LocalStatus != 0)
   {
      AppSystemLog(ERR_1, MODULE_NAME"InputErr: %d", LocalStatus);
      AppSystemLog(ERR_1, "Name: %s", ModulInputs[LocalStatus-1].Name);
      return ERR_1;
   }
   (void)VarsReadTypeCheck();

   int groupIndex;
   for (groupIndex = 0; groupIndex < PARAMETERS_GROUPS_SIZE; groupIndex++)
   {
      LocalStatus = OS_DoesVariablesExist(ModulParameters[groupIndex], ParaGroupsSizes[groupIndex]);
      if (LocalStatus != 0)
      {
         AppSystemLog(ERR_3, MODULE_NAME"ParameterErr: %d Group:%d", LocalStatus, groupIndex);
         AppSystemLog(ERR_3, "Name: %s", ModulParameters[groupIndex][LocalStatus-1].Name);
         return ERR_3;
      }
   }
   (void)ParaVarsReadTypeCheck();

   LocalStatus = OS_DoesVariablesExist(ModulOutputs, MODUL_OUTPUTS_SIZE);
   if (LocalStatus != 0)
   {
      AppSystemLog(ERR_2, MODULE_NAME"OutputErr: %d", LocalStatus);
      AppSystemLog(ERR_2, "Name: %s", ModulOutputs[LocalStatus-1].Name);
      return ERR_2;
   }
   (void)VarsWriteTypeCheck();

   return OS_SUCCESS;
}

#define VERIFY_VARIABLES

//-----------------------------------------------------------------------
// ALLOCATE MEMORY FOR SUMMATIONS        ALLOCATE MEMORY FOR SUMMATIONS
//-----------------------------------------------------------------------


//-----------------------------------------------------------------------
// SUMMATIONS                  SUMMATIONS                  SUMMATIONS
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// DEFINE MENUS               DEFINE MENUS               DEFINE MENUS
//-----------------------------------------------------------------------



// Menu line and link to local menu
//-----------------------------------------------------------------------
static struct line_struct M_LVRTLinkToLocalMenu[] =
{
   MENU_ELEMENT_LINE_LINK("LVRT",                              PASSWORD_LEVEL_LICENCE_CUSTOMER,    "M_LVRT",                           "G_LVRT"),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_LVRTMenu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_LVRT",                           PASSWORD_LEVEL_LICENCE_CUSTOMER),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_LVRTMenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("LVRT",                              PASSWORD_LEVEL_LICENCE_CUSTOMER,    "M_"APP_ID"AppMain",                "G_"APP_ID"App"),
   MENU_ELEMENT_LINE_LINK("Status",                            PASSWORD_LEVEL_END_CUSTOMER,        "M_Status2",                        "G_LVRT"),
   MENU_ELEMENT_LINE_LINK("Parameter",                         PASSWORD_LEVEL_END_CUSTOMER,        "M_Parameter3",                     "G_LVRT"),
   MENU_ELEMENT_LINE_LINK("Service",                           PASSWORD_LEVEL_SERVICE,             "M_Service4",                       "G_LVRT"),
   MENU_ELEMENT_LINE_LINK("Debug",                             PASSWORD_LEVEL_MITA_PROGRAMMER,     "M_Debug44",                        "G_LVRT"),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_Status2Menu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_Status2",                        PASSWORD_LEVEL_END_CUSTOMER),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_Status2MenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("STATUS",                            PASSWORD_LEVEL_END_CUSTOMER,        "M_LVRT",                           "G_LVRT"),
   MENU_ELEMENT_LINE_VARRO("LVRT Occured on",                  PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_LVRT_DropStartTimeStamp",                  LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("LVRT Duration Time",               PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_LVRT_DropDurationTime",                    LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("LVRT Pitch Back Time",             PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_LVRT_PitchBackTime",                       LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("LVRT Torque Recovery Time",        PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_LVRT_TorqueRecoveryTimeReal",              LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("LVRT Torque Drop Value",           PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_LVRT_TorqueDropMeanValuePct",              LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("LVRT Torque Recovery Rate",        PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_LVRT_TorqueRecoveryRatePct",               LINE_FORMAT_NONE),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_Parameter3Menu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_Parameter3",                     PASSWORD_LEVEL_END_CUSTOMER),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_Parameter3MenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("PARAMETER",                         PASSWORD_LEVEL_END_CUSTOMER,        "M_LVRT",                           "G_LVRT"),
   MENU_ELEMENT_LINE_VARRW("LVRT Enable",                      PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_LVRT_Enable",                              LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("LVRT Pitch Speed",                 PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_LVRT_PitchSpeed",                          LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("LVRT Pitch Delay",                 PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_LVRT_PitchDelay",                          LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("LVRT Pitch Recovery Rpm",          PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_LVRT_PitchRecoveryRpm",                    LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("LVRT Torque Recovery Rate Min",    PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_LVRT_TorqueRecoveryRateMin",               LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("LVRT Torque Recovery Rate Max",    PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_LVRT_TorqueRecoveryRateMax",               LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_LINK("Pitch Back Time Table",             PASSWORD_LEVEL_END_CUSTOMER,        "M_PitchBackTable8",                "G_LVRT"),
   MENU_ELEMENT_LINE_LINK("Pitch Angle Factor Table",          PASSWORD_LEVEL_END_CUSTOMER,        "M_PitchAngleFactorTable9",         "G_LVRT"),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_PitchBackTable8Menu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_PitchBackTable8",                PASSWORD_LEVEL_END_CUSTOMER),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_PitchBackTable8MenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("PITCH BACK TIME TABLE",             PASSWORD_LEVEL_END_CUSTOMER,        "M_Parameter3",                     "G_LVRT"),
   MENU_ELEMENT_LINE_VARRW("LVRT Pitch Back Time 0 Pct",       PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_LVRT_PitchBackTime0Pct",                   LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("LVRT Pitch Back Time 10 Pct",      PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_LVRT_PitchBackTime10Pct",                  LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("LVRT Pitch Back Time 20 Pct",      PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_LVRT_PitchBackTime20Pct",                  LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("LVRT Pitch Back Time 30 Pct",      PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_LVRT_PitchBackTime30Pct",                  LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("LVRT Pitch Back Time 40 Pct",      PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_LVRT_PitchBackTime40Pct",                  LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("LVRT Pitch Back Time 50 Pct",      PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_LVRT_PitchBackTime50Pct",                  LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("LVRT Pitch Back Time 60 Pct",      PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_LVRT_PitchBackTime60Pct",                  LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("LVRT Pitch Back Time 70 Pct",      PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_LVRT_PitchBackTime70Pct",                  LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("LVRT Pitch Back Time 80 Pct",      PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_LVRT_PitchBackTime80Pct",                  LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("LVRT Pitch Back Time 90 Pct",      PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_LVRT_PitchBackTime90Pct",                  LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("LVRT Pitch Back Time 100 Pct",     PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_LVRT_PitchBackTime100Pct",                 LINE_FORMAT_NONE),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_PitchAngleFactorTable9Menu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_PitchAngleFactorTable9",         PASSWORD_LEVEL_END_CUSTOMER),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_PitchAngleFactorTable9MenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("PITCH ANGLE FACTOR TABLE",          PASSWORD_LEVEL_END_CUSTOMER,        "M_Parameter3",                     "G_LVRT"),
   MENU_ELEMENT_LINE_VARRW("LVRT Pitch Angle Factor 0 Deg",    PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_LVRT_PitchAngleFactor0Deg",                LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("LVRT Pitch Angle Factor 2 Deg",    PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_LVRT_PitchAngleFactor2Deg",                LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("LVRT Pitch Angle Factor 4 Deg",    PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_LVRT_PitchAngleFactor4Deg",                LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("LVRT Pitch Angle Factor 6 Deg",    PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_LVRT_PitchAngleFactor6Deg",                LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("LVRT Pitch Angle Factor 8 Deg",    PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_LVRT_PitchAngleFactor8Deg",                LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("LVRT Pitch Angle Factor 10 Deg",   PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_LVRT_PitchAngleFactor10Deg",               LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("LVRT Pitch Angle Factor 12 Deg",   PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_LVRT_PitchAngleFactor12Deg",               LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("LVRT Pitch Angle Factor 14 Deg",   PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_LVRT_PitchAngleFactor14Deg",               LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("LVRT Pitch Angle Factor 16 Deg",   PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_LVRT_PitchAngleFactor16Deg",               LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("LVRT Pitch Angle Factor 18 Deg",   PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_LVRT_PitchAngleFactor18Deg",               LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("LVRT Pitch Angle Factor 20 Deg",   PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_LVRT_PitchAngleFactor20Deg",               LINE_FORMAT_NONE),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_Service4Menu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_Service4",                       PASSWORD_LEVEL_SERVICE),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_Service4MenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("SERVICE",                           PASSWORD_LEVEL_SERVICE,             "M_LVRT",                           "G_LVRT"),
   MENU_ELEMENT_LINE_VARRW("LVRT Simulate Actual Torque",      PASSWORD_LEVEL_SERVICE,             (char*)"V_LVRT_SimulateTorqueAct",                   LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("LVRT Simulate Drop Time",          PASSWORD_LEVEL_SERVICE,             (char*)"V_LVRT_SimulateDropTime",                    LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("LVRT Simulate Now",                PASSWORD_LEVEL_SERVICE,             (char*)"V_LVRT_SimulateLVRT",                        LINE_FORMAT_NONE),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_Debug44Menu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_Debug44",                        PASSWORD_LEVEL_MITA_PROGRAMMER),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_Debug44MenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("DEBUG",                             PASSWORD_LEVEL_MITA_PROGRAMMER,     "M_LVRT",                           "G_LVRT"),
   MENU_ELEMENT_LINE_VARRO("P_LVRT_TriggerLogEnable",          PASSWORD_LEVEL_MITA_PROGRAMMER,     (char*)"P_LVRT_TriggerLogEnable",                    LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("P_LVRT_MaxDurationTime",           PASSWORD_LEVEL_MITA_PROGRAMMER,     (char*)"P_LVRT_MaxDurationTime",                     LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("V_LVRT_PitchBackTimeFromTable",    PASSWORD_LEVEL_MITA_PROGRAMMER,     (char*)"V_LVRT_PitchBackTimeFromTable",              LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("V_LVRT_PitchAngleFactorFromTable", PASSWORD_LEVEL_MITA_PROGRAMMER,     (char*)"V_LVRT_PitchAngleFactorFromTable",           LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("V_LVRT_TorqueRecoveryTimeClaculated", PASSWORD_LEVEL_MITA_PROGRAMMER,     (char*)"V_LVRT_TorqueRecoveryTimeClaculated",        LINE_FORMAT_NONE),
};
// Creating parameters for multiplexed categories
//-----------------------------------------------------------------------
static struct multiplexed_info_struct M_LVRTMultiplexedCategoriesParameters[] =
{
0};

//-----------------------------------------------------------------------
// CREATE MENUS               CREATE MENUS               CREATE MENUS
//-----------------------------------------------------------------------

// Memory reservation
//-----------------------------------------------------------------------
static struct menu_group_struct ObjGroup[1];

// Creating the menus
//-----------------------------------------------------------------------
STATUS LVRTMenuAppInit(U8 ModuleState, OS_MEMORY_POOL* pPool)
{
   STATUS Status;

   if (ModuleState == APP_INIT1)
   {
      /* Create application group */
      Status = OS_CreateMenuGroup(ObjGroup, M_LVRTLinkToLocalMenu[0].LinkGroup);
      STATUS_LINE_VAR_RETURN_VALUE(Status);
   }

   Status = CreateAndInitializeMenu(ModuleState,
                                    M_LVRTMenuLines[0].LinkGroup,
                                    M_LVRTMenuLines[0].LinkName,
                                    ELEMENT(M_LVRTLinkToLocalMenu),
                                    M_LVRTLinkToLocalMenu[0].LinkGroup,
                                    ELEMENT(M_LVRTMenu),
                                    M_LVRTLinkToLocalMenu[0].LinkName,
                                    ELEMENT(M_LVRTMenuLines),
                                    pPool,
                                    M_LVRTMultiplexedCategoriesParameters);
   STATUS_LINE_VAR_RETURN_VALUE(Status);

   Status = CreateAndInitializeMenu(ModuleState,
                                    M_Status2MenuLines[0].LinkGroup,
                                    M_Status2MenuLines[0].LinkName,
                                    NULL,
                                    0,
                                    M_LVRTMenuLines[1].LinkGroup,
                                    ELEMENT(M_Status2Menu),
                                    M_LVRTMenuLines[1].LinkName,
                                    ELEMENT(M_Status2MenuLines),
                                    pPool,
                                    M_LVRTMultiplexedCategoriesParameters);
   STATUS_LINE_VAR_RETURN_VALUE(Status);

   Status = CreateAndInitializeMenu(ModuleState,
                                    M_Parameter3MenuLines[0].LinkGroup,
                                    M_Parameter3MenuLines[0].LinkName,
                                    NULL,
                                    0,
                                    M_LVRTMenuLines[2].LinkGroup,
                                    ELEMENT(M_Parameter3Menu),
                                    M_LVRTMenuLines[2].LinkName,
                                    ELEMENT(M_Parameter3MenuLines),
                                    pPool,
                                    M_LVRTMultiplexedCategoriesParameters);
   STATUS_LINE_VAR_RETURN_VALUE(Status);

   Status = CreateAndInitializeMenu(ModuleState,
                                    M_PitchBackTable8MenuLines[0].LinkGroup,
                                    M_PitchBackTable8MenuLines[0].LinkName,
                                    NULL,
                                    0,
                                    M_Parameter3MenuLines[7].LinkGroup,
                                    ELEMENT(M_PitchBackTable8Menu),
                                    M_Parameter3MenuLines[7].LinkName,
                                    ELEMENT(M_PitchBackTable8MenuLines),
                                    pPool,
                                    M_LVRTMultiplexedCategoriesParameters);
   STATUS_LINE_VAR_RETURN_VALUE(Status);

   Status = CreateAndInitializeMenu(ModuleState,
                                    M_PitchAngleFactorTable9MenuLines[0].LinkGroup,
                                    M_PitchAngleFactorTable9MenuLines[0].LinkName,
                                    NULL,
                                    0,
                                    M_Parameter3MenuLines[8].LinkGroup,
                                    ELEMENT(M_PitchAngleFactorTable9Menu),
                                    M_Parameter3MenuLines[8].LinkName,
                                    ELEMENT(M_PitchAngleFactorTable9MenuLines),
                                    pPool,
                                    M_LVRTMultiplexedCategoriesParameters);
   STATUS_LINE_VAR_RETURN_VALUE(Status);

   Status = CreateAndInitializeMenu(ModuleState,
                                    M_Service4MenuLines[0].LinkGroup,
                                    M_Service4MenuLines[0].LinkName,
                                    NULL,
                                    0,
                                    M_LVRTMenuLines[3].LinkGroup,
                                    ELEMENT(M_Service4Menu),
                                    M_LVRTMenuLines[3].LinkName,
                                    ELEMENT(M_Service4MenuLines),
                                    pPool,
                                    M_LVRTMultiplexedCategoriesParameters);
   STATUS_LINE_VAR_RETURN_VALUE(Status);

   Status = CreateAndInitializeMenu(ModuleState,
                                    M_Debug44MenuLines[0].LinkGroup,
                                    M_Debug44MenuLines[0].LinkName,
                                    NULL,
                                    0,
                                    M_LVRTMenuLines[4].LinkGroup,
                                    ELEMENT(M_Debug44Menu),
                                    M_LVRTMenuLines[4].LinkName,
                                    ELEMENT(M_Debug44MenuLines),
                                    pPool,
                                    M_LVRTMultiplexedCategoriesParameters);
   STATUS_LINE_VAR_RETURN_VALUE(Status);

   return OS_SUCCESS;
}

#define CREATE_MENU

//-----------------------------------------------------------------------
//               BUTTONS FUNCTIONS FORWARD DECLARATIONS
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// BUTTONS                       BUTTONS                      BUTTONS
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
//             SET/RESET FUNCTIONS FORWARD DECLARATIONS
//-----------------------------------------------------------------------
static U8 StatusSetFunc5039(void);
static U8 StatusResetFunc5039(void);
//-----------------------------------------------------------------------
// STATUSCODES                 STATUSCODES                 STATUSCODES
//-----------------------------------------------------------------------

static struct sts_statuscode_structure StatusCodes[] =
{
   STS_CODE_ELEMENT("LVRT active",            20*SEC,    5039,      STATUSCODE_UPDATE_TYPE_POLLING,         PASSWORD_LEVEL_SERVICE,            STATUSCODE_TIMER_TYPE_CONSTANT,     STATUSCODE_TIMER_TYPE_CONSTANT,     STATUSCODE_RESET_TYPE_AUTOMATIC,    STATUSCODE_PRIORITY_LOW,       27,   1,    32,   NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         StatusSetFunc5039,       StatusResetFunc5039,     BRAKE_PROG_0,        BRAKE_PROG_0,        BRAKE_PROG_MAX,      NULL,                PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    YAW_PROG_0,          YAW_PROG_0,          YAW_PROG_240,        NULL,                PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,    0,    255,  NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            1,  PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      20,        20,        1000,      NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         SETDELAY_MIN,   SETDELAY_MAX,   NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         RESETDELAY_MIN, RESETDELAY_MAX, NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         REPEATTIMES_MIN,     REPEATTIMES_MAX,     NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         REPEATPERIOD_MIN,    REPEATPERIOD_MAX,    NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         REPEATCODE_MIN,      REPEATCODE_MAX,      NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         TIMEOUTPERIOD_MIN,   TIMEOUTPERIOD_MAX,   NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         TIMEOUTCODE_MIN,     TIMEOUTCODE_MAX,     NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         NULL),
};

static STATUS_CODE_CONTROL_BLOCK StatusCodeControlBlock;

static STATUS LocalStatusCodeInit(void)
{
   STATUS LocalStatus;

   LocalStatus = OS_StatusCodeInit(STATUSCODE_INTERFACE_VERSION,
                                   &StatusCodeControlBlock,
                                   StatusCodes,
                                   sizeof(StatusCodes)/sizeof(StatusCodes[0]),
                                   AppLocalParameterPosition(),
                                   AppBackupPosition());
   STATUS_LINE_VAR_RETURN_CONST(LocalStatus, ERR_3);

   return OS_SUCCESS;
}

#define CREATE_STATUS_CODES

//-----------------------------------------------------------------------
// MODIFIABLE                  MODIFIABLE                   MODIFIABLE
//-----------------------------------------------------------------------

extern const char LVRTAppGroupName[];
extern const char LVRTAppMenuName[];

static void Init_Structures_From_Conf_File(void)
{
   M_LVRTMenuLines[0].LinkName = (char*)LVRTAppMenuName;
   M_LVRTMenuLines[0].LinkGroup = (char*)LVRTAppGroupName;
}

//-----------------------------------------------------------------------
// AUTOGENERATED END        AUTOGENERATED END        AUTOGENERATED END
//-----------------------------------------------------------------------
//}

#undef AUTOGENERATED_PART

//-----------------------------------------------------------------------
// USER DEFINITIONS         USER DEFINITIONS         USER DEFINITIONS
//-----------------------------------------------------------------------
//-----------------------------------------------------------------------
#define OPERATE_SOURCE_CODE
//-----------------------------------------------------------------------
#ifndef OPERATE_SOURCE_CODE
// Define for Actual Operate State numeric values used for Gateway OPC / third parity Modbus client
#define GW_LVRT 3000
//-----------------------------------------------------------------------
// LVRT Event
struct EventTextStruct EventText_OperateLVRT                  = {0, NULL};
LocalStatus += GetEventNumber(&EventText_OperateLVRT              , "LVRT"               );
//-----------------------------------------------------------------------
// Variable to store Operate state before LVRT (OperationG1 or TorqueTableChangeOperG1)
static void (*OperateStateBeforeLVRT)(U8 InitState) = 0;
//-----------------------------------------------------------------------
// Condition to change Operate state to LVRT
if (V_LVRT_Active)
{
   OperateStateBeforeLVRT = OperateState;
   OperateState = LVRTState;
}
//-----------------------------------------------------------------------
void LVRTState(U8 InitState)
{
   if(InitState)
   {
      UserEvent(EventText_OperateLVRT);
      strcpy(V_ActualOperateStateTxt,"LVRT");
      strcpy(V_ActualOperateStepTxt, "None" );
      V_ActualOperateStateGW = GW_LVRT;
      
      V_InverterMode       = INVERTER_RUN;
      V_MDSRequestMode     = MODE_OPERATE;
      
      // Set generator brake
      SetGeneratorBrake(BRAKE_OPEN);
   }

   //--------------------------------------------------
   // Wait for MDS to enter state OPERATE as requested
   // if operate waits "too long" for MDS, then set a statuscode
   //--------------------------------------------------
   if (V_MDSCurrentMode != MODE_OPERATE)
   {
	  S8 TimerExpired = StandardTimer(&MDSRequestTimeoutIntervalTimer);
	  if (TimerExpired != TIMER_NONE_END)
	  {
	     (void) OS_ActivateStatusCode(2612);
	  }
	  return;
   }
   
   // Update Display values
   strcpy(V_ActualOperateTimerTxt,V_LVRT_OperateTimerTxt);
   V_EventTimeOut = V_LVRT_EventTimeOut;
   
   // Update Pitch controller
   V_PitchMode          = V_LVRT_PitchMode;
   V_PitchPositionLimit = V_LVRT_PitchPositionLimit;
   V_PitchSpeedLimit    = V_LVRT_PitchSpeedLimit;
   V_GeneratorRpmLimit  = V_LVRT_GeneratorRpmLimit;
   //V_PitchRPMsetpoint   = GenRpm2RotRpm(V_GeneratorRpmLimit);
   //V_PitchPowersetpoint = V_LVRT_PitchPowersetpoint;

   // Update Torque controller
   V_TorqueLimit        = V_LVRT_TorqueLimit;

   // Check for different actions :
   // ------------------------------------------
   if (!V_LVRT_Active)
   {
      OperateState = OperateStateBeforeLVRT;
   }
}
#endif
//-----------------------------------------------------------------------
//-----------------------------------------------------------------------
// SET/RESET FUNCTIONS    SET/RESET FUNCTIONS    SET/RESET FUNCTIONS
//-----------------------------------------------------------------------
//-----------------------------------------------------------------------
static U8 StatusSetFunc5039(void)
{
   if (!P_LVRT_Enable)
      return 0;
   
   return V_LVRT_Active;
}
//-----------------------------------------------------------------------
static U8 StatusResetFunc5039(void)
{
   return !StatusSetFunc5039();
}
//-----------------------------------------------------------------------
//-----------------------------------------------------------------------
// DRIVER FUNCTION         DRIVER FUNCTION         DRIVER FUNCTION
//-----------------------------------------------------------------------
  
//-----------------------------------------------------------------------
// INIT                   INIT                     INIT
//-----------------------------------------------------------------------
//-----------------------------------------------------------------------
#define PITCH_BACK         101
#define PITCH_HOLD         102
#define PITCH_RECOVERY     103
#define PITCH_AUTO         104
#define TORQUE_DROP        201
#define TORQUE_RECOVERY    202
#define TORQUE_AUTO        203
//-----------------------------------------------------------------------
static time_t V_LVRT_DropStartTimeStamp    = 0;
//-----------------------------------------------------------------------
static U8  FirstTime                       = 0;               // Global flag, works on first scan when LVRT occured
static S32 LVRT_SavedPichAngle             = 0;
static S16 LVRT_SavedInverterTorqueAct     = 0;
static S32 LVRT_SavedGeneratorRpmLimit     = 0;
static U32 LVRT_SavedPitchRPMsetpoint      = 0;
static S32 LVRT_SavedPitchPowersetpoint    = 0;
static U32 LVRT_SavedPitchSpeedLimit       = 0;
static S32 LVRT_SavedPitchPositionLimit    = 0;
static U8  PitchStep                       = PITCH_BACK;
static U8  TorqueStep                      = TORQUE_DROP;
static U8  PitchRecovered                  = 0;
static U8  TorqueRecovered                 = 0;
static S32 LVRT_TorqueRecoveryRateNm       = 0;
static S32 LVRT_SavedTorqueLimit           = 0;
static S16 LVRT_IntermediateTorque_3       = 0;
static S16 LVRT_IntermediateTorque_2       = 0;
static S16 LVRT_IntermediateTorque_1       = 0;
static S32 LVRT_TorqueRecoveryRatePct_Temp = 0;
//-----------------------------------------------------------------------
//-----------------------------------------------------------------------
// CONTROL                CONTROL                 CONTROL
//-----------------------------------------------------------------------
U8 SoftwareDetect(void)
{
   return StatusCodeActive(5039);
}
//-----------------------------------------------------------------------
U8 HardwareDetect(void)
{
   return 0;
}
//-----------------------------------------------------------------------
U8 InverterDetect(void)
{
   return V_Inverter_StatusLVRT;
}
//-----------------------------------------------------------------------
void LVRTDetection(void)
{
   if ( (P_LVRT_SoftwareDetectEnabled && SoftwareDetect()) ||
        (P_LVRT_HardwareDetectEnabled && HardwareDetect()) ||
        (P_LVRT_InverterDetectEnabled && InverterDetect()) )
   {
      V_LVRT_Detected = 1;
   }
   else
   {
      V_LVRT_Detected = 0;
   }
}
//-----------------------------------------------------------------------
static struct StandardTimerVarStruct LVRTDropSimulatorTimer =
{
   0,                               // Timer value [ms]
   &V_LVRT_SimulateDropTime,        // TimeMax value [ms]
   TIMER_20MS,                      // Internal variable, always set to 0
   TIMER_STOP,                      // TIMER_DOWN / TIMER_STOP / TIMER_UP
   0                                // Standard timer called flag.
};
//-----------------------------------------------------------------------
void LVRTSimulation(void)
{
   if (V_LVRT_SimulateLVRT)
   {
      V_LVRT_Detected = 1;
      
      // Simulate torque drop
      V_Operate_TorqeuDuringLVRT = V_LVRT_SimulateTorqueAct;
      
      StartTimer(&LVRTDropSimulatorTimer);
      if (StandardTimer(&LVRTDropSimulatorTimer))
      {
         V_LVRT_Detected = 0;
         V_LVRT_SimulateLVRT = 0;
         OS_VarDB_UpdateVariableByName("V_LVRT_SimulateLVRT", &V_LVRT_SimulateLVRT, sizeof(V_LVRT_SimulateLVRT));
      }
   }
   else
   {
      ResetTimer(&LVRTDropSimulatorTimer);
   }
}
//-----------------------------------------------------------------------
#define PBTT_TIMES_COUNT         11
#define PBTT_MIN_TORQUE_DROP     0      //0.00%,     S32
#define PBTT_MAX_TORQUE_DROP     10000  //100.00%,   S32
#define PBTT_TORQUE_DROP_STEP    1000   //10.00%,    S32
//-----------------------------------------------------------------------
#define PAFT_FACTORS_COUNT       11
#define PAFT_MIN_ANGLE           0      //0.00deg,  S32
#define PAFT_MAX_ANGLE           2000   //20.00deg, S32
#define PAFT_ANGLE_STEP          200    //2.00deg,  S32
//-----------------------------------------------------------------------
U32 *PitchBackTimesTable[PBTT_TIMES_COUNT];
U16 *PitchAngleFactorsTable[PAFT_FACTORS_COUNT];
//-----------------------------------------------------------------------
void InitializeTables(void)
{
   PitchBackTimesTable[0]     = &P_LVRT_PitchBackTime0Pct;
   PitchBackTimesTable[1]     = &P_LVRT_PitchBackTime10Pct;
   PitchBackTimesTable[2]     = &P_LVRT_PitchBackTime20Pct;
   PitchBackTimesTable[3]     = &P_LVRT_PitchBackTime30Pct;
   PitchBackTimesTable[4]     = &P_LVRT_PitchBackTime40Pct;
   PitchBackTimesTable[5]     = &P_LVRT_PitchBackTime50Pct;
   PitchBackTimesTable[6]     = &P_LVRT_PitchBackTime60Pct;
   PitchBackTimesTable[7]     = &P_LVRT_PitchBackTime70Pct;
   PitchBackTimesTable[8]     = &P_LVRT_PitchBackTime80Pct;
   PitchBackTimesTable[9]     = &P_LVRT_PitchBackTime90Pct;
   PitchBackTimesTable[10]    = &P_LVRT_PitchBackTime100Pct;
   
   PitchAngleFactorsTable[0]  = &P_LVRT_PitchAngleFactor0Deg;
   PitchAngleFactorsTable[1]  = &P_LVRT_PitchAngleFactor2Deg;
   PitchAngleFactorsTable[2]  = &P_LVRT_PitchAngleFactor4Deg;
   PitchAngleFactorsTable[3]  = &P_LVRT_PitchAngleFactor6Deg;
   PitchAngleFactorsTable[4]  = &P_LVRT_PitchAngleFactor8Deg;
   PitchAngleFactorsTable[5]  = &P_LVRT_PitchAngleFactor10Deg;
   PitchAngleFactorsTable[6]  = &P_LVRT_PitchAngleFactor12Deg;
   PitchAngleFactorsTable[7]  = &P_LVRT_PitchAngleFactor14Deg;
   PitchAngleFactorsTable[8]  = &P_LVRT_PitchAngleFactor16Deg;
   PitchAngleFactorsTable[9]  = &P_LVRT_PitchAngleFactor18Deg;
   PitchAngleFactorsTable[10] = &P_LVRT_PitchAngleFactor20Deg;
}
//-----------------------------------------------------------------------
U32 GetPichBackTimeFromTable(S16 TorqueDrop)
{
   // Check upper & lower limit
   if (TorqueDrop <= PBTT_MIN_TORQUE_DROP)   { return *PitchBackTimesTable[0];                    }      
   if (TorqueDrop >= PBTT_MAX_TORQUE_DROP)   { return *PitchBackTimesTable[PBTT_TIMES_COUNT - 1]; }
   
   // Find in what segment torque drop fits in
   U8 LeftSeg = 0;
   U8 RightSeg = 1;
   for ( ; TorqueDrop > RightSeg * PBTT_TORQUE_DROP_STEP; LeftSeg++, RightSeg++);
   
   // Interpolate time value from the table
   //
   //                       (CurrentDrop - LowerDrop) * (UpperValue - LowerValue)
   //   Equation:   Value = ————————————————————————————————————————————————————— + LowerValue
   //                                       UpperDrop - LowerDrop
   //
   //   LaTeX:   $$ \frac{(CurrentDrop - LowerDrop)\cdot(UpperValue - LowerValue)}{UpperDrop - LowerDrop} + LowerValue $$
   //
   S32 TempTime = 0;
   TempTime = TorqueDrop - LeftSeg * PBTT_TORQUE_DROP_STEP;                                        // (CurrentDrop - LowerDrop)
   TempTime = TempTime * ((S32)*PitchBackTimesTable[RightSeg] - *PitchBackTimesTable[LeftSeg]);    // * (UpperValue - LowerValue)
   TempTime = TempTime / (RightSeg * PBTT_TORQUE_DROP_STEP - LeftSeg * PBTT_TORQUE_DROP_STEP);     // / (UpperDrop - LowerDrop)
   TempTime = TempTime + *PitchBackTimesTable[LeftSeg];                                            // + LowerValue
   
   return (U16)TempTime;
}
//-----------------------------------------------------------------------
U16 GetPitchAngleFactorFromTable(S32 Angle)
{
   // Check upper & lower limit
   if (Angle <= PAFT_MIN_ANGLE)   { return *PitchAngleFactorsTable[0];                      }      
   if (Angle >= PAFT_MAX_ANGLE)   { return *PitchAngleFactorsTable[PAFT_FACTORS_COUNT - 1]; }
   
   // Find in what segment angle fits in
   U8 LeftSeg  = 0;
   U8 RightSeg = 1;
   for ( ; Angle > RightSeg * PAFT_ANGLE_STEP; LeftSeg++, RightSeg++);
   
   // Interpolate from the table
   //
   //                      (CurrentAngle - LowerAngle) * (UpperValue - LowerValue)
   //   Equation:   Value = ——————————————————————————————————————————————————————— + LowerValue
   //                                       UpperAngle - LowerAngle
   //
   //   LaTeX:   $$ \frac{(CurrentAngle - LowerAngle)\cdot(UpperValue - LowerValue)}{UpperAngle - LowerAngle} + LowerValue $$
   //
   S32 TempFactor = 0;
   TempFactor = Angle - LeftSeg * PAFT_ANGLE_STEP;                                                          // (CurrentAngle - LowerAngle)
   TempFactor = TempFactor * ((S32)*PitchAngleFactorsTable[RightSeg] - *PitchAngleFactorsTable[LeftSeg]);   // * (UpperValue - LowerValue)
   TempFactor = TempFactor / (RightSeg * PAFT_ANGLE_STEP - LeftSeg * PAFT_ANGLE_STEP);                      // / (UpperAngle - LowerAngle)
   TempFactor = TempFactor + *PitchAngleFactorsTable[LeftSeg];                                              // + LowerValue
   
   return (U16)TempFactor;
}
//-----------------------------------------------------------------------
U32 CalculatePichBackTime(void)
{
   static U32 PitchBackTime = 0;
   static S32 TorqueDropCounter = 0;
   static S16 TorqueDropCurrentValuePct = 0;
   static S32 TorqueDropAccumulatedValuePct = 0;
   
   if (FirstTime)
   {
      // Get Pitch Angle Factor from table only once
      V_LVRT_PitchAngleFactorFromTable = GetPitchAngleFactorFromTable(LVRT_SavedPichAngle);
      
      // Reset counters
      TorqueDropAccumulatedValuePct = 0;
      TorqueDropCounter = 0;
   }
   
   // Calculate current torque drop value
   TorqueDropCurrentValuePct      = LVRT_SavedInverterTorqueAct - V_Operate_TorqeuDuringLVRT;
   
   // Calculate mean torque drop value
   if (V_LVRT_Detected)
   {
      TorqueDropAccumulatedValuePct += TorqueDropCurrentValuePct;
      TorqueDropCounter++;   
      V_LVRT_TorqueDropMeanValuePct  = TorqueDropAccumulatedValuePct / TorqueDropCounter;   
   }
   
   // Get Pitch Back Time from table based on MEAN torque drop value
   V_LVRT_PitchBackTimeFromTable = GetPichBackTimeFromTable(V_LVRT_TorqueDropMeanValuePct);
   
   // Calculate Pitch Back Time
   PitchBackTime = V_LVRT_PitchBackTimeFromTable * V_LVRT_PitchAngleFactorFromTable / 1000;//100.0%
   return PitchBackTime;
}
//-----------------------------------------------------------------------
S32 GetNm(S16 TorquePercent)
{
   S64 TempNm;
   
   TempNm  = 0; //(S64)TorquePercent * P_TorqueRatedNm;
   TempNm /= 10000;   
   
   return (S32)TempNm;
}
//-----------------------------------------------------------------------
static struct StandardTimerVarStruct LVRTMaxDurationTimer =
{
   0,                               // Timer value [ms]
   &P_LVRT_MaxDurationTime,         // TimeMax value [ms]
   TIMER_20MS,                      // Internal variable, always set to 0
   TIMER_STOP,                      // TIMER_DOWN / TIMER_STOP / TIMER_UP
   0                                // Standard timer called flag.
};
//-----------------------------------------------------------------------
void LVRTControl(void)
{
   if (V_LVRT_Detected)
   {
      V_LVRT_Active = 1;
   }
   
   if (V_LVRT_Active)
   {
      if (FirstTime)
      {
         // Set parameters which currently are not used in control algorithm
         V_LVRT_GeneratorRpmLimit  = LVRT_SavedGeneratorRpmLimit;
         V_LVRT_PitchRPMsetpoint   = LVRT_SavedPitchRPMsetpoint;
         V_LVRT_PitchPowersetpoint = LVRT_SavedPitchPowersetpoint;
         
         // Set pitch parameters, to avoid uninitialized use (maybe we don't need to pitch manually)
         //V_LVRT_PitchMode          = CTRL_AUTO;
         V_LVRT_PitchSpeedLimit    = LVRT_SavedPitchSpeedLimit;
         V_LVRT_PitchPositionLimit = LVRT_SavedPitchPositionLimit;
         
         // Save LVRT start time
         V_LVRT_DropStartTimeStamp = OS_GetTimeInMs();
         OS_VarDB_UpdateVariableByName("V_LVRT_DropStartTimeStamp", &V_LVRT_DropStartTimeStamp, sizeof(V_LVRT_DropStartTimeStamp));
         
         // Clear timer
         V_LVRT_EventTimeOut = 0;
         ResetTimer(&LVRTMaxDurationTimer);
         StartTimer(&LVRTMaxDurationTimer);
         
         // Save trigger log
         if (P_LVRT_TriggerLogEnable)
         {
            OS_TOTLOG_SetTrig();
         }
      }
      
      // Pitch Angle control
      switch (PitchStep)
      {
         case PITCH_BACK:
         {
            // Update time for pitch back in manual mode
            V_LVRT_PitchBackTime = CalculatePichBackTime();
            
            // Pitch towards stop position, if needed
            if ((U32)(OS_GetTimeInMs() - V_LVRT_DropStartTimeStamp) < V_LVRT_PitchBackTime)
            {
               //V_LVRT_PitchMode          = CTRL_MANUAL;
               V_LVRT_PitchSpeedLimit    = P_LVRT_PitchSpeed;
               V_LVRT_PitchPositionLimit = P_PitchStopPosition;
            }
            else
            {
               // Change step if pitch back time ran out or is not needed
               if (V_ControllerRpm < P_LVRT_PitchRecoveryRpm)
               {
                  if (V_LVRT_Detected)
                  {
                     PitchStep = PITCH_HOLD;
                  }
                  else
                  {
                     PitchStep = PITCH_RECOVERY;
                  }
               }
               else
               {
                  PitchStep = PITCH_AUTO;
               }
            }
            
            break;
         }
         case PITCH_HOLD:
         {
            // Hold the blades until LVRT ends
            //V_LVRT_PitchMode          = CTRL_MANUAL;
            V_LVRT_PitchSpeedLimit    = P_LVRT_PitchSpeed;
            V_LVRT_PitchPositionLimit = V_PitchAngle;
            
            // Change step when LVRT ends or we exceed max rpm
            if (V_ControllerRpm < P_LVRT_PitchRecoveryRpm)
            {
               if (!V_LVRT_Detected)
               {
                  PitchStep = PITCH_RECOVERY;
               }
            }
            else
            {
               PitchStep = PITCH_AUTO;
            }
            break;
         }
         case PITCH_RECOVERY:
         {
            // Pitch back towards angle before LVRT
            if (V_PitchAngle - 50 > LVRT_SavedPichAngle && V_ControllerRpm < P_LVRT_PitchRecoveryRpm)
            {              //- 0.5deg
               //V_LVRT_PitchMode          = CTRL_MANUAL;
               V_LVRT_PitchSpeedLimit    = P_LVRT_PitchSpeed;
               V_LVRT_PitchPositionLimit = LVRT_SavedPichAngle;
            }
            else
            {
               // Change step if angle before LVRT is reached,
               // or max rpm is exceeded
               PitchStep = PITCH_AUTO;
            }
            break;
         }
         case PITCH_AUTO:
         {
            // Restore Pitch controller
            //V_LVRT_PitchMode          = CTRL_AUTO;
            V_LVRT_PitchSpeedLimit    = LVRT_SavedPitchSpeedLimit;
            V_LVRT_PitchPositionLimit = LVRT_SavedPitchPositionLimit;
            PitchRecovered            = 1;
            
            break;
         }
      }
      
      // Torque control
      switch (TorqueStep)
      {
         case TORQUE_DROP:
         {
            // Limit torque reference with actual torque
            V_LVRT_TorqueLimit = GetNm(V_Operate_TorqeuDuringLVRT);
            
            // Update display values
            strcpy(V_LVRT_OperateTimerTxt,"Phase Drop");
            V_LVRT_EventTimeOut += 20;//20ms
            
            // Change step if voltage drop is over
            if (!V_LVRT_Detected)
            {
               // Calculate LVRT duration time
               V_LVRT_DropDurationTime  = (U32)(OS_GetTimeInMs() - V_LVRT_DropStartTimeStamp);
               
               // Calculate time left to recover torque together with pitch angle
               if (V_LVRT_PitchBackTime > 0)
               {
                  if (V_LVRT_PitchBackTime + P_LVRT_PitchDelay > V_LVRT_DropDurationTime)
                  {
                     // Duration of drop was less than pitch back time, torque recovery will start earlier than pitch recovery
                     V_LVRT_TorqueRecoveryTimeClaculated = 2 * V_LVRT_PitchBackTime + P_LVRT_PitchDelay - V_LVRT_DropDurationTime;
                  }
                  else
                  {
                     // Duration of drop was bigger than pitch back time, torque recovery will start together with pitch recovery
                     V_LVRT_TorqueRecoveryTimeClaculated = V_LVRT_PitchBackTime + P_LVRT_PitchDelay;
                  }
               }
               else
               {
                  // There was no pitch back, recover torque as fast as possible
                  V_LVRT_TorqueRecoveryTimeClaculated = 1;//1ms
               }
               
               // Calculate recovery rate in % to recover torque together with pitch angle
               LVRT_TorqueRecoveryRatePct_Temp = (LVRT_SavedInverterTorqueAct - V_Operate_TorqeuDuringLVRT) * 1000 / V_LVRT_TorqueRecoveryTimeClaculated;//per 1s
               
               // Fit recovery rate in reasonable range
               if      (LVRT_TorqueRecoveryRatePct_Temp > P_LVRT_TorqueRecoveryRateMax) { V_LVRT_TorqueRecoveryRatePct = P_LVRT_TorqueRecoveryRateMax;    }
               else if (LVRT_TorqueRecoveryRatePct_Temp < P_LVRT_TorqueRecoveryRateMin) { V_LVRT_TorqueRecoveryRatePct = P_LVRT_TorqueRecoveryRateMin;    }
               else                                                                     { V_LVRT_TorqueRecoveryRatePct = LVRT_TorqueRecoveryRatePct_Temp; }
               
               // Calculate recovery rate in Nm
               LVRT_TorqueRecoveryRateNm = GetNm(V_LVRT_TorqueRecoveryRatePct);
               
               // Set timer
               V_LVRT_EventTimeOut = V_LVRT_TorqueRecoveryTimeClaculated;
               V_LVRT_TorqueRecoveryTimeReal = 0;
               
               TorqueStep = TORQUE_RECOVERY;
            }

            break;
         }
         case TORQUE_RECOVERY:
         {
            // Ramp torque limit towards torque table value
            V_LVRT_TorqueLimit += LVRT_TorqueRecoveryRateNm / 50;//per 20ms scan
            
            // Update display values
            strcpy(V_LVRT_OperateTimerTxt,"Power Recovery");
            V_LVRT_EventTimeOut = (V_LVRT_EventTimeOut >= 20) ? V_LVRT_EventTimeOut - 20 : 0;//20ms
            V_LVRT_TorqueRecoveryTimeReal += 20;//20ms
            
            //// Change step if torque table value is reached
            //if (V_LVRT_TorqueLimit > V_TorqueSPNm)
            //{
            //   TorqueStep = TORQUE_AUTO;
            //   
            //   // Remove one obsolete scan
            //   V_LVRT_TorqueRecoveryTimeReal -= 20;//20ms
            //}
         
            break;
         }
         case TORQUE_AUTO:
         {
            // Restore Torque Limit
            V_LVRT_TorqueLimit = LVRT_SavedTorqueLimit;
            TorqueRecovered    = 1;
         }
      }
      
      // LVRT control finishes here
      if (StandardTimer(&LVRTMaxDurationTimer) || (PitchRecovered && TorqueRecovered))
      {
         V_LVRT_Active = 0;
      }
      
      // Clear first time flag
      if (FirstTime)
      {
         FirstTime = 0;
      }
   }
   else
   {
      // Save Actual Torque 60ms before LVRT
      LVRT_SavedInverterTorqueAct  = LVRT_IntermediateTorque_3;  // -60ms
      LVRT_IntermediateTorque_3    = LVRT_IntermediateTorque_2;  // -40ms
      LVRT_IntermediateTorque_2    = LVRT_IntermediateTorque_1;  // -20ms
      LVRT_IntermediateTorque_1    = V_CNV_TorqueActNm;
      
      // Save current operational conditions
      LVRT_SavedPichAngle          = V_PitchAngle;
      LVRT_SavedPitchSpeedLimit    = V_PitchSpeedLimit;
      LVRT_SavedPitchPositionLimit = V_PitchPositionLimit;
      LVRT_SavedTorqueLimit        = V_TorqueLimit;
      LVRT_SavedGeneratorRpmLimit  = V_GeneratorRpmLimit;
      //LVRT_SavedPitchRPMsetpoint   = V_PitchRPMsetpoint;
      //LVRT_SavedPitchPowersetpoint = V_PitchPowersetpoint;
      
      // Clear steps & flags for next LVRT
      if (!FirstTime)
      {
         strcpy(V_LVRT_OperateTimerTxt,"None");
         V_LVRT_EventTimeOut = 0;
         PitchStep           = PITCH_BACK;
         TorqueStep          = TORQUE_DROP;
         PitchRecovered      = 0;
         TorqueRecovered     = 0;
         FirstTime           = 1;
      }
   }
}
//-----------------------------------------------------------------------
static STATUS LocalCtrl(void)
{
   STATUS LocalStatus = 0;
   
   if (P_LVRT_Enable)
   {
      LVRTDetection();
      LVRTSimulation();
      LVRTControl();
   }
   else if (V_LVRT_SimulateLVRT) 
   {
      V_LVRT_SimulateLVRT = 0;
      OS_VarDB_UpdateVariableByName("V_LVRT_SimulateLVRT", &V_LVRT_SimulateLVRT, sizeof(V_LVRT_SimulateLVRT));
   }
   
   return LocalStatus;
} 
//-----------------------------------------------------------------------
//-----------------------------------------------------------------------
// MAIN CALL             MAIN CALL               MAIN CALL
//-----------------------------------------------------------------------
//-----------------------------------------------------------------------
STATUS LVRT(U8 ModuleState, OS_MEMORY_POOL *MemPool, U32 *Arg3)
{
   STATUS LocalStatus = 0;

   
   if(ModuleState == APP_INIT1)
   {
      LocalStatus = OS_ValidateAPI(API_VERSION_MAJOR,
                                   API_VERSION_MINOR,
                                   OS_LinkTime,
                                   ReleaseTag,
                                   __MODULE__
                                   );
      if ( OS_SUCCESS != LocalStatus )
      {
         return LocalStatus;
      }
   }
#ifdef READ_VARS
   // Read inputdata
   LocalStatus = InputReferenceRoutine(ModuleState);
   STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif
#ifdef COMMON_VDB_READ
   LocalStatus = ReadVdbWindow(ModuleState);
   STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif
   switch(ModuleState)
   {
      case APP_RUN :
      {
         #ifdef FUNCTION_BLOCKS_PRE_LOCAL_CONTROL
            LocalStatus = FunctionBlocksPreLocalCtrl( Interval );
            STATUS_LINE_VAR_RETURN_VALUE( LocalStatus );
         #endif

         LocalStatus = LocalCtrl();
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
        
         #ifdef FUNCTION_BLOCKS_POST_LOCAL_CONTROL
            LocalStatus = FunctionBlocksPostLocalCtrl( Interval );
            STATUS_LINE_VAR_RETURN_VALUE( LocalStatus );
         #endif

         
#ifdef WRITE_VARS
         // Write Outputdata
         LocalStatus = OutputReferenceRoutine(ModuleState);
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif

#ifdef COMMON_VDB_WRITE
         LocalStatus = WriteVdbWindow(ModuleState);
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif
         break;
      }
      case APP_INIT1 :
      {
         Init_Structures_From_Conf_File();

#ifdef CREATE_VARDB_VARS
         LocalStatus = CreateVarDbVars();
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif

#ifdef CREATE_MENU
         LocalStatus = LVRTMenuAppInit(ModuleState, MemPool);
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)

#ifdef MULTIPLEXIBLE_MENU
         LocalStatus = MenuArraysAppInit(ModuleState, MemPool);
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif
#endif

#ifdef CREATE_VARDB_ARRAY_VARS
         LocalStatus = CreateVdbArrays(MemPool);
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif

#ifdef CREATE_IO_VARS
         LocalStatus = CreateIOVars();
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif
         break;
      }
      case APP_INIT2 :
      {
#ifdef CREATE_MENU
#ifdef MULTIPLEXIBLE_MENU
         LocalStatus = MenuArraysAppInit(ModuleState, MemPool);
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif
#endif

#ifdef CREATE_ALIASES
         size_t ErrorEntry = 0;
         LocalStatus = OS_VarDB_CreateAliases(AliasVars, sizeof(AliasVars)/sizeof(AliasVars[0]), &ErrorEntry);
         STATUS_LINE_VAR_RETURN_CONST(LocalStatus, ErrorEntry)
#endif

#ifdef VERIFY_ARRAY
        LocalStatus = VerifyArray(MemPool);
        STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif

#ifdef VERIFY_VARIABLES
         LocalStatus = LocalIoCheck();
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif

#ifdef CREATE_BUTTONS
         LocalStatus = CreateButtons();
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif
         break;
      }
      case APP_INIT3 :
      {
#ifdef CREATE_SUMMATIONS
         LocalStatus = CreateSummations();
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif

#ifdef WRITE_VARS
         LocalStatus = InitOutputVars();
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif

#ifdef CREATE_STATUS_CODES
         LocalStatus = LocalStatusCodeInit();
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif

#ifdef CREATE_IO_VARS
        LVRTSetLockValues();
#endif
         break;
      }
      case APP_INIT4 :
      {
#ifdef CREATE_MENU
         LocalStatus = LVRTMenuAppInit(ModuleState, MemPool);
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)

#ifdef MULTIPLEXIBLE_MENU
         LocalStatus = MenuArraysAppInit(ModuleState, MemPool);
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif
#endif
         break;
      }
      case APP_INIT5 :
      {
#ifdef VALIDATE_HASH
         LocalStatus = ValidateHash(LVRT_copyright, MODULE_NAME, LVRT_initialValues);
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif

         #ifdef INIT_FUNCTION_BLOCKS
            LocalStatus = FunctionBlocksInit( Interval );
            STATUS_LINE_VAR_RETURN_VALUE( LocalStatus );
         #endif

         InitializeTables();
         
         break;
      }
      default :
      {
         break;
      }
   }
   return OS_SUCCESS;
}
//-----------------------------------------------------------------------
