//*****************************PEPTOOL Header Start******************************
//                                                                               
//                         Copyright © 2015 Mita-Teknik.                         
//This software may only be used with WP4x00 Controllers delivered by Mita-Teknik
//                                                                               
//*******************************************************************************
//                                                                               
// $PEPTOOL version:9.0$                                                         
// $PEPTOOL file version:111$                                                    
//                                                                               
//*******************************************************************************
//                                                                               
// $Date: XXXX/XX/XX XX:XX:XX $                                                  
// $Author: XXXX\XXX $                                                           
// $RCSfile: main.c,v $                                                          
// $Revision: X.X $                                                              
//                                                                               
//******************************PEPTOOL Header End*******************************
// OS header files
#include <os_main.h>
// AppLib header files
#include <lib_main.h>
// App header files
#include <turbdef.h>
#include <VarMacros.h>
// Object header file
#include <InitIo.h>
#include <main.h>
//#include <scan.h>
#include <CustomEleonScan.h>
//#include <VersionDefs.h>
//#include <ObjectsPresent.h>
#include <Version.h>
#include <os_lib.h>
#include <general.h>
#include <drivers.h>

#define AUTOGENERATED_INCLUDE

//#include <Configurator.h>
#include <DLL_simu.h>
#include <SafetySystem_MT_GL2010.h>
#include <EStopChain_MT_GL20101ExtStop.h>
#include <SafetyChain_MT_GL20102ManStop.h>
#include <VibrationMonitoringEmulator.h>
#include <SurgeProtection.h>
#include <Generator.h>
#include <TowerResonansTime.h>
//#include <WeatherSensor1.h>
#include <WeatherSensor2.h>
#include <WindSpeed.h>
#include <WindDirection.h>
#include <Wind.h>
#include <OutdoorTemperature.h>
#include <Brake.h>
#include <BladeController_emulator.h>
#include <Transformer.h>
#include <PowerReduction.h>
#include <Loss_Counter.h>
#include <PowerManagement.h>
#include <PitchAndTorque.h>
#include <Yaw_MK1.h>
#include <YawMotorControl_MK1.h>
#include <Power_Converter.h>
//#include <LiebherrConverter.h>
#include <FeConConverter_FeConGmbH_Type1.h>
#include <FeConConverter1_MT_Type1.h>
#include <FeConConverter2_MT_Type1.h>
#include <FeConConverter3_MT_Type1.h>
#include <FeConConverter4_MT_Type1.h>
#include <InverterCooling_MT_Type1.h>
#include <GeneratorCooling_MT_Type1.h>
#include <TowerBase.h>
#include <Nacelle.h>
#include <Panels.h>
#include <FlightWarningLight.h>
#include <WindRose.h>
#include <PowerCurve.h>
#include <FileInterface.h>
//#include <UPS1.h>
#include <Info.h>
#include <CMS.h>
#include <Lubrication_MT_Type1.h>
#include <Lubrication_Main_Bearing_MT_Type1.h>
#include <Lubrication_Pitch_Pinion_MT_Type1.h>
#include <LubricationYaw_MT_Type1.h>
//#include <UPS.h>
#include <FRT.h>
#include <Grid.h>
#include <AirPressure.h>
#include <WindSpeedPower_Normalization.h>
#include <Hub_MT_Type1.h>
#include <Operate_MT_Type2.h>
#include <LVRT.h>
#include <NacelleAcceleration.h>
//#include <BladeLoads_Type1.h>
//#include <Lidar.h>
#include <MainBearingPressure.h>
#include <Shutdown.h>

#define APP_CAPTION        N_("Application")
#define APP_RETURN_CAPTION N_("APPLICATION")
#define APP_MENU_NAME      "M_"APP_ID"AppMain"
#define APP_GROUP_NAME     "G_"APP_ID"App"

//extern U32 FeConConverter_FeConGmbH_Type1CallStatus;
//extern U32 LiebherrConverterCallStatus;
//extern U32 FeConConverter1_MT_Type1CallStatus;
//extern U32 FeConConverter2_MT_Type1CallStatus;
//extern U32 FeConConverter3_MT_Type1CallStatus;
//extern U32 FeConConverter4_MT_Type1CallStatus;
//extern U32 InverterCooling_MT_Type1CallStatus;

#undef AUTOGENERATED_INCLUDE

#define AUTOGENERATED_SET_VALUES

const char CP1_NAME[] = "Brake Program";
const char CP2_NAME[] = "Yaw Program";
const char CP3_NAME[] = "Alarm Program";

#undef AUTOGENERATED_SET_VALUES

//This mode must be verified before setting constant to 1
const U8 StartAppTaskBeforeInitRounds = 0;

#define APPSYSLOGCODE       50000
#define APPEVENTLOGCODE     50000

#ifdef CODESYS
#include "VectorList.h"
#endif

#ifndef TRG_X86

#define MITA_EXP_DECL

#define OS_VECTOR_TABEL 0x200

struct OS_Services *OS_SERVICES = (struct OS_Services *)OS_VECTOR_TABEL;

#else

struct OS_Services __OS_SERVICES = {4, 8};
struct OS_Services *OS_SERVICES = &__OS_SERVICES;

#define MITA_EXP_DECL       __declspec(dllexport)
char MITA_EXP_DECL *app_type = "MITA_X86_APP_FILE_V2";

#endif


#ifdef YAW_PRESENT
//Structure to YawCtrl module---------
struct YawCtrlArguments YawCtrlArg;
static OS_MEMORY_POOL *YawPtr;
#endif

#ifndef AS_TERMINATED
#define AS_TERMINATED       100
#endif

static U8 Request;
static OS_MEMORY_POOL *MemPool;

//----------------------------------------------------------------------------------------------------------------------
//                                APPLICATION MAIN MENU
//----------------------------------------------------------------------------------------------------------------------
static struct line_struct LinkToLocalMenu[] =          //Menu line and link to local menu
{
    MENU_ELEMENT_LINE_LINK ( APP_CAPTION,              PASSWORD_LEVEL_UNLOGGED_IN, APP_MENU_NAME, APP_GROUP_NAME  ),
#ifdef MITA_TEST
    MENU_ELEMENT_LINE_LINK ( "*********************",  PASSWORD_LEVEL_UNLOGGED_IN, "main", "os" ),
    MENU_ELEMENT_LINE_LINK ( "    TEST VERSION     ",  PASSWORD_LEVEL_UNLOGGED_IN, "main", "os" ),
    MENU_ELEMENT_LINE_LINK ( "DO NOT RUN IN TURBINE",  PASSWORD_LEVEL_UNLOGGED_IN, "main", "os" ),
    MENU_ELEMENT_LINE_LINK ( "*********************",  PASSWORD_LEVEL_UNLOGGED_IN, "main", "os" ),
    MENU_ELEMENT_LINE_LINK ( "                     ",  PASSWORD_LEVEL_UNLOGGED_IN, "main", "os" ),
#endif
};

static struct menu_struct AppMenu[] =                                                           // Local menu
{
    MENU_ELEMENT_MENU_TEXT (  APP_MENU_NAME,  PASSWORD_LEVEL_UNLOGGED_IN                   ),
};

static struct line_struct AppMenuLines[] =                                                      // Menu lines
{
    MENU_ELEMENT_LINE_LINK ( APP_RETURN_CAPTION, PASSWORD_LEVEL_UNLOGGED_IN,  "main", "os" ),
};

static struct menu_group_struct AppGroup[1];                                                    // Memory reservation


static STATUS AppMenuInit(void)
{
    STATUS Status;

    Status = OS_CreateMenuGroup ( AppGroup,       APP_GROUP_NAME                       );   STATUS_LINE_VAR_RETURN_VALUE(Status);
    Status = OS_CreateMenus     ( APP_GROUP_NAME, ELEMENT(AppMenu)                     );   STATUS_LINE_VAR_RETURN_VALUE(Status);
    Status = OS_AddLines        ( "os", "main",   ELEMENT(LinkToLocalMenu)             );   STATUS_LINE_VAR_RETURN_VALUE(Status);
    Status = OS_AddLines        ( APP_GROUP_NAME, APP_MENU_NAME, ELEMENT(AppMenuLines) );   STATUS_LINE_VAR_RETURN_VALUE(Status);

    return OS_SUCCESS;
}


//_____________________________________________________________________________________________________________________
//                                APPLICATION MAIN CALL
#define AUTOGENERATED_ADDITIONAL_METHODS
static STATUS StandardAverage(U8 ModuleState, U8* DoneState, U32 Interval)
{
	switch (ModuleState)
	{
	case APP_RUN:
	{
		Mid2StateUpdate();

		*DoneState = APP_RUN;
		break;
	}
	//__________________________________________________________________________
	case APP_INIT1:
	{
		*DoneState = APP_INIT1;
		break;
	}
	//__________________________________________________________________________
	case APP_INIT2:
	{
		*DoneState = APP_INIT2;
		break;
	}
	//__________________________________________________________________________
	case APP_INIT3:
	{
		*DoneState = APP_INIT3;
		break;
	}
	//__________________________________________________________________________
	case APP_INIT4:
	{
		*DoneState = APP_INIT4;
		break;
	}
	//__________________________________________________________________________
	case APP_INIT5:
	{
		*DoneState = APP_INIT5_DONE;
		break;
	}
	//__________________________________________________________________________
	case AS_SHUTDOWN:
	{
		*DoneState = AS_SHUTDOWN;
		break;
	}
	//__________________________________________________________________________
	case AS_REBOOT:
	{
		*DoneState = AS_REBOOT;
		break;
	}
	//__________________________________________________________________________
	case AS_SHUTDOWN_FAST:
	{
		*DoneState = AS_SHUTDOWN_FAST;
		break;
	}
	//__________________________________________________________________________
	default:
	{
		*DoneState = ModuleState;
		break;
	}
	}

	return OS_SUCCESS;
}



static STATUS log_app_state_requests(U8 request)
{
    if ( AS_RUN > request )
    {
        AppSystemLog           (APPSYSLOGCODE, APP_ID": INIT ROUND %u", request );
        //OS_EVENTLOG_make_entry (APPSYSLOGCODE, APP_ID": INIT ROUND %u", request );
    }
    else if ( AS_RUN == request )
    {
        AppSystemLog           (APPSYSLOGCODE, APP_ID": RUN" );
        OS_EVENTLOG_make_entry (APPSYSLOGCODE, APP_ID": RUN" );
    }
    else if ( AS_SHUTDOWN == request )
    {
        AppSystemLog           (APPSYSLOGCODE, APP_ID": SHUTDOWN" );
        OS_EVENTLOG_make_entry (APPSYSLOGCODE, APP_ID": SHUTDOWN" );
    }
    else if ( AS_REBOOT == request )
    {
        AppSystemLog           (APPSYSLOGCODE, APP_ID": REBOOT" );
        OS_EVENTLOG_make_entry (APPSYSLOGCODE, APP_ID": REBOOT" );
    }
    else if ( AS_SHUTDOWN_FAST == request )
    {
        AppSystemLog           (APPSYSLOGCODE, APP_ID": SHUTDOWN FAST" );
        OS_EVENTLOG_make_entry (APPSYSLOGCODE, APP_ID": SHUTDOWN FAST" );
    }
    else if ( AS_SHUTDOWN_DONE == request )
    {
        AppSystemLog           (APPSYSLOGCODE, APP_ID": SHUTDOWNDONE" );
        OS_EVENTLOG_make_entry (APPSYSLOGCODE, APP_ID": SHUTDOWNDONE" );
    }
    else if ( AS_FAILED == request )
    {
        AppSystemLog           (APPSYSLOGCODE, APP_ID": FAILED" );
        OS_EVENTLOG_make_entry (APPSYSLOGCODE, APP_ID": FAILED" );
    }
    else if ( AS_TERMINATED == request )
    {
        AppSystemLog           (APPSYSLOGCODE, APP_ID": TERMINATED" );
        OS_EVENTLOG_make_entry (APPSYSLOGCODE, APP_ID": TERMINATED" );
    }
    else
    {
        AppSystemLog           (APPSYSLOGCODE, APP_ID": UNKNOWN STATE" );
        OS_EVENTLOG_make_entry (APPSYSLOGCODE, APP_ID": UNKNOWN STATE" );
    }

    return OS_SUCCESS;
}

static STATUS log_app_state_done(U8 done_state)
{
    if ( AS_RUN > done_state )
    {
        AppSystemLog           ( APPSYSLOGCODE, APP_ID": INIT ROUND %u DONE", done_state );
        //OS_EVENTLOG_make_entry ( APPSYSLOGCODE, APP_ID": INIT ROUND %u DONE", done_state );
    }
    else if ( AS_RUN == done_state )
    {
        AppSystemLog           ( APPSYSLOGCODE, APP_ID": RUN DONE" );
        OS_EVENTLOG_make_entry ( APPSYSLOGCODE, APP_ID": RUN DONE" );
    }
    else if ( AS_SHUTDOWN == done_state )
    {
        AppSystemLog           ( APPSYSLOGCODE, APP_ID": SHUTDOWN DONE" );
        OS_EVENTLOG_make_entry ( APPSYSLOGCODE, APP_ID": SHUTDOWN DONE" );
    }
    else if ( AS_REBOOT == done_state )
    {
        AppSystemLog           ( APPSYSLOGCODE, APP_ID": REBOOT DONE" );
        OS_EVENTLOG_make_entry ( APPSYSLOGCODE, APP_ID": REBOOT DONE" );
    }

    else if ( AS_SHUTDOWN_FAST == done_state )
    {
        AppSystemLog           ( APPSYSLOGCODE, APP_ID": SHUTDOWN FAST DONE" );
        OS_EVENTLOG_make_entry ( APPSYSLOGCODE, APP_ID": SHUTDOWN FAST DONE" );
    }
    else if ( AS_SHUTDOWN_DONE == done_state )
    {
        AppSystemLog           ( APPSYSLOGCODE, APP_ID": SHUTDOWN_DONE DONE" );
        OS_EVENTLOG_make_entry ( APPSYSLOGCODE, APP_ID": SHUTDOWN_DONE DONE" );
    }
    else
    {
        AppSystemLog           ( APPSYSLOGCODE, APP_ID": UNKNOWN STATE DONE" );
        OS_EVENTLOG_make_entry ( APPSYSLOGCODE, APP_ID": UNKNOWN STATE DONE" );
    }

    return OS_SUCCESS;
}


static STATUS AddTasks (void)
{
    STATUS Status = OS_SUCCESS;

#define AUTOGENERATED_APPLICATION_TASKS

   int WD_MASK = 0xFFFFFFFF;
#if (1 == GDBDEBUG)
   WD_MASK = 0x00000000;
#endif

   //_________________________________________________________________________________________________________________________________________________________________________________________________________________________________
   //                               Name        | Priority | Stack Size  | Interval       | WD Enable         | WD Timeout     | Sensitivity | SafetyChain                 | WpLine          | Reboot          | Statuscode           | IsSync
   Status = AddCyclicTask         ( "El20ms",     33,        65536,        20,              WD_MASK&1,          200,             1,            WD_SAFETY_CHAIN_OPEN_ENABLE,  WD_WP_LINE_OFF,   WD_REBOOT_FAST,   WD_STATUSCODE_ENABLE,  1       ); STATUS_LINE_VAR_RETURN_VALUE(Status);
   Status = AddCyclicTask         ( "El100ms",    34,        65536,        100,             WD_MASK&1,          1000,            1,            WD_SAFETY_CHAIN_OPEN_ENABLE,  WD_WP_LINE_OFF,   WD_REBOOT_FAST,   WD_STATUSCODE_ENABLE,  1       ); STATUS_LINE_VAR_RETURN_VALUE(Status);
   Status = AddCyclicTask         ( "El1sec",     35,        65536,        1000,            WD_MASK&1,          10000,           1,            WD_SAFETY_CHAIN_OPEN_ENABLE,  WD_WP_LINE_OFF,   WD_REBOOT_NORMAL, WD_STATUSCODE_ENABLE,  1       ); STATUS_LINE_VAR_RETURN_VALUE(Status);
   Status = AddCyclicTask         ( "FCnv",       33,        65536,        20,              WD_MASK&1,          200,             1,            WD_SAFETY_CHAIN_OPEN_ENABLE,  WD_WP_LINE_OFF,   WD_REBOOT_FAST,   WD_STATUSCODE_ENABLE,  1       ); STATUS_LINE_VAR_RETURN_VALUE(Status);
   Status = AddNoScanTask         ( "IntTask",    50,        4096                                                                                                                                                                       ); STATUS_LINE_VAR_RETURN_VALUE(Status);
#undef AUTOGENERATED_APPLICATION_TASKS

    return OS_SUCCESS;
}


static STATUS AssignFuctionCalls()
{

    //-----------------------------------
    //Backward Compatibility
#ifdef YAW_PRESENT
    //Init YawCtrl structure--------------
    YawCtrlArg.TimerFunc   = (TimerFunc);
    YawCtrlArg.YawStop     = (YawStop);
    YawCtrlArg.YawStartCw  = (YawStartCw);
    YawCtrlArg.YawStartCcw = (YawStartCcw);
    YawCtrlArg.YawBlockCw  = (YawBlockCw);
    YawCtrlArg.YawBlockCcw = (YawBlockCcw);
    YawCtrlArg.YawBlockAll = (YawBlockAll);

    YawPtr = (OS_MEMORY_POOL *)&YawCtrlArg;
#endif
    //-----------------------------------

    STATUS Status = OS_SUCCESS;

#define AUTOGENERATED_ASSIGN_FUNCTION_CALLS
   Status = AddFunctionCall("El20ms",       StandardAverage,                          NULL); STATUS_LINE_VAR_RETURN_VALUE(Status);
   //Status = AddFunctionCall("El1sec",       Configurator,                             NULL); STATUS_LINE_VAR_RETURN_VALUE(Status);
   Status = AddFunctionCall("El20ms",       DLL_simu,                                 NULL); STATUS_LINE_VAR_RETURN_VALUE(Status);
   Status = AddBackCompFunctionCall("El20ms",       (void (*)())SafetySystem_MT_GL2010,       &Request, MemPool                   , NULL, NULL                                    ); STATUS_LINE_VAR_RETURN_VALUE(Status);
   Status = AddBackCompFunctionCall("El20ms",       (void (*)())EStopChain_MT_GL20101ExtStop, &Request, MemPool                   , NULL, NULL                                    ); STATUS_LINE_VAR_RETURN_VALUE(Status);
   Status = AddBackCompFunctionCall("El20ms",       (void (*)())SafetyChain_MT_GL20102ManStop, &Request, MemPool                   , NULL, NULL                                    ); STATUS_LINE_VAR_RETURN_VALUE(Status);
   Status = AddBackCompFunctionCall("El100ms",      (void (*)())VibrationMonitoringEmulator,          &Request, MemPool                   , NULL, NULL                                    ); STATUS_LINE_VAR_RETURN_VALUE(Status);
   Status = AddBackCompFunctionCall("El1sec",       (void (*)())SurgeProtection,              &Request, NULL                      , NULL, NULL                                    ); STATUS_LINE_VAR_RETURN_VALUE(Status);
   Status = AddBackCompFunctionCall("El20ms",       (void (*)())Generator,                    &Request, NULL                      , NULL, NULL                                    ); STATUS_LINE_VAR_RETURN_VALUE(Status);
   Status = AddBackCompFunctionCall("El20ms",       (void (*)())TowerResonansTime,            &Request, NULL                      , NULL, NULL                                    ); STATUS_LINE_VAR_RETURN_VALUE(Status);
   //Status = AddBackCompFunctionCall("El20ms",       (void (*)())WeatherSensor1,               &Request, MemPool                   , NULL, NULL                                    ); STATUS_LINE_VAR_RETURN_VALUE(Status);
   Status = AddBackCompFunctionCall("El20ms",       (void (*)())WeatherSensor2,               &Request, MemPool                   , NULL, NULL                                    ); STATUS_LINE_VAR_RETURN_VALUE(Status);
   Status = AddBackCompFunctionCall("El20ms",       (void (*)())WindSpeed,                    &Request, NULL                      , NULL, NULL                                    ); STATUS_LINE_VAR_RETURN_VALUE(Status);
   Status = AddBackCompFunctionCall("El20ms",       (void (*)())WindDirection,                &Request, NULL                      , NULL, NULL                                    ); STATUS_LINE_VAR_RETURN_VALUE(Status);
   Status = AddFunctionCall("El20ms",       Wind,                                     NULL); STATUS_LINE_VAR_RETURN_VALUE(Status);
   Status = AddBackCompFunctionCall("El20ms",       (void (*)())OutdoorTemperature,           &Request, NULL                      , NULL, NULL                                    ); STATUS_LINE_VAR_RETURN_VALUE(Status);
   Status = AddBackCompFunctionCall("El20ms",       (void (*)())Brake,                        &Request, NULL                      , NULL, NULL                                    ); STATUS_LINE_VAR_RETURN_VALUE(Status);
   Status = AddFunctionCall("El20ms", BladeController_emulator, NULL); STATUS_LINE_VAR_RETURN_VALUE(Status);
   Status = AddBackCompFunctionCall("El100ms",      (void (*)())Transformer,                  &Request, NULL                      , NULL, NULL                                    ); STATUS_LINE_VAR_RETURN_VALUE(Status);
   Status = AddFunctionCall("El100ms",      PowerReduction,                           NULL); STATUS_LINE_VAR_RETURN_VALUE(Status);
   Status = AddFunctionCall("El100ms",      Loss_Counter,                             NULL); STATUS_LINE_VAR_RETURN_VALUE(Status);
   Status = AddBackCompFunctionCall("El100ms",      (void (*)())PowerManagement,              &Request, MemPool                   , NULL, NULL                                    ); STATUS_LINE_VAR_RETURN_VALUE(Status);
   Status = AddFunctionCall("El20ms",       PitchAndTorque,                           NULL); STATUS_LINE_VAR_RETURN_VALUE(Status);
   Status = AddFunctionCall("El20ms",       Yaw_MK1,                                  NULL); STATUS_LINE_VAR_RETURN_VALUE(Status);
   Status = AddFunctionCall("El20ms",       YawMotorControl_MK1,                      NULL); STATUS_LINE_VAR_RETURN_VALUE(Status);
   Status = AddFunctionCall("El20ms",       Power_Converter,                          NULL); STATUS_LINE_VAR_RETURN_VALUE(Status);
   //Status = AddFunctionCall("FCnv",         LiebherrConverter,                        &LiebherrConverterCallStatus); STATUS_LINE_VAR_RETURN_VALUE(Status);
   //Status = AddFunctionCall("El20ms", LiebherrConverter, NULL); STATUS_LINE_VAR_RETURN_VALUE(Status);
   Status = AddFunctionCall("FCnv",         FeConConverter_FeConGmbH_Type1,           NULL); STATUS_LINE_VAR_RETURN_VALUE(Status);
   Status = AddBackCompFunctionCall("FCnv",         (void (*)())FeConConverter1_MT_Type1,     &Request, MemPool                   , NULL, NULL                                    ); STATUS_LINE_VAR_RETURN_VALUE(Status);
   Status = AddBackCompFunctionCall("FCnv",         (void (*)())FeConConverter2_MT_Type1,     &Request, MemPool                   , NULL, NULL                                    ); STATUS_LINE_VAR_RETURN_VALUE(Status);
   Status = AddBackCompFunctionCall("FCnv",         (void (*)())FeConConverter3_MT_Type1,     &Request, MemPool                   , NULL, NULL                                    ); STATUS_LINE_VAR_RETURN_VALUE(Status);
   Status = AddBackCompFunctionCall("FCnv",         (void (*)())FeConConverter4_MT_Type1,     &Request, MemPool                   , NULL, NULL                                    ); STATUS_LINE_VAR_RETURN_VALUE(Status);
   Status = AddBackCompFunctionCall("El100ms",      (void (*)())InverterCooling_MT_Type1,     &Request, MemPool                   , NULL, NULL                                    ); STATUS_LINE_VAR_RETURN_VALUE(Status);
   Status = AddBackCompFunctionCall("El100ms",      (void (*)())GeneratorCooling_MT_Type1,    &Request, MemPool                   , NULL, NULL                                    ); STATUS_LINE_VAR_RETURN_VALUE(Status);
   Status = AddBackCompFunctionCall("El1sec",       (void (*)())TowerBase,                    &Request, NULL                      , NULL, NULL                                    ); STATUS_LINE_VAR_RETURN_VALUE(Status);
   Status = AddBackCompFunctionCall("El20ms",       (void (*)())Nacelle,                      &Request, NULL                      , NULL, NULL                                    ); STATUS_LINE_VAR_RETURN_VALUE(Status);
   Status = AddBackCompFunctionCall("El1sec",       (void (*)())Panels,                       &Request, NULL                      , NULL, NULL                                    ); STATUS_LINE_VAR_RETURN_VALUE(Status);
   Status = AddBackCompFunctionCall("El1sec",       (void (*)())FlightWarningLight,           &Request, NULL                      , NULL, NULL                                    ); STATUS_LINE_VAR_RETURN_VALUE(Status);
	Status = AddFunctionCall("El20ms", WindRose, NULL); STATUS_LINE_VAR_RETURN_VALUE(Status);
	Status = AddFunctionCall("El20ms", PowerCurve, NULL); STATUS_LINE_VAR_RETURN_VALUE(Status);
	Status = AddFunctionCall("El20ms", FileInterface, NULL); STATUS_LINE_VAR_RETURN_VALUE(Status);
	//Status = AddFunctionCall("El100ms", UPS1, NULL); STATUS_LINE_VAR_RETURN_VALUE(Status);
   Status = AddBackCompFunctionCall("El100ms",      (void (*)())Info,                         &Request, NULL                      , NULL, NULL                                    ); STATUS_LINE_VAR_RETURN_VALUE(Status);
   Status = AddBackCompFunctionCall("El1sec",       (void (*)())CMS,                          &Request, NULL                      , NULL, NULL                                    ); STATUS_LINE_VAR_RETURN_VALUE(Status);
   Status = AddBackCompFunctionCall("El100ms",      (void (*)())Lubrication_MT_Type1,         &Request, MemPool                   , NULL, NULL                                    ); STATUS_LINE_VAR_RETURN_VALUE(Status);
   Status = AddBackCompFunctionCall("El100ms",      (void (*)())Lubrication_Main_Bearing_MT_Type1, &Request, MemPool                   , NULL, NULL                                    ); STATUS_LINE_VAR_RETURN_VALUE(Status);
   Status = AddBackCompFunctionCall("El100ms",      (void (*)())Lubrication_Pitch_Pinion_MT_Type1, &Request, MemPool                   , NULL, NULL                                    ); STATUS_LINE_VAR_RETURN_VALUE(Status);
   Status = AddBackCompFunctionCall("El100ms",      (void (*)())LubricationYaw_MT_Type1,      &Request, MemPool                   , NULL, NULL                                    ); STATUS_LINE_VAR_RETURN_VALUE(Status);
	// Status = AddFunctionCall("El100ms", UPS, NULL); STATUS_LINE_VAR_RETURN_VALUE(Status);
   Status = AddBackCompFunctionCall("El20ms",       (void (*)())FRT,                          &Request, MemPool                   , NULL, NULL                                    ); STATUS_LINE_VAR_RETURN_VALUE(Status);
   Status = AddBackCompFunctionCall("El20ms",       (void (*)())Grid,                         &Request, MemPool                   , NULL, NULL                                    ); STATUS_LINE_VAR_RETURN_VALUE(Status);
 	Status = AddFunctionCall("El20ms", AirPressure, NULL); STATUS_LINE_VAR_RETURN_VALUE(Status);
	Status = AddFunctionCall("El20ms", WindSpeedPower_Normalization, NULL); STATUS_LINE_VAR_RETURN_VALUE(Status);
   Status = AddBackCompFunctionCall("El20ms",       (void (*)())Hub_MT_Type1,                 &Request, NULL                      , NULL, NULL                                    ); STATUS_LINE_VAR_RETURN_VALUE(Status);
   Status = AddBackCompFunctionCall("El20ms",       (void (*)())Operate_MT_Type2,             &Request, MemPool                   , NULL, NULL                                    ); STATUS_LINE_VAR_RETURN_VALUE(Status);
   Status = AddBackCompFunctionCall("El20ms",       (void (*)())LVRT,                         &Request, NULL                      , NULL, NULL                                    ); STATUS_LINE_VAR_RETURN_VALUE(Status);
   //Status = AddBackCompFunctionCall("El100ms",      (void (*)())VibrationMonitoring2,         &Request, MemPool                   , NULL, NULL                                    ); STATUS_LINE_VAR_RETURN_VALUE(Status);
   Status = AddFunctionCall("El20ms",       NacelleAcceleration,                      NULL); STATUS_LINE_VAR_RETURN_VALUE(Status);
   //Status = AddFunctionCall("El100ms",      BladeLoads_Type1,                         NULL); STATUS_LINE_VAR_RETURN_VALUE(Status);
   //Status = AddBackCompFunctionCall("El20ms",       (void (*)())Lidar,                        &Request, MemPool                   , NULL, NULL                                    ); STATUS_LINE_VAR_RETURN_VALUE(Status);
   Status = AddFunctionCall("El100ms",      MainBearingPressure,                      NULL); STATUS_LINE_VAR_RETURN_VALUE(Status);
   Status = AddFunctionCall("El1sec",       Shutdown,                                 NULL); STATUS_LINE_VAR_RETURN_VALUE(Status);
   Status = AddFunctionCall("IntTask",      Version,                                  NULL); STATUS_LINE_VAR_RETURN_VALUE(Status);
   Status = AddFunctionCall("IntTask",      InitIoDrivers,                            NULL); STATUS_LINE_VAR_RETURN_VALUE(Status);
#undef AUTOGENERATED_ASSIGN_FUNCTION_CALLS

    return OS_SUCCESS;
}

static STATUS Set_Obj_Menu_Order ()
{
   STATUS Status = OS_SUCCESS;
   
#define AUTOGENERATED_ASSIGN_MENU_ORDERS
   U16 order = 0;
   Status = Set_Menu_Order((void (*)())(StandardAverage),                          order++);
   Status = Set_Menu_Order((void (*)())(InitIoDrivers),                            order++);
   Status = Set_Menu_Order((void (*)())(Version),                                  order++);
   //Status = Set_Menu_Order((void (*)())(Configurator),                             order++);
   Status = Set_Menu_Order((void (*)())(DLL_simu),                                 order++);
   Status = Set_Menu_Order((void (*)())(Info),                                     order++);
   Status = Set_Menu_Order((void (*)())(SafetySystem_MT_GL2010),                   order++);
   Status = Set_Menu_Order((void (*)())(EStopChain_MT_GL20101ExtStop),             order++);
   Status = Set_Menu_Order((void (*)())(SafetyChain_MT_GL20102ManStop),            order++);
   Status = Set_Menu_Order((void (*)())(Operate_MT_Type2),                         order++);
   Status = Set_Menu_Order((void (*)())(Grid),                                     order++);
   Status = Set_Menu_Order((void (*)())(LVRT),                                     order++);
   Status = Set_Menu_Order((void (*)())(FRT),                                      order++);
   Status = Set_Menu_Order((void (*)())(PowerManagement),                          order++);
   Status = Set_Menu_Order((void (*)())(PitchAndTorque),                           order++);
   Status = Set_Menu_Order((void (*)())(BladeController_emulator),		           order++);
   Status = Set_Menu_Order((void (*)())(Yaw_MK1),                                  order++);
   Status = Set_Menu_Order((void (*)())(YawMotorControl_MK1),                      order++);
   Status = Set_Menu_Order((void (*)())(Power_Converter),                          order++);
   Status = Set_Menu_Order((void (*)())(FeConConverter_FeConGmbH_Type1),           order++);
   Status = Set_Menu_Order((void (*)())(FeConConverter1_MT_Type1),                 order++);
   Status = Set_Menu_Order((void (*)())(FeConConverter2_MT_Type1),                 order++);
   Status = Set_Menu_Order((void (*)())(FeConConverter3_MT_Type1),                 order++);
   Status = Set_Menu_Order((void (*)())(FeConConverter4_MT_Type1),                 order++);
   Status = Set_Menu_Order((void (*)())(InverterCooling_MT_Type1),                 order++);
   //Status = Set_Menu_Order((void (*)())(LiebherrConverter),                        order++);
   Status = Set_Menu_Order((void (*)())(Generator),                                order++);
   Status = Set_Menu_Order((void (*)())(GeneratorCooling_MT_Type1),                order++);
   Status = Set_Menu_Order((void (*)())(MainBearingPressure),                      order++);
   Status = Set_Menu_Order((void (*)())(Wind),                                     order++);
   Status = Set_Menu_Order((void (*)())(WindSpeed),                                order++);
   Status = Set_Menu_Order((void (*)())(WindDirection),                            order++);
   Status = Set_Menu_Order((void (*)())(PowerReduction),                           order++);
   Status = Set_Menu_Order((void (*)())(Loss_Counter),                             order++);
   Status = Set_Menu_Order((void (*)())(Brake),                                    order++);
   Status = Set_Menu_Order((void (*)())(Transformer),                              order++);
   //Status = Set_Menu_Order((void (*)())(WeatherSensor1),                           order++);
   Status = Set_Menu_Order((void (*)())(WeatherSensor2),                           order++);
   Status = Set_Menu_Order((void (*)())(OutdoorTemperature),                       order++);
   Status = Set_Menu_Order((void (*)())(TowerBase),                                order++);
   Status = Set_Menu_Order((void (*)())(Nacelle),                                  order++);
   Status = Set_Menu_Order((void (*)())(Hub_MT_Type1),                             order++);
   Status = Set_Menu_Order((void (*)())(Panels),                                   order++);
   Status = Set_Menu_Order((void (*)())(FlightWarningLight),                       order++);
   Status = Set_Menu_Order((void (*)())(NacelleAcceleration),                      order++);
   //Status = Set_Menu_Order((void (*)())(VibrationMonitoring),                      order++);
   Status = Set_Menu_Order((void (*)())(Lubrication_MT_Type1),                     order++);
   Status = Set_Menu_Order((void (*)())(Lubrication_Main_Bearing_MT_Type1),        order++);
   Status = Set_Menu_Order((void (*)())(Lubrication_Pitch_Pinion_MT_Type1),        order++);
   Status = Set_Menu_Order((void (*)())(LubricationYaw_MT_Type1),                  order++);
   Status = Set_Menu_Order((void (*)())(TowerResonansTime),                        order++);
   Status = Set_Menu_Order((void (*)())(SurgeProtection),                          order++);
   Status = Set_Menu_Order((void (*)())(AirPressure),                              order++);
   Status = Set_Menu_Order((void (*)())(WindSpeedPower_Normalization),             order++);
   Status = Set_Menu_Order((void (*)())(WindRose),                                 order++);
   Status = Set_Menu_Order((void (*)())(PowerCurve),                               order++);
   //Status = Set_Menu_Order((void (*)())(UPS1),                                     order++);
   //Status = Set_Menu_Order((void (*)())(UPS),                                      order++);
   Status = Set_Menu_Order((void (*)())(CMS),                                      order++);
   //Status = Set_Menu_Order((void (*)())(BladeLoads_Type1),                         order++);
   //Status = Set_Menu_Order((void (*)())(Lidar),                                    order++);
   Status = Set_Menu_Order((void (*)())(FileInterface),                            order++);
   Status = Set_Menu_Order((void (*)())(Shutdown),                                 order++);
#undef AUTOGENERATED_ASSIGN_MENU_ORDERS

   return OS_SUCCESS;
}

static STATUS Set_Obj_Init_Order ()
{
   STATUS Status = OS_SUCCESS;

#define AUTOGENERATED_ASSIGN_INIT_ORDERS
   U16 order = 0;
   Status = Set_Init_Order((void (*)())(InitIoDrivers),                            order++);
   Status = Set_Init_Order((void (*)())(StandardAverage),                          order++);
   Status = Set_Init_Order((void (*)())(Version),                                  order++);
   //Status = Set_Init_Order((void (*)())(Configurator),                             order++);
   Status = Set_Init_Order((void (*)())(DLL_simu),                                 order++);
   Status = Set_Init_Order((void (*)())(SafetySystem_MT_GL2010),                   order++);
   Status = Set_Init_Order((void (*)())(EStopChain_MT_GL20101ExtStop),             order++);
   Status = Set_Init_Order((void (*)())(SafetyChain_MT_GL20102ManStop),            order++);
   Status = Set_Init_Order((void (*)())(VibrationMonitoringEmulator),                      order++);
   Status = Set_Init_Order((void (*)())(SurgeProtection),                          order++);
   Status = Set_Init_Order((void (*)())(Generator),                                order++);
   Status = Set_Init_Order((void (*)())(TowerResonansTime),                        order++);
   //Status = Set_Init_Order((void (*)())(WeatherSensor1),                           order++);
   Status = Set_Init_Order((void (*)())(WeatherSensor2),                           order++);
   Status = Set_Init_Order((void (*)())(WindSpeed),                                order++);
   Status = Set_Init_Order((void (*)())(WindDirection),                            order++);
   Status = Set_Init_Order((void (*)())(Wind),                                     order++);
   Status = Set_Init_Order((void (*)())(OutdoorTemperature),                       order++);
   Status = Set_Init_Order((void (*)())(Brake),                                    order++);
   Status = Set_Init_Order((void (*)())(BladeController_emulator),           order++);
   Status = Set_Init_Order((void (*)())(Transformer),                              order++);
   Status = Set_Init_Order((void (*)())(PowerReduction),                           order++);
   Status = Set_Init_Order((void (*)())(Loss_Counter), order++);
   Status = Set_Init_Order((void (*)())(PowerManagement),                          order++);
   Status = Set_Init_Order((void (*)())(PitchAndTorque),                           order++);
   Status = Set_Init_Order((void (*)())(Yaw_MK1),                                  order++);
   Status = Set_Init_Order((void (*)())(YawMotorControl_MK1),                      order++);
   Status = Set_Init_Order((void (*)())(Power_Converter),                          order++);
   //Status = Set_Init_Order((void (*)())(LiebherrConverter),                        order++);
   Status = Set_Init_Order((void (*)())(FeConConverter_FeConGmbH_Type1),           order++);
   Status = Set_Init_Order((void (*)())(FeConConverter1_MT_Type1),                 order++);
   Status = Set_Init_Order((void (*)())(FeConConverter2_MT_Type1),                 order++);
   Status = Set_Init_Order((void (*)())(FeConConverter3_MT_Type1),                 order++);
   Status = Set_Init_Order((void (*)())(FeConConverter4_MT_Type1),                 order++);
   Status = Set_Init_Order((void (*)())(InverterCooling_MT_Type1),                 order++);
   Status = Set_Init_Order((void (*)())(GeneratorCooling_MT_Type1),                order++);
   Status = Set_Init_Order((void (*)())(TowerBase),                                order++);
   Status = Set_Init_Order((void (*)())(Nacelle),                                  order++);
   Status = Set_Init_Order((void (*)())(Panels),                                   order++);
   Status = Set_Init_Order((void (*)())(FlightWarningLight),                       order++);
   Status = Set_Init_Order((void (*)())(WindRose),                                 order++);
   Status = Set_Init_Order((void (*)())(PowerCurve),                               order++);
   Status = Set_Init_Order((void (*)())(FileInterface),                            order++);
   //Status = Set_Init_Order((void (*)())(UPS1),                                     order++);
   Status = Set_Init_Order((void (*)())(Info),                                     order++);
   Status = Set_Init_Order((void (*)())(CMS),                                      order++);
   Status = Set_Init_Order((void (*)())(Lubrication_MT_Type1),                     order++);
   Status = Set_Init_Order((void (*)())(Lubrication_Main_Bearing_MT_Type1),        order++);
   Status = Set_Init_Order((void (*)())(Lubrication_Pitch_Pinion_MT_Type1),        order++);
   Status = Set_Init_Order((void (*)())(LubricationYaw_MT_Type1),                  order++);
   //Status = Set_Init_Order((void (*)())(UPS),                                      order++);
   Status = Set_Init_Order((void (*)())(FRT),                                      order++);
   Status = Set_Init_Order((void (*)())(Grid),                                     order++);
   Status = Set_Init_Order((void (*)())(AirPressure),                              order++);
   Status = Set_Init_Order((void (*)())(WindSpeedPower_Normalization),             order++);
   Status = Set_Init_Order((void (*)())(Hub_MT_Type1),                             order++);
   Status = Set_Init_Order((void (*)())(Operate_MT_Type2),                         order++);
   Status = Set_Init_Order((void (*)())(LVRT),                                     order++);
   Status = Set_Init_Order((void (*)())(NacelleAcceleration),                      order++);
   //Status = Set_Init_Order((void (*)())(BladeLoads_Type1),                         order++);
   //Status = Set_Init_Order((void (*)())(Lidar),                                    order++);
   Status = Set_Init_Order((void (*)())(MainBearingPressure),                      order++);
   Status = Set_Init_Order((void (*)())(Shutdown),                                 order++);
#undef AUTOGENERATED_ASSIGN_INIT_ORDERS

   return OS_SUCCESS;
}


void  app_mainApplication(UNSIGNED Argc, struct application_arguments *Argv)
{

	static STATUS Status = OS_SUCCESS;

	static OS_EVENT_GROUP EvGr_ReqStateChahge;
	static SUBSCRIPTION   Sbcr_ReqStateChahge;
	static UNSIGNED       ReqEv_ReqStateChahge,
		RetEv_ReqStateChahge;

	static U8             first_time_init = 1;
	static U8             emulate_req_state = 0;
	static U8             ReqState = 0;

	static U8             CurState = 0;
	static U8             AppTasksCreated = 0;

	AppSystemLog(APPSYSLOGCODE, APP_ID": Initializing");

	// Get the id of system variables 
	Set_App_RequestId_StateId(Argv->RequestId, Argv->StateId);
	SetMemPool(&Argv->Pool);

	MemPool = &Argv->Pool;      //Backward Compatibility

	Status = SetupParameterBackupFileNames(Argv->StateId);
	STATUS_LINE_VAR_RETURN(Status);

	//______________________________________________________________________________
	//Create Application Menu
	Status = AppMenuInit();              STATUS_LINE_VAR_RETURN(Status);


#ifdef MAIN_APP
   Status = Set_Sts_ControlPrgNames();  STATUS_LINE_VAR_RETURN(Status);
#endif
    //--------------------------------------------------------------------------------
    //Configurator Object

	//--------------------------------------------------------------------------------
	Status = AddTasks();                             STATUS_LINE_VAR_RETURN(Status);
	//--------------------------------------------------------------------------------
	Status = AssignFuctionCalls();                   STATUS_LINE_VAR_RETURN(Status);
	//--------------------------------------------------------------------------------
	Status = Set_Obj_Init_Order();                   STATUS_LINE_VAR_RETURN(Status);
	//--------------------------------------------------------------------------------
	Status = Set_Obj_Menu_Order();                   STATUS_LINE_VAR_RETURN(Status);
	//--------------------------------------------------------------------------------

	if (AppTasksCreated)
	{
		return 0;
	}
	else if (!first_time_init) {
		return -2;
	}


	//___________________________________________________________________________________________________
	while (TRUE)
	{
		if (first_time_init)
		{
			first_time_init = 0;

			if (APP_RUN == ReqState)
			{
				emulate_req_state = 1;
				ReqState = APP_INIT1;
				AppSystemLog(APPSYSLOGCODE, APP_ID": Asynchronous Starting");
			}
		}
		else  //emulate Init rounds for Async Application
		{
			if (APP_RUN > CurState)
			{
				ReqState = CurState + 1;
			}

			if (APP_RUN == ReqState)
			{
				emulate_req_state = 0;
			}
		}

		SetAppState(ReqState);

		log_app_state_requests(ReqState);

		Request = ReqState;   //Backward Compatibility


		if (APP_INIT1 == ReqState) //IO Channels Auto Detection
		{
			InitIo();
		}

		if (!StartAppTaskBeforeInitRounds)  //Init rounds from 0 89 executed in one task
		{
			if (APP_RUN > ReqState)
			{
				Status = AppTasks_InitCall(ReqState, &CurState);
                if (Status < 0)
                {
                    printf("\nINITIALIZATION FAILED\nAppTasks_InitCall returned error: %d\n\n", Status);
                }
				STATUS_LINE_VAR_RETURN(Status);

				if (APP_INIT5_DONE == CurState && !AppTasksCreated)
				{

					Status = AppTasks_Create(&Argv->Pool);
                    if (Status < 0)
                    {
                        printf("Error status: %d", Status);
                    }
					STATUS_LINE_VAR_RETURN(Status);
					AppSystemLog(APPSYSLOGCODE, APP_ID": Tasks Created");
					STATUS_LINE_VAR_RETURN(Status);
					AppTasksCreated = 1;

					return OS_SUCCESS;
				}

				//confirmation to OS that state done
				Status = OS_VarDB_UpdateU8(Get_StateId(), CurState);
                if (Status < 0)
                {
                    printf("Error status: %d", Status);
                }
				STATUS_LINE_VAR_RETURN(Status);
			}
		}
	}
	
    return -1;
}

STATUS mainApplication20msCall()
{
	return CustomEleonScan_20msCall();
}