//*****************************PEPTOOL Header Start******************************
//                                                                               
//                         Copyright © 2015 Mita-Teknik.                         
//This software may only be used with WP4x00 Controllers delivered by Mita-Teknik
//                                                                               
//*******************************************************************************
//                                                                               
// $PEPTOOL version:9.0$                                                         
// $PEPTOOL file version:106$                                                    
//                                                                               
//*******************************************************************************
//                                                                               
// $Date: 2014/05/23 09:10:13 $                                                  
// $Author: MITA\ihn $                                                           
// $RCSfile: Nacelle.c,v $                                                       
// $Revision: 1.20 $                                                             
//                                                                               
//******************************PEPTOOL Header End*******************************
// OS header files
#include <os_main.h>
// AppLib header files
#include <lib_main.h>
// App header files
#include <turbdef.h>
#include <VarMacros.h>
// Object header file
#include <Nacelle.h>

#define AUTOGENERATED_PART
//{
//-----------------------------------------------------------------------
// AUTOGENERATED START     AUTOGENERATED START     AUTOGENERATED START
//-----------------------------------------------------------------------

#define VALIDATE_HASH
char Nacelle_copyright[] =
{
   67, 111, 112, 121, 114, 105, 103, 104, 116, 32, 63, 32, 50, 48, 49, 53,
   32, 77, 105, 116, 97, 45, 84, 101, 107, 110, 105, 107, 46, 13, 10, 84,
   104, 105, 115, 32, 115, 111, 102, 116, 119, 97, 114, 101, 32, 109, 97, 121,
   32, 111, 110, 108, 121, 32, 98, 101, 32, 117, 115, 101, 100, 32, 119, 105,
   116, 104, 32, 87, 80, 52, 120, 48, 48, 32, 67, 111, 110, 116, 114, 111,
   108, 108, 101, 114, 115, 32, 100, 101, 108, 105, 118, 101, 114, 101, 100, 32,
   98, 121, 32, 77, 105, 116, 97, 45, 84, 101, 107, 110, 105, 107, 0
};

#define MODULE_NAME "NacelleA"

//-----------------------------------------------------------------------
// ALLOCATE MEMORY FOR STRINGS IN VARDB
//-----------------------------------------------------------------------

static char A_V_NacelleTempSensorStateTxt[31]  = "not defined";

//-----------------------------------------------------------------------
// DEFINE LOCAL VARIABLES DEFINE LOCAL VARIABLES DEFINE LOCAL VARIABLES
//-----------------------------------------------------------------------

static struct os_db_local LocalVars[] =
{
   VAR_ELEMENT_LOCAL("V_TempNacelleLog",                         TYPE_S16,     PASSWORD_LEVEL_UNLOGGED_IN,        PASSWORD_LEVEL_UNLOGGED_IN,        SCALE_DIV,    10,      UNIT_CELSIUS,       1,   0,               0,               0,               NULL,  TOTLOG_ENABLE | FIVEMINLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_NacelleTempSensorStateTxt",              TYPE_STRING + sizeof(A_V_NacelleTempSensorStateTxt) - 1,  PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   A_V_NacelleTempSensorStateTxt, 0,                0,                NULL,  NOLOG_ENABLE  ),
   VAR_ELEMENT_LOCAL("V_NacelleTempSensorState",                 TYPE_S32,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   0,               S32_MIN,         S32_MAX,         NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_NacelleSmokeDetectorReset",              TYPE_U8,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   0,               0,               1,               NULL,  NOLOG_ENABLE),
};

//-----------------------------------------------------------------------
// DEFINE PARAMETERS        DEFINE PARAMETERS        DEFINE PARAMETERS
//-----------------------------------------------------------------------

static struct os_db_parameter ParameterVars[] =
{
   VAR_ELEMENT_PARAMETER("P_NacelleHighTempWarnOn",                  TYPE_S16,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_DIV,    10,      UNIT_CELSIUS,       0,   550,             -300,            2000,            NULL  ),
   VAR_ELEMENT_PARAMETER("P_NacelleHighTempWarnOff",                 TYPE_S16,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_DIV,    10,      UNIT_CELSIUS,       0,   500,             -300,            2000,            NULL  ),
   VAR_ELEMENT_PARAMETER("P_NacelleHighTempStopOn",                  TYPE_S16,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_DIV,    10,      UNIT_CELSIUS,       0,   600,             -300,            2000,            NULL  ),
   VAR_ELEMENT_PARAMETER("P_NacelleHighTempStopOff",                 TYPE_S16,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_DIV,    10,      UNIT_CELSIUS,       0,   550,             -300,            2000,            NULL  ),
   VAR_ELEMENT_PARAMETER("P_NacelleLowTempWarnOn",                   TYPE_S16,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_DIV,    10,      UNIT_CELSIUS,       0,   -200,            -400,            400,             NULL  ),
   VAR_ELEMENT_PARAMETER("P_NacelleLowTempWarnOff",                  TYPE_S16,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_DIV,    10,      UNIT_CELSIUS,       0,   -150,            -400,            400,             NULL  ),
   VAR_ELEMENT_PARAMETER("P_NacelleLowTempStopOn",                   TYPE_S16,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_DIV,    10,      UNIT_CELSIUS,       0,   -250,            -400,            400,             NULL  ),
   VAR_ELEMENT_PARAMETER("P_NacelleLowTempStopOff",                  TYPE_S16,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_DIV,    10,      UNIT_CELSIUS,       0,   -200,            -400,            400,             NULL  ),
   VAR_ELEMENT_PARAMETER("P_NacelleTempEnable",                      TYPE_U8,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_NONE,   0,       UNIT_NONE,          0,   1,               0,               1,               NULL  ),
   VAR_ELEMENT_PARAMETER("P_NacelleTempErrHigh",                     TYPE_S16,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_DIV,    10,      UNIT_CELSIUS,       0,   2100,            0,               2200,            NULL  ),
   VAR_ELEMENT_PARAMETER("P_NacelleTempErrLow",                      TYPE_S16,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_DIV,    10,      UNIT_CELSIUS,       0,   -400,            -500,            0,               NULL  ),
};

//-----------------------------------------------------------------------
// DEFINE BACKUPS            DEFINE BACKUPS            DEFINE BACKUPS
//-----------------------------------------------------------------------

//----------------------------------------------------------------------------------
// DEFINE VAR ARRAYS            DEFINE VAR ARRAYS            DEFINE VAR ARRAYS
//----------------------------------------------------------------------------------
char Nacelle_initialValues[] =
{
   90, 151, 229, 55, 129, 25, 251, 36, 137, 239, 68, 126, 135, 61, 171, 232,
   61, 233, 84, 114, 106, 6, 82, 226, 231, 250, 96, 109, 248, 200, 232, 173,
   0
};

//-----------------------------------------------------------------------
// CREATE DATABASE VARS   CREATE DATABASE VARS   CREATE DATABASE VARS
//-----------------------------------------------------------------------

static STATUS CreateVarDbVars(void)
{
   STATUS Status;
   size_t ErrorEntry;

   Status = OS_VarDB_CreateLocals(LocalVars, sizeof(LocalVars)/sizeof(LocalVars[0]), &ErrorEntry, AppLocalParameterPosition());
   if (Status != 0)
   {
      AppSystemLog(ERR_7, MODULE_NAME"CrVL: %d,%d", Status, ErrorEntry);
      return ERR_7;
   }

   Status = OS_VarDB_CreateParameters(ParameterVars, sizeof(ParameterVars)/sizeof(ParameterVars[0]), &ErrorEntry, AppExportParameterPosition());
   if (Status != 0)
   {
      AppSystemLog(ERR_7, MODULE_NAME"CrVXP: %d,%d", Status, ErrorEntry);
      return ERR_7;
   }

   return OS_SUCCESS;
}

#define CREATE_VARDB_VARS

//-----------------------------------------------------------------------
// CREATE IO VARIABLES     CREATE IO VARIABLES     CREATE IO VARIABLES
//-----------------------------------------------------------------------

extern STATUS NacelleInitIOAliases();
extern struct os_db_alias* NacelleIOVars;
extern void (*NacelleSetLockValues)(void);
extern size_t NacelleIOVarsSize;

static STATUS CreateIOVars(void)
{
   STATUS Status;
   size_t ErrorEntry;

   varid_t VarId;
   BOOL variablesExist = false;
   U8 counter = 50;
   Status = NacelleInitIOAliases();
   STATUS_LINE_VAR_RETURN_VALUE(Status)
   while (!variablesExist && counter-- > 0)
   {
      variablesExist = true;
      U32 i = 0;
      for (i = 0; i < NacelleIOVarsSize; ++i)
      {
         if (OS_VarDB_GetVariableID(NacelleIOVars[i].Name, &VarId) != OS_SUCCESS)
         {
            variablesExist = false;
            break;
         }
      }

      if (!variablesExist)
      {
         OS_Sleep(100);
      }
   }

   Status = OS_VarDB_CreateAliases(NacelleIOVars, NacelleIOVarsSize, &ErrorEntry);
   if (Status)
   {
      AppDebugLog(5000, "Var Name = %s", NacelleIOVars[ErrorEntry].Alias);
   }
   STATUS_LINE_VAR_RETURN_CONST(Status, ErrorEntry);
   return OS_SUCCESS;
}

#define CREATE_IO_VARS

//-----------------------------------------------------------------------
// ALIASES                       ALIASES                       ALIASES
//-----------------------------------------------------------------------

static struct os_db_alias AliasVars[] =
{
   VAR_ELEMENT_ALIAS("PT_NacelleTemp",                           "V_NacelleTemp"),
};

#define CREATE_ALIASES

//-----------------------------------------------------------------------
// INPUT                          INPUT                          INPUT
//-----------------------------------------------------------------------

// Create local variable
#define MODUL_INPUTS
static S16 PT_NacelleTemp = 0;
static U8 V_ActiveControlProgram1 = 0;
static U8 DI_NacelleSmokeDetect = 0;
static U8 V_NacelleSmokeDetectorReset = 0;
static U8 DI_Nacelle_MCB_FB_PowerBeforeSC = 0;
static U8 DI_Nacelle_MCB_FB_PowerAfterSC = 0;

//-----------------------------------------------------------------------
static struct ModulInOut ModulInputs[] =
{
   {"PT_NacelleTemp",                           &PT_NacelleTemp,                           sizeof(PT_NacelleTemp),                           },
   {"V_ActiveControlProgram1",                  &V_ActiveControlProgram1,                  sizeof(V_ActiveControlProgram1),                  },
   {"DI_NacelleSmokeDetect",                    &DI_NacelleSmokeDetect,                    sizeof(DI_NacelleSmokeDetect),                    },
   {"V_NacelleSmokeDetectorReset",              &V_NacelleSmokeDetectorReset,              sizeof(V_NacelleSmokeDetectorReset),              },
   {"DI_Nacelle_MCB_FB_PowerBeforeSC",          &DI_Nacelle_MCB_FB_PowerBeforeSC,          sizeof(DI_Nacelle_MCB_FB_PowerBeforeSC),          },
   {"DI_Nacelle_MCB_FB_PowerAfterSC",           &DI_Nacelle_MCB_FB_PowerAfterSC,           sizeof(DI_Nacelle_MCB_FB_PowerAfterSC),           },
};

//-----------------------------------------------------------------------
// Check variable type
static STATUS VarsReadReturnStatus;
static type_t ReadVarType = TYPE_NONE;
static void VarsReadTypeCheck(void)
{
   (void)VarsReadReturnStatus;
   (void)ReadVarType;
   VERIFY_INPUT_REF_ID(S16,       ModulInputs[0].Name,                      ModulInputs[0].Id)
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[1].Name,                      ModulInputs[1].Id)
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[2].Name,                      ModulInputs[2].Id)
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[3].Name,                      ModulInputs[3].Id)
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[4].Name,                      ModulInputs[4].Id)
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[5].Name,                      ModulInputs[5].Id)
}

#undef MODUL_INPUTS
#define MODUL_INPUTS_SIZE (sizeof(ModulInputs)/sizeof(ModulInputs[0]))

//------------------------------------------------------------------------------------------
// READ/WRITE VARDB ARRAY      READ/WRITE VARDB ARRAY      READ/WRATE VARDB ARRAY
//------------------------------------------------------------------------------------------


//-----------------------------------------------------------------------
// PARAMETER                    PARAMETER                    PARAMETER
//-----------------------------------------------------------------------

// Create local variable
#define MODUL_PARAMETERS
static U8 P_NacelleTempEnable = 0;
static S16 P_NacelleHighTempWarnOn = 0;
static S16 P_NacelleHighTempWarnOff = 0;
static S16 P_NacelleHighTempStopOn = 0;
static S16 P_NacelleHighTempStopOff = 0;
static S16 P_NacelleLowTempWarnOn = 0;
static S16 P_NacelleLowTempWarnOff = 0;
static S16 P_NacelleLowTempStopOn = 0;
static S16 P_NacelleLowTempStopOff = 0;
static S16 P_NacelleTempErrHigh = 0;
static S16 P_NacelleTempErrLow = 0;



//-----------------------------------------------------------------------
static struct ModulInOut ModulParameters0[] =
{
   {"P_NacelleTempEnable",                      &P_NacelleTempEnable,                      sizeof(P_NacelleTempEnable),                      },
   {"P_NacelleHighTempWarnOn",                  &P_NacelleHighTempWarnOn,                  sizeof(P_NacelleHighTempWarnOn),                  },
   {"P_NacelleHighTempWarnOff",                 &P_NacelleHighTempWarnOff,                 sizeof(P_NacelleHighTempWarnOff),                 },
   {"P_NacelleHighTempStopOn",                  &P_NacelleHighTempStopOn,                  sizeof(P_NacelleHighTempStopOn),                  },
   {"P_NacelleHighTempStopOff",                 &P_NacelleHighTempStopOff,                 sizeof(P_NacelleHighTempStopOff),                 },
   {"P_NacelleLowTempWarnOn",                   &P_NacelleLowTempWarnOn,                   sizeof(P_NacelleLowTempWarnOn),                   },
   {"P_NacelleLowTempWarnOff",                  &P_NacelleLowTempWarnOff,                  sizeof(P_NacelleLowTempWarnOff),                  },
   {"P_NacelleLowTempStopOn",                   &P_NacelleLowTempStopOn,                   sizeof(P_NacelleLowTempStopOn),                   },
   {"P_NacelleLowTempStopOff",                  &P_NacelleLowTempStopOff,                  sizeof(P_NacelleLowTempStopOff),                  },
   {"P_NacelleTempErrHigh",                     &P_NacelleTempErrHigh,                     sizeof(P_NacelleTempErrHigh),                     },
   {"P_NacelleTempErrLow",                      &P_NacelleTempErrLow,                      sizeof(P_NacelleTempErrLow),                      },

};
static struct ModulInOut* ModulParameters[] =
{
   ModulParameters0,
};

//-----------------------------------------------------------------------
// Check variable type
static STATUS ParaVarsReadReturnStatus;
static type_t ParaReadVarType = TYPE_NONE;
static void ParaVarsReadTypeCheck(void)
{
   (void)ParaVarsReadReturnStatus;
   (void)ParaReadVarType;
}

#undef MODUL_PARAMETERS

#define PARAMETERS_GROUPS_SIZE        1
#define GENERAL_GROUP                 0
#define MODUL_PARAMETERS_TOTAL_SIZE   11
static SUBSCRIPTION ParaSubscription[MODUL_PARAMETERS_TOTAL_SIZE];
static U8 ReadParameters[PARAMETERS_GROUPS_SIZE];
static U8 ParametersChanged[PARAMETERS_GROUPS_SIZE];
static UNSIGNED GroupsIndexes[PARAMETERS_GROUPS_SIZE];
static int ParaGroupsSizes[PARAMETERS_GROUPS_SIZE] = { 11 };
static STATUS VarDbUpdateParameter(varid_t VariableId, void* Message, U16 Length, UNSIGNED paraGroupIndex, UNSIGNED Ref2)
{
   ReadParameters[paraGroupIndex] = 1;
   ParametersChanged[paraGroupIndex] = 1;
   return OS_SUCCESS;
}
static STATUS ReadParametersFunc(int paraGroupIndex)
{
   STATUS LocalStatus;
   // Check inputdata
   if (sizeof(ModulParameters[paraGroupIndex]) == 0)
   {
      AppSystemLog(ERR_4, MODULE_NAME"Group %d ModuleParameters = 0", paraGroupIndex);
      return ERR_4;
   }
   // Read inputdata
   LocalStatus = OS_ReadVariables(ModulParameters[paraGroupIndex], ParaGroupsSizes[paraGroupIndex]);
   if (LocalStatus != 0)
   {
      AppSystemLog(11, "LocalStatus: %d", LocalStatus);
      AppSystemLog(ERR_4, MODULE_NAME"ReadParErr: group=%d element=%d elementpointer=0x%x", paraGroupIndex, LocalStatus, &ModulParameters[LocalStatus]);
      return ERR_4;
   }
   return OS_SUCCESS;
}


//-----------------------------------------------------------------------
// READ VARS FROM VARDB    READ VARS FROM VARDB    READ VARS FROM VARDB
//-----------------------------------------------------------------------

static STATUS InputReferenceRoutine(U8 ModuleState)
{
   STATUS LocalStatus = 0;

   // Read input references
   if (ModuleState >= APP_INIT3)
   {
      // Check inputdata
      if (sizeof(ModulInputs) == 0)
      {
         AppSystemLog(ERR_4, MODULE_NAME"ModuleInputs = 0");
         return ERR_4;
      }
      // Read inputdata
      LocalStatus = OS_ReadVariables(ModulInputs, MODUL_INPUTS_SIZE);
      if (LocalStatus != 0)
      {
         AppSystemLog(ERR_4, MODULE_NAME"ReadVErr: element=%d elementpointer=0x%x", LocalStatus, &ModulInputs[LocalStatus]);
         return ERR_4;
      }
   }
   // Read input parameters
   if (ModuleState == APP_INIT3)
   {
      static size_t ParaCounter = 0;
      int groupIndex;
      for (groupIndex = 0; groupIndex < PARAMETERS_GROUPS_SIZE; groupIndex++)
      {
         ParametersChanged[groupIndex] = 1;
         ReadParameters[groupIndex] = 1;
         GroupsIndexes[groupIndex] = groupIndex;

         // Check inputdata
         if (sizeof(ModulParameters[groupIndex]) == 0)
         {
            AppSystemLog(ERR_4, MODULE_NAME"Group = %d ModuleParameters = 0", groupIndex);
            return ERR_4;
         }
         // Read inputdata
         LocalStatus = OS_ReadVariables(ModulParameters[groupIndex], ParaGroupsSizes[groupIndex]);
         if (LocalStatus != 0)
         {
            AppSystemLog(ERR_4, MODULE_NAME"ReadVParaErr: group=%d element=%d elementpointer=0x%x", groupIndex, LocalStatus, &ModulParameters[groupIndex][LocalStatus]);
            return ERR_4;
         }
         int paraIndex;
         for (paraIndex = 0; paraIndex < ParaGroupsSizes[groupIndex]; paraIndex++)
         {
            LocalStatus = OS_SubHandl_SubscribeFunctionWithRef(&ParaSubscription[ParaCounter], 1, &ModulParameters[groupIndex][paraIndex].Id, &GroupsIndexes[groupIndex], &GroupsIndexes[groupIndex], VarDbUpdateParameter);
            ParaCounter++;
            if (LocalStatus != 0)
            {
               AppSystemLog(ERR_4, MODULE_NAME"Subscribe Parameter: group=%d element=%d elementpointer=0x%x", groupIndex, LocalStatus, &ModulParameters[LocalStatus]);
               return ERR_4;
            }
         }
      }
   }
   if (ModuleState == APP_RUN)
   {
      int groupIndex;
      for (groupIndex = 0; groupIndex < PARAMETERS_GROUPS_SIZE; groupIndex++)
      {
         if (ReadParameters[groupIndex])
         {
            LocalStatus = ReadParametersFunc(groupIndex);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
            ReadParameters[groupIndex] = 0;
         }
      }
   }

   return 0;
}

#define READ_VARS

//-----------------------------------------------------------------------
// OUTPUT                         OUTPUT                         OUTPUT
//-----------------------------------------------------------------------

// Create local variable
#define MODUL_OUTPUTS
static S16 V_TempNacelleLog = 0;
static S32 V_NacelleTempSensorState = 0;
static U8 DO_NacelleSmokeDetectorSupply = 0;
static char V_NacelleTempSensorStateTxt[31];


//-----------------------------------------------------------------------
static struct ModulInOut ModulOutputs[] =
{
   {"V_TempNacelleLog",                         &V_TempNacelleLog,                         sizeof(V_TempNacelleLog),                         },
   {"V_NacelleTempSensorStateTxt",              &V_NacelleTempSensorStateTxt,              sizeof(V_NacelleTempSensorStateTxt),              },
   {"V_NacelleTempSensorState",                 &V_NacelleTempSensorState,                 sizeof(V_NacelleTempSensorState),                 },
   {"DO_NacelleSmokeDetectorSupply",            &DO_NacelleSmokeDetectorSupply,            sizeof(DO_NacelleSmokeDetectorSupply),            },
};

//-----------------------------------------------------------------------
// Check variable type
static STATUS VarsWriteReturnStatus;
static type_t WriteVarType = TYPE_NONE;
static void VarsWriteTypeCheck(void)
{
   (void)VarsWriteReturnStatus;
   (void)WriteVarType;
   VERIFY_OUTPUT_REF_ID(S16,       ModulOutputs[0].Name,                     ModulOutputs[0].Id,                       0)
   VERIFY_OUTPUT_STRING_REF_ID(STRING,     ModulOutputs[1].Name,                      ModulOutputs[1].Id,                   0)
   VERIFY_OUTPUT_REF_ID(S32,       ModulOutputs[2].Name,                     ModulOutputs[2].Id,                       0)
   VERIFY_OUTPUT_REF_ID(U8,        ModulOutputs[3].Name,                     ModulOutputs[3].Id,                       0)
}

#undef MODUL_OUTPUTS
#define MODUL_OUTPUTS_SIZE (sizeof(ModulOutputs)/sizeof(ModulOutputs[0]))

//-----------------------------------------------------------------------
// WRITE VARS TO VARDB     WRITE VARS TO VARDB     WRITE VARS TO VARDB
//-----------------------------------------------------------------------

static STATUS InitOutputVars(void)
{
   STATUS LocalStatus;
   // Read outputdata
   LocalStatus = OS_ReadVariables(ModulOutputs, MODUL_OUTPUTS_SIZE);
   if (LocalStatus != 0)
   {
      AppSystemLog(ERR_4, MODULE_NAME"InitErr: element=%d elementpointer=0x%x", LocalStatus, &ModulOutputs[LocalStatus]);
      return ERR_4;
   }
   return OS_SUCCESS;
}
static STATUS OutputReferenceRoutine(U8 ModuleState)
{
   STATUS LocalStatus = 0;
   // Write Outputdata
   LocalStatus = OS_WriteVariablesConditional(ModulOutputs, MODUL_OUTPUTS_SIZE);
   if (LocalStatus != 0)
   {
      AppSystemLog(ERR_5, MODULE_NAME"WriteVErr: element=%d elementpointer=0x%x", LocalStatus, &ModulOutputs[LocalStatus]);
      return ERR_5;
   }
   return 0;
}

#define WRITE_VARS

//-----------------------------------------------------------------------
// VERIFY VARIABLES CREATION                 VERIFY VARIABLES CREATION
//-----------------------------------------------------------------------

static STATUS LocalIoCheck(void)
{
   // Check if input variables exist.
   STATUS LocalStatus;

   LocalStatus = OS_DoesVariablesExist(ModulInputs, MODUL_INPUTS_SIZE);
   if (LocalStatus != 0)
   {
      AppSystemLog(ERR_1, MODULE_NAME"InputErr: %d", LocalStatus);
      AppSystemLog(ERR_1, "Name: %s", ModulInputs[LocalStatus-1].Name);
      return ERR_1;
   }
   (void)VarsReadTypeCheck();

   int groupIndex;
   for (groupIndex = 0; groupIndex < PARAMETERS_GROUPS_SIZE; groupIndex++)
   {
      LocalStatus = OS_DoesVariablesExist(ModulParameters[groupIndex], ParaGroupsSizes[groupIndex]);
      if (LocalStatus != 0)
      {
         AppSystemLog(ERR_3, MODULE_NAME"ParameterErr: %d Group:%d", LocalStatus, groupIndex);
         AppSystemLog(ERR_3, "Name: %s", ModulParameters[groupIndex][LocalStatus-1].Name);
         return ERR_3;
      }
   }
   (void)ParaVarsReadTypeCheck();

   LocalStatus = OS_DoesVariablesExist(ModulOutputs, MODUL_OUTPUTS_SIZE);
   if (LocalStatus != 0)
   {
      AppSystemLog(ERR_2, MODULE_NAME"OutputErr: %d", LocalStatus);
      AppSystemLog(ERR_2, "Name: %s", ModulOutputs[LocalStatus-1].Name);
      return ERR_2;
   }
   (void)VarsWriteTypeCheck();

   return OS_SUCCESS;
}

#define VERIFY_VARIABLES

//-----------------------------------------------------------------------
// ALLOCATE MEMORY FOR SUMMATIONS        ALLOCATE MEMORY FOR SUMMATIONS
//-----------------------------------------------------------------------


//-----------------------------------------------------------------------
// SUMMATIONS                  SUMMATIONS                  SUMMATIONS
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// DEFINE MENUS               DEFINE MENUS               DEFINE MENUS
//-----------------------------------------------------------------------



// Menu line and link to local menu
//-----------------------------------------------------------------------
static struct line_struct M_ObjMainLinkToLocalMenu[] =
{
   MENU_ELEMENT_LINE_LINK("Nacelle",                           PASSWORD_LEVEL_END_CUSTOMER,        "M_ObjMain",                        "G_Nacelle"),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_ObjMainMenu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_ObjMain",                        PASSWORD_LEVEL_END_CUSTOMER),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_ObjMainMenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("NACELLE",                           PASSWORD_LEVEL_END_CUSTOMER,        "M_"APP_ID"AppMain",                "G_"APP_ID"App"),
   MENU_ELEMENT_LINE_VARRO("Nacelle temp. Status",             PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_NacelleTempSensorStateTxt",                LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Nacelle Temperature",              PASSWORD_LEVEL_END_CUSTOMER,        (char*)"PT_NacelleTemp",                             LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Smoke Detection",                  PASSWORD_LEVEL_END_CUSTOMER,        (char*)"DI_NacelleSmokeDetect",                      LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_LINK("Status",                            PASSWORD_LEVEL_END_CUSTOMER,        "M_Status",                         "G_Nacelle"),
   MENU_ELEMENT_LINE_LINK("Parameter",                         PASSWORD_LEVEL_END_CUSTOMER,        "M_Parameter",                      "G_Nacelle"),
   MENU_ELEMENT_LINE_LINK("Service",                           PASSWORD_LEVEL_SERVICE,             "M_Service344340",                  "G_Nacelle"),
   MENU_ELEMENT_LINE_LINK("Debug",                             PASSWORD_LEVEL_MITA_PROGRAMMER,     "M_Debug32",                        "G_Nacelle"),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_StatusMenu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_Status",                         PASSWORD_LEVEL_END_CUSTOMER),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_StatusMenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("STATUS",                            PASSWORD_LEVEL_END_CUSTOMER,        "M_ObjMain",                        "G_Nacelle"),
   MENU_ELEMENT_LINE_VARRO("Smoke Detection",                  PASSWORD_LEVEL_END_CUSTOMER,        (char*)"DI_NacelleSmokeDetect",                      LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Nacelle Temperature",              PASSWORD_LEVEL_END_CUSTOMER,        (char*)"PT_NacelleTemp",                             LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Smoke Detector Supply",            PASSWORD_LEVEL_END_CUSTOMER,        (char*)"DO_NacelleSmokeDetectorSupply",              LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("MCB Feedback Power Before SC",     PASSWORD_LEVEL_END_CUSTOMER,        (char*)"DI_Nacelle_MCB_FB_PowerBeforeSC",            LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("MCB Feedback Power After SC",      PASSWORD_LEVEL_END_CUSTOMER,        (char*)"DI_Nacelle_MCB_FB_PowerAfterSC",             LINE_FORMAT_NONE),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_ParameterMenu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_Parameter",                      PASSWORD_LEVEL_END_CUSTOMER),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_ParameterMenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("PARAMETER",                         PASSWORD_LEVEL_END_CUSTOMER,        "M_ObjMain",                        "G_Nacelle"),
   MENU_ELEMENT_LINE_VARRW("Nacelle temp. Enable",             PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_NacelleTempEnable",                        LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Nacelle High temp. Warning ON",    PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_NacelleHighTempWarnOn",                    LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Nacelle High temp. Warning OFF",   PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_NacelleHighTempWarnOff",                   LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Nacelle High temp. Stop ON",       PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_NacelleHighTempStopOn",                    LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Nacelle High temp. Stop OFF",      PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_NacelleHighTempStopOff",                   LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Nacelle Low temp. Warning ON",     PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_NacelleLowTempWarnOn",                     LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Nacelle Low temp. Warning OFF",    PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_NacelleLowTempWarnOff",                    LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Nacelle Low temp. Stop ON",        PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_NacelleLowTempStopOn",                     LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Nacelle Low temp. Stop OFF",       PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_NacelleLowTempStopOff",                    LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("PT100 Sensor Error High",          PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_TowerBaseTempErrHigh",                     LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("PT100 Sensor Error Low",           PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_TowerBaseTempErrLow",                      LINE_FORMAT_NONE),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_Service344340Menu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_Service344340",                  PASSWORD_LEVEL_SERVICE),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_Service344340MenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("SERVICE",                           PASSWORD_LEVEL_SERVICE,             "M_ObjMain",                        "G_Nacelle"),
   MENU_ELEMENT_LINE_VARRW("Reset Smoke Detector",             PASSWORD_LEVEL_SERVICE,             (char*)"V_NacelleSmokeDetectorReset",                LINE_FORMAT_NONE),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_Debug32Menu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_Debug32",                        PASSWORD_LEVEL_MITA_PROGRAMMER),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_Debug32MenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("DEBUG",                             PASSWORD_LEVEL_MITA_PROGRAMMER,     "M_ObjMain",                        "G_Nacelle"),
   MENU_ELEMENT_LINE_VARRO("V_NacelleTempSensorState",         PASSWORD_LEVEL_MITA_PROGRAMMER,     (char*)"V_NacelleTempSensorState",                   LINE_FORMAT_NONE),
};
// Creating parameters for multiplexed categories
//-----------------------------------------------------------------------
static struct multiplexed_info_struct M_ObjMainMultiplexedCategoriesParameters[] =
{
0};

//-----------------------------------------------------------------------
// CREATE MENUS               CREATE MENUS               CREATE MENUS
//-----------------------------------------------------------------------

// Memory reservation
//-----------------------------------------------------------------------
static struct menu_group_struct ObjGroup[1];

// Creating the menus
//-----------------------------------------------------------------------
STATUS NacelleMenuAppInit(U8 ModuleState, OS_MEMORY_POOL* pPool)
{
   STATUS Status;

   if (ModuleState == APP_INIT1)
   {
      /* Create application group */
      Status = OS_CreateMenuGroup(ObjGroup, M_ObjMainLinkToLocalMenu[0].LinkGroup);
      STATUS_LINE_VAR_RETURN_VALUE(Status);
   }

   Status = CreateAndInitializeMenu(ModuleState,
                                    M_ObjMainMenuLines[0].LinkGroup,
                                    M_ObjMainMenuLines[0].LinkName,
                                    ELEMENT(M_ObjMainLinkToLocalMenu),
                                    M_ObjMainLinkToLocalMenu[0].LinkGroup,
                                    ELEMENT(M_ObjMainMenu),
                                    M_ObjMainLinkToLocalMenu[0].LinkName,
                                    ELEMENT(M_ObjMainMenuLines),
                                    pPool,
                                    M_ObjMainMultiplexedCategoriesParameters);
   STATUS_LINE_VAR_RETURN_VALUE(Status);

   Status = CreateAndInitializeMenu(ModuleState,
                                    M_StatusMenuLines[0].LinkGroup,
                                    M_StatusMenuLines[0].LinkName,
                                    NULL,
                                    0,
                                    M_ObjMainMenuLines[4].LinkGroup,
                                    ELEMENT(M_StatusMenu),
                                    M_ObjMainMenuLines[4].LinkName,
                                    ELEMENT(M_StatusMenuLines),
                                    pPool,
                                    M_ObjMainMultiplexedCategoriesParameters);
   STATUS_LINE_VAR_RETURN_VALUE(Status);

   Status = CreateAndInitializeMenu(ModuleState,
                                    M_ParameterMenuLines[0].LinkGroup,
                                    M_ParameterMenuLines[0].LinkName,
                                    NULL,
                                    0,
                                    M_ObjMainMenuLines[5].LinkGroup,
                                    ELEMENT(M_ParameterMenu),
                                    M_ObjMainMenuLines[5].LinkName,
                                    ELEMENT(M_ParameterMenuLines),
                                    pPool,
                                    M_ObjMainMultiplexedCategoriesParameters);
   STATUS_LINE_VAR_RETURN_VALUE(Status);

   Status = CreateAndInitializeMenu(ModuleState,
                                    M_Service344340MenuLines[0].LinkGroup,
                                    M_Service344340MenuLines[0].LinkName,
                                    NULL,
                                    0,
                                    M_ObjMainMenuLines[6].LinkGroup,
                                    ELEMENT(M_Service344340Menu),
                                    M_ObjMainMenuLines[6].LinkName,
                                    ELEMENT(M_Service344340MenuLines),
                                    pPool,
                                    M_ObjMainMultiplexedCategoriesParameters);
   STATUS_LINE_VAR_RETURN_VALUE(Status);

   Status = CreateAndInitializeMenu(ModuleState,
                                    M_Debug32MenuLines[0].LinkGroup,
                                    M_Debug32MenuLines[0].LinkName,
                                    NULL,
                                    0,
                                    M_ObjMainMenuLines[7].LinkGroup,
                                    ELEMENT(M_Debug32Menu),
                                    M_ObjMainMenuLines[7].LinkName,
                                    ELEMENT(M_Debug32MenuLines),
                                    pPool,
                                    M_ObjMainMultiplexedCategoriesParameters);
   STATUS_LINE_VAR_RETURN_VALUE(Status);

   return OS_SUCCESS;
}

#define CREATE_MENU

//-----------------------------------------------------------------------
//               BUTTONS FUNCTIONS FORWARD DECLARATIONS
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// BUTTONS                       BUTTONS                      BUTTONS
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
//             SET/RESET FUNCTIONS FORWARD DECLARATIONS
//-----------------------------------------------------------------------
static U8 StatusSetFunc30(void);
static U8 StatusResetFunc30(void);
static U8 StatusSetFunc31(void);
static U8 StatusResetFunc31(void);
static U8 StatusSetFunc1563(void);
static U8 StatusResetFunc1563(void);
static U8 StatusSetFunc2178(void);
static U8 StatusResetFunc2178(void);
static U8 StatusSetFunc3069(void);
static U8 StatusResetFunc3069(void);
static U8 StatusSetFunc2452(void);
static U8 StatusSetFunc5070(void);
//-----------------------------------------------------------------------
// STATUSCODES                 STATUSCODES                 STATUSCODES
//-----------------------------------------------------------------------

static struct sts_statuscode_structure StatusCodes[] =
{
   STS_CODE_ELEMENT("Nacelle temp.",          20*SEC,    30,        STATUSCODE_UPDATE_TYPE_POLLING,         PASSWORD_LEVEL_SERVICE,            STATUSCODE_TIMER_TYPE_CONSTANT,     STATUSCODE_TIMER_TYPE_CONSTANT,     STATUSCODE_RESET_TYPE_AUTOMATIC,    STATUSCODE_PRIORITY_LOW,       27,   1,    32,   NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    StatusSetFunc30,         StatusResetFunc30,       BRAKE_PROG_0,        BRAKE_PROG_0,        BRAKE_PROG_MAX,      NULL,                PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    YAW_PROG_0,          YAW_PROG_0,          YAW_PROG_240,        NULL,                PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,    0,    255,  NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            1,  PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      1000,      20,        1000,      NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    1*MINUTE,  SETDELAY_MIN,   SETDELAY_MAX,   NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      1*MINUTE,  RESETDELAY_MIN, RESETDELAY_MAX, NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      0,         REPEATTIMES_MIN,     REPEATTIMES_MAX,     NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         REPEATPERIOD_MIN,    REPEATPERIOD_MAX,    NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         REPEATCODE_MIN,      REPEATCODE_MAX,      NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         TIMEOUTPERIOD_MIN,   TIMEOUTPERIOD_MAX,   NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         TIMEOUTCODE_MIN,     TIMEOUTCODE_MAX,     NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    NULL),
   STS_CODE_ELEMENT("Nacelle temp. stop",     20*SEC,    31,        STATUSCODE_UPDATE_TYPE_POLLING,         PASSWORD_LEVEL_SERVICE,            STATUSCODE_TIMER_TYPE_CONSTANT,     STATUSCODE_TIMER_TYPE_CONSTANT,     STATUSCODE_RESET_TYPE_AUTOMATIC,    STATUSCODE_PRIORITY_LOW,       22,   1,    32,   NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    StatusSetFunc31,         StatusResetFunc31,       BRAKE_PROG_50,       BRAKE_PROG_0,        BRAKE_PROG_MAX,      NULL,                PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    YAW_PROG_0,          YAW_PROG_0,          YAW_PROG_240,        NULL,                PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    1,    0,    255,  NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            1,  PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      1000,      20,        1000,      NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    1*MINUTE,  SETDELAY_MIN,   SETDELAY_MAX,   NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      1*MINUTE,  RESETDELAY_MIN, RESETDELAY_MAX, NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      3,         REPEATTIMES_MIN,     REPEATTIMES_MAX,     NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    1ULL*DAY,  REPEATPERIOD_MIN,    REPEATPERIOD_MAX,    NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    23,        REPEATCODE_MIN,      REPEATCODE_MAX,      NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         TIMEOUTPERIOD_MIN,   TIMEOUTPERIOD_MAX,   NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         TIMEOUTCODE_MIN,     TIMEOUTCODE_MAX,     NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    NULL),
   STS_CODE_ELEMENT("Nacelle temp low",       20*SEC,    1563,      STATUSCODE_UPDATE_TYPE_POLLING,         PASSWORD_LEVEL_SERVICE,            STATUSCODE_TIMER_TYPE_CONSTANT,     STATUSCODE_TIMER_TYPE_CONSTANT,     STATUSCODE_RESET_TYPE_AUTOMATIC,    STATUSCODE_PRIORITY_LOW,       27,   1,    32,   NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    StatusSetFunc1563,       StatusResetFunc1563,     BRAKE_PROG_0,        BRAKE_PROG_0,        BRAKE_PROG_200,      NULL,                PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    YAW_PROG_0,          YAW_PROG_0,          YAW_PROG_240,        NULL,                PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    1,    0,    255,  NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            1,  PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      1000,      20,        1000,      NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    1*MINUTE,  SETDELAY_MIN,   SETDELAY_MAX,   NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      1*MINUTE,  RESETDELAY_MIN, RESETDELAY_MAX, NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      0,         REPEATTIMES_MIN,     REPEATTIMES_MAX,     NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         REPEATPERIOD_MIN,    REPEATPERIOD_MAX,    NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         REPEATCODE_MIN,      REPEATCODE_MAX,      NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         TIMEOUTPERIOD_MIN,   TIMEOUTPERIOD_MAX,   NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         TIMEOUTCODE_MIN,     TIMEOUTCODE_MAX,     NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    NULL),
   STS_CODE_ELEMENT("Nacelle temp lo stop",   20*SEC,    2178,      STATUSCODE_UPDATE_TYPE_POLLING,         PASSWORD_LEVEL_SERVICE,            STATUSCODE_TIMER_TYPE_CONSTANT,     STATUSCODE_TIMER_TYPE_CONSTANT,     STATUSCODE_RESET_TYPE_AUTOMATIC,    STATUSCODE_PRIORITY_LOW,       22,   1,    32,   NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    StatusSetFunc2178,       StatusResetFunc2178,     BRAKE_PROG_50,       BRAKE_PROG_0,        BRAKE_PROG_200,      NULL,                PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    YAW_PROG_0,          YAW_PROG_0,          YAW_PROG_240,        NULL,                PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    1,    0,    255,  NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            1,  PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      1000,      20,        1000,      NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    1*MINUTE,  SETDELAY_MIN,   SETDELAY_MAX,   NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      1*MINUTE,  RESETDELAY_MIN, RESETDELAY_MAX, NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      3,         REPEATTIMES_MIN,     REPEATTIMES_MAX,     NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    1ULL*DAY,  REPEATPERIOD_MIN,    REPEATPERIOD_MAX,    NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    23,        REPEATCODE_MIN,      REPEATCODE_MAX,      NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         TIMEOUTPERIOD_MIN,   TIMEOUTPERIOD_MAX,   NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         TIMEOUTCODE_MIN,     TIMEOUTCODE_MAX,     NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    NULL),
   STS_CODE_ELEMENT("Nacelle PT100!",         20*SEC,    3069,      STATUSCODE_UPDATE_TYPE_POLLING,         PASSWORD_LEVEL_SERVICE,            STATUSCODE_TIMER_TYPE_CONSTANT,     STATUSCODE_TIMER_TYPE_CONSTANT,     STATUSCODE_RESET_TYPE_AUTOMATIC,    STATUSCODE_PRIORITY_LOW,       21,   1,    32,   NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    StatusSetFunc3069,       StatusResetFunc3069,     BRAKE_PROG_50,       BRAKE_PROG_0,        BRAKE_PROG_MAX,      NULL,                PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    YAW_PROG_0,          YAW_PROG_0,          YAW_PROG_240,        NULL,                PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    1,    0,    255,  NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            1,  PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      1000,      20,        1000,      NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    5*SEC,     SETDELAY_MIN,   SETDELAY_MAX,   NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      5*SEC,     RESETDELAY_MIN, RESETDELAY_MAX, NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      3,         REPEATTIMES_MIN,     REPEATTIMES_MAX,     NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    1ULL*DAY,  REPEATPERIOD_MIN,    REPEATPERIOD_MAX,    NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    23,        REPEATCODE_MIN,      REPEATCODE_MAX,      NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         TIMEOUTPERIOD_MIN,   TIMEOUTPERIOD_MAX,   NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         TIMEOUTCODE_MIN,     TIMEOUTCODE_MAX,     NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    NULL),
   STS_CODE_ELEMENT("Smoke nacelle",          20*SEC,    2452,      STATUSCODE_UPDATE_TYPE_POLLING,         PASSWORD_LEVEL_SERVICE,            STATUSCODE_TIMER_TYPE_CONSTANT,     STATUSCODE_TIMER_TYPE_CONSTANT,     STATUSCODE_RESET_TYPE_DISPLAY,      STATUSCODE_PRIORITY_LOW,       15,   0,    32,   NULL,      PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_SERVICE,            StatusSetFunc2452,       NULL,                    BRAKE_PROG_50,       BRAKE_PROG_0,        BRAKE_PROG_MAX,      NULL,                PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_MITA_PROGRAMMER,    YAW_PROG_240,        YAW_PROG_0,          YAW_PROG_240,        NULL,                PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_MITA_PROGRAMMER,    1,    0,    255,  NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            1,  PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      1000,      20,        1000,      NULL,      PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         SETDELAY_MIN,   SETDELAY_MAX,   NULL,      PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         RESETDELAY_MIN, RESETDELAY_MAX, NULL,      PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         REPEATTIMES_MIN,     REPEATTIMES_MAX,     NULL,      PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         REPEATPERIOD_MIN,    REPEATPERIOD_MAX,    NULL,      PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         REPEATCODE_MIN,      REPEATCODE_MAX,      NULL,      PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         TIMEOUTPERIOD_MIN,   65535,               NULL,      PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         TIMEOUTCODE_MIN,     TIMEOUTCODE_MAX,     NULL,      PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_SERVICE,            NULL),
   STS_CODE_ELEMENT("MCB Power SC Stop",      20*SEC,    5070,      STATUSCODE_UPDATE_TYPE_POLLING,         PASSWORD_LEVEL_SERVICE,            STATUSCODE_TIMER_TYPE_CONSTANT,     STATUSCODE_TIMER_TYPE_CONSTANT,     STATUSCODE_RESET_TYPE_DISPLAY,      STATUSCODE_PRIORITY_LOW,       24,   0,    32,   NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            StatusSetFunc5070,       NULL,                    BRAKE_PROG_50,       BRAKE_PROG_0,        BRAKE_PROG_MAX,      NULL,                PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    YAW_PROG_240,        YAW_PROG_0,          YAW_PROG_240,        NULL,                PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    1,    0,    255,  NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            1,  PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      100,       20,        1000,      NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         SETDELAY_MIN,   SETDELAY_MAX,   NULL,      PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         RESETDELAY_MIN, RESETDELAY_MAX, NULL,      PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         REPEATTIMES_MIN,     REPEATTIMES_MAX,     NULL,      PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         REPEATPERIOD_MIN,    REPEATPERIOD_MAX,    NULL,      PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         REPEATCODE_MIN,      REPEATCODE_MAX,      NULL,      PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         TIMEOUTPERIOD_MIN,   65535,               NULL,      PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         TIMEOUTCODE_MIN,     TIMEOUTCODE_MAX,     NULL,      PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_SERVICE,            NULL),
};

static STATUS_CODE_CONTROL_BLOCK StatusCodeControlBlock;

static STATUS LocalStatusCodeInit(void)
{
   STATUS LocalStatus;

   LocalStatus = OS_StatusCodeInit(STATUSCODE_INTERFACE_VERSION,
                                   &StatusCodeControlBlock,
                                   StatusCodes,
                                   sizeof(StatusCodes)/sizeof(StatusCodes[0]),
                                   AppLocalParameterPosition(),
                                   AppBackupPosition());
   STATUS_LINE_VAR_RETURN_CONST(LocalStatus, ERR_3);

   return OS_SUCCESS;
}

#define CREATE_STATUS_CODES

//-----------------------------------------------------------------------
// MODIFIABLE                  MODIFIABLE                   MODIFIABLE
//-----------------------------------------------------------------------

extern const char NacelleAppGroupName[];
extern const char NacelleAppMenuName[];

static void Init_Structures_From_Conf_File(void)
{
   M_ObjMainMenuLines[0].LinkName = (char*)NacelleAppMenuName;
   M_ObjMainMenuLines[0].LinkGroup = (char*)NacelleAppGroupName;
}

//-----------------------------------------------------------------------
// AUTOGENERATED END        AUTOGENERATED END        AUTOGENERATED END
//-----------------------------------------------------------------------
//}

#undef AUTOGENERATED_PART

//-----------------------------------------------------------------------
// USER DEFINITIONS         USER DEFINITIONS         USER DEFINITIONS
//-----------------------------------------------------------------------

volatile const U8 Nacelle_ModuleInterfaceError_Version_1; // Version check

// Values for Status of the Sensors
typedef enum _SENSOR_STATUS_t
{
    SENSOR_STATUS_OK = 1,
    SENSOR_STATUS_ERROR,
    SENSOR_STATUS_DISABLED
} SENSOR_STATUS_t;

//-----------------------------------------------------------------------
// SET/RESET FUNCTIONS    SET/RESET FUNCTIONS    SET/RESET FUNCTIONS
//-----------------------------------------------------------------------
static U8 StatusSetFunc30( void )
{
    if( P_NacelleTempEnable && (PT_NacelleTemp > P_NacelleHighTempWarnOn) )
    {
        return 1;
    }
    return 0;
}

static U8 StatusResetFunc30( void )
{
    if( !P_NacelleTempEnable || (PT_NacelleTemp < P_NacelleHighTempWarnOff) )
    {
        return 1;
    }
    return 0;
}

static U8 StatusSetFunc31( void )
{
    if( P_NacelleTempEnable && (PT_NacelleTemp > P_NacelleHighTempStopOn) )
    {
        return 1;
    }
    return 0;
}

static U8 StatusResetFunc31( void )
{
    if( !P_NacelleTempEnable || (PT_NacelleTemp < P_NacelleHighTempStopOff) )
    {
        return 1;
    }
    return 0;
}

U8 StatusSetFunc1563( void )
{
    if( P_NacelleTempEnable && (PT_NacelleTemp < P_NacelleLowTempWarnOn) )
    {
        return 1;
    }

    return 0;
}

U8 StatusResetFunc1563( void )
{
    if( !P_NacelleTempEnable || (PT_NacelleTemp > P_NacelleLowTempWarnOff) )
    {
        return 1;
    }

    return 0;
}

U8 StatusSetFunc2178( void )
{
    if( P_NacelleTempEnable && (PT_NacelleTemp < P_NacelleLowTempStopOn) )
    {
        return 1;
    }

    return 0;
}

U8 StatusResetFunc2178( void )
{
    if( !P_NacelleTempEnable || (PT_NacelleTemp > P_NacelleLowTempStopOff) )
    {
        return 1;
    }

    return 0;
}

//Status Code 3069 : Nacelle PT100!
//-----------------------------------------------------------------------
static U8 StatusSetFunc3069( void )
{
    return (SENSOR_STATUS_ERROR == V_NacelleTempSensorState);
}

static U8 StatusResetFunc3069( void )
{
    return !StatusSetFunc3069();
}

//Status Code 2452 : Smoke nacelle
//-----------------------------------------------------------------------
static U8 StatusSetFunc2452(void)
{
    if ( GridErrorActive() || WPlineError() )
    {
       return 0;
    }

    return !DI_NacelleSmokeDetect;
}

//Status Code 5070 : MCB Power SC Stop
//-----------------------------------------------------------------------
static U8 StatusSetFunc5070(void)
{
   if(DI_Nacelle_MCB_FB_PowerBeforeSC
      && DI_Nacelle_MCB_FB_PowerAfterSC)
   {
      return 0;
   }

   if ( WPlineError() )
   {
      return 0;
   }

   return 1;

}
//-----------------------------------------------------------------------
// DRIVER FUNCTION         DRIVER FUNCTION         DRIVER FUNCTION
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// INIT                   INIT                     INIT
//-----------------------------------------------------------------------

static const U32 SmokeResetTimeout = 3000;   //  3 seconds
static varid_t V_NacelleSmokeDetectorResetID;

static struct StandardTimerVarStruct SmokeResetTimer =
{
   0,                              // Timer value [ms]
   &SmokeResetTimeout,             // Pointer to the timeout variable [ms]
   NACELLE_TIMER,                  // Timer interval [ms]. The function "StandardTimer" is called with this interval.
   TIMER_STOP,                     // Start TIMER_DOWN / TIMER_STOP / TIMER_UP
   0                               // Is used to check if the "StandardTimer" function is called.
};
//-----------------------------------------------------------------------
// CONTROL                CONTROL                 CONTROL
//-----------------------------------------------------------------------
static void SensorStatus( void )
{
    if( !P_NacelleTempEnable )
    {
        V_NacelleTempSensorState = SENSOR_STATUS_DISABLED;
    }
    else if( (PT_NacelleTemp > P_NacelleTempErrHigh) || (PT_NacelleTemp < P_NacelleTempErrLow) )
    {
        V_NacelleTempSensorState = SENSOR_STATUS_ERROR;
    }
    else
    {
        V_NacelleTempSensorState = SENSOR_STATUS_OK;
    }
}
//___________________________________________________________________
static void SensorStatusTxt( S32 Status, S32 *OldStatus, char *Text, S32 Size )
{
    if( Status != *OldStatus )
    {
        switch( Status )
        {
            case SENSOR_STATUS_OK:
            {
                strncpy( Text, "OK", Size );
            }
                break;
            case SENSOR_STATUS_DISABLED:
            {
                strncpy( Text, "Disabled", Size );
            }
                break;
            case SENSOR_STATUS_ERROR:
            {
                strncpy( Text, "Sensor Error", Size );
            }
                break;
            default:
            {
                strncpy( Text, "WARNING", Size );
            }
                break;
        }
    }

    *OldStatus = Status;
}

static void ResetSmokeDetector()
{
    if (V_NacelleSmokeDetectorReset)
    {
        DO_NacelleSmokeDetectorSupply = 0;
        StartTimer(&SmokeResetTimer);
        if (StandardTimer(&SmokeResetTimer))
        {
            V_NacelleSmokeDetectorReset = 0;
            OS_VarDB_UpdateVariable(V_NacelleSmokeDetectorResetID, &V_NacelleSmokeDetectorReset, sizeof V_NacelleSmokeDetectorReset);
            DO_NacelleSmokeDetectorSupply = 1;
        }
    }
    else
    {
        ResetTimer(&SmokeResetTimer);
        DO_NacelleSmokeDetectorSupply = 1;
    }
}

static STATUS LocalCtrl( void )
{
    static S32 NacelleTempSensorState_Old = 100500;

    // Update value to 5min log and total log
    V_TempNacelleLog = PT_NacelleTemp;

    SensorStatus();
    SensorStatusTxt( V_NacelleTempSensorState, &NacelleTempSensorState_Old, V_NacelleTempSensorStateTxt, sizeof(V_NacelleTempSensorStateTxt) );
    ResetSmokeDetector();

    return OS_SUCCESS;
}

//-----------------------------------------------------------------------
// MAIN CALL             MAIN CALL               MAIN CALL
//-----------------------------------------------------------------------

STATUS Nacelle( U8 ModuleState, OS_MEMORY_POOL *MemPool, U32 *Arg3 )
{
    STATUS LocalStatus = 0;

    // Version check
    if( ModuleState == APP_INIT1 )
    {
        LocalStatus = OS_ValidateAPI( OS_SERVICES->APIVersionMajor,
                                      OS_SERVICES->APIVersionMinor,
                                      OS_LinkTime,
                                      ReleaseTag,
                                      __MODULE__ );
        if( OS_SUCCESS != LocalStatus )
        {
            return LocalStatus;
        }
    }
#ifdef READ_VARS
    // Read inputdata
    LocalStatus = InputReferenceRoutine( ModuleState );
    STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif
#ifdef CREATE_MENU
    if( ModuleState == APP_INIT1 || ModuleState == APP_INIT4 )
    {
        LocalStatus = NacelleMenuAppInit( ModuleState, MemPool );
        STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
    }
#endif
    switch( ModuleState )
    {
        case APP_RUN:
        {
         #ifdef FUNCTION_BLOCKS_PRE_LOCAL_CONTROL
            LocalStatus = FunctionBlocksPreLocalCtrl( Interval );
            STATUS_LINE_VAR_RETURN_VALUE( LocalStatus );
         #endif

            LocalStatus = LocalCtrl();
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
        
         #ifdef FUNCTION_BLOCKS_POST_LOCAL_CONTROL
            LocalStatus = FunctionBlocksPostLocalCtrl( Interval );
            STATUS_LINE_VAR_RETURN_VALUE( LocalStatus );
         #endif

#ifdef WRITE_VARS
            // Write Outputdata
            LocalStatus = OutputReferenceRoutine( ModuleState );
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif
            break;
        }
        case APP_INIT1:
        {
            Init_Structures_From_Conf_File();
            (void)Nacelle_ModuleInterfaceError_Version_1; // Version check
#ifdef CREATE_VARDB_VARS
            LocalStatus = CreateVarDbVars();
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif
#ifdef CREATE_IO_VARS
            LocalStatus = CreateIOVars();
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif
#ifdef CREATE_ALIASES
            size_t ErrorEntry = 0;
            LocalStatus = OS_VarDB_CreateAliases( AliasVars, sizeof(AliasVars) / sizeof(AliasVars[ 0 ]), &ErrorEntry );
            STATUS_LINE_VAR_RETURN_CONST(LocalStatus, ErrorEntry)
#endif

            break;
        }
        case APP_INIT2:
        {
#ifdef VERIFY_VARIABLES
            LocalStatus = LocalIoCheck();
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif

#ifdef CREATE_BUTTONS
            LocalStatus = CreateButtons();
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif
            break;
        }
        case APP_INIT3:
        {
#ifdef CREATE_SUMMATIONS
            LocalStatus = CreateSummations();
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif

#ifdef WRITE_VARS
            LocalStatus = InitOutputVars();
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif

#ifdef CREATE_STATUS_CODES
            LocalStatus = LocalStatusCodeInit();
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif
#ifdef CREATE_IO_VARS
            NacelleSetLockValues();
#endif
            break;
        }
        case APP_INIT4:
        {
            break;
        }
        case APP_INIT5:
        {

         #ifdef INIT_FUNCTION_BLOCKS
            LocalStatus = FunctionBlocksInit( Interval );
            STATUS_LINE_VAR_RETURN_VALUE( LocalStatus );
         #endif

            LocalStatus = OS_VarDB_GetVariableID("V_NacelleSmokeDetectorReset", &V_NacelleSmokeDetectorResetID);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
            break;
        }
        default:
        {
            break;
        }
    }
    return OS_SUCCESS;
}
//-----------------------------------------------------------------------
