//*****************************PEPTOOL Header Start******************************
//                                                                               
//                         Copyright © 2015 Mita-Teknik.                         
//This software may only be used with WP4x00 Controllers delivered by Mita-Teknik
//                                                                               
//*******************************************************************************
//                                                                               
// $PEPTOOL version:9.0$                                                         
// $PEPTOOL file version:101$                                                    
//                                                                               
//*******************************************************************************
//                                                                               
// $Date: XXXX/XX/XX XX:XX:XX $                                                  
// $Author: XXXX\XXX $                                                           
// $RCSfile: NacelleAcceleration_Conf.c,v $                                      
// $Revision: X.X $                                                              
//                                                                               
//******************************PEPTOOL Header End*******************************

//***********************************************************************
// OS header files
#include <os_main.h>
// App header files
#include <InitIo.h>

#define AUTOGENERATED_PART

#include <Turbdef.h>

//-----------------------------------------------------------------------
// AUTOGENERATED START     AUTOGENERATED START     AUTOGENERATED START
//-----------------------------------------------------------------------
char NacelleAcceleration_Conf_copyright[] =
{
   67, 111, 112, 121, 114, 105, 103, 104, 116, 32, 63, 32, 50, 48, 49, 53,
   32, 77, 105, 116, 97, 45, 84, 101, 107, 110, 105, 107, 46, 13, 10, 84,
   104, 105, 115, 32, 115, 111, 102, 116, 119, 97, 114, 101, 32, 109, 97, 121,
   32, 111, 110, 108, 121, 32, 98, 101, 32, 117, 115, 101, 100, 32, 119, 105,
   116, 104, 32, 87, 80, 52, 120, 48, 48, 32, 67, 111, 110, 116, 114, 111,
   108, 108, 101, 114, 115, 32, 100, 101, 108, 105, 118, 101, 114, 101, 100, 32,
   98, 121, 32, 77, 105, 116, 97, 45, 84, 101, 107, 110, 105, 107, 0
};
//-----------------------------------------------------------------------
// MODIFIABLE                  MODIFIABLE               MODIFIABLE
//-----------------------------------------------------------------------
const char NacelleAccelerationAppGroupName[] = "G_"APP_ID"App";
const char NacelleAccelerationAppMenuName[] = "M_"APP_ID"AppMain";

//-----------------------------------------------------------------------
// IO VARIABLES                IO VARIABLES                IO VARIABLES
//-----------------------------------------------------------------------

void (*NacelleAccelerationSetLockValues)(void);
struct os_db_alias *NacelleAccelerationIOVars;
size_t NacelleAccelerationIOVarsSize = 0;
            
struct os_db_alias NacelleAccelerationIOVars1[]=
{
    VAR_ELEMENT_ALIAS("3.2.57",                           "AI_NAC_AccSideSide"),
    VAR_ELEMENT_ALIAS("3.2.57_Ss",                        "AI_NAC_AccSideSide_Ss"),
    VAR_ELEMENT_ALIAS("3.2.57_E",                         "AI_NAC_AccSideSide_E"),
    VAR_ELEMENT_ALIAS( "3.2.57_Th",                        "AI_NAC_AccSideSide_Th"),
    VAR_ELEMENT_ALIAS("3.2.57_Ht",                        "AI_NAC_AccSideSide_Ht"),
    VAR_ELEMENT_ALIAS("3.2.57_S",                         "AI_NAC_AccSideSide_S"),
    VAR_ELEMENT_ALIAS("3.2.57_O",                         "AI_NAC_AccSideSide_O"),

    VAR_ELEMENT_ALIAS("3.2.58",                           "AI_NAC_AccForeAft"),
    VAR_ELEMENT_ALIAS("3.2.58_Ss",                        "AI_NAC_AccForeAft_Ss"),
    VAR_ELEMENT_ALIAS("3.2.58_E",                         "AI_NAC_AccForeAft_E"),
    VAR_ELEMENT_ALIAS( "3.2.58_Th",                        "AI_NAC_AccForeAft_Th"),
    VAR_ELEMENT_ALIAS("3.2.58_Ht",                        "AI_NAC_AccForeAft_Ht"),
    VAR_ELEMENT_ALIAS("3.2.58_S",                         "AI_NAC_AccForeAft_S"),
    VAR_ELEMENT_ALIAS("3.2.58_O",                         "AI_NAC_AccForeAft_O"),

};
size_t NacelleAccelerationIOVars1Size = sizeof(NacelleAccelerationIOVars1)/sizeof(NacelleAccelerationIOVars1[0]);

void NacelleAccelerationSetLockValues1(void)
{
   SetLockValue("AI_NAC_AccSideSide_Ss",                 TYP_8,     1);
   SetLockValue("AI_NAC_AccSideSide_E",                  TYP_8,     1);
   SetLockValue("AI_NAC_AccSideSide_Th",                 TYP_16,    1);
   SetLockValue("AI_NAC_AccSideSide_Ht",                 TYP_32,    20);
   SetLockValue("AI_NAC_AccSideSide_S",                  TYP_32,    0);
   SetValue("AI_NAC_AccSideSide_O",                      TYP_32,    0);

   SetLockValue("AI_NAC_AccForeAft_Ss",                  TYP_8,     1);
   SetLockValue("AI_NAC_AccForeAft_E",                   TYP_8,     1);
   SetLockValue("AI_NAC_AccForeAft_Th",                  TYP_16,    1);
   SetLockValue("AI_NAC_AccForeAft_Ht",                  TYP_32,    20);
   SetLockValue("AI_NAC_AccForeAft_S",                   TYP_32,    0);
   SetValue("AI_NAC_AccForeAft_O",                       TYP_32,    0);
}


STATUS NacelleAccelerationInitIOAliases()
{
   NacelleAccelerationIOVars = NacelleAccelerationIOVars1;
   NacelleAccelerationIOVarsSize = NacelleAccelerationIOVars1Size;
   NacelleAccelerationSetLockValues = &NacelleAccelerationSetLockValues1;
   return OS_SUCCESS;
}
//-----------------------------------------------------------------------
// AUTOGENERATED END        AUTOGENERATED END        AUTOGENERATED END
//-----------------------------------------------------------------------

#undef AUTOGENERATED_PART
