//*****************************PEPTOOL Header Start******************************
//                                                                               
//                         Copyright © 2015 Mita-Teknik.                         
//This software may only be used with WP4x00 Controllers delivered by Mita-Teknik
//                                                                               
//*******************************************************************************
//                                                                               
// $PEPTOOL version:9.0$                                                         
// $PEPTOOL file version:101$                                                    
//                                                                               
//*******************************************************************************
//                                                                               
// $Date: 2014/04/23 06:33:08 $                                                  
// $Author: MITA\ihn $                                                           
// $RCSfile: Nacelle_Conf.c,v $                                                  
// $Revision: 1.12 $                                                             
//                                                                               
//******************************PEPTOOL Header End*******************************

//***********************************************************************
// OS header files
#include <os_main.h>
// IO init file
#include <InitIo.h>
      
#define AUTOGENERATED_PART

#include <Turbdef.h>

//-----------------------------------------------------------------------
// AUTOGENERATED START     AUTOGENERATED START     AUTOGENERATED START
//-----------------------------------------------------------------------
char Nacelle_Conf_copyright[] =
{
   67, 111, 112, 121, 114, 105, 103, 104, 116, 32, 63, 32, 50, 48, 49, 53,
   32, 77, 105, 116, 97, 45, 84, 101, 107, 110, 105, 107, 46, 13, 10, 84,
   104, 105, 115, 32, 115, 111, 102, 116, 119, 97, 114, 101, 32, 109, 97, 121,
   32, 111, 110, 108, 121, 32, 98, 101, 32, 117, 115, 101, 100, 32, 119, 105,
   116, 104, 32, 87, 80, 52, 120, 48, 48, 32, 67, 111, 110, 116, 114, 111,
   108, 108, 101, 114, 115, 32, 100, 101, 108, 105, 118, 101, 114, 101, 100, 32,
   98, 121, 32, 77, 105, 116, 97, 45, 84, 101, 107, 110, 105, 107, 0
};
//-----------------------------------------------------------------------
// MODIFIABLE                  MODIFIABLE               MODIFIABLE
//-----------------------------------------------------------------------
const char NacelleAppGroupName[] = "G_"APP_ID"App";
const char NacelleAppMenuName[] = "M_"APP_ID"AppMain";

//-----------------------------------------------------------------------
// IO VARIABLES                IO VARIABLES                IO VARIABLES
//-----------------------------------------------------------------------

void (*NacelleSetLockValues)(void);
struct os_db_alias *NacelleIOVars;
size_t NacelleIOVarsSize = 0;
            
struct os_db_alias NacelleIOVars1[]=
{
    VAR_ELEMENT_ALIAS("3.2.66",                           "PT_NacelleTemp"),
    VAR_ELEMENT_ALIAS("3.2.66_Ss",                        "PT_NacelleTemp_Ss"),
    VAR_ELEMENT_ALIAS("3.2.66_E",                         "PT_NacelleTemp_E"),
    VAR_ELEMENT_ALIAS( "3.2.66_Th",                        "PT_NacelleTemp_Th"),
    VAR_ELEMENT_ALIAS("3.2.66_Ht",                        "PT_NacelleTemp_Ht"),
    VAR_ELEMENT_ALIAS("3.2.66_S",                         "PT_NacelleTemp_S"),
    VAR_ELEMENT_ALIAS("3.2.66_O",                         "PT_NacelleTemp_O"),

    VAR_ELEMENT_ALIAS("3.3.41",                           "DI_NacelleSmokeDetect"),
    VAR_ELEMENT_ALIAS("3.3.41_Ss",                        "DI_NacelleSmokeDetect_Ss"),
    VAR_ELEMENT_ALIAS("3.3.41_E",                         "DI_NacelleSmokeDetect_E"),
    VAR_ELEMENT_ALIAS("3.3.41_I",                         "DI_NacelleSmokeDetect_I"),
    VAR_ELEMENT_ALIAS("3.3.41_Cm",                        "DI_NacelleSmokeDetect_Cm"),
    VAR_ELEMENT_ALIAS("3.3.41_Ht",                        "DI_NacelleSmokeDetect_Ht"),

    VAR_ELEMENT_ALIAS("3.3.12",                           "DO_NacelleSmokeDetectorSupply"),

    VAR_ELEMENT_ALIAS("3.2.44",                           "DI_Nacelle_MCB_FB_PowerBeforeSC"),
    VAR_ELEMENT_ALIAS("3.2.44_Ss",                        "DI_Nacelle_MCB_FB_PowerBeforeSC_Ss"),
    VAR_ELEMENT_ALIAS("3.2.44_E",                         "DI_Nacelle_MCB_FB_PowerBeforeSC_E"),
    VAR_ELEMENT_ALIAS("3.2.44_I",                         "DI_Nacelle_MCB_FB_PowerBeforeSC_I"),
    VAR_ELEMENT_ALIAS("3.2.44_Cm",                        "DI_Nacelle_MCB_FB_PowerBeforeSC_Cm"),
    VAR_ELEMENT_ALIAS("3.2.44_Ht",                        "DI_Nacelle_MCB_FB_PowerBeforeSC_Ht"),

    VAR_ELEMENT_ALIAS("3.2.45",                           "DI_Nacelle_MCB_FB_PowerAfterSC"),
    VAR_ELEMENT_ALIAS("3.2.45_Ss",                        "DI_Nacelle_MCB_FB_PowerAfterSC_Ss"),
    VAR_ELEMENT_ALIAS("3.2.45_E",                         "DI_Nacelle_MCB_FB_PowerAfterSC_E"),
    VAR_ELEMENT_ALIAS("3.2.45_I",                         "DI_Nacelle_MCB_FB_PowerAfterSC_I"),
    VAR_ELEMENT_ALIAS("3.2.45_Cm",                        "DI_Nacelle_MCB_FB_PowerAfterSC_Cm"),
    VAR_ELEMENT_ALIAS("3.2.45_Ht",                        "DI_Nacelle_MCB_FB_PowerAfterSC_Ht"),

};
size_t NacelleIOVars1Size = sizeof(NacelleIOVars1)/sizeof(NacelleIOVars1[0]);

void NacelleSetLockValues1(void)
{
   SetLockValue("PT_NacelleTemp_Ss",                     TYP_8,     1);
   SetLockValue("PT_NacelleTemp_E",                      TYP_8,     1);
   SetLockValue("PT_NacelleTemp_Th",                     TYP_16,    10);
   SetLockValue("PT_NacelleTemp_Ht",                     TYP_32,    1000);
   SetLockValue("PT_NacelleTemp_S",                      TYP_32,    0);
   SetValue("PT_NacelleTemp_O",                          TYP_32,    0);

   SetLockValue("DI_NacelleSmokeDetect_Ss",              TYP_8,     1);
   SetLockValue("DI_NacelleSmokeDetect_E",               TYP_8,     1);
   SetValue("DI_NacelleSmokeDetect_I",                   TYP_8,     0);
   SetLockValue("DI_NacelleSmokeDetect_Cm",              TYP_8,     1);
   SetLockValue("DI_NacelleSmokeDetect_Ht",              TYP_32,    100);

   SetLockValue("DI_Nacelle_MCB_FB_PowerBeforeSC_Ss",    TYP_8,     1);
   SetLockValue("DI_Nacelle_MCB_FB_PowerBeforeSC_E",     TYP_8,     1);
   SetValue("DI_Nacelle_MCB_FB_PowerBeforeSC_I",         TYP_8,     0);
   SetLockValue("DI_Nacelle_MCB_FB_PowerBeforeSC_Cm",    TYP_8,     1);
   SetLockValue("DI_Nacelle_MCB_FB_PowerBeforeSC_Ht",    TYP_32,    100);

   SetLockValue("DI_Nacelle_MCB_FB_PowerAfterSC_Ss",     TYP_8,     1);
   SetLockValue("DI_Nacelle_MCB_FB_PowerAfterSC_E",      TYP_8,     1);
   SetValue("DI_Nacelle_MCB_FB_PowerAfterSC_I",          TYP_8,     0);
   SetLockValue("DI_Nacelle_MCB_FB_PowerAfterSC_Cm",     TYP_8,     1);
   SetLockValue("DI_Nacelle_MCB_FB_PowerAfterSC_Ht",     TYP_32,    100);
}


STATUS NacelleInitIOAliases()
{
   NacelleIOVars = NacelleIOVars1;
   NacelleIOVarsSize = NacelleIOVars1Size;
   NacelleSetLockValues = &NacelleSetLockValues1;
   return OS_SUCCESS;
}
//-----------------------------------------------------------------------
// AUTOGENERATED END        AUTOGENERATED END        AUTOGENERATED END
//-----------------------------------------------------------------------

#undef AUTOGENERATED_PART

const char NacelleAppDisplayText[] = N_("APPLICATION");
