//*****************************PEPTOOL Header Start******************************
//                                                                               
//                         Copyright © 2015 Mita-Teknik.                         
//This software may only be used with WP4x00 Controllers delivered by Mita-Teknik
//                                                                               
//*******************************************************************************
//                                                                               
// $PEPTOOL version:9.0$                                                         
// $PEPTOOL file version:101$                                                    
//                                                                               
//*******************************************************************************
//                                                                               
// $Date: 2014/06/06 05:11:23 $                                                  
// $Author: MITA\ihn $                                                           
// $RCSfile: Operate_MT_Type2_Conf.c,v $                                         
// $Revision: 1.14 $                                                             
//                                                                               
//******************************PEPTOOL Header End*******************************

//***********************************************************************
// OS header files
#include <os_main.h>
// IO init file
#include <InitIo.h>
      
#define AUTOGENERATED_PART

#include <Turbdef.h>

//-----------------------------------------------------------------------
// AUTOGENERATED START     AUTOGENERATED START     AUTOGENERATED START
//-----------------------------------------------------------------------
char Operate_MT_Type2_Conf_copyright[] =
{
   67, 111, 112, 121, 114, 105, 103, 104, 116, 32, 63, 32, 50, 48, 49, 53,
   32, 77, 105, 116, 97, 45, 84, 101, 107, 110, 105, 107, 46, 13, 10, 84,
   104, 105, 115, 32, 115, 111, 102, 116, 119, 97, 114, 101, 32, 109, 97, 121,
   32, 111, 110, 108, 121, 32, 98, 101, 32, 117, 115, 101, 100, 32, 119, 105,
   116, 104, 32, 87, 80, 52, 120, 48, 48, 32, 67, 111, 110, 116, 114, 111,
   108, 108, 101, 114, 115, 32, 100, 101, 108, 105, 118, 101, 114, 101, 100, 32,
   98, 121, 32, 77, 105, 116, 97, 45, 84, 101, 107, 110, 105, 107, 0
};
//-----------------------------------------------------------------------
// MODIFIABLE                  MODIFIABLE               MODIFIABLE
//-----------------------------------------------------------------------
const char Operate_MT_Type2AppGroupName[] = "G_"APP_ID"App";
const char Operate_MT_Type2AppMenuName[] = "M_"APP_ID"AppMain";

//-----------------------------------------------------------------------
// IO VARIABLES                IO VARIABLES                IO VARIABLES
//-----------------------------------------------------------------------

void (*Operate_MT_Type2SetLockValues)(void);
struct os_db_alias *Operate_MT_Type2IOVars;
size_t Operate_MT_Type2IOVarsSize = 0;
            
struct os_db_alias Operate_MT_Type2IOVars1[]=
{
    VAR_ELEMENT_ALIAS("1.4.26",                           "DI_ManualStopTowerBase"),
    VAR_ELEMENT_ALIAS("1.4.26_Ss",                        "DI_ManualStopTowerBase_Ss"),
    VAR_ELEMENT_ALIAS("1.4.26_E",                         "DI_ManualStopTowerBase_E"),
    VAR_ELEMENT_ALIAS("1.4.26_I",                         "DI_ManualStopTowerBase_I"),
    VAR_ELEMENT_ALIAS("1.4.26_Cm",                        "DI_ManualStopTowerBase_Cm"),
    VAR_ELEMENT_ALIAS("1.4.26_Ht",                        "DI_ManualStopTowerBase_Ht"),

    VAR_ELEMENT_ALIAS("3.2.39",                           "DI_ManualStopNacelle"),
    VAR_ELEMENT_ALIAS("3.2.39_Ss",                        "DI_ManualStopNacelle_Ss"),
    VAR_ELEMENT_ALIAS("3.2.39_E",                         "DI_ManualStopNacelle_E"),
    VAR_ELEMENT_ALIAS("3.2.39_I",                         "DI_ManualStopNacelle_I"),
    VAR_ELEMENT_ALIAS("3.2.39_Cm",                        "DI_ManualStopNacelle_Cm"),
    VAR_ELEMENT_ALIAS("3.2.39_Ht",                        "DI_ManualStopNacelle_Ht"),

    VAR_ELEMENT_ALIAS("1.4.27",                           "DI_ServiceModeSwitch"),
    VAR_ELEMENT_ALIAS("1.4.27_Ss",                        "DI_ServiceModeSwitch_Ss"),
    VAR_ELEMENT_ALIAS("1.4.27_E",                         "DI_ServiceModeSwitch_E"),
    VAR_ELEMENT_ALIAS("1.4.27_I",                         "DI_ServiceModeSwitch_I"),
    VAR_ELEMENT_ALIAS("1.4.27_Cm",                        "DI_ServiceModeSwitch_Cm"),
    VAR_ELEMENT_ALIAS("1.4.27_Ht",                        "DI_ServiceModeSwitch_Ht"),

};
size_t Operate_MT_Type2IOVars1Size = sizeof(Operate_MT_Type2IOVars1)/sizeof(Operate_MT_Type2IOVars1[0]);

void Operate_MT_Type2SetLockValues1(void)
{
   SetLockValue("DI_ManualStopTowerBase_Ss",             TYP_8,     1);
   SetLockValue("DI_ManualStopTowerBase_E",              TYP_8,     1);
   SetValue("DI_ManualStopTowerBase_I",                  TYP_8,     0);
   SetLockValue("DI_ManualStopTowerBase_Cm",             TYP_8,     1);
   SetLockValue("DI_ManualStopTowerBase_Ht",             TYP_32,    1000);

   SetLockValue("DI_ManualStopNacelle_Ss",               TYP_8,     1);
   SetLockValue("DI_ManualStopNacelle_E",                TYP_8,     1);
   SetValue("DI_ManualStopNacelle_I",                    TYP_8,     0);
   SetLockValue("DI_ManualStopNacelle_Cm",               TYP_8,     1);
   SetLockValue("DI_ManualStopNacelle_Ht",               TYP_32,    1000);

   SetLockValue("DI_ServiceModeSwitch_Ss",               TYP_8,     1);
   SetLockValue("DI_ServiceModeSwitch_E",                TYP_8,     1);
   SetValue("DI_ServiceModeSwitch_I",                    TYP_8,     0);
   SetLockValue("DI_ServiceModeSwitch_Cm",               TYP_8,     1);
   SetLockValue("DI_ServiceModeSwitch_Ht",               TYP_32,    1000);
}


STATUS Operate_MT_Type2InitIOAliases()
{
   Operate_MT_Type2IOVars = Operate_MT_Type2IOVars1;
   Operate_MT_Type2IOVarsSize = Operate_MT_Type2IOVars1Size;
   Operate_MT_Type2SetLockValues = &Operate_MT_Type2SetLockValues1;
   return OS_SUCCESS;
}
//-----------------------------------------------------------------------
// AUTOGENERATED END        AUTOGENERATED END        AUTOGENERATED END
//-----------------------------------------------------------------------

#undef AUTOGENERATED_PART
