//*****************************PEPTOOL Header Start******************************
//                                                                               
//                         Copyright © 2015 Mita-Teknik.                         
//This software may only be used with WP4x00 Controllers delivered by Mita-Teknik
//                                                                               
//*******************************************************************************
//                                                                               
// $PEPTOOL version:9.0$                                                         
// $PEPTOOL file version:101$                                                    
//                                                                               
//*******************************************************************************
//                                                                               
// $Date: 2014/03/06 15:58:28 $                                                  
// $Author: MITA\ihn $                                                           
// $RCSfile: OutdoorTemperature_Conf.c,v $                                       
// $Revision: 1.7 $                                                              
//                                                                               
//******************************PEPTOOL Header End*******************************

//***********************************************************************
// OS header files
#include <os_main.h>
// App header files
#include <InitIo.h>

#define AUTOGENERATED_PART

#include <Turbdef.h>

//-----------------------------------------------------------------------
// AUTOGENERATED START     AUTOGENERATED START     AUTOGENERATED START
//-----------------------------------------------------------------------
char OutdoorTemperature_Conf_copyright[] =
{
   67, 111, 112, 121, 114, 105, 103, 104, 116, 32, 63, 32, 50, 48, 49, 53,
   32, 77, 105, 116, 97, 45, 84, 101, 107, 110, 105, 107, 46, 13, 10, 84,
   104, 105, 115, 32, 115, 111, 102, 116, 119, 97, 114, 101, 32, 109, 97, 121,
   32, 111, 110, 108, 121, 32, 98, 101, 32, 117, 115, 101, 100, 32, 119, 105,
   116, 104, 32, 87, 80, 52, 120, 48, 48, 32, 67, 111, 110, 116, 114, 111,
   108, 108, 101, 114, 115, 32, 100, 101, 108, 105, 118, 101, 114, 101, 100, 32,
   98, 121, 32, 77, 105, 116, 97, 45, 84, 101, 107, 110, 105, 107, 0
};
//-----------------------------------------------------------------------
// MODIFIABLE                  MODIFIABLE               MODIFIABLE
//-----------------------------------------------------------------------
const char OutdoorTemperatureAppGroupName[] = "G_"APP_ID"App";
const char OutdoorTemperatureAppMenuName[] = "M_"APP_ID"AppMain";

//-----------------------------------------------------------------------
// IO VARIABLES                IO VARIABLES                IO VARIABLES
//-----------------------------------------------------------------------

void (*OutdoorTemperatureSetLockValues)(void);
struct os_db_alias *OutdoorTemperatureIOVars;
size_t OutdoorTemperatureIOVarsSize = 0;
            
struct os_db_alias OutdoorTemperatureIOVars1[]=
{
    VAR_ELEMENT_ALIAS("3.4.1",                            "PT_OutdoorTemperature"),
    VAR_ELEMENT_ALIAS("3.4.1_Ss",                         "PT_OutdoorTemperature_Ss"),
    VAR_ELEMENT_ALIAS("3.4.1_E",                          "PT_OutdoorTemperature_E"),
    VAR_ELEMENT_ALIAS( "3.4.1_Th",                         "PT_OutdoorTemperature_Th"),
    VAR_ELEMENT_ALIAS("3.4.1_Ht",                         "PT_OutdoorTemperature_Ht"),
    VAR_ELEMENT_ALIAS("3.4.1_S",                          "PT_OutdoorTemperature_S"),
    VAR_ELEMENT_ALIAS("3.4.1_O",                          "PT_OutdoorTemperature_O"),

    VAR_ELEMENT_ALIAS("3.3.61",                           "AI_OutdoorAirHumidity"),
    VAR_ELEMENT_ALIAS("3.3.61_Ss",                        "AI_OutdoorAirHumidity_Ss"),
    VAR_ELEMENT_ALIAS("3.3.61_E",                         "AI_OutdoorAirHumidity_E"),
    VAR_ELEMENT_ALIAS( "3.3.61_Th",                        "AI_OutdoorAirHumidity_Th"),
    VAR_ELEMENT_ALIAS("3.3.61_Ht",                        "AI_OutdoorAirHumidity_Ht"),
    VAR_ELEMENT_ALIAS("3.3.61_S",                         "AI_OutdoorAirHumidity_S"),
    VAR_ELEMENT_ALIAS("3.3.61_O",                         "AI_OutdoorAirHumidity_O"),

    VAR_ELEMENT_ALIAS("3.3.62",                           "AI_OutdoorTempSensor4_Curr"),
    VAR_ELEMENT_ALIAS("3.3.62_Ss",                        "AI_OutdoorTempSensor4_Curr_Ss"),
    VAR_ELEMENT_ALIAS("3.3.62_E",                         "AI_OutdoorTempSensor4_Curr_E"),
    VAR_ELEMENT_ALIAS( "3.3.62_Th",                        "AI_OutdoorTempSensor4_Curr_Th"),
    VAR_ELEMENT_ALIAS("3.3.62_Ht",                        "AI_OutdoorTempSensor4_Curr_Ht"),
    VAR_ELEMENT_ALIAS("3.3.62_S",                         "AI_OutdoorTempSensor4_Curr_S"),
    VAR_ELEMENT_ALIAS("3.3.62_O",                         "AI_OutdoorTempSensor4_Curr_O"),

};
size_t OutdoorTemperatureIOVars1Size = sizeof(OutdoorTemperatureIOVars1)/sizeof(OutdoorTemperatureIOVars1[0]);

void OutdoorTemperatureSetLockValues1(void)
{
   SetLockValue("PT_OutdoorTemperature_Ss",              TYP_8,     1);
   SetLockValue("PT_OutdoorTemperature_E",               TYP_8,     1);
   SetLockValue("PT_OutdoorTemperature_Th",              TYP_16,    10);
   SetLockValue("PT_OutdoorTemperature_Ht",              TYP_32,    1000);
   SetLockValue("PT_OutdoorTemperature_S",               TYP_32,    0);
   SetValue("PT_OutdoorTemperature_O",                   TYP_32,    0);

   SetLockValue("AI_OutdoorAirHumidity_Ss",              TYP_8,     1);
   SetLockValue("AI_OutdoorAirHumidity_E",               TYP_8,     1);
   SetLockValue("AI_OutdoorAirHumidity_Th",              TYP_16,    50);
   SetLockValue("AI_OutdoorAirHumidity_Ht",              TYP_32,    1000);
   SetLockValue("AI_OutdoorAirHumidity_S",               TYP_32,    0);
   SetValue("AI_OutdoorAirHumidity_O",                   TYP_32,    0);

   SetLockValue("AI_OutdoorTempSensor4_Curr_Ss",         TYP_8,     1);
   SetLockValue("AI_OutdoorTempSensor4_Curr_E",          TYP_8,     1);
   SetLockValue("AI_OutdoorTempSensor4_Curr_Th",         TYP_16,    10);
   SetLockValue("AI_OutdoorTempSensor4_Curr_Ht",         TYP_32,    1000);
   SetLockValue("AI_OutdoorTempSensor4_Curr_S",          TYP_32,    0);
   SetValue("AI_OutdoorTempSensor4_Curr_O",              TYP_32,    0);
}


STATUS OutdoorTemperatureInitIOAliases()
{
   OutdoorTemperatureIOVars = OutdoorTemperatureIOVars1;
   OutdoorTemperatureIOVarsSize = OutdoorTemperatureIOVars1Size;
   OutdoorTemperatureSetLockValues = &OutdoorTemperatureSetLockValues1;
   return OS_SUCCESS;
}
//-----------------------------------------------------------------------
// AUTOGENERATED END        AUTOGENERATED END        AUTOGENERATED END
//-----------------------------------------------------------------------

#undef AUTOGENERATED_PART
