//*****************************PEPTOOL Header Start******************************
//                                                                               
//                         Copyright © 2015 Mita-Teknik.                         
//This software may only be used with WP4x00 Controllers delivered by Mita-Teknik
//                                                                               
//*******************************************************************************
//                                                                               
// $PEPTOOL version:9.0$                                                         
// $PEPTOOL file version:106$                                                    
//                                                                               
//*******************************************************************************
//                                                                               
// $Date: 2014/05/23 09:10:17 $                                                  
// $Author: MITA\ihn $                                                           
// $RCSfile: OutdoorTemperature.c,v $                                            
// $Revision: 1.11 $                                                             
//                                                                               
//******************************PEPTOOL Header End*******************************

//***********************************************************************

// OS header files
#include <os_main.h>
// AppLib header files
#include <lib_main.h>
// App header files
#include <turbdef.h>
#include <VarMacros.h>

// Object header file
#include <OutdoorTemperature.h>

#define AUTOGENERATED_PART
//{
//-----------------------------------------------------------------------
// AUTOGENERATED START     AUTOGENERATED START     AUTOGENERATED START
//-----------------------------------------------------------------------

#define VALIDATE_HASH
char OutdoorTemperature_copyright[] =
{
   67, 111, 112, 121, 114, 105, 103, 104, 116, 32, 63, 32, 50, 48, 49, 53,
   32, 77, 105, 116, 97, 45, 84, 101, 107, 110, 105, 107, 46, 13, 10, 84,
   104, 105, 115, 32, 115, 111, 102, 116, 119, 97, 114, 101, 32, 109, 97, 121,
   32, 111, 110, 108, 121, 32, 98, 101, 32, 117, 115, 101, 100, 32, 119, 105,
   116, 104, 32, 87, 80, 52, 120, 48, 48, 32, 67, 111, 110, 116, 114, 111,
   108, 108, 101, 114, 115, 32, 100, 101, 108, 105, 118, 101, 114, 101, 100, 32,
   98, 121, 32, 77, 105, 116, 97, 45, 84, 101, 107, 110, 105, 107, 0
};

#define MODULE_NAME "Outdoor TemperatureA"

//-----------------------------------------------------------------------
// ALLOCATE MEMORY FOR STRINGS IN VARDB
//-----------------------------------------------------------------------

static char A_V_OutdoorTempSensorsActiveText[31]  = "12345678901234567890123456789";
static char A_V_OutdoorTempSensor1StatusText[31]  = "12345678901234567890123456789";
static char A_V_OutdoorTempSensor2StatusText[31]  = "12345678901234567890123456789";
static char A_V_OutdoorTempSensor3StatusText[31]  = "12345678901234567890123456789";
static char A_V_OutdoorAirHumidity_StatusText[31]  = "12345678901234567890123456789";
static char A_V_OutdoorTempSensor4StatusTxt[31]  = "not defined";

//-----------------------------------------------------------------------
// DEFINE LOCAL VARIABLES DEFINE LOCAL VARIABLES DEFINE LOCAL VARIABLES
//-----------------------------------------------------------------------

static struct os_db_local LocalVars[] =
{
   VAR_ELEMENT_LOCAL("V_OutDoorTemp",                            TYPE_S16,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    10,      UNIT_CELSIUS,       1,   0,               -400,            999,             NULL,  TOTLOG_ENABLE | FIVEMINLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_OutDoorTemp1Sec",                        TYPE_S16,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    10,      UNIT_CELSIUS,       1,   0,               -400,            999,             NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_OutDoorTemp3Sec",                        TYPE_S16,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    10,      UNIT_CELSIUS,       1,   0,               -400,            999,             NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_OutDoorTemp30Sec",                       TYPE_S16,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    10,      UNIT_CELSIUS,       1,   0,               -400,            999,             NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_OutDoorTemp10Min",                       TYPE_S16,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    10,      UNIT_CELSIUS,       1,   0,               -400,            999,             NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_OutdoorTempSensorsActiveText",           TYPE_STRING + sizeof(A_V_OutdoorTempSensorsActiveText) - 1,  PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   A_V_OutdoorTempSensorsActiveText, 0,                0,                NULL,  NOLOG_ENABLE  ),
   VAR_ELEMENT_LOCAL("V_OutdoorTempSensor1StatusText",           TYPE_STRING + sizeof(A_V_OutdoorTempSensor1StatusText) - 1,  PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   A_V_OutdoorTempSensor1StatusText, 0,                0,                NULL,  NOLOG_ENABLE  ),
   VAR_ELEMENT_LOCAL("V_OutdoorTempSensor2StatusText",           TYPE_STRING + sizeof(A_V_OutdoorTempSensor2StatusText) - 1,  PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   A_V_OutdoorTempSensor2StatusText, 0,                0,                NULL,  NOLOG_ENABLE  ),
   VAR_ELEMENT_LOCAL("V_OutdoorTempSensor3StatusText",           TYPE_STRING + sizeof(A_V_OutdoorTempSensor3StatusText) - 1,  PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   A_V_OutdoorTempSensor3StatusText, 0,                0,                NULL,  NOLOG_ENABLE  ),
   VAR_ELEMENT_LOCAL("V_OutdoorTemperatureRef",                  TYPE_S16,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    10,      UNIT_CELSIUS,       1,   0,               -400,            2100,            NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_OutdoorTempSensor3Status",               TYPE_U8,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   0,               U8_MIN,          U8_MAX,          NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_OutdoorAirHumidity",                     TYPE_U32,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    1000,    UNIT_PCT,           0,   0,               U32_MIN,         U32_MAX,         NULL,  TOTLOG_ENABLE | FIVEMINLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_OutdoorAirHumidity_StatusText",          TYPE_STRING + sizeof(A_V_OutdoorAirHumidity_StatusText) - 1,  PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   A_V_OutdoorAirHumidity_StatusText, 0,                0,                NULL,  NOLOG_ENABLE  ),
   VAR_ELEMENT_LOCAL("V_OutdoorAirHumidity_SensorStatus",        TYPE_U8,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   0,               U8_MIN,          U8_MAX,          NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("AI_OutdoorTempSensor4",                    TYPE_S16,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    10,      UNIT_CELSIUS,       1,   0,               S16_MIN,         S16_MAX,         NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_OutdoorTempSensor4StatusTxt",            TYPE_STRING + sizeof(A_V_OutdoorTempSensor4StatusTxt) - 1,  PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   A_V_OutdoorTempSensor4StatusTxt, 0,                0,                NULL,  NOLOG_ENABLE  ),
   VAR_ELEMENT_LOCAL("V_OutdoorTempSensor4Status",               TYPE_S32,     PASSWORD_LEVEL_ADMINISTRATOR,      PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   0,               S32_MIN,         S32_MAX,         NULL,  NOLOG_ENABLE),
};

//-----------------------------------------------------------------------
// DEFINE PARAMETERS        DEFINE PARAMETERS        DEFINE PARAMETERS
//-----------------------------------------------------------------------

static struct os_db_parameter ParameterVars[] =
{
   VAR_ELEMENT_PARAMETER("P_OutdoorTempLowWarnOn",                   TYPE_S16,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_DIV,    10,      UNIT_CELSIUS,       1,   0,               -200,            0,               NULL  ),
   VAR_ELEMENT_PARAMETER("P_OutdoorTempLowWarnOff",                  TYPE_S16,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_DIV,    10,      UNIT_CELSIUS,       1,   100,             -200,            100,             NULL  ),
   VAR_ELEMENT_PARAMETER("P_OutdoorTempLowStopOn",                   TYPE_S16,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_DIV,    10,      UNIT_CELSIUS,       1,   -200,            -200,            0,               NULL  ),
   VAR_ELEMENT_PARAMETER("P_OutdoorTempLowStopOff",                  TYPE_S16,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_DIV,    10,      UNIT_CELSIUS,       1,   -100,            -200,            0,               NULL  ),
   VAR_ELEMENT_PARAMETER("P_OutdoorTempHighWarnOn",                  TYPE_S16,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_DIV,    10,      UNIT_CELSIUS,       1,   400,             300,             500,             NULL  ),
   VAR_ELEMENT_PARAMETER("P_OutdoorTempHighWarnOff",                 TYPE_S16,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_DIV,    10,      UNIT_CELSIUS,       1,   300,             300,             500,             NULL  ),
   VAR_ELEMENT_PARAMETER("P_OutdoorTempHighStopOn",                  TYPE_S16,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_DIV,    10,      UNIT_CELSIUS,       1,   500,             300,             500,             NULL  ),
   VAR_ELEMENT_PARAMETER("P_OutdoorTempHighStopOff",                 TYPE_S16,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_DIV,    10,      UNIT_CELSIUS,       1,   400,             300,             500,             NULL  ),
   VAR_ELEMENT_PARAMETER("P_OutdoorTempSensorSelect",                TYPE_U8,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_NONE,   0,       UNIT_NONE,          0,   0,               0,               4,               NULL  ),
   VAR_ELEMENT_PARAMETER("P_OutdoorTempEnable",                      TYPE_U8,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_NONE,   0,       UNIT_NONE,          0,   1,               0,               1,               NULL  ),
   VAR_ELEMENT_PARAMETER("P_Outdoor_PT100_ErrLow",                   TYPE_S32,     PASSWORD_LEVEL_ADMINISTRATOR,      PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    10,      UNIT_CELSIUS,       1,   -400,            -600,            100,             NULL  ),
   VAR_ELEMENT_PARAMETER("P_Outdoor_AirHumidityInputMax",            TYPE_S32,     PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    1000,    UNIT_MAMPERE,       0,   20000,           0,               25000,           NULL  ),
   VAR_ELEMENT_PARAMETER("P_Outdoor_AirHumidityInputMin",            TYPE_S32,     PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    1000,    UNIT_MAMPERE,       0,   4000,            0,               25000,           NULL  ),
   VAR_ELEMENT_PARAMETER("P_Outdoor_AirHumidityOutputMax",           TYPE_S32,     PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    1000,    UNIT_PCT,           0,   100000,          0,               100000,          NULL  ),
   VAR_ELEMENT_PARAMETER("P_Outdoor_AirHumidityOutputMin",           TYPE_S32,     PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    1000,    UNIT_PCT,           0,   0,               0,               100000,          NULL  ),
   VAR_ELEMENT_PARAMETER("P_Outdoor_AirHumidity_Enable",             TYPE_U8,      PASSWORD_LEVEL_ADMINISTRATOR,      PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   1,               0,               1,               NULL  ),
   VAR_ELEMENT_PARAMETER("P_Outdoor_AirHumidityInputErr",            TYPE_S32,     PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    1000,    UNIT_MAMPERE,       0,   200,             0,               2000,            NULL  ),
   VAR_ELEMENT_PARAMETER("P_Outdoor_AirHumidity_IcedDanger",         TYPE_S32,     PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    1000,    UNIT_PCT,           0,   80000,           0,               100000,          NULL  ),
   VAR_ELEMENT_PARAMETER("P_OutdoorTemp_IcedDanger",                 TYPE_S16,     PASSWORD_LEVEL_ADMINISTRATOR,      PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    10,      UNIT_CELSIUS,       1,   0,               -200,            100,             NULL  ),
   VAR_ELEMENT_PARAMETER("P_OutdoorTempEnable_Sensor4",              TYPE_U8,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_NONE,   0,       UNIT_NONE,          0,   1,               0,               1,               NULL  ),
   VAR_ELEMENT_PARAMETER("P_OutdoorTempSensor4InputMin",             TYPE_S32,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_DIV,    1000,    UNIT_MAMPERE,       0,   4000,            0,               20000,           NULL  ),
   VAR_ELEMENT_PARAMETER("P_OutdoorTempSensor4InputMax",             TYPE_S32,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_DIV,    1000,    UNIT_MAMPERE,       0,   20000,           0,               20000,           NULL  ),
   VAR_ELEMENT_PARAMETER("P_OutdoorTempSensorOutputMin",             TYPE_S32,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_DIV,    10,      UNIT_CELSIUS,       1,   -350,            -500,            1000,            NULL  ),
   VAR_ELEMENT_PARAMETER("P_OutdoorTempSensor4OutputMax",            TYPE_S32,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_DIV,    10,      UNIT_CELSIUS,       1,   750,             -500,            1000,            NULL  ),
   VAR_ELEMENT_PARAMETER("P_Outdoor_PT100_ErrHigh",                  TYPE_S16,     PASSWORD_LEVEL_ADMINISTRATOR,      PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    10,      UNIT_CELSIUS,       1,   2200,            600,             3000,            NULL  ),
};

//-----------------------------------------------------------------------
// DEFINE BACKUPS            DEFINE BACKUPS            DEFINE BACKUPS
//-----------------------------------------------------------------------

//----------------------------------------------------------------------------------
// DEFINE VAR ARRAYS            DEFINE VAR ARRAYS            DEFINE VAR ARRAYS
//----------------------------------------------------------------------------------
char OutdoorTemperature_initialValues[] =
{
   98, 162, 16, 13, 136, 107, 251, 252, 218, 222, 205, 153, 7, 188, 58, 140,
   97, 231, 12, 60, 52, 32, 121, 126, 150, 184, 227, 82, 2, 150, 28, 153,
   0
};

//-----------------------------------------------------------------------
// CREATE DATABASE VARS   CREATE DATABASE VARS   CREATE DATABASE VARS
//-----------------------------------------------------------------------

static STATUS CreateVarDbVars(void)
{
   STATUS Status;
   size_t ErrorEntry;

   Status = OS_VarDB_CreateLocals(LocalVars, sizeof(LocalVars)/sizeof(LocalVars[0]), &ErrorEntry, AppLocalParameterPosition());
   if (Status != 0)
   {
      AppSystemLog(ERR_7, MODULE_NAME"CrVL: %d,%d", Status, ErrorEntry);
      return ERR_7;
   }

   Status = OS_VarDB_CreateParameters(ParameterVars, sizeof(ParameterVars)/sizeof(ParameterVars[0]), &ErrorEntry, AppExportParameterPosition());
   if (Status != 0)
   {
      AppSystemLog(ERR_7, MODULE_NAME"CrVXP: %d,%d", Status, ErrorEntry);
      return ERR_7;
   }

   return OS_SUCCESS;
}

#define CREATE_VARDB_VARS

//-----------------------------------------------------------------------
// CREATE IO VARIABLES     CREATE IO VARIABLES     CREATE IO VARIABLES
//-----------------------------------------------------------------------

extern STATUS OutdoorTemperatureInitIOAliases();
extern struct os_db_alias* OutdoorTemperatureIOVars;
extern void (*OutdoorTemperatureSetLockValues)(void);
extern size_t OutdoorTemperatureIOVarsSize;

static STATUS CreateIOVars(void)
{
   STATUS Status;
   size_t ErrorEntry;

   varid_t VarId;
   BOOL variablesExist = false;
   U8 counter = 50;
   Status = OutdoorTemperatureInitIOAliases();
   STATUS_LINE_VAR_RETURN_VALUE(Status)
   while (!variablesExist && counter-- > 0)
   {
      variablesExist = true;
      U32 i = 0;
      for (i = 0; i < OutdoorTemperatureIOVarsSize; ++i)
      {
         if (OS_VarDB_GetVariableID(OutdoorTemperatureIOVars[i].Name, &VarId) != OS_SUCCESS)
         {
            variablesExist = false;
            break;
         }
      }

      if (!variablesExist)
      {
         OS_Sleep(100);
      }
   }

   Status = OS_VarDB_CreateAliases(OutdoorTemperatureIOVars, OutdoorTemperatureIOVarsSize, &ErrorEntry);
   if (Status)
   {
      AppDebugLog(5000, "Var Name = %s", OutdoorTemperatureIOVars[ErrorEntry].Alias);
   }
   STATUS_LINE_VAR_RETURN_CONST(Status, ErrorEntry);
   return OS_SUCCESS;
}

#define CREATE_IO_VARS

//-----------------------------------------------------------------------
// ALIASES                       ALIASES                       ALIASES
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// INPUT                          INPUT                          INPUT
//-----------------------------------------------------------------------

// Create local variable
#define MODUL_INPUTS
static S16 P_OutdoorTempHighWarnOn = 0;
static S16 P_OutdoorTempHighWarnOff = 0;
static S16 P_OutdoorTempHighStopOn = 0;
static S16 P_OutdoorTempHighStopOff = 0;
static S16 P_OutdoorTempLowWarnOn = 0;
static S16 P_OutdoorTempLowWarnOff = 0;
static S16 P_OutdoorTempLowStopOn = 0;
static S16 P_OutdoorTempLowStopOff = 0;
static U8 P_OutdoorTempSensorSelect = 0;
static U8 P_OutdoorTempEnable = 0;
static S16 V_OutdoorTempSensor1 = 0;
static S16 V_OutdoorTempSensor2 = 0;
static U16 V_OutdoorTempSensor1Status = 0;
static U16 V_OutdoorTempSensor2Status = 0;
static S16 PT_OutdoorTemperature = 0;
static S16 AI_OutdoorAirHumidity = 0;
static S16 AI_OutdoorTempSensor4_Curr = 0;

//-----------------------------------------------------------------------
static struct ModulInOut ModulInputs[] =
{
   {"P_OutdoorTempHighWarnOn",                  &P_OutdoorTempHighWarnOn,                  sizeof(P_OutdoorTempHighWarnOn),                  },
   {"P_OutdoorTempHighWarnOff",                 &P_OutdoorTempHighWarnOff,                 sizeof(P_OutdoorTempHighWarnOff),                 },
   {"P_OutdoorTempHighStopOn",                  &P_OutdoorTempHighStopOn,                  sizeof(P_OutdoorTempHighStopOn),                  },
   {"P_OutdoorTempHighStopOff",                 &P_OutdoorTempHighStopOff,                 sizeof(P_OutdoorTempHighStopOff),                 },
   {"P_OutdoorTempLowWarnOn",                   &P_OutdoorTempLowWarnOn,                   sizeof(P_OutdoorTempLowWarnOn),                   },
   {"P_OutdoorTempLowWarnOff",                  &P_OutdoorTempLowWarnOff,                  sizeof(P_OutdoorTempLowWarnOff),                  },
   {"P_OutdoorTempLowStopOn",                   &P_OutdoorTempLowStopOn,                   sizeof(P_OutdoorTempLowStopOn),                   },
   {"P_OutdoorTempLowStopOff",                  &P_OutdoorTempLowStopOff,                  sizeof(P_OutdoorTempLowStopOff),                  },
   {"P_OutdoorTempSensorSelect",                &P_OutdoorTempSensorSelect,                sizeof(P_OutdoorTempSensorSelect),                },
   {"P_OutdoorTempEnable",                      &P_OutdoorTempEnable,                      sizeof(P_OutdoorTempEnable),                      },
   {"V_OutdoorTempSensor1",                     &V_OutdoorTempSensor1,                     sizeof(V_OutdoorTempSensor1),                     },
   {"V_OutdoorTempSensor2",                     &V_OutdoorTempSensor2,                     sizeof(V_OutdoorTempSensor2),                     },
   {"V_OutdoorTempSensor1Status",               &V_OutdoorTempSensor1Status,               sizeof(V_OutdoorTempSensor1Status),               },
   {"V_OutdoorTempSensor2Status",               &V_OutdoorTempSensor2Status,               sizeof(V_OutdoorTempSensor2Status),               },
   {"PT_OutdoorTemperature",                    &PT_OutdoorTemperature,                    sizeof(PT_OutdoorTemperature),                    },
   {"AI_OutdoorAirHumidity",                    &AI_OutdoorAirHumidity,                    sizeof(AI_OutdoorAirHumidity),                    },
   {"AI_OutdoorTempSensor4_Curr",               &AI_OutdoorTempSensor4_Curr,               sizeof(AI_OutdoorTempSensor4_Curr),               },
};

//-----------------------------------------------------------------------
// Check variable type
static STATUS VarsReadReturnStatus;
static type_t ReadVarType = TYPE_NONE;
static void VarsReadTypeCheck(void)
{
   (void)VarsReadReturnStatus;
   (void)ReadVarType;
   VERIFY_INPUT_REF_ID(S16,       ModulInputs[0].Name,                      ModulInputs[0].Id)
   VERIFY_INPUT_REF_ID(S16,       ModulInputs[1].Name,                      ModulInputs[1].Id)
   VERIFY_INPUT_REF_ID(S16,       ModulInputs[2].Name,                      ModulInputs[2].Id)
   VERIFY_INPUT_REF_ID(S16,       ModulInputs[3].Name,                      ModulInputs[3].Id)
   VERIFY_INPUT_REF_ID(S16,       ModulInputs[4].Name,                      ModulInputs[4].Id)
   VERIFY_INPUT_REF_ID(S16,       ModulInputs[5].Name,                      ModulInputs[5].Id)
   VERIFY_INPUT_REF_ID(S16,       ModulInputs[6].Name,                      ModulInputs[6].Id)
   VERIFY_INPUT_REF_ID(S16,       ModulInputs[7].Name,                      ModulInputs[7].Id)
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[8].Name,                      ModulInputs[8].Id)
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[9].Name,                      ModulInputs[9].Id)
   VERIFY_INPUT_REF_ID(S16,       ModulInputs[10].Name,                     ModulInputs[10].Id)
   VERIFY_INPUT_REF_ID(S16,       ModulInputs[11].Name,                     ModulInputs[11].Id)
   VERIFY_INPUT_REF_ID(U16,       ModulInputs[12].Name,                     ModulInputs[12].Id)
   VERIFY_INPUT_REF_ID(U16,       ModulInputs[13].Name,                     ModulInputs[13].Id)
   VERIFY_INPUT_REF_ID(S16,       ModulInputs[14].Name,                     ModulInputs[14].Id)
   VERIFY_INPUT_REF_ID(S16,       ModulInputs[15].Name,                     ModulInputs[15].Id)
   VERIFY_INPUT_REF_ID(S16,       ModulInputs[16].Name,                     ModulInputs[16].Id)
}

#undef MODUL_INPUTS
#define MODUL_INPUTS_SIZE (sizeof(ModulInputs)/sizeof(ModulInputs[0]))

//------------------------------------------------------------------------------------------
// READ/WRITE VARDB ARRAY      READ/WRITE VARDB ARRAY      READ/WRATE VARDB ARRAY
//------------------------------------------------------------------------------------------


//-----------------------------------------------------------------------
// PARAMETER                    PARAMETER                    PARAMETER
//-----------------------------------------------------------------------

// Create local variable
#define MODUL_PARAMETERS
static S16 P_Outdoor_PT100_ErrHigh = 0;
static S32 P_Outdoor_PT100_ErrLow = 0;
static S32 P_Outdoor_AirHumidityInputMax = 0;
static S32 P_Outdoor_AirHumidityOutputMax = 0;
static S32 P_Outdoor_AirHumidityInputMin = 0;
static S32 P_Outdoor_AirHumidityOutputMin = 0;
static U8 P_Outdoor_AirHumidity_Enable = 0;
static S32 P_Outdoor_AirHumidityInputErr = 0;
static S32 P_Outdoor_AirHumidity_IcedDanger = 0;
static S16 P_OutdoorTemp_IcedDanger = 0;
static U8 P_OutdoorTempEnable_Sensor4 = 0;
static S32 P_OutdoorTempSensor4InputMin = 0;
static S32 P_OutdoorTempSensor4InputMax = 0;
static S32 P_OutdoorTempSensorOutputMin = 0;
static S32 P_OutdoorTempSensor4OutputMax = 0;



//-----------------------------------------------------------------------
static struct ModulInOut ModulParameters0[] =
{
   {"P_Outdoor_PT100_ErrHigh",                  &P_Outdoor_PT100_ErrHigh,                  sizeof(P_Outdoor_PT100_ErrHigh),                  },
   {"P_Outdoor_PT100_ErrLow",                   &P_Outdoor_PT100_ErrLow,                   sizeof(P_Outdoor_PT100_ErrLow),                   },
   {"P_Outdoor_AirHumidityInputMax",            &P_Outdoor_AirHumidityInputMax,            sizeof(P_Outdoor_AirHumidityInputMax),            },
   {"P_Outdoor_AirHumidityOutputMax",           &P_Outdoor_AirHumidityOutputMax,           sizeof(P_Outdoor_AirHumidityOutputMax),           },
   {"P_Outdoor_AirHumidityInputMin",            &P_Outdoor_AirHumidityInputMin,            sizeof(P_Outdoor_AirHumidityInputMin),            },
   {"P_Outdoor_AirHumidityOutputMin",           &P_Outdoor_AirHumidityOutputMin,           sizeof(P_Outdoor_AirHumidityOutputMin),           },
   {"P_Outdoor_AirHumidity_Enable",             &P_Outdoor_AirHumidity_Enable,             sizeof(P_Outdoor_AirHumidity_Enable),             },
   {"P_Outdoor_AirHumidityInputErr",            &P_Outdoor_AirHumidityInputErr,            sizeof(P_Outdoor_AirHumidityInputErr),            },
   {"P_Outdoor_AirHumidity_IcedDanger",         &P_Outdoor_AirHumidity_IcedDanger,         sizeof(P_Outdoor_AirHumidity_IcedDanger),         },
   {"P_OutdoorTemp_IcedDanger",                 &P_OutdoorTemp_IcedDanger,                 sizeof(P_OutdoorTemp_IcedDanger),                 },
   {"P_OutdoorTempEnable_Sensor4",              &P_OutdoorTempEnable_Sensor4,              sizeof(P_OutdoorTempEnable_Sensor4),              },
   {"P_OutdoorTempSensor4InputMin",             &P_OutdoorTempSensor4InputMin,             sizeof(P_OutdoorTempSensor4InputMin),             },
   {"P_OutdoorTempSensor4InputMax",             &P_OutdoorTempSensor4InputMax,             sizeof(P_OutdoorTempSensor4InputMax),             },
   {"P_OutdoorTempSensorOutputMin",             &P_OutdoorTempSensorOutputMin,             sizeof(P_OutdoorTempSensorOutputMin),             },
   {"P_OutdoorTempSensor4OutputMax",            &P_OutdoorTempSensor4OutputMax,            sizeof(P_OutdoorTempSensor4OutputMax),            },

};
static struct ModulInOut* ModulParameters[] =
{
   ModulParameters0,
};

//-----------------------------------------------------------------------
// Check variable type
static STATUS ParaVarsReadReturnStatus;
static type_t ParaReadVarType = TYPE_NONE;
static void ParaVarsReadTypeCheck(void)
{
   (void)ParaVarsReadReturnStatus;
   (void)ParaReadVarType;
}

#undef MODUL_PARAMETERS

#define PARAMETERS_GROUPS_SIZE        1
#define GENERAL_GROUP                 0
#define MODUL_PARAMETERS_TOTAL_SIZE   15
static SUBSCRIPTION ParaSubscription[MODUL_PARAMETERS_TOTAL_SIZE];
static U8 ReadParameters[PARAMETERS_GROUPS_SIZE];
static U8 ParametersChanged[PARAMETERS_GROUPS_SIZE];
static UNSIGNED GroupsIndexes[PARAMETERS_GROUPS_SIZE];
static int ParaGroupsSizes[PARAMETERS_GROUPS_SIZE] = { 15 };
static STATUS VarDbUpdateParameter(varid_t VariableId, void* Message, U16 Length, UNSIGNED paraGroupIndex, UNSIGNED Ref2)
{
   ReadParameters[paraGroupIndex] = 1;
   ParametersChanged[paraGroupIndex] = 1;
   return OS_SUCCESS;
}
static STATUS ReadParametersFunc(int paraGroupIndex)
{
   STATUS LocalStatus;
   // Check inputdata
   if (sizeof(ModulParameters[paraGroupIndex]) == 0)
   {
      AppSystemLog(ERR_4, MODULE_NAME"Group %d ModuleParameters = 0", paraGroupIndex);
      return ERR_4;
   }
   // Read inputdata
   LocalStatus = OS_ReadVariables(ModulParameters[paraGroupIndex], ParaGroupsSizes[paraGroupIndex]);
   if (LocalStatus != 0)
   {
      AppSystemLog(11, "LocalStatus: %d", LocalStatus);
      AppSystemLog(ERR_4, MODULE_NAME"ReadParErr: group=%d element=%d elementpointer=0x%x", paraGroupIndex, LocalStatus, &ModulParameters[LocalStatus]);
      return ERR_4;
   }
   return OS_SUCCESS;
}


//-----------------------------------------------------------------------
// READ VARS FROM VARDB    READ VARS FROM VARDB    READ VARS FROM VARDB
//-----------------------------------------------------------------------

static STATUS InputReferenceRoutine(U8 ModuleState)
{
   STATUS LocalStatus = 0;

   // Read input references
   if (ModuleState >= APP_INIT3)
   {
      // Check inputdata
      if (sizeof(ModulInputs) == 0)
      {
         AppSystemLog(ERR_4, MODULE_NAME"ModuleInputs = 0");
         return ERR_4;
      }
      // Read inputdata
      LocalStatus = OS_ReadVariables(ModulInputs, MODUL_INPUTS_SIZE);
      if (LocalStatus != 0)
      {
         AppSystemLog(ERR_4, MODULE_NAME"ReadVErr: element=%d elementpointer=0x%x", LocalStatus, &ModulInputs[LocalStatus]);
         return ERR_4;
      }
   }
   // Read input parameters
   if (ModuleState == APP_INIT3)
   {
      static size_t ParaCounter = 0;
      int groupIndex;
      for (groupIndex = 0; groupIndex < PARAMETERS_GROUPS_SIZE; groupIndex++)
      {
         ParametersChanged[groupIndex] = 1;
         ReadParameters[groupIndex] = 1;
         GroupsIndexes[groupIndex] = groupIndex;

         // Check inputdata
         if (sizeof(ModulParameters[groupIndex]) == 0)
         {
            AppSystemLog(ERR_4, MODULE_NAME"Group = %d ModuleParameters = 0", groupIndex);
            return ERR_4;
         }
         // Read inputdata
         LocalStatus = OS_ReadVariables(ModulParameters[groupIndex], ParaGroupsSizes[groupIndex]);
         if (LocalStatus != 0)
         {
            AppSystemLog(ERR_4, MODULE_NAME"ReadVParaErr: group=%d element=%d elementpointer=0x%x", groupIndex, LocalStatus, &ModulParameters[groupIndex][LocalStatus]);
            return ERR_4;
         }
         int paraIndex;
         for (paraIndex = 0; paraIndex < ParaGroupsSizes[groupIndex]; paraIndex++)
         {
            LocalStatus = OS_SubHandl_SubscribeFunctionWithRef(&ParaSubscription[ParaCounter], 1, &ModulParameters[groupIndex][paraIndex].Id, &GroupsIndexes[groupIndex], &GroupsIndexes[groupIndex], VarDbUpdateParameter);
            ParaCounter++;
            if (LocalStatus != 0)
            {
               AppSystemLog(ERR_4, MODULE_NAME"Subscribe Parameter: group=%d element=%d elementpointer=0x%x", groupIndex, LocalStatus, &ModulParameters[LocalStatus]);
               return ERR_4;
            }
         }
      }
   }
   if (ModuleState == APP_RUN)
   {
      int groupIndex;
      for (groupIndex = 0; groupIndex < PARAMETERS_GROUPS_SIZE; groupIndex++)
      {
         if (ReadParameters[groupIndex])
         {
            LocalStatus = ReadParametersFunc(groupIndex);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
            ReadParameters[groupIndex] = 0;
         }
      }
   }

   return 0;
}

#define READ_VARS

//-----------------------------------------------------------------------
// OUTPUT                         OUTPUT                         OUTPUT
//-----------------------------------------------------------------------

// Create local variable
#define MODUL_OUTPUTS
static S16 V_OutdoorTemperatureRef = 0;
static S16 V_OutDoorTemp = 0;
static S16 V_OutDoorTemp1Sec = 0;
static S16 V_OutDoorTemp3Sec = 0;
static S16 V_OutDoorTemp30Sec = 0;
static S16 V_OutDoorTemp10Min = 0;
static U8 V_OutdoorTempSensor3Status = 0;
static U32 V_OutdoorAirHumidity = 0;
static U8 V_OutdoorAirHumidity_SensorStatus = 0;
static S16 AI_OutdoorTempSensor4 = 0;
static S32 V_OutdoorTempSensor4Status = 0;
static char V_OutdoorTempSensorsActiveText[31];
static char V_OutdoorTempSensor1StatusText[31];
static char V_OutdoorTempSensor2StatusText[31];
static char V_OutdoorTempSensor3StatusText[31];
static char V_OutdoorAirHumidity_StatusText[31];
static char V_OutdoorTempSensor4StatusTxt[31];


//-----------------------------------------------------------------------
static struct ModulInOut ModulOutputs[] =
{
   {"V_OutdoorTemperatureRef",                  &V_OutdoorTemperatureRef,                  sizeof(V_OutdoorTemperatureRef),                  },
   {"V_OutdoorTempSensorsActiveText",           &V_OutdoorTempSensorsActiveText,           sizeof(V_OutdoorTempSensorsActiveText),           },
   {"V_OutdoorTempSensor1StatusText",           &V_OutdoorTempSensor1StatusText,           sizeof(V_OutdoorTempSensor1StatusText),           },
   {"V_OutdoorTempSensor2StatusText",           &V_OutdoorTempSensor2StatusText,           sizeof(V_OutdoorTempSensor2StatusText),           },
   {"V_OutDoorTemp",                            &V_OutDoorTemp,                            sizeof(V_OutDoorTemp),                            },
   {"V_OutDoorTemp1Sec",                        &V_OutDoorTemp1Sec,                        sizeof(V_OutDoorTemp1Sec),                        },
   {"V_OutDoorTemp3Sec",                        &V_OutDoorTemp3Sec,                        sizeof(V_OutDoorTemp3Sec),                        },
   {"V_OutDoorTemp30Sec",                       &V_OutDoorTemp30Sec,                       sizeof(V_OutDoorTemp30Sec),                       },
   {"V_OutDoorTemp10Min",                       &V_OutDoorTemp10Min,                       sizeof(V_OutDoorTemp10Min),                       },
   {"V_OutdoorTempSensor3Status",               &V_OutdoorTempSensor3Status,               sizeof(V_OutdoorTempSensor3Status),               },
   {"V_OutdoorTempSensor3StatusText",           &V_OutdoorTempSensor3StatusText,           sizeof(V_OutdoorTempSensor3StatusText),           },
   {"V_OutdoorAirHumidity",                     &V_OutdoorAirHumidity,                     sizeof(V_OutdoorAirHumidity),                     },
   {"V_OutdoorAirHumidity_SensorStatus",        &V_OutdoorAirHumidity_SensorStatus,        sizeof(V_OutdoorAirHumidity_SensorStatus),        },
   {"V_OutdoorAirHumidity_StatusText",          &V_OutdoorAirHumidity_StatusText,          sizeof(V_OutdoorAirHumidity_StatusText),          },
   {"AI_OutdoorTempSensor4",                    &AI_OutdoorTempSensor4,                    sizeof(AI_OutdoorTempSensor4),                    },
   {"V_OutdoorTempSensor4StatusTxt",            &V_OutdoorTempSensor4StatusTxt,            sizeof(V_OutdoorTempSensor4StatusTxt),            },
   {"V_OutdoorTempSensor4Status",               &V_OutdoorTempSensor4Status,               sizeof(V_OutdoorTempSensor4Status),               },
};

//-----------------------------------------------------------------------
// Check variable type
static STATUS VarsWriteReturnStatus;
static type_t WriteVarType = TYPE_NONE;
static void VarsWriteTypeCheck(void)
{
   (void)VarsWriteReturnStatus;
   (void)WriteVarType;
   VERIFY_OUTPUT_REF_ID(S16,       ModulOutputs[0].Name,                     ModulOutputs[0].Id,                       0)
   VERIFY_OUTPUT_STRING_REF_ID(STRING,     ModulOutputs[1].Name,                      ModulOutputs[1].Id, 0)
   VERIFY_OUTPUT_STRING_REF_ID(STRING,     ModulOutputs[2].Name,                      ModulOutputs[2].Id, 0)
   VERIFY_OUTPUT_STRING_REF_ID(STRING,     ModulOutputs[3].Name,                      ModulOutputs[3].Id, 0)
   VERIFY_OUTPUT_REF_ID(S16,       ModulOutputs[4].Name,                     ModulOutputs[4].Id,                       0)
   VERIFY_OUTPUT_REF_ID(S16,       ModulOutputs[5].Name,                     ModulOutputs[5].Id,                       0)
   VERIFY_OUTPUT_REF_ID(S16,       ModulOutputs[6].Name,                     ModulOutputs[6].Id,                       0)
   VERIFY_OUTPUT_REF_ID(S16,       ModulOutputs[7].Name,                     ModulOutputs[7].Id,                       0)
   VERIFY_OUTPUT_REF_ID(S16,       ModulOutputs[8].Name,                     ModulOutputs[8].Id,                       0)
   VERIFY_OUTPUT_REF_ID(U8,        ModulOutputs[9].Name,                     ModulOutputs[9].Id,                       0)
   VERIFY_OUTPUT_STRING_REF_ID(STRING,     ModulOutputs[10].Name,                     ModulOutputs[10].Id, 0)
   VERIFY_OUTPUT_REF_ID(U32,       ModulOutputs[11].Name,                    ModulOutputs[11].Id,                      0)
   VERIFY_OUTPUT_REF_ID(U8,        ModulOutputs[12].Name,                    ModulOutputs[12].Id,                      0)
   VERIFY_OUTPUT_STRING_REF_ID(STRING,     ModulOutputs[13].Name,                     ModulOutputs[13].Id, 0)
   VERIFY_OUTPUT_REF_ID(S16,       ModulOutputs[14].Name,                    ModulOutputs[14].Id,                      0)
   VERIFY_OUTPUT_STRING_REF_ID(STRING,     ModulOutputs[15].Name,                     ModulOutputs[15].Id,                   0)
   VERIFY_OUTPUT_REF_ID(S32,       ModulOutputs[16].Name,                    ModulOutputs[16].Id,                      0)
}

#undef MODUL_OUTPUTS
#define MODUL_OUTPUTS_SIZE (sizeof(ModulOutputs)/sizeof(ModulOutputs[0]))

//-----------------------------------------------------------------------
// WRITE VARS TO VARDB     WRITE VARS TO VARDB     WRITE VARS TO VARDB
//-----------------------------------------------------------------------

static STATUS InitOutputVars(void)
{
   STATUS LocalStatus;
   // Read outputdata
   LocalStatus = OS_ReadVariables(ModulOutputs, MODUL_OUTPUTS_SIZE);
   if (LocalStatus != 0)
   {
      AppSystemLog(ERR_4, MODULE_NAME"InitErr: element=%d elementpointer=0x%x", LocalStatus, &ModulOutputs[LocalStatus]);
      return ERR_4;
   }
   return OS_SUCCESS;
}
static STATUS OutputReferenceRoutine(U8 ModuleState)
{
   STATUS LocalStatus = 0;
   // Write Outputdata
   LocalStatus = OS_WriteVariablesConditional(ModulOutputs, MODUL_OUTPUTS_SIZE);
   if (LocalStatus != 0)
   {
      AppSystemLog(ERR_5, MODULE_NAME"WriteVErr: element=%d elementpointer=0x%x", LocalStatus, &ModulOutputs[LocalStatus]);
      return ERR_5;
   }
   return 0;
}

#define WRITE_VARS

//-----------------------------------------------------------------------
// VERIFY VARIABLES CREATION                 VERIFY VARIABLES CREATION
//-----------------------------------------------------------------------

static STATUS LocalIoCheck(void)
{
   // Check if input variables exist.
   STATUS LocalStatus;

   LocalStatus = OS_DoesVariablesExist(ModulInputs, MODUL_INPUTS_SIZE);
   if (LocalStatus != 0)
   {
      AppSystemLog(ERR_1, MODULE_NAME"InputErr: %d", LocalStatus);
      AppSystemLog(ERR_1, "Name: %s", ModulInputs[LocalStatus-1].Name);
      return ERR_1;
   }
   (void)VarsReadTypeCheck();

   int groupIndex;
   for (groupIndex = 0; groupIndex < PARAMETERS_GROUPS_SIZE; groupIndex++)
   {
      LocalStatus = OS_DoesVariablesExist(ModulParameters[groupIndex], ParaGroupsSizes[groupIndex]);
      if (LocalStatus != 0)
      {
         AppSystemLog(ERR_3, MODULE_NAME"ParameterErr: %d Group:%d", LocalStatus, groupIndex);
         AppSystemLog(ERR_3, "Name: %s", ModulParameters[groupIndex][LocalStatus-1].Name);
         return ERR_3;
      }
   }
   (void)ParaVarsReadTypeCheck();

   LocalStatus = OS_DoesVariablesExist(ModulOutputs, MODUL_OUTPUTS_SIZE);
   if (LocalStatus != 0)
   {
      AppSystemLog(ERR_2, MODULE_NAME"OutputErr: %d", LocalStatus);
      AppSystemLog(ERR_2, "Name: %s", ModulOutputs[LocalStatus-1].Name);
      return ERR_2;
   }
   (void)VarsWriteTypeCheck();

   return OS_SUCCESS;
}

#define VERIFY_VARIABLES

//-----------------------------------------------------------------------
// ALLOCATE MEMORY FOR SUMMATIONS        ALLOCATE MEMORY FOR SUMMATIONS
//-----------------------------------------------------------------------


//-----------------------------------------------------------------------
// SUMMATIONS                  SUMMATIONS                  SUMMATIONS
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// DEFINE MENUS               DEFINE MENUS               DEFINE MENUS
//-----------------------------------------------------------------------



// Menu line and link to local menu
//-----------------------------------------------------------------------
static struct line_struct M_OutdoorTemperatureLinkToLocalMenu[] =
{
   MENU_ELEMENT_LINE_LINK("Outdoor Temperature",               PASSWORD_LEVEL_END_CUSTOMER,        "M_OutdoorTemperature",             "G_OutdoorTemperature"),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_OutdoorTemperatureMenu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_OutdoorTemperature",             PASSWORD_LEVEL_END_CUSTOMER),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_OutdoorTemperatureMenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("OUTDOOR TEMPERATURE",               PASSWORD_LEVEL_END_CUSTOMER,        "M_"APP_ID"AppMain",                "G_"APP_ID"App"),
   MENU_ELEMENT_LINE_VARRO("Air Humidity",                     PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_OutdoorAirHumidity",                       LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Outdoor Temperature",              PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_OutDoorTemp",                              LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Sensors Active",                   PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_OutdoorTempSensorsActiveText",             LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_LINK("Status",                            PASSWORD_LEVEL_END_CUSTOMER,        "M_Status2",                        "G_OutdoorTemperature"),
   MENU_ELEMENT_LINE_LINK("Parameter",                         PASSWORD_LEVEL_END_CUSTOMER,        "M_Parameter3",                     "G_OutdoorTemperature"),
   MENU_ELEMENT_LINE_LINK("Debug",                             PASSWORD_LEVEL_MITA_PROGRAMMER,     "M_Debug86",                        "G_OutdoorTemperature"),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_Status2Menu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_Status2",                        PASSWORD_LEVEL_END_CUSTOMER),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_Status2MenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("STATUS",                            PASSWORD_LEVEL_END_CUSTOMER,        "M_OutdoorTemperature",             "G_OutdoorTemperature"),
   MENU_ELEMENT_LINE_VARRO("Air Humidity",                     PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_OutdoorAirHumidity",                       LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Outdoor Temperature",              PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_OutDoorTemp",                              LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Outdoor Temperature 3 s.",         PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_OutDoorTemp3Sec",                          LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Outdoor Temperature 30 s.",        PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_OutDoorTemp30Sec",                         LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Outdoor Temperature 10 min.",      PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_OutDoorTemp10Min",                         LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Outdoor Temperature Reference",    PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_OutdoorTemperatureRef",                    LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_LINK("Sensor Inputs",                     PASSWORD_LEVEL_END_CUSTOMER,        "M_SensorInputs50",                 "G_OutdoorTemperature"),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_SensorInputs50Menu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_SensorInputs50",                 PASSWORD_LEVEL_END_CUSTOMER),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_SensorInputs50MenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("SENSOR INPUTS",                     PASSWORD_LEVEL_END_CUSTOMER,        "M_Status2",                        "G_OutdoorTemperature"),
   MENU_ELEMENT_LINE_VARRO("Outdoor Temp. Sensor 1",           PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_OutdoorTempSensor1",                       LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Outdoor Temp. Sensor 1 Status",    PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_OutdoorTempSensor1StatusText",             LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Outdoor Temp. Sensor 2",           PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_OutdoorTempSensor2",                       LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Outdoor Temp. Sensor 2 Status",    PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_OutdoorTempSensor2StatusText",             LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Outdoor Temp. Sensor 3",           PASSWORD_LEVEL_END_CUSTOMER,        (char*)"PT_OutdoorTemperature",                      LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Outdoor Temp. Sensor 3 Status",    PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_OutdoorTempSensor3StatusText",             LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Air Humidity",                     PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_OutdoorAirHumidity",                       LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Air Humidity",                     PASSWORD_LEVEL_END_CUSTOMER,        (char*)"AI_OutdoorAirHumidity",                      LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Air Humidity Sensor Status",       PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_OutdoorAirHumidity_StatusText",            LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Outdoor temp. Sensor 4",           PASSWORD_LEVEL_END_CUSTOMER,        (char*)"AI_OutdoorTempSensor4",                      LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Outdoor temp. Sensor 4",           PASSWORD_LEVEL_END_CUSTOMER,        (char*)"AI_OutdoorTempSensor4_Curr",                 LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Outdoor temp. Sensor 4 Status",    PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_OutdoorTempSensor4StatusTxt",              LINE_FORMAT_NONE),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_Parameter3Menu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_Parameter3",                     PASSWORD_LEVEL_END_CUSTOMER),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_Parameter3MenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("PARAMETER",                         PASSWORD_LEVEL_END_CUSTOMER,        "M_OutdoorTemperature",             "G_OutdoorTemperature"),
   MENU_ELEMENT_LINE_VARRW("Air Humidity Iced Danger",         PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_Outdoor_AirHumidity_IcedDanger",           LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Outdoor Temp. Iced Danger",        PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_OutdoorTemp_IcedDanger",                   LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_LINK("Air Humidity Parameters",           PASSWORD_LEVEL_END_CUSTOMER,        "M_AirHumidityParameters109",       "G_OutdoorTemperature"),
   MENU_ELEMENT_LINE_LINK("Outdoor Temperature Parameters",    PASSWORD_LEVEL_END_CUSTOMER,        "M_OutdoorTemperatureParameters122", "G_OutdoorTemperature"),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_AirHumidityParameters109Menu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_AirHumidityParameters109",       PASSWORD_LEVEL_END_CUSTOMER),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_AirHumidityParameters109MenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("AIR HUMIDITY PARAMETERS",           PASSWORD_LEVEL_END_CUSTOMER,        "M_Parameter3",                     "G_OutdoorTemperature"),
   MENU_ELEMENT_LINE_VARRW("Air Humidity Enable",              PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_Outdoor_AirHumidity_Enable",               LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Air Humidity Max Input",           PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_Outdoor_AirHumidityInputMax",              LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Air Humidity Min Input",           PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_Outdoor_AirHumidityInputMin",              LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Air Humidity Max Output",          PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_Outdoor_AirHumidityOutputMax",             LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Air Humidity Min Output",          PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_Outdoor_AirHumidityOutputMin",             LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Air Humidity Sensor Error",        PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_Outdoor_AirHumidityInputErr",              LINE_FORMAT_NONE),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_OutdoorTemperatureParameters122Menu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_OutdoorTemperatureParameters122",PASSWORD_LEVEL_END_CUSTOMER),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_OutdoorTemperatureParameters122MenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("OUTDOOR TEMPERATURE PARAMETERS",    PASSWORD_LEVEL_END_CUSTOMER,        "M_Parameter3",                     "G_OutdoorTemperature"),
   MENU_ELEMENT_LINE_VARRW("Outdoor Temp. Enable",             PASSWORD_LEVEL_LICENCE_CUSTOMER,    (char*)"P_OutdoorTempEnable",                        LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Outdoor Temp. Sensor Select",      PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_OutdoorTempSensorSelect",                  LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Outdoor Low Temp. Warning ON",     PASSWORD_LEVEL_LICENCE_CUSTOMER,    (char*)"P_OutdoorTempLowWarnOn",                     LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Outdoor Low Temp. Warning OFF",    PASSWORD_LEVEL_LICENCE_CUSTOMER,    (char*)"P_OutdoorTempLowWarnOff",                    LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Outdoor Low Temp. Stop ON",        PASSWORD_LEVEL_LICENCE_CUSTOMER,    (char*)"P_OutdoorTempLowStopOn",                     LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Outdoor Low Temp. Stop OFF",       PASSWORD_LEVEL_LICENCE_CUSTOMER,    (char*)"P_OutdoorTempLowStopOff",                    LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Outdoor High Temp. Warning ON",    PASSWORD_LEVEL_LICENCE_CUSTOMER,    (char*)"P_OutdoorTempHighWarnOn",                    LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Outdoor High Temp. Warning OFF",   PASSWORD_LEVEL_LICENCE_CUSTOMER,    (char*)"P_OutdoorTempHighWarnOff",                   LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Outdoor High Temp. Stop ON",       PASSWORD_LEVEL_LICENCE_CUSTOMER,    (char*)"P_OutdoorTempHighStopOn",                    LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Outdoor High Temp. Stop OFF",      PASSWORD_LEVEL_LICENCE_CUSTOMER,    (char*)"P_OutdoorTempHighStopOff",                   LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Outdoor PT100 Sensor Error High",  PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_Outdoor_PT100_ErrHigh",                    LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Outdoor PT100 Sensor Error Low",   PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_Outdoor_PT100_ErrLow",                     LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_LINK("Temperature Sensor 4",              PASSWORD_LEVEL_END_CUSTOMER,        "M_TemperatureSensor488",           "G_OutdoorTemperature"),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_TemperatureSensor488Menu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_TemperatureSensor488",           PASSWORD_LEVEL_END_CUSTOMER),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_TemperatureSensor488MenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("TEMPERATURE SENSOR 4",              PASSWORD_LEVEL_END_CUSTOMER,        "M_OutdoorTemperatureParameters122", "G_OutdoorTemperature"),
   MENU_ELEMENT_LINE_VARRW("Outdoor temp. Enable",             PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_OutdoorTempEnable_Sensor4",                LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Outdoor temp. Sensor Input Min",   PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_OutdoorTempSensor4InputMin",               LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Outdoor temp. Sensor Input Max",   PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_OutdoorTempSensor4InputMax",               LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Outdoor temp. Sensor Output Min",  PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_OutdoorTempSensorOutputMin",               LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Outdoor temp. Sensor Output Max",  PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_OutdoorTempSensor4OutputMax",              LINE_FORMAT_NONE),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_Debug86Menu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_Debug86",                        PASSWORD_LEVEL_MITA_PROGRAMMER),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_Debug86MenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("DEBUG",                             PASSWORD_LEVEL_MITA_PROGRAMMER,     "M_OutdoorTemperature",             "G_OutdoorTemperature"),
   MENU_ELEMENT_LINE_VARRO("V_OutdoorTempSensor4Status",       PASSWORD_LEVEL_MITA_PROGRAMMER,     (char*)"V_OutdoorTempSensor4Status",                 LINE_FORMAT_NONE),
};
// Creating parameters for multiplexed categories
//-----------------------------------------------------------------------
static struct multiplexed_info_struct M_OutdoorTemperatureMultiplexedCategoriesParameters[] =
{
0};

//-----------------------------------------------------------------------
// CREATE MENUS               CREATE MENUS               CREATE MENUS
//-----------------------------------------------------------------------

// Memory reservation
//-----------------------------------------------------------------------
static struct menu_group_struct ObjGroup[1];

// Creating the menus
//-----------------------------------------------------------------------
STATUS OutdoorTemperatureMenuAppInit(U8 ModuleState, OS_MEMORY_POOL* pPool)
{
   STATUS Status;

   if (ModuleState == APP_INIT1)
   {
      /* Create application group */
      Status = OS_CreateMenuGroup(ObjGroup, M_OutdoorTemperatureLinkToLocalMenu[0].LinkGroup);
      STATUS_LINE_VAR_RETURN_VALUE(Status);
   }

   Status = CreateAndInitializeMenu(ModuleState,
                                    M_OutdoorTemperatureMenuLines[0].LinkGroup,
                                    M_OutdoorTemperatureMenuLines[0].LinkName,
                                    ELEMENT(M_OutdoorTemperatureLinkToLocalMenu),
                                    M_OutdoorTemperatureLinkToLocalMenu[0].LinkGroup,
                                    ELEMENT(M_OutdoorTemperatureMenu),
                                    M_OutdoorTemperatureLinkToLocalMenu[0].LinkName,
                                    ELEMENT(M_OutdoorTemperatureMenuLines),
                                    pPool,
                                    M_OutdoorTemperatureMultiplexedCategoriesParameters);
   STATUS_LINE_VAR_RETURN_VALUE(Status);

   Status = CreateAndInitializeMenu(ModuleState,
                                    M_Status2MenuLines[0].LinkGroup,
                                    M_Status2MenuLines[0].LinkName,
                                    NULL,
                                    0,
                                    M_OutdoorTemperatureMenuLines[4].LinkGroup,
                                    ELEMENT(M_Status2Menu),
                                    M_OutdoorTemperatureMenuLines[4].LinkName,
                                    ELEMENT(M_Status2MenuLines),
                                    pPool,
                                    M_OutdoorTemperatureMultiplexedCategoriesParameters);
   STATUS_LINE_VAR_RETURN_VALUE(Status);

   Status = CreateAndInitializeMenu(ModuleState,
                                    M_SensorInputs50MenuLines[0].LinkGroup,
                                    M_SensorInputs50MenuLines[0].LinkName,
                                    NULL,
                                    0,
                                    M_Status2MenuLines[7].LinkGroup,
                                    ELEMENT(M_SensorInputs50Menu),
                                    M_Status2MenuLines[7].LinkName,
                                    ELEMENT(M_SensorInputs50MenuLines),
                                    pPool,
                                    M_OutdoorTemperatureMultiplexedCategoriesParameters);
   STATUS_LINE_VAR_RETURN_VALUE(Status);

   Status = CreateAndInitializeMenu(ModuleState,
                                    M_Parameter3MenuLines[0].LinkGroup,
                                    M_Parameter3MenuLines[0].LinkName,
                                    NULL,
                                    0,
                                    M_OutdoorTemperatureMenuLines[5].LinkGroup,
                                    ELEMENT(M_Parameter3Menu),
                                    M_OutdoorTemperatureMenuLines[5].LinkName,
                                    ELEMENT(M_Parameter3MenuLines),
                                    pPool,
                                    M_OutdoorTemperatureMultiplexedCategoriesParameters);
   STATUS_LINE_VAR_RETURN_VALUE(Status);

   Status = CreateAndInitializeMenu(ModuleState,
                                    M_AirHumidityParameters109MenuLines[0].LinkGroup,
                                    M_AirHumidityParameters109MenuLines[0].LinkName,
                                    NULL,
                                    0,
                                    M_Parameter3MenuLines[3].LinkGroup,
                                    ELEMENT(M_AirHumidityParameters109Menu),
                                    M_Parameter3MenuLines[3].LinkName,
                                    ELEMENT(M_AirHumidityParameters109MenuLines),
                                    pPool,
                                    M_OutdoorTemperatureMultiplexedCategoriesParameters);
   STATUS_LINE_VAR_RETURN_VALUE(Status);

   Status = CreateAndInitializeMenu(ModuleState,
                                    M_OutdoorTemperatureParameters122MenuLines[0].LinkGroup,
                                    M_OutdoorTemperatureParameters122MenuLines[0].LinkName,
                                    NULL,
                                    0,
                                    M_Parameter3MenuLines[4].LinkGroup,
                                    ELEMENT(M_OutdoorTemperatureParameters122Menu),
                                    M_Parameter3MenuLines[4].LinkName,
                                    ELEMENT(M_OutdoorTemperatureParameters122MenuLines),
                                    pPool,
                                    M_OutdoorTemperatureMultiplexedCategoriesParameters);
   STATUS_LINE_VAR_RETURN_VALUE(Status);

   Status = CreateAndInitializeMenu(ModuleState,
                                    M_TemperatureSensor488MenuLines[0].LinkGroup,
                                    M_TemperatureSensor488MenuLines[0].LinkName,
                                    NULL,
                                    0,
                                    M_OutdoorTemperatureParameters122MenuLines[13].LinkGroup,
                                    ELEMENT(M_TemperatureSensor488Menu),
                                    M_OutdoorTemperatureParameters122MenuLines[13].LinkName,
                                    ELEMENT(M_TemperatureSensor488MenuLines),
                                    pPool,
                                    M_OutdoorTemperatureMultiplexedCategoriesParameters);
   STATUS_LINE_VAR_RETURN_VALUE(Status);

   Status = CreateAndInitializeMenu(ModuleState,
                                    M_Debug86MenuLines[0].LinkGroup,
                                    M_Debug86MenuLines[0].LinkName,
                                    NULL,
                                    0,
                                    M_OutdoorTemperatureMenuLines[6].LinkGroup,
                                    ELEMENT(M_Debug86Menu),
                                    M_OutdoorTemperatureMenuLines[6].LinkName,
                                    ELEMENT(M_Debug86MenuLines),
                                    pPool,
                                    M_OutdoorTemperatureMultiplexedCategoriesParameters);
   STATUS_LINE_VAR_RETURN_VALUE(Status);

   return OS_SUCCESS;
}

#define CREATE_MENU

//-----------------------------------------------------------------------
//               BUTTONS FUNCTIONS FORWARD DECLARATIONS
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// BUTTONS                       BUTTONS                      BUTTONS
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
//             SET/RESET FUNCTIONS FORWARD DECLARATIONS
//-----------------------------------------------------------------------
static U8 StatusSetFunc200(void);
static U8 StatusResetFunc200(void);
static U8 StatusSetFunc201(void);
static U8 StatusResetFunc201(void);
static U8 StatusSetFunc236(void);
static U8 StatusResetFunc236(void);
static U8 StatusSetFunc237(void);
static U8 StatusResetFunc237(void);
static U8 StatusSetFunc264(void);
static U8 StatusResetFunc264(void);
static U8 StatusSetFunc5050(void);
static U8 StatusResetFunc5050(void);
static U8 StatusSetFunc5051(void);
//-----------------------------------------------------------------------
// STATUSCODES                 STATUSCODES                 STATUSCODES
//-----------------------------------------------------------------------

static struct sts_statuscode_structure StatusCodes[] =
{
   STS_CODE_ELEMENT("Outdoor temp. low",      20*SEC,    200,       STATUSCODE_UPDATE_TYPE_POLLING,         PASSWORD_LEVEL_SERVICE,            STATUSCODE_TIMER_TYPE_CONSTANT,     STATUSCODE_TIMER_TYPE_CONSTANT,     STATUSCODE_RESET_TYPE_AUTOMATIC,    STATUSCODE_PRIORITY_LOW,       27,   1,    32,   NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    StatusSetFunc200,        StatusResetFunc200,      BRAKE_PROG_0,        BRAKE_PROG_0,        BRAKE_PROG_MAX,      NULL,                PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    YAW_PROG_0,          YAW_PROG_0,          YAW_PROG_240,        NULL,                PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,    0,    255,  NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            1,  PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      1000,      20,        1000,      NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    1*MINUTE,  SETDELAY_MIN,   SETDELAY_MAX,   NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      1*MINUTE,  RESETDELAY_MIN, RESETDELAY_MAX, NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      0,         REPEATTIMES_MIN,     REPEATTIMES_MAX,     NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         REPEATPERIOD_MIN,    REPEATPERIOD_MAX,    NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         REPEATCODE_MIN,      REPEATCODE_MAX,      NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         TIMEOUTPERIOD_MIN,   65535,               NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         TIMEOUTCODE_MIN,     TIMEOUTCODE_MAX,     NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    NULL),
   STS_CODE_ELEMENT("Outdoor temp. high",     20*SEC,    201,       STATUSCODE_UPDATE_TYPE_POLLING,         PASSWORD_LEVEL_SERVICE,            STATUSCODE_TIMER_TYPE_CONSTANT,     STATUSCODE_TIMER_TYPE_CONSTANT,     STATUSCODE_RESET_TYPE_AUTOMATIC,    STATUSCODE_PRIORITY_LOW,       27,   1,    32,   NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    StatusSetFunc201,        StatusResetFunc201,      BRAKE_PROG_0,        BRAKE_PROG_0,        BRAKE_PROG_MAX,      NULL,                PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    YAW_PROG_0,          YAW_PROG_0,          YAW_PROG_240,        NULL,                PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,    0,    255,  NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            1,  PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      1000,      20,        1000,      NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    1*MINUTE,  SETDELAY_MIN,   SETDELAY_MAX,   NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      1*MINUTE,  RESETDELAY_MIN, RESETDELAY_MAX, NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      0,         REPEATTIMES_MIN,     REPEATTIMES_MAX,     NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         REPEATPERIOD_MIN,    REPEATPERIOD_MAX,    NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         REPEATCODE_MIN,      REPEATCODE_MAX,      NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         TIMEOUTPERIOD_MIN,   65535,               NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         TIMEOUTCODE_MIN,     TIMEOUTCODE_MAX,     NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    NULL),
   STS_CODE_ELEMENT("Out.temp low stop",      20*SEC,    236,       STATUSCODE_UPDATE_TYPE_POLLING,         PASSWORD_LEVEL_SERVICE,            STATUSCODE_TIMER_TYPE_CONSTANT,     STATUSCODE_TIMER_TYPE_CONSTANT,     STATUSCODE_RESET_TYPE_AUTOMATIC,    STATUSCODE_PRIORITY_LOW,       29,   1,    32,   NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    StatusSetFunc236,        StatusResetFunc236,      BRAKE_PROG_50,       BRAKE_PROG_0,        BRAKE_PROG_MAX,      NULL,                PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    YAW_PROG_0,          YAW_PROG_0,          YAW_PROG_240,        NULL,                PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    1,    0,    255,  NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            1,  PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      1000,      20,        1000,      NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    1*MINUTE,  SETDELAY_MIN,   SETDELAY_MAX,   NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      1*MINUTE,  RESETDELAY_MIN, RESETDELAY_MAX, NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      3,         REPEATTIMES_MIN,     REPEATTIMES_MAX,     NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    1ULL*DAY,  REPEATPERIOD_MIN,    REPEATPERIOD_MAX,    NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    23,        REPEATCODE_MIN,      REPEATCODE_MAX,      NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         TIMEOUTPERIOD_MIN,   65535,               NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         TIMEOUTCODE_MIN,     TIMEOUTCODE_MAX,     NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    NULL),
   STS_CODE_ELEMENT("Out.temp hi. Stop",      20*SEC,    237,       STATUSCODE_UPDATE_TYPE_POLLING,         PASSWORD_LEVEL_SERVICE,            STATUSCODE_TIMER_TYPE_CONSTANT,     STATUSCODE_TIMER_TYPE_CONSTANT,     STATUSCODE_RESET_TYPE_AUTOMATIC,    STATUSCODE_PRIORITY_LOW,       29,   1,    32,   NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    StatusSetFunc237,        StatusResetFunc237,      BRAKE_PROG_50,       BRAKE_PROG_0,        BRAKE_PROG_MAX,      NULL,                PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    YAW_PROG_0,          YAW_PROG_0,          YAW_PROG_240,        NULL,                PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    1,    0,    255,  NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            1,  PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      1000,      20,        1000,      NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    1*MINUTE,  SETDELAY_MIN,   SETDELAY_MAX,   NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      1*MINUTE,  RESETDELAY_MIN, RESETDELAY_MAX, NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      3,         REPEATTIMES_MIN,     REPEATTIMES_MAX,     NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    1ULL*DAY,  REPEATPERIOD_MIN,    REPEATPERIOD_MAX,    NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    23,        REPEATCODE_MIN,      REPEATCODE_MAX,      NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         TIMEOUTPERIOD_MIN,   65535,               NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         TIMEOUTCODE_MIN,     TIMEOUTCODE_MAX,     NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    NULL),
   STS_CODE_ELEMENT("Outdoor Temperature!",   20*SEC,    264,       STATUSCODE_UPDATE_TYPE_POLLING,         PASSWORD_LEVEL_SERVICE,            STATUSCODE_TIMER_TYPE_CONSTANT,     STATUSCODE_TIMER_TYPE_CONSTANT,     STATUSCODE_RESET_TYPE_AUTOMATIC,    STATUSCODE_PRIORITY_LOW,       27,   1,    32,   NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    StatusSetFunc264,        StatusResetFunc264,      BRAKE_PROG_50,       BRAKE_PROG_0,        BRAKE_PROG_MAX,      NULL,                PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    YAW_PROG_0,          YAW_PROG_0,          YAW_PROG_240,        NULL,                PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    1,    0,    255,  NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            1,  PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      1000,      20,        1000,      NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    10*SEC,    SETDELAY_MIN,   SETDELAY_MAX,   NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      10*SEC,    RESETDELAY_MIN, RESETDELAY_MAX, NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      3,         REPEATTIMES_MIN,     REPEATTIMES_MAX,     NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    1ULL*DAY,  REPEATPERIOD_MIN,    REPEATPERIOD_MAX,    NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    23,        REPEATCODE_MIN,      REPEATCODE_MAX,      NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         TIMEOUTPERIOD_MIN,   65535,               NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         TIMEOUTCODE_MIN,     TIMEOUTCODE_MAX,     NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    NULL),
   STS_CODE_ELEMENT("Outdoor 4-20mA!",        20*SEC,    5050,      STATUSCODE_UPDATE_TYPE_POLLING,         PASSWORD_LEVEL_SERVICE,            STATUSCODE_TIMER_TYPE_CONSTANT,     STATUSCODE_TIMER_TYPE_CONSTANT,     STATUSCODE_RESET_TYPE_AUTOMATIC,    STATUSCODE_PRIORITY_LOW,       0,    0,    32,   NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         StatusSetFunc5050,       StatusResetFunc5050,     0,                   BRAKE_PROG_0,        BRAKE_PROG_MAX,      NULL,                PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,                   YAW_PROG_0,          YAW_PROG_240,        NULL,                PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,    0,    255,  NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            1,  PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      1000,      20,        1000,      NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         SETDELAY_MIN,   SETDELAY_MAX,   NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         0,         RESETDELAY_MIN, RESETDELAY_MAX, NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         0,         REPEATTIMES_MIN,     REPEATTIMES_MAX,     NULL,      PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         REPEATPERIOD_MIN,    REPEATPERIOD_MAX,    NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         REPEATCODE_MIN,      REPEATCODE_MAX,      NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         TIMEOUTPERIOD_MIN,   TIMEOUTPERIOD_MAX,   NULL,      PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         TIMEOUTCODE_MIN,     TIMEOUTCODE_MAX,     NULL,      PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         NULL),
   STS_CODE_ELEMENT("Ice-forming",            20*SEC,    5051,      STATUSCODE_UPDATE_TYPE_POLLING,         PASSWORD_LEVEL_SERVICE,            STATUSCODE_TIMER_TYPE_CONSTANT,     STATUSCODE_TIMER_TYPE_CONSTANT,     STATUSCODE_RESET_TYPE_DISPLAY,      STATUSCODE_PRIORITY_LOW,       27,   0,    32,   NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         StatusSetFunc5051,       NULL,                    BRAKE_PROG_50,       BRAKE_PROG_0,        BRAKE_PROG_MAX,      NULL,                PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,                   YAW_PROG_0,          YAW_PROG_240,        NULL,                PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    1,    0,    255,  NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            1,  PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_LICENCE_PROGRAMMER, 1000,      20,        1000,      NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         SETDELAY_MIN,   SETDELAY_MAX,   NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         0,         RESETDELAY_MIN, RESETDELAY_MAX, NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         0,         REPEATTIMES_MIN,     REPEATTIMES_MAX,     NULL,      PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         REPEATPERIOD_MIN,    REPEATPERIOD_MAX,    NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         REPEATCODE_MIN,      REPEATCODE_MAX,      NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         TIMEOUTPERIOD_MIN,   TIMEOUTPERIOD_MAX,   NULL,      PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         TIMEOUTCODE_MIN,     TIMEOUTCODE_MAX,     NULL,      PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         NULL),
};

static STATUS_CODE_CONTROL_BLOCK StatusCodeControlBlock;

static STATUS LocalStatusCodeInit(void)
{
   STATUS LocalStatus;

   LocalStatus = OS_StatusCodeInit(STATUSCODE_INTERFACE_VERSION,
                                   &StatusCodeControlBlock,
                                   StatusCodes,
                                   sizeof(StatusCodes)/sizeof(StatusCodes[0]),
                                   AppLocalParameterPosition(),
                                   AppBackupPosition());
   STATUS_LINE_VAR_RETURN_CONST(LocalStatus, ERR_3);

   return OS_SUCCESS;
}

#define CREATE_STATUS_CODES

//-----------------------------------------------------------------------
// MODIFIABLE                  MODIFIABLE                   MODIFIABLE
//-----------------------------------------------------------------------

extern const char OutdoorTemperatureAppGroupName[];
extern const char OutdoorTemperatureAppMenuName[];

static void Init_Structures_From_Conf_File(void)
{
   M_OutdoorTemperatureMenuLines[0].LinkName = (char*)OutdoorTemperatureAppMenuName;
   M_OutdoorTemperatureMenuLines[0].LinkGroup = (char*)OutdoorTemperatureAppGroupName;
}

//-----------------------------------------------------------------------
// AUTOGENERATED END        AUTOGENERATED END        AUTOGENERATED END
//-----------------------------------------------------------------------
//}

#undef AUTOGENERATED_PART

//-----------------------------------------------------------------------
// USER DEFINITIONS         USER DEFINITIONS         USER DEFINITIONS
//-----------------------------------------------------------------------

volatile const U8 OutdoorTemperature_ModuleInterfaceError_Version_1; // Version check
struct  S32Buffer OutdoorTempAverBuf;
// Values for Status of the Sensors

typedef enum _SENSOR_STATUS_t
{
    SENSOR_STATUS_OK = 0,
    SENSOR_STATUS_ERROR,
    SENSOR_STATUS_DISABLED
} SENSOR_STATUS_t;

//-----------------------------------------------------------------------
// DRIVER FUNCTION         DRIVER FUNCTION         DRIVER FUNCTION
//-----------------------------------------------------------------------
static S32 LinearConvertion(S32 Value, S32 MinIn, S32 MaxIn, S32 MinOut, S32 MaxOut)
{
    S32 Res;

    if (MaxIn != MinIn) { Res = ((S64)Value - MinIn)*(MaxOut - MinOut)/(MaxIn - MinIn) + MinOut; }
    else                { Res = MinOut; }

    return Res;
}
//-----------------------------------------------------------------------
S32 LinearLimConvertion(S32 Value, S32 MinIn, S32 MaxIn, S32 MinOut, S32 MaxOut)
{
    S32 Res;

    Res = LinearConvertion( Value, MinIn, MaxIn, MinOut, MaxOut );

    if( MinOut <= MaxOut )
    {
        if      ( Res < MinOut )    { Res = MinOut; }
        else if ( Res > MaxOut )    { Res = MaxOut; }
    }
    else
    {
        if      ( Res < MaxOut )    { Res = MaxOut; }
        else if ( Res > MinOut )    { Res = MinOut; }
    }

    return Res;
}
//-----------------------------------------------------------------------
static U8 VerifyLimits(S32 Input, S32 Min, S32 Max)
{
    if( (Input > Max) || (Input < Min ) )
    {
        return SENSOR_STATUS_ERROR;
    }
    else
    {
        return SENSOR_STATUS_OK;
    }
}

static U8 SensorStatus( U8 Enable, S32 Input, S32 Min, S32 Max )
{
    if( !Enable )
    {
        return SENSOR_STATUS_DISABLED;
    }
    else
    {
        return VerifyLimits( Input, Min, Max );
    }
}

static void SensorStatusTxt( S32 Status, S32 *OldStatus, char *Text, S32 Size )
{
    if( Status != *OldStatus )
    {
        switch( Status )
        {
            case SENSOR_STATUS_OK:
            {
                strncpy( Text, "OK", Size );
            }
                break;
            case SENSOR_STATUS_DISABLED:
            {
                strncpy( Text, "Disabled", Size );
            }
                break;
            case SENSOR_STATUS_ERROR:
            {
                strncpy( Text, "Sensor Error", Size );
            }
                break;
            default:
            {
                strncpy( Text, "WARNING", Size );
            }
                break;
        }
    }

    *OldStatus = Status;
}

//-----------------------------------------------------------------------
// SET/RESET FUNCTIONS    SET/RESET FUNCTIONS    SET/RESET FUNCTIONS
//-----------------------------------------------------------------------

static U8 StatusSetFunc200(void)
{
	if(V_OutDoorTemp >= P_OutdoorTempLowWarnOn)
		return 0;
	if(!P_OutdoorTempEnable)
		return 0;
	if(StatusCodeActive(236))
	   return 0;
	return 1;
}

static U8 StatusResetFunc200(void)
{
	if(V_OutDoorTemp > P_OutdoorTempLowWarnOff)
		return 1;
	if(!P_OutdoorTempEnable)
	   return 1;
	if(StatusCodeActive(236))
	   return 1;
   return 0;
}

static U8 StatusSetFunc201(void)
{
    if(V_OutDoorTemp <= P_OutdoorTempHighWarnOn)
    	return 0;
	if(!P_OutdoorTempEnable)
		return 0;
    if(StatusCodeActive(237))
	    return 0;
   return 1;
}

static U8 StatusResetFunc201(void)
{
	if(V_OutDoorTemp < P_OutdoorTempHighWarnOff)
		return 1;
	if(!P_OutdoorTempEnable)
	   return 1;
   if(StatusCodeActive(237))
	   return 1;
   return 0;
}

static U8 StatusSetFunc236(void)
{
	if(V_OutDoorTemp >= P_OutdoorTempLowStopOn)
		   return 0;
	if(!P_OutdoorTempEnable)
	   return 0;
   return 1;
}

static U8 StatusResetFunc236(void)
{
	if(V_OutDoorTemp > P_OutdoorTempLowStopOff)
		return 1;
	if(!P_OutdoorTempEnable)
		return 1;
   return 0;
}

static U8 StatusSetFunc237(void)
{
	if(V_OutDoorTemp <= P_OutdoorTempHighStopOn)
		return 0;
	if(!P_OutdoorTempEnable)
	   return 0;
   return 1;
}

static U8 StatusResetFunc237(void)
{
	if(V_OutDoorTemp < P_OutdoorTempHighStopOff)
		return 1;
	if(!P_OutdoorTempEnable)
		return 1;
   return 0;
}

static U8 StatusSetFunc264(void)
{
   if(!P_OutdoorTempEnable)
	   return 0;
   if(P_OutdoorTempSensorSelect == 0 && V_OutdoorTempSensor1Status && V_OutdoorTempSensor2Status && V_OutdoorTempSensor3Status)
	   return 1;
   if(P_OutdoorTempSensorSelect == 1 && V_OutdoorTempSensor1Status)
	   return 1;
   if(P_OutdoorTempSensorSelect == 2 && V_OutdoorTempSensor2Status)
	   return 1;
   if(P_OutdoorTempSensorSelect == 3 && V_OutdoorTempSensor3Status)
       return 1;
   if( (P_OutdoorTempSensorSelect == 4) && (SENSOR_STATUS_OK < V_OutdoorTempSensor4Status) )
      return 1;
   return 0;
}

static U8 StatusResetFunc264(void)
{
   if(!P_OutdoorTempEnable)
	   return 1;
   if(P_OutdoorTempSensorSelect == 0 && (!V_OutdoorTempSensor1Status || !V_OutdoorTempSensor2Status || !V_OutdoorTempSensor3Status))
	   return 1;
   if(P_OutdoorTempSensorSelect == 1 && !V_OutdoorTempSensor1Status)
	   return 1;
   if(P_OutdoorTempSensorSelect == 2 && !V_OutdoorTempSensor2Status)
	   return 1;
   if(P_OutdoorTempSensorSelect == 3 && !V_OutdoorTempSensor3Status)
       return 1;
   if( (P_OutdoorTempSensorSelect == 4) && (SENSOR_STATUS_OK == V_OutdoorTempSensor4Status) )
       return 1;
   return 0;
}

static U8 StatusSetFunc5050(void)
{
   if( (SENSOR_STATUS_ERROR == V_OutdoorAirHumidity_SensorStatus) ||
       (SENSOR_STATUS_ERROR == V_OutdoorTempSensor4Status) )
       return 1;
   return 0;
}

static U8 StatusResetFunc5050(void)
{
   return !StatusSetFunc5050();
}

static U8 StatusSetFunc5051(void)
{
   if(!P_Outdoor_AirHumidity_Enable || V_OutdoorAirHumidity_SensorStatus)
       return 0;
   if(!P_OutdoorTempEnable || StatusCodeActive(264))
       return 0;
   if(   V_OutDoorTemp          < P_OutdoorTemp_IcedDanger
      && V_OutdoorAirHumidity   > P_Outdoor_AirHumidity_IcedDanger)
       return 1;
   return 0;
}

//-----------------------------------------------------------------------
// INIT                   INIT                     INIT
//-----------------------------------------------------------------------


static STATUS AverageInit(void)
{
   ClearS32Buffer(&OutdoorTempAverBuf);

   return OS_SUCCESS;
}

//-----------------------------------------------------------------------
// CONTROL                CONTROL                 CONTROL
//-----------------------------------------------------------------------
  
static STATUS LocalCtrl(void)
{
   STATUS LocalStatus = 0;
   static S32 OutdoorTempSensor4Status_old          = S32_MIN;
   static S32 OutdoorAirHumidity_SensorStatus_old   = S32_MIN;
   S32 HumiditySensorErrorLow  = P_Outdoor_AirHumidityInputMin - P_Outdoor_AirHumidityInputErr;
   S32 HumiditySensorErrorHigh = P_Outdoor_AirHumidityInputMax + P_Outdoor_AirHumidityInputErr;

   // Air Humidity
   V_OutdoorAirHumidity_SensorStatus = SensorStatus( P_Outdoor_AirHumidity_Enable,
                                                    (S32)AI_OutdoorAirHumidity,
                                                     HumiditySensorErrorLow,
                                                     HumiditySensorErrorHigh
                                                   );
   if( SENSOR_STATUS_OK == V_OutdoorAirHumidity_SensorStatus )
   {
       V_OutdoorAirHumidity = (U32)LinearLimConvertion( (S32)AI_OutdoorAirHumidity,       //S32 Value
                                                         P_Outdoor_AirHumidityInputMin,   //S32 MinIn
                                                         P_Outdoor_AirHumidityInputMax,   //S32 MaxIn
                                                         P_Outdoor_AirHumidityOutputMin,  //S32 MinOut
                                                         P_Outdoor_AirHumidityOutputMax   //S32 MaxOut
                                                       );
   }
   SensorStatusTxt( V_OutdoorAirHumidity_SensorStatus,
                    &OutdoorAirHumidity_SensorStatus_old,
                    V_OutdoorAirHumidity_StatusText,
                    sizeof(V_OutdoorAirHumidity_StatusText)
                  );

   // Outdoor temp. Sensor 4
   V_OutdoorTempSensor4Status       = SensorStatus( P_OutdoorTempEnable_Sensor4,
                                                      (S32)AI_OutdoorTempSensor4_Curr,
                                                      P_OutdoorTempSensor4InputMin,
                                                      P_OutdoorTempSensor4InputMax );
   if( SENSOR_STATUS_OK == V_OutdoorTempSensor4Status  )
   {
       AI_OutdoorTempSensor4 = (S16)LinearLimConvertion( (S32)AI_OutdoorTempSensor4_Curr,
                                                       P_OutdoorTempSensor4InputMin,
                                                       P_OutdoorTempSensor4InputMax,
                                                       P_OutdoorTempSensorOutputMin,
                                                       P_OutdoorTempSensor4OutputMax
                                                  );
   }

   SensorStatusTxt( V_OutdoorTempSensor4Status,
                    &OutdoorTempSensor4Status_old,
                    V_OutdoorTempSensor4StatusTxt,
                    sizeof(V_OutdoorTempSensor4StatusTxt)
                  );

   V_OutdoorTempSensor3Status        = VerifyLimits((S32)PT_OutdoorTemperature,
                                                    P_Outdoor_PT100_ErrLow,
                                                    P_Outdoor_PT100_ErrHigh);

   // Sensor Selector
   	switch(P_OutdoorTempSensorSelect)
   	{
   		case 0: //AUTO
   		{
   			if(!V_OutdoorTempSensor1Status && !V_OutdoorTempSensor2Status)
   			{
   				strcpy(V_OutdoorTempSensorsActiveText,"All" );
   				V_OutDoorTemp = (V_OutdoorTempSensor1 + V_OutdoorTempSensor2) / 2;
   				if(V_OutdoorTempSensor1 > V_OutdoorTempSensor2)
   					V_OutdoorTemperatureRef = V_OutdoorTempSensor1;
   				else
   					V_OutdoorTemperatureRef = V_OutdoorTempSensor2;

   			}
   			else if(!V_OutdoorTempSensor1Status && V_OutdoorTempSensor2Status)
   			{
   				strcpy(V_OutdoorTempSensorsActiveText,"Sensor 1" );
   				V_OutDoorTemp = V_OutdoorTempSensor1;
   				V_OutdoorTemperatureRef = V_OutdoorTempSensor1;
   			}
   			else if(V_OutdoorTempSensor1Status && !V_OutdoorTempSensor2Status)
   			{
   				strcpy(V_OutdoorTempSensorsActiveText,"Sensor 2" );
   				V_OutDoorTemp = V_OutdoorTempSensor2;
   				V_OutdoorTemperatureRef = V_OutdoorTempSensor2;
   			}
   			else
   			{
   				strcpy(V_OutdoorTempSensorsActiveText,"None" );
   				V_OutDoorTemp = 0;
   				V_OutdoorTemperatureRef = 0;
   			}
   			break;
   		}
   		case 1: //Sensor 1 selected manually
   		{
   			if(!V_OutdoorTempSensor1Status) //No Errors in sensor 1
   			{
   				strcpy(V_OutdoorTempSensorsActiveText,"Sensor 1" );
   				V_OutDoorTemp = V_OutdoorTempSensor1;
   				V_OutdoorTemperatureRef = V_OutdoorTempSensor1;
   			}
   			else
   			{
   				strcpy(V_OutdoorTempSensorsActiveText,"None" );
   				V_OutDoorTemp = 0;
   				V_OutdoorTemperatureRef = 0;
   			}
   			break;
   		}
   		case 2: //Sensor 2 selected manually
   		{
   			if(!V_OutdoorTempSensor2Status) //No Errors in sensor 2
   			{
   				strcpy(V_OutdoorTempSensorsActiveText,"Sensor 2" );
   				V_OutDoorTemp = V_OutdoorTempSensor2;
   				V_OutdoorTemperatureRef = V_OutdoorTempSensor2;
   			}
   			else
   			{
   				strcpy(V_OutdoorTempSensorsActiveText,"None" );
   				V_OutDoorTemp = 0;
   				V_OutdoorTemperatureRef = 0;
   			}
   			break;
   		}
   		case 3: //Sensor 3 selected manually
        {
            if(!V_OutdoorTempSensor3Status) //No Errors in sensor 3
            {
                strcpy(V_OutdoorTempSensorsActiveText,"Sensor 3" );
                V_OutDoorTemp = PT_OutdoorTemperature;
                V_OutdoorTemperatureRef = PT_OutdoorTemperature;
            }
            else
            {
                strcpy(V_OutdoorTempSensorsActiveText,"None" );
                V_OutDoorTemp = 0;
                V_OutdoorTemperatureRef = 0;
            }
            break;
        }
   		case 4: //Sensor 4 selected manually
        {
            if(!V_OutdoorTempSensor4Status) //No Errors in sensor 4
            {
                strcpy(V_OutdoorTempSensorsActiveText,"Sensor 4" );
                V_OutDoorTemp = AI_OutdoorTempSensor4;
                V_OutdoorTemperatureRef = AI_OutdoorTempSensor4;
            }
            else
            {
                strcpy(V_OutdoorTempSensorsActiveText,"None" );
                V_OutDoorTemp = 0;
                V_OutdoorTemperatureRef = 0;
            }
            break;
        }
   		default:
   		{
   			break;
   		}
   	}

   	//Sensor status text update
   	if(!V_OutdoorTempSensor1Status)
   		strcpy(V_OutdoorTempSensor1StatusText,"Ok" );
   	else
   		strcpy(V_OutdoorTempSensor1StatusText,"Error" );
   	if(!V_OutdoorTempSensor2Status)
   		strcpy(V_OutdoorTempSensor2StatusText,"Ok" );
   	else
   		strcpy(V_OutdoorTempSensor2StatusText,"Error" );
   	if(!V_OutdoorTempSensor3Status)
        strcpy(V_OutdoorTempSensor3StatusText,"Ok" );
    else
        strcpy(V_OutdoorTempSensor3StatusText,"Error" );


	LocalStatus = UpdateS32Buffer(&OutdoorTempAverBuf , (S32)V_OutDoorTemp);
	STATUS_LINE_VAR_RETURN_CONST(LocalStatus, ERR_3);
	V_OutDoorTemp1Sec = (S16)(OutdoorTemp1s());
	V_OutDoorTemp3Sec = (S16)(OutdoorTemp3s());
	V_OutDoorTemp30Sec = (S16)(OutdoorTemp30s());
	V_OutDoorTemp10Min = (S16)(OutdoorTemp10m());

   return LocalStatus;
}
  
//-----------------------------------------------------------------------
// MAIN CALL             MAIN CALL               MAIN CALL
//-----------------------------------------------------------------------

STATUS OutdoorTemperature(U8 ModuleState, OS_MEMORY_POOL *MemPool, U32 *Arg3)
{
   STATUS LocalStatus = 0;

   // Version check
   if(ModuleState == APP_INIT1)
   {
      LocalStatus = OS_ValidateAPI(API_VERSION_MAJOR,
                                   API_VERSION_MINOR,
                                   OS_LinkTime,
                                   ReleaseTag,
                                   __MODULE__
                                   );
      if ( OS_SUCCESS != LocalStatus )
      {
         return LocalStatus;
      }
   }
#ifdef READ_VARS
   // Read inputdata
   LocalStatus = InputReferenceRoutine(ModuleState);
   STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif
#ifdef COMMON_VDB_READ
   LocalStatus = ReadVdbWindow(ModuleState);
   STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif
   switch(ModuleState)
   {
      case APP_RUN :
      {
         #ifdef FUNCTION_BLOCKS_PRE_LOCAL_CONTROL
            LocalStatus = FunctionBlocksPreLocalCtrl( Interval );
            STATUS_LINE_VAR_RETURN_VALUE( LocalStatus );
         #endif

         LocalStatus = LocalCtrl();
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
        
         #ifdef FUNCTION_BLOCKS_POST_LOCAL_CONTROL
            LocalStatus = FunctionBlocksPostLocalCtrl( Interval );
            STATUS_LINE_VAR_RETURN_VALUE( LocalStatus );
         #endif

#ifdef WRITE_VARS
         // Write Outputdata
         LocalStatus = OutputReferenceRoutine(ModuleState);
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif

#ifdef COMMON_VDB_WRITE
         LocalStatus = WriteVdbWindow(ModuleState);
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif
         break;
      }
      case APP_INIT1 :
      {
         Init_Structures_From_Conf_File();
         (void)OutdoorTemperature_ModuleInterfaceError_Version_1;        // Version check
#ifdef CREATE_VARDB_VARS
         LocalStatus = CreateVarDbVars();
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif

#ifdef CREATE_MENU
         LocalStatus = OutdoorTemperatureMenuAppInit(ModuleState, MemPool);
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)

#ifdef MULTIPLEXIBLE_MENU
         LocalStatus = MenuArraysAppInit(ModuleState, MemPool);
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif
#endif

#ifdef CREATE_VARDB_ARRAY_VARS
         LocalStatus = CreateVdbArrays(MemPool);
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif

#ifdef CREATE_IO_VARS
         LocalStatus = CreateIOVars();
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif
         break;
      }
      case APP_INIT2 :
      {
#ifdef CREATE_MENU
#ifdef MULTIPLEXIBLE_MENU
         LocalStatus = MenuArraysAppInit(ModuleState, MemPool);
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif
#endif

#ifdef CREATE_ALIASES
         size_t ErrorEntry = 0;
         LocalStatus = OS_VarDB_CreateAliases(AliasVars, sizeof(AliasVars)/sizeof(AliasVars[0]), &ErrorEntry);
         STATUS_LINE_VAR_RETURN_CONST(LocalStatus, ErrorEntry)
#endif

#ifdef VERIFY_ARRAY
        LocalStatus = VerifyArray(MemPool);
        STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif

#ifdef VERIFY_VARIABLES
         LocalStatus = LocalIoCheck();
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif

#ifdef CREATE_BUTTONS
         LocalStatus = CreateButtons();
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif
         break;
      }
      case APP_INIT3 :
      {
#ifdef CREATE_SUMMATIONS
         LocalStatus = CreateSummations();
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif

#ifdef WRITE_VARS
         LocalStatus = InitOutputVars();
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif

#ifdef CREATE_STATUS_CODES
         LocalStatus = LocalStatusCodeInit();
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif

#ifdef CREATE_IO_VARS
        OutdoorTemperatureSetLockValues();
#endif
         break;
      }
      case APP_INIT4 :
      {
#ifdef CREATE_MENU
         LocalStatus = OutdoorTemperatureMenuAppInit(ModuleState, MemPool);
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)

#ifdef MULTIPLEXIBLE_MENU
         LocalStatus = MenuArraysAppInit(ModuleState, MemPool);
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif
#endif
         break;
      }
      case APP_INIT5 :
      {
#ifdef VALIDATE_HASH
         LocalStatus = ValidateHash(OutdoorTemperature_copyright, MODULE_NAME, OutdoorTemperature_initialValues);
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif

         #ifdef INIT_FUNCTION_BLOCKS
            LocalStatus = FunctionBlocksInit( Interval );
            STATUS_LINE_VAR_RETURN_VALUE( LocalStatus );
         #endif

         LocalStatus = AverageInit();
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
         break;
      }
      default :
      {
         break;
      }
   }
   return OS_SUCCESS;
}
//-----------------------------------------------------------------------
