//*****************************PEPTOOL Header Start******************************
//                                                                               
//                         Copyright © 2015 Mita-Teknik.                         
//This software may only be used with WP4x00 Controllers delivered by Mita-Teknik
//                                                                               
//*******************************************************************************
//                                                                               
// $PEPTOOL version:9.0$                                                         
// $PEPTOOL file version:101$                                                    
//                                                                               
//*******************************************************************************
//                                                                               
// $Date: 2014/03/04 14:32:13 $                                                  
// $Author: MITA\ihn $                                                           
// $RCSfile: Panels_Conf.c,v $                                                   
// $Revision: 1.10 $                                                             
//                                                                               
//******************************PEPTOOL Header End*******************************

//***********************************************************************
// OS header files
#include <os_main.h>
// IO init file
#include <InitIo.h>
      
#define AUTOGENERATED_PART

#include <Turbdef.h>

//-----------------------------------------------------------------------
// AUTOGENERATED START     AUTOGENERATED START     AUTOGENERATED START
//-----------------------------------------------------------------------
char Panels_Conf_copyright[] =
{
   67, 111, 112, 121, 114, 105, 103, 104, 116, 32, 63, 32, 50, 48, 49, 53,
   32, 77, 105, 116, 97, 45, 84, 101, 107, 110, 105, 107, 46, 13, 10, 84,
   104, 105, 115, 32, 115, 111, 102, 116, 119, 97, 114, 101, 32, 109, 97, 121,
   32, 111, 110, 108, 121, 32, 98, 101, 32, 117, 115, 101, 100, 32, 119, 105,
   116, 104, 32, 87, 80, 52, 120, 48, 48, 32, 67, 111, 110, 116, 114, 111,
   108, 108, 101, 114, 115, 32, 100, 101, 108, 105, 118, 101, 114, 101, 100, 32,
   98, 121, 32, 77, 105, 116, 97, 45, 84, 101, 107, 110, 105, 107, 0
};
//-----------------------------------------------------------------------
// MODIFIABLE                  MODIFIABLE               MODIFIABLE
//-----------------------------------------------------------------------
const char PanelsAppGroupName[] = "G_"APP_ID"App";
const char PanelsAppMenuName[] = "M_"APP_ID"AppMain";

//-----------------------------------------------------------------------
// IO VARIABLES                IO VARIABLES                IO VARIABLES
//-----------------------------------------------------------------------

void (*PanelsSetLockValues)(void);
struct os_db_alias *PanelsIOVars;
size_t PanelsIOVarsSize = 0;
            
struct os_db_alias PanelsIOVars1[]=
{
    VAR_ELEMENT_ALIAS("1.4.5",                            "DO_TowerRunGreenLamp"),

    VAR_ELEMENT_ALIAS("1.4.6",                            "DO_TowerFaultRed"),

    VAR_ELEMENT_ALIAS("1.4.7",                            "DO_TowerWarningYellowLamp"),

    VAR_ELEMENT_ALIAS("1.4.8",                            "DO_TowerSafetyChainGreenLamp"),

    VAR_ELEMENT_ALIAS("1.4.11",                           "DO_TowerLeaveIndicatorWhiteLamp"),

    VAR_ELEMENT_ALIAS("1.4.65",                           "PT_TowerControlPanelTemp"),
    VAR_ELEMENT_ALIAS("1.4.65_Ss",                        "PT_TowerControlPanelTemp_Ss"),
    VAR_ELEMENT_ALIAS("1.4.65_E",                         "PT_TowerControlPanelTemp_E"),
    VAR_ELEMENT_ALIAS( "1.4.65_Th",                        "PT_TowerControlPanelTemp_Th"),
    VAR_ELEMENT_ALIAS("1.4.65_Ht",                        "PT_TowerControlPanelTemp_Ht"),
    VAR_ELEMENT_ALIAS("1.4.65_S",                         "PT_TowerControlPanelTemp_S"),
    VAR_ELEMENT_ALIAS("1.4.65_O",                         "PT_TowerControlPanelTemp_O"),

    VAR_ELEMENT_ALIAS("3.2.65",                           "PT_NacelleControlPanelTemp"),
    VAR_ELEMENT_ALIAS("3.2.65_Ss",                        "PT_NacelleControlPanelTemp_Ss"),
    VAR_ELEMENT_ALIAS("3.2.65_E",                         "PT_NacelleControlPanelTemp_E"),
    VAR_ELEMENT_ALIAS( "3.2.65_Th",                        "PT_NacelleControlPanelTemp_Th"),
    VAR_ELEMENT_ALIAS("3.2.65_Ht",                        "PT_NacelleControlPanelTemp_Ht"),
    VAR_ELEMENT_ALIAS("3.2.65_S",                         "PT_NacelleControlPanelTemp_S"),
    VAR_ELEMENT_ALIAS("3.2.65_O",                         "PT_NacelleControlPanelTemp_O"),

    VAR_ELEMENT_ALIAS("3.4.25",                           "PT_PowerPanelLeftSideTemp"),
    VAR_ELEMENT_ALIAS("3.4.25_Ss",                        "PT_PowerPanelLeftSideTemp_Ss"),
    VAR_ELEMENT_ALIAS("3.4.25_E",                         "PT_PowerPanelLeftSideTemp_E"),
    VAR_ELEMENT_ALIAS( "3.4.25_Th",                        "PT_PowerPanelLeftSideTemp_Th"),
    VAR_ELEMENT_ALIAS("3.4.25_Ht",                        "PT_PowerPanelLeftSideTemp_Ht"),
    VAR_ELEMENT_ALIAS("3.4.25_S",                         "PT_PowerPanelLeftSideTemp_S"),
    VAR_ELEMENT_ALIAS("3.4.25_O",                         "PT_PowerPanelLeftSideTemp_O"),

    VAR_ELEMENT_ALIAS("3.4.26",                           "PT_PowerPanelRightSideTemp"),
    VAR_ELEMENT_ALIAS("3.4.26_Ss",                        "PT_PowerPanelRightSideTemp_Ss"),
    VAR_ELEMENT_ALIAS("3.4.26_E",                         "PT_PowerPanelRightSideTemp_E"),
    VAR_ELEMENT_ALIAS( "3.4.26_Th",                        "PT_PowerPanelRightSideTemp_Th"),
    VAR_ELEMENT_ALIAS("3.4.26_Ht",                        "PT_PowerPanelRightSideTemp_Ht"),
    VAR_ELEMENT_ALIAS("3.4.26_S",                         "PT_PowerPanelRightSideTemp_S"),
    VAR_ELEMENT_ALIAS("3.4.26_O",                         "PT_PowerPanelRightSideTemp_O"),

    VAR_ELEMENT_ALIAS("5.2.65",                           "PT_HubControlPanelTemp"),
    VAR_ELEMENT_ALIAS("5.2.65_Ss",                        "PT_HubControlPanelTemp_Ss"),
    VAR_ELEMENT_ALIAS("5.2.65_E",                         "PT_HubControlPanelTemp_E"),
    VAR_ELEMENT_ALIAS( "5.2.65_Th",                        "PT_HubControlPanelTemp_Th"),
    VAR_ELEMENT_ALIAS("5.2.65_Ht",                        "PT_HubControlPanelTemp_Ht"),
    VAR_ELEMENT_ALIAS("5.2.65_S",                         "PT_HubControlPanelTemp_S"),
    VAR_ELEMENT_ALIAS("5.2.65_O",                         "PT_HubControlPanelTemp_O"),

    VAR_ELEMENT_ALIAS("5.2.27",                           "DI_PanelsHubHeatingCoolingSystemFB"),
    VAR_ELEMENT_ALIAS("5.2.27_Ss",                        "DI_PanelsHubHeatingCoolingSystemFB_Ss"),
    VAR_ELEMENT_ALIAS("5.2.27_E",                         "DI_PanelsHubHeatingCoolingSystemFB_E"),
    VAR_ELEMENT_ALIAS("5.2.27_I",                         "DI_PanelsHubHeatingCoolingSystemFB_I"),
    VAR_ELEMENT_ALIAS("5.2.27_Cm",                        "DI_PanelsHubHeatingCoolingSystemFB_Cm"),
    VAR_ELEMENT_ALIAS("5.2.27_Ht",                        "DI_PanelsHubHeatingCoolingSystemFB_Ht"),

    VAR_ELEMENT_ALIAS("1.4.41",                           "DI_Panels_MCCB_StatusBasePanel"),
    VAR_ELEMENT_ALIAS("1.4.41_Ss",                        "DI_Panels_MCCB_StatusBasePanel_Ss"),
    VAR_ELEMENT_ALIAS("1.4.41_E",                         "DI_Panels_MCCB_StatusBasePanel_E"),
    VAR_ELEMENT_ALIAS("1.4.41_I",                         "DI_Panels_MCCB_StatusBasePanel_I"),
    VAR_ELEMENT_ALIAS("1.4.41_Cm",                        "DI_Panels_MCCB_StatusBasePanel_Cm"),
    VAR_ELEMENT_ALIAS("1.4.41_Ht",                        "DI_Panels_MCCB_StatusBasePanel_Ht"),

    VAR_ELEMENT_ALIAS("1.4.40",                           "DI_Panels_TowerBasePanelLight"),
    VAR_ELEMENT_ALIAS("1.4.40_Ss",                        "DI_Panels_TowerBasePanelLight_Ss"),
    VAR_ELEMENT_ALIAS("1.4.40_E",                         "DI_Panels_TowerBasePanelLight_E"),
    VAR_ELEMENT_ALIAS("1.4.40_I",                         "DI_Panels_TowerBasePanelLight_I"),
    VAR_ELEMENT_ALIAS("1.4.40_Cm",                        "DI_Panels_TowerBasePanelLight_Cm"),
    VAR_ELEMENT_ALIAS("1.4.40_Ht",                        "DI_Panels_TowerBasePanelLight_Ht"),

    VAR_ELEMENT_ALIAS("1.4.16",                           "DO_Panels_LightOnOff"),

};
size_t PanelsIOVars1Size = sizeof(PanelsIOVars1)/sizeof(PanelsIOVars1[0]);

void PanelsSetLockValues1(void)
{
   SetLockValue("PT_TowerControlPanelTemp_Ss",           TYP_8,     1);
   SetLockValue("PT_TowerControlPanelTemp_E",            TYP_8,     1);
   SetLockValue("PT_TowerControlPanelTemp_Th",           TYP_16,    1);
   SetLockValue("PT_TowerControlPanelTemp_Ht",           TYP_32,    1000);
   SetLockValue("PT_TowerControlPanelTemp_S",            TYP_32,    0);
   SetValue("PT_TowerControlPanelTemp_O",                TYP_32,    0);

   SetLockValue("PT_NacelleControlPanelTemp_Ss",         TYP_8,     1);
   SetLockValue("PT_NacelleControlPanelTemp_E",          TYP_8,     1);
   SetLockValue("PT_NacelleControlPanelTemp_Th",         TYP_16,    1);
   SetLockValue("PT_NacelleControlPanelTemp_Ht",         TYP_32,    1000);
   SetLockValue("PT_NacelleControlPanelTemp_S",          TYP_32,    0);
   SetValue("PT_NacelleControlPanelTemp_O",              TYP_32,    0);

   SetLockValue("PT_PowerPanelLeftSideTemp_Ss",          TYP_8,     1);
   SetLockValue("PT_PowerPanelLeftSideTemp_E",           TYP_8,     1);
   SetLockValue("PT_PowerPanelLeftSideTemp_Th",          TYP_16,    1);
   SetLockValue("PT_PowerPanelLeftSideTemp_Ht",          TYP_32,    1000);
   SetLockValue("PT_PowerPanelLeftSideTemp_S",           TYP_32,    0);
   SetValue("PT_PowerPanelLeftSideTemp_O",               TYP_32,    0);

   SetLockValue("PT_PowerPanelRightSideTemp_Ss",         TYP_8,     1);
   SetLockValue("PT_PowerPanelRightSideTemp_E",          TYP_8,     1);
   SetLockValue("PT_PowerPanelRightSideTemp_Th",         TYP_16,    1);
   SetLockValue("PT_PowerPanelRightSideTemp_Ht",         TYP_32,    1000);
   SetLockValue("PT_PowerPanelRightSideTemp_S",          TYP_32,    0);
   SetValue("PT_PowerPanelRightSideTemp_O",              TYP_32,    0);

   SetLockValue("PT_HubControlPanelTemp_Ss",             TYP_8,     1);
   SetLockValue("PT_HubControlPanelTemp_E",              TYP_8,     1);
   SetLockValue("PT_HubControlPanelTemp_Th",             TYP_16,    1);
   SetLockValue("PT_HubControlPanelTemp_Ht",             TYP_32,    2000);
   SetLockValue("PT_HubControlPanelTemp_S",              TYP_32,    0);
   SetValue("PT_HubControlPanelTemp_O",                  TYP_32,    0);

   SetLockValue("DI_PanelsHubHeatingCoolingSystemFB_Ss", TYP_8,     1);
   SetLockValue("DI_PanelsHubHeatingCoolingSystemFB_E",  TYP_8,     1);
   SetValue("DI_PanelsHubHeatingCoolingSystemFB_I",      TYP_8,     0);
   SetLockValue("DI_PanelsHubHeatingCoolingSystemFB_Cm", TYP_8,     1);
   SetLockValue("DI_PanelsHubHeatingCoolingSystemFB_Ht", TYP_32,    1000);

   SetLockValue("DI_Panels_MCCB_StatusBasePanel_Ss",     TYP_8,     1);
   SetLockValue("DI_Panels_MCCB_StatusBasePanel_E",      TYP_8,     1);
   SetValue("DI_Panels_MCCB_StatusBasePanel_I",          TYP_8,     0);
   SetLockValue("DI_Panels_MCCB_StatusBasePanel_Cm",     TYP_8,     1);
   SetLockValue("DI_Panels_MCCB_StatusBasePanel_Ht",     TYP_32,    20);

   SetLockValue("DI_Panels_TowerBasePanelLight_Ss",      TYP_8,     1);
   SetLockValue("DI_Panels_TowerBasePanelLight_E",       TYP_8,     1);
   SetValue("DI_Panels_TowerBasePanelLight_I",           TYP_8,     0);
   SetLockValue("DI_Panels_TowerBasePanelLight_Cm",      TYP_8,     1);
   SetLockValue("DI_Panels_TowerBasePanelLight_Ht",      TYP_32,    1000);
}


STATUS PanelsInitIOAliases()
{
   PanelsIOVars = PanelsIOVars1;
   PanelsIOVarsSize = PanelsIOVars1Size;
   PanelsSetLockValues = &PanelsSetLockValues1;
   return OS_SUCCESS;
}
//-----------------------------------------------------------------------
// AUTOGENERATED END        AUTOGENERATED END        AUTOGENERATED END
//-----------------------------------------------------------------------

#undef AUTOGENERATED_PART

const char PanelsAppDisplayText[] = N_("APPLICATION");
