//*****************************PEPTOOL Header Start******************************
//                                                                               
//                         Copyright © 2015 Mita-Teknik.                         
//This software may only be used with WP4x00 Controllers delivered by Mita-Teknik
//                                                                               
//*******************************************************************************
//                                                                               
// $PEPTOOL version:9.0$                                                         
// $PEPTOOL file version:106$                                                    
//                                                                               
//*******************************************************************************
//                                                                               
// $Date: 2014/04/22 14:02:51 $                                                  
// $Author: MITA\aos $                                                           
// $RCSfile: Pitch.c,v $                                                         
// $Revision: 1.8 $                                                              
//                                                                               
//******************************PEPTOOL Header End*******************************
// OS header files
#include <os_main.h>
// AppLib header files
#include <lib_main.h>
// App header files
#include <turbdef.h>
#include <VarMacros.h>
#include <vardb_macros.h>

#include <main.h>
// Object header file

//#include <Operate\Operate.h>
//#include <Rotor\Rotor.h>

#include <Pitch.h>

#define PHI 3.14159265359

#define AUTOGENERATED_PART
//{
//-----------------------------------------------------------------------
// AUTOGENERATED START     AUTOGENERATED START     AUTOGENERATED START
//-----------------------------------------------------------------------

#define VALIDATE_HASH
char Pitch_copyright[] =
{
   67, 111, 112, 121, 114, 105, 103, 104, 116, 32, 63, 32, 50, 48, 49, 53,
   32, 77, 105, 116, 97, 45, 84, 101, 107, 110, 105, 107, 46, 13, 10, 84,
   104, 105, 115, 32, 115, 111, 102, 116, 119, 97, 114, 101, 32, 109, 97, 121,
   32, 111, 110, 108, 121, 32, 98, 101, 32, 117, 115, 101, 100, 32, 119, 105,
   116, 104, 32, 87, 80, 52, 120, 48, 48, 32, 67, 111, 110, 116, 114, 111,
   108, 108, 101, 114, 115, 32, 100, 101, 108, 105, 118, 101, 114, 101, 100, 32,
   98, 121, 32, 77, 105, 116, 97, 45, 84, 101, 107, 110, 105, 107, 0
};

#define MODULE_NAME "PitchA"

//-----------------------------------------------------------------------
// ALLOCATE MEMORY FOR STRINGS IN VARDB
//-----------------------------------------------------------------------


//-----------------------------------------------------------------------
// DEFINE LOCAL VARIABLES DEFINE LOCAL VARIABLES DEFINE LOCAL VARIABLES
//-----------------------------------------------------------------------

static struct os_db_local LocalVars[] =
{
   VAR_ELEMENT_LOCAL("V_PitchRPMsetpoint",                       TYPE_U32,     PASSWORD_LEVEL_UNLOGGED_IN,        PASSWORD_LEVEL_UNLOGGED_IN,        SCALE_DIV,    100,     UNIT_RPM,           3,   0,               0,               20000,           NULL,  TOTLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_PitchPowersetpoint",                     TYPE_S32,     PASSWORD_LEVEL_UNLOGGED_IN,        PASSWORD_LEVEL_UNLOGGED_IN,        SCALE_DIV,    1000,    UNIT_KWATT,         1,   0,               0,               2500000,         NULL,  TOTLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_e_rpm",                                  TYPE_S32,     PASSWORD_LEVEL_LICENCE_PROGRAMMER, PASSWORD_LEVEL_LICENCE_PROGRAMMER, SCALE_NONE,   0,       UNIT_NONE,          0,   0,               0,               0,               NULL,  TOTLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_e_power",                                TYPE_S32,     PASSWORD_LEVEL_LICENCE_PROGRAMMER, PASSWORD_LEVEL_LICENCE_PROGRAMMER, SCALE_NONE,   0,       UNIT_NONE,          0,   0,               0,               0,               NULL,  TOTLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_e_PID",                                  TYPE_S32,     PASSWORD_LEVEL_LICENCE_PROGRAMMER, PASSWORD_LEVEL_LICENCE_PROGRAMMER, SCALE_NONE,   0,       UNIT_NONE,          0,   0,               0,               0,               NULL,  TOTLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_P_out",                                  TYPE_S32,     PASSWORD_LEVEL_LICENCE_PROGRAMMER, PASSWORD_LEVEL_LICENCE_PROGRAMMER, SCALE_NONE,   0,       UNIT_NONE,          0,   0,               0,               0,               NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_I_out",                                  TYPE_S32,     PASSWORD_LEVEL_LICENCE_PROGRAMMER, PASSWORD_LEVEL_LICENCE_PROGRAMMER, SCALE_NONE,   0,       UNIT_NONE,          0,   0,               0,               0,               NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_D_out",                                  TYPE_S32,     PASSWORD_LEVEL_LICENCE_PROGRAMMER, PASSWORD_LEVEL_LICENCE_PROGRAMMER, SCALE_NONE,   0,       UNIT_NONE,          0,   0,               0,               0,               NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_Blade_Gain",                             TYPE_S32,     PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_SERVICE,            SCALE_NONE,   0,       UNIT_NONE,          0,   0,               0,               0,               NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_PID_out",                                TYPE_S32,     PASSWORD_LEVEL_LICENCE_PROGRAMMER, PASSWORD_LEVEL_LICENCE_PROGRAMMER, SCALE_NONE,   0,       UNIT_NONE,          0,   0,               0,               0,               NULL,  TOTLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_Ripple_out",                             TYPE_S32,     PASSWORD_LEVEL_LICENCE_PROGRAMMER, PASSWORD_LEVEL_LICENCE_PROGRAMMER, SCALE_NONE,   0,       UNIT_NONE,          0,   0,               0,               0,               NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_Zero_out",                               TYPE_S32,     PASSWORD_LEVEL_LICENCE_PROGRAMMER, PASSWORD_LEVEL_LICENCE_PROGRAMMER, SCALE_NONE,   0,       UNIT_NONE,          0,   0,               0,               0,               NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_Setp_out",                               TYPE_S32,     PASSWORD_LEVEL_LICENCE_PROGRAMMER, PASSWORD_LEVEL_LICENCE_PROGRAMMER, SCALE_NONE,   0,       UNIT_NONE,          0,   0,               0,               0,               NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_DebugAngleChange0",                      TYPE_S32,     PASSWORD_LEVEL_LICENCE_PROGRAMMER, PASSWORD_LEVEL_LICENCE_PROGRAMMER, SCALE_DIV,    100,     UNIT_DEGREE,        2,   9500,            -1000,           9500,            NULL,  TOTLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_DebugAngleChange1",                      TYPE_S32,     PASSWORD_LEVEL_LICENCE_PROGRAMMER, PASSWORD_LEVEL_LICENCE_PROGRAMMER, SCALE_DIV,    100,     UNIT_DEGREE,        2,   0,               -1000,           9500,            NULL,  TOTLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_DebugAngleChange2",                      TYPE_S32,     PASSWORD_LEVEL_LICENCE_PROGRAMMER, PASSWORD_LEVEL_LICENCE_PROGRAMMER, SCALE_DIV,    100,     UNIT_DEGREE,        2,   0,               -1000,           9500,            NULL,  TOTLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_DebugAngleChange3",                      TYPE_S32,     PASSWORD_LEVEL_LICENCE_PROGRAMMER, PASSWORD_LEVEL_LICENCE_PROGRAMMER, SCALE_DIV,    100,     UNIT_DEGREE,        2,   0,               -1000,           9500,            NULL,  TOTLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_DebugAngleChange4",                      TYPE_S32,     PASSWORD_LEVEL_LICENCE_PROGRAMMER, PASSWORD_LEVEL_LICENCE_PROGRAMMER, SCALE_DIV,    100,     UNIT_DEGREE,        2,   0,               -1000,           9500,            NULL,  TOTLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_DebugAngleChange5",                      TYPE_S32,     PASSWORD_LEVEL_LICENCE_PROGRAMMER, PASSWORD_LEVEL_LICENCE_PROGRAMMER, SCALE_DIV,    100,     UNIT_DEGREE,        2,   0,               -1000,           9500,            NULL,  TOTLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_DebugAngleChange6",                      TYPE_S32,     PASSWORD_LEVEL_LICENCE_PROGRAMMER, PASSWORD_LEVEL_LICENCE_PROGRAMMER, SCALE_DIV,    100,     UNIT_DEGREE,        2,   0,               -1000,           9500,            NULL,  TOTLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_MinimumAngle",                           TYPE_S32,     PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_SERVICE,            SCALE_DIV,    100,     UNIT_DEGREE,        2,   0,               -1000,           9500,            NULL,  TOTLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_PitchAngleSpeed",                        TYPE_S32,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_DIV,    100,     UNIT_DEGREESPSEC,   2,   0,               -5000,           5000,            NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_PitchAngleOutOpper",                     TYPE_S32,     PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_SERVICE,            SCALE_DIV,    100,     UNIT_DEGREE,        1,   8500,            -1000,           9500,            NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_PID_Mode",                               TYPE_U8,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   0,               0,               1,               NULL,  TOTLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_PitchNotchFilterOutput",                 TYPE_S32,     PASSWORD_LEVEL_ADMINISTRATOR,      PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   0,               S32_MIN,         S32_MAX,         NULL,  TOTLOG_ENABLE),
};

//-----------------------------------------------------------------------
// DEFINE PARAMETERS        DEFINE PARAMETERS        DEFINE PARAMETERS
//-----------------------------------------------------------------------

static struct os_db_parameter ParameterVars[] =
{
   VAR_ELEMENT_PARAMETER("P_RPMSpanPos",                             TYPE_S32,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_DIV,    100,     UNIT_RPM,           2,   100,             0,               1000,            NULL  ),
   VAR_ELEMENT_PARAMETER("P_RPMSpanNeg",                             TYPE_S32,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_DIV,    100,     UNIT_RPM,           2,   45,              0,               1000,            NULL  ),
   VAR_ELEMENT_PARAMETER("P_PowerSpanPos",                           TYPE_S32,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_NONE,   0,       UNIT_KWATT,         0,   50,              0,               10000,           NULL  ),
   VAR_ELEMENT_PARAMETER("P_PowerSpanNeg",                           TYPE_S32,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_NONE,   0,       UNIT_KWATT,         0,   50,              0,               10000,           NULL  ),
   VAR_ELEMENT_PARAMETER("P_PIDkp",                                  TYPE_S32,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_DIV,    10000,   UNIT_NONE,          4,   1370,            0,               10000,           NULL  ),
   VAR_ELEMENT_PARAMETER("P_PIDki",                                  TYPE_S32,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_DIV,    10000,   UNIT_NONE,          4,   1,               0,               10000,           NULL  ),
   VAR_ELEMENT_PARAMETER("P_PIDkd",                                  TYPE_S32,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_DIV,    10000,   UNIT_NONE,          4,   3200,            0,               10000,           NULL  ),
   VAR_ELEMENT_PARAMETER("P_PIDkd_Neg",                              TYPE_S32,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_DIV,    10000,   UNIT_NONE,          4,   2200,            0,               10000,           NULL  ),
   VAR_ELEMENT_PARAMETER("P_PIDkpFw",                                TYPE_S32,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_DIV,    10000,   UNIT_NONE,          4,   1500,            0,               10000,           NULL  ),
   VAR_ELEMENT_PARAMETER("P_PIDkiFw",                                TYPE_S32,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_DIV,    10000,   UNIT_NONE,          4,   0,               0,               10000,           NULL  ),
   VAR_ELEMENT_PARAMETER("P_PIDkdFw",                                TYPE_S32,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_DIV,    10000,   UNIT_NONE,          4,   520,             0,               10000,           NULL  ),
   VAR_ELEMENT_PARAMETER("P_PosWindup",                              TYPE_S32,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_NONE,   0,       UNIT_NONE,          0,   1900,            0,               2000,            NULL  ),
   VAR_ELEMENT_PARAMETER("P_NegWindup",                              TYPE_S32,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_NONE,   0,       UNIT_NONE,          0,   -1900,           -2000,           0,               NULL  ),
   VAR_ELEMENT_PARAMETER("P_MaxPitchRPM",                            TYPE_U32,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_DIV,    10,      UNIT_PCT,           1,   80,              1,               1000,            NULL  ),
   VAR_ELEMENT_PARAMETER("P_HighRPMPitchSpeedFactor",                TYPE_U32,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_DIV,    100,     UNIT_NONE,          2,   300,             10,              1000,            NULL  ),
   VAR_ELEMENT_PARAMETER("P_MaxPitchRate",                           TYPE_S32,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_DIV,    100,     UNIT_DEGREESPSEC,   1,   300,             0,               1100,            NULL  ),
   VAR_ELEMENT_PARAMETER("P_MinPitchRate",                           TYPE_S32,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_DIV,    100,     UNIT_DEGREESPSEC,   1,   -300,            -1100,           0,               NULL  ),
   VAR_ELEMENT_PARAMETER("P_UseRealPower",                           TYPE_U8,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_NONE,   0,       UNIT_NONE,          0,   2,               0,               3,               NULL  ),
   VAR_ELEMENT_PARAMETER("P_BladeGainBelowTwoDeg",                   TYPE_S32,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_NONE,   0,       UNIT_NONE,          0,   10000,           1000,            20000,           NULL  ),
   VAR_ELEMENT_PARAMETER("P_BladeGainBelowFourDeg",                  TYPE_S32,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_NONE,   0,       UNIT_NONE,          0,   10000,           1000,            20000,           NULL  ),
   VAR_ELEMENT_PARAMETER("P_BladeGainBelowSixDeg",                   TYPE_S32,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_NONE,   0,       UNIT_NONE,          0,   8500,            1000,            20000,           NULL  ),
   VAR_ELEMENT_PARAMETER("P_BladeGainBelowEightDeg",                 TYPE_S32,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_NONE,   0,       UNIT_NONE,          0,   7000,            1000,            20000,           NULL  ),
   VAR_ELEMENT_PARAMETER("P_BladeGainBelowTenDeg",                   TYPE_S32,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_NONE,   0,       UNIT_NONE,          0,   5700,            1000,            20000,           NULL  ),
   VAR_ELEMENT_PARAMETER("P_BladeGainBelowTvelveDeg",                TYPE_S32,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_NONE,   0,       UNIT_NONE,          0,   5000,            1000,            20000,           NULL  ),
   VAR_ELEMENT_PARAMETER("P_BladeGainBelowFourTeenDeg",              TYPE_S32,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_NONE,   0,       UNIT_NONE,          0,   4400,            1000,            20000,           NULL  ),
   VAR_ELEMENT_PARAMETER("P_BladeGainBelowSixTeenDeg",               TYPE_S32,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_NONE,   0,       UNIT_NONE,          0,   3900,            1000,            20000,           NULL  ),
   VAR_ELEMENT_PARAMETER("P_BladeGainBelowEightTeenDeg",             TYPE_S32,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_NONE,   0,       UNIT_NONE,          0,   3500,            1000,            20000,           NULL  ),
   VAR_ELEMENT_PARAMETER("P_BladeGainBelowTwentyDeg",                TYPE_S32,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_NONE,   0,       UNIT_NONE,          0,   3100,            1000,            20000,           NULL  ),
   VAR_ELEMENT_PARAMETER("P_BladeGainBelowTwentyFiveDeg",            TYPE_S32,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_NONE,   0,       UNIT_NONE,          0,   2600,            1000,            20000,           NULL  ),
   VAR_ELEMENT_PARAMETER("P_BladeGainBelowThirtyDeg",                TYPE_S32,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_NONE,   0,       UNIT_NONE,          0,   2600,            1000,            20000,           NULL  ),
   VAR_ELEMENT_PARAMETER("P_HighRPMLimit",                           TYPE_U8,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_DIV,    10,      UNIT_PCT,           1,   10,              0,               100,             NULL  ),
   VAR_ELEMENT_PARAMETER("P_PID_Sel_Man",                            TYPE_U8,      PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_SERVICE,            SCALE_NONE,   0,       UNIT_NONE,          0,   1,               0,               1,               NULL  ),
   VAR_ELEMENT_PARAMETER("P_RippleDamperEnable",                     TYPE_U8,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_NONE,   0,       UNIT_NONE,          0,   1,               0,               1,               NULL  ),
   VAR_ELEMENT_PARAMETER("P_ZeroPointDamperEnable",                  TYPE_U8,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_NONE,   0,       UNIT_NONE,          0,   1,               0,               1,               NULL  ),
   VAR_ELEMENT_PARAMETER("P_PitchNotchFrq",                          TYPE_U32,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_DIV,    1000,    UNIT_HERTZ,         3,   408,             1,               10000,           NULL  ),
   VAR_ELEMENT_PARAMETER("P_PitchNotchDampingNom",                   TYPE_U32,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_DIV,    1000,    UNIT_NONE,          3,   10,              1,               10000,           NULL  ),
   VAR_ELEMENT_PARAMETER("P_PitchNotchDampingDenom",                 TYPE_U32,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_DIV,    1000,    UNIT_NONE,          3,   100,             1,               10000,           NULL  ),
   VAR_ELEMENT_PARAMETER("P_PitchNotchON",                           TYPE_U8,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_NONE,   0,       UNIT_NONE,          0,   0,               0,               1,               NULL  ),
};

//-----------------------------------------------------------------------
// DEFINE BACKUPS            DEFINE BACKUPS            DEFINE BACKUPS
//-----------------------------------------------------------------------

//----------------------------------------------------------------------------------
// DEFINE VAR ARRAYS            DEFINE VAR ARRAYS            DEFINE VAR ARRAYS
//----------------------------------------------------------------------------------
char Pitch_initialValues[] =
{
   186, 9, 60, 181, 114, 33, 178, 26, 146, 198, 214, 130, 99, 152, 71, 138,
   130, 248, 53, 36, 132, 53, 252, 175, 202, 85, 10, 201, 86, 247, 109, 164,
   0
};

//-----------------------------------------------------------------------
// CREATE DATABASE VARS   CREATE DATABASE VARS   CREATE DATABASE VARS
//-----------------------------------------------------------------------

static STATUS CreateVarDbVars(void)
{
   STATUS Status;
   size_t ErrorEntry;

   Status = OS_VarDB_CreateLocals(LocalVars, sizeof(LocalVars)/sizeof(LocalVars[0]), &ErrorEntry, AppLocalParameterPosition());
   if (Status != 0)
   {
      AppSystemLog(ERR_7, MODULE_NAME"CrVL: %d,%d", Status, ErrorEntry);
      return ERR_7;
   }

   Status = OS_VarDB_CreateParameters(ParameterVars, sizeof(ParameterVars)/sizeof(ParameterVars[0]), &ErrorEntry, AppExportParameterPosition());
   if (Status != 0)
   {
      AppSystemLog(ERR_7, MODULE_NAME"CrVXP: %d,%d", Status, ErrorEntry);
      return ERR_7;
   }

   return OS_SUCCESS;
}

#define CREATE_VARDB_VARS

//-----------------------------------------------------------------------
// CREATE IO VARIABLES     CREATE IO VARIABLES     CREATE IO VARIABLES
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// ALIASES                       ALIASES                       ALIASES
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// INPUT                          INPUT                          INPUT
//-----------------------------------------------------------------------

// Create local variable
#define MODUL_INPUTS
static U32 V_PitchRPMsetpoint = 0;
static S32 V_PitchPowersetpoint = 0;
static S32 V_GridRealPower1Sec = 0;
static S32 V_PitchAngle = 0;
static S32 AI_GridRealPower = 0;
static S32 V_PitchPositionLimit = 0;
static U32 V_PitchSpeedLimit = 0;
static U8 V_PitchMode = 0;
static U8 V_PID_Mode = 0;
static U8 P_HighRPMLimit = 0;
static U8 P_PID_Sel_Man = 0;
static U8 V_GeneratorProducing = 0;
static U8 P_RippleDamperEnable = 0;
static U8 P_ZeroPointDamperEnable = 0;
static U32 P_PitchNotchFrq = 0;
static U32 P_PitchNotchDampingNom = 0;
static U32 P_PitchNotchDampingDenom = 0;
static U8 P_PitchNotchON = 0;
static U32 V_ControllerRpm = 0;

//-----------------------------------------------------------------------
static struct ModulInOut ModulInputs[] =
{
   {"V_PitchRPMsetpoint",                       &V_PitchRPMsetpoint,                       sizeof(V_PitchRPMsetpoint),                       },
   {"V_PitchPowersetpoint",                     &V_PitchPowersetpoint,                     sizeof(V_PitchPowersetpoint),                     },
   {"V_GridRealPower1Sec",                      &V_GridRealPower1Sec,                      sizeof(V_GridRealPower1Sec),                      },
   {"V_PitchAngle",                             &V_PitchAngle,                             sizeof(V_PitchAngle),                             },
   {"AI_GridRealPower",                         &AI_GridRealPower,                         sizeof(AI_GridRealPower),                         },
   {"V_PitchPositionLimit",                     &V_PitchPositionLimit,                     sizeof(V_PitchPositionLimit),                     },
   {"V_PitchSpeedLimit",                        &V_PitchSpeedLimit,                        sizeof(V_PitchSpeedLimit),                        },
   {"V_PitchMode",                              &V_PitchMode,                              sizeof(V_PitchMode),                              },
   {"V_PID_Mode",                               &V_PID_Mode,                               sizeof(V_PID_Mode),                               },
   {"P_HighRPMLimit",                           &P_HighRPMLimit,                           sizeof(P_HighRPMLimit),                           },
   {"P_PID_Sel_Man",                            &P_PID_Sel_Man,                            sizeof(P_PID_Sel_Man),                            },
   {"V_GeneratorProducing",                     &V_GeneratorProducing,                     sizeof(V_GeneratorProducing),                     },
   {"P_RippleDamperEnable",                     &P_RippleDamperEnable,                     sizeof(P_RippleDamperEnable),                     },
   {"P_ZeroPointDamperEnable",                  &P_ZeroPointDamperEnable,                  sizeof(P_ZeroPointDamperEnable),                  },
   {"P_PitchNotchFrq",                          &P_PitchNotchFrq,                          sizeof(P_PitchNotchFrq),                          },
   {"P_PitchNotchDampingNom",                   &P_PitchNotchDampingNom,                   sizeof(P_PitchNotchDampingNom),                   },
   {"P_PitchNotchDampingDenom",                 &P_PitchNotchDampingDenom,                 sizeof(P_PitchNotchDampingDenom),                 },
   {"P_PitchNotchON",                           &P_PitchNotchON,                           sizeof(P_PitchNotchON),                           },
   {"V_ControllerRpm",                          &V_ControllerRpm,                          sizeof(V_ControllerRpm),                          },
};

//-----------------------------------------------------------------------
// Check variable type
static STATUS VarsReadReturnStatus;
static type_t ReadVarType = TYPE_NONE;
static void VarsReadTypeCheck(void)
{
   (void)VarsReadReturnStatus;
   (void)ReadVarType;
   VERIFY_INPUT_REF_ID(U32,       ModulInputs[0].Name,                      ModulInputs[0].Id)
   VERIFY_INPUT_REF_ID(S32,       ModulInputs[1].Name,                      ModulInputs[1].Id)
   VERIFY_INPUT_REF_ID(S32,       ModulInputs[2].Name,                      ModulInputs[2].Id)
   VERIFY_INPUT_REF_ID(S32,       ModulInputs[3].Name,                      ModulInputs[3].Id)
   VERIFY_INPUT_REF_ID(S32,       ModulInputs[4].Name,                      ModulInputs[4].Id)
   VERIFY_INPUT_REF_ID(S32,       ModulInputs[5].Name,                      ModulInputs[5].Id)
   VERIFY_INPUT_REF_ID(U32,       ModulInputs[6].Name,                      ModulInputs[6].Id)
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[7].Name,                      ModulInputs[7].Id)
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[8].Name,                      ModulInputs[8].Id)
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[9].Name,                      ModulInputs[9].Id)
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[10].Name,                     ModulInputs[10].Id)
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[11].Name,                     ModulInputs[11].Id)
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[12].Name,                     ModulInputs[12].Id)
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[13].Name,                     ModulInputs[13].Id)
   VERIFY_INPUT_REF_ID(U32,       ModulInputs[14].Name,                     ModulInputs[14].Id)
   VERIFY_INPUT_REF_ID(U32,       ModulInputs[15].Name,                     ModulInputs[15].Id)
   VERIFY_INPUT_REF_ID(U32,       ModulInputs[16].Name,                     ModulInputs[16].Id)
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[17].Name,                     ModulInputs[17].Id)
   VERIFY_INPUT_REF_ID(U32,       ModulInputs[18].Name,                     ModulInputs[18].Id)
}

#undef MODUL_INPUTS
#define MODUL_INPUTS_SIZE (sizeof(ModulInputs)/sizeof(ModulInputs[0]))

//------------------------------------------------------------------------------------------
// READ/WRITE VARDB ARRAY      READ/WRITE VARDB ARRAY      READ/WRATE VARDB ARRAY
//------------------------------------------------------------------------------------------


//-----------------------------------------------------------------------
// PARAMETER                    PARAMETER                    PARAMETER
//-----------------------------------------------------------------------

// Create local variable
#define MODUL_PARAMETERS
static S32 P_PowerSpanPos = 0;
static S32 P_PowerSpanNeg = 0;
static S32 P_PIDkp = 0;
static S32 P_PIDki = 0;
static S32 P_PIDkd = 0;
static S32 P_PIDkd_Neg = 0;
static S32 P_PIDkpFw = 0;
static S32 P_PIDkiFw = 0;
static S32 P_PIDkdFw = 0;
static S32 P_PosWindup = 0;
static S32 P_NegWindup = 0;
static S32 P_BladeGainBelowTwoDeg = 0;
static S32 P_BladeGainBelowFourDeg = 0;
static S32 P_BladeGainBelowSixDeg = 0;
static S32 P_BladeGainBelowEightDeg = 0;
static S32 P_BladeGainBelowTenDeg = 0;
static S32 P_BladeGainBelowTvelveDeg = 0;
static S32 P_BladeGainBelowFourTeenDeg = 0;
static S32 P_BladeGainBelowSixTeenDeg = 0;
static S32 P_BladeGainBelowEightTeenDeg = 0;
static S32 P_BladeGainBelowTwentyDeg = 0;
static S32 P_BladeGainBelowTwentyFiveDeg = 0;
static S32 P_BladeGainBelowThirtyDeg = 0;
static U32 P_MaxPitchRPM = 0;
static U32 P_HighRPMPitchSpeedFactor = 0;
static S32 P_MaxPitchRate = 0;
static S32 P_MinPitchRate = 0;
static U8 P_UseRealPower = 0;
static S32 P_RPMSpanPos = 0;
static S32 P_RPMSpanNeg = 0;
static S32 P_OperGeneratorRpm = 0;



//-----------------------------------------------------------------------
static struct ModulInOut ModulParameters0[] =
{
   {"P_PowerSpanPos",                           &P_PowerSpanPos,                           sizeof(P_PowerSpanPos),                           },
   {"P_PowerSpanNeg",                           &P_PowerSpanNeg,                           sizeof(P_PowerSpanNeg),                           },
   {"P_PIDkp",                                  &P_PIDkp,                                  sizeof(P_PIDkp),                                  },
   {"P_PIDki",                                  &P_PIDki,                                  sizeof(P_PIDki),                                  },
   {"P_PIDkd",                                  &P_PIDkd,                                  sizeof(P_PIDkd),                                  },
   {"P_PIDkd_Neg",                              &P_PIDkd_Neg,                              sizeof(P_PIDkd_Neg),                              },
   {"P_PIDkpFw",                                &P_PIDkpFw,                                sizeof(P_PIDkpFw),                                },
   {"P_PIDkiFw",                                &P_PIDkiFw,                                sizeof(P_PIDkiFw),                                },
   {"P_PIDkdFw",                                &P_PIDkdFw,                                sizeof(P_PIDkdFw),                                },
   {"P_PosWindup",                              &P_PosWindup,                              sizeof(P_PosWindup),                              },
   {"P_NegWindup",                              &P_NegWindup,                              sizeof(P_NegWindup),                              },
   {"P_BladeGainBelowTwoDeg",                   &P_BladeGainBelowTwoDeg,                   sizeof(P_BladeGainBelowTwoDeg),                   },
   {"P_BladeGainBelowFourDeg",                  &P_BladeGainBelowFourDeg,                  sizeof(P_BladeGainBelowFourDeg),                  },
   {"P_BladeGainBelowSixDeg",                   &P_BladeGainBelowSixDeg,                   sizeof(P_BladeGainBelowSixDeg),                   },
   {"P_BladeGainBelowEightDeg",                 &P_BladeGainBelowEightDeg,                 sizeof(P_BladeGainBelowEightDeg),                 },
   {"P_BladeGainBelowTenDeg",                   &P_BladeGainBelowTenDeg,                   sizeof(P_BladeGainBelowTenDeg),                   },
   {"P_BladeGainBelowTvelveDeg",                &P_BladeGainBelowTvelveDeg,                sizeof(P_BladeGainBelowTvelveDeg),                },
   {"P_BladeGainBelowFourTeenDeg",              &P_BladeGainBelowFourTeenDeg,              sizeof(P_BladeGainBelowFourTeenDeg),              },
   {"P_BladeGainBelowSixTeenDeg",               &P_BladeGainBelowSixTeenDeg,               sizeof(P_BladeGainBelowSixTeenDeg),               },
   {"P_BladeGainBelowEightTeenDeg",             &P_BladeGainBelowEightTeenDeg,             sizeof(P_BladeGainBelowEightTeenDeg),             },
   {"P_BladeGainBelowTwentyDeg",                &P_BladeGainBelowTwentyDeg,                sizeof(P_BladeGainBelowTwentyDeg),                },
   {"P_BladeGainBelowTwentyFiveDeg",            &P_BladeGainBelowTwentyFiveDeg,            sizeof(P_BladeGainBelowTwentyFiveDeg),            },
   {"P_BladeGainBelowThirtyDeg",                &P_BladeGainBelowThirtyDeg,                sizeof(P_BladeGainBelowThirtyDeg),                },
   {"P_MaxPitchRPM",                            &P_MaxPitchRPM,                            sizeof(P_MaxPitchRPM),                            },
   {"P_HighRPMPitchSpeedFactor",                &P_HighRPMPitchSpeedFactor,                sizeof(P_HighRPMPitchSpeedFactor),                },
   {"P_MaxPitchRate",                           &P_MaxPitchRate,                           sizeof(P_MaxPitchRate),                           },
   {"P_MinPitchRate",                           &P_MinPitchRate,                           sizeof(P_MinPitchRate),                           },
   {"P_UseRealPower",                           &P_UseRealPower,                           sizeof(P_UseRealPower),                           },
   {"P_RPMSpanPos",                             &P_RPMSpanPos,                             sizeof(P_RPMSpanPos),                             },
   {"P_RPMSpanNeg",                             &P_RPMSpanNeg,                             sizeof(P_RPMSpanNeg),                             },
   {"P_OperGeneratorRpm",                       &P_OperGeneratorRpm,                       sizeof(P_OperGeneratorRpm),                       },

};
static struct ModulInOut* ModulParameters[] =
{
   ModulParameters0,
};

//-----------------------------------------------------------------------
// Check variable type
static STATUS ParaVarsReadReturnStatus;
static type_t ParaReadVarType = TYPE_NONE;
static void ParaVarsReadTypeCheck(void)
{
   (void)ParaVarsReadReturnStatus;
   (void)ParaReadVarType;
}

#undef MODUL_PARAMETERS

#define PARAMETERS_GROUPS_SIZE        1
#define GENERAL_GROUP                 0
#define MODUL_PARAMETERS_TOTAL_SIZE   31
static SUBSCRIPTION ParaSubscription[MODUL_PARAMETERS_TOTAL_SIZE];
static U8 ReadParameters[PARAMETERS_GROUPS_SIZE];
static U8 ParametersChanged[PARAMETERS_GROUPS_SIZE];
static UNSIGNED GroupsIndexes[PARAMETERS_GROUPS_SIZE];
static int ParaGroupsSizes[PARAMETERS_GROUPS_SIZE] = { 31 };
static STATUS VarDbUpdateParameter(varid_t VariableId, void* Message, U16 Length, UNSIGNED paraGroupIndex, UNSIGNED Ref2)
{
   ReadParameters[paraGroupIndex] = 1;
   ParametersChanged[paraGroupIndex] = 1;
   return OS_SUCCESS;
}
static STATUS ReadParametersFunc(int paraGroupIndex)
{
   STATUS LocalStatus;
   // Check inputdata
   if (sizeof(ModulParameters[paraGroupIndex]) == 0)
   {
      AppSystemLog(ERR_4, MODULE_NAME"Group %d ModuleParameters = 0", paraGroupIndex);
      return ERR_4;
   }
   // Read inputdata
   LocalStatus = OS_ReadVariables(ModulParameters[paraGroupIndex], ParaGroupsSizes[paraGroupIndex]);
   if (LocalStatus != 0)
   {
      AppSystemLog(11, "LocalStatus: %d", LocalStatus);
      AppSystemLog(ERR_4, MODULE_NAME"ReadParErr: group=%d element=%d elementpointer=0x%x", paraGroupIndex, LocalStatus, &ModulParameters[LocalStatus]);
      return ERR_4;
   }
   return OS_SUCCESS;
}


//-----------------------------------------------------------------------
// READ VARS FROM VARDB    READ VARS FROM VARDB    READ VARS FROM VARDB
//-----------------------------------------------------------------------

static STATUS InputReferenceRoutine(U8 ModuleState)
{
   STATUS LocalStatus = 0;

   // Read input references
   if (ModuleState >= APP_INIT3)
   {
      // Check inputdata
      if (sizeof(ModulInputs) == 0)
      {
         AppSystemLog(ERR_4, MODULE_NAME"ModuleInputs = 0");
         return ERR_4;
      }
      // Read inputdata
      LocalStatus = OS_ReadVariables(ModulInputs, MODUL_INPUTS_SIZE);
      if (LocalStatus != 0)
      {
         AppSystemLog(ERR_4, MODULE_NAME"ReadVErr: element=%d elementpointer=0x%x", LocalStatus, &ModulInputs[LocalStatus]);
         return ERR_4;
      }
   }
   // Read input parameters
   if (ModuleState == APP_INIT3)
   {
      static size_t ParaCounter = 0;
      int groupIndex;
      for (groupIndex = 0; groupIndex < PARAMETERS_GROUPS_SIZE; groupIndex++)
      {
         ParametersChanged[groupIndex] = 1;
         ReadParameters[groupIndex] = 1;
         GroupsIndexes[groupIndex] = groupIndex;

         // Check inputdata
         if (sizeof(ModulParameters[groupIndex]) == 0)
         {
            AppSystemLog(ERR_4, MODULE_NAME"Group = %d ModuleParameters = 0", groupIndex);
            return ERR_4;
         }
         // Read inputdata
         LocalStatus = OS_ReadVariables(ModulParameters[groupIndex], ParaGroupsSizes[groupIndex]);
         if (LocalStatus != 0)
         {
            AppSystemLog(ERR_4, MODULE_NAME"ReadVParaErr: group=%d element=%d elementpointer=0x%x", groupIndex, LocalStatus, &ModulParameters[groupIndex][LocalStatus]);
            return ERR_4;
         }
         int paraIndex;
         for (paraIndex = 0; paraIndex < ParaGroupsSizes[groupIndex]; paraIndex++)
         {
            LocalStatus = OS_SubHandl_SubscribeFunctionWithRef(&ParaSubscription[ParaCounter], 1, &ModulParameters[groupIndex][paraIndex].Id, &GroupsIndexes[groupIndex], &GroupsIndexes[groupIndex], VarDbUpdateParameter);
            ParaCounter++;
            if (LocalStatus != 0)
            {
               AppSystemLog(ERR_4, MODULE_NAME"Subscribe Parameter: group=%d element=%d elementpointer=0x%x", groupIndex, LocalStatus, &ModulParameters[LocalStatus]);
               return ERR_4;
            }
         }
      }
   }
   if (ModuleState == APP_RUN)
   {
      int groupIndex;
      for (groupIndex = 0; groupIndex < PARAMETERS_GROUPS_SIZE; groupIndex++)
      {
         if (ReadParameters[groupIndex])
         {
            LocalStatus = ReadParametersFunc(groupIndex);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
            ReadParameters[groupIndex] = 0;
         }
      }
   }

   return 0;
}

#define READ_VARS

//-----------------------------------------------------------------------
// OUTPUT                         OUTPUT                         OUTPUT
//-----------------------------------------------------------------------

// Create local variable
#define MODUL_OUTPUTS
static S32 V_e_rpm = 0;
static S32 V_e_power = 0;
static S32 V_e_PID = 0;
static S32 V_PID_out = 0;
static S32 V_P_out = 0;
static S32 V_I_out = 0;
static S32 V_D_out = 0;
static S32 V_Blade_Gain = 0;
static S32 V_Ripple_out = 0;
static S32 V_Zero_out = 0;
static S32 V_Setp_out = 0;
static S32 V_PitchAngleSetPoint = 0;
static S32 V_DebugAngleChange0 = 0;
static S32 V_DebugAngleChange1 = 0;
static S32 V_DebugAngleChange2 = 0;
static S32 V_DebugAngleChange3 = 0;
static S32 V_DebugAngleChange4 = 0;
static S32 V_DebugAngleChange5 = 0;
static S32 V_DebugAngleChange6 = 0;
static S32 V_PitchAngleSpeed = 0;
static S32 V_PitchAngleOutOpper = 0;
static S32 V_MinimumAngle = 0;
static S32 V_PitchNotchFilterOutput = 0;


//-----------------------------------------------------------------------
static struct ModulInOut ModulOutputs[] =
{
   {"V_e_rpm",                                  &V_e_rpm,                                  sizeof(V_e_rpm),                                  },
   {"V_e_power",                                &V_e_power,                                sizeof(V_e_power),                                },
   {"V_e_PID",                                  &V_e_PID,                                  sizeof(V_e_PID),                                  },
   {"V_PID_out",                                &V_PID_out,                                sizeof(V_PID_out),                                },
   {"V_P_out",                                  &V_P_out,                                  sizeof(V_P_out),                                  },
   {"V_I_out",                                  &V_I_out,                                  sizeof(V_I_out),                                  },
   {"V_D_out",                                  &V_D_out,                                  sizeof(V_D_out),                                  },
   {"V_Blade_Gain",                             &V_Blade_Gain,                             sizeof(V_Blade_Gain),                             },
   {"V_Ripple_out",                             &V_Ripple_out,                             sizeof(V_Ripple_out),                             },
   {"V_Zero_out",                               &V_Zero_out,                               sizeof(V_Zero_out),                               },
   {"V_Setp_out",                               &V_Setp_out,                               sizeof(V_Setp_out),                               },
   {"V_PitchAngleSetPoint",                     &V_PitchAngleSetPoint,                     sizeof(V_PitchAngleSetPoint),                     },
   {"V_DebugAngleChange0",                      &V_DebugAngleChange0,                      sizeof(V_DebugAngleChange0),                      },
   {"V_DebugAngleChange1",                      &V_DebugAngleChange1,                      sizeof(V_DebugAngleChange1),                      },
   {"V_DebugAngleChange2",                      &V_DebugAngleChange2,                      sizeof(V_DebugAngleChange2),                      },
   {"V_DebugAngleChange3",                      &V_DebugAngleChange3,                      sizeof(V_DebugAngleChange3),                      },
   {"V_DebugAngleChange4",                      &V_DebugAngleChange4,                      sizeof(V_DebugAngleChange4),                      },
   {"V_DebugAngleChange5",                      &V_DebugAngleChange5,                      sizeof(V_DebugAngleChange5),                      },
   {"V_DebugAngleChange6",                      &V_DebugAngleChange6,                      sizeof(V_DebugAngleChange6),                      },
   {"V_PitchAngleSpeed",                        &V_PitchAngleSpeed,                        sizeof(V_PitchAngleSpeed),                        },
   {"V_PitchAngleOutOpper",                     &V_PitchAngleOutOpper,                     sizeof(V_PitchAngleOutOpper),                     },
   {"V_MinimumAngle",                           &V_MinimumAngle,                           sizeof(V_MinimumAngle),                           },
   {"V_PitchNotchFilterOutput",                 &V_PitchNotchFilterOutput,                 sizeof(V_PitchNotchFilterOutput),                 },
};

//-----------------------------------------------------------------------
// Check variable type
static STATUS VarsWriteReturnStatus;
static type_t WriteVarType = TYPE_NONE;
static void VarsWriteTypeCheck(void)
{
   (void)VarsWriteReturnStatus;
   (void)WriteVarType;
   VERIFY_OUTPUT_REF_ID(S32,       ModulOutputs[0].Name,                     ModulOutputs[0].Id,                       0)
   VERIFY_OUTPUT_REF_ID(S32,       ModulOutputs[1].Name,                     ModulOutputs[1].Id,                       0)
   VERIFY_OUTPUT_REF_ID(S32,       ModulOutputs[2].Name,                     ModulOutputs[2].Id,                       0)
   VERIFY_OUTPUT_REF_ID(S32,       ModulOutputs[3].Name,                     ModulOutputs[3].Id,                       0)
   VERIFY_OUTPUT_REF_ID(S32,       ModulOutputs[4].Name,                     ModulOutputs[4].Id,                       0)
   VERIFY_OUTPUT_REF_ID(S32,       ModulOutputs[5].Name,                     ModulOutputs[5].Id,                       0)
   VERIFY_OUTPUT_REF_ID(S32,       ModulOutputs[6].Name,                     ModulOutputs[6].Id,                       0)
   VERIFY_OUTPUT_REF_ID(S32,       ModulOutputs[7].Name,                     ModulOutputs[7].Id,                       0)
   VERIFY_OUTPUT_REF_ID(S32,       ModulOutputs[8].Name,                     ModulOutputs[8].Id,                       0)
   VERIFY_OUTPUT_REF_ID(S32,       ModulOutputs[9].Name,                     ModulOutputs[9].Id,                       0)
   VERIFY_OUTPUT_REF_ID(S32,       ModulOutputs[10].Name,                    ModulOutputs[10].Id,                      0)
   VERIFY_OUTPUT_REF_ID(S32,       ModulOutputs[11].Name,                    ModulOutputs[11].Id,                      0)
   VERIFY_OUTPUT_REF_ID(S32,       ModulOutputs[12].Name,                    ModulOutputs[12].Id,                      0)
   VERIFY_OUTPUT_REF_ID(S32,       ModulOutputs[13].Name,                    ModulOutputs[13].Id,                      0)
   VERIFY_OUTPUT_REF_ID(S32,       ModulOutputs[14].Name,                    ModulOutputs[14].Id,                      0)
   VERIFY_OUTPUT_REF_ID(S32,       ModulOutputs[15].Name,                    ModulOutputs[15].Id,                      0)
   VERIFY_OUTPUT_REF_ID(S32,       ModulOutputs[16].Name,                    ModulOutputs[16].Id,                      0)
   VERIFY_OUTPUT_REF_ID(S32,       ModulOutputs[17].Name,                    ModulOutputs[17].Id,                      0)
   VERIFY_OUTPUT_REF_ID(S32,       ModulOutputs[18].Name,                    ModulOutputs[18].Id,                      0)
   VERIFY_OUTPUT_REF_ID(S32,       ModulOutputs[19].Name,                    ModulOutputs[19].Id,                      0)
   VERIFY_OUTPUT_REF_ID(S32,       ModulOutputs[20].Name,                    ModulOutputs[20].Id,                      0)
   VERIFY_OUTPUT_REF_ID(S32,       ModulOutputs[21].Name,                    ModulOutputs[21].Id,                      0)
   VERIFY_OUTPUT_REF_ID(S32,       ModulOutputs[22].Name,                    ModulOutputs[22].Id,                      0)
}

#undef MODUL_OUTPUTS
#define MODUL_OUTPUTS_SIZE (sizeof(ModulOutputs)/sizeof(ModulOutputs[0]))

//-----------------------------------------------------------------------
// WRITE VARS TO VARDB     WRITE VARS TO VARDB     WRITE VARS TO VARDB
//-----------------------------------------------------------------------

static STATUS InitOutputVars(void)
{
   STATUS LocalStatus;
   // Read outputdata
   LocalStatus = OS_ReadVariables(ModulOutputs, MODUL_OUTPUTS_SIZE);
   if (LocalStatus != 0)
   {
      AppSystemLog(ERR_4, MODULE_NAME"InitErr: element=%d elementpointer=0x%x", LocalStatus, &ModulOutputs[LocalStatus]);
      return ERR_4;
   }
   return OS_SUCCESS;
}
static STATUS OutputReferenceRoutine(U8 ModuleState)
{
   STATUS LocalStatus = 0;
   // Write Outputdata
   LocalStatus = OS_WriteVariablesConditional(ModulOutputs, MODUL_OUTPUTS_SIZE);
   if (LocalStatus != 0)
   {
      AppSystemLog(ERR_5, MODULE_NAME"WriteVErr: element=%d elementpointer=0x%x", LocalStatus, &ModulOutputs[LocalStatus]);
      return ERR_5;
   }
   return 0;
}

#define WRITE_VARS

//-----------------------------------------------------------------------
// VERIFY VARIABLES CREATION                 VERIFY VARIABLES CREATION
//-----------------------------------------------------------------------

static STATUS LocalIoCheck(void)
{
   // Check if input variables exist.
   STATUS LocalStatus;

   LocalStatus = OS_DoesVariablesExist(ModulInputs, MODUL_INPUTS_SIZE);
   if (LocalStatus != 0)
   {
      AppSystemLog(ERR_1, MODULE_NAME"InputErr: %d", LocalStatus);
      AppSystemLog(ERR_1, "Name: %s", ModulInputs[LocalStatus-1].Name);
      return ERR_1;
   }
   (void)VarsReadTypeCheck();

   int groupIndex;
   for (groupIndex = 0; groupIndex < PARAMETERS_GROUPS_SIZE; groupIndex++)
   {
      LocalStatus = OS_DoesVariablesExist(ModulParameters[groupIndex], ParaGroupsSizes[groupIndex]);
      if (LocalStatus != 0)
      {
         AppSystemLog(ERR_3, MODULE_NAME"ParameterErr: %d Group:%d", LocalStatus, groupIndex);
         AppSystemLog(ERR_3, "Name: %s", ModulParameters[groupIndex][LocalStatus-1].Name);
         return ERR_3;
      }
   }
   (void)ParaVarsReadTypeCheck();

   LocalStatus = OS_DoesVariablesExist(ModulOutputs, MODUL_OUTPUTS_SIZE);
   if (LocalStatus != 0)
   {
      AppSystemLog(ERR_2, MODULE_NAME"OutputErr: %d", LocalStatus);
      AppSystemLog(ERR_2, "Name: %s", ModulOutputs[LocalStatus-1].Name);
      return ERR_2;
   }
   (void)VarsWriteTypeCheck();

   return OS_SUCCESS;
}

#define VERIFY_VARIABLES

//-----------------------------------------------------------------------
// ALLOCATE MEMORY FOR SUMMATIONS        ALLOCATE MEMORY FOR SUMMATIONS
//-----------------------------------------------------------------------


//-----------------------------------------------------------------------
// SUMMATIONS                  SUMMATIONS                  SUMMATIONS
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// DEFINE MENUS               DEFINE MENUS               DEFINE MENUS
//-----------------------------------------------------------------------



// Menu line and link to local menu
//-----------------------------------------------------------------------
static struct line_struct M_ObjMainLinkToLocalMenu[] =
{
   MENU_ELEMENT_LINE_LINK("Pitch",                             PASSWORD_LEVEL_END_CUSTOMER,        "M_ObjMain",                        "G_Pitch"),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_ObjMainMenu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_ObjMain",                        PASSWORD_LEVEL_END_CUSTOMER),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_ObjMainMenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("PITCH",                             PASSWORD_LEVEL_END_CUSTOMER,        "M_"APP_ID"AppMain",                "G_"APP_ID"App"),
   MENU_ELEMENT_LINE_VARRO("RPM setpoint",                     PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_PitchRPMsetpoint",                         LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Power setpoint",                   PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_PitchPowersetpoint",                       LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Pitch angle",                      PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_PitchAngle",                               LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_LINK("Status",                            PASSWORD_LEVEL_END_CUSTOMER,        "M_Status",                         "G_Pitch"),
   MENU_ELEMENT_LINE_LINK("Parameter",                         PASSWORD_LEVEL_END_CUSTOMER,        "M_Parameter",                      "G_Pitch"),
   MENU_ELEMENT_LINE_LINK("Service",                           PASSWORD_LEVEL_SERVICE,             "M_Service",                        "G_Pitch"),
   MENU_ELEMENT_LINE_LINK("Programmer",                        PASSWORD_LEVEL_LICENCE_PROGRAMMER,  "M_Programmer",                     "G_Pitch"),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_StatusMenu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_Status",                         PASSWORD_LEVEL_END_CUSTOMER),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_StatusMenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("STATUS",                            PASSWORD_LEVEL_END_CUSTOMER,        "M_ObjMain",                        "G_Pitch"),
   MENU_ELEMENT_LINE_VARRO("Pitch angle",                      PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_PitchAngle",                               LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Pitch speed",                      PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_PitchAngleSpeed",                          LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("RPM setpoint",                     PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_PitchRPMsetpoint",                         LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Power setpoint",                   PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_PitchPowersetpoint",                       LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("PID input mode",                   PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_PID_Mode",                                 LINE_FORMAT_NONE),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_ParameterMenu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_Parameter",                      PASSWORD_LEVEL_END_CUSTOMER),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_ParameterMenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("PARAMETER",                         PASSWORD_LEVEL_END_CUSTOMER,        "M_ObjMain",                        "G_Pitch"),
   MENU_ELEMENT_LINE_VARRW("RPM >span< +",                     PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_RPMSpanPos",                               LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("RPM >span< -",                     PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_RPMSpanNeg",                               LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Power >span< +",                   PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_PowerSpanPos",                             LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Power >span< -",                   PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_PowerSpanNeg",                             LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Use real power",                   PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_UseRealPower",                             LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("PID Kp(FreeWheel)",                PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_PIDkpFw",                                  LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("PID Ki(FreeWheel)",                PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_PIDkiFw",                                  LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("PID Kd(FreeWheel)",                PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_PIDkdFw",                                  LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("PID Kp(Grid Connected)",           PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_PIDkp",                                    LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("PID Ki(Grid Connected)",           PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_PIDki",                                    LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("PID Kd + (Grid Connected)",        PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_PIDkd",                                    LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("PID Kd - (Grid Connected)",        PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_PIDkd_Neg",                                LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Pos. Windup*1e3",                  PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_PosWindup",                                LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Neg. Windup*1e3",                  PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_NegWindup",                                LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Max pitch RPM",                    PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_MaxPitchRPM",                              LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("High RPM gain factor",             PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_HighRPMPitchSpeedFactor",                  LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("High RPM Limit",                   PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_HighRPMLimit",                             LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Max pitch speed",                  PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_MaxPitchRate",                             LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Min pitch speed",                  PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_MinPitchRate",                             LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Enable Ripple Damper",             PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_RippleDamperEnable",                       LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Enable Zero Cross Ripple Damper",  PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_ZeroPointDamperEnable",                    LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Blade gain < 2 deg",               PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_BladeGainBelowTwoDeg",                     LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Blade gain < 4 deg",               PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_BladeGainBelowFourDeg",                    LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Blade gain < 6 deg",               PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_BladeGainBelowSixDeg",                     LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Blade gain < 8 deg",               PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_BladeGainBelowEightDeg",                   LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Blade gain < 10 deg",              PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_BladeGainBelowTenDeg",                     LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Blade gain < 12 deg",              PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_BladeGainBelowTvelveDeg",                  LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Blade gain < 14 deg",              PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_BladeGainBelowFourTeenDeg",                LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Blade gain < 16 deg",              PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_BladeGainBelowSixTeenDeg",                 LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Blade gain < 18 deg",              PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_BladeGainBelowEightTeenDeg",               LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Blade gain < 20 deg",              PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_BladeGainBelowTwentyDeg",                  LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Blade gain < 25 deg",              PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_BladeGainBelowTwentyFiveDeg",              LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Blade gain > 25 deg",              PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_BladeGainBelowThirtyDeg",                  LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Notch filter enable",              PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_PitchNotchON",                             LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Notch filter Resonance frequency", PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_PitchNotchFrq",                            LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Notch filter Damping Nominator",   PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_PitchNotchDampingNom",                     LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Notch filter Damping Denominator", PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_PitchNotchDampingDenom",                   LINE_FORMAT_NONE),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_ServiceMenu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_Service",                        PASSWORD_LEVEL_SERVICE),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_ServiceMenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("SERVICE",                           PASSWORD_LEVEL_SERVICE,             "M_ObjMain",                        "G_Pitch"),
   MENU_ELEMENT_LINE_VARRW("Man. PID Input Selector(0=Auto,1=rpm)", PASSWORD_LEVEL_SERVICE,             (char*)"P_PID_Sel_Man",                              LINE_FORMAT_NONE),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_ProgrammerMenu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_Programmer",                     PASSWORD_LEVEL_LICENCE_PROGRAMMER),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_ProgrammerMenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("PROGRAMMER",                        PASSWORD_LEVEL_LICENCE_PROGRAMMER,  "M_ObjMain",                        "G_Pitch"),
   MENU_ELEMENT_LINE_VARRO("Rotor rpm",                        PASSWORD_LEVEL_LICENCE_PROGRAMMER,  (char*)"V_GEN_EncoderRpm",                           LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Power",                            PASSWORD_LEVEL_LICENCE_PROGRAMMER,  (char*)"V_GridRealPower1Sec",                        LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("e_rpm",                            PASSWORD_LEVEL_LICENCE_PROGRAMMER,  (char*)"V_e_rpm",                                    LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("e_power",                          PASSWORD_LEVEL_LICENCE_PROGRAMMER,  (char*)"V_e_power",                                  LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("e_PID",                            PASSWORD_LEVEL_LICENCE_PROGRAMMER,  (char*)"V_e_PID",                                    LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Noutch filter output",             PASSWORD_LEVEL_MITA_PROGRAMMER,     (char*)"V_PitchNotchFilterOutput",                   LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("P_out",                            PASSWORD_LEVEL_LICENCE_PROGRAMMER,  (char*)"V_P_out",                                    LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("I_out",                            PASSWORD_LEVEL_LICENCE_PROGRAMMER,  (char*)"V_I_out",                                    LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("D_out",                            PASSWORD_LEVEL_LICENCE_PROGRAMMER,  (char*)"V_D_out",                                    LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("PID_out",                          PASSWORD_LEVEL_LICENCE_PROGRAMMER,  (char*)"V_PID_out",                                  LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Ripple_out",                       PASSWORD_LEVEL_LICENCE_PROGRAMMER,  (char*)"V_Ripple_out",                               LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Zero_out",                         PASSWORD_LEVEL_LICENCE_PROGRAMMER,  (char*)"V_Zero_out",                                 LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Setp_out",                         PASSWORD_LEVEL_LICENCE_PROGRAMMER,  (char*)"V_Setp_out",                                 LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Angle setpoint",                   PASSWORD_LEVEL_LICENCE_PROGRAMMER,  (char*)"V_PitchAngleSetPoint",                       LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Debug angle change",               PASSWORD_LEVEL_LICENCE_PROGRAMMER,  (char*)"V_DebugAngleChange0",                        LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Debug angle change",               PASSWORD_LEVEL_LICENCE_PROGRAMMER,  (char*)"V_DebugAngleChange1",                        LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Debug angle change",               PASSWORD_LEVEL_LICENCE_PROGRAMMER,  (char*)"V_DebugAngleChange2",                        LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Debug angle change",               PASSWORD_LEVEL_LICENCE_PROGRAMMER,  (char*)"V_DebugAngleChange3",                        LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Debug angle change",               PASSWORD_LEVEL_LICENCE_PROGRAMMER,  (char*)"V_DebugAngleChange4",                        LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Debug angle change",               PASSWORD_LEVEL_LICENCE_PROGRAMMER,  (char*)"V_DebugAngleChange5",                        LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Debug angle change",               PASSWORD_LEVEL_LICENCE_PROGRAMMER,  (char*)"V_DebugAngleChange6",                        LINE_FORMAT_NONE),
};
// Creating parameters for multiplexed categories
//-----------------------------------------------------------------------
static struct multiplexed_info_struct M_ObjMainMultiplexedCategoriesParameters[] =
{0};

//-----------------------------------------------------------------------
// CREATE MENUS               CREATE MENUS               CREATE MENUS
//-----------------------------------------------------------------------

// Memory reservation
//-----------------------------------------------------------------------
static struct menu_group_struct ObjGroup[1];

// Creating the menus
//-----------------------------------------------------------------------
STATUS PitchMenuAppInit(U8 ModuleState, OS_MEMORY_POOL* pPool)
{
   STATUS Status;

   if (ModuleState == APP_INIT1)
   {
      /* Create application group */
      Status = OS_CreateMenuGroup(ObjGroup, M_ObjMainLinkToLocalMenu[0].LinkGroup);
      STATUS_LINE_VAR_RETURN_VALUE(Status);
   }

   Status = CreateAndInitializeMenu(ModuleState,
                                    M_ObjMainMenuLines[0].LinkGroup,
                                    M_ObjMainMenuLines[0].LinkName,
                                    ELEMENT(M_ObjMainLinkToLocalMenu),
                                    M_ObjMainLinkToLocalMenu[0].LinkGroup,
                                    ELEMENT(M_ObjMainMenu),
                                    M_ObjMainLinkToLocalMenu[0].LinkName,
                                    ELEMENT(M_ObjMainMenuLines),
                                    pPool,
                                    M_ObjMainMultiplexedCategoriesParameters);
   STATUS_LINE_VAR_RETURN_VALUE(Status);

   Status = CreateAndInitializeMenu(ModuleState,
                                    M_StatusMenuLines[0].LinkGroup,
                                    M_StatusMenuLines[0].LinkName,
                                    NULL,
                                    0,
                                    M_ObjMainMenuLines[4].LinkGroup,
                                    ELEMENT(M_StatusMenu),
                                    M_ObjMainMenuLines[4].LinkName,
                                    ELEMENT(M_StatusMenuLines),
                                    pPool,
                                    M_ObjMainMultiplexedCategoriesParameters);
   STATUS_LINE_VAR_RETURN_VALUE(Status);

   Status = CreateAndInitializeMenu(ModuleState,
                                    M_ParameterMenuLines[0].LinkGroup,
                                    M_ParameterMenuLines[0].LinkName,
                                    NULL,
                                    0,
                                    M_ObjMainMenuLines[5].LinkGroup,
                                    ELEMENT(M_ParameterMenu),
                                    M_ObjMainMenuLines[5].LinkName,
                                    ELEMENT(M_ParameterMenuLines),
                                    pPool,
                                    M_ObjMainMultiplexedCategoriesParameters);
   STATUS_LINE_VAR_RETURN_VALUE(Status);

   Status = CreateAndInitializeMenu(ModuleState,
                                    M_ServiceMenuLines[0].LinkGroup,
                                    M_ServiceMenuLines[0].LinkName,
                                    NULL,
                                    0,
                                    M_ObjMainMenuLines[6].LinkGroup,
                                    ELEMENT(M_ServiceMenu),
                                    M_ObjMainMenuLines[6].LinkName,
                                    ELEMENT(M_ServiceMenuLines),
                                    pPool,
                                    M_ObjMainMultiplexedCategoriesParameters);
   STATUS_LINE_VAR_RETURN_VALUE(Status);

   Status = CreateAndInitializeMenu(ModuleState,
                                    M_ProgrammerMenuLines[0].LinkGroup,
                                    M_ProgrammerMenuLines[0].LinkName,
                                    NULL,
                                    0,
                                    M_ObjMainMenuLines[7].LinkGroup,
                                    ELEMENT(M_ProgrammerMenu),
                                    M_ObjMainMenuLines[7].LinkName,
                                    ELEMENT(M_ProgrammerMenuLines),
                                    pPool,
                                    M_ObjMainMultiplexedCategoriesParameters);
   STATUS_LINE_VAR_RETURN_VALUE(Status);

   return OS_SUCCESS;
}

#define CREATE_MENU

//-----------------------------------------------------------------------
//               BUTTONS FUNCTIONS FORWARD DECLARATIONS
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// BUTTONS                       BUTTONS                      BUTTONS
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
//             SET/RESET FUNCTIONS FORWARD DECLARATIONS
//-----------------------------------------------------------------------
//-----------------------------------------------------------------------
// STATUSCODES                 STATUSCODES                 STATUSCODES
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// MODIFIABLE                  MODIFIABLE                   MODIFIABLE
//-----------------------------------------------------------------------

extern const char PitchAppGroupName[];
extern const char PitchAppMenuName[];

static void Init_Structures_From_Conf_File(void)
{
   M_ObjMainMenuLines[0].LinkName = (char*)PitchAppMenuName;
   M_ObjMainMenuLines[0].LinkGroup = (char*)PitchAppGroupName;
}

//-----------------------------------------------------------------------
// AUTOGENERATED END        AUTOGENERATED END        AUTOGENERATED END
//-----------------------------------------------------------------------
//}

#undef AUTOGENERATED_PART

//-----------------------------------------------------------------------
// USER DEFINITIONS         USER DEFINITIONS         USER DEFINITIONS
//-----------------------------------------------------------------------


#define PI 3.14159265359
//-----------------------------------------------------------------------
// SET/RESET FUNCTIONS    SET/RESET FUNCTIONS    SET/RESET FUNCTIONS
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// DRIVER FUNCTION         DRIVER FUNCTION         DRIVER FUNCTION
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// INIT                   INIT                     INIT
//-----------------------------------------------------------------------
struct pNotch
{
   U8 OK;
   F32 W1;
   F32 W2;
   F32 D1;
   F32 D2;
   F32 DT;
   U8 Init;
   F32 Num[3];
   F32 Den[3];
   F32 Work[4];
};


//-----------------------------------------------------------------------
// CONTROL                CONTROL                 CONTROL
//-----------------------------------------------------------------------

struct pNotch PitchNotchStruct={0};

void PitchNotchParaUpdate(void)
{
      PitchNotchStruct.W1 =2*PI*(F32)P_PitchNotchFrq/1000.0F;      // Do not miss the 2*pi !!!
      PitchNotchStruct.W2 =2*PI*(F32)P_PitchNotchFrq/1000.0F;      // (W2 = W1)
      PitchNotchStruct.D1 =(F32)P_PitchNotchDampingNom/1000.0F;
      PitchNotchStruct.D2 =(F32)P_PitchNotchDampingDenom/1000.0F;
      PitchNotchStruct.DT =0.02;                      // Sample time 20 mS
      PitchNotchStruct.OK =P_PitchNotchON;               // Flag for notch filter on/off
      PitchNotchStruct.Init=1;
}

static F32 PitchNotch (F32 InputPF)
{
   F32 rWT1, rWT2;
   F32 OutputPF;
   U8 i;
   static F32 K  = 0;
   static F32 Kn = 0;
   static F32 K0 = 0;
   static F32 K1 = 0;
   static F32 K2 = 0;
   static F32 K3 = 0;
   static F32 K4 = 0;

   if (PitchNotchStruct.OK)
   {
      if (PitchNotchStruct.Init == 1)
      {
         rWT1 = PitchNotchStruct.W1 * PitchNotchStruct.DT;
         PitchNotchStruct.Num[0] = 4.0F + 4.0F*PitchNotchStruct.D1*rWT1 + rWT1*rWT1;
         PitchNotchStruct.Num[1] =-8.0F + 2.0F*rWT1*rWT1;
         PitchNotchStruct.Num[2] = 4.0F - 4.0F*PitchNotchStruct.D1*rWT1 + rWT1*rWT1;
         rWT2 = PitchNotchStruct.W2 * PitchNotchStruct.DT;
         PitchNotchStruct.Den[0] = 4.0F + 4.0F*PitchNotchStruct.D2*rWT2 + rWT2*rWT2;
         PitchNotchStruct.Den[1] =-8.0F + 2.0F*rWT2*rWT2;
         PitchNotchStruct.Den[2] = 4.0F - 4.0F*PitchNotchStruct.D2*rWT2 + rWT2*rWT2;

         //For unity DC gain:
         for (i=0; i<=2; i++)
         {
            PitchNotchStruct.Num[i] *= (PitchNotchStruct.W2 * PitchNotchStruct.W2);
            PitchNotchStruct.Den[i] *= (PitchNotchStruct.W1 * PitchNotchStruct.W1);
         }
         PitchNotchStruct.Work[0] = InputPF;
         PitchNotchStruct.Work[1] = InputPF;
         PitchNotchStruct.Work[2] = InputPF;
         PitchNotchStruct.Work[3] = InputPF;

         if (PitchNotchStruct.Den[0] != 0)
            K = 1 / PitchNotchStruct.Den[0];
         else
            K = 0;

         Kn = -K;
         K0 = PitchNotchStruct.Num[0] * K;
         K1 = PitchNotchStruct.Num[1] * K;
         K2 = PitchNotchStruct.Num[2] * K;
         K3 = PitchNotchStruct.Den[1] * Kn;
         K4 = PitchNotchStruct.Den[2] * Kn;
         PitchNotchStruct.Init = 0;
      }
      OutputPF = K0 * InputPF + K1 * PitchNotchStruct.Work[0] + K2 * PitchNotchStruct.Work[1] + K3 * PitchNotchStruct.Work[2] + K4 * PitchNotchStruct.Work[3];

      PitchNotchStruct.Work[3] = PitchNotchStruct.Work[2];
      PitchNotchStruct.Work[2] = OutputPF;
      PitchNotchStruct.Work[1] = PitchNotchStruct.Work[0];
      PitchNotchStruct.Work[0] = InputPF;
      return(OutputPF);
   }
   else

      return(InputPF);
}


static void CalcPitchAngle(void)
{
   static U8 DelayMs = 0;
   static S32 PrevPitchAngle;
   S32 PitchAngleDiff;

   DelayMs += 20;

   if ( DelayMs >= 120)
   {
      PitchAngleDiff = V_PitchAngle - PrevPitchAngle;
      V_PitchAngleSpeed = (PitchAngleDiff * 1000) / 120;
      PrevPitchAngle = V_PitchAngle;
      DelayMs = 0;
   }
}

//-----------------------------------------------------------------------


static void RPM_error(void)
{
   S32 RpmError;

   RpmError = (S32)V_ControllerRpm - (S32)V_PitchRPMsetpoint;

	if(RpmError >= 0)
	{
		if(P_RPMSpanPos != 0)
		{
			V_e_rpm = 10000 * RpmError;
			V_e_rpm = V_e_rpm / P_RPMSpanPos;
		}

      if(V_e_rpm > 10000)
      {
         V_e_rpm = 10000;
      }
	}
	else
	{
		if(P_RPMSpanNeg != 0)
		{
			V_e_rpm = 10000 * RpmError;
			V_e_rpm = V_e_rpm / P_RPMSpanNeg;
		}

      if(V_e_rpm < -10000)
      {
         V_e_rpm = -10000;
      }
	}
}

static void Power_error(void)
{
   S32 PowerError = 0;
   static S32 SmoothRealPower[5];
   if(P_PID_Sel_Man || V_PID_Mode)
   {
	   V_e_power = 0;
   }
   else
   {
	   if(P_UseRealPower)
	   {
			S32 Power;
			   if(P_UseRealPower == 1)
			   {
			SmoothRealPower[4] = SmoothRealPower[3];
			SmoothRealPower[3] = SmoothRealPower[2];
			SmoothRealPower[2] = SmoothRealPower[1];
			SmoothRealPower[1] = SmoothRealPower[0];
			SmoothRealPower[0] = AI_GridRealPower;

			Power = (SmoothRealPower[4] + SmoothRealPower[3]  + SmoothRealPower[2] + SmoothRealPower[1] + SmoothRealPower[0]) / 5;
			PowerError = ((S32)Power / 1000) - ((S32)V_PitchPowersetpoint / 1000);
			   }
			   else
			   if(P_UseRealPower == 2)
			   {
					SmoothRealPower[1] = SmoothRealPower[0];
					SmoothRealPower[0] = AI_GridRealPower;

					Power = (SmoothRealPower[1] + SmoothRealPower[0]) / 2;
					PowerError = ((S32)Power / 1000) - ((S32)V_PitchPowersetpoint / 1000);
			   }
			   else
			   if(P_UseRealPower == 3)
			   {
					PowerError = ((S32)AI_GridRealPower / 1000) - ((S32)V_PitchPowersetpoint / 1000);
			   }
	   }
	   else
	   {
	   PowerError = ((S32)V_GridRealPower1Sec / 1000) - ((S32)V_PitchPowersetpoint / 1000);
	   }

		if(PowerError >= 0)
		{
			if(P_PowerSpanPos != 0)
			{
			 V_e_power = 10000 * PowerError;
			 V_e_power = V_e_power / P_PowerSpanPos;
			}

		  if(V_e_power > 10000)
		  {
			 V_e_power = 10000;
		  }
		}
		else
		{
			if(P_PowerSpanNeg != 0)
			{
			 V_e_power = 10000 * PowerError;
			 V_e_power = V_e_power / P_PowerSpanNeg;
			}

		  if(V_e_power < -10000)
		  {
			 V_e_power = -10000;
		  }
		}
   }
}

static void HighInSel(void)
{
   //Notch Filter Initialize
   static U32 PNotchFrq, PNotchNom, PNotchDenom;
   static U8 PNotchOn;

   if( (V_e_rpm) > (V_e_power) )
	{
		V_e_PID = V_e_rpm;
	}
	else
	{
		V_e_PID = V_e_power;
	}
	if ( P_PID_Sel_Man == 1 || V_PID_Mode)
	{
		 V_e_PID = V_e_rpm;
	}

   if (  (PNotchFrq  != P_PitchNotchFrq) ||
		 (PNotchNom  != P_PitchNotchDampingNom) ||
		 (PNotchDenom!= P_PitchNotchDampingDenom) ||
		 (PNotchOn   != P_PitchNotchON))
   {
	  PNotchFrq   = P_PitchNotchFrq;
	  PNotchNom   = P_PitchNotchDampingNom;
	  PNotchDenom = P_PitchNotchDampingDenom;
	  PNotchOn    = P_PitchNotchON;
	  PitchNotchParaUpdate();
   }

   //Call notchfilter
   F32 NotchReturn = 0;
   NotchReturn = PitchNotch((F32)V_e_PID/10000.0F) * 10000.0F;
   V_PitchNotchFilterOutput = NotchReturn;
}

static void SetMinimumPitchAngle(S16 MinAngle)
{
   if (abs(V_MinimumAngle - MinAngle) > 100) /* more than 0.1 degree ramp it. */
   {
      if (V_MinimumAngle < MinAngle)
      {
         V_MinimumAngle += 1000/50; /* ramp it by 1 deg/s*/
      }
      else
      {
         V_MinimumAngle -= 1000/50; /* ramp it by 1 deg/s*/
      }
   }
   else
   {
      V_MinimumAngle = MinAngle;
   }
}

static void SetPitchController(void)
{

   S32 MaxPitchChange;

   MaxPitchChange = V_PitchSpeedLimit / 50;

   SetMinimumPitchAngle(V_PitchPositionLimit);

   if ( MaxPitchChange < 0 )
   {
      MaxPitchChange = 0 - MaxPitchChange ;
   }

   switch ( V_PitchMode )
   {
      case CTRL_AUTO :
    	 V_PitchAngleOutOpper = V_PitchAngle;     // - Update V_PitchAngleOutOpper to PitchAngle
         break;

      case CTRL_MANUAL :
      case CTRL_ESTOP :
         if ( V_PitchPositionLimit < ( V_PitchAngleOutOpper - MaxPitchChange ) )
         {
            V_PitchAngleOutOpper -= MaxPitchChange;
         }
         else
         {
            if ( V_PitchPositionLimit > ( V_PitchAngleOutOpper + MaxPitchChange ) )
            {
               V_PitchAngleOutOpper += MaxPitchChange;
            }
            else
            {
               V_PitchAngleOutOpper = V_PitchPositionLimit;
            }
         }
     	 break;

      default :
         AppDebugLog(0, "SetPitchController(%u)", V_PitchMode );
         break;
   }
}

static void PID(void)
{
   static F32 e1            = 0;
   static F32 eAvr1         = 0;
   static F32 eAvr2         = 0;
   static F32 eAvr3         = 0;
   static F32 eAvr4         = 0;
   static F32 eAvr5         = 0;
   static F32 eAvr6         = 0;
   static F32 eAvr7         = 0;
   static F32 eAvr8         = 0;
   static F32 eAvr9         = 0;
   static F32 eAvr10        = 0;
   static F32 sumerror      = 0;
   static S8  Sign 			 = 0;
   static S8 DeltaDelay		 = 0;
   F32 newsumerror			 = 0;
   static F32 deltae;

   static U8  Old_V_PitchMode = 0;

	//  *************************************************************************
	//		I-error
	//  *************************************************************************


   // *************************************************************************
   //   Recalculation of I-term in case the PID controller not being active
   //   when rated speed is reached
   // *************************************************************************
   if(V_PitchNotchFilterOutput > 0)
   {
		if(Sign != 1) sumerror = 0;
		Sign = 1;
   }
   else
   {
	if(Sign != -1) sumerror = 0;
		Sign = -1;
   }

   if ( Old_V_PitchMode != CTRL_AUTO && V_PitchMode == CTRL_AUTO )
   {                                         // When PitchMode changes state from "MANUAL" or "ESTOP"   =>   "AUTO"
      e1             = 0;                        // - ResetPID
      eAvr1          = 0;
      eAvr2          = 0;
      eAvr3          = 0;
      eAvr4          = 0;
      eAvr5          = 0;
      eAvr6          = 0;
      eAvr7          = 0;
      eAvr8          = 0;
      eAvr9          = 0;
      eAvr10         = 0;
      sumerror       = 0;
	  Sign           = 0;
   }
   else
   {
      newsumerror = sumerror + V_PitchNotchFilterOutput*0.02; /* multiplyed by samle time*/
   }
   Old_V_PitchMode = V_PitchMode;            // store PitchMode state for next time

   // anti-windup
   if (newsumerror > (P_PosWindup*1000))
      newsumerror = (P_PosWindup*1000);
   if (newsumerror < (P_NegWindup*1000))
      newsumerror = (P_NegWindup*1000);

	sumerror = newsumerror;

	//  *************************************************************************
	//		P-error & Filter.
	//  *************************************************************************


	//  *************************************************************************
	//		D-error
	//  *************************************************************************
   // Averaged errors (3 samples)

   e1 = V_PitchNotchFilterOutput;

   if(++DeltaDelay >= 5)
   {
	   DeltaDelay = 0;
       eAvr10     = eAvr9;
       eAvr9      = eAvr8;
       eAvr8      = eAvr7;
   	   eAvr7      = eAvr6;
   	   eAvr6      = eAvr5;
   	   eAvr5      = eAvr4;
   	   eAvr4      = eAvr3;
   	   eAvr3      = eAvr2;
   	   eAvr2      = eAvr1;
       eAvr1      = V_PitchNotchFilterOutput;

	   deltae = (V_PitchNotchFilterOutput - eAvr10) * 5;             //delta is calculated as PID error difference over the last second, and is updated every 100ms.
   }
   // Unaveraged errors

	//  *************************************************************************
	//		PID-error
	//  *************************************************************************
   if ( V_GeneratorProducing ) // Connected to Grid // (DI_BypassFB)
	{
		V_Blade_Gain =  10000;
		     if(V_PitchAngle <  200) V_Blade_Gain =  P_BladeGainBelowTwoDeg;
		else if(V_PitchAngle <  400) V_Blade_Gain =  P_BladeGainBelowFourDeg;
		else if(V_PitchAngle <  600) V_Blade_Gain =  P_BladeGainBelowSixDeg;
		else if(V_PitchAngle <  800) V_Blade_Gain =  P_BladeGainBelowEightDeg;
		else if(V_PitchAngle < 1000) V_Blade_Gain =  P_BladeGainBelowTenDeg;
		else if(V_PitchAngle < 1200) V_Blade_Gain =  P_BladeGainBelowTvelveDeg;
		else if(V_PitchAngle < 1400) V_Blade_Gain =  P_BladeGainBelowFourTeenDeg;
		else if(V_PitchAngle < 1600) V_Blade_Gain =  P_BladeGainBelowSixTeenDeg;
		else if(V_PitchAngle < 1800) V_Blade_Gain =  P_BladeGainBelowEightTeenDeg;
		else if(V_PitchAngle < 2000) V_Blade_Gain =  P_BladeGainBelowTwentyDeg;
		else if(V_PitchAngle < 2500) V_Blade_Gain =  P_BladeGainBelowTwentyFiveDeg;
		else V_Blade_Gain =  P_BladeGainBelowThirtyDeg;

		V_P_out = (P_PIDkp * V_PitchNotchFilterOutput) / 10000;
		V_I_out = (P_PIDki * newsumerror) / 10000;

		if (deltae > 0)
			V_D_out = (P_PIDkd * deltae) / 10000;
		else
			V_D_out = (P_PIDkd_Neg * deltae) / 10000;

		V_PID_out = (S32)(((S64)(V_P_out + V_I_out + V_D_out) * (S64)V_Blade_Gain) / 10000);
	}
	else
	{
		V_P_out = (P_PIDkpFw * V_PitchNotchFilterOutput) / 10000;
		V_I_out = (P_PIDkiFw * newsumerror) / 10000;
		V_D_out = (P_PIDkdFw * deltae) / 10000;
		V_PID_out = (V_P_out + V_I_out + V_D_out);

	}

	if(V_PID_out > 10000)
    {
		V_PID_out = 10000;
	}

	if(V_PID_out < -10000)
    {
		V_PID_out = -10000;
	}
}

static void RippleDamp(void)
{
	static S32 PID_out[4] = {0,0,0,0};

    if (P_RippleDamperEnable)
    {
    	PID_out[3] = PID_out[2];
    	PID_out[2] = PID_out[1];
    	PID_out[1] = PID_out[0];
    	PID_out[0] = V_PID_out;

    	V_Ripple_out = (PID_out[0] + PID_out[1] + PID_out[2] + PID_out[3]) / 4;
    }
    else
    {
    	V_Ripple_out = V_PID_out;
    }
}

static void ZeroPointDamp(void)
{
	static S32 Old_Ripple_out = 0;
	static S32 Ripple_Diff = 0;
	static S32 DivisionFactor = 5;

	if(P_ZeroPointDamperEnable)
	{
		Ripple_Diff = V_Ripple_out - Old_Ripple_out;

		if( (abs(Ripple_Diff) > abs(V_Ripple_out)) || (abs(Ripple_Diff) > abs(Old_Ripple_out)))
		{
			DivisionFactor = 5;
		}

		if(DivisionFactor > 1)
		{
			DivisionFactor--;
		}

		V_Zero_out = V_Ripple_out / DivisionFactor;

	  	Old_Ripple_out = V_Ripple_out;
	}
	else
	{
		V_Zero_out = V_Ripple_out;
	}

}

static void HighRpm(void)
{
	static S32 PitchSpeed;
	S32 MaxPitchRPM;
	MaxPitchRPM = ( ( (1000 + (P_MaxPitchRPM)) * P_OperGeneratorRpm) / 1000 );
    if(V_ControllerRpm > MaxPitchRPM )
	{
      PitchSpeed = P_HighRPMPitchSpeedFactor * ((V_ControllerRpm - MaxPitchRPM)^2);
      PitchSpeed = PitchSpeed / 100;
	}
    else
    {
      PitchSpeed = 0;
    }

	V_Setp_out = PitchSpeed;
}

static void SpeedToAngle(void)
{
    static S32 First = 1;
	static S32 TempSetP = 0;
	static S32 OldTempSetP = 0;
    static S32 OldAngleOut;
    static S32 TempSetPError = 0;
    if ( First )
    {
      OldAngleOut = V_PitchAngleSetPoint;
      First = 0;
    }

    V_DebugAngleChange1 = TempSetP;

    TempSetP = ( V_Zero_out * P_MaxPitchRate ) / 10000;

    V_DebugAngleChange2 = TempSetP;

    TempSetP = TempSetP + V_Setp_out;

    V_DebugAngleChange3 = TempSetP;

    if ( TempSetP > ( P_MaxPitchRate ) )
	{
      TempSetP = ( P_MaxPitchRate );
	}

    V_DebugAngleChange4 = TempSetP;

    if ( TempSetP < ( P_MinPitchRate ) )
	{
      TempSetP = ( P_MinPitchRate );
	}

    V_DebugAngleChange5 = TempSetP;

    if ( V_ControllerRpm > ( ( (1000 + (P_HighRPMLimit)) * P_OperGeneratorRpm ) / 1000 ) && TempSetP < OldTempSetP )
	{
      TempSetP = OldTempSetP;
	}

    V_DebugAngleChange6 = TempSetP;

    if ( V_PitchMode == CTRL_AUTO )                     // If PitchMode = AUTO
    {                                                   // Enabled PID
	    TempSetPError += TempSetP % 50;
  	    V_DebugAngleChange0 = TempSetPError;
	    if ( TempSetPError >= 50)
	    {
           OldAngleOut++;
		     TempSetPError -= 50;
	    }
	    else
	        if ( TempSetPError <= -50)
	        {
              OldAngleOut--;
		        TempSetPError += 50;
	        }

       V_PitchAngleSetPoint = OldAngleOut + TempSetP / 50;           //(TempSetP * 0.02) / 10000 => (TempSetP * 2) / 1000000
       if ( V_PitchAngleSetPoint > 8500 )
	    {
           V_PitchAngleSetPoint = 8500;
	    }
       if ( V_PitchAngleSetPoint < V_MinimumAngle )
	    {
           V_PitchAngleSetPoint = V_MinimumAngle;
	    }
	}
	else                                               // If PitchMode = MANUAL or ESTOP
	{                                                  // Disabled PID
      V_PitchAngleSetPoint = V_PitchAngleOutOpper;
	}

   OldAngleOut = V_PitchAngleSetPoint;
   OldTempSetP = TempSetP;
}

static STATUS LocalCtrl(void)
{
   RPM_error();
   Power_error();
   HighInSel();
   SetPitchController();
   PID();
   RippleDamp();
   ZeroPointDamp();
   HighRpm();
   SpeedToAngle();

   CalcPitchAngle();

   return OS_SUCCESS;
}

//-----------------------------------------------------------------------
// MAIN CALL             MAIN CALL               MAIN CALL
//-----------------------------------------------------------------------

STATUS Pitch(U8 ModuleState, OS_MEMORY_POOL *MemPool, U32 *Arg3)
{
   STATUS LocalStatus = 0;


   if(ModuleState == APP_INIT1)
   {
      LocalStatus = OS_ValidateAPI(OS_SERVICES->APIVersionMajor,
                                   OS_SERVICES->APIVersionMinor,
                                   OS_LinkTime,
                                   ReleaseTag,
                                   __MODULE__
                                   );
      if ( OS_SUCCESS != LocalStatus )
      {
         return LocalStatus;
      }
   }
#ifdef READ_VARS
   // Read inputdata
   LocalStatus = InputReferenceRoutine(ModuleState);
   STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif
#ifdef CREATE_MENU
   if (ModuleState == APP_INIT1 || ModuleState == APP_INIT4)
   {
      LocalStatus = PitchMenuAppInit(ModuleState, MemPool);
      STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
   }
#endif
   switch(ModuleState)
   {
      case APP_RUN :
      {
         #ifdef FUNCTION_BLOCKS_PRE_LOCAL_CONTROL
            LocalStatus = FunctionBlocksPreLocalCtrl( Interval );
            STATUS_LINE_VAR_RETURN_VALUE( LocalStatus );
         #endif

         LocalStatus = LocalCtrl();
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
        
         #ifdef FUNCTION_BLOCKS_POST_LOCAL_CONTROL
            LocalStatus = FunctionBlocksPostLocalCtrl( Interval );
            STATUS_LINE_VAR_RETURN_VALUE( LocalStatus );
         #endif

#ifdef WRITE_VARS
         // Write Outputdata
         LocalStatus = OutputReferenceRoutine(ModuleState);
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif
         break;
      }
      case APP_INIT1 :
      {
 		     Init_Structures_From_Conf_File();

#ifdef CREATE_VARDB_VARS
         LocalStatus = CreateVarDbVars();
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif
#ifdef CREATE_IO_VARS
         LocalStatus = CreateIOVars();
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif
         break;
      }
      case APP_INIT2 :
      {
#ifdef CREATE_ALIASES
         size_t ErrorEntry = 0;
         LocalStatus = OS_VarDB_CreateAliases(AliasVars, sizeof(AliasVars)/sizeof(AliasVars[0]), &ErrorEntry);
         STATUS_LINE_VAR_RETURN_CONST(LocalStatus, ErrorEntry)
#endif

#ifdef VERIFY_VARIABLES
         LocalStatus = LocalIoCheck();
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif

#ifdef CREATE_BUTTONS
         LocalStatus = CreateButtons();
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif
         break;
      }
      case APP_INIT3 :
      {
#ifdef CREATE_SUMMATIONS
         LocalStatus = CreateSummations();
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif

#ifdef WRITE_VARS
         LocalStatus = InitOutputVars();
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif

#ifdef CREATE_STATUS_CODES
         LocalStatus = LocalStatusCodeInit();
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif
#ifdef CREATE_IO_VARS
         PitchSetLockValues();
#endif
         break;
      }
      case APP_INIT4 :
      {
         break;
      }
      case APP_INIT5 :
      {

         #ifdef INIT_FUNCTION_BLOCKS
            LocalStatus = FunctionBlocksInit( Interval );
            STATUS_LINE_VAR_RETURN_VALUE( LocalStatus );
         #endif

         break;
      }
      default :
      {
         break;
      }
   }
   return OS_SUCCESS;
}
//-----------------------------------------------------------------------
