//*****************************PEPTOOL Header Start******************************
//                                                                               
//                         Copyright © 2015 Mita-Teknik.                         
//This software may only be used with WP4x00 Controllers delivered by Mita-Teknik
//                                                                               
//*******************************************************************************
//                                                                               
// $PEPTOOL version:9.0$                                                         
// $PEPTOOL file version:106$                                                    
//                                                                               
//*******************************************************************************
//                                                                               
// $Date: XXXX/XX/XX XX:XX:XX $                                                  
// $Author: XXXX\XXX $                                                           
// $RCSfile: PowerCurve.c,v $                                                    
// $Revision: X.X $                                                              
//                                                                               
//******************************PEPTOOL Header End*******************************

//***********************************************************************

// OS header files
#include <os_main.h>
// AppLib header files
#include <lib_main.h>
// App header files
#include <turbdef.h>
#include <VarMacros.h>

// Object header file
#include <PowerCurve.h>

#define AUTOGENERATED_PART
//{
//-----------------------------------------------------------------------
// AUTOGENERATED START     AUTOGENERATED START     AUTOGENERATED START
//-----------------------------------------------------------------------

#define VALIDATE_HASH
char PowerCurve_copyright[] =
{
   67, 111, 112, 121, 114, 105, 103, 104, 116, 32, 63, 32, 50, 48, 49, 53,
   32, 77, 105, 116, 97, 45, 84, 101, 107, 110, 105, 107, 46, 13, 10, 84,
   104, 105, 115, 32, 115, 111, 102, 116, 119, 97, 114, 101, 32, 109, 97, 121,
   32, 111, 110, 108, 121, 32, 98, 101, 32, 117, 115, 101, 100, 32, 119, 105,
   116, 104, 32, 87, 80, 52, 120, 48, 48, 32, 67, 111, 110, 116, 114, 111,
   108, 108, 101, 114, 115, 32, 100, 101, 108, 105, 118, 101, 114, 101, 100, 32,
   98, 121, 32, 77, 105, 116, 97, 45, 84, 101, 107, 110, 105, 107, 0
};

#define MODULE_NAME "Power CurveA"

//-----------------------------------------------------------------------
// ALLOCATE MEMORY FOR STRINGS IN VARDB
//-----------------------------------------------------------------------

static char A_P_PowerCurve30SecName1[48]  = "30 s mode 1";
static char A_P_PowerCurve30SecName2[48]  = "30 s mode 2";
static char A_P_PowerCurve30SecName3[48]  = "30 s mode 3";
static char A_P_PowerCurve10MinName1[48]  = "10 min mode 1";
static char A_P_PowerCurve10MinName2[48]  = "10 min mode 2";
static char A_P_PowerCurve10MinName3[48]  = "10 min mode 3";

//-----------------------------------------------------------------------
// DEFINE LOCAL VARIABLES DEFINE LOCAL VARIABLES DEFINE LOCAL VARIABLES
//-----------------------------------------------------------------------

static struct os_db_local LocalVars[] =
{
   VAR_ELEMENT_LOCAL("V_PowerCurve30SecReset",                   TYPE_U8,      PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_SERVICE,            SCALE_NONE,   0,       UNIT_NONE,          0,   0,               0,               1,               NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_PowerCurve10MinReset",                   TYPE_U8,      PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_SERVICE,            SCALE_NONE,   0,       UNIT_NONE,          0,   0,               0,               1,               NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_PowerCurve30SecStartTime",               TYPE_TIME,    PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   (0ULL),          (0ULL),          (0ULL),          NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_PowerCurve10MinStartTime",               TYPE_TIME,    PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   (0ULL),          (0ULL),          (0ULL),          NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_PowerReducedOperation",                  TYPE_U8,      PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_SERVICE,            SCALE_NONE,   0,       UNIT_NONE,          0,   0,               0,               1,               NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_PowerCurveSemaphore",                    TYPE_U8,      PASSWORD_LEVEL_ADMINISTRATOR,      PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   2,               U8_MIN,          U8_MAX,          NULL,  NOLOG_ENABLE),
};

//-----------------------------------------------------------------------
// DEFINE PARAMETERS        DEFINE PARAMETERS        DEFINE PARAMETERS
//-----------------------------------------------------------------------

static struct os_db_parameter ParameterVars[] =
{
   VAR_ELEMENT_PARAMETER("P_PowerCurveWindSpeedOffset",              TYPE_U16,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_DIV,    100,     UNIT_MPS,           2,   0,               0,               400,             NULL  ),
};

//-----------------------------------------------------------------------
// DEFINE BACKUPS            DEFINE BACKUPS            DEFINE BACKUPS
//-----------------------------------------------------------------------

static struct os_db_backup BackupVars[] =
{
   VAR_ELEMENT_BACKUP("P_PowerCurve30SecName1",                   TYPE_STRING + sizeof(A_P_PowerCurve30SecName1) - 1,  PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_NONE,   0,       UNIT_NONE,          0,   A_P_PowerCurve30SecName1, 0,                0,                NULL,  NOLOG_ENABLE  ),
   VAR_ELEMENT_BACKUP("P_PowerCurve30SecName2",                   TYPE_STRING + sizeof(A_P_PowerCurve30SecName2) - 1,  PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_NONE,   0,       UNIT_NONE,          0,   A_P_PowerCurve30SecName2, 0,                0,                NULL,  NOLOG_ENABLE  ),
   VAR_ELEMENT_BACKUP("P_PowerCurve30SecName3",                   TYPE_STRING + sizeof(A_P_PowerCurve30SecName3) - 1,  PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_NONE,   0,       UNIT_NONE,          0,   A_P_PowerCurve30SecName3, 0,                0,                NULL,  NOLOG_ENABLE  ),
   VAR_ELEMENT_BACKUP("P_PowerCurve10MinName1",                   TYPE_STRING + sizeof(A_P_PowerCurve10MinName1) - 1,  PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_NONE,   0,       UNIT_NONE,          0,   A_P_PowerCurve10MinName1, 0,                0,                NULL,  NOLOG_ENABLE  ),
   VAR_ELEMENT_BACKUP("P_PowerCurve10MinName2",                   TYPE_STRING + sizeof(A_P_PowerCurve10MinName2) - 1,  PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_NONE,   0,       UNIT_NONE,          0,   A_P_PowerCurve10MinName2, 0,                0,                NULL,  NOLOG_ENABLE  ),
   VAR_ELEMENT_BACKUP("P_PowerCurve10MinName3",                   TYPE_STRING + sizeof(A_P_PowerCurve10MinName3) - 1,  PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_NONE,   0,       UNIT_NONE,          0,   A_P_PowerCurve10MinName3, 0,                0,                NULL,  NOLOG_ENABLE  ),
};

//----------------------------------------------------------------------------------
// DEFINE VAR ARRAYS            DEFINE VAR ARRAYS            DEFINE VAR ARRAYS
//----------------------------------------------------------------------------------
char PowerCurve_initialValues[] =
{
   145, 72, 63, 170, 19, 58, 169, 41, 83, 14, 55, 88, 29, 166, 87, 11,
   7, 81, 100, 39, 236, 130, 49, 6, 204, 42, 194, 28, 4, 166, 240, 60,
   0
};

//-----------------------------------------------------------------------
// CREATE DATABASE VARS   CREATE DATABASE VARS   CREATE DATABASE VARS
//-----------------------------------------------------------------------

static STATUS CreateVarDbVars(void)
{
   STATUS Status;
   size_t ErrorEntry;

   Status = OS_VarDB_CreateLocals(LocalVars, sizeof(LocalVars)/sizeof(LocalVars[0]), &ErrorEntry, AppLocalParameterPosition());
   if (Status != 0)
   {
      AppSystemLog(ERR_7, MODULE_NAME"CrVL: %d,%d", Status, ErrorEntry);
      return ERR_7;
   }

   Status = OS_VarDB_CreateParameters(ParameterVars, sizeof(ParameterVars)/sizeof(ParameterVars[0]), &ErrorEntry, AppExportParameterPosition());
   if (Status != 0)
   {
      AppSystemLog(ERR_7, MODULE_NAME"CrVXP: %d,%d", Status, ErrorEntry);
      return ERR_7;
   }

   Status = OS_VarDB_CreateBackups(BackupVars, sizeof(BackupVars)/sizeof(BackupVars[0]), &ErrorEntry, AppLocalParameterPosition(), AppBackupPosition());
   if (Status != 0)
   {
      AppSystemLog(ERR_7, MODULE_NAME"CrVB: %d,%d", Status, ErrorEntry);
      return ERR_7;
   }

   return OS_SUCCESS;
}

#define CREATE_VARDB_VARS

//-----------------------------------------------------------------------
// CREATE IO VARIABLES     CREATE IO VARIABLES     CREATE IO VARIABLES
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// ALIASES                       ALIASES                       ALIASES
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// INPUT                          INPUT                          INPUT
//-----------------------------------------------------------------------

// Create local variable
#define MODUL_INPUTS
static S32 V_NormPower30Sec = 0;
static S32 V_NormPower10Min = 0;
static U16 V_NormWindSpeed30Sec = 0;
static U16 V_NormWindSpeed10Min = 0;
static U8 V_PowerCurveSemaphore = 0;
static U8 V_ActiveControlProgram1 = 0;
static U8 V_PowerReducedOperation = 0;
static U16 P_PowerCurveWindSpeedOffset = 0;
static U8 V_PowerCurve30SecReset = 0;
static U8 V_PowerCurve10MinReset = 0;
static char P_PowerCurve30SecName1[48];
static char P_PowerCurve30SecName2[48];
static char P_PowerCurve30SecName3[48];
static char P_PowerCurve10MinName1[48];
static char P_PowerCurve10MinName2[48];
static char P_PowerCurve10MinName3[48];

//-----------------------------------------------------------------------
static struct ModulInOut ModulInputs[] =
{
   {"V_NormPower30Sec",                         &V_NormPower30Sec,                         sizeof(V_NormPower30Sec),                         },
   {"V_NormPower10Min",                         &V_NormPower10Min,                         sizeof(V_NormPower10Min),                         },
   {"V_NormWindSpeed30Sec",                     &V_NormWindSpeed30Sec,                     sizeof(V_NormWindSpeed30Sec),                     },
   {"V_NormWindSpeed10Min",                     &V_NormWindSpeed10Min,                     sizeof(V_NormWindSpeed10Min),                     },
   {"P_PowerCurve30SecName1",                   &P_PowerCurve30SecName1,                   sizeof(P_PowerCurve30SecName1),                   },
   {"V_PowerCurveSemaphore",                    &V_PowerCurveSemaphore,                    sizeof(V_PowerCurveSemaphore),                    },
   {"V_ActiveControlProgram1",                  &V_ActiveControlProgram1,                  sizeof(V_ActiveControlProgram1),                  },
   {"V_PowerReducedOperation",                  &V_PowerReducedOperation,                  sizeof(V_PowerReducedOperation),                  },
   {"P_PowerCurveWindSpeedOffset",              &P_PowerCurveWindSpeedOffset,              sizeof(P_PowerCurveWindSpeedOffset),              },
   {"P_PowerCurve30SecName2",                   &P_PowerCurve30SecName2,                   sizeof(P_PowerCurve30SecName2),                   },
   {"P_PowerCurve30SecName3",                   &P_PowerCurve30SecName3,                   sizeof(P_PowerCurve30SecName3),                   },
   {"P_PowerCurve10MinName1",                   &P_PowerCurve10MinName1,                   sizeof(P_PowerCurve10MinName1),                   },
   {"P_PowerCurve10MinName2",                   &P_PowerCurve10MinName2,                   sizeof(P_PowerCurve10MinName2),                   },
   {"P_PowerCurve10MinName3",                   &P_PowerCurve10MinName3,                   sizeof(P_PowerCurve10MinName3),                   },
   {"V_PowerCurve30SecReset",                   &V_PowerCurve30SecReset,                   sizeof(V_PowerCurve30SecReset),                   },
   {"V_PowerCurve10MinReset",                   &V_PowerCurve10MinReset,                   sizeof(V_PowerCurve10MinReset),                   },
};

//-----------------------------------------------------------------------
// Check variable type
static STATUS VarsReadReturnStatus;
static type_t ReadVarType = TYPE_NONE;
static void VarsReadTypeCheck(void)
{
   (void)VarsReadReturnStatus;
   (void)ReadVarType;
   VERIFY_INPUT_REF_ID(S32,       ModulInputs[0].Name,                      ModulInputs[0].Id)
   VERIFY_INPUT_REF_ID(S32,       ModulInputs[1].Name,                      ModulInputs[1].Id)
   VERIFY_INPUT_REF_ID(U16,       ModulInputs[2].Name,                      ModulInputs[2].Id)
   VERIFY_INPUT_REF_ID(U16,       ModulInputs[3].Name,                      ModulInputs[3].Id)
   VERIFY_INPUT_STRING_REF_ID(STRING,    ModulInputs[4].Name,                      ModulInputs[4].Id)
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[5].Name,                      ModulInputs[5].Id)
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[6].Name,                      ModulInputs[6].Id)
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[7].Name,                      ModulInputs[7].Id)
   VERIFY_INPUT_REF_ID(U16,       ModulInputs[8].Name,                      ModulInputs[8].Id)
   VERIFY_INPUT_STRING_REF_ID(STRING,    ModulInputs[9].Name,                      ModulInputs[9].Id)
   VERIFY_INPUT_STRING_REF_ID(STRING,    ModulInputs[10].Name,                     ModulInputs[10].Id)
   VERIFY_INPUT_STRING_REF_ID(STRING,    ModulInputs[11].Name,                     ModulInputs[11].Id)
   VERIFY_INPUT_STRING_REF_ID(STRING,    ModulInputs[12].Name,                     ModulInputs[12].Id)
   VERIFY_INPUT_STRING_REF_ID(STRING,    ModulInputs[13].Name,                     ModulInputs[13].Id)
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[14].Name,                     ModulInputs[14].Id)
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[15].Name,                     ModulInputs[15].Id)
}

#undef MODUL_INPUTS
#define MODUL_INPUTS_SIZE (sizeof(ModulInputs)/sizeof(ModulInputs[0]))

//------------------------------------------------------------------------------------------
// READ/WRITE VARDB ARRAY      READ/WRITE VARDB ARRAY      READ/WRATE VARDB ARRAY
//------------------------------------------------------------------------------------------


//-----------------------------------------------------------------------
// PARAMETER                    PARAMETER                    PARAMETER
//-----------------------------------------------------------------------


//-----------------------------------------------------------------------
// READ VARS FROM VARDB    READ VARS FROM VARDB    READ VARS FROM VARDB
//-----------------------------------------------------------------------

static STATUS InputReferenceRoutine(U8 ModuleState)
{
   STATUS LocalStatus = 0;

   // Read input references
   if (ModuleState >= APP_INIT3)
   {
      // Check inputdata
      if (sizeof(ModulInputs) == 0)
      {
         AppSystemLog(ERR_4, MODULE_NAME"ModuleInputs = 0");
         return ERR_4;
      }
      // Read inputdata
      LocalStatus = OS_ReadVariables(ModulInputs, MODUL_INPUTS_SIZE);
      if (LocalStatus != 0)
      {
         AppSystemLog(ERR_4, MODULE_NAME"ReadVErr: element=%d elementpointer=0x%x", LocalStatus, &ModulInputs[LocalStatus]);
         return ERR_4;
      }
   }
   return 0;
}

#define READ_VARS

//-----------------------------------------------------------------------
// OUTPUT                         OUTPUT                         OUTPUT
//-----------------------------------------------------------------------

// Create local variable
#define MODUL_OUTPUTS


//-----------------------------------------------------------------------
static struct ModulInOut ModulOutputs[] =
{
   {"V_PowerCurveSemaphore",                    &V_PowerCurveSemaphore,                    sizeof(V_PowerCurveSemaphore),                    },
};

//-----------------------------------------------------------------------
// Check variable type
static STATUS VarsWriteReturnStatus;
static type_t WriteVarType = TYPE_NONE;
static void VarsWriteTypeCheck(void)
{
   (void)VarsWriteReturnStatus;
   (void)WriteVarType;
   VERIFY_OUTPUT_REF_ID(U8,        ModulOutputs[0].Name,                     ModulOutputs[0].Id,                       0)
}

#undef MODUL_OUTPUTS
#define MODUL_OUTPUTS_SIZE (sizeof(ModulOutputs)/sizeof(ModulOutputs[0]))

//-----------------------------------------------------------------------
// WRITE VARS TO VARDB     WRITE VARS TO VARDB     WRITE VARS TO VARDB
//-----------------------------------------------------------------------

static STATUS InitOutputVars(void)
{
   STATUS LocalStatus;
   // Read outputdata
   LocalStatus = OS_ReadVariables(ModulOutputs, MODUL_OUTPUTS_SIZE);
   if (LocalStatus != 0)
   {
      AppSystemLog(ERR_4, MODULE_NAME"InitErr: element=%d elementpointer=0x%x", LocalStatus, &ModulOutputs[LocalStatus]);
      return ERR_4;
   }
   return OS_SUCCESS;
}
static STATUS OutputReferenceRoutine(U8 ModuleState)
{
   STATUS LocalStatus = 0;
   // Write Outputdata
   LocalStatus = OS_WriteVariablesConditional(ModulOutputs, MODUL_OUTPUTS_SIZE);
   if (LocalStatus != 0)
   {
      AppSystemLog(ERR_5, MODULE_NAME"WriteVErr: element=%d elementpointer=0x%x", LocalStatus, &ModulOutputs[LocalStatus]);
      return ERR_5;
   }
   return 0;
}

#define WRITE_VARS

//-----------------------------------------------------------------------
// VERIFY VARIABLES CREATION                 VERIFY VARIABLES CREATION
//-----------------------------------------------------------------------

static STATUS LocalIoCheck(void)
{
   // Check if input variables exist.
   STATUS LocalStatus;

   LocalStatus = OS_DoesVariablesExist(ModulInputs, MODUL_INPUTS_SIZE);
   if (LocalStatus != 0)
   {
      AppSystemLog(ERR_1, MODULE_NAME"InputErr: %d", LocalStatus);
      AppSystemLog(ERR_1, "Name: %s", ModulInputs[LocalStatus-1].Name);
      return ERR_1;
   }
   (void)VarsReadTypeCheck();

   LocalStatus = OS_DoesVariablesExist(ModulOutputs, MODUL_OUTPUTS_SIZE);
   if (LocalStatus != 0)
   {
      AppSystemLog(ERR_2, MODULE_NAME"OutputErr: %d", LocalStatus);
      AppSystemLog(ERR_2, "Name: %s", ModulOutputs[LocalStatus-1].Name);
      return ERR_2;
   }
   (void)VarsWriteTypeCheck();

   return OS_SUCCESS;
}

#define VERIFY_VARIABLES

//-----------------------------------------------------------------------
// ALLOCATE MEMORY FOR SUMMATIONS        ALLOCATE MEMORY FOR SUMMATIONS
//-----------------------------------------------------------------------


//-----------------------------------------------------------------------
// SUMMATIONS                  SUMMATIONS                  SUMMATIONS
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// DEFINE MENUS               DEFINE MENUS               DEFINE MENUS
//-----------------------------------------------------------------------



// Menu line and link to local menu
//-----------------------------------------------------------------------
static struct line_struct M_PowerCurveLinkToLocalMenu[] =
{
   MENU_ELEMENT_LINE_LINK("Power Curve",                       PASSWORD_LEVEL_END_CUSTOMER,        "M_PowerCurve",                     "G_PowerCurve"),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_PowerCurveMenu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_PowerCurve",                     PASSWORD_LEVEL_END_CUSTOMER),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_PowerCurveMenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("POWER CURVE",                       PASSWORD_LEVEL_END_CUSTOMER,        "M_"APP_ID"AppMain",                "G_"APP_ID"App"),
   MENU_ELEMENT_LINE_LINK("Status",                            PASSWORD_LEVEL_END_CUSTOMER,        "M_Status1",                        "G_PowerCurve"),
   MENU_ELEMENT_LINE_LINK("Parameter",                         PASSWORD_LEVEL_END_CUSTOMER,        "M_Parameter1",                     "G_PowerCurve"),
   MENU_ELEMENT_LINE_LINK("Service",                           PASSWORD_LEVEL_SERVICE,             "M_Service1",                       "G_PowerCurve"),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_Status1Menu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_Status1",                        PASSWORD_LEVEL_END_CUSTOMER),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_Status1MenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("STATUS",                            PASSWORD_LEVEL_END_CUSTOMER,        "M_PowerCurve",                     "G_PowerCurve"),
   MENU_ELEMENT_LINE_VARRO("30 s Reset",                       PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_PowerCurve30SecStartTime",                 LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("10 min Reset",                     PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_PowerCurve10MinStartTime",                 LINE_FORMAT_NONE),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_Parameter1Menu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_Parameter1",                     PASSWORD_LEVEL_END_CUSTOMER),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_Parameter1MenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("PARAMETER",                         PASSWORD_LEVEL_END_CUSTOMER,        "M_PowerCurve",                     "G_PowerCurve"),
   MENU_ELEMENT_LINE_VARRW("Wind Offset",                      PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_PowerCurveWindSpeedOffset",                LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("30 s Name 1",                      PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_PowerCurve30SecName1",                     LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("30 s Name 2",                      PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_PowerCurve30SecName2",                     LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("30 s Name 3",                      PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_PowerCurve30SecName3",                     LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("10 min Name 1",                    PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_PowerCurve10MinName1",                     LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("10 min Name 2",                    PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_PowerCurve10MinName2",                     LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("10 min Name 3",                    PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_PowerCurve10MinName3",                     LINE_FORMAT_NONE),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_Service1Menu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_Service1",                       PASSWORD_LEVEL_SERVICE),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_Service1MenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("SERVICE",                           PASSWORD_LEVEL_SERVICE,             "M_PowerCurve",                     "G_PowerCurve"),
   MENU_ELEMENT_LINE_VARRW("30 s Reset",                       PASSWORD_LEVEL_SERVICE,             (char*)"V_PowerCurve30SecReset",                     LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("10 min Reset",                     PASSWORD_LEVEL_SERVICE,             (char*)"V_PowerCurve10MinReset",                     LINE_FORMAT_NONE),
};
// Creating parameters for multiplexed categories
//-----------------------------------------------------------------------
static struct multiplexed_info_struct M_PowerCurveMultiplexedCategoriesParameters[] =
{
0};

//-----------------------------------------------------------------------
// CREATE MENUS               CREATE MENUS               CREATE MENUS
//-----------------------------------------------------------------------

// Memory reservation
//-----------------------------------------------------------------------
static struct menu_group_struct ObjGroup[1];

// Creating the menus
//-----------------------------------------------------------------------
STATUS PowerCurveMenuAppInit(U8 ModuleState, OS_MEMORY_POOL* pPool)
{
   STATUS Status;

   if (ModuleState == APP_INIT1)
   {
      /* Create application group */
      Status = OS_CreateMenuGroup(ObjGroup, M_PowerCurveLinkToLocalMenu[0].LinkGroup);
      STATUS_LINE_VAR_RETURN_VALUE(Status);
   }

   Status = CreateAndInitializeMenu(ModuleState,
                                    M_PowerCurveMenuLines[0].LinkGroup,
                                    M_PowerCurveMenuLines[0].LinkName,
                                    ELEMENT(M_PowerCurveLinkToLocalMenu),
                                    M_PowerCurveLinkToLocalMenu[0].LinkGroup,
                                    ELEMENT(M_PowerCurveMenu),
                                    M_PowerCurveLinkToLocalMenu[0].LinkName,
                                    ELEMENT(M_PowerCurveMenuLines),
                                    pPool,
                                    M_PowerCurveMultiplexedCategoriesParameters);
   STATUS_LINE_VAR_RETURN_VALUE(Status);

   Status = CreateAndInitializeMenu(ModuleState,
                                    M_Status1MenuLines[0].LinkGroup,
                                    M_Status1MenuLines[0].LinkName,
                                    NULL,
                                    0,
                                    M_PowerCurveMenuLines[1].LinkGroup,
                                    ELEMENT(M_Status1Menu),
                                    M_PowerCurveMenuLines[1].LinkName,
                                    ELEMENT(M_Status1MenuLines),
                                    pPool,
                                    M_PowerCurveMultiplexedCategoriesParameters);
   STATUS_LINE_VAR_RETURN_VALUE(Status);

   Status = CreateAndInitializeMenu(ModuleState,
                                    M_Parameter1MenuLines[0].LinkGroup,
                                    M_Parameter1MenuLines[0].LinkName,
                                    NULL,
                                    0,
                                    M_PowerCurveMenuLines[2].LinkGroup,
                                    ELEMENT(M_Parameter1Menu),
                                    M_PowerCurveMenuLines[2].LinkName,
                                    ELEMENT(M_Parameter1MenuLines),
                                    pPool,
                                    M_PowerCurveMultiplexedCategoriesParameters);
   STATUS_LINE_VAR_RETURN_VALUE(Status);

   Status = CreateAndInitializeMenu(ModuleState,
                                    M_Service1MenuLines[0].LinkGroup,
                                    M_Service1MenuLines[0].LinkName,
                                    NULL,
                                    0,
                                    M_PowerCurveMenuLines[3].LinkGroup,
                                    ELEMENT(M_Service1Menu),
                                    M_PowerCurveMenuLines[3].LinkName,
                                    ELEMENT(M_Service1MenuLines),
                                    pPool,
                                    M_PowerCurveMultiplexedCategoriesParameters);
   STATUS_LINE_VAR_RETURN_VALUE(Status);

   return OS_SUCCESS;
}

#define CREATE_MENU

//-----------------------------------------------------------------------
//               BUTTONS FUNCTIONS FORWARD DECLARATIONS
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// BUTTONS                       BUTTONS                      BUTTONS
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
//             SET/RESET FUNCTIONS FORWARD DECLARATIONS
//-----------------------------------------------------------------------
//-----------------------------------------------------------------------
// STATUSCODES                 STATUSCODES                 STATUSCODES
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// MODIFIABLE                  MODIFIABLE                   MODIFIABLE
//-----------------------------------------------------------------------

extern const char PowerCurveAppGroupName[];
extern const char PowerCurveAppMenuName[];

static void Init_Structures_From_Conf_File(void)
{
   M_PowerCurveMenuLines[0].LinkName = (char*)PowerCurveAppMenuName;
   M_PowerCurveMenuLines[0].LinkGroup = (char*)PowerCurveAppGroupName;
}

//-----------------------------------------------------------------------
// AUTOGENERATED END        AUTOGENERATED END        AUTOGENERATED END
//-----------------------------------------------------------------------
//}

#undef AUTOGENERATED_PART

//-----------------------------------------------------------------------
// USER DEFINITIONS         USER DEFINITIONS         USER DEFINITIONS
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// SET/RESET FUNCTIONS    SET/RESET FUNCTIONS    SET/RESET FUNCTIONS
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// DRIVER FUNCTION         DRIVER FUNCTION         DRIVER FUNCTION
//-----------------------------------------------------------------------
  
//-----------------------------------------------------------------------
// INIT                   INIT                     INIT
//-----------------------------------------------------------------------
  
//-----------------------------------------------------------------------
// CONTROL                CONTROL                 CONTROL
//-----------------------------------------------------------------------
  
static STATUS LocalCtrl( U32 Interval )
{
   STATUS LocalStatus = 0;

   return LocalStatus;
}

static STATUS ShutdownCtrl( U8 ModuleState, U8 *DoneState, U32 Interval )
{
    STATUS LocalStatus = 0;

    LocalStatus = LocalCtrl( Interval );
    STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);

    switch( ModuleState )
    {
        case AS_SHUTDOWN:
        {
            // Activate "Manual Shutdown" status code

            *DoneState = AS_SHUTDOWN;
            break;
        }
        case AS_REBOOT:
        {

            *DoneState = AS_REBOOT;
            break;
        }
        case AS_SHUTDOWN_FAST:
        {

            *DoneState = AS_SHUTDOWN_FAST;
            break;
        }
        default:
        {
            *DoneState = ModuleState;
            break;
        }
    }
    return LocalStatus;
}
 
//-----------------------------------------------------------------------
// MAIN CALL             MAIN CALL               MAIN CALL
//-----------------------------------------------------------------------

STATUS PowerCurve( U8 ModuleState, U8 *DoneState , U32 Interval )
{
   STATUS LocalStatus = 0;

   #ifdef READ_VARS
      // Read input data
      LocalStatus = InputReferenceRoutine(ModuleState);
      STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
   #endif
   #ifdef COMMON_VDB_READ
      LocalStatus = ReadVdbWindow(ModuleState);
      STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
   #endif


   switch( ModuleState )
   {
      //__________________________________________________________________________
      case APP_RUN:
      {
         #ifdef FUNCTION_BLOCKS_PRE_LOCAL_CONTROL
            LocalStatus = FunctionBlocksPreLocalCtrl( Interval );
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif
         
         LocalStatus = LocalCtrl( Interval );
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);

         #ifdef FUNCTION_BLOCKS_POST_LOCAL_CONTROL
            LocalStatus = FunctionBlocksPostLocalCtrl( Interval );
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef WRITE_VARS
            // Write Output data
            LocalStatus = OutputReferenceRoutine(ModuleState);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef COMMON_VDB_WRITE
            LocalStatus = WriteVdbWindow(ModuleState);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         *DoneState = APP_RUN;
         break;
      }
      //__________________________________________________________________________
      case APP_INIT1:
      {
         // Version check
         LocalStatus = OS_ValidateAPI( API_VERSION_MAJOR,
                                API_VERSION_MINOR,
                                OS_LinkTime,
                                ReleaseTag,
                                __MODULE__
                               );
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);

         Init_Structures_From_Conf_File();

         #ifdef CREATE_VARDB_VARS
            LocalStatus = CreateVarDbVars();
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef CREATE_MENU
            LocalStatus = PowerCurveMenuAppInit(ModuleState, GetMemPool());
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);

            #ifdef MULTIPLEXIBLE_MENU
               LocalStatus = MenuArraysAppInit(ModuleState, GetMemPool());
               STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
            #endif
         #endif

         #ifdef CREATE_VARDB_ARRAY_VARS
               LocalStatus = CreateVdbArrays(GetMemPool());
               STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
         #endif


         #ifdef CREATE_IO_VARS
               LocalStatus = CreateIOVars();
               STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
         #endif

         *DoneState = APP_INIT1;

         break;
      }
      //__________________________________________________________________________
      case APP_INIT2:
      {
         #ifdef CREATE_MENU
            #ifdef MULTIPLEXIBLE_MENU
               LocalStatus = MenuArraysAppInit(ModuleState, GetMemPool());
               STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
            #endif
         #endif

         #ifdef CREATE_ALIASES
               size_t ErrorEntry = 0;
               LocalStatus = OS_VarDB_CreateAliases(AliasVars, sizeof(AliasVars)/sizeof(AliasVars[0]), &ErrorEntry);
               STATUS_LINE_VAR_RETURN_CONST(LocalStatus, ErrorEntry);
         #endif

         #ifdef VERIFY_ARRAY
               LocalStatus = VerifyArray(GetMemPool());
               STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef VERIFY_VARIABLES
               LocalStatus = LocalIoCheck();
               STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef CREATE_BUTTONS
               LocalStatus = CreateButtons();
               STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         *DoneState = APP_INIT2;

         break;
      }
      //__________________________________________________________________________
      case APP_INIT3 :
      {
         #ifdef CREATE_SUMMATIONS
            LocalStatus = CreateSummations();
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef WRITE_VARS
            LocalStatus = InitOutputVars();
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef CREATE_STATUS_CODES
            LocalStatus = LocalStatusCodeInit();
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef CREATE_IO_VARS
           PowerCurveSetLockValues();
         #endif

         *DoneState = APP_INIT3;

         break;
      }
      //__________________________________________________________________________
      case APP_INIT4:
      {
         #ifdef CREATE_MENU
            LocalStatus = PowerCurveMenuAppInit(ModuleState, GetMemPool());
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);

            #ifdef MULTIPLEXIBLE_MENU
               LocalStatus = MenuArraysAppInit(ModuleState, GetMemPool());
               STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
            #endif
         #endif

         *DoneState = APP_INIT4;

         break;
      }
      //__________________________________________________________________________
      case APP_INIT5:
      {
         #ifdef VALIDATE_HASH
            LocalStatus = ValidateHash( PowerCurve_copyright, MODULE_NAME, PowerCurve_initialValues);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef INIT_FUNCTION_BLOCKS
            LocalStatus = FunctionBlocksInit( Interval );
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         *DoneState = APP_INIT5_DONE;

         break;
      }
      //__________________________________________________________________________
      //Other initialization round can be inserted here
      //__________________________________________________________________________
      case AS_SHUTDOWN:
      {
         LocalStatus = ShutdownCtrl ( ModuleState, DoneState, Interval );
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);

         #ifdef WRITE_VARS
            // Write Output data
            LocalStatus = OutputReferenceRoutine(ModuleState);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef COMMON_VDB_WRITE
            LocalStatus = WriteVdbWindow(ModuleState);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         break;
      }
      //__________________________________________________________________________
      case AS_REBOOT:
      {
         LocalStatus = ShutdownCtrl ( ModuleState, DoneState, Interval );
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);

         #ifdef WRITE_VARS
            // Write Output data
            LocalStatus = OutputReferenceRoutine(ModuleState);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef COMMON_VDB_WRITE
            LocalStatus = WriteVdbWindow(ModuleState);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         break;
      }
      //__________________________________________________________________________
      case AS_SHUTDOWN_FAST:
      {
         LocalStatus = ShutdownCtrl ( ModuleState, DoneState, Interval );
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);

         #ifdef WRITE_VARS
            // Write Output data
            LocalStatus = OutputReferenceRoutine(ModuleState);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef COMMON_VDB_WRITE
            LocalStatus = WriteVdbWindow(ModuleState);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         break;
      }
      default:
      {
         *DoneState = ModuleState;

         break;
      }
   }
   return OS_SUCCESS;
}
//-----------------------------------------------------------------------
