//*****************************PEPTOOL Header Start******************************
//                                                                               
//                         Copyright © 2015 Mita-Teknik.                         
//This software may only be used with WP4x00 Controllers delivered by Mita-Teknik
//                                                                               
//*******************************************************************************
//                                                                               
// $PEPTOOL version:9.0$                                                         
// $PEPTOOL file version:106$                                                    
//                                                                               
//*******************************************************************************
//                                                                               
// $Date: XXXX/XX/XX XX:XX:XX $                                                  
// $Author: XXXX\XXX $                                                           
// $RCSfile: DLL_object.c,v $                                                    
// $Revision: X.X $                                                              
//                                                                               
//******************************PEPTOOL Header End*******************************

//***********************************************************************

// OS header files
#include <os_main.h>
// AppLib header files
#include <lib_main.h>
// App header files
#include <turbdef.h>
#include <VarMacros.h>

// Object header file
#include <Power_Converter.h>

#define AUTOGENERATED_PART
//{
//-----------------------------------------------------------------------
// AUTOGENERATED START     AUTOGENERATED START     AUTOGENERATED START
//-----------------------------------------------------------------------

#define VALIDATE_HASH
char Power_Converter_copyright[] =
{
    67, 111, 112, 121, 114, 105, 103, 104, 116, 32, 63, 32, 50, 48, 49, 53,
    32, 77, 105, 116, 97, 45, 84, 101, 107, 110, 105, 107, 46, 13, 10, 84,
    104, 105, 115, 32, 115, 111, 102, 116, 119, 97, 114, 101, 32, 109, 97, 121,
    32, 111, 110, 108, 121, 32, 98, 101, 32, 117, 115, 101, 100, 32, 119, 105,
    116, 104, 32, 87, 80, 52, 120, 48, 48, 32, 67, 111, 110, 116, 114, 111,
    108, 108, 101, 114, 115, 32, 100, 101, 108, 105, 118, 101, 114, 101, 100, 32,
    98, 121, 32, 77, 105, 116, 97, 45, 84, 101, 107, 110, 105, 107, 0
};

#define MODULE_NAME "Power ConverterA"

//-----------------------------------------------------------------------
// ALLOCATE MEMORY FOR STRINGS IN VARDB
//-----------------------------------------------------------------------

static char A_V_CNV_RequestedStateTxt[31]  = "NA";
static char A_V_CNV_StateTxt[31]  = "NA";

//-----------------------------------------------------------------------
// DEFINE LOCAL VARIABLES DEFINE LOCAL VARIABLES DEFINE LOCAL VARIABLES
//-----------------------------------------------------------------------

static struct os_db_local LocalVars[] =
{
   VAR_ELEMENT_LOCAL("V_CNV_RequestedState",                     TYPE_U8,      PASSWORD_LEVEL_ADMINISTRATOR,      PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   0,               U8_MIN,          U8_MAX,          NULL,  TOTLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_CNV_RequestedStateTxt",                  TYPE_STRING + sizeof(A_V_CNV_RequestedStateTxt) - 1,  PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         SCALE_NONE,   0,       UNIT_NONE,          0,   A_V_CNV_RequestedStateTxt, 0,                0,                NULL,  NOLOG_ENABLE  ),
   VAR_ELEMENT_LOCAL("V_CNV_State",                              TYPE_U8,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         SCALE_NONE,   0,       UNIT_NONE,          0,   0,               U8_MIN,          U8_MAX,          NULL,  TOTLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_CNV_StateTxt",                           TYPE_STRING + sizeof(A_V_CNV_StateTxt) - 1,  PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         SCALE_NONE,   0,       UNIT_NONE,          0,   A_V_CNV_StateTxt, 0,                0,                NULL,  NOLOG_ENABLE  ),
   VAR_ELEMENT_LOCAL("V_CNV_PowerSetpoint",                      TYPE_S32,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         SCALE_DIV,    10,      UNIT_KWATT,         0,   0,               S32_MIN,         S32_MAX,         NULL,  TOTLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_CNV_TorqueSetpointkNm",                  TYPE_S16,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   0,               S16_MIN,         S16_MAX,         NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_CNV_ReactivePowerSetpoint",              TYPE_S32,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    10,      UNIT_KVAR,          1,   0,               S32_MIN,         S32_MAX,         NULL,  TOTLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_CNV_MaxTemp",                            TYPE_S16,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         SCALE_DIV,    10,      UNIT_CELSIUS,       1,   0,               S16_MIN,         S16_MAX,         NULL,  FIVEMINLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_CNV_MinTemp",                            TYPE_S16,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         SCALE_DIV,    10,      UNIT_CELSIUS,       1,   0,               S16_MIN,         S16_MAX,         NULL,  FIVEMINLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_CNV_TorqueActPct",                       TYPE_S16,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         SCALE_DIV,    100,     UNIT_PCT,           2,   0,               S16_MIN,         S16_MAX,         NULL,  TOTLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_CNV_TorqueActNm",                        TYPE_S32,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    10000,   UNIT_NONE,          1,   0,               S32_MIN,         S32_MAX,         NULL,  TOTLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_CNV_MinIGBTTemp",                        TYPE_S16,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    10,      UNIT_CELSIUS,       1,   50,              S16_MIN,         S16_MAX,         NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_CNV_MaxIGBTTemp",                        TYPE_S16,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    10,      UNIT_CELSIUS,       1,   0,               S16_MIN,         S16_MAX,         NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_CNV_MaxInductTemp",                      TYPE_S16,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    10,      UNIT_CELSIUS,       1,   0,               S16_MIN,         S16_MAX,         NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_CNV_MaxControlTemp",                     TYPE_S16,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    10,      UNIT_CELSIUS,       1,   0,               S16_MIN,         S16_MAX,         NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_CNV_GridSide_ActivePower_Total",         TYPE_S32,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    10,      UNIT_KWATT,         1,   0,               S32_MIN,         S32_MAX,         NULL,  NOLOG_ENABLE),
};

//-----------------------------------------------------------------------
// DEFINE PARAMETERS        DEFINE PARAMETERS        DEFINE PARAMETERS
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// DEFINE BACKUPS            DEFINE BACKUPS            DEFINE BACKUPS
//-----------------------------------------------------------------------

//----------------------------------------------------------------------------------
// DEFINE VAR ARRAYS            DEFINE VAR ARRAYS            DEFINE VAR ARRAYS
//----------------------------------------------------------------------------------
char Power_Converter_initialValues[] =
{
    120, 220, 53, 132, 130, 117, 70, 88, 248, 213, 107, 115, 160, 207, 61, 32,
    106, 106, 161, 214, 228, 127, 52, 151, 209, 39, 195, 3, 175, 186, 128, 161,
    0
};

//-----------------------------------------------------------------------
// CREATE DATABASE VARS   CREATE DATABASE VARS   CREATE DATABASE VARS
//-----------------------------------------------------------------------

static STATUS CreateVarDbVars(void)
{
   STATUS Status;
   size_t ErrorEntry;

   Status = OS_VarDB_CreateLocals(LocalVars, sizeof(LocalVars)/sizeof(LocalVars[0]), &ErrorEntry, AppLocalParameterPosition());
   if (Status != 0)
   {
      AppSystemLog(ERR_7, MODULE_NAME"CrVL: %d,%d", Status, ErrorEntry);
      return ERR_7;
   }

   return OS_SUCCESS;
}

#define CREATE_VARDB_VARS

//-----------------------------------------------------------------------
// CREATE IO VARIABLES     CREATE IO VARIABLES     CREATE IO VARIABLES
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// ALIASES                       ALIASES                       ALIASES
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// INPUT                          INPUT                          INPUT
//-----------------------------------------------------------------------

// Create local variable
#define MODUL_INPUTS
static U8 V_CNV_RequestedState = 0;

//-----------------------------------------------------------------------
static struct ModulInOut ModulInputs[] =
{
   {"V_CNV_RequestedState",                     &V_CNV_RequestedState,                     sizeof(V_CNV_RequestedState),                     },
};

//-----------------------------------------------------------------------
// Check variable type
static STATUS VarsReadReturnStatus;
static type_t ReadVarType = TYPE_NONE;
static void VarsReadTypeCheck(void)
{
   (void)VarsReadReturnStatus;
   (void)ReadVarType;
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[0].Name,                      ModulInputs[0].Id)
}

#undef MODUL_INPUTS
#define MODUL_INPUTS_SIZE (sizeof(ModulInputs)/sizeof(ModulInputs[0]))

//------------------------------------------------------------------------------------------
// READ/WRITE VARDB ARRAY      READ/WRITE VARDB ARRAY      READ/WRATE VARDB ARRAY
//------------------------------------------------------------------------------------------


//-----------------------------------------------------------------------
// PARAMETER                    PARAMETER                    PARAMETER
//-----------------------------------------------------------------------


//-----------------------------------------------------------------------
// READ VARS FROM VARDB    READ VARS FROM VARDB    READ VARS FROM VARDB
//-----------------------------------------------------------------------

static STATUS InputReferenceRoutine(U8 ModuleState)
{
   STATUS LocalStatus = 0;

   // Read input references
   if (ModuleState >= APP_INIT3)
   {
      // Check inputdata
      if (sizeof(ModulInputs) == 0)
      {
         AppSystemLog(ERR_4, MODULE_NAME"ModuleInputs = 0");
         return ERR_4;
      }
      // Read inputdata
      LocalStatus = OS_ReadVariables(ModulInputs, MODUL_INPUTS_SIZE);
      if (LocalStatus != 0)
      {
         AppSystemLog(ERR_4, MODULE_NAME"ReadVErr: element=%d elementpointer=0x%x", LocalStatus, &ModulInputs[LocalStatus]);
         return ERR_4;
      }
   }
   return 0;
}

#define READ_VARS

//-----------------------------------------------------------------------
// OUTPUT                         OUTPUT                         OUTPUT
//-----------------------------------------------------------------------

// Create local variable
#define MODUL_OUTPUTS
static char V_CNV_RequestedStateTxt[31];


//-----------------------------------------------------------------------
static struct ModulInOut ModulOutputs[] =
{
   {"V_CNV_RequestedStateTxt",                  &V_CNV_RequestedStateTxt,                  sizeof(V_CNV_RequestedStateTxt),                  },
};

//-----------------------------------------------------------------------
// Check variable type
static STATUS VarsWriteReturnStatus;
static type_t WriteVarType = TYPE_NONE;
static void VarsWriteTypeCheck(void)
{
   (void)VarsWriteReturnStatus;
   (void)WriteVarType;
   VERIFY_OUTPUT_STRING_REF_ID(STRING,     ModulOutputs[0].Name,                      ModulOutputs[0].Id,                            0)
}

#undef MODUL_OUTPUTS
#define MODUL_OUTPUTS_SIZE (sizeof(ModulOutputs)/sizeof(ModulOutputs[0]))

//-----------------------------------------------------------------------
// WRITE VARS TO VARDB     WRITE VARS TO VARDB     WRITE VARS TO VARDB
//-----------------------------------------------------------------------

static STATUS InitOutputVars(void)
{
   STATUS LocalStatus;
   // Read outputdata
   LocalStatus = OS_ReadVariables(ModulOutputs, MODUL_OUTPUTS_SIZE);
   if (LocalStatus != 0)
   {
      AppSystemLog(ERR_4, MODULE_NAME"InitErr: element=%d elementpointer=0x%x", LocalStatus, &ModulOutputs[LocalStatus]);
      return ERR_4;
   }
   return OS_SUCCESS;
}
static STATUS OutputReferenceRoutine(U8 ModuleState)
{
   STATUS LocalStatus = 0;
   // Write Outputdata
   LocalStatus = OS_WriteVariablesConditional(ModulOutputs, MODUL_OUTPUTS_SIZE);
   if (LocalStatus != 0)
   {
      AppSystemLog(ERR_5, MODULE_NAME"WriteVErr: element=%d elementpointer=0x%x", LocalStatus, &ModulOutputs[LocalStatus]);
      return ERR_5;
   }
   return 0;
}

#define WRITE_VARS

//-----------------------------------------------------------------------
// VERIFY VARIABLES CREATION                 VERIFY VARIABLES CREATION
//-----------------------------------------------------------------------

static STATUS LocalIoCheck(void)
{
   // Check if input variables exist.
   STATUS LocalStatus;

   LocalStatus = OS_DoesVariablesExist(ModulInputs, MODUL_INPUTS_SIZE);
   if (LocalStatus != 0)
   {
      AppSystemLog(ERR_1, MODULE_NAME"InputErr: %d", LocalStatus);
      AppSystemLog(ERR_1, "Name: %s", ModulInputs[LocalStatus-1].Name);
      return ERR_1;
   }
   (void)VarsReadTypeCheck();

   LocalStatus = OS_DoesVariablesExist(ModulOutputs, MODUL_OUTPUTS_SIZE);
   if (LocalStatus != 0)
   {
      AppSystemLog(ERR_2, MODULE_NAME"OutputErr: %d", LocalStatus);
      AppSystemLog(ERR_2, "Name: %s", ModulOutputs[LocalStatus-1].Name);
      return ERR_2;
   }
   (void)VarsWriteTypeCheck();

   return OS_SUCCESS;
}

#define VERIFY_VARIABLES

//-----------------------------------------------------------------------
// ALLOCATE MEMORY FOR SUMMATIONS        ALLOCATE MEMORY FOR SUMMATIONS
//-----------------------------------------------------------------------


//-----------------------------------------------------------------------
// SUMMATIONS                  SUMMATIONS                  SUMMATIONS
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// DEFINE MENUS               DEFINE MENUS               DEFINE MENUS
//-----------------------------------------------------------------------



// Menu line and link to local menu
//-----------------------------------------------------------------------
static struct line_struct M_PowerConverterLinkToLocalMenu[] =
{
   MENU_ELEMENT_LINE_LINK("Power Converter",                   PASSWORD_LEVEL_END_CUSTOMER,        "M_PowerConverter",                 "G_Power_Converter"),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_PowerConverterMenu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_PowerConverter",                 PASSWORD_LEVEL_END_CUSTOMER),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_PowerConverterMenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("POWER CONVERTER",                   PASSWORD_LEVEL_END_CUSTOMER,        "M_"APP_ID"AppMain",                "G_"APP_ID"App"),
   MENU_ELEMENT_LINE_VARRO("Converter state",                  PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_CNV_StateTxt",                             LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Requested state",                  PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_CNV_RequestedStateTxt",                    LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Power setpoint",                   PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_CNV_PowerSetpoint",                        LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Torque setpoint kNm",              PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_CNV_TorqueSetpointkNm",                    LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_LINK("Debug",                             PASSWORD_LEVEL_END_CUSTOMER,        "M_Debug",                          "G_Power_Converter"),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_DebugMenu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_Debug",                          PASSWORD_LEVEL_END_CUSTOMER),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_DebugMenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("DEBUG",                             PASSWORD_LEVEL_END_CUSTOMER,        "M_PowerConverter",                 "G_Power_Converter"),
   MENU_ELEMENT_LINE_VARRO("Converter state",                  PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_CNV_State",                                LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Requested state",                  PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_CNV_RequestedState",                       LINE_FORMAT_NONE),
};
// Creating parameters for multiplexed categories
//-----------------------------------------------------------------------
static struct multiplexed_info_struct M_PowerConverterMultiplexedCategoriesParameters[] =
{0
};

//-----------------------------------------------------------------------
// CREATE MENUS               CREATE MENUS               CREATE MENUS
//-----------------------------------------------------------------------

// Memory reservation
//-----------------------------------------------------------------------
static struct menu_group_struct ObjGroup[1];

// Creating the menus
//-----------------------------------------------------------------------
STATUS Power_ConverterMenuAppInit(U8 ModuleState, OS_MEMORY_POOL* pPool)
{
   STATUS Status;

   if (ModuleState == APP_INIT1)
   {
      /* Create application group */
      Status = OS_CreateMenuGroup(ObjGroup, M_PowerConverterLinkToLocalMenu[0].LinkGroup);
      STATUS_LINE_VAR_RETURN_VALUE(Status);
   }

   Status = CreateAndInitializeMenu(ModuleState,
                                    M_PowerConverterMenuLines[0].LinkGroup,
                                    M_PowerConverterMenuLines[0].LinkName,
                                    ELEMENT(M_PowerConverterLinkToLocalMenu),
                                    M_PowerConverterLinkToLocalMenu[0].LinkGroup,
                                    ELEMENT(M_PowerConverterMenu),
                                    M_PowerConverterLinkToLocalMenu[0].LinkName,
                                    ELEMENT(M_PowerConverterMenuLines),
                                    pPool,
                                    M_PowerConverterMultiplexedCategoriesParameters);
   STATUS_LINE_VAR_RETURN_VALUE(Status);

   Status = CreateAndInitializeMenu(ModuleState,
                                    M_DebugMenuLines[0].LinkGroup,
                                    M_DebugMenuLines[0].LinkName,
                                    NULL,
                                    0,
                                    M_PowerConverterMenuLines[5].LinkGroup,
                                    ELEMENT(M_DebugMenu),
                                    M_PowerConverterMenuLines[5].LinkName,
                                    ELEMENT(M_DebugMenuLines),
                                    pPool,
                                    M_PowerConverterMultiplexedCategoriesParameters);
   STATUS_LINE_VAR_RETURN_VALUE(Status);

   return OS_SUCCESS;
}

#define CREATE_MENU

//-----------------------------------------------------------------------
//               BUTTONS FUNCTIONS FORWARD DECLARATIONS
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// BUTTONS                       BUTTONS                      BUTTONS
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
//             SET/RESET FUNCTIONS FORWARD DECLARATIONS
//-----------------------------------------------------------------------
//-----------------------------------------------------------------------
// STATUSCODES                 STATUSCODES                 STATUSCODES
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// MODIFIABLE                  MODIFIABLE                   MODIFIABLE
//-----------------------------------------------------------------------

extern const char Power_ConverterAppGroupName[];
extern const char Power_ConverterAppMenuName[];

static void Init_Structures_From_Conf_File(void)
{
   M_PowerConverterMenuLines[0].LinkName = (char*)Power_ConverterAppMenuName;
   M_PowerConverterMenuLines[0].LinkGroup = (char*)Power_ConverterAppGroupName;
}

//-----------------------------------------------------------------------
// AUTOGENERATED END        AUTOGENERATED END        AUTOGENERATED END
//-----------------------------------------------------------------------
//}

#undef AUTOGENERATED_PART

//-----------------------------------------------------------------------
// USER DEFINITIONS         USER DEFINITIONS         USER DEFINITIONS
//-----------------------------------------------------------------------


//-----------------------------------------------------------------------
// SET/RESET FUNCTIONS    SET/RESET FUNCTIONS    SET/RESET FUNCTIONS
//-----------------------------------------------------------------------


//-----------------------------------------------------------------------
// DRIVER FUNCTION         DRIVER FUNCTION         DRIVER FUNCTION
//-----------------------------------------------------------------------
  
//-----------------------------------------------------------------------
// INIT                   INIT                     INIT
//-----------------------------------------------------------------------

static STATUS Initialize()
{
   S32 result = 0;
   
   return 0;
}
  
//-----------------------------------------------------------------------
// CONTROL                CONTROL                 CONTROL
//-----------------------------------------------------------------------
static void UpdateRequestedStateTxt()
{
    static U8 V_CNV_RequestedState_prev = 0;
    
    if (V_CNV_RequestedState != V_CNV_RequestedState_prev)
    {
        switch(V_CNV_RequestedState)
        {
            case CNV_DISABLED:
                strcpy(V_CNV_RequestedStateTxt, "Disabled");
                break;
            
            case CNV_READYTOSTART:
                strcpy(V_CNV_RequestedStateTxt, "Ready to Start");
                break;
            
            case CNV_FAULT:
                strcpy(V_CNV_RequestedStateTxt, "Fault");
                break;
            
            case CNV_EM_STOP:
                strcpy(V_CNV_RequestedStateTxt, "Em Stop");
                break;
            
            case CNV_STOP:
                strcpy(V_CNV_RequestedStateTxt, "Stop");
                break;
            
            case CNV_GRID_DISCONNECTING:
                strcpy(V_CNV_RequestedStateTxt, "Disconnecting Grid");
                break;
            
            case CNV_GRID_CONNECTING:
                strcpy(V_CNV_RequestedStateTxt, "Connecting Grid");
                break;
            
            case CNV_GRID_CONNECTED:
                strcpy(V_CNV_RequestedStateTxt, "Grid Connected");
                break;
            
            case CNV_GRID_STOPPING:
                strcpy(V_CNV_RequestedStateTxt, "Stopping Grid");
                break;
            
            case CNV_GRID_STARTING:
                strcpy(V_CNV_RequestedStateTxt, "Starting Grid");
                break;
            
            case CNV_GRID_RUNNING:
                strcpy(V_CNV_RequestedStateTxt, "Grid Running");
                break;
            
            case CNV_GEN_DISCONNECTING:
                strcpy(V_CNV_RequestedStateTxt, "Disconnecting Gen");
                break;
            
            case CNV_GEN_CONNECTING:
                strcpy(V_CNV_RequestedStateTxt, "Connecting Gen");
                break;
            
            case CNV_GEN_CONNECTED:
                strcpy(V_CNV_RequestedStateTxt, "Gen Connected");
                break;
            
            case CNV_GEN_STOPPING:
                strcpy(V_CNV_RequestedStateTxt, "Stopping Gen");
                break;
            
            case CNV_GEN_STARTING:
                strcpy(V_CNV_RequestedStateTxt, "Starting Gen");
                break;
            
            case CNV_GEN_RUNNING:
                strcpy(V_CNV_RequestedStateTxt, "Gen Running");
                break;
            
            case CNV_PRODUCTION:
                strcpy(V_CNV_RequestedStateTxt, "Producing");
                break;
            
            case CNV_FRT:
                strcpy(V_CNV_RequestedStateTxt, "FRT");
                break;
            
            case CNV_MOTOR_RUNNING:
                strcpy(V_CNV_RequestedStateTxt, "Motor Running");
                break;
        }
    }
    V_CNV_RequestedState_prev = V_CNV_RequestedState;
}

  
static STATUS LocalCtrl( U32 Interval )
{
   STATUS LocalStatus = 0;
   
   UpdateRequestedStateTxt();
   
   return LocalStatus;
}

static STATUS ShutdownCtrl( U8 ModuleState, U8 *DoneState, U32 Interval )
{
    STATUS LocalStatus = 0;

    LocalStatus = LocalCtrl( Interval );
    STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);

    switch( ModuleState )
    {
        case AS_SHUTDOWN:
        {
            // Activate "Manual Shutdown" status code

            *DoneState = AS_SHUTDOWN;
            break;
        }
        case AS_REBOOT:
        {

            *DoneState = AS_REBOOT;
            break;
        }
        case AS_SHUTDOWN_FAST:
        {

            *DoneState = AS_SHUTDOWN_FAST;
            break;
        }
        default:
        {
            *DoneState = ModuleState;
            break;
        }
    }
    return LocalStatus;
}
 
//-----------------------------------------------------------------------
// MAIN CALL             MAIN CALL               MAIN CALL
//-----------------------------------------------------------------------

STATUS Power_Converter( U8 ModuleState, U8 *DoneState , U32 Interval )
{
   STATUS LocalStatus = 0;

   #ifdef READ_VARS
      // Read input data
      LocalStatus = InputReferenceRoutine(ModuleState);
      STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
   #endif
   #ifdef COMMON_VDB_READ
      LocalStatus = ReadVdbWindow(ModuleState);
      STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
   #endif


   switch( ModuleState )
   {
      //__________________________________________________________________________
      case APP_RUN:
      {
         #ifdef FUNCTION_BLOCKS_PRE_LOCAL_CONTROL
            LocalStatus = FunctionBlocksPreLocalCtrl( Interval );
            STATUS_LINE_VAR_RETURN_VALUE( LocalStatus );
         #endif

         LocalStatus = LocalCtrl( Interval );
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
        
         #ifdef FUNCTION_BLOCKS_POST_LOCAL_CONTROL
            LocalStatus = FunctionBlocksPostLocalCtrl( Interval );
            STATUS_LINE_VAR_RETURN_VALUE( LocalStatus );
         #endif

         #ifdef WRITE_VARS
            // Write Output data
            LocalStatus = OutputReferenceRoutine(ModuleState);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef COMMON_VDB_WRITE
            LocalStatus = WriteVdbWindow(ModuleState);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         *DoneState = APP_RUN;
         break;
      }
      //__________________________________________________________________________
      case APP_INIT1:
      {
         // Version check
         LocalStatus = OS_ValidateAPI( API_VERSION_MAJOR,
                                API_VERSION_MINOR,
                                OS_LinkTime,
                                ReleaseTag,
                                __MODULE__
                               );
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);

         Init_Structures_From_Conf_File();

         #ifdef CREATE_VARDB_VARS
            LocalStatus = CreateVarDbVars();
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef CREATE_MENU
            LocalStatus = Power_ConverterMenuAppInit(ModuleState, GetMemPool());
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);

            #ifdef MULTIPLEXIBLE_MENU
               LocalStatus = MenuArraysAppInit(ModuleState, GetMemPool());
               STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
            #endif
         #endif

         #ifdef CREATE_VARDB_ARRAY_VARS
               LocalStatus = CreateVdbArrays(GetMemPool());
               STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
         #endif


         #ifdef CREATE_IO_VARS
               LocalStatus = CreateIOVars();
               STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
         #endif

         *DoneState = APP_INIT1;

         break;
      }
      //__________________________________________________________________________
      case APP_INIT2:
      {
         #ifdef CREATE_MENU
            #ifdef MULTIPLEXIBLE_MENU
               LocalStatus = MenuArraysAppInit(ModuleState, GetMemPool());
               STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
            #endif
         #endif

         #ifdef CREATE_ALIASES
               size_t ErrorEntry = 0;
               LocalStatus = OS_VarDB_CreateAliases(AliasVars, sizeof(AliasVars)/sizeof(AliasVars[0]), &ErrorEntry);
               STATUS_LINE_VAR_RETURN_CONST(LocalStatus, ErrorEntry);
         #endif

         #ifdef VERIFY_ARRAY
               LocalStatus = VerifyArray(GetMemPool());
               STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef VERIFY_VARIABLES
               LocalStatus = LocalIoCheck();
               STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef CREATE_BUTTONS
               LocalStatus = CreateButtons();
               STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         *DoneState = APP_INIT2;

         break;
      }
      //__________________________________________________________________________
      case APP_INIT3 :
      {
         #ifdef CREATE_SUMMATIONS
            LocalStatus = CreateSummations();
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef WRITE_VARS
            LocalStatus = InitOutputVars();
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef CREATE_STATUS_CODES
            LocalStatus = LocalStatusCodeInit();
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef CREATE_IO_VARS
           Power_ConverterSetLockValues();
         #endif

         *DoneState = APP_INIT3;

         break;
      }
      //__________________________________________________________________________
      case APP_INIT4:
      {
         #ifdef CREATE_MENU
            LocalStatus = Power_ConverterMenuAppInit(ModuleState, GetMemPool());
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);

            #ifdef MULTIPLEXIBLE_MENU
               LocalStatus = MenuArraysAppInit(ModuleState, GetMemPool());
               STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
            #endif
         #endif

         *DoneState = APP_INIT4;

         break;
      }
      //__________________________________________________________________________
      case APP_INIT5:
      {
         #ifdef VALIDATE_HASH
            LocalStatus = ValidateHash( Power_Converter_copyright, MODULE_NAME, Power_Converter_initialValues);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef INIT_FUNCTION_BLOCKS
            LocalStatus = FunctionBlocksInit( Interval );
            STATUS_LINE_VAR_RETURN_VALUE( LocalStatus );
         #endif

         LocalStatus = Initialize();
         STATUS_LINE_VAR_RETURN_VALUE( LocalStatus );

         *DoneState = APP_INIT5_DONE;

         break;
      }
      //__________________________________________________________________________
      //Other initialization round can be inserted here
      //__________________________________________________________________________
      case AS_SHUTDOWN:
      {
         LocalStatus = ShutdownCtrl ( ModuleState, DoneState, Interval );
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);

         #ifdef WRITE_VARS
            // Write Output data
            LocalStatus = OutputReferenceRoutine(ModuleState);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef COMMON_VDB_WRITE
            LocalStatus = WriteVdbWindow(ModuleState);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         break;
      }
      //__________________________________________________________________________
      case AS_REBOOT:
      {
         LocalStatus = ShutdownCtrl ( ModuleState, DoneState, Interval );
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);

         #ifdef WRITE_VARS
            // Write Output data
            LocalStatus = OutputReferenceRoutine(ModuleState);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef COMMON_VDB_WRITE
            LocalStatus = WriteVdbWindow(ModuleState);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         break;
      }
      //__________________________________________________________________________
      case AS_SHUTDOWN_FAST:
      {
         LocalStatus = ShutdownCtrl ( ModuleState, DoneState, Interval );
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);

         #ifdef WRITE_VARS
            // Write Output data
            LocalStatus = OutputReferenceRoutine(ModuleState);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef COMMON_VDB_WRITE
            LocalStatus = WriteVdbWindow(ModuleState);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         break;
      }
      default:
      {
         *DoneState = ModuleState;

         break;
      }
   }
   return OS_SUCCESS;
}
//-----------------------------------------------------------------------
