//*****************************PEPTOOL Header Start******************************
//                                                                               
//                         Copyright © 2015 Mita-Teknik.                         
//This software may only be used with WP4x00 Controllers delivered by Mita-Teknik
//                                                                               
//*******************************************************************************
//                                                                               
// $PEPTOOL version:9.0$                                                         
// $PEPTOOL file version:106$                                                    
//                                                                               
//*******************************************************************************
//                                                                               
// $Date: XXXX/XX/XX XX:XX:XX $                                                  
// $Author: XXXX\XXX $                                                           
// $RCSfile: SafetyChain_MT_GL20102ManStop.c,v $                                 
// $Revision: X.X $                                                              
//                                                                               
//******************************PEPTOOL Header End*******************************

//***********************************************************************

// OS header files
#include <os_main.h>
// AppLib header files
#include <lib_main.h>
// App header files
#include <turbdef.h>
#include <VarMacros.h>

// Object header file
#include <SafetyChain_MT_GL20102ManStop.h>

#define AUTOGENERATED_PART
//{
//-----------------------------------------------------------------------
// AUTOGENERATED START     AUTOGENERATED START     AUTOGENERATED START
//-----------------------------------------------------------------------

#define VALIDATE_HASH
char SafetyChain_MT_GL20102ManStop_copyright[] =
{
   67, 111, 112, 121, 114, 105, 103, 104, 116, 32, 63, 32, 50, 48, 49, 53,
   32, 77, 105, 116, 97, 45, 84, 101, 107, 110, 105, 107, 46, 13, 10, 84,
   104, 105, 115, 32, 115, 111, 102, 116, 119, 97, 114, 101, 32, 109, 97, 121,
   32, 111, 110, 108, 121, 32, 98, 101, 32, 117, 115, 101, 100, 32, 119, 105,
   116, 104, 32, 87, 80, 52, 120, 48, 48, 32, 67, 111, 110, 116, 114, 111,
   108, 108, 101, 114, 115, 32, 100, 101, 108, 105, 118, 101, 114, 101, 100, 32,
   98, 121, 32, 77, 105, 116, 97, 45, 84, 101, 107, 110, 105, 107, 0
};

#define MODULE_NAME "Safety ChainA"

//-----------------------------------------------------------------------
// ALLOCATE MEMORY FOR STRINGS IN VARDB
//-----------------------------------------------------------------------

static char A_V_SafetySystemSCStatusText[31]  = "12345678901234567890123456789";
static char A_V_SafetySystemSCSelftestStepText[31]  = "12345678901234567890123456789";

//-----------------------------------------------------------------------
// DEFINE LOCAL VARIABLES DEFINE LOCAL VARIABLES DEFINE LOCAL VARIABLES
//-----------------------------------------------------------------------

static struct os_db_local LocalVars[] =
{
   VAR_ELEMENT_LOCAL("V_SafetySystemSCStatusText",               TYPE_STRING + sizeof(A_V_SafetySystemSCStatusText) - 1,  PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   A_V_SafetySystemSCStatusText, 0,                0,                NULL,  NOLOG_ENABLE  ),
   VAR_ELEMENT_LOCAL("V_SafetySystemSCStatus",                   TYPE_U16,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   0,               0,               2,               NULL,  TOTLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_SafetySystemRequestSafetyStop",          TYPE_U8,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   0,               0,               1,               NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_SafetySystemInvertK1WP2035",             TYPE_U8,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   0,               0,               1,               NULL,  TOTLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_SafetySystemInvertK2WP2035",             TYPE_U8,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   0,               0,               1,               NULL,  TOTLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_SafetySystemSCSelftestSuccess",          TYPE_U8,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   0,               0,               1,               NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_SafetySystemSCSelftestInProgress",       TYPE_U8,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   0,               0,               1,               NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_SafetySystemSCSelftestStep",             TYPE_U8,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   0,               U8_MIN,          U8_MAX,          NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_SafetySystemSCSelftestStepText",         TYPE_STRING + sizeof(A_V_SafetySystemSCSelftestStepText) - 1,  PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   A_V_SafetySystemSCSelftestStepText, 0,                0,                NULL,  NOLOG_ENABLE  ),
   VAR_ELEMENT_LOCAL("V_SafetySystemSafetyStopControllerService",TYPE_U8,      PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_SERVICE,            SCALE_NONE,   0,       UNIT_NONE,          0,   0,               0,               1,               NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_SafetySystemSCSelftestForce",            TYPE_U8,      PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_SERVICE,            SCALE_NONE,   0,       UNIT_NONE,          0,   0,               0,               1,               NULL,  NOLOG_ENABLE),
};

//-----------------------------------------------------------------------
// DEFINE PARAMETERS        DEFINE PARAMETERS        DEFINE PARAMETERS
//-----------------------------------------------------------------------

static struct os_db_parameter ParameterVars[] =
{
   VAR_ELEMENT_PARAMETER("P_SafetySystemWP2035SelftestInterval",     TYPE_U32,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         SCALE_DIV,    86400000,UNIT_DAY,           2,   604800000,       86400000,        604800000,       NULL  ),
};

//-----------------------------------------------------------------------
// DEFINE BACKUPS            DEFINE BACKUPS            DEFINE BACKUPS
//-----------------------------------------------------------------------

static struct os_db_backup BackupVars[] =
{
   VAR_ELEMENT_BACKUP("B_SafetySystemSafetyChainTimeXCK1",        TYPE_TIME,    PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_SERVICE,            SCALE_NONE,   0,       UNIT_NONE,          0,   (0ULL),          ((U8)U8_MIN),    ((U8)U8_MAX),    NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_BACKUP("B_SafetySystemSafetyChainTimeXCK2",        TYPE_TIME,    PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_SERVICE,            SCALE_NONE,   0,       UNIT_NONE,          0,   (0ULL),          ((U8)U8_MIN),    ((U8)U8_MAX),    NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_BACKUP("B_SafetySystemSafetyChainTimeK1WP2035",    TYPE_TIME,    PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_SERVICE,            SCALE_NONE,   0,       UNIT_NONE,          0,   (0ULL),          ((U8)U8_MIN),    ((U8)U8_MAX),    NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_BACKUP("B_SafetySystemSafetyChainTimeK2WP2035",    TYPE_TIME,    PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_SERVICE,            SCALE_NONE,   0,       UNIT_NONE,          0,   (0ULL),          ((U8)U8_MIN),    ((U8)U8_MAX),    NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_BACKUP("B_SafetySystemSafetyChainTimeSCMS",        TYPE_TIME,    PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_SERVICE,            SCALE_NONE,   0,       UNIT_NONE,          0,   (0ULL),          ((U8)U8_MIN),    ((U8)U8_MAX),    NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_BACKUP("B_SafetySystemSafetyChainTimeCONV",        TYPE_TIME,    PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_SERVICE,            SCALE_NONE,   0,       UNIT_NONE,          0,   (0ULL),          ((U8)U8_MIN),    ((U8)U8_MAX),    NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_BACKUP("B_SafetySystemSafetyChainTimeMCCB",        TYPE_TIME,    PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_SERVICE,            SCALE_NONE,   0,       UNIT_NONE,          0,   (0ULL),          ((U8)U8_MIN),    ((U8)U8_MAX),    NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_BACKUP("B_SafetySystemSafetyChainTimeOSCR",        TYPE_TIME,    PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_SERVICE,            SCALE_NONE,   0,       UNIT_NONE,          0,   (0ULL),          ((U8)U8_MIN),    ((U8)U8_MAX),    NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_BACKUP("B_SafetySystemSCSelftestDueIn",            TYPE_U32,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    3600000, UNIT_HOUR,          2,   604800000,       0,               604800000,       NULL,  TOTLOG_ENABLE),
   VAR_ELEMENT_BACKUP("B_SafetySystemSafetyStopControllerService",TYPE_U8,      PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_SERVICE,            SCALE_NONE,   0,       UNIT_NONE,          0,   0,               0,               1,               NULL,  NOLOG_ENABLE),
};

//----------------------------------------------------------------------------------
// DEFINE VAR ARRAYS            DEFINE VAR ARRAYS            DEFINE VAR ARRAYS
//----------------------------------------------------------------------------------
char SafetyChain_MT_GL20102ManStop_initialValues[] =
{
   179, 235, 17, 117, 37, 26, 240, 124, 23, 213, 157, 1, 50, 46, 149, 103,
   51, 172, 22, 64, 168, 142, 89, 81, 91, 204, 35, 27, 252, 253, 27, 0,
   0
};

//-----------------------------------------------------------------------
// CREATE DATABASE VARS   CREATE DATABASE VARS   CREATE DATABASE VARS
//-----------------------------------------------------------------------

static STATUS CreateVarDbVars(void)
{
   STATUS Status;
   size_t ErrorEntry;

   Status = OS_VarDB_CreateLocals(LocalVars, sizeof(LocalVars)/sizeof(LocalVars[0]), &ErrorEntry, AppLocalParameterPosition());
   if (Status != 0)
   {
      AppSystemLog(ERR_7, MODULE_NAME"CrVL: %d,%d", Status, ErrorEntry);
      return ERR_7;
   }

   Status = OS_VarDB_CreateParameters(ParameterVars, sizeof(ParameterVars)/sizeof(ParameterVars[0]), &ErrorEntry, AppExportParameterPosition());
   if (Status != 0)
   {
      AppSystemLog(ERR_7, MODULE_NAME"CrVXP: %d,%d", Status, ErrorEntry);
      return ERR_7;
   }

   Status = OS_VarDB_CreateBackups(BackupVars, sizeof(BackupVars)/sizeof(BackupVars[0]), &ErrorEntry, AppLocalParameterPosition(), AppBackupPosition());
   if (Status != 0)
   {
      AppSystemLog(ERR_7, MODULE_NAME"CrVB: %d,%d", Status, ErrorEntry);
      return ERR_7;
   }

   return OS_SUCCESS;
}

#define CREATE_VARDB_VARS

//-----------------------------------------------------------------------
// CREATE IO VARIABLES     CREATE IO VARIABLES     CREATE IO VARIABLES
//-----------------------------------------------------------------------

extern STATUS SafetyChain_MT_GL20102ManStopInitIOAliases();
extern struct os_db_alias* SafetyChain_MT_GL20102ManStopIOVars;
extern void (*SafetyChain_MT_GL20102ManStopSetLockValues)(void);
extern size_t SafetyChain_MT_GL20102ManStopIOVarsSize;

static STATUS CreateIOVars(void)
{
   STATUS Status;
   size_t ErrorEntry;

   varid_t VarId;
   BOOL variablesExist = false;
   U8 counter = 50;
   Status = SafetyChain_MT_GL20102ManStopInitIOAliases();
   STATUS_LINE_VAR_RETURN_VALUE(Status)
   while (!variablesExist && counter-- > 0)
   {
      variablesExist = true;
      U32 i = 0;
      for (i = 0; i < SafetyChain_MT_GL20102ManStopIOVarsSize; ++i)
      {
         if (OS_VarDB_GetVariableID(SafetyChain_MT_GL20102ManStopIOVars[i].Name, &VarId) != OS_SUCCESS)
         {
            variablesExist = false;
            break;
         }
      }

      if (!variablesExist)
      {
         OS_Sleep(100);
      }
   }

   Status = OS_VarDB_CreateAliases(SafetyChain_MT_GL20102ManStopIOVars, SafetyChain_MT_GL20102ManStopIOVarsSize, &ErrorEntry);
   if (Status)
   {
      AppDebugLog(5000, "Var Name = %s", SafetyChain_MT_GL20102ManStopIOVars[ErrorEntry].Alias);
   }
   STATUS_LINE_VAR_RETURN_CONST(Status, ErrorEntry);
   return OS_SUCCESS;
}

#define CREATE_IO_VARS

//-----------------------------------------------------------------------
// ALIASES                       ALIASES                       ALIASES
//-----------------------------------------------------------------------

static struct os_db_alias AliasVars[] =
{
   VAR_ELEMENT_ALIAS("DI_SafetySystemK1WP2035",                  "DI_FeedbackGeneratorOverspeed"),
   VAR_ELEMENT_ALIAS("DI_SafetySystemK2WP2035",                  "DI_FeedbackRotorOverspeed"),
};

#define CREATE_ALIASES

//-----------------------------------------------------------------------
// INPUT                          INPUT                          INPUT
//-----------------------------------------------------------------------

// Create local variable
#define MODUL_INPUTS
static U8 DI_SafetySystemXCK1 = 0;
static U8 DI_SafetySystemXCK2 = 0;
static U8 DI_SafetySystemK1WP2035 = 0;
static U8 DI_SafetySystemK2WP2035 = 0;
static U8 DI_SafetySystemKSSR = 0;
static U8 DI_SafetySystemSCMS = 0;
static U8 DI_SafetySystemCONV = 0;
static U8 DI_SafetySystemMCCB = 0;
static U8 B_SafetySystemSafetyStopControllerService = 0;
static U8 V_GridErrorActive = 0;
static U8 V_SafetySystemExecuteSelftest = 0;
static U8 V_SafetySystemRequestSafetyStop = 0;
static U8 V_SafetySystemSCSelftestForce = 0;
static U8 V_SafetySystemSCSelftestStep = 0;
static U8 V_SafetySystemSCSelftestInProgress = 0;
static U8 V_BladeControllerSafetyChainOk = 0;
static U8 Chain_Out_Signal = 0;
static U8 Chain_In_Signal = 0;
static U8 Chain_Enable = 0;
static U32 P_SafetySystemWP2035SelftestInterval = 0;

//-----------------------------------------------------------------------
static struct ModulInOut ModulInputs[] =
{
   {"DI_SafetySystemXCK1",                      &DI_SafetySystemXCK1,                      sizeof(DI_SafetySystemXCK1),                      },
   {"DI_SafetySystemXCK2",                      &DI_SafetySystemXCK2,                      sizeof(DI_SafetySystemXCK2),                      },
   {"DI_SafetySystemK1WP2035",                  &DI_SafetySystemK1WP2035,                  sizeof(DI_SafetySystemK1WP2035),                  },
   {"DI_SafetySystemK2WP2035",                  &DI_SafetySystemK2WP2035,                  sizeof(DI_SafetySystemK2WP2035),                  },
   {"DI_SafetySystemKSSR",                      &DI_SafetySystemKSSR,                      sizeof(DI_SafetySystemKSSR),                      },
   {"DI_SafetySystemSCMS",                      &DI_SafetySystemSCMS,                      sizeof(DI_SafetySystemSCMS),                      },
   {"DI_SafetySystemCONV",                      &DI_SafetySystemCONV,                      sizeof(DI_SafetySystemCONV),                      },
   {"DI_SafetySystemMCCB",                      &DI_SafetySystemMCCB,                      sizeof(DI_SafetySystemMCCB),                      },
   {"B_SafetySystemSafetyStopControllerService",&B_SafetySystemSafetyStopControllerService,sizeof(B_SafetySystemSafetyStopControllerService),},
   {"V_GridErrorActive",                        &V_GridErrorActive,                        sizeof(V_GridErrorActive),                        },
   {"V_SafetySystemExecuteSelftest",            &V_SafetySystemExecuteSelftest,            sizeof(V_SafetySystemExecuteSelftest),            },
   {"V_SafetySystemRequestSafetyStop",          &V_SafetySystemRequestSafetyStop,          sizeof(V_SafetySystemRequestSafetyStop),          },
   {"V_SafetySystemSCSelftestForce",            &V_SafetySystemSCSelftestForce,            sizeof(V_SafetySystemSCSelftestForce),            },
   {"V_SafetySystemSCSelftestStep",             &V_SafetySystemSCSelftestStep,             sizeof(V_SafetySystemSCSelftestStep),             },
   {"V_SafetySystemSCSelftestInProgress",       &V_SafetySystemSCSelftestInProgress,       sizeof(V_SafetySystemSCSelftestInProgress),       },
   {"V_BladeControllerSafetyChainOk",           &V_BladeControllerSafetyChainOk,           sizeof(V_BladeControllerSafetyChainOk),           },
   {"Chain_Out_Signal",                         &Chain_Out_Signal,                         sizeof(Chain_Out_Signal),                         },
   {"Chain_In_Signal",                          &Chain_In_Signal,                          sizeof(Chain_In_Signal),                          },
   {"Chain_Enable",                             &Chain_Enable,                             sizeof(Chain_Enable),                             },
   {"P_SafetySystemWP2035SelftestInterval",     &P_SafetySystemWP2035SelftestInterval,     sizeof(P_SafetySystemWP2035SelftestInterval),     },
};

//-----------------------------------------------------------------------
// Check variable type
static STATUS VarsReadReturnStatus;
static type_t ReadVarType = TYPE_NONE;
static void VarsReadTypeCheck(void)
{
   (void)VarsReadReturnStatus;
   (void)ReadVarType;
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[0].Name,                      ModulInputs[0].Id)
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[1].Name,                      ModulInputs[1].Id)
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[2].Name,                      ModulInputs[2].Id)
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[3].Name,                      ModulInputs[3].Id)
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[4].Name,                      ModulInputs[4].Id)
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[5].Name,                      ModulInputs[5].Id)
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[6].Name,                      ModulInputs[6].Id)
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[7].Name,                      ModulInputs[7].Id)
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[8].Name,                      ModulInputs[8].Id)
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[9].Name,                      ModulInputs[9].Id)
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[10].Name,                     ModulInputs[10].Id)
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[11].Name,                     ModulInputs[11].Id)
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[12].Name,                     ModulInputs[12].Id)
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[13].Name,                     ModulInputs[13].Id)
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[14].Name,                     ModulInputs[14].Id)
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[15].Name,                     ModulInputs[15].Id)
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[16].Name,                     ModulInputs[16].Id)
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[17].Name,                     ModulInputs[17].Id)
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[18].Name,                     ModulInputs[18].Id)
   VERIFY_INPUT_REF_ID(U32,       ModulInputs[19].Name,                     ModulInputs[19].Id)
}

#undef MODUL_INPUTS
#define MODUL_INPUTS_SIZE (sizeof(ModulInputs)/sizeof(ModulInputs[0]))

//------------------------------------------------------------------------------------------
// READ/WRITE VARDB ARRAY      READ/WRITE VARDB ARRAY      READ/WRATE VARDB ARRAY
//------------------------------------------------------------------------------------------


//-----------------------------------------------------------------------
// PARAMETER                    PARAMETER                    PARAMETER
//-----------------------------------------------------------------------


//-----------------------------------------------------------------------
// READ VARS FROM VARDB    READ VARS FROM VARDB    READ VARS FROM VARDB
//-----------------------------------------------------------------------

static STATUS InputReferenceRoutine(U8 ModuleState)
{
   STATUS LocalStatus = 0;

   // Read input references
   if (ModuleState >= APP_INIT3)
   {
      // Check inputdata
      if (sizeof(ModulInputs) == 0)
      {
         AppSystemLog(ERR_4, MODULE_NAME"ModuleInputs = 0");
         return ERR_4;
      }
      // Read inputdata
      LocalStatus = OS_ReadVariables(ModulInputs, MODUL_INPUTS_SIZE);
      if (LocalStatus != 0)
      {
         AppSystemLog(ERR_4, MODULE_NAME"ReadVErr: element=%d elementpointer=0x%x", LocalStatus, &ModulInputs[LocalStatus]);
         return ERR_4;
      }
   }
   return 0;
}

#define READ_VARS

//-----------------------------------------------------------------------
// OUTPUT                         OUTPUT                         OUTPUT
//-----------------------------------------------------------------------

// Create local variable
#define MODUL_OUTPUTS
static U8 DO_SafetySystemOSCR = 0;
static U8 V_SafetySystemInvertK1WP2035 = 0;
static U8 V_SafetySystemInvertK2WP2035 = 0;
static U32 B_SafetySystemSCSelftestDueIn = 0;
static time_t B_SafetySystemSafetyChainTimeXCK1 = 0;
static time_t B_SafetySystemSafetyChainTimeXCK2 = 0;
static time_t B_SafetySystemSafetyChainTimeK1WP2035 = 0;
static time_t B_SafetySystemSafetyChainTimeK2WP2035 = 0;
static time_t B_SafetySystemSafetyChainTimeSCMS = 0;
static time_t B_SafetySystemSafetyChainTimeCONV = 0;
static time_t B_SafetySystemSafetyChainTimeMCCB = 0;
static time_t B_SafetySystemSafetyChainTimeOSCR = 0;
static U8 V_SafetySystemSCSelftestSuccess = 0;
static U16 V_SafetySystemSCStatus = 0;
static char V_SafetySystemSCStatusText[31];
static char V_SafetySystemSCSelftestStepText[31];


//-----------------------------------------------------------------------
static struct ModulInOut ModulOutputs[] =
{
   {"DO_SafetySystemOSCR",                      &DO_SafetySystemOSCR,                      sizeof(DO_SafetySystemOSCR),                      },
   {"V_SafetySystemInvertK1WP2035",             &V_SafetySystemInvertK1WP2035,             sizeof(V_SafetySystemInvertK1WP2035),             },
   {"V_SafetySystemInvertK2WP2035",             &V_SafetySystemInvertK2WP2035,             sizeof(V_SafetySystemInvertK2WP2035),             },
   {"B_SafetySystemSCSelftestDueIn",            &B_SafetySystemSCSelftestDueIn,            sizeof(B_SafetySystemSCSelftestDueIn),            },
   {"B_SafetySystemSafetyChainTimeXCK1",        &B_SafetySystemSafetyChainTimeXCK1,        sizeof(B_SafetySystemSafetyChainTimeXCK1),        },
   {"B_SafetySystemSafetyChainTimeXCK2",        &B_SafetySystemSafetyChainTimeXCK2,        sizeof(B_SafetySystemSafetyChainTimeXCK2),        },
   {"B_SafetySystemSafetyChainTimeK1WP2035",    &B_SafetySystemSafetyChainTimeK1WP2035,    sizeof(B_SafetySystemSafetyChainTimeK1WP2035),    },
   {"B_SafetySystemSafetyChainTimeK2WP2035",    &B_SafetySystemSafetyChainTimeK2WP2035,    sizeof(B_SafetySystemSafetyChainTimeK2WP2035),    },
   {"B_SafetySystemSafetyChainTimeSCMS",        &B_SafetySystemSafetyChainTimeSCMS,        sizeof(B_SafetySystemSafetyChainTimeSCMS),        },
   {"B_SafetySystemSafetyChainTimeCONV",        &B_SafetySystemSafetyChainTimeCONV,        sizeof(B_SafetySystemSafetyChainTimeCONV),        },
   {"B_SafetySystemSafetyChainTimeMCCB",        &B_SafetySystemSafetyChainTimeMCCB,        sizeof(B_SafetySystemSafetyChainTimeMCCB),        },
   {"B_SafetySystemSafetyChainTimeOSCR",        &B_SafetySystemSafetyChainTimeOSCR,        sizeof(B_SafetySystemSafetyChainTimeOSCR),        },
   {"V_SafetySystemSCSelftestSuccess",          &V_SafetySystemSCSelftestSuccess,          sizeof(V_SafetySystemSCSelftestSuccess),          },
   {"V_SafetySystemSCSelftestInProgress",       &V_SafetySystemSCSelftestInProgress,       sizeof(V_SafetySystemSCSelftestInProgress),       },
   {"V_SafetySystemSCStatusText",               &V_SafetySystemSCStatusText,               sizeof(V_SafetySystemSCStatusText),               },
   {"V_SafetySystemSCStatus",                   &V_SafetySystemSCStatus,                   sizeof(V_SafetySystemSCStatus),                   },
   {"V_SafetySystemSCSelftestStep",             &V_SafetySystemSCSelftestStep,             sizeof(V_SafetySystemSCSelftestStep),             },
   {"V_SafetySystemSCSelftestStepText",         &V_SafetySystemSCSelftestStepText,         sizeof(V_SafetySystemSCSelftestStepText),         },
};

//-----------------------------------------------------------------------
// Check variable type
static STATUS VarsWriteReturnStatus;
static type_t WriteVarType = TYPE_NONE;
static void VarsWriteTypeCheck(void)
{
   (void)VarsWriteReturnStatus;
   (void)WriteVarType;
   VERIFY_OUTPUT_REF_ID(U8,        ModulOutputs[0].Name,                     ModulOutputs[0].Id,                       0)
   VERIFY_OUTPUT_REF_ID(U8,        ModulOutputs[1].Name,                     ModulOutputs[1].Id,                       0)
   VERIFY_OUTPUT_REF_ID(U8,        ModulOutputs[2].Name,                     ModulOutputs[2].Id,                       0)
   VERIFY_OUTPUT_REF_ID(U32,       ModulOutputs[3].Name,                     ModulOutputs[3].Id,                       0)
   VERIFY_OUTPUT_TIME_REF_ID(time_t,       ModulOutputs[4].Name,                     ModulOutputs[4].Id,                       0)
   VERIFY_OUTPUT_TIME_REF_ID(time_t,       ModulOutputs[5].Name,                     ModulOutputs[5].Id,                       0)
   VERIFY_OUTPUT_TIME_REF_ID(time_t,       ModulOutputs[6].Name,                     ModulOutputs[6].Id,                       0)
   VERIFY_OUTPUT_TIME_REF_ID(time_t,       ModulOutputs[7].Name,                     ModulOutputs[7].Id,                       0)
   VERIFY_OUTPUT_TIME_REF_ID(time_t,       ModulOutputs[8].Name,                     ModulOutputs[8].Id,                       0)
   VERIFY_OUTPUT_TIME_REF_ID(time_t,       ModulOutputs[9].Name,                     ModulOutputs[9].Id,                       0)
   VERIFY_OUTPUT_TIME_REF_ID(time_t,       ModulOutputs[10].Name,                    ModulOutputs[10].Id,                      0)
   VERIFY_OUTPUT_TIME_REF_ID(time_t,       ModulOutputs[11].Name,                    ModulOutputs[11].Id,                      0)
   VERIFY_OUTPUT_REF_ID(U8,        ModulOutputs[12].Name,                    ModulOutputs[12].Id,                      0)
   VERIFY_OUTPUT_REF_ID(U8,        ModulOutputs[13].Name,                    ModulOutputs[13].Id,                      0)
   VERIFY_OUTPUT_STRING_REF_ID(STRING,     ModulOutputs[14].Name,                     ModulOutputs[14].Id, 0)
   VERIFY_OUTPUT_REF_ID(U16,       ModulOutputs[15].Name,                    ModulOutputs[15].Id,                      0)
   VERIFY_OUTPUT_REF_ID(U8,        ModulOutputs[16].Name,                    ModulOutputs[16].Id,                      0)
   VERIFY_OUTPUT_STRING_REF_ID(STRING,     ModulOutputs[17].Name,                     ModulOutputs[17].Id, 0)
}

#undef MODUL_OUTPUTS
#define MODUL_OUTPUTS_SIZE (sizeof(ModulOutputs)/sizeof(ModulOutputs[0]))

//-----------------------------------------------------------------------
// WRITE VARS TO VARDB     WRITE VARS TO VARDB     WRITE VARS TO VARDB
//-----------------------------------------------------------------------

static STATUS InitOutputVars(void)
{
   STATUS LocalStatus;
   // Read outputdata
   LocalStatus = OS_ReadVariables(ModulOutputs, MODUL_OUTPUTS_SIZE);
   if (LocalStatus != 0)
   {
      AppSystemLog(ERR_4, MODULE_NAME"InitErr: element=%d elementpointer=0x%x", LocalStatus, &ModulOutputs[LocalStatus]);
      return ERR_4;
   }
   return OS_SUCCESS;
}
static STATUS OutputReferenceRoutine(U8 ModuleState)
{
   STATUS LocalStatus = 0;
   // Write Outputdata
   LocalStatus = OS_WriteVariablesConditional(ModulOutputs, MODUL_OUTPUTS_SIZE);
   if (LocalStatus != 0)
   {
      AppSystemLog(ERR_5, MODULE_NAME"WriteVErr: element=%d elementpointer=0x%x", LocalStatus, &ModulOutputs[LocalStatus]);
      return ERR_5;
   }
   return 0;
}

#define WRITE_VARS

//-----------------------------------------------------------------------
// VERIFY VARIABLES CREATION                 VERIFY VARIABLES CREATION
//-----------------------------------------------------------------------

static STATUS LocalIoCheck(void)
{
   // Check if input variables exist.
   STATUS LocalStatus;

   LocalStatus = OS_DoesVariablesExist(ModulInputs, MODUL_INPUTS_SIZE);
   if (LocalStatus != 0)
   {
      AppSystemLog(ERR_1, MODULE_NAME"InputErr: %d", LocalStatus);
      AppSystemLog(ERR_1, "Name: %s", ModulInputs[LocalStatus-1].Name);
      return ERR_1;
   }
   (void)VarsReadTypeCheck();

   LocalStatus = OS_DoesVariablesExist(ModulOutputs, MODUL_OUTPUTS_SIZE);
   if (LocalStatus != 0)
   {
      AppSystemLog(ERR_2, MODULE_NAME"OutputErr: %d", LocalStatus);
      AppSystemLog(ERR_2, "Name: %s", ModulOutputs[LocalStatus-1].Name);
      return ERR_2;
   }
   (void)VarsWriteTypeCheck();

   return OS_SUCCESS;
}

#define VERIFY_VARIABLES

//-----------------------------------------------------------------------
// ALLOCATE MEMORY FOR SUMMATIONS        ALLOCATE MEMORY FOR SUMMATIONS
//-----------------------------------------------------------------------


//-----------------------------------------------------------------------
// SUMMATIONS                  SUMMATIONS                  SUMMATIONS
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// DEFINE MENUS               DEFINE MENUS               DEFINE MENUS
//-----------------------------------------------------------------------



// Menu line and link to local menu
//-----------------------------------------------------------------------
static struct line_struct M_SafetyChainLinkToLocalMenu[] =
{
   MENU_ELEMENT_LINE_LINK("Safety Chain",                      PASSWORD_LEVEL_END_CUSTOMER,        "M_SafetyChain",                    "G_SafetyChain_MT_GL20102ManStop"),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_SafetyChainMenu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_SafetyChain",                    PASSWORD_LEVEL_END_CUSTOMER),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_SafetyChainMenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("SAFETY CHAIN",                      PASSWORD_LEVEL_END_CUSTOMER,        "M_"APP_ID"AppMain",                "G_"APP_ID"App"),
   MENU_ELEMENT_LINE_VARRO("Safety Chain Status",              PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_SafetySystemSCStatusText",                 LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_LINK("Status",                            PASSWORD_LEVEL_END_CUSTOMER,        "M_Status531",                      "G_SafetyChain_MT_GL20102ManStop"),
   MENU_ELEMENT_LINE_LINK("Parameter",                         PASSWORD_LEVEL_END_CUSTOMER,        "M_Parameter771",                   "G_SafetyChain_MT_GL20102ManStop"),
   MENU_ELEMENT_LINE_LINK("Service",                           PASSWORD_LEVEL_SERVICE,             "M_Service401",                     "G_SafetyChain_MT_GL20102ManStop"),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_Status531Menu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_Status531",                      PASSWORD_LEVEL_END_CUSTOMER),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_Status531MenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("STATUS",                            PASSWORD_LEVEL_END_CUSTOMER,        "M_SafetyChain",                    "G_SafetyChain_MT_GL20102ManStop"),
   MENU_ELEMENT_LINE_VARRO("(G) Overspeed (K1-WP2035)",        PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_SafetySystemInvertK1WP2035",               LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("(R) Overspeed (K2-WP2035)",        PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_SafetySystemInvertK2WP2035",               LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Shock Sensor 1 (XCK 1)",           PASSWORD_LEVEL_END_CUSTOMER,        (char*)"DI_SafetySystemXCK1",                        LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Shock Sensor 2 (XCK 2)",           PASSWORD_LEVEL_END_CUSTOMER,        (char*)"DI_SafetySystemXCK2",                        LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("MCCB Over Current (MCCB)",         PASSWORD_LEVEL_END_CUSTOMER,        (char*)"DI_SafetySystemMCCB",                        LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("(I) Safety Stop (CONV)",           PASSWORD_LEVEL_END_CUSTOMER,        (char*)"DI_SafetySystemCONV",                        LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Controller Chain In",              PASSWORD_LEVEL_END_CUSTOMER,        (char*)"Chain_In_Signal",                            LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Controller Chain Out",             PASSWORD_LEVEL_END_CUSTOMER,        (char*)"Chain_Out_Signal",                           LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Blade Controller",                 PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_BladeControllerSafetyChainOk",             LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Control System Open Safety Chain (OSCR)", PASSWORD_LEVEL_END_CUSTOMER,        (char*)"DO_SafetySystemOSCR",                        LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Safety Chain Relay (KSSR)",        PASSWORD_LEVEL_END_CUSTOMER,        (char*)"DI_SafetySystemKSSR",                        LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Yaw-Safety Chain Mode Switch (SCMS)", PASSWORD_LEVEL_END_CUSTOMER,        (char*)"DI_SafetySystemSCMS",                        LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_LINK("Selftest",                          PASSWORD_LEVEL_END_CUSTOMER,        "M_Selftest641",                    "G_SafetyChain_MT_GL20102ManStop"),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_Selftest641Menu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_Selftest641",                    PASSWORD_LEVEL_END_CUSTOMER),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_Selftest641MenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("SELFTEST",                          PASSWORD_LEVEL_END_CUSTOMER,        "M_Status531",                      "G_SafetyChain_MT_GL20102ManStop"),
   MENU_ELEMENT_LINE_VARRO("Next WP2035 Selftest Due in",      PASSWORD_LEVEL_END_CUSTOMER,        (char*)"B_SafetySystemSCSelftestDueIn",              LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Selftest Step",                    PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_SafetySystemSCSelftestStepText",           LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Selftest In Progress",             PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_SafetySystemSCSelftestInProgress",         LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Selftest Success",                 PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_SafetySystemSCSelftestSuccess",            LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Selftest Execute",                 PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_SafetySystemExecuteSelftest",              LINE_FORMAT_NONE),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_Parameter771Menu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_Parameter771",                   PASSWORD_LEVEL_END_CUSTOMER),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_Parameter771MenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("PARAMETER",                         PASSWORD_LEVEL_END_CUSTOMER,        "M_SafetyChain",                    "G_SafetyChain_MT_GL20102ManStop"),
   MENU_ELEMENT_LINE_VARRW("WP2035 Selftest Min. Interval",    PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_SafetySystemWP2035SelftestInterval",       LINE_FORMAT_NONE),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_Service401Menu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_Service401",                     PASSWORD_LEVEL_SERVICE),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_Service401MenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("SERVICE",                           PASSWORD_LEVEL_SERVICE,             "M_SafetyChain",                    "G_SafetyChain_MT_GL20102ManStop"),
   MENU_ELEMENT_LINE_VARRW("Manual Safety Stop (OSCR)",        PASSWORD_LEVEL_SERVICE,             (char*)"B_SafetySystemSafetyStopControllerService",  LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Manual Force Selftest",            PASSWORD_LEVEL_SERVICE,             (char*)"V_SafetySystemSCSelftestForce",              LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_TEXT("Last Time Activations:",            PASSWORD_LEVEL_SERVICE),
   MENU_ELEMENT_LINE_VARRO("(G) Overspeed",                    PASSWORD_LEVEL_SERVICE,             (char*)"B_SafetySystemSafetyChainTimeK1WP2035",      LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("(R) Overspeed",                    PASSWORD_LEVEL_SERVICE,             (char*)"B_SafetySystemSafetyChainTimeK2WP2035",      LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Shock Sensor 1",                   PASSWORD_LEVEL_SERVICE,             (char*)"B_SafetySystemSafetyChainTimeXCK1",          LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Shock Sensor 2",                   PASSWORD_LEVEL_SERVICE,             (char*)"B_SafetySystemSafetyChainTimeXCK2",          LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Inverter",                         PASSWORD_LEVEL_SERVICE,             (char*)"B_SafetySystemSafetyChainTimeCONV",          LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("MCCB",                             PASSWORD_LEVEL_SERVICE,             (char*)"B_SafetySystemSafetyChainTimeMCCB",          LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Control System",                   PASSWORD_LEVEL_SERVICE,             (char*)"B_SafetySystemSafetyChainTimeOSCR",          LINE_FORMAT_NONE),
};
// Creating parameters for multiplexed categories
//-----------------------------------------------------------------------
static struct multiplexed_info_struct M_SafetyChainMultiplexedCategoriesParameters[] =
{
0};

//-----------------------------------------------------------------------
// CREATE MENUS               CREATE MENUS               CREATE MENUS
//-----------------------------------------------------------------------

// Memory reservation
//-----------------------------------------------------------------------
static struct menu_group_struct ObjGroup[1];

// Creating the menus
//-----------------------------------------------------------------------
STATUS SafetyChain_MT_GL20102ManStopMenuAppInit(U8 ModuleState, OS_MEMORY_POOL* pPool)
{
   STATUS Status;

   if (ModuleState == APP_INIT1)
   {
      /* Create application group */
      Status = OS_CreateMenuGroup(ObjGroup, M_SafetyChainLinkToLocalMenu[0].LinkGroup);
      STATUS_LINE_VAR_RETURN_VALUE(Status);
   }

   Status = CreateAndInitializeMenu(ModuleState,
                                    M_SafetyChainMenuLines[0].LinkGroup,
                                    M_SafetyChainMenuLines[0].LinkName,
                                    ELEMENT(M_SafetyChainLinkToLocalMenu),
                                    M_SafetyChainLinkToLocalMenu[0].LinkGroup,
                                    ELEMENT(M_SafetyChainMenu),
                                    M_SafetyChainLinkToLocalMenu[0].LinkName,
                                    ELEMENT(M_SafetyChainMenuLines),
                                    pPool,
                                    M_SafetyChainMultiplexedCategoriesParameters);
   STATUS_LINE_VAR_RETURN_VALUE(Status);

   Status = CreateAndInitializeMenu(ModuleState,
                                    M_Status531MenuLines[0].LinkGroup,
                                    M_Status531MenuLines[0].LinkName,
                                    NULL,
                                    0,
                                    M_SafetyChainMenuLines[2].LinkGroup,
                                    ELEMENT(M_Status531Menu),
                                    M_SafetyChainMenuLines[2].LinkName,
                                    ELEMENT(M_Status531MenuLines),
                                    pPool,
                                    M_SafetyChainMultiplexedCategoriesParameters);
   STATUS_LINE_VAR_RETURN_VALUE(Status);

   Status = CreateAndInitializeMenu(ModuleState,
                                    M_Selftest641MenuLines[0].LinkGroup,
                                    M_Selftest641MenuLines[0].LinkName,
                                    NULL,
                                    0,
                                    M_Status531MenuLines[13].LinkGroup,
                                    ELEMENT(M_Selftest641Menu),
                                    M_Status531MenuLines[13].LinkName,
                                    ELEMENT(M_Selftest641MenuLines),
                                    pPool,
                                    M_SafetyChainMultiplexedCategoriesParameters);
   STATUS_LINE_VAR_RETURN_VALUE(Status);

   Status = CreateAndInitializeMenu(ModuleState,
                                    M_Parameter771MenuLines[0].LinkGroup,
                                    M_Parameter771MenuLines[0].LinkName,
                                    NULL,
                                    0,
                                    M_SafetyChainMenuLines[3].LinkGroup,
                                    ELEMENT(M_Parameter771Menu),
                                    M_SafetyChainMenuLines[3].LinkName,
                                    ELEMENT(M_Parameter771MenuLines),
                                    pPool,
                                    M_SafetyChainMultiplexedCategoriesParameters);
   STATUS_LINE_VAR_RETURN_VALUE(Status);

   Status = CreateAndInitializeMenu(ModuleState,
                                    M_Service401MenuLines[0].LinkGroup,
                                    M_Service401MenuLines[0].LinkName,
                                    NULL,
                                    0,
                                    M_SafetyChainMenuLines[4].LinkGroup,
                                    ELEMENT(M_Service401Menu),
                                    M_SafetyChainMenuLines[4].LinkName,
                                    ELEMENT(M_Service401MenuLines),
                                    pPool,
                                    M_SafetyChainMultiplexedCategoriesParameters);
   STATUS_LINE_VAR_RETURN_VALUE(Status);

   return OS_SUCCESS;
}

#define CREATE_MENU

//-----------------------------------------------------------------------
//               BUTTONS FUNCTIONS FORWARD DECLARATIONS
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// BUTTONS                       BUTTONS                      BUTTONS
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
//             SET/RESET FUNCTIONS FORWARD DECLARATIONS
//-----------------------------------------------------------------------
//-----------------------------------------------------------------------
// STATUSCODES                 STATUSCODES                 STATUSCODES
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// MODIFIABLE                  MODIFIABLE                   MODIFIABLE
//-----------------------------------------------------------------------

extern const char SafetyChain_MT_GL20102ManStopAppGroupName[];
extern const char SafetyChain_MT_GL20102ManStopAppMenuName[];

static void Init_Structures_From_Conf_File(void)
{
   M_SafetyChainMenuLines[0].LinkName = (char*)SafetyChain_MT_GL20102ManStopAppMenuName;
   M_SafetyChainMenuLines[0].LinkGroup = (char*)SafetyChain_MT_GL20102ManStopAppGroupName;
}

//-----------------------------------------------------------------------
// AUTOGENERATED END        AUTOGENERATED END        AUTOGENERATED END
//-----------------------------------------------------------------------
//}

#undef AUTOGENERATED_PART

//-----------------------------------------------------------------------
// USER DEFINITIONS         USER DEFINITIONS         USER DEFINITIONS
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// SET/RESET FUNCTIONS    SET/RESET FUNCTIONS    SET/RESET FUNCTIONS
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// DRIVER FUNCTION         DRIVER FUNCTION         DRIVER FUNCTION
//-----------------------------------------------------------------------
  
//-----------------------------------------------------------------------
// INIT                   INIT                     INIT
//-----------------------------------------------------------------------
  
//-----------------------------------------------------------------------
// CONTROL                CONTROL                 CONTROL
//-----------------------------------------------------------------------
  
static STATUS LocalCtrl( U32 Interval )
{
   STATUS LocalStatus = 0;

   return LocalStatus;
}

static STATUS ShutdownCtrl( U8 ModuleState, U8 *DoneState, U32 Interval )
{
    STATUS LocalStatus = 0;

    LocalStatus = LocalCtrl( Interval );
    STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);

    switch( ModuleState )
    {
        case AS_SHUTDOWN:
        {
            // Activate "Manual Shutdown" status code

            *DoneState = AS_SHUTDOWN;
            break;
        }
        case AS_REBOOT:
        {

            *DoneState = AS_REBOOT;
            break;
        }
        case AS_SHUTDOWN_FAST:
        {

            *DoneState = AS_SHUTDOWN_FAST;
            break;
        }
        default:
        {
            *DoneState = ModuleState;
            break;
        }
    }
    return LocalStatus;
}
 
//-----------------------------------------------------------------------
// MAIN CALL             MAIN CALL               MAIN CALL
//-----------------------------------------------------------------------

STATUS SafetyChain_MT_GL20102ManStop( U8 ModuleState, U8 *DoneState , U32 Interval )
{
   STATUS LocalStatus = 0;

   #ifdef READ_VARS
      // Read input data
      LocalStatus = InputReferenceRoutine(ModuleState);
      STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
   #endif
   #ifdef COMMON_VDB_READ
      LocalStatus = ReadVdbWindow(ModuleState);
      STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
   #endif


   switch( ModuleState )
   {
      //__________________________________________________________________________
      case APP_RUN:
      {
         #ifdef FUNCTION_BLOCKS_PRE_LOCAL_CONTROL
            LocalStatus = FunctionBlocksPreLocalCtrl( Interval );
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif
         
         LocalStatus = LocalCtrl( Interval );
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);

         #ifdef FUNCTION_BLOCKS_POST_LOCAL_CONTROL
            LocalStatus = FunctionBlocksPostLocalCtrl( Interval );
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef WRITE_VARS
            // Write Output data
            LocalStatus = OutputReferenceRoutine(ModuleState);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef COMMON_VDB_WRITE
            LocalStatus = WriteVdbWindow(ModuleState);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         *DoneState = APP_RUN;
         break;
      }
      //__________________________________________________________________________
      case APP_INIT1:
      {
         // Version check
         LocalStatus = OS_ValidateAPI( API_VERSION_MAJOR,
                                API_VERSION_MINOR,
                                OS_LinkTime,
                                ReleaseTag,
                                __MODULE__
                               );
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);

         Init_Structures_From_Conf_File();

         #ifdef CREATE_VARDB_VARS
            LocalStatus = CreateVarDbVars();
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef CREATE_MENU
            LocalStatus = SafetyChain_MT_GL20102ManStopMenuAppInit(ModuleState, GetMemPool());
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);

            #ifdef MULTIPLEXIBLE_MENU
               LocalStatus = MenuArraysAppInit(ModuleState, GetMemPool());
               STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
            #endif
         #endif

         #ifdef CREATE_VARDB_ARRAY_VARS
               LocalStatus = CreateVdbArrays(GetMemPool());
               STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
         #endif


         #ifdef CREATE_IO_VARS
               LocalStatus = CreateIOVars();
               STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
         #endif

         *DoneState = APP_INIT1;

         break;
      }
      //__________________________________________________________________________
      case APP_INIT2:
      {
         #ifdef CREATE_MENU
            #ifdef MULTIPLEXIBLE_MENU
               LocalStatus = MenuArraysAppInit(ModuleState, GetMemPool());
               STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
            #endif
         #endif

         #ifdef CREATE_ALIASES
               size_t ErrorEntry = 0;
               LocalStatus = OS_VarDB_CreateAliases(AliasVars, sizeof(AliasVars)/sizeof(AliasVars[0]), &ErrorEntry);
               STATUS_LINE_VAR_RETURN_CONST(LocalStatus, ErrorEntry);
         #endif

         #ifdef VERIFY_ARRAY
               LocalStatus = VerifyArray(GetMemPool());
               STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef VERIFY_VARIABLES
               LocalStatus = LocalIoCheck();
               STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef CREATE_BUTTONS
               LocalStatus = CreateButtons();
               STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         *DoneState = APP_INIT2;

         break;
      }
      //__________________________________________________________________________
      case APP_INIT3 :
      {
         #ifdef CREATE_SUMMATIONS
            LocalStatus = CreateSummations();
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef WRITE_VARS
            LocalStatus = InitOutputVars();
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef CREATE_STATUS_CODES
            LocalStatus = LocalStatusCodeInit();
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef CREATE_IO_VARS
           SafetyChain_MT_GL20102ManStopSetLockValues();
         #endif

         *DoneState = APP_INIT3;

         break;
      }
      //__________________________________________________________________________
      case APP_INIT4:
      {
         #ifdef CREATE_MENU
            LocalStatus = SafetyChain_MT_GL20102ManStopMenuAppInit(ModuleState, GetMemPool());
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);

            #ifdef MULTIPLEXIBLE_MENU
               LocalStatus = MenuArraysAppInit(ModuleState, GetMemPool());
               STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
            #endif
         #endif

         *DoneState = APP_INIT4;

         break;
      }
      //__________________________________________________________________________
      case APP_INIT5:
      {
         #ifdef VALIDATE_HASH
            LocalStatus = ValidateHash( SafetyChain_MT_GL20102ManStop_copyright, MODULE_NAME, SafetyChain_MT_GL20102ManStop_initialValues);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef INIT_FUNCTION_BLOCKS
            LocalStatus = FunctionBlocksInit( Interval );
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         *DoneState = APP_INIT5_DONE;

         break;
      }
      //__________________________________________________________________________
      //Other initialization round can be inserted here
      //__________________________________________________________________________
      case AS_SHUTDOWN:
      {
         LocalStatus = ShutdownCtrl ( ModuleState, DoneState, Interval );
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);

         #ifdef WRITE_VARS
            // Write Output data
            LocalStatus = OutputReferenceRoutine(ModuleState);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef COMMON_VDB_WRITE
            LocalStatus = WriteVdbWindow(ModuleState);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         break;
      }
      //__________________________________________________________________________
      case AS_REBOOT:
      {
         LocalStatus = ShutdownCtrl ( ModuleState, DoneState, Interval );
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);

         #ifdef WRITE_VARS
            // Write Output data
            LocalStatus = OutputReferenceRoutine(ModuleState);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef COMMON_VDB_WRITE
            LocalStatus = WriteVdbWindow(ModuleState);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         break;
      }
      //__________________________________________________________________________
      case AS_SHUTDOWN_FAST:
      {
         LocalStatus = ShutdownCtrl ( ModuleState, DoneState, Interval );
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);

         #ifdef WRITE_VARS
            // Write Output data
            LocalStatus = OutputReferenceRoutine(ModuleState);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef COMMON_VDB_WRITE
            LocalStatus = WriteVdbWindow(ModuleState);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         break;
      }
      default:
      {
         *DoneState = ModuleState;

         break;
      }
   }
   return OS_SUCCESS;
}
//-----------------------------------------------------------------------
