//*****************************PEPTOOL Header Start******************************
//                                                                               
//                         Copyright © 2015 Mita-Teknik.                         
//This software may only be used with WP4x00 Controllers delivered by Mita-Teknik
//                                                                               
//*******************************************************************************
//                                                                               
// $PEPTOOL version:9.0$                                                         
// $PEPTOOL file version:101$                                                    
//                                                                               
//*******************************************************************************
//                                                                               
// $Date: XXXX/XX/XX XX:XX:XX $                                                  
// $Author: XXXX\XXX $                                                           
// $RCSfile: SafetyChain_MT_GL20102ManStop_Conf.c,v $                            
// $Revision: X.X $                                                              
//                                                                               
//******************************PEPTOOL Header End*******************************

//***********************************************************************
// OS header files
#include <os_main.h>
// App header files
#include <InitIo.h>

#define AUTOGENERATED_PART

#include <Turbdef.h>

//-----------------------------------------------------------------------
// AUTOGENERATED START     AUTOGENERATED START     AUTOGENERATED START
//-----------------------------------------------------------------------
char SafetyChain_MT_GL20102ManStop_Conf_copyright[] =
{
   67, 111, 112, 121, 114, 105, 103, 104, 116, 32, 63, 32, 50, 48, 49, 53,
   32, 77, 105, 116, 97, 45, 84, 101, 107, 110, 105, 107, 46, 13, 10, 84,
   104, 105, 115, 32, 115, 111, 102, 116, 119, 97, 114, 101, 32, 109, 97, 121,
   32, 111, 110, 108, 121, 32, 98, 101, 32, 117, 115, 101, 100, 32, 119, 105,
   116, 104, 32, 87, 80, 52, 120, 48, 48, 32, 67, 111, 110, 116, 114, 111,
   108, 108, 101, 114, 115, 32, 100, 101, 108, 105, 118, 101, 114, 101, 100, 32,
   98, 121, 32, 77, 105, 116, 97, 45, 84, 101, 107, 110, 105, 107, 0
};
//-----------------------------------------------------------------------
// MODIFIABLE                  MODIFIABLE               MODIFIABLE
//-----------------------------------------------------------------------
const char SafetyChain_MT_GL20102ManStopAppGroupName[] = "G_"APP_ID"App";
const char SafetyChain_MT_GL20102ManStopAppMenuName[] = "M_"APP_ID"AppMain";

//-----------------------------------------------------------------------
// IO VARIABLES                IO VARIABLES                IO VARIABLES
//-----------------------------------------------------------------------

void (*SafetyChain_MT_GL20102ManStopSetLockValues)(void);
struct os_db_alias *SafetyChain_MT_GL20102ManStopIOVars;
size_t SafetyChain_MT_GL20102ManStopIOVarsSize = 0;
            
struct os_db_alias SafetyChain_MT_GL20102ManStopIOVars1[]=
{
    VAR_ELEMENT_ALIAS("3.2.37",                           "DI_SafetySystemXCK1"),
    VAR_ELEMENT_ALIAS("3.2.37_Ss",                        "DI_SafetySystemXCK1_Ss"),
    VAR_ELEMENT_ALIAS("3.2.37_E",                         "DI_SafetySystemXCK1_E"),
    VAR_ELEMENT_ALIAS("3.2.37_I",                         "DI_SafetySystemXCK1_I"),
    VAR_ELEMENT_ALIAS("3.2.37_Cm",                        "DI_SafetySystemXCK1_Cm"),
    VAR_ELEMENT_ALIAS("3.2.37_Ht",                        "DI_SafetySystemXCK1_Ht"),

    VAR_ELEMENT_ALIAS("3.2.38",                           "DI_SafetySystemXCK2"),
    VAR_ELEMENT_ALIAS("3.2.38_Ss",                        "DI_SafetySystemXCK2_Ss"),
    VAR_ELEMENT_ALIAS("3.2.38_E",                         "DI_SafetySystemXCK2_E"),
    VAR_ELEMENT_ALIAS("3.2.38_I",                         "DI_SafetySystemXCK2_I"),
    VAR_ELEMENT_ALIAS("3.2.38_Cm",                        "DI_SafetySystemXCK2_Cm"),
    VAR_ELEMENT_ALIAS("3.2.38_Ht",                        "DI_SafetySystemXCK2_Ht"),

    VAR_ELEMENT_ALIAS("3.2.36",                           "DI_SafetySystemK1WP2035"),
    VAR_ELEMENT_ALIAS("3.2.36_Ss",                        "DI_SafetySystemK1WP2035_Ss"),
    VAR_ELEMENT_ALIAS("3.2.36_E",                         "DI_SafetySystemK1WP2035_E"),
    VAR_ELEMENT_ALIAS("3.2.36_I",                         "DI_SafetySystemK1WP2035_I"),
    VAR_ELEMENT_ALIAS("3.2.36_Cm",                        "DI_SafetySystemK1WP2035_Cm"),
    VAR_ELEMENT_ALIAS("3.2.36_Ht",                        "DI_SafetySystemK1WP2035_Ht"),

    VAR_ELEMENT_ALIAS("3.2.24_D",                         "DI_SafetySystemK2WP2035"),
    VAR_ELEMENT_ALIAS("3.2.24_D_Ss",                      "DI_SafetySystemK2WP2035_Ss"),
    VAR_ELEMENT_ALIAS("3.2.24_D_E",                       "DI_SafetySystemK2WP2035_E"),
    VAR_ELEMENT_ALIAS("3.2.24_D_I",                       "DI_SafetySystemK2WP2035_I"),
    VAR_ELEMENT_ALIAS("3.2.24_D_Cm",                      "DI_SafetySystemK2WP2035_Cm"),
    VAR_ELEMENT_ALIAS("3.2.24_D_Ht",                      "DI_SafetySystemK2WP2035_Ht"),

    VAR_ELEMENT_ALIAS("3.2.29",                           "DI_SafetySystemKSSR"),
    VAR_ELEMENT_ALIAS("3.2.29_Ss",                        "DI_SafetySystemKSSR_Ss"),
    VAR_ELEMENT_ALIAS("3.2.29_E",                         "DI_SafetySystemKSSR_E"),
    VAR_ELEMENT_ALIAS("3.2.29_I",                         "DI_SafetySystemKSSR_I"),
    VAR_ELEMENT_ALIAS("3.2.29_Cm",                        "DI_SafetySystemKSSR_Cm"),
    VAR_ELEMENT_ALIAS("3.2.29_Ht",                        "DI_SafetySystemKSSR_Ht"),

    VAR_ELEMENT_ALIAS("3.2.34",                           "DI_SafetySystemSCMS"),
    VAR_ELEMENT_ALIAS("3.2.34_Ss",                        "DI_SafetySystemSCMS_Ss"),
    VAR_ELEMENT_ALIAS("3.2.34_E",                         "DI_SafetySystemSCMS_E"),
    VAR_ELEMENT_ALIAS("3.2.34_I",                         "DI_SafetySystemSCMS_I"),
    VAR_ELEMENT_ALIAS("3.2.34_Cm",                        "DI_SafetySystemSCMS_Cm"),
    VAR_ELEMENT_ALIAS("3.2.34_Ht",                        "DI_SafetySystemSCMS_Ht"),

    VAR_ELEMENT_ALIAS("3.3.20",                           "DO_SafetySystemOSCR"),

    VAR_ELEMENT_ALIAS("1.4.43",                           "DI_SafetySystemCONV"),
    VAR_ELEMENT_ALIAS("1.4.43_Ss",                        "DI_SafetySystemCONV_Ss"),
    VAR_ELEMENT_ALIAS("1.4.43_E",                         "DI_SafetySystemCONV_E"),
    VAR_ELEMENT_ALIAS("1.4.43_I",                         "DI_SafetySystemCONV_I"),
    VAR_ELEMENT_ALIAS("1.4.43_Cm",                        "DI_SafetySystemCONV_Cm"),
    VAR_ELEMENT_ALIAS("1.4.43_Ht",                        "DI_SafetySystemCONV_Ht"),

    VAR_ELEMENT_ALIAS("1.4.42",                           "DI_SafetySystemMCCB"),
    VAR_ELEMENT_ALIAS("1.4.42_Ss",                        "DI_SafetySystemMCCB_Ss"),
    VAR_ELEMENT_ALIAS("1.4.42_E",                         "DI_SafetySystemMCCB_E"),
    VAR_ELEMENT_ALIAS("1.4.42_I",                         "DI_SafetySystemMCCB_I"),
    VAR_ELEMENT_ALIAS("1.4.42_Cm",                        "DI_SafetySystemMCCB_Cm"),
    VAR_ELEMENT_ALIAS("1.4.42_Ht",                        "DI_SafetySystemMCCB_Ht"),

};
size_t SafetyChain_MT_GL20102ManStopIOVars1Size = sizeof(SafetyChain_MT_GL20102ManStopIOVars1)/sizeof(SafetyChain_MT_GL20102ManStopIOVars1[0]);

void SafetyChain_MT_GL20102ManStopSetLockValues1(void)
{
   SetLockValue("DI_SafetySystemXCK1_Ss",                TYP_8,     1);
   SetLockValue("DI_SafetySystemXCK1_E",                 TYP_8,     1);
   SetValue("DI_SafetySystemXCK1_I",                     TYP_8,     0);
   SetLockValue("DI_SafetySystemXCK1_Cm",                TYP_8,     1);
   SetLockValue("DI_SafetySystemXCK1_Ht",                TYP_32,    20);

   SetLockValue("DI_SafetySystemXCK2_Ss",                TYP_8,     1);
   SetLockValue("DI_SafetySystemXCK2_E",                 TYP_8,     1);
   SetValue("DI_SafetySystemXCK2_I",                     TYP_8,     0);
   SetLockValue("DI_SafetySystemXCK2_Cm",                TYP_8,     1);
   SetLockValue("DI_SafetySystemXCK2_Ht",                TYP_32,    20);

   SetLockValue("DI_SafetySystemK1WP2035_Ss",            TYP_8,     1);
   SetLockValue("DI_SafetySystemK1WP2035_E",             TYP_8,     1);
   SetValue("DI_SafetySystemK1WP2035_I",                 TYP_8,     0);
   SetLockValue("DI_SafetySystemK1WP2035_Cm",            TYP_8,     1);
   SetLockValue("DI_SafetySystemK1WP2035_Ht",            TYP_32,    20);

   SetLockValue("DI_SafetySystemK2WP2035_Ss",            TYP_8,     1);
   SetLockValue("DI_SafetySystemK2WP2035_E",             TYP_8,     1);
   SetValue("DI_SafetySystemK2WP2035_I",                 TYP_8,     0);
   SetLockValue("DI_SafetySystemK2WP2035_Cm",            TYP_8,     1);
   SetLockValue("DI_SafetySystemK2WP2035_Ht",            TYP_32,    20);

   SetLockValue("DI_SafetySystemKSSR_Ss",                TYP_8,     1);
   SetLockValue("DI_SafetySystemKSSR_E",                 TYP_8,     1);
   SetValue("DI_SafetySystemKSSR_I",                     TYP_8,     0);
   SetLockValue("DI_SafetySystemKSSR_Cm",                TYP_8,     1);
   SetLockValue("DI_SafetySystemKSSR_Ht",                TYP_32,    20);

   SetLockValue("DI_SafetySystemSCMS_Ss",                TYP_8,     1);
   SetLockValue("DI_SafetySystemSCMS_E",                 TYP_8,     1);
   SetValue("DI_SafetySystemSCMS_I",                     TYP_8,     0);
   SetLockValue("DI_SafetySystemSCMS_Cm",                TYP_8,     1);
   SetLockValue("DI_SafetySystemSCMS_Ht",                TYP_32,    100);

   SetLockValue("DI_SafetySystemCONV_Ss",                TYP_8,     1);
   SetLockValue("DI_SafetySystemCONV_E",                 TYP_8,     1);
   SetValue("DI_SafetySystemCONV_I",                     TYP_8,     0);
   SetLockValue("DI_SafetySystemCONV_Cm",                TYP_8,     1);
   SetLockValue("DI_SafetySystemCONV_Ht",                TYP_32,    20);

   SetLockValue("DI_SafetySystemMCCB_Ss",                TYP_8,     1);
   SetLockValue("DI_SafetySystemMCCB_E",                 TYP_8,     1);
   SetValue("DI_SafetySystemMCCB_I",                     TYP_8,     0);
   SetLockValue("DI_SafetySystemMCCB_Cm",                TYP_8,     1);
   SetLockValue("DI_SafetySystemMCCB_Ht",                TYP_32,    1000);
}


STATUS SafetyChain_MT_GL20102ManStopInitIOAliases()
{
   SafetyChain_MT_GL20102ManStopIOVars = SafetyChain_MT_GL20102ManStopIOVars1;
   SafetyChain_MT_GL20102ManStopIOVarsSize = SafetyChain_MT_GL20102ManStopIOVars1Size;
   SafetyChain_MT_GL20102ManStopSetLockValues = &SafetyChain_MT_GL20102ManStopSetLockValues1;
   return OS_SUCCESS;
}
//-----------------------------------------------------------------------
// AUTOGENERATED END        AUTOGENERATED END        AUTOGENERATED END
//-----------------------------------------------------------------------

#undef AUTOGENERATED_PART
