//*****************************PEPTOOL Header Start******************************
//                                                                               
//                         Copyright © 2015 Mita-Teknik.                         
//This software may only be used with WP4x00 Controllers delivered by Mita-Teknik
//                                                                               
//*******************************************************************************
//                                                                               
// $PEPTOOL version:9.0$                                                         
// $PEPTOOL file version:106$                                                    
//                                                                               
//*******************************************************************************
//                                                                               
// $Date: XXXX/XX/XX XX:XX:XX $                                                  
// $Author: XXXX\XXX $                                                           
// $RCSfile: SafetySystem_MT_GL2010.c,v $                                        
// $Revision: X.X $                                                              
//                                                                               
//******************************PEPTOOL Header End*******************************

//***********************************************************************

// OS header files
#include <os_main.h>
// AppLib header files
#include <lib_main.h>
// App header files
#include <turbdef.h>
#include <VarMacros.h>

// Object header file
#include <SafetySystem_MT_GL2010.h>

#define AUTOGENERATED_PART
//{
//-----------------------------------------------------------------------
// AUTOGENERATED START     AUTOGENERATED START     AUTOGENERATED START
//-----------------------------------------------------------------------

#define VALIDATE_HASH
char SafetySystem_MT_GL2010_copyright[] =
{
   67, 111, 112, 121, 114, 105, 103, 104, 116, 32, 63, 32, 50, 48, 49, 53,
   32, 77, 105, 116, 97, 45, 84, 101, 107, 110, 105, 107, 46, 13, 10, 84,
   104, 105, 115, 32, 115, 111, 102, 116, 119, 97, 114, 101, 32, 109, 97, 121,
   32, 111, 110, 108, 121, 32, 98, 101, 32, 117, 115, 101, 100, 32, 119, 105,
   116, 104, 32, 87, 80, 52, 120, 48, 48, 32, 67, 111, 110, 116, 114, 111,
   108, 108, 101, 114, 115, 32, 100, 101, 108, 105, 118, 101, 114, 101, 100, 32,
   98, 121, 32, 77, 105, 116, 97, 45, 84, 101, 107, 110, 105, 107, 0
};

#define MODULE_NAME "Safety SystemA"

//-----------------------------------------------------------------------
// ALLOCATE MEMORY FOR STRINGS IN VARDB
//-----------------------------------------------------------------------

static char A_V_SafetySystemStatusText[31]  = "12345678901234567890123456789";
static char A_V_SafetyChainStateText[31]  = "12345678901234567890123456789";

//-----------------------------------------------------------------------
// DEFINE LOCAL VARIABLES DEFINE LOCAL VARIABLES DEFINE LOCAL VARIABLES
//-----------------------------------------------------------------------

static struct os_db_local LocalVars[] =
{
   VAR_ELEMENT_LOCAL("V_SafetySystemStatus",                     TYPE_U16,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   0,               0,               2,               NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_SafetySystemStatusText",                 TYPE_STRING + sizeof(A_V_SafetySystemStatusText) - 1,  PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   A_V_SafetySystemStatusText, 0,                0,                NULL,  NOLOG_ENABLE  ),
   VAR_ELEMENT_LOCAL("V_SafetySystemServiceRSCR",                TYPE_U8,      PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_SERVICE,            SCALE_NONE,   0,       UNIT_NONE,          0,   0,               0,               1,               NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_SafetySystemServiceRESR",                TYPE_U8,      PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_SERVICE,            SCALE_NONE,   0,       UNIT_NONE,          0,   0,               0,               1,               NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_SafetySystemExecuteSelftest",            TYPE_U8,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   0,               0,               1,               NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_SafetySystemStatusOk",                   TYPE_U8,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   0,               0,               1,               NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_SafetySystemSelftestDue",                TYPE_U8,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   0,               0,               1,               NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_SafetySystemSelftestDueIn",              TYPE_U32,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    3600000, UNIT_HOUR,          2,   0,               0,               U32_MAX,         NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_SafetySystemSelftestSuccess",            TYPE_U8,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   0,               0,               1,               NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_SafetySystemSelftestInProgress",         TYPE_U8,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   0,               0,               1,               NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_ServiceModeSwitchInvert",                TYPE_U8,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   0,               0,               1,               NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_SafetySystemSelftestRequest",            TYPE_U8,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   1,               0,               1,               NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_SafetyChainStateText",                   TYPE_STRING + sizeof(A_V_SafetyChainStateText) - 1,  PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   A_V_SafetyChainStateText, 0,                0,                NULL,  NOLOG_ENABLE  ),
};

//-----------------------------------------------------------------------
// DEFINE PARAMETERS        DEFINE PARAMETERS        DEFINE PARAMETERS
//-----------------------------------------------------------------------

static struct os_db_parameter ParameterVars[] =
{
   VAR_ELEMENT_PARAMETER("P_SafetySystemResetPulseTime",             TYPE_U32,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         SCALE_DIV,    1000,    UNIT_SECOND,        1,   2000,            500,             10000,           NULL  ),
};

//-----------------------------------------------------------------------
// DEFINE BACKUPS            DEFINE BACKUPS            DEFINE BACKUPS
//-----------------------------------------------------------------------

static struct os_db_backup BackupVars[] =
{
   VAR_ELEMENT_BACKUP("B_SafetySystemOkAtShutdown",               TYPE_U8,      PASSWORD_LEVEL_ADMINISTRATOR,      PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   0,               U8_MIN,          U8_MAX,          NULL,  NOLOG_ENABLE),
};

//----------------------------------------------------------------------------------
// DEFINE VAR ARRAYS            DEFINE VAR ARRAYS            DEFINE VAR ARRAYS
//----------------------------------------------------------------------------------
char SafetySystem_MT_GL2010_initialValues[] =
{
   108, 59, 7, 5, 220, 50, 109, 156, 176, 9, 226, 255, 47, 216, 43, 201,
   63, 199, 150, 200, 80, 159, 248, 13, 213, 97, 110, 27, 155, 98, 206, 20,
   0
};

//-----------------------------------------------------------------------
// CREATE DATABASE VARS   CREATE DATABASE VARS   CREATE DATABASE VARS
//-----------------------------------------------------------------------

static STATUS CreateVarDbVars(void)
{
   STATUS Status;
   size_t ErrorEntry;

   Status = OS_VarDB_CreateLocals(LocalVars, sizeof(LocalVars)/sizeof(LocalVars[0]), &ErrorEntry, AppLocalParameterPosition());
   if (Status != 0)
   {
      AppSystemLog(ERR_7, MODULE_NAME"CrVL: %d,%d", Status, ErrorEntry);
      return ERR_7;
   }

   Status = OS_VarDB_CreateParameters(ParameterVars, sizeof(ParameterVars)/sizeof(ParameterVars[0]), &ErrorEntry, AppExportParameterPosition());
   if (Status != 0)
   {
      AppSystemLog(ERR_7, MODULE_NAME"CrVXP: %d,%d", Status, ErrorEntry);
      return ERR_7;
   }

   Status = OS_VarDB_CreateBackups(BackupVars, sizeof(BackupVars)/sizeof(BackupVars[0]), &ErrorEntry, AppLocalParameterPosition(), AppBackupPosition());
   if (Status != 0)
   {
      AppSystemLog(ERR_7, MODULE_NAME"CrVB: %d,%d", Status, ErrorEntry);
      return ERR_7;
   }

   return OS_SUCCESS;
}

#define CREATE_VARDB_VARS

//-----------------------------------------------------------------------
// CREATE IO VARIABLES     CREATE IO VARIABLES     CREATE IO VARIABLES
//-----------------------------------------------------------------------

extern STATUS SafetySystem_MT_GL2010InitIOAliases();
extern struct os_db_alias* SafetySystem_MT_GL2010IOVars;
extern void (*SafetySystem_MT_GL2010SetLockValues)(void);
extern size_t SafetySystem_MT_GL2010IOVarsSize;

static STATUS CreateIOVars(void)
{
   STATUS Status;
   size_t ErrorEntry;

   varid_t VarId;
   BOOL variablesExist = false;
   U8 counter = 50;
   Status = SafetySystem_MT_GL2010InitIOAliases();
   STATUS_LINE_VAR_RETURN_VALUE(Status)
   while (!variablesExist && counter-- > 0)
   {
      variablesExist = true;
      U32 i = 0;
      for (i = 0; i < SafetySystem_MT_GL2010IOVarsSize; ++i)
      {
         if (OS_VarDB_GetVariableID(SafetySystem_MT_GL2010IOVars[i].Name, &VarId) != OS_SUCCESS)
         {
            variablesExist = false;
            break;
         }
      }

      if (!variablesExist)
      {
         OS_Sleep(100);
      }
   }

   Status = OS_VarDB_CreateAliases(SafetySystem_MT_GL2010IOVars, SafetySystem_MT_GL2010IOVarsSize, &ErrorEntry);
   if (Status)
   {
      AppDebugLog(5000, "Var Name = %s", SafetySystem_MT_GL2010IOVars[ErrorEntry].Alias);
   }
   STATUS_LINE_VAR_RETURN_CONST(Status, ErrorEntry);
   return OS_SUCCESS;
}

#define CREATE_IO_VARS

//-----------------------------------------------------------------------
// ALIASES                       ALIASES                       ALIASES
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// INPUT                          INPUT                          INPUT
//-----------------------------------------------------------------------

// Create local variable
#define MODUL_INPUTS
static U8 DI_ServiceModeSwitch = 0;
static U8 V_SafetySystemServiceRSCR = 0;
static U8 V_SafetySystemServiceRESR = 0;
static U8 V_SafetySystemESCStatus = 0;
static U8 V_SafetySystemESCSelftestSuccess = 0;
static U8 V_SafetySystemESCSelftestInProgress = 0;
static U32 B_SafetySystemESCSelftestDueIn = 0;
static U16 V_SafetySystemSCStatus = 0;
static U8 V_SafetySystemSCSelftestSuccess = 0;
static U8 V_SafetySystemSCSelftestInProgress = 0;
static U32 B_SafetySystemSCSelftestDueIn = 0;
static U8 V_GridErrorActive = 0;
static U8 DI_SafetySystemResetTBp = 0;
static U8 DI_SafetySystemResetNp = 0;
static U8 B_SafetySystemOkAtShutdown = 0;
static U8 V_ResetButtonState = 0;
static U8 DO_SafetySystemRSCR = 0;
static U8 DO_SafetySystemRESR = 0;
static U8 V_ActiveControlProgram1 = 0;
static U8 V_RSC_ZeroRpm = 0;
static S32 V_BlCtrl_PitchAngle = 0;
static U32 P_SafetySystemResetPulseTime = 0;

//-----------------------------------------------------------------------
static struct ModulInOut ModulInputs[] =
{
   {"DI_ServiceModeSwitch",                     &DI_ServiceModeSwitch,                     sizeof(DI_ServiceModeSwitch),                     },
   {"V_SafetySystemServiceRSCR",                &V_SafetySystemServiceRSCR,                sizeof(V_SafetySystemServiceRSCR),                },
   {"V_SafetySystemServiceRESR",                &V_SafetySystemServiceRESR,                sizeof(V_SafetySystemServiceRESR),                },
   {"V_SafetySystemESCStatus",                  &V_SafetySystemESCStatus,                  sizeof(V_SafetySystemESCStatus),                  },
   {"V_SafetySystemESCSelftestSuccess",         &V_SafetySystemESCSelftestSuccess,         sizeof(V_SafetySystemESCSelftestSuccess),         },
   {"V_SafetySystemESCSelftestInProgress",      &V_SafetySystemESCSelftestInProgress,      sizeof(V_SafetySystemESCSelftestInProgress),      },
   {"B_SafetySystemESCSelftestDueIn",           &B_SafetySystemESCSelftestDueIn,           sizeof(B_SafetySystemESCSelftestDueIn),           },
   {"V_SafetySystemSCStatus",                   &V_SafetySystemSCStatus,                   sizeof(V_SafetySystemSCStatus),                   },
   {"V_SafetySystemSCSelftestSuccess",          &V_SafetySystemSCSelftestSuccess,          sizeof(V_SafetySystemSCSelftestSuccess),          },
   {"V_SafetySystemSCSelftestInProgress",       &V_SafetySystemSCSelftestInProgress,       sizeof(V_SafetySystemSCSelftestInProgress),       },
   {"B_SafetySystemSCSelftestDueIn",            &B_SafetySystemSCSelftestDueIn,            sizeof(B_SafetySystemSCSelftestDueIn),            },
   {"V_GridErrorActive",                        &V_GridErrorActive,                        sizeof(V_GridErrorActive),                        },
   {"DI_SafetySystemResetTBp",                  &DI_SafetySystemResetTBp,                  sizeof(DI_SafetySystemResetTBp),                  },
   {"DI_SafetySystemResetNp",                   &DI_SafetySystemResetNp,                   sizeof(DI_SafetySystemResetNp),                   },
   {"B_SafetySystemOkAtShutdown",               &B_SafetySystemOkAtShutdown,               sizeof(B_SafetySystemOkAtShutdown),               },
   {"V_ResetButtonState",                       &V_ResetButtonState,                       sizeof(V_ResetButtonState),                       },
   {"DO_SafetySystemRSCR",                      &DO_SafetySystemRSCR,                      sizeof(DO_SafetySystemRSCR),                      },
   {"DO_SafetySystemRESR",                      &DO_SafetySystemRESR,                      sizeof(DO_SafetySystemRESR),                      },
   {"V_ActiveControlProgram1",                  &V_ActiveControlProgram1,                  sizeof(V_ActiveControlProgram1),                  },
   {"V_RSC_ZeroRpm",                            &V_RSC_ZeroRpm,                            sizeof(V_RSC_ZeroRpm),                            },
   {"V_BlCtrl_PitchAngle",                      &V_BlCtrl_PitchAngle,                      sizeof(V_BlCtrl_PitchAngle),                      },
   {"P_SafetySystemResetPulseTime",             &P_SafetySystemResetPulseTime,             sizeof(P_SafetySystemResetPulseTime),             },
};

//-----------------------------------------------------------------------
// Check variable type
static STATUS VarsReadReturnStatus;
static type_t ReadVarType = TYPE_NONE;
static void VarsReadTypeCheck(void)
{
   (void)VarsReadReturnStatus;
   (void)ReadVarType;
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[0].Name,                      ModulInputs[0].Id)
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[1].Name,                      ModulInputs[1].Id)
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[2].Name,                      ModulInputs[2].Id)
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[3].Name,                      ModulInputs[3].Id)
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[4].Name,                      ModulInputs[4].Id)
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[5].Name,                      ModulInputs[5].Id)
   VERIFY_INPUT_REF_ID(U32,       ModulInputs[6].Name,                      ModulInputs[6].Id)
   VERIFY_INPUT_REF_ID(U16,       ModulInputs[7].Name,                      ModulInputs[7].Id)
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[8].Name,                      ModulInputs[8].Id)
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[9].Name,                      ModulInputs[9].Id)
   VERIFY_INPUT_REF_ID(U32,       ModulInputs[10].Name,                     ModulInputs[10].Id)
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[11].Name,                     ModulInputs[11].Id)
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[12].Name,                     ModulInputs[12].Id)
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[13].Name,                     ModulInputs[13].Id)
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[14].Name,                     ModulInputs[14].Id)
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[15].Name,                     ModulInputs[15].Id)
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[16].Name,                     ModulInputs[16].Id)
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[17].Name,                     ModulInputs[17].Id)
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[18].Name,                     ModulInputs[18].Id)
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[19].Name,                     ModulInputs[19].Id)
   VERIFY_INPUT_REF_ID(S32,       ModulInputs[20].Name,                     ModulInputs[20].Id)
   VERIFY_INPUT_REF_ID(U32,       ModulInputs[21].Name,                     ModulInputs[21].Id)
}

#undef MODUL_INPUTS
#define MODUL_INPUTS_SIZE (sizeof(ModulInputs)/sizeof(ModulInputs[0]))

//------------------------------------------------------------------------------------------
// READ/WRITE VARDB ARRAY      READ/WRITE VARDB ARRAY      READ/WRATE VARDB ARRAY
//------------------------------------------------------------------------------------------


//-----------------------------------------------------------------------
// PARAMETER                    PARAMETER                    PARAMETER
//-----------------------------------------------------------------------


//-----------------------------------------------------------------------
// READ VARS FROM VARDB    READ VARS FROM VARDB    READ VARS FROM VARDB
//-----------------------------------------------------------------------

static STATUS InputReferenceRoutine(U8 ModuleState)
{
   STATUS LocalStatus = 0;

   // Read input references
   if (ModuleState >= APP_INIT3)
   {
      // Check inputdata
      if (sizeof(ModulInputs) == 0)
      {
         AppSystemLog(ERR_4, MODULE_NAME"ModuleInputs = 0");
         return ERR_4;
      }
      // Read inputdata
      LocalStatus = OS_ReadVariables(ModulInputs, MODUL_INPUTS_SIZE);
      if (LocalStatus != 0)
      {
         AppSystemLog(ERR_4, MODULE_NAME"ReadVErr: element=%d elementpointer=0x%x", LocalStatus, &ModulInputs[LocalStatus]);
         return ERR_4;
      }
   }
   return 0;
}

#define READ_VARS

//-----------------------------------------------------------------------
// OUTPUT                         OUTPUT                         OUTPUT
//-----------------------------------------------------------------------

// Create local variable
#define MODUL_OUTPUTS
static U16 V_SafetySystemStatus = 0;
static U8 V_ServiceModeSwitchInvert = 0;
static U8 V_SafetySystemStatusOk = 0;
static U8 V_SafetySystemSelftestDue = 0;
static U32 V_SafetySystemSelftestDueIn = 0;
static U8 V_SafetySystemSelftestSuccess = 0;
static U8 V_SafetySystemSelftestInProgress = 0;
static U8 V_SafetySystemExecuteSelftest = 0;
static U8 V_SafetySystemSelftestRequest = 0;
static char V_SafetySystemStatusText[31];
static char V_SafetyChainStateText[31];


//-----------------------------------------------------------------------
static struct ModulInOut ModulOutputs[] =
{
   {"DO_SafetySystemRSCR",                      &DO_SafetySystemRSCR,                      sizeof(DO_SafetySystemRSCR),                      },
   {"DO_SafetySystemRESR",                      &DO_SafetySystemRESR,                      sizeof(DO_SafetySystemRESR),                      },
   {"V_SafetySystemStatus",                     &V_SafetySystemStatus,                     sizeof(V_SafetySystemStatus),                     },
   {"V_SafetySystemStatusText",                 &V_SafetySystemStatusText,                 sizeof(V_SafetySystemStatusText),                 },
   {"V_ServiceModeSwitchInvert",                &V_ServiceModeSwitchInvert,                sizeof(V_ServiceModeSwitchInvert),                },
   {"V_SafetySystemStatusOk",                   &V_SafetySystemStatusOk,                   sizeof(V_SafetySystemStatusOk),                   },
   {"V_SafetySystemSelftestDue",                &V_SafetySystemSelftestDue,                sizeof(V_SafetySystemSelftestDue),                },
   {"V_SafetySystemSelftestDueIn",              &V_SafetySystemSelftestDueIn,              sizeof(V_SafetySystemSelftestDueIn),              },
   {"V_SafetySystemSelftestSuccess",            &V_SafetySystemSelftestSuccess,            sizeof(V_SafetySystemSelftestSuccess),            },
   {"V_SafetySystemSelftestInProgress",         &V_SafetySystemSelftestInProgress,         sizeof(V_SafetySystemSelftestInProgress),         },
   {"B_SafetySystemOkAtShutdown",               &B_SafetySystemOkAtShutdown,               sizeof(B_SafetySystemOkAtShutdown),               },
   {"V_SafetySystemExecuteSelftest",            &V_SafetySystemExecuteSelftest,            sizeof(V_SafetySystemExecuteSelftest),            },
   {"V_SafetyChainStateText",                   &V_SafetyChainStateText,                   sizeof(V_SafetyChainStateText),                   },
   {"V_SafetySystemSelftestRequest",            &V_SafetySystemSelftestRequest,            sizeof(V_SafetySystemSelftestRequest),            },
};

//-----------------------------------------------------------------------
// Check variable type
static STATUS VarsWriteReturnStatus;
static type_t WriteVarType = TYPE_NONE;
static void VarsWriteTypeCheck(void)
{
   (void)VarsWriteReturnStatus;
   (void)WriteVarType;
   VERIFY_OUTPUT_REF_ID(U8,        ModulOutputs[0].Name,                     ModulOutputs[0].Id,                       0)
   VERIFY_OUTPUT_REF_ID(U8,        ModulOutputs[1].Name,                     ModulOutputs[1].Id,                       0)
   VERIFY_OUTPUT_REF_ID(U16,       ModulOutputs[2].Name,                     ModulOutputs[2].Id,                       0)
   VERIFY_OUTPUT_STRING_REF_ID(STRING,     ModulOutputs[3].Name,                      ModulOutputs[3].Id, 0)
   VERIFY_OUTPUT_REF_ID(U8,        ModulOutputs[4].Name,                     ModulOutputs[4].Id,                       0)
   VERIFY_OUTPUT_REF_ID(U8,        ModulOutputs[5].Name,                     ModulOutputs[5].Id,                       0)
   VERIFY_OUTPUT_REF_ID(U8,        ModulOutputs[6].Name,                     ModulOutputs[6].Id,                       0)
   VERIFY_OUTPUT_REF_ID(U32,       ModulOutputs[7].Name,                     ModulOutputs[7].Id,                       0)
   VERIFY_OUTPUT_REF_ID(U8,        ModulOutputs[8].Name,                     ModulOutputs[8].Id,                       0)
   VERIFY_OUTPUT_REF_ID(U8,        ModulOutputs[9].Name,                     ModulOutputs[9].Id,                       0)
   VERIFY_OUTPUT_REF_ID(U8,        ModulOutputs[10].Name,                    ModulOutputs[10].Id,                      0)
   VERIFY_OUTPUT_REF_ID(U8,        ModulOutputs[11].Name,                    ModulOutputs[11].Id,                      0)
   VERIFY_OUTPUT_STRING_REF_ID(STRING,     ModulOutputs[12].Name,                     ModulOutputs[12].Id, 0)
   VERIFY_OUTPUT_REF_ID(U8,        ModulOutputs[13].Name,                    ModulOutputs[13].Id,                      0)
}

#undef MODUL_OUTPUTS
#define MODUL_OUTPUTS_SIZE (sizeof(ModulOutputs)/sizeof(ModulOutputs[0]))

//-----------------------------------------------------------------------
// WRITE VARS TO VARDB     WRITE VARS TO VARDB     WRITE VARS TO VARDB
//-----------------------------------------------------------------------

static STATUS InitOutputVars(void)
{
   STATUS LocalStatus;
   // Read outputdata
   LocalStatus = OS_ReadVariables(ModulOutputs, MODUL_OUTPUTS_SIZE);
   if (LocalStatus != 0)
   {
      AppSystemLog(ERR_4, MODULE_NAME"InitErr: element=%d elementpointer=0x%x", LocalStatus, &ModulOutputs[LocalStatus]);
      return ERR_4;
   }
   return OS_SUCCESS;
}
static STATUS OutputReferenceRoutine(U8 ModuleState)
{
   STATUS LocalStatus = 0;
   // Write Outputdata
   LocalStatus = OS_WriteVariablesConditional(ModulOutputs, MODUL_OUTPUTS_SIZE);
   if (LocalStatus != 0)
   {
      AppSystemLog(ERR_5, MODULE_NAME"WriteVErr: element=%d elementpointer=0x%x", LocalStatus, &ModulOutputs[LocalStatus]);
      return ERR_5;
   }
   return 0;
}

#define WRITE_VARS

//-----------------------------------------------------------------------
// VERIFY VARIABLES CREATION                 VERIFY VARIABLES CREATION
//-----------------------------------------------------------------------

static STATUS LocalIoCheck(void)
{
   // Check if input variables exist.
   STATUS LocalStatus;

   LocalStatus = OS_DoesVariablesExist(ModulInputs, MODUL_INPUTS_SIZE);
   if (LocalStatus != 0)
   {
      AppSystemLog(ERR_1, MODULE_NAME"InputErr: %d", LocalStatus);
      AppSystemLog(ERR_1, "Name: %s", ModulInputs[LocalStatus-1].Name);
      return ERR_1;
   }
   (void)VarsReadTypeCheck();

   LocalStatus = OS_DoesVariablesExist(ModulOutputs, MODUL_OUTPUTS_SIZE);
   if (LocalStatus != 0)
   {
      AppSystemLog(ERR_2, MODULE_NAME"OutputErr: %d", LocalStatus);
      AppSystemLog(ERR_2, "Name: %s", ModulOutputs[LocalStatus-1].Name);
      return ERR_2;
   }
   (void)VarsWriteTypeCheck();

   return OS_SUCCESS;
}

#define VERIFY_VARIABLES

//-----------------------------------------------------------------------
// ALLOCATE MEMORY FOR SUMMATIONS        ALLOCATE MEMORY FOR SUMMATIONS
//-----------------------------------------------------------------------


//-----------------------------------------------------------------------
// SUMMATIONS                  SUMMATIONS                  SUMMATIONS
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// DEFINE MENUS               DEFINE MENUS               DEFINE MENUS
//-----------------------------------------------------------------------



// Menu line and link to local menu
//-----------------------------------------------------------------------
static struct line_struct M_SafetySystemLinkToLocalMenu[] =
{
   MENU_ELEMENT_LINE_LINK("Safety System",                     PASSWORD_LEVEL_END_CUSTOMER,        "M_SafetySystem",                   "G_SafetySystem_MT_GL2010"),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_SafetySystemMenu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_SafetySystem",                   PASSWORD_LEVEL_END_CUSTOMER),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_SafetySystemMenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("SAFETY SYSTEM",                     PASSWORD_LEVEL_END_CUSTOMER,        "M_"APP_ID"AppMain",                "G_"APP_ID"App"),
   MENU_ELEMENT_LINE_LINK("Safety System",                     PASSWORD_LEVEL_END_CUSTOMER,        "M_SafetySystem1",                  "G_SafetySystem_MT_GL2010"),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_SafetySystem1Menu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_SafetySystem1",                  PASSWORD_LEVEL_END_CUSTOMER),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_SafetySystem1MenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("SAFETY SYSTEM",                     PASSWORD_LEVEL_END_CUSTOMER,        "M_SafetySystem",                   "G_SafetySystem_MT_GL2010"),
   MENU_ELEMENT_LINE_VARRO("Safety System Status",             PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_SafetySystemStatusText",                   LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("E-Stop Chain Status",              PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_SafetySystemESCStatusText",                LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Safety Chain Status",              PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_SafetySystemSCStatusText",                 LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_LINK("Status",                            PASSWORD_LEVEL_END_CUSTOMER,        "M_Status91",                       "G_SafetySystem_MT_GL2010"),
   MENU_ELEMENT_LINE_LINK("Parameter",                         PASSWORD_LEVEL_END_CUSTOMER,        "M_Parameter31",                    "G_SafetySystem_MT_GL2010"),
   MENU_ELEMENT_LINE_LINK("Service",                           PASSWORD_LEVEL_SERVICE,             "M_Service41",                      "G_SafetySystem_MT_GL2010"),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_Status91Menu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_Status91",                       PASSWORD_LEVEL_END_CUSTOMER),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_Status91MenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("STATUS",                            PASSWORD_LEVEL_END_CUSTOMER,        "M_SafetySystem1",                  "G_SafetySystem_MT_GL2010"),
   MENU_ELEMENT_LINE_VARRO("Next Selftest Due in",             PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_SafetySystemSelftestDueIn",                LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Service Switch Active",            PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_ServiceModeSwitchInvert",                  LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Reset Switch (Np)",                PASSWORD_LEVEL_END_CUSTOMER,        (char*)"DI_SafetySystemResetNp",                     LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Reset Switch (TBp)",               PASSWORD_LEVEL_END_CUSTOMER,        (char*)"DI_SafetySystemResetTBp",                    LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Reset E-Stop Chain (RESR)",        PASSWORD_LEVEL_END_CUSTOMER,        (char*)"DO_SafetySystemRESR",                        LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Reset Safety Chain (RSCR)",        PASSWORD_LEVEL_END_CUSTOMER,        (char*)"DO_SafetySystemRSCR",                        LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Yaw-Safety Chain Mode Switch (SCMS)", PASSWORD_LEVEL_END_CUSTOMER,        (char*)"DI_SafetySystemSCMS",                        LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_LINK("Selftest",                          PASSWORD_LEVEL_END_CUSTOMER,        "M_Selftest271",                    "G_SafetySystem_MT_GL2010"),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_Selftest271Menu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_Selftest271",                    PASSWORD_LEVEL_END_CUSTOMER),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_Selftest271MenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("SELFTEST",                          PASSWORD_LEVEL_END_CUSTOMER,        "M_Status91",                       "G_SafetySystem_MT_GL2010"),
   MENU_ELEMENT_LINE_VARRO("Selftest Due",                     PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_SafetySystemSelftestDue",                  LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Selftest Success",                 PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_SafetySystemSelftestSuccess",              LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Selftest Requested",               PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_SafetySystemSelftestRequest",              LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Selftest in Progress",             PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_SafetySystemSelftestInProgress",           LINE_FORMAT_NONE),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_Parameter31Menu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_Parameter31",                    PASSWORD_LEVEL_END_CUSTOMER),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_Parameter31MenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("PARAMETER",                         PASSWORD_LEVEL_END_CUSTOMER,        "M_SafetySystem1",                  "G_SafetySystem_MT_GL2010"),
   MENU_ELEMENT_LINE_VARRW("Reset Pulse Time",                 PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_SafetySystemResetPulseTime",               LINE_FORMAT_NONE),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_Service41Menu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_Service41",                      PASSWORD_LEVEL_SERVICE),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_Service41MenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("SERVICE",                           PASSWORD_LEVEL_SERVICE,             "M_SafetySystem1",                  "G_SafetySystem_MT_GL2010"),
   MENU_ELEMENT_LINE_VARRW("Manual Reset Safety Chain (RSCR)", PASSWORD_LEVEL_SERVICE,             (char*)"V_SafetySystemServiceRSCR",                  LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Manual Reset E-Stop Chain (RESR)", PASSWORD_LEVEL_SERVICE,             (char*)"V_SafetySystemServiceRESR",                  LINE_FORMAT_NONE),
};
// Creating parameters for multiplexed categories
//-----------------------------------------------------------------------
static struct multiplexed_info_struct M_SafetySystemMultiplexedCategoriesParameters[] =
{
0};

//-----------------------------------------------------------------------
// CREATE MENUS               CREATE MENUS               CREATE MENUS
//-----------------------------------------------------------------------

// Memory reservation
//-----------------------------------------------------------------------
static struct menu_group_struct ObjGroup[1];

// Creating the menus
//-----------------------------------------------------------------------
STATUS SafetySystem_MT_GL2010MenuAppInit(U8 ModuleState, OS_MEMORY_POOL* pPool)
{
   STATUS Status;

   if (ModuleState == APP_INIT1)
   {
      /* Create application group */
      Status = OS_CreateMenuGroup(ObjGroup, M_SafetySystemLinkToLocalMenu[0].LinkGroup);
      STATUS_LINE_VAR_RETURN_VALUE(Status);
   }

   Status = CreateAndInitializeMenu(ModuleState,
                                    M_SafetySystemMenuLines[0].LinkGroup,
                                    M_SafetySystemMenuLines[0].LinkName,
                                    ELEMENT(M_SafetySystemLinkToLocalMenu),
                                    M_SafetySystemLinkToLocalMenu[0].LinkGroup,
                                    ELEMENT(M_SafetySystemMenu),
                                    M_SafetySystemLinkToLocalMenu[0].LinkName,
                                    ELEMENT(M_SafetySystemMenuLines),
                                    pPool,
                                    M_SafetySystemMultiplexedCategoriesParameters);
   STATUS_LINE_VAR_RETURN_VALUE(Status);

   Status = CreateAndInitializeMenu(ModuleState,
                                    M_SafetySystem1MenuLines[0].LinkGroup,
                                    M_SafetySystem1MenuLines[0].LinkName,
                                    NULL,
                                    0,
                                    M_SafetySystemMenuLines[1].LinkGroup,
                                    ELEMENT(M_SafetySystem1Menu),
                                    M_SafetySystemMenuLines[1].LinkName,
                                    ELEMENT(M_SafetySystem1MenuLines),
                                    pPool,
                                    M_SafetySystemMultiplexedCategoriesParameters);
   STATUS_LINE_VAR_RETURN_VALUE(Status);

   Status = CreateAndInitializeMenu(ModuleState,
                                    M_Status91MenuLines[0].LinkGroup,
                                    M_Status91MenuLines[0].LinkName,
                                    NULL,
                                    0,
                                    M_SafetySystem1MenuLines[4].LinkGroup,
                                    ELEMENT(M_Status91Menu),
                                    M_SafetySystem1MenuLines[4].LinkName,
                                    ELEMENT(M_Status91MenuLines),
                                    pPool,
                                    M_SafetySystemMultiplexedCategoriesParameters);
   STATUS_LINE_VAR_RETURN_VALUE(Status);

   Status = CreateAndInitializeMenu(ModuleState,
                                    M_Selftest271MenuLines[0].LinkGroup,
                                    M_Selftest271MenuLines[0].LinkName,
                                    NULL,
                                    0,
                                    M_Status91MenuLines[8].LinkGroup,
                                    ELEMENT(M_Selftest271Menu),
                                    M_Status91MenuLines[8].LinkName,
                                    ELEMENT(M_Selftest271MenuLines),
                                    pPool,
                                    M_SafetySystemMultiplexedCategoriesParameters);
   STATUS_LINE_VAR_RETURN_VALUE(Status);

   Status = CreateAndInitializeMenu(ModuleState,
                                    M_Parameter31MenuLines[0].LinkGroup,
                                    M_Parameter31MenuLines[0].LinkName,
                                    NULL,
                                    0,
                                    M_SafetySystem1MenuLines[5].LinkGroup,
                                    ELEMENT(M_Parameter31Menu),
                                    M_SafetySystem1MenuLines[5].LinkName,
                                    ELEMENT(M_Parameter31MenuLines),
                                    pPool,
                                    M_SafetySystemMultiplexedCategoriesParameters);
   STATUS_LINE_VAR_RETURN_VALUE(Status);

   Status = CreateAndInitializeMenu(ModuleState,
                                    M_Service41MenuLines[0].LinkGroup,
                                    M_Service41MenuLines[0].LinkName,
                                    NULL,
                                    0,
                                    M_SafetySystem1MenuLines[6].LinkGroup,
                                    ELEMENT(M_Service41Menu),
                                    M_SafetySystem1MenuLines[6].LinkName,
                                    ELEMENT(M_Service41MenuLines),
                                    pPool,
                                    M_SafetySystemMultiplexedCategoriesParameters);
   STATUS_LINE_VAR_RETURN_VALUE(Status);

   return OS_SUCCESS;
}

#define CREATE_MENU

//-----------------------------------------------------------------------
//               BUTTONS FUNCTIONS FORWARD DECLARATIONS
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// BUTTONS                       BUTTONS                      BUTTONS
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
//             SET/RESET FUNCTIONS FORWARD DECLARATIONS
//-----------------------------------------------------------------------
//-----------------------------------------------------------------------
// STATUSCODES                 STATUSCODES                 STATUSCODES
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// MODIFIABLE                  MODIFIABLE                   MODIFIABLE
//-----------------------------------------------------------------------

extern const char SafetySystem_MT_GL2010AppGroupName[];
extern const char SafetySystem_MT_GL2010AppMenuName[];

static void Init_Structures_From_Conf_File(void)
{
   M_SafetySystemMenuLines[0].LinkName = (char*)SafetySystem_MT_GL2010AppMenuName;
   M_SafetySystemMenuLines[0].LinkGroup = (char*)SafetySystem_MT_GL2010AppGroupName;
}

//-----------------------------------------------------------------------
// AUTOGENERATED END        AUTOGENERATED END        AUTOGENERATED END
//-----------------------------------------------------------------------
//}

#undef AUTOGENERATED_PART

//-----------------------------------------------------------------------
// USER DEFINITIONS         USER DEFINITIONS         USER DEFINITIONS
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// SET/RESET FUNCTIONS    SET/RESET FUNCTIONS    SET/RESET FUNCTIONS
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// DRIVER FUNCTION         DRIVER FUNCTION         DRIVER FUNCTION
//-----------------------------------------------------------------------
  
//-----------------------------------------------------------------------
// INIT                   INIT                     INIT
//-----------------------------------------------------------------------
  
//-----------------------------------------------------------------------
// CONTROL                CONTROL                 CONTROL
//-----------------------------------------------------------------------
  
static STATUS LocalCtrl( U32 Interval )
{
   STATUS LocalStatus = 0;

   return LocalStatus;
}

static STATUS ShutdownCtrl( U8 ModuleState, U8 *DoneState, U32 Interval )
{
    STATUS LocalStatus = 0;

    LocalStatus = LocalCtrl( Interval );
    STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);

    switch( ModuleState )
    {
        case AS_SHUTDOWN:
        {
            // Activate "Manual Shutdown" status code

            *DoneState = AS_SHUTDOWN;
            break;
        }
        case AS_REBOOT:
        {

            *DoneState = AS_REBOOT;
            break;
        }
        case AS_SHUTDOWN_FAST:
        {

            *DoneState = AS_SHUTDOWN_FAST;
            break;
        }
        default:
        {
            *DoneState = ModuleState;
            break;
        }
    }
    return LocalStatus;
}
 
//-----------------------------------------------------------------------
// MAIN CALL             MAIN CALL               MAIN CALL
//-----------------------------------------------------------------------

STATUS SafetySystem_MT_GL2010( U8 ModuleState, U8 *DoneState , U32 Interval )
{
   STATUS LocalStatus = 0;

   #ifdef READ_VARS
      // Read input data
      LocalStatus = InputReferenceRoutine(ModuleState);
      STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
   #endif
   #ifdef COMMON_VDB_READ
      LocalStatus = ReadVdbWindow(ModuleState);
      STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
   #endif


   switch( ModuleState )
   {
      //__________________________________________________________________________
      case APP_RUN:
      {
         #ifdef FUNCTION_BLOCKS_PRE_LOCAL_CONTROL
            LocalStatus = FunctionBlocksPreLocalCtrl( Interval );
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif
         
         LocalStatus = LocalCtrl( Interval );
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);

         #ifdef FUNCTION_BLOCKS_POST_LOCAL_CONTROL
            LocalStatus = FunctionBlocksPostLocalCtrl( Interval );
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef WRITE_VARS
            // Write Output data
            LocalStatus = OutputReferenceRoutine(ModuleState);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef COMMON_VDB_WRITE
            LocalStatus = WriteVdbWindow(ModuleState);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         *DoneState = APP_RUN;
         break;
      }
      //__________________________________________________________________________
      case APP_INIT1:
      {
         // Version check
         LocalStatus = OS_ValidateAPI( API_VERSION_MAJOR,
                                API_VERSION_MINOR,
                                OS_LinkTime,
                                ReleaseTag,
                                __MODULE__
                               );
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);

         Init_Structures_From_Conf_File();

         #ifdef CREATE_VARDB_VARS
            LocalStatus = CreateVarDbVars();
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef CREATE_MENU
            LocalStatus = SafetySystem_MT_GL2010MenuAppInit(ModuleState, GetMemPool());
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);

            #ifdef MULTIPLEXIBLE_MENU
               LocalStatus = MenuArraysAppInit(ModuleState, GetMemPool());
               STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
            #endif
         #endif

         #ifdef CREATE_VARDB_ARRAY_VARS
               LocalStatus = CreateVdbArrays(GetMemPool());
               STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
         #endif


         #ifdef CREATE_IO_VARS
               LocalStatus = CreateIOVars();
               STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
         #endif

         *DoneState = APP_INIT1;

         break;
      }
      //__________________________________________________________________________
      case APP_INIT2:
      {
         #ifdef CREATE_MENU
            #ifdef MULTIPLEXIBLE_MENU
               LocalStatus = MenuArraysAppInit(ModuleState, GetMemPool());
               STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
            #endif
         #endif

         #ifdef CREATE_ALIASES
               size_t ErrorEntry = 0;
               LocalStatus = OS_VarDB_CreateAliases(AliasVars, sizeof(AliasVars)/sizeof(AliasVars[0]), &ErrorEntry);
               STATUS_LINE_VAR_RETURN_CONST(LocalStatus, ErrorEntry);
         #endif

         #ifdef VERIFY_ARRAY
               LocalStatus = VerifyArray(GetMemPool());
               STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef VERIFY_VARIABLES
               LocalStatus = LocalIoCheck();
               STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef CREATE_BUTTONS
               LocalStatus = CreateButtons();
               STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         *DoneState = APP_INIT2;

         break;
      }
      //__________________________________________________________________________
      case APP_INIT3 :
      {
         #ifdef CREATE_SUMMATIONS
            LocalStatus = CreateSummations();
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef WRITE_VARS
            LocalStatus = InitOutputVars();
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef CREATE_STATUS_CODES
            LocalStatus = LocalStatusCodeInit();
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef CREATE_IO_VARS
           SafetySystem_MT_GL2010SetLockValues();
         #endif

         *DoneState = APP_INIT3;

         break;
      }
      //__________________________________________________________________________
      case APP_INIT4:
      {
         #ifdef CREATE_MENU
            LocalStatus = SafetySystem_MT_GL2010MenuAppInit(ModuleState, GetMemPool());
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);

            #ifdef MULTIPLEXIBLE_MENU
               LocalStatus = MenuArraysAppInit(ModuleState, GetMemPool());
               STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
            #endif
         #endif

         *DoneState = APP_INIT4;

         break;
      }
      //__________________________________________________________________________
      case APP_INIT5:
      {
         #ifdef VALIDATE_HASH
            LocalStatus = ValidateHash( SafetySystem_MT_GL2010_copyright, MODULE_NAME, SafetySystem_MT_GL2010_initialValues);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef INIT_FUNCTION_BLOCKS
            LocalStatus = FunctionBlocksInit( Interval );
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         *DoneState = APP_INIT5_DONE;

         break;
      }
      //__________________________________________________________________________
      //Other initialization round can be inserted here
      //__________________________________________________________________________
      case AS_SHUTDOWN:
      {
         LocalStatus = ShutdownCtrl ( ModuleState, DoneState, Interval );
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);

         #ifdef WRITE_VARS
            // Write Output data
            LocalStatus = OutputReferenceRoutine(ModuleState);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef COMMON_VDB_WRITE
            LocalStatus = WriteVdbWindow(ModuleState);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         break;
      }
      //__________________________________________________________________________
      case AS_REBOOT:
      {
         LocalStatus = ShutdownCtrl ( ModuleState, DoneState, Interval );
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);

         #ifdef WRITE_VARS
            // Write Output data
            LocalStatus = OutputReferenceRoutine(ModuleState);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef COMMON_VDB_WRITE
            LocalStatus = WriteVdbWindow(ModuleState);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         break;
      }
      //__________________________________________________________________________
      case AS_SHUTDOWN_FAST:
      {
         LocalStatus = ShutdownCtrl ( ModuleState, DoneState, Interval );
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);

         #ifdef WRITE_VARS
            // Write Output data
            LocalStatus = OutputReferenceRoutine(ModuleState);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef COMMON_VDB_WRITE
            LocalStatus = WriteVdbWindow(ModuleState);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         break;
      }
      default:
      {
         *DoneState = ModuleState;

         break;
      }
   }
   return OS_SUCCESS;
}
//-----------------------------------------------------------------------
