//*****************************PEPTOOL Header Start******************************
//                                                                               
//                         Copyright © 2015 Mita-Teknik.                         
//This software may only be used with WP4x00 Controllers delivered by Mita-Teknik
//                                                                               
//*******************************************************************************
//                                                                               
// $PEPTOOL version:9.0$                                                         
// $PEPTOOL file version:101$                                                    
//                                                                               
//*******************************************************************************
//                                                                               
// $Date: 2014/03/04 14:35:37 $                                                  
// $Author: MITA\ihn $                                                           
// $RCSfile: SurgeProtection_Conf.c,v $                                          
// $Revision: 1.7 $                                                              
//                                                                               
//******************************PEPTOOL Header End*******************************

//***********************************************************************
// OS header files
#include <os_main.h>
// IO init file
#include <InitIo.h>
      
#define AUTOGENERATED_PART

#include <Turbdef.h>

//-----------------------------------------------------------------------
// AUTOGENERATED START     AUTOGENERATED START     AUTOGENERATED START
//-----------------------------------------------------------------------
char SurgeProtection_Conf_copyright[] =
{
   67, 111, 112, 121, 114, 105, 103, 104, 116, 32, 63, 32, 50, 48, 49, 53,
   32, 77, 105, 116, 97, 45, 84, 101, 107, 110, 105, 107, 46, 13, 10, 84,
   104, 105, 115, 32, 115, 111, 102, 116, 119, 97, 114, 101, 32, 109, 97, 121,
   32, 111, 110, 108, 121, 32, 98, 101, 32, 117, 115, 101, 100, 32, 119, 105,
   116, 104, 32, 87, 80, 52, 120, 48, 48, 32, 67, 111, 110, 116, 114, 111,
   108, 108, 101, 114, 115, 32, 100, 101, 108, 105, 118, 101, 114, 101, 100, 32,
   98, 121, 32, 77, 105, 116, 97, 45, 84, 101, 107, 110, 105, 107, 0
};
//-----------------------------------------------------------------------
// MODIFIABLE                  MODIFIABLE               MODIFIABLE
//-----------------------------------------------------------------------
const char SurgeProtectionAppGroupName[] = "G_"APP_ID"App";
const char SurgeProtectionAppMenuName[] = "M_"APP_ID"AppMain";

//-----------------------------------------------------------------------
// IO VARIABLES                IO VARIABLES                IO VARIABLES
//-----------------------------------------------------------------------

void (*SurgeProtectionSetLockValues)(void);
struct os_db_alias *SurgeProtectionIOVars;
size_t SurgeProtectionIOVarsSize = 0;
            
struct os_db_alias SurgeProtectionIOVars1[]=
{
    VAR_ELEMENT_ALIAS("1.4.49",                           "DI_SurgeProtectionTowerBase"),
    VAR_ELEMENT_ALIAS("1.4.49_Ss",                        "DI_SurgeProtectionTowerBase_Ss"),
    VAR_ELEMENT_ALIAS("1.4.49_E",                         "DI_SurgeProtectionTowerBase_E"),
    VAR_ELEMENT_ALIAS("1.4.49_I",                         "DI_SurgeProtectionTowerBase_I"),
    VAR_ELEMENT_ALIAS("1.4.49_Cm",                        "DI_SurgeProtectionTowerBase_Cm"),
    VAR_ELEMENT_ALIAS("1.4.49_Ht",                        "DI_SurgeProtectionTowerBase_Ht"),

    VAR_ELEMENT_ALIAS("3.2.49",                           "DI_SurgeProtectionNacelle"),
    VAR_ELEMENT_ALIAS("3.2.49_Ss",                        "DI_SurgeProtectionNacelle_Ss"),
    VAR_ELEMENT_ALIAS("3.2.49_E",                         "DI_SurgeProtectionNacelle_E"),
    VAR_ELEMENT_ALIAS("3.2.49_I",                         "DI_SurgeProtectionNacelle_I"),
    VAR_ELEMENT_ALIAS("3.2.49_Cm",                        "DI_SurgeProtectionNacelle_Cm"),
    VAR_ELEMENT_ALIAS("3.2.49_Ht",                        "DI_SurgeProtectionNacelle_Ht"),

    VAR_ELEMENT_ALIAS("1.4.50",                           "DI_SurgeProtectionTowerBase400V"),
    VAR_ELEMENT_ALIAS("1.4.50_Ss",                        "DI_SurgeProtectionTowerBase400V_Ss"),
    VAR_ELEMENT_ALIAS("1.4.50_E",                         "DI_SurgeProtectionTowerBase400V_E"),
    VAR_ELEMENT_ALIAS("1.4.50_I",                         "DI_SurgeProtectionTowerBase400V_I"),
    VAR_ELEMENT_ALIAS("1.4.50_Cm",                        "DI_SurgeProtectionTowerBase400V_Cm"),
    VAR_ELEMENT_ALIAS("1.4.50_Ht",                        "DI_SurgeProtectionTowerBase400V_Ht"),

    VAR_ELEMENT_ALIAS("3.2.50",                           "DI_SurgeProtectionNacelle400V"),
    VAR_ELEMENT_ALIAS("3.2.50_Ss",                        "DI_SurgeProtectionNacelle400V_Ss"),
    VAR_ELEMENT_ALIAS("3.2.50_E",                         "DI_SurgeProtectionNacelle400V_E"),
    VAR_ELEMENT_ALIAS("3.2.50_I",                         "DI_SurgeProtectionNacelle400V_I"),
    VAR_ELEMENT_ALIAS("3.2.50_Cm",                        "DI_SurgeProtectionNacelle400V_Cm"),
    VAR_ELEMENT_ALIAS("3.2.50_Ht",                        "DI_SurgeProtectionNacelle400V_Ht"),

    VAR_ELEMENT_ALIAS("5.2.26",                           "DI_SurgeProtectionHub"),
    VAR_ELEMENT_ALIAS("5.2.26_Ss",                        "DI_SurgeProtectionHub_Ss"),
    VAR_ELEMENT_ALIAS("5.2.26_E",                         "DI_SurgeProtectionHub_E"),
    VAR_ELEMENT_ALIAS("5.2.26_I",                         "DI_SurgeProtectionHub_I"),
    VAR_ELEMENT_ALIAS("5.2.26_Cm",                        "DI_SurgeProtectionHub_Cm"),
    VAR_ELEMENT_ALIAS("5.2.26_Ht",                        "DI_SurgeProtectionHub_Ht"),

    VAR_ELEMENT_ALIAS("5.2.25",                           "DI_SurgeProtectionHub400V"),
    VAR_ELEMENT_ALIAS("5.2.25_Ss",                        "DI_SurgeProtectionHub400V_Ss"),
    VAR_ELEMENT_ALIAS("5.2.25_E",                         "DI_SurgeProtectionHub400V_E"),
    VAR_ELEMENT_ALIAS("5.2.25_I",                         "DI_SurgeProtectionHub400V_I"),
    VAR_ELEMENT_ALIAS("5.2.25_Cm",                        "DI_SurgeProtectionHub400V_Cm"),
    VAR_ELEMENT_ALIAS("5.2.25_Ht",                        "DI_SurgeProtectionHub400V_Ht"),

};
size_t SurgeProtectionIOVars1Size = sizeof(SurgeProtectionIOVars1)/sizeof(SurgeProtectionIOVars1[0]);

void SurgeProtectionSetLockValues1(void)
{
   SetLockValue("DI_SurgeProtectionTowerBase_Ss",        TYP_8,     1);
   SetLockValue("DI_SurgeProtectionTowerBase_E",         TYP_8,     1);
   SetValue("DI_SurgeProtectionTowerBase_I",             TYP_8,     0);
   SetLockValue("DI_SurgeProtectionTowerBase_Cm",        TYP_8,     1);
   SetLockValue("DI_SurgeProtectionTowerBase_Ht",        TYP_32,    1000);

   SetLockValue("DI_SurgeProtectionNacelle_Ss",          TYP_8,     1);
   SetLockValue("DI_SurgeProtectionNacelle_E",           TYP_8,     1);
   SetValue("DI_SurgeProtectionNacelle_I",               TYP_8,     0);
   SetLockValue("DI_SurgeProtectionNacelle_Cm",          TYP_8,     1);
   SetLockValue("DI_SurgeProtectionNacelle_Ht",          TYP_32,    1000);

   SetLockValue("DI_SurgeProtectionTowerBase400V_Ss",    TYP_8,     1);
   SetLockValue("DI_SurgeProtectionTowerBase400V_E",     TYP_8,     1);
   SetValue("DI_SurgeProtectionTowerBase400V_I",         TYP_8,     0);
   SetLockValue("DI_SurgeProtectionTowerBase400V_Cm",    TYP_8,     1);
   SetLockValue("DI_SurgeProtectionTowerBase400V_Ht",    TYP_32,    1000);

   SetLockValue("DI_SurgeProtectionNacelle400V_Ss",      TYP_8,     1);
   SetLockValue("DI_SurgeProtectionNacelle400V_E",       TYP_8,     1);
   SetValue("DI_SurgeProtectionNacelle400V_I",           TYP_8,     0);
   SetLockValue("DI_SurgeProtectionNacelle400V_Cm",      TYP_8,     1);
   SetLockValue("DI_SurgeProtectionNacelle400V_Ht",      TYP_32,    1000);

   SetLockValue("DI_SurgeProtectionHub_Ss",              TYP_8,     1);
   SetLockValue("DI_SurgeProtectionHub_E",               TYP_8,     1);
   SetValue("DI_SurgeProtectionHub_I",                   TYP_8,     0);
   SetLockValue("DI_SurgeProtectionHub_Cm",              TYP_8,     1);
   SetLockValue("DI_SurgeProtectionHub_Ht",              TYP_32,    1000);

   SetLockValue("DI_SurgeProtectionHub400V_Ss",          TYP_8,     1);
   SetLockValue("DI_SurgeProtectionHub400V_E",           TYP_8,     1);
   SetValue("DI_SurgeProtectionHub400V_I",               TYP_8,     0);
   SetLockValue("DI_SurgeProtectionHub400V_Cm",          TYP_8,     1);
   SetLockValue("DI_SurgeProtectionHub400V_Ht",          TYP_32,    1000);
}


STATUS SurgeProtectionInitIOAliases()
{
   SurgeProtectionIOVars = SurgeProtectionIOVars1;
   SurgeProtectionIOVarsSize = SurgeProtectionIOVars1Size;
   SurgeProtectionSetLockValues = &SurgeProtectionSetLockValues1;
   return OS_SUCCESS;
}
//-----------------------------------------------------------------------
// AUTOGENERATED END        AUTOGENERATED END        AUTOGENERATED END
//-----------------------------------------------------------------------

#undef AUTOGENERATED_PART
