//*****************************PEPTOOL Header Start******************************
//                                                                               
//                         Copyright © 2015 Mita-Teknik.                         
//This software may only be used with WP4x00 Controllers delivered by Mita-Teknik
//                                                                               
//*******************************************************************************
//                                                                               
// $PEPTOOL version:9.0$                                                         
// $PEPTOOL file version:101$                                                    
//                                                                               
//*******************************************************************************
//                                                                               
// $Date: 2014/03/06 16:00:16 $                                                  
// $Author: MITA\ihn $                                                           
// $RCSfile: Transformer_Conf.c,v $                                              
// $Revision: 1.8 $                                                              
//                                                                               
//******************************PEPTOOL Header End*******************************

//***********************************************************************
// OS header files
#include <os_main.h>
// App header files
#include <InitIo.h>

#define AUTOGENERATED_PART

#include <Turbdef.h>

//-----------------------------------------------------------------------
// AUTOGENERATED START     AUTOGENERATED START     AUTOGENERATED START
//-----------------------------------------------------------------------
char Transformer_Conf_copyright[] =
{
   67, 111, 112, 121, 114, 105, 103, 104, 116, 32, 63, 32, 50, 48, 49, 53,
   32, 77, 105, 116, 97, 45, 84, 101, 107, 110, 105, 107, 46, 13, 10, 84,
   104, 105, 115, 32, 115, 111, 102, 116, 119, 97, 114, 101, 32, 109, 97, 121,
   32, 111, 110, 108, 121, 32, 98, 101, 32, 117, 115, 101, 100, 32, 119, 105,
   116, 104, 32, 87, 80, 52, 120, 48, 48, 32, 67, 111, 110, 116, 114, 111,
   108, 108, 101, 114, 115, 32, 100, 101, 108, 105, 118, 101, 114, 101, 100, 32,
   98, 121, 32, 77, 105, 116, 97, 45, 84, 101, 107, 110, 105, 107, 0
};
//-----------------------------------------------------------------------
// MODIFIABLE                  MODIFIABLE               MODIFIABLE
//-----------------------------------------------------------------------
const char TransformerAppGroupName[] = "G_"APP_ID"App";
const char TransformerAppMenuName[] = "M_"APP_ID"AppMain";

//-----------------------------------------------------------------------
// IO VARIABLES                IO VARIABLES                IO VARIABLES
//-----------------------------------------------------------------------

void (*TransformerSetLockValues)(void);
struct os_db_alias *TransformerIOVars;
size_t TransformerIOVarsSize = 0;
            
struct os_db_alias TransformerIOVars1[]=
{
    VAR_ELEMENT_ALIAS("1.4.33",                           "DI_Transformer_GasReed"),
    VAR_ELEMENT_ALIAS("1.4.33_Ss",                        "DI_Transformer_GasReed_Ss"),
    VAR_ELEMENT_ALIAS("1.4.33_E",                         "DI_Transformer_GasReed_E"),
    VAR_ELEMENT_ALIAS("1.4.33_I",                         "DI_Transformer_GasReed_I"),
    VAR_ELEMENT_ALIAS("1.4.33_Cm",                        "DI_Transformer_GasReed_Cm"),
    VAR_ELEMENT_ALIAS("1.4.33_Ht",                        "DI_Transformer_GasReed_Ht"),

    VAR_ELEMENT_ALIAS("1.4.34",                           "DI_Transformer_PressureSwitch"),
    VAR_ELEMENT_ALIAS("1.4.34_Ss",                        "DI_Transformer_PressureSwitch_Ss"),
    VAR_ELEMENT_ALIAS("1.4.34_E",                         "DI_Transformer_PressureSwitch_E"),
    VAR_ELEMENT_ALIAS("1.4.34_I",                         "DI_Transformer_PressureSwitch_I"),
    VAR_ELEMENT_ALIAS("1.4.34_Cm",                        "DI_Transformer_PressureSwitch_Cm"),
    VAR_ELEMENT_ALIAS("1.4.34_Ht",                        "DI_Transformer_PressureSwitch_Ht"),

    VAR_ELEMENT_ALIAS("1.4.35",                           "DI_Transformer_ThermostatT1"),
    VAR_ELEMENT_ALIAS("1.4.35_Ss",                        "DI_Transformer_ThermostatT1_Ss"),
    VAR_ELEMENT_ALIAS("1.4.35_E",                         "DI_Transformer_ThermostatT1_E"),
    VAR_ELEMENT_ALIAS("1.4.35_I",                         "DI_Transformer_ThermostatT1_I"),
    VAR_ELEMENT_ALIAS("1.4.35_Cm",                        "DI_Transformer_ThermostatT1_Cm"),
    VAR_ELEMENT_ALIAS("1.4.35_Ht",                        "DI_Transformer_ThermostatT1_Ht"),

    VAR_ELEMENT_ALIAS("1.4.36",                           "DI_Transformer_ThermostatT2"),
    VAR_ELEMENT_ALIAS("1.4.36_Ss",                        "DI_Transformer_ThermostatT2_Ss"),
    VAR_ELEMENT_ALIAS("1.4.36_E",                         "DI_Transformer_ThermostatT2_E"),
    VAR_ELEMENT_ALIAS("1.4.36_I",                         "DI_Transformer_ThermostatT2_I"),
    VAR_ELEMENT_ALIAS("1.4.36_Cm",                        "DI_Transformer_ThermostatT2_Cm"),
    VAR_ELEMENT_ALIAS("1.4.36_Ht",                        "DI_Transformer_ThermostatT2_Ht"),

    VAR_ELEMENT_ALIAS("1.4.15",                           "DO_Transformer_Fan"),

};
size_t TransformerIOVars1Size = sizeof(TransformerIOVars1)/sizeof(TransformerIOVars1[0]);

void TransformerSetLockValues1(void)
{
   SetLockValue("DI_Transformer_GasReed_Ss",             TYP_8,     1);
   SetLockValue("DI_Transformer_GasReed_E",              TYP_8,     1);
   SetValue("DI_Transformer_GasReed_I",                  TYP_8,     0);
   SetLockValue("DI_Transformer_GasReed_Cm",             TYP_8,     1);
   SetLockValue("DI_Transformer_GasReed_Ht",             TYP_32,    100);

   SetLockValue("DI_Transformer_PressureSwitch_Ss",      TYP_8,     1);
   SetLockValue("DI_Transformer_PressureSwitch_E",       TYP_8,     1);
   SetValue("DI_Transformer_PressureSwitch_I",           TYP_8,     0);
   SetLockValue("DI_Transformer_PressureSwitch_Cm",      TYP_8,     1);
   SetLockValue("DI_Transformer_PressureSwitch_Ht",      TYP_32,    100);

   SetLockValue("DI_Transformer_ThermostatT1_Ss",        TYP_8,     1);
   SetLockValue("DI_Transformer_ThermostatT1_E",         TYP_8,     1);
   SetValue("DI_Transformer_ThermostatT1_I",             TYP_8,     0);
   SetLockValue("DI_Transformer_ThermostatT1_Cm",        TYP_8,     1);
   SetLockValue("DI_Transformer_ThermostatT1_Ht",        TYP_32,    100);

   SetLockValue("DI_Transformer_ThermostatT2_Ss",        TYP_8,     1);
   SetLockValue("DI_Transformer_ThermostatT2_E",         TYP_8,     1);
   SetValue("DI_Transformer_ThermostatT2_I",             TYP_8,     0);
   SetLockValue("DI_Transformer_ThermostatT2_Cm",        TYP_8,     1);
   SetLockValue("DI_Transformer_ThermostatT2_Ht",        TYP_32,    100);
}


STATUS TransformerInitIOAliases()
{
   TransformerIOVars = TransformerIOVars1;
   TransformerIOVarsSize = TransformerIOVars1Size;
   TransformerSetLockValues = &TransformerSetLockValues1;
   return OS_SUCCESS;
}
//-----------------------------------------------------------------------
// AUTOGENERATED END        AUTOGENERATED END        AUTOGENERATED END
//-----------------------------------------------------------------------

#undef AUTOGENERATED_PART
