//*****************************PEPTOOL Header Start******************************
//                                                                               
//                         Copyright © 2015 Mita-Teknik.                         
//This software may only be used with WP4x00 Controllers delivered by Mita-Teknik
//                                                                               
//*******************************************************************************
//                                                                               
// $PEPTOOL version:9.0$                                                         
// $PEPTOOL file version:106$                                                    
//                                                                               
//*******************************************************************************
//                                                                               
// $Date: 2014/05/23 09:10:24 $                                                  
// $Author: MITA\ihn $                                                           
// $RCSfile: Transformer.c,v $                                                   
// $Revision: 1.16 $                                                             
//                                                                               
//******************************PEPTOOL Header End*******************************

//***********************************************************************
// OS header files
#include <os_main.h>
// AppLib header files
#include <lib_main.h>
// App header files
#include <turbdef.h>
#include <VarMacros.h>
// Object header file
#include <Transformer.h>

#define AUTOGENERATED_PART
//{
//-----------------------------------------------------------------------
// AUTOGENERATED START     AUTOGENERATED START     AUTOGENERATED START
//-----------------------------------------------------------------------

#define VALIDATE_HASH
char Transformer_copyright[] =
{
   67, 111, 112, 121, 114, 105, 103, 104, 116, 32, 63, 32, 50, 48, 49, 53,
   32, 77, 105, 116, 97, 45, 84, 101, 107, 110, 105, 107, 46, 13, 10, 84,
   104, 105, 115, 32, 115, 111, 102, 116, 119, 97, 114, 101, 32, 109, 97, 121,
   32, 111, 110, 108, 121, 32, 98, 101, 32, 117, 115, 101, 100, 32, 119, 105,
   116, 104, 32, 87, 80, 52, 120, 48, 48, 32, 67, 111, 110, 116, 114, 111,
   108, 108, 101, 114, 115, 32, 100, 101, 108, 105, 118, 101, 114, 101, 100, 32,
   98, 121, 32, 77, 105, 116, 97, 45, 84, 101, 107, 110, 105, 107, 0
};

#define MODULE_NAME "TransformerA"

//-----------------------------------------------------------------------
// ALLOCATE MEMORY FOR STRINGS IN VARDB
//-----------------------------------------------------------------------

static char A_V_Transformer_Fan_StateTxt[31]  = "12345678901234567890123456789";

//-----------------------------------------------------------------------
// DEFINE LOCAL VARIABLES DEFINE LOCAL VARIABLES DEFINE LOCAL VARIABLES
//-----------------------------------------------------------------------

static struct os_db_local LocalVars[] =
{
   VAR_ELEMENT_LOCAL("V_Transformer_Fan_StateTxt",               TYPE_STRING + sizeof(A_V_Transformer_Fan_StateTxt) - 1,  PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   A_V_Transformer_Fan_StateTxt, 0,                0,                NULL,  NOLOG_ENABLE  ),
   VAR_ELEMENT_LOCAL("V_Transformer_Fan_State",                  TYPE_U8,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   0,               U8_MIN,          U8_MAX,          NULL,  NOLOG_ENABLE),
};

//-----------------------------------------------------------------------
// DEFINE PARAMETERS        DEFINE PARAMETERS        DEFINE PARAMETERS
//-----------------------------------------------------------------------

static struct os_db_parameter ParameterVars[] =
{
   VAR_ELEMENT_PARAMETER("P_Transformer_Fan_StartDelay",             TYPE_U32,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         SCALE_DIV,    1000,    UNIT_SECOND,        0,   30000,           0,               300000,          NULL  ),
   VAR_ELEMENT_PARAMETER("P_Transformer_Fan_StopDelay",              TYPE_U32,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         SCALE_DIV,    1000,    UNIT_SECOND,        0,   30000,           0,               300000,          NULL  ),
   VAR_ELEMENT_PARAMETER("P_Transformer_Fan_ServiceCtrl",            TYPE_U8,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_NONE,   0,       UNIT_NONE,          0,   0,               0,               2,               NULL  ),
   VAR_ELEMENT_PARAMETER("P_Transformer_Fan_Start",                  TYPE_S32,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_DIV,    1000,    UNIT_KWATT,         2,   1900000,         0,               3000000,         NULL  ),
   VAR_ELEMENT_PARAMETER("P_Transformer_Fan_Stop",                   TYPE_S32,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            SCALE_DIV,    1000,    UNIT_KWATT,         2,   1000000,         0,               3000000,         NULL  ),
};

//-----------------------------------------------------------------------
// DEFINE BACKUPS            DEFINE BACKUPS            DEFINE BACKUPS
//-----------------------------------------------------------------------

//----------------------------------------------------------------------------------
// DEFINE VAR ARRAYS            DEFINE VAR ARRAYS            DEFINE VAR ARRAYS
//----------------------------------------------------------------------------------
char Transformer_initialValues[] =
{
   56, 51, 135, 215, 79, 197, 14, 144, 212, 44, 83, 91, 87, 60, 171, 13,
   16, 205, 143, 228, 16, 50, 152, 91, 60, 110, 185, 248, 183, 74, 239, 252,
   0
};

//-----------------------------------------------------------------------
// CREATE DATABASE VARS   CREATE DATABASE VARS   CREATE DATABASE VARS
//-----------------------------------------------------------------------

static STATUS CreateVarDbVars(void)
{
   STATUS Status;
   size_t ErrorEntry;

   Status = OS_VarDB_CreateLocals(LocalVars, sizeof(LocalVars)/sizeof(LocalVars[0]), &ErrorEntry, AppLocalParameterPosition());
   if (Status != 0)
   {
      AppSystemLog(ERR_7, MODULE_NAME"CrVL: %d,%d", Status, ErrorEntry);
      return ERR_7;
   }

   Status = OS_VarDB_CreateParameters(ParameterVars, sizeof(ParameterVars)/sizeof(ParameterVars[0]), &ErrorEntry, AppExportParameterPosition());
   if (Status != 0)
   {
      AppSystemLog(ERR_7, MODULE_NAME"CrVXP: %d,%d", Status, ErrorEntry);
      return ERR_7;
   }

   return OS_SUCCESS;
}

#define CREATE_VARDB_VARS

//-----------------------------------------------------------------------
// CREATE IO VARIABLES     CREATE IO VARIABLES     CREATE IO VARIABLES
//-----------------------------------------------------------------------

extern STATUS TransformerInitIOAliases();
extern struct os_db_alias* TransformerIOVars;
extern void (*TransformerSetLockValues)(void);
extern size_t TransformerIOVarsSize;

static STATUS CreateIOVars(void)
{
   STATUS Status;
   size_t ErrorEntry;

   varid_t VarId;
   BOOL variablesExist = false;
   U8 counter = 50;
   Status = TransformerInitIOAliases();
   STATUS_LINE_VAR_RETURN_VALUE(Status)
   while (!variablesExist && counter-- > 0)
   {
      variablesExist = true;
      U32 i = 0;
      for (i = 0; i < TransformerIOVarsSize; ++i)
      {
         if (OS_VarDB_GetVariableID(TransformerIOVars[i].Name, &VarId) != OS_SUCCESS)
         {
            variablesExist = false;
            break;
         }
      }

      if (!variablesExist)
      {
         OS_Sleep(100);
      }
   }

   Status = OS_VarDB_CreateAliases(TransformerIOVars, TransformerIOVarsSize, &ErrorEntry);
   if (Status)
   {
      AppDebugLog(5000, "Var Name = %s", TransformerIOVars[ErrorEntry].Alias);
   }
   STATUS_LINE_VAR_RETURN_CONST(Status, ErrorEntry);
   return OS_SUCCESS;
}

#define CREATE_IO_VARS

//-----------------------------------------------------------------------
// ALIASES                       ALIASES                       ALIASES
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// INPUT                          INPUT                          INPUT
//-----------------------------------------------------------------------

// Create local variable
#define MODUL_INPUTS
static U8 DI_Transformer_GasReed = 0;
static U8 DI_Transformer_PressureSwitch = 0;
static U8 DI_Transformer_ThermostatT1 = 0;
static U8 DI_Transformer_ThermostatT2 = 0;
static S32 AI_GridRealPower = 0;

//-----------------------------------------------------------------------
static struct ModulInOut ModulInputs[] =
{
   {"DI_Transformer_GasReed",                   &DI_Transformer_GasReed,                   sizeof(DI_Transformer_GasReed),                   },
   {"DI_Transformer_PressureSwitch",            &DI_Transformer_PressureSwitch,            sizeof(DI_Transformer_PressureSwitch),            },
   {"DI_Transformer_ThermostatT1",              &DI_Transformer_ThermostatT1,              sizeof(DI_Transformer_ThermostatT1),              },
   {"DI_Transformer_ThermostatT2",              &DI_Transformer_ThermostatT2,              sizeof(DI_Transformer_ThermostatT2),              },
   {"AI_GridRealPower",                         &AI_GridRealPower,                         sizeof(AI_GridRealPower),                         },
};

//-----------------------------------------------------------------------
// Check variable type
static STATUS VarsReadReturnStatus;
static type_t ReadVarType = TYPE_NONE;
static void VarsReadTypeCheck(void)
{
   (void)VarsReadReturnStatus;
   (void)ReadVarType;
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[0].Name,                      ModulInputs[0].Id)
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[1].Name,                      ModulInputs[1].Id)
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[2].Name,                      ModulInputs[2].Id)
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[3].Name,                      ModulInputs[3].Id)
   VERIFY_INPUT_REF_ID(S32,       ModulInputs[4].Name,                      ModulInputs[4].Id)
}

#undef MODUL_INPUTS
#define MODUL_INPUTS_SIZE (sizeof(ModulInputs)/sizeof(ModulInputs[0]))

//------------------------------------------------------------------------------------------
// READ/WRITE VARDB ARRAY      READ/WRITE VARDB ARRAY      READ/WRATE VARDB ARRAY
//------------------------------------------------------------------------------------------


//-----------------------------------------------------------------------
// PARAMETER                    PARAMETER                    PARAMETER
//-----------------------------------------------------------------------

// Create local variable
#define MODUL_PARAMETERS
static U32 P_Transformer_Fan_StartDelay = 0;
static U32 P_Transformer_Fan_StopDelay = 0;
static U8 P_Transformer_Fan_ServiceCtrl = 0;
static S32 P_Transformer_Fan_Start = 0;
static S32 P_Transformer_Fan_Stop = 0;



//-----------------------------------------------------------------------
static struct ModulInOut ModulParameters0[] =
{
   {"P_Transformer_Fan_StartDelay",             &P_Transformer_Fan_StartDelay,             sizeof(P_Transformer_Fan_StartDelay),             },
   {"P_Transformer_Fan_StopDelay",              &P_Transformer_Fan_StopDelay,              sizeof(P_Transformer_Fan_StopDelay),              },
   {"P_Transformer_Fan_ServiceCtrl",            &P_Transformer_Fan_ServiceCtrl,            sizeof(P_Transformer_Fan_ServiceCtrl),            },
   {"P_Transformer_Fan_Start",                  &P_Transformer_Fan_Start,                  sizeof(P_Transformer_Fan_Start),                  },
   {"P_Transformer_Fan_Stop",                   &P_Transformer_Fan_Stop,                   sizeof(P_Transformer_Fan_Stop),                   },

};
static struct ModulInOut* ModulParameters[] =
{
   ModulParameters0,
};

//-----------------------------------------------------------------------
// Check variable type
static STATUS ParaVarsReadReturnStatus;
static type_t ParaReadVarType = TYPE_NONE;
static void ParaVarsReadTypeCheck(void)
{
   (void)ParaVarsReadReturnStatus;
   (void)ParaReadVarType;
}

#undef MODUL_PARAMETERS

#define PARAMETERS_GROUPS_SIZE        1
#define GENERAL_GROUP                 0
#define MODUL_PARAMETERS_TOTAL_SIZE   5
static SUBSCRIPTION ParaSubscription[MODUL_PARAMETERS_TOTAL_SIZE];
static U8 ReadParameters[PARAMETERS_GROUPS_SIZE];
static U8 ParametersChanged[PARAMETERS_GROUPS_SIZE];
static UNSIGNED GroupsIndexes[PARAMETERS_GROUPS_SIZE];
static int ParaGroupsSizes[PARAMETERS_GROUPS_SIZE] = { 5 };
static STATUS VarDbUpdateParameter(varid_t VariableId, void* Message, U16 Length, UNSIGNED paraGroupIndex, UNSIGNED Ref2)
{
   ReadParameters[paraGroupIndex] = 1;
   ParametersChanged[paraGroupIndex] = 1;
   return OS_SUCCESS;
}
static STATUS ReadParametersFunc(int paraGroupIndex)
{
   STATUS LocalStatus;
   // Check inputdata
   if (sizeof(ModulParameters[paraGroupIndex]) == 0)
   {
      AppSystemLog(ERR_4, MODULE_NAME"Group %d ModuleParameters = 0", paraGroupIndex);
      return ERR_4;
   }
   // Read inputdata
   LocalStatus = OS_ReadVariables(ModulParameters[paraGroupIndex], ParaGroupsSizes[paraGroupIndex]);
   if (LocalStatus != 0)
   {
      AppSystemLog(11, "LocalStatus: %d", LocalStatus);
      AppSystemLog(ERR_4, MODULE_NAME"ReadParErr: group=%d element=%d elementpointer=0x%x", paraGroupIndex, LocalStatus, &ModulParameters[LocalStatus]);
      return ERR_4;
   }
   return OS_SUCCESS;
}


//-----------------------------------------------------------------------
// READ VARS FROM VARDB    READ VARS FROM VARDB    READ VARS FROM VARDB
//-----------------------------------------------------------------------

static STATUS InputReferenceRoutine(U8 ModuleState)
{
   STATUS LocalStatus = 0;

   // Read input references
   if (ModuleState >= APP_INIT3)
   {
      // Check inputdata
      if (sizeof(ModulInputs) == 0)
      {
         AppSystemLog(ERR_4, MODULE_NAME"ModuleInputs = 0");
         return ERR_4;
      }
      // Read inputdata
      LocalStatus = OS_ReadVariables(ModulInputs, MODUL_INPUTS_SIZE);
      if (LocalStatus != 0)
      {
         AppSystemLog(ERR_4, MODULE_NAME"ReadVErr: element=%d elementpointer=0x%x", LocalStatus, &ModulInputs[LocalStatus]);
         return ERR_4;
      }
   }
   // Read input parameters
   if (ModuleState == APP_INIT3)
   {
      static size_t ParaCounter = 0;
      int groupIndex;
      for (groupIndex = 0; groupIndex < PARAMETERS_GROUPS_SIZE; groupIndex++)
      {
         ParametersChanged[groupIndex] = 1;
         ReadParameters[groupIndex] = 1;
         GroupsIndexes[groupIndex] = groupIndex;

         // Check inputdata
         if (sizeof(ModulParameters[groupIndex]) == 0)
         {
            AppSystemLog(ERR_4, MODULE_NAME"Group = %d ModuleParameters = 0", groupIndex);
            return ERR_4;
         }
         // Read inputdata
         LocalStatus = OS_ReadVariables(ModulParameters[groupIndex], ParaGroupsSizes[groupIndex]);
         if (LocalStatus != 0)
         {
            AppSystemLog(ERR_4, MODULE_NAME"ReadVParaErr: group=%d element=%d elementpointer=0x%x", groupIndex, LocalStatus, &ModulParameters[groupIndex][LocalStatus]);
            return ERR_4;
         }
         int paraIndex;
         for (paraIndex = 0; paraIndex < ParaGroupsSizes[groupIndex]; paraIndex++)
         {
            LocalStatus = OS_SubHandl_SubscribeFunctionWithRef(&ParaSubscription[ParaCounter], 1, &ModulParameters[groupIndex][paraIndex].Id, &GroupsIndexes[groupIndex], &GroupsIndexes[groupIndex], VarDbUpdateParameter);
            ParaCounter++;
            if (LocalStatus != 0)
            {
               AppSystemLog(ERR_4, MODULE_NAME"Subscribe Parameter: group=%d element=%d elementpointer=0x%x", groupIndex, LocalStatus, &ModulParameters[LocalStatus]);
               return ERR_4;
            }
         }
      }
   }
   if (ModuleState == APP_RUN)
   {
      int groupIndex;
      for (groupIndex = 0; groupIndex < PARAMETERS_GROUPS_SIZE; groupIndex++)
      {
         if (ReadParameters[groupIndex])
         {
            LocalStatus = ReadParametersFunc(groupIndex);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
            ReadParameters[groupIndex] = 0;
         }
      }
   }

   return 0;
}

#define READ_VARS

//-----------------------------------------------------------------------
// OUTPUT                         OUTPUT                         OUTPUT
//-----------------------------------------------------------------------

// Create local variable
#define MODUL_OUTPUTS
static U8 DO_Transformer_Fan = 0;
static U8 V_Transformer_Fan_State = 0;
static char V_Transformer_Fan_StateTxt[31];


//-----------------------------------------------------------------------
static struct ModulInOut ModulOutputs[] =
{
   {"DO_Transformer_Fan",                       &DO_Transformer_Fan,                       sizeof(DO_Transformer_Fan),                       },
   {"V_Transformer_Fan_StateTxt",               &V_Transformer_Fan_StateTxt,               sizeof(V_Transformer_Fan_StateTxt),               },
   {"V_Transformer_Fan_State",                  &V_Transformer_Fan_State,                  sizeof(V_Transformer_Fan_State),                  },
};

//-----------------------------------------------------------------------
// Check variable type
static STATUS VarsWriteReturnStatus;
static type_t WriteVarType = TYPE_NONE;
static void VarsWriteTypeCheck(void)
{
   (void)VarsWriteReturnStatus;
   (void)WriteVarType;
   VERIFY_OUTPUT_REF_ID(U8,        ModulOutputs[0].Name,                     ModulOutputs[0].Id,                       0)
   VERIFY_OUTPUT_STRING_REF_ID(STRING,     ModulOutputs[1].Name,                      ModulOutputs[1].Id, 0)
   VERIFY_OUTPUT_REF_ID(U8,        ModulOutputs[2].Name,                     ModulOutputs[2].Id,                       0)
}

#undef MODUL_OUTPUTS
#define MODUL_OUTPUTS_SIZE (sizeof(ModulOutputs)/sizeof(ModulOutputs[0]))

//-----------------------------------------------------------------------
// WRITE VARS TO VARDB     WRITE VARS TO VARDB     WRITE VARS TO VARDB
//-----------------------------------------------------------------------

static STATUS InitOutputVars(void)
{
   STATUS LocalStatus;
   // Read outputdata
   LocalStatus = OS_ReadVariables(ModulOutputs, MODUL_OUTPUTS_SIZE);
   if (LocalStatus != 0)
   {
      AppSystemLog(ERR_4, MODULE_NAME"InitErr: element=%d elementpointer=0x%x", LocalStatus, &ModulOutputs[LocalStatus]);
      return ERR_4;
   }
   return OS_SUCCESS;
}
static STATUS OutputReferenceRoutine(U8 ModuleState)
{
   STATUS LocalStatus = 0;
   // Write Outputdata
   LocalStatus = OS_WriteVariablesConditional(ModulOutputs, MODUL_OUTPUTS_SIZE);
   if (LocalStatus != 0)
   {
      AppSystemLog(ERR_5, MODULE_NAME"WriteVErr: element=%d elementpointer=0x%x", LocalStatus, &ModulOutputs[LocalStatus]);
      return ERR_5;
   }
   return 0;
}

#define WRITE_VARS

//-----------------------------------------------------------------------
// VERIFY VARIABLES CREATION                 VERIFY VARIABLES CREATION
//-----------------------------------------------------------------------

static STATUS LocalIoCheck(void)
{
   // Check if input variables exist.
   STATUS LocalStatus;

   LocalStatus = OS_DoesVariablesExist(ModulInputs, MODUL_INPUTS_SIZE);
   if (LocalStatus != 0)
   {
      AppSystemLog(ERR_1, MODULE_NAME"InputErr: %d", LocalStatus);
      AppSystemLog(ERR_1, "Name: %s", ModulInputs[LocalStatus-1].Name);
      return ERR_1;
   }
   (void)VarsReadTypeCheck();

   int groupIndex;
   for (groupIndex = 0; groupIndex < PARAMETERS_GROUPS_SIZE; groupIndex++)
   {
      LocalStatus = OS_DoesVariablesExist(ModulParameters[groupIndex], ParaGroupsSizes[groupIndex]);
      if (LocalStatus != 0)
      {
         AppSystemLog(ERR_3, MODULE_NAME"ParameterErr: %d Group:%d", LocalStatus, groupIndex);
         AppSystemLog(ERR_3, "Name: %s", ModulParameters[groupIndex][LocalStatus-1].Name);
         return ERR_3;
      }
   }
   (void)ParaVarsReadTypeCheck();

   LocalStatus = OS_DoesVariablesExist(ModulOutputs, MODUL_OUTPUTS_SIZE);
   if (LocalStatus != 0)
   {
      AppSystemLog(ERR_2, MODULE_NAME"OutputErr: %d", LocalStatus);
      AppSystemLog(ERR_2, "Name: %s", ModulOutputs[LocalStatus-1].Name);
      return ERR_2;
   }
   (void)VarsWriteTypeCheck();

   return OS_SUCCESS;
}

#define VERIFY_VARIABLES

//-----------------------------------------------------------------------
// ALLOCATE MEMORY FOR SUMMATIONS        ALLOCATE MEMORY FOR SUMMATIONS
//-----------------------------------------------------------------------

static SSUM SSummationS_TransformerCoolingFan;

//-----------------------------------------------------------------------
// SUMMATIONS                  SUMMATIONS                  SUMMATIONS
//-----------------------------------------------------------------------

static struct os_db_summation ServiceSummations[] =
{
   VAR_ELEMENT_SERVICE_SUM( "S_TransformerCoolingFan",                  PASSWORD_LEVEL_UNLOGGED_IN,        PASSWORD_LEVEL_UNLOGGED_IN,        "DO_Transformer_Fan",                       SSummationS_TransformerCoolingFan   ),
};

static STATUS CreateSummations(void)
{
  STATUS LocalStatus = 0;
  size_t ErrorEntry = 0;

  LocalStatus = OS_SUM_CreateSummations(ServiceSummations, sizeof(ServiceSummations)/sizeof(ServiceSummations[0]), &ErrorEntry, AppBackupPosition());
  if (OS_SUCCESS != LocalStatus)
  {
    return LocalStatus;
  }

  return LocalStatus;
}

#define CREATE_SUMMATIONS

//-----------------------------------------------------------------------
// DEFINE MENUS               DEFINE MENUS               DEFINE MENUS
//-----------------------------------------------------------------------



// Menu line and link to local menu
//-----------------------------------------------------------------------
static struct line_struct M_TransformerLinkToLocalMenu[] =
{
   MENU_ELEMENT_LINE_LINK("Transformer",                       PASSWORD_LEVEL_END_CUSTOMER,        "M_Transformer",                    "G_Transformer"),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_TransformerMenu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_Transformer",                    PASSWORD_LEVEL_END_CUSTOMER),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_TransformerMenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("TRANSFORMER",                       PASSWORD_LEVEL_END_CUSTOMER,        "M_"APP_ID"AppMain",                "G_"APP_ID"App"),
   MENU_ELEMENT_LINE_VARRO("Transformer Gas Reed",             PASSWORD_LEVEL_END_CUSTOMER,        (char*)"DI_Transformer_GasReed",                     LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Transformer Pressure Switch",      PASSWORD_LEVEL_END_CUSTOMER,        (char*)"DI_Transformer_PressureSwitch",              LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Transformer Thermostat T1",        PASSWORD_LEVEL_END_CUSTOMER,        (char*)"DI_Transformer_ThermostatT1",                LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Transformer Thermostat T2",        PASSWORD_LEVEL_END_CUSTOMER,        (char*)"DI_Transformer_ThermostatT2",                LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Transformer Fan State",            PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_Transformer_Fan_StateTxt",                 LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Transformer Fan",                  PASSWORD_LEVEL_END_CUSTOMER,        (char*)"DO_Transformer_Fan",                         LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_LINK("Parameter",                         PASSWORD_LEVEL_END_CUSTOMER,        "M_Parameter4",                     "G_Transformer"),
   MENU_ELEMENT_LINE_LINK("Service",                           PASSWORD_LEVEL_SERVICE,             "M_Service3527",                    "G_Transformer"),
   MENU_ELEMENT_LINE_LINK("Debug",                             PASSWORD_LEVEL_MITA_PROGRAMMER,     "M_Debug22",                        "G_Transformer"),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_Parameter4Menu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_Parameter4",                     PASSWORD_LEVEL_END_CUSTOMER),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_Parameter4MenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("PARAMETER",                         PASSWORD_LEVEL_END_CUSTOMER,        "M_Transformer",                    "G_Transformer"),
   MENU_ELEMENT_LINE_VARRW("Transformer Fan Start",            PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_Transformer_Fan_Start",                    LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Transformer Fan Start Delay",      PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_Transformer_Fan_StartDelay",               LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Transformer Fan Stop",             PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_Transformer_Fan_Stop",                     LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Transformer Fan Stop Delay",       PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_Transformer_Fan_StopDelay",                LINE_FORMAT_NONE),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_Service3527Menu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_Service3527",                    PASSWORD_LEVEL_SERVICE),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_Service3527MenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("SERVICE",                           PASSWORD_LEVEL_SERVICE,             "M_Transformer",                    "G_Transformer"),
   MENU_ELEMENT_LINE_VARRW("Transformer Fan Service Control",  PASSWORD_LEVEL_SERVICE,             (char*)"P_Transformer_Fan_ServiceCtrl",              LINE_FORMAT_NONE),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_Debug22Menu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_Debug22",                        PASSWORD_LEVEL_MITA_PROGRAMMER),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_Debug22MenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("DEBUG",                             PASSWORD_LEVEL_MITA_PROGRAMMER,     "M_Transformer",                    "G_Transformer"),
   MENU_ELEMENT_LINE_VARRO("Transformer Fan State",            PASSWORD_LEVEL_MITA_PROGRAMMER,     (char*)"V_Transformer_Fan_State",                    LINE_FORMAT_NONE),
};
// Creating parameters for multiplexed categories
//-----------------------------------------------------------------------
static struct multiplexed_info_struct M_TransformerMultiplexedCategoriesParameters[] =
{
0};

//-----------------------------------------------------------------------
// CREATE MENUS               CREATE MENUS               CREATE MENUS
//-----------------------------------------------------------------------

// Memory reservation
//-----------------------------------------------------------------------
static struct menu_group_struct ObjGroup[1];

// Creating the menus
//-----------------------------------------------------------------------
STATUS TransformerMenuAppInit(U8 ModuleState, OS_MEMORY_POOL* pPool)
{
   STATUS Status;

   if (ModuleState == APP_INIT1)
   {
      /* Create application group */
      Status = OS_CreateMenuGroup(ObjGroup, M_TransformerLinkToLocalMenu[0].LinkGroup);
      STATUS_LINE_VAR_RETURN_VALUE(Status);
   }

   Status = CreateAndInitializeMenu(ModuleState,
                                    M_TransformerMenuLines[0].LinkGroup,
                                    M_TransformerMenuLines[0].LinkName,
                                    ELEMENT(M_TransformerLinkToLocalMenu),
                                    M_TransformerLinkToLocalMenu[0].LinkGroup,
                                    ELEMENT(M_TransformerMenu),
                                    M_TransformerLinkToLocalMenu[0].LinkName,
                                    ELEMENT(M_TransformerMenuLines),
                                    pPool,
                                    M_TransformerMultiplexedCategoriesParameters);
   STATUS_LINE_VAR_RETURN_VALUE(Status);

   Status = CreateAndInitializeMenu(ModuleState,
                                    M_Parameter4MenuLines[0].LinkGroup,
                                    M_Parameter4MenuLines[0].LinkName,
                                    NULL,
                                    0,
                                    M_TransformerMenuLines[7].LinkGroup,
                                    ELEMENT(M_Parameter4Menu),
                                    M_TransformerMenuLines[7].LinkName,
                                    ELEMENT(M_Parameter4MenuLines),
                                    pPool,
                                    M_TransformerMultiplexedCategoriesParameters);
   STATUS_LINE_VAR_RETURN_VALUE(Status);

   Status = CreateAndInitializeMenu(ModuleState,
                                    M_Service3527MenuLines[0].LinkGroup,
                                    M_Service3527MenuLines[0].LinkName,
                                    NULL,
                                    0,
                                    M_TransformerMenuLines[8].LinkGroup,
                                    ELEMENT(M_Service3527Menu),
                                    M_TransformerMenuLines[8].LinkName,
                                    ELEMENT(M_Service3527MenuLines),
                                    pPool,
                                    M_TransformerMultiplexedCategoriesParameters);
   STATUS_LINE_VAR_RETURN_VALUE(Status);

   Status = CreateAndInitializeMenu(ModuleState,
                                    M_Debug22MenuLines[0].LinkGroup,
                                    M_Debug22MenuLines[0].LinkName,
                                    NULL,
                                    0,
                                    M_TransformerMenuLines[9].LinkGroup,
                                    ELEMENT(M_Debug22Menu),
                                    M_TransformerMenuLines[9].LinkName,
                                    ELEMENT(M_Debug22MenuLines),
                                    pPool,
                                    M_TransformerMultiplexedCategoriesParameters);
   STATUS_LINE_VAR_RETURN_VALUE(Status);

   return OS_SUCCESS;
}

#define CREATE_MENU

//-----------------------------------------------------------------------
//               BUTTONS FUNCTIONS FORWARD DECLARATIONS
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// BUTTONS                       BUTTONS                      BUTTONS
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
//             SET/RESET FUNCTIONS FORWARD DECLARATIONS
//-----------------------------------------------------------------------
static U8 StatusSetFunc611(void);
static U8 StatusResetFunc611(void);
static U8 StatusSetFunc612(void);
static U8 StatusSetFunc614(void);
static U8 StatusSetFunc2462(void);
static U8 StatusResetFunc2462(void);
//-----------------------------------------------------------------------
// STATUSCODES                 STATUSCODES                 STATUSCODES
//-----------------------------------------------------------------------

static struct sts_statuscode_structure StatusCodes[] =
{
   STS_CODE_ELEMENT("Trafo oil temp. high",   20*SEC,    611,       STATUSCODE_UPDATE_TYPE_POLLING,         PASSWORD_LEVEL_SERVICE,            STATUSCODE_TIMER_TYPE_CONSTANT,     STATUSCODE_TIMER_TYPE_CONSTANT,     STATUSCODE_RESET_TYPE_AUTOMATIC,    STATUSCODE_PRIORITY_LOW,       27,   1,    32,   NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         StatusSetFunc611,        StatusResetFunc611,      BRAKE_PROG_0,        BRAKE_PROG_0,        BRAKE_PROG_MAX,      NULL,                PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    YAW_PROG_0,          YAW_PROG_0,          YAW_PROG_240,        NULL,                PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    1,    0,    255,  NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            1,  PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      1000,      20,        1000,      NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         SETDELAY_MIN,   SETDELAY_MAX,   NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         5*MINUTE,  RESETDELAY_MIN, RESETDELAY_MAX, NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         0,         REPEATTIMES_MIN,     REPEATTIMES_MAX,     NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         REPEATPERIOD_MIN,    REPEATPERIOD_MAX,    NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         REPEATCODE_MIN,      REPEATCODE_MAX,      NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         TIMEOUTPERIOD_MIN,   65535,               NULL,      PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         TIMEOUTCODE_MIN,     TIMEOUTCODE_MAX,     NULL,      PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         NULL),
   STS_CODE_ELEMENT("Trafo oil temp. stop",   20*SEC,    612,       STATUSCODE_UPDATE_TYPE_POLLING,         PASSWORD_LEVEL_SERVICE,            STATUSCODE_TIMER_TYPE_CONSTANT,     STATUSCODE_TIMER_TYPE_CONSTANT,     STATUSCODE_RESET_TYPE_DISPLAY,      STATUSCODE_PRIORITY_LOW,       22,   1,    32,   NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         StatusSetFunc612,        NULL,                    BRAKE_PROG_50,       BRAKE_PROG_0,        BRAKE_PROG_MAX,      NULL,                PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    YAW_PROG_0,          YAW_PROG_0,          YAW_PROG_240,        NULL,                PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    1,    0,    255,  NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            1,  PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      100,       20,        1000,      NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         SETDELAY_MIN,   SETDELAY_MAX,   NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         0,         RESETDELAY_MIN, RESETDELAY_MAX, NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         0,         REPEATTIMES_MIN,     REPEATTIMES_MAX,     NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         REPEATPERIOD_MIN,    REPEATPERIOD_MAX,    NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         REPEATCODE_MIN,      REPEATCODE_MAX,      NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         TIMEOUTPERIOD_MIN,   65535,               NULL,      PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         TIMEOUTCODE_MIN,     TIMEOUTCODE_MAX,     NULL,      PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         NULL),
   STS_CODE_ELEMENT("Trafo oil press.",       20*SEC,    614,       STATUSCODE_UPDATE_TYPE_POLLING,         PASSWORD_LEVEL_SERVICE,            STATUSCODE_TIMER_TYPE_CONSTANT,     STATUSCODE_TIMER_TYPE_CONSTANT,     STATUSCODE_RESET_TYPE_DISPLAY,      STATUSCODE_PRIORITY_LOW,       15,   1,    32,   NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         StatusSetFunc614,        NULL,                    BRAKE_PROG_99,       BRAKE_PROG_0,        BRAKE_PROG_MAX,      NULL,                PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    YAW_PROG_0,          YAW_PROG_0,          YAW_PROG_240,        NULL,                PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    1,    0,    255,  NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            1,  PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      100,       20,        1000,      NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         SETDELAY_MIN,   SETDELAY_MAX,   NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         0,         RESETDELAY_MIN, RESETDELAY_MAX, NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         0,         REPEATTIMES_MIN,     REPEATTIMES_MAX,     NULL,      PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         REPEATPERIOD_MIN,    REPEATPERIOD_MAX,    NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         REPEATCODE_MIN,      REPEATCODE_MAX,      NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         TIMEOUTPERIOD_MIN,   TIMEOUTPERIOD_MAX,   NULL,      PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         TIMEOUTCODE_MIN,     TIMEOUTCODE_MAX,     NULL,      PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         NULL),
   STS_CODE_ELEMENT("Trafo gas high",         20*SEC,    2462,      STATUSCODE_UPDATE_TYPE_POLLING,         PASSWORD_LEVEL_SERVICE,            STATUSCODE_TIMER_TYPE_CONSTANT,     STATUSCODE_TIMER_TYPE_CONSTANT,     STATUSCODE_RESET_TYPE_AUTOMATIC,    STATUSCODE_PRIORITY_LOW,       27,   0,    32,   NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         StatusSetFunc2462,       StatusResetFunc2462,     0,                   BRAKE_PROG_0,        BRAKE_PROG_MAX,      NULL,                PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,                   YAW_PROG_0,          YAW_PROG_240,        NULL,                PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,    0,    255,  NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            1,  PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      100,       20,        1000,      NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         SETDELAY_MIN,   SETDELAY_MAX,   NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         5*MINUTE,  RESETDELAY_MIN, RESETDELAY_MAX, NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         0,         REPEATTIMES_MIN,     REPEATTIMES_MAX,     NULL,      PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         REPEATPERIOD_MIN,    REPEATPERIOD_MAX,    NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         REPEATCODE_MIN,      REPEATCODE_MAX,      NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         TIMEOUTPERIOD_MIN,   TIMEOUTPERIOD_MAX,   NULL,      PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         TIMEOUTCODE_MIN,     TIMEOUTCODE_MAX,     NULL,      PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         NULL),
};

static STATUS_CODE_CONTROL_BLOCK StatusCodeControlBlock;

static STATUS LocalStatusCodeInit(void)
{
   STATUS LocalStatus;

   LocalStatus = OS_StatusCodeInit(STATUSCODE_INTERFACE_VERSION,
                                   &StatusCodeControlBlock,
                                   StatusCodes,
                                   sizeof(StatusCodes)/sizeof(StatusCodes[0]),
                                   AppLocalParameterPosition(),
                                   AppBackupPosition());
   STATUS_LINE_VAR_RETURN_CONST(LocalStatus, ERR_3);

   return OS_SUCCESS;
}

#define CREATE_STATUS_CODES

//-----------------------------------------------------------------------
// MODIFIABLE                  MODIFIABLE                   MODIFIABLE
//-----------------------------------------------------------------------

extern const char TransformerAppGroupName[];
extern const char TransformerAppMenuName[];

static void Init_Structures_From_Conf_File(void)
{
   M_TransformerMenuLines[0].LinkName = (char*)TransformerAppMenuName;
   M_TransformerMenuLines[0].LinkGroup = (char*)TransformerAppGroupName;
}

//-----------------------------------------------------------------------
// AUTOGENERATED END        AUTOGENERATED END        AUTOGENERATED END
//-----------------------------------------------------------------------
//}

#undef AUTOGENERATED_PART

//-----------------------------------------------------------------------
// USER DEFINITIONS         USER DEFINITIONS         USER DEFINITIONS
//-----------------------------------------------------------------------

volatile const U8 Transformer_ModuleInterfaceError_Version_1; // Version check

//-----------------------------------------------------------------------
// SET/RESET FUNCTIONS    SET/RESET FUNCTIONS    SET/RESET FUNCTIONS
//-----------------------------------------------------------------------
//_______________________________________________ Trafo oil temp. high
static U8 StatusSetFunc611( void )
{
    if ( WPlineError() )
    {
       return 0;
    }

    return !DI_Transformer_ThermostatT1;
}

static U8 StatusResetFunc611( void )
{
    return !StatusSetFunc611();
}
//_______________________________________________ Trafo oil temp. stop
static U8 StatusSetFunc612( void )
{
    if ( WPlineError() )
    {
       return 0;
    }

    return !DI_Transformer_ThermostatT2;
}
//_______________________________________________ Trafo oil press.stop
static U8 StatusSetFunc614( void )
{
    if ( WPlineError() )
    {
       return 0;
    }

    return !DI_Transformer_PressureSwitch;
}
//_______________________________________________ Trafo gas high
static U8 StatusSetFunc2462( void )
{
    if ( WPlineError() )
    {
       return 0;
    }

    return !DI_Transformer_GasReed;
}

static U8 StatusResetFunc2462( void )
{
    return !StatusSetFunc2462();
}
//-----------------------------------------------------------------------
// DRIVER FUNCTION         DRIVER FUNCTION         DRIVER FUNCTION
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// INIT                   INIT                     INIT
//-----------------------------------------------------------------------

static struct StandardTimerVarStruct TrafoFanStartDelay =
{
   0,                               // Timer value [ms]
   &P_Transformer_Fan_StartDelay,   // Pointer to the timeout variable [ms]
   TRANSFORMER_TIMER,               // Timer interval [ms]. The function "StandardTimer" is called with this interval.
   TIMER_STOP,                      // Start TIMER_DOWN / TIMER_STOP / TIMER_UP
   0                                // Is used to check if the "StandardTimer" function is called.
};

static struct StandardTimerVarStruct TrafoFanStopDelay =
{
   0,                               // Timer value [ms]
   &P_Transformer_Fan_StopDelay,    // Pointer to the timeout variable [ms]
   TRANSFORMER_TIMER,               // Timer interval [ms]. The function "StandardTimer" is called with this interval.
   TIMER_STOP,                      // Start TIMER_DOWN / TIMER_STOP / TIMER_UP
   0                                // Is used to check if the "StandardTimer" function is called.
};

typedef enum _TRAFO_MODE
{
    TRAFO_MODE_AUTO = 0,
    TRAFO_MODE_FORCED_OFF,
    TRAFO_MODE_FORCED_ON
}_TRAFO_MODE_t;

typedef enum _TRAFO_STATE
{
    TRAFO_STATE_AUTO_OFF = 0,
    TRAFO_STATE_AUTO_ON,
    TRAFO_STATE_FORCED_OFF,
    TRAFO_STATE_FORCED_ON,
    TRAFO_STATE_UNDEFINED = 0xff
}_TRAFO_STATE_t;

//-----------------------------------------------------------------------
// CONTROL                CONTROL                 CONTROL
//-----------------------------------------------------------------------
static void TrafoFanStateTxt(S32 State, S32 *PrevState, char *Text, S32 Size)
{
    if( State != *PrevState )
    {
        switch( State )
        {
           case TRAFO_STATE_AUTO_OFF:
                strncpy( Text, "AUTO OFF", Size );
                break;

           case TRAFO_STATE_AUTO_ON:
                strncpy( Text, "AUTO ON", Size );
                break;

           case TRAFO_STATE_FORCED_OFF:
                strncpy( Text, "FORCED OFF", Size );
                break;

            case TRAFO_STATE_FORCED_ON:
                strncpy( Text, "FORCED ON", Size );
                break;

            case TRAFO_STATE_UNDEFINED:
                //drop to default
            default:
                strncpy( Text, "WARNING", Size );
                break;
        }
    }

    *PrevState = State;
}
//_______________________________________________________________________
static void TrafoFanAutoCtlr()
{
    if( P_Transformer_Fan_Start < AI_GridRealPower )
    {
        StartTimer(&TrafoFanStartDelay);
        ResetTimer(&TrafoFanStopDelay);

        if( StandardTimer(&TrafoFanStartDelay) )
        {
            ResetTimer(&TrafoFanStartDelay);
            DO_Transformer_Fan = ON;
            V_Transformer_Fan_State = TRAFO_STATE_AUTO_ON;
        }
    }
    else if( (P_Transformer_Fan_Stop > AI_GridRealPower) &&
            DI_Transformer_ThermostatT1 && DI_Transformer_ThermostatT2)
    {
        StartTimer(&TrafoFanStopDelay);
        ResetTimer(&TrafoFanStartDelay);

        if( StandardTimer(&TrafoFanStopDelay) )
        {
            ResetTimer(&TrafoFanStopDelay);
            DO_Transformer_Fan = OFF;
            V_Transformer_Fan_State = TRAFO_STATE_AUTO_OFF;
        }
    }
}
//_______________________________________________________________________
static STATUS LocalCtrl( void )
{
    STATUS LocalStatus = 0;
    static S32 PrevFanState = TRAFO_STATE_UNDEFINED;


    switch(P_Transformer_Fan_ServiceCtrl)
    {
        case TRAFO_MODE_AUTO:
            TrafoFanAutoCtlr();
            break;

        case TRAFO_MODE_FORCED_OFF:
            DO_Transformer_Fan = OFF;
            V_Transformer_Fan_State = TRAFO_STATE_FORCED_OFF;
            break;

        case TRAFO_MODE_FORCED_ON:
            DO_Transformer_Fan = ON;
            V_Transformer_Fan_State = TRAFO_STATE_FORCED_ON;
            break;

        default:
            DO_Transformer_Fan = OFF;
            V_Transformer_Fan_State = TRAFO_STATE_UNDEFINED;
            break;
    }

    TrafoFanStateTxt(V_Transformer_Fan_State, &PrevFanState, V_Transformer_Fan_StateTxt, sizeof(V_Transformer_Fan_StateTxt));

    return LocalStatus;
}
//-----------------------------------------------------------------------
// MAIN CALL             MAIN CALL               MAIN CALL
//-----------------------------------------------------------------------

STATUS Transformer( U8 ModuleState, OS_MEMORY_POOL *MemPool, U32 *Arg3 )
{
    STATUS LocalStatus = 0;

    // Version check
    if( ModuleState == APP_INIT1 )
    {
        LocalStatus = OS_ValidateAPI( API_VERSION_MAJOR,
                                      API_VERSION_MINOR,
                                      OS_LinkTime,
                                      ReleaseTag,
                                      __MODULE__ );
        if( OS_SUCCESS != LocalStatus )
        {
            return LocalStatus;
        }
    }
#ifdef READ_VARS
    // Read inputdata
    LocalStatus = InputReferenceRoutine( ModuleState );
    STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif
#ifdef COMMON_VDB_READ
    LocalStatus = ReadVdbWindow(ModuleState);
    STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif
    switch( ModuleState )
    {
        case APP_RUN:
        {
         #ifdef FUNCTION_BLOCKS_PRE_LOCAL_CONTROL
            LocalStatus = FunctionBlocksPreLocalCtrl( Interval );
            STATUS_LINE_VAR_RETURN_VALUE( LocalStatus );
         #endif

            LocalStatus = LocalCtrl();
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
        
         #ifdef FUNCTION_BLOCKS_POST_LOCAL_CONTROL
            LocalStatus = FunctionBlocksPostLocalCtrl( Interval );
            STATUS_LINE_VAR_RETURN_VALUE( LocalStatus );
         #endif

#ifdef WRITE_VARS
            // Write Outputdata
            LocalStatus = OutputReferenceRoutine( ModuleState );
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif

#ifdef COMMON_VDB_WRITE
            LocalStatus = WriteVdbWindow(ModuleState);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif
            break;
        }
        case APP_INIT1:
        {
            Init_Structures_From_Conf_File();
            (void)Transformer_ModuleInterfaceError_Version_1; // Version check

#ifdef CREATE_MENU
            LocalStatus = TransformerMenuAppInit( ModuleState, MemPool );
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)

#ifdef MULTIPLEXIBLE_MENU
            LocalStatus = MenuArraysAppInit(ModuleState, MemPool);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif
#endif

#ifdef CREATE_VARDB_VARS
            LocalStatus = CreateVarDbVars();
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif

#ifdef CREATE_VARDB_ARRAY_VARS
            LocalStatus = CreateVdbArrays(MemPool);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif

#ifdef CREATE_IO_VARS
            LocalStatus = CreateIOVars();
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif
            break;
        }
        case APP_INIT2:
        {
#ifdef CREATE_MENU
#ifdef MULTIPLEXIBLE_MENU
            LocalStatus = MenuArraysAppInit(ModuleState, MemPool);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif
#endif

#ifdef CREATE_ALIASES
            size_t ErrorEntry = 0;
            LocalStatus = OS_VarDB_CreateAliases(AliasVars, sizeof(AliasVars)/sizeof(AliasVars[0]), &ErrorEntry);
            STATUS_LINE_VAR_RETURN_CONST(LocalStatus, ErrorEntry)
#endif

#ifdef VERIFY_ARRAY
            LocalStatus = VerifyArray();
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif

#ifdef VERIFY_VARIABLES
            LocalStatus = LocalIoCheck();
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif

#ifdef CREATE_BUTTONS
            LocalStatus = CreateButtons();
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif
            break;
        }
        case APP_INIT3:
        {
#ifdef CREATE_SUMMATIONS
            LocalStatus = CreateSummations();
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif

#ifdef WRITE_VARS
            LocalStatus = InitOutputVars();
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif

#ifdef CREATE_STATUS_CODES
            LocalStatus = LocalStatusCodeInit();
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif

#ifdef CREATE_IO_VARS
            TransformerSetLockValues();
#endif
            break;
        }
        case APP_INIT4:
        {
#ifdef CREATE_MENU
            LocalStatus = TransformerMenuAppInit( ModuleState, MemPool );
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)

#ifdef MULTIPLEXIBLE_MENU
            LocalStatus = MenuArraysAppInit(ModuleState, MemPool);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif
#endif
            break;
        }
        case APP_INIT5:
        {
#ifdef VALIDATE_HASH
            LocalStatus = ValidateHash( Transformer_copyright, MODULE_NAME, Transformer_initialValues );
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif

         #ifdef INIT_FUNCTION_BLOCKS
            LocalStatus = FunctionBlocksInit( Interval );
            STATUS_LINE_VAR_RETURN_VALUE( LocalStatus );
         #endif

            break;
        }
        default:
        {
            break;
        }
    }
    return OS_SUCCESS;
}
//-----------------------------------------------------------------------
