//*****************************PEPTOOL Header Start******************************
//                                                                               
//                         Copyright © 2015 Mita-Teknik.                         
//This software may only be used with WP4x00 Controllers delivered by Mita-Teknik
//                                                                               
//*******************************************************************************
//                                                                               
// $PEPTOOL version:9.0$                                                         
// $PEPTOOL file version:101$                                                    
//                                                                               
//*******************************************************************************
//                                                                               
// $Date: XXXX/XX/XX XX:XX:XX $                                                  
// $Author: XXXX\XXX $                                                           
// $RCSfile: UPS1_Conf.c,v $                                                     
// $Revision: X.X $                                                              
//                                                                               
//******************************PEPTOOL Header End*******************************

//***********************************************************************
// OS header files
#include <os_main.h>
// App header files
#include <InitIo.h>

#define AUTOGENERATED_PART

#include <Turbdef.h>

//-----------------------------------------------------------------------
// AUTOGENERATED START     AUTOGENERATED START     AUTOGENERATED START
//-----------------------------------------------------------------------
char UPS1_Conf_copyright[] =
{
   67, 111, 112, 121, 114, 105, 103, 104, 116, 32, 63, 32, 50, 48, 49, 53,
   32, 77, 105, 116, 97, 45, 84, 101, 107, 110, 105, 107, 46, 13, 10, 84,
   104, 105, 115, 32, 115, 111, 102, 116, 119, 97, 114, 101, 32, 109, 97, 121,
   32, 111, 110, 108, 121, 32, 98, 101, 32, 117, 115, 101, 100, 32, 119, 105,
   116, 104, 32, 87, 80, 52, 120, 48, 48, 32, 67, 111, 110, 116, 114, 111,
   108, 108, 101, 114, 115, 32, 100, 101, 108, 105, 118, 101, 114, 101, 100, 32,
   98, 121, 32, 77, 105, 116, 97, 45, 84, 101, 107, 110, 105, 107, 0
};
//-----------------------------------------------------------------------
// MODIFIABLE                  MODIFIABLE               MODIFIABLE
//-----------------------------------------------------------------------
const char UPS1AppGroupName[] = "G_"APP_ID"App";
const char UPS1AppMenuName[] = "M_"APP_ID"AppMain";

//-----------------------------------------------------------------------
// IO VARIABLES                IO VARIABLES                IO VARIABLES
//-----------------------------------------------------------------------

void (*UPS1SetLockValues)(void);
struct os_db_alias *UPS1IOVars;
size_t UPS1IOVarsSize = 0;
            
struct os_db_alias UPS1IOVars1[]=
{
    VAR_ELEMENT_ALIAS("5.2.30",                           "DI_UPS1_Ready"),
    VAR_ELEMENT_ALIAS("5.2.30_Ss",                        "DI_UPS1_Ready_Ss"),
    VAR_ELEMENT_ALIAS("5.2.30_E",                         "DI_UPS1_Ready_E"),
    VAR_ELEMENT_ALIAS("5.2.30_I",                         "DI_UPS1_Ready_I"),
    VAR_ELEMENT_ALIAS("5.2.30_Cm",                        "DI_UPS1_Ready_Cm"),
    VAR_ELEMENT_ALIAS("5.2.30_Ht",                        "DI_UPS1_Ready_Ht"),

    VAR_ELEMENT_ALIAS("5.2.31",                           "DI_UPS1_Buffering"),
    VAR_ELEMENT_ALIAS("5.2.31_Ss",                        "DI_UPS1_Buffering_Ss"),
    VAR_ELEMENT_ALIAS("5.2.31_E",                         "DI_UPS1_Buffering_E"),
    VAR_ELEMENT_ALIAS("5.2.31_I",                         "DI_UPS1_Buffering_I"),
    VAR_ELEMENT_ALIAS("5.2.31_Cm",                        "DI_UPS1_Buffering_Cm"),
    VAR_ELEMENT_ALIAS("5.2.31_Ht",                        "DI_UPS1_Buffering_Ht"),

    VAR_ELEMENT_ALIAS("5.2.32",                           "DI_UPS1_Replace_Battery"),
    VAR_ELEMENT_ALIAS("5.2.32_Ss",                        "DI_UPS1_Replace_Battery_Ss"),
    VAR_ELEMENT_ALIAS("5.2.32_E",                         "DI_UPS1_Replace_Battery_E"),
    VAR_ELEMENT_ALIAS("5.2.32_I",                         "DI_UPS1_Replace_Battery_I"),
    VAR_ELEMENT_ALIAS("5.2.32_Cm",                        "DI_UPS1_Replace_Battery_Cm"),
    VAR_ELEMENT_ALIAS("5.2.32_Ht",                        "DI_UPS1_Replace_Battery_Ht"),

    VAR_ELEMENT_ALIAS("5.2.5",                            "DO_UPS1_Inhibit"),

};
size_t UPS1IOVars1Size = sizeof(UPS1IOVars1)/sizeof(UPS1IOVars1[0]);

void UPS1SetLockValues1(void)
{
   SetLockValue("DI_UPS1_Ready_Ss",                      TYP_8,     1);
   SetLockValue("DI_UPS1_Ready_E",                       TYP_8,     1);
   SetValue("DI_UPS1_Ready_I",                           TYP_8,     0);
   SetLockValue("DI_UPS1_Ready_Cm",                      TYP_8,     1);
   SetLockValue("DI_UPS1_Ready_Ht",                      TYP_32,    100);

   SetLockValue("DI_UPS1_Buffering_Ss",                  TYP_8,     1);
   SetLockValue("DI_UPS1_Buffering_E",                   TYP_8,     1);
   SetValue("DI_UPS1_Buffering_I",                       TYP_8,     0);
   SetLockValue("DI_UPS1_Buffering_Cm",                  TYP_8,     1);
   SetLockValue("DI_UPS1_Buffering_Ht",                  TYP_32,    100);

   SetLockValue("DI_UPS1_Replace_Battery_Ss",            TYP_8,     1);
   SetLockValue("DI_UPS1_Replace_Battery_E",             TYP_8,     1);
   SetValue("DI_UPS1_Replace_Battery_I",                 TYP_8,     0);
   SetLockValue("DI_UPS1_Replace_Battery_Cm",            TYP_8,     1);
   SetLockValue("DI_UPS1_Replace_Battery_Ht",            TYP_32,    100);
}


STATUS UPS1InitIOAliases()
{
   UPS1IOVars = UPS1IOVars1;
   UPS1IOVarsSize = UPS1IOVars1Size;
   UPS1SetLockValues = &UPS1SetLockValues1;
   return OS_SUCCESS;
}
//-----------------------------------------------------------------------
// AUTOGENERATED END        AUTOGENERATED END        AUTOGENERATED END
//-----------------------------------------------------------------------

#undef AUTOGENERATED_PART
