//*****************************PEPTOOL Header Start******************************
//                                                                               
//                         Copyright © 2015 Mita-Teknik.                         
//This software may only be used with WP4x00 Controllers delivered by Mita-Teknik
//                                                                               
//*******************************************************************************
//                                                                               
// $PEPTOOL version:9.0$                                                         
// $PEPTOOL file version:106$                                                    
//                                                                               
//*******************************************************************************
//                                                                               
// $Date: XXXX/XX/XX XX:XX:XX $                                                  
// $Author: XXXX\XXX $                                                           
// $RCSfile: VibrationMonitoringEmulator.c,v $                                   
// $Revision: X.X $                                                              
//                                                                               
//******************************PEPTOOL Header End*******************************

//***********************************************************************

// OS header files
#include <os_main.h>
// AppLib header files
#include <lib_main.h>
// App header files
#include <turbdef.h>
#include <VarMacros.h>

// Object header file
#include <VibrationMonitoringEmulator.h>

#define AUTOGENERATED_PART
//{
//-----------------------------------------------------------------------
// AUTOGENERATED START     AUTOGENERATED START     AUTOGENERATED START
//-----------------------------------------------------------------------

#define VALIDATE_HASH
char VibrationMonitoringEmulator_copyright[] =
{
   67, 111, 112, 121, 114, 105, 103, 104, 116, 32, 63, 32, 50, 48, 49, 53,
   32, 77, 105, 116, 97, 45, 84, 101, 107, 110, 105, 107, 46, 13, 10, 84,
   104, 105, 115, 32, 115, 111, 102, 116, 119, 97, 114, 101, 32, 109, 97, 121,
   32, 111, 110, 108, 121, 32, 98, 101, 32, 117, 115, 101, 100, 32, 119, 105,
   116, 104, 32, 87, 80, 52, 120, 48, 48, 32, 67, 111, 110, 116, 114, 111,
   108, 108, 101, 114, 115, 32, 100, 101, 108, 105, 118, 101, 114, 101, 100, 32,
   98, 121, 32, 77, 105, 116, 97, 45, 84, 101, 107, 110, 105, 107, 0
};

#define MODULE_NAME "Vibration Monitoring emulatorA"

//-----------------------------------------------------------------------
// ALLOCATE MEMORY FOR STRINGS IN VARDB
//-----------------------------------------------------------------------


//-----------------------------------------------------------------------
// DEFINE LOCAL VARIABLES DEFINE LOCAL VARIABLES DEFINE LOCAL VARIABLES
//-----------------------------------------------------------------------

static struct os_db_local LocalVars[] =
{
   VAR_ELEMENT_LOCAL("V_WP4084No1VibOne",                        TYPE_U16,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    1000,    UNIT_GRAVITY,       3,   0,               U16_MIN,         U16_MAX,         NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_WP4084No1VibTwo",                        TYPE_U16,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    1000,    UNIT_GRAVITY,       3,   0,               U16_MIN,         U16_MAX,         NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_WP4084No2VibOne",                        TYPE_U16,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    1000,    UNIT_GRAVITY,       3,   0,               U16_MIN,         U16_MAX,         NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_WP4084No2VibTwo",                        TYPE_U16,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    1000,    UNIT_GRAVITY,       3,   0,               U16_MIN,         U16_MAX,         NULL,  NOLOG_ENABLE),
};

//-----------------------------------------------------------------------
// DEFINE PARAMETERS        DEFINE PARAMETERS        DEFINE PARAMETERS
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// DEFINE BACKUPS            DEFINE BACKUPS            DEFINE BACKUPS
//-----------------------------------------------------------------------

//----------------------------------------------------------------------------------
// DEFINE VAR ARRAYS            DEFINE VAR ARRAYS            DEFINE VAR ARRAYS
//----------------------------------------------------------------------------------
char VibrationMonitoringEmulator_initialValues[] =
{
   112, 15, 41, 241, 159, 56, 193, 248, 179, 78, 3, 148, 251, 118, 16, 169,
   12, 129, 229, 117, 58, 79, 90, 124, 231, 99, 117, 194, 73, 32, 234, 165,
   0
};

//-----------------------------------------------------------------------
// CREATE DATABASE VARS   CREATE DATABASE VARS   CREATE DATABASE VARS
//-----------------------------------------------------------------------

static STATUS CreateVarDbVars(void)
{
   STATUS Status;
   size_t ErrorEntry;

   Status = OS_VarDB_CreateLocals(LocalVars, sizeof(LocalVars)/sizeof(LocalVars[0]), &ErrorEntry, AppLocalParameterPosition());
   if (Status != 0)
   {
      AppSystemLog(ERR_7, MODULE_NAME"CrVL: %d,%d", Status, ErrorEntry);
      return ERR_7;
   }

   return OS_SUCCESS;
}

#define CREATE_VARDB_VARS

//-----------------------------------------------------------------------
// CREATE IO VARIABLES     CREATE IO VARIABLES     CREATE IO VARIABLES
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// ALIASES                       ALIASES                       ALIASES
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// INPUT                          INPUT                          INPUT
//-----------------------------------------------------------------------

//------------------------------------------------------------------------------------------
// READ/WRITE VARDB ARRAY      READ/WRITE VARDB ARRAY      READ/WRATE VARDB ARRAY
//------------------------------------------------------------------------------------------


//-----------------------------------------------------------------------
// PARAMETER                    PARAMETER                    PARAMETER
//-----------------------------------------------------------------------


//-----------------------------------------------------------------------
// READ VARS FROM VARDB    READ VARS FROM VARDB    READ VARS FROM VARDB
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// OUTPUT                         OUTPUT                         OUTPUT
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// WRITE VARS TO VARDB     WRITE VARS TO VARDB     WRITE VARS TO VARDB
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// VERIFY VARIABLES CREATION                 VERIFY VARIABLES CREATION
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// ALLOCATE MEMORY FOR SUMMATIONS        ALLOCATE MEMORY FOR SUMMATIONS
//-----------------------------------------------------------------------


//-----------------------------------------------------------------------
// SUMMATIONS                  SUMMATIONS                  SUMMATIONS
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// DEFINE MENUS               DEFINE MENUS               DEFINE MENUS
//-----------------------------------------------------------------------



// Menu line and link to local menu
//-----------------------------------------------------------------------
static struct line_struct M_VibrationMonitoringemulatorLinkToLocalMenu[] =
{
   MENU_ELEMENT_LINE_LINK("Vibration Monitoring emulator",     PASSWORD_LEVEL_LICENCE_CUSTOMER,    "M_VibrationMonitoringemulator",    "G_VibrationMonitoringEmulator"),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_VibrationMonitoringemulatorMenu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_VibrationMonitoringemulator",    PASSWORD_LEVEL_LICENCE_CUSTOMER),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_VibrationMonitoringemulatorMenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("VIBRATION MONITORING EMULATOR",     PASSWORD_LEVEL_LICENCE_CUSTOMER,    "M_"APP_ID"AppMain",                "G_"APP_ID"App"),
   MENU_ELEMENT_LINE_VARRW("Sensor 1 channel 1",               PASSWORD_LEVEL_LICENCE_CUSTOMER,    (char*)"V_WP4084No1VibOne",                          LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Sensor 1 channel 2",               PASSWORD_LEVEL_LICENCE_CUSTOMER,    (char*)"V_WP4084No1VibTwo",                          LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Sensor 2 channel 1",               PASSWORD_LEVEL_LICENCE_CUSTOMER,    (char*)"V_WP4084No2VibOne",                          LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Sensor 2 channel 2",               PASSWORD_LEVEL_LICENCE_CUSTOMER,    (char*)"V_WP4084No2VibTwo",                          LINE_FORMAT_NONE),
};
// Creating parameters for multiplexed categories
//-----------------------------------------------------------------------
static struct multiplexed_info_struct M_VibrationMonitoringemulatorMultiplexedCategoriesParameters[] =
{
0};

//-----------------------------------------------------------------------
// CREATE MENUS               CREATE MENUS               CREATE MENUS
//-----------------------------------------------------------------------

// Memory reservation
//-----------------------------------------------------------------------
static struct menu_group_struct ObjGroup[1];

// Creating the menus
//-----------------------------------------------------------------------
STATUS VibrationMonitoringEmulatorMenuAppInit(U8 ModuleState, OS_MEMORY_POOL* pPool)
{
   STATUS Status;

   if (ModuleState == APP_INIT1)
   {
      /* Create application group */
      Status = OS_CreateMenuGroup(ObjGroup, M_VibrationMonitoringemulatorLinkToLocalMenu[0].LinkGroup);
      STATUS_LINE_VAR_RETURN_VALUE(Status);
   }

   Status = CreateAndInitializeMenu(ModuleState,
                                    M_VibrationMonitoringemulatorMenuLines[0].LinkGroup,
                                    M_VibrationMonitoringemulatorMenuLines[0].LinkName,
                                    ELEMENT(M_VibrationMonitoringemulatorLinkToLocalMenu),
                                    M_VibrationMonitoringemulatorLinkToLocalMenu[0].LinkGroup,
                                    ELEMENT(M_VibrationMonitoringemulatorMenu),
                                    M_VibrationMonitoringemulatorLinkToLocalMenu[0].LinkName,
                                    ELEMENT(M_VibrationMonitoringemulatorMenuLines),
                                    pPool,
                                    M_VibrationMonitoringemulatorMultiplexedCategoriesParameters);
   STATUS_LINE_VAR_RETURN_VALUE(Status);

   return OS_SUCCESS;
}

#define CREATE_MENU

//-----------------------------------------------------------------------
//               BUTTONS FUNCTIONS FORWARD DECLARATIONS
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// BUTTONS                       BUTTONS                      BUTTONS
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
//             SET/RESET FUNCTIONS FORWARD DECLARATIONS
//-----------------------------------------------------------------------
//-----------------------------------------------------------------------
// STATUSCODES                 STATUSCODES                 STATUSCODES
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// MODIFIABLE                  MODIFIABLE                   MODIFIABLE
//-----------------------------------------------------------------------

extern const char VibrationMonitoringEmulatorAppGroupName[];
extern const char VibrationMonitoringEmulatorAppMenuName[];

static void Init_Structures_From_Conf_File(void)
{
   M_VibrationMonitoringemulatorMenuLines[0].LinkName = (char*)VibrationMonitoringEmulatorAppMenuName;
   M_VibrationMonitoringemulatorMenuLines[0].LinkGroup = (char*)VibrationMonitoringEmulatorAppGroupName;
}

//-----------------------------------------------------------------------
// AUTOGENERATED END        AUTOGENERATED END        AUTOGENERATED END
//-----------------------------------------------------------------------
//}

#undef AUTOGENERATED_PART

//-----------------------------------------------------------------------
// USER DEFINITIONS         USER DEFINITIONS         USER DEFINITIONS
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// SET/RESET FUNCTIONS    SET/RESET FUNCTIONS    SET/RESET FUNCTIONS
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// DRIVER FUNCTION         DRIVER FUNCTION         DRIVER FUNCTION
//-----------------------------------------------------------------------
  
//-----------------------------------------------------------------------
// INIT                   INIT                     INIT
//-----------------------------------------------------------------------
  
//-----------------------------------------------------------------------
// CONTROL                CONTROL                 CONTROL
//-----------------------------------------------------------------------
  
static STATUS LocalCtrl( U32 Interval )
{
   STATUS LocalStatus = 0;

   return LocalStatus;
}

static STATUS ShutdownCtrl( U8 ModuleState, U8 *DoneState, U32 Interval )
{
    STATUS LocalStatus = 0;

    LocalStatus = LocalCtrl( Interval );
    STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);

    switch( ModuleState )
    {
        case AS_SHUTDOWN:
        {
            // Activate "Manual Shutdown" status code

            *DoneState = AS_SHUTDOWN;
            break;
        }
        case AS_REBOOT:
        {

            *DoneState = AS_REBOOT;
            break;
        }
        case AS_SHUTDOWN_FAST:
        {

            *DoneState = AS_SHUTDOWN_FAST;
            break;
        }
        default:
        {
            *DoneState = ModuleState;
            break;
        }
    }
    return LocalStatus;
}
 
//-----------------------------------------------------------------------
// MAIN CALL             MAIN CALL               MAIN CALL
//-----------------------------------------------------------------------

STATUS VibrationMonitoringEmulator( U8 ModuleState, U8 *DoneState , U32 Interval )
{
   STATUS LocalStatus = 0;

   #ifdef READ_VARS
      // Read input data
      LocalStatus = InputReferenceRoutine(ModuleState);
      STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
   #endif
   #ifdef COMMON_VDB_READ
      LocalStatus = ReadVdbWindow(ModuleState);
      STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
   #endif


   switch( ModuleState )
   {
      //__________________________________________________________________________
      case APP_RUN:
      {
         #ifdef FUNCTION_BLOCKS_PRE_LOCAL_CONTROL
            LocalStatus = FunctionBlocksPreLocalCtrl( Interval );
            STATUS_LINE_VAR_RETURN_VALUE( LocalStatus );
         #endif

         LocalStatus = LocalCtrl( Interval );
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
        
         #ifdef FUNCTION_BLOCKS_POST_LOCAL_CONTROL
            LocalStatus = FunctionBlocksPostLocalCtrl( Interval );
            STATUS_LINE_VAR_RETURN_VALUE( LocalStatus );
         #endif

         #ifdef WRITE_VARS
            // Write Output data
            LocalStatus = OutputReferenceRoutine(ModuleState);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef COMMON_VDB_WRITE
            LocalStatus = WriteVdbWindow(ModuleState);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         *DoneState = APP_RUN;
         break;
      }
      //__________________________________________________________________________
      case APP_INIT1:
      {
         // Version check
         LocalStatus = OS_ValidateAPI( API_VERSION_MAJOR,
                                API_VERSION_MINOR,
                                OS_LinkTime,
                                ReleaseTag,
                                __MODULE__
                               );
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);

         Init_Structures_From_Conf_File();

         #ifdef CREATE_VARDB_VARS
            LocalStatus = CreateVarDbVars();
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef CREATE_MENU
            LocalStatus = VibrationMonitoringEmulatorMenuAppInit(ModuleState, GetMemPool());
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);

            #ifdef MULTIPLEXIBLE_MENU
               LocalStatus = MenuArraysAppInit(ModuleState, GetMemPool());
               STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
            #endif
         #endif

         #ifdef CREATE_VARDB_ARRAY_VARS
               LocalStatus = CreateVdbArrays(GetMemPool());
               STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
         #endif


         #ifdef CREATE_IO_VARS
               LocalStatus = CreateIOVars();
               STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
         #endif

         *DoneState = APP_INIT1;

         break;
      }
      //__________________________________________________________________________
      case APP_INIT2:
      {
         #ifdef CREATE_MENU
            #ifdef MULTIPLEXIBLE_MENU
               LocalStatus = MenuArraysAppInit(ModuleState, GetMemPool());
               STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
            #endif
         #endif

         #ifdef CREATE_ALIASES
               size_t ErrorEntry = 0;
               LocalStatus = OS_VarDB_CreateAliases(AliasVars, sizeof(AliasVars)/sizeof(AliasVars[0]), &ErrorEntry);
               STATUS_LINE_VAR_RETURN_CONST(LocalStatus, ErrorEntry);
         #endif

         #ifdef VERIFY_ARRAY
               LocalStatus = VerifyArray(GetMemPool());
               STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef VERIFY_VARIABLES
               LocalStatus = LocalIoCheck();
               STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef CREATE_BUTTONS
               LocalStatus = CreateButtons();
               STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         *DoneState = APP_INIT2;

         break;
      }
      //__________________________________________________________________________
      case APP_INIT3 :
      {
         #ifdef CREATE_SUMMATIONS
            LocalStatus = CreateSummations();
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef WRITE_VARS
            LocalStatus = InitOutputVars();
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef CREATE_STATUS_CODES
            LocalStatus = LocalStatusCodeInit();
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef CREATE_IO_VARS
           VibrationMonitoringEmulatorSetLockValues();
         #endif

         *DoneState = APP_INIT3;

         break;
      }
      //__________________________________________________________________________
      case APP_INIT4:
      {
         #ifdef CREATE_MENU
            LocalStatus = VibrationMonitoringEmulatorMenuAppInit(ModuleState, GetMemPool());
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);

            #ifdef MULTIPLEXIBLE_MENU
               LocalStatus = MenuArraysAppInit(ModuleState, GetMemPool());
               STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
            #endif
         #endif

         *DoneState = APP_INIT4;

         break;
      }
      //__________________________________________________________________________
      case APP_INIT5:
      {
         #ifdef VALIDATE_HASH
            LocalStatus = ValidateHash( VibrationMonitoringEmulator_copyright, MODULE_NAME, VibrationMonitoringEmulator_initialValues);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef INIT_FUNCTION_BLOCKS
            LocalStatus = FunctionBlocksInit( Interval );
            STATUS_LINE_VAR_RETURN_VALUE( LocalStatus );
         #endif


         *DoneState = APP_INIT5_DONE;

         break;
      }
      //__________________________________________________________________________
      //Other initialization round can be inserted here
      //__________________________________________________________________________
      case AS_SHUTDOWN:
      {
         LocalStatus = ShutdownCtrl ( ModuleState, DoneState, Interval );
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);

         #ifdef WRITE_VARS
            // Write Output data
            LocalStatus = OutputReferenceRoutine(ModuleState);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef COMMON_VDB_WRITE
            LocalStatus = WriteVdbWindow(ModuleState);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         break;
      }
      //__________________________________________________________________________
      case AS_REBOOT:
      {
         LocalStatus = ShutdownCtrl ( ModuleState, DoneState, Interval );
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);

         #ifdef WRITE_VARS
            // Write Output data
            LocalStatus = OutputReferenceRoutine(ModuleState);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef COMMON_VDB_WRITE
            LocalStatus = WriteVdbWindow(ModuleState);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         break;
      }
      //__________________________________________________________________________
      case AS_SHUTDOWN_FAST:
      {
         LocalStatus = ShutdownCtrl ( ModuleState, DoneState, Interval );
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);

         #ifdef WRITE_VARS
            // Write Output data
            LocalStatus = OutputReferenceRoutine(ModuleState);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef COMMON_VDB_WRITE
            LocalStatus = WriteVdbWindow(ModuleState);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         break;
      }
      default:
      {
         *DoneState = ModuleState;

         break;
      }
   }
   return OS_SUCCESS;
}
//-----------------------------------------------------------------------
