//*****************************PEPTOOL Header Start******************************
//                                                                               
//                         Copyright © 2015 Mita-Teknik.                         
//This software may only be used with WP4x00 Controllers delivered by Mita-Teknik
//                                                                               
//*******************************************************************************
//                                                                               
// $PEPTOOL version:9.0$                                                         
// $PEPTOOL file version:101$                                                    
//                                                                               
//*******************************************************************************
//                                                                               
// $Date: XXXX/XX/XX XX:XX:XX $                                                  
// $Author: XXXX\XXX $                                                           
// $RCSfile: WeatherSensor2_Eleon_Type1_Conf.c,v $                               
// $Revision: X.X $                                                              
//                                                                               
//******************************PEPTOOL Header End*******************************

//***********************************************************************
// OS header files
#include <os_main.h>
// App header files
#include <InitIo.h>

#define AUTOGENERATED_PART

#include <Turbdef.h>

//-----------------------------------------------------------------------
// AUTOGENERATED START     AUTOGENERATED START     AUTOGENERATED START
//-----------------------------------------------------------------------
char WeatherSensor2_Conf_copyright[] =
{
   67, 111, 112, 121, 114, 105, 103, 104, 116, 32, 63, 32, 50, 48, 49, 53,
   32, 77, 105, 116, 97, 45, 84, 101, 107, 110, 105, 107, 46, 13, 10, 84,
   104, 105, 115, 32, 115, 111, 102, 116, 119, 97, 114, 101, 32, 109, 97, 121,
   32, 111, 110, 108, 121, 32, 98, 101, 32, 117, 115, 101, 100, 32, 119, 105,
   116, 104, 32, 87, 80, 52, 120, 48, 48, 32, 67, 111, 110, 116, 114, 111,
   108, 108, 101, 114, 115, 32, 100, 101, 108, 105, 118, 101, 114, 101, 100, 32,
   98, 121, 32, 77, 105, 116, 97, 45, 84, 101, 107, 110, 105, 107, 0
};
//-----------------------------------------------------------------------
// MODIFIABLE                  MODIFIABLE               MODIFIABLE
//-----------------------------------------------------------------------
const char WeatherSensor2AppGroupName[] = "G_"APP_ID"App";
const char WeatherSensor2AppMenuName[] = "M_"APP_ID"AppMain";

//-----------------------------------------------------------------------
// IO VARIABLES                IO VARIABLES                IO VARIABLES
//-----------------------------------------------------------------------

void (*WeatherSensor2SetLockValues)(void);
struct os_db_alias *WeatherSensor2IOVars;
size_t WeatherSensor2IOVarsSize = 0;
            
struct os_db_alias WeatherSensor2IOVars1[]=
{
    VAR_ELEMENT_ALIAS("3.3.COM2_Sync",                    "COM_WeatherSensor2_Sync"),

    VAR_ELEMENT_ALIAS("3.3.COM2_TX",                      "COM_WeatherSensor2_TxData"),

    VAR_ELEMENT_ALIAS("3.3.COM2_RX",                      "COM_WeatherSensor2_RxData"),

    VAR_ELEMENT_ALIAS("3.3.COM2_Mode",                    "COM_WeatherSensor2_Mode"),

    VAR_ELEMENT_ALIAS("3.3.COM2_Baud",                    "ComPortConfiguration3Point3PointCOM2BaudRate"),

    VAR_ELEMENT_ALIAS("3.3.COM2_DataBits",                "ComPortConfiguration3Point3PointCOM2DataBits"),

    VAR_ELEMENT_ALIAS("3.3.COM2_StopBits",                "ComPortConfiguration3Point3PointCOM2StopBits"),

    VAR_ELEMENT_ALIAS("3.3.COM2_Parity",                  "ComPortConfiguration3Point3PointCOM2Parity"),

};
size_t WeatherSensor2IOVars1Size = sizeof(WeatherSensor2IOVars1)/sizeof(WeatherSensor2IOVars1[0]);

void WeatherSensor2SetLockValues1(void)
{
   SetValue("COM_WeatherSensor2_Sync",                   TYP_8,     0);

   SetValue("COM_WeatherSensor2_Mode",                   TYP_8,     2);

   SetValue("ComPortConfiguration3Point3PointCOM2BaudRate",TYP_32,    9600);

   SetValue("ComPortConfiguration3Point3PointCOM2DataBits",TYP_8,     8);

   SetValue("ComPortConfiguration3Point3PointCOM2StopBits",TYP_8,     1);

   SetValue("ComPortConfiguration3Point3PointCOM2Parity",TYP_8,     0);
}


STATUS WeatherSensor2InitIOAliases()
{
   WeatherSensor2IOVars = WeatherSensor2IOVars1;
   WeatherSensor2IOVarsSize = WeatherSensor2IOVars1Size;
   WeatherSensor2SetLockValues = &WeatherSensor2SetLockValues1;
   return OS_SUCCESS;
}
//-----------------------------------------------------------------------
// AUTOGENERATED END        AUTOGENERATED END        AUTOGENERATED END
//-----------------------------------------------------------------------

#undef AUTOGENERATED_PART
