//*****************************PEPTOOL Header Start******************************
//                                                                               
//                         Copyright © 2015 Mita-Teknik.                         
//This software may only be used with WP4x00 Controllers delivered by Mita-Teknik
//                                                                               
//*******************************************************************************
//                                                                               
// $PEPTOOL version:9.0$                                                         
// $PEPTOOL file version:106$                                                    
//                                                                               
//*******************************************************************************
//                                                                               
// $Date: XXXX/XX/XX XX:XX:XX $                                                  
// $Author: XXXX\XXX $                                                           
// $RCSfile: WeatherSensor1_Eleon_Type1.c,v $                                    
// $Revision: X.X $                                                              
//                                                                               
//******************************PEPTOOL Header End*******************************

//***********************************************************************

// OS header files
#include <os_main.h>
// AppLib header files
#include <lib_main.h>
// App header files
#include <turbdef.h>
#include <VarMacros.h>

// Object header file
#include <WeatherSensor1.h>

#define AUTOGENERATED_PART
//{
//-----------------------------------------------------------------------
// AUTOGENERATED START     AUTOGENERATED START     AUTOGENERATED START
//-----------------------------------------------------------------------

#define VALIDATE_HASH
char WeatherSensor1_copyright[] =
{
   67, 111, 112, 121, 114, 105, 103, 104, 116, 32, 63, 32, 50, 48, 49, 53,
   32, 77, 105, 116, 97, 45, 84, 101, 107, 110, 105, 107, 46, 13, 10, 84,
   104, 105, 115, 32, 115, 111, 102, 116, 119, 97, 114, 101, 32, 109, 97, 121,
   32, 111, 110, 108, 121, 32, 98, 101, 32, 117, 115, 101, 100, 32, 119, 105,
   116, 104, 32, 87, 80, 52, 120, 48, 48, 32, 67, 111, 110, 116, 114, 111,
   108, 108, 101, 114, 115, 32, 100, 101, 108, 105, 118, 101, 114, 101, 100, 32,
   98, 121, 32, 77, 105, 116, 97, 45, 84, 101, 107, 110, 105, 107, 0
};

#define MODULE_NAME "Weather Sensor 1A"

//-----------------------------------------------------------------------
// ALLOCATE MEMORY FOR STRINGS IN VARDB
//-----------------------------------------------------------------------

static char A_V_WeatherSensor1StatusText[31]  = "12345678901234567890123456789";
static char A_V_WeatherSensor1CRC[3]  = "00";
static char A_V_WeatherSensor1CalcCRC[3]  = "00";
static char A_V_WeatherSensor1StatusByteHex[3]  = "00";

//-----------------------------------------------------------------------
// DEFINE LOCAL VARIABLES DEFINE LOCAL VARIABLES DEFINE LOCAL VARIABLES
//-----------------------------------------------------------------------

static struct os_db_local LocalVars[] =
{
   VAR_ELEMENT_LOCAL("V_WindSpeedSensor1",                       TYPE_U16,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    100,     UNIT_MPS,           1,   0,               0,               9000,            NULL,  TOTLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_WindDirectionSensor1",                   TYPE_U16,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    10,      UNIT_DEGREE,        1,   0,               0,               3600,            NULL,  TOTLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_OutdoorTempSensor1",                     TYPE_S16,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    10,      UNIT_CELSIUS,       1,   0,               -400,            2100,            NULL,  TOTLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_OutdoorTempSensor1Local",                TYPE_S16,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    10,      UNIT_CELSIUS,       1,   0,               -400,            2100,            NULL,  TOTLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_WindSpeedSensor1Status",                 TYPE_U16,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   0,               U16_MIN,         U16_MAX,         NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_WindDirectionSensor1Status",             TYPE_U16,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   0,               U16_MIN,         U16_MAX,         NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_OutdoorTempSensor1Status",               TYPE_U16,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   0,               U16_MIN,         U16_MAX,         NULL,  TOTLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_WeatherSensor1WSDataError",              TYPE_U8,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   0,               0,               1,               NULL,  TOTLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_WeatherSensor1WDDataError",              TYPE_U8,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   0,               0,               1,               NULL,  TOTLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_WeatherSensor1TempDataError",            TYPE_U8,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   0,               0,               1,               NULL,  TOTLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_WeatherSensor1ComError",                 TYPE_U8,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   0,               0,               1,               NULL,  TOTLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_WeatherSensor1StatusText",               TYPE_STRING + sizeof(A_V_WeatherSensor1StatusText) - 1,  PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   A_V_WeatherSensor1StatusText, 0,                0,                NULL,  NOLOG_ENABLE  ),
   VAR_ELEMENT_LOCAL("V_WeatherSensor1IcedOver",                 TYPE_U8,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   0,               0,               1,               NULL,  TOTLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_WeatherSensor1DataReceived",             TYPE_U32,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   0,               0,               U32_MAX,         NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_WeatherSensor1DataTransmitted",          TYPE_U32,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   0,               0,               U32_MAX,         NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_WeatherSensor1GeneralMalfunc",           TYPE_U8,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   0,               0,               1,               NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_WeatherSensor1StaticMalfunc",            TYPE_U8,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   0,               0,               1,               NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_WeatherSensor1SWVer",                    TYPE_U32,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    100,     UNIT_NONE,          2,   0,               0,               99999,           NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_WeatherSensor1HeatingCriterion",         TYPE_U8,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   0,               0,               1,               NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_WeatherSensor1HeatingOn",                TYPE_U8,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   0,               0,               1,               NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_WeatherSensor1CRC",                      TYPE_STRING + sizeof(A_V_WeatherSensor1CRC) - 1,  PASSWORD_LEVEL_LICENCE_PROGRAMMER, PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_HEX,           0,   A_V_WeatherSensor1CRC, 0,                0,                NULL,  NOLOG_ENABLE  ),
   VAR_ELEMENT_LOCAL("V_WeatherSensor1CalcCRC",                  TYPE_STRING + sizeof(A_V_WeatherSensor1CalcCRC) - 1,  PASSWORD_LEVEL_ADMINISTRATOR,      PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_HEX,           0,   A_V_WeatherSensor1CalcCRC, 0,                0,                NULL,  NOLOG_ENABLE  ),
   VAR_ELEMENT_LOCAL("V_WeatherSensor1CRCError",                 TYPE_U32,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   0,               0,               U32_MAX,         NULL,  TOTLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_WeatherSensor1TelegramError",            TYPE_U32,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   0,               0,               U32_MAX,         NULL,  TOTLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_WeatherSensor1WSDeviationTime",          TYPE_U16,     PASSWORD_LEVEL_ADMINISTRATOR,      PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    1000,    UNIT_SECOND,        0,   0,               U16_MIN,         U16_MAX,         NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_WeatherSensor1WSDeviationError",         TYPE_U8,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   0,               0,               1,               NULL,  TOTLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_WeatherSensor1WDDeviationError",         TYPE_U8,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   0,               0,               1,               NULL,  TOTLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_WeatherSensor1TempDeviationError",       TYPE_U8,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   0,               0,               1,               NULL,  TOTLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_WeatherSensor1WDDeviationTime",          TYPE_U16,     PASSWORD_LEVEL_ADMINISTRATOR,      PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    1000,    UNIT_SECOND,        0,   0,               (U8)U8_MIN,      (U8)U8_MAX,      NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_WeatherSensor1TempDeviationTime",        TYPE_U16,     PASSWORD_LEVEL_ADMINISTRATOR,      PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    1000,    UNIT_SECOND,        0,   0,               (U8)U8_MIN,      (U8)U8_MAX,      NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_WeatherSensor1StatusByte",               TYPE_U8,      PASSWORD_LEVEL_ADMINISTRATOR,      PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   0,               U8_MIN,          U8_MAX,          NULL,  TOTLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_WeatherSensor1StatusByteHex",            TYPE_STRING + sizeof(A_V_WeatherSensor1StatusByteHex) - 1,  PASSWORD_LEVEL_ADMINISTRATOR,      PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_HEX,           0,   A_V_WeatherSensor1StatusByteHex, 0,                0,                NULL,  NOLOG_ENABLE  ),
   VAR_ELEMENT_LOCAL("V_WeatherSensor1BusTermination",           TYPE_U8,      PASSWORD_LEVEL_ADMINISTRATOR,      PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   0,               0,               1,               NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_WindSpeedSensor1Local",                  TYPE_U16,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    100,     UNIT_MPS,           1,   0,               0,               9000,            NULL,  TOTLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_WindDirectionSensor1Local",              TYPE_U16,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    10,      UNIT_DEGREE,        1,   0,               0,               3600,            NULL,  NOLOG_ENABLE),
};

//-----------------------------------------------------------------------
// DEFINE PARAMETERS        DEFINE PARAMETERS        DEFINE PARAMETERS
//-----------------------------------------------------------------------

static struct os_db_parameter ParameterVars[] =
{
   VAR_ELEMENT_PARAMETER("P_WeatherSensor1PositionOffset",           TYPE_U16,     PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    10,      UNIT_DEGREE,        1,   0,               0,               3599,            NULL  ),
   VAR_ELEMENT_PARAMETER("P_WeatherSensor1Enable",                   TYPE_U8,      PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   1,               0,               1,               NULL  ),
   VAR_ELEMENT_PARAMETER("P_WeatherSensor1IceWarnTemp",              TYPE_S16,     PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    10,      UNIT_CELSIUS,       1,   40,              0,               50,              NULL  ),
   VAR_ELEMENT_PARAMETER("P_WeatherSensor1WSMaxDeviation",           TYPE_U16,     PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    100,     UNIT_MPS,           1,   500,             0,               1000,            NULL  ),
   VAR_ELEMENT_PARAMETER("P_WeatherSensor1WDMaxDeviation",           TYPE_U16,     PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    10,      UNIT_DEGREE,        1,   100,             0,               150,             NULL  ),
   VAR_ELEMENT_PARAMETER("P_WeatherSensor1TempMaxDeviation",         TYPE_S16,     PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    10,      UNIT_CELSIUS,       1,   100,             0,               200,             NULL  ),
   VAR_ELEMENT_PARAMETER("P_WeatherSensor1DeviationDelay",           TYPE_U32,     PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    1000,    UNIT_SECOND,        0,   30000,           0,               60000,           NULL  ),
   VAR_ELEMENT_PARAMETER("P_WeatherSensor1CommTransmitInterval",     TYPE_U32,     PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    1000,    UNIT_SECOND,        1,   100,             40,              2000,            NULL  ),
   VAR_ELEMENT_PARAMETER("P_WeatherSensor1WDDeviationWS",            TYPE_U16,     PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    100,     UNIT_MPS,           1,   200,             50,              500,             NULL  ),
};

//-----------------------------------------------------------------------
// DEFINE BACKUPS            DEFINE BACKUPS            DEFINE BACKUPS
//-----------------------------------------------------------------------

//----------------------------------------------------------------------------------
// DEFINE VAR ARRAYS            DEFINE VAR ARRAYS            DEFINE VAR ARRAYS
//----------------------------------------------------------------------------------
char WeatherSensor1_initialValues[] =
{
   200, 116, 12, 202, 93, 235, 15, 110, 46, 250, 40, 63, 138, 178, 134, 38,
   238, 113, 154, 253, 72, 139, 87, 161, 155, 218, 105, 65, 116, 192, 55, 173,
   0
};

//-----------------------------------------------------------------------
// CREATE DATABASE VARS   CREATE DATABASE VARS   CREATE DATABASE VARS
//-----------------------------------------------------------------------

static STATUS CreateVarDbVars(void)
{
   STATUS Status;
   size_t ErrorEntry;

   Status = OS_VarDB_CreateLocals(LocalVars, sizeof(LocalVars)/sizeof(LocalVars[0]), &ErrorEntry, AppLocalParameterPosition());
   if (Status != 0)
   {
      AppSystemLog(ERR_7, MODULE_NAME"CrVL: %d,%d", Status, ErrorEntry);
      return ERR_7;
   }

   Status = OS_VarDB_CreateParameters(ParameterVars, sizeof(ParameterVars)/sizeof(ParameterVars[0]), &ErrorEntry, AppExportParameterPosition());
   if (Status != 0)
   {
      AppSystemLog(ERR_7, MODULE_NAME"CrVXP: %d,%d", Status, ErrorEntry);
      return ERR_7;
   }

   return OS_SUCCESS;
}

#define CREATE_VARDB_VARS

//-----------------------------------------------------------------------
// CREATE IO VARIABLES     CREATE IO VARIABLES     CREATE IO VARIABLES
//-----------------------------------------------------------------------

extern STATUS WeatherSensor1InitIOAliases();
extern struct os_db_alias* WeatherSensor1IOVars;
extern void (*WeatherSensor1SetLockValues)(void);
extern size_t WeatherSensor1IOVarsSize;

static STATUS CreateIOVars(void)
{
   STATUS Status;
   size_t ErrorEntry;

   varid_t VarId;
   BOOL variablesExist = false;
   U8 counter = 50;
   Status = WeatherSensor1InitIOAliases();
   STATUS_LINE_VAR_RETURN_VALUE(Status)
   while (!variablesExist && counter-- > 0)
   {
      variablesExist = true;
      U32 i = 0;
      for (i = 0; i < WeatherSensor1IOVarsSize; ++i)
      {
         if (OS_VarDB_GetVariableID(WeatherSensor1IOVars[i].Name, &VarId) != OS_SUCCESS)
         {
            variablesExist = false;
            break;
         }
      }

      if (!variablesExist)
      {
         OS_Sleep(100);
      }
   }

   Status = OS_VarDB_CreateAliases(WeatherSensor1IOVars, WeatherSensor1IOVarsSize, &ErrorEntry);
   if (Status)
   {
      AppDebugLog(5000, "Var Name = %s", WeatherSensor1IOVars[ErrorEntry].Alias);
   }
   STATUS_LINE_VAR_RETURN_CONST(Status, ErrorEntry);
   return OS_SUCCESS;
}

#define CREATE_IO_VARS

//-----------------------------------------------------------------------
// ALIASES                       ALIASES                       ALIASES
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// INPUT                          INPUT                          INPUT
//-----------------------------------------------------------------------

// Create local variable
#define MODUL_INPUTS
static U16 P_WeatherSensor1PositionOffset = 0;
static U8 P_WeatherSensor1Enable = 0;
static S16 P_WeatherSensor1IceWarnTemp = 0;
static U16 P_WeatherSensor1WSMaxDeviation = 0;
static S16 P_WeatherSensor1TempMaxDeviation = 0;
static S16 V_WindDirectionRef = 0;
static S16 V_OutdoorTemperatureRef = 0;
static U32 P_WeatherSensor1CommTransmitInterval = 0;
static U16 P_WeatherSensor1WDMaxDeviation = 0;
static U32 P_WeatherSensor1DeviationDelay = 0;
static U16 P_WeatherSensor1WDDeviationWS = 0;
static U16 V_WindSpeedRef = 0;

//-----------------------------------------------------------------------
static struct ModulInOut ModulInputs[] =
{
   {"P_WeatherSensor1PositionOffset",           &P_WeatherSensor1PositionOffset,           sizeof(P_WeatherSensor1PositionOffset),           },
   {"P_WeatherSensor1Enable",                   &P_WeatherSensor1Enable,                   sizeof(P_WeatherSensor1Enable),                   },
   {"P_WeatherSensor1IceWarnTemp",              &P_WeatherSensor1IceWarnTemp,              sizeof(P_WeatherSensor1IceWarnTemp),              },
   {"P_WeatherSensor1WSMaxDeviation",           &P_WeatherSensor1WSMaxDeviation,           sizeof(P_WeatherSensor1WSMaxDeviation),           },
   {"P_WeatherSensor1TempMaxDeviation",         &P_WeatherSensor1TempMaxDeviation,         sizeof(P_WeatherSensor1TempMaxDeviation),         },
   {"V_WindDirectionRef",                       &V_WindDirectionRef,                       sizeof(V_WindDirectionRef),                       },
   {"V_OutdoorTemperatureRef",                  &V_OutdoorTemperatureRef,                  sizeof(V_OutdoorTemperatureRef),                  },
   {"P_WeatherSensor1CommTransmitInterval",     &P_WeatherSensor1CommTransmitInterval,     sizeof(P_WeatherSensor1CommTransmitInterval),     },
   {"P_WeatherSensor1WDMaxDeviation",           &P_WeatherSensor1WDMaxDeviation,           sizeof(P_WeatherSensor1WDMaxDeviation),           },
   {"P_WeatherSensor1DeviationDelay",           &P_WeatherSensor1DeviationDelay,           sizeof(P_WeatherSensor1DeviationDelay),           },
   {"P_WeatherSensor1WDDeviationWS",            &P_WeatherSensor1WDDeviationWS,            sizeof(P_WeatherSensor1WDDeviationWS),            },
   {"V_WindSpeedRef",                           &V_WindSpeedRef,                           sizeof(V_WindSpeedRef),                           },
};

//-----------------------------------------------------------------------
// Check variable type
static STATUS VarsReadReturnStatus;
static type_t ReadVarType = TYPE_NONE;
static void VarsReadTypeCheck(void)
{
   (void)VarsReadReturnStatus;
   (void)ReadVarType;
   VERIFY_INPUT_REF_ID(U16,       ModulInputs[0].Name,                      ModulInputs[0].Id)
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[1].Name,                      ModulInputs[1].Id)
   VERIFY_INPUT_REF_ID(S16,       ModulInputs[2].Name,                      ModulInputs[2].Id)
   VERIFY_INPUT_REF_ID(U16,       ModulInputs[3].Name,                      ModulInputs[3].Id)
   VERIFY_INPUT_REF_ID(S16,       ModulInputs[4].Name,                      ModulInputs[4].Id)
   VERIFY_INPUT_REF_ID(S16,       ModulInputs[5].Name,                      ModulInputs[5].Id)
   VERIFY_INPUT_REF_ID(S16,       ModulInputs[6].Name,                      ModulInputs[6].Id)
   VERIFY_INPUT_REF_ID(U32,       ModulInputs[7].Name,                      ModulInputs[7].Id)
   VERIFY_INPUT_REF_ID(U16,       ModulInputs[8].Name,                      ModulInputs[8].Id)
   VERIFY_INPUT_REF_ID(U32,       ModulInputs[9].Name,                      ModulInputs[9].Id)
   VERIFY_INPUT_REF_ID(U16,       ModulInputs[10].Name,                     ModulInputs[10].Id)
   VERIFY_INPUT_REF_ID(U16,       ModulInputs[11].Name,                     ModulInputs[11].Id)
}

#undef MODUL_INPUTS
#define MODUL_INPUTS_SIZE (sizeof(ModulInputs)/sizeof(ModulInputs[0]))

//------------------------------------------------------------------------------------------
// READ/WRITE VARDB ARRAY      READ/WRITE VARDB ARRAY      READ/WRATE VARDB ARRAY
//------------------------------------------------------------------------------------------


//-----------------------------------------------------------------------
// PARAMETER                    PARAMETER                    PARAMETER
//-----------------------------------------------------------------------


//-----------------------------------------------------------------------
// READ VARS FROM VARDB    READ VARS FROM VARDB    READ VARS FROM VARDB
//-----------------------------------------------------------------------

static STATUS InputReferenceRoutine(U8 ModuleState)
{
   STATUS LocalStatus = 0;

   // Read input references
   if (ModuleState >= APP_INIT3)
   {
      // Check inputdata
      if (sizeof(ModulInputs) == 0)
      {
         AppSystemLog(ERR_4, MODULE_NAME"ModuleInputs = 0");
         return ERR_4;
      }
      // Read inputdata
      LocalStatus = OS_ReadVariables(ModulInputs, MODUL_INPUTS_SIZE);
      if (LocalStatus != 0)
      {
         AppSystemLog(ERR_4, MODULE_NAME"ReadVErr: element=%d elementpointer=0x%x", LocalStatus, &ModulInputs[LocalStatus]);
         return ERR_4;
      }
   }
   return 0;
}

#define READ_VARS

//-----------------------------------------------------------------------
// OUTPUT                         OUTPUT                         OUTPUT
//-----------------------------------------------------------------------

// Create local variable
#define MODUL_OUTPUTS
static U16 V_WindSpeedSensor1 = 0;
static U16 V_WindDirectionSensor1 = 0;
static S16 V_OutdoorTempSensor1 = 0;
static U16 V_WindSpeedSensor1Status = 0;
static U16 V_WindDirectionSensor1Status = 0;
static U16 V_OutdoorTempSensor1Status = 0;
static U32 V_WeatherSensor1DataReceived = 0;
static U32 V_WeatherSensor1DataTransmitted = 0;
static U8 V_WeatherSensor1ComError = 0;
static U8 V_WeatherSensor1TempDataError = 0;
static U8 V_WeatherSensor1WSDataError = 0;
static U8 V_WeatherSensor1WDDataError = 0;
static U8 V_WeatherSensor1GeneralMalfunc = 0;
static U8 V_WeatherSensor1StaticMalfunc = 0;
static U8 V_WeatherSensor1IcedOver = 0;
static U32 V_WeatherSensor1SWVer = 0;
static U8 V_WeatherSensor1HeatingOn = 0;
static U8 V_WeatherSensor1HeatingCriterion = 0;
static U32 V_WeatherSensor1CRCError = 0;
static U32 V_WeatherSensor1TelegramError = 0;
static U16 V_WeatherSensor1WSDeviationTime = 0;
static U8 V_WeatherSensor1WSDeviationError = 0;
static U8 V_WeatherSensor1WDDeviationError = 0;
static U8 V_WeatherSensor1TempDeviationError = 0;
static U16 V_WeatherSensor1WDDeviationTime = 0;
static U16 V_WeatherSensor1TempDeviationTime = 0;
static U8 V_WeatherSensor1StatusByte = 0;
static U8 V_WeatherSensor1BusTermination = 0;
static U16 V_WindSpeedSensor1Local = 0;
static U16 V_WindDirectionSensor1Local = 0;
static S16 V_OutdoorTempSensor1Local = 0;
static char V_WeatherSensor1StatusText[31];
static char V_WeatherSensor1CRC[3];
static char V_WeatherSensor1CalcCRC[3];
static char V_WeatherSensor1StatusByteHex[3];


//-----------------------------------------------------------------------
static struct ModulInOut ModulOutputs[] =
{
   {"V_WindSpeedSensor1",                       &V_WindSpeedSensor1,                       sizeof(V_WindSpeedSensor1),                       },
   {"V_WindDirectionSensor1",                   &V_WindDirectionSensor1,                   sizeof(V_WindDirectionSensor1),                   },
   {"V_OutdoorTempSensor1",                     &V_OutdoorTempSensor1,                     sizeof(V_OutdoorTempSensor1),                     },
   {"V_WindSpeedSensor1Status",                 &V_WindSpeedSensor1Status,                 sizeof(V_WindSpeedSensor1Status),                 },
   {"V_WindDirectionSensor1Status",             &V_WindDirectionSensor1Status,             sizeof(V_WindDirectionSensor1Status),             },
   {"V_OutdoorTempSensor1Status",               &V_OutdoorTempSensor1Status,               sizeof(V_OutdoorTempSensor1Status),               },
   {"V_WeatherSensor1DataReceived",             &V_WeatherSensor1DataReceived,             sizeof(V_WeatherSensor1DataReceived),             },
   {"V_WeatherSensor1DataTransmitted",          &V_WeatherSensor1DataTransmitted,          sizeof(V_WeatherSensor1DataTransmitted),          },
   {"V_WeatherSensor1ComError",                 &V_WeatherSensor1ComError,                 sizeof(V_WeatherSensor1ComError),                 },
   {"V_WeatherSensor1TempDataError",            &V_WeatherSensor1TempDataError,            sizeof(V_WeatherSensor1TempDataError),            },
   {"V_WeatherSensor1WSDataError",              &V_WeatherSensor1WSDataError,              sizeof(V_WeatherSensor1WSDataError),              },
   {"V_WeatherSensor1WDDataError",              &V_WeatherSensor1WDDataError,              sizeof(V_WeatherSensor1WDDataError),              },
   {"V_WeatherSensor1GeneralMalfunc",           &V_WeatherSensor1GeneralMalfunc,           sizeof(V_WeatherSensor1GeneralMalfunc),           },
   {"V_WeatherSensor1StaticMalfunc",            &V_WeatherSensor1StaticMalfunc,            sizeof(V_WeatherSensor1StaticMalfunc),            },
   {"V_WeatherSensor1IcedOver",                 &V_WeatherSensor1IcedOver,                 sizeof(V_WeatherSensor1IcedOver),                 },
   {"V_WeatherSensor1SWVer",                    &V_WeatherSensor1SWVer,                    sizeof(V_WeatherSensor1SWVer),                    },
   {"V_WeatherSensor1StatusText",               &V_WeatherSensor1StatusText,               sizeof(V_WeatherSensor1StatusText),               },
   {"V_WeatherSensor1HeatingOn",                &V_WeatherSensor1HeatingOn,                sizeof(V_WeatherSensor1HeatingOn),                },
   {"V_WeatherSensor1HeatingCriterion",         &V_WeatherSensor1HeatingCriterion,         sizeof(V_WeatherSensor1HeatingCriterion),         },
   {"V_WeatherSensor1CRC",                      &V_WeatherSensor1CRC,                      sizeof(V_WeatherSensor1CRC),                      },
   {"V_WeatherSensor1CalcCRC",                  &V_WeatherSensor1CalcCRC,                  sizeof(V_WeatherSensor1CalcCRC),                  },
   {"V_WeatherSensor1CRCError",                 &V_WeatherSensor1CRCError,                 sizeof(V_WeatherSensor1CRCError),                 },
   {"V_WeatherSensor1TelegramError",            &V_WeatherSensor1TelegramError,            sizeof(V_WeatherSensor1TelegramError),            },
   {"V_WeatherSensor1WSDeviationTime",          &V_WeatherSensor1WSDeviationTime,          sizeof(V_WeatherSensor1WSDeviationTime),          },
   {"V_WeatherSensor1WSDeviationError",         &V_WeatherSensor1WSDeviationError,         sizeof(V_WeatherSensor1WSDeviationError),         },
   {"V_WeatherSensor1WDDeviationError",         &V_WeatherSensor1WDDeviationError,         sizeof(V_WeatherSensor1WDDeviationError),         },
   {"V_WeatherSensor1TempDeviationError",       &V_WeatherSensor1TempDeviationError,       sizeof(V_WeatherSensor1TempDeviationError),       },
   {"V_WeatherSensor1WDDeviationTime",          &V_WeatherSensor1WDDeviationTime,          sizeof(V_WeatherSensor1WDDeviationTime),          },
   {"V_WeatherSensor1TempDeviationTime",        &V_WeatherSensor1TempDeviationTime,        sizeof(V_WeatherSensor1TempDeviationTime),        },
   {"V_WeatherSensor1StatusByte",               &V_WeatherSensor1StatusByte,               sizeof(V_WeatherSensor1StatusByte),               },
   {"V_WeatherSensor1StatusByteHex",            &V_WeatherSensor1StatusByteHex,            sizeof(V_WeatherSensor1StatusByteHex),            },
   {"V_WeatherSensor1BusTermination",           &V_WeatherSensor1BusTermination,           sizeof(V_WeatherSensor1BusTermination),           },
   {"V_WindSpeedSensor1Local",                  &V_WindSpeedSensor1Local,                  sizeof(V_WindSpeedSensor1Local),                  },
   {"V_WindDirectionSensor1Local",              &V_WindDirectionSensor1Local,              sizeof(V_WindDirectionSensor1Local),              },
   {"V_OutdoorTempSensor1Local",                &V_OutdoorTempSensor1Local,                sizeof(V_OutdoorTempSensor1Local),                },
};

//-----------------------------------------------------------------------
// Check variable type
static STATUS VarsWriteReturnStatus;
static type_t WriteVarType = TYPE_NONE;
static void VarsWriteTypeCheck(void)
{
   (void)VarsWriteReturnStatus;
   (void)WriteVarType;
   VERIFY_OUTPUT_REF_ID(U16,       ModulOutputs[0].Name,                     ModulOutputs[0].Id,                       0)
   VERIFY_OUTPUT_REF_ID(U16,       ModulOutputs[1].Name,                     ModulOutputs[1].Id,                       0)
   VERIFY_OUTPUT_REF_ID(S16,       ModulOutputs[2].Name,                     ModulOutputs[2].Id,                       0)
   VERIFY_OUTPUT_REF_ID(U16,       ModulOutputs[3].Name,                     ModulOutputs[3].Id,                       0)
   VERIFY_OUTPUT_REF_ID(U16,       ModulOutputs[4].Name,                     ModulOutputs[4].Id,                       0)
   VERIFY_OUTPUT_REF_ID(U16,       ModulOutputs[5].Name,                     ModulOutputs[5].Id,                       0)
   VERIFY_OUTPUT_REF_ID(U32,       ModulOutputs[6].Name,                     ModulOutputs[6].Id,                       0)
   VERIFY_OUTPUT_REF_ID(U32,       ModulOutputs[7].Name,                     ModulOutputs[7].Id,                       0)
   VERIFY_OUTPUT_REF_ID(U8,        ModulOutputs[8].Name,                     ModulOutputs[8].Id,                       0)
   VERIFY_OUTPUT_REF_ID(U8,        ModulOutputs[9].Name,                     ModulOutputs[9].Id,                       0)
   VERIFY_OUTPUT_REF_ID(U8,        ModulOutputs[10].Name,                    ModulOutputs[10].Id,                      0)
   VERIFY_OUTPUT_REF_ID(U8,        ModulOutputs[11].Name,                    ModulOutputs[11].Id,                      0)
   VERIFY_OUTPUT_REF_ID(U8,        ModulOutputs[12].Name,                    ModulOutputs[12].Id,                      0)
   VERIFY_OUTPUT_REF_ID(U8,        ModulOutputs[13].Name,                    ModulOutputs[13].Id,                      0)
   VERIFY_OUTPUT_REF_ID(U8,        ModulOutputs[14].Name,                    ModulOutputs[14].Id,                      0)
   VERIFY_OUTPUT_REF_ID(U32,       ModulOutputs[15].Name,                    ModulOutputs[15].Id,                      0)
   VERIFY_OUTPUT_STRING_REF_ID(STRING,     ModulOutputs[16].Name,                     ModulOutputs[16].Id, 0)
   VERIFY_OUTPUT_REF_ID(U8,        ModulOutputs[17].Name,                    ModulOutputs[17].Id,                      0)
   VERIFY_OUTPUT_REF_ID(U8,        ModulOutputs[18].Name,                    ModulOutputs[18].Id,                      0)
   VERIFY_OUTPUT_STRING_REF_ID(STRING,     ModulOutputs[19].Name,                     ModulOutputs[19].Id,                            0)
   VERIFY_OUTPUT_STRING_REF_ID(STRING,     ModulOutputs[20].Name,                     ModulOutputs[20].Id,                            0)
   VERIFY_OUTPUT_REF_ID(U32,       ModulOutputs[21].Name,                    ModulOutputs[21].Id,                      0)
   VERIFY_OUTPUT_REF_ID(U32,       ModulOutputs[22].Name,                    ModulOutputs[22].Id,                      0)
   VERIFY_OUTPUT_REF_ID(U16,       ModulOutputs[23].Name,                    ModulOutputs[23].Id,                      0)
   VERIFY_OUTPUT_REF_ID(U8,        ModulOutputs[24].Name,                    ModulOutputs[24].Id,                      0)
   VERIFY_OUTPUT_REF_ID(U8,        ModulOutputs[25].Name,                    ModulOutputs[25].Id,                      0)
   VERIFY_OUTPUT_REF_ID(U8,        ModulOutputs[26].Name,                    ModulOutputs[26].Id,                      0)
   VERIFY_OUTPUT_REF_ID(U16,       ModulOutputs[27].Name,                    ModulOutputs[27].Id,                      0)
   VERIFY_OUTPUT_REF_ID(U16,       ModulOutputs[28].Name,                    ModulOutputs[28].Id,                      0)
   VERIFY_OUTPUT_REF_ID(U8,        ModulOutputs[29].Name,                    ModulOutputs[29].Id,                      0)
   VERIFY_OUTPUT_STRING_REF_ID(STRING,     ModulOutputs[30].Name,                     ModulOutputs[30].Id,                            0)
   VERIFY_OUTPUT_REF_ID(U8,        ModulOutputs[31].Name,                    ModulOutputs[31].Id,                      0)
   VERIFY_OUTPUT_REF_ID(U16,       ModulOutputs[32].Name,                    ModulOutputs[32].Id,                      0)
   VERIFY_OUTPUT_REF_ID(U16,       ModulOutputs[33].Name,                    ModulOutputs[33].Id,                      0)
   VERIFY_OUTPUT_REF_ID(S16,       ModulOutputs[34].Name,                    ModulOutputs[34].Id,                      0)
}

#undef MODUL_OUTPUTS
#define MODUL_OUTPUTS_SIZE (sizeof(ModulOutputs)/sizeof(ModulOutputs[0]))

//-----------------------------------------------------------------------
// WRITE VARS TO VARDB     WRITE VARS TO VARDB     WRITE VARS TO VARDB
//-----------------------------------------------------------------------

static STATUS InitOutputVars(void)
{
   STATUS LocalStatus;
   // Read outputdata
   LocalStatus = OS_ReadVariables(ModulOutputs, MODUL_OUTPUTS_SIZE);
   if (LocalStatus != 0)
   {
      AppSystemLog(ERR_4, MODULE_NAME"InitErr: element=%d elementpointer=0x%x", LocalStatus, &ModulOutputs[LocalStatus]);
      return ERR_4;
   }
   return OS_SUCCESS;
}
static STATUS OutputReferenceRoutine(U8 ModuleState)
{
   STATUS LocalStatus = 0;
   // Write Outputdata
   LocalStatus = OS_WriteVariablesConditional(ModulOutputs, MODUL_OUTPUTS_SIZE);
   if (LocalStatus != 0)
   {
      AppSystemLog(ERR_5, MODULE_NAME"WriteVErr: element=%d elementpointer=0x%x", LocalStatus, &ModulOutputs[LocalStatus]);
      return ERR_5;
   }
   return 0;
}

#define WRITE_VARS

//-----------------------------------------------------------------------
// VERIFY VARIABLES CREATION                 VERIFY VARIABLES CREATION
//-----------------------------------------------------------------------

static STATUS LocalIoCheck(void)
{
   // Check if input variables exist.
   STATUS LocalStatus;

   LocalStatus = OS_DoesVariablesExist(ModulInputs, MODUL_INPUTS_SIZE);
   if (LocalStatus != 0)
   {
      AppSystemLog(ERR_1, MODULE_NAME"InputErr: %d", LocalStatus);
      AppSystemLog(ERR_1, "Name: %s", ModulInputs[LocalStatus-1].Name);
      return ERR_1;
   }
   (void)VarsReadTypeCheck();

   LocalStatus = OS_DoesVariablesExist(ModulOutputs, MODUL_OUTPUTS_SIZE);
   if (LocalStatus != 0)
   {
      AppSystemLog(ERR_2, MODULE_NAME"OutputErr: %d", LocalStatus);
      AppSystemLog(ERR_2, "Name: %s", ModulOutputs[LocalStatus-1].Name);
      return ERR_2;
   }
   (void)VarsWriteTypeCheck();

   return OS_SUCCESS;
}

#define VERIFY_VARIABLES

//-----------------------------------------------------------------------
// ALLOCATE MEMORY FOR SUMMATIONS        ALLOCATE MEMORY FOR SUMMATIONS
//-----------------------------------------------------------------------


//-----------------------------------------------------------------------
// SUMMATIONS                  SUMMATIONS                  SUMMATIONS
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// DEFINE MENUS               DEFINE MENUS               DEFINE MENUS
//-----------------------------------------------------------------------



// Menu line and link to local menu
//-----------------------------------------------------------------------
static struct line_struct M_WeatherSensor1LinkToLocalMenu[] =
{
   MENU_ELEMENT_LINE_LINK("Weather Sensor 1",                  PASSWORD_LEVEL_END_CUSTOMER,        "M_WeatherSensor1",                 "G_WeatherSensor1_Eleon_Type1"),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_WeatherSensor1Menu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_WeatherSensor1",                 PASSWORD_LEVEL_END_CUSTOMER),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_WeatherSensor1MenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("WEATHER SENSOR 1",                  PASSWORD_LEVEL_END_CUSTOMER,        "M_"APP_ID"AppMain",                "G_"APP_ID"App"),
   MENU_ELEMENT_LINE_VARRO("Wind Speed Sensor 1",              PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_WindSpeedSensor1",                         LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Wind Direction Sensor 1",          PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_WindDirectionSensor1",                     LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Outdoor Temp. Sensor 1",           PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_OutdoorTempSensor1",                       LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Sensor Status",                    PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_WeatherSensor1StatusText",                 LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_LINK("Status",                            PASSWORD_LEVEL_END_CUSTOMER,        "M_Status21",                       "G_WeatherSensor1_Eleon_Type1"),
   MENU_ELEMENT_LINE_LINK("Parameter",                         PASSWORD_LEVEL_SERVICE,             "M_Parameter31",                    "G_WeatherSensor1_Eleon_Type1"),
   MENU_ELEMENT_LINE_LINK("Programmer",                        PASSWORD_LEVEL_LICENCE_PROGRAMMER,  "M_Programmer561",                  "G_WeatherSensor1_Eleon_Type1"),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_Status21Menu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_Status21",                       PASSWORD_LEVEL_END_CUSTOMER),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_Status21MenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("STATUS",                            PASSWORD_LEVEL_END_CUSTOMER,        "M_WeatherSensor1",                 "G_WeatherSensor1_Eleon_Type1"),
   MENU_ELEMENT_LINE_VARRO("Wind Speed Sensor 1",              PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_WindSpeedSensor1",                         LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Wind Speed Sensor 1   3 s.",       PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_WindSpeedSensor1Local",                    LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Wind Direction Sensor 1",          PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_WindDirectionSensor1",                     LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Wind Direction Sensor 1   3 s.",   PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_WindDirectionSensor1Local",                LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Outdoor Temp. Sensor 1",           PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_OutdoorTempSensor1",                       LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Outdoor Temp. Sensor 1   3 s.",    PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_OutdoorTempSensor1Local",                  LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Wind Speed Reference",             PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_WindSpeedRef",                             LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Wind Direction Reference",         PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_WindDirectionRef",                         LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Outdoor Temperature Reference",    PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_OutdoorTemperatureRef",                    LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_LINK("Communication Statistics",          PASSWORD_LEVEL_END_CUSTOMER,        "M_CommunicationStatistics371",     "G_WeatherSensor1_Eleon_Type1"),
   
  MENU_ELEMENT_LINE_LINK_VARRO("Sensor Status",                   PASSWORD_LEVEL_END_CUSTOMER,       "M_SensorStatus611",               "G_WeatherSensor1_Eleon_Type1",    (char*)"V_WeatherSensor1StatusText",                LINE_FORMAT_NONE),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_CommunicationStatistics371Menu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_CommunicationStatistics371",     PASSWORD_LEVEL_END_CUSTOMER),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_CommunicationStatistics371MenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("COMMUNICATION STATISTICS",          PASSWORD_LEVEL_END_CUSTOMER,        "M_Status21",                       "G_WeatherSensor1_Eleon_Type1"),
   MENU_ELEMENT_LINE_VARRO("Transmitted Data",                 PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_WeatherSensor1DataTransmitted",            LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Received Data",                    PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_WeatherSensor1DataReceived",               LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Received Data Checksum Errors",    PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_WeatherSensor1CRCError",                   LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Received Data Telegram Errors",    PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_WeatherSensor1TelegramError",              LINE_FORMAT_NONE),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_SensorStatus611Menu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_SensorStatus611",                PASSWORD_LEVEL_END_CUSTOMER),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_SensorStatus611MenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("SENSOR STATUS",                     PASSWORD_LEVEL_END_CUSTOMER,        "M_Status21",                       "G_WeatherSensor1_Eleon_Type1"),
   MENU_ELEMENT_LINE_VARRO("Communication Error",              PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_WeatherSensor1ComError",                   LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Wind Speed Data Error",            PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_WeatherSensor1WSDataError",                LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Wind Speed Deviation Error",       PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_WeatherSensor1WSDeviationError",           LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Wind Direction Data Error",        PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_WeatherSensor1WDDataError",                LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Wind Direction Deviation Error",   PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_WeatherSensor1WDDeviationError",           LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Outdoor Temp. Data Error",         PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_WeatherSensor1TempDataError",              LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Outdoor Temp. Deviation Error",    PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_WeatherSensor1TempDeviationError",         LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Sensor Iced Over",                 PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_WeatherSensor1IcedOver",                   LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Sensor General Malfunction",       PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_WeatherSensor1GeneralMalfunc",             LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Sensor Static Malfunction",        PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_WeatherSensor1StaticMalfunc",              LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Sensor Heating Criterion",         PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_WeatherSensor1HeatingCriterion",           LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Sensor Heating On",                PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_WeatherSensor1HeatingOn",                  LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Sensor Software Version",          PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_WeatherSensor1SWVer",                      LINE_FORMAT_NONE),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_Parameter31Menu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_Parameter31",                    PASSWORD_LEVEL_SERVICE),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_Parameter31MenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("PARAMETER",                         PASSWORD_LEVEL_SERVICE,             "M_WeatherSensor1",                 "G_WeatherSensor1_Eleon_Type1"),
   MENU_ELEMENT_LINE_VARRW("Weather Sensor 1 Enable",          PASSWORD_LEVEL_SERVICE,             (char*)"P_WeatherSensor1Enable",                     LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Sensor Position Offset",           PASSWORD_LEVEL_SERVICE,             (char*)"P_WeatherSensor1PositionOffset",             LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Sensor Ice Warning Temp.",         PASSWORD_LEVEL_SERVICE,             (char*)"P_WeatherSensor1IceWarnTemp",                LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Wind Speed Max. Deviation",        PASSWORD_LEVEL_SERVICE,             (char*)"P_WeatherSensor1WSMaxDeviation",             LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Wind Direction Max. Deviation",    PASSWORD_LEVEL_SERVICE,             (char*)"P_WeatherSensor1WDMaxDeviation",             LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Wind Direction Dev. Min. Wind Speed", PASSWORD_LEVEL_SERVICE,             (char*)"P_WeatherSensor1WDDeviationWS",              LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Outdoor Temp. Max. Deviation",     PASSWORD_LEVEL_SERVICE,             (char*)"P_WeatherSensor1TempMaxDeviation",           LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Max. Deviation Delay",             PASSWORD_LEVEL_SERVICE,             (char*)"P_WeatherSensor1DeviationDelay",             LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Comm. Transmit Interval",          PASSWORD_LEVEL_SERVICE,             (char*)"P_WeatherSensor1CommTransmitInterval",       LINE_FORMAT_NONE),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_Programmer561Menu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_Programmer561",                  PASSWORD_LEVEL_LICENCE_PROGRAMMER),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_Programmer561MenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("PROGRAMMER",                        PASSWORD_LEVEL_LICENCE_PROGRAMMER,  "M_WeatherSensor1",                 "G_WeatherSensor1_Eleon_Type1"),
   MENU_ELEMENT_LINE_VARRO("Status Information Byte",          PASSWORD_LEVEL_LICENCE_PROGRAMMER,  (char*)"V_WeatherSensor1StatusByteHex",              LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("CRC Received",                     PASSWORD_LEVEL_LICENCE_PROGRAMMER,  (char*)"V_WeatherSensor1CRC",                        LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("CRC Calculated",                   PASSWORD_LEVEL_LICENCE_PROGRAMMER,  (char*)"V_WeatherSensor1CalcCRC",                    LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Wind Speed Deviation Timer",       PASSWORD_LEVEL_LICENCE_PROGRAMMER,  (char*)"V_WeatherSensor1WSDeviationTime",            LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Wind Direction Deviation Timer",   PASSWORD_LEVEL_LICENCE_PROGRAMMER,  (char*)"V_WeatherSensor1WDDeviationTime",            LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Outdoor Temperature Deviation Timer", PASSWORD_LEVEL_LICENCE_PROGRAMMER,  (char*)"V_WeatherSensor1TempDeviationTime",          LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Bus Termination Enabled",          PASSWORD_LEVEL_LICENCE_PROGRAMMER,  (char*)"V_WeatherSensor1BusTermination",             LINE_FORMAT_NONE),
};
// Creating parameters for multiplexed categories
//-----------------------------------------------------------------------
static struct multiplexed_info_struct M_WeatherSensor1MultiplexedCategoriesParameters[] =
{
0};

//-----------------------------------------------------------------------
// CREATE MENUS               CREATE MENUS               CREATE MENUS
//-----------------------------------------------------------------------

// Memory reservation
//-----------------------------------------------------------------------
static struct menu_group_struct ObjGroup[1];

// Creating the menus
//-----------------------------------------------------------------------
STATUS WeatherSensor1MenuAppInit(U8 ModuleState, OS_MEMORY_POOL* pPool)
{
   STATUS Status;

   if (ModuleState == APP_INIT1)
   {
      /* Create application group */
      Status = OS_CreateMenuGroup(ObjGroup, M_WeatherSensor1LinkToLocalMenu[0].LinkGroup);
      STATUS_LINE_VAR_RETURN_VALUE(Status);
   }

   Status = CreateAndInitializeMenu(ModuleState,
                                    M_WeatherSensor1MenuLines[0].LinkGroup,
                                    M_WeatherSensor1MenuLines[0].LinkName,
                                    ELEMENT(M_WeatherSensor1LinkToLocalMenu),
                                    M_WeatherSensor1LinkToLocalMenu[0].LinkGroup,
                                    ELEMENT(M_WeatherSensor1Menu),
                                    M_WeatherSensor1LinkToLocalMenu[0].LinkName,
                                    ELEMENT(M_WeatherSensor1MenuLines),
                                    pPool,
                                    M_WeatherSensor1MultiplexedCategoriesParameters);
   STATUS_LINE_VAR_RETURN_VALUE(Status);

   Status = CreateAndInitializeMenu(ModuleState,
                                    M_Status21MenuLines[0].LinkGroup,
                                    M_Status21MenuLines[0].LinkName,
                                    NULL,
                                    0,
                                    M_WeatherSensor1MenuLines[5].LinkGroup,
                                    ELEMENT(M_Status21Menu),
                                    M_WeatherSensor1MenuLines[5].LinkName,
                                    ELEMENT(M_Status21MenuLines),
                                    pPool,
                                    M_WeatherSensor1MultiplexedCategoriesParameters);
   STATUS_LINE_VAR_RETURN_VALUE(Status);

   Status = CreateAndInitializeMenu(ModuleState,
                                    M_CommunicationStatistics371MenuLines[0].LinkGroup,
                                    M_CommunicationStatistics371MenuLines[0].LinkName,
                                    NULL,
                                    0,
                                    M_Status21MenuLines[10].LinkGroup,
                                    ELEMENT(M_CommunicationStatistics371Menu),
                                    M_Status21MenuLines[10].LinkName,
                                    ELEMENT(M_CommunicationStatistics371MenuLines),
                                    pPool,
                                    M_WeatherSensor1MultiplexedCategoriesParameters);
   STATUS_LINE_VAR_RETURN_VALUE(Status);

   Status = CreateAndInitializeMenu(ModuleState,
                                    M_SensorStatus611MenuLines[0].LinkGroup,
                                    M_SensorStatus611MenuLines[0].LinkName,
                                    NULL,
                                    0,
                                    M_Status21MenuLines[11].LinkGroup,
                                    ELEMENT(M_SensorStatus611Menu),
                                    M_Status21MenuLines[11].LinkName,
                                    ELEMENT(M_SensorStatus611MenuLines),
                                    pPool,
                                    M_WeatherSensor1MultiplexedCategoriesParameters);
   STATUS_LINE_VAR_RETURN_VALUE(Status);

   Status = CreateAndInitializeMenu(ModuleState,
                                    M_Parameter31MenuLines[0].LinkGroup,
                                    M_Parameter31MenuLines[0].LinkName,
                                    NULL,
                                    0,
                                    M_WeatherSensor1MenuLines[6].LinkGroup,
                                    ELEMENT(M_Parameter31Menu),
                                    M_WeatherSensor1MenuLines[6].LinkName,
                                    ELEMENT(M_Parameter31MenuLines),
                                    pPool,
                                    M_WeatherSensor1MultiplexedCategoriesParameters);
   STATUS_LINE_VAR_RETURN_VALUE(Status);

   Status = CreateAndInitializeMenu(ModuleState,
                                    M_Programmer561MenuLines[0].LinkGroup,
                                    M_Programmer561MenuLines[0].LinkName,
                                    NULL,
                                    0,
                                    M_WeatherSensor1MenuLines[7].LinkGroup,
                                    ELEMENT(M_Programmer561Menu),
                                    M_WeatherSensor1MenuLines[7].LinkName,
                                    ELEMENT(M_Programmer561MenuLines),
                                    pPool,
                                    M_WeatherSensor1MultiplexedCategoriesParameters);
   STATUS_LINE_VAR_RETURN_VALUE(Status);

   return OS_SUCCESS;
}

#define CREATE_MENU

//-----------------------------------------------------------------------
//               BUTTONS FUNCTIONS FORWARD DECLARATIONS
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// BUTTONS                       BUTTONS                      BUTTONS
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
//             SET/RESET FUNCTIONS FORWARD DECLARATIONS
//-----------------------------------------------------------------------
static U8 StatusSetFunc265(void);
static U8 StatusResetFunc265(void);
static U8 StatusSetFunc266(void);
static U8 StatusResetFunc266(void);
static U8 StatusSetFunc267(void);
static U8 StatusResetFunc267(void);
//-----------------------------------------------------------------------
// STATUSCODES                 STATUSCODES                 STATUSCODES
//-----------------------------------------------------------------------

static struct sts_statuscode_structure StatusCodes[] =
{
   STS_CODE_ELEMENT("Weather #1 Com.!",       20*SEC,    265,       STATUSCODE_UPDATE_TYPE_POLLING,         PASSWORD_LEVEL_SERVICE,            STATUSCODE_TIMER_TYPE_CONSTANT,     STATUSCODE_TIMER_TYPE_CONSTANT,     STATUSCODE_RESET_TYPE_AUTOMATIC,    STATUSCODE_PRIORITY_LOW,       27,   0,    32,   NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         StatusSetFunc265,        StatusResetFunc265,      BRAKE_PROG_0,        BRAKE_PROG_0,        BRAKE_PROG_MAX,      NULL,                PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    YAW_PROG_0,          YAW_PROG_0,          YAW_PROG_240,        NULL,                PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,    0,    255,  NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            1,  PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      20,        20,        1000,      NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         SETDELAY_MIN,   SETDELAY_MAX,   NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         0,         RESETDELAY_MIN, RESETDELAY_MAX, NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         0,         REPEATTIMES_MIN,     REPEATTIMES_MAX,     NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         REPEATPERIOD_MIN,    REPEATPERIOD_MAX,    NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         REPEATCODE_MIN,      REPEATCODE_MAX,      NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         TIMEOUTPERIOD_MIN,   65535,               NULL,      PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         TIMEOUTCODE_MIN,     TIMEOUTCODE_MAX,     NULL,      PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         NULL),
   STS_CODE_ELEMENT("Weather #1!",            20*SEC,    266,       STATUSCODE_UPDATE_TYPE_POLLING,         PASSWORD_LEVEL_SERVICE,            STATUSCODE_TIMER_TYPE_CONSTANT,     STATUSCODE_TIMER_TYPE_CONSTANT,     STATUSCODE_RESET_TYPE_AUTOMATIC,    STATUSCODE_PRIORITY_LOW,       27,   0,    32,   NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         StatusSetFunc266,        StatusResetFunc266,      BRAKE_PROG_0,        BRAKE_PROG_0,        BRAKE_PROG_MAX,      NULL,                PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    YAW_PROG_0,          YAW_PROG_0,          YAW_PROG_240,        NULL,                PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,    0,    255,  NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            1,  PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      20,        20,        1000,      NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         SETDELAY_MIN,   SETDELAY_MAX,   NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         0,         RESETDELAY_MIN, RESETDELAY_MAX, NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         0,         REPEATTIMES_MIN,     REPEATTIMES_MAX,     NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         REPEATPERIOD_MIN,    REPEATPERIOD_MAX,    NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         REPEATCODE_MIN,      REPEATCODE_MAX,      NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         TIMEOUTPERIOD_MIN,   65535,               NULL,      PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         TIMEOUTCODE_MIN,     TIMEOUTCODE_MAX,     NULL,      PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         NULL),
   STS_CODE_ELEMENT("Weather #1 Iced",        20*SEC,    267,       STATUSCODE_UPDATE_TYPE_POLLING,         PASSWORD_LEVEL_SERVICE,            STATUSCODE_TIMER_TYPE_CONSTANT,     STATUSCODE_TIMER_TYPE_CONSTANT,     STATUSCODE_RESET_TYPE_AUTOMATIC,    STATUSCODE_PRIORITY_LOW,       27,   0,    32,   NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         StatusSetFunc267,        StatusResetFunc267,      BRAKE_PROG_0,        BRAKE_PROG_0,        BRAKE_PROG_MAX,      NULL,                PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    YAW_PROG_0,          YAW_PROG_0,          YAW_PROG_240,        NULL,                PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,    0,    255,  NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SERVICE,            1,  PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      20,        20,        1000,      NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    1*MINUTE,  SETDELAY_MIN,   SETDELAY_MAX,   NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         1*MINUTE,  RESETDELAY_MIN, RESETDELAY_MAX, NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         0,         REPEATTIMES_MIN,     REPEATTIMES_MAX,     NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         REPEATPERIOD_MIN,    REPEATPERIOD_MAX,    NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         REPEATCODE_MIN,      REPEATCODE_MAX,      NULL,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         TIMEOUTPERIOD_MIN,   65535,               NULL,      PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         TIMEOUTCODE_MIN,     TIMEOUTCODE_MAX,     NULL,      PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         NULL),
};

static STATUS_CODE_CONTROL_BLOCK StatusCodeControlBlock;

static STATUS LocalStatusCodeInit(void)
{
   STATUS LocalStatus;

   LocalStatus = OS_StatusCodeInit(STATUSCODE_INTERFACE_VERSION,
                                   &StatusCodeControlBlock,
                                   StatusCodes,
                                   sizeof(StatusCodes)/sizeof(StatusCodes[0]),
                                   AppLocalParameterPosition(),
                                   AppBackupPosition());
   STATUS_LINE_VAR_RETURN_CONST(LocalStatus, ERR_3);

   return OS_SUCCESS;
}

#define CREATE_STATUS_CODES

//-----------------------------------------------------------------------
// MODIFIABLE                  MODIFIABLE                   MODIFIABLE
//-----------------------------------------------------------------------

extern const char WeatherSensor1AppGroupName[];
extern const char WeatherSensor1AppMenuName[];

static void Init_Structures_From_Conf_File(void)
{
   M_WeatherSensor1MenuLines[0].LinkName = (char*)WeatherSensor1AppMenuName;
   M_WeatherSensor1MenuLines[0].LinkGroup = (char*)WeatherSensor1AppGroupName;
}

//-----------------------------------------------------------------------
// AUTOGENERATED END        AUTOGENERATED END        AUTOGENERATED END
//-----------------------------------------------------------------------
//}

#undef AUTOGENERATED_PART

//-----------------------------------------------------------------------
// USER DEFINITIONS         USER DEFINITIONS         USER DEFINITIONS
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// SET/RESET FUNCTIONS    SET/RESET FUNCTIONS    SET/RESET FUNCTIONS
//-----------------------------------------------------------------------

static U8 StatusSetFunc265(void)
{
   return 1;
}

static U8 StatusResetFunc265(void)
{
   return !StatusSetFunc265();
}

static U8 StatusSetFunc266(void)
{
   return 1;
}

static U8 StatusResetFunc266(void)
{
   return !StatusSetFunc266();
}

static U8 StatusSetFunc267(void)
{
   return 1;
}

static U8 StatusResetFunc267(void)
{
   return !StatusSetFunc267();
}

//-----------------------------------------------------------------------
// DRIVER FUNCTION         DRIVER FUNCTION         DRIVER FUNCTION
//-----------------------------------------------------------------------
  
//-----------------------------------------------------------------------
// INIT                   INIT                     INIT
//-----------------------------------------------------------------------
  
//-----------------------------------------------------------------------
// CONTROL                CONTROL                 CONTROL
//-----------------------------------------------------------------------
  
static STATUS LocalCtrl( U32 Interval )
{
   STATUS LocalStatus = 0;

   return LocalStatus;
}

static STATUS ShutdownCtrl( U8 ModuleState, U8 *DoneState, U32 Interval )
{
    STATUS LocalStatus = 0;

    LocalStatus = LocalCtrl( Interval );
    STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);

    switch( ModuleState )
    {
        case AS_SHUTDOWN:
        {
            // Activate "Manual Shutdown" status code

            *DoneState = AS_SHUTDOWN;
            break;
        }
        case AS_REBOOT:
        {

            *DoneState = AS_REBOOT;
            break;
        }
        case AS_SHUTDOWN_FAST:
        {

            *DoneState = AS_SHUTDOWN_FAST;
            break;
        }
        default:
        {
            *DoneState = ModuleState;
            break;
        }
    }
    return LocalStatus;
}
 
//-----------------------------------------------------------------------
// MAIN CALL             MAIN CALL               MAIN CALL
//-----------------------------------------------------------------------

STATUS WeatherSensor1( U8 ModuleState, U8 *DoneState , U32 Interval )
{
   STATUS LocalStatus = 0;

   #ifdef READ_VARS
      // Read input data
      LocalStatus = InputReferenceRoutine(ModuleState);
      STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
   #endif
   #ifdef COMMON_VDB_READ
      LocalStatus = ReadVdbWindow(ModuleState);
      STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
   #endif


   switch( ModuleState )
   {
      //__________________________________________________________________________
      case APP_RUN:
      {
         #ifdef FUNCTION_BLOCKS_PRE_LOCAL_CONTROL
            LocalStatus = FunctionBlocksPreLocalCtrl( Interval );
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif
         
         LocalStatus = LocalCtrl( Interval );
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);

         #ifdef FUNCTION_BLOCKS_POST_LOCAL_CONTROL
            LocalStatus = FunctionBlocksPostLocalCtrl( Interval );
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef WRITE_VARS
            // Write Output data
            LocalStatus = OutputReferenceRoutine(ModuleState);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef COMMON_VDB_WRITE
            LocalStatus = WriteVdbWindow(ModuleState);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         *DoneState = APP_RUN;
         break;
      }
      //__________________________________________________________________________
      case APP_INIT1:
      {
         // Version check
         LocalStatus = OS_ValidateAPI( API_VERSION_MAJOR,
                                API_VERSION_MINOR,
                                OS_LinkTime,
                                ReleaseTag,
                                __MODULE__
                               );
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);

         Init_Structures_From_Conf_File();

         #ifdef CREATE_VARDB_VARS
            LocalStatus = CreateVarDbVars();
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef CREATE_MENU
            LocalStatus = WeatherSensor1MenuAppInit(ModuleState, GetMemPool());
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);

            #ifdef MULTIPLEXIBLE_MENU
               LocalStatus = MenuArraysAppInit(ModuleState, GetMemPool());
               STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
            #endif
         #endif

         #ifdef CREATE_VARDB_ARRAY_VARS
               LocalStatus = CreateVdbArrays(GetMemPool());
               STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
         #endif


         #ifdef CREATE_IO_VARS
               LocalStatus = CreateIOVars();
               STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
         #endif

         *DoneState = APP_INIT1;

         break;
      }
      //__________________________________________________________________________
      case APP_INIT2:
      {
         #ifdef CREATE_MENU
            #ifdef MULTIPLEXIBLE_MENU
               LocalStatus = MenuArraysAppInit(ModuleState, GetMemPool());
               STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
            #endif
         #endif

         #ifdef CREATE_ALIASES
               size_t ErrorEntry = 0;
               LocalStatus = OS_VarDB_CreateAliases(AliasVars, sizeof(AliasVars)/sizeof(AliasVars[0]), &ErrorEntry);
               STATUS_LINE_VAR_RETURN_CONST(LocalStatus, ErrorEntry);
         #endif

         #ifdef VERIFY_ARRAY
               LocalStatus = VerifyArray(GetMemPool());
               STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef VERIFY_VARIABLES
               LocalStatus = LocalIoCheck();
               STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef CREATE_BUTTONS
               LocalStatus = CreateButtons();
               STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         *DoneState = APP_INIT2;

         break;
      }
      //__________________________________________________________________________
      case APP_INIT3 :
      {
         #ifdef CREATE_SUMMATIONS
            LocalStatus = CreateSummations();
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef WRITE_VARS
            LocalStatus = InitOutputVars();
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef CREATE_STATUS_CODES
            LocalStatus = LocalStatusCodeInit();
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef CREATE_IO_VARS
           WeatherSensor1SetLockValues();
         #endif

         *DoneState = APP_INIT3;

         break;
      }
      //__________________________________________________________________________
      case APP_INIT4:
      {
         #ifdef CREATE_MENU
            LocalStatus = WeatherSensor1MenuAppInit(ModuleState, GetMemPool());
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);

            #ifdef MULTIPLEXIBLE_MENU
               LocalStatus = MenuArraysAppInit(ModuleState, GetMemPool());
               STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
            #endif
         #endif

         *DoneState = APP_INIT4;

         break;
      }
      //__________________________________________________________________________
      case APP_INIT5:
      {
         #ifdef VALIDATE_HASH
            LocalStatus = ValidateHash( WeatherSensor1_copyright, MODULE_NAME, WeatherSensor1_initialValues);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef INIT_FUNCTION_BLOCKS
            LocalStatus = FunctionBlocksInit( Interval );
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         *DoneState = APP_INIT5_DONE;

         break;
      }
      //__________________________________________________________________________
      //Other initialization round can be inserted here
      //__________________________________________________________________________
      case AS_SHUTDOWN:
      {
         LocalStatus = ShutdownCtrl ( ModuleState, DoneState, Interval );
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);

         #ifdef WRITE_VARS
            // Write Output data
            LocalStatus = OutputReferenceRoutine(ModuleState);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef COMMON_VDB_WRITE
            LocalStatus = WriteVdbWindow(ModuleState);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         break;
      }
      //__________________________________________________________________________
      case AS_REBOOT:
      {
         LocalStatus = ShutdownCtrl ( ModuleState, DoneState, Interval );
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);

         #ifdef WRITE_VARS
            // Write Output data
            LocalStatus = OutputReferenceRoutine(ModuleState);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef COMMON_VDB_WRITE
            LocalStatus = WriteVdbWindow(ModuleState);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         break;
      }
      //__________________________________________________________________________
      case AS_SHUTDOWN_FAST:
      {
         LocalStatus = ShutdownCtrl ( ModuleState, DoneState, Interval );
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);

         #ifdef WRITE_VARS
            // Write Output data
            LocalStatus = OutputReferenceRoutine(ModuleState);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef COMMON_VDB_WRITE
            LocalStatus = WriteVdbWindow(ModuleState);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         break;
      }
      default:
      {
         *DoneState = ModuleState;

         break;
      }
   }
   return OS_SUCCESS;
}
//-----------------------------------------------------------------------
