//*****************************PEPTOOL Header Start******************************
//                                                                               
//                         Copyright © 2015 Mita-Teknik.                         
//This software may only be used with WP4x00 Controllers delivered by Mita-Teknik
//                                                                               
//*******************************************************************************
//                                                                               
// $PEPTOOL version:9.0$                                                         
// $PEPTOOL file version:106$                                                    
//                                                                               
//*******************************************************************************
//                                                                               
// $Date: 2011/02/17 12:05:33 $                                                  
// $Author: MITA\bbj $                                                           
// $RCSfile: WindSpeed.c,v $                                                     
// $Revision: 1.5 $                                                              
//                                                                               
//******************************PEPTOOL Header End*******************************

//***********************************************************************
// OS header files
#include <os_main.h>
// AppLib header files
#include <lib_main.h>
// App header files
#include <turbdef.h>
#include <VarMacros.h>
#include <Rate_Limiter.h>
// Object header file
#include <WindSpeed.h>

#define AUTOGENERATED_PART
//{
//-----------------------------------------------------------------------
// AUTOGENERATED START     AUTOGENERATED START     AUTOGENERATED START
//-----------------------------------------------------------------------

#define VALIDATE_HASH
char WindSpeed_copyright[] =
{
   67, 111, 112, 121, 114, 105, 103, 104, 116, 32, 63, 32, 50, 48, 49, 53,
   32, 77, 105, 116, 97, 45, 84, 101, 107, 110, 105, 107, 46, 13, 10, 84,
   104, 105, 115, 32, 115, 111, 102, 116, 119, 97, 114, 101, 32, 109, 97, 121,
   32, 111, 110, 108, 121, 32, 98, 101, 32, 117, 115, 101, 100, 32, 119, 105,
   116, 104, 32, 87, 80, 52, 120, 48, 48, 32, 67, 111, 110, 116, 114, 111,
   108, 108, 101, 114, 115, 32, 100, 101, 108, 105, 118, 101, 114, 101, 100, 32,
   98, 121, 32, 77, 105, 116, 97, 45, 84, 101, 107, 110, 105, 107, 0
};

#define MODULE_NAME "Wind SpeedA"

//-----------------------------------------------------------------------
// ALLOCATE MEMORY FOR STRINGS IN VARDB
//-----------------------------------------------------------------------

static char A_V_WindSpeedSensorsActive[31]  = "12345678901234567890123456789";
static char A_V_WSSensor1StatusText[31]  = "12345678901234567890123456789";
static char A_V_WSSensor2StatusText[31]  = "12345678901234567890123456789";

//-----------------------------------------------------------------------
// DEFINE LOCAL VARIABLES DEFINE LOCAL VARIABLES DEFINE LOCAL VARIABLES
//-----------------------------------------------------------------------

static struct os_db_local LocalVars[] =
{
   VAR_ELEMENT_LOCAL("V_WindSpeed",                              TYPE_U16,     PASSWORD_LEVEL_ADMINISTRATOR,      PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    100,     UNIT_MPS,           1,   0,               0,               9000,            NULL,  TOTLOG_ENABLE | FIVEMINLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_WindSpeed1Sec",                          TYPE_U16,     PASSWORD_LEVEL_ADMINISTRATOR,      PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    100,     UNIT_MPS,           1,   0,               0,               9000,            NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_WindSpeed3Sec",                          TYPE_U16,     PASSWORD_LEVEL_ADMINISTRATOR,      PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    100,     UNIT_MPS,           1,   0,               0,               9000,            NULL,  TOTLOG_ENABLE | FIVEMINLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_WindSpeed30Sec",                         TYPE_U16,     PASSWORD_LEVEL_ADMINISTRATOR,      PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    100,     UNIT_MPS,           1,   0,               0,               9000,            NULL,  TOTLOG_ENABLE | FIVEMINLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_WindSpeed10Min",                         TYPE_U16,     PASSWORD_LEVEL_ADMINISTRATOR,      PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    100,     UNIT_MPS,           1,   0,               0,               9000,            NULL,  TOTLOG_ENABLE | FIVEMINLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_WindSpeedSensorsActive",                 TYPE_STRING + sizeof(A_V_WindSpeedSensorsActive) - 1,  PASSWORD_LEVEL_ADMINISTRATOR,      PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   A_V_WindSpeedSensorsActive, 0,                0,                NULL,  NOLOG_ENABLE  ),
   VAR_ELEMENT_LOCAL("V_WSSensor1StatusText",                    TYPE_STRING + sizeof(A_V_WSSensor1StatusText) - 1,  PASSWORD_LEVEL_ADMINISTRATOR,      PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   A_V_WSSensor1StatusText, 0,                0,                NULL,  NOLOG_ENABLE  ),
   VAR_ELEMENT_LOCAL("V_WSSensor2StatusText",                    TYPE_STRING + sizeof(A_V_WSSensor2StatusText) - 1,  PASSWORD_LEVEL_ADMINISTRATOR,      PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   A_V_WSSensor2StatusText, 0,                0,                NULL,  NOLOG_ENABLE  ),
   VAR_ELEMENT_LOCAL("V_WindSpeedRef",                           TYPE_U16,     PASSWORD_LEVEL_ADMINISTRATOR,      PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    100,     UNIT_MPS,           1,   0,               0,               9000,            NULL,  TOTLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_WIS_LoadParameters",                     TYPE_U8,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   0,               0,               1,               NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_WIS_WindSpeed_Debug",                    TYPE_U16,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    100,     UNIT_MPS,           1,   0,               U16_MIN,         U16_MAX,         NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_WIS_WindSpeedMax",                       TYPE_U16,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    100,     UNIT_MPS,           1,   0,               U16_MIN,         U16_MAX,         NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_WIS_WindSpeedMin",                       TYPE_U16,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    100,     UNIT_MPS,           1,   0,               U16_MIN,         U16_MAX,         NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_WIS_SpeedVariationPct",                  TYPE_U16,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    10,      UNIT_PCT,           1,   0,               U16_MIN,         U16_MAX,         NULL,  NOLOG_ENABLE),
};

//-----------------------------------------------------------------------
// DEFINE PARAMETERS        DEFINE PARAMETERS        DEFINE PARAMETERS
//-----------------------------------------------------------------------

static struct os_db_parameter ParameterVars[] =
{
   VAR_ELEMENT_PARAMETER("P_WindSpeedMaxON",                         TYPE_U16,     PASSWORD_LEVEL_ADMINISTRATOR,      PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    100,     UNIT_MPS,           1,   2700,            0,               4000,            NULL  ),
   VAR_ELEMENT_PARAMETER("P_WindSpeedMaxOFF",                        TYPE_U16,     PASSWORD_LEVEL_ADMINISTRATOR,      PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    100,     UNIT_MPS,           1,   2500,            0,               4000,            NULL  ),
   VAR_ELEMENT_PARAMETER("P_WindSpeedMaxMaxON",                      TYPE_U16,     PASSWORD_LEVEL_ADMINISTRATOR,      PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    100,     UNIT_MPS,           1,   3500,            0,               4000,            NULL  ),
   VAR_ELEMENT_PARAMETER("P_WindSpeedMaxMaxOFF",                     TYPE_U16,     PASSWORD_LEVEL_ADMINISTRATOR,      PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    100,     UNIT_MPS,           1,   3000,            0,               4000,            NULL  ),
   VAR_ELEMENT_PARAMETER("P_WindSpeedSensorSelect",                  TYPE_U8,      PASSWORD_LEVEL_ADMINISTRATOR,      PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   0,               0,               2,               NULL  ),
   VAR_ELEMENT_PARAMETER("P_WIS_SpeedOffset",                        TYPE_S16,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    100,     UNIT_MPS,           1,   -150,            -500,            500,             NULL  ),
   VAR_ELEMENT_PARAMETER("P_WIS_OffsetPeakSpeed",                    TYPE_U16,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    100,     UNIT_MPS,           1,   1500,            U16_MIN,         5000,            NULL  ),
   VAR_ELEMENT_PARAMETER("P_WIS_OffsetMaxSpeed",                     TYPE_U16,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    100,     UNIT_MPS,           1,   5000,            U16_MIN,         5000,            NULL  ),
   VAR_ELEMENT_PARAMETER("P_WIS_SpeedVariationRateUp",               TYPE_U16,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    10,      UNIT_PCTPSEC,       1,   10,              0,               1000,            NULL  ),
   VAR_ELEMENT_PARAMETER("P_WIS_SpeedVariationRateDown",             TYPE_U16,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    10,      UNIT_PCTPSEC,       1,   10,              0,               1000,            NULL  ),
};

//-----------------------------------------------------------------------
// DEFINE BACKUPS            DEFINE BACKUPS            DEFINE BACKUPS
//-----------------------------------------------------------------------

//----------------------------------------------------------------------------------
// DEFINE VAR ARRAYS            DEFINE VAR ARRAYS            DEFINE VAR ARRAYS
//----------------------------------------------------------------------------------
char WindSpeed_initialValues[] =
{
   129, 19, 71, 118, 78, 91, 241, 32, 51, 159, 248, 18, 140, 24, 41, 94,
   39, 215, 251, 220, 42, 169, 128, 117, 96, 123, 171, 115, 26, 194, 147, 8,
   0
};

//-----------------------------------------------------------------------
// CREATE DATABASE VARS   CREATE DATABASE VARS   CREATE DATABASE VARS
//-----------------------------------------------------------------------

static STATUS CreateVarDbVars(void)
{
   STATUS Status;
   size_t ErrorEntry;

   Status = OS_VarDB_CreateLocals(LocalVars, sizeof(LocalVars)/sizeof(LocalVars[0]), &ErrorEntry, AppLocalParameterPosition());
   if (Status != 0)
   {
      AppSystemLog(ERR_7, MODULE_NAME"CrVL: %d,%d", Status, ErrorEntry);
      return ERR_7;
   }

   Status = OS_VarDB_CreateParameters(ParameterVars, sizeof(ParameterVars)/sizeof(ParameterVars[0]), &ErrorEntry, AppExportParameterPosition());
   if (Status != 0)
   {
      AppSystemLog(ERR_7, MODULE_NAME"CrVXP: %d,%d", Status, ErrorEntry);
      return ERR_7;
   }

   return OS_SUCCESS;
}

#define CREATE_VARDB_VARS

//-----------------------------------------------------------------------
// CREATE IO VARIABLES     CREATE IO VARIABLES     CREATE IO VARIABLES
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// ALIASES                       ALIASES                       ALIASES
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// INPUT                          INPUT                          INPUT
//-----------------------------------------------------------------------

// Create local variable
#define MODUL_INPUTS
static U16 V_WindSpeedSensor1 = 0;
static U16 V_WindSpeedSensor1Status = 0;
static U16 V_WindSpeedSensor2 = 0;
static U16 V_WindSpeedSensor2Status = 0;
static U16 P_WindSpeedMaxON = 0;
static U16 P_WindSpeedMaxOFF = 0;
static U16 P_WindSpeedMaxMaxON = 0;
static U8 P_WindSpeedSensorSelect = 0;
static U16 P_WindSpeedMaxMaxOFF = 0;
static U8 V_WIS_LoadParameters = 0;
static U16 V_WIS_WindSpeed_Debug = 0;

//-----------------------------------------------------------------------
static struct ModulInOut ModulInputs[] =
{
   {"V_WindSpeedSensor1",                       &V_WindSpeedSensor1,                       sizeof(V_WindSpeedSensor1),                       },
   {"V_WindSpeedSensor1Status",                 &V_WindSpeedSensor1Status,                 sizeof(V_WindSpeedSensor1Status),                 },
   {"V_WindSpeedSensor2",                       &V_WindSpeedSensor2,                       sizeof(V_WindSpeedSensor2),                       },
   {"V_WindSpeedSensor2Status",                 &V_WindSpeedSensor2Status,                 sizeof(V_WindSpeedSensor2Status),                 },
   {"P_WindSpeedMaxON",                         &P_WindSpeedMaxON,                         sizeof(P_WindSpeedMaxON),                         },
   {"P_WindSpeedMaxOFF",                        &P_WindSpeedMaxOFF,                        sizeof(P_WindSpeedMaxOFF),                        },
   {"P_WindSpeedMaxMaxON",                      &P_WindSpeedMaxMaxON,                      sizeof(P_WindSpeedMaxMaxON),                      },
   {"P_WindSpeedSensorSelect",                  &P_WindSpeedSensorSelect,                  sizeof(P_WindSpeedSensorSelect),                  },
   {"P_WindSpeedMaxMaxOFF",                     &P_WindSpeedMaxMaxOFF,                     sizeof(P_WindSpeedMaxMaxOFF),                     },
   {"V_WIS_LoadParameters",                     &V_WIS_LoadParameters,                     sizeof(V_WIS_LoadParameters),                     },
   {"V_WIS_WindSpeed_Debug",                    &V_WIS_WindSpeed_Debug,                    sizeof(V_WIS_WindSpeed_Debug),                    },
};

//-----------------------------------------------------------------------
// Check variable type
static STATUS VarsReadReturnStatus;
static type_t ReadVarType = TYPE_NONE;
static void VarsReadTypeCheck(void)
{
   (void)VarsReadReturnStatus;
   (void)ReadVarType;
   VERIFY_INPUT_REF_ID(U16,       ModulInputs[0].Name,                      ModulInputs[0].Id)
   VERIFY_INPUT_REF_ID(U16,       ModulInputs[1].Name,                      ModulInputs[1].Id)
   VERIFY_INPUT_REF_ID(U16,       ModulInputs[2].Name,                      ModulInputs[2].Id)
   VERIFY_INPUT_REF_ID(U16,       ModulInputs[3].Name,                      ModulInputs[3].Id)
   VERIFY_INPUT_REF_ID(U16,       ModulInputs[4].Name,                      ModulInputs[4].Id)
   VERIFY_INPUT_REF_ID(U16,       ModulInputs[5].Name,                      ModulInputs[5].Id)
   VERIFY_INPUT_REF_ID(U16,       ModulInputs[6].Name,                      ModulInputs[6].Id)
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[7].Name,                      ModulInputs[7].Id)
   VERIFY_INPUT_REF_ID(U16,       ModulInputs[8].Name,                      ModulInputs[8].Id)
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[9].Name,                      ModulInputs[9].Id)
   VERIFY_INPUT_REF_ID(U16,       ModulInputs[10].Name,                     ModulInputs[10].Id)
}

#undef MODUL_INPUTS
#define MODUL_INPUTS_SIZE (sizeof(ModulInputs)/sizeof(ModulInputs[0]))

//------------------------------------------------------------------------------------------
// READ/WRITE VARDB ARRAY      READ/WRITE VARDB ARRAY      READ/WRATE VARDB ARRAY
//------------------------------------------------------------------------------------------


//-----------------------------------------------------------------------
// PARAMETER                    PARAMETER                    PARAMETER
//-----------------------------------------------------------------------


//-----------------------------------------------------------------------
// READ VARS FROM VARDB    READ VARS FROM VARDB    READ VARS FROM VARDB
//-----------------------------------------------------------------------

static STATUS InputReferenceRoutine(U8 ModuleState)
{
   STATUS LocalStatus = 0;

   // Read input references
   if (ModuleState >= APP_INIT3)
   {
      // Check inputdata
      if (sizeof(ModulInputs) == 0)
      {
         AppSystemLog(ERR_4, MODULE_NAME"ModuleInputs = 0");
         return ERR_4;
      }
      // Read inputdata
      LocalStatus = OS_ReadVariables(ModulInputs, MODUL_INPUTS_SIZE);
      if (LocalStatus != 0)
      {
         AppSystemLog(ERR_4, MODULE_NAME"ReadVErr: element=%d elementpointer=0x%x", LocalStatus, &ModulInputs[LocalStatus]);
         return ERR_4;
      }
   }
   return 0;
}

#define READ_VARS

//-----------------------------------------------------------------------
// OUTPUT                         OUTPUT                         OUTPUT
//-----------------------------------------------------------------------

// Create local variable
#define MODUL_OUTPUTS
static U16 V_WindSpeed = 0;
static U16 V_WindSpeed1Sec = 0;
static U16 V_WindSpeed3Sec = 0;
static U16 V_WindSpeed30Sec = 0;
static U16 V_WindSpeed10Min = 0;
static U16 V_WindSpeedRef = 0;
static U16 V_WIS_WindSpeedMax = 0;
static U16 V_WIS_WindSpeedMin = 0;
static U16 V_WIS_SpeedVariationPct = 0;
static char V_WindSpeedSensorsActive[31];
static char V_WSSensor1StatusText[31];
static char V_WSSensor2StatusText[31];


//-----------------------------------------------------------------------
static struct ModulInOut ModulOutputs[] =
{
   {"V_WindSpeed",                              &V_WindSpeed,                              sizeof(V_WindSpeed),                              },
   {"V_WindSpeed1Sec",                          &V_WindSpeed1Sec,                          sizeof(V_WindSpeed1Sec),                          },
   {"V_WindSpeed3Sec",                          &V_WindSpeed3Sec,                          sizeof(V_WindSpeed3Sec),                          },
   {"V_WindSpeed30Sec",                         &V_WindSpeed30Sec,                         sizeof(V_WindSpeed30Sec),                         },
   {"V_WindSpeed10Min",                         &V_WindSpeed10Min,                         sizeof(V_WindSpeed10Min),                         },
   {"V_WindSpeedSensorsActive",                 &V_WindSpeedSensorsActive,                 sizeof(V_WindSpeedSensorsActive),                 },
   {"V_WindSpeedRef",                           &V_WindSpeedRef,                           sizeof(V_WindSpeedRef),                           },
   {"V_WSSensor1StatusText",                    &V_WSSensor1StatusText,                    sizeof(V_WSSensor1StatusText),                    },
   {"V_WSSensor2StatusText",                    &V_WSSensor2StatusText,                    sizeof(V_WSSensor2StatusText),                    },
   {"V_WIS_WindSpeedMax",                       &V_WIS_WindSpeedMax,                       sizeof(V_WIS_WindSpeedMax),                       },
   {"V_WIS_WindSpeedMin",                       &V_WIS_WindSpeedMin,                       sizeof(V_WIS_WindSpeedMin),                       },
   {"V_WIS_SpeedVariationPct",                  &V_WIS_SpeedVariationPct,                  sizeof(V_WIS_SpeedVariationPct),                  },
};

//-----------------------------------------------------------------------
// Check variable type
static STATUS VarsWriteReturnStatus;
static type_t WriteVarType = TYPE_NONE;
static void VarsWriteTypeCheck(void)
{
   (void)VarsWriteReturnStatus;
   (void)WriteVarType;
   VERIFY_OUTPUT_REF_ID(U16,       ModulOutputs[0].Name,                     ModulOutputs[0].Id,                       0)
   VERIFY_OUTPUT_REF_ID(U16,       ModulOutputs[1].Name,                     ModulOutputs[1].Id,                       0)
   VERIFY_OUTPUT_REF_ID(U16,       ModulOutputs[2].Name,                     ModulOutputs[2].Id,                       0)
   VERIFY_OUTPUT_REF_ID(U16,       ModulOutputs[3].Name,                     ModulOutputs[3].Id,                       0)
   VERIFY_OUTPUT_REF_ID(U16,       ModulOutputs[4].Name,                     ModulOutputs[4].Id,                       0)
   VERIFY_OUTPUT_STRING_REF_ID(STRING,     ModulOutputs[5].Name,                      ModulOutputs[5].Id, 0)
   VERIFY_OUTPUT_REF_ID(U16,       ModulOutputs[6].Name,                     ModulOutputs[6].Id,                       0)
   VERIFY_OUTPUT_STRING_REF_ID(STRING,     ModulOutputs[7].Name,                      ModulOutputs[7].Id, 0)
   VERIFY_OUTPUT_STRING_REF_ID(STRING,     ModulOutputs[8].Name,                      ModulOutputs[8].Id, 0)
   VERIFY_OUTPUT_REF_ID(U16,       ModulOutputs[9].Name,                     ModulOutputs[9].Id,                       0)
   VERIFY_OUTPUT_REF_ID(U16,       ModulOutputs[10].Name,                    ModulOutputs[10].Id,                      0)
   VERIFY_OUTPUT_REF_ID(U16,       ModulOutputs[11].Name,                    ModulOutputs[11].Id,                      0)
}

#undef MODUL_OUTPUTS
#define MODUL_OUTPUTS_SIZE (sizeof(ModulOutputs)/sizeof(ModulOutputs[0]))

//-----------------------------------------------------------------------
// WRITE VARS TO VARDB     WRITE VARS TO VARDB     WRITE VARS TO VARDB
//-----------------------------------------------------------------------

static STATUS InitOutputVars(void)
{
   STATUS LocalStatus;
   // Read outputdata
   LocalStatus = OS_ReadVariables(ModulOutputs, MODUL_OUTPUTS_SIZE);
   if (LocalStatus != 0)
   {
      AppSystemLog(ERR_4, MODULE_NAME"InitErr: element=%d elementpointer=0x%x", LocalStatus, &ModulOutputs[LocalStatus]);
      return ERR_4;
   }
   return OS_SUCCESS;
}
static STATUS OutputReferenceRoutine(U8 ModuleState)
{
   STATUS LocalStatus = 0;
   // Write Outputdata
   LocalStatus = OS_WriteVariablesConditional(ModulOutputs, MODUL_OUTPUTS_SIZE);
   if (LocalStatus != 0)
   {
      AppSystemLog(ERR_5, MODULE_NAME"WriteVErr: element=%d elementpointer=0x%x", LocalStatus, &ModulOutputs[LocalStatus]);
      return ERR_5;
   }
   return 0;
}

#define WRITE_VARS

//-----------------------------------------------------------------------
// VERIFY VARIABLES CREATION                 VERIFY VARIABLES CREATION
//-----------------------------------------------------------------------

static STATUS LocalIoCheck(void)
{
   // Check if input variables exist.
   STATUS LocalStatus;

   LocalStatus = OS_DoesVariablesExist(ModulInputs, MODUL_INPUTS_SIZE);
   if (LocalStatus != 0)
   {
      AppSystemLog(ERR_1, MODULE_NAME"InputErr: %d", LocalStatus);
      AppSystemLog(ERR_1, "Name: %s", ModulInputs[LocalStatus-1].Name);
      return ERR_1;
   }
   (void)VarsReadTypeCheck();

   LocalStatus = OS_DoesVariablesExist(ModulOutputs, MODUL_OUTPUTS_SIZE);
   if (LocalStatus != 0)
   {
      AppSystemLog(ERR_2, MODULE_NAME"OutputErr: %d", LocalStatus);
      AppSystemLog(ERR_2, "Name: %s", ModulOutputs[LocalStatus-1].Name);
      return ERR_2;
   }
   (void)VarsWriteTypeCheck();

   return OS_SUCCESS;
}

#define VERIFY_VARIABLES

//-----------------------------------------------------------------------
// ALLOCATE MEMORY FOR SUMMATIONS        ALLOCATE MEMORY FOR SUMMATIONS
//-----------------------------------------------------------------------


//-----------------------------------------------------------------------
// SUMMATIONS                  SUMMATIONS                  SUMMATIONS
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// DEFINE MENUS               DEFINE MENUS               DEFINE MENUS
//-----------------------------------------------------------------------



// Menu line and link to local menu
//-----------------------------------------------------------------------
static struct line_struct M_WindSpeedLinkToLocalMenu[] =
{
   MENU_ELEMENT_LINE_LINK("Wind Speed",                        PASSWORD_LEVEL_LICENCE_CUSTOMER,    "M_WindSpeed",                      "G_WindSpeed"),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_WindSpeedMenu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_WindSpeed",                      PASSWORD_LEVEL_LICENCE_CUSTOMER),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_WindSpeedMenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("WIND SPEED",                        PASSWORD_LEVEL_LICENCE_CUSTOMER,    "M_"APP_ID"AppMain",                "G_"APP_ID"App"),
   MENU_ELEMENT_LINE_VARRO("Wind Speed",                       PASSWORD_LEVEL_LICENCE_CUSTOMER,    (char*)"V_WindSpeed",                                LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Sensors Active",                   PASSWORD_LEVEL_LICENCE_CUSTOMER,    (char*)"V_WindSpeedSensorsActive",                   LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_LINK("Status",                            PASSWORD_LEVEL_LICENCE_CUSTOMER,    "M_Status2",                        "G_WindSpeed"),
   MENU_ELEMENT_LINE_LINK("Parameter",                         PASSWORD_LEVEL_LICENCE_CUSTOMER,    "M_Parameter3",                     "G_WindSpeed"),
   MENU_ELEMENT_LINE_LINK("Debug",                             PASSWORD_LEVEL_MITA_PROGRAMMER,     "M_Debug",                          "G_WindSpeed"),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_Status2Menu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_Status2",                        PASSWORD_LEVEL_LICENCE_CUSTOMER),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_Status2MenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("STATUS",                            PASSWORD_LEVEL_LICENCE_CUSTOMER,    "M_WindSpeed",                      "G_WindSpeed"),
   MENU_ELEMENT_LINE_VARRO("Wind Speed",                       PASSWORD_LEVEL_LICENCE_CUSTOMER,    (char*)"V_WindSpeed",                                LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Wind Speed 3 s.",                  PASSWORD_LEVEL_LICENCE_CUSTOMER,    (char*)"V_WindSpeed3Sec",                            LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Wind Speed 30 s.",                 PASSWORD_LEVEL_LICENCE_CUSTOMER,    (char*)"V_WindSpeed30Sec",                           LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Wind Speed 10 min.",               PASSWORD_LEVEL_LICENCE_CUSTOMER,    (char*)"V_WindSpeed10Min",                           LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Wind Speed Reference",             PASSWORD_LEVEL_LICENCE_CUSTOMER,    (char*)"V_WindSpeedRef",                             LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Wind speed max",                   PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_WIS_WindSpeedMax",                         LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Wind speed min",                   PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_WIS_WindSpeedMin",                         LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Wind speed variation",             PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_WIS_SpeedVariationPct",                    LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_LINK("Sensor Inputs",                     PASSWORD_LEVEL_LICENCE_CUSTOMER,    "M_SensorInputs35",                 "G_WindSpeed"),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_SensorInputs35Menu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_SensorInputs35",                 PASSWORD_LEVEL_LICENCE_CUSTOMER),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_SensorInputs35MenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("SENSOR INPUTS",                     PASSWORD_LEVEL_LICENCE_CUSTOMER,    "M_Status2",                        "G_WindSpeed"),
   MENU_ELEMENT_LINE_VARRO("Wind Speed Sensor 1",              PASSWORD_LEVEL_LICENCE_CUSTOMER,    (char*)"V_WindSpeedSensor1",                         LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Wind Speed Sensor 1 Status",       PASSWORD_LEVEL_LICENCE_CUSTOMER,    (char*)"V_WSSensor1StatusText",                      LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Wind Speed Sensor 2",              PASSWORD_LEVEL_LICENCE_CUSTOMER,    (char*)"V_WindSpeedSensor2",                         LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Wind Speed Sensor 2 Status",       PASSWORD_LEVEL_LICENCE_CUSTOMER,    (char*)"V_WSSensor2StatusText",                      LINE_FORMAT_NONE),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_Parameter3Menu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_Parameter3",                     PASSWORD_LEVEL_LICENCE_CUSTOMER),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_Parameter3MenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("PARAMETER",                         PASSWORD_LEVEL_LICENCE_CUSTOMER,    "M_WindSpeed",                      "G_WindSpeed"),
   MENU_ELEMENT_LINE_VARRW("Reload parameters",                PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_WIS_LoadParameters",                       LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Wind Speed Sensor Select",         PASSWORD_LEVEL_LICENCE_CUSTOMER,    (char*)"P_WindSpeedSensorSelect",                    LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_LINK("Max Wind Limit",                    PASSWORD_LEVEL_END_CUSTOMER,        "M_MaxWindLimit",                   "G_WindSpeed"),
   MENU_ELEMENT_LINE_LINK("Wind Speed Offset",                 PASSWORD_LEVEL_END_CUSTOMER,        "M_WindSpeedOffset",                "G_WindSpeed"),
   MENU_ELEMENT_LINE_VARRW("Wind speed variation rate up",     PASSWORD_LEVEL_LICENCE_PROGRAMMER,  (char*)"P_WIS_SpeedVariationRateUp",                 LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Wind speed variation rate down",   PASSWORD_LEVEL_LICENCE_PROGRAMMER,  (char*)"P_WIS_SpeedVariationRateDown",               LINE_FORMAT_NONE),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_MaxWindLimitMenu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_MaxWindLimit",                   PASSWORD_LEVEL_END_CUSTOMER),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_MaxWindLimitMenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("MAX WIND LIMIT",                    PASSWORD_LEVEL_END_CUSTOMER,        "M_Parameter3",                     "G_WindSpeed"),
   MENU_ELEMENT_LINE_VARRW("Wind Speed > Max. ON",             PASSWORD_LEVEL_LICENCE_CUSTOMER,    (char*)"P_WindSpeedMaxON",                           LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Wind Speed > Max. OFF",            PASSWORD_LEVEL_LICENCE_CUSTOMER,    (char*)"P_WindSpeedMaxOFF",                          LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Wind Speed >> Max. ON",            PASSWORD_LEVEL_LICENCE_CUSTOMER,    (char*)"P_WindSpeedMaxMaxON",                        LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Wind Speed >> Max. OFF",           PASSWORD_LEVEL_LICENCE_CUSTOMER,    (char*)"P_WindSpeedMaxMaxOFF",                       LINE_FORMAT_NONE),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_WindSpeedOffsetMenu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_WindSpeedOffset",                PASSWORD_LEVEL_END_CUSTOMER),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_WindSpeedOffsetMenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("WIND SPEED OFFSET",                 PASSWORD_LEVEL_END_CUSTOMER,        "M_Parameter3",                     "G_WindSpeed"),
   MENU_ELEMENT_LINE_VARRW("Offset value at peak wind",        PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_WIS_SpeedOffset",                          LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Offset peak wind speed",           PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_WIS_OffsetPeakSpeed",                      LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Offset max wind speed",            PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_WIS_OffsetMaxSpeed",                       LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_LINK("Help",                              PASSWORD_LEVEL_END_CUSTOMER,        "M_Help",                           "G_WindSpeed"),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_HelpMenu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_Help",                           PASSWORD_LEVEL_END_CUSTOMER),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_HelpMenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("HELP",                              PASSWORD_LEVEL_END_CUSTOMER,        "M_WindSpeedOffset",                "G_WindSpeed"),
   MENU_ELEMENT_LINE_TEXT("Wind speed offset is applied in linear relation", PASSWORD_LEVEL_END_CUSTOMER),
   MENU_ELEMENT_LINE_TEXT("from 0 to \"peak\" wind speed in increasing value.", PASSWORD_LEVEL_END_CUSTOMER),
   MENU_ELEMENT_LINE_TEXT("In \"peak\" wind speed, actual offset equals the", PASSWORD_LEVEL_END_CUSTOMER),
   MENU_ELEMENT_LINE_TEXT("offset parameter value.",           PASSWORD_LEVEL_END_CUSTOMER),
   MENU_ELEMENT_LINE_TEXT("Above peak wind, offset starts to decrease", PASSWORD_LEVEL_END_CUSTOMER),
   MENU_ELEMENT_LINE_TEXT("and finally reaches 0 at \"max\" wind speed.", PASSWORD_LEVEL_END_CUSTOMER),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_DebugMenu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_Debug",                          PASSWORD_LEVEL_MITA_PROGRAMMER),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_DebugMenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("DEBUG",                             PASSWORD_LEVEL_MITA_PROGRAMMER,     "M_WindSpeed",                      "G_WindSpeed"),
   MENU_ELEMENT_LINE_VARRW("V_WIS_WindSpeed_Debug",            PASSWORD_LEVEL_LICENCE_PROGRAMMER,  (char*)"V_WIS_WindSpeed_Debug",                      LINE_FORMAT_NONE),
};
// Creating parameters for multiplexed categories
//-----------------------------------------------------------------------
static struct multiplexed_info_struct M_WindSpeedMultiplexedCategoriesParameters[] =
{
0};

//-----------------------------------------------------------------------
// CREATE MENUS               CREATE MENUS               CREATE MENUS
//-----------------------------------------------------------------------

// Memory reservation
//-----------------------------------------------------------------------
static struct menu_group_struct ObjGroup[1];

// Creating the menus
//-----------------------------------------------------------------------
STATUS WindSpeedMenuAppInit(U8 ModuleState, OS_MEMORY_POOL* pPool)
{
   STATUS Status;

   if (ModuleState == APP_INIT1)
   {
      /* Create application group */
      Status = OS_CreateMenuGroup(ObjGroup, M_WindSpeedLinkToLocalMenu[0].LinkGroup);
      STATUS_LINE_VAR_RETURN_VALUE(Status);
   }

   Status = CreateAndInitializeMenu(ModuleState,
                                    M_WindSpeedMenuLines[0].LinkGroup,
                                    M_WindSpeedMenuLines[0].LinkName,
                                    ELEMENT(M_WindSpeedLinkToLocalMenu),
                                    M_WindSpeedLinkToLocalMenu[0].LinkGroup,
                                    ELEMENT(M_WindSpeedMenu),
                                    M_WindSpeedLinkToLocalMenu[0].LinkName,
                                    ELEMENT(M_WindSpeedMenuLines),
                                    pPool,
                                    M_WindSpeedMultiplexedCategoriesParameters);
   STATUS_LINE_VAR_RETURN_VALUE(Status);

   Status = CreateAndInitializeMenu(ModuleState,
                                    M_Status2MenuLines[0].LinkGroup,
                                    M_Status2MenuLines[0].LinkName,
                                    NULL,
                                    0,
                                    M_WindSpeedMenuLines[3].LinkGroup,
                                    ELEMENT(M_Status2Menu),
                                    M_WindSpeedMenuLines[3].LinkName,
                                    ELEMENT(M_Status2MenuLines),
                                    pPool,
                                    M_WindSpeedMultiplexedCategoriesParameters);
   STATUS_LINE_VAR_RETURN_VALUE(Status);

   Status = CreateAndInitializeMenu(ModuleState,
                                    M_SensorInputs35MenuLines[0].LinkGroup,
                                    M_SensorInputs35MenuLines[0].LinkName,
                                    NULL,
                                    0,
                                    M_Status2MenuLines[9].LinkGroup,
                                    ELEMENT(M_SensorInputs35Menu),
                                    M_Status2MenuLines[9].LinkName,
                                    ELEMENT(M_SensorInputs35MenuLines),
                                    pPool,
                                    M_WindSpeedMultiplexedCategoriesParameters);
   STATUS_LINE_VAR_RETURN_VALUE(Status);

   Status = CreateAndInitializeMenu(ModuleState,
                                    M_Parameter3MenuLines[0].LinkGroup,
                                    M_Parameter3MenuLines[0].LinkName,
                                    NULL,
                                    0,
                                    M_WindSpeedMenuLines[4].LinkGroup,
                                    ELEMENT(M_Parameter3Menu),
                                    M_WindSpeedMenuLines[4].LinkName,
                                    ELEMENT(M_Parameter3MenuLines),
                                    pPool,
                                    M_WindSpeedMultiplexedCategoriesParameters);
   STATUS_LINE_VAR_RETURN_VALUE(Status);

   Status = CreateAndInitializeMenu(ModuleState,
                                    M_MaxWindLimitMenuLines[0].LinkGroup,
                                    M_MaxWindLimitMenuLines[0].LinkName,
                                    NULL,
                                    0,
                                    M_Parameter3MenuLines[3].LinkGroup,
                                    ELEMENT(M_MaxWindLimitMenu),
                                    M_Parameter3MenuLines[3].LinkName,
                                    ELEMENT(M_MaxWindLimitMenuLines),
                                    pPool,
                                    M_WindSpeedMultiplexedCategoriesParameters);
   STATUS_LINE_VAR_RETURN_VALUE(Status);

   Status = CreateAndInitializeMenu(ModuleState,
                                    M_WindSpeedOffsetMenuLines[0].LinkGroup,
                                    M_WindSpeedOffsetMenuLines[0].LinkName,
                                    NULL,
                                    0,
                                    M_Parameter3MenuLines[4].LinkGroup,
                                    ELEMENT(M_WindSpeedOffsetMenu),
                                    M_Parameter3MenuLines[4].LinkName,
                                    ELEMENT(M_WindSpeedOffsetMenuLines),
                                    pPool,
                                    M_WindSpeedMultiplexedCategoriesParameters);
   STATUS_LINE_VAR_RETURN_VALUE(Status);

   Status = CreateAndInitializeMenu(ModuleState,
                                    M_HelpMenuLines[0].LinkGroup,
                                    M_HelpMenuLines[0].LinkName,
                                    NULL,
                                    0,
                                    M_WindSpeedOffsetMenuLines[4].LinkGroup,
                                    ELEMENT(M_HelpMenu),
                                    M_WindSpeedOffsetMenuLines[4].LinkName,
                                    ELEMENT(M_HelpMenuLines),
                                    pPool,
                                    M_WindSpeedMultiplexedCategoriesParameters);
   STATUS_LINE_VAR_RETURN_VALUE(Status);

   Status = CreateAndInitializeMenu(ModuleState,
                                    M_DebugMenuLines[0].LinkGroup,
                                    M_DebugMenuLines[0].LinkName,
                                    NULL,
                                    0,
                                    M_WindSpeedMenuLines[5].LinkGroup,
                                    ELEMENT(M_DebugMenu),
                                    M_WindSpeedMenuLines[5].LinkName,
                                    ELEMENT(M_DebugMenuLines),
                                    pPool,
                                    M_WindSpeedMultiplexedCategoriesParameters);
   STATUS_LINE_VAR_RETURN_VALUE(Status);

   return OS_SUCCESS;
}

#define CREATE_MENU

//-----------------------------------------------------------------------
//               BUTTONS FUNCTIONS FORWARD DECLARATIONS
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// BUTTONS                       BUTTONS                      BUTTONS
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
//             SET/RESET FUNCTIONS FORWARD DECLARATIONS
//-----------------------------------------------------------------------
static U8 StatusSetFunc249(void);
static U8 StatusResetFunc249(void);
static U8 StatusSetFunc250(void);
static U8 StatusResetFunc250(void);
static U8 StatusSetFunc251(void);
static U8 StatusResetFunc251(void);
//-----------------------------------------------------------------------
// STATUSCODES                 STATUSCODES                 STATUSCODES
//-----------------------------------------------------------------------

static struct sts_statuscode_structure StatusCodes[] =
{
   STS_CODE_ELEMENT("Wind Speed!",            20*SEC,    249,       STATUSCODE_UPDATE_TYPE_POLLING,         PASSWORD_LEVEL_SERVICE,            STATUSCODE_TIMER_TYPE_CONSTANT,     STATUSCODE_TIMER_TYPE_CONSTANT,     STATUSCODE_RESET_TYPE_AUTOMATIC,    STATUSCODE_PRIORITY_LOW,       21,   0,    32,   NULL,      PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_SERVICE,            StatusSetFunc249,        StatusResetFunc249,      BRAKE_PROG_50,       BRAKE_PROG_0,        BRAKE_PROG_MAX,      NULL,                PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_MITA_PROGRAMMER,    YAW_PROG_0,          YAW_PROG_0,          YAW_PROG_240,        NULL,                PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_MITA_PROGRAMMER,    0,    0,    255,  NULL,      PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_SERVICE,            1,  PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_ADMINISTRATOR,      20,        20,        1000,      NULL,      PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         SETDELAY_MIN,   SETDELAY_MAX,   NULL,      PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         RESETDELAY_MIN, RESETDELAY_MAX, NULL,      PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         REPEATTIMES_MIN,     REPEATTIMES_MAX,     NULL,      PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         REPEATPERIOD_MIN,    REPEATPERIOD_MAX,    NULL,      PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         REPEATCODE_MIN,      REPEATCODE_MAX,      NULL,      PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         TIMEOUTPERIOD_MIN,   65535,               NULL,      PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         TIMEOUTCODE_MIN,     TIMEOUTCODE_MAX,     NULL,      PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_SERVICE,            NULL),
   STS_CODE_ELEMENT("Wind > max.",            20*SEC,    250,       STATUSCODE_UPDATE_TYPE_POLLING,         PASSWORD_LEVEL_SERVICE,            STATUSCODE_TIMER_TYPE_CONSTANT,     STATUSCODE_TIMER_TYPE_CONSTANT,     STATUSCODE_RESET_TYPE_AUTOMATIC,    STATUSCODE_PRIORITY_LOW,       15,   0,    32,   NULL,      PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_SERVICE,            StatusSetFunc250,        StatusResetFunc250,      BRAKE_PROG_50,       BRAKE_PROG_0,        BRAKE_PROG_MAX,      NULL,                PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_MITA_PROGRAMMER,    YAW_PROG_0,          YAW_PROG_0,          YAW_PROG_240,        NULL,                PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_MITA_PROGRAMMER,    0,    0,    255,  NULL,      PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_SERVICE,            1,  PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_ADMINISTRATOR,      20,        20,        1000,      NULL,      PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         SETDELAY_MIN,   SETDELAY_MAX,   NULL,      PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         RESETDELAY_MIN, RESETDELAY_MAX, NULL,      PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         REPEATTIMES_MIN,     REPEATTIMES_MAX,     NULL,      PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         REPEATPERIOD_MIN,    REPEATPERIOD_MAX,    NULL,      PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         REPEATCODE_MIN,      REPEATCODE_MAX,      NULL,      PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         TIMEOUTPERIOD_MIN,   65535,               NULL,      PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         TIMEOUTCODE_MIN,     TIMEOUTCODE_MAX,     NULL,      PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_SERVICE,            NULL),
   STS_CODE_ELEMENT("Wind >> max.",           20*SEC,    251,       STATUSCODE_UPDATE_TYPE_POLLING,         PASSWORD_LEVEL_SERVICE,            STATUSCODE_TIMER_TYPE_CONSTANT,     STATUSCODE_TIMER_TYPE_CONSTANT,     STATUSCODE_RESET_TYPE_AUTOMATIC,    STATUSCODE_PRIORITY_LOW,       15,   0,    32,   NULL,      PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_SERVICE,            StatusSetFunc251,        StatusResetFunc251,      BRAKE_PROG_50,       BRAKE_PROG_0,        BRAKE_PROG_MAX,      NULL,                PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_MITA_PROGRAMMER,    YAW_PROG_0,          YAW_PROG_0,          YAW_PROG_240,        NULL,                PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_MITA_PROGRAMMER,    0,    0,    255,  NULL,      PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_SERVICE,            1,  PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_ADMINISTRATOR,      20,        20,        1000,      NULL,      PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         SETDELAY_MIN,   SETDELAY_MAX,   NULL,      PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         RESETDELAY_MIN, RESETDELAY_MAX, NULL,      PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         REPEATTIMES_MIN,     REPEATTIMES_MAX,     NULL,      PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         REPEATPERIOD_MIN,    REPEATPERIOD_MAX,    NULL,      PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         REPEATCODE_MIN,      REPEATCODE_MAX,      NULL,      PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         TIMEOUTPERIOD_MIN,   65535,               NULL,      PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         TIMEOUTCODE_MIN,     TIMEOUTCODE_MAX,     NULL,      PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_SERVICE,            NULL),
};

static STATUS_CODE_CONTROL_BLOCK StatusCodeControlBlock;

static STATUS LocalStatusCodeInit(void)
{
   STATUS LocalStatus;

   LocalStatus = OS_StatusCodeInit(STATUSCODE_INTERFACE_VERSION,
                                   &StatusCodeControlBlock,
                                   StatusCodes,
                                   sizeof(StatusCodes)/sizeof(StatusCodes[0]),
                                   AppLocalParameterPosition(),
                                   AppBackupPosition());
   STATUS_LINE_VAR_RETURN_CONST(LocalStatus, ERR_3);

   return OS_SUCCESS;
}

#define CREATE_STATUS_CODES

//-----------------------------------------------------------------------
// MODIFIABLE                  MODIFIABLE                   MODIFIABLE
//-----------------------------------------------------------------------

extern const char WindSpeedAppGroupName[];
extern const char WindSpeedAppMenuName[];
extern const U8 WindSpeed_Conf_Menu_Main_Read;
extern const U8 WindSpeed_Conf_Menu_Main_Write;
extern const U8 WindSpeed_Conf_Menu_Mita_Read;
extern const U8 WindSpeed_Conf_Menu_Mita_Write;
extern const U8 WindSpeed_Conf_Menu_Parameter_Read;
extern const U8 WindSpeed_Conf_Menu_Parameter_Write;
extern const U8 WindSpeed_Conf_Menu_Service_Read;
extern const U8 WindSpeed_Conf_Menu_Service_Write;
extern const U8 WindSpeed_Conf_Menu_Status_Read;
extern const U16 WindSpeed_Conf_P_WindSpeedMaxMaxOFF_InitValueExt;
extern const U16 WindSpeed_Conf_P_WindSpeedMaxMaxOFF_MaximumValueExt;
extern const U16 WindSpeed_Conf_P_WindSpeedMaxMaxOFF_MinimumValueExt;
extern const U16 WindSpeed_Conf_P_WindSpeedMaxMaxON_InitValueExt;
extern const U16 WindSpeed_Conf_P_WindSpeedMaxMaxON_MaximumValueExt;
extern const U16 WindSpeed_Conf_P_WindSpeedMaxMaxON_MinimumValueExt;
extern const U16 WindSpeed_Conf_P_WindSpeedMaxOFF_InitValueExt;
extern const U16 WindSpeed_Conf_P_WindSpeedMaxOFF_MaximumValueExt;
extern const U16 WindSpeed_Conf_P_WindSpeedMaxOFF_MinimumValueExt;
extern const U16 WindSpeed_Conf_P_WindSpeedMaxON_InitValueExt;
extern const U16 WindSpeed_Conf_P_WindSpeedMaxON_MaximumValueExt;
extern const U16 WindSpeed_Conf_P_WindSpeedMaxON_MinimumValueExt;
extern const U8 WindSpeed_Conf_SC_249_AlarmProgramConst;
extern const U8 WindSpeed_Conf_SC_249_AvailabilityGroupConst;
extern const U8 WindSpeed_Conf_SC_249_BrakeProgramConst;
extern const U8 WindSpeed_Conf_SC_249_EnableStatusCodeConst;
extern const U32 WindSpeed_Conf_SC_249_ResetDelayConst;
extern const U32 WindSpeed_Conf_SC_249_SetDelayConst;
extern const U8 WindSpeed_Conf_SC_249_YawProgramConst;
extern const U8 WindSpeed_Conf_SC_250_AlarmProgramConst;
extern const U8 WindSpeed_Conf_SC_250_AvailabilityGroupConst;
extern const U8 WindSpeed_Conf_SC_250_BrakeProgramConst;
extern const U8 WindSpeed_Conf_SC_250_EnableStatusCodeConst;
extern const U32 WindSpeed_Conf_SC_250_ResetDelayConst;
extern const U32 WindSpeed_Conf_SC_250_SetDelayConst;
extern const U8 WindSpeed_Conf_SC_250_YawProgramConst;
extern const U8 WindSpeed_Conf_SC_251_AlarmProgramConst;
extern const U8 WindSpeed_Conf_SC_251_AvailabilityGroupConst;
extern const U8 WindSpeed_Conf_SC_251_BrakeProgramConst;
extern const U8 WindSpeed_Conf_SC_251_EnableStatusCodeConst;
extern const U32 WindSpeed_Conf_SC_251_ResetDelayConst;
extern const U32 WindSpeed_Conf_SC_251_SetDelayConst;
extern const U8 WindSpeed_Conf_SC_251_YawProgramConst;
extern const U8 WindSpeed_Conf_SC_Activate_Counter_Backup_Read;
extern const U8 WindSpeed_Conf_SC_Activate_Counter_Backup_Write;
extern const U8 WindSpeed_Conf_SC_Alarm_Program_Read;
extern const U8 WindSpeed_Conf_SC_Availability_Group_Read;
extern const U8 WindSpeed_Conf_SC_Availability_Group_Write;
extern const U8 WindSpeed_Conf_SC_Brake_Program_Read;
extern const U8 WindSpeed_Conf_SC_Enable_Read;
extern const U8 WindSpeed_Conf_SC_Enable_Write;
extern const U8 WindSpeed_Conf_SC_Repeat_Code_Read;
extern const U8 WindSpeed_Conf_SC_Repeat_Period_Read;
extern const U8 WindSpeed_Conf_SC_Repeat_Times_Read;
extern const U8 WindSpeed_Conf_SC_Reset_Delay_Read;
extern const U8 WindSpeed_Conf_SC_Reset_Delay_Write;
extern const U8 WindSpeed_Conf_SC_Reset_Status_Code_Write;
extern const U8 WindSpeed_Conf_SC_Set_Delay_Read;
extern const U8 WindSpeed_Conf_SC_Set_Delay_Write;
extern const U8 WindSpeed_Conf_SC_TimeOut_Code_Read;
extern const U8 WindSpeed_Conf_SC_TimeOut_Period_Read;
extern const U8 WindSpeed_Conf_SC_Update_Interval_Read;
extern const U8 WindSpeed_Conf_SC_Yaw_Program_Read;
extern const U8 WindSpeed_Conf_Summation_Read;
extern const U8 WindSpeed_Conf_Summation_Write;

static void Init_Structures_From_Conf_File(void)
{
   LocalVars[0].c.AccessRead = WindSpeed_Conf_Menu_Status_Read;
   LocalVars[1].c.AccessRead = WindSpeed_Conf_Menu_Status_Read;
   LocalVars[2].c.AccessRead = WindSpeed_Conf_Menu_Status_Read;
   LocalVars[3].c.AccessRead = WindSpeed_Conf_Menu_Status_Read;
   LocalVars[4].c.AccessRead = WindSpeed_Conf_Menu_Status_Read;
   LocalVars[5].c.AccessRead = WindSpeed_Conf_Menu_Status_Read;
   LocalVars[6].c.AccessRead = WindSpeed_Conf_Menu_Status_Read;
   LocalVars[7].c.AccessRead = WindSpeed_Conf_Menu_Status_Read;
   LocalVars[8].c.AccessRead = WindSpeed_Conf_Menu_Status_Read;
   ParameterVars[0].c.AccessRead = WindSpeed_Conf_Menu_Parameter_Read;
   ParameterVars[0].c.AccessWrite = WindSpeed_Conf_Menu_Parameter_Write;
   ParameterVars[0].c.Value.u16 = WindSpeed_Conf_P_WindSpeedMaxON_InitValueExt;
   ParameterVars[0].l.Minimum.u16 = WindSpeed_Conf_P_WindSpeedMaxON_MinimumValueExt;
   ParameterVars[0].l.Maximum.u16 = WindSpeed_Conf_P_WindSpeedMaxON_MaximumValueExt;
   ParameterVars[1].c.AccessRead = WindSpeed_Conf_Menu_Parameter_Read;
   ParameterVars[1].c.AccessWrite = WindSpeed_Conf_Menu_Parameter_Write;
   ParameterVars[1].c.Value.u16 = WindSpeed_Conf_P_WindSpeedMaxOFF_InitValueExt;
   ParameterVars[1].l.Minimum.u16 = WindSpeed_Conf_P_WindSpeedMaxOFF_MinimumValueExt;
   ParameterVars[1].l.Maximum.u16 = WindSpeed_Conf_P_WindSpeedMaxOFF_MaximumValueExt;
   ParameterVars[2].c.AccessRead = WindSpeed_Conf_Menu_Parameter_Read;
   ParameterVars[2].c.AccessWrite = WindSpeed_Conf_Menu_Parameter_Write;
   ParameterVars[2].c.Value.u16 = WindSpeed_Conf_P_WindSpeedMaxMaxON_InitValueExt;
   ParameterVars[2].l.Minimum.u16 = WindSpeed_Conf_P_WindSpeedMaxMaxON_MinimumValueExt;
   ParameterVars[2].l.Maximum.u16 = WindSpeed_Conf_P_WindSpeedMaxMaxON_MaximumValueExt;
   ParameterVars[3].c.AccessRead = WindSpeed_Conf_Menu_Parameter_Read;
   ParameterVars[3].c.AccessWrite = WindSpeed_Conf_Menu_Parameter_Write;
   ParameterVars[3].c.Value.u16 = WindSpeed_Conf_P_WindSpeedMaxMaxOFF_InitValueExt;
   ParameterVars[3].l.Minimum.u16 = WindSpeed_Conf_P_WindSpeedMaxMaxOFF_MinimumValueExt;
   ParameterVars[3].l.Maximum.u16 = WindSpeed_Conf_P_WindSpeedMaxMaxOFF_MaximumValueExt;
   ParameterVars[4].c.AccessRead = WindSpeed_Conf_Menu_Parameter_Read;
   ParameterVars[4].c.AccessWrite = WindSpeed_Conf_Menu_Parameter_Write;
   M_WindSpeedMenuLines[0].LinkName = (char*)WindSpeedAppMenuName;
   M_WindSpeedMenuLines[0].LinkGroup = (char*)WindSpeedAppGroupName;
   M_Status2MenuLines[9].ViewPasswordLevel = WindSpeed_Conf_Menu_Status_Read;
   M_SensorInputs35Menu[0].ViewPasswordLevel = WindSpeed_Conf_Menu_Status_Read;
   M_SensorInputs35MenuLines[0].ViewPasswordLevel = WindSpeed_Conf_Menu_Status_Read;
   M_WindSpeedMenuLines[3].ViewPasswordLevel = WindSpeed_Conf_Menu_Status_Read;
   M_Status2Menu[0].ViewPasswordLevel = WindSpeed_Conf_Menu_Status_Read;
   M_Status2MenuLines[0].ViewPasswordLevel = WindSpeed_Conf_Menu_Status_Read;
   M_WindSpeedMenuLines[4].ViewPasswordLevel = WindSpeed_Conf_Menu_Parameter_Read;
   M_Parameter3Menu[0].ViewPasswordLevel = WindSpeed_Conf_Menu_Parameter_Read;
   M_Parameter3MenuLines[0].ViewPasswordLevel = WindSpeed_Conf_Menu_Parameter_Read;
   M_WindSpeedLinkToLocalMenu[0].ViewPasswordLevel = WindSpeed_Conf_Menu_Main_Read;
   M_WindSpeedMenu[0].ViewPasswordLevel = WindSpeed_Conf_Menu_Main_Read;
   M_WindSpeedMenuLines[0].ViewPasswordLevel = WindSpeed_Conf_Menu_Main_Read;
   M_WindSpeedMenuLines[1].ViewPasswordLevel = WindSpeed_Conf_Menu_Main_Read;
   M_WindSpeedMenuLines[2].ViewPasswordLevel = WindSpeed_Conf_Menu_Main_Read;
   M_Status2MenuLines[1].ViewPasswordLevel = WindSpeed_Conf_Menu_Status_Read;
   M_Status2MenuLines[2].ViewPasswordLevel = WindSpeed_Conf_Menu_Status_Read;
   M_Status2MenuLines[3].ViewPasswordLevel = WindSpeed_Conf_Menu_Status_Read;
   M_Status2MenuLines[4].ViewPasswordLevel = WindSpeed_Conf_Menu_Status_Read;
   M_Status2MenuLines[5].ViewPasswordLevel = WindSpeed_Conf_Menu_Status_Read;
   M_SensorInputs35MenuLines[1].ViewPasswordLevel = WindSpeed_Conf_Menu_Status_Read;
   M_SensorInputs35MenuLines[2].ViewPasswordLevel = WindSpeed_Conf_Menu_Status_Read;
   M_SensorInputs35MenuLines[3].ViewPasswordLevel = WindSpeed_Conf_Menu_Status_Read;
   M_SensorInputs35MenuLines[4].ViewPasswordLevel = WindSpeed_Conf_Menu_Status_Read;
   M_Parameter3MenuLines[2].ViewPasswordLevel = WindSpeed_Conf_Menu_Parameter_Read;
   M_MaxWindLimitMenuLines[1].ViewPasswordLevel = WindSpeed_Conf_Menu_Parameter_Read;
   M_MaxWindLimitMenuLines[2].ViewPasswordLevel = WindSpeed_Conf_Menu_Parameter_Read;
   M_MaxWindLimitMenuLines[3].ViewPasswordLevel = WindSpeed_Conf_Menu_Parameter_Read;
   M_MaxWindLimitMenuLines[4].ViewPasswordLevel = WindSpeed_Conf_Menu_Parameter_Read;
   StatusCodes[0].StsResetPasswordLevel = WindSpeed_Conf_SC_Reset_Status_Code_Write;
   StatusCodes[0].StsUpdateIntervalAccessRead = WindSpeed_Conf_SC_Update_Interval_Read;
   StatusCodes[0].StsAvailabilityGroup = WindSpeed_Conf_SC_249_AvailabilityGroupConst;
   StatusCodes[0].AvailabilityGroupAccessRead = WindSpeed_Conf_SC_Availability_Group_Read;
   StatusCodes[0].AvailabilityGroupAccessWrite = WindSpeed_Conf_SC_Availability_Group_Write;
   StatusCodes[0].StsControlProgram1 = WindSpeed_Conf_SC_249_BrakeProgramConst;
   StatusCodes[0].StsControlProgram1AccessRead = WindSpeed_Conf_SC_Brake_Program_Read;
   StatusCodes[0].StsControlProgram2 = WindSpeed_Conf_SC_249_YawProgramConst;
   StatusCodes[0].StsControlProgram2AccessRead = WindSpeed_Conf_SC_Yaw_Program_Read;
   StatusCodes[0].StsControlProgram3 = WindSpeed_Conf_SC_249_AlarmProgramConst;
   StatusCodes[0].StsControlProgram3AccessRead = WindSpeed_Conf_SC_Alarm_Program_Read;
   StatusCodes[0].StsCodeEnable = WindSpeed_Conf_SC_249_EnableStatusCodeConst;
   StatusCodes[0].StsCodeEnableAccessRead = WindSpeed_Conf_SC_Enable_Read;
   StatusCodes[0].StsCodeEnableAccessWrite = WindSpeed_Conf_SC_Enable_Write;
   StatusCodes[0].StsSetDelay = WindSpeed_Conf_SC_249_SetDelayConst;
   StatusCodes[0].StsSetDelayAccessRead = WindSpeed_Conf_SC_Set_Delay_Read;
   StatusCodes[0].StsSetDelayAccessWrite = WindSpeed_Conf_SC_Set_Delay_Write;
   StatusCodes[0].StsResetDelay = WindSpeed_Conf_SC_249_ResetDelayConst;
   StatusCodes[0].StsResetDelayAccessRead = WindSpeed_Conf_SC_Reset_Delay_Read;
   StatusCodes[0].StsResetDelayAccessWrite = WindSpeed_Conf_SC_Reset_Delay_Write;
   StatusCodes[0].StsActiveRepeatTimesAccessRead = WindSpeed_Conf_SC_Repeat_Times_Read;
   StatusCodes[0].StsActiveRepeatPeriodAccessRead = WindSpeed_Conf_SC_Repeat_Period_Read;
   StatusCodes[0].StsActiveRepeatCodeAccessRead = WindSpeed_Conf_SC_Repeat_Code_Read;
   StatusCodes[0].StsActiveTimeoutPeriodAccessRead = WindSpeed_Conf_SC_TimeOut_Period_Read;
   StatusCodes[0].StsActiveTimeoutCodeAccessRead = WindSpeed_Conf_SC_TimeOut_Code_Read;
   StatusCodes[0].ActivateCounterAccessRead = WindSpeed_Conf_SC_Activate_Counter_Backup_Read;
   StatusCodes[0].ActivateCounterAccessWrite = WindSpeed_Conf_SC_Activate_Counter_Backup_Write;
   StatusCodes[1].StsResetPasswordLevel = WindSpeed_Conf_SC_Reset_Status_Code_Write;
   StatusCodes[1].StsUpdateIntervalAccessRead = WindSpeed_Conf_SC_Update_Interval_Read;
   StatusCodes[1].StsAvailabilityGroup = WindSpeed_Conf_SC_250_AvailabilityGroupConst;
   StatusCodes[1].AvailabilityGroupAccessRead = WindSpeed_Conf_SC_Availability_Group_Read;
   StatusCodes[1].AvailabilityGroupAccessWrite = WindSpeed_Conf_SC_Availability_Group_Write;
   StatusCodes[1].StsControlProgram1 = WindSpeed_Conf_SC_250_BrakeProgramConst;
   StatusCodes[1].StsControlProgram1AccessRead = WindSpeed_Conf_SC_Brake_Program_Read;
   StatusCodes[1].StsControlProgram2 = WindSpeed_Conf_SC_250_YawProgramConst;
   StatusCodes[1].StsControlProgram2AccessRead = WindSpeed_Conf_SC_Yaw_Program_Read;
   StatusCodes[1].StsControlProgram3 = WindSpeed_Conf_SC_250_AlarmProgramConst;
   StatusCodes[1].StsControlProgram3AccessRead = WindSpeed_Conf_SC_Alarm_Program_Read;
   StatusCodes[1].StsCodeEnable = WindSpeed_Conf_SC_250_EnableStatusCodeConst;
   StatusCodes[1].StsCodeEnableAccessRead = WindSpeed_Conf_SC_Enable_Read;
   StatusCodes[1].StsCodeEnableAccessWrite = WindSpeed_Conf_SC_Enable_Write;
   StatusCodes[1].StsSetDelay = WindSpeed_Conf_SC_250_SetDelayConst;
   StatusCodes[1].StsSetDelayAccessRead = WindSpeed_Conf_SC_Set_Delay_Read;
   StatusCodes[1].StsSetDelayAccessWrite = WindSpeed_Conf_SC_Set_Delay_Write;
   StatusCodes[1].StsResetDelay = WindSpeed_Conf_SC_250_ResetDelayConst;
   StatusCodes[1].StsResetDelayAccessRead = WindSpeed_Conf_SC_Reset_Delay_Read;
   StatusCodes[1].StsResetDelayAccessWrite = WindSpeed_Conf_SC_Reset_Delay_Write;
   StatusCodes[1].StsActiveRepeatTimesAccessRead = WindSpeed_Conf_SC_Repeat_Times_Read;
   StatusCodes[1].StsActiveRepeatPeriodAccessRead = WindSpeed_Conf_SC_Repeat_Period_Read;
   StatusCodes[1].StsActiveRepeatCodeAccessRead = WindSpeed_Conf_SC_Repeat_Code_Read;
   StatusCodes[1].StsActiveTimeoutPeriodAccessRead = WindSpeed_Conf_SC_TimeOut_Period_Read;
   StatusCodes[1].StsActiveTimeoutCodeAccessRead = WindSpeed_Conf_SC_TimeOut_Code_Read;
   StatusCodes[1].ActivateCounterAccessRead = WindSpeed_Conf_SC_Activate_Counter_Backup_Read;
   StatusCodes[1].ActivateCounterAccessWrite = WindSpeed_Conf_SC_Activate_Counter_Backup_Write;
   StatusCodes[2].StsResetPasswordLevel = WindSpeed_Conf_SC_Reset_Status_Code_Write;
   StatusCodes[2].StsUpdateIntervalAccessRead = WindSpeed_Conf_SC_Update_Interval_Read;
   StatusCodes[2].StsAvailabilityGroup = WindSpeed_Conf_SC_251_AvailabilityGroupConst;
   StatusCodes[2].AvailabilityGroupAccessRead = WindSpeed_Conf_SC_Availability_Group_Read;
   StatusCodes[2].AvailabilityGroupAccessWrite = WindSpeed_Conf_SC_Availability_Group_Write;
   StatusCodes[2].StsControlProgram1 = WindSpeed_Conf_SC_251_BrakeProgramConst;
   StatusCodes[2].StsControlProgram1AccessRead = WindSpeed_Conf_SC_Brake_Program_Read;
   StatusCodes[2].StsControlProgram2 = WindSpeed_Conf_SC_251_YawProgramConst;
   StatusCodes[2].StsControlProgram2AccessRead = WindSpeed_Conf_SC_Yaw_Program_Read;
   StatusCodes[2].StsControlProgram3 = WindSpeed_Conf_SC_251_AlarmProgramConst;
   StatusCodes[2].StsControlProgram3AccessRead = WindSpeed_Conf_SC_Alarm_Program_Read;
   StatusCodes[2].StsCodeEnable = WindSpeed_Conf_SC_251_EnableStatusCodeConst;
   StatusCodes[2].StsCodeEnableAccessRead = WindSpeed_Conf_SC_Enable_Read;
   StatusCodes[2].StsCodeEnableAccessWrite = WindSpeed_Conf_SC_Enable_Write;
   StatusCodes[2].StsSetDelay = WindSpeed_Conf_SC_251_SetDelayConst;
   StatusCodes[2].StsSetDelayAccessRead = WindSpeed_Conf_SC_Set_Delay_Read;
   StatusCodes[2].StsSetDelayAccessWrite = WindSpeed_Conf_SC_Set_Delay_Write;
   StatusCodes[2].StsResetDelay = WindSpeed_Conf_SC_251_ResetDelayConst;
   StatusCodes[2].StsResetDelayAccessRead = WindSpeed_Conf_SC_Reset_Delay_Read;
   StatusCodes[2].StsResetDelayAccessWrite = WindSpeed_Conf_SC_Reset_Delay_Write;
   StatusCodes[2].StsActiveRepeatTimesAccessRead = WindSpeed_Conf_SC_Repeat_Times_Read;
   StatusCodes[2].StsActiveRepeatPeriodAccessRead = WindSpeed_Conf_SC_Repeat_Period_Read;
   StatusCodes[2].StsActiveRepeatCodeAccessRead = WindSpeed_Conf_SC_Repeat_Code_Read;
   StatusCodes[2].StsActiveTimeoutPeriodAccessRead = WindSpeed_Conf_SC_TimeOut_Period_Read;
   StatusCodes[2].StsActiveTimeoutCodeAccessRead = WindSpeed_Conf_SC_TimeOut_Code_Read;
   StatusCodes[2].ActivateCounterAccessRead = WindSpeed_Conf_SC_Activate_Counter_Backup_Read;
   StatusCodes[2].ActivateCounterAccessWrite = WindSpeed_Conf_SC_Activate_Counter_Backup_Write;
}

//-----------------------------------------------------------------------
// AUTOGENERATED END        AUTOGENERATED END        AUTOGENERATED END
//-----------------------------------------------------------------------
//}

#undef AUTOGENERATED_PART

//-----------------------------------------------------------------------
// USER DEFINITIONS         USER DEFINITIONS         USER DEFINITIONS
//-----------------------------------------------------------------------

//#define WIS_DEBUG

#define WIS_TASK_SCANTIME 20


// parameters
S16 P_WIS_SpeedOffset = 0;
U16 P_WIS_OffsetPeakSpeed = 0;
U16 P_WIS_OffsetMaxSpeed = 0;
U16 P_WIS_SpeedVariationRateUp = 0;
U16 P_WIS_SpeedVariationRateDown = 0;
 
F32 OffsetGain1 = 0;
F32 OffsetGain2 = 0;
 
static Rate_Limiter WindSpeedMax_RateLim;
static Rate_Limiter WindSpeedMin_RateLim;
static Rate_Limiter SpeedVariation_RateLim;

#if defined DLL_SIMU
varid_t DLL_IN_HubWindSpeed_ID;
F32 DLL_IN_HubWindSpeed;
#endif

 

//-----------------------------------------------------------------------
// SET/RESET FUNCTIONS    SET/RESET FUNCTIONS    SET/RESET FUNCTIONS
//-----------------------------------------------------------------------
static U8 StatusSetFunc249(void)
{
	if((P_WindSpeedSensorSelect == 0) && V_WindSpeedSensor1Status && V_WindSpeedSensor2Status)
		return 1;
	if((P_WindSpeedSensorSelect == 1) && V_WindSpeedSensor1Status)
		return 1;
	if((P_WindSpeedSensorSelect == 2) && V_WindSpeedSensor2Status)
		return 1;
	return 0;
}

static U8 StatusResetFunc249(void)
{
	if((P_WindSpeedSensorSelect == 0) && V_WindSpeedSensor1Status && V_WindSpeedSensor2Status)
		return 0;
	if((P_WindSpeedSensorSelect == 1) && V_WindSpeedSensor1Status)
		return 0;
	if((P_WindSpeedSensorSelect == 2) && V_WindSpeedSensor2Status)
		return 0;
	return 1;
}

static U8 StatusSetFunc250(void)
{
	if(V_WindSpeed10Min > P_WindSpeedMaxON)
		return 1;
	return 0;
}

static U8 StatusResetFunc250(void)
{
	if(V_WindSpeed10Min < P_WindSpeedMaxOFF)
		return 1;
	return 0;
}

static U8 StatusSetFunc251(void)
{
	if(V_WindSpeed3Sec > P_WindSpeedMaxMaxON)
		return 1;
	return 0;
}

static U8 StatusResetFunc251(void)
{
	if(V_WindSpeed3Sec < P_WindSpeedMaxMaxOFF)
		return 1;
	return 0;
}
//-----------------------------------------------------------------------
// DRIVER FUNCTION         DRIVER FUNCTION         DRIVER FUNCTION
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// INIT                   INIT                     INIT
//-----------------------------------------------------------------------

struct  U32Buffer WindSpeedAverBuf;

static void WindSpeedAverageInit(void)
{
   ClearU32Buffer(&WindSpeedAverBuf);
}

static void LoadParameters()
{
	OS_VarDB_ReadVariableByName("P_WIS_SpeedOffset", &P_WIS_SpeedOffset, sizeof(P_WIS_SpeedOffset), NULL);
	OS_VarDB_ReadVariableByName("P_WIS_OffsetPeakSpeed", &P_WIS_OffsetPeakSpeed, sizeof(P_WIS_OffsetPeakSpeed), NULL);
	OS_VarDB_ReadVariableByName("P_WIS_OffsetMaxSpeed", &P_WIS_OffsetMaxSpeed, sizeof(P_WIS_OffsetMaxSpeed), NULL);
	OS_VarDB_ReadVariableByName("P_WIS_SpeedVariationRateUp", &P_WIS_SpeedVariationRateUp, sizeof(P_WIS_SpeedVariationRateUp), NULL);
	OS_VarDB_ReadVariableByName("P_WIS_SpeedVariationRateDown", &P_WIS_SpeedVariationRateDown, sizeof(P_WIS_SpeedVariationRateDown), NULL);
	
	
	// calculate offset gain values
	if(P_WIS_OffsetPeakSpeed != 0)	// prevent dividing by zero
	{
		OffsetGain1 = (F32)P_WIS_SpeedOffset / P_WIS_OffsetPeakSpeed;
	}
	else
	{
		OffsetGain1 = 0;
	}
	if( (P_WIS_OffsetMaxSpeed - P_WIS_OffsetPeakSpeed) != 0)	// prevent dividing by zero
	{
		OffsetGain2 = (F32)P_WIS_SpeedOffset / (P_WIS_OffsetMaxSpeed - P_WIS_OffsetPeakSpeed);
	}
	else
	{
		OffsetGain2 = 0;
	}
	
	RateLim_Set_RateUp(SpeedVariation_RateLim, P_WIS_SpeedVariationRateUp);
	RateLim_Set_RateDown(SpeedVariation_RateLim, P_WIS_SpeedVariationRateDown);
}

static STATUS Initialize()
{	
	STATUS LocalStatus = 0;
   
   #if defined DLL_SIMU
   LocalStatus = OS_VarDB_GetVariableID("DLL_IN_HubWindSpeed", &DLL_IN_HubWindSpeed_ID);
   if (LocalStatus != 0)
   {
      return LocalStatus;
   }
   #endif
   
    WindSpeedMax_RateLim = RateLim_New(400/*RateUp*/, 10/*RateDown*/, 1000/*TimeBase*/, WIS_TASK_SCANTIME/*TimeStep*/);
	WindSpeedMin_RateLim = RateLim_New(10/*RateUp*/, 400/*RateDown*/, 1000/*TimeBase*/, WIS_TASK_SCANTIME/*TimeStep*/);
	SpeedVariation_RateLim = RateLim_New(1/*RateUp*/, 1/*RateDown*/, 1000/*TimeBase*/, WIS_TASK_SCANTIME/*TimeStep*/);
	
	WindSpeedAverageInit();
	LoadParameters();
	
	return OS_SUCCESS;
}

//-----------------------------------------------------------------------
// CONTROL                CONTROL                 CONTROL
//-----------------------------------------------------------------------

static S16 Get_Offset(U16 WindSpeed)
{
	U16 offset = 0;
	
	if(WindSpeed < P_WIS_OffsetPeakSpeed)
	{
		offset = (S16)(WindSpeed * OffsetGain1);
	}
	else if (WindSpeed < P_WIS_OffsetMaxSpeed)
	{
		offset = (S16)((P_WIS_OffsetMaxSpeed - WindSpeed) * OffsetGain2);
	}
	
	return offset;
}


static STATUS LocalCtrl(void)
{
	STATUS LocalStatus = 0;
	static S16 delayedStartTimer1 = 2000;
	static BOOL delayedStart1 = false;
   
   
   // reloading parameters from menu
	if (V_WIS_LoadParameters)
	{
		V_WIS_LoadParameters = false;
		OS_VarDB_UpdateVariableByName("V_WIS_LoadParameters", &V_WIS_LoadParameters, sizeof(V_WIS_LoadParameters));
		LoadParameters();
		InfoMessage("Parameters reloaded", 1);
	}
	

#if defined DLL_SIMU
   
   OS_VarDB_ReadVariable(DLL_IN_HubWindSpeed_ID, &DLL_IN_HubWindSpeed, sizeof(DLL_IN_HubWindSpeed), NULL);
   V_WindSpeed = DLL_IN_HubWindSpeed * 100;
   
#else
   
   // Wind Speed Sensor Selector
	switch(P_WindSpeedSensorSelect)
	{
		case 0: //AUTO
		{
			if(!V_WindSpeedSensor1Status && !V_WindSpeedSensor2Status)
			{
				strcpy(V_WindSpeedSensorsActive,"All" );
				//V_WindSpeed = (V_WindSpeedSensor1 + V_WindSpeedSensor2) / 2;

				if(V_WindSpeedSensor1 > V_WindSpeedSensor2)
				{
					V_WindSpeed = V_WindSpeedSensor1;
					V_WindSpeedRef = V_WindSpeedSensor1;
				}
				else
				{
					V_WindSpeed = V_WindSpeedSensor2;
					V_WindSpeedRef = V_WindSpeedSensor2;
				}
			}
			else if(!V_WindSpeedSensor1Status && V_WindSpeedSensor2Status)
			{
				strcpy(V_WindSpeedSensorsActive,"Sensor 1" );
				V_WindSpeed = V_WindSpeedSensor1;
				V_WindSpeedRef = V_WindSpeedSensor1;
			}
			else if(V_WindSpeedSensor1Status && !V_WindSpeedSensor2Status)
			{
				strcpy(V_WindSpeedSensorsActive,"Sensor 2" );
				V_WindSpeed = V_WindSpeedSensor2;
				V_WindSpeedRef = V_WindSpeedSensor2;
			}
			else
			{
				strcpy(V_WindSpeedSensorsActive,"None" );
				V_WindSpeed = 0;
				V_WindSpeedRef = 0;
			}
			break;
		}
		case 1: //Sensor 1 selected manually
		{
			if(!V_WindSpeedSensor1Status) //No Errors in sensor 1
			{
				strcpy(V_WindSpeedSensorsActive,"Sensor 1" );
				V_WindSpeed = V_WindSpeedSensor1;
				V_WindSpeedRef = V_WindSpeedSensor1;
			}
			else
			{
				strcpy(V_WindSpeedSensorsActive,"None" );
				V_WindSpeed = 0;
				V_WindSpeedRef = 0;
			}
			break;
		}
		case 2: //Sensor 2 selected manually
		{
			if(!V_WindSpeedSensor2Status)
			{
				strcpy(V_WindSpeedSensorsActive,"Sensor 2" );
				V_WindSpeed = V_WindSpeedSensor2;
				V_WindSpeedRef = V_WindSpeedSensor2;
			}
			else
			{
				strcpy(V_WindSpeedSensorsActive,"None" );
				V_WindSpeed = 0;
				V_WindSpeedRef = 0;
			}
			break;
		}
		default:
		{
			break;
		}
	}

	//Sensor status text update
	if(!V_WindSpeedSensor1Status)
		strcpy(V_WSSensor1StatusText,"Ok" );
	else
		strcpy(V_WSSensor1StatusText,"Error" );

	if(!V_WindSpeedSensor2Status)
		strcpy(V_WSSensor2StatusText,"Ok" );
	else
		strcpy(V_WSSensor2StatusText,"Error" );
      
   // Add wind speed offset
	V_WindSpeed += Get_Offset(V_WindSpeed);
   
#endif
	
	
	
#if defined(WIS_DEBUG) || defined(INCLUDE_DEBUG)
   V_WindSpeed = V_WIS_WindSpeed_Debug;   //DEBUG
#endif
	
	
	LocalStatus = UpdateU32Buffer(&WindSpeedAverBuf , V_WindSpeed);
	STATUS_LINE_VAR_RETURN_CONST(LocalStatus, ERR_3);
	V_WindSpeed1Sec = WindSpeed1s();
  	V_WindSpeed3Sec = WindSpeed3s();
	V_WindSpeed30Sec = WindSpeed30s();
	V_WindSpeed10Min = WindSpeed10m();
	
	
	//**********************************************************************************
	//**********************************************************************************
	// CONTINUE PROGRAM BEYOND THIS POINT ONLY WHEN START DELAY HAS PASSED
	//**********************************************************************************
	//**********************************************************************************
	if (!delayedStart1)
	{
	   	delayedStartTimer1 -= WIS_TASK_SCANTIME;
		if (delayedStartTimer1 > 0) return OS_SUCCESS;
		
		delayedStart1 = true;
		// reset rate limiter structs to have correct values after reboot and not to start from 0
		RateLim_Reset(WindSpeedMax_RateLim, V_WindSpeed/*Output*/);
		RateLim_Reset(WindSpeedMin_RateLim, V_WindSpeed/*Output*/);
	}
	//**********************************************************************************
	//**********************************************************************************
	
	// Get max wind speed value
	V_WIS_WindSpeedMax = RateLim_Control(WindSpeedMax_RateLim, V_WindSpeed3Sec);
	// Get min wind speed value
	V_WIS_WindSpeedMin = RateLim_Control(WindSpeedMin_RateLim, V_WindSpeed3Sec);
	// Get wind speed change value
	if (V_WIS_WindSpeedMax > V_WIS_WindSpeedMin && V_WIS_WindSpeedMin > 0)	// make sure it does not create negative value
	{
	   U16 speedChange = V_WIS_WindSpeedMax - V_WIS_WindSpeedMin;
	   V_WIS_SpeedVariationPct = (U16)(((U32)speedChange * 1000) / (V_WIS_WindSpeedMin + (speedChange / 2)));
	}
	else
	{
	   V_WIS_SpeedVariationPct = 0;
	}
	
	// rate limiter for wind speed variation value
	V_WIS_SpeedVariationPct = RateLim_Control(SpeedVariation_RateLim, V_WIS_SpeedVariationPct);

   return LocalStatus;
}

//-----------------------------------------------------------------------
// MAIN CALL             MAIN CALL               MAIN CALL
//-----------------------------------------------------------------------

STATUS WindSpeed(U8 ModuleState, OS_MEMORY_POOL *MemPool, U32 *Arg3)
{
   STATUS LocalStatus = 0;

   
   if(ModuleState == APP_INIT1)
   {
      LocalStatus = OS_ValidateAPI(API_VERSION_MAJOR,
                                   API_VERSION_MINOR,
                                   OS_LinkTime,
                                   ReleaseTag,
                                   __MODULE__
                                   );
      if ( OS_SUCCESS != LocalStatus )
      {
         return LocalStatus;
      }
   }
#ifdef READ_VARS
   // Read inputdata
   LocalStatus = InputReferenceRoutine(ModuleState);
   STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif
#ifdef COMMON_VDB_READ
   LocalStatus = ReadVdbWindow(ModuleState);
   STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif
   switch(ModuleState)
   {
      case APP_RUN :
      {
         #ifdef FUNCTION_BLOCKS_PRE_LOCAL_CONTROL
            LocalStatus = FunctionBlocksPreLocalCtrl( Interval );
            STATUS_LINE_VAR_RETURN_VALUE( LocalStatus );
         #endif

         LocalStatus = LocalCtrl();
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
        
         #ifdef FUNCTION_BLOCKS_POST_LOCAL_CONTROL
            LocalStatus = FunctionBlocksPostLocalCtrl( Interval );
            STATUS_LINE_VAR_RETURN_VALUE( LocalStatus );
         #endif

#ifdef WRITE_VARS
         // Write Outputdata
         LocalStatus = OutputReferenceRoutine(ModuleState);
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif

#ifdef COMMON_VDB_WRITE
         LocalStatus = WriteVdbWindow(ModuleState);
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif
         break;
      }
      case APP_INIT1 :
      {
         Init_Structures_From_Conf_File();
                 

#ifdef CREATE_MENU
         LocalStatus = WindSpeedMenuAppInit(ModuleState, MemPool);
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)

#ifdef MULTIPLEXIBLE_MENU
         LocalStatus = MenuArraysAppInit(ModuleState, MemPool);
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif
#endif

#ifdef CREATE_VARDB_VARS
         LocalStatus = CreateVarDbVars();
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif

#ifdef CREATE_VARDB_ARRAY_VARS
         LocalStatus = CreateVdbArrays(MemPool);
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif

#ifdef CREATE_IO_VARS
         LocalStatus = CreateIOVars();
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif
         break;
      }
      case APP_INIT2 :
      {
#ifdef CREATE_MENU
#ifdef MULTIPLEXIBLE_MENU
         LocalStatus = MenuArraysAppInit(ModuleState, MemPool);
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif
#endif

#ifdef CREATE_ALIASES
         size_t ErrorEntry = 0;
         LocalStatus = OS_VarDB_CreateAliases(AliasVars, sizeof(AliasVars)/sizeof(AliasVars[0]), &ErrorEntry);
         STATUS_LINE_VAR_RETURN_CONST(LocalStatus, ErrorEntry)
#endif

#ifdef VERIFY_ARRAY
        LocalStatus = VerifyArray();
        STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif

#ifdef VERIFY_VARIABLES
         LocalStatus = LocalIoCheck();
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif

#ifdef CREATE_BUTTONS
         LocalStatus = CreateButtons();
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif
         break;
      }
      case APP_INIT3 :
      {
#ifdef CREATE_SUMMATIONS
         LocalStatus = CreateSummations();
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif

#ifdef WRITE_VARS
         LocalStatus = InitOutputVars();
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif

#ifdef CREATE_STATUS_CODES
         LocalStatus = LocalStatusCodeInit();
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif

#ifdef CREATE_IO_VARS
        WindSpeedSetLockValues();
#endif
         break;
      }
      case APP_INIT4 :
      {
#ifdef CREATE_MENU
         LocalStatus = WindSpeedMenuAppInit(ModuleState, MemPool);
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)

#ifdef MULTIPLEXIBLE_MENU
         LocalStatus = MenuArraysAppInit(ModuleState, MemPool);
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif
#endif
         break;
      }
      case APP_INIT5 :
      {
#ifdef VALIDATE_HASH
         LocalStatus = ValidateHash(WindSpeed_copyright, MODULE_NAME, WindSpeed_initialValues);
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
#endif

         #ifdef INIT_FUNCTION_BLOCKS
            LocalStatus = FunctionBlocksInit( Interval );
            STATUS_LINE_VAR_RETURN_VALUE( LocalStatus );
         #endif

      LocalStatus = Initialize();
      STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         break;
      }
      default :
      {
         break;
      }
   }
   return OS_SUCCESS;
}
//-----------------------------------------------------------------------
