//*****************************PEPTOOL Header Start******************************
//                                                                               
//                         Copyright © 2015 Mita-Teknik.                         
//This software may only be used with WP4x00 Controllers delivered by Mita-Teknik
//                                                                               
//*******************************************************************************
//                                                                               
// $PEPTOOL version:9.0$                                                         
// $PEPTOOL file version:101$                                                    
//                                                                               
//*******************************************************************************
//                                                                               
// $Date: 2015/03/13 17:31:22 $                                                  
// $Author: MITA\ihn $                                                           
// $RCSfile: WindSpeed_Conf.c,v $                                                
// $Revision: 1.8 $                                                              
//                                                                               
//******************************PEPTOOL Header End*******************************

//***********************************************************************
// OS header files
#include <os_main.h>
// App header files
#include <InitIo.h>

#define AUTOGENERATED_PART

#include <Turbdef.h>

//-----------------------------------------------------------------------
// AUTOGENERATED START     AUTOGENERATED START     AUTOGENERATED START
//-----------------------------------------------------------------------
char WindSpeed_Conf_copyright[] =
{
   67, 111, 112, 121, 114, 105, 103, 104, 116, 32, 63, 32, 50, 48, 49, 53,
   32, 77, 105, 116, 97, 45, 84, 101, 107, 110, 105, 107, 46, 13, 10, 84,
   104, 105, 115, 32, 115, 111, 102, 116, 119, 97, 114, 101, 32, 109, 97, 121,
   32, 111, 110, 108, 121, 32, 98, 101, 32, 117, 115, 101, 100, 32, 119, 105,
   116, 104, 32, 87, 80, 52, 120, 48, 48, 32, 67, 111, 110, 116, 114, 111,
   108, 108, 101, 114, 115, 32, 100, 101, 108, 105, 118, 101, 114, 101, 100, 32,
   98, 121, 32, 77, 105, 116, 97, 45, 84, 101, 107, 110, 105, 107, 0
};
//-----------------------------------------------------------------------
// MODIFIABLE                  MODIFIABLE               MODIFIABLE
//-----------------------------------------------------------------------
const char WindSpeedAppGroupName[] = "G_Wind";
const char WindSpeedAppMenuName[] = "M_Wind";
const U8 WindSpeed_Conf_Menu_Main_Read = 30;
const U8 WindSpeed_Conf_Menu_Main_Write = 90;
const U8 WindSpeed_Conf_Menu_Mita_Read = 190;
const U8 WindSpeed_Conf_Menu_Mita_Write = 190;
const U8 WindSpeed_Conf_Menu_Parameter_Read = 30;
const U8 WindSpeed_Conf_Menu_Parameter_Write = 80;
const U8 WindSpeed_Conf_Menu_Service_Read = 80;
const U8 WindSpeed_Conf_Menu_Service_Write = 80;
const U8 WindSpeed_Conf_Menu_Status_Read = 30;
const U16 WindSpeed_Conf_P_WindSpeedMaxMaxOFF_InitValueExt = 2500;
const U16 WindSpeed_Conf_P_WindSpeedMaxMaxOFF_MaximumValueExt = 4000;
const U16 WindSpeed_Conf_P_WindSpeedMaxMaxOFF_MinimumValueExt = 0;
const U16 WindSpeed_Conf_P_WindSpeedMaxMaxON_InitValueExt = 3000;
const U16 WindSpeed_Conf_P_WindSpeedMaxMaxON_MaximumValueExt = 4000;
const U16 WindSpeed_Conf_P_WindSpeedMaxMaxON_MinimumValueExt = 0;
const U16 WindSpeed_Conf_P_WindSpeedMaxOFF_InitValueExt = 2300;
const U16 WindSpeed_Conf_P_WindSpeedMaxOFF_MaximumValueExt = 4000;
const U16 WindSpeed_Conf_P_WindSpeedMaxOFF_MinimumValueExt = 0;
const U16 WindSpeed_Conf_P_WindSpeedMaxON_InitValueExt = 2500;
const U16 WindSpeed_Conf_P_WindSpeedMaxON_MaximumValueExt = 4000;
const U16 WindSpeed_Conf_P_WindSpeedMaxON_MinimumValueExt = 0;
const U8 WindSpeed_Conf_SC_249_AlarmProgramConst = 0;
const U8 WindSpeed_Conf_SC_249_AvailabilityGroupConst = 21;
const U8 WindSpeed_Conf_SC_249_BrakeProgramConst = 50;
const U8 WindSpeed_Conf_SC_249_EnableStatusCodeConst = 1;
const U32 WindSpeed_Conf_SC_249_ResetDelayConst = 0;
const U32 WindSpeed_Conf_SC_249_SetDelayConst = 0;
const U8 WindSpeed_Conf_SC_249_YawProgramConst = 0;
const U8 WindSpeed_Conf_SC_250_AlarmProgramConst = 0;
const U8 WindSpeed_Conf_SC_250_AvailabilityGroupConst = 29;
const U8 WindSpeed_Conf_SC_250_BrakeProgramConst = 50;
const U8 WindSpeed_Conf_SC_250_EnableStatusCodeConst = 1;
const U32 WindSpeed_Conf_SC_250_ResetDelayConst = 0;
const U32 WindSpeed_Conf_SC_250_SetDelayConst = 0;
const U8 WindSpeed_Conf_SC_250_YawProgramConst = 0;
const U8 WindSpeed_Conf_SC_251_AlarmProgramConst = 0;
const U8 WindSpeed_Conf_SC_251_AvailabilityGroupConst = 29;
const U8 WindSpeed_Conf_SC_251_BrakeProgramConst = 50;
const U8 WindSpeed_Conf_SC_251_EnableStatusCodeConst = 1;
const U32 WindSpeed_Conf_SC_251_ResetDelayConst = 300000;
const U32 WindSpeed_Conf_SC_251_SetDelayConst = 0;
const U8 WindSpeed_Conf_SC_251_YawProgramConst = 0;
const U8 WindSpeed_Conf_SC_Activate_Counter_Backup_Read = 30;
const U8 WindSpeed_Conf_SC_Activate_Counter_Backup_Write = 200;
const U8 WindSpeed_Conf_SC_Alarm_Program_Read = 30;
const U8 WindSpeed_Conf_SC_Availability_Group_Read = 30;
const U8 WindSpeed_Conf_SC_Availability_Group_Write = 200;
const U8 WindSpeed_Conf_SC_Brake_Program_Read = 30;
const U8 WindSpeed_Conf_SC_Enable_Read = 30;
const U8 WindSpeed_Conf_SC_Enable_Write = 100;
const U8 WindSpeed_Conf_SC_Repeat_Code_Read = 30;
const U8 WindSpeed_Conf_SC_Repeat_Period_Read = 30;
const U8 WindSpeed_Conf_SC_Repeat_Times_Read = 30;
const U8 WindSpeed_Conf_SC_Reset_Delay_Read = 30;
const U8 WindSpeed_Conf_SC_Reset_Delay_Write = 190;
const U8 WindSpeed_Conf_SC_Reset_Status_Code_Write = 80;
const U8 WindSpeed_Conf_SC_Set_Delay_Read = 30;
const U8 WindSpeed_Conf_SC_Set_Delay_Write = 200;
const U8 WindSpeed_Conf_SC_TimeOut_Code_Read = 30;
const U8 WindSpeed_Conf_SC_TimeOut_Period_Read = 30;
const U8 WindSpeed_Conf_SC_Update_Interval_Read = 30;
const U8 WindSpeed_Conf_SC_Yaw_Program_Read = 30;
const U8 WindSpeed_Conf_Summation_Read = 30;
const U8 WindSpeed_Conf_Summation_Write = 99;

//-----------------------------------------------------------------------
// IO VARIABLES                IO VARIABLES                IO VARIABLES
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// AUTOGENERATED END        AUTOGENERATED END        AUTOGENERATED END
//-----------------------------------------------------------------------

#undef AUTOGENERATED_PART
