//*****************************PEPTOOL Header Start******************************
//                                                                               
//                         Copyright © 2015 Mita-Teknik.                         
//This software may only be used with WP4x00 Controllers delivered by Mita-Teknik
//                                                                               
//*******************************************************************************
//                                                                               
// $PEPTOOL version:9.0$                                                         
// $PEPTOOL file version:106$                                                    
//                                                                               
//*******************************************************************************
//                                                                               
// $Date: 2012/05/21 13:37:45 $                                                  
// $Author: MITA\ipi $                                                           
// $RCSfile: WindDirection.c,v $                                                 
// $Revision: 1.5 $                                                              
//                                                                               
//******************************PEPTOOL Header End*******************************

//***********************************************************************
// OS header files
#include <os_main.h>
// AppLib header files
#include <lib_main.h>
// App header files
#include <turbdef.h>
#include <VarMacros.h>
#include <PI_Regulator_2.h>
#include <Rate_Limiter.h>
#include <Aver_Bearing.h>
// Object header file
#include <WindDirection.h>

#define AUTOGENERATED_PART
//{
//-----------------------------------------------------------------------
// AUTOGENERATED START     AUTOGENERATED START     AUTOGENERATED START
//-----------------------------------------------------------------------

#define VALIDATE_HASH
char WindDirection_copyright[] =
{
   67, 111, 112, 121, 114, 105, 103, 104, 116, 32, 63, 32, 50, 48, 49, 53,
   32, 77, 105, 116, 97, 45, 84, 101, 107, 110, 105, 107, 46, 13, 10, 84,
   104, 105, 115, 32, 115, 111, 102, 116, 119, 97, 114, 101, 32, 109, 97, 121,
   32, 111, 110, 108, 121, 32, 98, 101, 32, 117, 115, 101, 100, 32, 119, 105,
   116, 104, 32, 87, 80, 52, 120, 48, 48, 32, 67, 111, 110, 116, 114, 111,
   108, 108, 101, 114, 115, 32, 100, 101, 108, 105, 118, 101, 114, 101, 100, 32,
   98, 121, 32, 77, 105, 116, 97, 45, 84, 101, 107, 110, 105, 107, 0
};

#define MODULE_NAME "Wind DirectionA"

//-----------------------------------------------------------------------
// ALLOCATE MEMORY FOR STRINGS IN VARDB
//-----------------------------------------------------------------------

static char A_V_WindDirectionSensorsActive[31]  = "12345678901234567890123456789";
static char A_V_WDSensor1StatusText[31]  = "12345678901234567890123456789";
static char A_V_WDSensor2StatusText[31]  = "12345678901234567890123456789";

//-----------------------------------------------------------------------
// DEFINE LOCAL VARIABLES DEFINE LOCAL VARIABLES DEFINE LOCAL VARIABLES
//-----------------------------------------------------------------------

static struct os_db_local LocalVars[] =
{
   VAR_ELEMENT_LOCAL("V_WindDirection",                          TYPE_U16,     PASSWORD_LEVEL_ADMINISTRATOR,      PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    10,      UNIT_DEGREE,        1,   0,               0,               3599,            NULL,  TOTLOG_ENABLE | FIVEMINLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_WindDirection1Sec",                      TYPE_U16,     PASSWORD_LEVEL_ADMINISTRATOR,      PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    10,      UNIT_DEGREE,        1,   0,               0,               3599,            NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_WindDirection3Sec",                      TYPE_U16,     PASSWORD_LEVEL_ADMINISTRATOR,      PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    10,      UNIT_DEGREE,        1,   0,               0,               3599,            NULL,  FIVEMINLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_WindDirection30Sec",                     TYPE_U16,     PASSWORD_LEVEL_ADMINISTRATOR,      PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    10,      UNIT_DEGREE,        1,   0,               0,               3599,            NULL,  FIVEMINLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_WindDirection10Min",                     TYPE_U16,     PASSWORD_LEVEL_ADMINISTRATOR,      PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    10,      UNIT_DEGREE,        1,   0,               0,               3599,            NULL,  FIVEMINLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_WindDirectionRelative",                  TYPE_S16,     PASSWORD_LEVEL_ADMINISTRATOR,      PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    10,      UNIT_DEGREE,        1,   0,               -1799,           1800,            NULL,  TOTLOG_ENABLE | FIVEMINLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_WindDirectionRelative3Sec",              TYPE_S16,     PASSWORD_LEVEL_ADMINISTRATOR,      PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    10,      UNIT_DEGREE,        1,   0,               -1799,           1800,            NULL,  FIVEMINLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_WindDirectionRelative30Sec",             TYPE_S16,     PASSWORD_LEVEL_ADMINISTRATOR,      PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    10,      UNIT_DEGREE,        1,   0,               -1799,           1800,            NULL,  FIVEMINLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_WindDirectionRelative10Min",             TYPE_S16,     PASSWORD_LEVEL_ADMINISTRATOR,      PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    10,      UNIT_DEGREE,        1,   0,               -1799,           1800,            NULL,  FIVEMINLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_WindDirectionSensorsActive",             TYPE_STRING + sizeof(A_V_WindDirectionSensorsActive) - 1,  PASSWORD_LEVEL_ADMINISTRATOR,      PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   A_V_WindDirectionSensorsActive, 0,                0,                NULL,  NOLOG_ENABLE  ),
   VAR_ELEMENT_LOCAL("V_WDSensor1StatusText",                    TYPE_STRING + sizeof(A_V_WDSensor1StatusText) - 1,  PASSWORD_LEVEL_ADMINISTRATOR,      PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   A_V_WDSensor1StatusText, 0,                0,                NULL,  NOLOG_ENABLE  ),
   VAR_ELEMENT_LOCAL("V_WDSensor2StatusText",                    TYPE_STRING + sizeof(A_V_WDSensor2StatusText) - 1,  PASSWORD_LEVEL_ADMINISTRATOR,      PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   A_V_WDSensor2StatusText, 0,                0,                NULL,  NOLOG_ENABLE  ),
   VAR_ELEMENT_LOCAL("V_WindDirectionRef",                       TYPE_S16,     PASSWORD_LEVEL_ADMINISTRATOR,      PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    10,      UNIT_DEGREE,        1,   0,               -1799,           1800,            NULL,  TOTLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_WindDirectionSensor",                    TYPE_U16,     PASSWORD_LEVEL_ADMINISTRATOR,      PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    10,      UNIT_DEGREE,        1,   0,               0,               3599,            NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_WindDirectionSensor1Sec",                TYPE_U16,     PASSWORD_LEVEL_ADMINISTRATOR,      PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    10,      UNIT_DEGREE,        1,   0,               0,               3599,            NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_WindDirectionSensor3Sec",                TYPE_U16,     PASSWORD_LEVEL_ADMINISTRATOR,      PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    10,      UNIT_DEGREE,        1,   0,               0,               3599,            NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_WindDirectionSensor30Sec",               TYPE_U16,     PASSWORD_LEVEL_ADMINISTRATOR,      PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    10,      UNIT_DEGREE,        1,   0,               0,               3599,            NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_WindDirectionSensor10Min",               TYPE_U16,     PASSWORD_LEVEL_ADMINISTRATOR,      PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    10,      UNIT_DEGREE,        1,   0,               0,               3599,            NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_WID_LoadParameters",                     TYPE_U8,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_NONE,   0,       UNIT_NONE,          0,   0,               0,               1,               NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_WID_WindDirectionRef",                   TYPE_S16,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    10,      UNIT_DEGREE,        1,   0,               S16_MIN,         S16_MAX,         NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_WID_WindLeft",                           TYPE_S16,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    10,      UNIT_DEGREE,        1,   0,               S16_MIN,         S16_MAX,         NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_WID_WindRight",                          TYPE_S16,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    10,      UNIT_DEGREE,        1,   0,               S16_MIN,         S16_MAX,         NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_WID_WindDirectionSensorTest",            TYPE_U16,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    10,      UNIT_DEGREE,        1,   0,               U16_MIN,         U16_MAX,         NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_WID_DirVariation",                       TYPE_U16,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    10,      UNIT_DEGREE,        1,   0,               U16_MIN,         U16_MAX,         NULL,  NOLOG_ENABLE),
};

//-----------------------------------------------------------------------
// DEFINE PARAMETERS        DEFINE PARAMETERS        DEFINE PARAMETERS
//-----------------------------------------------------------------------

static struct os_db_parameter ParameterVars[] =
{
   VAR_ELEMENT_PARAMETER("P_WindDirectionSensorSelect",              TYPE_U8,      PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_SERVICE,            SCALE_NONE,   0,       UNIT_NONE,          0,   0,               0,               2,               NULL  ),
   VAR_ELEMENT_PARAMETER_F32("P_WID_PIkpInc",                                     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,                           UNIT_NONE,          0,   0.0F,            F32_MIN,         F32_MAX,         NULL  ),
   VAR_ELEMENT_PARAMETER_F32("P_WID_PIkpDec",                                     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,                           UNIT_NONE,          0,   0.0F,            F32_MIN,         F32_MAX,         NULL  ),
   VAR_ELEMENT_PARAMETER_F32("P_WID_PIkiInc",                                     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,                           UNIT_NONE,          0,   0.008F,          F32_MIN,         F32_MAX,         NULL  ),
   VAR_ELEMENT_PARAMETER_F32("P_WID_PIkiDec",                                     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,                           UNIT_NONE,          0,   0.0004F,         F32_MIN,         F32_MAX,         NULL  ),
   VAR_ELEMENT_PARAMETER("P_WID_DirVariationRateUp",                 TYPE_U16,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    10,      UNIT_DEGREESPSEC,   1,   1,               0,               1000,            NULL  ),
   VAR_ELEMENT_PARAMETER("P_WID_DirVariationRateDown",               TYPE_U16,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_ADMINISTRATOR,      SCALE_DIV,    10,      UNIT_DEGREESPSEC,   1,   1,               0,               1000,            NULL  ),
};

//-----------------------------------------------------------------------
// DEFINE BACKUPS            DEFINE BACKUPS            DEFINE BACKUPS
//-----------------------------------------------------------------------

//----------------------------------------------------------------------------------
// DEFINE VAR ARRAYS            DEFINE VAR ARRAYS            DEFINE VAR ARRAYS
//----------------------------------------------------------------------------------
char WindDirection_initialValues[] =
{
   132, 205, 193, 19, 191, 199, 108, 230, 45, 63, 165, 9, 189, 45, 223, 208,
   222, 143, 56, 175, 21, 195, 202, 192, 176, 159, 166, 96, 75, 163, 145, 181,
   0
};

//-----------------------------------------------------------------------
// CREATE DATABASE VARS   CREATE DATABASE VARS   CREATE DATABASE VARS
//-----------------------------------------------------------------------

static STATUS CreateVarDbVars(void)
{
   STATUS Status;
   size_t ErrorEntry;

   Status = OS_VarDB_CreateLocals(LocalVars, sizeof(LocalVars)/sizeof(LocalVars[0]), &ErrorEntry, AppLocalParameterPosition());
   if (Status != 0)
   {
      AppSystemLog(ERR_7, MODULE_NAME"CrVL: %d,%d", Status, ErrorEntry);
      return ERR_7;
   }

   Status = OS_VarDB_CreateParameters(ParameterVars, sizeof(ParameterVars)/sizeof(ParameterVars[0]), &ErrorEntry, AppExportParameterPosition());
   if (Status != 0)
   {
      AppSystemLog(ERR_7, MODULE_NAME"CrVXP: %d,%d", Status, ErrorEntry);
      return ERR_7;
   }

   return OS_SUCCESS;
}

#define CREATE_VARDB_VARS

//-----------------------------------------------------------------------
// CREATE IO VARIABLES     CREATE IO VARIABLES     CREATE IO VARIABLES
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// ALIASES                       ALIASES                       ALIASES
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// INPUT                          INPUT                          INPUT
//-----------------------------------------------------------------------

// Create local variable
#define MODUL_INPUTS
static U8 P_WindDirectionSensorSelect = 0;
static U16 V_NacelleDirection = 0;
static U16 V_WindDirectionSensor1 = 0;
static U16 V_WindDirectionSensor2 = 0;
static U16 V_WindDirectionSensor1Status = 0;
static U16 V_WindDirectionSensor2Status = 0;
static U8 V_WID_LoadParameters = 0;
static U16 V_WID_WindDirectionSensorTest = 0;

//-----------------------------------------------------------------------
static struct ModulInOut ModulInputs[] =
{
   {"P_WindDirectionSensorSelect",              &P_WindDirectionSensorSelect,              sizeof(P_WindDirectionSensorSelect),              },
   {"V_NacelleDirection",                       &V_NacelleDirection,                       sizeof(V_NacelleDirection),                       },
   {"V_WindDirectionSensor1",                   &V_WindDirectionSensor1,                   sizeof(V_WindDirectionSensor1),                   },
   {"V_WindDirectionSensor2",                   &V_WindDirectionSensor2,                   sizeof(V_WindDirectionSensor2),                   },
   {"V_WindDirectionSensor1Status",             &V_WindDirectionSensor1Status,             sizeof(V_WindDirectionSensor1Status),             },
   {"V_WindDirectionSensor2Status",             &V_WindDirectionSensor2Status,             sizeof(V_WindDirectionSensor2Status),             },
   {"V_WID_LoadParameters",                     &V_WID_LoadParameters,                     sizeof(V_WID_LoadParameters),                     },
   {"V_WID_WindDirectionSensorTest",            &V_WID_WindDirectionSensorTest,            sizeof(V_WID_WindDirectionSensorTest),            },
};

//-----------------------------------------------------------------------
// Check variable type
static STATUS VarsReadReturnStatus;
static type_t ReadVarType = TYPE_NONE;
static void VarsReadTypeCheck(void)
{
   (void)VarsReadReturnStatus;
   (void)ReadVarType;
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[0].Name,                      ModulInputs[0].Id)
   VERIFY_INPUT_REF_ID(U16,       ModulInputs[1].Name,                      ModulInputs[1].Id)
   VERIFY_INPUT_REF_ID(U16,       ModulInputs[2].Name,                      ModulInputs[2].Id)
   VERIFY_INPUT_REF_ID(U16,       ModulInputs[3].Name,                      ModulInputs[3].Id)
   VERIFY_INPUT_REF_ID(U16,       ModulInputs[4].Name,                      ModulInputs[4].Id)
   VERIFY_INPUT_REF_ID(U16,       ModulInputs[5].Name,                      ModulInputs[5].Id)
   VERIFY_INPUT_REF_ID(U8,        ModulInputs[6].Name,                      ModulInputs[6].Id)
   VERIFY_INPUT_REF_ID(U16,       ModulInputs[7].Name,                      ModulInputs[7].Id)
}

#undef MODUL_INPUTS
#define MODUL_INPUTS_SIZE (sizeof(ModulInputs)/sizeof(ModulInputs[0]))

//------------------------------------------------------------------------------------------
// READ/WRITE VARDB ARRAY      READ/WRITE VARDB ARRAY      READ/WRATE VARDB ARRAY
//------------------------------------------------------------------------------------------


//-----------------------------------------------------------------------
// PARAMETER                    PARAMETER                    PARAMETER
//-----------------------------------------------------------------------


//-----------------------------------------------------------------------
// READ VARS FROM VARDB    READ VARS FROM VARDB    READ VARS FROM VARDB
//-----------------------------------------------------------------------

static STATUS InputReferenceRoutine(U8 ModuleState)
{
   STATUS LocalStatus = 0;

   // Read input references
   if (ModuleState >= APP_INIT3)
   {
      // Check inputdata
      if (sizeof(ModulInputs) == 0)
      {
         AppSystemLog(ERR_4, MODULE_NAME"ModuleInputs = 0");
         return ERR_4;
      }
      // Read inputdata
      LocalStatus = OS_ReadVariables(ModulInputs, MODUL_INPUTS_SIZE);
      if (LocalStatus != 0)
      {
         AppSystemLog(ERR_4, MODULE_NAME"ReadVErr: element=%d elementpointer=0x%x", LocalStatus, &ModulInputs[LocalStatus]);
         return ERR_4;
      }
   }
   return 0;
}

#define READ_VARS

//-----------------------------------------------------------------------
// OUTPUT                         OUTPUT                         OUTPUT
//-----------------------------------------------------------------------

// Create local variable
#define MODUL_OUTPUTS
static S16 V_WindDirectionRef = 0;
static U16 V_WindDirection = 0;
static U16 V_WindDirection1Sec = 0;
static U16 V_WindDirection3Sec = 0;
static U16 V_WindDirection30Sec = 0;
static U16 V_WindDirection10Min = 0;
static S16 V_WindDirectionRelative = 0;
static S16 V_WindDirectionRelative3Sec = 0;
static U16 V_WindDirectionSensor30Sec = 0;
static S16 V_WindDirectionRelative10Min = 0;
static U16 V_WindDirectionSensor = 0;
static U16 V_WindDirectionSensor1Sec = 0;
static U16 V_WindDirectionSensor3Sec = 0;
static S16 V_WindDirectionRelative30Sec = 0;
static U16 V_WindDirectionSensor10Min = 0;
static S16 V_WID_WindDirectionRef = 0;
static S16 V_WID_WindLeft = 0;
static S16 V_WID_WindRight = 0;
static U16 V_WID_DirVariation = 0;
static char V_WindDirectionSensorsActive[31];
static char V_WDSensor1StatusText[31];
static char V_WDSensor2StatusText[31];


//-----------------------------------------------------------------------
static struct ModulInOut ModulOutputs[] =
{
   {"V_WindDirectionRef",                       &V_WindDirectionRef,                       sizeof(V_WindDirectionRef),                       },
   {"V_WindDirection",                          &V_WindDirection,                          sizeof(V_WindDirection),                          },
   {"V_WindDirection1Sec",                      &V_WindDirection1Sec,                      sizeof(V_WindDirection1Sec),                      },
   {"V_WindDirection3Sec",                      &V_WindDirection3Sec,                      sizeof(V_WindDirection3Sec),                      },
   {"V_WindDirection30Sec",                     &V_WindDirection30Sec,                     sizeof(V_WindDirection30Sec),                     },
   {"V_WindDirection10Min",                     &V_WindDirection10Min,                     sizeof(V_WindDirection10Min),                     },
   {"V_WindDirectionRelative",                  &V_WindDirectionRelative,                  sizeof(V_WindDirectionRelative),                  },
   {"V_WindDirectionRelative3Sec",              &V_WindDirectionRelative3Sec,              sizeof(V_WindDirectionRelative3Sec),              },
   {"V_WindDirectionSensor30Sec",               &V_WindDirectionSensor30Sec,               sizeof(V_WindDirectionSensor30Sec),               },
   {"V_WindDirectionRelative10Min",             &V_WindDirectionRelative10Min,             sizeof(V_WindDirectionRelative10Min),             },
   {"V_WindDirectionSensor",                    &V_WindDirectionSensor,                    sizeof(V_WindDirectionSensor),                    },
   {"V_WindDirectionSensor1Sec",                &V_WindDirectionSensor1Sec,                sizeof(V_WindDirectionSensor1Sec),                },
   {"V_WindDirectionSensor3Sec",                &V_WindDirectionSensor3Sec,                sizeof(V_WindDirectionSensor3Sec),                },
   {"V_WindDirectionRelative30Sec",             &V_WindDirectionRelative30Sec,             sizeof(V_WindDirectionRelative30Sec),             },
   {"V_WindDirectionSensor10Min",               &V_WindDirectionSensor10Min,               sizeof(V_WindDirectionSensor10Min),               },
   {"V_WindDirectionSensorsActive",             &V_WindDirectionSensorsActive,             sizeof(V_WindDirectionSensorsActive),             },
   {"V_WDSensor1StatusText",                    &V_WDSensor1StatusText,                    sizeof(V_WDSensor1StatusText),                    },
   {"V_WDSensor2StatusText",                    &V_WDSensor2StatusText,                    sizeof(V_WDSensor2StatusText),                    },
   {"V_WID_WindDirectionRef",                   &V_WID_WindDirectionRef,                   sizeof(V_WID_WindDirectionRef),                   },
   {"V_WID_WindLeft",                           &V_WID_WindLeft,                           sizeof(V_WID_WindLeft),                           },
   {"V_WID_WindRight",                          &V_WID_WindRight,                          sizeof(V_WID_WindRight),                          },
   {"V_WID_DirVariation",                       &V_WID_DirVariation,                       sizeof(V_WID_DirVariation),                       },
};

//-----------------------------------------------------------------------
// Check variable type
static STATUS VarsWriteReturnStatus;
static type_t WriteVarType = TYPE_NONE;
static void VarsWriteTypeCheck(void)
{
   (void)VarsWriteReturnStatus;
   (void)WriteVarType;
   VERIFY_OUTPUT_REF_ID(S16,       ModulOutputs[0].Name,                     ModulOutputs[0].Id,                       0)
   VERIFY_OUTPUT_REF_ID(U16,       ModulOutputs[1].Name,                     ModulOutputs[1].Id,                       0)
   VERIFY_OUTPUT_REF_ID(U16,       ModulOutputs[2].Name,                     ModulOutputs[2].Id,                       0)
   VERIFY_OUTPUT_REF_ID(U16,       ModulOutputs[3].Name,                     ModulOutputs[3].Id,                       0)
   VERIFY_OUTPUT_REF_ID(U16,       ModulOutputs[4].Name,                     ModulOutputs[4].Id,                       0)
   VERIFY_OUTPUT_REF_ID(U16,       ModulOutputs[5].Name,                     ModulOutputs[5].Id,                       0)
   VERIFY_OUTPUT_REF_ID(S16,       ModulOutputs[6].Name,                     ModulOutputs[6].Id,                       0)
   VERIFY_OUTPUT_REF_ID(S16,       ModulOutputs[7].Name,                     ModulOutputs[7].Id,                       0)
   VERIFY_OUTPUT_REF_ID(U16,       ModulOutputs[8].Name,                     ModulOutputs[8].Id,                       0)
   VERIFY_OUTPUT_REF_ID(S16,       ModulOutputs[9].Name,                     ModulOutputs[9].Id,                       0)
   VERIFY_OUTPUT_REF_ID(U16,       ModulOutputs[10].Name,                    ModulOutputs[10].Id,                      0)
   VERIFY_OUTPUT_REF_ID(U16,       ModulOutputs[11].Name,                    ModulOutputs[11].Id,                      0)
   VERIFY_OUTPUT_REF_ID(U16,       ModulOutputs[12].Name,                    ModulOutputs[12].Id,                      0)
   VERIFY_OUTPUT_REF_ID(S16,       ModulOutputs[13].Name,                    ModulOutputs[13].Id,                      0)
   VERIFY_OUTPUT_REF_ID(U16,       ModulOutputs[14].Name,                    ModulOutputs[14].Id,                      0)
   VERIFY_OUTPUT_STRING_REF_ID(STRING,     ModulOutputs[15].Name,                     ModulOutputs[15].Id, 0)
   VERIFY_OUTPUT_STRING_REF_ID(STRING,     ModulOutputs[16].Name,                     ModulOutputs[16].Id, 0)
   VERIFY_OUTPUT_STRING_REF_ID(STRING,     ModulOutputs[17].Name,                     ModulOutputs[17].Id, 0)
   VERIFY_OUTPUT_REF_ID(S16,       ModulOutputs[18].Name,                    ModulOutputs[18].Id,                      0)
   VERIFY_OUTPUT_REF_ID(S16,       ModulOutputs[19].Name,                    ModulOutputs[19].Id,                      0)
   VERIFY_OUTPUT_REF_ID(S16,       ModulOutputs[20].Name,                    ModulOutputs[20].Id,                      0)
   VERIFY_OUTPUT_REF_ID(U16,       ModulOutputs[21].Name,                    ModulOutputs[21].Id,                      0)
}

#undef MODUL_OUTPUTS
#define MODUL_OUTPUTS_SIZE (sizeof(ModulOutputs)/sizeof(ModulOutputs[0]))

//-----------------------------------------------------------------------
// WRITE VARS TO VARDB     WRITE VARS TO VARDB     WRITE VARS TO VARDB
//-----------------------------------------------------------------------

static STATUS InitOutputVars(void)
{
   STATUS LocalStatus;
   // Read outputdata
   LocalStatus = OS_ReadVariables(ModulOutputs, MODUL_OUTPUTS_SIZE);
   if (LocalStatus != 0)
   {
      AppSystemLog(ERR_4, MODULE_NAME"InitErr: element=%d elementpointer=0x%x", LocalStatus, &ModulOutputs[LocalStatus]);
      return ERR_4;
   }
   return OS_SUCCESS;
}
static STATUS OutputReferenceRoutine(U8 ModuleState)
{
   STATUS LocalStatus = 0;
   // Write Outputdata
   LocalStatus = OS_WriteVariablesConditional(ModulOutputs, MODUL_OUTPUTS_SIZE);
   if (LocalStatus != 0)
   {
      AppSystemLog(ERR_5, MODULE_NAME"WriteVErr: element=%d elementpointer=0x%x", LocalStatus, &ModulOutputs[LocalStatus]);
      return ERR_5;
   }
   return 0;
}

#define WRITE_VARS

//-----------------------------------------------------------------------
// VERIFY VARIABLES CREATION                 VERIFY VARIABLES CREATION
//-----------------------------------------------------------------------

static STATUS LocalIoCheck(void)
{
   // Check if input variables exist.
   STATUS LocalStatus;

   LocalStatus = OS_DoesVariablesExist(ModulInputs, MODUL_INPUTS_SIZE);
   if (LocalStatus != 0)
   {
      AppSystemLog(ERR_1, MODULE_NAME"InputErr: %d", LocalStatus);
      AppSystemLog(ERR_1, "Name: %s", ModulInputs[LocalStatus-1].Name);
      return ERR_1;
   }
   (void)VarsReadTypeCheck();

   LocalStatus = OS_DoesVariablesExist(ModulOutputs, MODUL_OUTPUTS_SIZE);
   if (LocalStatus != 0)
   {
      AppSystemLog(ERR_2, MODULE_NAME"OutputErr: %d", LocalStatus);
      AppSystemLog(ERR_2, "Name: %s", ModulOutputs[LocalStatus-1].Name);
      return ERR_2;
   }
   (void)VarsWriteTypeCheck();

   return OS_SUCCESS;
}

#define VERIFY_VARIABLES

//-----------------------------------------------------------------------
// ALLOCATE MEMORY FOR SUMMATIONS        ALLOCATE MEMORY FOR SUMMATIONS
//-----------------------------------------------------------------------


//-----------------------------------------------------------------------
// SUMMATIONS                  SUMMATIONS                  SUMMATIONS
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// DEFINE MENUS               DEFINE MENUS               DEFINE MENUS
//-----------------------------------------------------------------------



// Menu line and link to local menu
//-----------------------------------------------------------------------
static struct line_struct M_WindDirectionLinkToLocalMenu[] =
{
   MENU_ELEMENT_LINE_LINK("Wind Direction",                    PASSWORD_LEVEL_LICENCE_CUSTOMER,    "M_WindDirection",                  "G_WindDirection"),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_WindDirectionMenu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_WindDirection",                  PASSWORD_LEVEL_LICENCE_CUSTOMER),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_WindDirectionMenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("WIND DIRECTION",                    PASSWORD_LEVEL_LICENCE_CUSTOMER,    "M_"APP_ID"AppMain",                "G_"APP_ID"App"),
   MENU_ELEMENT_LINE_VARRO("Wind Direction",                   PASSWORD_LEVEL_LICENCE_CUSTOMER,    (char*)"V_WindDirection",                            LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Relative Wind Direction",          PASSWORD_LEVEL_LICENCE_CUSTOMER,    (char*)"V_WindDirectionRelative",                    LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Sensors Active",                   PASSWORD_LEVEL_LICENCE_CUSTOMER,    (char*)"V_WindDirectionSensorsActive",               LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_LINK("Status",                            PASSWORD_LEVEL_LICENCE_CUSTOMER,    "M_Status2",                        "G_WindDirection"),
   MENU_ELEMENT_LINE_LINK("Parameter",                         PASSWORD_LEVEL_LICENCE_CUSTOMER,    "M_Parameter3",                     "G_WindDirection"),
   MENU_ELEMENT_LINE_LINK("Debug",                             PASSWORD_LEVEL_MITA_PROGRAMMER,     "M_Debug",                          "G_WindDirection"),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_Status2Menu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_Status2",                        PASSWORD_LEVEL_LICENCE_CUSTOMER),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_Status2MenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("STATUS",                            PASSWORD_LEVEL_LICENCE_CUSTOMER,    "M_WindDirection",                  "G_WindDirection"),
   MENU_ELEMENT_LINE_VARRO("Wind Direction",                   PASSWORD_LEVEL_LICENCE_CUSTOMER,    (char*)"V_WindDirection",                            LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Wind Direction 3 s.",              PASSWORD_LEVEL_LICENCE_CUSTOMER,    (char*)"V_WindDirection3Sec",                        LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Wind Direction 30 s.",             PASSWORD_LEVEL_LICENCE_CUSTOMER,    (char*)"V_WindDirection30Sec",                       LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Wind Direction 10 min.",           PASSWORD_LEVEL_LICENCE_CUSTOMER,    (char*)"V_WindDirection10Min",                       LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Nacelle Direction",                PASSWORD_LEVEL_LICENCE_CUSTOMER,    (char*)"V_NacelleDirection",                         LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Relative Wind Direction",          PASSWORD_LEVEL_LICENCE_CUSTOMER,    (char*)"V_WindDirectionRelative",                    LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Relative Wind Direction 3 s.",     PASSWORD_LEVEL_LICENCE_CUSTOMER,    (char*)"V_WindDirectionRelative3Sec",                LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Relative Wind Direction 30 s.",    PASSWORD_LEVEL_LICENCE_CUSTOMER,    (char*)"V_WindDirectionRelative30Sec",               LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Relative Wind Direction 10 min.",  PASSWORD_LEVEL_LICENCE_CUSTOMER,    (char*)"V_WindDirectionRelative10Min",               LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Wind direction ref",               PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_WID_WindDirectionRef",                     LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Wind direction left dev",          PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_WID_WindLeft",                             LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Wind direction right dev",         PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_WID_WindRight",                            LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Wind direction variation",         PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_WID_DirVariation",                         LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_LINK("Sensor Inputs",                     PASSWORD_LEVEL_LICENCE_CUSTOMER,    "M_SensorInputs38",                 "G_WindDirection"),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_SensorInputs38Menu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_SensorInputs38",                 PASSWORD_LEVEL_LICENCE_CUSTOMER),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_SensorInputs38MenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("SENSOR INPUTS",                     PASSWORD_LEVEL_LICENCE_CUSTOMER,    "M_Status2",                        "G_WindDirection"),
   MENU_ELEMENT_LINE_VARRO("Wind Direction Sensor 1",          PASSWORD_LEVEL_LICENCE_CUSTOMER,    (char*)"V_WindDirectionSensor1",                     LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Wind Direction Sensor 1 Status",   PASSWORD_LEVEL_LICENCE_CUSTOMER,    (char*)"V_WDSensor1StatusText",                      LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Wind Direction Sensor 2",          PASSWORD_LEVEL_LICENCE_CUSTOMER,    (char*)"V_WindDirectionSensor2",                     LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Wind Direction Sensor 2 Status",   PASSWORD_LEVEL_LICENCE_CUSTOMER,    (char*)"V_WDSensor2StatusText",                      LINE_FORMAT_NONE),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_Parameter3Menu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_Parameter3",                     PASSWORD_LEVEL_LICENCE_CUSTOMER),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_Parameter3MenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("PARAMETER",                         PASSWORD_LEVEL_LICENCE_CUSTOMER,    "M_WindDirection",                  "G_WindDirection"),
   MENU_ELEMENT_LINE_VARRW("Load parameters",                  PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_WID_LoadParameters",                       LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Wind Direction Sensor Select",     PASSWORD_LEVEL_LICENCE_CUSTOMER,    (char*)"P_WindDirectionSensorSelect",                LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Wind direction variation rate up", PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_WID_DirVariationRateUp",                   LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Wind direction variation rate down", PASSWORD_LEVEL_END_CUSTOMER,        (char*)"P_WID_DirVariationRateDown",                 LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_LINK("Ref Wind Direction Calc",           PASSWORD_LEVEL_LICENCE_PROGRAMMER,  "M_RefWindDirection",               "G_WindDirection"),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_RefWindDirectionMenu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_RefWindDirection",               PASSWORD_LEVEL_LICENCE_PROGRAMMER),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_RefWindDirectionMenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("REF WIND DIRECTION CALC",           PASSWORD_LEVEL_LICENCE_PROGRAMMER,  "M_Parameter3",                     "G_WindDirection"),
   MENU_ELEMENT_LINE_VARRW("PI kp Inc",                        PASSWORD_LEVEL_LICENCE_PROGRAMMER,  (char*)"P_WID_PIkpInc",                              LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("PI kp Dec",                        PASSWORD_LEVEL_LICENCE_PROGRAMMER,  (char*)"P_WID_PIkpDec",                              LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("PI ki Inc",                        PASSWORD_LEVEL_LICENCE_PROGRAMMER,  (char*)"P_WID_PIkiInc",                              LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("PI ki Dec",                        PASSWORD_LEVEL_LICENCE_PROGRAMMER,  (char*)"P_WID_PIkiDec",                              LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_LINK("Help",                              PASSWORD_LEVEL_LICENCE_PROGRAMMER,  "M_Help",                           "G_WindDirection"),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_HelpMenu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_Help",                           PASSWORD_LEVEL_LICENCE_PROGRAMMER),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_HelpMenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("HELP",                              PASSWORD_LEVEL_LICENCE_PROGRAMMER,  "M_RefWindDirection",               "G_WindDirection"),
   MENU_ELEMENT_LINE_TEXT("These parameters define how the",   PASSWORD_LEVEL_LICENCE_PROGRAMMER),
   MENU_ELEMENT_LINE_TEXT("reference wind direction is calculated", PASSWORD_LEVEL_LICENCE_PROGRAMMER),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_DebugMenu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_Debug",                          PASSWORD_LEVEL_MITA_PROGRAMMER),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_DebugMenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("DEBUG",                             PASSWORD_LEVEL_MITA_PROGRAMMER,     "M_WindDirection",                  "G_WindDirection"),
   MENU_ELEMENT_LINE_VARRW("V_WID_WindDirectionSensorTest",    PASSWORD_LEVEL_LICENCE_PROGRAMMER,  (char*)"V_WID_WindDirectionSensorTest",              LINE_FORMAT_NONE),
};
// Creating parameters for multiplexed categories
//-----------------------------------------------------------------------
static struct multiplexed_info_struct M_WindDirectionMultiplexedCategoriesParameters[] =
{
0};

//-----------------------------------------------------------------------
// CREATE MENUS               CREATE MENUS               CREATE MENUS
//-----------------------------------------------------------------------

// Memory reservation
//-----------------------------------------------------------------------
static struct menu_group_struct ObjGroup[1];

// Creating the menus
//-----------------------------------------------------------------------
STATUS WindDirectionMenuAppInit(U8 ModuleState, OS_MEMORY_POOL* pPool)
{
   STATUS Status;

   if (ModuleState == APP_INIT1)
   {
      /* Create application group */
      Status = OS_CreateMenuGroup(ObjGroup, M_WindDirectionLinkToLocalMenu[0].LinkGroup);
      STATUS_LINE_VAR_RETURN_VALUE(Status);
   }

   Status = CreateAndInitializeMenu(ModuleState,
                                    M_WindDirectionMenuLines[0].LinkGroup,
                                    M_WindDirectionMenuLines[0].LinkName,
                                    ELEMENT(M_WindDirectionLinkToLocalMenu),
                                    M_WindDirectionLinkToLocalMenu[0].LinkGroup,
                                    ELEMENT(M_WindDirectionMenu),
                                    M_WindDirectionLinkToLocalMenu[0].LinkName,
                                    ELEMENT(M_WindDirectionMenuLines),
                                    pPool,
                                    M_WindDirectionMultiplexedCategoriesParameters);
   STATUS_LINE_VAR_RETURN_VALUE(Status);

   Status = CreateAndInitializeMenu(ModuleState,
                                    M_Status2MenuLines[0].LinkGroup,
                                    M_Status2MenuLines[0].LinkName,
                                    NULL,
                                    0,
                                    M_WindDirectionMenuLines[4].LinkGroup,
                                    ELEMENT(M_Status2Menu),
                                    M_WindDirectionMenuLines[4].LinkName,
                                    ELEMENT(M_Status2MenuLines),
                                    pPool,
                                    M_WindDirectionMultiplexedCategoriesParameters);
   STATUS_LINE_VAR_RETURN_VALUE(Status);

   Status = CreateAndInitializeMenu(ModuleState,
                                    M_SensorInputs38MenuLines[0].LinkGroup,
                                    M_SensorInputs38MenuLines[0].LinkName,
                                    NULL,
                                    0,
                                    M_Status2MenuLines[14].LinkGroup,
                                    ELEMENT(M_SensorInputs38Menu),
                                    M_Status2MenuLines[14].LinkName,
                                    ELEMENT(M_SensorInputs38MenuLines),
                                    pPool,
                                    M_WindDirectionMultiplexedCategoriesParameters);
   STATUS_LINE_VAR_RETURN_VALUE(Status);

   Status = CreateAndInitializeMenu(ModuleState,
                                    M_Parameter3MenuLines[0].LinkGroup,
                                    M_Parameter3MenuLines[0].LinkName,
                                    NULL,
                                    0,
                                    M_WindDirectionMenuLines[5].LinkGroup,
                                    ELEMENT(M_Parameter3Menu),
                                    M_WindDirectionMenuLines[5].LinkName,
                                    ELEMENT(M_Parameter3MenuLines),
                                    pPool,
                                    M_WindDirectionMultiplexedCategoriesParameters);
   STATUS_LINE_VAR_RETURN_VALUE(Status);

   Status = CreateAndInitializeMenu(ModuleState,
                                    M_RefWindDirectionMenuLines[0].LinkGroup,
                                    M_RefWindDirectionMenuLines[0].LinkName,
                                    NULL,
                                    0,
                                    M_Parameter3MenuLines[5].LinkGroup,
                                    ELEMENT(M_RefWindDirectionMenu),
                                    M_Parameter3MenuLines[5].LinkName,
                                    ELEMENT(M_RefWindDirectionMenuLines),
                                    pPool,
                                    M_WindDirectionMultiplexedCategoriesParameters);
   STATUS_LINE_VAR_RETURN_VALUE(Status);

   Status = CreateAndInitializeMenu(ModuleState,
                                    M_HelpMenuLines[0].LinkGroup,
                                    M_HelpMenuLines[0].LinkName,
                                    NULL,
                                    0,
                                    M_RefWindDirectionMenuLines[5].LinkGroup,
                                    ELEMENT(M_HelpMenu),
                                    M_RefWindDirectionMenuLines[5].LinkName,
                                    ELEMENT(M_HelpMenuLines),
                                    pPool,
                                    M_WindDirectionMultiplexedCategoriesParameters);
   STATUS_LINE_VAR_RETURN_VALUE(Status);

   Status = CreateAndInitializeMenu(ModuleState,
                                    M_DebugMenuLines[0].LinkGroup,
                                    M_DebugMenuLines[0].LinkName,
                                    NULL,
                                    0,
                                    M_WindDirectionMenuLines[6].LinkGroup,
                                    ELEMENT(M_DebugMenu),
                                    M_WindDirectionMenuLines[6].LinkName,
                                    ELEMENT(M_DebugMenuLines),
                                    pPool,
                                    M_WindDirectionMultiplexedCategoriesParameters);
   STATUS_LINE_VAR_RETURN_VALUE(Status);

   return OS_SUCCESS;
}

#define CREATE_MENU

//-----------------------------------------------------------------------
//               BUTTONS FUNCTIONS FORWARD DECLARATIONS
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// BUTTONS                       BUTTONS                      BUTTONS
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
//             SET/RESET FUNCTIONS FORWARD DECLARATIONS
//-----------------------------------------------------------------------
static U8 StatusSetFunc263(void);
static U8 StatusResetFunc263(void);
//-----------------------------------------------------------------------
// STATUSCODES                 STATUSCODES                 STATUSCODES
//-----------------------------------------------------------------------

static struct sts_statuscode_structure StatusCodes[] =
{
   STS_CODE_ELEMENT("Wind Direction!",        20*SEC,    263,       STATUSCODE_UPDATE_TYPE_POLLING,         PASSWORD_LEVEL_SERVICE,            STATUSCODE_TIMER_TYPE_CONSTANT,     STATUSCODE_TIMER_TYPE_CONSTANT,     STATUSCODE_RESET_TYPE_AUTOMATIC,    STATUSCODE_PRIORITY_LOW,       21,   0,    32,   NULL,      PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_SERVICE,            StatusSetFunc263,        StatusResetFunc263,      BRAKE_PROG_50,       BRAKE_PROG_0,        BRAKE_PROG_MAX,      NULL,                PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_MITA_PROGRAMMER,    YAW_PROG_0,          YAW_PROG_0,          YAW_PROG_240,        NULL,                PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_MITA_PROGRAMMER,    0,    0,    255,  NULL,      PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_SERVICE,            1,  PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_ADMINISTRATOR,      20,        20,        1000,      NULL,      PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         SETDELAY_MIN,   SETDELAY_MAX,   NULL,      PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         RESETDELAY_MIN, RESETDELAY_MAX, NULL,      PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         REPEATTIMES_MIN,     REPEATTIMES_MAX,     NULL,      PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         REPEATPERIOD_MIN,    REPEATPERIOD_MAX,    NULL,      PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         REPEATCODE_MIN,      REPEATCODE_MAX,      NULL,      PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         TIMEOUTPERIOD_MIN,   65535,               NULL,      PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_MITA_PROGRAMMER,    0,         TIMEOUTCODE_MIN,     TIMEOUTCODE_MAX,     NULL,      PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_MITA_PROGRAMMER,    PASSWORD_LEVEL_SERVICE,            PASSWORD_LEVEL_SERVICE,            NULL),
};

static STATUS_CODE_CONTROL_BLOCK StatusCodeControlBlock;

static STATUS LocalStatusCodeInit(void)
{
   STATUS LocalStatus;

   LocalStatus = OS_StatusCodeInit(STATUSCODE_INTERFACE_VERSION,
                                   &StatusCodeControlBlock,
                                   StatusCodes,
                                   sizeof(StatusCodes)/sizeof(StatusCodes[0]),
                                   AppLocalParameterPosition(),
                                   AppBackupPosition());
   STATUS_LINE_VAR_RETURN_CONST(LocalStatus, ERR_3);

   return OS_SUCCESS;
}

#define CREATE_STATUS_CODES

//-----------------------------------------------------------------------
// MODIFIABLE                  MODIFIABLE                   MODIFIABLE
//-----------------------------------------------------------------------

extern const char WindDirectionAppGroupName[];
extern const char WindDirectionAppMenuName[];
extern const U8 WindDirection_Conf_Menu_Main_Read;
extern const U8 WindDirection_Conf_Menu_Main_Write;
extern const U8 WindDirection_Conf_Menu_Mita_Read;
extern const U8 WindDirection_Conf_Menu_Mita_Write;
extern const U8 WindDirection_Conf_Menu_Parameter_Read;
extern const U8 WindDirection_Conf_Menu_Parameter_Write;
extern const U8 WindDirection_Conf_Menu_Service_Read;
extern const U8 WindDirection_Conf_Menu_Service_Write;
extern const U8 WindDirection_Conf_Menu_Status_Read;
extern const U8 WindDirection_Conf_SC_Activate_Counter_Backup_Read;
extern const U8 WindDirection_Conf_SC_Activate_Counter_Backup_Write;
extern const U8 WindDirection_Conf_SC_Alarm_Program_Read;
extern const U8 WindDirection_Conf_SC_Availability_Group_Read;
extern const U8 WindDirection_Conf_SC_Availability_Group_Write;
extern const U8 WindDirection_Conf_SC_Brake_Program_Read;
extern const U8 WindDirection_Conf_SC_Enable_Read;
extern const U8 WindDirection_Conf_SC_Enable_Write;
extern const U8 WindDirection_Conf_SC_Repeat_Code_Read;
extern const U8 WindDirection_Conf_SC_Repeat_Period_Read;
extern const U8 WindDirection_Conf_SC_Repeat_Times_Read;
extern const U8 WindDirection_Conf_SC_Reset_Delay_Read;
extern const U8 WindDirection_Conf_SC_Reset_Delay_Write;
extern const U8 WindDirection_Conf_SC_Reset_Status_Code_Write;
extern const U8 WindDirection_Conf_SC_Set_Delay_Read;
extern const U8 WindDirection_Conf_SC_Set_Delay_Write;
extern const U8 WindDirection_Conf_SC_TimeOut_Code_Read;
extern const U8 WindDirection_Conf_SC_TimeOut_Period_Read;
extern const U8 WindDirection_Conf_SC_Update_Interval_Read;
extern const U8 WindDirection_Conf_SC_Yaw_Program_Read;
extern const U8 WindDirection_Conf_Summation_Read;
extern const U8 WindDirection_Conf_Summation_Write;
extern const U8 WindDirection_Conf_P_WindDirectionSensorSelect_InitValueExt;
extern const U8 WindDirection_Conf_SC_263_AvailabilityGroupConst;
extern const U8 WindDirection_Conf_SC_263_EnableStatusCodeConst;
extern const U8 WindDirection_Conf_SC_263_BrakeProgramConst;
extern const U8 WindDirection_Conf_SC_263_YawProgramConst;
extern const U8 WindDirection_Conf_SC_263_AlarmProgramConst;
extern const U32 WindDirection_Conf_SC_263_ResetDelayConst;
extern const U32 WindDirection_Conf_SC_263_SetDelayConst;

static void Init_Structures_From_Conf_File(void)
{
   LocalVars[0].c.AccessRead = WindDirection_Conf_Menu_Status_Read;
   LocalVars[2].c.AccessRead = WindDirection_Conf_Menu_Status_Read;
   LocalVars[3].c.AccessRead = WindDirection_Conf_Menu_Status_Read;
   LocalVars[4].c.AccessRead = WindDirection_Conf_Menu_Status_Read;
   LocalVars[5].c.AccessRead = WindDirection_Conf_Menu_Status_Read;
   LocalVars[6].c.AccessRead = WindDirection_Conf_Menu_Status_Read;
   LocalVars[7].c.AccessRead = WindDirection_Conf_Menu_Status_Read;
   LocalVars[8].c.AccessRead = WindDirection_Conf_Menu_Status_Read;
   LocalVars[9].c.AccessRead = WindDirection_Conf_Menu_Status_Read;
   LocalVars[10].c.AccessRead = WindDirection_Conf_Menu_Status_Read;
   LocalVars[11].c.AccessRead = WindDirection_Conf_Menu_Status_Read;
   LocalVars[12].c.AccessRead = WindDirection_Conf_Menu_Status_Read;
   ParameterVars[0].c.AccessRead = WindDirection_Conf_Menu_Parameter_Read;
   ParameterVars[0].c.AccessWrite = WindDirection_Conf_Menu_Parameter_Write;
   ParameterVars[0].c.Value.u8 = WindDirection_Conf_P_WindDirectionSensorSelect_InitValueExt;
   M_WindDirectionMenuLines[0].LinkName = (char*)WindDirectionAppMenuName;
   M_WindDirectionMenuLines[0].LinkGroup = (char*)WindDirectionAppGroupName;
   M_Status2MenuLines[14].ViewPasswordLevel = WindDirection_Conf_Menu_Status_Read;
   M_SensorInputs38Menu[0].ViewPasswordLevel = WindDirection_Conf_Menu_Status_Read;
   M_SensorInputs38MenuLines[0].ViewPasswordLevel = WindDirection_Conf_Menu_Status_Read;
   M_WindDirectionMenuLines[4].ViewPasswordLevel = WindDirection_Conf_Menu_Status_Read;
   M_Status2Menu[0].ViewPasswordLevel = WindDirection_Conf_Menu_Status_Read;
   M_Status2MenuLines[0].ViewPasswordLevel = WindDirection_Conf_Menu_Status_Read;
   M_WindDirectionMenuLines[5].ViewPasswordLevel = WindDirection_Conf_Menu_Parameter_Read;
   M_Parameter3Menu[0].ViewPasswordLevel = WindDirection_Conf_Menu_Parameter_Read;
   M_Parameter3MenuLines[0].ViewPasswordLevel = WindDirection_Conf_Menu_Parameter_Read;
   M_WindDirectionLinkToLocalMenu[0].ViewPasswordLevel = WindDirection_Conf_Menu_Main_Read;
   M_WindDirectionMenu[0].ViewPasswordLevel = WindDirection_Conf_Menu_Main_Read;
   M_WindDirectionMenuLines[0].ViewPasswordLevel = WindDirection_Conf_Menu_Main_Read;
   M_WindDirectionMenuLines[1].ViewPasswordLevel = WindDirection_Conf_Menu_Main_Read;
   M_WindDirectionMenuLines[2].ViewPasswordLevel = WindDirection_Conf_Menu_Main_Read;
   M_WindDirectionMenuLines[3].ViewPasswordLevel = WindDirection_Conf_Menu_Main_Read;
   M_Status2MenuLines[1].ViewPasswordLevel = WindDirection_Conf_Menu_Status_Read;
   M_Status2MenuLines[2].ViewPasswordLevel = WindDirection_Conf_Menu_Status_Read;
   M_Status2MenuLines[3].ViewPasswordLevel = WindDirection_Conf_Menu_Status_Read;
   M_Status2MenuLines[4].ViewPasswordLevel = WindDirection_Conf_Menu_Status_Read;
   M_Status2MenuLines[5].ViewPasswordLevel = WindDirection_Conf_Menu_Status_Read;
   M_Status2MenuLines[6].ViewPasswordLevel = WindDirection_Conf_Menu_Status_Read;
   M_Status2MenuLines[7].ViewPasswordLevel = WindDirection_Conf_Menu_Status_Read;
   M_Status2MenuLines[8].ViewPasswordLevel = WindDirection_Conf_Menu_Status_Read;
   M_Status2MenuLines[9].ViewPasswordLevel = WindDirection_Conf_Menu_Status_Read;
   M_SensorInputs38MenuLines[1].ViewPasswordLevel = WindDirection_Conf_Menu_Status_Read;
   M_SensorInputs38MenuLines[2].ViewPasswordLevel = WindDirection_Conf_Menu_Status_Read;
   M_SensorInputs38MenuLines[3].ViewPasswordLevel = WindDirection_Conf_Menu_Status_Read;
   M_SensorInputs38MenuLines[4].ViewPasswordLevel = WindDirection_Conf_Menu_Status_Read;
   M_Parameter3MenuLines[2].ViewPasswordLevel = WindDirection_Conf_Menu_Parameter_Read;
   StatusCodes[0].StsResetPasswordLevel = WindDirection_Conf_SC_Reset_Status_Code_Write;
   StatusCodes[0].StsUpdateIntervalAccessRead = WindDirection_Conf_SC_Update_Interval_Read;
   StatusCodes[0].StsAvailabilityGroup = WindDirection_Conf_SC_263_AvailabilityGroupConst;
   StatusCodes[0].AvailabilityGroupAccessRead = WindDirection_Conf_SC_Availability_Group_Read;
   StatusCodes[0].AvailabilityGroupAccessWrite = WindDirection_Conf_SC_Availability_Group_Write;
   StatusCodes[0].StsControlProgram1 = WindDirection_Conf_SC_263_BrakeProgramConst;
   StatusCodes[0].StsControlProgram1AccessRead = WindDirection_Conf_SC_Brake_Program_Read;
   StatusCodes[0].StsControlProgram2 = WindDirection_Conf_SC_263_YawProgramConst;
   StatusCodes[0].StsControlProgram2AccessRead = WindDirection_Conf_SC_Yaw_Program_Read;
   StatusCodes[0].StsControlProgram3 = WindDirection_Conf_SC_263_AlarmProgramConst;
   StatusCodes[0].StsControlProgram3AccessRead = WindDirection_Conf_SC_Alarm_Program_Read;
   StatusCodes[0].StsCodeEnable = WindDirection_Conf_SC_263_EnableStatusCodeConst;
   StatusCodes[0].StsCodeEnableAccessRead = WindDirection_Conf_SC_Enable_Read;
   StatusCodes[0].StsCodeEnableAccessWrite = WindDirection_Conf_SC_Enable_Write;
   StatusCodes[0].StsSetDelay = WindDirection_Conf_SC_263_SetDelayConst;
   StatusCodes[0].StsSetDelayAccessRead = WindDirection_Conf_SC_Set_Delay_Read;
   StatusCodes[0].StsSetDelayAccessWrite = WindDirection_Conf_SC_Set_Delay_Write;
   StatusCodes[0].StsResetDelay = WindDirection_Conf_SC_263_ResetDelayConst;
   StatusCodes[0].StsResetDelayAccessRead = WindDirection_Conf_SC_Reset_Delay_Read;
   StatusCodes[0].StsResetDelayAccessWrite = WindDirection_Conf_SC_Reset_Delay_Write;
   StatusCodes[0].StsActiveRepeatTimesAccessRead = WindDirection_Conf_SC_Repeat_Times_Read;
   StatusCodes[0].StsActiveRepeatPeriodAccessRead = WindDirection_Conf_SC_Repeat_Period_Read;
   StatusCodes[0].StsActiveRepeatCodeAccessRead = WindDirection_Conf_SC_Repeat_Code_Read;
   StatusCodes[0].StsActiveTimeoutPeriodAccessRead = WindDirection_Conf_SC_TimeOut_Period_Read;
   StatusCodes[0].StsActiveTimeoutCodeAccessRead = WindDirection_Conf_SC_TimeOut_Code_Read;
   StatusCodes[0].ActivateCounterAccessRead = WindDirection_Conf_SC_Activate_Counter_Backup_Read;
   StatusCodes[0].ActivateCounterAccessWrite = WindDirection_Conf_SC_Activate_Counter_Backup_Write;
}

//-----------------------------------------------------------------------
// AUTOGENERATED END        AUTOGENERATED END        AUTOGENERATED END
//-----------------------------------------------------------------------
//}

#undef AUTOGENERATED_PART

//-----------------------------------------------------------------------
// USER DEFINITIONS         USER DEFINITIONS         USER DEFINITIONS
//-----------------------------------------------------------------------

//#define WID_DEBUG

#define WID_TASK_SCANTIME 20


struct AvgBearing_F32_20ms_Struct WindDirAvg_Buffer;

static PI_Regulator_2 WindLeftPI;
static PI_Regulator_2 WindRightPI;
static Rate_Limiter DirVariation_RateLim;

F32 PIkpInc = 0;
F32 PIkpDec = 0;
F32 PIkiInc = 0;
F32 PIkiDec = 0;

// parameters
U16 P_WID_DirVariationRateUp;
U16 P_WID_DirVariationRateDown;


// function declarations
static STATUS LoadParameters(void);

#if defined DLL_SIMU
varid_t DLL_IN_WindDirectionRel_ID;
F32 DLL_IN_WindDirectionRel;
#endif

//-----------------------------------------------------------------------
// SET/RESET FUNCTIONS    SET/RESET FUNCTIONS    SET/RESET FUNCTIONS
//-----------------------------------------------------------------------
static U8 StatusSetFunc263(void)
{
    if ((P_WindDirectionSensorSelect == 0) && V_WindDirectionSensor1Status && V_WindDirectionSensor2Status)
    {
        return 1;
    }
    if ((P_WindDirectionSensorSelect == 1) && V_WindDirectionSensor1Status)
    {
        return 1;
    }
    if ((P_WindDirectionSensorSelect == 2) && V_WindDirectionSensor2Status)
    {
        return 1;
    }
    return 0;
}

static U8 StatusResetFunc263(void)
{
    if ((P_WindDirectionSensorSelect == 0) && V_WindDirectionSensor1Status && V_WindDirectionSensor2Status)
    {
        return 0;
    }
    if ((P_WindDirectionSensorSelect == 1) && V_WindDirectionSensor1Status)
    {
        return 0;
    }
    if ((P_WindDirectionSensorSelect == 2) && V_WindDirectionSensor2Status)
    {
        return 0;
    }
    return 1;
}
//-----------------------------------------------------------------------
// DRIVER FUNCTION         DRIVER FUNCTION         DRIVER FUNCTION
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// INIT                   INIT                     INIT
//-----------------------------------------------------------------------
static STATUS WindDirectionInit(void)
{
    InitializeAvgBearing(&WindDirAvg_Buffer);

    return OS_SUCCESS;
}

static STATUS Initialize()
{
    STATUS Status = OS_SUCCESS;
    
    #if defined DLL_SIMU
    Status = OS_VarDB_GetVariableID("DLL_IN_WindDirectionRel", &DLL_IN_WindDirectionRel_ID);
    if (Status != 0)
    {
       return Status;
    }
    #endif

    Status = WindDirectionInit();
    if (Status != OS_SUCCESS) { return Status; }

    WindLeftPI = PI_New_2(PIkpDec, PIkpInc, PIkiDec, PIkiInc, -1800, 1800);
    WindRightPI = PI_New_2(PIkpInc, PIkpDec, PIkiInc, PIkiDec, -1800, 1800);
    DirVariation_RateLim = RateLim_New(1/*RateUp*/, 1/*RateDown*/, 1000/*TimeBase*/, WID_TASK_SCANTIME/*TimeStep*/);

    Status = LoadParameters();
    if (Status != OS_SUCCESS) { return Status; }

    return Status;
}
//-----------------------------------------------------------------------
// CONTROL                CONTROL                 CONTROL
//-----------------------------------------------------------------------

static STATUS LoadParameters()
{
    STATUS Status = OS_SUCCESS;

    // read parameters from varDB
    Status = OS_VarDB_ReadVariableByName("P_WID_PIkpInc", &PIkpInc, sizeof(F32), NULL);
    if (Status != OS_SUCCESS) { return Status; }
    Status = OS_VarDB_ReadVariableByName("P_WID_PIkpDec", &PIkpDec, sizeof(F32), NULL);
    if (Status != OS_SUCCESS) { return Status; }
    Status = OS_VarDB_ReadVariableByName("P_WID_PIkiInc", &PIkiInc, sizeof(F32), NULL);
    if (Status != OS_SUCCESS) { return Status; }
    Status = OS_VarDB_ReadVariableByName("P_WID_PIkiDec", &PIkiDec, sizeof(F32), NULL);
    if (Status != OS_SUCCESS) { return Status; }
    Status = OS_VarDB_ReadVariableByName("P_WID_DirVariationRateUp", &P_WID_DirVariationRateUp, sizeof(P_WID_DirVariationRateUp), NULL);
    if (Status != OS_SUCCESS) { return Status; }
    Status = OS_VarDB_ReadVariableByName("P_WID_DirVariationRateDown", &P_WID_DirVariationRateDown, sizeof(P_WID_DirVariationRateDown), NULL);
    if (Status != OS_SUCCESS) { return Status; }

    // reload PI regulator parameters
    Status = PI_Set_KpInc_2(WindLeftPI, PIkpDec);
    if (Status != OS_SUCCESS) { return Status; }
    Status = PI_Set_KpDec_2(WindLeftPI, PIkpInc);
    if (Status != OS_SUCCESS) { return Status; }
    Status = PI_Set_KiInc_2(WindLeftPI, PIkiDec);
    if (Status != OS_SUCCESS) { return Status; }
    Status = PI_Set_KiDec_2(WindLeftPI, PIkiInc);
    if (Status != OS_SUCCESS) { return Status; }

    Status = PI_Set_KpInc_2(WindRightPI, PIkpInc);
    if (Status != OS_SUCCESS) { return Status; }
    Status = PI_Set_KpDec_2(WindRightPI, PIkpDec);
    if (Status != OS_SUCCESS) { return Status; }
    Status = PI_Set_KiInc_2(WindRightPI, PIkiInc);
    if (Status != OS_SUCCESS) { return Status; }
    Status = PI_Set_KiDec_2(WindRightPI, PIkiDec);
    if (Status != OS_SUCCESS) { return Status; }

    Status = PI_Reset_2(WindLeftPI);
    if (Status != OS_SUCCESS) { return Status; }
    Status = PI_Reset_2(WindRightPI);
    if (Status != OS_SUCCESS) { return Status; }

    RateLim_Set_RateUp(DirVariation_RateLim, P_WID_DirVariationRateUp);
    RateLim_Set_RateDown(DirVariation_RateLim, P_WID_DirVariationRateDown);


    return OS_SUCCESS;
}


static STATUS LocalCtrl(void)
{
    STATUS LocalStatus = OS_SUCCESS;

#if defined DLL_SIMU
   
    OS_VarDB_ReadVariable(DLL_IN_WindDirectionRel_ID, &DLL_IN_WindDirectionRel, sizeof(DLL_IN_WindDirectionRel), NULL);
    S16 direction_rel = DLL_IN_WindDirectionRel * 10;
    if (direction_rel < 0)
    {
       V_WindDirectionSensor = direction_rel + 3600;
    }
    else
    {
       V_WindDirectionSensor = direction_rel;
    }
   
#else

    // Wind Direction Sensor Selector
    switch (P_WindDirectionSensorSelect)
    {
        case 0: //AUTO
        {
            if (!V_WindDirectionSensor1Status && !V_WindDirectionSensor2Status)
            {
                strcpy(V_WindDirectionSensorsActive, "All");
                // calculate average of the two wind direction sensors values
                U16 diff;
                if (V_WindDirectionSensor2 > V_WindDirectionSensor1)
                {
                    diff = V_WindDirectionSensor2 - V_WindDirectionSensor1;
                    if (diff > 1800) { V_WindDirectionSensor = V_WindDirectionSensor1 - (3600 - diff) / 2; }
                    else { V_WindDirectionSensor = V_WindDirectionSensor1 + diff / 2; }
                }
                else if (V_WindDirectionSensor2 < V_WindDirectionSensor1)
                {
                    diff = V_WindDirectionSensor1 - V_WindDirectionSensor2;
                    if (diff > 1800) { V_WindDirectionSensor = V_WindDirectionSensor1 + (3600 - diff) / 2; }
                    else { V_WindDirectionSensor = V_WindDirectionSensor1 - diff / 2; }
                }
                if (V_WindDirectionSensor >= 3600) { V_WindDirectionSensor -= 3600; }
                else if (V_WindDirectionSensor < 0) { V_WindDirectionSensor += 3600; }
            }
            else if (!V_WindDirectionSensor1Status && V_WindDirectionSensor2Status)
            {
                strcpy(V_WindDirectionSensorsActive, "Sensor 1");
                V_WindDirectionSensor = V_WindDirectionSensor1;
            }
            else if (V_WindDirectionSensor1Status && !V_WindDirectionSensor2Status)
            {
                strcpy(V_WindDirectionSensorsActive, "Sensor 2");
                V_WindDirectionSensor = V_WindDirectionSensor2;
            }
            else
            {
                strcpy(V_WindDirectionSensorsActive, "None");
                V_WindDirectionSensor = 0;
            }
            break;
        }
        case 1: //Sensor 1 selected manually
        {
            if (!V_WindDirectionSensor1Status) //No Errors in sensor 1
            {
                strcpy(V_WindDirectionSensorsActive, "Sensor 1");
                V_WindDirectionSensor = V_WindDirectionSensor1;
            }
            else
            {
                strcpy(V_WindDirectionSensorsActive, "None");
                V_WindDirectionSensor = 0;
            }
            break;
        }
        case 2: //Sensor 2 selected manually
        {
            if (!V_WindDirectionSensor2Status)
            {
                strcpy(V_WindDirectionSensorsActive, "Sensor 2");
                V_WindDirectionSensor = V_WindDirectionSensor2;
            }
            else
            {
                strcpy(V_WindDirectionSensorsActive, "None");
                V_WindDirectionSensor = 0;
            }
            break;
        }
        default:
        {
            break;
        }
    }

#endif

    //-----------------------------
    //Wind Direction calculations
    //-----------------------------

#if defined(WID_DEBUG) || defined(INCLUDE_DEBUG)
    V_WindDirectionSensor = V_WID_WindDirectionSensorTest;   //DEBUG
#endif

    // average values
    F32 avg1s;
    F32 avg3s;
    F32 avg30s;
    F32 avg10m;
    UpdateAvgBearing(&WindDirAvg_Buffer, (F32)V_WindDirectionSensor / 10, NULL, &avg1s, &avg3s, &avg30s, &avg10m);
    V_WindDirectionSensor1Sec = (U16)((avg1s + 0.05) * 10);
    V_WindDirectionSensor3Sec = (U16)((avg3s + 0.05) * 10);
    V_WindDirectionSensor30Sec = (U16)((avg30s + 0.05) * 10);
    V_WindDirectionSensor10Min = (U16)((avg10m + 0.05) * 10);

    // update wind direction ref value, which is used as reference for checking sensor malfunction
    V_WindDirectionRef = V_WindDirectionSensor30Sec;

    // Calculate absolute wind direction based on nacelle position
    V_WindDirection = V_NacelleDirection + V_WindDirectionSensor;
    if (V_WindDirection >= 3600) { V_WindDirection -= 3600; }
    V_WindDirection1Sec = V_NacelleDirection + V_WindDirectionSensor1Sec;
    if (V_WindDirection1Sec >= 3600) { V_WindDirection1Sec -= 3600; }
    V_WindDirection3Sec = V_NacelleDirection + V_WindDirectionSensor3Sec;
    if (V_WindDirection3Sec >= 3600) { V_WindDirection3Sec -= 3600; }
    V_WindDirection30Sec = V_NacelleDirection + V_WindDirectionSensor30Sec;
    if (V_WindDirection30Sec >= 3600) { V_WindDirection30Sec -= 3600; }
    V_WindDirection10Min = V_NacelleDirection + V_WindDirectionSensor10Min;
    if (V_WindDirection10Min >= 3600) { V_WindDirection10Min -= 3600; }

    // Calculate relative wind direction
    if (V_WindDirectionSensor <= 1800) { V_WindDirectionRelative = V_WindDirectionSensor; }
    else { V_WindDirectionRelative = (S16)V_WindDirectionSensor - 3600; }
    if (V_WindDirectionSensor3Sec <= 1800) { V_WindDirectionRelative3Sec = V_WindDirectionSensor3Sec; }
    else { V_WindDirectionRelative3Sec = (S16)V_WindDirectionSensor3Sec - 3600; }
    if (V_WindDirectionSensor30Sec <= 1800) { V_WindDirectionRelative30Sec = V_WindDirectionSensor30Sec; }
    else { V_WindDirectionRelative30Sec = (S16)V_WindDirectionSensor30Sec - 3600; }
    if (V_WindDirectionSensor10Min <= 1800) { V_WindDirectionRelative10Min = V_WindDirectionSensor10Min; }
    else { V_WindDirectionRelative10Min = (S16)V_WindDirectionSensor10Min - 3600; }

    
    // Wind Direction Sensor status update
    if (V_WindDirectionSensor1Status)
    {
        strcpy(V_WDSensor1StatusText, "Error");
    }
    else
    {
        strcpy(V_WDSensor1StatusText, "Ok");
    }
    if (V_WindDirectionSensor2Status)
    {
        strcpy(V_WDSensor2StatusText, "Error");
    }
    else
    {
        strcpy(V_WDSensor2StatusText, "Ok");
    }


    // calculating reference wind direction
    V_WID_WindLeft = (S16)PI_Control_2(WindLeftPI, (F32)V_WindDirectionRelative3Sec, (F32)V_WID_WindLeft);
    V_WID_WindRight = (S16)PI_Control_2(WindRightPI, (F32)V_WindDirectionRelative3Sec, (F32)V_WID_WindRight);
    V_WID_WindDirectionRef = ((V_WID_WindLeft + V_WID_WindRight) % 3600) / 2;
    
    // wind direction variation value calculation
    V_WID_DirVariation = V_WID_WindRight - V_WID_WindLeft;
	V_WID_DirVariation = RateLim_Control(DirVariation_RateLim, V_WID_DirVariation);
    

    // reloading parameters from menu
    if (V_WID_LoadParameters)
    {
        V_WID_LoadParameters = false;
        OS_VarDB_UpdateVariableByName("V_WID_LoadParameters", &V_WID_LoadParameters, sizeof(V_WID_LoadParameters));
        LoadParameters();
    }

    return LocalStatus;
}

//-----------------------------------------------------------------------
// MAIN CALL             MAIN CALL               MAIN CALL
//-----------------------------------------------------------------------

STATUS WindDirection(U8 ModuleState, OS_MEMORY_POOL* MemPool, U32* Arg3)
{
    STATUS LocalStatus = 0;


    if (ModuleState == APP_INIT1)
    {
        LocalStatus = OS_ValidateAPI(API_VERSION_MAJOR,
                                     API_VERSION_MINOR,
                                     OS_LinkTime,
                                     ReleaseTag,
                                     __MODULE__
                                    );
        if (OS_SUCCESS != LocalStatus)
        {
            return LocalStatus;
        }
    }
#ifdef READ_VARS
    // Read inputdata
    LocalStatus = InputReferenceRoutine(ModuleState);
    STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
#endif
#ifdef COMMON_VDB_READ
    LocalStatus = ReadVdbWindow(ModuleState);
    STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
#endif
    switch (ModuleState)
    {
        case APP_RUN :
        {
         #ifdef FUNCTION_BLOCKS_PRE_LOCAL_CONTROL
            LocalStatus = FunctionBlocksPreLocalCtrl( Interval );
            STATUS_LINE_VAR_RETURN_VALUE( LocalStatus );
         #endif

            LocalStatus = LocalCtrl();
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
        
         #ifdef FUNCTION_BLOCKS_POST_LOCAL_CONTROL
            LocalStatus = FunctionBlocksPostLocalCtrl( Interval );
            STATUS_LINE_VAR_RETURN_VALUE( LocalStatus );
         #endif

#ifdef WRITE_VARS
            // Write Outputdata
            LocalStatus = OutputReferenceRoutine(ModuleState);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
#endif

#ifdef COMMON_VDB_WRITE
            LocalStatus = WriteVdbWindow(ModuleState);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
#endif
            break;
        }
        case APP_INIT1 :
        {
            Init_Structures_From_Conf_File();


#ifdef CREATE_MENU
            LocalStatus = WindDirectionMenuAppInit(ModuleState, MemPool);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);

#ifdef MULTIPLEXIBLE_MENU
            LocalStatus = MenuArraysAppInit(ModuleState, MemPool);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
#endif
#endif

#ifdef CREATE_VARDB_VARS
            LocalStatus = CreateVarDbVars();
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
#endif

#ifdef CREATE_VARDB_ARRAY_VARS
            LocalStatus = CreateVdbArrays(MemPool);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
#endif

#ifdef CREATE_IO_VARS
            LocalStatus = CreateIOVars();
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
#endif
            break;
        }
        case APP_INIT2 :
        {
#ifdef CREATE_MENU
#ifdef MULTIPLEXIBLE_MENU
            LocalStatus = MenuArraysAppInit(ModuleState, MemPool);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
#endif
#endif

#ifdef CREATE_ALIASES
            size_t ErrorEntry = 0;
            LocalStatus = OS_VarDB_CreateAliases(AliasVars, sizeof(AliasVars) / sizeof(AliasVars[0]), &ErrorEntry);
            STATUS_LINE_VAR_RETURN_CONST(LocalStatus, ErrorEntry);
#endif

#ifdef VERIFY_ARRAY
            LocalStatus = VerifyArray();
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
#endif

#ifdef VERIFY_VARIABLES
            LocalStatus = LocalIoCheck();
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
#endif

#ifdef CREATE_BUTTONS
            LocalStatus = CreateButtons();
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
#endif
            break;
        }
        case APP_INIT3 :
        {
#ifdef CREATE_SUMMATIONS
            LocalStatus = CreateSummations();
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
#endif

#ifdef WRITE_VARS
            LocalStatus = InitOutputVars();
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
#endif

#ifdef CREATE_STATUS_CODES
            LocalStatus = LocalStatusCodeInit();
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
#endif

#ifdef CREATE_IO_VARS
            WindDirectionSetLockValues();
#endif
            break;
        }
        case APP_INIT4 :
        {
#ifdef CREATE_MENU
            LocalStatus = WindDirectionMenuAppInit(ModuleState, MemPool);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);

#ifdef MULTIPLEXIBLE_MENU
            LocalStatus = MenuArraysAppInit(ModuleState, MemPool);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
#endif
#endif
            break;
        }
        case APP_INIT5 :
        {
#ifdef VALIDATE_HASH
            LocalStatus = ValidateHash(WindDirection_copyright, MODULE_NAME, WindDirection_initialValues);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
#endif

         #ifdef INIT_FUNCTION_BLOCKS
            LocalStatus = FunctionBlocksInit( Interval );
            STATUS_LINE_VAR_RETURN_VALUE( LocalStatus );
         #endif

            LocalStatus = Initialize();
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);

            break;
        }
        default :
        {
            break;
        }
    }
    return OS_SUCCESS;
}
//-----------------------------------------------------------------------
