//*****************************PEPTOOL Header Start******************************
//                                                                               
//                         Copyright © 2015 Mita-Teknik.                         
//This software may only be used with WP4x00 Controllers delivered by Mita-Teknik
//                                                                               
//*******************************************************************************
//                                                                               
// $PEPTOOL version:9.0$                                                         
// $PEPTOOL file version:101$                                                    
//                                                                               
//*******************************************************************************
//                                                                               
// $Date: XXXX/XX/XX XX:XX:XX $                                                  
// $Author: XXXX\XXX $                                                           
// $RCSfile: Yaw_MK1_Conf.c,v $                                                  
// $Revision: X.X $                                                              
//                                                                               
//******************************PEPTOOL Header End*******************************

//***********************************************************************
// OS header files
#include <os_main.h>
// App header files
#include <InitIo.h>

#define AUTOGENERATED_PART

#include <Turbdef.h>

//-----------------------------------------------------------------------
// AUTOGENERATED START     AUTOGENERATED START     AUTOGENERATED START
//-----------------------------------------------------------------------
char Yaw_MK1_Conf_copyright[] =
{
   67, 111, 112, 121, 114, 105, 103, 104, 116, 32, 63, 32, 50, 48, 49, 53,
   32, 77, 105, 116, 97, 45, 84, 101, 107, 110, 105, 107, 46, 13, 10, 84,
   104, 105, 115, 32, 115, 111, 102, 116, 119, 97, 114, 101, 32, 109, 97, 121,
   32, 111, 110, 108, 121, 32, 98, 101, 32, 117, 115, 101, 100, 32, 119, 105,
   116, 104, 32, 87, 80, 52, 120, 48, 48, 32, 67, 111, 110, 116, 114, 111,
   108, 108, 101, 114, 115, 32, 100, 101, 108, 105, 118, 101, 114, 101, 100, 32,
   98, 121, 32, 77, 105, 116, 97, 45, 84, 101, 107, 110, 105, 107, 0
};
//-----------------------------------------------------------------------
// MODIFIABLE                  MODIFIABLE               MODIFIABLE
//-----------------------------------------------------------------------
const char Yaw_MK1AppGroupName[] = "G_"APP_ID"App";
const char Yaw_MK1AppMenuName[] = "M_"APP_ID"AppMain";

//-----------------------------------------------------------------------
// IO VARIABLES                IO VARIABLES                IO VARIABLES
//-----------------------------------------------------------------------

void (*Yaw_MK1SetLockValues)(void);
struct os_db_alias *Yaw_MK1IOVars;
size_t Yaw_MK1IOVarsSize = 0;
            
struct os_db_alias Yaw_MK1IOVars1[]=
{
    VAR_ELEMENT_ALIAS("3.3.64",                           "AI_YawAbsoluteEncoderSignal"),
    VAR_ELEMENT_ALIAS("3.3.64_Ss",                        "AI_YawAbsoluteEncoderSignal_Ss"),
    VAR_ELEMENT_ALIAS("3.3.64_E",                         "AI_YawAbsoluteEncoderSignal_E"),
    VAR_ELEMENT_ALIAS( "3.3.64_Th",                        "AI_YawAbsoluteEncoderSignal_Th"),
    VAR_ELEMENT_ALIAS("3.3.64_Ht",                        "AI_YawAbsoluteEncoderSignal_Ht"),
    VAR_ELEMENT_ALIAS("3.3.64_S",                         "AI_YawAbsoluteEncoderSignal_S"),
    VAR_ELEMENT_ALIAS("3.3.64_O",                         "AI_YawAbsoluteEncoderSignal_O"),

};
size_t Yaw_MK1IOVars1Size = sizeof(Yaw_MK1IOVars1)/sizeof(Yaw_MK1IOVars1[0]);

void Yaw_MK1SetLockValues1(void)
{
   SetLockValue("AI_YawAbsoluteEncoderSignal_Ss",        TYP_8,     1);
   SetLockValue("AI_YawAbsoluteEncoderSignal_E",         TYP_8,     1);
   SetLockValue("AI_YawAbsoluteEncoderSignal_Th",        TYP_16,    1);
   SetLockValue("AI_YawAbsoluteEncoderSignal_Ht",        TYP_32,    100);
   SetLockValue("AI_YawAbsoluteEncoderSignal_S",         TYP_32,    0);
   SetValue("AI_YawAbsoluteEncoderSignal_O",             TYP_32,    0);
}


STATUS Yaw_MK1InitIOAliases()
{
   Yaw_MK1IOVars = Yaw_MK1IOVars1;
   Yaw_MK1IOVarsSize = Yaw_MK1IOVars1Size;
   Yaw_MK1SetLockValues = &Yaw_MK1SetLockValues1;
   return OS_SUCCESS;
}
//-----------------------------------------------------------------------
// AUTOGENERATED END        AUTOGENERATED END        AUTOGENERATED END
//-----------------------------------------------------------------------

#undef AUTOGENERATED_PART
