//*****************************PEPTOOL Header Start******************************
//                                                                               
//                         Copyright © 2019 Mita-Teknik.                         
// This software may only be used with the Controllers delivered by Mita-Teknik  
//                                                                               
//*******************************************************************************
//                                                                               
// $PEPTOOL version:9.0$                                                         
// $PEPTOOL file version:106$                                                    
//                                                                               
//*******************************************************************************
//                                                                               
// $Date: XXXX/XX/XX XX:XX:XX $                                                  
// $Author: XXXX\XXX $                                                           
// $RCSfile: StatusCodes_Eleon.c,v $                                             
// $Revision: X.X $                                                              
//                                                                               
//******************************PEPTOOL Header End*******************************

//***********************************************************************

// OS header files
#include <os_main.h>
// AppLib header files
#include <lib_main.h>
// App header files
#include <turbdef.h>
#include <VarMacros.h>

// Object header file
#include <StatusCodes_Eleon.h>
#include <Mita.h>   //provides OS Api function declarations
#include <List.h>
#define APP_ID "0"
#define AUTOGENERATED_PART
//{
//-----------------------------------------------------------------------
// AUTOGENERATED START     AUTOGENERATED START     AUTOGENERATED START
//-----------------------------------------------------------------------

#define VALIDATE_HASH
char StatusCodes_Eleon_copyright[] =
{
   67, 111, 112, 121, 114, 105, 103, 104, 116, 32, 63, 32, 50, 48, 49, 57,
   32, 77, 105, 116, 97, 45, 84, 101, 107, 110, 105, 107, 46, 13, 10, 84,
   104, 105, 115, 32, 115, 111, 102, 116, 119, 97, 114, 101, 32, 109, 97, 121,
   32, 111, 110, 108, 121, 32, 98, 101, 32, 117, 115, 101, 100, 32, 119, 105,
   116, 104, 32, 116, 104, 101, 32, 67, 111, 110, 116, 114, 111, 108, 108, 101,
   114, 115, 32, 100, 101, 108, 105, 118, 101, 114, 101, 100, 32, 98, 121, 32,
   77, 105, 116, 97, 45, 84, 101, 107, 110, 105, 107, 0
};

#define MODULE_NAME "Status CodesA"

//-----------------------------------------------------------------------
// ALLOCATE MEMORY FOR STRINGS IN VARDB
//-----------------------------------------------------------------------

static char A_STS_DetailMenu_Name[31] = "12345678901234567890123456789";

//-----------------------------------------------------------------------
// DEFINE LOCAL VARIABLES DEFINE LOCAL VARIABLES DEFINE LOCAL VARIABLES
//-----------------------------------------------------------------------

static struct os_db_local LocalVars[] =
{
   VAR_ELEMENT_LOCAL("SYSTEM_STS_NoOfActiveStsCodes",            TYPE_U16,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         SCALE_NONE,   0,       UNIT_COUNT,         0,   0,               U16_MIN,         U16_MAX,         NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("SYSTEM_STS_NoOfStsCodes",                  TYPE_U16,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         SCALE_NONE,   0,       UNIT_COUNT,         0,   0,               U16_MIN,         U16_MAX,         NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_ActiveControlProgram1",                  TYPE_U8,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         SCALE_NONE,   0,       UNIT_NONE,          0,   0,               U8_MIN,          U8_MAX,          NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_ActiveControlProgram2",                  TYPE_U8,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         SCALE_NONE,   0,       UNIT_NONE,          0,   0,               U8_MIN,          U8_MAX,          NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_ActiveControlProgram3",                  TYPE_U8,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         SCALE_NONE,   0,       UNIT_NONE,          0,   0,               U8_MIN,          U8_MAX,          NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_ActiveCP1CodeNo",                        TYPE_U16,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         SCALE_NONE,   0,       UNIT_NONE,          0,   0,               U16_MIN,         U16_MAX,         NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_ActiveCP2CodeNo",                        TYPE_U16,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         SCALE_NONE,   0,       UNIT_NONE,          0,   0,               U16_MIN,         U16_MAX,         NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_ActiveCP3CodeNo",                        TYPE_U16,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         SCALE_NONE,   0,       UNIT_NONE,          0,   0,               U16_MIN,         U16_MAX,         NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("STS_DetailMenu_Name",                      TYPE_STRING + sizeof(A_STS_DetailMenu_Name) - 1,  PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         SCALE_NONE,   0,       UNIT_NONE,          0,   A_STS_DetailMenu_Name, 0,                0,                NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("STS_DetailMenu_Enabled",                   TYPE_U8,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         SCALE_NONE,   0,       UNIT_NONE,          0,   0,               U8_MIN,          U8_MAX,          NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("STS_DetailMenu_Number",                    TYPE_U16,     PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         SCALE_NONE,   0,       UNIT_NONE,          0,   0,               U16_MIN,         U16_MAX,         NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("STS_DetailMenu_CurrentState",              TYPE_U8,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         SCALE_NONE,   0,       UNIT_NONE,          0,   0,               U8_MIN,          U8_MAX,          NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("STS_DetailMenu_BrakeProgram",              TYPE_U8,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         SCALE_NONE,   0,       UNIT_NONE,          0,   0,               U8_MIN,          U8_MAX,          NULL,  NOLOG_ENABLE),
   VAR_ELEMENT_LOCAL("V_ResetButtonState",                       TYPE_U8,      PASSWORD_LEVEL_END_CUSTOMER,       PASSWORD_LEVEL_SUPERVISOR,         SCALE_NONE,   0,       UNIT_NONE,          0,   0,               U8_MIN,          U8_MAX,          NULL,  NOLOG_ENABLE),
};

//-----------------------------------------------------------------------
// DEFINE PARAMETERS        DEFINE PARAMETERS        DEFINE PARAMETERS
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// DEFINE BACKUPS            DEFINE BACKUPS            DEFINE BACKUPS
//-----------------------------------------------------------------------

//----------------------------------------------------------------------------------
// DEFINE VAR ARRAYS            DEFINE VAR ARRAYS            DEFINE VAR ARRAYS
//----------------------------------------------------------------------------------
char StatusCodes_Eleon_initialValues[] =
{
   25, 86, 45, 212, 227, 78, 79, 119, 169, 236, 146, 87, 30, 239, 46, 86,
   160, 205, 129, 178, 223, 129, 239, 151, 85, 207, 125, 220, 46, 215, 184, 250,
   0
};

//-----------------------------------------------------------------------
// CREATE DATABASE VARS   CREATE DATABASE VARS   CREATE DATABASE VARS
//-----------------------------------------------------------------------

static STATUS CreateVarDbVars(void)
{
	STATUS Status;
	size_t ErrorEntry;

	Status = OS_VarDB_CreateLocals(LocalVars, sizeof(LocalVars) / sizeof(LocalVars[0]), &ErrorEntry, AppLocalParameterPosition());
	if (Status != 0)
	{
		AppSystemLog(ERR_7, MODULE_NAME"CrVL: %d,%d", Status, ErrorEntry);
		return ERR_7;
	}

	return OS_SUCCESS;
}

#define CREATE_VARDB_VARS

//-----------------------------------------------------------------------
// CREATE IO VARIABLES     CREATE IO VARIABLES     CREATE IO VARIABLES
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// ALIASES                       ALIASES                       ALIASES
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// INPUT                          INPUT                          INPUT
//-----------------------------------------------------------------------

// Create local variable
#define MODUL_INPUTS
static U8 STS_DetailMenu_Enabled = 0;
static U16 STS_DetailMenu_Number = 0;
static U8 STS_DetailMenu_BrakeProgram = 0;
static U8 V_ResetButtonState = 0;

//-----------------------------------------------------------------------
static struct ModulInOut ModulInputs[] =
{
   {"STS_DetailMenu_Enabled",                   &STS_DetailMenu_Enabled,                   sizeof(STS_DetailMenu_Enabled),                   },
   {"STS_DetailMenu_Number",                    &STS_DetailMenu_Number,                    sizeof(STS_DetailMenu_Number),                    },
   {"STS_DetailMenu_BrakeProgram",              &STS_DetailMenu_BrakeProgram,              sizeof(STS_DetailMenu_BrakeProgram),              },
   {"V_ResetButtonState",                       &V_ResetButtonState,                       sizeof(V_ResetButtonState),                       },
};

//-----------------------------------------------------------------------
// Check variable type
static STATUS VarsReadReturnStatus;
static type_t ReadVarType = TYPE_NONE;
static void VarsReadTypeCheck(void)
{
	(void)VarsReadReturnStatus;
	(void)ReadVarType;
	VERIFY_INPUT_REF_ID(U8, ModulInputs[0].Name, ModulInputs[0].Id)
		VERIFY_INPUT_REF_ID(U16, ModulInputs[1].Name, ModulInputs[1].Id)
		VERIFY_INPUT_REF_ID(U8, ModulInputs[2].Name, ModulInputs[2].Id)
		VERIFY_INPUT_REF_ID(U8, ModulInputs[3].Name, ModulInputs[3].Id)
}

#undef MODUL_INPUTS
#define MODUL_INPUTS_SIZE (sizeof(ModulInputs)/sizeof(ModulInputs[0]))

//------------------------------------------------------------------------------------------
// READ/WRITE VARDB ARRAY      READ/WRITE VARDB ARRAY      READ/WRATE VARDB ARRAY
//------------------------------------------------------------------------------------------


//-----------------------------------------------------------------------
// PARAMETER                    PARAMETER                    PARAMETER
//-----------------------------------------------------------------------


//-----------------------------------------------------------------------
// READ VARS FROM VARDB    READ VARS FROM VARDB    READ VARS FROM VARDB
//-----------------------------------------------------------------------

static STATUS InputReferenceRoutine(U8 ModuleState)
{
	STATUS LocalStatus = 0;

	// Read input references
	if (ModuleState >= APP_INIT3)
	{
		// Check inputdata
		if (sizeof(ModulInputs) == 0)
		{
			AppSystemLog(ERR_4, MODULE_NAME"ModuleInputs = 0");
			return ERR_4;
		}
		// Read inputdata
		LocalStatus = OS_ReadVariables(ModulInputs, MODUL_INPUTS_SIZE);
		if (LocalStatus != 0)
		{
			AppSystemLog(ERR_4, MODULE_NAME"ReadVErr: element=%d elementpointer=0x%x", LocalStatus, &ModulInputs[LocalStatus]);
			return ERR_4;
		}
	}
	return 0;
}

#define READ_VARS

//-----------------------------------------------------------------------
// OUTPUT                         OUTPUT                         OUTPUT
//-----------------------------------------------------------------------

// Create local variable
#define MODUL_OUTPUTS
static U8 V_ActiveControlProgram1 = 0;
static U8 V_ActiveControlProgram2 = 0;
static U8 V_ActiveControlProgram3 = 0;
static U16 V_ActiveCP1CodeNo = 0;
static U16 V_ActiveCP2CodeNo = 0;
static U16 V_ActiveCP3CodeNo = 0;
static U16 SYSTEM_STS_NoOfActiveStsCodes = 0;
static U16 SYSTEM_STS_NoOfStsCodes = 0;
static U8 STS_DetailMenu_CurrentState = 0;
static char STS_DetailMenu_Name[31];


//-----------------------------------------------------------------------
static struct ModulInOut ModulOutputs[] =
{
   {"V_ActiveControlProgram1",                  &V_ActiveControlProgram1,                  sizeof(V_ActiveControlProgram1),                  },
   {"V_ActiveControlProgram2",                  &V_ActiveControlProgram2,                  sizeof(V_ActiveControlProgram2),                  },
   {"V_ActiveControlProgram3",                  &V_ActiveControlProgram3,                  sizeof(V_ActiveControlProgram3),                  },
   {"V_ActiveCP1CodeNo",                        &V_ActiveCP1CodeNo,                        sizeof(V_ActiveCP1CodeNo),                        },
   {"V_ActiveCP2CodeNo",                        &V_ActiveCP2CodeNo,                        sizeof(V_ActiveCP2CodeNo),                        },
   {"V_ActiveCP3CodeNo",                        &V_ActiveCP3CodeNo,                        sizeof(V_ActiveCP3CodeNo),                        },
   {"SYSTEM_STS_NoOfActiveStsCodes",            &SYSTEM_STS_NoOfActiveStsCodes,            sizeof(SYSTEM_STS_NoOfActiveStsCodes),            },
   {"SYSTEM_STS_NoOfStsCodes",                  &SYSTEM_STS_NoOfStsCodes,                  sizeof(SYSTEM_STS_NoOfStsCodes),                  },
   {"STS_DetailMenu_Name",                      &STS_DetailMenu_Name,                      sizeof(STS_DetailMenu_Name),                      },
   {"STS_DetailMenu_Enabled",                   &STS_DetailMenu_Enabled,                   sizeof(STS_DetailMenu_Enabled),                   },
   {"STS_DetailMenu_Number",                    &STS_DetailMenu_Number,                    sizeof(STS_DetailMenu_Number),                    },
   {"STS_DetailMenu_CurrentState",              &STS_DetailMenu_CurrentState,              sizeof(STS_DetailMenu_CurrentState),              },
   {"STS_DetailMenu_BrakeProgram",              &STS_DetailMenu_BrakeProgram,              sizeof(STS_DetailMenu_BrakeProgram),              },
   {"V_ResetButtonState",                       &V_ResetButtonState,                       sizeof(V_ResetButtonState),                       },
};

//-----------------------------------------------------------------------
// Check variable type
static STATUS VarsWriteReturnStatus;
static type_t WriteVarType = TYPE_NONE;
static void VarsWriteTypeCheck(void)
{
	(void)VarsWriteReturnStatus;
	(void)WriteVarType;
	VERIFY_OUTPUT_REF_ID(U8, ModulOutputs[0].Name, ModulOutputs[0].Id, 0)
		VERIFY_OUTPUT_REF_ID(U8, ModulOutputs[1].Name, ModulOutputs[1].Id, 0)
		VERIFY_OUTPUT_REF_ID(U8, ModulOutputs[2].Name, ModulOutputs[2].Id, 0)
		VERIFY_OUTPUT_REF_ID(U16, ModulOutputs[3].Name, ModulOutputs[3].Id, 0)
		VERIFY_OUTPUT_REF_ID(U16, ModulOutputs[4].Name, ModulOutputs[4].Id, 0)
		VERIFY_OUTPUT_REF_ID(U16, ModulOutputs[5].Name, ModulOutputs[5].Id, 0)
		VERIFY_OUTPUT_REF_ID(U16, ModulOutputs[6].Name, ModulOutputs[6].Id, 0)
		VERIFY_OUTPUT_REF_ID(U16, ModulOutputs[7].Name, ModulOutputs[7].Id, 0)
		VERIFY_OUTPUT_STRING_REF_ID(STRING, ModulOutputs[8].Name, ModulOutputs[8].Id, 0)
		VERIFY_OUTPUT_REF_ID(U8, ModulOutputs[9].Name, ModulOutputs[9].Id, 0)
		VERIFY_OUTPUT_REF_ID(U16, ModulOutputs[10].Name, ModulOutputs[10].Id, 0)
		VERIFY_OUTPUT_REF_ID(U8, ModulOutputs[11].Name, ModulOutputs[11].Id, 0)
		VERIFY_OUTPUT_REF_ID(U8, ModulOutputs[12].Name, ModulOutputs[12].Id, 0)
		VERIFY_OUTPUT_REF_ID(U8, ModulOutputs[13].Name, ModulOutputs[13].Id, 0)
}

#undef MODUL_OUTPUTS
#define MODUL_OUTPUTS_SIZE (sizeof(ModulOutputs)/sizeof(ModulOutputs[0]))

//-----------------------------------------------------------------------
// WRITE VARS TO VARDB     WRITE VARS TO VARDB     WRITE VARS TO VARDB
//-----------------------------------------------------------------------

static STATUS InitOutputVars(void)
{
	STATUS LocalStatus;
	// Read outputdata
	LocalStatus = OS_ReadVariables(ModulOutputs, MODUL_OUTPUTS_SIZE);
	if (LocalStatus != 0)
	{
		AppSystemLog(ERR_4, MODULE_NAME"InitErr: element=%d elementpointer=0x%x", LocalStatus, &ModulOutputs[LocalStatus]);
		return ERR_4;
	}
	return OS_SUCCESS;
}
static STATUS OutputReferenceRoutine(U8 ModuleState)
{
	STATUS LocalStatus = 0;
	// Write Outputdata
	LocalStatus = OS_WriteVariablesConditional(ModulOutputs, MODUL_OUTPUTS_SIZE);
	if (LocalStatus != 0)
	{
		AppSystemLog(ERR_5, MODULE_NAME"WriteVErr: element=%d elementpointer=0x%x", LocalStatus, &ModulOutputs[LocalStatus]);
		return ERR_5;
	}
	return 0;
}

#define WRITE_VARS

//-----------------------------------------------------------------------
// VERIFY VARIABLES CREATION                 VERIFY VARIABLES CREATION
//-----------------------------------------------------------------------

static STATUS LocalIoCheck(void)
{
	// Check if input variables exist.
	STATUS LocalStatus;

	LocalStatus = OS_DoesVariablesExist(ModulInputs, MODUL_INPUTS_SIZE);
	if (LocalStatus != 0)
	{
		AppSystemLog(ERR_1, MODULE_NAME"InputErr: %d", LocalStatus);
		AppSystemLog(ERR_1, "Name: %s", ModulInputs[LocalStatus - 1].Name);
		return ERR_1;
	}
	(void)VarsReadTypeCheck();

	LocalStatus = OS_DoesVariablesExist(ModulOutputs, MODUL_OUTPUTS_SIZE);
	if (LocalStatus != 0)
	{
		AppSystemLog(ERR_2, MODULE_NAME"OutputErr: %d", LocalStatus);
		AppSystemLog(ERR_2, "Name: %s", ModulOutputs[LocalStatus - 1].Name);
		return ERR_2;
	}
	(void)VarsWriteTypeCheck();

	return OS_SUCCESS;
}

#define VERIFY_VARIABLES

//-----------------------------------------------------------------------
// ALLOCATE MEMORY FOR SUMMATIONS        ALLOCATE MEMORY FOR SUMMATIONS
//-----------------------------------------------------------------------


//-----------------------------------------------------------------------
// SUMMATIONS                  SUMMATIONS                  SUMMATIONS
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// DEFINE MENUS               DEFINE MENUS               DEFINE MENUS
//-----------------------------------------------------------------------



// Menu line and link to local menu
//-----------------------------------------------------------------------
static struct line_struct M_StatusCodesLinkToLocalMenu[] =
{
   MENU_ELEMENT_LINE_LINK("Status Codes",                      PASSWORD_LEVEL_END_CUSTOMER,        "M_StatusCodes",                    "G_StatusCodes_Eleon"),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_StatusCodesMenu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_StatusCodes",                    PASSWORD_LEVEL_END_CUSTOMER),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_StatusCodesMenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("STATUS CODES",                      PASSWORD_LEVEL_END_CUSTOMER,        "M_"APP_ID"AppMain",                "G_"APP_ID"App"),
   MENU_ELEMENT_LINE_LINK("Result",                            PASSWORD_LEVEL_END_CUSTOMER,        "M_Result",                         "G_StatusCodes_Eleon"),
   MENU_ELEMENT_LINE_LINK("Overview",                          PASSWORD_LEVEL_END_CUSTOMER,        "M_Overview",                       "G_StatusCodes_Eleon"),
   MENU_ELEMENT_LINE_LINK("Active",                            PASSWORD_LEVEL_END_CUSTOMER,        "M_Active",                         "G_StatusCodes_Eleon"),
   MENU_ELEMENT_LINE_LINK("Disabled",                          PASSWORD_LEVEL_END_CUSTOMER,        "M_Disabled",                       "G_StatusCodes_Eleon"),
   MENU_ELEMENT_LINE_LINK("Browse",                            PASSWORD_LEVEL_END_CUSTOMER,        "M_Browse",                         "G_StatusCodes_Eleon"),
   MENU_ELEMENT_LINE_LINK("Log",                               PASSWORD_LEVEL_END_CUSTOMER,        "M_Log",                            "G_StatusCodes_Eleon"),
   MENU_ELEMENT_LINE_LINK("Setup",                             PASSWORD_LEVEL_END_CUSTOMER,        "M_Setup",                          "G_StatusCodes_Eleon"),
   MENU_ELEMENT_LINE_VARRO("No Of Active Sts Codes",           PASSWORD_LEVEL_END_CUSTOMER,        (char*)"SYSTEM_STS_NoOfActiveStsCodes",              LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("No Of Sts Codes",                  PASSWORD_LEVEL_END_CUSTOMER,        (char*)"SYSTEM_STS_NoOfStsCodes",                    LINE_FORMAT_NONE),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_ResultMenu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_Result",                         PASSWORD_LEVEL_END_CUSTOMER),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_ResultMenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("RESULT",                            PASSWORD_LEVEL_END_CUSTOMER,        "M_StatusCodes",                    "G_StatusCodes_Eleon"),
   MENU_ELEMENT_LINE_VARRO("Brake Program",                    PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_ActiveControlProgram1",                    LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Status code : ",                   PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_ActiveCP1CodeNo",                   LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Yaw Program",                      PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_ActiveControlProgram2",                    LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Status code : ",                   PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_ActiveCP2CodeNo",                   LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Alarm Program",                    PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_ActiveControlProgram3",                    LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Status code : ",                   PASSWORD_LEVEL_END_CUSTOMER,        (char*)"V_ActiveCP3CodeNo",                   LINE_FORMAT_NONE),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_OverviewMenu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_Overview",                       PASSWORD_LEVEL_END_CUSTOMER),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_OverviewMenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("OVERVIEW",                          PASSWORD_LEVEL_END_CUSTOMER,        "M_StatusCodes",                    "G_StatusCodes_Eleon"),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_ActiveMenu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_Active",                         PASSWORD_LEVEL_END_CUSTOMER),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_ActiveMenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("ACTIVE",                            PASSWORD_LEVEL_END_CUSTOMER,        "M_StatusCodes",                    "G_StatusCodes_Eleon"),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_DisabledMenu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_Disabled",                       PASSWORD_LEVEL_END_CUSTOMER),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_DisabledMenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("DISABLED",                          PASSWORD_LEVEL_END_CUSTOMER,        "M_StatusCodes",                    "G_StatusCodes_Eleon"),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_BrowseMenu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_Browse",                         PASSWORD_LEVEL_END_CUSTOMER),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_BrowseMenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("BROWSE",                            PASSWORD_LEVEL_END_CUSTOMER,        "M_StatusCodes",                    "G_StatusCodes_Eleon"),
   MENU_ELEMENT_LINE_VARRW("Number",                           PASSWORD_LEVEL_END_CUSTOMER,        (char*)"STS_DetailMenu_Number",                      LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Name",                             PASSWORD_LEVEL_END_CUSTOMER,        (char*)"STS_DetailMenu_Name",                        LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Enabled Status",                   PASSWORD_LEVEL_END_CUSTOMER,        (char*)"STS_DetailMenu_Enabled",                     LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRO("Current State",                    PASSWORD_LEVEL_END_CUSTOMER,        (char*)"STS_DetailMenu_CurrentState",                LINE_FORMAT_NONE),
   MENU_ELEMENT_LINE_VARRW("Brake Program",                    PASSWORD_LEVEL_END_CUSTOMER,        (char*)"STS_DetailMenu_BrakeProgram",                LINE_FORMAT_NONE),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_LogMenu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_Log",                            PASSWORD_LEVEL_END_CUSTOMER),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_LogMenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("LOG",                               PASSWORD_LEVEL_END_CUSTOMER,        "M_StatusCodes",                    "G_StatusCodes_Eleon"),
};

// Local menu
//-----------------------------------------------------------------------
static struct menu_struct M_SetupMenu[] =
{
   MENU_ELEMENT_MENU_TEXT("M_Setup",                          PASSWORD_LEVEL_END_CUSTOMER),
};

// Menu lines
//-----------------------------------------------------------------------
static struct line_struct M_SetupMenuLines[] =
{
   MENU_ELEMENT_LINE_LINK("SETUP",                             PASSWORD_LEVEL_END_CUSTOMER,        "M_StatusCodes",                    "G_StatusCodes_Eleon"),
};
// Creating parameters for multiplexed categories
//-----------------------------------------------------------------------
static struct multiplexed_info_struct M_StatusCodesMultiplexedCategoriesParameters[] ={0};

//-----------------------------------------------------------------------
// CREATE MENUS               CREATE MENUS               CREATE MENUS
//-----------------------------------------------------------------------

// Memory reservation
//-----------------------------------------------------------------------
static struct menu_group_struct ObjGroup[1];

// Creating the menus
//-----------------------------------------------------------------------
STATUS StatusCodes_EleonMenuAppInit(U8 ModuleState, OS_MEMORY_POOL* pPool)
{
	STATUS Status;

	if (ModuleState == APP_INIT1)
	{
		/* Create application group */
		Status = OS_CreateMenuGroup(ObjGroup, M_StatusCodesLinkToLocalMenu[0].LinkGroup);
		STATUS_LINE_VAR_RETURN_VALUE(Status);
	}

	Status = CreateAndInitializeMenu(ModuleState,
		M_StatusCodesMenuLines[0].LinkGroup,
		M_StatusCodesMenuLines[0].LinkName,
		ELEMENT(M_StatusCodesLinkToLocalMenu),
		M_StatusCodesLinkToLocalMenu[0].LinkGroup,
		ELEMENT(M_StatusCodesMenu),
		M_StatusCodesLinkToLocalMenu[0].LinkName,
		ELEMENT(M_StatusCodesMenuLines),
		pPool,
		M_StatusCodesMultiplexedCategoriesParameters);
	STATUS_LINE_VAR_RETURN_VALUE(Status);

	Status = CreateAndInitializeMenu(ModuleState,
		M_ResultMenuLines[0].LinkGroup,
		M_ResultMenuLines[0].LinkName,
		NULL,
		0,
		M_StatusCodesMenuLines[1].LinkGroup,
		ELEMENT(M_ResultMenu),
		M_StatusCodesMenuLines[1].LinkName,
		ELEMENT(M_ResultMenuLines),
		pPool,
		M_StatusCodesMultiplexedCategoriesParameters);
	STATUS_LINE_VAR_RETURN_VALUE(Status);

	Status = CreateAndInitializeMenu(ModuleState,
		M_OverviewMenuLines[0].LinkGroup,
		M_OverviewMenuLines[0].LinkName,
		NULL,
		0,
		M_StatusCodesMenuLines[2].LinkGroup,
		ELEMENT(M_OverviewMenu),
		M_StatusCodesMenuLines[2].LinkName,
		ELEMENT(M_OverviewMenuLines),
		pPool,
		M_StatusCodesMultiplexedCategoriesParameters);
	STATUS_LINE_VAR_RETURN_VALUE(Status);

	Status = CreateAndInitializeMenu(ModuleState,
		M_ActiveMenuLines[0].LinkGroup,
		M_ActiveMenuLines[0].LinkName,
		NULL,
		0,
		M_StatusCodesMenuLines[3].LinkGroup,
		ELEMENT(M_ActiveMenu),
		M_StatusCodesMenuLines[3].LinkName,
		ELEMENT(M_ActiveMenuLines),
		pPool,
		M_StatusCodesMultiplexedCategoriesParameters);
	STATUS_LINE_VAR_RETURN_VALUE(Status);

	Status = CreateAndInitializeMenu(ModuleState,
		M_DisabledMenuLines[0].LinkGroup,
		M_DisabledMenuLines[0].LinkName,
		NULL,
		0,
		M_StatusCodesMenuLines[4].LinkGroup,
		ELEMENT(M_DisabledMenu),
		M_StatusCodesMenuLines[4].LinkName,
		ELEMENT(M_DisabledMenuLines),
		pPool,
		M_StatusCodesMultiplexedCategoriesParameters);
	STATUS_LINE_VAR_RETURN_VALUE(Status);

	Status = CreateAndInitializeMenu(ModuleState,
		M_BrowseMenuLines[0].LinkGroup,
		M_BrowseMenuLines[0].LinkName,
		NULL,
		0,
		M_StatusCodesMenuLines[5].LinkGroup,
		ELEMENT(M_BrowseMenu),
		M_StatusCodesMenuLines[5].LinkName,
		ELEMENT(M_BrowseMenuLines),
		pPool,
		M_StatusCodesMultiplexedCategoriesParameters);
	STATUS_LINE_VAR_RETURN_VALUE(Status);

	Status = CreateAndInitializeMenu(ModuleState,
		M_LogMenuLines[0].LinkGroup,
		M_LogMenuLines[0].LinkName,
		NULL,
		0,
		M_StatusCodesMenuLines[6].LinkGroup,
		ELEMENT(M_LogMenu),
		M_StatusCodesMenuLines[6].LinkName,
		ELEMENT(M_LogMenuLines),
		pPool,
		M_StatusCodesMultiplexedCategoriesParameters);
	STATUS_LINE_VAR_RETURN_VALUE(Status);

	Status = CreateAndInitializeMenu(ModuleState,
		M_SetupMenuLines[0].LinkGroup,
		M_SetupMenuLines[0].LinkName,
		NULL,
		0,
		M_StatusCodesMenuLines[7].LinkGroup,
		ELEMENT(M_SetupMenu),
		M_StatusCodesMenuLines[7].LinkName,
		ELEMENT(M_SetupMenuLines),
		pPool,
		M_StatusCodesMultiplexedCategoriesParameters);
	STATUS_LINE_VAR_RETURN_VALUE(Status);

	return OS_SUCCESS;
}

#define CREATE_MENU

//-----------------------------------------------------------------------
//               BUTTONS FUNCTIONS FORWARD DECLARATIONS
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// BUTTONS                       BUTTONS                      BUTTONS
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
//             SET/RESET FUNCTIONS FORWARD DECLARATIONS
//-----------------------------------------------------------------------
//-----------------------------------------------------------------------
// STATUSCODES                 STATUSCODES                 STATUSCODES
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// MODIFIABLE                  MODIFIABLE                   MODIFIABLE
//-----------------------------------------------------------------------

extern const char StatusCodes_EleonAppGroupName[];
extern const char StatusCodes_EleonAppMenuName[];

static void Init_Structures_From_Conf_File(void)
{
	M_StatusCodesMenuLines[0].LinkName = (char*)StatusCodes_EleonAppMenuName;
	M_StatusCodesMenuLines[0].LinkGroup = (char*)StatusCodes_EleonAppGroupName;
}

//-----------------------------------------------------------------------
// AUTOGENERATED END        AUTOGENERATED END        AUTOGENERATED END
//-----------------------------------------------------------------------
//}

#undef AUTOGENERATED_PART

//------------------------------------------------------------------
// User menu
//--------------------------------------------------------

// Menu lines
//-----------------------------------------------------------------------
	
	List StatusCodeMenus;

	//static int CreateMenuLineLinkForStatusCode() {

	  /* Create Application menu structure */
	//Status = OS_CreateMenus(groupname, newmenu, MenuElements);
	//if (Status != 0)
	//{
//		AppSystemLog(10, "Menu err %d", Status);
	//	return Status;
//	}

//}
	

//-----------------------------------------------------------------------
// USER DEFINITIONS         USER DEFINITIONS         USER DEFINITIONS
//-----------------------------------------------------------------------

#define SYSTEM_STS_TASK_SCANTIME 20
#define SYSTEM_STS_MAX_NUM_OF_STATUS_CODES 65535
  

static U16 SYSTEM_STS_NoOfStsCodeControlBlocks = 0;

static STATUS_CODE_CONTROL_BLOCK *OS_stsCodes; // main structure to hold all status codes;

static struct sts_statuscode_structure* OS_stsCodesArray[SYSTEM_STS_MAX_NUM_OF_STATUS_CODES];


static const char *modulesStsNameFormat[4] =
{
		"Sts%05d_CurrentState",
		"Sts%05d_Enable",
		"Sts%05d_SetDelay",
		"Sts%05d_ResetDelay"		
};



typedef struct StsInternalData
{
	U32 timer;
	U32 setTimer;
	U32 resetTimer;
	BOOL isActive;
	BOOL firstEntry;
	varid_t CurrentState;
	varid_t Enabled;
	varid_t SetDelay;
	varid_t ResetDelay;
	//struct menu_struct Menu;
	struct line_struct MenuLine;
	char displayText[31];

	struct line_struct LineforOverview;
	struct line_struct LineforActive;
	struct line_struct LineforDisabled;
	//struct line_struct M_ResultMenuLines[5];
	//struct line_struct M_ResultMenuLines[33];
	
} StsInternalData;

//-----------------------------------------------------------------------
// SET/RESET FUNCTIONS    SET/RESET FUNCTIONS    SET/RESET FUNCTIONS
//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// DRIVER FUNCTION         DRIVER FUNCTION         DRIVER FUNCTION
//-----------------------------------------------------------------------
  
//-----------------------------------------------------------------------
// INIT                   INIT                     INIT
//-----------------------------------------------------------------------
  
//-----------------------------------------------------------------------
// CONTROL                CONTROL                 CONTROL
//-----------------------------------------------------------------------





static STATUS GetStatusCodeStructure(U16 StatusCodeNo, struct sts_statuscode_structure ** statuscode) {

	STATUS_CODE_CONTROL_BLOCK * temp;
	if (OS_stsCodes == NULL) {
		return -1;
	}
	size_t i;
	temp = OS_stsCodes;
	do {
		for (i = 0; i < temp->entries; i++) {

			if (((struct sts_statuscode_structure *)temp->table)[i].StsStatuscodeNo == StatusCodeNo) {
				*statuscode = &((struct sts_statuscode_structure *)temp->table)[i];
				return 0;
			}

		}
		temp = temp->next;
	} while (temp != NULL);

	return -1;
}

S32 OS_ActivateStatusCode(U16 StatusCodeNo)
{
	STATUS LocalStatus = 0;
	struct sts_statuscode_structure *statuscode = OS_stsCodesArray[StatusCodeNo];

	((StsInternalData *)(statuscode->InternalData))->isActive = TRUE;
	OS_VarDB_UpdateU8(((StsInternalData *)(statuscode->InternalData))->CurrentState, TRUE);

	return 0;
}



static BOOL ResetAll = false;
static U8 ResetPasswordLevel;
static U8 ResetType;
void OS_StatusCodeResetAll(U8 ResetPswLevel, U8 ResetTyp) 
{
	ResetPasswordLevel = ResetPswLevel;
	ResetType = ResetTyp;
	ResetAll = true;
}

U16 OS_NoOfActiveStatusCodes(void)
{
	return SYSTEM_STS_NoOfActiveStsCodes;
}

U8 OS_StatusCodeActive(U16 StatusCodeNo) {
	if (OS_stsCodesArray[StatusCodeNo] != NULL && ((StsInternalData *)OS_stsCodesArray[StatusCodeNo]->InternalData)->isActive) {
		return 1;
	}
	return 0;
}

static struct line_struct* M_OverviewMenuLinesPointer;

static struct line_struct* M_ActiveMenuLinesPointer;
static BOOL LocalResetAll = FALSE;


int addLinesToOverViewMenu(struct sts_statuscode_structure * data) {
		int LocalStatus = 0;

		((StsInternalData *)(data->InternalData))->LineforOverview.MagicNumber = 0;
		((StsInternalData *)(data->InternalData))->LineforOverview.DisplayText = ((StsInternalData *)(data->InternalData))->displayText;
		((StsInternalData *)(data->InternalData))->LineforOverview.ViewPasswordLevel = PASSWORD_LEVEL_END_CUSTOMER;
		((StsInternalData *)(data->InternalData))->LineforOverview.Linetype = PACKTYPE_LINK;
		((StsInternalData *)(data->InternalData))->LineforOverview.LinkName = "M_Browse";
		((StsInternalData *)(data->InternalData))->LineforOverview.LinkGroup = "G_StatusCodes_Eleon";
		((StsInternalData *)(data->InternalData))->LineforOverview.VarName = "SYSYEM_STS_specialVariableNo"; // not real variable
		((StsInternalData *)(data->InternalData))->LineforOverview.Var_ID = &data->StsStatuscodeNo; // not real variable


	
	if (M_OverviewMenuLinesPointer == NULL) {

		M_OverviewMenuLinesPointer = &((StsInternalData *)(data->InternalData))->LineforOverview;
		((StsInternalData *)(data->InternalData))->LineforOverview.nextline = NULL;
		int test = 2;
	}
	else
	{
		M_OverviewMenuLinesPointer->nextline = M_OverviewMenuLinesPointer;
		M_OverviewMenuLinesPointer = &((StsInternalData *)(data->InternalData))->LineforOverview;
		((StsInternalData *)(data->InternalData))->LineforOverview.nextline = NULL;

	}
	LocalStatus = OS_AddLines("G_StatusCodes_Eleon", "M_Overview", &((StsInternalData *)(data->InternalData))->LineforOverview, 1);
	if (LocalStatus != 0)
	{
		AppSystemLog(20, "Menu err %d", LocalStatus);
		return LocalStatus;
	}

}
int addLinesToActiveMenu(struct sts_statuscode_structure * data) {
	int LocalStatus = 0;

	((StsInternalData *)(data->InternalData))->LineforActive.MagicNumber = 0;
	((StsInternalData *)(data->InternalData))->LineforActive.DisplayText = ((StsInternalData *)(data->InternalData))->displayText;
	((StsInternalData *)(data->InternalData))->LineforActive.ViewPasswordLevel = PASSWORD_LEVEL_END_CUSTOMER;
	((StsInternalData *)(data->InternalData))->LineforActive.Linetype = PACKTYPE_LINK;
	((StsInternalData *)(data->InternalData))->LineforActive.LinkName = "M_Browse";
	((StsInternalData *)(data->InternalData))->LineforActive.LinkGroup = "G_StatusCodes_Eleon";
	((StsInternalData *)(data->InternalData))->LineforActive.VarName="SYSYEM_STS_specialVariableNo"; // not real variable
	((StsInternalData *)(data->InternalData))->LineforActive.Var_ID = &data->StsStatuscodeNo; // not real variable

}

int addLinesToDisabledMenu(struct sts_statuscode_structure * data) {
	int LocalStatus = 0;

	((StsInternalData *)(data->InternalData))->LineforDisabled.MagicNumber = 0;
	((StsInternalData *)(data->InternalData))->LineforDisabled.DisplayText = ((StsInternalData *)(data->InternalData))->displayText;
	((StsInternalData *)(data->InternalData))->LineforDisabled.ViewPasswordLevel = PASSWORD_LEVEL_END_CUSTOMER;
	((StsInternalData *)(data->InternalData))->LineforDisabled.Linetype = PACKTYPE_LINK;
	((StsInternalData *)(data->InternalData))->LineforDisabled.LinkName = "M_Browse";
	((StsInternalData *)(data->InternalData))->LineforDisabled.LinkGroup = "G_StatusCodes_Eleon";
	((StsInternalData *)(data->InternalData))->LineforDisabled.VarName = "SYSYEM_STS_specialVariableNo"; // not real variable
	((StsInternalData *)(data->InternalData))->LineforDisabled.Var_ID = &data->StsStatuscodeNo; // not real variable

}


static int CreateMenuStatusCodeStructure(struct sts_statuscode_structure * data) {
	StsInternalData * internalData = (StsInternalData *)(data->InternalData);
	internalData->MenuLine.MagicNumber = 0;
	internalData->MenuLine.DisplayText = data->StsText;
	internalData->MenuLine.ViewPasswordLevel = PASSWORD_LEVEL_END_CUSTOMER;
	internalData->MenuLine.Linetype = PACKTYPE_LINK;
	internalData->MenuLine.menulink = "M_Browse";
	internalData->MenuLine.LinkGroup = "G_StatusCodes_Eleon";

	
	return 0;
}

STATUS OS_StatusCodeInit(int InterfaceVersion, STATUS_CODE_CONTROL_BLOCK *ControlBlock, struct sts_statuscode_structure *InitTable,
	size_t Size, const char *ParamameterFile, const char *BackupFile)
{
	size_t i;

	struct os_db_local* newdatabasevar;
	size_t ErrorEntry = 0;
	static struct os_db_local LocalnewVars[1];
	int result = 0;
	for (i = 0; i < Size; i++) {
		//add module sts
		int result = OS_Allocate_Memory(GetMemPool(), &(((struct sts_statuscode_structure *)InitTable)[i].InternalData), sizeof(StsInternalData), OS_NO_SUSPEND);
		if (result != OS_SUCCESS) { return NULL; }
		((StsInternalData *)(((struct sts_statuscode_structure *)InitTable)[i].InternalData))->timer = 0;
		((StsInternalData*)(((struct sts_statuscode_structure*)InitTable)[i].InternalData))->setTimer = 0;
		((StsInternalData*)(((struct sts_statuscode_structure*)InitTable)[i].InternalData))->resetTimer = 0;

		((StsInternalData *)(((struct sts_statuscode_structure *)InitTable)[i].InternalData))->isActive = false;
		((StsInternalData *)(((struct sts_statuscode_structure *)InitTable)[i].InternalData))->firstEntry = true;
		
		sprintf(((StsInternalData *)(((struct sts_statuscode_structure *)InitTable)[i].InternalData))->displayText, "%d %s", InitTable[i].StsStatuscodeNo, InitTable[i].StsText);
		
		
		CreateMenuStatusCodeStructure(&InitTable[i]);
		addLinesToOverViewMenu(&InitTable[i]);
		addLinesToActiveMenu(&InitTable[i]);
		addLinesToDisabledMenu(&InitTable[i]);
		int scnt;
		for (scnt = 0; scnt < sizeof(modulesStsNameFormat) / sizeof(modulesStsNameFormat[0]); scnt++) {

			//Sts00100_CurrentState
			
			result = OS_Allocate_Memory(GetMemPool(), &newdatabasevar, sizeof(struct os_db_local), OS_NO_SUSPEND);
			if (result != OS_SUCCESS) { return NULL; }

			result = OS_Allocate_Memory(GetMemPool(), &newdatabasevar->c.Name, 30, OS_NO_SUSPEND);
			if (result != OS_SUCCESS) { return NULL; }


			newdatabasevar->c.MagicNumber = VAR_MAGIC_NUMBER;
			newdatabasevar->c.HashValue = 0;
			newdatabasevar->c.NextName = NULL;

			snprintf(newdatabasevar->c.Name, 30, modulesStsNameFormat[scnt], InitTable[i].StsStatuscodeNo);


			newdatabasevar->c.ScaleType = SCALE_NONE;
			newdatabasevar->c.ScaleValue = 0;
			newdatabasevar->c.Unit = UNIT_NONE;
			newdatabasevar->c.Precision = 0;
			if (scnt == 0) {

				newdatabasevar->c.Type = TYPE_U8;
				newdatabasevar->c.AccessRead = 200;
				newdatabasevar->c.AccessWrite = 200;
				((StsInternalData *)(((struct sts_statuscode_structure *)InitTable)[i].InternalData))->CurrentState = newdatabasevar;
				newdatabasevar->c.ScaleType = (scaletype_t)0;  /* DisplayScaleType */      \
				newdatabasevar->c.ScaleValue = (scalevalue_t)0;   /* DisplayScaleValue */     \
				newdatabasevar->c.DisplayUnit = (unit_t)0;        /* DisplayUnit */           \
				newdatabasevar->c.DisplayPrecision = 0;                 /* DisplayPrecision*/       \
				newdatabasevar->c.Value.u8 = ((StsInternalData *)(((struct sts_statuscode_structure *)InitTable)[i].InternalData))->isActive;
			}
			else if (scnt == 1) {

				newdatabasevar->c.Type = TYPE_U8;
				newdatabasevar->c.AccessRead = InitTable[i].StsCodeEnableAccessRead;
				newdatabasevar->c.AccessWrite = InitTable[i].StsCodeEnableAccessWrite;
				((StsInternalData *)(((struct sts_statuscode_structure *)InitTable)[i].InternalData))->Enabled = newdatabasevar;
				newdatabasevar->c.ScaleType = (scaletype_t)0;  /* DisplayScaleType */      \
				newdatabasevar->c.ScaleValue = (scalevalue_t)0;   /* DisplayScaleValue */     \
				newdatabasevar->c.DisplayUnit = (unit_t)0;        /* DisplayUnit */           \
				newdatabasevar->c.DisplayPrecision = 0;                 /* DisplayPrecision*/       \
				newdatabasevar->c.Value.u8 = InitTable[i].StsCodeEnable;
			}
			else if (scnt == 2) {

				newdatabasevar->c.Type = TYPE_U32;
				newdatabasevar->c.AccessRead = InitTable[i].StsSetDelayAccessRead;
				newdatabasevar->c.AccessWrite = InitTable[i].StsSetDelayAccessWrite;
				((StsInternalData *)(((struct sts_statuscode_structure *)InitTable)[i].InternalData))->SetDelay = newdatabasevar;
				newdatabasevar->c.ScaleType = SCALE_DIV;  /* DisplayScaleType */      \
				newdatabasevar->c.ScaleValue = 1000;   /* DisplayScaleValue */     \
				newdatabasevar->c.Unit = UNIT_NONE;       /* DisplayUnit */           \
				newdatabasevar->c.Precision = 3;                 /* DisplayPrecision*/       \
			


				newdatabasevar->c.Value.u32 = InitTable[i].StsSetDelay;
			}
			else if (scnt == 3) {

				newdatabasevar->c.Type = TYPE_U32;
				newdatabasevar->c.AccessRead = InitTable[i].StsResetDelayAccessRead;
				newdatabasevar->c.AccessWrite = InitTable[i].StsResetDelayAccessWrite;
				((StsInternalData *)(((struct sts_statuscode_structure *)InitTable)[i].InternalData))->ResetDelay = newdatabasevar;
				newdatabasevar->c.ScaleType = SCALE_DIV;	/* DisplayScaleType */      \
				newdatabasevar->c.ScaleValue = 1000;		/* DisplayScaleValue */     \
				newdatabasevar->c.Unit = UNIT_NONE;			/* DisplayUnit */           \
				newdatabasevar->c.Precision = 3;            /* DisplayPrecision*/       \



				newdatabasevar->c.Value.u32 = InitTable[i].StsResetDelay;
			}
			newdatabasevar->c.TimeStamp = NOLOG_ENABLE;
			
			newdatabasevar->c.Update = (enum update)LOCAL;		/* Update type */           \
			newdatabasevar->c.FirstSubscriber = NULL;           /* FirstSubscriber */       \
			newdatabasevar->c.PreviousVariable = NULL;          /* PreviousVariable */      \
			newdatabasevar->c.NextVariable = NULL;              /* NextVariable */          \
			newdatabasevar->c.ActiveReaders = 0;				/* ActiveReaders */         \
			newdatabasevar->c.OldValueBeingRead = 0;            /* OldValueBeingRead */     \
			newdatabasevar->c.TotalLogID = 0;					/* TotalLogID */            \
			newdatabasevar->c.FiveMinLogID = 0;					/* 5 min log ID */          \
			newdatabasevar->l.LogFlags = NULL;
			newdatabasevar->l.Minimum.string = 0;
			newdatabasevar->l.Maximum.string = 0;
			newdatabasevar->l.Lists = NULL;

			LocalnewVars[0] = *newdatabasevar;
			result = OS_VarDB_CreateLocals(newdatabasevar, 1, &ErrorEntry, AppLocalParameterPosition());
			if (result != 0)
			{
				AppSystemLog(7, "module add failed: %d", result);
			}
			if (scnt == 0) {

				//((StsInternalData *)(((struct sts_statuscode_structure *)InitTable)[i].InternalData))->CurrentState = newdatabasevar;
				//newdatabasevar->c.Value.u8 = ((StsInternalData *)(((struct sts_statuscode_structure *)InitTable)[i].InternalData))->isActive;
			}
			else if (scnt == 1) {
				InitTable[i].StsCodeEnable = newdatabasevar->c.Value.u8;
			}
			else if (scnt == 2) {InitTable[i].StsSetDelay = newdatabasevar->c.Value.u32;}
			else if (scnt == 3) { InitTable[i].StsResetDelay = newdatabasevar->c.Value.u32; }

		}
		if (OS_stsCodesArray[(InitTable)[i].StsStatuscodeNo] != NULL) {
			return ERR_STATUSCODE_DUPLICATE;
		}
		OS_stsCodesArray[(InitTable)[i].StsStatuscodeNo] = &InitTable[i];
		SYSTEM_STS_NoOfStsCodes++;

	}

	ControlBlock->table = InitTable;
	ControlBlock->entries = Size;

	if (OS_stsCodes == NULL) {
		OS_stsCodes = ControlBlock;
	}
	else {
		ControlBlock->next = OS_stsCodes;
		OS_stsCodes = ControlBlock;
	}

	SYSTEM_STS_NoOfStsCodeControlBlocks++;



	return 0;

}




S32 OS_StatusCodeResetAutomatic(U16 StatusCodeNo)
{
	if (((StsInternalData *)OS_stsCodesArray[StatusCodeNo]->InternalData)->isActive)
	{
		((StsInternalData*)OS_stsCodesArray[StatusCodeNo]->InternalData)->resetTimer = 0;
		((StsInternalData*)OS_stsCodesArray[StatusCodeNo]->InternalData)->setTimer = 0;
		((StsInternalData *)OS_stsCodesArray[StatusCodeNo]->InternalData)->isActive = FALSE;
		OS_VarDB_UpdateU8(((StsInternalData *)(OS_stsCodesArray[StatusCodeNo]->InternalData))->CurrentState, FALSE);
	}

	return 0;
}




S32 OS_StatusCodeSetAutomatic(U16 StatusCodeNo)
{
	if (!((StsInternalData *)OS_stsCodesArray[StatusCodeNo]->InternalData)->isActive)
	{
		((StsInternalData*)OS_stsCodesArray[StatusCodeNo]->InternalData)->resetTimer = 0;
		((StsInternalData*)OS_stsCodesArray[StatusCodeNo]->InternalData)->setTimer = 0;
		((StsInternalData *)OS_stsCodesArray[StatusCodeNo]->InternalData)->isActive = TRUE;
		OS_VarDB_UpdateU8(((StsInternalData *)(OS_stsCodesArray[StatusCodeNo]->InternalData))->CurrentState, TRUE);
	}

	return 0;
}


void OS_StatusCodeSetReset(U16 StatusCodeNo)
{	
	if (OS_stsCodesArray[StatusCodeNo] != NULL)
	{
		((StsInternalData*)OS_stsCodesArray[StatusCodeNo]->InternalData)->resetTimer = 0;
		((StsInternalData*)OS_stsCodesArray[StatusCodeNo]->InternalData)->setTimer = 0;
		((StsInternalData *)OS_stsCodesArray[StatusCodeNo]->InternalData)->isActive = !((StsInternalData *)OS_stsCodesArray[StatusCodeNo]->InternalData)->isActive;
		OS_VarDB_UpdateU8(((StsInternalData *)OS_stsCodesArray[StatusCodeNo]->InternalData)->CurrentState, ((StsInternalData *)OS_stsCodesArray[StatusCodeNo]->InternalData)->isActive);
	}
}
#pragma endregion   //end----------------------------------------------------------------------------------------------------
static BOOL firstEntryToActiceStatusCodes;

static int AddToActiveMenu(BOOL firstEntry, struct sts_statuscode_structure  *data){
	
	if (firstEntry)
	{
		M_ActiveMenuLines[0].nextline = &((StsInternalData *)(data->InternalData))->LineforActive;
		M_ActiveMenu[0].Type.Text.last_line = &((StsInternalData *)(data->InternalData))->LineforActive;
		M_ActiveMenu[0].Type.Text.NoOfLines = 2;
	}else{
		M_ActiveMenu[0].Type.Text.last_line->nextline = &((StsInternalData *)(data->InternalData))->LineforActive;
		M_ActiveMenu[0].Type.Text.last_line = &((StsInternalData *)(data->InternalData))->LineforActive;
		M_ActiveMenu[0].Type.Text.NoOfLines++;
	}
	((StsInternalData *)(data->InternalData))->LineforActive.nextline = NULL;

}

static BOOL firstEntryToDisabledStatusCodes;

static int AddToDisabledMenu(BOOL firstEntry, struct sts_statuscode_structure  *data) {

	if (firstEntry)
	{
		M_DisabledMenuLines[0].nextline = &((StsInternalData *)(data->InternalData))->LineforDisabled;
		M_DisabledMenu[0].Type.Text.last_line = &((StsInternalData *)(data->InternalData))->LineforDisabled;
		M_DisabledMenu[0].Type.Text.NoOfLines = 2;
	}
	else {
		M_DisabledMenu[0].Type.Text.last_line->nextline = &((StsInternalData *)(data->InternalData))->LineforDisabled;
		M_DisabledMenu[0].Type.Text.last_line = &((StsInternalData *)(data->InternalData))->LineforDisabled;
		M_DisabledMenu[0].Type.Text.NoOfLines++;
	}
	((StsInternalData *)(data->InternalData))->LineforDisabled.nextline = NULL;

}




static int Update_Polling(struct sts_statuscode_structure  *statuscode)
{
	U32 Updateinterval;

	if (((StsInternalData *)statuscode->InternalData)->firstEntry)
	{
		Updateinterval = statuscode->StsPowerUpDelay + statuscode->StsUpdateInterval;
	}
	else
	{
		Updateinterval = statuscode->StsUpdateInterval;
	}

	((StsInternalData *)statuscode->InternalData)->timer += SYSTEM_STS_TASK_SCANTIME;	// increment status code update timer
	if (((StsInternalData *)statuscode->InternalData)->timer >= Updateinterval)
	{
		if (((StsInternalData*)statuscode->InternalData)->firstEntry)
		{
			((StsInternalData*)statuscode->InternalData)->firstEntry = FALSE;
		}

		((StsInternalData *)statuscode->InternalData)->timer = 0;

		if (((StsInternalData *)statuscode->InternalData)->isActive)
		{
			if (statuscode->StsResetType == STATUSCODE_RESET_TYPE_AUTOMATIC)
			{
				if (statuscode->StsResetFunc != NULL)
				{
					if (statuscode->StsResetFunc())
					{
						U32 resetDelay = ((StsInternalData*)statuscode->InternalData)->SetDelay->c.Value.u32;
						((StsInternalData*)statuscode->InternalData)->setTimer += statuscode->StsUpdateInterval;
						if (((StsInternalData*)statuscode->InternalData)->resetTimer >= resetDelay)
						{
							((StsInternalData*)statuscode->InternalData)->isActive = FALSE;
							OS_VarDB_UpdateU8(((StsInternalData*)(statuscode->InternalData))->CurrentState, FALSE);
						}
					}
					else
					{
						((StsInternalData*)statuscode->InternalData)->resetTimer = 0;
					}
				}
				else
				{
					printf("STS Error - no ResetFunc exist for SC: %d", statuscode->StsStatuscodeNo);
				}
			}
			
		}
		else
		{
			if (statuscode->StsSetFunc != NULL)
			{
				if (statuscode->StsSetFunc())
				{
					U32 setDelay = ((StsInternalData*)statuscode->InternalData)->SetDelay->c.Value.u32;
					((StsInternalData*)statuscode->InternalData)->setTimer += statuscode->StsUpdateInterval;
					if (((StsInternalData*)statuscode->InternalData)->setTimer >= setDelay)
					{
						((StsInternalData*)statuscode->InternalData)->isActive = TRUE;
						OS_VarDB_UpdateU8(((StsInternalData*)(statuscode->InternalData))->CurrentState, TRUE);
					}
				}
				else
				{
					((StsInternalData*)statuscode->InternalData)->setTimer = 0;
				}
			}
			else
			{
				printf("STS Error - no SetFunc exist for SC: %d", statuscode->StsStatuscodeNo);
			}
		}
	}

	return 0;
}


static int ProcessStatusCode( struct sts_statuscode_structure  *statuscode)
{
	int  LocalStatus = 0;
	switch(statuscode->StsUpdateType) {
	case STATUSCODE_UPDATE_TYPE_POLLING: 
	//Status code of this type will be activated/deactivated by calling Set/Reset callback functions at StsUpdateInterval time intervals.
		LocalStatus = Update_Polling(statuscode);
		if (LocalStatus != 0) {
			return LocalStatus;
		}
		break;
	case STATUSCODE_UPDATE_TYPE_AUTOMATIC: 
		//Status code of this type can be activated by calling the Status Code System API functions
		//OS_StatusCodeSetAutomatic(statuscode->StsStatuscodeNo);
		//OS_StatusCodeResetAutomatic(statuscode->StsStatuscodeNo);

		break;
	case STATUSCODE_UPDATE_TYPE_REPEAT:
		//This type indicates that certain status code was activated a certain number of times.
		//TODO
		break;
	case STATUSCODE_UPDATE_TYPE_TIMEOUT:
		//This type indicates that certain status code was activated during a predefined period of time.
		//TODO
		break;
	}
	//Process active lines
	if (((StsInternalData *)statuscode->InternalData)->isActive && statuscode->StsCodeEnable) {
		if (V_ActiveControlProgram1 <= statuscode->StsControlProgram1) {
			V_ActiveControlProgram1 = statuscode->StsControlProgram1;
			if (statuscode->StsStatuscodeNo != 0) {
				V_ActiveCP1CodeNo = statuscode->StsStatuscodeNo;
			}

		}
		if (V_ActiveControlProgram2 <= statuscode->StsControlProgram2) {
			V_ActiveControlProgram2 = statuscode->StsControlProgram2;
			if (statuscode->StsStatuscodeNo != 0) {
				V_ActiveCP2CodeNo = statuscode->StsStatuscodeNo;
			}

		}
		if (V_ActiveControlProgram3 <= statuscode->StsControlProgram3) {
			V_ActiveControlProgram3 = statuscode->StsControlProgram3;
			if (statuscode->StsStatuscodeNo != 0) {
				V_ActiveCP3CodeNo = statuscode->StsStatuscodeNo;
			}

		}
			AddToActiveMenu(firstEntryToActiceStatusCodes, statuscode);
			firstEntryToActiceStatusCodes = false;
		
		SYSTEM_STS_NoOfActiveStsCodes++;

	}
	else if (!statuscode->StsCodeEnable) {

		AddToDisabledMenu(firstEntryToDisabledStatusCodes, statuscode);
		firstEntryToDisabledStatusCodes = false;
	}

	//try to reset if resetAll is Received
	if (LocalResetAll) 
	{

		if ( ((StsInternalData *)(statuscode->InternalData))->isActive && statuscode->StsResetPasswordLevel <= ResetPasswordLevel && statuscode->StsResetType >= ResetType )
		{
			((StsInternalData *)(statuscode->InternalData))->isActive = FALSE;
			((StsInternalData*)(statuscode->InternalData))->setTimer = 0;
			((StsInternalData*)(statuscode->InternalData))->resetTimer = 0;
			OS_VarDB_UpdateU8(((StsInternalData *)(statuscode->InternalData))->CurrentState, FALSE);
		}


	}

	return 0;
}

static int Process()
{
	int LocalStatus = 0;
	V_ActiveControlProgram1 = 0;
	V_ActiveControlProgram2 = 0;
	V_ActiveControlProgram3 = 0;
	SYSTEM_STS_NoOfActiveStsCodes = 0;

	if (V_ResetButtonState) {
		OS_StatusCodeResetAll(200, STATUSCODE_RESET_TYPE_DISPLAY);
	}
	if (ResetAll) {
		ResetAll = FALSE;
		LocalResetAll = TRUE;
	}

	STATUS_CODE_CONTROL_BLOCK * temp;
	if (OS_stsCodes == NULL) {
		return 0;
	}
	size_t i;
	temp = OS_stsCodes;
	firstEntryToActiceStatusCodes = TRUE;
	firstEntryToDisabledStatusCodes = TRUE;
	M_DisabledMenu[0].Type.Text.NoOfLines = 1;
	M_ActiveMenu[0].Type.Text.NoOfLines = 1;
	do {
		for (i = 0; i < temp->entries; i++) {
			LocalStatus =  ProcessStatusCode(&(((struct sts_statuscode_structure *)temp->table)[i]));

			if (LocalStatus != 0) {
				return LocalStatus;
			}
		}
		temp = temp->next;
	} while (temp != NULL);

	if (LocalResetAll) {
		LocalResetAll = FALSE;
	}

	return 0;
}

static U16 STS_DetailMenu_Number_Old = 5000;

 static int SetMenuDetailView(U16 Number) {


	STS_DetailMenu_Number = Number;
	if (STS_DetailMenu_Number != STS_DetailMenu_Number_Old)
	{
		STS_DetailMenu_Number_Old = STS_DetailMenu_Number;
		OS_Internal_MenuServer_ForceUpdateMenuLines();
		if (OS_stsCodesArray[Number] == NULL) {
			strcpy(STS_DetailMenu_Name, "No such status code");
			M_BrowseMenuLines[3].Linetype = PACKTYPE_TEXT;
			M_BrowseMenuLines[3].DisplayText = "";
			M_BrowseMenuLines[4].Linetype = PACKTYPE_TEXT;
			M_BrowseMenuLines[4].DisplayText = "";
			M_BrowseMenuLines[5].Linetype = PACKTYPE_TEXT;
			M_BrowseMenuLines[5].DisplayText = "";
			return;
		}
		M_BrowseMenuLines[3].Linetype = PACKTYPE_LINK_VAR_RW;
		M_BrowseMenuLines[3].DisplayText = "Enabled Status";
		M_BrowseMenuLines[4].Linetype = PACKTYPE_LINK_VAR_RO;
		M_BrowseMenuLines[4].DisplayText = "Current State";
		M_BrowseMenuLines[5].Linetype = PACKTYPE_LINK_VAR_RW;
		M_BrowseMenuLines[5].DisplayText = "Brake Program";

	strcpy(STS_DetailMenu_Name, OS_stsCodesArray[Number]->StsText);
	STS_DetailMenu_BrakeProgram = OS_stsCodesArray[Number]->StsControlProgram1;
	STS_DetailMenu_Enabled = OS_stsCodesArray[Number]->StsCodeEnable;
	STS_DetailMenu_CurrentState = ((StsInternalData *)OS_stsCodesArray[Number]->InternalData)->isActive;
		
	}
	if (OS_stsCodesArray[Number] != NULL) {
		if (OS_stsCodesArray[Number]->StsCodeEnable != STS_DetailMenu_Enabled) {
			OS_VarDB_UpdateU8(((StsInternalData *)OS_stsCodesArray[Number]->InternalData)->Enabled, STS_DetailMenu_Enabled);
			OS_stsCodesArray[Number]->StsCodeEnable = STS_DetailMenu_Enabled;
		}
		if (OS_stsCodesArray[Number]->StsControlProgram1 != STS_DetailMenu_BrakeProgram) {
			OS_stsCodesArray[Number]->StsControlProgram1 = STS_DetailMenu_BrakeProgram;
		}

	}


}

static STATUS LocalCtrl( U32 Interval )
{
	static BOOL firstEntry = true;
   STATUS LocalStatus = 0;

   LocalStatus= Process();
 if (LocalStatus != 0) {
	   return LocalStatus;
   }
	
 int i = 0;
   if(firstEntry) {
	   if (SYSTEM_STS_NoOfStsCodes > 0) {
		   for (i = 0; i < SYSTEM_STS_MAX_NUM_OF_STATUS_CODES; i++) {
			   if (OS_stsCodesArray[i] != NULL) {
				   STS_DetailMenu_Number = i;

			   }
		   }
		   firstEntry = false;
	   }
   }
   if (SYSTEM_STS_NoOfStsCodes > 0) {

	SetMenuDetailView(STS_DetailMenu_Number);
   }
   return LocalStatus;
}

static STATUS ShutdownCtrl( U8 ModuleState, U8 *DoneState, U32 Interval )
{
    STATUS LocalStatus = 0;

    LocalStatus = LocalCtrl( Interval );
    STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);

    switch( ModuleState )
    {
        case AS_SHUTDOWN:
        {
            // Activate "Manual Shutdown" status code

            *DoneState = AS_SHUTDOWN;
            break;
        }
        case AS_REBOOT:
        {

		    *DoneState = AS_REBOOT;
            break;
        }
        case AS_SHUTDOWN_FAST:
        {

            *DoneState = AS_SHUTDOWN_FAST;
            break;
        }
        default:
        {
            *DoneState = ModuleState;
            break;
        }
    }
    return LocalStatus;
}
 
//-----------------------------------------------------------------------
// MAIN CALL             MAIN CALL               MAIN CALL
//-----------------------------------------------------------------------

STATUS StatusCodes_Eleon( U8 ModuleState, U8 *DoneState , U32 Interval )
{
   STATUS LocalStatus = 0;

   #ifdef READ_VARS
      // Read input data
      LocalStatus = InputReferenceRoutine(ModuleState);
      STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
   #endif
   #ifdef COMMON_VDB_READ
      LocalStatus = ReadVdbWindow(ModuleState);
      STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
   #endif


   switch( ModuleState )
   {
      //__________________________________________________________________________
      case APP_RUN:
      {
         #ifdef FUNCTION_BLOCKS_PRE_LOCAL_CONTROL
            LocalStatus = FunctionBlocksPreLocalCtrl( Interval );
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif
         
         LocalStatus = LocalCtrl( Interval );
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);

         #ifdef FUNCTION_BLOCKS_POST_LOCAL_CONTROL
            LocalStatus = FunctionBlocksPostLocalCtrl( Interval );
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef WRITE_VARS
            // Write Output data
            LocalStatus = OutputReferenceRoutine(ModuleState);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef COMMON_VDB_WRITE
            LocalStatus = WriteVdbWindow(ModuleState);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         *DoneState = APP_RUN;
         break;
      }
      //__________________________________________________________________________
      case APP_INIT1:
      {
         // Version check
         LocalStatus = OS_ValidateAPI( API_VERSION_MAJOR,
                                API_VERSION_MINOR,
                                OS_LinkTime,
                                ReleaseTag,
                                __MODULE__
                               );
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);

         Init_Structures_From_Conf_File();

         #ifdef CREATE_VARDB_VARS
            LocalStatus = CreateVarDbVars();
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef CREATE_MENU
            LocalStatus = StatusCodes_EleonMenuAppInit(ModuleState, GetMemPool());
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);

            #ifdef MULTIPLEXIBLE_MENU
               LocalStatus = MenuArraysAppInit(ModuleState, GetMemPool());
               STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
            #endif
         #endif

         #ifdef CREATE_VARDB_ARRAY_VARS
               LocalStatus = CreateVdbArrays(GetMemPool());
               STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
         #endif


         #ifdef CREATE_IO_VARS
               LocalStatus = CreateIOVars();
               STATUS_LINE_VAR_RETURN_VALUE(LocalStatus)
         #endif

         *DoneState = APP_INIT1;

         break;
      }
      //__________________________________________________________________________
      case APP_INIT2:
      {
         #ifdef CREATE_MENU
            #ifdef MULTIPLEXIBLE_MENU
               LocalStatus = MenuArraysAppInit(ModuleState, GetMemPool());
               STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
            #endif
         #endif

         #ifdef CREATE_ALIASES
               size_t ErrorEntry = 0;
               LocalStatus = OS_VarDB_CreateAliases(AliasVars, sizeof(AliasVars)/sizeof(AliasVars[0]), &ErrorEntry);
               STATUS_LINE_VAR_RETURN_CONST(LocalStatus, ErrorEntry);
         #endif

         #ifdef VERIFY_ARRAY
               LocalStatus = VerifyArray(GetMemPool());
               STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef VERIFY_VARIABLES
               LocalStatus = LocalIoCheck();
               STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef CREATE_BUTTONS
               LocalStatus = CreateButtons();
               STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         *DoneState = APP_INIT2;

         break;
      }
      //__________________________________________________________________________
      case APP_INIT3 :
      {
         #ifdef CREATE_SUMMATIONS
            LocalStatus = CreateSummations();
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef WRITE_VARS
            LocalStatus = InitOutputVars();
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef CREATE_STATUS_CODES
            LocalStatus = LocalStatusCodeInit();
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef CREATE_IO_VARS
           StatusCodes_EleonSetLockValues();
         #endif

         *DoneState = APP_INIT3;

         break;
      }
      //__________________________________________________________________________
      case APP_INIT4:
      {
         #ifdef CREATE_MENU
            LocalStatus = StatusCodes_EleonMenuAppInit(ModuleState, GetMemPool());
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);

            #ifdef MULTIPLEXIBLE_MENU
               LocalStatus = MenuArraysAppInit(ModuleState, GetMemPool());
               STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
            #endif
         #endif

         *DoneState = APP_INIT4;

         break;
      }
      //__________________________________________________________________________
      case APP_INIT5:
      {
         #ifdef VALIDATE_HASH
            LocalStatus = ValidateHash( StatusCodes_Eleon_copyright, MODULE_NAME, StatusCodes_Eleon_initialValues);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef INIT_FUNCTION_BLOCKS
            LocalStatus = FunctionBlocksInit( Interval );
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif
			//user part
			M_StatusCodesMenuLines[5].VarName = "SYSYEM_STS_specialVariableNo";

			//user part
         *DoneState = APP_INIT5_DONE;

         break;
      }
      //__________________________________________________________________________
      //Other initialization round can be inserted here
      //__________________________________________________________________________
      case AS_SHUTDOWN:
      {
         LocalStatus = ShutdownCtrl ( ModuleState, DoneState, Interval );
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);

         #ifdef WRITE_VARS
            // Write Output data
            LocalStatus = OutputReferenceRoutine(ModuleState);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef COMMON_VDB_WRITE
            LocalStatus = WriteVdbWindow(ModuleState);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         break;
      }
      //__________________________________________________________________________
      case AS_REBOOT:
      {
         LocalStatus = ShutdownCtrl ( ModuleState, DoneState, Interval );
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);

         #ifdef WRITE_VARS
            // Write Output data
            LocalStatus = OutputReferenceRoutine(ModuleState);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef COMMON_VDB_WRITE
            LocalStatus = WriteVdbWindow(ModuleState);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         break;
      }
      //__________________________________________________________________________
      case AS_SHUTDOWN_FAST:
      {
         LocalStatus = ShutdownCtrl ( ModuleState, DoneState, Interval );
         STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);

         #ifdef WRITE_VARS
            // Write Output data
            LocalStatus = OutputReferenceRoutine(ModuleState);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         #ifdef COMMON_VDB_WRITE
            LocalStatus = WriteVdbWindow(ModuleState);
            STATUS_LINE_VAR_RETURN_VALUE(LocalStatus);
         #endif

         break;
      }
      default:
      {
         *DoneState = ModuleState;

         break;
      }
   }
   return OS_SUCCESS;
}
//-----------------------------------------------------------------------
#undef APP_ID